/**
 * DRKOÇ — KELİME KAYITLARI: A1 / Modül 2 — Aile ve çevre
 *
 * Aile kelimeleri kolay görünür ama iki tuzağı vardır:
 *   1. Telaffuz — mother, father, brother kelimelerindeki /ð/ sesi
 *      Türkçede yoktur ve "d" ile söylenince kelime tanınmaz.
 *   2. İyelik — Türkçede "annem" tek kelimedir; İngilizcede "my mother"
 *      iki kelimedir ve iyelik sıfatı asla düşmez.
 * Bu yüzden kayıtlardaki `hata` alanları ağırlıklı olarak bu ikisine
 * bakar.
 */

export const KELIMELER = [
  {
    id: 'k-family',
    dil: 'en',
    kelime: 'family',
    tur: 'isim',
    seviye: 'A1',
    ingilizceTanim: 'a group of people who are related to each other, like parents and children',
    turkceDestek: 'aile',
    ipa: '/ˈfæməli/',
    heceler: 'FAM·i·ly',
    ornekler: [
      { en: 'I have a big family.', tr: 'Büyük bir ailem var.' },
      { en: 'My family lives in Bursa.', tr: 'Ailem Bursa\'da yaşıyor.' },
    ],
    esdizim: ['a big family', 'family member', 'my family and I'],
    esAnlam: [],
    zitAnlam: [],
    aile: ['familiar'],
    hata: 'İlk hecedeki ses /æ/ — Türkçedeki "e" değil. Ağzı biraz daha açarak "FEM-ı-li" değil "FÆM-ı-li" denir.',
    kayit: 'gundelik',
    hatirlatma: 'Üç hece ama ortadaki hece neredeyse yutulur: FAM-li gibi duyulur.',
    uretim: {
      yonerge: '"Büyük bir ailem var." cümlesini İngilizce yaz.',
      kabul: ['I have a big family', 'I have got a big family', "I've got a big family"],
    },
  },
  {
    id: 'k-mother',
    dil: 'en',
    kelime: 'mother',
    tur: 'isim',
    seviye: 'A1',
    ingilizceTanim: 'a woman who has a child',
    turkceDestek: 'anne',
    ipa: '/ˈmʌðər/',
    heceler: 'MO·ther',
    ornekler: [
      { en: 'My mother is a nurse.', tr: 'Annem hemşire.' },
      { en: 'Her mother works in a bank.', tr: 'Onun annesi bir bankada çalışıyor.' },
    ],
    esdizim: ['my mother', 'mother tongue', 'a working mother'],
    esAnlam: ['mum', 'mom'],
    zitAnlam: ['father'],
    aile: ['motherhood', 'grandmother'],
    hata: 'Ortadaki "th" /ð/ sesidir: dil dişlerin arasında ve boğaz titrer. "moder" demek yaygın ama yanlıştır.',
    kayit: 'gundelik',
    ingUsa: { usa: 'mom (gündelik)', ing: 'mum (gündelik)' },
    hatirlatma: 'Türkçede "annem" tek kelimedir; İngilizcede "my mother" — "my" düşmez.',
    uretim: {
      yonerge: '"Annem öğretmen." cümlesini İngilizce yaz.',
      kabul: ['My mother is a teacher', 'My mum is a teacher', 'My mom is a teacher'],
    },
  },
  {
    id: 'k-father',
    dil: 'en',
    kelime: 'father',
    tur: 'isim',
    seviye: 'A1',
    ingilizceTanim: 'a man who has a child',
    turkceDestek: 'baba',
    ipa: '/ˈfɑːðər/',
    heceler: 'FA·ther',
    ornekler: [
      { en: 'My father is a driver.', tr: 'Babam şoför.' },
      { en: 'His father is from Izmir.', tr: 'Onun babası İzmirli.' },
    ],
    esdizim: ['my father', 'a good father'],
    esAnlam: ['dad'],
    zitAnlam: ['mother'],
    aile: ['grandfather'],
    hata: 'İlk ünlü uzundur (/ɑː/) ve "th" yine /ð/ sesidir: FAA-dhır.',
    kayit: 'gundelik',
    hatirlatma: 'mother ile father aynı kalıptadır; birini doğru söylersen diğeri de gelir.',
    uretim: {
      yonerge: '"Babam bir mühendis." cümlesini İngilizce yaz.',
      kabul: ['My father is an engineer', 'My dad is an engineer'],
    },
  },
  {
    id: 'k-sister',
    dil: 'en',
    kelime: 'sister',
    tur: 'isim',
    seviye: 'A1',
    ingilizceTanim: 'a girl or woman who has the same parents as you',
    turkceDestek: 'kız kardeş / abla',
    ipa: '/ˈsɪstər/',
    heceler: 'SIS·ter',
    ornekler: [
      { en: 'I have two sisters.', tr: 'İki kız kardeşim var.' },
      { en: 'My sister is older than me.', tr: 'Ablam benden büyük.' },
    ],
    esdizim: ['big sister', 'little sister', 'twin sister'],
    esAnlam: [],
    zitAnlam: ['brother'],
    aile: [],
    hata: 'İngilizcede "abla" ile "kız kardeş" ayrı kelime değildir; ikisi de sister. Yaş farkı gerekiyorsa "older/younger sister" denir.',
    kayit: 'gundelik',
    hatirlatma: 'Türkçede yaşa göre ayrı kelimeler var (abla/kardeş); İngilizcede tek kelime + sıfat.',
    uretim: {
      yonerge: '"Bir ablam var." cümlesini İngilizce yaz.',
      kabul: ['I have an older sister', 'I have got an older sister', "I've got an older sister", 'I have a big sister'],
    },
  },
  {
    id: 'k-brother',
    dil: 'en',
    kelime: 'brother',
    tur: 'isim',
    seviye: 'A1',
    ingilizceTanim: 'a boy or man who has the same parents as you',
    turkceDestek: 'erkek kardeş / abi',
    ipa: '/ˈbrʌðər/',
    heceler: 'BRO·ther',
    ornekler: [
      { en: 'My brother is ten years old.', tr: 'Kardeşim on yaşında.' },
      { en: 'I go to school with my brother.', tr: 'Okula kardeşimle gidiyorum.' },
    ],
    esdizim: ['little brother', 'older brother'],
    esAnlam: [],
    zitAnlam: ['sister'],
    aile: [],
    hata: 'Baştaki "br-" ünsüz kümesidir; araya ünlü koyma ("bırader" değil, tek hamlede "brʌ").',
    kayit: 'gundelik',
    hatirlatma: 'mother-father-brother üçü de /ð/ ailesindendir.',
    uretim: {
      yonerge: '"İki erkek kardeşim var." cümlesini İngilizce yaz.',
      kabul: ['I have two brothers', 'I have got two brothers', "I've got two brothers"],
    },
  },
  {
    id: 'k-parents',
    dil: 'en',
    kelime: 'parents',
    tur: 'isim',
    seviye: 'A1',
    ingilizceTanim: 'your mother and father',
    turkceDestek: 'anne baba, ebeveynler',
    ipa: '/ˈperənts/',
    heceler: 'PA·rents',
    ornekler: [
      { en: 'My parents are teachers.', tr: 'Annem ve babam öğretmen.' },
      { en: 'I live with my parents.', tr: 'Ailemle yaşıyorum.' },
    ],
    esdizim: ['my parents', 'live with my parents'],
    esAnlam: [],
    zitAnlam: ['children'],
    aile: ['parent'],
    hata: 'Bu kelime her zaman çoğuldur ve çoğul fiil alır: "My parents ARE…" — "is" değil.',
    kayit: 'gundelik',
    hatirlatma: '"Anne babam" iki kişidir; İngilizcede tek kelimeyle "parents" denir.',
    uretim: {
      yonerge: '"Annem ve babam Ankara\'da yaşıyor." cümlesini "parents" kullanarak yaz.',
      kabul: ['My parents live in Ankara'],
    },
  },
  {
    id: 'k-grandmother',
    dil: 'en',
    kelime: 'grandmother',
    tur: 'isim',
    seviye: 'A1',
    ingilizceTanim: 'the mother of your mother or father',
    turkceDestek: 'büyükanne, anneanne, babaanne',
    ipa: '/ˈɡrænmʌðər/',
    heceler: 'GRAND·mo·ther',
    ornekler: [
      { en: 'My grandmother makes very good soup.', tr: 'Babaannem çok güzel çorba yapar.' },
      { en: 'We visit our grandmother every Sunday.', tr: 'Her pazar büyükannemizi ziyaret ederiz.' },
    ],
    esdizim: ['my grandmother', 'visit my grandmother'],
    esAnlam: ['grandma'],
    zitAnlam: ['grandfather'],
    aile: ['grandfather', 'grandparents', 'grandchild'],
    hata: 'Türkçede anneanne ve babaanne ayrı kelimelerdir; İngilizcede ikisi de grandmother. Gerekirse "my mother\'s mother" denir.',
    kayit: 'gundelik',
    hatirlatma: 'grand- öneki bir kuşak yukarı ya da aşağı demektir.',
    uretim: {
      yonerge: '"Büyükannem seksen yaşında." cümlesini İngilizce yaz.',
      kabul: ['My grandmother is eighty years old', 'My grandmother is eighty', 'My grandma is eighty years old'],
    },
  },
  {
    id: 'k-have-got',
    dil: 'en',
    kelime: 'have got',
    tur: 'fiil',
    seviye: 'A1',
    ingilizceTanim: 'used to say that something belongs to you or is part of your life',
    turkceDestek: 'sahip olmak (-m var)',
    ipa: '/hæv ˈɡɒt/',
    heceler: 'have GOT',
    ornekler: [
      { en: 'I have got two brothers.', tr: 'İki erkek kardeşim var.' },
      { en: 'She has got long hair.', tr: 'Onun uzun saçı var.' },
    ],
    esdizim: ["I've got", "he's got", 'have got a car'],
    esAnlam: ['have'],
    zitAnlam: [],
    aile: ['have', 'has'],
    hata: 'Üçüncü tekilde "has got" olur: "She have got" yanlıştır. Ayrıca "I have got a sister" ile "I have a sister" aynı anlamdadır.',
    kayit: 'gundelik',
    ingUsa: { usa: '"I have a sister" daha yaygın', ing: '"I\'ve got a sister" daha yaygın' },
    hatirlatma: 'Türkçede "var" ayrı bir kelimedir ve özne almaz ("kardeşim var"). İngilizcede özne + have/has got sırası zorunludur.',
    uretim: {
      yonerge: '"Bir kedim var." cümlesini "have got" ile yaz.',
      kabul: ['I have got a cat', "I've got a cat", 'I have a cat'],
    },
  },
  {
    id: 'k-tall',
    dil: 'en',
    kelime: 'tall',
    tur: 'sıfat',
    seviye: 'A1',
    ingilizceTanim: 'having more than average height',
    turkceDestek: 'uzun boylu',
    ipa: '/tɔːl/',
    heceler: 'tall (tek hece)',
    ornekler: [
      { en: 'My brother is very tall.', tr: 'Kardeşim çok uzun boylu.' },
      { en: 'She is taller than me.', tr: 'O benden daha uzun.' },
    ],
    esdizim: ['very tall', 'tall building', 'six feet tall'],
    esAnlam: [],
    zitAnlam: ['short'],
    aile: ['taller', 'tallest'],
    hata: 'İnsan boyu için "tall", nesne uzunluğu için "long" kullanılır: "long hair" ama "tall person".',
    kayit: 'gundelik',
    hatirlatma: 'Türkçede "uzun" hem boy hem uzunluk için kullanılır; İngilizcede ikiye ayrılır.',
    uretim: {
      yonerge: '"Kardeşim uzun boylu." cümlesini İngilizce yaz.',
      kabul: ['My brother is tall', 'My sister is tall'],
    },
  },
  {
    id: 'k-short',
    dil: 'en',
    kelime: 'short',
    tur: 'sıfat',
    seviye: 'A1',
    ingilizceTanim: 'not tall, or not long',
    turkceDestek: 'kısa (boylu)',
    ipa: '/ʃɔːrt/',
    heceler: 'short (tek hece)',
    ornekler: [
      { en: 'My grandmother is short.', tr: 'Büyükannem kısa boylu.' },
      { en: 'She has short hair.', tr: 'Onun kısa saçı var.' },
    ],
    esdizim: ['short hair', 'a short film', 'in short'],
    esAnlam: [],
    zitAnlam: ['tall', 'long'],
    aile: ['shorter', 'shortly'],
    hata: '"short" hem boy hem uzunluk için kullanılabilir; ama karşıtı değişir: short↔tall (boy), short↔long (uzunluk).',
    kayit: 'gundelik',
    hatirlatma: 'Baştaki "sh" sesi Türkçedeki "ş" ile aynıdır — bu kolay olanı.',
    uretim: {
      yonerge: '"Onun kısa saçı var." cümlesini İngilizce yaz.',
      kabul: ['She has short hair', 'He has short hair', 'She has got short hair', 'He has got short hair'],
    },
  },
  {
    id: 'k-hair',
    dil: 'en',
    kelime: 'hair',
    tur: 'isim',
    seviye: 'A1',
    ingilizceTanim: 'the thing that grows on your head',
    turkceDestek: 'saç',
    ipa: '/her/',
    heceler: 'hair (tek hece)',
    ornekler: [
      { en: 'She has long brown hair.', tr: 'Onun uzun kahverengi saçı var.' },
      { en: 'My hair is very short now.', tr: 'Saçım şu an çok kısa.' },
    ],
    esdizim: ['long hair', 'short hair', 'curly hair', 'brown hair'],
    esAnlam: [],
    zitAnlam: [],
    aile: ['hairy'],
    hata: 'Saç İngilizcede SAYILAMAZ isimdir: "hairs" denmez. "She has long hair" doğru, "long hairs" yanlıştır.',
    kayit: 'gundelik',
    hatirlatma: 'Sıfat sırası: uzunluk → renk. "long brown hair" doğru, "brown long hair" kulağa yanlış gelir.',
    uretim: {
      yonerge: '"Uzun siyah saçım var." cümlesini İngilizce yaz.',
      kabul: ['I have long black hair', 'I have got long black hair', "I've got long black hair"],
    },
  },
  {
    id: 'k-kind',
    dil: 'en',
    kelime: 'kind',
    tur: 'sıfat',
    seviye: 'A1',
    ingilizceTanim: 'friendly and caring about other people',
    turkceDestek: 'nazik, iyi kalpli',
    ipa: '/kaɪnd/',
    heceler: 'kind (tek hece)',
    ornekler: [
      { en: 'My teacher is very kind.', tr: 'Öğretmenim çok nazik.' },
      { en: 'She is kind to everybody.', tr: 'Herkese karşı iyi kalpli.' },
    ],
    esdizim: ['kind to somebody', 'very kind', 'that is very kind of you'],
    esAnlam: ['nice', 'friendly'],
    zitAnlam: ['unkind', 'rude'],
    aile: ['kindly', 'kindness'],
    hata: '"kind" ayrıca "tür, çeşit" anlamına da gelir: "What kind of music?" — bağlama bak.',
    kayit: 'gundelik',
    hatirlatma: '"i" burada "ay" okunur: KAYND.',
    uretim: {
      yonerge: '"Öğretmenim çok nazik." cümlesini İngilizce yaz.',
      kabul: ['My teacher is very kind', 'My teacher is very nice'],
    },
  },
  {
    id: 'k-funny',
    dil: 'en',
    kelime: 'funny',
    tur: 'sıfat',
    seviye: 'A1',
    ingilizceTanim: 'making you laugh',
    turkceDestek: 'komik, eğlenceli',
    ipa: '/ˈfʌni/',
    heceler: 'FUN·ny',
    ornekler: [
      { en: 'My little brother is very funny.', tr: 'Küçük kardeşim çok komik.' },
      { en: 'That film was really funny.', tr: 'O film gerçekten komikti.' },
    ],
    esdizim: ['really funny', 'a funny story'],
    esAnlam: ['amusing'],
    zitAnlam: ['serious', 'boring'],
    aile: ['fun'],
    hata: '"funny" ile "fun" karıştırılır: funny = güldüren, fun = eğlenceli/keyifli. "The party was fun" doğru; "The party was funny" partinin komik olduğunu söyler.',
    kayit: 'gundelik',
    hatirlatma: '"u" burada "a" gibi okunur: FA-ni.',
    uretim: {
      yonerge: '"Kardeşim çok komik." cümlesini İngilizce yaz.',
      kabul: ['My brother is very funny', 'My sister is very funny'],
    },
  },
  {
    id: 'k-quiet',
    dil: 'en',
    kelime: 'quiet',
    tur: 'sıfat',
    seviye: 'A1',
    ingilizceTanim: 'not making much noise; not talking a lot',
    turkceDestek: 'sessiz, sakin',
    ipa: '/ˈkwaɪət/',
    heceler: 'QUI·et',
    ornekler: [
      { en: 'My sister is very quiet.', tr: 'Kız kardeşim çok sessiz.' },
      { en: 'Our street is quiet at night.', tr: 'Sokağımız geceleri sessizdir.' },
    ],
    esdizim: ['a quiet person', 'be quiet', 'a quiet street'],
    esAnlam: ['calm'],
    zitAnlam: ['loud', 'noisy'],
    aile: ['quietly'],
    hata: '"quiet" (sessiz) ile "quite" (oldukça) yazımı çok benzer ama farklı kelimelerdir. Yazarken harf sırasına dikkat et.',
    kayit: 'gundelik',
    hatirlatma: '"qu" her zaman /kw/ okunur: KWAY-ıt.',
    uretim: {
      yonerge: '"Kız kardeşim çok sessiz." cümlesini İngilizce yaz.',
      kabul: ['My sister is very quiet'],
    },
  },
]
