/**
 * DRKOÇ — KELİME KAYITLARI: A1 / Modül 4 — Okul ve dersler
 *
 * Bu modülün kelimeleri okulda her gün karşılaşılan şeylerdir, ama
 * içlerinde iki tehlikeli "yanlış dost" var: `subject` (ders) ile
 * Türkçedeki "sübjektif" çağrışımı, ve `lesson` ile `course` ayrımı.
 * Ayrıca `favourite` kelimesinin İngiliz/Amerikan yazımı farklıdır ve
 * öğrenciler ikisini karıştırıp tutarsız yazar.
 */

export const KELIMELER = [
  {
    id: 'k-subject',
    dil: 'en',
    kelime: 'subject',
    tur: 'isim',
    seviye: 'A1',
    ingilizceTanim: 'an area of knowledge that you study at school, like maths or history',
    turkceDestek: 'ders (okul dersi)',
    ipa: '/ˈsʌbdʒɪkt/',
    heceler: 'SUB·ject',
    ornekler: [
      { en: 'My favourite subject is English.', tr: 'En sevdiğim ders İngilizce.' },
      { en: 'We have got six subjects this year.', tr: 'Bu yıl altı dersimiz var.' },
    ],
    esdizim: ['favourite subject', 'a difficult subject', 'school subjects'],
    esAnlam: [],
    zitAnlam: [],
    aile: [],
    hata: '"subject" bir DERS ALANIDIR (matematik, tarih). Bir saatlik ders için "lesson" kullanılır: "We have four lessons today."',
    kayit: 'gundelik',
    hatirlatma: 'Türkçede "ders" hem alanı hem saati anlatır; İngilizcede subject (alan) ve lesson (saat) ayrılır.',
    uretim: {
      yonerge: '"En sevdiğim ders matematik." cümlesini İngilizce yaz.',
      kabul: ['My favourite subject is maths', 'My favorite subject is math', 'My favourite subject is mathematics', 'My favorite subject is maths'],
    },
  },
  {
    id: 'k-favourite',
    dil: 'en',
    kelime: 'favourite',
    tur: 'sıfat',
    seviye: 'A1',
    ingilizceTanim: 'the one that you like more than all the others',
    turkceDestek: 'en sevdiğin, favori',
    ipa: '/ˈfeɪvərɪt/',
    heceler: 'FA·vou·rite',
    ornekler: [
      { en: 'My favourite colour is blue.', tr: 'En sevdiğim renk mavi.' },
      { en: 'Who is your favourite singer?', tr: 'En sevdiğin şarkıcı kim?' },
    ],
    esdizim: ['my favourite subject', 'favourite food', 'favourite team'],
    esAnlam: [],
    zitAnlam: [],
    aile: [],
    hata: 'Kelimenin içinde "en" anlamı zaten vardır: "my most favourite" denmez.',
    kayit: 'gundelik',
    ingUsa: { usa: 'favorite (u yok)', ing: 'favourite (u var)' },
    hatirlatma: 'Hangi yazımı seçersen seç, metnin tamamında aynısını kullan.',
    uretim: {
      yonerge: '"En sevdiğim renk yeşil." cümlesini yaz.',
      kabul: ['My favourite colour is green', 'My favorite color is green', 'My favourite color is green'],
    },
  },
  {
    id: 'k-maths',
    dil: 'en',
    kelime: 'maths',
    tur: 'isim',
    seviye: 'A1',
    ingilizceTanim: 'the subject about numbers and shapes',
    turkceDestek: 'matematik',
    ipa: '/mæθs/',
    heceler: 'maths (tek hece)',
    ornekler: [
      { en: 'I have got maths on Monday.', tr: 'Pazartesi matematiğim var.' },
      { en: 'Maths is difficult for me.', tr: 'Matematik benim için zor.' },
    ],
    esdizim: ['maths lesson', 'good at maths'],
    esAnlam: ['mathematics'],
    zitAnlam: [],
    aile: ['mathematics'],
    hata: 'Sonda hem /θ/ hem /s/ var: mæθs. Türkçe alışkanlığıyla "mets" ya da "mat" demek kelimeyi tanınmaz kılar.',
    kayit: 'gundelik',
    ingUsa: { usa: 'math (s yok)', ing: 'maths (s var)' },
    hatirlatma: 'Bir derste iyi olmak "good AT" ile söylenir: "I am good at maths."',
    uretim: {
      yonerge: '"Matematikte iyiyim." cümlesini yaz.',
      kabul: ['I am good at maths', "I'm good at maths", 'I am good at math', "I'm good at math"],
    },
  },
  {
    id: 'k-difficult',
    dil: 'en',
    kelime: 'difficult',
    tur: 'sıfat',
    seviye: 'A1',
    ingilizceTanim: 'not easy; needing a lot of effort',
    turkceDestek: 'zor',
    ipa: '/ˈdɪfɪkəlt/',
    heceler: 'DIF·fi·cult',
    ornekler: [
      { en: 'This question is very difficult.', tr: 'Bu soru çok zor.' },
      { en: 'English is not difficult for me.', tr: 'İngilizce benim için zor değil.' },
    ],
    esdizim: ['a difficult question', 'difficult for me'],
    esAnlam: ['hard'],
    zitAnlam: ['easy'],
    aile: ['difficulty'],
    hata: '"hard" da zor demektir ama "sert" anlamı da taşır. Ders için ikisi de kullanılabilir: "a hard question" / "a difficult question".',
    kayit: 'gundelik',
    hatirlatma: 'Vurgu ilk hecede: DİF-fi-kılt. Üç hecelik kelimelerde Türkçe alışkanlığıyla sonu vurgulama.',
    uretim: {
      yonerge: '"Bu soru çok zor." cümlesini yaz.',
      kabul: ['This question is very difficult', 'This question is very hard'],
    },
  },
  {
    id: 'k-easy',
    dil: 'en',
    kelime: 'easy',
    tur: 'sıfat',
    seviye: 'A1',
    ingilizceTanim: 'not difficult; needing little effort',
    turkceDestek: 'kolay',
    ipa: '/ˈiːzi/',
    heceler: 'EA·sy',
    ornekler: [
      { en: 'The test was easy.', tr: 'Sınav kolaydı.' },
      { en: 'It is easy for me.', tr: 'Benim için kolay.' },
    ],
    esdizim: ['an easy question', 'easy for me', 'take it easy'],
    esAnlam: ['simple'],
    zitAnlam: ['difficult', 'hard'],
    aile: ['easily'],
    hata: 'Zarf biçimi "easily"dir: "I can do it easily." — "easy" burada kullanılmaz.',
    kayit: 'gundelik',
    hatirlatma: 'Baştaki "ea" uzun /iː/: İİ-zi.',
    uretim: {
      yonerge: '"Bu ders benim için kolay." cümlesini yaz.',
      kabul: ['This lesson is easy for me', 'This subject is easy for me'],
    },
  },
  {
    id: 'k-interesting',
    dil: 'en',
    kelime: 'interesting',
    tur: 'sıfat',
    seviye: 'A1',
    ingilizceTanim: 'making you want to know more about it',
    turkceDestek: 'ilginç, ilgi çekici',
    ipa: '/ˈɪntrəstɪŋ/',
    heceler: 'IN·te·res·ting',
    ornekler: [
      { en: 'History is very interesting.', tr: 'Tarih çok ilgi çekici.' },
      { en: 'That is an interesting question.', tr: 'Bu ilginç bir soru.' },
    ],
    esdizim: ['an interesting book', 'really interesting'],
    esAnlam: [],
    zitAnlam: ['boring'],
    aile: ['interest', 'interested'],
    hata: '"interesting" ŞEYİ anlatır (ders ilgi çekici), "interested" KİŞİYİ anlatır (ben ilgiliyim). "I am interesting" demek "ben ilginç biriyim" olur.',
    kayit: 'gundelik',
    hatirlatma: 'Konuşmada ortadaki hece yutulur: İN-trıs-ting (dört değil üç hece gibi duyulur).',
    uretim: {
      yonerge: '"Tarih ilgi çekici bir ders." cümlesini yaz.',
      kabul: ['History is an interesting subject', 'History is interesting'],
    },
  },
  {
    id: 'k-boring',
    dil: 'en',
    kelime: 'boring',
    tur: 'sıfat',
    seviye: 'A1',
    ingilizceTanim: 'not interesting; making you tired or unhappy',
    turkceDestek: 'sıkıcı',
    ipa: '/ˈbɔːrɪŋ/',
    heceler: 'BOR·ing',
    ornekler: [
      { en: 'The film was really boring.', tr: 'Film gerçekten sıkıcıydı.' },
      { en: 'I do not think it is boring.', tr: 'Sıkıcı olduğunu düşünmüyorum.' },
    ],
    esdizim: ['really boring', 'a boring lesson'],
    esAnlam: ['dull'],
    zitAnlam: ['interesting', 'exciting'],
    aile: ['bored', 'bore'],
    hata: '"boring" ŞEY sıkıcıdır, "bored" KİŞİ sıkılmıştır. "I am boring" demek "ben sıkıcı biriyim" olur — sık yapılan ve utandırıcı bir hata.',
    kayit: 'gundelik',
    hatirlatma: '-ing → sebep (film sıkıcı), -ed → his (ben sıkıldım). Bu kural bütün duygu sıfatlarında geçerlidir.',
    uretim: {
      yonerge: '"Sıkıldım." cümlesini yaz.',
      kabul: ['I am bored', "I'm bored"],
    },
  },
  {
    id: 'k-can',
    dil: 'en',
    kelime: 'can',
    tur: 'yardımcı fiil',
    seviye: 'A1',
    ingilizceTanim: 'to be able to do something',
    turkceDestek: '-ebilmek',
    ipa: '/kæn/',
    heceler: 'can (tek hece)',
    ornekler: [
      { en: 'I can swim but I cannot drive.', tr: 'Yüzebilirim ama araba kullanamam.' },
      { en: 'Can you speak English?', tr: 'İngilizce konuşabiliyor musun?' },
    ],
    esdizim: ['can swim', "can't do it", 'Can you help me?'],
    esAnlam: ['be able to'],
    zitAnlam: ["can't"],
    aile: ['cannot', "can't"],
    hata: '"can" sonrası fiil YALIN kalır: "I can swim" ✓, "I can to swim" ✗, "I can swimming" ✗.',
    kayit: 'gundelik',
    hatirlatma: 'Türkçede "-ebilmek" fiile yapışır; İngilizcede ayrı bir kelimedir ve kendisi çekimlenmez: "He can" ✓, "He cans" ✗.',
    uretim: {
      yonerge: '"Yüzebilirim." cümlesini yaz.',
      kabul: ['I can swim'],
    },
  },
  {
    id: 'k-classroom',
    dil: 'en',
    kelime: 'classroom',
    tur: 'isim',
    seviye: 'A1',
    ingilizceTanim: 'the room where students have lessons',
    turkceDestek: 'sınıf (oda)',
    ipa: '/ˈklɑːsruːm/',
    heceler: 'CLASS·room',
    ornekler: [
      { en: 'Our classroom is on the first floor.', tr: 'Sınıfımız birinci katta.' },
      { en: 'There are thirty desks in the classroom.', tr: 'Sınıfta otuz sıra var.' },
    ],
    esdizim: ['in the classroom', 'a big classroom'],
    esAnlam: [],
    zitAnlam: [],
    aile: ['class', 'classmate'],
    hata: '"class" öğrenci grubu ya da ders demektir; ODA için "classroom" kullanılır.',
    kayit: 'gundelik',
    hatirlatma: 'Baştaki "cl-" ünsüz kümesidir; araya ünlü koyma.',
    uretim: {
      yonerge: '"Sınıfımız çok büyük." cümlesini yaz.',
      kabul: ['Our classroom is very big'],
    },
  },
  {
    id: 'k-notebook',
    dil: 'en',
    kelime: 'notebook',
    tur: 'isim',
    seviye: 'A1',
    ingilizceTanim: 'a book with empty pages for writing notes',
    turkceDestek: 'defter',
    ipa: '/ˈnoʊtbʊk/',
    heceler: 'NOTE·book',
    ornekler: [
      { en: 'I write new words in my notebook.', tr: 'Yeni kelimeleri defterime yazarım.' },
      { en: 'Where is my notebook?', tr: 'Defterim nerede?' },
    ],
    esdizim: ['in my notebook', 'a new notebook'],
    esAnlam: [],
    zitAnlam: [],
    aile: ['note', 'book'],
    hata: 'Türkçede "not defteri" iki kelimedir; İngilizcede tek kelime yazılır: notebook.',
    kayit: 'gundelik',
    hatirlatma: '"notebook" ayrıca dizüstü bilgisayar anlamına da gelebilir; bağlam ayırır.',
    uretim: {
      yonerge: '"Defterim çantamda." cümlesini yaz.',
      kabul: ['My notebook is in my bag'],
    },
  },
  {
    id: 'k-teacher-say',
    dil: 'en',
    kelime: 'homework diary',
    tur: 'isim',
    seviye: 'A1',
    ingilizceTanim: 'a small book where you write the homework your teacher gives you',
    turkceDestek: 'ödev defteri, ajanda',
    ipa: '/ˈhoʊmwɜːrk ˌdaɪəri/',
    heceler: 'HOME·work DI·a·ry',
    ornekler: [
      { en: 'Write it in your homework diary.', tr: 'Ödev defterine yaz.' },
      { en: 'I forgot my homework diary at home.', tr: 'Ödev defterimi evde unuttum.' },
    ],
    esdizim: ['in your homework diary'],
    esAnlam: ['planner'],
    zitAnlam: [],
    aile: ['diary', 'homework'],
    hata: '"diary" günlük demektir; "ödev defteri" için başına homework gelir.',
    kayit: 'gundelik',
    hatirlatma: 'Sınıf içi yönergelerde çok geçer: "Open your homework diary."',
    uretim: {
      yonerge: '"Ödev defterimi unuttum." cümlesini yaz.',
      kabul: ['I forgot my homework diary', 'I have forgotten my homework diary'],
    },
  },
  {
    id: 'k-break',
    dil: 'en',
    kelime: 'break',
    tur: 'isim',
    seviye: 'A1',
    ingilizceTanim: 'a short time between lessons when you can rest',
    turkceDestek: 'teneffüs, mola',
    ipa: '/breɪk/',
    heceler: 'break (tek hece)',
    ornekler: [
      { en: 'We have a break at eleven.', tr: 'On birde teneffüsümüz var.' },
      { en: 'I eat a sandwich at break.', tr: 'Teneffüste sandviç yerim.' },
    ],
    esdizim: ['have a break', 'at break', 'lunch break'],
    esAnlam: ['recess'],
    zitAnlam: ['lesson'],
    aile: ['breakfast'],
    hata: '"break" aynı zamanda "kırmak" fiilidir. Ayrıca "ea" burada "ey" okunur: BREYK.',
    kayit: 'gundelik',
    hatirlatma: 'Mola VERMEK "have a break" ile söylenir; "do a break" ya da "make a break" yanlıştır.',
    uretim: {
      yonerge: '"On birde teneffüsümüz var." cümlesini yaz.',
      kabul: ['We have a break at eleven', 'We have a break at 11'],
    },
  },
  {
    id: 'k-good-at',
    dil: 'en',
    kelime: 'be good at',
    tur: 'kalıp',
    seviye: 'A1',
    ingilizceTanim: 'to do something well',
    turkceDestek: '-de iyi olmak',
    ipa: '/biː ˈɡʊd ət/',
    heceler: 'be GOOD at',
    ornekler: [
      { en: 'I am good at English.', tr: 'İngilizcede iyiyim.' },
      { en: 'She is not very good at drawing.', tr: 'Resim çizmekte pek iyi değil.' },
    ],
    esdizim: ['good at maths', 'good at drawing', 'bad at'],
    esAnlam: [],
    zitAnlam: ['be bad at'],
    aile: ['good', 'better', 'best'],
    hata: 'Edat "at"tır: "good at maths" ✓, "good in maths" ✗. Türkçedeki "-de/-da" doğrudan "in"e çevrilince hata çıkar.',
    kayit: 'gundelik',
    hatirlatma: '"at" sonrası fiil gelecekse -ing alır: good at drawing, good at swimming.',
    uretim: {
      yonerge: '"Resim çizmekte iyiyim." cümlesini yaz.',
      kabul: ['I am good at drawing', "I'm good at drawing"],
    },
  },
]
