/**
 * DRKOÇ — KELİME KAYITLARI: A1 / Modül 3 — Günlük rutin
 *
 * Bu modülün kelimelerinin çoğu TEK KELİME DEĞİL, kalıptır: get up,
 * have breakfast, go to bed. Türkçede bunlar tek fiille karşılanır
 * (kalkmak, kahvaltı yapmak, yatmak) ve öğrenci fiili tek tek çevirmeye
 * çalışınca "make breakfast", "sleep to bed" gibi cümleler çıkar.
 * Bu yüzden kayıtlar kalıbın tamamını taşır.
 */

export const KELIMELER = [
  {
    id: 'k-get-up',
    dil: 'en',
    kelime: 'get up',
    tur: 'fiil (kalıp)',
    seviye: 'A1',
    ingilizceTanim: 'to leave your bed after sleeping',
    turkceDestek: 'kalkmak (yataktan)',
    ipa: '/ˌɡet ˈʌp/',
    heceler: 'get UP',
    ornekler: [
      { en: 'I get up at seven o\'clock.', tr: 'Saat yedide kalkarım.' },
      { en: 'She gets up early every day.', tr: 'Her gün erken kalkar.' },
    ],
    esdizim: ['get up early', 'get up late', 'What time do you get up?'],
    esAnlam: ['wake up'],
    zitAnlam: ['go to bed'],
    aile: [],
    hata: '"wake up" uyanmak, "get up" yataktan kalkmaktır. Türkçede ikisi de "kalkmak" olabildiği için karışır.',
    kayit: 'gundelik',
    hatirlatma: 'İki kelimelik fiillerde vurgu genelde ikinci kelimededir: get UP.',
    uretim: {
      yonerge: '"Saat yedide kalkarım." cümlesini İngilizce yaz.',
      kabul: ['I get up at seven', "I get up at seven o'clock", 'I get up at 7', "I get up at 7 o'clock"],
    },
  },
  {
    id: 'k-have-breakfast',
    dil: 'en',
    kelime: 'have breakfast',
    tur: 'fiil (kalıp)',
    seviye: 'A1',
    ingilizceTanim: 'to eat the first meal of the day',
    turkceDestek: 'kahvaltı yapmak',
    ipa: '/hæv ˈbrekfəst/',
    heceler: 'have BREAK·fast',
    ornekler: [
      { en: 'I have breakfast at half past seven.', tr: 'Yedi buçukta kahvaltı yaparım.' },
      { en: 'We do not have breakfast on Sundays.', tr: 'Pazar günleri kahvaltı yapmayız.' },
    ],
    esdizim: ['have lunch', 'have dinner', 'a big breakfast'],
    esAnlam: ['eat breakfast'],
    zitAnlam: [],
    aile: ['breakfast', 'lunch', 'dinner'],
    hata: 'Türkçedeki "kahvaltı YAPMAK" doğrudan "make breakfast"e çevrilir; oysa o "kahvaltı hazırlamak" demektir. Yemek yemek için "have" kullanılır.',
    kayit: 'gundelik',
    hatirlatma: 'breakfast = break + fast (orucu bozmak). "brek-fıst" okunur, "breyk-fast" değil.',
    uretim: {
      yonerge: '"Sekizde kahvaltı yaparım." cümlesini İngilizce yaz.',
      kabul: ['I have breakfast at eight', "I have breakfast at eight o'clock", 'I have breakfast at 8'],
    },
  },
  {
    id: 'k-go-to-bed',
    dil: 'en',
    kelime: 'go to bed',
    tur: 'fiil (kalıp)',
    seviye: 'A1',
    ingilizceTanim: 'to get into bed in order to sleep',
    turkceDestek: 'yatmak',
    ipa: '/ɡoʊ tə ˈbed/',
    heceler: 'go to BED',
    ornekler: [
      { en: 'I go to bed at eleven.', tr: 'Saat on birde yatarım.' },
      { en: 'My little brother goes to bed early.', tr: 'Küçük kardeşim erken yatar.' },
    ],
    esdizim: ['go to bed early', 'go to bed late'],
    esAnlam: [],
    zitAnlam: ['get up'],
    aile: ['bed', 'bedroom'],
    hata: 'Bu kalıpta "the" YOKTUR: "go to bed" ✓, "go to the bed" ✗. Aynı kural: go to school, go to work.',
    kayit: 'gundelik',
    hatirlatma: 'Bir yere AMACI için gidiliyorsa "the" düşer: go to bed (uyumak için), go to school (okumak için).',
    uretim: {
      yonerge: '"Saat onda yatarım." cümlesini İngilizce yaz.',
      kabul: ['I go to bed at ten', "I go to bed at ten o'clock", 'I go to bed at 10'],
    },
  },
  {
    id: 'k-homework',
    dil: 'en',
    kelime: 'homework',
    tur: 'isim',
    seviye: 'A1',
    ingilizceTanim: 'work that a teacher gives you to do at home',
    turkceDestek: 'ödev',
    ipa: '/ˈhoʊmwɜːrk/',
    heceler: 'HOME·work',
    ornekler: [
      { en: 'I do my homework after dinner.', tr: 'Ödevimi akşam yemeğinden sonra yaparım.' },
      { en: 'We have got a lot of homework today.', tr: 'Bugün çok ödevimiz var.' },
    ],
    esdizim: ['do homework', 'a lot of homework', 'finish my homework'],
    esAnlam: [],
    zitAnlam: [],
    aile: ['housework'],
    hata: 'İki hata birden: (1) ödev "do" ile yapılır, "make" ile değil. (2) SAYILAMAZ isimdir: "homeworks" ya da "a homework" denmez.',
    kayit: 'gundelik',
    hatirlatma: 'Türkçede "ödevler" doğal; İngilizcede çoğul yapılmaz. Sayı gerekiyorsa "two pieces of homework" denir.',
    uretim: {
      yonerge: '"Her akşam ödevimi yaparım." cümlesini İngilizce yaz.',
      kabul: ['I do my homework every evening', 'I do my homework every night'],
    },
  },
  {
    id: 'k-always',
    dil: 'en',
    kelime: 'always',
    tur: 'zarf (sıklık)',
    seviye: 'A1',
    ingilizceTanim: 'every time; at all times',
    turkceDestek: 'her zaman, daima',
    ipa: '/ˈɔːlweɪz/',
    heceler: 'AL·ways',
    ornekler: [
      { en: 'I always walk to school.', tr: 'Okula her zaman yürürüm.' },
      { en: 'She is always late.', tr: 'O her zaman geç kalır.' },
    ],
    esdizim: ['always late', 'almost always'],
    esAnlam: [],
    zitAnlam: ['never'],
    aile: [],
    hata: 'Yeri sabittir: ana fiilden ÖNCE ("I always walk"), ama be fiilinden SONRA ("She is always late").',
    kayit: 'gundelik',
    hatirlatma: 'Türkçede "her zaman" cümlenin başında da sonunda da durabilir; İngilizcede yeri kuralla belirlenir.',
    uretim: {
      yonerge: '"Okula her zaman otobüsle giderim." cümlesini yaz.',
      kabul: ['I always go to school by bus', 'I always take the bus to school'],
    },
  },
  {
    id: 'k-usually',
    dil: 'en',
    kelime: 'usually',
    tur: 'zarf (sıklık)',
    seviye: 'A1',
    ingilizceTanim: 'most of the time, but not every time',
    turkceDestek: 'genellikle',
    ipa: '/ˈjuːʒuəli/',
    heceler: 'U·su·al·ly',
    ornekler: [
      { en: 'I usually get up at seven.', tr: 'Genellikle yedide kalkarım.' },
      { en: 'We usually have dinner at eight.', tr: 'Genellikle sekizde akşam yemeği yeriz.' },
    ],
    esdizim: ['usually go', 'usually have'],
    esAnlam: ['normally', 'generally'],
    zitAnlam: [],
    aile: ['usual', 'unusual'],
    hata: 'Baştaki "u" bir ünsüz gibi başlar: /juː/. "u-su-al-ly" değil, "YUU-ju-ı-li" diye okunur.',
    kayit: 'gundelik',
    hatirlatma: 'always > usually > often > sometimes > never sıralamasını bir çizgi gibi düşün.',
    uretim: {
      yonerge: '"Genellikle yedide kalkarım." cümlesini yaz.',
      kabul: ['I usually get up at seven', 'I usually get up at 7', "I usually get up at seven o'clock"],
    },
  },
  {
    id: 'k-sometimes',
    dil: 'en',
    kelime: 'sometimes',
    tur: 'zarf (sıklık)',
    seviye: 'A1',
    ingilizceTanim: 'on some occasions but not often',
    turkceDestek: 'bazen',
    ipa: '/ˈsʌmtaɪmz/',
    heceler: 'SOME·times',
    ornekler: [
      { en: 'I sometimes watch TV in the evening.', tr: 'Akşamları bazen televizyon izlerim.' },
      { en: 'Sometimes we go to the cinema.', tr: 'Bazen sinemaya gideriz.' },
    ],
    esdizim: ['sometimes go', 'sometimes very late'],
    esAnlam: ['occasionally'],
    zitAnlam: ['always', 'never'],
    aile: ['some', 'time'],
    hata: '"sometimes" (bazen) ile "some times" (birkaç kez) ve "sometime" (ileride bir gün) farklı şeylerdir.',
    kayit: 'gundelik',
    hatirlatma: 'Diğer sıklık zarflarından farklı olarak cümlenin başında da durabilir.',
    uretim: {
      yonerge: '"Bazen kitap okurum." cümlesini yaz.',
      kabul: ['I sometimes read books', 'Sometimes I read books', 'I sometimes read a book', 'Sometimes I read a book'],
    },
  },
  {
    id: 'k-never',
    dil: 'en',
    kelime: 'never',
    tur: 'zarf (sıklık)',
    seviye: 'A1',
    ingilizceTanim: 'not at any time',
    turkceDestek: 'asla, hiç',
    ipa: '/ˈnevər/',
    heceler: 'NE·ver',
    ornekler: [
      { en: 'I never drink coffee.', tr: 'Hiç kahve içmem.' },
      { en: 'He is never late.', tr: 'O asla geç kalmaz.' },
    ],
    esdizim: ['never mind', 'almost never'],
    esAnlam: [],
    zitAnlam: ['always'],
    aile: [],
    hata: '"never" kendisi olumsuzdur; cümlede ikinci bir olumsuzluk olmaz. "I don\'t never drink coffee" yanlıştır.',
    kayit: 'gundelik',
    hatirlatma: 'Türkçede "hiç kahve İÇMEM" — olumsuzluk fiilde. İngilizcede olumsuzluk "never"da olduğu için fiil OLUMLU kalır.',
    uretim: {
      yonerge: '"Hiç çay içmem." cümlesini yaz.',
      kabul: ['I never drink tea'],
    },
  },
  {
    id: 'k-early',
    dil: 'en',
    kelime: 'early',
    tur: 'zarf / sıfat',
    seviye: 'A1',
    ingilizceTanim: 'before the usual or expected time',
    turkceDestek: 'erken',
    ipa: '/ˈɜːrli/',
    heceler: 'EAR·ly',
    ornekler: [
      { en: 'I get up early on school days.', tr: 'Okul günleri erken kalkarım.' },
      { en: 'The bus was early today.', tr: 'Otobüs bugün erken geldi.' },
    ],
    esdizim: ['early in the morning', 'get up early', 'an early start'],
    esAnlam: [],
    zitAnlam: ['late'],
    aile: ['earlier', 'earliest'],
    hata: '"early" zarf olduğunda -ly eki ALMAZ; zaten bu biçimdedir. "earlyly" diye bir kelime yoktur.',
    kayit: 'gundelik',
    hatirlatma: '"ear" burada "kulak" gibi okunmaz: ÖR-li.',
    uretim: {
      yonerge: '"Erken kalkarım." cümlesini yaz.',
      kabul: ['I get up early'],
    },
  },
  {
    id: 'k-late',
    dil: 'en',
    kelime: 'late',
    tur: 'zarf / sıfat',
    seviye: 'A1',
    ingilizceTanim: 'after the usual or expected time',
    turkceDestek: 'geç',
    ipa: '/leɪt/',
    heceler: 'late (tek hece)',
    ornekler: [
      { en: 'I go to bed late at the weekend.', tr: 'Hafta sonu geç yatarım.' },
      { en: 'Sorry, I am late.', tr: 'Özür dilerim, geç kaldım.' },
    ],
    esdizim: ['be late', 'late at night', 'too late'],
    esAnlam: [],
    zitAnlam: ['early'],
    aile: ['later', 'lately'],
    hata: '"lately" geç demek değildir, "son zamanlarda" demektir. Geç için sadece "late" kullanılır.',
    kayit: 'gundelik',
    hatirlatma: 'Geç KALMAK be fiiliyle kurulur: "I am late" — "I have late" değil.',
    uretim: {
      yonerge: '"Hafta sonu geç yatarım." cümlesini yaz.',
      kabul: ['I go to bed late at the weekend', 'I go to bed late at weekends', 'At the weekend I go to bed late'],
    },
  },
  {
    id: 'k-weekend',
    dil: 'en',
    kelime: 'weekend',
    tur: 'isim',
    seviye: 'A1',
    ingilizceTanim: 'Saturday and Sunday',
    turkceDestek: 'hafta sonu',
    ipa: '/ˈwiːkend/',
    heceler: 'WEEK·end',
    ornekler: [
      { en: 'I do not get up early at the weekend.', tr: 'Hafta sonu erken kalkmam.' },
      { en: 'What do you do at weekends?', tr: 'Hafta sonları ne yaparsın?' },
    ],
    esdizim: ['at the weekend', 'this weekend', 'have a nice weekend'],
    esAnlam: [],
    zitAnlam: ['weekday'],
    aile: ['week', 'weekday'],
    hata: 'Edat farkı: İngiltere\'de "at the weekend", Amerika\'da "on the weekend". İkisi de doğrudur, birini seç.',
    kayit: 'gundelik',
    ingUsa: { usa: 'on the weekend', ing: 'at the weekend' },
    hatirlatma: 'Baştaki /w/ sesi: dudaklar öne yuvarlanır, "v" değil.',
    uretim: {
      yonerge: '"Hafta sonları arkadaşlarımla buluşurum." cümlesini yaz.',
      kabul: ['I meet my friends at the weekend', 'I meet my friends at weekends', 'I meet my friends on the weekend'],
    },
  },
  {
    id: 'k-oclock',
    dil: 'en',
    kelime: "o'clock",
    tur: 'zarf',
    seviye: 'A1',
    ingilizceTanim: 'used after a number to say the exact hour',
    turkceDestek: 'tam saat (…\'de)',
    ipa: '/əˈklɒk/',
    heceler: 'o·CLOCK',
    ornekler: [
      { en: 'The lesson starts at nine o\'clock.', tr: 'Ders dokuzda başlar.' },
      { en: 'It is three o\'clock.', tr: 'Saat üç.' },
    ],
    esdizim: ["at seven o'clock", "It's five o'clock"],
    esAnlam: [],
    zitAnlam: [],
    aile: ['clock'],
    hata: 'Yalnız TAM saatlerde kullanılır. "half past seven o\'clock" yanlıştır; "half past seven" yeterlidir.',
    kayit: 'gundelik',
    hatirlatma: "o'clock aslında \"of the clock\" ifadesinin kısalmış hâlidir; kesme işareti oradan gelir.",
    uretim: {
      yonerge: '"Ders dokuzda başlar." cümlesini yaz.',
      kabul: ["The lesson starts at nine o'clock", 'The lesson starts at nine', 'The lesson starts at 9'],
    },
  },
  {
    id: 'k-start',
    dil: 'en',
    kelime: 'start',
    tur: 'fiil',
    seviye: 'A1',
    ingilizceTanim: 'to begin doing something',
    turkceDestek: 'başlamak',
    ipa: '/stɑːrt/',
    heceler: 'start (tek hece)',
    ornekler: [
      { en: 'School starts at eight thirty.', tr: 'Okul sekiz otuzda başlar.' },
      { en: 'I start my homework after dinner.', tr: 'Ödevime akşam yemeğinden sonra başlarım.' },
    ],
    esdizim: ['start school', 'start work', 'start at eight'],
    esAnlam: ['begin'],
    zitAnlam: ['finish', 'end'],
    aile: ['starting'],
    hata: 'Baştaki "st-" ünsüz kümesidir; araya ünlü koyma ("sitart" değil).',
    kayit: 'gundelik',
    hatirlatma: '"start to do" ve "start doing" ikisi de doğrudur.',
    uretim: {
      yonerge: '"Okul sekizde başlar." cümlesini yaz.',
      kabul: ['School starts at eight', "School starts at eight o'clock", 'School starts at 8'],
    },
  },
  {
    id: 'k-finish',
    dil: 'en',
    kelime: 'finish',
    tur: 'fiil',
    seviye: 'A1',
    ingilizceTanim: 'to come to the end of something',
    turkceDestek: 'bitmek, bitirmek',
    ipa: '/ˈfɪnɪʃ/',
    heceler: 'FIN·ish',
    ornekler: [
      { en: 'School finishes at three.', tr: 'Okul üçte biter.' },
      { en: 'I finish my homework at nine.', tr: 'Ödevimi dokuzda bitiririm.' },
    ],
    esdizim: ['finish school', 'finish work', 'finish at three'],
    esAnlam: ['end'],
    zitAnlam: ['start', 'begin'],
    aile: ['finished'],
    hata: '"finish" sonrasında fiil gelecekse -ing alır: "I finish doing my homework." — "to do" değil.',
    kayit: 'gundelik',
    hatirlatma: 'İlk ünlü kısa /ɪ/: FİN-iş. "fay-niş" değil.',
    uretim: {
      yonerge: '"Okul üçte biter." cümlesini yaz.',
      kabul: ['School finishes at three', "School finishes at three o'clock", 'School finishes at 3'],
    },
  },
]
