/**
 * DRKOÇ — KELİME KAYITLARI: A1 / Modül 6 — Şehir, yol ve yön
 *
 * Bu modülün asıl zorluğu kelimeler değil EDATLARDIR. Türkçede yer
 * bildirimi tek bir ekle çözülür ("okulda, otobüste, masada"); İngilizce
 * bunu in / on / at diye üçe böler ve seçim mantığı Türkçeden çıkarılamaz.
 * Bu yüzden her yer kelimesinin kaydında hangi edatla kullanıldığı yazar.
 */

export const KELIMELER = [
  {
    id: 'k-street',
    dil: 'en',
    kelime: 'street',
    tur: 'isim',
    seviye: 'A1',
    ingilizceTanim: 'a road in a town or city with houses and shops',
    turkceDestek: 'sokak, cadde',
    ipa: '/striːt/',
    heceler: 'street (tek hece)',
    ornekler: [
      { en: 'I live in a quiet street.', tr: 'Sessiz bir sokakta oturuyorum.' },
      { en: 'The shop is on the other side of the street.', tr: 'Dükkân caddenin diğer tarafında.' },
    ],
    esdizim: ['in the street', 'on the street', 'a busy street'],
    esAnlam: ['road'],
    zitAnlam: [],
    aile: [],
    hata: 'Baştaki "str-" üç ünsüzlü bir kümedir; araya ünlü koyma ("sitirit" değil, tek hamlede "striit").',
    kayit: 'gundelik',
    ingUsa: { usa: 'on the street', ing: 'in the street' },
    hatirlatma: 'Adres verirken "in Bahar Street" değil "on Bahar Street" ya da sadece "in Bahar Street" (İng.) kullanılır; ikisi de duyulur.',
    uretim: {
      yonerge: '"Sessiz bir sokakta oturuyorum." cümlesini yaz.',
      kabul: ['I live in a quiet street', 'I live on a quiet street'],
    },
  },
  {
    id: 'k-park',
    dil: 'en',
    kelime: 'park',
    tur: 'isim / fiil',
    seviye: 'A1',
    ingilizceTanim: 'a large public area with grass and trees where people can walk',
    turkceDestek: 'park',
    ipa: '/pɑːrk/',
    heceler: 'park (tek hece)',
    ornekler: [
      { en: 'There is a big park near my house.', tr: 'Evimin yakınında büyük bir park var.' },
      { en: 'We play football in the park.', tr: 'Parkta futbol oynarız.' },
    ],
    esdizim: ['in the park', 'go to the park', 'a car park'],
    esAnlam: [],
    zitAnlam: [],
    aile: ['parking'],
    hata: 'Parkın İÇİNDE olmak "in the park"tır; "at the park" da doğrudur ama "on the park" yanlıştır.',
    kayit: 'gundelik',
    hatirlatma: '"park" ayrıca "araç park etmek" fiilidir: "You can park here."',
    uretim: {
      yonerge: '"Evimin yakınında bir park var." cümlesini yaz.',
      kabul: ['There is a park near my house', "There's a park near my house", 'There is a big park near my house'],
    },
  },
  {
    id: 'k-supermarket',
    dil: 'en',
    kelime: 'supermarket',
    tur: 'isim',
    seviye: 'A1',
    ingilizceTanim: 'a large shop that sells food and things for the house',
    turkceDestek: 'süpermarket',
    ipa: '/ˈsuːpərmɑːrkɪt/',
    heceler: 'SU·per·mar·ket',
    ornekler: [
      { en: 'The supermarket is opposite the school.', tr: 'Süpermarket okulun karşısında.' },
      { en: 'My mother goes to the supermarket on Saturdays.', tr: 'Annem cumartesileri süpermarkete gider.' },
    ],
    esdizim: ['go to the supermarket', 'at the supermarket'],
    esAnlam: [],
    zitAnlam: [],
    aile: ['market'],
    hata: 'Vurgu İLK hecededir: SUU-pır-maar-kit. Türkçedeki "süpermarKET" vurgusu yanlış duyulur.',
    kayit: 'gundelik',
    hatirlatma: 'Belirli bir yere gidiliyorsa "the" gerekir: go to THE supermarket.',
    uretim: {
      yonerge: '"Süpermarket okulun karşısında." cümlesini yaz.',
      kabul: ['The supermarket is opposite the school'],
    },
  },
  {
    id: 'k-station',
    dil: 'en',
    kelime: 'station',
    tur: 'isim',
    seviye: 'A1',
    ingilizceTanim: 'a place where trains or buses stop',
    turkceDestek: 'istasyon, gar',
    ipa: '/ˈsteɪʃn/',
    heceler: 'STA·tion',
    ornekler: [
      { en: 'The station is five minutes from here.', tr: 'İstasyon buradan beş dakika.' },
      { en: 'I meet my friends at the station.', tr: 'Arkadaşlarımla istasyonda buluşurum.' },
    ],
    esdizim: ['at the station', 'train station', 'bus station'],
    esAnlam: [],
    zitAnlam: [],
    aile: [],
    hata: 'Bir noktada buluşma ya da bulunma için "at" kullanılır: "at the station" ✓, "in the station" binanın içini vurgular.',
    kayit: 'gundelik',
    hatirlatma: '"-tion" eki her zaman "şın" okunur: STEY-şın.',
    uretim: {
      yonerge: '"İstasyonda buluşalım." cümlesini yaz.',
      kabul: ["Let's meet at the station", 'Let us meet at the station', 'We can meet at the station'],
    },
  },
  {
    id: 'k-near',
    dil: 'en',
    kelime: 'near',
    tur: 'edat',
    seviye: 'A1',
    ingilizceTanim: 'a short distance from something',
    turkceDestek: 'yakın, yakınında',
    ipa: '/nɪr/',
    heceler: 'near (tek hece)',
    ornekler: [
      { en: 'There is a park near my school.', tr: 'Okulumun yakınında bir park var.' },
      { en: 'I live near the station.', tr: 'İstasyona yakın oturuyorum.' },
    ],
    esdizim: ['near here', 'near my house', 'quite near'],
    esAnlam: ['close to'],
    zitAnlam: ['far from'],
    aile: ['nearly'],
    hata: '"near" doğrudan isim alır: "near the school" ✓. "near to the school" gereksizdir. Ama "close" ile "to" gerekir: "close TO the school".',
    kayit: 'gundelik',
    hatirlatma: '"nearly" yakın demek değildir, "neredeyse" demektir.',
    uretim: {
      yonerge: '"Okulumun yakınında oturuyorum." cümlesini yaz.',
      kabul: ['I live near my school', 'I live near school', 'I live close to my school'],
    },
  },
  {
    id: 'k-next-to',
    dil: 'en',
    kelime: 'next to',
    tur: 'edat',
    seviye: 'A1',
    ingilizceTanim: 'at the side of something, very close to it',
    turkceDestek: 'yanında, bitişiğinde',
    ipa: '/ˈnekst tuː/',
    heceler: 'NEXT to',
    ornekler: [
      { en: 'The bank is next to the post office.', tr: 'Banka postanenin yanında.' },
      { en: 'Sit next to me.', tr: 'Yanıma otur.' },
    ],
    esdizim: ['next to the bank', 'sit next to somebody'],
    esAnlam: ['beside'],
    zitAnlam: [],
    aile: ['next'],
    hata: '"next to" ile "opposite" karıştırılır: next to = yan yana (aynı taraf), opposite = karşı karşıya (karşı taraf).',
    kayit: 'gundelik',
    hatirlatma: '"to" bu kalıbın ayrılmaz parçasıdır: "next the bank" yanlıştır.',
    uretim: {
      yonerge: '"Banka postanenin yanında." cümlesini yaz.',
      kabul: ['The bank is next to the post office'],
    },
  },
  {
    id: 'k-opposite',
    dil: 'en',
    kelime: 'opposite',
    tur: 'edat',
    seviye: 'A1',
    ingilizceTanim: 'on the other side of a road or space, facing something',
    turkceDestek: 'karşısında',
    ipa: '/ˈɒpəzɪt/',
    heceler: 'OP·po·site',
    ornekler: [
      { en: 'The school is opposite the park.', tr: 'Okul parkın karşısında.' },
      { en: 'There is a café opposite my house.', tr: 'Evimin karşısında bir kafe var.' },
    ],
    esdizim: ['opposite the bank', 'the opposite side'],
    esAnlam: ['across from'],
    zitAnlam: [],
    aile: [],
    hata: '"opposite" doğrudan isim alır: "opposite the school" ✓, "opposite to the school" ✗ ve "opposite of" da yanlıştır.',
    kayit: 'gundelik',
    hatirlatma: 'Amerika\'da "across from" daha yaygındır; ikisi de doğrudur.',
    uretim: {
      yonerge: '"Okul parkın karşısında." cümlesini yaz.',
      kabul: ['The school is opposite the park', 'The school is across from the park'],
    },
  },
  {
    id: 'k-between',
    dil: 'en',
    kelime: 'between',
    tur: 'edat',
    seviye: 'A1',
    ingilizceTanim: 'in the space that separates two things',
    turkceDestek: 'arasında',
    ipa: '/bɪˈtwiːn/',
    heceler: 'be·TWEEN',
    ornekler: [
      { en: 'The bank is between the school and the café.', tr: 'Banka okulla kafenin arasında.' },
      { en: 'Sit between us.', tr: 'Aramıza otur.' },
    ],
    esdizim: ['between A and B', 'in between'],
    esAnlam: [],
    zitAnlam: [],
    aile: [],
    hata: 'İki şey varsa "between", ikiden fazlaysa "among" kullanılır. Ayrıca kalıp her zaman "between … AND …" biçimindedir; "between … or …" yanlıştır.',
    kayit: 'gundelik',
    hatirlatma: 'Baştaki "tw" kümesinde /w/ sesi var: bi-TWİİN.',
    uretim: {
      yonerge: '"Banka okulla kafenin arasında." cümlesini yaz.',
      kabul: ['The bank is between the school and the cafe', 'The bank is between the school and the café'],
    },
  },
  {
    id: 'k-turn-left',
    dil: 'en',
    kelime: 'turn left / turn right',
    tur: 'kalıp',
    seviye: 'A1',
    ingilizceTanim: 'to change direction to the left or to the right',
    turkceDestek: 'sola dön / sağa dön',
    ipa: '/tɜːrn ˈleft/',
    heceler: 'turn LEFT',
    ornekler: [
      { en: 'Turn left at the traffic lights.', tr: 'Trafik ışıklarından sola dön.' },
      { en: 'Turn right and the bank is on your left.', tr: 'Sağa dön, banka solunda kalacak.' },
    ],
    esdizim: ['turn left at…', 'on your left', 'on the right'],
    esAnlam: [],
    zitAnlam: [],
    aile: ['left', 'right'],
    hata: 'Bir şeyin solda BULUNDUĞUNU söylerken "on the left" denir: "The bank is on the left." — "in the left" ya da "at the left" değil.',
    kayit: 'gundelik',
    hatirlatma: 'Yol tarifinde emir kipi normaldir ve kaba durmaz: "Turn left." "Go straight on."',
    uretim: {
      yonerge: '"Trafik ışıklarından sola dön." cümlesini yaz.',
      kabul: ['Turn left at the traffic lights', 'Turn left at the lights'],
    },
  },
  {
    id: 'k-go-straight',
    dil: 'en',
    kelime: 'go straight on',
    tur: 'kalıp',
    seviye: 'A1',
    ingilizceTanim: 'to continue in the same direction without turning',
    turkceDestek: 'düz git, dosdoğru devam et',
    ipa: '/ɡoʊ streɪt ˈɒn/',
    heceler: 'go straight ON',
    ornekler: [
      { en: 'Go straight on for about two hundred metres.', tr: 'Yaklaşık iki yüz metre düz git.' },
      { en: 'Go straight on and then turn left.', tr: 'Düz git, sonra sola dön.' },
    ],
    esdizim: ['go straight on', 'go along this street', 'go past the bank'],
    esAnlam: ['go ahead'],
    zitAnlam: [],
    aile: ['straight'],
    hata: '"straight" içindeki "gh" okunmaz: STREYT. Ayrıca Amerika\'da "go straight ahead" daha yaygındır.',
    kayit: 'gundelik',
    ingUsa: { usa: 'go straight ahead', ing: 'go straight on' },
    hatirlatma: 'Yol tarifi hep aynı üç kalıpla döner: go straight on · turn left/right · it is on your left/right.',
    uretim: {
      yonerge: '"Düz git ve sonra sağa dön." cümlesini yaz.',
      kabul: ['Go straight on and then turn right', 'Go straight and then turn right', 'Go straight ahead and then turn right'],
    },
  },
  {
    id: 'k-corner',
    dil: 'en',
    kelime: 'corner',
    tur: 'isim',
    seviye: 'A1',
    ingilizceTanim: 'the place where two streets meet',
    turkceDestek: 'köşe',
    ipa: '/ˈkɔːrnər/',
    heceler: 'COR·ner',
    ornekler: [
      { en: 'There is a small shop on the corner.', tr: 'Köşede küçük bir dükkân var.' },
      { en: 'Turn left at the corner.', tr: 'Köşeden sola dön.' },
    ],
    esdizim: ['on the corner', 'at the corner', 'around the corner'],
    esAnlam: [],
    zitAnlam: [],
    aile: [],
    hata: 'Dükkân köşedeyse "ON the corner", köşede beklerken "AT the corner" denir. "in the corner" ise bir odanın köşesidir.',
    kayit: 'gundelik',
    hatirlatma: '"around the corner" = çok yakın, köşeyi dönünce.',
    uretim: {
      yonerge: '"Köşede bir dükkân var." cümlesini yaz.',
      kabul: ['There is a shop on the corner', "There's a shop on the corner", 'There is a small shop on the corner'],
    },
  },
  {
    id: 'k-how-far',
    dil: 'en',
    kelime: 'How far…?',
    tur: 'kalıp',
    seviye: 'A1',
    ingilizceTanim: 'used to ask about distance',
    turkceDestek: 'Ne kadar uzakta?',
    ipa: '/haʊ ˈfɑːr/',
    heceler: 'how FAR',
    ornekler: [
      { en: 'How far is the station from here?', tr: 'İstasyon buradan ne kadar uzakta?' },
      { en: 'It is about ten minutes on foot.', tr: 'Yürüyerek yaklaşık on dakika.' },
    ],
    esdizim: ['How far is it?', 'ten minutes on foot', 'not far from here'],
    esAnlam: [],
    zitAnlam: [],
    aile: ['far'],
    hata: 'Cevapta mesafe genelde SÜREYLE verilir: "ten minutes on foot" ya da "five minutes by bus".',
    kayit: 'gundelik',
    hatirlatma: 'Yürüyerek "on foot" denir; "by foot" yaygın bir hatadır.',
    uretim: {
      yonerge: '"İstasyon buradan ne kadar uzakta?" sorusunu yaz.',
      kabul: ['How far is the station from here', 'How far is the station', 'How far is it from here'],
    },
  },
  {
    id: 'k-excuse-me-directions',
    dil: 'en',
    kelime: 'Excuse me, where is…?',
    tur: 'kalıp',
    seviye: 'A1',
    ingilizceTanim: 'the polite way to start asking for directions',
    turkceDestek: 'Affedersiniz, … nerede?',
    ipa: '/ɪkˈskjuːz miː wer ɪz/',
    heceler: 'ex·CUSE me, WHERE is',
    ornekler: [
      { en: 'Excuse me, where is the post office?', tr: 'Affedersiniz, postane nerede?' },
      { en: 'Excuse me, is there a bank near here?', tr: 'Affedersiniz, buralarda banka var mı?' },
    ],
    esdizim: ['Excuse me, how do I get to…?', 'Is there a … near here?'],
    esAnlam: [],
    zitAnlam: [],
    aile: ['excuse'],
    hata: 'Doğrudan "Where is the bank?" diye başlamak kaba duyulur; önce "Excuse me" gelir.',
    kayit: 'gundelik',
    hatirlatma: 'Üç açılış kalıbı: "Excuse me, where is…?" · "Is there a … near here?" · "How do I get to…?"',
    uretim: {
      yonerge: 'Bir yabancıdan postanenin yerini sor.',
      kabul: [
        'Excuse me where is the post office', 'Excuse me, where is the post office?',
        'Excuse me how do I get to the post office', 'Excuse me, is there a post office near here?',
      ],
    },
  },
]
