/**
 * DRKOÇ — KELİME KAYITLARI: A1 / Tanışma
 * ==================================================================
 *
 * Kelime sayfası "İngilizce = Türkçe" listesi DEĞİLDİR. Her kayıt,
 * kelimeyi gerçekten kullanabilmek için gereken her şeyi taşır:
 * öğrenci dostu İNGİLİZCE tanım (öncelikli), gerektiğinde Türkçe köprü,
 * IPA, heceler, iki farklı bağlamda örnek, eşdizimler, kelime ailesi,
 * sık yapılan hata ve kelimeyi ÜRETTİRECEK bir görev.
 *
 * TÜRKÇE DESTEK BİLİNÇLİ OLARAK İKİNCİL: A1'de köprü olarak durur, üst
 * seviyelerde kaybolur. Amaç öğrencinin kelimeyi Türkçe karşılığı
 * üzerinden değil, anlamı ve kullanımı üzerinden hatırlaması.
 *
 * IPA gösterimleri Amerikan İngilizcesi temel alınarak yazılmış, farklı
 * olduğunda İngiliz İngilizcesi `ingUsa` alanında ayrıca verilmiştir.
 */

export const KELIMELER = [
  {
    id: 'k-hello',
    dil: 'en',
    kelime: 'hello',
    tur: 'ünlem',
    seviye: 'A1',
    ingilizceTanim: 'a word you say when you meet someone or answer the phone',
    turkceDestek: 'merhaba',
    ipa: '/həˈloʊ/',
    heceler: 'hel·LO',
    vurgu: 'İkinci hecede: he-LO. Türkçedeki gibi ilk heceyi vurgularsan yabancı duyulur.',
    ornekler: [
      { en: 'Hello! My name is Deniz.', tr: 'Merhaba! Benim adım Deniz.' },
      { en: 'Hello, is this Dr. Smith\'s office?', tr: 'Alo, Dr. Smith\'in ofisi mi?' },
    ],
    esdizim: ['say hello', 'hello there'],
    esAnlam: ['hi', 'hey'],
    zitAnlam: ['goodbye'],
    aile: [],
    hata: 'Telefonda Türkçedeki "alo" yerine de hello kullanılır; "alo" İngilizce değildir.',
    kayit: 'gundelik',
    hatirlatma: 'Kapıda birine el sallarken "he-LO" diye iki heceyi ayır: ikinci hece yüksek.',
    uretim: {
      yonerge: 'Sınıfa girdin ve öğretmenini gördün. Ne dersin?',
      kabul: ['Hello', 'Hello teacher', 'Hello, teacher'],
    },
  },
  {
    id: 'k-good-morning',
    dil: 'en',
    kelime: 'good morning',
    tur: 'kalıp',
    seviye: 'A1',
    ingilizceTanim: 'the greeting you use before 12 o\'clock',
    turkceDestek: 'günaydın',
    ipa: '/ˌɡʊd ˈmɔːrnɪŋ/',
    heceler: 'good MOR·ning',
    ornekler: [
      { en: 'Good morning, everyone. Please sit down.', tr: 'Günaydın herkese. Lütfen oturun.' },
      { en: 'Good morning! Did you sleep well?', tr: 'Günaydın! İyi uyudun mu?' },
    ],
    esdizim: ['good afternoon', 'good evening', 'good night'],
    esAnlam: [],
    zitAnlam: ['good night'],
    aile: ['morning'],
    hata: '"Good night" bir selamlaşma değil, VEDA kalıbıdır — akşam biriyle karşılaşınca "Good evening" denir.',
    kayit: 'gundelik',
    hatirlatma: 'Saate göre üçe bölünür: 12\'ye kadar morning, 18\'e kadar afternoon, sonrası evening.',
    uretim: {
      yonerge: 'Saat 09:00, okulda öğretmenini gördün. Selam ver.',
      kabul: ['Good morning', 'Good morning teacher', 'Good morning, teacher'],
    },
  },
  {
    id: 'k-name',
    dil: 'en',
    kelime: 'name',
    tur: 'isim',
    seviye: 'A1',
    ingilizceTanim: 'the word that people use to call you',
    turkceDestek: 'ad, isim',
    ipa: '/neɪm/',
    heceler: 'name (tek hece)',
    ornekler: [
      { en: 'My name is Elif.', tr: 'Benim adım Elif.' },
      { en: 'What is your name?', tr: 'Adın ne?' },
    ],
    esdizim: ['first name', 'last name', 'full name', "What's your name?"],
    esAnlam: [],
    zitAnlam: [],
    aile: ['named', 'nickname', 'surname'],
    hata: 'Türkçede "adım Elif" derken fiil yoktur. İngilizcede "My name IS Elif" — is atlanmaz.',
    kayit: 'gundelik',
    hatirlatma: 'a harfi burada "ey" okunur: neym. Yazıldığı gibi "na-me" değil.',
    uretim: {
      yonerge: 'Adını söyleyen tam bir cümle yaz.',
      kabul: ['My name is', 'my name is'],
      serbestBaslangic: true,
    },
  },
  {
    id: 'k-nice-to-meet-you',
    dil: 'en',
    kelime: 'Nice to meet you.',
    tur: 'kalıp',
    seviye: 'A1',
    ingilizceTanim: 'what you say the first time you meet someone',
    turkceDestek: 'Tanıştığımıza memnun oldum.',
    ipa: '/ˌnaɪs tə ˈmiːt juː/',
    heceler: 'NICE to MEET you',
    ornekler: [
      { en: '— I\'m Kerem. — Nice to meet you, Kerem.', tr: '— Ben Kerem. — Memnun oldum Kerem.' },
      { en: 'Nice to meet you too.', tr: 'Ben de memnun oldum.' },
    ],
    esdizim: ['Nice to meet you too', 'Pleased to meet you'],
    esAnlam: ['Pleased to meet you'],
    zitAnlam: [],
    aile: ['meet', 'meeting'],
    hata: 'Aynı kişiyle ikinci kez karşılaşınca bu kullanılmaz; "Nice to see you again" denir.',
    kayit: 'gundelik',
    hatirlatma: 'Doğal konuşmada "to" zayıflar: nays-tə-MİİT-yu. Her heceyi eşit vurgularsan robot gibi duyulur.',
    uretim: {
      yonerge: 'Biri kendini tanıttı. Uygun karşılığı yaz.',
      kabul: ['Nice to meet you', 'Nice to meet you too', 'Pleased to meet you'],
    },
  },
  {
    id: 'k-from',
    dil: 'en',
    kelime: 'from',
    tur: 'edat',
    seviye: 'A1',
    ingilizceTanim: 'used to show where a person or thing started',
    turkceDestek: '-den, -dan (kaynak, köken)',
    ipa: '/frʌm/',
    heceler: 'from (tek hece)',
    ornekler: [
      { en: 'I am from Turkey.', tr: 'Ben Türkiye\'denim.' },
      { en: 'This letter is from my sister.', tr: 'Bu mektup kız kardeşimden.' },
    ],
    esdizim: ['from Turkey', 'far from', 'from Monday to Friday'],
    esAnlam: [],
    zitAnlam: ['to'],
    aile: [],
    hata: 'Nereli olduğunu söylerken ÜLKE adı kullanılır: "I am from Turkey." Milliyet kullanılacaksa from düşer: "I am Turkish."',
    kayit: 'gundelik',
    hatirlatma: 'from = kaynak. Nereden geldi? sorusunun cevabı.',
    uretim: {
      yonerge: '"Ben İzmir\'denim." cümlesini İngilizce yaz.',
      kabul: ['I am from Izmir', "I'm from Izmir", 'I am from İzmir', "I'm from İzmir"],
    },
  },
  {
    id: 'k-country',
    dil: 'en',
    kelime: 'country',
    tur: 'isim',
    seviye: 'A1',
    ingilizceTanim: 'an area of land with its own government, like Turkey or Japan',
    turkceDestek: 'ülke',
    ipa: '/ˈkʌntri/',
    heceler: 'COUN·try',
    ornekler: [
      { en: 'Which country are you from?', tr: 'Hangi ülkedensin?' },
      { en: 'Turkey is a beautiful country.', tr: 'Türkiye güzel bir ülke.' },
    ],
    esdizim: ['my country', 'foreign country', 'which country'],
    esAnlam: ['nation'],
    zitAnlam: ['city'],
    aile: ['countryside'],
    hata: 'Çoğulu "countrys" değil, "countries" — sonu ünsüz + y olan isimlerde y düşer, ies gelir.',
    kayit: 'gundelik',
    hatirlatma: 'ou burada "a" gibi okunur: KAN-tri. "kaun-tri" değil.',
    uretim: {
      yonerge: '"Hangi ülkedensin?" sorusunu İngilizce yaz.',
      kabul: ['Which country are you from', 'What country are you from'],
    },
  },
  {
    id: 'k-turkish',
    dil: 'en',
    kelime: 'Turkish',
    tur: 'sıfat / isim',
    seviye: 'A1',
    ingilizceTanim: 'connected with Turkey; also the language spoken in Turkey',
    turkceDestek: 'Türk, Türkçe',
    ipa: '/ˈtɜːrkɪʃ/',
    heceler: 'TUR·kish',
    ornekler: [
      { en: 'I am Turkish and I live in Ankara.', tr: 'Ben Türk\'üm ve Ankara\'da yaşıyorum.' },
      { en: 'She speaks Turkish and English.', tr: 'Türkçe ve İngilizce konuşuyor.' },
    ],
    esdizim: ['Turkish coffee', 'speak Turkish', 'Turkish food'],
    esAnlam: [],
    zitAnlam: [],
    aile: ['Turkey'],
    hata: 'Ülke Turkey, milliyet/dil Turkish. "I am from Turkish" yanlış; ya "I am from Turkey" ya da "I am Turkish".',
    kayit: 'gundelik',
    hatirlatma: 'Milliyet ve dil adları İngilizcede her zaman BÜYÜK harfle başlar.',
    uretim: {
      yonerge: '"Ben Türk\'üm." cümlesini İngilizce yaz.',
      kabul: ['I am Turkish', "I'm Turkish"],
    },
  },
  {
    id: 'k-student',
    dil: 'en',
    kelime: 'student',
    tur: 'isim',
    seviye: 'A1',
    ingilizceTanim: 'a person who studies at a school or university',
    turkceDestek: 'öğrenci',
    ipa: '/ˈstuːdənt/',
    heceler: 'STU·dent',
    ornekler: [
      { en: 'I am a student at Ankara High School.', tr: 'Ankara Lisesi\'nde öğrenciyim.' },
      { en: 'There are 24 students in my class.', tr: 'Sınıfımda 24 öğrenci var.' },
    ],
    esdizim: ['high school student', 'a good student', 'exchange student'],
    esAnlam: ['pupil'],
    zitAnlam: ['teacher'],
    aile: ['study', 'studies'],
    hata: 'Meslek/konum söylerken "a" unutulmaz: "I am A student." Türkçede "öğrenciyim" derken böyle bir işaret olmadığı için sık atlanır.',
    kayit: 'gundelik',
    ingUsa: { usa: '/ˈstuːdənt/ — STU-dınt', ing: '/ˈstjuːdnt/ — STYU-dınt' },
    hatirlatma: 'İngiliz İngilizcesinde araya bir "y" sesi girer: styudent.',
    uretim: {
      yonerge: '"Ben bir öğrenciyim." cümlesini İngilizce yaz.',
      kabul: ['I am a student', "I'm a student"],
    },
  },
  {
    id: 'k-teacher',
    dil: 'en',
    kelime: 'teacher',
    tur: 'isim',
    seviye: 'A1',
    ingilizceTanim: 'a person whose job is to help other people learn',
    turkceDestek: 'öğretmen',
    ipa: '/ˈtiːtʃər/',
    heceler: 'TEA·cher',
    ornekler: [
      { en: 'My English teacher is very kind.', tr: 'İngilizce öğretmenim çok nazik.' },
      { en: 'She is a maths teacher.', tr: 'O bir matematik öğretmeni.' },
    ],
    esdizim: ['English teacher', 'head teacher', 'a strict teacher'],
    esAnlam: ['instructor'],
    zitAnlam: ['student'],
    aile: ['teach', 'taught', 'teaching'],
    hata: 'İngilizcede öğretmene seslenirken tek başına "Teacher!" denmez; "Excuse me" ya da "Mr./Ms. + soyadı" kullanılır.',
    kayit: 'gundelik',
    hatirlatma: 'ea burada uzun "i": Tİİ-çır.',
    uretim: {
      yonerge: '"O bir İngilizce öğretmeni." cümlesini İngilizce yaz.',
      kabul: ['He is an English teacher', 'She is an English teacher', "He's an English teacher", "She's an English teacher"],
    },
  },
  {
    id: 'k-live',
    dil: 'en',
    kelime: 'live',
    tur: 'fiil',
    seviye: 'A1',
    ingilizceTanim: 'to have your home in a place',
    turkceDestek: 'yaşamak, oturmak (bir yerde)',
    ipa: '/lɪv/',
    heceler: 'live (tek hece)',
    ornekler: [
      { en: 'I live in Istanbul.', tr: 'İstanbul\'da yaşıyorum.' },
      { en: 'Where do you live?', tr: 'Nerede oturuyorsun?' },
    ],
    esdizim: ['live in a city', 'live with my family', 'live alone'],
    esAnlam: [],
    zitAnlam: [],
    aile: ['living', 'life', 'alive'],
    hata: 'Şehir ve ülke için "in" kullanılır: live IN Ankara. "live at Ankara" yanlıştır; at yalnız tam adres için.',
    kayit: 'gundelik',
    hatirlatma: 'Sıfat olan "live" (canlı yayın) /laɪv/ diye okunur; fiil olan bu kelime kısa: liv.',
    uretim: {
      yonerge: '"Nerede yaşıyorsun?" sorusunu İngilizce yaz.',
      kabul: ['Where do you live'],
    },
  },
  {
    id: 'k-how-old',
    dil: 'en',
    kelime: 'How old are you?',
    tur: 'kalıp',
    seviye: 'A1',
    ingilizceTanim: 'the question you ask to learn someone\'s age',
    turkceDestek: 'Kaç yaşındasın?',
    ipa: '/ˌhaʊ ˈoʊld ɑːr juː/',
    heceler: 'how OLD are you',
    ornekler: [
      { en: '— How old are you? — I am fifteen.', tr: '— Kaç yaşındasın? — On beş.' },
      { en: 'How old is your brother?', tr: 'Abin kaç yaşında?' },
    ],
    esdizim: ['How old is he/she', 'I am … years old'],
    esAnlam: [],
    zitAnlam: [],
    aile: ['old', 'age'],
    hata: 'Yaş söylerken "have" kullanılmaz: "I have 15 years" yanlış — İngilizcede yaş bir DURUMDUR: "I am 15."',
    kayit: 'gundelik',
    hatirlatma: 'Türkçede "yaşındayım" ekle biter; İngilizcede yaş "olmak" fiiliyle söylenir: I AM 15.',
    uretim: {
      yonerge: '"On dört yaşındayım." cümlesini İngilizce yaz.',
      kabul: ['I am fourteen', "I'm fourteen", 'I am 14', "I'm 14", 'I am fourteen years old', "I'm fourteen years old"],
    },
  },
  {
    id: 'k-spell',
    dil: 'en',
    kelime: 'spell',
    tur: 'fiil',
    seviye: 'A1',
    ingilizceTanim: 'to say or write the letters of a word one by one',
    turkceDestek: 'harf harf söylemek / yazmak',
    ipa: '/spel/',
    heceler: 'spell (tek hece)',
    ornekler: [
      { en: 'How do you spell your name?', tr: 'Adını nasıl heceliyorsun?' },
      { en: 'Can you spell that, please?', tr: 'Bunu harf harf söyler misin?' },
    ],
    esdizim: ['How do you spell…', 'spelling mistake'],
    esAnlam: [],
    zitAnlam: [],
    aile: ['spelling'],
    hata: 'Türkçede "nasıl yazılıyor" deriz; İngilizcede bu soru "How do you spell it?" kalıbıyla sorulur, "How do you write it?" değil.',
    kayit: 'gundelik',
    hatirlatma: 'İngilizcede yazım okunuştan farklı olduğu için bu soru çok sık kullanılır. Ezberlemeye değer.',
    uretim: {
      yonerge: '"Adını nasıl hecelersin?" sorusunu İngilizce yaz.',
      kabul: ['How do you spell your name'],
    },
  },
  {
    id: 'k-again',
    dil: 'en',
    kelime: 'again',
    tur: 'zarf',
    seviye: 'A1',
    ingilizceTanim: 'one more time',
    turkceDestek: 'tekrar, yeniden',
    ipa: '/əˈɡen/',
    heceler: 'a·GAIN',
    ornekler: [
      { en: 'Can you say that again, please?', tr: 'Bunu tekrar söyler misin lütfen?' },
      { en: 'See you again soon!', tr: 'Yakında yine görüşürüz!' },
    ],
    esdizim: ['say it again', 'once again', 'again and again'],
    esAnlam: ['once more'],
    zitAnlam: [],
    aile: [],
    hata: 'Vurgu ikinci hecede: a-GEN. İlk heceyi vurgularsan anlaşılmaz.',
    kayit: 'gundelik',
    hatirlatma: 'Anlamadığında kullanacağın en değerli kelime: "Again, please."',
    uretim: {
      yonerge: 'Öğretmeni duymadın. Tekrar etmesini nazikçe iste.',
      kabul: ['Can you say that again please', 'Can you say that again', 'Could you say that again please', 'Could you say that again', 'Again please'],
    },
  },
  {
    id: 'k-understand',
    dil: 'en',
    kelime: 'understand',
    tur: 'fiil',
    seviye: 'A1',
    ingilizceTanim: 'to know what something means',
    turkceDestek: 'anlamak',
    ipa: '/ˌʌndərˈstænd/',
    heceler: 'un·der·STAND',
    ornekler: [
      { en: 'I don\'t understand this word.', tr: 'Bu kelimeyi anlamıyorum.' },
      { en: 'Do you understand the question?', tr: 'Soruyu anlıyor musun?' },
    ],
    esdizim: ["I don't understand", 'hard to understand', 'understand each other'],
    esAnlam: ['get'],
    zitAnlam: ['misunderstand'],
    aile: ['understanding', 'misunderstand'],
    hata: 'Bu fiil şimdiki zamanda -ing almaz: "I am not understanding" yerine "I don\'t understand" denir.',
    kayit: 'gundelik',
    hatirlatma: 'Vurgu SONDA: an-dır-STEND. Üç heceli uzun kelimelerde Türkçe alışkanlığıyla ilk heceyi vurgulama.',
    uretim: {
      yonerge: '"Anlamıyorum." cümlesini İngilizce yaz.',
      kabul: ["I don't understand", 'I do not understand'],
    },
  },
  {
    id: 'k-thank-you',
    dil: 'en',
    kelime: 'thank you',
    tur: 'kalıp',
    seviye: 'A1',
    ingilizceTanim: 'what you say when someone helps you or gives you something',
    turkceDestek: 'teşekkür ederim',
    ipa: '/ˈθæŋk juː/',
    heceler: 'THANK you',
    ornekler: [
      { en: 'Thank you for your help.', tr: 'Yardımın için teşekkürler.' },
      { en: '— Here is your book. — Thank you!', tr: '— Kitabın burada. — Teşekkürler!' },
    ],
    esdizim: ['thank you very much', 'thanks a lot', 'thank you for…'],
    esAnlam: ['thanks'],
    zitAnlam: [],
    aile: ['thanks', 'thankful'],
    hata: '"thank you for" sonrası fiil gelecekse -ing alır: thank you for helping me (to help değil).',
    kayit: 'gundelik',
    hatirlatma: 'Baştaki th sesi /θ/ — dilin ucu dişlerin arasında. Türkçedeki "t" ya da "s" değil.',
    uretim: {
      yonerge: 'Biri sana yardım etti. Teşekkür et.',
      kabul: ['Thank you', 'Thanks', 'Thank you very much', 'Thanks a lot'],
    },
  },
  {
    id: 'k-please',
    dil: 'en',
    kelime: 'please',
    tur: 'zarf',
    seviye: 'A1',
    ingilizceTanim: 'a polite word you add when you ask for something',
    turkceDestek: 'lütfen',
    ipa: '/pliːz/',
    heceler: 'please (tek hece)',
    ornekler: [
      { en: 'Can you help me, please?', tr: 'Bana yardım eder misin lütfen?' },
      { en: 'Please sit down.', tr: 'Lütfen otur.' },
    ],
    esdizim: ['yes, please', 'please help me'],
    esAnlam: [],
    zitAnlam: [],
    aile: ['pleased', 'pleasure'],
    hata: 'İngilizcede please, Türkçedeki "lütfen"den daha sık kullanılır. Ricadan çıkarılırsa cümle kaba duyulabilir.',
    kayit: 'gundelik',
    hatirlatma: 'Sonundaki s aslında "z" okunur: pliiz.',
    uretim: {
      yonerge: '"Bana yardım eder misin lütfen?" cümlesini İngilizce yaz.',
      kabul: ['Can you help me please', 'Could you help me please', 'Can you help me, please'],
    },
  },
  {
    id: 'k-sorry',
    dil: 'en',
    kelime: 'sorry',
    tur: 'sıfat',
    seviye: 'A1',
    ingilizceTanim: 'the word you use to apologise, or to ask someone to repeat',
    turkceDestek: 'özür dilerim / pardon',
    ipa: '/ˈsɑːri/',
    heceler: 'SOR·ry',
    ornekler: [
      { en: 'Sorry, I am late.', tr: 'Özür dilerim, geç kaldım.' },
      { en: 'Sorry? Can you repeat that?', tr: 'Pardon? Tekrar eder misin?' },
    ],
    esdizim: ["I'm sorry", 'sorry about that', 'sorry for being late'],
    esAnlam: ['excuse me'],
    zitAnlam: [],
    aile: [],
    hata: '"Sorry" ile "Excuse me" farklıdır: sorry bir şey OLDUKTAN sonra, excuse me bir şey yapmadan ÖNCE (dikkat çekmek için) kullanılır.',
    kayit: 'gundelik',
    ingUsa: { usa: '/ˈsɑːri/ — SAA-ri', ing: '/ˈsɒri/ — SO-ri' },
    hatirlatma: 'Yükselen tonla söylenen "Sorry?" = "Anlamadım, tekrar eder misin?"',
    uretim: {
      yonerge: 'Derse geç kaldın, içeri girerken ne dersin?',
      kabul: ['Sorry I am late', "Sorry, I'm late", "I'm sorry I'm late", 'Sorry, I am late'],
    },
  },
  {
    id: 'k-goodbye',
    dil: 'en',
    kelime: 'goodbye',
    tur: 'ünlem',
    seviye: 'A1',
    ingilizceTanim: 'what you say when you leave someone',
    turkceDestek: 'hoşça kal, güle güle',
    ipa: '/ˌɡʊdˈbaɪ/',
    heceler: 'good·BYE',
    ornekler: [
      { en: 'Goodbye! See you tomorrow.', tr: 'Hoşça kal! Yarın görüşürüz.' },
      { en: 'She said goodbye and left.', tr: 'Vedalaşıp gitti.' },
    ],
    esdizim: ['say goodbye', 'goodbye for now'],
    esAnlam: ['bye', 'see you'],
    zitAnlam: ['hello'],
    aile: ['bye'],
    hata: 'Günlük konuşmada tam biçim ağır durur; arkadaşlar arasında "Bye" ya da "See you" tercih edilir.',
    kayit: 'gundelik',
    hatirlatma: 'Vurgu ikinci hecede: gud-BAY.',
    uretim: {
      yonerge: 'Arkadaşından ayrılıyorsun, yarın yine göreceksin. Ne dersin?',
      kabul: ['See you tomorrow', 'Goodbye see you tomorrow', 'Bye see you tomorrow', 'See you'],
    },
  },
  {
    id: 'k-friend',
    dil: 'en',
    kelime: 'friend',
    tur: 'isim',
    seviye: 'A1',
    ingilizceTanim: 'a person you like and know well, but who is not in your family',
    turkceDestek: 'arkadaş',
    ipa: '/frend/',
    heceler: 'friend (tek hece)',
    ornekler: [
      { en: 'This is my friend Ayşe.', tr: 'Bu arkadaşım Ayşe.' },
      { en: 'I have a lot of friends at school.', tr: 'Okulda çok arkadaşım var.' },
    ],
    esdizim: ['best friend', 'close friend', 'make friends'],
    esAnlam: [],
    zitAnlam: ['enemy'],
    aile: ['friendly', 'friendship'],
    hata: 'Arkadaş EDİNMEK için "make friends" denir; "do friends" ya da "take friends" yanlıştır.',
    kayit: 'gundelik',
    hatirlatma: 'ie burada "e" gibi okunur: FREND. "fri-end" diye iki heceye bölme.',
    uretim: {
      yonerge: '"Bu benim arkadaşım." cümlesini İngilizce yaz.',
      kabul: ['This is my friend'],
    },
  },
  {
    id: 'k-where',
    dil: 'en',
    kelime: 'where',
    tur: 'soru sözcüğü',
    seviye: 'A1',
    ingilizceTanim: 'the question word you use to ask about a place',
    turkceDestek: 'nerede, nereye',
    ipa: '/wer/',
    heceler: 'where (tek hece)',
    ornekler: [
      { en: 'Where are you from?', tr: 'Nerelisin?' },
      { en: 'Where is my bag?', tr: 'Çantam nerede?' },
    ],
    esdizim: ['where are you from', 'where is', 'where do you live'],
    esAnlam: [],
    zitAnlam: [],
    aile: ['everywhere', 'nowhere', 'somewhere'],
    hata: 'Soru sözcüğünden sonra yardımcı fiil ÖNE geçer: "Where ARE you?" — "Where you are?" değil.',
    kayit: 'gundelik',
    hatirlatma: 'w sesi Türkçede yok: dudaklar öne büzülür, "v" gibi dişe değmez.',
    uretim: {
      yonerge: '"Nerelisin?" sorusunu İngilizce yaz.',
      kabul: ['Where are you from'],
    },
  },
  {
    id: 'k-what',
    dil: 'en',
    kelime: 'what',
    tur: 'soru sözcüğü',
    seviye: 'A1',
    ingilizceTanim: 'the question word you use to ask about a thing',
    turkceDestek: 'ne',
    ipa: '/wʌt/',
    heceler: 'what (tek hece)',
    ornekler: [
      { en: 'What is your name?', tr: 'Adın ne?' },
      { en: 'What do you do?', tr: 'Ne iş yapıyorsun?' },
    ],
    esdizim: ['what is your name', 'what time', 'what about'],
    esAnlam: [],
    zitAnlam: [],
    aile: [],
    hata: 'Bir şeyin adı sorulurken "how" değil "what" kullanılır: "What do you call this?" — "How do you call this?" değil.',
    kayit: 'gundelik',
    hatirlatma: 'wh burada yalnız "w" okunur, h duyulmaz: WAT.',
    uretim: {
      yonerge: '"Adın ne?" sorusunu İngilizce yaz.',
      kabul: ['What is your name', "What's your name"],
    },
  },
  {
    id: 'k-year',
    dil: 'en',
    kelime: 'year',
    tur: 'isim',
    seviye: 'A1',
    ingilizceTanim: 'a period of twelve months',
    turkceDestek: 'yıl, sene',
    ipa: '/jɪr/',
    heceler: 'year (tek hece)',
    ornekler: [
      { en: 'I am fifteen years old.', tr: 'On beş yaşındayım.' },
      { en: 'We study English every year.', tr: 'Her yıl İngilizce çalışıyoruz.' },
    ],
    esdizim: ['years old', 'last year', 'next year', 'this year'],
    esAnlam: [],
    zitAnlam: [],
    aile: ['yearly'],
    hata: 'Yaş söylerken çoğul olur: "fifteen yearS old". Türkçede "on beş yaş" tekil kaldığı için sık atlanır.',
    kayit: 'gundelik',
    hatirlatma: 'Baştaki y bir ünsüzdür: YİR. "i-ir" değil.',
    uretim: {
      yonerge: '"On altı yaşındayım." cümlesini "years old" kullanarak yaz.',
      kabul: ['I am sixteen years old', "I'm sixteen years old", 'I am 16 years old', "I'm 16 years old"],
    },
  },
  {
    id: 'k-welcome',
    dil: 'en',
    kelime: 'welcome',
    tur: 'ünlem / sıfat',
    seviye: 'A1',
    ingilizceTanim: 'a friendly word for someone who has just arrived',
    turkceDestek: 'hoş geldin',
    ipa: '/ˈwelkəm/',
    heceler: 'WEL·come',
    ornekler: [
      { en: 'Welcome to our school!', tr: 'Okulumuza hoş geldin!' },
      { en: '— Thank you. — You\'re welcome.', tr: '— Teşekkürler. — Rica ederim.' },
    ],
    esdizim: ['welcome to…', "you're welcome"],
    esAnlam: [],
    zitAnlam: [],
    aile: [],
    hata: '"You\'re welcome" hoş geldin demek değildir; teşekküre karşılık "rica ederim" demektir.',
    kayit: 'gundelik',
    hatirlatma: 'Türkçedeki "hoş bulduk"un birebir karşılığı yoktur; "Thank you" denir.',
    uretim: {
      yonerge: 'Biri sana teşekkür etti. Nazik karşılığı yaz.',
      kabul: ["You're welcome", 'You are welcome', 'No problem'],
    },
  },
  {
    id: 'k-number',
    dil: 'en',
    kelime: 'number',
    tur: 'isim',
    seviye: 'A1',
    ingilizceTanim: 'a word or sign like 1, 2, 3 that shows how many',
    turkceDestek: 'sayı, numara',
    ipa: '/ˈnʌmbər/',
    heceler: 'NUM·ber',
    ornekler: [
      { en: 'What is your phone number?', tr: 'Telefon numaran ne?' },
      { en: 'Write the numbers from one to ten.', tr: 'Birden ona kadar sayıları yaz.' },
    ],
    esdizim: ['phone number', 'a large number of', 'number one'],
    esAnlam: [],
    zitAnlam: [],
    aile: ['numbers'],
    hata: 'Telefon numarası sorulurken "How is your number?" değil "What is your number?" denir.',
    kayit: 'gundelik',
    hatirlatma: 'u burada "a" gibi: NAM-bır.',
    uretim: {
      yonerge: '"Telefon numaran ne?" sorusunu İngilizce yaz.',
      kabul: ['What is your phone number', "What's your phone number", 'What is your number'],
    },
  },
]

/** Kelimeyi id ile getirir. */
export function kelimeBul(id) {
  return KELIMELER.find((k) => k.id === id) ?? null
}
