/**
 * DRKOÇ — KELİME KAYITLARI: A1 / Modül 5 — Yemek ve alışveriş
 *
 * Bu modülün merkezinde SAYILABİLEN / SAYILAMAYAN ayrımı var. Türkçede
 * böyle bir dilbilgisi ayrımı yoktur: "üç ekmek", "iki su", "çok bilgi"
 * hepsi kurallıdır. İngilizcede bu ayrım artikel, çoğul eki, some/any ve
 * how much/how many seçimini birden belirler. Bu yüzden her kelime
 * kaydında `sayilabilir` bilgisi açıkça yazılıdır.
 */

export const KELIMELER = [
  {
    id: 'k-bread',
    dil: 'en',
    kelime: 'bread',
    tur: 'isim (sayılamaz)',
    seviye: 'A1',
    ingilizceTanim: 'a common food made from flour and water and baked in an oven',
    turkceDestek: 'ekmek',
    ipa: '/bred/',
    heceler: 'bread (tek hece)',
    ornekler: [
      { en: 'We need some bread.', tr: 'Biraz ekmeğe ihtiyacımız var.' },
      { en: 'I eat bread and cheese for breakfast.', tr: 'Kahvaltıda ekmek peynir yerim.' },
    ],
    esdizim: ['a loaf of bread', 'a slice of bread', 'brown bread'],
    esAnlam: [],
    zitAnlam: [],
    aile: [],
    hata: 'SAYILAMAZ isimdir: "a bread" ya da "two breads" denmez. Sayı gerekiyorsa ölçü eklenir: "two loaves of bread", "a slice of bread".',
    kayit: 'gundelik',
    hatirlatma: '"ea" burada kısa /e/ okunur: BRED. "briid" değil.',
    uretim: {
      yonerge: '"Biraz ekmeğe ihtiyacımız var." cümlesini yaz.',
      kabul: ['We need some bread', 'We need bread'],
    },
  },
  {
    id: 'k-water',
    dil: 'en',
    kelime: 'water',
    tur: 'isim (sayılamaz)',
    seviye: 'A1',
    ingilizceTanim: 'the clear liquid that people drink',
    turkceDestek: 'su',
    ipa: '/ˈwɔːtər/',
    heceler: 'WA·ter',
    ornekler: [
      { en: 'Can I have some water, please?', tr: 'Biraz su alabilir miyim?' },
      { en: 'I drink a lot of water every day.', tr: 'Her gün çok su içerim.' },
    ],
    esdizim: ['a glass of water', 'bottled water', 'drink water'],
    esAnlam: [],
    zitAnlam: [],
    aile: [],
    hata: 'SAYILAMAZ: "two waters" resmî olarak yanlıştır. Restoranda "two waters" duyulabilir ama bu "two bottles of water" kısaltmasıdır.',
    kayit: 'gundelik',
    hatirlatma: 'Baştaki /w/ sesi: dudaklar öne yuvarlanır, "vater" değil "WOO-tır".',
    uretim: {
      yonerge: '"Biraz su alabilir miyim lütfen?" cümlesini yaz.',
      kabul: ['Can I have some water please', 'Can I have some water, please?', 'Could I have some water please', 'Can I have water please'],
    },
  },
  {
    id: 'k-apple',
    dil: 'en',
    kelime: 'apple',
    tur: 'isim (sayılabilir)',
    seviye: 'A1',
    ingilizceTanim: 'a round fruit with red or green skin',
    turkceDestek: 'elma',
    ipa: '/ˈæpl/',
    heceler: 'AP·ple',
    ornekler: [
      { en: 'I eat an apple every day.', tr: 'Her gün bir elma yerim.' },
      { en: 'We have got three apples.', tr: 'Üç elmamız var.' },
    ],
    esdizim: ['an apple a day', 'green apple', 'apple juice'],
    esAnlam: [],
    zitAnlam: [],
    aile: [],
    hata: 'SAYILABİLİR isimdir: tekilken "an" alır (ünlü sesle başladığı için "a" değil "an"), çoğulken -s alır.',
    kayit: 'gundelik',
    hatirlatma: 'Türkçede "elma yerim" derken sayı işareti yok; İngilizcede tekil sayılabilir isim artikelsiz kalamaz.',
    uretim: {
      yonerge: '"Her gün bir elma yerim." cümlesini yaz.',
      kabul: ['I eat an apple every day', 'Every day I eat an apple'],
    },
  },
  {
    id: 'k-milk',
    dil: 'en',
    kelime: 'milk',
    tur: 'isim (sayılamaz)',
    seviye: 'A1',
    ingilizceTanim: 'the white liquid that comes from cows',
    turkceDestek: 'süt',
    ipa: '/mɪlk/',
    heceler: 'milk (tek hece)',
    ornekler: [
      { en: 'There is not any milk in the fridge.', tr: 'Buzdolabında hiç süt yok.' },
      { en: 'I drink milk with my breakfast.', tr: 'Kahvaltıda süt içerim.' },
    ],
    esdizim: ['a glass of milk', 'a carton of milk', 'tea with milk'],
    esAnlam: [],
    zitAnlam: [],
    aile: [],
    hata: 'SAYILAMAZ: "milks" denmez. Miktar için "a glass of milk" ya da "a carton of milk" kullanılır.',
    kayit: 'gundelik',
    hatirlatma: 'Sonundaki "lk" kümesi tek nefeste söylenir; araya ünlü koyma.',
    uretim: {
      yonerge: '"Buzdolabında hiç süt yok." cümlesini yaz.',
      kabul: [
        'There is not any milk in the fridge', "There isn't any milk in the fridge",
        'There is no milk in the fridge',
      ],
    },
  },
  {
    id: 'k-some',
    dil: 'en',
    kelime: 'some',
    tur: 'belirteç',
    seviye: 'A1',
    ingilizceTanim: 'an amount of something, when you do not say exactly how much',
    turkceDestek: 'biraz, birkaç',
    ipa: '/sʌm/',
    heceler: 'some (tek hece)',
    ornekler: [
      { en: 'I have got some money.', tr: 'Biraz param var.' },
      { en: 'We need some apples.', tr: 'Birkaç elmaya ihtiyacımız var.' },
    ],
    esdizim: ['some water', 'some friends', 'Would you like some tea?'],
    esAnlam: [],
    zitAnlam: ['any'],
    aile: ['somebody', 'something'],
    hata: 'OLUMLU cümlelerde ve TEKLİF sorularında kullanılır. Normal sorularda ve olumsuzlarda "any" gelir: "Have you got any money?"',
    kayit: 'gundelik',
    hatirlatma: 'İstisna: teklif ve rica sorularında "some" kullanılır — "Would you like some tea?"',
    uretim: {
      yonerge: '"Biraz suya ihtiyacım var." cümlesini yaz.',
      kabul: ['I need some water'],
    },
  },
  {
    id: 'k-any',
    dil: 'en',
    kelime: 'any',
    tur: 'belirteç',
    seviye: 'A1',
    ingilizceTanim: 'used in questions and negative sentences instead of "some"',
    turkceDestek: 'hiç, herhangi',
    ipa: '/ˈeni/',
    heceler: 'AN·y',
    ornekler: [
      { en: 'Have you got any brothers?', tr: 'Hiç erkek kardeşin var mı?' },
      { en: 'There are not any eggs.', tr: 'Hiç yumurta yok.' },
    ],
    esdizim: ['any questions', 'not any', 'any time'],
    esAnlam: [],
    zitAnlam: ['some'],
    aile: ['anybody', 'anything'],
    hata: '"not any" ile "no" aynı anlama gelir: "There are not any eggs." = "There are no eggs." İkisini birleştirme: "There are not no eggs" yanlıştır.',
    kayit: 'gundelik',
    hatirlatma: 'Kısa yol: olumlu → some, soru ve olumsuz → any.',
    uretim: {
      yonerge: '"Hiç kardeşin var mı?" sorusunu yaz.',
      kabul: [
        'Have you got any brothers or sisters', 'Have you got any brothers',
        'Do you have any brothers or sisters', 'Do you have any brothers',
        'Have you got any siblings',
      ],
    },
  },
  {
    id: 'k-how-much',
    dil: 'en',
    kelime: 'How much…?',
    tur: 'kalıp',
    seviye: 'A1',
    ingilizceTanim: 'used to ask about the price, or about the amount of something you cannot count',
    turkceDestek: 'Ne kadar? / Kaç para?',
    ipa: '/haʊ ˈmʌtʃ/',
    heceler: 'how MUCH',
    ornekler: [
      { en: 'How much is this T-shirt?', tr: 'Bu tişört kaç para?' },
      { en: 'How much sugar do you want?', tr: 'Ne kadar şeker istersin?' },
    ],
    esdizim: ['How much is it?', 'How much does it cost?'],
    esAnlam: [],
    zitAnlam: [],
    aile: ['much'],
    hata: 'SAYILAMAYAN isimlerle ve fiyat sorarken kullanılır. Sayılabilen isimler için "How many" gelir.',
    kayit: 'gundelik',
    hatirlatma: 'Fiyat sorarken Türkçedeki "fiyatı ne kadar" kalıbı doğrudan çevrilmez; günlük İngilizcede "How much is it?" denir.',
    uretim: {
      yonerge: 'Bir tişörtün fiyatını sor.',
      kabul: [
        'How much is this t-shirt', 'How much is it', 'How much is this',
        'How much does it cost', 'How much is this T-shirt',
      ],
    },
  },
  {
    id: 'k-how-many',
    dil: 'en',
    kelime: 'How many…?',
    tur: 'kalıp',
    seviye: 'A1',
    ingilizceTanim: 'used to ask about the number of things you can count',
    turkceDestek: 'Kaç tane?',
    ipa: '/haʊ ˈmeni/',
    heceler: 'how MAN·y',
    ornekler: [
      { en: 'How many apples do you want?', tr: 'Kaç elma istersin?' },
      { en: 'How many students are there in your class?', tr: 'Sınıfında kaç öğrenci var?' },
    ],
    esdizim: ['How many people?', 'How many times?'],
    esAnlam: [],
    zitAnlam: [],
    aile: ['many'],
    hata: 'Arkasından gelen isim ÇOĞUL olur: "How many apple?" değil "How many apples?"',
    kayit: 'gundelik',
    hatirlatma: 'Türkçede "kaç elma" tekildir; İngilizcede çoğul olmak zorundadır.',
    uretim: {
      yonerge: '"Sınıfında kaç öğrenci var?" sorusunu yaz.',
      kabul: [
        'How many students are there in your class', 'How many students are in your class',
        'How many students are there in your classroom',
      ],
    },
  },
  {
    id: 'k-would-like',
    dil: 'en',
    kelime: 'would like',
    tur: 'kalıp',
    seviye: 'A1',
    ingilizceTanim: 'a polite way to say "want"',
    turkceDestek: 'istemek (nazik biçim)',
    ipa: '/wʊd ˈlaɪk/',
    heceler: 'would LIKE',
    ornekler: [
      { en: 'I would like a cup of tea, please.', tr: 'Bir bardak çay istiyorum lütfen.' },
      { en: 'Would you like some cake?', tr: 'Biraz kek ister misin?' },
    ],
    esdizim: ["I'd like…", 'Would you like…?', "I'd like to…"],
    esAnlam: ['want'],
    zitAnlam: [],
    aile: ['like'],
    hata: '"I want a tea" dilbilgisel olarak doğru ama kaba duyulur. Sipariş verirken ve rica ederken "I would like" kullanılır.',
    kayit: 'resmi',
    hatirlatma: 'Kısaltması "I\'d like"tır ve konuşmada neredeyse her zaman kısaltma kullanılır.',
    uretim: {
      yonerge: 'Bir bardak çay sipariş et (nazik biçimde).',
      kabul: [
        'I would like a cup of tea please', "I'd like a cup of tea please",
        'I would like a cup of tea, please.', "I'd like a tea please",
        'I would like a tea please', "I'd like a cup of tea, please",
      ],
    },
  },
  {
    id: 'k-expensive',
    dil: 'en',
    kelime: 'expensive',
    tur: 'sıfat',
    seviye: 'A1',
    ingilizceTanim: 'costing a lot of money',
    turkceDestek: 'pahalı',
    ipa: '/ɪkˈspensɪv/',
    heceler: 'ex·PEN·sive',
    ornekler: [
      { en: 'This bag is very expensive.', tr: 'Bu çanta çok pahalı.' },
      { en: 'It is too expensive for me.', tr: 'Benim için fazla pahalı.' },
    ],
    esdizim: ['very expensive', 'too expensive'],
    esAnlam: [],
    zitAnlam: ['cheap'],
    aile: ['expense'],
    hata: '"very expensive" = çok pahalı (olumlu bir gözlem). "too expensive" = alamayacak kadar pahalı. İkisi farklıdır.',
    kayit: 'gundelik',
    hatirlatma: 'Vurgu ikinci hecede: eks-PEN-siv.',
    uretim: {
      yonerge: '"Bu çok pahalı." cümlesini yaz.',
      kabul: ['This is very expensive', 'It is very expensive', "It's very expensive", 'This is too expensive'],
    },
  },
  {
    id: 'k-cheap',
    dil: 'en',
    kelime: 'cheap',
    tur: 'sıfat',
    seviye: 'A1',
    ingilizceTanim: 'not costing much money',
    turkceDestek: 'ucuz',
    ipa: '/tʃiːp/',
    heceler: 'cheap (tek hece)',
    ornekler: [
      { en: 'These shoes are quite cheap.', tr: 'Bu ayakkabılar oldukça ucuz.' },
      { en: 'It is cheaper than the other one.', tr: 'Diğerinden daha ucuz.' },
    ],
    esdizim: ['quite cheap', 'a cheap ticket'],
    esAnlam: ['inexpensive'],
    zitAnlam: ['expensive'],
    aile: ['cheaper'],
    hata: '"cheap" bazen "kalitesiz" anlamı da taşır. Yalnız fiyat kastediliyorsa "inexpensive" ya da "good value" daha güvenlidir.',
    kayit: 'gundelik',
    hatirlatma: 'Baştaki "ch" /tʃ/ — Türkçedeki "ç" ile aynı. Bu kolay olanı.',
    uretim: {
      yonerge: '"Bu ayakkabılar ucuz." cümlesini yaz.',
      kabul: ['These shoes are cheap', 'These shoes are quite cheap'],
    },
  },
  {
    id: 'k-buy',
    dil: 'en',
    kelime: 'buy',
    tur: 'fiil',
    seviye: 'A1',
    ingilizceTanim: 'to get something by paying money for it',
    turkceDestek: 'satın almak',
    ipa: '/baɪ/',
    heceler: 'buy (tek hece)',
    ornekler: [
      { en: 'I want to buy a new bag.', tr: 'Yeni bir çanta almak istiyorum.' },
      { en: 'Where do you buy your books?', tr: 'Kitaplarını nereden alıyorsun?' },
    ],
    esdizim: ['buy a ticket', 'buy something for someone'],
    esAnlam: ['purchase'],
    zitAnlam: ['sell'],
    aile: ['bought'],
    hata: 'Geçmiş biçimi düzensizdir: buy → bought. Ayrıca "buy" ile "by" (yanında/ile) aynı okunur ama farklı kelimelerdir.',
    kayit: 'gundelik',
    hatirlatma: '"u" burada okunmaz; kelime "bay" diye okunur.',
    uretim: {
      yonerge: '"Yeni bir çanta almak istiyorum." cümlesini yaz.',
      kabul: ['I want to buy a new bag'],
    },
  },
  {
    id: 'k-shop',
    dil: 'en',
    kelime: 'shop',
    tur: 'isim / fiil',
    seviye: 'A1',
    ingilizceTanim: 'a place where you can buy things',
    turkceDestek: 'dükkân, mağaza',
    ipa: '/ʃɒp/',
    heceler: 'shop (tek hece)',
    ornekler: [
      { en: 'There is a small shop near my house.', tr: 'Evimin yakınında küçük bir dükkân var.' },
      { en: 'The shops open at nine.', tr: 'Dükkânlar dokuzda açılır.' },
    ],
    esdizim: ['go shopping', 'a shoe shop', 'the shops are open'],
    esAnlam: ['store'],
    zitAnlam: [],
    aile: ['shopping', 'shopkeeper'],
    hata: 'Alışverişe gitmek "go shopping"tir; "go to shopping" ya da "make shopping" yanlıştır.',
    kayit: 'gundelik',
    ingUsa: { usa: 'store daha yaygın', ing: 'shop daha yaygın' },
    hatirlatma: 'Türkçedeki "alışveriş yapmak" doğrudan "make shopping"e çevrilmez.',
    uretim: {
      yonerge: '"Cumartesi günleri alışverişe giderim." cümlesini yaz.',
      kabul: ['I go shopping on Saturdays', 'I go shopping on Saturday', 'On Saturdays I go shopping'],
    },
  },
  {
    id: 'k-hungry',
    dil: 'en',
    kelime: 'hungry',
    tur: 'sıfat',
    seviye: 'A1',
    ingilizceTanim: 'wanting to eat',
    turkceDestek: 'aç',
    ipa: '/ˈhʌŋɡri/',
    heceler: 'HUN·gry',
    ornekler: [
      { en: 'I am very hungry.', tr: 'Çok açım.' },
      { en: 'Are you hungry? Let us eat something.', tr: 'Aç mısın? Bir şeyler yiyelim.' },
    ],
    esdizim: ['very hungry', 'get hungry', 'hungry for'],
    esAnlam: [],
    zitAnlam: ['full'],
    aile: ['hunger'],
    hata: 'Açlık be fiiliyle söylenir: "I am hungry." — "I have hunger" ya da "My stomach is hungry" değil.',
    kayit: 'gundelik',
    hatirlatma: 'Türkçede "acıktım" bir fiildir; İngilizcede bir DURUMDUR ve be ile kurulur.',
    uretim: {
      yonerge: '"Çok açım." cümlesini yaz.',
      kabul: ['I am very hungry', "I'm very hungry"],
    },
  },
]
