/**
 * DRKOÇ — KELİME KAYITLARI: A2 / Modül 1 — Geçmişi anlatmak
 *
 * Bu modülün zorluğu kelime değil ZAMAN İŞARETLEYİCİLERİDİR. Türkçede
 * geçmiş tek ekle kurulur ("gittim") ve zaman kelimesi seçmeli kalır.
 * İngilizcede ise zaman işaretleyicisi cümlenin kipini belirler:
 * "yesterday" varsa Past Simple ZORUNLUDUR. Bu yüzden her kayıtta
 * kelimenin hangi zamanla birlikte kullanıldığı yazar.
 */

export const KELIMELER = [
  {
    id: 'k-yesterday',
    dil: 'en',
    kelime: 'yesterday',
    tur: 'zarf',
    seviye: 'A2',
    ingilizceTanim: 'the day before today',
    turkceDestek: 'dün',
    ipa: '/ˈjestədeɪ/',
    heceler: 'yes-ter-day (vurgu ilk hecede)',
    ornekler: [
      { en: 'I watched a film yesterday.', tr: 'Dün bir film izledim.' },
      { en: 'Yesterday was a difficult day.', tr: 'Dün zor bir gündü.' },
    ],
    esdizim: ['yesterday morning', 'yesterday evening', 'the day before yesterday'],
    esAnlam: [],
    zitAnlam: ['tomorrow'],
    aile: [],
    hata: 'Bu kelime cümleyi geçmişe kilitler: "I watch a film yesterday" YANLIŞTIR, fiil "watched" olmalıdır.',
    kayit: 'gundelik',
    hatirlatma: 'Cümlenin başında da sonunda da durabilir; ortada durmaz.',
    uretim: {
      yonerge: '"Dün futbol oynadım." cümlesini yaz.',
      kabul: ['I played football yesterday', 'Yesterday I played football'],
    },
  },
  {
    id: 'k-ago',
    dil: 'en',
    kelime: 'ago',
    tur: 'zarf',
    seviye: 'A2',
    ingilizceTanim: 'used to say how far back in the past something happened',
    turkceDestek: 'önce',
    ipa: '/əˈɡəʊ/',
    heceler: 'a-go (vurgu ikinci hecede)',
    ornekler: [
      { en: 'We moved here two years ago.', tr: 'Buraya iki yıl önce taşındık.' },
      { en: 'She called me ten minutes ago.', tr: 'Beni on dakika önce aradı.' },
    ],
    esdizim: ['a long time ago', 'two days ago', 'a moment ago'],
    esAnlam: [],
    zitAnlam: [],
    aile: [],
    hata: 'Türkçedeki sıra terstir: Türkçe "iki yıl önce", İngilizce "two years ago" — kelime SONA gelir. "Ago two years" YANLIŞTIR.',
    kayit: 'gundelik',
    hatirlatma: 'Daima Past Simple ile kullanılır; "have + ago" birleşimi kurulmaz.',
    uretim: {
      yonerge: '"Üç gün önce hastaydım." cümlesini yaz.',
      kabul: ['I was ill three days ago', 'I was sick three days ago'],
    },
  },
  {
    id: 'k-last-night',
    dil: 'en',
    kelime: 'last night',
    tur: 'zaman ifadesi',
    seviye: 'A2',
    ingilizceTanim: 'the night of yesterday',
    turkceDestek: 'dün gece',
    ipa: '/lɑːst naɪt/',
    heceler: 'last night (iki kelime, iki hece)',
    ornekler: [
      { en: 'I slept badly last night.', tr: 'Dün gece kötü uyudum.' },
      { en: 'Last night we had guests.', tr: 'Dün gece misafirimiz vardı.' },
    ],
    esdizim: ['last week', 'last summer', 'last Monday'],
    esAnlam: [],
    zitAnlam: ['tonight'],
    aile: [],
    hata: '"The last night" denmez; "last" zaman ifadelerinde artikel almaz. "In last night" da YANLIŞTIR, edat kullanılmaz.',
    kayit: 'gundelik',
    hatirlatma: 'Aynı kural bütün "last" ifadelerinde geçerlidir: last week, last year, last month.',
    uretim: {
      yonerge: '"Dün gece geç yattım." cümlesini yaz.',
      kabul: ['I went to bed late last night', 'Last night I went to bed late'],
    },
  },
  {
    id: 'k-then',
    dil: 'en',
    kelime: 'then',
    tur: 'bağlaç / zarf',
    seviye: 'A2',
    ingilizceTanim: 'after that, next in a sequence of events',
    turkceDestek: 'sonra',
    ipa: '/ðen/',
    heceler: 'then (tek hece)',
    ornekler: [
      { en: 'We had breakfast, then we went out.', tr: 'Kahvaltı ettik, sonra dışarı çıktık.' },
      { en: 'First I finished my homework, then I watched TV.', tr: 'Önce ödevimi bitirdim, sonra televizyon izledim.' },
    ],
    esdizim: ['and then', 'first … then', 'back then'],
    esAnlam: ['after that', 'next'],
    zitAnlam: [],
    aile: [],
    hata: '"Than" ile karıştırılır: "than" karşılaştırma yapar (bigger than), "then" sıralama yapar. Tek harf anlamı tamamen değiştirir.',
    kayit: 'gundelik',
    hatirlatma: 'Anlatıda üç adım kalıbı işe yarar: First… Then… Finally…',
    uretim: {
      yonerge: '"Önce ders çalıştım, sonra dışarı çıktım." cümlesini yaz.',
      kabul: ['First I studied, then I went out', 'First I studied then I went out'],
    },
  },
  {
    id: 'k-finally',
    dil: 'en',
    kelime: 'finally',
    tur: 'zarf',
    seviye: 'A2',
    ingilizceTanim: 'as the last thing in a series of events',
    turkceDestek: 'sonunda, en sonunda',
    ipa: '/ˈfaɪnəli/',
    heceler: 'fi-nal-ly (vurgu ilk hecede)',
    ornekler: [
      { en: 'Finally, we found the address.', tr: 'Sonunda adresi bulduk.' },
      { en: 'The bus finally arrived at nine.', tr: 'Otobüs sonunda dokuzda geldi.' },
    ],
    esdizim: ['finally arrive', 'and finally', 'finally decide'],
    esAnlam: ['in the end', 'at last'],
    zitAnlam: ['first'],
    aile: ['final', 'finalise'],
    hata: '"At the end" ile karıştırılır: "at the end" yerin ya da metnin sonunu gösterir (at the end of the street), "finally" olay sırasının sonunu gösterir.',
    kayit: 'gundelik',
    hatirlatma: 'Anlatının son adımını işaretler; kompozisyonda kapanış cümlesini açar.',
    uretim: {
      yonerge: '"Sonunda otobüsü bulduk." cümlesini yaz.',
      kabul: ['Finally we found the bus', 'We finally found the bus'],
    },
  },
  {
    id: 'k-happen',
    dil: 'en',
    kelime: 'happen',
    tur: 'fiil',
    seviye: 'A2',
    ingilizceTanim: 'to take place, especially without being planned',
    turkceDestek: 'olmak, meydana gelmek',
    ipa: '/ˈhæpən/',
    heceler: 'hap-pen (vurgu ilk hecede)',
    ornekler: [
      { en: 'What happened yesterday?', tr: 'Dün ne oldu?' },
      { en: 'The accident happened near the school.', tr: 'Kaza okulun yakınında oldu.' },
    ],
    esdizim: ['what happened', 'happen to someone', 'it happened suddenly'],
    esAnlam: ['occur', 'take place'],
    zitAnlam: [],
    aile: ['happening'],
    hata: 'Edilgen kurulmaz: "It was happened" YANLIŞTIR. Fiil kendisi zaten "olmak" anlamındadır: "It happened".',
    kayit: 'gundelik',
    hatirlatma: 'Soru kalıbı yardımcı fiil almaz: "What happened?" — "What did happen?" doğal değildir.',
    uretim: {
      yonerge: '"Dün ne oldu?" sorusunu yaz.',
      kabul: ['What happened yesterday'],
    },
  },
  {
    id: 'k-decide',
    dil: 'en',
    kelime: 'decide',
    tur: 'fiil',
    seviye: 'A2',
    ingilizceTanim: 'to choose something after thinking about it',
    turkceDestek: 'karar vermek',
    ipa: '/dɪˈsaɪd/',
    heceler: 'de-cide (vurgu ikinci hecede)',
    ornekler: [
      { en: 'We decided to stay at home.', tr: 'Evde kalmaya karar verdik.' },
      { en: 'She decided not to go.', tr: 'Gitmemeye karar verdi.' },
    ],
    esdizim: ['decide to do something', 'make a decision', 'decide against'],
    esAnlam: [],
    zitAnlam: [],
    aile: ['decision', 'decisive'],
    hata: 'Sonrasında "to + fiil" gelir: "We decided to stay" doğrudur; "We decided staying" YANLIŞTIR.',
    kayit: 'gundelik',
    hatirlatma: 'Geçmiş hâli düzenlidir: decide → decided ("dısaydıd" değil, "dısaydid" gibi tek ek).',
    uretim: {
      yonerge: '"Evde kalmaya karar verdik." cümlesini yaz.',
      kabul: ['We decided to stay at home', 'We decided to stay home'],
    },
  },
  {
    id: 'k-journey',
    dil: 'en',
    kelime: 'journey',
    tur: 'isim',
    seviye: 'A2',
    ingilizceTanim: 'an act of travelling from one place to another',
    turkceDestek: 'yolculuk',
    ipa: '/ˈdʒɜːni/',
    heceler: 'jour-ney (vurgu ilk hecede)',
    ornekler: [
      { en: 'The journey took four hours.', tr: 'Yolculuk dört saat sürdü.' },
      { en: 'We had a long journey by bus.', tr: 'Otobüsle uzun bir yolculuk yaptık.' },
    ],
    esdizim: ['a long journey', 'the journey home', 'a safe journey'],
    esAnlam: ['trip'],
    zitAnlam: [],
    aile: [],
    hata: '"Travel" fiildir ve sayılamaz; yolculuğun kendisi "a journey" ya da "a trip"tir. "I had a good travel" YANLIŞTIR.',
    kayit: 'gundelik',
    hatirlatma: 'İngiltere\'de günlük gidiş gelişe "journey", tatil gezisine "trip" denir.',
    uretim: {
      yonerge: '"Yolculuk üç saat sürdü." cümlesini yaz.',
      kabul: ['The journey took three hours'],
    },
  },
  {
    id: 'k-exciting',
    dil: 'en',
    kelime: 'exciting',
    tur: 'sıfat',
    seviye: 'A2',
    ingilizceTanim: 'making you feel happy, interested and full of energy',
    turkceDestek: 'heyecan verici',
    ipa: '/ɪkˈsaɪtɪŋ/',
    heceler: 'ex-ci-ting (vurgu ikinci hecede)',
    ornekler: [
      { en: 'It was an exciting match.', tr: 'Heyecan verici bir maçtı.' },
      { en: 'The trip was really exciting.', tr: 'Gezi gerçekten heyecan vericiydi.' },
    ],
    esdizim: ['an exciting match', 'exciting news', 'sound exciting'],
    esAnlam: ['thrilling'],
    zitAnlam: ['boring'],
    aile: ['excite', 'excited', 'excitement'],
    hata: '"Excited" ile karıştırılır: -ing nesneyi anlatır (an exciting film), -ed kişiyi anlatır (I was excited). "I was exciting" tuhaf bir anlam verir.',
    kayit: 'gundelik',
    hatirlatma: 'Aynı ikilik pek çok sıfatta vardır: boring/bored, tiring/tired, interesting/interested.',
    uretim: {
      yonerge: '"Heyecan verici bir maçtı." cümlesini yaz.',
      kabul: ['It was an exciting match'],
    },
  },
  {
    id: 'k-terrible',
    dil: 'en',
    kelime: 'terrible',
    tur: 'sıfat',
    seviye: 'A2',
    ingilizceTanim: 'very bad or unpleasant',
    turkceDestek: 'berbat, korkunç',
    ipa: '/ˈterəbl/',
    heceler: 'ter-ri-ble (vurgu ilk hecede)',
    ornekler: [
      { en: 'The weather was terrible all week.', tr: 'Hava bütün hafta berbattı.' },
      { en: 'I had a terrible headache.', tr: 'Berbat bir baş ağrım vardı.' },
    ],
    esdizim: ['terrible weather', 'a terrible day', 'feel terrible'],
    esAnlam: ['awful', 'dreadful'],
    zitAnlam: ['wonderful'],
    aile: ['terribly'],
    hata: '"Very terrible" denmez: kelime zaten uç bir derecedir. Güçlendirmek için "absolutely terrible" kullanılır.',
    kayit: 'gundelik',
    hatirlatma: 'Anlatıda olumsuz bir dönüm noktasını işaretlemek için idealdir.',
    uretim: {
      yonerge: '"Hava berbattı." cümlesini yaz.',
      kabul: ['The weather was terrible'],
    },
  },
  {
    id: 'k-suddenly',
    dil: 'en',
    kelime: 'suddenly',
    tur: 'zarf',
    seviye: 'A2',
    ingilizceTanim: 'quickly and without warning',
    turkceDestek: 'aniden, birdenbire',
    ipa: '/ˈsʌdənli/',
    heceler: 'sud-den-ly (vurgu ilk hecede)',
    ornekler: [
      { en: 'Suddenly it started to rain.', tr: 'Birdenbire yağmur başladı.' },
      { en: 'The car suddenly stopped.', tr: 'Araba aniden durdu.' },
    ],
    esdizim: ['suddenly stop', 'suddenly appear', 'all of a sudden'],
    esAnlam: ['all of a sudden'],
    zitAnlam: ['slowly'],
    aile: ['sudden'],
    hata: 'Cümlenin başında ya da fiilin önünde durur; sonda durması doğal değildir.',
    kayit: 'gundelik',
    hatirlatma: 'Hikâye anlatımının dönüm noktası kelimesidir; okuyucunun dikkatini toplar.',
    uretim: {
      yonerge: '"Birdenbire yağmur başladı." cümlesini yaz.',
      kabul: ['Suddenly it started to rain', 'Suddenly it began to rain'],
    },
  },
  {
    id: 'k-remember',
    dil: 'en',
    kelime: 'remember',
    tur: 'fiil',
    seviye: 'A2',
    ingilizceTanim: 'to keep something in your mind or bring it back to your mind',
    turkceDestek: 'hatırlamak',
    ipa: '/rɪˈmembə/',
    heceler: 're-mem-ber (vurgu ikinci hecede)',
    ornekler: [
      { en: 'I remember that day very well.', tr: 'O günü çok iyi hatırlıyorum.' },
      { en: 'I do not remember his name.', tr: 'Adını hatırlamıyorum.' },
    ],
    esdizim: ['remember doing something', 'remember to do something', 'if I remember correctly'],
    esAnlam: [],
    zitAnlam: ['forget'],
    aile: ['memory'],
    hata: 'İki yapı iki farklı anlam verir: "remember doing" geçmişte yaptığını hatırlamak, "remember to do" yapmayı unutmamaktır.',
    kayit: 'gundelik',
    hatirlatma: 'Çocukluk anlatırken en çok kullanılan fiildir: "I remember playing in the garden."',
    uretim: {
      yonerge: '"O günü çok iyi hatırlıyorum." cümlesini yaz.',
      kabul: ['I remember that day very well'],
    },
  },
]

export default KELIMELER
