/**
 * DRKOÇ — ALMANCA SEVİYE TESPİT MADDE BANKASI
 * ==================================================================
 *
 * Sınav motoru (lib/almanca/seviyeTespit.js) bu bankadan soru seçer.
 * Her madde iki etiket taşır:
 *   seviye  → maddenin zorluk basamağı (Pre-A1 … C1)
 *   beceri  → hangi beceriyi ölçtüğü
 *
 * Banka bilinçli olarak yalnız çoktan seçmeli gramer sorusundan oluşmaz.
 * Ölçülenler: kelime, bağlamda kelime, dil bilgisi, cümle dizimi, okuduğunu
 * anlama, dinlediğini anlama, telaffuz farkındalığı ve Almanca düşünme
 * (Türkçeden birebir çeviri eğilimi).
 *
 * DİNLEME maddeleri yalnız cihazda Almanca ses varsa sorulur; yoksa
 * motor bunları eler ve dinleme "ölçülemedi" olarak raporlanır.
 *
 * Her seviyede en az bir "dusunme" maddesi vardır: doğru cevabın
 * dilbilgisiyle değil, Türkçe düşünme alışkanlığıyla ilgili olduğu
 * maddeler. Bunlar sonuç ekranındaki "çeviri alışkanlığı" bölümünü besler.
 *
 * ARTİKEL ÖLÇÜMÜ: Almancaya özgü olarak, her seviyede artikel/hâl
 * hâkimiyetini ölçen en az bir madde vardır. Artikeli bilmeyen öğrenci
 * hiçbir seviyede "sorunsuz" sayılamaz.
 */

export const MADDELER = [
  /* ---------------------------- Pre-A1 ---------------------------- */
  {
    id: 'st-p1',
    seviye: 'Pre-A1',
    beceri: 'kelime',
    tur: 'coktan-secmeli',
    yonerge: 'Doğru karşılığı seç.',
    soru: '"das Buch" ne demek?',
    secenekler: [
      { id: 'a', metin: 'kitap' },
      { id: 'b', metin: 'masa' },
      { id: 'c', metin: 'kapı' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-p2',
    seviye: 'Pre-A1',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Boşluğa hangisi gelir?',
    soru: 'Ich ____ Schüler.',
    secenekler: [
      { id: 'a', metin: 'bin' },
      { id: 'b', metin: 'ist' },
      { id: 'c', metin: 'bist' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-p3',
    seviye: 'Pre-A1',
    beceri: 'dizim',
    tur: 'siralama',
    yonerge: 'Kelimeleri sıraya diz.',
    parcalar: ['heiße', 'Ich', 'Ali'],
    dogruSira: [1, 0, 2],
  },
  {
    id: 'st-p4',
    seviye: 'Pre-A1',
    beceri: 'okuma',
    tur: 'coktan-secmeli',
    yonerge: 'Oku ve cevapla.',
    soru: '"Hallo! Ich bin Sam. Ich bin zehn Jahre alt." — Sam kaç yaşında?',
    secenekler: [
      { id: 'a', metin: '10' },
      { id: 'b', metin: '2' },
      { id: 'c', metin: 'Belli değil' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-p5',
    seviye: 'Pre-A1',
    beceri: 'telaffuz',
    tur: 'coktan-secmeli',
    yonerge: 'Hangi kelimede "z" harfi "ts" okunur?',
    soru: 'Almancada "z" harfi nasıl okunur?',
    secenekler: [
      { id: 'a', metin: 'Her zaman "ts" (Zeit → "tsayt")' },
      { id: 'b', metin: 'Her zaman "z" (Zeit → "zayt")' },
      { id: 'c', metin: 'Kelimeye göre değişir' },
    ],
    dogruId: 'a',
    aciklama: 'Almancada "z" istisnasız "ts" okunur. Bu, en yüksek getirili telaffuz kurallarından biridir.',
  },
  {
    id: 'st-p6',
    seviye: 'Pre-A1',
    beceri: 'dinleme',
    tur: 'dinle-sec',
    yonerge: 'Dinle ve duyduğun kelimeyi seç.',
    seslendir: 'vier',
    secenekler: [
      { id: 'a', metin: 'vier (dört)' },
      { id: 'b', metin: 'wir (biz)' },
      { id: 'c', metin: 'Bier (bira)' },
    ],
    dogruId: 'a',
  },

  /* ------------------------------ A1 ------------------------------ */
  {
    id: 'st-a1-1',
    seviye: 'A1',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Boşluğa hangisi gelir?',
    soru: 'Ich habe ____ Bruder.',
    secenekler: [
      { id: 'a', metin: 'einen' },
      { id: 'b', metin: 'ein' },
      { id: 'c', metin: 'eine' },
    ],
    dogruId: 'a',
    aciklama: '"Bruder" eril (der) olduğu için nesne konumunda "einen" olur. Akkusativ yalnız eril isimlerde biçim değiştirir.',
  },
  {
    id: 'st-a1-2',
    seviye: 'A1',
    beceri: 'dizim',
    tur: 'coktan-secmeli',
    yonerge: 'Hangisi doğru?',
    soru: 'Bugün okula gidiyorum.',
    secenekler: [
      { id: 'a', metin: 'Heute gehe ich zur Schule.' },
      { id: 'b', metin: 'Heute ich gehe zur Schule.' },
      { id: 'c', metin: 'Ich heute gehe zur Schule.' },
    ],
    dogruId: 'a',
    aciklama: 'Ana cümlede çekimli fiil her zaman İKİNCİ sıradadır. Cümle zaman ifadesiyle başlayınca özne fiilin arkasına geçer.',
  },
  {
    id: 'st-a1-3',
    seviye: 'A1',
    beceri: 'kelime',
    tur: 'coktan-secmeli',
    yonerge: 'Hangi artikel doğru?',
    soru: '____ Mädchen heißt Zeynep.',
    secenekler: [
      { id: 'a', metin: 'Das' },
      { id: 'b', metin: 'Die' },
      { id: 'c', metin: 'Der' },
    ],
    dogruId: 'a',
    aciklama: '-chen ile biten her kelime "das" alır — anlamı kız çocuğu olsa bile. Almancada cinsiyet anlamla değil kelimeyle gelir.',
  },
  {
    id: 'st-a1-4',
    seviye: 'A1',
    beceri: 'gramer',
    tur: 'bosluk',
    yonerge: 'Boşluğu doldur (ayrılabilen fiile dikkat).',
    parcalar: ['Ich ', { bosluk: 0 }, ' um sieben Uhr ', { bosluk: 1 }, '.'],
    cevaplar: [
      { kabul: ['stehe'], ipucu: 'aufstehen fiilinin çekimli kısmı' },
      { kabul: ['auf'], ipucu: 'ön ek nereye gider?' },
    ],
    aciklama: 'Ayrılabilen fiilde çekimli kısım ikinci sırada kalır, ön ek cümlenin sonuna atılır.',
  },
  {
    id: 'st-a1-5',
    seviye: 'A1',
    beceri: 'okuma',
    tur: 'coktan-secmeli',
    yonerge: 'Oku ve cevapla.',
    soru: '"Ich heiße Lena. Ich wohne in Wien, aber ich komme aus Hamburg." — Lena nerede yaşıyor?',
    secenekler: [
      { id: 'a', metin: 'Viyana' },
      { id: 'b', metin: 'Hamburg' },
      { id: 'c', metin: 'Belli değil' },
    ],
    dogruId: 'a',
    aciklama: '"wohnen" oturulan yeri, "kommen aus" ise nereli olduğunu söyler. İki bilgi karıştırılmamalı.',
  },
  {
    id: 'st-a1-6',
    seviye: 'A1',
    beceri: 'dusunme',
    tur: 'coktan-secmeli',
    yonerge: 'Hangisi doğal Almanca?',
    soru: '"On beş yaşındayım." nasıl söylenir?',
    secenekler: [
      { id: 'a', metin: 'Ich bin fünfzehn Jahre alt.' },
      { id: 'b', metin: 'Ich habe fünfzehn Jahre.' },
      { id: 'c', metin: 'Mein Alter ist fünfzehn.' },
    ],
    dogruId: 'a',
    secenekNotu: {
      b: 'Yaş Almancada "haben" ile söylenmez; bu kalıp Fransızca ve İtalyancadan gelir.',
      c: 'Dilbilgisi doğru ama kimse böyle konuşmaz.',
    },
  },
  {
    id: 'st-a1-7',
    seviye: 'A1',
    beceri: 'dinleme',
    tur: 'dinle-yaz',
    yonerge: 'Dinle ve duyduğun cümleyi yaz.',
    seslendir: 'Ich komme aus der Türkei.',
    kabul: ['Ich komme aus der Türkei', 'Ich komme aus der Tuerkei'],
  },
  {
    id: 'st-a1-8',
    seviye: 'A1',
    beceri: 'telaffuz',
    tur: 'coktan-secmeli',
    yonerge: 'Hangisi doğru okunuş?',
    soru: '"Vater" kelimesi nasıl okunur?',
    secenekler: [
      { id: 'a', metin: '"faata" — v harfi f okunur' },
      { id: 'b', metin: '"vater" — yazıldığı gibi' },
      { id: 'c', metin: '"vaata" — v harfi v okunur' },
    ],
    dogruId: 'a',
    aciklama: 'Almanca kökenli kelimelerde "v" harfi "f" okunur (Vater, viel, vier). "w" harfi ise "v" okunur.',
  },

  /* ------------------------------ A2 ------------------------------ */
  {
    id: 'st-a2-1',
    seviye: 'A2',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Boşluğa hangisi gelir?',
    soru: 'Gestern ____ ich ins Kino gegangen.',
    secenekler: [
      { id: 'a', metin: 'bin' },
      { id: 'b', metin: 'habe' },
      { id: 'c', metin: 'war' },
    ],
    dogruId: 'a',
    aciklama: 'Yer değiştirme bildiren fiiller (gehen, kommen, fahren) Perfekt\'i "sein" ile kurar.',
  },
  {
    id: 'st-a2-2',
    seviye: 'A2',
    beceri: 'dizim',
    tur: 'siralama',
    yonerge: 'Cümleyi doğru sıraya diz.',
    parcalar: ['zu Hause', 'Ich', 'weil', 'bleibe', 'bin', 'ich', 'müde'],
    dogruSira: [1, 3, 0, 2, 5, 6, 4],
    aciklama: 'Ana cümlede fiil ikinci (bleibe), yan cümlede sondadır (bin). Almancanın iki ayrı sırası aynı cümlede görünür.',
  },
  {
    id: 'st-a2-3',
    seviye: 'A2',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Boşluğa hangisi gelir?',
    soru: 'Ich helfe ____ bei den Hausaufgaben.',
    secenekler: [
      { id: 'a', metin: 'dir' },
      { id: 'b', metin: 'dich' },
      { id: 'c', metin: 'du' },
    ],
    dogruId: 'a',
    aciklama: '"helfen" Dativ ister. Türkçedeki "sana yardım" sezgisi doğrudur; çeviri sırasında nesne "-i" hâline kayıyor.',
  },
  {
    id: 'st-a2-4',
    seviye: 'A2',
    beceri: 'kelime',
    tur: 'coktan-secmeli',
    yonerge: 'Hangi fiil doğru?',
    soru: 'Ich ____ eine Frage.',
    secenekler: [
      { id: 'a', metin: 'stelle' },
      { id: 'b', metin: 'mache' },
      { id: 'c', metin: 'gebe' },
    ],
    dogruId: 'a',
    aciklama: 'Almancada soru "stellen" ile sorulur. Kelime doğru olsa da eşdizim yanlışsa cümle yapay durur.',
  },
  {
    id: 'st-a2-5',
    seviye: 'A2',
    beceri: 'okuma',
    tur: 'coktan-secmeli',
    yonerge: 'Oku ve cevapla.',
    soru: '"Der Zug fährt um 14:20 ab. Bitte seien Sie zehn Minuten früher am Gleis." — Peronda saat kaçta olunmalı?',
    secenekler: [
      { id: 'a', metin: '14:10' },
      { id: 'b', metin: '14:20' },
      { id: 'c', metin: '14:30' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-a2-6',
    seviye: 'A2',
    beceri: 'dusunme',
    tur: 'dogal-secim',
    yonerge: 'Hangisi doğal Almanca?',
    baglam: 'Kitap okumayı sevdiğini söylüyorsun.',
    secenekler: [
      { id: 'a', metin: 'Ich liebe Bücher zu lesen.', dogal: false, neden: 'Türkçedeki "okumayı severim" kalıbının birebir aktarımı. Almancada bu yapı kurulmaz.' },
      { id: 'b', metin: 'Ich lese gern Bücher.', dogal: true, neden: 'Eylemi sevmek, fiile eklenen "gern" ile anlatılır.' },
    ],
  },
  {
    id: 'st-a2-7',
    seviye: 'A2',
    beceri: 'gramer',
    tur: 'bosluk',
    yonerge: 'Boşluğu doldur.',
    parcalar: ['Das Buch liegt auf ', { bosluk: 0 }, ' Tisch.'],
    cevaplar: [{ kabul: ['dem'], ipucu: 'Duruş bildiriyor — hangi hâl?' }],
    aciklama: '"Wo?" sorusunun cevabı Dativ\'dir: auf dem Tisch. Hareket olsaydı "auf den Tisch" olurdu.',
  },
  {
    id: 'st-a2-8',
    seviye: 'A2',
    beceri: 'dinleme',
    tur: 'dinle-sec',
    yonerge: 'Dinle ve doğru cevabı seç.',
    seslendir: 'Der Termin ist am Dienstag um halb neun.',
    secenekler: [
      { id: 'a', metin: 'Salı, 08:30' },
      { id: 'b', metin: 'Salı, 09:30' },
      { id: 'c', metin: 'Perşembe, 08:30' },
    ],
    dogruId: 'a',
    aciklama: '"halb neun" = dokuza yarım kala, yani 8:30. Almanca saat söyleyişi ileriye bakar; Türkçedeki "sekiz buçuk" mantığından farklıdır.',
  },
  {
    id: 'st-a2-9',
    seviye: 'A2',
    beceri: 'dizim',
    tur: 'hata-bul',
    yonerge: 'Cümledeki hatayı bul ve düzelt.',
    cumle: 'Ich kann sprechen gut Deutsch.',
    hataliParca: 'sprechen gut Deutsch',
    dogruParca: 'gut Deutsch sprechen',
    kabul: ['Ich kann gut Deutsch sprechen'],
    aciklama: 'Modal fiil ikinci sırada, asıl fiil MASTAR hâlinde cümlenin sonundadır.',
  },
  {
    id: 'st-a2-10',
    seviye: 'A2',
    beceri: 'telaffuz',
    tur: 'coktan-secmeli',
    yonerge: 'Hangi çiftte iki farklı "ch" sesi vardır?',
    soru: 'Aşağıdaki çiftlerden hangisinde "ch" iki ayrı biçimde okunur?',
    secenekler: [
      { id: 'a', metin: 'Buch – Bücher' },
      { id: 'b', metin: 'ich – nicht' },
      { id: 'c', metin: 'machen – Nacht' },
    ],
    dogruId: 'a',
    aciklama: 'a, o, u, au\'dan sonra sert /x/; e, i, ä, ö, ü\'den sonra yumuşak /ç/. Buch sert, Bücher yumuşaktır.',
  },

  /* ------------------------------ B1 ------------------------------ */
  {
    id: 'st-b1-1',
    seviye: 'B1',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Boşluğa hangisi gelir?',
    soru: 'Wenn ich Zeit ____, würde ich mehr lesen.',
    secenekler: [
      { id: 'a', metin: 'hätte' },
      { id: 'b', metin: 'habe' },
      { id: 'c', metin: 'hatte' },
    ],
    dogruId: 'a',
    aciklama: 'Gerçek dışı koşul Konjunktiv II ister: hätte. "hatte" geçmiş zamandır, "habe" ise şimdiki.',
  },
  {
    id: 'st-b1-2',
    seviye: 'B1',
    beceri: 'dizim',
    tur: 'coktan-secmeli',
    yonerge: 'Hangisi doğru?',
    soru: 'Sınav zor olmasına rağmen geçtim.',
    secenekler: [
      { id: 'a', metin: 'Obwohl die Prüfung schwer war, habe ich bestanden.' },
      { id: 'b', metin: 'Obwohl die Prüfung war schwer, ich habe bestanden.' },
      { id: 'c', metin: 'Obwohl war die Prüfung schwer, habe ich bestanden.' },
    ],
    dogruId: 'a',
    aciklama: 'Yan cümle başta olduğunda ana cümlenin fiili hemen virgülden sonra gelir — yan cümlenin tamamı "birinci sıra" sayılır.',
  },
  {
    id: 'st-b1-3',
    seviye: 'B1',
    beceri: 'kelime',
    tur: 'coktan-secmeli',
    yonerge: 'Hangi kelime doğru?',
    soru: 'Ich ____ ihn seit der Grundschule.',
    secenekler: [
      { id: 'a', metin: 'kenne' },
      { id: 'b', metin: 'weiß' },
      { id: 'c', metin: 'erkenne' },
    ],
    dogruId: 'a',
    aciklama: 'Kişiyi ve yeri tanımak "kennen", bilgiyi bilmek "wissen"dir. Türkçede ikisi de "bilmek/tanımak" ile karşılanır.',
  },
  {
    id: 'st-b1-4',
    seviye: 'B1',
    beceri: 'okuma',
    tur: 'coktan-secmeli',
    yonerge: 'Metni oku ve yazarın tutumunu seç.',
    soru: '"Die neue Regelung ist gut gemeint, aber sie löst das eigentliche Problem nicht." — Yazar ne düşünüyor?',
    secenekler: [
      { id: 'a', metin: 'Düzenlemenin niyeti iyi ama yetersiz.' },
      { id: 'b', metin: 'Düzenleme tamamen gereksiz.' },
      { id: 'c', metin: 'Düzenleme sorunu çözdü.' },
    ],
    dogruId: 'a',
    aciklama: '"gut gemeint, aber…" kalıbı ölçülü bir eleştiridir: niyet olumlu, sonuç yetersiz.',
  },
  {
    id: 'st-b1-5',
    seviye: 'B1',
    beceri: 'gramer',
    tur: 'bosluk',
    yonerge: 'Boşluğu doldur.',
    parcalar: ['Ich freue mich ', { bosluk: 0 }, ' die Ferien.'],
    cevaplar: [{ kabul: ['auf'], ipucu: 'Gelecekteki bir şeyi dört gözle bekliyorsun.' }],
    aciklama: '"sich freuen auf" = ileride olacak bir şeye sevinmek; "sich freuen über" = olmuş bir şeye sevinmek.',
  },
  {
    id: 'st-b1-6',
    seviye: 'B1',
    beceri: 'dusunme',
    tur: 'dogal-secim',
    yonerge: 'Hangisi doğal Almanca?',
    baglam: 'Bir öneriye katıldığını söylüyorsun.',
    secenekler: [
      { id: 'a', metin: 'Ich bin einverstanden.', dogal: true, neden: 'Almancanın kendi kalıbı; hem gündelik hem resmî bağlamda kullanılır.' },
      { id: 'b', metin: 'Ich bin zustimmen.', dogal: false, neden: '"zustimmen" bir fiildir, "sein" ile birleşmez: "Ich stimme zu" olmalıydı.' },
    ],
  },
  {
    id: 'st-b1-7',
    seviye: 'B1',
    beceri: 'dinleme',
    tur: 'dinle-sec',
    yonerge: 'Dinle ve konuşmacının niyetini seç.',
    seslendir: 'Könnten Sie das vielleicht noch einmal erklären? Ich bin mir nicht ganz sicher.',
    secenekler: [
      { id: 'a', metin: 'Nazikçe tekrar istiyor.' },
      { id: 'b', metin: 'Anlatımı eleştiriyor.' },
      { id: 'c', metin: 'Konuyu değiştirmek istiyor.' },
    ],
    dogruId: 'a',
    aciklama: '"Könnten Sie… vielleicht…" Almancadaki en nazik rica katmanıdır; iki yumuşatıcı üst üste kullanılmıştır.',
  },
  {
    id: 'st-b1-8',
    seviye: 'B1',
    beceri: 'dizim',
    tur: 'hata-bul',
    yonerge: 'Cümledeki hatayı bul ve düzelt.',
    cumle: 'Ich habe gestern meinen Freund getroffen und wir sind ins Kino gegangen, weil wir hatten Zeit.',
    hataliParca: 'weil wir hatten Zeit',
    dogruParca: 'weil wir Zeit hatten',
    kabul: [
      'weil wir Zeit hatten',
      'Ich habe gestern meinen Freund getroffen und wir sind ins Kino gegangen, weil wir Zeit hatten',
    ],
    aciklama: 'weil yan cümlesinde çekimli fiil SONA gider. Cümlenin uzunluğu bu kuralı değiştirmez.',
  },
  {
    id: 'st-b1-9',
    seviye: 'B1',
    beceri: 'kelime',
    tur: 'tanim-kelime',
    yonerge: 'Tanıma uyan kelimeyi yaz.',
    tanim: 'Ein Gefühl, wenn man etwas nicht kennt und es kennenlernen möchte.',
    ilkHarf: 'N',
    kabul: ['Neugier', 'die Neugier', 'neugierig'],
    ornekCevap: 'die Neugier (merak)',
  },

  /* ------------------------------ B2 ------------------------------ */
  {
    id: 'st-b2-1',
    seviye: 'B2',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Boşluğa hangisi gelir?',
    soru: 'Das Problem, ____ wir gesprochen haben, ist gelöst.',
    secenekler: [
      { id: 'a', metin: 'über das' },
      { id: 'b', metin: 'das' },
      { id: 'c', metin: 'dem' },
    ],
    dogruId: 'a',
    aciklama: '"sprechen über" edatı ilgi cümlesine taşınır: über das. Edat, fiilin istediği hâli belirler.',
  },
  {
    id: 'st-b2-2',
    seviye: 'B2',
    beceri: 'kelime',
    tur: 'coktan-secmeli',
    yonerge: 'Hangisi doğal eşdizim?',
    soru: 'eine Entscheidung ____',
    secenekler: [
      { id: 'a', metin: 'treffen' },
      { id: 'b', metin: 'machen' },
      { id: 'c', metin: 'nehmen' },
    ],
    dogruId: 'a',
    aciklama: 'Almancada karar "treffen" ile alınır. B2 seviyesinin ayırt edici becerisi budur: doğru kelime + doğru eşdizim.',
  },
  {
    id: 'st-b2-3',
    seviye: 'B2',
    beceri: 'okuma',
    tur: 'coktan-secmeli',
    yonerge: 'Cümlenin örtük anlamını seç.',
    soru: '"Nun, das ist sicherlich ein interessanter Ansatz." — Konuşmacı ne ima ediyor?',
    secenekler: [
      { id: 'a', metin: 'İkna olmamış; nazikçe mesafe koyuyor.' },
      { id: 'b', metin: 'Fikri çok beğenmiş.' },
      { id: 'c', metin: 'Fikri hiç anlamamış.' },
    ],
    dogruId: 'a',
    aciklama: '"Nun…" ile başlayan ve "interessant" ile devam eden değerlendirme, Almancada çoğu zaman kibar bir çekincedir.',
  },
  {
    id: 'st-b2-4',
    seviye: 'B2',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Hangisi doğru edilgen biçim?',
    soru: 'Man hat das Haus 1920 gebaut. → ?',
    secenekler: [
      { id: 'a', metin: 'Das Haus wurde 1920 gebaut.' },
      { id: 'b', metin: 'Das Haus ist 1920 bauen.' },
      { id: 'c', metin: 'Das Haus hat 1920 gebaut.' },
    ],
    dogruId: 'a',
    aciklama: 'Geçmişte edilgen "wurde + Partizip II" ile kurulur.',
  },
  {
    id: 'st-b2-5',
    seviye: 'B2',
    beceri: 'dusunme',
    tur: 'dogal-secim',
    yonerge: 'Hangisi daha doğal?',
    baglam: 'Bir konuda deneyimin olduğunu söylüyorsun.',
    secenekler: [
      { id: 'a', metin: 'Ich habe damit Erfahrung gemacht.', dogal: false, neden: '"Erfahrung machen" belirli bir olayı yaşamak demektir; genel deneyim için kullanılmaz.' },
      { id: 'b', metin: 'Ich habe damit Erfahrung.', dogal: true, neden: 'Genel deneyim "Erfahrung haben" ile söylenir.' },
    ],
  },
  {
    id: 'st-b2-6',
    seviye: 'B2',
    beceri: 'dinleme',
    tur: 'dinle-sec',
    yonerge: 'Dinle ve konuşmacının tutumunu seç.',
    seslendir: 'Grundsätzlich stimme ich Ihnen zu, allerdings sehe ich ein Problem bei der Umsetzung.',
    secenekler: [
      { id: 'a', metin: 'Genel olarak katılıyor ama uygulamada çekincesi var.' },
      { id: 'b', metin: 'Tamamen karşı çıkıyor.' },
      { id: 'c', metin: 'Kararsız, fikri yok.' },
    ],
    dogruId: 'a',
    aciklama: '"Grundsätzlich… allerdings…" yapısı Almancadaki tipik ölçülü itiraz kalıbıdır.',
  },

  /* ------------------------------ C1 ------------------------------ */
  {
    id: 'st-c1-1',
    seviye: 'C1',
    beceri: 'kelime',
    tur: 'coktan-secmeli',
    yonerge: 'Hangisi bağlama uygun?',
    soru: 'Die Ergebnisse sind mit Vorsicht zu ____.',
    secenekler: [
      { id: 'a', metin: 'genießen' },
      { id: 'b', metin: 'essen' },
      { id: 'c', metin: 'nehmen' },
    ],
    dogruId: 'a',
    aciklama: '"mit Vorsicht zu genießen" yerleşik bir deyimdir: "ihtiyatla karşılanmalı". Kelime kelime çevrilirse anlamsız görünür.',
  },
  {
    id: 'st-c1-2',
    seviye: 'C1',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Hangisi doğru?',
    soru: 'Er behauptet, er ____ nichts davon gewusst.',
    secenekler: [
      { id: 'a', metin: 'habe' },
      { id: 'b', metin: 'hat' },
      { id: 'c', metin: 'hätte' },
    ],
    dogruId: 'a',
    aciklama: 'Dolaylı anlatımda Konjunktiv I kullanılır: "er habe". Bu, yazarın bilgiye mesafe koyduğunu gösterir ve haber dilinde standarttır.',
  },
  {
    id: 'st-c1-3',
    seviye: 'C1',
    beceri: 'okuma',
    tur: 'coktan-secmeli',
    yonerge: 'Yazarın üslubunu seç.',
    soru: '"Es wäre wohl übertrieben zu behaupten, dass die Maßnahme gescheitert sei." — Yazarın tutumu?',
    secenekler: [
      { id: 'a', metin: 'Başarısızlık iddiasını fazla bulur; ölçülü bir savunma yapar.' },
      { id: 'b', metin: 'Önlemin başarısız olduğunu açıkça söyler.' },
      { id: 'c', metin: 'Önlemi tamamen över.' },
    ],
    dogruId: 'a',
    aciklama: '"Es wäre übertrieben zu behaupten" kalıbı, bir iddiayı reddetmeden yumuşatmanın akademik yoludur.',
  },
  {
    id: 'st-c1-4',
    seviye: 'C1',
    beceri: 'dizim',
    tur: 'coktan-secmeli',
    yonerge: 'Hangisi daha akıcı?',
    soru: 'Aynı bilgiyi hangi cümle daha iyi taşır?',
    secenekler: [
      { id: 'a', metin: 'Nach eingehender Prüfung wurde der Antrag genehmigt.' },
      { id: 'b', metin: 'Man hat den Antrag geprüft und dann hat man ihn genehmigt.' },
      { id: 'c', metin: 'Der Antrag, den man geprüft hat, ist genehmigt worden von jemandem.' },
    ],
    dogruId: 'a',
    aciklama: 'Resmî yazıda nominal üslup ve edilgen yapı tercih edilir; C1 bu üslup seçimini bilinçli yapabilmektir.',
  },
  {
    id: 'st-c1-5',
    seviye: 'C1',
    beceri: 'dusunme',
    tur: 'dogal-secim',
    yonerge: 'Hangisi daha doğal?',
    baglam: 'Bir toplantıda söz almak istiyorsun.',
    secenekler: [
      { id: 'a', metin: 'Darf ich kurz einhaken?', dogal: true, neden: 'Almancada toplantıda söz almanın yerleşik ve nazik yoludur.' },
      { id: 'b', metin: 'Kann ich ein Wort nehmen?', dogal: false, neden: 'Kelime kelime çeviri izi taşır; Almancada böyle bir kalıp yoktur.' },
    ],
  },
  {
    id: 'st-c1-6',
    seviye: 'C1',
    beceri: 'kelime',
    tur: 'tanim-kelime',
    yonerge: 'Tanıma uyan kelimeyi yaz.',
    tanim: 'Die Fähigkeit, sich in die Gefühle anderer Menschen hineinzuversetzen.',
    ilkHarf: 'E',
    kabul: ['Empathie', 'die Empathie', 'Einfühlungsvermögen', 'das Einfühlungsvermögen'],
    ornekCevap: 'die Empathie / das Einfühlungsvermögen',
  },
]

/**
 * YAZMA GÖREVİ — sınavın son adımı.
 *
 * Otomatik puanlanmaz; ölçülebilir göstergelere bakılır (uzunluk, aranan
 * yapılar, bağlaç kullanımı, Türkçe düşünme izleri). Geri kalanı öğrenciye
 * kendi kontrol listesi olarak verilir. Sahte bir "9/10" üretilmez.
 */
export const YAZMA_GOREVI = {
  id: 'st-yazma',
  seviye: 'A2',
  beceri: 'yazma',
  tur: 'yazma',
  yonerge: 'Son adım: kendini kısaca tanıt. Ne kadar yazabiliyorsan o kadar yaz — kısa yazman sonucu bozmaz, yalnız daha az bilgi verir.',
  gorev: 'Schreib etwas über dich auf Deutsch: Wer bist du, wo wohnst du, was machst du, und warum lernst du Deutsch?',
  ornekMetin: null,
  kaliplar: [],
  asamalar: [
    { ad: 'Yaz', aciklama: 'Aklına geldiği gibi yaz. Bu bir sınav değil, ölçüm.' },
  ],
  olcut: [
    'Kendimi tanıttım (Ich heiße… / Ich bin…).',
    'Nerede yaşadığımı yazdım.',
    'Ne yaptığımı (okul/iş) yazdım.',
    'Neden Almanca öğrendiğimi yazdım.',
    'İsimleri büyük harfle yazdım.',
  ],
  enAzKelime: 25,
  aranan: [
    { etiket: 'sein fiili', desen: /\b(bin|bist|ist|sind|seid)\b/i },
    { etiket: 'Präsens fiili', desen: /\b(wohne|lerne|gehe|mache|arbeite|komme|spiele|habe)\b/i },
    { etiket: 'bağlaç (und/aber/weil)', desen: /\b(und|aber|weil|denn|oder)\b/i },
    { etiket: 'geçmiş ya da gelecek', desen: /\b(war|hatte|habe \w+t|bin \w+en|werde|möchte|moechte)\b/i },
    { etiket: 'amaç bildirme (um … zu / weil)', desen: /\b(um .* zu \w+|weil ich)\b/i },
  ],
}
