/**
 * Adaptörlerin ürün koduna bağlanmadan doğrulanabildiği sentetik örnekler.
 * Kimlikler gerçek kullanıcıya ait değildir; ham soru/metin/görsel içermez.
 */
export const SOURCE_ADAPTER_FIXTURES = Object.freeze([
  {
    id: 'daily-log-tyt-topic',
    matrixId: 'M03',
    adapter: 'adaptDailyLog',
    input: { id: 'daily-fixture-1', exam_type: 'TYT', subject: 'Matematik', topic: 'Temel Kavramlar', study_date: '2026-09-01', correct: 8, incorrect: 2, empty: 0, duration_minutes: 40, notes: 'var' },
    context: { sourceRevision: 'v1', opaqueLocatorToken: 'dailyRef01' },
  },
  {
    id: 'mock-exam-subject',
    matrixId: 'M04',
    adapter: 'adaptMockExamSubject',
    input: { id: 'mock-subject-1', exam_type: 'LGS', subject: 'Matematik', exam_date: '2026-09-01', correct: 15, incorrect: 3, empty: 2, duration_minutes: 45, exam_name: 'Sentetik deneme' },
    context: { sourceRevision: 'v1', opaqueLocatorToken: 'mockRef001' },
  },
  {
    id: 'branch-exam',
    matrixId: 'M05',
    adapter: 'adaptBranchExam',
    input: { id: 'branch-fixture-1', exam_type: 'TYT', topic: 'Matematik - Problemler', exam_date: '2026-09-01', correct: 12, incorrect: 4, empty: 4, duration_minutes: 35 },
    context: { sourceRevision: 'v1', opaqueLocatorToken: 'branchRef1' },
  },
  {
    id: 'homework-snapshot',
    matrixId: 'M06',
    adapter: 'adaptHomework',
    input: { id: 'homework-fixture-1', status: 'completed', due_date: '2026-09-02', lesson_session_id: null },
    context: { sourceRevision: 'v2', asOf: '2026-09-02T12:00:00.000Z', opaqueLocatorToken: 'homework01' },
  },
  {
    id: 'teacher-feedback',
    matrixId: 'M07',
    adapter: 'adaptTeacherQuestionFeedback',
    input: { id: 'question-fixture-1', exam_type: 'TYT', subject: 'Matematik', topic: 'Problemler', status: 'answered', teacher_reply: 'var', image_url: 'var' },
    context: { sourceRevision: 'v2', asOf: '2026-09-02T12:00:00.000Z', opaqueLocatorToken: 'question01' },
  },
  {
    id: 'coach-action',
    matrixId: 'M09',
    adapter: 'adaptCoachAction',
    input: { id: 'task-fixture-1', semantic_event_type: 'study_task_status_changed', status: 'completed', exam_type: 'TYT', subject: 'Matematik', topic: 'Problemler', plan_group_id: 'present', memory_key: 'none' },
    context: { sourceRevision: 'v2', occurredAt: '2026-09-02T12:00:00.000Z', opaqueLocatorToken: 'coachRef01' },
  },
  {
    id: 'ai-solve-unmatched',
    matrixId: 'M11',
    adapter: 'adaptAiSolveEvent',
    input: { id: 'solve-fixture-1', event_id: 'solve-event-1', exam_type: 'TYT', subject: 'Matematik', topic: 'Uydurma konu', topic_matched: false, semantic_event_type: 'solution_requested', created_at: '2026-09-02T12:00:00.000Z' },
    context: { sourceRevision: 'v1', opaqueLocatorToken: 'solveRef01' },
    expectedQuarantine: 'SOURCE_TOPIC_MATCH_FALSE',
  },
  {
    id: 'ai-solve-review',
    matrixId: 'M12',
    adapter: 'adaptAiSolveReview',
    input: { id: 'solve-fixture-2', reviewed: true },
    context: { sourceRevision: 'v2', asOf: '2026-09-02T13:00:00.000Z', storageScope: 'server', opaqueLocatorToken: 'reviewRef1' },
  },
  {
    id: 'structured-lesson-answer',
    matrixId: 'M15',
    adapter: 'adaptStructuredLessonEvent',
    input: { event_id: 'lesson-event-1', lesson_id: 'lesson-fixture-1', event_type: 'quiz_answered', exam_type: 'TYT', subject: 'Matematik', topic: 'Problemler', block_id: 'quiz-1', section_id: 'section-1', is_correct: true },
    context: { sourceRevision: 'v1', occurredAt: '2026-09-02T12:00:00.000Z', opaqueLocatorToken: 'lessonRef1' },
  },
  {
    id: 'bundled-lesson-answer',
    matrixId: 'M16',
    adapter: 'adaptBundledLessonEvent',
    input: { lesson_id: 'temel-kavramlar', event_type: 'quiz_answered', exam_type: 'TYT', subject: 'Matematik', topic: 'Temel Kavramlar', block_id: 'quiz-1', section_id: 'section-1', is_correct: false },
    context: { sourceRevision: 'content-r1', contentRevision: 'content-r1', occurredAt: '2026-09-02T12:00:00.000Z', opaqueLocatorToken: 'bundled01' },
  },
  {
    id: 'content-exposure',
    matrixId: 'M17',
    adapter: 'adaptContentExposure',
    input: { id: 'note-fixture-1', exam_type: 'TYT', subject: 'Matematik', topic: 'Problemler', content_kind: 'pdf' },
    context: { sourceRevision: 'v1', contentRevision: 'content-r1', occurredAt: '2026-09-02T12:00:00.000Z', opaqueLocatorToken: 'content001' },
  },
  {
    id: 'db-question-test',
    matrixId: 'M19',
    adapter: 'adaptQuestionTestResult',
    input: { attempt_id: 'attempt-fixture-1', question_set_id: 'set-fixture-1', exam_type: 'TYT', subject: 'Matematik', topic: 'Problemler', correct: 8, incorrect: 1, empty: 1, duration_minutes: 20 },
    context: { sourceCode: 'db_question_test', sourceRevision: 'v1', contentRevision: 'content-r1', occurredAt: '2026-09-02T12:00:00.000Z', opaqueLocatorToken: 'dbtestRef1' },
  },
  {
    id: 'bundled-question-test',
    matrixId: 'M20',
    adapter: 'adaptQuestionTestResult',
    input: { attempt_id: 'attempt-fixture-2', question_set_id: 'bundled-set-1', exam_type: 'TYT', subject: 'Matematik', topic: 'Problemler', correct: 7, incorrect: 2, empty: 1 },
    context: { sourceCode: 'bundled_question_test', sourceRevision: 'content-r1', contentRevision: 'content-r1', occurredAt: '2026-09-02T12:00:00.000Z', opaqueLocatorToken: 'pkgtest001' },
  },
  {
    id: 'physics-atlas-snapshot',
    matrixId: 'M21',
    adapter: 'adaptAtlasSnapshot',
    input: { id: 'hareket-deneyi', task_code: 'hareket-deneyi', storage_version: 'v1', correct: 3, incorrect: 1, completed: true },
    context: { sourceCode: 'physics_atlas', atlas: 'fizik', regionCode: 'mekanik', sourceRevision: 'v3', asOf: '2026-09-02T12:00:00.000Z', opaqueLocatorToken: 'physics001' },
  },
  {
    id: 'biology-atlas-snapshot',
    matrixId: 'M22',
    adapter: 'adaptAtlasSnapshot',
    input: { id: 'biyo-001', question_id: 'biyo-001', storage_version: 'v1', correct: 1, incorrect: 0, completed: true },
    context: { sourceCode: 'biology_atlas', atlas: 'biyoloji', regionCode: 'hucre', sourceRevision: 'v2', asOf: '2026-09-02T12:00:00.000Z', opaqueLocatorToken: 'biology001' },
  },
  {
    id: 'geography-atlas-snapshot',
    matrixId: 'M23',
    adapter: 'adaptAtlasSnapshot',
    input: { id: 'tyt-1', question_id: 'tyt-1', storage_version: 'v1', correct: 6, incorrect: 2, blank: 0, timed: true, duration_minutes: 12 },
    context: { sourceCode: 'geography_atlas', atlas: 'cografya', regionCode: 'turkiye', sourceRevision: 'v2', asOf: '2026-09-02T12:00:00.000Z', opaqueLocatorToken: 'geoRef0001' },
  },
  {
    id: 'chemistry-mini-test',
    matrixId: 'M24',
    adapter: 'adaptAtlasSnapshot',
    input: { id: 'mini-test-attempt-1', task_code: 'mini-test-v1', storage_version: 'v1', correct: 9, incorrect: 3, blank: 0 },
    context: { sourceCode: 'chemistry_atlas', atlas: 'kimya', regionCode: 'global', semanticEventType: 'mini_test_completed', sourceRevision: 'content-r1', asOf: '2026-09-02T12:00:00.000Z', opaqueLocatorToken: 'chemRef001' },
  },
  {
    id: 'geometry-pilot-test',
    matrixId: 'M26',
    adapter: 'adaptQuestionTestResult',
    input: { attempt_id: 'geometry-attempt-1', exam_type: 'TYT', subject: 'Geometri', topic: 'Üçgende Açılar', correct: 3, incorrect: 1, empty: 0 },
    context: { sourceCode: 'geometry_pilot', sourceRevision: 'content-r1', contentRevision: 'content-r1', occurredAt: '2026-09-02T12:00:00.000Z', opaqueLocatorToken: 'geometry01' },
  },
  {
    id: 'english-lesson-snapshot',
    matrixId: 'M27',
    adapter: 'adaptLanguageSnapshot',
    input: { id: 'a1-m1-d1', lesson_id: 'a1-m1-d1', storage_version: 'v1', cefr_level: 'A1', skill: 'reading', correct: 8, incorrect: 2, duration_minutes: 15 },
    context: { sourceCode: 'ingilizce_learning', language: 'ingilizce', snapshotSection: 'lesson', sourceRevision: 'v2', asOf: '2026-09-02T12:00:00.000Z', opaqueLocatorToken: 'english001' },
  },
  {
    id: 'german-lesson-snapshot',
    matrixId: 'M28',
    adapter: 'adaptLanguageSnapshot',
    input: { id: 'a1-m1-d1', lesson_id: 'a1-m1-d1', storage_version: 'v1', cefr_level: 'A1', skill: 'reading', correct: 8, incorrect: 2, duration_minutes: 15 },
    context: { sourceCode: 'almanca_learning', language: 'almanca', snapshotSection: 'lesson', sourceRevision: 'v2', asOf: '2026-09-02T12:00:00.000Z', opaqueLocatorToken: 'german0001' },
  },
  {
    id: 'french-lesson-snapshot',
    matrixId: 'M29',
    adapter: 'adaptLanguageSnapshot',
    input: { id: 'a1-m1-d1', lesson_id: 'a1-m1-d1', storage_version: 'v1', cefr_level: 'A1', skill: 'reading', correct: 8, incorrect: 2, duration_minutes: 15 },
    context: { sourceCode: 'fransizca_learning', language: 'fransizca', snapshotSection: 'lesson', sourceRevision: 'v2', asOf: '2026-09-02T12:00:00.000Z', opaqueLocatorToken: 'french0001' },
  },
  {
    id: 'spanish-lesson-snapshot',
    matrixId: 'M30',
    adapter: 'adaptLanguageSnapshot',
    input: { id: 'a1-m1-d1', lesson_id: 'a1-m1-d1', storage_version: 'v1', cefr_level: 'A1', skill: 'reading', correct: 8, incorrect: 2, duration_minutes: 15 },
    context: { sourceCode: 'ispanyolca_learning', language: 'ispanyolca', snapshotSection: 'lesson', sourceRevision: 'v2', asOf: '2026-09-02T12:00:00.000Z', opaqueLocatorToken: 'spanish001' },
  },
  {
    id: 'live-attendance',
    matrixId: 'M31',
    adapter: 'adaptLiveLessonAttendance',
    input: { session_id: 'session-fixture-1', participant_id: 'participant-fixture-1', state: 'left', duration_minutes: 45 },
    context: { sourceRevision: 'v2', asOf: '2026-09-02T13:00:00.000Z', opaqueLocatorToken: 'liveRef001' },
  },
  {
    id: 'shared-lesson-summary',
    matrixId: 'M33',
    adapter: 'adaptSharedLessonSummary',
    input: { lesson_session_id: 'session-fixture-1', shared_with_student: true, exam_type: 'TYT', subject: 'Matematik', topic: 'Problemler' },
    context: { sourceRevision: 'v3', asOf: '2026-09-02T13:00:00.000Z', actorRole: 'teacher', completionStatus: 'completed', opaqueLocatorToken: 'summary001' },
  },
  {
    id: 'profile-context-snapshot',
    matrixId: 'M36',
    adapter: 'adaptProfileSnapshot',
    input: { id: 'profile-fixture-1', target_exam: 'TYT', grade_level: '12', exam_date: '2027-06-20' },
    context: { sourceRevision: 'v2', asOf: '2026-09-02T13:00:00.000Z', opaqueLocatorToken: 'profile001' },
  },
])

export const TRUSTED_EVIDENCE_FIXTURE = Object.freeze({
  record_id: '10000000-0000-4000-8000-000000000001',
  student_id: '00000000-0000-4000-8000-000000000001',
  actor_id: '00000000-0000-4000-8000-000000000001',
  actor_role: 'student',
  actor_student_relation: 'self',
  recorded_at: '2026-09-02T14:00:00.000Z',
  evidence_strength: 'medium',
  trust_level: 'account_bound',
})
