/**
 * DRKOÇ — FRANSIZCA SEVİYE TESPİT MADDE BANKASI
 * ==================================================================
 *
 * Bu bankanın amacı öğrenciyi ELEMEK değil, nereden başlayacağını
 * bulmaktır. Bu yüzden maddeler "zor soru" olarak değil, BASAMAK olarak
 * seçildi: her madde belirli bir seviyenin ayırt edici yapısını ölçer.
 *
 * SEÇİM ÖLÇÜTÜ: bir maddenin bankaya girebilmesi için, o seviyeyi geçmiş
 * bir öğrencinin doğru, geçmemiş bir öğrencinin yanlış yapma olasılığının
 * yüksek olması gerekir. "Herkesin bildiği" ya da "kimsenin bilmediği"
 * maddeler bilgi vermez ve bankaya alınmaz.
 *
 * FRANSIZCAYA ÖZGÜ AYIRT EDİCİLER — hangi seviyede neyin ölçüldüğü:
 *   Pre-A1 → temel kelime tanıma, sayı, selamlaşma
 *   A1     → être/avoir, cinsiyet, olumsuzluk, présent çekimi
 *   A2     → passé composé, kısmi artikel, sıfat uyumu, kaynaşma
 *   B1     → imparfait/passé composé ayrımı, zamirler, koşul cümlesi
 *   B2     → subjonctif, edilgen, ince edat ve eşdizim seçimi
 *   C1     → deyim, üslup, örtük anlam
 *
 * Sınav uyarlanabilirdir (bkz. lib/fransizca/seviyeTespit.js): doğru
 * cevapta zorluk yükselir, yanlışta düşer. Bu yüzden her seviyede birden
 * çok madde bulunur.
 */

export const MADDELER = [
  /* ---------------------------- Pre-A1 ---------------------------- */
  {
    id: 'st-p1',
    seviye: 'Pre-A1',
    beceri: 'kelime',
    tur: 'coktan-secmeli',
    yonerge: 'Doğru karşılığı seç.',
    soru: '"le livre" ne demek?',
    secenekler: [
      { id: 'a', metin: 'kitap' },
      { id: 'b', metin: 'masa' },
      { id: 'c', metin: 'kapı' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-p2',
    seviye: 'Pre-A1',
    beceri: 'kelime',
    tur: 'coktan-secmeli',
    yonerge: 'Akşam saat 20:00’de birini selamlıyorsun. Ne dersin?',
    soru: 'Doğru selamlama hangisi?',
    secenekler: [
      { id: 'a', metin: 'Bonsoir' },
      { id: 'b', metin: 'Bonjour' },
      { id: 'c', metin: 'Bonne nuit' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-p3',
    seviye: 'Pre-A1',
    beceri: 'kelime',
    tur: 'coktan-secmeli',
    yonerge: 'Sayıyı seç.',
    soru: '"douze" kaçtır?',
    secenekler: [
      { id: 'a', metin: '12' },
      { id: 'b', metin: '2' },
      { id: 'c', metin: '20' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-p4',
    seviye: 'Pre-A1',
    beceri: 'telaffuz',
    tur: 'coktan-secmeli',
    yonerge: 'Okunuşu seç.',
    soru: '"tu" kelimesi nasıl okunur?',
    secenekler: [
      { id: 'a', metin: '"tü"' },
      { id: 'b', metin: '"tu"' },
      { id: 'c', metin: '"tuv"' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-p5',
    seviye: 'Pre-A1',
    beceri: 'dinleme',
    tur: 'dinle-sec',
    yonerge: 'Dinle ve duyduğunu seç.',
    seslendir: 'Merci beaucoup !',
    secenekler: [
      { id: 'a', metin: 'Merci beaucoup !' },
      { id: 'b', metin: 'Mercredi beau !' },
      { id: 'c', metin: 'Merci bien !' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-p6',
    seviye: 'Pre-A1',
    beceri: 'kelime',
    tur: 'tanim-kelime',
    yonerge: 'Tanımı okuyup kelimeyi yaz.',
    tanim: 'C’est la personne qui enseigne dans une classe.',
    ilkHarf: 'p',
    kabul: ['professeur', 'le professeur', 'prof', 'un professeur'],
  },

  /* ------------------------------ A1 ------------------------------ */
  {
    id: 'st-a1-1',
    seviye: 'A1',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Boşluğa hangisi gelir?',
    soru: 'Je ____ étudiant.',
    secenekler: [
      { id: 'a', metin: 'suis' },
      { id: 'b', metin: 'ai' },
      { id: 'c', metin: 'est' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-a1-2',
    seviye: 'A1',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Boşluğa hangisi gelir?',
    soru: 'J’____ seize ans.',
    secenekler: [
      { id: 'a', metin: 'ai' },
      { id: 'b', metin: 'suis' },
      { id: 'c', metin: 'es' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-a1-3',
    seviye: 'A1',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Doğru artikeli seç.',
    soru: '____ maison de mes parents est grande.',
    secenekler: [
      { id: 'a', metin: 'La' },
      { id: 'b', metin: 'Le' },
      { id: 'c', metin: 'Les' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-a1-4',
    seviye: 'A1',
    beceri: 'gramer',
    tur: 'hata-bul',
    yonerge: 'Cümlede bir hata var. Doğru biçimini yaz.',
    cumle: 'Je comprends pas la question.',
    hataliParca: 'comprends pas',
    dogruParca: 'ne comprends pas',
    kabul: ['Je ne comprends pas la question', 'ne comprends pas', 'Je ne comprends pas'],
  },
  {
    id: 'st-a1-5',
    seviye: 'A1',
    beceri: 'dizim',
    tur: 'siralama',
    yonerge: 'Kelimeleri sıralayarak doğru cümleyi kur.',
    parcalar: ['au', 'Je', 'lycée', 'vais'],
    dogruSira: [1, 3, 0, 2],
  },
  {
    id: 'st-a1-6',
    seviye: 'A1',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Doğru çekimi seç.',
    soru: 'Nous ____ français à l’école.',
    secenekler: [
      { id: 'a', metin: 'parlons' },
      { id: 'b', metin: 'parlez' },
      { id: 'c', metin: 'parle' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-a1-7',
    seviye: 'A1',
    beceri: 'dinleme',
    tur: 'dinle-sec',
    yonerge: 'Dinle ve duyduğunu seç.',
    seslendir: 'Il a deux frères.',
    secenekler: [
      { id: 'a', metin: 'Il a deux frères.' },
      { id: 'b', metin: 'Il est deux frères.' },
      { id: 'c', metin: 'Ils ont deux frères.' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-a1-8',
    seviye: 'A1',
    beceri: 'kelime',
    tur: 'bosluk',
    yonerge: 'Boşluğu doldur.',
    parcalar: ['Excusez-moi, ', { bosluk: 0 }, ' est la gare ?'],
    cevaplar: [{ kabul: ['où', 'ou'], ipucu: 'yer soran kelime' }],
  },

  /* ------------------------------ A2 ------------------------------ */
  {
    id: 'st-a2-1',
    seviye: 'A2',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Boşluğa hangisi gelir?',
    soru: 'Hier, j’____ mangé au restaurant.',
    secenekler: [
      { id: 'a', metin: 'ai' },
      { id: 'b', metin: 'suis' },
      { id: 'c', metin: 'avais' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-a2-2',
    seviye: 'A2',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Boşluğa hangisi gelir?',
    soru: 'Elle ____ allée à Paris le mois dernier.',
    secenekler: [
      { id: 'a', metin: 'est' },
      { id: 'b', metin: 'a' },
      { id: 'c', metin: 'était' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-a2-3',
    seviye: 'A2',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Boşluğa hangisi gelir?',
    soru: 'Je bois ____ eau.',
    secenekler: [
      { id: 'a', metin: 'de l’' },
      { id: 'b', metin: 'de la' },
      { id: 'c', metin: 'du' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-a2-4',
    seviye: 'A2',
    beceri: 'gramer',
    tur: 'hata-bul',
    yonerge: 'Cümlede bir hata var. Doğru biçimini yaz.',
    cumle: 'Je vais à le cinéma ce soir.',
    hataliParca: 'à le',
    dogruParca: 'au',
    kabul: ['Je vais au cinéma ce soir', 'au', 'Je vais au cinéma'],
  },
  {
    id: 'st-a2-5',
    seviye: 'A2',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Doğru biçimi seç.',
    soru: 'Ma sœur est très ____.',
    secenekler: [
      { id: 'a', metin: 'gentille' },
      { id: 'b', metin: 'gentil' },
      { id: 'c', metin: 'gentils' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-a2-6',
    seviye: 'A2',
    beceri: 'gramer',
    tur: 'bosluk',
    yonerge: 'Olumsuz cümleyi tamamla.',
    parcalar: ['Il n’y a pas ', { bosluk: 0 }, ' pain.'],
    cevaplar: [{ kabul: ['de', "d'"], ipucu: 'olumsuzda artikel neye döner?' }],
  },
  {
    id: 'st-a2-7',
    seviye: 'A2',
    beceri: 'dizim',
    tur: 'siralama',
    yonerge: 'Kelimeleri sıralayarak doğru soruyu kur.',
    parcalar: ['tu', 'Qu’est-ce que', 'fais', 'ce soir'],
    dogruSira: [1, 0, 2, 3],
  },
  {
    id: 'st-a2-8',
    seviye: 'A2',
    beceri: 'dusunme',
    tur: 'dogal-secim',
    yonerge: 'İkisi de dil bilgisi bakımından doğru. Hangisi doğal?',
    baglam: 'Bir mağazada bir çantanın fiyatını soruyorsun.',
    secenekler: [
      { id: 'a', metin: 'C’est combien ?', dogal: true, neden: 'Günlük dilde fiyat böyle sorulur.' },
      { id: 'b', metin: 'Quel est le prix de ce sac ?', dogal: false, neden: 'Doğru ama resmî ve kitabi; konuşmada nadiren duyulur.' },
    ],
  },
  {
    id: 'st-a2-9',
    seviye: 'A2',
    beceri: 'dinleme',
    tur: 'dinle-yaz',
    yonerge: 'Dinle ve duyduğun cümleyi yaz.',
    seslendir: 'Nous avons deux enfants.',
    kabul: ['Nous avons deux enfants', 'nous avons deux enfants'],
  },
  {
    id: 'st-a2-10',
    seviye: 'A2',
    beceri: 'kelime',
    tur: 'coktan-secmeli',
    yonerge: 'Doğru kelimeyi seç.',
    soru: 'Je vais à la ____ pour acheter un roman.',
    secenekler: [
      { id: 'a', metin: 'librairie' },
      { id: 'b', metin: 'bibliothèque' },
      { id: 'c', metin: 'boulangerie' },
    ],
    dogruId: 'a',
  },

  /* ------------------------------ B1 ------------------------------ */
  {
    id: 'st-b1-1',
    seviye: 'B1',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Boşluğa hangisi gelir?',
    soru: 'Quand j’étais petit, je ____ souvent au parc.',
    secenekler: [
      { id: 'a', metin: 'allais' },
      { id: 'b', metin: 'suis allé' },
      { id: 'c', metin: 'irai' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-b1-2',
    seviye: 'B1',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Boşluğa hangisi gelir?',
    soru: 'Je lui ai donné le livre. → "lui" burada neyin yerine geçiyor?',
    secenekler: [
      { id: 'a', metin: 'kişi (COI — dolaylı nesne)' },
      { id: 'b', metin: 'nesne (COD — doğrudan nesne)' },
      { id: 'c', metin: 'yer' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-b1-3',
    seviye: 'B1',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Boşluğa hangisi gelir?',
    soru: 'Si j’avais le temps, je ____ avec toi.',
    secenekler: [
      { id: 'a', metin: 'viendrais' },
      { id: 'b', metin: 'viendrai' },
      { id: 'c', metin: 'viens' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-b1-4',
    seviye: 'B1',
    beceri: 'gramer',
    tur: 'hata-bul',
    yonerge: 'Cümlede bir hata var. Doğru biçimini yaz.',
    cumle: 'J’ai vu Marie hier. Je l’ai parlé longtemps.',
    hataliParca: 'l’ai parlé',
    dogruParca: 'lui ai parlé',
    kabul: ['Je lui ai parlé longtemps', 'lui ai parlé', 'lui'],
  },
  {
    id: 'st-b1-5',
    seviye: 'B1',
    beceri: 'kelime',
    tur: 'coktan-secmeli',
    yonerge: 'Doğru kelimeyi seç.',
    soru: 'Je dois ____ à la réunion de demain.',
    secenekler: [
      { id: 'a', metin: 'assister' },
      { id: 'b', metin: 'attendre' },
      { id: 'c', metin: 'assurer' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-b1-6',
    seviye: 'B1',
    beceri: 'dusunme',
    tur: 'dogal-secim',
    yonerge: 'Hangisi daha doğal?',
    baglam: 'Bir öneriyi kibarca reddediyorsun.',
    secenekler: [
      { id: 'a', metin: 'C’est gentil, mais je ne peux pas.', dogal: true, neden: 'Önce teşekkür/övgü, sonra ret — Fransızcada beklenen sıra budur.' },
      { id: 'b', metin: 'Non, je ne veux pas.', dogal: false, neden: 'Dil bilgisi doğru ama kaba duyulur.' },
    ],
  },
  {
    id: 'st-b1-7',
    seviye: 'B1',
    beceri: 'dinleme',
    tur: 'dinle-sec',
    yonerge: 'Dinle ve duyduğunu seç.',
    seslendir: 'Ils ont pris le train de huit heures.',
    secenekler: [
      { id: 'a', metin: 'Ils ont pris le train de huit heures.' },
      { id: 'b', metin: 'Ils sont pris le train de huit heures.' },
      { id: 'c', metin: 'Il a pris le train de huit heures.' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-b1-8',
    seviye: 'B1',
    beceri: 'gramer',
    tur: 'bosluk',
    yonerge: 'Boşluğu doldur.',
    parcalar: ['Il faut que tu ', { bosluk: 0 }, ' tes devoirs avant de sortir.'],
    cevaplar: [{ kabul: ['fasses'], ipucu: 'il faut que → subjonctif' }],
  },
  {
    id: 'st-b1-9',
    seviye: 'B1',
    beceri: 'okuma',
    tur: 'coktan-secmeli',
    yonerge: 'Metni okuyup soruyu cevapla.',
    soru: '"Malgré la pluie, ils ont décidé de partir." — Ne olmuş?',
    secenekler: [
      { id: 'a', metin: 'Yağmura rağmen yola çıkmışlar.' },
      { id: 'b', metin: 'Yağmur yüzünden kalmışlar.' },
      { id: 'c', metin: 'Yağmuru beklemişler.' },
    ],
    dogruId: 'a',
  },

  /* ------------------------------ B2 ------------------------------ */
  {
    id: 'st-b2-1',
    seviye: 'B2',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Boşluğa hangisi gelir?',
    soru: 'Bien qu’il ____ fatigué, il a continué à travailler.',
    secenekler: [
      { id: 'a', metin: 'soit' },
      { id: 'b', metin: 'est' },
      { id: 'c', metin: 'sera' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-b2-2',
    seviye: 'B2',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Edilgen biçimi seç.',
    soru: '"Le professeur corrige les copies." cümlesinin edilgeni hangisidir?',
    secenekler: [
      { id: 'a', metin: 'Les copies sont corrigées par le professeur.' },
      { id: 'b', metin: 'Les copies corrigent le professeur.' },
      { id: 'c', metin: 'Le professeur est corrigé les copies.' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-b2-3',
    seviye: 'B2',
    beceri: 'kelime',
    tur: 'coktan-secmeli',
    yonerge: 'En uygun eşdizimi seç.',
    soru: 'Il a ____ une décision importante.',
    secenekler: [
      { id: 'a', metin: 'pris' },
      { id: 'b', metin: 'fait' },
      { id: 'c', metin: 'donné' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-b2-4',
    seviye: 'B2',
    beceri: 'dusunme',
    tur: 'dogal-secim',
    yonerge: 'Hangisi daha doğal?',
    baglam: 'Bir tartışmada karşı görüşe geçiş yapıyorsun.',
    secenekler: [
      { id: 'a', metin: 'Cela dit, il ne faut pas oublier que…', dogal: true, neden: 'Karşı görüşe yumuşak geçiş için kullanılan standart bağlayıcıdır.' },
      { id: 'b', metin: 'Mais non, c’est faux.', dogal: false, neden: 'Doğru ama tartışma dilinde sert ve kestirip atan bir ifadedir.' },
    ],
  },
  {
    id: 'st-b2-5',
    seviye: 'B2',
    beceri: 'okuma',
    tur: 'coktan-secmeli',
    yonerge: 'Yazarın tutumunu seç.',
    soru: '"Ce projet, aussi ambitieux soit-il, reste difficilement réalisable." — Yazar ne düşünüyor?',
    secenekler: [
      { id: 'a', metin: 'Proje iddialı ama gerçekleşmesi zor.' },
      { id: 'b', metin: 'Proje kolayca gerçekleşir.' },
      { id: 'c', metin: 'Proje iddialı değil.' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-b2-6',
    seviye: 'B2',
    beceri: 'gramer',
    tur: 'hata-bul',
    yonerge: 'Cümlede bir hata var. Doğru biçimini yaz.',
    cumle: 'Après qu’il soit parti, nous avons fermé la porte.',
    hataliParca: 'soit parti',
    dogruParca: 'est parti',
    kabul: ['Après qu’il est parti', 'est parti', "Après qu'il est parti"],
  },

  /* ------------------------------ C1 ------------------------------ */
  {
    id: 'st-c1-1',
    seviye: 'C1',
    beceri: 'kelime',
    tur: 'coktan-secmeli',
    yonerge: 'Deyimin anlamını seç.',
    soru: '"Il a mis les pieds dans le plat." ne demek?',
    secenekler: [
      { id: 'a', metin: 'Pot kırdı, patavatsızlık etti.' },
      { id: 'b', metin: 'Yemeğe başladı.' },
      { id: 'c', metin: 'İşi bıraktı.' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-c1-2',
    seviye: 'C1',
    beceri: 'kelime',
    tur: 'coktan-secmeli',
    yonerge: 'En uygun kelimeyi seç.',
    soru: 'Son argumentation, bien que ____, n’a convaincu personne.',
    secenekler: [
      { id: 'a', metin: 'rigoureuse' },
      { id: 'b', metin: 'rigide' },
      { id: 'c', metin: 'rigolote' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-c1-3',
    seviye: 'C1',
    beceri: 'okuma',
    tur: 'coktan-secmeli',
    yonerge: 'Örtük anlamı seç.',
    soru: '"On ne peut pas dire que ce film soit un chef-d’œuvre." — Konuşan ne demek istiyor?',
    secenekler: [
      { id: 'a', metin: 'Film pek iyi değil (kibar bir olumsuzlama).' },
      { id: 'b', metin: 'Film bir başyapıt.' },
      { id: 'c', metin: 'Filmi izlemedi.' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-c1-4',
    seviye: 'C1',
    beceri: 'dusunme',
    tur: 'dogal-secim',
    yonerge: 'Akademik metinde hangisi uygundur?',
    baglam: 'Bir makalede sonuç bölümüne geçiyorsun.',
    secenekler: [
      { id: 'a', metin: 'En définitive, il apparaît que…', dogal: true, neden: 'Akademik üsluba uygun, ölçülü bir sonuç bağlayıcısıdır.' },
      { id: 'b', metin: 'Bref, voilà quoi.', dogal: false, neden: 'Tamamen sözlü ve gündelik bir kapanıştır; yazıda kullanılmaz.' },
    ],
  },
  {
    id: 'st-c1-5',
    seviye: 'C1',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Doğru biçimi seç.',
    soru: 'Les mesures ____ le gouvernement a prises sont contestées.',
    secenekler: [
      { id: 'a', metin: 'que' },
      { id: 'b', metin: 'qui' },
      { id: 'c', metin: 'dont' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-c1-6',
    seviye: 'C1',
    beceri: 'dinleme',
    tur: 'dinle-sec',
    yonerge: 'Dinle ve duyduğunu seç.',
    seslendir: 'Il aurait fallu qu’on s’en aperçoive plus tôt.',
    secenekler: [
      { id: 'a', metin: 'Il aurait fallu qu’on s’en aperçoive plus tôt.' },
      { id: 'b', metin: 'Il a fallu qu’on s’en aperçoive plus tôt.' },
      { id: 'c', metin: 'Il faudrait qu’on s’en aperçoive plus tôt.' },
    ],
    dogruId: 'a',
  },
]

export const YAZMA_GOREVI = {
  id: 'st-yazma',
  seviye: 'A2',
  beceri: 'yazma',
  tur: 'yazma',
  yonerge: 'Son adım: kendini kısaca tanıt. Ne kadar yazabiliyorsan o kadar yaz — kısa yazman sonucu bozmaz, yalnız daha az bilgi verir.',
  gorev: 'Écris quelques phrases sur toi en français : qui es-tu, où habites-tu, qu’est-ce que tu fais, et pourquoi apprends-tu le français ?',
  ornekMetin: null,
  kaliplar: [],
  asamalar: [
    { ad: 'Yaz', aciklama: 'Aklına geldiği gibi yaz. Bu bir sınav değil, ölçüm.' },
  ],
  olcut: [
    'Kendimi tanıttım (Je m’appelle… / Je suis…).',
    'Nerede yaşadığımı yazdım.',
    'Ne yaptığımı (okul/iş) yazdım.',
    'Neden Fransızca öğrendiğimi yazdım.',
    'Her cümlede özne zamiri kullandım.',
  ],
  enAzKelime: 25,
  aranan: [
    { etiket: 'être fiili', desen: /\b(suis|es|est|sommes|êtes|etes|sont)\b/i },
    { etiket: 'présent fiili', desen: /\b(habite|habites|parle|parles|étudie|etudie|travaille|apprends|aime|fais|vais)\b/i },
    { etiket: 'bağlaç (et/mais/parce que)', desen: /\b(et|mais|parce que|donc|ou)\b/i },
    { etiket: 'geçmiş ya da gelecek', desen: /\b(ai \w+é|suis \w+é|était|étais|vais \w+er|voudrais|j'aimerais)\b/i },
    { etiket: 'amaç bildirme (pour / parce que)', desen: /\b(pour \w+er|parce que je)\b/i },
  ],
}
