import { buildTopic } from './rapid-builder.js'

const c = (term, definition, why, boundary) => ({ term, definition, why, boundary })
const r = (prompt, answer, review) => ({ prompt, answer, review })
const e = (title, prompt, steps, answer, takeaway, check) => ({ title, prompt, steps, answer, takeaway, check })
const q = (level, question, options, answer, idea, solution, wrong, check) => ({ level, question, options, answer, idea, solution, wrong, check })
const t = (title, wrong, right, cause, check) => ({ title, wrong, right, cause, check })

const inequalities = buildTopic({
  topic: 'Basit Eşitsizlikler',
  subtitle: 'Çözüm kümesini sayı doğrusunda kur; yön değiştiren adımı ve sınırları görünür tut.',
  prerequisites: [{ topic: 'Temel Kavramlar', why: 'Sıralama, negatif sayı ve sayı doğrusu bilgisi gerekir.' }],
  connections: ['Mutlak Değer', 'Denklem Çözme', 'Problemler'],
  mapCore: 'Bir koşulu eşitsizliğe çevirir, eşdeğer dönüşümlerle çözüm kümesini bulur.',
  introduction: 'Eşitsizlik tek bir değeri değil, koşulu sağlayan değerler kümesini anlatır. Çözümün doğal gösterimi bu nedenle sayı doğrusu ve aralıktır.',
  tytUse: 'Yaş, bütçe, kapasite, hız ve en az-en çok koşulları çoğu kez bir eşitsizlik modeli gerektirir.',
  struggle: 'Negatif sayıyla çarpma veya bölmede yönü değiştirmemek; açık ve kapalı uçları karıştırmak.',
  osymBody: 'Basit eşitsizlik doğrudan işlem sorusu olabildiği gibi problem, mutlak değer ve grafik içinde de yardımcı araç olarak kullanılır.',
  osymMeasures: ['Eşdeğer dönüşüm', 'Aralık okuma', 'Tam sayı sayma', 'Sözel sınır modelleme'],
  patternBody: 'Sayı doğrusu, çift taraflı eşitsizlik, seçenek eleme ve günlük üst-alt sınır bağlamları görülür.',
  patterns: ['Sayı doğrusu', 'Çift taraflı koşul', 'Tam sayı çözüm sayısı', 'En az-en çok problemi'],
  readiness: [
    r('$x+4<9$ ise $x$ için ne söylenir?', '$x<5$.', 'Denklemde ters işlem ve sıralama dilini tekrar et.'),
    r('$-2< x\\le3$ aralığında kaç tam sayı vardır?', '$-1,0,1,2,3$ olmak üzere 5.', 'Açık ve kapalı uçları sayı doğrusunda göster.'),
    r('$-6\\div(-2)$ kaçtır?', '$3$.', 'Negatif sayılarda işlem işaretlerini onar.'),
  ],
  concepts: [
    c('Çözüm kümesi', 'Eşitsizliği doğru yapan bütün değerlerin kümesidir.', 'Tek sonuç aramak yerine aralığı eksiksiz verir.', 'Değişkenin tam sayı, gerçek sayı veya doğal sayı olduğu ayrıca okunur.'),
    c('Eşdeğer dönüşüm', 'İki tarafa aynı sayı eklemek/çıkarmak yönü korur; pozitif sayıyla çarpma/bölme de yönü korur.', 'Çözüm kümesini değiştirmeden ifadeyi sadeleştirir.', 'Negatif çarpan veya bölen yönü tersine çevirir.'),
    c('Aralık gösterimi', '$a<x\\le b$ koşulu $(a,b]$ ile gösterilir.', 'Uçların dâhil olup olmadığını tek bakışta taşır.', 'Sonsuzluk hiçbir zaman kapalı uçla yazılmaz.'),
  ],
  why: { question: 'Neden negatif sayıyla çarpınca eşitsizlik yön değiştirir?', body: '$2<5$ doğruyken her iki tarafı $-1$ ile çarparsak sayı doğrusunda yansıma olur: $-2>-5$. Negatif çarpma sıralamayı tersine çevirir.', boundary: 'Toplama ve çıkarma bir ötelemedir; bu işlemlerde yön değişmez.' },
  formulas: [{ title: 'Yön değiştirme kuralı', latex: 'a<b,\ c<0\\Rightarrow ac>bc', meaning: 'Negatif ölçek sayı doğrusundaki sırayı ters çevirir.', condition: '$c$nin negatif olduğu bilinmelidir.' }],
  certainInfo: 'Eşitsizliğin iki tarafı negatif bir sayıyla çarpılır veya bölünürse eşitsizlik işareti ters çevrilir.',
  examples: [
    e('Tek adımlı dönüşüm', '$-3x<12$', [['Negatif sayıya böl', '$x>-4$; yön değişir.']], '$x>-4$', 'İşaret değişimini ayrı bir adım olarak yaz.', '$x=0$ sağlar, $x=-5$ sağlamaz.'),
    e('Çift taraflı aralık', '$2<3x-1\\le11$', [['Her tarafa 1 ekle', '$3<3x\\le12$.'], ['3e böl', '$1<x\\le4$.']], '$(1,4]$', 'Üç parçaya aynı işlem uygulanır.', '$x=4$ dâhil, $x=1$ dışarıdadır.'),
    e('Tam sayı sayısı', '$-2\\le 2x+1<7$ koşulunu sağlayan kaç tam sayı $x$ vardır?', [['Sadeleştir', '$-3\\le2x<6$.'], ['İkiye böl', '$-\\frac32\\le x<3$.'], ['Tam sayıları yaz', '$-1,0,1,2$.']], '$4$', 'Tam sayı koşulunu aralık bulunduktan sonra uygula.', 'Her değeri ilk eşitsizlikte dene.'),
    e('Sözel sınır', 'Bir asansör en çok 600 kg taşır. İçeride 78 kg görevli varken 65 kg olan en fazla kaç kişi binebilir?', [['Model', '$78+65n\\le600$.'], ['Çöz', '$65n\\le522\\Rightarrow n\\le8{,}03\\ldots$.'], ['Doğal sayı yorumu', 'En büyük tam sayı 8dir.']], '$8$', 'Ondalık sonucu bağlama göre aşağı yuvarla.', '$78+8\\cdot65=598$; dokuz kişi sınırı aşar.'),
  ],
  tactic: { title: 'Sınırı önce yaz', logic: '“En az, en çok, altında, aşmıyor” sözcüklerini işarete çevir; sonra cebir yap.', works: 'Kapasite, bütçe, puan ve tam sayı sayma sorularında.', risk: 'Yuvarlamayı bağlamı okumadan yapmak veya değişken kümesini unutmak.', steps: [['Anahtar sözcüğü işaretle', 'Alt/üst sınırı ve eşitlik olasılığını belirle.'], ['Eşitsizliği kur', 'Birimleri aynılaştır.'], ['Çözüm aralığını bul', 'Negatif bölmede yönü değiştir.'], ['Bağlama dön', 'Tam sayı ve uç koşullarını uygula.']] },
  traps: [
    t('Yönü korumak', '$-2x>6\\Rightarrow x>-3$.', '$-2x>6\\Rightarrow x<-3$.', 'Bölmenin negatif olduğunu atlamak.', '$x=-4$ ve $x=0$ ile sınama yap.'),
    t('Açık ucu dâhil etmek', '$x<3$ için 3ü çözüm saymak.', '$x<3$te 3 çözüm değildir.', 'Sembolü yalnız sayı olarak okumak.', '$3<3$ yanlışlığını yaz.'),
    t('Kümeyi unutmak', '$x<2{,}4$ sonucundan bağlamda 2,4 kişi seçmek.', 'Kişi sayısı doğal sayı olduğundan en çok 2dir.', 'Cebirsel sonuçla gerçek durumun aynı türde olduğunu sanmak.', 'Birimi sonuca ekle.'),
  ],
  questions: [
    q('Temel', '$5-2x\\ge11$ eşitsizliğinin çözümü nedir?', ['$x\\ge-3$', '$x\\le-3$', '$x\\ge3$', '$x\\le3$'], 1, 'Bilinmeyeni yalnız bırak.', '$-2x\\ge6\\Rightarrow x\\le-3$.', 'Negatif ikiye bölerken yönü değiştirmemek.', '$x=-3$ eşitlik verir.'),
    q('Orta', '$-2\\le x<3$ aralığında kaç tam sayı vardır?', ['4', '5', '6', '7'], 1, 'Uçları okuyup listele.', '$-2,-1,0,1,2$: beş sayı.', '3ü açık uca rağmen saymak.', 'Listeyi eşitsizlikte denetle.'),
    q('Orta', '$x+4>2x-1$ için hangisi doğrudur?', ['$x<5$', '$x>5$', '$x\\le5$', '$x\\ge5$'], 0, 'Değişkenleri bir tarafta topla.', '$5>x$, yani $x<5$.', 'Taraf değiştirirken eşitsizlik yönünü keyfî çevirmek.', '$x=0$ sağlamalıdır.'),
    q('İleri', '$2(1-x)\\le3x+7$ çözümü nedir?', ['$x\\le-1$', '$x\\ge-1$', '$x<-1$', '$x>1$'], 1, 'Parantezi aç ve sınırı koru.', '$2-2x\\le3x+7\\Rightarrow-5\\le5x\\Rightarrow x\\ge-1$.', '$-5\\le5x$ ifadesini ters okumak.', '$x=-1$ eşitlik sağlar.'),
  ],
  simulation: { passage: 'Bir kurye paket ve ambalajla birlikte en fazla 12 kg taşıyabiliyor. Ambalaj 1,5 kg, her özdeş ürün 0,7 kgdır.', question: 'Kurye tek seferde en fazla kaç ürün taşıyabilir?', options: [['14', 'Toplam 11,3 kg olur; fakat daha fazlası mümkündür.'], ['15', '$1{,}5+15\\cdot0{,}7=12$ kgdır.'], ['16', 'Toplam 12,7 kg ile sınırı aşar.'], ['17', 'Toplam 13,4 kg ile sınırı aşar.']], answer: 1, stemAnalysis: '“En fazla” eşitliğe izin veren üst sınırdır.', criticalPoint: '$1{,}5+0{,}7n\\le12\\Rightarrow n\\le15$.', takeaway: 'Birim ve doğal sayı koşulu son adımda birlikte uygulanır.' },
  summary: ['Çözüm bir değer değil çoğu kez aralıktır.', 'Negatif sayıyla çarpma/bölmede yön değişir.', 'Açık uç eşitliği dışlar; kapalı uç dâhil eder.', 'Değişken kümesini sonuca uygula.', 'Sözel sınırı cebirden önce doğru işarete çevir.', 'Sonucu sınır ve birimle kontrol et.'],
  nextBody: 'Eşitsizlik dilini uzaklık modeliyle birleştirerek mutlak değere geç.',
}, 6)

const absoluteValue = buildTopic({
  topic: 'Mutlak Değer',
  subtitle: 'Mutlak değeri işaret silme değil, sayı doğrusunda uzaklık olarak oku.',
  prerequisites: [{ topic: 'Basit Eşitsizlikler', why: 'Aralık ve yön bilgisi gerekir.' }],
  connections: ['Fonksiyonlar (Temel)', 'Analitik Geometri (Nokta - Doğru)', 'Problemler'],
  mapCore: 'Bir sayının sıfıra veya başka bir noktaya uzaklığını denklem ve eşitsizlikle ifade eder.',
  introduction: '$|x|$, $x$in sıfıra uzaklığıdır ve bu nedenle negatif olamaz. $|x-a|$ ise $x$ ile $a$ arasındaki uzaklıktır.',
  tytUse: 'Uzaklık, hata payı, aralık ve parçalı koşulları kısa bir ifadeyle birleştirir.',
  struggle: '$|x|$i her durumda $x$ yazmak; eşitsizlikte iki yönü eksik kurmak.',
  osymBody: 'Mutlak değer çoğu yıl bağımsız veya grafik/uzaklık sorusunun çekirdeği olarak görünür.',
  osymMeasures: ['Uzaklık yorumu', 'Parçalı tanım', 'Denklem/eşitsizlik', 'Minimum-maksimum düşünmesi'],
  patternBody: 'Sayı doğrusu, iç içe mutlak değer, hata aralığı ve grafik okuma biçimleri kullanılır.',
  patterns: ['Uzaklık', 'İç içe ifade', 'Aralık', 'Minimum değer'],
  readiness: [r('$|-7|$ kaçtır?', '$7$.', 'Mutlak değeri sıfıra uzaklık olarak düşün.'), r('$|x|=4$ ise $x$ nedir?', '$x=4$ veya $x=-4$.', 'Aynı uzaklıktaki iki noktayı işaretle.'), r('$-3<x<3$ aralığını mutlak değerle yaz.', '$|x|<3$.', 'Simetrik aralık ilişkisini tekrar et.')],
  concepts: [
    c('Uzaklık', '$|x-a|$, $x$ ile $a$ arasındaki uzaklıktır.', 'Denklem ve eşitsizliği geometrik olarak görmeyi sağlar.', 'Uzaklık negatif olamaz.'),
    c('Parçalı tanım', '$|x|=x$ ($x\\ge0$), $|x|=-x$ ($x<0$).', 'İşarete göre neden farklı ifade oluştuğunu açıklar.', 'İçerinin işareti bilinmeden mutlak değer doğrudan kaldırılamaz.'),
    c('Simetrik aralık', '$|x-a|<r$, merkezi $a$ ve yarıçapı $r$ olan açık aralıktır.', 'İki eşitsizliği tek ifadede taşır.', '$r<0$ ise çözüm yoktur; $r=0$ özel durumdur.'),
  ],
  why: { question: 'Neden $|x|^2=x^2$ olur?', body: '$x$ pozitifse $|x|=x$, negatifse $|x|=-x$; her iki durumda da karesi $x^2$dir.', boundary: '$\\sqrt{x^2}=|x|$tir; doğrudan $x$ yazmak $x<0$ için yanlıştır.' },
  formulas: [{ title: 'Uzaklık eşitsizliği', latex: '|x-a|<r\\Leftrightarrow a-r<x<a+r', meaning: '$x$, $a$ merkezine $r$den daha yakındır.', condition: '$r>0$.' }],
  certainInfo: '$|A|\\ge0$ ve $|A|=0$ ancak $A=0$ iken gerçekleşir.',
  examples: [
    e('İki noktalı çözüm', '$|x-3|=5$', [['Uzaklığı yorumla', '$x$, 3ten 5 birim uzaktadır.'], ['İki yön', '$x=3+5$ veya $x=3-5$.']], '$x=8,-2$', 'Mutlak değer denklemi iki simetrik nokta verebilir.', 'Her iki değerde uzaklık 5tir.'),
    e('Aralık', '$|2x+1|<5$', [['Çift taraflı yaz', '$-5<2x+1<5$.'], ['Sadeleştir', '$-6<2x<4\\Rightarrow-3<x<2$.']], '$(-3,2)$', '“Küçüktür” merkez çevresini verir.', '0 aralıkta ve ifadeyi sağlar.'),
    e('İç içe ifade', '$\\big||x|-4\\big|=1$', [['Dış denklemi aç', '$|x|-4=1$ veya $-1$.'], ['İç değerler', '$|x|=5$ veya $|x|=3$.'], ['Noktalar', '$x=\\pm5,\\pm3$.']], '$\\{-5,-3,3,5\\}$', 'Her katmanı dıştan içe çöz.', 'Dört değeri ilk ifadede dene.'),
    e('Minimum değer', '$|x-2|+|x+2|$ ifadesinin en küçük değeri nedir?', [['Geometrik anlam', 'x noktasının 2 ve -2ye uzaklıkları toplamı.'], ['Üçgen yolu', 'İki sabit nokta arası uzaklık 4tür; $x\\in[-2,2]$ iken toplam 4 olur.']], '$4$', 'Uzaklık toplamı sabit noktalar arasından küçük olamaz.', '$x=0$ için $2+2=4$.'),
  ],
  tactic: { title: 'Merkez ve yarıçapı gör', logic: '$|x-a|$ ifadesini önce uzaklık olarak adlandır.', works: 'Denklem, eşitsizlik, hata payı ve minimum uzaklık sorularında.', risk: 'Sağ taraf negatifken standart kalıbı körlemesine uygulamak.', steps: [['İç ifadeyi merkezle', '$x-a$ yapısını ara.'], ['Sağ tarafı kontrol et', 'Negatif, sıfır veya pozitif mi?'], ['Geometriyi kur', 'İki nokta ya da aralık.'], ['Yerine koy', 'Adayları özgün ifadede doğrula.']] },
  traps: [t('İşareti silmek', '$|-5|=-5$.', '$|-5|=5$.', 'Mutlak değeri parantez gibi görmek.', 'Sonucun negatif olup olmadığını sor.'), t('Karekökü yanlış açmak', '$\\sqrt{x^2}=x$.', '$\\sqrt{x^2}=|x|$.', 'Ana karekökün negatif olmadığını unutmak.', '$x=-3$ karşı örneğini kullan.'), t('Tek dal almak', '$|x-1|=4\\Rightarrow x=5$.', '$x=5$ veya $x=-3$.', 'Uzaklığın iki yönlü olduğunu unutmak.', 'Sayı doğrusunda merkezin iki yanını işaretle.')],
  questions: [
    q('Temel', '$|x+2|=3$ denkleminin çözümleri nedir?', ['$1,-5$', '$5,-1$', '$1,5$', '$-1,-5$'], 0, 'Merkez -2dir.', '$x+2=\\pm3\\Rightarrow x=1,-5$.', 'Yalnız pozitif dalı almak.', 'Her iki değeri yerine koy.'),
    q('Orta', '$|x-4|\\le2$ çözümü nedir?', ['$[2,6]$', '$(2,6)$', '$[-6,-2]$', '$(-\\infty,2]$'], 0, '4e en çok 2 uzaklık.', '$2\\le x\\le6$.', 'Uçlarda eşitliği dışlamak.', '$x=2,6$ ifadeyi 2 yapar.'),
    q('Orta', '$|2x|=|x-3|$ ise çözümler toplamı kaçtır?', ['$-2$', '$0$', '$2$', '$4$'], 0, 'Karelerini eşitle.', '$4x^2=(x-3)^2\\Rightarrow3x^2+6x-9=0\\Rightarrow x=1,-3$; toplam -2dir.', 'Kökler toplamını işaret hatasıyla 2 bulmak.', '$x=1$ ve $-3$ ilk denklemi sağlar.'),
    q('İleri', '$|x-1|+|x-5|$ ifadesinin minimumu kaçtır?', ['2', '3', '4', '6'], 2, 'İki sabit nokta arasındaki uzaklığı kullan.', '1 ile 5 arası uzaklık 4tür; $x\\in[1,5]$ için toplam 4.', 'Orta noktada sıfır sanmak.', '$x=3$ için $2+2=4$.'),
  ],
  simulation: { passage: 'Bir sensörün kabul edilen ölçümü 20 birimden en fazla 1,5 birim sapabilir.', question: 'Aşağıdaki ölçümlerden hangisi kabul edilmez?', options: [['18,6', 'Sapma 1,4; kabul edilir.'], ['19,2', 'Sapma 0,8; kabul edilir.'], ['21,5', 'Sapma tam 1,5; “en fazla” koşuluyla kabul edilir.'], ['21,6', 'Sapma 1,6; sınırı aşar.']], answer: 3, stemAnalysis: 'Koşul $|x-20|\\le1{,}5$tir.', criticalPoint: 'Kabul aralığı $[18{,}5,21{,}5]$ olur.', takeaway: '“En fazla” kapalı aralık verir.' },
  summary: ['$|x|$ sıfıra uzaklıktır ve negatif olamaz.', '$|x-a|$ iki nokta arasındaki uzaklıktır.', '$|A|=r$ iki dal; $|A|<r$ bir aralık verir.', '$\\sqrt{x^2}=|x|$.', 'İç içe ifadeyi dıştan içe çöz.', 'Sağ tarafın işaretini kalıp uygulamadan önce kontrol et.'],
  nextBody: 'Uzaklık ve aralık fikrini fonksiyon grafikleri ve analitik geometri içinde yeniden kullan.',
}, 7)

const exponents = buildTopic({
  topic: 'Üslü Sayılar',
  subtitle: 'Üs kurallarını taban ve işlem koşullarıyla kullan; büyüklüğü hesaplamadan karşılaştır.',
  prerequisites: [{ topic: 'Temel Kavramlar', why: 'İşlem önceliği ve işaret bilgisi gerekir.' }],
  connections: ['Köklü Sayılar', 'Denklem Çözme', 'Problemler'],
  mapCore: 'Tekrarlı çarpımı üs diliyle temsil eder ve aynı taban/üs ilişkilerini yönetir.',
  introduction: '$a^n$, uygun tam sayı $n$ için $a$ tabanının tekrarlı çarpımını kısaltır. Kuralların her biri belirli işlem ve sıfır olmama koşullarına bağlıdır.',
  tytUse: 'Bilimsel gösterim, katlanarak değişim, basamak ve büyük sayı karşılaştırmalarında kullanılır.',
  struggle: 'Toplamada üsleri birleştirmek, negatif tabanda parantezi atlamak ve sıfırıncı/negatif üs koşulunu unutmak.',
  osymBody: 'Üslü sayılar düzenli görülen başlıklardandır; son yıllarda işlem yükünden çok eşdeğer yazım ve karşılaştırma öne çıkar.',
  osymMeasures: ['Kural koşulu', 'Eş taban', 'Bilimsel gösterim', 'Büyüklük karşılaştırma'],
  patternBody: 'Tablo, katlanma süreci, bilimsel ölçü ve cebirsel sadeleştirme içinde sunulur.',
  patterns: ['Aynı taban', 'Bilimsel gösterim', 'Katlanma', 'Karşılaştırma'],
  readiness: [r('$2^4$ kaçtır?', '$16$.', 'Üssü tekrarlı çarpım olarak aç.'), r('$(-3)^2$ ile $-3^2$ aynı mıdır?', 'Hayır; sırasıyla 9 ve -9dur.', 'Parantez ve işlem önceliğini gözden geçir.'), r('$10^{-2}$ kaçtır?', '$\\frac1{100}=0{,}01$.', 'Negatif üs tanımını tekrar et.')],
  concepts: [c('Taban ve üs', '$a^n$ ifadesinde $a$ taban, $n$ üstür.', 'Tekrarlı çarpımı ve ölçek değişimini taşır.', 'Negatif taban parantezle gösterilmelidir.'), c('Negatif üs', '$a^{-n}=1/a^n$.', 'Tersini alma ilişkisini açıklar.', '$a\\ne0$ olmalıdır.'), c('Bilimsel gösterim', '$m\\cdot10^n$ ve $1\\le |m|<10$ biçimidir.', 'Çok büyük/küçük ölçüleri karşılaştırır.', 'Katsayı aralık koşulunu sağlamalıdır.')],
  why: { question: 'Neden $a^0=1$ kabul edilir?', body: '$a^m/a^m=a^{m-m}=a^0$; öte yandan sıfır olmayan bir sayının kendisine bölümü 1dir.', boundary: 'Bu gerekçe $a\\ne0$ içindir; $0^0$ bu kuraldan tanımlanmaz.' },
  formulas: [{ title: 'Temel üs kuralları', latex: 'a^m a^n=a^{m+n},\\quad \\frac{a^m}{a^n}=a^{m-n}', meaning: 'Aynı tabanlı çarpımda üsler toplanır, bölümde çıkarılır.', condition: 'Bölümde $a\\ne0$; toplama işleminde bu kural yoktur.' }],
  certainInfo: '$a^m+a^n$ genel olarak $a^{m+n}$ değildir; üs toplama yalnız aynı tabanlı çarpımda kullanılır.',
  examples: [
    e('Aynı tabanı kur', '$8^2\\cdot4^3/2^5$', [['İkiye çevir', '$2^6\\cdot2^6/2^5$.'], ['Üsleri yönet', '$2^{6+6-5}=2^7$.']], '$128$', 'Önce ortak tabanı ara.', 'Doğrudan hesap da 128 verir.'),
    e('Negatif üs', '$\\left(\\frac23\\right)^{-3}$', [['Ters çevir', '$(\\frac32)^3$.'], ['Üssü uygula', '$\\frac{27}{8}$.']], '$\\frac{27}{8}$', 'Negatif üs sonucu negatif yapmaz; tabanı ters çevirir.', 'Çarpanlarla küpünü aç.'),
    e('Bilimsel gösterim', '$0{,}00042$ sayısını bilimsel göster.', [['Virgülü taşı', '$4{,}2$ elde etmek için 4 basamak sağa.'], ['Üs', 'Sağa taşıma $10^{-4}$ verir.']], '$4{,}2\\cdot10^{-4}$', 'Katsayı 1 ile 10 arasında olmalı.', 'Gösterimi açınca özgün sayı gelir.'),
    e('Karşılaştırma', '$3^{20}$ ile $9^9$u karşılaştır.', [['Ortak taban', '$9^9=(3^2)^9=3^{18}$.'], ['Üsleri karşılaştır', '$3>1$ olduğundan $3^{20}>3^{18}$.']], '$3^{20}>9^9$', 'Büyük sayıları hesaplama.', 'Oran $3^2=9>1$dir.'),
  ],
  tactic: { title: 'Ortak tabana indir', logic: 'Sayıları hesaplamadan önce tabanlar arasında kuvvet ilişkisi ara.', works: 'Sadeleştirme, denklem ve karşılaştırmada.', risk: 'Toplama içinde üsleri birleştirmek.', steps: [['Parantezi düzelt', 'Negatif tabanı görünür kıl.'], ['Tabanları asal kuvvete çevir', 'Örneğin 8, 4 ve 2yi aynı tabanda yaz.'], ['İşleme uygun kuralı seç', 'Çarpma, bölüm, kuvvetin kuvveti.'], ['Yaklaşık kontrol yap', 'Sonucun işaret ve büyüklüğünü denetle.']] },
  traps: [t('Toplamada üs toplamak', '$2^3+2^4=2^7$.', '$2^3+2^4=8+16=24$.', 'Çarpım kuralını toplama taşımak.', 'İşlem işaretini kuraldan önce seslendir.'), t('Parantezi atlamak', '$(-2)^4=-16$.', '$(-2)^4=16$.', 'Eksi işaretini tabanın dışında okumak.', 'Çarpanları dört kez yaz.'), t('Negatif üssü negatif sonuç sanmak', '$2^{-3}=-8$.', '$2^{-3}=1/8$.', 'Üs işareti ile sayı işaretini karıştırmak.', 'Ters alma tanımını yaz.')],
  questions: [q('Temel', '$5^3\\cdot5^{-1}$ kaçtır?', ['5', '25', '125', '625'], 1, 'Aynı tabanda üsleri topla.', '$5^{3-1}=5^2=25$.', 'Negatif üssü sonucu negatif yapmak.', '125/5=25.'), q('Orta', '$(2^3)^4/2^5$ kaçtır?', ['64', '128', '256', '512'], 1, 'Kuvvetin kuvvetinde üsleri çarp.', '$2^{12-5}=2^7=128$.', '3+4 yapmak.', 'Üs sırası 7dir.'), q('Orta', '$4^7$ aşağıdakilerden hangisine eşittir?', ['$2^7$', '$2^{11}$', '$2^{14}$', '$8^7$'], 2, '$4=2^2$.', '$(2^2)^7=2^{14}$.', 'Tabanı değiştirip üssü aynı bırakmak.', 'Her iki tarafın logik üs yapısı aynıdır.'), q('İleri', '$2^x=32\\cdot4$ ise $x$ kaçtır?', ['5', '6', '7', '8'], 2, 'Sağ tarafı iki tabanında yaz.', '$32\\cdot4=2^5\\cdot2^2=2^7$, dolayısıyla $x=7$.', '32+4 hesaplamak.', '$2^7=128$.')],
  simulation: { passage: 'Bir veri dosyasının boyutu her sıkıştırma adımında yarıya iniyor. Başlangıç boyutu $2^{12}$ KBdir.', question: 'Beş adım sonra dosya kaç KB olur?', options: [['64', 'Bu $2^6$dır; bir adım eksik sayılmıştır.'], ['128', '$2^{12}/2^5=2^7=128$.'], ['256', 'Bu yalnız dört kez yarıya inmeye karşılık gelir.'], ['2048', 'Bu bir kez yarıya inmiş değerdir.']], answer: 1, stemAnalysis: 'Her yarıya inme 2ye bölmek, yani üsten 1 eksiltmektir.', criticalPoint: 'Beş adım toplamda $2^5$e bölmedir.', takeaway: 'Tekrarlı değişimi tek bir üs işlemiyle göster.' },
  summary: ['Aynı tabanlı çarpımda üsler toplanır.', 'Bölümde üsler çıkarılır ve taban sıfır olamaz.', 'Kuvvetin kuvvetinde üsler çarpılır.', 'Negatif üs tersini alır.', '$a^0=1$ yalnız $a\\ne0$ için.', 'Toplamada üs birleştirme kuralı yoktur.'],
  nextBody: 'Kesirli üs ve ana karekök ilişkisiyle köklü sayılara geç.',
}, 8)

const radicals = buildTopic({
  topic: 'Köklü Sayılar',
  subtitle: 'Karekökü ana değer ve tanım koşuluyla kullan; kök içini çarpan yapısıyla sadeleştir.',
  prerequisites: [{ topic: 'Üslü Sayılar', why: 'Kesirli üs ve çarpan yapısı gerekir.' }],
  connections: ['Çarpanlara Ayırma', 'Denklem Çözme', 'Özel Üçgenler (Dik, İkizkenar, Eşkenar)'],
  mapCore: 'Kökün tanımını, sadeleştirmeyi ve karşılaştırmayı gerçek sayılar üzerinde yönetir.',
  introduction: '$\\sqrt a$, karesi $a$ olan negatif olmayan sayıdır. Kök sembolü iki işaretli cevap değil, ana karekökü gösterir.',
  tytUse: 'Uzunluk, alan, irrasyonel karşılaştırma ve cebirsel sadeleştirme içinde kullanılır.',
  struggle: '$\\sqrt{x^2}=x$ sanmak; toplamı köklere ayırmak; tanım koşulunu atlamak.',
  osymBody: 'Köklü sayılar düzenli biçimde işlem, sıralama veya geometri bağlantısıyla ölçülür.',
  osymMeasures: ['Ana kök', 'Kök dışına çıkarma', 'Tanım kümesi', 'Karşılaştırma'],
  patternBody: 'Alan-uzunluk, sayı doğrusu, yaklaşık değer ve eşdeğer ifade biçimleri kullanılır.',
  patterns: ['Sadeleştirme', 'Payda düzenleme', 'Uzunluk', 'Karşılaştırma'],
  readiness: [r('$\\sqrt{49}$ kaçtır?', '$7$.', 'Ana karekökün negatif olmadığını hatırla.'), r('$\\sqrt{12}$ sadeleşir mi?', '$2\\sqrt3$.', 'Tam kare çarpan ara.'), r('$\\sqrt{x-2}$ gerçek sayı ise $x$ için ne gerekir?', '$x\\ge2$.', 'Çift dereceli kökte kök içini negatif yapma.')],
  concepts: [c('Ana karekök', '$\\sqrt a\\ge0$ ve $(\\sqrt a)^2=a$dır.', 'Kök sembolünün tek değerini belirler.', '$a\\ge0$ gerçek sayılar için.'), c('Kök dışına çıkarma', '$\\sqrt{k^2a}=|k|\\sqrt a$.', 'Tam kare çarpanı sadeleştirir.', '$k$ negatif olabilir; bu yüzden mutlak değer gerekir.'), c('Benzer köklüler', '$p\\sqrt a$ ve $q\\sqrt a$ katsayıları toplanabilir.', 'Toplama-çıkarma için ortak kök yapısını gösterir.', 'Kök içleri farklıysa önce sadeleştirme yapılır.')],
  why: { question: 'Neden $\\sqrt{a+b}=\\sqrt a+\\sqrt b$ değildir?', body: 'Sağ tarafın karesi $a+b+2\\sqrt{ab}$ olur; ek çapraz terim genellikle sıfır değildir. Örneğin $\\sqrt9=3$ iken $\\sqrt4+\\sqrt5>4$ olur.', boundary: 'Çarpım kuralı uygun tanım koşullarında çalışır; toplama için benzer bir dağılım yoktur.' },
  formulas: [{ title: 'Kök-üs ilişkisi', latex: '\\sqrt[n]{a}=a^{1/n}', meaning: 'Köklü ifade kesirli üs olarak okunabilir.', condition: 'Çift $n$ için gerçek sayılarda $a\\ge0$.' }],
  certainInfo: '$\\sqrt{x^2}=|x|$; ana karekök negatif değer vermez.',
  examples: [e('Kök dışına çıkar', '$\\sqrt{180}$', [['Tam kareyi ayır', '$180=36\\cdot5$.'], ['Kökü al', '$6\\sqrt5$.']], '$6\\sqrt5$', 'En büyük tam kare çarpan işlemi kısaltır.', 'Karesi 180 olan pozitif değeri temsil eder.'), e('Benzer köklüleri birleştir', '$3\\sqrt8-\\sqrt{18}$', [['Sadeleştir', '$3\\cdot2\\sqrt2-3\\sqrt2$.'], ['Birleştir', '$3\\sqrt2$.']], '$3\\sqrt2$', 'Önce kök içlerini ortaklaştır.', 'Yaklaşık değer 4,24tür.'), e('Paydayı düzenle', '$\\frac{4}{\\sqrt2}$', [['Birle çarp', '$\\frac{4\\sqrt2}{2}$.'], ['Sadeleştir', '$2\\sqrt2$.']], '$2\\sqrt2$', 'Değeri değiştirmeden paydada kökü kaldır.', 'İki ifadenin kareleri 8dir.'), e('Karşılaştır', '$\\sqrt{50}$ hangi iki ardışık tam sayı arasındadır?', [['Kareleri sınırla', '$7^2=49<50<64=8^2$.']], '$7<\\sqrt{50}<8$', 'Yaklaşık hesap yerine komşu tam kareleri kullan.', 'Karekök artan fonksiyondur.')],
  tactic: { title: 'Tam kare avı', logic: 'Kök içini asal çarpanlara veya uygun tam kare çarpana ayır.', works: 'Sadeleştirme, toplama ve karşılaştırmada.', risk: 'Kökü toplama üzerine dağıtmak.', steps: [['Tanım koşulunu yaz', 'Çift dereceli kök içi negatif olamaz.'], ['Tam kare çarpanı ayır', '4,9,16,25,36…'], ['Benzer yapıları birleştir', 'Aynı kök içi oluştu mu?'], ['Kareyle kontrol et', 'İşaret ve büyüklüğü doğrula.']] },
  traps: [t('Kökü toplama dağıtmak', '$\\sqrt{4+5}=2+\\sqrt5$.', '$\\sqrt9=3$.', 'Çarpım kuralını toplama taşımak.', 'Basit sayısal karşı örnek kullan.'), t('Çift işaret vermek', '$\\sqrt{25}=\\pm5$.', '$\\sqrt{25}=5$.', '$x^2=25$ denklemiyle kök sembolünü karıştırmak.', 'Sembolün ana kökü gösterdiğini hatırla.'), t('Mutlak değeri unutmak', '$\\sqrt{x^2}=x$.', '$\\sqrt{x^2}=|x|$.', 'Negatif x durumunu sınamamak.', '$x=-2$ koy.')],
  questions: [q('Temel', '$\\sqrt{72}$ nedir?', ['$3\\sqrt8$', '$6\\sqrt2$', '$8\\sqrt2$', '$12\\sqrt2$'], 1, '$72=36\\cdot2$.', '$\\sqrt{72}=6\\sqrt2$.', 'Tam kareyi eksik çıkarmak.', 'Karesi 72dir.'), q('Orta', '$\\sqrt{27}+\\sqrt{12}$ kaçtır?', ['$3\\sqrt3$', '$5\\sqrt3$', '$7\\sqrt3$', '$\\sqrt{39}$'], 1, 'İki kökü sadeleştir.', '$3\\sqrt3+2\\sqrt3=5\\sqrt3$.', 'Kök içlerini toplamak.', 'Yaklaşık 8,66.'), q('Orta', '$\\sqrt{x-1}$ gerçek sayı olduğuna göre en küçük tam sayı $x$ kaçtır?', ['-1', '0', '1', '2'], 2, 'Kök içi negatif olamaz.', '$x-1\\ge0\\Rightarrow x\\ge1$.', 'Kökün pozitif olmak zorunda olduğunu sanmak.', '$x=1$ kökü 0 yapar ve tanımlıdır.'), q('İleri', '$\\frac{1}{\\sqrt3-1}$ ifadesinin eşiti hangisidir?', ['$\\frac{\\sqrt3+1}{2}$', '$\\sqrt3+1$', '$\\frac{\\sqrt3-1}{2}$', '$2(\\sqrt3+1)$'], 0, 'Eşlenikle çarp.', 'Pay ve paydayı $\\sqrt3+1$ ile çarpınca payda $3-1=2$ olur.', 'Paydayı toplama gibi karelemek.', 'Geri çarpınca 1 verir.')],
  simulation: { passage: 'Alanı 98 m² olan kare biçimli bir bahçenin bir kenarı, alanı 8 m² olan kare taşın bir kenarının kaç katıdır?', question: 'Oran kaçtır?', options: [['$\\frac72$', '$\\sqrt{98}/\\sqrt8=\\sqrt{49/4}=7/2$.'], ['$\\frac{49}{4}$', 'Bu alanların oranıdır, kenarların değil.'], ['$\\frac{7}{4}$', 'Karekök oranı eksik sadeleştirilmiştir.'], ['$\\sqrt{90}$', 'Kökler çıkarılmaz.']], answer: 0, stemAnalysis: 'Karenin kenarı alanın kareköküdür.', criticalPoint: '$\\sqrt{98}/\\sqrt8=7/2$.', takeaway: 'Alan oranı ile uzunluk oranını ayır.' },
  summary: ['$\\sqrt a$ ana, negatif olmayan köktür.', '$\\sqrt{x^2}=|x|$.', 'Kök dışına yalnız tam kare çarpan çıkar.', 'Benzer köklüler katsayılarıyla toplanır.', 'Kök toplama üzerine dağılmaz.', 'Çift dereceli kökte tanım koşulunu önce yaz.'],
  nextBody: 'Kök sadeleştirmesinde kullandığın çarpan yapısını cebirsel ifadelere taşı.',
}, 9)

const factoring = buildTopic({
  topic: 'Çarpanlara Ayırma',
  subtitle: 'Toplamı çarpıma dönüştür; ortak çarpanı ve özdeşlik yapısını seçmeden önce görünür kıl.',
  prerequisites: [{ topic: 'Üslü Sayılar', why: 'Kuvvet ve işaret bilgisi gerekir.' }],
  connections: ['Denklem Çözme', 'Fonksiyonlar (Temel)', 'Analitik Geometri (Nokta - Doğru)'],
  mapCore: 'Cebirsel ifadeyi çarpanların çarpımı olarak yeniden yazar ve sıfır çarpımını kullanır.',
  introduction: 'Çarpanlara ayırma, dağıtma işleminin tersidir. Amaç ifadeyi yalnız kısaltmak değil, kökleri, işareti ve ortak yapıyı görünür yapmaktır.',
  tytUse: 'Denklem, sadeleştirme, alan modeli ve özdeşlik tanıma sorularında yardımcı omurgadır.',
  struggle: 'Ortak çarpanı atlamak, işaretleri karıştırmak ve sadeleştirmede paydanın sıfır olma koşulunu unutmak.',
  osymBody: 'Çarpanlara ayırma çoğu zaman tek başına etiketlenmez; denklem, fonksiyon ve rasyonel ifade içinde kullanılır.',
  osymMeasures: ['Ortak çarpan', 'Özdeşlik tanıma', 'Sıfır çarpımı', 'Tanım koşulu'],
  patternBody: 'Alan parçaları, harfli ifade, kök bulma ve eşdeğerlik seçeneği olarak görünür.',
  patterns: ['Ortak çarpan', 'İki kare farkı', 'Tam kare', 'İkinci derece üç terim'],
  readiness: [r('$3x+6$ ifadesinde ortak çarpan nedir?', '$3$; ifade $3(x+2)$ olur.', 'Dağılma özelliğini ters yönde kullan.'), r('$a^2-b^2$ nasıl ayrılır?', '$(a-b)(a+b)$.', 'İki kare farkı özdeşliğini tekrar et.'), r('$x^2+5x+6$ için çarpımı 6, toplamı 5 olan sayılar nedir?', '$2$ ve $3$.', 'İkinci derece üç terim yöntemine hazırlık yap.')],
  concepts: [c('Ortak çarpan', 'Her terimde bulunan en büyük ortak cebirsel çarpandır.', 'İlk ve çoğu kez en güvenli adımdır.', 'Tüm terimlere bölünmeyen ifade dışarı alınamaz.'), c('Özdeşlik', 'Değişkenlerin her uygun değeri için doğru olan eşitliktir.', 'Örüntüyü tek hamlede çarpıma çevirir.', 'Benzer görünen toplam ve farklar aynı kalıba girmez.'), c('Sıfır çarpım ilkesi', '$AB=0$ ise $A=0$ veya $B=0$dır.', 'Çarpanlara ayrılmış denklemin köklerini verir.', 'Sağ taraf sıfır değilse doğrudan uygulanmaz.')],
  why: { question: 'Neden $a^2-b^2=(a-b)(a+b)$ olur?', body: 'Sağ tarafı dağıtırsak $a^2+ab-ab-b^2=a^2-b^2$; çapraz terimler birbirini yok eder.', boundary: '$a^2+b^2$ gerçek sayılarda aynı biçimde çarpanlara ayrılmaz.' },
  formulas: [{ title: 'Temel özdeşlikler', latex: '(a\\pm b)^2=a^2\\pm2ab+b^2,\\quad a^2-b^2=(a-b)(a+b)', meaning: 'Tam kare ve iki kare farkı kalıplarıdır.', condition: 'Orta terimin işareti ve $2ab$ katsayısı kontrol edilir.' }],
  certainInfo: 'Çarpanlara ayırdıktan sonra ifadeyi yeniden dağıtarak özgün ifadeyi elde etmek en hızlı doğrulamadır.',
  examples: [e('Ortak çarpan', '$6x^3-9x^2$', [['Ortak yapıyı bul', 'Katsayılarda 3, değişkende $x^2$.'], ['Dışarı al', '$3x^2(2x-3)$.']], '$3x^2(2x-3)$', 'Her zaman önce ortak çarpanı kontrol et.', 'Dağıtınca özgün ifade gelir.'), e('İki kare farkı', '$9x^2-25$', [['Kareleri gör', '$(3x)^2-5^2$.'], ['Ayır', '$(3x-5)(3x+5)$.']], '$(3x-5)(3x+5)$', 'Toplam-fark eşlenikleri çapraz terimi yok eder.', 'Dağıtarak doğrula.'), e('Üç terim', '$x^2-x-12$', [['Sayıları seç', 'Çarpım -12, toplam -1: -4 ve 3.'], ['Ayır', '$(x-4)(x+3)$.']], '$(x-4)(x+3)$', 'İşaretleri toplam koşuluyla denetle.', 'Kökler 4 ve -3tür.'), e('Sadeleştirme ve koşul', '$\\frac{x^2-9}{x-3}$', [['Payı ayır', '$(x-3)(x+3)$.'], ['Sadeleştir', '$x+3$.'], ['Koşul', 'Özgün payda nedeniyle $x\\ne3$.']], '$x+3,\ x\\ne3$', 'Sadeleşen çarpan tanım yasağını silmez.', '$x=4$ için iki ifade de 7dir.' )],
  tactic: { title: 'Önce ortak, sonra kalıp', logic: 'Terimlerin tümünde ortak parça aramadan özel özdeşliğe atlama.', works: 'Çok terimli ifadeler, denklemler ve sadeleştirmede.', risk: 'Toplam içindeki terimleri tek tek sadeleştirmek.', steps: [['Ortak çarpanı ara', 'Katsayı ve en küçük üs.'], ['Terim sayısını say', 'İki terim mi, üç terim mi?'], ['Kalıbı doğrula', 'Kareler ve orta terim.'], ['Geri dağıt', 'İşaretleri kontrol et.']] },
  traps: [t('Kareler toplamını ayırmak', '$a^2+b^2=(a-b)(a+b)$.', 'Bu çarpım $a^2-b^2$ verir.', 'Fark işaretini görmemek.', 'Dağıtma kontrolü yap.'), t('Orta terimi unutmak', '$(a+b)^2=a^2+b^2$.', '$(a+b)^2=a^2+2ab+b^2$.', 'Kareyi terimlere dağıtmak.', 'Binomları çarp.'), t('Yasak değeri kaybetmek', 'Sadeleşince her x geçerlidir.', 'Özgün paydadan gelen yasak değer korunur.', 'Sadeleştirmeyi eşit fonksiyon sanmak.', 'Özgün paydayı sıfır yapan değeri yaz.')],
  questions: [q('Temel', '$4x^2-12x$ nasıl ayrılır?', ['$4x(x-3)$', '$4(x^2-3)$', '$x(4x-12x)$', '$2x(2x-12)$'], 0, 'En büyük ortak çarpan $4x$tir.', '$4x^2-12x=4x(x-3)$.', 'Yalnız katsayıyı dışarı almak.', 'Dağıt.'), q('Orta', '$x^2-16$ hangisidir?', ['$(x-4)^2$', '$(x-8)(x+2)$', '$(x-4)(x+4)$', '$(x-16)(x+1)$'], 2, 'İki kare farkı.', '$x^2-4^2=(x-4)(x+4)$.', 'Tam kareyle karıştırmak.', 'Çarpanları dağıt.'), q('Orta', '$x^2+7x+12$ nasıl ayrılır?', ['$(x+3)(x+4)$', '$(x+2)(x+6)$', '$(x-3)(x-4)$', '$(x+1)(x+12)$'], 0, 'Çarpım 12, toplam 7.', '3 ve 4 seçilir.', 'Yalnız çarpımı kontrol etmek.', 'Orta terim 7x gelir.'), q('İleri', '$x^3-4x=0$ denkleminin kaç farklı gerçek kökü vardır?', ['1', '2', '3', '4'], 2, 'Ortak çarpan ve kare farkı.', '$x(x^2-4)=x(x-2)(x+2)=0$; kökler -2,0,2.', 'Yalnız $x=0$ı almak.', 'Üç kökü yerine koy.')],
  simulation: { passage: 'Kenarları $x+3$ ve $x-3$ metre olan dikdörtgenin alanı $x^2-9$ m²dir. $x>3$ kabul ediliyor.', question: 'Alan 40 m² ise uzun kenar kaç metredir?', options: [['5', '$x-3$ kısa kenardır.'], ['8', '$x^2=49\\Rightarrow x=7$ ve uzun kenar $10$dur; 8 değildir.'], ['10', '$x=7$, dolayısıyla $x+3=10$.'], ['14', 'Bu iki kenarın toplamıdır.']], answer: 2, stemAnalysis: 'Alan iki kare farkı olarak çarpanlara ayrılmıştır.', criticalPoint: '$x^2-9=40\\Rightarrow x^2=49$; $x>3$ nedeniyle $x=7$.', takeaway: 'Cebirsel kökü bağlam koşuluyla seç.' },
  summary: ['İlk kontrol ortak çarpandır.', '$a^2-b^2=(a-b)(a+b)$.', 'Tam karede orta terim $\\pm2ab$dir.', 'Üç terimde çarpım ve toplam birlikte kontrol edilir.', 'Sıfır çarpım ilkesi yalnız sağ taraf sıfırken kullanılır.', 'Sadeleşen paydanın yasak değeri korunur.'],
  nextBody: 'Çarpan yapısını doğrusal ve ikinci derece denklemlerin çözümünde kullan.',
}, 10)

const ratio = buildTopic({
  topic: 'Oran - Orantı',
  subtitle: 'İki niceliği aynı birimde karşılaştır; doğru ve ters değişimi tabloyla ayır.',
  prerequisites: [{ topic: 'Rasyonel Sayılar', why: 'Kesir ve sadeleştirme gerekir.' }],
  connections: ['Problemler', 'Benzerlik', 'İstatistik ve Veri Analizi'],
  mapCore: 'Nicelikler arasındaki göreli büyüklüğü ve birlikte değişimi oranla modeller.',
  introduction: 'Oran, iki niceliğin bölümüdür; birimsiz olması için nicelikler aynı türe ve birime getirilir. Orantı iki oranın eşitliğidir.',
  tytUse: 'Karışım, ölçek, hız, iş, yüzde ve tablo yorumunda temel modeldir.',
  struggle: 'Sırayı ters kurmak, birimleri eşitlememek ve her ilişkiyi doğru orantı sanmak.',
  osymBody: 'Oran-orantı çoğunlukla problem gövdesinde görünür ve birkaç koşulu aynı tabloda izletir.',
  osymMeasures: ['Oran sırası', 'Birim dönüşümü', 'Doğru/ters orantı', 'Ölçekleme'],
  patternBody: 'Tablo, karışım, harita ölçeği, üretim ve paylaşım bağlamları öne çıkar.',
  patterns: ['Paylaşım', 'Karışım', 'Ölçek', 'Doğru-ters değişim'],
  readiness: [r('6nın 9a oranı nedir?', '$6/9=2/3$.', 'Oran sırasını sözcük sırasıyla yaz.'), r('2 metre kaç santimetredir?', '200 cm.', 'Oran öncesi birimleri eşitle.'), r('İşçi sayısı artarken aynı işin süresi nasıl değişir?', 'Diğer koşullar sabitse ters orantılı azalır.', 'Doğru ve ters değişimi ayır.')],
  concepts: [c('Oran', '$a$ niceliğinin $b$ niceliğine oranı $a/b$dir.', 'Mutlak değer yerine göreli büyüklük verir.', '$b\\ne0$; sıra önemlidir.'), c('Doğru orantı', '$y=kx$ biçimidir ve $y/x$ sabittir.', 'Bir nicelik kaç kat olursa diğeri de aynı kat olur.', 'Başlangıçta sabit ek terim varsa ilişki doğru orantı olmayabilir.'), c('Ters orantı', '$xy=k$ biçimidir.', 'Biri artarken aynı çarpımı korumak için diğeri azalır.', 'Diğer koşulların sabit olduğu varsayımı açık olmalıdır.')],
  why: { question: 'Neden oranda birimleri eşitlemek gerekir?', body: '2 metre ile 50 santimetreyi 2/50 yazmak birim ölçeklerini karıştırır. 200 cm/50 cm=4, gerçek karşılaştırmayı verir.', boundary: 'Hız gibi türetilmiş oranlarda birim kalabilir; amaç iki aynı tür niceliği karşılaştırırken ortak birim kullanmaktır.' },
  formulas: [{ title: 'Orantının temel özelliği', latex: '\\frac ab=\\frac cd\\Rightarrow ad=bc', meaning: 'Paydalar sıfır değilken içler-dışlar çarpımı eşittir.', condition: '$b,d\\ne0$.' }],
  certainInfo: 'Bir oranı genişletmek her iki terimi aynı sıfır olmayan sayı ile çarpmaktır; yalnız bir terimi değiştirmek oranı değiştirir.',
  examples: [e('Oranla paylaşım', '180 TL, 2:3:4 oranında paylaştırılıyor. En büyük pay kaç TLdir?', [['Toplam parça', '$2+3+4=9$.'], ['Birim parça', '$180/9=20$.'], ['En büyük pay', '$4\\cdot20=80$.']], '80 TL', 'Oran terimleri miktar değil parça sayısıdır.', '40+60+80=180.'), e('Doğru orantı', '5 defter 90 TL ise aynı fiyattan 8 defter kaç TLdir?', [['Birim fiyat', '$90/5=18$.'], ['Ölçekle', '$8\\cdot18=144$.']], '144 TL', 'Birim oran güvenli kontrol sağlar.', '$144/8=18$.'), e('Ters orantı', '6 işçi bir işi 15 günde bitiriyorsa aynı hızla 10 işçi kaç günde bitirir?', [['Sabit iş', '$6\\cdot15=10\\cdot t$.'], ['Çöz', '$t=9$.']], '9 gün', 'İşçi-gün çarpımı sabit kalır.', '$60$ işçi-gün iki durumda da aynıdır.'), e('Ölçek', '1:50 000 ölçekli haritada 3 cm kaç km gerçektir?', [['Gerçek cm', '$3\\cdot50\\,000=150\\,000$ cm.'], ['Kilometreye çevir', '$150\\,000$ cm = 1,5 km.']], '1,5 km', 'Ölçekten sonra birimi çevir.', '1 km=100 000 cm.' )],
  tactic: { title: 'Birim oranı sabitle', logic: 'Önce “bir birim için ne kadar?” veya “hangi çarpım sabit?” sorusunu cevapla.', works: 'Fiyat, karışım, ölçek, işçi ve hız bağlamında.', risk: 'İlişkinin doğrusal olmadığını kontrol etmeden içler-dışlar çarpımı yapmak.', steps: [['Oran sırasını yaz', 'İlk sözcük paya.'], ['Birimleri eşitle', 'Aynı ölçeğe getir.'], ['İlişki türünü seç', 'Oran mı çarpım mı sabit?'], ['Toplamla kontrol et', 'Paylaşımda parçalar bütünü vermeli.']] },
  traps: [t('Sırayı ters çevirmek', 'Anın Bye oranını $B/A$ yazmak.', '$A/B$ yazılır.', 'Sözel sırayı izlememek.', 'Oranı cümleyle yeniden oku.'), t('Ters ilişkiyi doğru sanmak', 'İşçi iki kat olunca süre de iki kat olur.', 'Aynı işte süre yarıya iner.', 'Artış sözcüğünü otomatik doğru orantı saymak.', 'Toplam işçi-günü kontrol et.'), t('Birim karıştırmak', '3 km/500 m = 3/500.', '3000/500=6.', 'Ölçüleri dönüştürmemek.', 'Orandaki birimleri sadeleştir.')],
  questions: [q('Temel', '$a:b=3:5$ ve $a=21$ ise $b$ kaçtır?', ['28', '30', '35', '42'], 2, '3 parça 21 ise bir parça 7.', '$b=5\\cdot7=35$.', '21i 5le çarpmak.', '$21/35=3/5$.'), q('Orta', '240 sayısı 1:3 oranında bölünürse büyük parça kaçtır?', ['60', '120', '160', '180'], 3, 'Toplam 4 parça.', '$240/4=60$, büyük parça $3\\cdot60=180$.', 'Oran terimini doğrudan 240la çarpmak.', '60+180=240.'), q('Orta', '12 musluk özdeş hızla bir depoyu 10 saatte dolduruyor. 15 musluk kaç saatte doldurur?', ['6', '8', '12', '12,5'], 1, 'Ters orantı.', '$12\\cdot10=15t\\Rightarrow t=8$.', 'Musluk artınca süreyi artırmak.', '$120$ musluk-saat.'), q('İleri', 'Bir karışımda su:şurup=7:3tür. Karışıma yalnız 20 L su eklenince oran 3:1 oluyor. Başta kaç L şurup vardır?', ['15', '20', '30', '40'], 2, 'Başlangıcı 7k ve 3k yaz.', '$(7k+20)/(3k)=3\\Rightarrow7k+20=9k\\Rightarrow k=10$; şurup 30 L.', 'Yeni toplamı oran paydasına koymak.', 'Su 90, şurup 30; oran 3.' )],
  simulation: { passage: 'Bir uygulama arayüzü 360 piksel genişliğinde tasarlanıyor. Birinci ve ikinci sütun genişlikleri 5:4, aralarındaki boşluk 36 pikseldir.', question: 'Birinci sütun kaç pikseldir?', options: [['144', 'Bu ikinci sütunun genişliğidir.'], ['160', 'Kullanılabilir genişlik 324; 5/9u 180dir.'], ['180', '$(360-36)\\cdot5/9=180$.'], ['200', 'Boşluğu oran parçalarına katmıştır.']], answer: 2, stemAnalysis: 'Önce oranla paylaşılmayan sabit boşluk çıkarılır.', criticalPoint: 'Sütunlara kalan 324 piksel 5+4=9 parçadır.', takeaway: 'Oran dışındaki sabit miktarı paylaşım öncesi ayır.' },
  summary: ['Oran sırası önemlidir ve payda sıfır olamaz.', 'Aynı tür nicelikleri ortak birime getir.', 'Doğru orantıda bölüm, ters orantıda çarpım sabittir.', 'Paylaşımda oran terimlerini topla.', 'Ölçekte önce çarp, sonra birimi dönüştür.', 'Sonuç bütünü ve birimleri sağlamalıdır.'],
  nextBody: 'Oran modelini yüzde, karışım, hız ve iş problemleri içinde genişlet.',
}, 11)

const equations = buildTopic({
  topic: 'Denklem Çözme',
  subtitle: 'Eşitliği koruyan dönüşümleri seç; aday kökleri tanım ve bağlam koşuluyla denetle.',
  prerequisites: [{ topic: 'Çarpanlara Ayırma', why: 'İkinci derece denklemlerde çarpan ve sıfır çarpımı gerekir.' }],
  connections: ['Problemler', 'Fonksiyonlar (Temel)', 'Analitik Geometri (Nokta - Doğru)'],
  mapCore: 'Bilinmeyen değerleri eşitliği koruyan adımlarla bulur; yabancı kökü eler.',
  introduction: 'Denklem, iki ifadenin hangi değerlerde eşit olduğunu sorar. Çözüm adımları eşitliğin iki tarafına aynı geçerli işlemi uygulamalıdır.',
  tytUse: 'Sözel model, oran, mutlak değer, köklü ifade ve fonksiyon sorularının çözüm motorudur.',
  struggle: '“Karşıya atma”yı gerekçesiz işaret değiştirme sanmak, paydayı sıfır yapan değeri almak ve karesini alırken yabancı kök üretmek.',
  osymBody: 'Doğrudan denklem sayısı sınırlı olsa da hemen her problem türünde denklem kurma ve çözme kullanılır.',
  osymMeasures: ['Eşitlik koruma', 'Model kurma', 'Kök kontrolü', 'İkinci derece temel'],
  patternBody: 'Terazi, tablo, sayı ilişkisi, parça-bütün ve tanım kümesi içinde görünür.',
  patterns: ['Doğrusal denklem', 'Kesirli denklem', 'Çarpanlara ayrılan ikinci derece', 'Kök kontrolü'],
  readiness: [r('$3x+2=14$ ise $x$ kaçtır?', '$4$.', 'Ters işlemleri eşitliğin iki tarafına uygula.'), r('$x^2=9$ ise kökler nedir?', '$x=3$ veya $x=-3$.', 'Kare denkleminin iki işaretini hatırla.'), r('$\\frac1{x-2}$ ifadesinde hangi değer yasaktır?', '$x=2$.', 'Paydayı sıfır yapan değeri baştan dışla.')],
  concepts: [c('Denklemin kökü', 'Denklemi doğru eşitliğe dönüştüren değişken değeridir.', 'Çözüm kümesinin elemanını tanımlar.', 'Tanım kümesi dışında kalan değer kök değildir.'), c('Eşdeğer denklem', 'Aynı çözüm kümesine sahip denklemlerdir.', 'Güvenli dönüşümün hedefidir.', 'Karesini alma gibi işlemler tek yönlü olabilir ve yabancı kök üretebilir.'), c('İkinci derece denklem', '$ax^2+bx+c=0$, $a\\ne0$ biçimidir.', 'İki köklü, tek köklü veya gerçek köksüz temel modeli verir.', 'Çarpanlara ayırma mümkün değilse diskriminant kullanılabilir.')],
  why: { question: 'Neden denklemin iki tarafına aynı sayı eklemek çözümü değiştirmez?', body: 'Eşit iki miktar aynı kadar ötelenirse eşitlik korunur: $A=B$ ise $A+c=B+c$. Terazi benzetmesinde iki kefeye aynı ağırlığı eklemek dengeyi bozmaz.', boundary: 'İki tarafı değişkene bağlı ve sıfır olabilecek ifadeye bölmek kök kaybettirebilir.' },
  formulas: [{ title: 'İkinci derece kök formülü', latex: 'x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}', meaning: '$ax^2+bx+c=0$ denkleminin gerçek/karmaşık köklerini verir.', condition: '$a\\ne0$; TYT düzeyinde çoğu soru çarpan yapısı veya diskriminant yorumu kullanır.' }],
  certainInfo: 'Paydalı, köklü veya karesi alınmış denklemlerde bulunan her aday özgün denklemde kontrol edilmelidir.',
  examples: [e('Doğrusal denklem', '$4(2x-1)=3x+11$', [['Parantezi aç', '$8x-4=3x+11$.'], ['Topla-çıkar', '$5x=15$.'], ['Böl', '$x=3$.']], '$3$', 'Her adımı iki tarafa uygulanan işlem olarak düşün.', '$4(5)=20$ ve sağ taraf 20.'), e('Kesirli denklem', '$\\frac{x+1}{x-2}=2$', [['Yasak değer', '$x\\ne2$.'], ['Çarp', '$x+1=2x-4$.'], ['Çöz', '$x=5$.']], '$5$', 'Tanım koşulunu çözümden önce yaz.', '5 yasak değildir ve eşitliği sağlar.'), e('İkinci derece', '$x^2-5x+6=0$', [['Çarpanlara ayır', '$(x-2)(x-3)=0$.'], ['Sıfır çarpımı', '$x=2$ veya $x=3$.']], '$\\{2,3\\}$', 'Sağ taraf sıfırken çarpanları ayrı sıfırla.', 'Her iki kökü yerine koy.'), e('Yabancı kök kontrolü', '$\\sqrt{x+1}=x-1$', [['Tanım ve işaret', '$x\\ge1$.'], ['Kare al', '$x+1=x^2-2x+1\\Rightarrow x(x-3)=0$.'], ['Adayları ele', '$x=0$ koşul dışı; $x=3$ geçerli.']], '$3$', 'Kare alma aday üretir, özgün denklem karar verir.', '$\\sqrt4=2=3-1$.' )],
  tactic: { title: 'Koşul–dönüşüm–kontrol', logic: 'İşlemden önce tanım koşulunu, işlemden sonra aday kontrolünü yaz.', works: 'Paydalı, köklü, mutlak değerli ve ikinci derece denklemlerde.', risk: 'Sıfır olabilecek ifadeye bölerek kök kaybetmek.', steps: [['Tanım koşulunu çıkar', 'Payda ve kök içi.'], ['Denklemi sadeleştir', 'Parantez, ortak payda, çarpan.'], ['Adayları bul', 'Eşdeğer adımları kullan.'], ['Özgün denklemde dene', 'Yasak ve yabancı kökleri ele.']] },
  traps: [t('Karşıya atmayı sihir saymak', 'Terim taraf değiştirince sebepsiz işaret değiştirir.', 'İki taraftan aynı terim çıkarılır.', 'İşlemi yazmamak.', 'Ara eşitliği göster.'), t('Sıfıra bölmek', '$x(x-2)=0$ı x ile bölüp yalnız 2yi bulmak.', '$x=0$ veya $x=2$.', 'x sıfır olasılığını bölerek silmek.', 'Önce sıfır çarpımı kullan.'), t('Adayı kök sanmak', 'Karesi alınan denklemde çıkan her değer köktür.', 'Her aday özgün denklemde denenir.', 'Tek yönlü işlemi eşdeğer sanmak.', 'Yerine koyma yap.')],
  questions: [q('Temel', '$7x-5=23$ ise $x$ kaçtır?', ['3', '4', '5', '6'], 1, 'Önce 5 ekle.', '$7x=28\\Rightarrow x=4$.', '23-5 yapmak.', '$28-5=23$.'), q('Orta', '$\\frac{2x-1}{3}=5$ ise $x$ kaçtır?', ['7', '8', '9', '10'], 1, 'Üçle çarp.', '$2x-1=15\\Rightarrow2x=16\\Rightarrow x=8$.', 'Paydayı yalnız bir terime uygulamak.', '$(16-1)/3=5$.'), q('Orta', '$x^2+x-12=0$ köklerinin toplamı kaçtır?', ['-4', '-1', '1', '4'], 1, 'Çarpanlara ayır veya $-b/a$ kullan.', '$(x+4)(x-3)=0$; kökler -4 ve 3, toplam -1.', 'İşaretleri ters almak.', 'Vieta toplamı -1dir.'), q('İleri', '$\\frac{x}{x-1}=\\frac2{x-1}$ denkleminin çözümü nedir?', ['$x=1$', '$x=2$', '$x=1,2$', 'Çözüm yok'], 1, 'Önce $x\\ne1$.', 'Ortak payda sıfır değilken $x=2$; geçerlidir.', 'Paydayı sıfır yapan 1i kök almak.', '$2/(1)=2/(1)$.' )],
  simulation: { passage: 'Bir üyelikte sabit 120 TL ücret ve kullanım başına 18 TL alınmaktadır. Toplam ödeme 300 TLdir.', question: 'Kaç kullanım yapılmıştır?', options: [['8', 'Toplam 264 TL olur.'], ['9', 'Toplam 282 TL olur.'], ['10', '$120+18\\cdot10=300$.'], ['12', 'Toplam 336 TL olur.']], answer: 2, stemAnalysis: 'Sabit ve değişken maliyet ayrı terimlerdir.', criticalPoint: '$120+18n=300\\Rightarrow18n=180\\Rightarrow n=10$.', takeaway: 'Denklem kökünü birim ve bağlamla doğrula.' },
  summary: ['Denklemin kökü özgün eşitliği sağlayan değerdir.', 'Her adım eşitliğin iki tarafına uygulanır.', 'Payda sıfır olamaz; koşulu baştan yaz.', 'Sıfır çarpım ilkesi çarpanlara ayrılmış denklemi çözer.', 'Kare alma yabancı kök üretebilir.', 'Adayları özgün denklemde kontrol et.'],
  nextBody: 'Denklem kurma becerisini yaş, yüzde, hareket, iş ve karışım problemlerine taşı.',
}, 12)

export const ADDITIONAL_ALGEBRA_LESSONS = [inequalities, absoluteValue, exponents, radicals, factoring, ratio, equations]
