import { defineLesson, option, step } from './catalog-helpers.js'

const temelKavramlar = defineLesson({
  topic: 'Temel Kavramlar',
  subtitle: 'Sayı kümelerini, işlem dilini ve tek-çift düşünmesini ezber listesi olmadan kur.',
  minutes: 70,
  prerequisites: [
    { topic: 'Dört işlem', why: 'İşlem önceliğini ve işaretleri güvenle uygulamak gerekir.' },
    { topic: 'Sayı doğrusu', why: 'Sıralama, aralık ve uzaklık bu model üzerinde okunur.' },
  ],
  connections: ['Sayı Basamakları', 'Basit Eşitsizlikler', 'Problemler'],
  mapCore: 'Sayıların hangi kümeye ait olduğunu, nasıl sıralandığını ve işlem sonucunun hangi özelliği taşıdığını açıklar.',
  openingLead: 'Temel kavramlar “ilk birkaç kolay soru” değildir; sonraki her çözümün dilidir.',
  introduction: `Bir sayının değerini bilmek başka, o sayının hangi özellikleri taşıdığını bilmek başkadır. $-3$ bir tam sayıdır; aynı zamanda rasyonel ve gerçektir ama doğal sayı değildir. Bu iç içe yapı, bir sorudaki “tam sayı”, “pozitif”, “tek” veya “ardışık” koşullarının çözüm uzayını nasıl daralttığını gösterir.

İşlem önceliği de yazım dilinin parçasıdır. Parantez önce, sonra üs, çarpma-bölme ve en son toplama-çıkarma uygulanır; aynı öncelikteki işlemler soldan sağa yürür. Kuralın amacı herkesin aynı ifadeyi aynı şekilde okumasıdır.`,
  tytUse: 'ÖSYM sayı özelliğini çoğu kez yeni tanımlanmış bir sembol, günlük ölçü veya koşullu bir sayı problemi içine yerleştirir. Asıl ölçülen, tanımı okuyup gerekli koşulu eksiksiz taşıyabilmektir.',
  struggle: 'Öğrenci genellikle bir örnekte doğru olan sonucu “her zaman” sanır; negatif sayıları doğal sayılara katar veya işlem önceliğinde soldan sağa koşulsuz ilerler.',
  osymBody: '2018-2026 kitapçıklarında temel kavramlar doğrudan sayı kümesi sorusu olarak da, tek-çift/ardışık sayı ve yeni tanım yorumlama biçiminde de görülür. Bilgiden çok koşul takibi ve karşı örnek üretme öne çıkar.',
  osymMeasures: ['Sayı kümesini doğru daraltma', 'İşlem önceliği', 'Tek-çift çıkarımı', 'Yeni tanımı örneğe uygulama'],
  patternBody: 'Sembolik ifade, sayı doğrusu, kısa günlük bağlam ve özel tanımlı sayı yapıları kullanılır. Güçlü çeldirici, bir koşulu atlayarak bulunan ama seçeneklerde yer alan sonuçtur.',
  patterns: ['Kısa sembolik işlem', 'Yeni tanımlı sayı', 'Tek-çift koşulu', 'Ardışık sayı modeli'],
  readiness: [
    { prompt: '$18-3\\cdot4$ kaçtır?', answer: '$18-12=6$.', review: 'Çarpma toplama/çıkarmadan önce yapılmıyorsa dört işlem ve işlem önceliğini tekrarla.' },
    { prompt: '$-5$, $0$ ve $\\frac{2}{3}$ sayılarından hangileri tam sayıdır?', answer: '$-5$ ve $0$ tam sayıdır; $\\frac{2}{3}$ değildir.', review: 'Sayı kümeleri ve kapsama ilişkisini gözden geçir.' },
    { prompt: 'Ardışık iki tam sayının toplamı 17 ise sayılar nelerdir?', answer: '$8$ ve $9$.', review: 'Ardışık sayıları $n$ ve $n+1$ ile temsil etmeyi çalış.' },
  ],
  concepts: [
    { term: 'Sayı kümeleri', definition: '$\\mathbb{N}\\subset\\mathbb{Z}\\subset\\mathbb{Q}\\subset\\mathbb{R}$ kapsama zinciri kullanılır; irrasyoneller $\\mathbb{R}\\setminus\\mathbb{Q}$ içindedir.', why: 'Bir değişkenin alabileceği değerler bu kümeyle sınırlandırılır.', boundary: 'Doğal sayıların $0$ ile başlayıp başlamadığı kaynakta açık olmalıdır; DRKOÇ notlarında $0\\in\\mathbb N$ kabul edilir ve gerektiğinde soru koşulu ayrıca okunur.' },
    { term: 'Tek ve çift tam sayı', definition: '$2k$ biçimindeki tam sayılar çift, $2k+1$ biçimindekiler tektir.', why: 'Son basamağa veya örneğe değil cebirsel yapıya dayanan güvenli çıkarım sağlar.', boundary: 'Tek-çift yalnız tam sayılar için kullanılır; $\\frac12$ “tek değildir” diye çift sayı olmaz.' },
    { term: 'Ardışık sayılar', definition: 'Ardışık tam sayılar $n,n+1,n+2,\\ldots$; ardışık çift veya tek sayılar $n,n+2,n+4,\\ldots$ biçiminde modellenir.', why: 'Sözel “peş peşe” ilişkisini tek değişkenli denkleme çevirir.', boundary: 'Ardışık çift sayılarda başlangıç değerinin de çift olduğu belirtilmeli veya $2k,2k+2$ yazılmalıdır.' },
  ],
  why: {
    question: 'Neden iki tek sayının toplamı her zaman çifttir?',
    body: 'Tek sayıları $2a+1$ ve $2b+1$ yazarsak toplam $2a+2b+2=2(a+b+1)$ olur. Sonuç $2$ ile bir tam sayının çarpımıdır; dolayısıyla çifttir. Tek bir sayısal örnek yalnız sonucu gösterir, bu cebirsel yazım “her zaman”ı açıklar.',
    boundary: 'Bu gerekçe toplama içindir. İki tek sayının farkı da çift, çarpımı ise tektir; işlem değişince aynı sonucu otomatik taşıma.',
  },
  certainInfo: 'Bir önermede “her zaman” deniyorsa tek örnek kanıt değildir; yanlışlığı göstermek için ise tek karşı örnek yeterlidir.',
  examples: [
    { title: 'İşlem dilini doğru oku', prompt: '$24\\div 3\\cdot2-5$ işlemini hesapla.', steps: [step('Aynı önceliği soldan sağa uygula', '$24\\div3=8$, sonra $8\\cdot2=16$.'), step('Çıkar', '$16-5=11$.')], answer: '$11$', takeaway: 'Çarpma her zaman bölmeden önce değildir; ikisi aynı önceliktedir.', check: 'İfadeyi $(24\\div3)\\cdot2-5$ diye parantezleyince aynı sonuç çıkar.' },
    { title: 'Kümeyi daralt', prompt: '$x$ negatif bir tam sayı ve $x^2<10$ ise $x$ hangi değerleri alabilir?', steps: [step('Küme şartı', '$x\\in\\{-1,-2,-3,\\ldots\\}$.'), step('Büyüklük şartı', '$x^2<10$ için $|x|<\\sqrt{10}$; negatif tam sayılar $-1,-2,-3$.')], answer: '$x\\in\\{-3,-2,-1\\}$', takeaway: 'Negatiflik ve tam sayılık birlikte uygulanır.', check: 'Kareleri sırasıyla $9,4,1$; $-4$ için kare $16$ olduğu için sınır dışında.' },
    { title: 'Tek-çift çıkarımı', prompt: '$a+b$ tek ve $b+c$ çift ise $a$ ile $c$ aynı mı, farklı mı parity taşır?', steps: [step('İlk koşul', '$a$ ile $b$ farklı tek-çift türündedir.'), step('İkinci koşul', '$b$ ile $c$ aynı türdedir.'), step('Birleştir', '$a$ ile $c$ farklı türdedir.')], answer: 'Biri tek, diğeri çifttir.', takeaway: 'Değeri değil yalnız gereken özelliği izle.', check: '$b=2$ seçilirse $a$ tek, $c$ çift olur; koşullar sağlanır.' },
    { title: 'Ardışık sayıyı modelle', prompt: 'Ardışık üç çift tam sayının toplamı 42 ise en büyüğü kaçtır?', steps: [step('Temsil', '$2k,2k+2,2k+4$.'), step('Denklem', '$6k+6=42\\Rightarrow k=6$.'), step('İstenen', '$2k+4=16$.')], answer: '$16$', takeaway: 'Ortadaki sayıyı $n$ seçmek de mümkündür: $n-2+n+n+2=42$.', check: '$12+14+16=42$.' },
    { title: 'Karşı örnekle genellemeyi sınama', prompt: '“İki gerçek sayının toplamı, sayıların her birinden büyüktür.” önermesi doğru mudur?', steps: [step('Her zaman ifadesini fark et', 'Yanlışlamak için bir karşı örnek yeterlidir.'), step('Negatif sayı dene', '$3+(-1)=2$ ve $2$, $3$ten büyük değildir.')], answer: 'Yanlıştır.', takeaway: 'Pozitif sayılarda çalışan sezgiyi bütün gerçek sayılara genişletme.', check: 'Seçilen değerler gerçek sayıdır ve önerme koşulunu doğrudan bozar.' },
  ],
  recognitionIntro: 'Soru sayıların adını vermeyebilir; “tam”, “pozitif”, “ardışık”, “farklı”, “her zaman” kelimeleri çözüm uzayını kurar.',
  decisionTree: [
    { question: '“Her zaman / kesinlikle” mi deniyor?', yes: 'Cebirsel temsil kur veya karşı örnek ara.', no: 'Verilen özel değerlere göre ilerle.' },
    { question: 'Tek-çift özelliği yeterli mi?', yes: 'Sayı yerine $2k$ ve $2k+1$ kullan.', no: 'Değer veya başka bir koşul gerekiyor; erken genelleme yapma.' },
    { question: 'Ardışıklık var mı?', yes: 'Tek değişken ve sabit farkla temsil et.', no: 'Sayıları bağımsız değişkenler olarak koru.' },
  ],
  recognitionTakeaway: 'Önce sayı kümesi, sonra ek koşul, en son işlem. Bu sıra geçersiz değer üretmeyi önler.',
  tactic: {
    title: 'Değer değil özellik takip et',
    logic: 'Soru yalnız tek-çift veya işaret soruyorsa bilinmeyenleri sayısal olarak bulmaya çalışma; gerekli özelliği cebirsel biçimde taşı.',
    works: 'Tek-çift, pozitif-negatif, ardışıklık ve “her zaman” soruları.',
    risk: 'Sonucun gerçek sayısal değeri isteniyorsa özellik takibi tek başına yetmez.',
    steps: [step('Koşul kelimelerini işaretle', 'Tam, pozitif, farklı, ardışık gibi her koşulu ayrı yaz.'), step('En dar temsili seç', 'Örneğin tek sayı için $2k+1$ kullan.'), step('İstenen özelliğe kadar sadeleştir', 'Gereksiz bilinmeyen çözme.'), step('Sınır değerle kontrol et', '$0$, $1$ ve negatif küçük değerler yanlış genellemeyi yakalar.')],
  },
  traps: [
    { title: '0 ne pozitif ne negatiftir', wrong: '$0$ı pozitif veya negatif gruba yazmak.', right: '$0$ işaretsiz sınır değeridir; çift tam sayıdır.', cause: 'Sayı doğrusunda sağ-sol ayrımını ezber cümlesiyle karıştırmak.', check: '“$x>0$” veya “$x<0$” eşitsizliklerinden hangisini sağladığını sor; ikisini de sağlamaz.' },
    { title: 'Tek değilse çift sanmak', wrong: '$\\frac13$ tek değil, o hâlde çifttir.', right: 'Tek-çift sınıflaması yalnız tam sayılarda yapılır.', cause: 'İkili sınıflandırmanın evrenini unutmak.', check: 'Önce sayının tam sayı olup olmadığını denetle.' },
    { title: 'Aynı öncelikte yönü unutmak', wrong: '$24\\div3\\cdot2$ ifadesinde önce çarpmak.', right: 'Çarpma ve bölme aynı öncelikte; soldan sağa ilerlenir.', cause: '“Çarpma önce” cümlesini bölmeye karşı üstünlük gibi okumak.', check: 'İfadeye işlemlerin uygulanma sırasını gösteren parantez ekle.' },
  ],
  questions: [
    { level: 'Temel', question: '$-7,0,\\frac45,\\sqrt9$ sayılarından kaç tanesi tam sayıdır?', options: ['1', '2', '3', '4'], answer: 2, idea: '$\\sqrt9=3$ olduğunu gör ve kümeyi sonra belirle.', solution: '$-7,0,3$ tam sayıdır; $\\frac45$ değildir. Cevap 3.', wrong: 'Kök işaretini görünce sonucu irrasyonel sanmak.', check: 'Her sayıyı sade biçimde yeniden yaz.' },
    { level: 'Temel', question: 'İki ardışık tek sayının toplamı 36 ise büyük sayı kaçtır?', options: ['17', '18', '19', '21'], answer: 2, idea: '$n$ ve $n+2$ modeli.', solution: '$n+n+2=36\\Rightarrow n=17$; büyük sayı $19$.', wrong: 'Ardışık tek sayılar arasındaki farkı 1 almak.', check: '$17+19=36$.' },
    { level: 'Orta', question: '$a$ tek, $b$ çift ise hangisi her zaman çifttir?', options: ['$a+b$', '$ab$', '$a^2+b$', '$a+b+2$'], answer: 1, idea: 'Çift çarpan içeren çarpım çifttir.', solution: '$ab$ içinde $b=2k$ olduğundan $ab=2(ak)$.', wrong: 'Çift sayı eklenince tek sayının türünün değiştiğini sanmak.', check: '$a=3,b=2$ ile seçenekleri dene.' },
    { level: 'İleri', question: '$x$ tam sayı ve $-2<x\\le 3$ ise $x$ kaç farklı değer alır?', options: ['4', '5', '6', '7'], answer: 1, idea: 'Açık ve kapalı uçları ayrı oku.', solution: '$x=-1,0,1,2,3$; beş değer.', wrong: '$-2$yi açık uç olmasına rağmen dâhil etmek.', check: 'Her değeri eşitsizlikte yerine koy.' },
    { level: 'Karma', question: '$n,n+1,n+2$ sayılarından tam ikisi tek ise $n$ için ne söylenir?', options: ['Kesinlikle tek', 'Kesinlikle çift', 'Pozitif', 'Belirlenemez'], answer: 0, idea: 'Üç ardışık sayının tek-çift örüntüsünü yaz.', solution: '$n$ çiftse örüntü çift-tek-çift olur ve yalnız bir tek vardır; $n$ tekse tek-çift-tek olur. Bu yüzden $n$ tektir.', wrong: 'Örnek denemeden “belirlenemez” demek.', check: '$n=1$ ve $n=2$ durumlarını karşılaştır.' },
  ],
  simulation: {
    passage: 'Bir oyunda seçilen tam sayıya önce 3 ekleniyor, sonuç 2 ile çarpılıyor. Elde edilen sayı çift ve negatif olduğunda oyuncu puan kazanıyor.',
    question: 'Aşağıdaki başlangıç sayılarından hangisi puan kazandırır?',
    options: [option('-4', '$2(-4+3)=-2$; çift ve negatiftir.'), option('-3', 'Sonuç 0 olur; negatif değildir.'), option('-2', 'Sonuç 2, pozitiftir.'), option('1', 'Sonuç 8, pozitiftir.')],
    answer: 0,
    stemAnalysis: '“Çift” koşulu işlem nedeniyle zaten sağlanır; ayırt edici koşul sonucun negatif olmasıdır.',
    criticalPoint: '$2(x+3)<0$ eşitsizliği $x<-3$ verir. Seçeneklerden yalnız $-4$ uygundur.',
    takeaway: 'Koşullardan otomatik sağlananı ayırmak gereksiz denemeyi azaltır.',
  },
  summary: ['Sayı kümesini belirtmeden tek-çift veya işaret genellemesi yapma.', 'İşlem önceliği: parantez, üs, çarpma-bölme, toplama-çıkarma; eş öncelikte soldan sağa.', 'Tek: $2k+1$, çift: $2k$; ardışık tam sayılar sabit farkla modellenir.', '“Her zaman” için gerekçe; yanlışlık için tek karşı örnek yeterlidir.', '$0$ çifttir fakat pozitif veya negatif değildir.', 'Soru görünce önce evreni ve bütün koşulları yaz.'],
  nextBody: 'Sayı özelliklerini basamak değeriyle birleştirerek rakam koşullu sorulara geç.',
}, 1)

const sayiBasamaklari = defineLesson({
  topic: 'Sayı Basamakları',
  subtitle: 'Rakamı sayıdan ayır, basamak değerini cebire çevir ve koşulları sistemli tara.',
  prerequisites: [{ topic: 'Temel Kavramlar', why: 'Doğal sayı, rakam ve işlem önceliği gerekir.' }],
  connections: ['Bölme ve Bölünebilme', 'Denklem Çözme', 'Permütasyon - Kombinasyon - Olasılık'],
  mapCore: 'Bir sayının yazılışını basamak değerlerinin toplamı olarak ifade eder.',
  openingLead: 'Basamak sorusunun kalbi deneme yapmak değil, yazılışı cebirle görünür kılmaktır.',
  introduction: `Rakam, sayıları yazmak için kullandığımız $0,1,\\ldots,9$ sembollerinden biridir. Üç basamaklı $\\overline{abc}$ sayısı $100a+10b+c$ demektir. Üst çizgi çarpma değil, rakamların yan yana yazıldığını gösterir.

Bu dönüşümden sonra “rakamları toplamı”, “ters yazılışı”, “basamakları farklı” gibi sözel koşullar bir denklem veya kontrollü listeye dönüşür.`,
  tytUse: 'Sorular çoğu kez özel bir sayı tanımlar; rakamların farklılığı, bölünebilme, sıralama veya rakam toplamı koşullarını birlikte izletir.',
  struggle: 'Başta sıfıra izin vermek, $AB$yi $A\\cdot B$ sanmak ve farklılık koşulunu sonradan unutmak.',
  osymBody: 'Her yıl çevresinde en az bir baskın sayı basamakları sorusu görülür. Son yıllarda doğrudan çözümleme yerine özgün ad verilmiş sayı özelliği ve birden fazla rakam koşulu öne çıkar.',
  osymMeasures: ['Basamak çözümlemesi', 'Koşul eleme', 'Rakam-toplam ilişkisi', 'Sistematik tarama'],
  patternBody: 'Yeni tanımlı doğal sayı, ters yazma, rakam toplamı ve bölünebilme birlikte kullanılabilir. En güçlü çeldirici, baştaki rakamın sıfır olamayacağını veya rakamların farklılığını atlayan sonuçtur.',
  patterns: ['Özel tanımlı sayı', 'Eksik rakam', 'Ters çevrilen sayı', 'Rakam toplamı'],
  readiness: [
    { prompt: '$5072$ sayısında 7 rakamının basamak değeri nedir?', answer: '$70$.', review: 'Rakam değeri ile basamak değerini ayır.' },
    { prompt: '$\\overline{ab}$ sayısını cebirsel yaz.', answer: '$10a+b$.', review: 'İki basamaklı sayı çözümlemesini tekrar et.' },
    { prompt: 'Üç basamaklı bir doğal sayının yüzler basamağı 0 olabilir mi?', answer: 'Hayır; olursa sayı üç basamaklı olmaz.', review: 'Baştaki rakam koşulunu görünür tut.' },
  ],
  concepts: [
    { term: 'Rakam ve sayı', definition: 'Rakam yazı sembolüdür; sayı bir miktarı/değeri ifade eder. $347$ bir sayı, 3-4-7 onun rakamlarıdır.', why: 'Koşulun rakama mı tüm sayıya mı uygulandığını ayırır.', boundary: '“Rakamları farklı” denmedikçe aynı rakam tekrarlanabilir.' },
    { term: 'Basamak değeri', definition: 'Rakamın bulunduğu konuma göre kazandığı değerdir. $\\overline{abc}=100a+10b+c$.', why: 'Yan yana yazmayı denklem diline çevirir.', boundary: 'Yüzler basamağındaki $a\\ne0$; diğer basamaklar 0 olabilir.' },
    { term: 'Ters yazılış', definition: '$\\overline{abc}$ sayısının ters yazılışı $\\overline{cba}=100c+10b+a$ olur.', why: 'Fark ve toplam ilişkilerini kısa cebirle verir.', boundary: '$c=0$ ise ters yazılan ifade üç basamaklı bir sayı olmayabilir; soru koşulu kontrol edilir.' },
  ],
  why: { question: 'Neden iki basamaklı bir sayı ile tersinin farkı 9un katıdır?', body: '$(10a+b)-(10b+a)=9(a-b)$ olur. Bu nedenle fark, her geçerli $a,b$ için 9un katıdır.', boundary: 'Sonucun işareti $a-b$ye bağlıdır; “fark” mutlak değer anlamında kullanılmışsa $9|a-b|$ alınır.' },
  formulas: [{ title: 'Basamak çözümlemesi', latex: '\\overline{abc}=100a+10b+c', meaning: '$a$ yüzler, $b$ onlar, $c$ birler basamağındaki rakamdır.', condition: '$a\\in\\{1,\\ldots,9\\}$; $b,c\\in\\{0,\\ldots,9\\}$.', variables: [{ sym: 'a,b,c', desc: 'Rakamlar' }] }],
  certainInfo: 'Bir $n$ basamaklı doğal sayının ilk rakamı 0 olamaz; her rakam 0 ile 9 arasında tam sayıdır.',
  examples: [
    { title: 'Çözümlemeyi kullan', prompt: '$\\overline{ab}+\\overline{ba}=121$ ise $a+b$ kaçtır?', steps: [step('Aç', '$(10a+b)+(10b+a)=11(a+b)$.'), step('Denklemi çöz', '$11(a+b)=121\\Rightarrow a+b=11$.')], answer: '$11$', takeaway: 'Tek tek rakam aramaya gerek yok.', check: '$a+b=11$ olan her geçerli ikili toplamda 121 verir.' },
    { title: 'Farklılık koşulunu uygula', prompt: 'Rakamları farklı en küçük üç basamaklı pozitif sayı nedir?', steps: [step('Yüzler basamağını küçült', '$1$.'), step('Onlar basamağı', 'Kullanılmayan en küçük rakam $0$.'), step('Birler basamağı', '0 ve 1den farklı en küçük rakam $2$.')], answer: '$102$', takeaway: 'Küçültme soldan sağa yapılır.', check: '$100$ ve $101$ rakamları farklı değildir.' },
    { title: 'Rakam toplamı ve bölünebilme', prompt: '$\\overline{4a2}$ sayısı 9 ile tam bölünüyorsa $a$ kaç olabilir?', steps: [step('Rakam toplamı', '$4+a+2=a+6$.'), step('9un katı', '$a+6$ 6 ile 15 arasındadır; tek uygun 9dur.'), step('Rakamı bul', '$a=3$.')], answer: '$3$', takeaway: 'Rakam aralığı olası katları sınırlar.', check: '$432\\div9=48$.' },
    { title: 'Ters sayı ilişkisi', prompt: 'İki basamaklı bir sayı tersinden 27 fazladır. Rakamları farkı kaçtır?', steps: [step('Farkı aç', '$9(a-b)=27$.'), step('Sadeleştir', '$a-b=3$.')], answer: '$3$', takeaway: 'Sayının kendisini bulmadan istenen ilişki bulunabilir.', check: '$41-14=27$ örneği koşulu doğrular.' },
    { title: 'Sistematik liste', prompt: 'Rakamları toplamı 5 olan kaç tane iki basamaklı doğal sayı vardır?', steps: [step('Denklem', '$a+b=5$, $a\\ge1$, $b\\ge0$.'), step('İkililer', '$(1,4),(2,3),(3,2),(4,1),(5,0)$.')], answer: '$5$', takeaway: 'Başta sıfırı ele; birler basamağında sıfıra izin ver.', check: '$14,23,32,41,50$ listesi eksiksizdir.' },
  ],
  recognitionIntro: 'AB, BA, rakamları toplamı, basamak değeri veya “rakamları farklı” ifadeleri görünce sayıyı hemen çözümle.',
  decisionTree: [{ question: 'Yan yana yazılmış harfli sayı var mı?', yes: '$\\overline{ab}=10a+b$ biçimine çevir.', no: 'Doğrudan basamak tablosu yeterli olabilir.' }, { question: 'Rakamlar farklı mı?', yes: 'Her seçimde kullanılan rakamı ele.', no: 'Tekrara izin ver.' }, { question: 'En küçük/en büyük sayı mı?', yes: 'Basamakları soldan sağa optimize et.', no: 'Denklem veya sistematik listeyi sürdür.' }],
  recognitionTakeaway: 'Önce basamak denklemi, sonra rakam aralığı, sonra farklılık ve bölünebilme.',
  tactic: { title: 'Önce cebir, sonra kısa tarama', logic: 'Bütün sayıları rastgele denemek yerine basamak çözümlemesiyle koşulu daralt; kalan az olasılığı listele.', works: 'Ters sayı, rakam toplamı, eksik rakam ve özel tanımlı sayı soruları.', risk: 'Küçük ve sonlu bir liste oluşmadan kaba deneme yapmak değer atlatır.', steps: [step('Sayıyı aç', 'Basamak katsayılarını yaz.'), step('Rakam sınırlarını ekle', '0-9 ve baştaki rakamın sıfır olmaması.'), step('Diğer koşulları uygula', 'Farklılık, bölünebilme, sıralama.'), step('Kalanları sırayla denetle', 'Listeyi eksiksiz bitir.')] },
  traps: [
    { title: 'AByi çarpım sanmak', wrong: '$AB=A\\cdot B$.', right: '$\\overline{AB}=10A+B$.', cause: 'Üst çizgi veya bağlamı görmeden cebir alışkanlığıyla okumak.', check: '$A=2,B=3$ için sayının 23 mü 6 mı olması gerektiğini sor.' },
    { title: 'Başa sıfır koymak', wrong: '$047$yi üç basamaklı saymak.', right: '$047=47$ iki basamaklıdır.', cause: 'Her kutuyu bağımsız rakam yeri sanmak.', check: 'En soldaki rakamın sıfır olmadığını ayrıca yaz.' },
    { title: 'Farklı rakam koşulunu unutmak', wrong: 'Denklemi sağlayan tekrarlı rakamı kabul etmek.', right: 'Denklem sonrası tüm sözel koşullar yeniden işaretlenir.', cause: 'İşlem bitince soru köküne dönmemek.', check: 'Bulduğun sayının her koşuluna ayrı onay işareti koy.' },
  ],
  questions: [
    { level: 'Temel', question: '$\\overline{3a7}=307+10a$ olduğuna göre bu eşitlik hangi $a$ rakamları için doğrudur?', options: ['Yalnız 0', 'Yalnız 7', 'Bütün rakamlar', 'Hiçbiri'], answer: 2, idea: 'Basamak çözümlemesini karşılaştır.', solution: '$\\overline{3a7}=300+10a+7=307+10a$ her rakam için.', wrong: '$a$yı bilinmeyen denklem gibi gereksiz çözmek.', check: '$a=0$ ve $a=9$ sınırlarını dene.' },
    { level: 'Orta', question: '$\\overline{ab}-\\overline{ba}=45$ ise $a-b$ kaçtır?', options: ['3', '4', '5', '9'], answer: 2, idea: 'Fark $9(a-b)$dir.', solution: '$9(a-b)=45\\Rightarrow a-b=5$.', wrong: '45i iki rakamın doğrudan farkı sanmak.', check: '$72-27=45$.' },
    { level: 'Orta', question: 'Rakamları toplamı 3 olan kaç üç basamaklı doğal sayı vardır?', options: ['3', '4', '5', '6'], answer: 3, idea: '$a\\ge1$ koşuluyla $a+b+c=3$.', solution: '$a\\mapsto a-1$ dönüşümüyle üç negatif olmayan değişkenin toplamı 2dir; 6 çözüm vardır.', wrong: 'Yüzler basamağında 0a izin vermek.', check: '$102,111,120,201,210,300$.' },
    { level: 'İleri', question: '$\\overline{abc}=2\\overline{cba}$ ve $a,c\\ne0$ ise hangisi kesindir?', options: ['$a>c$', '$a<c$', '$a=c$', '$b=0$'], answer: 0, idea: 'Sayı iki katına çıkınca tersinin ilk rakam ilişkisini düşün.', solution: '$\\overline{abc}$ daha büyük olduğundan yüzler basamağı $a$, tersinin yüzler basamağı $c$den büyüktür: $a>c$.', wrong: 'Eşitliği rakam rakam çarpmak.', check: 'İki pozitif üç basamaklı sayının büyüklüğü ilk farklı basamakta belirlenir.' },
    { level: 'Karma', question: 'Rakamları farklı en büyük iki basamaklı çift sayı kaçtır?', options: ['96', '98', '97', '88'], answer: 1, idea: 'Önce onlar basamağını, sonra çift birler basamağını büyüt.', solution: 'Onlar 9; birler 9dan farklı en büyük çift rakam 8dir. Sayı 98.', wrong: '96da durmak veya 88de farklılığı unutmak.', check: '99dan geriye doğru ilk geçerli sayı 98dir.' },
  ],
  simulation: { passage: 'Bir kilit, rakamları birbirinden farklı üç basamaklı bir kod kullanıyor. Kodun yüzler ve birler basamağındaki rakamların toplamı 9, onlar basamağı 0 ve kod 5 ile tam bölünüyor.', question: 'Kod aşağıdakilerden hangisi olabilir?', options: [option('405', '4+5=9; rakamlar farklı; son rakam 5.'), option('504', '5 ile bölünmez.'), option('900', 'Rakamlar farklı değildir.'), option('108', 'Yüzler ve birler toplamı 9 olsa da 5 ile bölünmez.')], answer: 0, stemAnalysis: 'Üç koşul ayrı filtrelenir: farklılık, toplam ve son basamak.', criticalPoint: '5 ile bölünebilme son rakamı 0 veya 5 yapar; onlar zaten 0 olduğu için farklılık nedeniyle son rakam 5 olmalıdır.', takeaway: 'En kısıtlayıcı koşulu önce uygulamak seçenekleri hızla azaltır.' },
  summary: ['$\\overline{ab}=10a+b$, $\\overline{abc}=100a+10b+c$.', 'İlk basamak 0 olamaz; diğerleri olabilir.', 'Ters iki basamaklı sayıların farkı $9(a-b)$dir.', 'Rakam, sayı ve basamak değeri aynı kavram değildir.', 'Farklılık ve bölünebilme koşullarını işlemden sonra yeniden kontrol et.', 'En küçük/en büyük sayıda soldan sağa karar ver.'],
  nextBody: 'Basamak çözümlemesini bölünebilme ve kalan kurallarıyla birleştir.',
}, 2)

const bolme = defineLesson({
  topic: 'Bölme ve Bölünebilme',
  subtitle: 'Bölüm-kalan eşitliğini kur, kuralları nedenleriyle kullan ve döngüyü fark et.',
  prerequisites: [{ topic: 'Sayı Basamakları', why: 'Bölünebilme kuralları basamak yapısını kullanır.' }],
  connections: ['OBEB - OKEK', 'Problemler', 'Permütasyon - Kombinasyon - Olasılık'],
  mapCore: 'Bir sayıyı bölen, bölüm ve kalanla yeniden kurar; basamak kurallarını bu yapıya bağlar.',
  openingLead: 'Kalan, bölme işleminin artığı değil sayıyı yeniden kuran temel bilgidir.',
  introduction: `Bir $a$ tam sayısı pozitif $b$ sayısına bölündüğünde $a=bq+r$ yazılır. Burada $q$ bölüm, $r$ kalandır ve $0\\le r<b$ olmalıdır. Kalanın bö­lenden küçük olması tek bir bölüm-kalan çifti elde etmemizi sağlar.

Bölünebilme, kalanın 0 olmasıdır. Kurallar ezberlenecek bağımsız hileler değil, onluk sistemde basamak değerlerinin belirli bölenlere göre kalanlarının düzenlenmesidir.`,
  tytUse: 'Özel tanımlı sayılar, eş kalanlar, takvim-döngü ve basamak koşulları içinde görünür. Çoğu soru “hangi kurala göre?” demez; kalan ilişkisini modellemek gerekir.',
  struggle: 'Kalanı bö­lenden büyük almak, negatif farkta kalan dilini karıştırmak ve 3/9 kuralını sayının kendisi yerine rakamların her birine uygulamak.',
  osymBody: '2021-2026 kitapçıklarında baskın bölünebilme etiketi düzenli görünür. Soru, kuralı doğrudan sormaktan çok rakam koşulu veya yeni tanımlı bölüm-kalan ilişkisi kurdurur.',
  osymMeasures: ['Bölme algoritması', 'Kalan yorumlama', 'Basamak kuralı', 'Döngü/periyot'],
  patternBody: 'Eksik rakam, eş kalan, bölüm-kalan yer değiştirmesi ve tekrarlı örüntü başlıca sunumlardır. Çeldirici genellikle kalan sınırını ihlal eder.',
  patterns: ['Eksik rakam', 'Bölüm-kalan modeli', 'Tekrarlı döngü', 'Özel tanım'],
  readiness: [
    { prompt: '$37$ sayısının 5 ile bölümünden kalan kaçtır?', answer: '$2$.', review: '$37=5\\cdot7+2$ biçimini kur.' },
    { prompt: 'Bir sayının 3 ile bölünebilmesi için ne kontrol edilir?', answer: 'Rakamları toplamının 3 ile bölünebilmesi.', review: '3 ve 9 bölünebilme kurallarını tekrar et.' },
    { prompt: 'Kalan 7, bölen 6 olabilir mi?', answer: 'Hayır; kalan bölenden küçük olmalıdır.', review: 'Bölme algoritmasının sınırını gözden geçir.' },
  ],
  concepts: [
    { term: 'Bölme algoritması', definition: '$a=bq+r$ ve $0\\le r<b$.', why: 'Sayıyı bölen, bölüm ve kalanla eksiksiz yeniden kurar.', boundary: '$b>0$ alınır; kalan sınırı bö­lene göre yazılır.' },
    { term: 'Bölünebilme', definition: '$a$ sayısı $b$ye tam bölünüyorsa $r=0$ ve $a=bq$ olur.', why: 'Bir sayının bölen yapısını ve gruplamayı belirler.', boundary: 'Sıfıra bölme tanımsızdır; 0, sıfır olmayan her tam sayıya tam bölünür.' },
    { term: 'Eş kalan', definition: '$a$ ve $c$ sayıları $b$ ile bölündüğünde aynı kalanı veriyorsa $a-c$, $b$nin katıdır.', why: 'İki ayrı bölmeyi tek fark ilişkisine çevirir.', boundary: 'Tersi de geçerlidir; fakat bölen sıfır olamaz.' },
  ],
  why: { question: 'Neden 3 ve 9 için rakamlar toplamı kullanılır?', body: '$10\\equiv1$ olduğundan $10^k\\equiv1$ (mod 3 ve mod 9). Bu yüzden $100a+10b+c$ ile $a+b+c$ aynı kalanı verir.', boundary: 'Bu açıklama 3 ve 9 içindir; her bölen için rakamlar toplamı kuralı kullanılamaz.' },
  formulas: [{ title: 'Bölme algoritması', latex: 'a=bq+r,\\quad 0\\le r<b', meaning: '$a$ bölünen, $b$ pozitif bölen, $q$ bölüm, $r$ kalandır.', condition: 'Bölen 0 olamaz; standart kalan negatif veya bö­lenden büyük seçilmez.', variables: [{ sym: 'a', desc: 'Bölünen' }, { sym: 'b', desc: 'Pozitif bölen' }, { sym: 'q', desc: 'Bölüm' }, { sym: 'r', desc: 'Kalan' }] }],
  certainInfo: 'Bir sayı $b$ ile bölündüğünde olası standart kalanlar yalnız $0,1,\\ldots,b-1$dir.',
  examples: [
    { title: 'Sayıyı yeniden kur', prompt: 'Bir sayı 7 ile bölündüğünde bölüm 12, kalan 5tir. Sayı kaçtır?', steps: [step('Formülü yaz', '$a=7\\cdot12+5$.'), step('Hesapla', '$a=84+5=89$.')], answer: '$89$', takeaway: 'Bölünen = bölen × bölüm + kalan.', check: '$89\\div7=12$ kalan $5$.' },
    { title: 'Eksik rakam', prompt: '$43a$ üç basamaklı sayısı 9 ile tam bölünüyorsa $a$ kaçtır?', steps: [step('Rakam toplamı', '$4+3+a=7+a$.'), step('9un katını bul', 'Aralık 7-16; uygun kat 9.'), step('Rakam', '$a=2$.')], answer: '$2$', takeaway: 'Önce olası toplam aralığını kullan.', check: '$432=9\\cdot48$.' },
    { title: 'Eş kalanı farkla çöz', prompt: '$n$ sayısı 8 ile bölündüğünde 3, $n+13$ sayısı 8 ile bölündüğünde kaç kalan verir?', steps: [step('Kalanlara göre sadeleştir', '$n\\equiv3$ ve $13\\equiv5$.'), step('Topla', '$3+5=8\\equiv0$.')], answer: '$0$', takeaway: 'Sayının kendisini bulmak gerekmez.', check: '$n=11$ seçilirse $24$ tam bölünür.' },
    { title: 'Kalan sınırı', prompt: '$a=5q+7$ eşitliği bir standart bölme işlemini gösterir mi?', steps: [step('Sınırı kontrol et', 'Bölen 5 iken kalan 7 olamaz.'), step('Yeniden düzenle', '$5q+7=5(q+1)+2$.')], answer: 'Standart bölüm $q+1$, kalan $2$dir.', takeaway: 'Kalanı bö­lenden küçük hâle getir.', check: '$2<5$.' },
    { title: 'Döngü', prompt: '$2^{20}$ sayısının 5 ile bölümünden kalan kaçtır?', steps: [step('Kalan döngüsü', '$2,4,3,1$ dört adımda tekrar eder.'), step('Üs konumu', '$20$ dörtle tam bölünür; döngünün 4. değeri alınır.')], answer: '$1$', takeaway: 'Büyük sayıyı hesaplamak yerine periyodu kullan.', check: '$2^4=16\\equiv1$ olduğundan $(2^4)^5\\equiv1$.' },
  ],
  recognitionIntro: '“Gruplandığında artan”, “bölüm-kalan”, “kaçıncı tekrar” veya eksik rakam gördüğünde kalan dilini kur.',
  decisionTree: [{ question: 'Bölüm ve kalan açık mı?', yes: '$a=bq+r$ yaz.', no: 'Bölünebilme veya periyot ipucu ara.' }, { question: 'Basamaklı sayı mı?', yes: 'Uygun bölünebilme kuralını ve rakam aralığını kullan.', no: 'Kalan eşitliği daha doğrudan olabilir.' }, { question: 'Çok büyük üs/tekrar mı?', yes: 'Kalan döngüsünü bul.', no: 'Doğrudan bölüm-kalanla ilerle.' }],
  recognitionTakeaway: 'Kuralı seçmeden önce böleni belirle; sonra kalanın alabileceği aralığı yaz.',
  tactic: { title: 'Kalan diline küçült', logic: 'Büyük sayıları hesaplamak yerine yalnız bö­lene göre kalanlarını taşı.', works: 'Üslü sayı, takvim, tekrar ve eş kalan soruları.', risk: 'Sonucun gerçek değeri isteniyorsa yalnız kalan yetmez.', steps: [step('Böleni sabitle', 'Bütün eşitliklerde aynı bö­lene göre konuş.'), step('Her terimi kalana indir', 'Gerekirse negatif olmayan standart kalana çevir.'), step('İşlemi kalanlarla yap', 'Toplama ve çarpmayı uygula.'), step('Son kalanı standartlaştır', '$0\\le r<b$.')] },
  traps: [
    { title: 'Kalan bö­lenden büyük olamaz', wrong: 'Bölen 6, kalan 8 yazmak.', right: '$8=6+2$ olduğundan bölüm bir artar, kalan 2 olur.', cause: 'Eşitliğin sayısal olarak doğru olmasını standart bölme sanmak.', check: '$0\\le r<b$ satırını her soruda yaz.' },
    { title: '11 kuralında işaretli toplam', wrong: 'Bütün rakamları toplamak.', right: 'Birer atlayarak alınan toplamların farkı 11in katı olmalıdır.', cause: '3 ve 9 kuralını genellemek.', check: 'Kuralın hangi bö­lene ait olduğunu söyle.' },
    { title: 'Negatif kalanı bırakmak', wrong: '$-1$ı standart kalan yazmak.', right: 'Bölen $b$ ise $-1\\equiv b-1$.', cause: 'Modüler eşdeğerlikle standart kalanı karıştırmak.', check: 'Kalanın negatif olmadığını denetle.' },
  ],
  questions: [
    { level: 'Temel', question: '$125$ sayısının 8 ile bölümünden kalan kaçtır?', options: ['1', '3', '5', '7'], answer: 2, idea: '$125=8\\cdot15+5$.', solution: 'Kalan 5tir.', wrong: 'Son iki basamağa bakıp 25i cevaplamak.', check: '$5<8$.' },
    { level: 'Orta', question: '$7a4$ sayısı 3 ile tam bölünüyor. $a$ kaç farklı değer alır?', options: ['2', '3', '4', '5'], answer: 1, idea: '$11+a$ 3ün katı olmalı.', solution: '$a=1,4,7$; üç değer.', wrong: '0ı otomatik dâhil etmek.', check: 'Rakam toplamları 12,15,18.' },
    { level: 'Orta', question: '$n\\equiv4\\pmod7$ ise $2n+3$ün 7 ile bölümünden kalan kaçtır?', options: ['1', '2', '4', '6'], answer: 2, idea: '$n$ yerine kalanı taşı.', solution: '$2\\cdot4+3=11\\equiv4$.', wrong: '$n$yi belirli bir sayı sanmak.', check: '$n=11$ için $25$in kalanı 4.' },
    { level: 'İleri', question: '$3^{15}$ sayısının 4 ile bölümünden kalan kaçtır?', options: ['0', '1', '2', '3'], answer: 3, idea: '$3\\equiv-1\\pmod4$.', solution: 'Tek üs nedeniyle $(-1)^{15}=-1\\equiv3$.', wrong: 'Üssü 4e bölmeye çalışmak.', check: '$3,1$ döngüsü tek üslerde 3 verir.' },
    { level: 'Karma', question: 'Bir sayı 6 ile bölündüğünde 5 kalanını veriyor. Aynı sayının 3 ile bölümünden kalan kaçtır?', options: ['0', '1', '2', 'Belirlenemez'], answer: 2, idea: '$n=6k+5=3(2k+1)+2$.', solution: 'Kalan 2dir.', wrong: 'Bölen değişince ilişkinin kaybolduğunu sanmak.', check: '5,11,17 örneklerinin hepsi 3e göre 2 kalanını verir.' },
  ],
  simulation: { passage: 'Bir depodaki ürünler 12şerli kutulara konduğunda 5 ürün artıyor. Aynı ürün sayısına 7 ürün daha ekleniyor.', question: 'Yeni toplam 12şerli kutulara konduğunda kaç ürün artar?', options: [option('0', '$5+7=12$; kalan 0.'), option('2'), option('5'), option('7')], answer: 0, stemAnalysis: 'Toplam ürün sayısı gereksizdir; yalnız 12ye göre kalan izlenir.', criticalPoint: '$n\\equiv5$ ve $n+7\\equiv12\\equiv0$.', takeaway: 'Kalanı taşımak bilinmeyen toplamı bulma ihtiyacını ortadan kaldırır.' },
  summary: ['$a=bq+r$ ve $0\\le r<b$.', 'Tam bölünmede kalan 0dır.', 'Aynı bö­lene göre eş kalan veren sayıların farkı bö­lenin katıdır.', '3 ve 9 için rakamlar toplamı; 4 için son iki, 8 için son üç basamak kullanılabilir.', 'Büyük üslerde kalan döngüsünü ara.', 'Standart kalan negatif veya bö­lenden büyük olamaz.'],
  nextBody: 'Bölünebilme bilgisini asal çarpan, ortak bölen ve ortak kat yapısına taşı.',
}, 3)

const ebobEkok = defineLesson({
  topic: 'OBEB - OKEK',
  subtitle: 'Asal çarpanları, bölenleri ve ortak düzeni aynı modelde birleştir.',
  prerequisites: [{ topic: 'Bölme ve Bölünebilme', why: 'Bölen ve kat kavramları gerekir.' }],
  connections: ['Rasyonel Sayılar', 'Problemler', 'Permütasyon - Kombinasyon - Olasılık'],
  mapCore: 'Sayıların ortak bölen ve kat yapısını asal çarpanlar üzerinden karşılaştırır.',
  openingLead: 'EBOB eş parça büyüklüğünü, EKOK tekrarların ilk ortak buluşmasını düzenler.',
  introduction: `Asal sayı yalnız 1e ve kendisine bölünen, 1den büyük doğal sayıdır. Her 1den büyük doğal sayı asal çarpanların çarpımı olarak tek biçimde yazılır. EBOB ortak asal çarpanların küçük üslerini, EKOK ise tüm asal çarpanların büyük üslerini alır.

Soruda “en büyük eş parça” EBOB; “ilk kez birlikte”, “en küçük ortak toplam” EKOK ipucudur. Yine de kelimeye körlemesine bağlanma: arananın bölen mi kat mı olduğunu modelden doğrula.`,
  tytUse: 'ÖSYM çoğu kez EBOB/EKOK adını söylemez; dikdörtgen kenarı, eş paket, sandalye düzeni veya periyodik buluşma üzerinden ortak yapı kurdurur.',
  struggle: 'EBOB ile EKOKu anahtar kelime ezberiyle seçmek ve asal çarpan üslerinde küçük-büyük ayrımını ters çevirmek.',
  osymBody: 'Doğrudan frekansı düşük olsa da bölen, çarpan ve ortak düzen 2020, 2024 ve 2026 gibi yıllarda baskın veya problem içinde görünür. Ön koşul değeri soru sayısından büyüktür.',
  osymMeasures: ['Asal çarpan yapısı', 'Bölen sayısı', 'Eş gruplama', 'Periyodik buluşma'],
  patternBody: 'Dikdörtgen alanı, eş sıra-sütun, paketleme ve tekrar zamanları kullanılır. Çeldirici, EBOB yerine EKOK veya tersini almaktan doğar.',
  patterns: ['Eş parça', 'Ortak periyot', 'Dikdörtgen/bölen', 'Bölen sayısı'],
  readiness: [
    { prompt: '$36$yı asal çarpanlarına ayır.', answer: '$36=2^2\\cdot3^2$.', review: 'Asal çarpan ağacını tekrar et.' },
    { prompt: '$12$ ve $18$in ortak bölenlerinden en büyüğü kaçtır?', answer: '$6$.', review: 'EBOB kavramını gözden geçir.' },
    { prompt: '$4$ ve $6$ sayılarının ilk pozitif ortak katı nedir?', answer: '$12$.', review: 'EKOK kavramını gözden geçir.' },
  ],
  concepts: [
    { term: 'Asal çarpan', definition: 'Bir doğal sayıyı tam bölen asal sayıdır; $60=2^2\\cdot3\\cdot5$.', why: 'Bölenlerin bütün yapısını küçük bir üs listesine dönüştürür.', boundary: '$1$ asal değildir; asal çarpan listesine yazılmaz.' },
    { term: 'EBOB', definition: 'İki veya daha çok sayının ortak pozitif bölenlerinin en büyüğüdür.', why: 'Miktarları artıksız bölen en büyük eş birimi verir.', boundary: 'Aranan büyüklük verilen sayıları bölmelidir.' },
    { term: 'EKOK', definition: 'İki veya daha çok sayının ortak pozitif katlarının en küçüğüdür.', why: 'Farklı periyotların ilk pozitif ortak buluşmasını verir.', boundary: 'Aranan büyüklük verilen sayıların katı olmalıdır.' },
  ],
  why: { question: 'Neden EBOBda küçük, EKOKta büyük üs alınır?', body: 'Ortak bölen her sayıyı bölmelidir; bu yüzden bir asalın üssü hiçbir sayıda bulunandan büyük olamaz ve ortak olan en büyük değer küçük üstür. Ortak kat ise her sayıyı içermelidir; bu yüzden gereken en büyük üssü taşır.', boundary: 'Bu açıklama pozitif doğal sayıların asal çarpan gösterimi içindir.' },
  formulas: [{ title: 'İki sayı için çarpım ilişkisi', latex: '\\operatorname{EBOB}(a,b)\\cdot\\operatorname{EKOK}(a,b)=a\\cdot b', meaning: 'Pozitif iki doğal sayının EBOB ve EKOK çarpımı sayıların çarpımına eşittir.', condition: 'İki pozitif doğal sayı içindir; üç veya daha çok sayıya doğrudan genellenmez.', variables: [{ sym: 'a,b', desc: 'Pozitif doğal sayılar' }] }],
  certainInfo: 'EBOB verilen sayıların böleni, EKOK verilen sayıların katıdır; sonuç bu hızlı kontrolü geçmelidir.',
  examples: [
    { title: 'Asal üslerle EBOB-EKOK', prompt: '$72=2^3\\cdot3^2$ ve $120=2^3\\cdot3\\cdot5$ için EBOB ve EKOKu bul.', steps: [step('EBOB', 'Ortak asallarda küçük üs: $2^3\\cdot3=24$.'), step('EKOK', 'Tüm asallarda büyük üs: $2^3\\cdot3^2\\cdot5=360$.')], answer: 'EBOB $24$, EKOK $360$.', takeaway: 'Eksik asalın EBOBdaki üssü 0dır.', check: '24 iki sayıyı böler; 360 ikisinin de katıdır.' },
    { title: 'En büyük eş parça', prompt: '48 kırmızı ve 60 mavi boncuk, her pakette renk başına eş sayılar olacak ve artmayacak biçimde en çok kaç özdeş pakete ayrılır?', steps: [step('Paket sayısı ortak bölen', 'Paket sayısı hem 48i hem 60ı bölmeli.'), step('En çok istendi', '$\\operatorname{EBOB}(48,60)=12$.')], answer: '$12$ paket.', takeaway: 'Paket sayısı EBOB; paket başına miktarlar $4$ ve $5$.', check: '$12\\cdot4=48$, $12\\cdot5=60$.' },
    { title: 'İlk ortak buluşma', prompt: 'Biri 8, diğeri 12 dakikada bir çalışan iki zil birlikte çaldı. Kaç dakika sonra yeniden birlikte çalar?', steps: [step('Periyotların katı', 'Süre hem 8in hem 12nin katı olmalı.'), step('İlk pozitif ortak', '$\\operatorname{EKOK}(8,12)=24$.')], answer: '$24$ dakika.', takeaway: 'Birlikte başlangıç anını 0 kabul et; “yeniden” ilk pozitif ortak kattır.', check: '24/8=3 ve 24/12=2.' },
    { title: 'Bölen sayısı', prompt: '$N=2^3\\cdot3^2$ sayısının kaç pozitif böleni vardır?', steps: [step('Üs seçenekleri', '2nin üssü 0-3: 4 seçenek; 3ün üssü 0-2: 3 seçenek.'), step('Bağımsız seçimleri çarp', '$4\\cdot3=12$.')], answer: '$12$', takeaway: 'Her bölen asal üslerin bağımsız seçimidir.', check: 'Formül $(3+1)(2+1)=12$.' },
    { title: 'Çarpım ilişkisi', prompt: 'EBOBları 6, EKOKları 180 olan iki pozitif doğal sayının çarpımı kaçtır?', steps: [step('İki sayı formülü', '$a\\cdot b=6\\cdot180$.')], answer: '$1080$', takeaway: 'Sayıları tek tek bulmaya gerek yok.', check: 'Birimler doğal sayı çarpımı; sonuç pozitiftir.' },
  ],
  recognitionIntro: 'Aranan değer verilenleri mi bölüyor, yoksa verilenler arananı mı bölüyor? Bu tek soru EBOB-EKOK seçimini güvenle yapar.',
  decisionTree: [{ question: 'Eş ve artıksız parçalara mı ayırıyorsun?', yes: 'Ortak bölen; en büyük istenirse EBOB.', no: 'Ortak kat ihtimalini kontrol et.' }, { question: 'Periyotlar yeniden birlikte mi olacak?', yes: 'İlk pozitif ortak kat, EKOK.', no: 'Bölen veya asal çarpan sorusu olabilir.' }, { question: 'Sonucun verilen sayıları bölmesi mi gerekir?', yes: 'EBOB tarafındasın.', no: 'Verilenlerin sonucu bölmesi gerekiyorsa EKOK tarafındasın.' }],
  recognitionTakeaway: 'Anahtar kelime yerine bölme yönünü test et.',
  tactic: { title: 'Sonucun yönünü çiz', logic: 'EBOBda sonuçtan sayılara “böler” oku; EKOKta sayılardan sonuca “böler” oku çiz.', works: 'Paketleme, döşeme, sıra-sütun ve periyot soruları.', risk: 'Ek koşullar varsa yalnız EBOB/EKOK sonucu yeterli olmayabilir.', steps: [step('Verilenleri yaz', 'Aynı birimde olmalı.'), step('Bölme yönünü belirle', 'Sonuç bölen mi kat mı?'), step('Asal üsleri seç', 'Küçük veya büyük üs.'), step('Bağlama geri dön', 'Paket sayısı mı, parça boyu mu istendiğini ayır.')] },
  traps: [
    { title: 'Paket sayısı ile paket büyüklüğünü karıştırmak', wrong: 'EBOBu bulup doğrudan her paketteki ürün sayısı sanmak.', right: 'EBOB bazen paket sayısı, bazen parça uzunluğudur; cümledeki birimi kontrol et.', cause: 'Bağlama dönmeden sayıyı cevap yazmak.', check: 'Sonucun birimini ve neyi saydığını söyle.' },
    { title: 'EKOKta ortak olmayan asalı atmak', wrong: '$120$deki 5i EKOKa almamak.', right: 'EKOK her sayının bütün asal çarpanlarını içermelidir.', cause: '“Ortak” kelimesini yalnız ortak asal sanmak.', check: 'Bulduğun EKOK verilen her sayıya tam bölünüyor mu?' },
    { title: 'Çarpım formülünü üç sayıya taşımak', wrong: 'EBOB·EKOK = sayıların çarpımı ilişkisini üç sayıda kullanmak.', right: 'Basit formül yalnız iki pozitif doğal sayı içindir.', cause: 'Koşulu formülden ayırmak.', check: 'Formüldeki değişken sayısını gör.' },
  ],
  questions: [
    { level: 'Temel', question: '$84$ ve $126$ sayılarının EBOBu kaçtır?', options: ['14', '21', '42', '63'], answer: 2, idea: '$84=2^2\\cdot3\\cdot7$, $126=2\\cdot3^2\\cdot7$.', solution: '$2\\cdot3\\cdot7=42$.', wrong: 'Büyük üsleri alıp EKOK bulmak.', check: '42 her ikisini böler.' },
    { level: 'Temel', question: '$6$ ve $15$in EKOKu kaçtır?', options: ['15', '30', '45', '90'], answer: 1, idea: '$2\\cdot3\\cdot5$.', solution: 'EKOK 30dur.', wrong: 'Yalnız ortak 3ü almak.', check: '30 hem 6 hem 15in katı.' },
    { level: 'Orta', question: '45 ve 75 metrelik iki ip eşit ve en uzun parçalara ayrılacaktır. Bir parça kaç metredir?', options: ['5', '10', '15', '25'], answer: 2, idea: 'En uzun ortak parça EBOB.', solution: '$\\operatorname{EBOB}(45,75)=15$.', wrong: 'Parça sayısını cevaplamak.', check: '45/15=3, 75/15=5.' },
    { level: 'İleri', question: '$N=2^4\\cdot3\\cdot5^2$ sayısının bölen sayısı kaçtır?', options: ['24', '30', '36', '48'], answer: 1, idea: 'Üslere bir ekle ve çarp.', solution: '$(4+1)(1+1)(2+1)=5\\cdot2\\cdot3=30$.', wrong: 'Üsleri doğrudan çarpmak.', check: '1 ve sayının kendisi de seçeneklere dâhildir.' },
    { level: 'Karma', question: 'İki lamba 18 ve 24 saniyede bir yanıyor. Birlikte yandıktan sonraki 5 dakikada kaç kez yeniden birlikte yanarlar?', options: ['3', '4', '5', '6'], answer: 1, idea: 'EKOK 72 saniye; 300 saniyedeki pozitif katları say.', solution: '$72,144,216,288$; dört kez.', wrong: 'Başlangıç anını da saymak.', check: '$5\\cdot72=360>300$.' },
  ],
  simulation: { passage: 'Bir salonun 84 kırmızı ve 108 mavi sandalyesi, her sırada yalnız tek renk bulunacak ve bütün sıralarda eşit sayıda sandalye olacak biçimde dizilecektir.', question: 'Bir sıradaki sandalye sayısı en fazla kaç olabilir?', options: [option('6'), option('12', '84 ve 108in EBOBu 12dir.'), option('18'), option('24')], answer: 1, stemAnalysis: 'Sıra büyüklüğü her iki toplamı da artıksız bölmelidir; “en fazla” EBOBu seçtirir.', criticalPoint: '$84=7\\cdot12$ ve $108=9\\cdot12$.', takeaway: 'Aranan sıra sayısı değil, bir sıradaki sandalye sayısıdır; birim kontrolü sonucu yorumlatır.' },
  summary: ['$1$ asal değildir.', 'Asal çarpan gösterimi bölen yapısını görünür kılar.', 'EBOB ortak asallarda küçük, EKOK tüm asallarda büyük üsleri alır.', 'EBOB verilenleri böler; EKOK verilenlerin katıdır.', 'En büyük eş parça çoğunlukla EBOB, ilk ortak buluşma EKOKtur.', 'Bölen sayısı için asal üslerin bir fazlaları çarpılır.'],
  nextBody: 'Bölen ve kat yapısını kesir sadeleştirme ve ortak payda ile ilişkilendir.',
}, 4)

const rasyonel = defineLesson({
  topic: 'Rasyonel Sayılar',
  subtitle: 'Kesri parça-bütün modeliyle anlamlandır, sıralamayı ve işlemleri güvenli biçimde yap.',
  prerequisites: [{ topic: 'Temel Kavramlar', why: 'Sayı kümeleri ve işaret bilgisi gerekir.' }, { topic: 'OBEB - OKEK', why: 'Sadeleştirme ve ortak payda için kullanılır.' }],
  connections: ['Oran - Orantı', 'Basit Eşitsizlikler', 'Problemler'],
  mapCore: 'Bir bütünün veya iki niceliğin oranını kesir, ondalık ve sayı doğrusu temsilleri arasında dönüştürür.',
  openingLead: 'Kesir yalnız “üstteki bölü alttaki” değildir; bir oranı ve sayı doğrusundaki tek bir noktayı gösterir.',
  introduction: `Rasyonel sayı $\\frac ab$ biçiminde yazılabilen sayıdır; $a,b$ tam sayı ve $b\\ne0$dır. Eş değer kesirler aynı sayıyı farklı parçalarla anlatır. Pay ve paydayı aynı sıfır olmayan sayıyla çarpmak veya bölmek değeri değiştirmez.

Toplama-çıkarma için parçaların türü, yani payda eşitlenir. Çarpmada paylar ve paydalar çarpılır; bölmede ikinci kesrin çarpmaya göre tersiyle çarpılır.`,
  tytUse: 'Ölçü, yüzde, olasılık, karışım, zaman ve grafik sorularının ortak dilidir. Doğrudan rasyonel sayı etiketi az görünse de problem sorularının büyük kısmında ara beceridir.',
  struggle: 'Paydaları da toplamak, negatif işareti yanlış taşımak ve payda 0 yapan değeri kabul etmek.',
  osymBody: '2018-2026 boyunca rasyonel yapı hem doğrudan kesir/ondalık hem de problem modellerinde düzenli kullanılır. Temsil değiştirme ve yaklaşık büyüklük kontrolü öne çıkar.',
  osymMeasures: ['Parça-bütün', 'Eş değer kesir', 'Sıralama', 'Kesir-ondalık dönüşümü'],
  patternBody: 'Ölçek, doluluk, zaman dilimi, oran ve gösterge bağlamları yaygındır. Çeldirici çoğunlukla payda eşitlemeden toplama veya bütünü yanlış seçmedir.',
  patterns: ['Parça-bütün görseli', 'Ondalık ölçü', 'Oran tablosu', 'Sayı doğrusu'],
  readiness: [
    { prompt: '$\\frac{6}{8}$ kesrini sadeleştir.', answer: '$\\frac34$.', review: 'Ortak bölenle sadeleştirmeyi tekrar et.' },
    { prompt: '$0{,}25$ hangi basit kesirdir?', answer: '$\\frac14$.', review: 'Ondalık-kesir dönüşümünü tekrar et.' },
    { prompt: '$\\frac23$ mü $\\frac34$ mü büyüktür?', answer: '$\\frac34$; çapraz çarpımda $8<9$.', review: 'Kesir karşılaştırmayı çalış.' },
  ],
  concepts: [
    { term: 'Rasyonel sayı', definition: '$\\frac ab$ biçiminde yazılabilir; $a,b\\in\\mathbb Z$, $b\\ne0$.', why: 'Kesir, sonlu ve devirli ondalıkları tek kümede toplar.', boundary: 'Pay 0 olabilir; payda 0 olamaz.' },
    { term: 'Eş değer kesir', definition: '$\\frac ab=\\frac{ka}{kb}$, $k\\ne0$.', why: 'Aynı oranın farklı birim parçalarla gösterimidir.', boundary: 'Pay ve paydaya aynı sayıyı eklemek değeri korumaz.' },
    { term: 'Bütün', definition: 'Kesrin hangi toplamın parçası olduğunu belirleyen referanstır.', why: 'Problemde paydanın neyi saydığını doğru kurdurur.', boundary: 'Bütün değişirse aynı pay farklı kesir anlamına gelir.' },
  ],
  why: { question: 'Neden kesirler toplanırken payda eşitlenir?', body: '$\\frac12$ “iki eş parçadan bir”, $\\frac13$ “üç eş parçadan bir” demektir. Farklı büyüklükte parçalar doğrudan sayılamaz. Altıda bir büyüklüğünde ortak parçaya geçince $\\frac12=\\frac36$, $\\frac13=\\frac26$ ve toplam $\\frac56$ olur.', boundary: 'Bu alan modeli toplama-çıkarma sezgisidir; çarpmada payda eşitlemek gerekmez.' },
  formulas: [{ title: 'Kesir işlemleri', latex: '\\frac ab+\\frac cd=\\frac{ad+bc}{bd},\\quad \\frac ab\\div\\frac cd=\\frac ab\\cdot\\frac dc', meaning: 'Toplamada ortak parça oluşturulur; bölmede ikinci kesrin tersiyle çarpılır.', condition: '$b,d\\ne0$; bölmede ayrıca $c\\ne0$.', variables: [{ sym: 'a,b,c,d', desc: 'Tam sayılar; paydalar sıfır değildir' }] }],
  certainInfo: 'Bir kesrin değeri, pay ve paydanın aynı sıfır olmayan çarpanla genişletilip sadeleştirilmesiyle değişmez.',
  examples: [
    { title: 'Ortak payda', prompt: '$\\frac34-\\frac5{12}$ işlemini yap.', steps: [step('Paydayı eşitle', '$\\frac34=\\frac9{12}$.'), step('Çıkar', '$\\frac9{12}-\\frac5{12}=\\frac4{12}$.'), step('Sadeleştir', '$\\frac13$.')], answer: '$\\frac13$', takeaway: 'Payda eşitlenince yalnız paylar işleme girer.', check: 'Yaklaşık $0{,}75-0{,}42\\approx0{,}33$.' },
    { title: 'Bölme', prompt: '$\\frac56\\div\\frac{10}{9}$ işlemini hesapla.', steps: [step('Ters çevir ve çarp', '$\\frac56\\cdot\\frac9{10}$.'), step('Sadeleştir', '$\\frac{3}{4}$.')], answer: '$\\frac34$', takeaway: 'İkinci kesir sıfır olamaz.', check: '$\\frac56$yı 1den büyük bir sayıya bölünce sonuç küçülmelidir.' },
    { title: 'Sıralama', prompt: '$-\\frac23$, $-0{,}6$ ve $-\\frac58$ sayılarını küçükten büyüğe sırala.', steps: [step('Ondalığa yaklaştır', '$-\\frac23\\approx-0{,}667$, $-\\frac58=-0{,}625$.'), step('Negatif yönü oku', 'Daha büyük mutlak değer daha küçüktür.')], answer: '$-\\frac23<-\\frac58<-0{,}6$', takeaway: 'Negatiflerde sayı doğrusu yönünü unutma.', check: 'Üçü de $-1$ ile $0$ arasındadır.' },
    { title: 'Bütünü doğru seç', prompt: 'Bir sınıfın $\\frac25$i kızdır. Kızların $\\frac14$ü gözlüklüyse sınıfın kaçta kaçı gözlüklü kızdır?', steps: [step('İç içe parça', '$\\frac14$ of $\\frac25$.'), step('Çarp', '$\\frac14\\cdot\\frac25=\\frac1{10}$.')], answer: '$\\frac1{10}$', takeaway: '“Bir parçanın parçası” çarpma modelidir.', check: 'Sonuç kızların oranından küçük olmalı.' },
    { title: 'Devirli ondalık', prompt: '$0{,}\\overline{3}$ sayısını kesre çevir.', steps: [step('Değişken', '$x=0{,}\\overline3$.'), step('Bir basamak kaydır', '$10x=3{,}\\overline3$.'), step('Çıkar', '$9x=3\\Rightarrow x=\\frac13$.')], answer: '$\\frac13$', takeaway: 'Tekrarlayan kısmı çıkarma ile yok et.', check: '$1\\div3=0{,}333\\ldots$.' },
  ],
  recognitionIntro: '“Kaçta kaçı”, doluluk, oran, yüzde veya ondalık ölçü görünce önce bütünü ve birimi sabitle.',
  decisionTree: [{ question: 'Toplama/çıkarma mı?', yes: 'Paydaları eşitle.', no: 'Çarpma/bölme veya karşılaştırma olabilir.' }, { question: 'Bir parçanın parçası mı?', yes: 'Kesirleri çarp.', no: 'Aynı bütün üzerindeki oranları karşılaştır.' }, { question: 'Negatif kesir var mı?', yes: 'Sayı doğrusu yönünü ayrıca kontrol et.', no: 'Çapraz çarpım veya ortak payda kullan.' }],
  recognitionTakeaway: 'Bütünü adlandırmadan kesir işlemi yapma; sonuç büyüklüğünü önceden tahmin et.',
  tactic: { title: 'Önce büyüklük tahmini', logic: 'İşlemden önce sonucun 0-1 arasında mı, negatif mi, ilk sayıdan küçük mü olması gerektiğini söyle.', works: 'Kesir işlemi, problem ve seçenek eleme.', risk: 'Tahmin kesin hesap yerine geçmez; yakın seçeneklerde işlem gerekir.', steps: [step('İşaret', 'Pozitif/negatif?'), step('Aralık', '0-1, 1den büyük veya başka sınır?'), step('İşlemin etkisi', 'Çarpan 1den küçükse büyüklük azalır.'), step('Kesin işlemi yap', 'Tahminle sonucu karşılaştır.')] },
  traps: [
    { title: 'Payda toplamak', wrong: '$\\frac12+\\frac13=\\frac25$.', right: '$\\frac36+\\frac26=\\frac56$.', cause: 'Farklı büyüklükte parçaları aynı tür sanmak.', check: '$\\frac12+\\frac13$ yarımdan büyük olmalı; $\\frac25$ küçüktür.' },
    { title: 'Sadeleştirmede toplama yapmak', wrong: 'Pay ve paydaya aynı sayıyı eklemek.', right: 'Yalnız aynı sıfır olmayan çarpanla çarpma/bölme değeri korur.', cause: '“İkisine de aynı işlem” cümlesini koşulsuz genellemek.', check: '$\\frac12$ ile $\\frac23$ün eşit olmadığını gör.' },
    { title: 'Paydayı sıfır yapmak', wrong: 'Rasyonel ifadede payda 0 yapan değeri çözüm kabul etmek.', right: 'Tanım koşulu işlemden önce yazılır.', cause: 'Denklemi çözüp başlangıç ifadesine dönmemek.', check: 'Bulduğun değeri orijinal paydada yerine koy.' },
  ],
  questions: [
    { level: 'Temel', question: '$\\frac23+\\frac16$ kaçtır?', options: ['$\\frac39$', '$\\frac56$', '$\\frac12$', '$1$'], answer: 1, idea: '$\\frac23=\\frac46$.', solution: '$\\frac46+\\frac16=\\frac56$.', wrong: 'Pay ve paydayı ayrı toplamak.', check: 'Sonuç $\\frac23$ten büyük, 1den küçük.' },
    { level: 'Temel', question: '$\\frac35$in $\\frac23$ü kaçtır?', options: ['$\\frac15$', '$\\frac25$', '$\\frac59$', '$\\frac56$'], answer: 1, idea: 'Bir parçanın parçası çarpılır.', solution: '$\\frac35\\cdot\\frac23=\\frac25$.', wrong: 'Payda eşitlemek.', check: 'Sonuç $\\frac35$ten küçük.' },
    { level: 'Orta', question: 'Hangisi en büyüktür?', options: ['$\\frac78$', '$0{,}86$', '$\\frac56$', '$0{,}9$'], answer: 3, idea: 'Aynı temsile dönüştür.', solution: '$\\frac78=0{,}875$, $\\frac56\\approx0{,}833$; en büyük $0{,}9$.', wrong: 'Payı büyük kesri büyük sanmak.', check: 'Hepsi 1den küçüktür.' },
    { level: 'İleri', question: '$\\frac{x-1}{x+2}=0$ denkleminin çözümü nedir?', options: ['$-2$', '$-1$', '$1$', 'Çözüm yok'], answer: 2, idea: 'Kesrin 0 olması için pay 0, payda 0dan farklı olmalı.', solution: '$x-1=0\\Rightarrow x=1$; payda 3.', wrong: 'Paydayı 0 yapan $-2$yi seçmek.', check: '$x=1$ yerine konunca sonuç 0.' },
    { level: 'Karma', question: 'Bir deponun önce $\\frac14$ü, sonra kalan kısmın $\\frac13$ü boşaltılıyor. Deponun kaçta kaçı kalır?', options: ['$\\frac12$', '$\\frac7{12}$', '$\\frac23$', '$\\frac34$'], answer: 0, idea: 'İkinci kesrin bütünü kalan kısımdır.', solution: 'İlkten sonra $\\frac34$ kalır; bunun $\\frac13$ü yani $\\frac14$ boşalır. $\\frac12$ kalır.', wrong: '$\\frac14+\\frac13$ü doğrudan bütünden çıkarmak.', check: 'Başlangıcı 12 birim al: 3, sonra 3 boşalır; 6 kalır.' },
  ],
  simulation: { passage: 'Bir yürüyüş yolunun ilk gün $\\frac38$i, ikinci gün kalan bölümün $\\frac25$i tamamlanıyor.', question: 'İki gün sonunda yolun kaçta kaçı tamamlanmıştır?', options: [option('$\\frac{23}{40}$', 'Kalan $\\frac58$in $\\frac25$i $\\frac14$tür; toplam $\\frac38+\\frac14=\\frac58$ olmalı.'), option('$\\frac58$', 'Doğru.'), option('$\\frac34$'), option('$\\frac45$')], answer: 1, stemAnalysis: 'İkinci gün oranı bütün yolun değil, kalan yolun oranıdır.', criticalPoint: '$\\frac25\\cdot\\frac58=\\frac14$.', takeaway: '“Kalanın” kelimesi yeni bütünü değiştirir.' },
  summary: ['$\\frac ab$ için $b\\ne0$.', 'Toplama-çıkarma ortak payda; çarpma doğrudan; bölme ikinci kesrin tersiyle çarpma.', 'Bir parçanın parçası çarpma ile bulunur.', 'Negatif kesirlerde sayı doğrusu yönünü kontrol et.', 'Kesir, ondalık ve yüzde aynı değerin farklı temsilleridir.', 'İşlemden önce sonuç büyüklüğünü tahmin et.'],
  nextBody: 'Rasyonel büyüklükleri eşitsizlikte sıralamaya ve oran problemlerinde modellemeye geç.',
}, 5)

export const CORE_MATH_LESSONS = [temelKavramlar, sayiBasamaklari, bolme, ebobEkok, rasyonel]
