/**
 * DRKOÇ — İSPANYOLCA SEVİYE TESPİT MADDE BANKASI
 * ==================================================================
 *
 * Bu bankanın amacı öğrenciyi ELEMEK değil, nereden başlayacağını
 * bulmaktır. Bu yüzden maddeler "zor soru" olarak değil, BASAMAK olarak
 * seçildi: her madde belirli bir seviyenin ayırt edici yapısını ölçer.
 *
 * SEÇİM ÖLÇÜTÜ: bir maddenin bankaya girebilmesi için, o seviyeyi geçmiş
 * bir öğrencinin doğru, geçmemiş bir öğrencinin yanlış yapma olasılığının
 * yüksek olması gerekir.
 *
 * İSPANYOLCAYA ÖZGÜ AYIRT EDİCİLER — hangi seviyede neyin ölçüldüğü:
 *   Pre-A1 → temel kelime tanıma, sayı, selamlaşma, okuma
 *   A1     → ser/estar, tener ile yaş, cinsiyet, gustar, presente
 *   A2     → indefinido, nesne zamirleri, muy/mucho, por/para
 *   B1     → indefinido/imperfecto ayrımı, subjuntivo girişi, koşul
 *   B2     → subjuntivo kullanımı, ince edat ve eşdizim seçimi
 *   C1     → deyim, üslup, örtük anlam
 *
 * Sınav uyarlanabilirdir (bkz. lib/ispanyolca/seviyeTespit.js): doğru
 * cevapta zorluk yükselir, yanlışta düşer.
 */

export const MADDELER = [
  /* ---------------------------- Pre-A1 ---------------------------- */
  {
    id: 'st-p1',
    seviye: 'Pre-A1',
    beceri: 'kelime',
    tur: 'coktan-secmeli',
    yonerge: 'Doğru karşılığı seç.',
    soru: '"el libro" ne demek?',
    secenekler: [
      { id: 'a', metin: 'kitap' },
      { id: 'b', metin: 'masa' },
      { id: 'c', metin: 'kapı' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-p2',
    seviye: 'Pre-A1',
    beceri: 'kelime',
    tur: 'coktan-secmeli',
    yonerge: 'Akşam saat 21:00’de birini selamlıyorsun.',
    soru: 'Doğru selamlama hangisi?',
    secenekler: [
      { id: 'a', metin: 'Buenas noches' },
      { id: 'b', metin: 'Buenos días' },
      { id: 'c', metin: 'Buenas tardes' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-p3',
    seviye: 'Pre-A1',
    beceri: 'kelime',
    tur: 'coktan-secmeli',
    yonerge: 'Sayıyı seç.',
    soru: '"doce" kaçtır?',
    secenekler: [
      { id: 'a', metin: '12' },
      { id: 'b', metin: '2' },
      { id: 'c', metin: '20' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-p4',
    seviye: 'Pre-A1',
    beceri: 'telaffuz',
    tur: 'coktan-secmeli',
    yonerge: 'Okunuşu seç.',
    soru: '"hola" kelimesi nasıl okunur?',
    secenekler: [
      { id: 'a', metin: '"ola" (h okunmaz)' },
      { id: 'b', metin: '"hola"' },
      { id: 'c', metin: '"hola" (sert h)' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-p5',
    seviye: 'Pre-A1',
    beceri: 'dinleme',
    tur: 'dinle-sec',
    yonerge: 'Dinle ve duyduğunu seç.',
    seslendir: '¡Muchas gracias!',
    secenekler: [
      { id: 'a', metin: '¡Muchas gracias!' },
      { id: 'b', metin: '¡Muchos grados!' },
      { id: 'c', metin: '¡Mucha gracia!' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-p6',
    seviye: 'Pre-A1',
    beceri: 'kelime',
    tur: 'tanim-kelime',
    yonerge: 'Tanımı okuyup kelimeyi yaz.',
    tanim: 'Es la persona que enseña en una clase.',
    ilkHarf: 'p',
    kabul: ['profesor', 'el profesor', 'profesora', 'maestro'],
  },

  /* ------------------------------ A1 ------------------------------ */
  {
    id: 'st-a1-1',
    seviye: 'A1',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Boşluğa hangisi gelir?',
    soru: '____ estudiante.',
    secenekler: [
      { id: 'a', metin: 'Soy' },
      { id: 'b', metin: 'Estoy' },
      { id: 'c', metin: 'Tengo' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-a1-2',
    seviye: 'A1',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Boşluğa hangisi gelir?',
    soru: '____ dieciséis años.',
    secenekler: [
      { id: 'a', metin: 'Tengo' },
      { id: 'b', metin: 'Soy' },
      { id: 'c', metin: 'Estoy' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-a1-3',
    seviye: 'A1',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Doğru artikeli seç.',
    soru: '____ casa de mis padres es grande.',
    secenekler: [
      { id: 'a', metin: 'La' },
      { id: 'b', metin: 'El' },
      { id: 'c', metin: 'Los' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-a1-4',
    seviye: 'A1',
    beceri: 'gramer',
    tur: 'hata-bul',
    yonerge: 'Cümlede bir hata var. Doğru biçimini yaz.',
    cumle: 'Soy en casa ahora.',
    hataliParca: 'Soy',
    dogruParca: 'Estoy',
    kabul: ['Estoy en casa ahora', 'Estoy en casa', 'Estoy'],
  },
  {
    id: 'st-a1-5',
    seviye: 'A1',
    beceri: 'dizim',
    tur: 'siralama',
    yonerge: 'Kelimeleri sıralayarak doğru cümleyi kur.',
    parcalar: ['al', 'Voy', 'instituto'],
    dogruSira: [1, 0, 2],
  },
  {
    id: 'st-a1-6',
    seviye: 'A1',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Doğru çekimi seç.',
    soru: 'Nosotros ____ español en clase.',
    secenekler: [
      { id: 'a', metin: 'hablamos' },
      { id: 'b', metin: 'habláis' },
      { id: 'c', metin: 'habla' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-a1-7',
    seviye: 'A1',
    beceri: 'dinleme',
    tur: 'dinle-sec',
    yonerge: 'Dinle ve duyduğunu seç.',
    seslendir: 'Tiene dos hermanos.',
    secenekler: [
      { id: 'a', metin: 'Tiene dos hermanos.' },
      { id: 'b', metin: 'Tienen dos hermanos.' },
      { id: 'c', metin: 'Es dos hermanos.' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-a1-8',
    seviye: 'A1',
    beceri: 'kelime',
    tur: 'bosluk',
    yonerge: 'Boşluğu doldur.',
    parcalar: ['Perdone, ¿', { bosluk: 0 }, ' está la estación?'],
    cevaplar: [{ kabul: ['dónde', 'donde'], ipucu: 'yer soran kelime' }],
  },

  /* ------------------------------ A2 ------------------------------ */
  {
    id: 'st-a2-1',
    seviye: 'A2',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Boşluğa hangisi gelir?',
    soru: 'Ayer ____ en un restaurante.',
    secenekler: [
      { id: 'a', metin: 'comí' },
      { id: 'b', metin: 'como' },
      { id: 'c', metin: 'comeré' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-a2-2',
    seviye: 'A2',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Boşluğa hangisi gelir?',
    soru: 'El mes pasado ____ a Madrid.',
    secenekler: [
      { id: 'a', metin: 'fui' },
      { id: 'b', metin: 'voy' },
      { id: 'c', metin: 'iba' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-a2-3',
    seviye: 'A2',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Boşluğa hangisi gelir?',
    soru: 'A mí ____ los libros de historia.',
    secenekler: [
      { id: 'a', metin: 'me gustan' },
      { id: 'b', metin: 'me gusta' },
      { id: 'c', metin: 'yo gusto' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-a2-4',
    seviye: 'A2',
    beceri: 'gramer',
    tur: 'hata-bul',
    yonerge: 'Cümlede bir hata var. Doğru biçimini yaz.',
    cumle: 'Voy a el cine esta tarde.',
    hataliParca: 'a el',
    dogruParca: 'al',
    kabul: ['Voy al cine esta tarde', 'al', 'Voy al cine'],
  },
  {
    id: 'st-a2-5',
    seviye: 'A2',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Doğru biçimi seç.',
    soru: 'Mi hermana es muy ____.',
    secenekler: [
      { id: 'a', metin: 'simpática' },
      { id: 'b', metin: 'simpático' },
      { id: 'c', metin: 'simpáticos' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-a2-6',
    seviye: 'A2',
    beceri: 'kelime',
    tur: 'bosluk',
    yonerge: 'muy ya da mucho yaz.',
    parcalar: ['El examen es ', { bosluk: 0 }, ' difícil y tengo ', { bosluk: 1 }, ' trabajo.'],
    cevaplar: [
      { kabul: ['muy'], ipucu: 'sıfat önünde' },
      { kabul: ['mucho'], ipucu: 'isim önünde' },
    ],
  },
  {
    id: 'st-a2-7',
    seviye: 'A2',
    beceri: 'dizim',
    tur: 'siralama',
    yonerge: 'Kelimeleri sıralayarak doğru soruyu kur.',
    parcalar: ['haces', 'Qué', 'esta tarde'],
    dogruSira: [1, 0, 2],
  },
  {
    id: 'st-a2-8',
    seviye: 'A2',
    beceri: 'dusunme',
    tur: 'dogal-secim',
    yonerge: 'İkisi de dil bilgisi bakımından doğru. Hangisi doğal?',
    baglam: 'Bir mağazada bir çantanın fiyatını soruyorsun.',
    secenekler: [
      { id: 'a', metin: '¿Cuánto cuesta?', dogal: true, neden: 'Günlük dilde fiyat böyle sorulur.' },
      { id: 'b', metin: '¿Cuál es el precio de este bolso?', dogal: false, neden: 'Doğru ama resmî ve kitabi; konuşmada nadiren duyulur.' },
    ],
  },
  {
    id: 'st-a2-9',
    seviye: 'A2',
    beceri: 'dinleme',
    tur: 'dinle-yaz',
    yonerge: 'Dinle ve duyduğun cümleyi yaz.',
    seslendir: 'Tenemos dos hijos.',
    kabul: ['Tenemos dos hijos', 'tenemos dos hijos'],
  },
  {
    id: 'st-a2-10',
    seviye: 'A2',
    beceri: 'kelime',
    tur: 'coktan-secmeli',
    yonerge: 'Doğru kelimeyi seç.',
    soru: 'Gracias ____ tu ayuda.',
    secenekler: [
      { id: 'a', metin: 'por' },
      { id: 'b', metin: 'para' },
      { id: 'c', metin: 'de' },
    ],
    dogruId: 'a',
  },

  /* ------------------------------ B1 ------------------------------ */
  {
    id: 'st-b1-1',
    seviye: 'B1',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Boşluğa hangisi gelir?',
    soru: 'Cuando era pequeño, ____ mucho al parque.',
    secenekler: [
      { id: 'a', metin: 'iba' },
      { id: 'b', metin: 'fui' },
      { id: 'c', metin: 'iré' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-b1-2',
    seviye: 'B1',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Cümleyi tamamla.',
    soru: 'Le di el libro. → "le" burada neyin yerine geçiyor?',
    secenekler: [
      { id: 'a', metin: 'kişi (dolaylı nesne)' },
      { id: 'b', metin: 'nesne (doğrudan nesne)' },
      { id: 'c', metin: 'yer' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-b1-3',
    seviye: 'B1',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Boşluğa hangisi gelir?',
    soru: 'Si tuviera tiempo, ____ contigo.',
    secenekler: [
      { id: 'a', metin: 'iría' },
      { id: 'b', metin: 'iré' },
      { id: 'c', metin: 'voy' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-b1-4',
    seviye: 'B1',
    beceri: 'gramer',
    tur: 'hata-bul',
    yonerge: 'Cümlede bir hata var. Doğru biçimini yaz.',
    cumle: 'Espero que tienes razón.',
    hataliParca: 'tienes',
    dogruParca: 'tengas',
    kabul: ['Espero que tengas razón', 'tengas', 'Espero que tengas razon'],
  },
  {
    id: 'st-b1-5',
    seviye: 'B1',
    beceri: 'kelime',
    tur: 'coktan-secmeli',
    yonerge: 'Doğru kelimeyi seç.',
    soru: 'Tengo que ____ a la reunión de mañana.',
    secenekler: [
      { id: 'a', metin: 'asistir' },
      { id: 'b', metin: 'atender' },
      { id: 'c', metin: 'esperar' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-b1-6',
    seviye: 'B1',
    beceri: 'dusunme',
    tur: 'dogal-secim',
    yonerge: 'Hangisi daha doğal?',
    baglam: 'Bir öneriyi kibarca reddediyorsun.',
    secenekler: [
      { id: 'a', metin: 'Te lo agradezco, pero no puedo.', dogal: true, neden: 'Önce teşekkür, sonra ret — beklenen sıra budur.' },
      { id: 'b', metin: 'No, no quiero.', dogal: false, neden: 'Dil bilgisi doğru ama kaba duyulur.' },
    ],
  },
  {
    id: 'st-b1-7',
    seviye: 'B1',
    beceri: 'dinleme',
    tur: 'dinle-sec',
    yonerge: 'Dinle ve duyduğunu seç.',
    seslendir: 'Cogieron el tren de las ocho.',
    secenekler: [
      { id: 'a', metin: 'Cogieron el tren de las ocho.' },
      { id: 'b', metin: 'Cogimos el tren de las ocho.' },
      { id: 'c', metin: 'Cogía el tren de las ocho.' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-b1-8',
    seviye: 'B1',
    beceri: 'gramer',
    tur: 'bosluk',
    yonerge: 'Boşluğu doldur.',
    parcalar: ['Es necesario que ', { bosluk: 0 }, ' los deberes antes de salir.'],
    cevaplar: [{ kabul: ['hagas', 'haga'], ipucu: 'es necesario que → subjuntivo' }],
  },
  {
    id: 'st-b1-9',
    seviye: 'B1',
    beceri: 'okuma',
    tur: 'coktan-secmeli',
    yonerge: 'Metni okuyup soruyu cevapla.',
    soru: '"A pesar de la lluvia, decidieron salir." — Ne olmuş?',
    secenekler: [
      { id: 'a', metin: 'Yağmura rağmen çıkmaya karar vermişler.' },
      { id: 'b', metin: 'Yağmur yüzünden kalmışlar.' },
      { id: 'c', metin: 'Yağmuru beklemişler.' },
    ],
    dogruId: 'a',
  },

  /* ------------------------------ B2 ------------------------------ */
  {
    id: 'st-b2-1',
    seviye: 'B2',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Boşluğa hangisi gelir?',
    soru: 'Aunque ____ cansado, siguió trabajando.',
    secenekler: [
      { id: 'a', metin: 'estaba' },
      { id: 'b', metin: 'esté' },
      { id: 'c', metin: 'estará' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-b2-2',
    seviye: 'B2',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Edilgen biçimi seç.',
    soru: '"El profesor corrige los exámenes." cümlesinin edilgeni hangisidir?',
    secenekler: [
      { id: 'a', metin: 'Los exámenes son corregidos por el profesor.' },
      { id: 'b', metin: 'Los exámenes corrigen al profesor.' },
      { id: 'c', metin: 'El profesor es corregido los exámenes.' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-b2-3',
    seviye: 'B2',
    beceri: 'kelime',
    tur: 'coktan-secmeli',
    yonerge: 'En uygun eşdizimi seç.',
    soru: 'Ha ____ una decisión importante.',
    secenekler: [
      { id: 'a', metin: 'tomado' },
      { id: 'b', metin: 'hecho' },
      { id: 'c', metin: 'dado' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-b2-4',
    seviye: 'B2',
    beceri: 'dusunme',
    tur: 'dogal-secim',
    yonerge: 'Hangisi daha doğal?',
    baglam: 'Bir tartışmada karşı görüşe geçiş yapıyorsun.',
    secenekler: [
      { id: 'a', metin: 'Dicho esto, no hay que olvidar que…', dogal: true, neden: 'Karşı görüşe yumuşak geçiş için kullanılan standart bağlayıcıdır.' },
      { id: 'b', metin: 'No, eso es falso.', dogal: false, neden: 'Doğru ama tartışma dilinde sert ve kestirip atan bir ifadedir.' },
    ],
  },
  {
    id: 'st-b2-5',
    seviye: 'B2',
    beceri: 'okuma',
    tur: 'coktan-secmeli',
    yonerge: 'Yazarın tutumunu seç.',
    soru: '"Este proyecto, por ambicioso que sea, resulta difícilmente viable." — Yazar ne düşünüyor?',
    secenekler: [
      { id: 'a', metin: 'Proje iddialı ama gerçekleşmesi zor.' },
      { id: 'b', metin: 'Proje kolayca gerçekleşir.' },
      { id: 'c', metin: 'Proje iddialı değil.' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-b2-6',
    seviye: 'B2',
    beceri: 'gramer',
    tur: 'hata-bul',
    yonerge: 'Cümlede bir hata var. Doğru biçimini yaz.',
    cumle: 'Cuando llegué, ella ya se fue.',
    hataliParca: 'se fue',
    dogruParca: 'se había ido',
    kabul: ['Cuando llegué, ella ya se había ido', 'se había ido', 'se habia ido'],
  },

  /* ------------------------------ C1 ------------------------------ */
  {
    id: 'st-c1-1',
    seviye: 'C1',
    beceri: 'kelime',
    tur: 'coktan-secmeli',
    yonerge: 'Deyimin anlamını seç.',
    soru: '"Meter la pata" ne demek?',
    secenekler: [
      { id: 'a', metin: 'Pot kırmak, gaf yapmak.' },
      { id: 'b', metin: 'Ayağını uzatmak.' },
      { id: 'c', metin: 'İşe başlamak.' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-c1-2',
    seviye: 'C1',
    beceri: 'kelime',
    tur: 'coktan-secmeli',
    yonerge: 'En uygun kelimeyi seç.',
    soru: 'Su argumentación, aunque ____, no convenció a nadie.',
    secenekler: [
      { id: 'a', metin: 'rigurosa' },
      { id: 'b', metin: 'rígida' },
      { id: 'c', metin: 'ridícula' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-c1-3',
    seviye: 'C1',
    beceri: 'okuma',
    tur: 'coktan-secmeli',
    yonerge: 'Örtük anlamı seç.',
    soru: '"No se puede decir que esta película sea una obra maestra." — Konuşan ne demek istiyor?',
    secenekler: [
      { id: 'a', metin: 'Film pek iyi değil (kibar bir olumsuzlama).' },
      { id: 'b', metin: 'Film bir başyapıt.' },
      { id: 'c', metin: 'Filmi izlemedi.' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-c1-4',
    seviye: 'C1',
    beceri: 'dusunme',
    tur: 'dogal-secim',
    yonerge: 'Akademik metinde hangisi uygundur?',
    baglam: 'Bir makalede sonuç bölümüne geçiyorsun.',
    secenekler: [
      { id: 'a', metin: 'En definitiva, cabe señalar que…', dogal: true, neden: 'Akademik üsluba uygun, ölçülü bir sonuç bağlayıcısıdır.' },
      { id: 'b', metin: 'Bueno, pues eso.', dogal: false, neden: 'Tamamen sözlü ve gündelik bir kapanıştır; yazıda kullanılmaz.' },
    ],
  },
  {
    id: 'st-c1-5',
    seviye: 'C1',
    beceri: 'gramer',
    tur: 'coktan-secmeli',
    yonerge: 'Doğru biçimi seç.',
    soru: 'Las medidas ____ el gobierno ha tomado son polémicas.',
    secenekler: [
      { id: 'a', metin: 'que' },
      { id: 'b', metin: 'quien' },
      { id: 'c', metin: 'cuyas' },
    ],
    dogruId: 'a',
  },
  {
    id: 'st-c1-6',
    seviye: 'C1',
    beceri: 'dinleme',
    tur: 'dinle-sec',
    yonerge: 'Dinle ve duyduğunu seç.',
    seslendir: 'Habría sido mejor que nos hubiéramos dado cuenta antes.',
    secenekler: [
      { id: 'a', metin: 'Habría sido mejor que nos hubiéramos dado cuenta antes.' },
      { id: 'b', metin: 'Ha sido mejor que nos hemos dado cuenta antes.' },
      { id: 'c', metin: 'Sería mejor que nos diéramos cuenta antes.' },
    ],
    dogruId: 'a',
  },
]

export const YAZMA_GOREVI = {
  id: 'st-yazma',
  seviye: 'A2',
  beceri: 'yazma',
  tur: 'yazma',
  yonerge: 'Son adım: kendini kısaca tanıt. Ne kadar yazabiliyorsan o kadar yaz — kısa yazman sonucu bozmaz, yalnız daha az bilgi verir.',
  gorev: 'Escribe unas frases sobre ti en español: ¿quién eres, dónde vives, qué haces y por qué estudias español?',
  ornekMetin: null,
  kaliplar: [],
  asamalar: [
    { ad: 'Yaz', aciklama: 'Aklına geldiği gibi yaz. Bu bir sınav değil, ölçüm.' },
  ],
  olcut: [
    'Kendimi tanıttım (Me llamo… / Soy…).',
    'Nerede yaşadığımı yazdım.',
    'Ne yaptığımı (okul/iş) yazdım.',
    'Neden İspanyolca öğrendiğimi yazdım.',
    'Yaşı "tener" ile söyledim.',
  ],
  enAzKelime: 25,
  aranan: [
    { etiket: 'ser fiili', desen: /\b(soy|eres|es|somos|sois|son)\b/i },
    { etiket: 'presente fiili', desen: /\b(vivo|hablo|estudio|trabajo|tengo|voy|hago|aprendo)\b/i },
    { etiket: 'bağlaç (y/pero/porque)', desen: /\b(y|pero|porque|además|o)\b/i },
    { etiket: 'geçmiş ya da gelecek', desen: /\b(fui|estuve|tuve|hice|voy a \w+r|quiero|me gustaría)\b/i },
    { etiket: 'amaç bildirme (para / porque)', desen: /\b(para \w+r|porque)\b/i },
  ],
}
