/**
 * DESTE — FUTBOL VE SPOR (İspanyolca)
 *
 * İspanyolca futbol dili dünyada en çok duyulan futbol dilidir; öğrenci
 * bu kelimelerin çoğunu maç anlatımlarından zaten duymuştur. Kartlar bu
 * tanıdıklığı kullanır ve üstüne doğru artikeli ekler.
 */

export const DESTE = {
  id: 'futbol-spor',
  dil: 'es',
  ad: 'Futbol ve spor',
  simge: '⚽',
  aciklama: 'Maç anlatımında ve tribünde geçen kelimeler — artikelleriyle.',
  seviye: 'A1–A2',
  kartlar: [
    {
      id: 'es-fut-01', on: 'el gol', okunus: 'el gol', tur: 'isim (eril)',
      arka: 'gol',
      ornek: 'Marcó un gol en el último minuto.',
      ornekTr: 'Son dakikada bir gol attı.',
      not: 'Gol atmak "marcar un gol"dur. Çoğulu "los goles".',
    },
    {
      id: 'es-fut-02', on: 'el partido', okunus: 'el partido', tur: 'isim (eril)',
      arka: 'maç',
      ornek: 'El partido empieza a las nueve.',
      ornekTr: 'Maç dokuzda başlıyor.',
      not: 'Aynı kelime siyasi "parti" anlamına da gelir; bağlam ayırır.',
    },
    {
      id: 'es-fut-03', on: 'el equipo', okunus: 'el ekipo', tur: 'isim (eril)',
      arka: 'takım',
      ornek: 'Mi equipo favorito ganó ayer.',
      ornekTr: 'En sevdiğim takım dün kazandı.',
      not: 'Türkçedeki "ekip" kelimesiyle aynı kökten. Erildir.',
    },
    {
      id: 'es-fut-04', on: 'ganar', okunus: 'ganar', tur: 'fiil',
      arka: 'kazanmak',
      ornek: 'Vamos a ganar este partido.',
      ornekTr: 'Bu maçı kazanacağız.',
      not: 'Hem maç hem para kazanmak için kullanılır.',
    },
    {
      id: 'es-fut-05', on: 'perder', okunus: 'perder', tur: 'fiil (kök değişimli)',
      arka: 'kaybetmek',
      ornek: 'Perdieron dos a cero.',
      ornekTr: 'İki sıfır kaybettiler.',
      not: 'Kök değişir: pierdo, pierdes… Skor "a" ile: dos a cero.',
    },
    {
      id: 'es-fut-06', on: 'el entrenador', okunus: 'el entrenador', tur: 'isim (eril)',
      arka: 'teknik direktör',
      ornek: 'El entrenador cambió a tres jugadores.',
      ornekTr: 'Teknik direktör üç oyuncu değiştirdi.',
      not: 'Dişili "la entrenadora". Antrenman "el entrenamiento".',
    },
    {
      id: 'es-fut-07', on: 'el jugador', okunus: 'el hugador', tur: 'isim (eril)',
      arka: 'oyuncu',
      ornek: 'Es el mejor jugador del mundo.',
      ornekTr: 'Dünyanın en iyi oyuncusu.',
      not: '"jugar" (oynamak) fiilinden. Baştaki "j" gırtlaktan okunur.',
    },
    {
      id: 'es-fut-08', on: 'la afición', okunus: 'la afisyon', tur: 'isim (dişil)',
      arka: 'taraftar topluluğu',
      ornek: 'La afición llenó el estadio.',
      ornekTr: 'Taraftarlar stadyumu doldurdu.',
      not: 'Tek bir taraftar "el aficionado / la aficionada"dır.',
    },
    {
      id: 'es-fut-09', on: 'entrenar', okunus: 'entrenar', tur: 'fiil',
      arka: 'antrenman yapmak',
      ornek: 'Entreno tres veces por semana.',
      ornekTr: 'Haftada üç kez antrenman yapıyorum.',
      not: 'Sıklık "veces por semana" ile söylenir.',
    },
    {
      id: 'es-fut-10', on: 'lesionarse', kok: 'lesion', okunus: 'lesyonarse', tur: 'fiil (dönüşlü)',
      arka: 'sakatlanmak',
      ornek: 'Se lesionó en el entrenamiento.',
      ornekTr: 'Antrenmanda sakatlandı.',
      not: 'Dönüşlüdür: me lesiono, te lesionas… Sakatlık "la lesión".',
    },
    /* --- Mevkiler ve takım --- */
    {
      id: 'es-fut-11', on: 'el portero', okunus: 'el portero', tur: 'isim (eril)',
      arka: 'kaleci',
      ornek: 'El portero paró tres tiros.',
      ornekTr: 'Kaleci üç şut kurtardı.',
      not: 'Aynı kelime "kapıcı" anlamına da gelir.',
    },
    {
      id: 'es-fut-12', on: 'el delantero', okunus: 'el delantero', tur: 'isim (eril)',
      arka: 'forvet',
      ornek: 'El delantero es muy rápido.',
      ornekTr: 'Forvet çok hızlı.',
      not: '"delante" ön, ileri demektir.',
    },
    {
      id: 'es-fut-13', on: 'el defensa', okunus: 'el defensa', tur: 'isim (eril)',
      arka: 'defans oyuncusu',
      ornek: 'El defensa juega con mucha calma.',
      ornekTr: 'Defans oyuncusu çok sakin oynuyor.',
      not: 'Kelime "-a" ile bitse de oyuncu için eril artikel alır.',
    },
    {
      id: 'es-fut-14', on: 'el centrocampista', okunus: 'el sentrokampista', tur: 'isim (eril)',
      arka: 'orta saha oyuncusu',
      ornek: 'El centrocampista controla el partido.',
      ornekTr: 'Orta saha oyuncusu maçı yönetiyor.',
      not: '"centro" merkez, "campo" saha demektir.',
    },
    {
      id: 'es-fut-15', on: 'el árbitro', okunus: 'el arbitro', tur: 'isim (eril)',
      arka: 'hakem',
      ornek: 'El árbitro pitó el final del partido.',
      ornekTr: 'Hakem maçın bitiş düdüğünü çaldı.',
      not: '"pitar" düdük çalmak demektir.',
    },
    {
      id: 'es-fut-16', on: 'el capitán', okunus: 'el kapitan', tur: 'isim (eril)',
      arka: 'kaptan',
      ornek: 'El capitán lleva el brazalete.',
      ornekTr: 'Kaptan pazubandı takıyor.',
      not: '"el brazalete" pazuband demektir.',
    },
    {
      id: 'es-fut-17', on: 'el suplente', okunus: 'el suplente', tur: 'isim (eril)',
      arka: 'yedek oyuncu',
      ornek: 'El suplente entró en el descanso.',
      ornekTr: 'Yedek oyuncu devrede oyuna girdi.',
      not: '"suplir" yerini doldurmak demektir.',
    },
    {
      id: 'es-fut-18', on: 'la plantilla', okunus: 'la plantiya', tur: 'isim (dişil)',
      arka: 'kadro',
      ornek: 'La plantilla tiene veinticinco jugadores.',
      ornekTr: 'Kadroda yirmi beş oyuncu var.',
      not: 'Şirket çalışanları için de kullanılır.',
    },
    {
      id: 'es-fut-19', on: 'la alineación', okunus: 'la alineasyon', tur: 'isim (dişil)',
      arka: 'ilk on bir',
      ornek: 'El entrenador anunció la alineación.',
      ornekTr: 'Antrenör ilk on biri açıkladı.',
      not: '"alinear" sıraya dizmek demektir.',
    },
    {
      id: 'es-fut-20', on: 'la camiseta', okunus: 'la kamiseta', tur: 'isim (dişil)',
      arka: 'forma',
      ornek: 'Lleva la camiseta número diez.',
      ornekTr: 'On numaralı formayı giyiyor.',
      not: '"la camisa" gömlek demektir; "-eta" küçültme ekidir.',
    },
    /* --- Maçın içi --- */
    {
      id: 'es-fut-21', on: 'el saque inicial', okunus: 'el sake inisyal', tur: 'isim (eril)',
      arka: 'başlama vuruşu',
      ornek: 'El saque inicial es a las ocho.',
      ornekTr: 'Başlama vuruşu saat sekizde.',
      not: '"sacar" çıkarmak, vuruş yapmak demektir.',
    },
    {
      id: 'es-fut-22', on: 'el descanso', okunus: 'el deskanso', tur: 'isim (eril)',
      arka: 'devre arası',
      ornek: 'En el descanso iban empatados.',
      ornekTr: 'Devre arasında berabereydiler.',
      not: '"descansar" dinlenmek demektir.',
    },
    {
      id: 'es-fut-23', on: 'el penalti', okunus: 'el penalti', tur: 'isim (eril)',
      arka: 'penaltı',
      ornek: 'El árbitro señaló un penalti.',
      ornekTr: 'Hakem penaltı verdi.',
      not: '"señalar" işaret etmek demektir.',
    },
    {
      id: 'es-fut-24', on: 'el tiro libre', okunus: 'el tiro libre', tur: 'isim (eril)',
      arka: 'serbest vuruş, frikik',
      ornek: 'Marcó de tiro libre.',
      ornekTr: 'Frikikten gol attı.',
      not: 'Edatı "de"dir: marcar de tiro libre.',
    },
    {
      id: 'es-fut-25', on: 'el córner', okunus: 'el korner', tur: 'isim (eril)',
      arka: 'korner',
      ornek: 'Sacaron seis córners en la primera parte.',
      ornekTr: 'İlk yarıda altı korner kullandılar.',
      not: '"el saque de esquina" da denir.',
    },
    {
      id: 'es-fut-26', on: 'el fuera de juego', okunus: 'el fuera de huego', tur: 'isim (eril)',
      arka: 'ofsayt',
      ornek: 'Anularon el gol por fuera de juego.',
      ornekTr: 'Golü ofsayt nedeniyle iptal ettiler.',
      not: '"anular" iptal etmek demektir.',
    },
    {
      id: 'es-fut-27', on: 'la falta', okunus: 'la falta', tur: 'isim (dişil)',
      arka: 'faul; eksiklik',
      ornek: 'Fue una falta clara.',
      ornekTr: 'Açık bir fauldü.',
      not: '"hacer falta" ise "gerekmek" demektir; farklı anlamdır.',
    },
    {
      id: 'es-fut-28', on: 'la tarjeta amarilla', okunus: 'la tarheta amariya', tur: 'isim (dişil)',
      arka: 'sarı kart',
      ornek: 'Recibió una tarjeta amarilla.',
      ornekTr: 'Sarı kart gördü.',
      not: 'Kırmızı kart "la tarjeta roja"dır.',
    },
    {
      id: 'es-fut-29', on: 'la prórroga', okunus: 'la prorroga', tur: 'isim (dişil)',
      arka: 'uzatma',
      ornek: 'El partido se fue a la prórroga.',
      ornekTr: 'Maç uzatmalara gitti.',
      not: '"prorrogar" uzatmak demektir.',
    },
    {
      id: 'es-fut-30', on: 'el gol en propia puerta', okunus: 'el gol en propya puerta', tur: 'isim (eril)',
      arka: 'kendi kalesine gol',
      ornek: 'Marcó un gol en propia puerta.',
      ornekTr: 'Kendi kalesine gol attı.',
      not: '"propia" kendi, "puerta" kapı demektir.',
    },
    /* --- Oyun fiilleri --- */
    {
      id: 'es-fut-31', on: 'chutar', okunus: 'çutar', tur: 'fiil',
      arka: 'şut atmak',
      ornek: 'Chuta desde veinte metros.',
      ornekTr: 'Yirmi metreden şut atıyor.',
      not: 'İngilizce "shoot" kelimesinden gelir.',
    },
    {
      id: 'es-fut-32', on: 'pasar el balón', okunus: 'pasar el balon', tur: 'kalıp',
      arka: 'topu paslamak',
      ornek: 'Pasa el balón a la izquierda.',
      ornekTr: 'Topu sola paslıyor.',
      not: '"el balón" büyük top, "la pelota" küçük toptur.',
    },
    {
      id: 'es-fut-33', on: 'parar', okunus: 'parar', tur: 'fiil',
      arka: 'durdurmak, kurtarmak',
      ornek: 'El portero para el tiro con una mano.',
      ornekTr: 'Kaleci şutu tek eliyle kurtarıyor.',
      not: 'Kurtarış "la parada"dır.',
    },
    {
      id: 'es-fut-34', on: 'regatear', okunus: 'regatear', tur: 'fiil',
      arka: 'çalım atmak',
      ornek: 'Regatea a dos defensas.',
      ornekTr: 'İki defans oyuncusunu çalımlıyor.',
      not: '"el regate" çalım demektir.',
    },
    {
      id: 'es-fut-35', on: 'empatar', okunus: 'empatar', tur: 'fiil',
      arka: 'berabere kalmak',
      ornek: 'Empatamos a uno.',
      ornekTr: 'Birer bir berabere kaldık.',
      not: '"el empate" beraberlik demektir.',
    },
    {
      id: 'es-fut-36', on: 'la victoria', okunus: 'la viktorya', tur: 'isim (dişil)',
      arka: 'galibiyet',
      ornek: 'La victoria fue importante para nosotros.',
      ornekTr: 'Galibiyet bizim için önemliydi.',
      not: 'Karşıtı "la derrota" = yenilgi.',
    },
    {
      id: 'es-fut-37', on: 'la derrota', okunus: 'la derrota', tur: 'isim (dişil)',
      arka: 'yenilgi',
      ornek: 'Tras la derrota, todos estaban tristes.',
      ornekTr: 'Yenilgiden sonra herkes üzgündü.',
      not: '"tras" sonra demektir; "después de" ile aynıdır.',
    },
    {
      id: 'es-fut-38', on: 'el resultado', okunus: 'el resultado', tur: 'isim (eril)',
      arka: 'sonuç, skor',
      ornek: 'El resultado final fue dos a cero.',
      ornekTr: 'Nihai skor iki sıfırdı.',
      not: 'Sınav sonucu için de aynı kelime kullanılır.',
    },
    {
      id: 'es-fut-39', on: 'el campo', okunus: 'el kampo', tur: 'isim (eril)',
      arka: 'saha',
      ornek: 'Los jugadores salen al campo.',
      ornekTr: 'Oyuncular sahaya çıkıyor.',
      not: 'Aynı kelime "kır, tarla" anlamına da gelir.',
    },
    {
      id: 'es-fut-40', on: 'el punto', okunus: 'el punto', tur: 'isim (eril)',
      arka: 'puan',
      ornek: 'Necesitamos tres puntos más.',
      ornekTr: 'Üç puana daha ihtiyacımız var.',
      not: 'Aynı kelime "nokta" anlamına da gelir.',
    },
    /* --- Lig ve turnuva --- */
    {
      id: 'es-fut-41', on: 'la liga', okunus: 'la liga', tur: 'isim (dişil)',
      arka: 'lig',
      ornek: 'La liga empieza en agosto.',
      ornekTr: 'Lig ağustosta başlıyor.',
      not: 'İspanya\'nın birinci ligi "LaLiga" olarak anılır.',
    },
    {
      id: 'es-fut-42', on: 'la clasificación', okunus: 'la klasifikasyon', tur: 'isim (dişil)',
      arka: 'puan tablosu',
      ornek: 'Estamos terceros en la clasificación.',
      ornekTr: 'Puan tablosunda üçüncüyüz.',
      not: '"clasificar" sınıflandırmak, sıralamak demektir.',
    },
    {
      id: 'es-fut-43', on: 'el título', okunus: 'el titulo', tur: 'isim (eril)',
      arka: 'şampiyonluk; başlık',
      ornek: 'Ganaron el título por primera vez.',
      ornekTr: 'Şampiyonluğu ilk kez kazandılar.',
      not: '"por primera vez" = ilk kez.',
    },
    {
      id: 'es-fut-44', on: 'el descenso', okunus: 'el desenso', tur: 'isim (eril)',
      arka: 'küme düşme',
      ornek: 'El equipo evitó el descenso.',
      ornekTr: 'Takım küme düşmekten kurtuldu.',
      not: '"descender" inmek; çıkış "el ascenso"dur.',
    },
    {
      id: 'es-fut-45', on: 'el derbi', okunus: 'el derbi', tur: 'isim (eril)',
      arka: 'derbi',
      ornek: 'El derbi siempre está agotado.',
      ornekTr: 'Derbinin biletleri hep tükeniyor.',
      not: '"agotado" tükenmiş demektir.',
    },
    {
      id: 'es-fut-46', on: 'la copa', okunus: 'la kopa', tur: 'isim (dişil)',
      arka: 'kupa',
      ornek: 'Levantaron la copa ante su afición.',
      ornekTr: 'Kupayı taraftarlarının önünde kaldırdılar.',
      not: '"levantar" kaldırmak demektir. Aynı kelime "bardak" anlamına da gelir.',
    },
    {
      id: 'es-fut-47', on: 'la final', okunus: 'la final', tur: 'isim (dişil)',
      arka: 'final',
      ornek: 'La final se juega en Madrid.',
      ornekTr: 'Final Madrid\'de oynanıyor.',
      not: 'Dişildir: "la final". "El final" ise "son" demektir.',
    },
    {
      id: 'es-fut-48', on: 'el torneo', okunus: 'el torneo', tur: 'isim (eril)',
      arka: 'turnuva',
      ornek: 'Nuestro instituto organiza un torneo.',
      ornekTr: 'Lisemiz bir turnuva düzenliyor.',
      not: 'Satranç ve tenis için de kullanılır.',
    },
    {
      id: 'es-fut-49', on: 'el Mundial', okunus: 'el mundyal', tur: 'isim (eril)',
      arka: 'Dünya Kupası',
      ornek: 'El Mundial se celebra cada cuatro años.',
      ornekTr: 'Dünya Kupası dört yılda bir düzenleniyor.',
      not: '"celebrarse" düzenlenmek demektir.',
    },
    {
      id: 'es-fut-50', on: 'el hat-trick', okunus: 'el hat trik', tur: 'isim (eril)',
      arka: 'bir maçta üç gol',
      ornek: 'Marcó un hat-trick contra su exequipo.',
      ornekTr: 'Eski takımına karşı üç gol attı.',
      not: 'İspanyolcada "un triplete" de denir.',
    },
    /* --- Taraftar ve stat --- */
    {
      id: 'es-fut-51', on: 'el estadio', okunus: 'el estadyo', tur: 'isim (eril)',
      arka: 'stat',
      ornek: 'El estadio estaba lleno.',
      ornekTr: 'Stat doluydu.',
      not: '"lleno" dolu demektir.',
    },
    {
      id: 'es-fut-52', on: 'la grada', okunus: 'la grada', tur: 'isim (dişil)',
      arka: 'tribün',
      ornek: 'Estábamos en la grada norte.',
      ornekTr: 'Kuzey tribünündeydik.',
      not: 'Çoğul "las gradas" da yaygındır.',
    },
    {
      id: 'es-fut-53', on: 'el ambiente', okunus: 'el ambyente', tur: 'isim (eril)',
      arka: 'atmosfer, ortam',
      ornek: 'El ambiente en el estadio era increíble.',
      ornekTr: 'Stattaki atmosfer inanılmazdı.',
      not: '"el medio ambiente" ise "çevre" demektir.',
    },
    {
      id: 'es-fut-54', on: 'la bufanda', okunus: 'la bufanda', tur: 'isim (dişil)',
      arka: 'atkı',
      ornek: 'Los aficionados levantan sus bufandas.',
      ornekTr: 'Taraftarlar atkılarını kaldırıyor.',
      not: 'Kışlık atkı için de aynı kelime kullanılır.',
    },
    {
      id: 'es-fut-55', on: 'animar', okunus: 'animar', tur: 'fiil',
      arka: 'tezahürat yapmak, desteklemek',
      ornek: 'Fuimos al estadio para animar al equipo.',
      ornekTr: 'Takımı desteklemek için stada gittik.',
      not: 'Aynı fiil "moral vermek" anlamına da gelir.',
    },
    {
      id: 'es-fut-56', on: 'el himno', okunus: 'el imno', tur: 'isim (eril)',
      arka: 'marş',
      ornek: 'Cantaron el himno antes del partido.',
      ornekTr: 'Maçtan önce marşı söylediler.',
      not: 'Baştaki "h" okunmaz.',
    },
    {
      id: 'es-fut-57', on: 'agotado', okunus: 'agotado', tur: 'sıfat',
      arka: 'tükenmiş (bilet); bitkin',
      ornek: 'Las entradas están agotadas.',
      ornekTr: 'Biletler tükendi.',
      not: '"la entrada" bilet demektir. Kişi için "bitkin" anlamına gelir.',
    },
    {
      id: 'es-fut-58', on: 'en casa / fuera', okunus: 'en kasa / fuera', tur: 'kalıp',
      arka: 'iç sahada / deplasmanda',
      ornek: 'Jugamos en casa el sábado.',
      ornekTr: 'Cumartesi iç sahada oynuyoruz.',
      not: '"jugar fuera" deplasmanda oynamak demektir.',
    },
    {
      id: 'es-fut-59', on: 'el socio', okunus: 'el sosyo', tur: 'isim (eril)',
      arka: 'kulüp üyesi',
      ornek: 'Mi tío es socio del club.',
      ornekTr: 'Amcam kulübün üyesi.',
      not: 'İspanya\'da büyük kulüpler üyeleri tarafından yönetilir.',
    },
    {
      id: 'es-fut-60', on: 'el público', okunus: 'el publiko', tur: 'isim (eril)',
      arka: 'seyirci',
      ornek: 'El público aplaudió durante cinco minutos.',
      ornekTr: 'Seyirci beş dakika alkışladı.',
      not: '"aplaudir" alkışlamak demektir.',
    },
    /* --- Diğer sporlar --- */
    {
      id: 'es-fut-61', on: 'el baloncesto', okunus: 'el balonsesto', tur: 'isim (eril)',
      arka: 'basketbol',
      ornek: 'Juego al baloncesto los miércoles.',
      ornekTr: 'Çarşambaları basketbol oynuyorum.',
      not: 'Spor için "jugar a" kalıbı kullanılır: jugar al fútbol.',
    },
    {
      id: 'es-fut-62', on: 'la natación', okunus: 'la natasyon', tur: 'isim (dişil)',
      arka: 'yüzme',
      ornek: 'La natación es buena para la espalda.',
      ornekTr: 'Yüzme sırt için iyidir.',
      not: 'Fiili "nadar"dır.',
    },
    {
      id: 'es-fut-63', on: 'el ciclismo', okunus: 'el siklismo', tur: 'isim (eril)',
      arka: 'bisiklet sporu',
      ornek: 'El ciclismo es muy popular en España.',
      ornekTr: 'Bisiklet sporu İspanya\'da çok popüler.',
      not: 'La Vuelta İspanya\'nın en ünlü bisiklet yarışıdır.',
    },
    {
      id: 'es-fut-64', on: 'el atletismo', okunus: 'el atletismo', tur: 'isim (eril)',
      arka: 'atletizm',
      ornek: 'El atletismo exige mucha resistencia.',
      ornekTr: 'Atletizm çok dayanıklılık ister.',
      not: '"exigir" gerektirmek demektir.',
    },
    {
      id: 'es-fut-65', on: 'la medalla', okunus: 'la medaya', tur: 'isim (dişil)',
      arka: 'madalya',
      ornek: 'Ganó una medalla de oro.',
      ornekTr: 'Altın madalya kazandı.',
      not: 'Altın "oro", gümüş "plata", bronz "bronce"dur.',
    },
    {
      id: 'es-fut-66', on: 'el récord', okunus: 'el rekord', tur: 'isim (eril)',
      arka: 'rekor',
      ornek: 'Batió el récord del instituto.',
      ornekTr: 'Lise rekorunu kırdı.',
      not: '"batir" kırmak demektir.',
    },
    {
      id: 'es-fut-67', on: 'la competición', okunus: 'la kompetisyon', tur: 'isim (dişil)',
      arka: 'yarışma, müsabaka',
      ornek: 'La competición empieza a las diez.',
      ornekTr: 'Müsabaka saat onda başlıyor.',
      not: 'Latin Amerika\'da "la competencia" denir.',
    },
    {
      id: 'es-fut-68', on: 'participar en', okunus: 'partisipar en', tur: 'fiil',
      arka: 'katılmak',
      ornek: 'Cuarenta colegios participan en el torneo.',
      ornekTr: 'Turnuvaya kırk okul katılıyor.',
      not: 'Edatı "en"dir.',
    },
    {
      id: 'es-fut-69', on: 'la marca personal', okunus: 'la marka personal', tur: 'isim (dişil)',
      arka: 'kişisel rekor',
      ornek: 'Mejoró su marca personal.',
      ornekTr: 'Kişisel rekorunu geliştirdi.',
      not: '"mejorar" iyileştirmek demektir.',
    },
    {
      id: 'es-fut-70', on: 'hacer deporte', okunus: 'aser deporte', tur: 'kalıp',
      arka: 'spor yapmak',
      ornek: 'Hay que hacer deporte tres veces por semana.',
      ornekTr: 'Haftada üç kez spor yapmak gerekir.',
      not: '"hay que" = gerekir; kişisiz zorunluluk bildirir.',
    },
    /* --- Antrenman ve beden --- */
    {
      id: 'es-fut-71', on: 'calentar', okunus: 'kalentar', tur: 'fiil',
      arka: 'ısınmak',
      ornek: 'Calentamos diez minutos antes de jugar.',
      ornekTr: 'Oynamadan önce on dakika ısınıyoruz.',
      not: '"el calentamiento" ısınma demektir.',
    },
    {
      id: 'es-fut-72', on: 'estirar', okunus: 'estirar', tur: 'fiil',
      arka: 'esnemek, germe yapmak',
      ornek: 'Hay que estirar después del deporte.',
      ornekTr: 'Spordan sonra germe yapmak gerekir.',
      not: '"los estiramientos" germe hareketleri demektir.',
    },
    {
      id: 'es-fut-73', on: 'la resistencia', okunus: 'la resistensya', tur: 'isim (dişil)',
      arka: 'dayanıklılık',
      ornek: 'Correr mejora la resistencia.',
      ornekTr: 'Koşmak dayanıklılığı artırır.',
      not: '"resistir" direnmek, dayanmak demektir.',
    },
    {
      id: 'es-fut-74', on: 'la lesión', okunus: 'la lesyon', tur: 'isim (dişil)',
      arka: 'sakatlık',
      ornek: 'Por suerte, la lesión no fue grave.',
      ornekTr: 'Neyse ki sakatlık ciddi değildi.',
      not: '"por suerte" = neyse ki.',
    },
    {
      id: 'es-fut-75', on: 'recuperarse', okunus: 'rekuperarse', tur: 'fiil (dönüşlü)',
      arka: 'iyileşmek, toparlanmak',
      ornek: 'Se recupera después del partido.',
      ornekTr: 'Maçtan sonra toparlanıyor.',
      not: 'Dönüşlü zamir zorunludur.',
    },
    {
      id: 'es-fut-76', on: 'estar en forma', okunus: 'estar en forma', tur: 'kalıp',
      arka: 'formda olmak',
      ornek: 'Está en plena forma esta temporada.',
      ornekTr: 'Bu sezon tam formda.',
      not: '"la temporada" sezon demektir.',
    },
    {
      id: 'es-fut-77', on: 'rendirse', okunus: 'rendirse', tur: 'fiil (dönüşlü)',
      arka: 'pes etmek',
      ornek: 'Nunca se rinde.',
      ornekTr: 'Asla pes etmiyor.',
      not: 'Çekimi düzensizdir: me rindo, se rinde.',
      kok: 'rinde',
    },
    {
      id: 'es-fut-78', on: 'superarse', okunus: 'superarse', tur: 'fiil (dönüşlü)',
      arka: 'kendini aşmak',
      ornek: 'Hay que superarse en cada entrenamiento.',
      ornekTr: 'Her antrenmanda kendini aşmak gerekir.',
      not: '"superar" aşmak, geçmek demektir.',
    },
    {
      id: 'es-fut-79', on: 'sudar', okunus: 'sudar', tur: 'fiil',
      arka: 'terlemek',
      ornek: 'Se suda mucho en verano.',
      ornekTr: 'Yazın çok terleniyor.',
      not: '"el sudor" ter demektir.',
    },
    {
      id: 'es-fut-80', on: 'el entrenamiento', okunus: 'el entrenamyento', tur: 'isim (eril)',
      arka: 'antrenman',
      ornek: 'El entrenamiento se canceló hoy.',
      ornekTr: 'Antrenman bugün iptal edildi.',
      not: '"cancelarse" iptal olmak demektir.',
    },
    /* --- Spor deyimleri --- */
    {
      id: 'es-fut-81', on: 'ponerse las pilas', okunus: 'ponerse las pilas', tur: 'deyim',
      arka: 'kendine gelmek, gaza basmak',
      ornek: 'Tienes que ponerte las pilas antes del examen.',
      ornekTr: 'Sınavdan önce gaza basman lazım.',
      not: 'Kelimesi kelimesine "pilleri takmak" demektir.',
    },
    {
      id: 'es-fut-82', on: 'tirar la toalla', okunus: 'tirar la toaya', tur: 'deyim',
      arka: 'havlu atmak, pes etmek',
      ornek: 'Estaba cansado pero no tiró la toalla.',
      ornekTr: 'Yorgundu ama pes etmedi.',
      not: 'Boks kökenlidir; Türkçesiyle birebir aynıdır.',
    },
    {
      id: 'es-fut-83', on: 'estar en racha', okunus: 'estar en raça', tur: 'deyim',
      arka: 'iyi bir seride olmak',
      ornek: 'El equipo está en racha este mes.',
      ornekTr: 'Takım bu ay iyi gidiyor.',
      not: '"la racha" seri, rüzgâr esintisi demektir.',
    },
    {
      id: 'es-fut-84', on: 'ser un crack', okunus: 'ser un krak', tur: 'deyim',
      arka: 'çok yetenekli olmak',
      ornek: 'Ese chico es un crack jugando.',
      ornekTr: 'O çocuk oyunda müthiş.',
      not: 'İspanyolcada övgü olarak çok kullanılır.',
    },
    {
      id: 'es-fut-85', on: 'meter un golazo', okunus: 'meter un golaso', tur: 'kalıp',
      arka: 'muhteşem bir gol atmak',
      ornek: 'Metió un golazo desde fuera del área.',
      ornekTr: 'Ceza sahası dışından muhteşem bir gol attı.',
      not: '"-azo" eki büyütme ve hayranlık katar.',
    },
    {
      id: 'es-fut-86', on: 'la pelota está en tu tejado', okunus: 'la pelota esta en tu tehado', tur: 'deyim',
      arka: 'Top sende, karar senin',
      ornek: 'Yo ya hice mi parte: la pelota está en tu tejado.',
      ornekTr: 'Ben üzerime düşeni yaptım: top sende.',
      not: '"el tejado" çatı demektir.',
    },
    {
      id: 'es-fut-87', on: 'dar lo mejor de uno mismo', okunus: 'dar lo mehor de uno mismo', tur: 'kalıp',
      arka: 'elinden gelenin en iyisini yapmak',
      ornek: 'Solo tienes que dar lo mejor de ti mismo.',
      ornekTr: 'Sadece elinden gelenin en iyisini yapman gerekiyor.',
      not: 'Sınav öncesi cesaret vermek için kullanılır.',
    },
    {
      id: 'es-fut-88', on: 'ir codo con codo', okunus: 'ir kodo kon kodo', tur: 'deyim',
      arka: 'başa baş gitmek',
      ornek: 'Los dos equipos van codo con codo.',
      ornekTr: 'İki takım başa baş gidiyor.',
      not: '"el codo" dirsek demektir.',
    },
    {
      id: 'es-fut-89', on: 'el juego limpio', okunus: 'el huego limpyo', tur: 'isim (eril)',
      arka: 'centilmence oyun',
      ornek: 'El juego limpio importa más que ganar.',
      ornekTr: 'Centilmence oyun kazanmaktan önemlidir.',
      not: '"limpio" temiz demektir.',
    },
    {
      id: 'es-fut-90', on: 'el gafe', okunus: 'el gafe', tur: 'isim (eril)',
      arka: 'uğursuzluk getiren kişi',
      ornek: 'Dicen que soy un gafe cuando veo el partido.',
      ornekTr: 'Maçı izleyince uğursuzluk getirdiğimi söylüyorlar.',
      not: 'Şaka yollu kullanılan çok yaygın bir kelimedir.',
    },
    /* --- Maç konuşmaları --- */
    {
      id: 'es-fut-91', on: '¿Cómo van?', okunus: 'komo van', tur: 'soru kalıbı',
      arka: 'Skor kaç? Nasıl gidiyor?',
      ornek: '¿Cómo van? - Dos a uno.',
      ornekTr: 'Skor kaç? - İki bir.',
      not: 'Skor "a" ile söylenir: dos a uno.',
    },
    {
      id: 'es-fut-92', on: '¿Quién ganó?', okunus: 'kyen gano', tur: 'soru kalıbı',
      arka: 'Kim kazandı?',
      ornek: '¿Quién ganó anoche?',
      ornekTr: 'Dün gece kim kazandı?',
      not: '"anoche" dün gece demektir.',
    },
    {
      id: 'es-fut-93', on: 'Fue muy reñido', okunus: 'fue muy renyido', tur: 'kalıp',
      arka: 'Çok çekişmeliydi',
      ornek: 'El partido fue muy reñido hasta el final.',
      ornekTr: 'Maç sonuna kadar çok çekişmeliydi.',
      not: '"reñir" tartışmak, çekişmek demektir.',
    },
    {
      id: 'es-fut-94', on: '¡Suerte!', okunus: 'suerte', tur: 'kalıp',
      arka: 'Bol şans!',
      ornek: '¡Suerte en el partido!',
      ornekTr: 'Maçta bol şans!',
      not: '"la suerte" şans demektir.',
    },
    {
      id: 'es-fut-95', on: '¡Ganamos!', okunus: 'ganamos', tur: 'kalıp',
      arka: 'Kazandık!',
      ornek: '¡Ganamos tres a uno!',
      ornekTr: 'Üç bir kazandık!',
      not: 'Geniş zaman ve geçmiş zaman biçimi aynıdır; bağlam ayırır.',
    },
    {
      id: 'es-fut-96', on: 'emocionante', okunus: 'emosyonante', tur: 'sıfat',
      arka: 'heyecan verici',
      ornek: 'Fue un partido emocionante.',
      ornekTr: 'Heyecan verici bir maçtı.',
      not: '"la emoción" heyecan, duygu demektir.',
    },
    {
      id: 'es-fut-97', on: 'aburrido', okunus: 'aburrido', tur: 'sıfat',
      arka: 'sıkıcı',
      ornek: 'La primera parte fue aburrida.',
      ornekTr: 'İlk yarı sıkıcıydı.',
      not: '"estar aburrido" canı sıkılmak, "ser aburrido" sıkıcı olmaktır.',
    },
    {
      id: 'es-fut-98', on: 'merecer', okunus: 'mereser', tur: 'fiil',
      arka: 'hak etmek',
      ornek: 'Merecen esta victoria.',
      ornekTr: 'Bu galibiyeti hak ediyorlar.',
      not: '"merecer la pena" = değmek.',
    },
    {
      id: 'es-fut-99', on: 'dominar', okunus: 'dominar', tur: 'fiil',
      arka: 'oyuna hâkim olmak',
      ornek: 'Dominamos la segunda parte.',
      ornekTr: 'İkinci yarıya hâkim olduk.',
      not: 'Aynı fiil "bir dili çok iyi bilmek" anlamına da gelir.',
    },
    {
      id: 'es-fut-100', on: 'la posesión del balón', okunus: 'la posesyon del balon', tur: 'isim (dişil)',
      arka: 'topa sahip olma oranı',
      ornek: 'Tuvieron el sesenta por ciento de posesión del balón.',
      ornekTr: 'Topa sahip olma oranları yüzde altmıştı.',
      not: '"por ciento" = yüzde.',
    },
  ],
}

export default DESTE
