/**
 * DESTE — GÜNLÜK KONUŞMA (İspanyolca)
 *
 * İspanyolca konuşulurken hızlıdır ve kalıplarla ilerler. Öğrenci
 * gramerini bilse bile bu kalıpları bilmezse konuşmayı takip edemez.
 *
 * BÖLGESEL FARK her kartta not edildi: İspanya ile Latin Amerika günlük
 * dilde en çok burada ayrışır.
 */

export const DESTE = {
  id: 'gunluk-konusma',
  dil: 'es',
  ad: 'Günlük konuşma',
  simge: '💬',
  aciklama: 'Kitapların yazmadığı, her gün duyacağın kalıplar.',
  seviye: 'A2',
  kartlar: [
    {
      id: 'es-gun-01', on: '¿Qué tal?', kok: 'tal', okunus: 'ke tal', tur: 'kalıp',
      arka: 'Nasılsın? Naber?',
      ornek: '¡Hola! ¿Qué tal todo?',
      ornekTr: 'Selam! Her şey nasıl?',
      not: '"¿Cómo estás?"tan daha kısa ve daha günlüktür.',
    },
    {
      id: 'es-gun-02', on: 'vale', okunus: 'bale', tur: 'ünlem',
      arka: 'tamam, olur',
      ornek: '— ¿Nos vemos a las seis? — ¡Vale!',
      ornekTr: '— Altıda buluşalım mı? — Tamam!',
      not: 'İSPANYA\'ya özgüdür ve çok sık duyulur. Latin Amerika\'da "bueno" ya da "dale".',
    },
    {
      id: 'es-gun-03', on: 'o sea', okunus: 'o sea', tur: 'kalıp',
      arka: 'yani',
      ornek: 'No puedo ir, o sea, tengo mucho trabajo.',
      ornekTr: 'Gelemem, yani çok işim var.',
      not: 'Konuşmada cümleyi toparlamak için sürekli kullanılır.',
    },
    {
      id: 'es-gun-04', on: 'no pasa nada', kok: 'pasa', okunus: 'no pasa nada', tur: 'kalıp',
      arka: 'sorun değil, önemli değil',
      ornek: '— Perdona, llego tarde. — No pasa nada.',
      ornekTr: '— Kusura bakma, geç kaldım. — Sorun değil.',
      not: 'Çift olumsuzluk burada da doğrudur: "no … nada".',
    },
    {
      id: 'es-gun-05', on: 'ni idea', okunus: 'ni idea', tur: 'kalıp',
      arka: 'hiçbir fikrim yok',
      ornek: '— ¿Dónde está el profesor? — Ni idea.',
      ornekTr: '— Öğretmen nerede? — Hiçbir fikrim yok.',
      not: '"No tengo ni idea"nın kısaltılmış hâlidir.',
    },
    {
      id: 'es-gun-06', on: 'me da igual', kok: 'igual', okunus: 'me da igual', tur: 'kalıp',
      arka: 'benim için fark etmez',
      ornek: '— ¿Pizza o pasta? — Me da igual.',
      ornekTr: '— Pizza mı makarna mı? — Fark etmez.',
      not: '"gustar" gibi ters kurulur: bana eşit geliyor.',
    },
    {
      id: 'es-gun-07', on: 'qué rollo', okunus: 'ke royo', tur: 'kalıp (argo)',
      arka: 'ne sıkıcı, ne saçma',
      ornek: '¡Qué rollo, otra vez examen!',
      ornekTr: 'Ne sıkıcı, yine sınav!',
      not: '"el rollo" rulo demektir; günlük dilde sıkıcı durum anlamına gelir.',
    },
    {
      id: 'es-gun-08', on: 'venga', okunus: 'benga', tur: 'ünlem',
      arka: 'hadi, yapma ya',
      ornek: '¡Venga, vamos que llegamos tarde!',
      ornekTr: 'Hadi, gidelim geç kalıyoruz!',
      not: 'Hem teşvik hem itiraz olabilir; ton belirler. İspanya\'ya özgüdür.',
    },
    {
      id: 'es-gun-09', on: 'la verdad es que', kok: 'verdad', okunus: 'la berdad es ke', tur: 'kalıp',
      arka: 'açıkçası, doğrusu',
      ornek: 'La verdad es que no me gustó el final.',
      ornekTr: 'Açıkçası sonu hoşuma gitmedi.',
      not: 'Fikir belirtirken cümleyi yumuşatır.',
    },
    {
      id: 'es-gun-10', on: 'hasta luego', kok: 'luego', okunus: 'asta luego', tur: 'kalıp',
      arka: 'görüşürüz',
      ornek: 'Me tengo que ir. ¡Hasta luego!',
      ornekTr: 'Gitmem lazım. Görüşürüz!',
      not: 'Ailesi: hasta mañana (yarın), hasta pronto (yakında), hasta ahora (birazdan).',
    },
    /* --- Selamlaşma ve vedalaşma --- */
    {
      id: 'es-gun-11', on: 'Buenos días', okunus: 'buenos diyas', tur: 'kalıp',
      arka: 'Günaydın',
      ornek: 'Buenos días, ¿cómo está usted?',
      ornekTr: 'Günaydın, nasılsınız?',
      not: 'Öğleden sonra "buenas tardes", akşam "buenas noches" denir.',
    },
    {
      id: 'es-gun-12', on: '¿Cómo estás?', okunus: 'komo estas', tur: 'soru kalıbı',
      arka: 'Nasılsın?',
      ornek: '¡Hola! ¿Cómo estás hoy?',
      ornekTr: 'Merhaba! Bugün nasılsın?',
      not: 'Resmî hâli "¿Cómo está usted?"tir.',
    },
    {
      id: 'es-gun-13', on: '¿Qué te cuentas?', okunus: 'ke te kuentas', tur: 'soru kalıbı',
      arka: 'Ne var ne yok?',
      ornek: '¡Hombre! ¿Qué te cuentas?',
      ornekTr: 'Vay! Ne var ne yok?',
      not: '"¡Hombre!" burada şaşkınlık ünlemidir, "adam" demek değildir.',
    },
    {
      id: 'es-gun-14', on: '¡Cuánto tiempo!', okunus: 'kuanto tyempo', tur: 'kalıp',
      arka: 'Görüşmeyeli çok oldu!',
      ornek: '¡Cuánto tiempo sin verte!',
      ornekTr: 'Seni görmeyeli çok oldu!',
      not: '"sin verte" seni görmeden demektir.',
    },
    {
      id: 'es-gun-15', on: 'Hasta mañana', okunus: 'asta manyana', tur: 'kalıp',
      arka: 'Yarın görüşürüz',
      ornek: 'Me voy. ¡Hasta mañana!',
      ornekTr: 'Gidiyorum. Yarın görüşürüz!',
      not: '"hasta" ile veda: hasta pronto, hasta el lunes.',
    },
    {
      id: 'es-gun-16', on: 'Cuídate', okunus: 'kuidate', tur: 'kalıp',
      arka: 'Kendine iyi bak',
      ornek: 'Adiós, ¡cuídate!',
      ornekTr: 'Hoşça kal, kendine iyi bak!',
      not: '"cuidar" bakmak demektir.',
    },
    {
      id: 'es-gun-17', on: 'Saluda a...', okunus: 'saluda a', tur: 'kalıp',
      arka: '... selam söyle',
      ornek: 'Saluda a tu hermano de mi parte.',
      ornekTr: 'Kardeşine benden selam söyle.',
      not: '"de mi parte" benden demektir.',
    },
    {
      id: 'es-gun-18', on: 'Me tengo que ir', okunus: 'me tengo ke ir', tur: 'kalıp',
      arka: 'Gitmem lazım',
      ornek: 'Lo siento, me tengo que ir.',
      ornekTr: 'Kusura bakma, gitmem lazım.',
      not: '"tener que + mastar" zorunluluk bildirir.',
    },
    {
      id: 'es-gun-19', on: 'Nos vemos', okunus: 'nos vemos', tur: 'kalıp',
      arka: 'Görüşürüz',
      ornek: 'Nos vemos el sábado.',
      ornekTr: 'Cumartesi görüşürüz.',
      not: 'Karşılıklı fiil biçimidir: "ver" görmek.',
    },
    {
      id: 'es-gun-20', on: '¡Que te vaya bien!', okunus: 'ke te vaya byen', tur: 'kalıp',
      arka: 'Yolun açık olsun!',
      ornek: 'Mucha suerte, ¡que te vaya bien!',
      ornekTr: 'Bol şans, yolun açık olsun!',
      not: 'Dilek kipi kullanılır: "vaya".',
    },
    /* --- Fikir belirtmek --- */
    {
      id: 'es-gun-21', on: 'Creo que', okunus: 'kreo ke', tur: 'kalıp',
      arka: 'Bence, sanırım',
      ornek: 'Creo que tiene razón.',
      ornekTr: 'Bence haklı.',
      not: '"creer" inanmak, düşünmek demektir.',
    },
    {
      id: 'es-gun-22', on: 'Me parece que', okunus: 'me parese ke', tur: 'kalıp',
      arka: 'Bana öyle geliyor ki',
      ornek: 'Me parece que es demasiado caro.',
      ornekTr: 'Bana çok pahalı geliyor.',
      not: '"parecer" görünmek demektir.',
    },
    {
      id: 'es-gun-23', on: 'Sinceramente', okunus: 'sinseramente', tur: 'zarf',
      arka: 'Açıkçası',
      ornek: 'Sinceramente, no me gustó.',
      ornekTr: 'Açıkçası beğenmedim.',
      not: '"sincero" samimi demektir.',
    },
    {
      id: 'es-gun-24', on: 'Tienes razón', okunus: 'tyenes rason', tur: 'kalıp',
      arka: 'Haklısın',
      ornek: 'Tienes toda la razón.',
      ornekTr: 'Tamamen haklısın.',
      not: '"tener razón" haklı olmak demektir.',
    },
    {
      id: 'es-gun-25', on: 'No estoy de acuerdo', okunus: 'no estoy de akuerdo', tur: 'kalıp',
      arka: 'Katılmıyorum',
      ornek: 'Lo siento, no estoy de acuerdo.',
      ornekTr: 'Kusura bakma, katılmıyorum.',
      not: '"estar de acuerdo" hemfikir olmak demektir.',
    },
    {
      id: 'es-gun-26', on: 'Desde luego', okunus: 'desde luego', tur: 'kalıp',
      arka: 'Elbette, kesinlikle',
      ornek: 'Desde luego, tienes que descansar.',
      ornekTr: 'Elbette dinlenmen gerekiyor.',
      not: 'Güçlü bir onay ifadesidir.',
    },
    {
      id: 'es-gun-27', on: 'por un lado... por otro', okunus: 'por un lado... por otro', tur: 'kalıp',
      arka: 'bir yandan... öte yandan',
      ornek: 'Por un lado es caro, por otro es bueno.',
      ornekTr: 'Bir yandan pahalı, öte yandan iyi.',
      not: '"el lado" taraf demektir.',
    },
    {
      id: 'es-gun-28', on: 'Puede ser', okunus: 'puede ser', tur: 'kalıp',
      arka: 'Olabilir',
      ornek: '¿Va a llover? - Puede ser.',
      ornekTr: 'Yağmur yağacak mı? - Olabilir.',
      not: '"es posible" ile aynı anlamdadır.',
    },
    {
      id: 'es-gun-29', on: 'No estoy seguro', okunus: 'no estoy seguro', tur: 'kalıp',
      arka: 'Emin değilim',
      ornek: 'No estoy seguro de la respuesta.',
      ornekTr: 'Cevaptan emin değilim.',
      not: 'Edatı "de"dir.',
    },
    {
      id: 'es-gun-30', on: 'Lo dudo', okunus: 'lo dudo', tur: 'kalıp',
      arka: 'Sanmıyorum',
      ornek: '¿Va a venir? Lo dudo.',
      ornekTr: 'Gelecek mi? Sanmıyorum.',
      not: '"dudar" şüphe etmek demektir.',
    },
    /* --- Rica ve nezaket --- */
    {
      id: 'es-gun-31', on: '¿Puedes...?', okunus: 'puedes', tur: 'soru kalıbı',
      arka: '... yapabilir misin?',
      ornek: '¿Puedes ayudarme un momento?',
      ornekTr: 'Bir dakika bana yardım edebilir misin?',
      not: 'Resmî hâli "¿Puede usted...?"tir.',
    },
    {
      id: 'es-gun-32', on: '¿Podría...?', okunus: 'podriya', tur: 'soru kalıbı',
      arka: '... yapabilir misiniz? (kibar)',
      ornek: '¿Podría repetirlo, por favor?',
      ornekTr: 'Tekrar eder misiniz lütfen?',
      not: 'Koşul kipi ricayı kibarlaştırır.',
    },
    {
      id: 'es-gun-33', on: '¿Te importa si...?', okunus: 'te importa si', tur: 'soru kalıbı',
      arka: '... yapsam sorun olur mu?',
      ornek: '¿Te importa si abro la ventana?',
      ornekTr: 'Pencereyi açsam sorun olur mu?',
      not: '"importar" önemli olmak, rahatsız etmek demektir.',
    },
    {
      id: 'es-gun-34', on: 'Adelante', okunus: 'adelante', tur: 'kalıp',
      arka: 'Buyur, geç',
      ornek: '¿Puedo pasar? - Adelante.',
      ornekTr: 'Girebilir miyim? - Buyur.',
      not: 'İzin vermenin ve içeri davet etmenin yoludur.',
    },
    {
      id: 'es-gun-35', on: 'Con mucho gusto', okunus: 'kon muço gusto', tur: 'kalıp',
      arka: 'Memnuniyetle',
      ornek: '¿Me ayudas? - Con mucho gusto.',
      ornekTr: 'Yardım eder misin? - Memnuniyetle.',
      not: '"el gusto" zevk demektir.',
    },
    {
      id: 'es-gun-36', on: 'De nada', okunus: 'de nada', tur: 'kalıp',
      arka: 'Rica ederim',
      ornek: '¡Muchas gracias! - De nada.',
      ornekTr: 'Çok teşekkürler! - Rica ederim.',
      not: 'Latin Amerika\'da "por nada" da denir.',
    },
    {
      id: 'es-gun-37', on: 'Perdona', okunus: 'perdona', tur: 'kalıp',
      arka: 'Affedersin, pardon',
      ornek: 'Perdona, ¿tienes un momento?',
      ornekTr: 'Affedersin, bir dakikan var mı?',
      not: 'Resmî hâli "perdone"dir.',
    },
    {
      id: 'es-gun-38', on: 'Lo siento', okunus: 'lo syento', tur: 'kalıp',
      arka: 'Üzgünüm',
      ornek: 'Lo siento mucho, se me olvidó.',
      ornekTr: 'Çok üzgünüm, unutmuşum.',
      not: '"se me olvidó" unuttum demenin doğal yoludur.',
    },
    {
      id: 'es-gun-39', on: 'Siento molestarte', okunus: 'syento molestarte', tur: 'kalıp',
      arka: 'Rahatsız ettiğim için üzgünüm',
      ornek: 'Siento molestarte, tengo una duda.',
      ornekTr: 'Rahatsız ettiğim için üzgünüm, bir sorum var.',
      not: '"la duda" burada soru, tereddüt demektir.',
    },
    {
      id: 'es-gun-40', on: 'No dudes en', okunus: 'no dudes en', tur: 'kalıp',
      arka: 'Çekinme',
      ornek: 'No dudes en preguntar.',
      ornekTr: 'Sormaktan çekinme.',
      not: 'Sonrasında mastar gelir.',
    },
    /* --- Teklif ve plan --- */
    {
      id: 'es-gun-41', on: '¿Te apetece?', okunus: 'te apetese', tur: 'soru kalıbı',
      arka: 'Canın ister mi?',
      ornek: '¿Te apetece un café?',
      ornekTr: 'Kahve ister misin?',
      not: '"apetecer" canı çekmek demektir; İspanya\'da çok yaygındır.',
    },
    {
      id: 'es-gun-42', on: '¿Vamos?', okunus: 'vamos', tur: 'soru kalıbı',
      arka: 'Gidelim mi?',
      ornek: 'Es tarde, ¿vamos?',
      ornekTr: 'Geç oldu, gidelim mi?',
      not: '"¡Vamos!" ünlemi "hadi!" demektir.',
    },
    {
      id: 'es-gun-43', on: '¿Por qué no?', okunus: 'por ke no', tur: 'kalıp',
      arka: 'Neden olmasın?',
      ornek: '¿Un paseo? ¡Por qué no!',
      ornekTr: 'Yürüyüş mü? Neden olmasın!',
      not: 'Teklifi rahat biçimde kabul eder.',
    },
    {
      id: 'es-gun-44', on: 'Me apunto', okunus: 'me apunto', tur: 'kalıp',
      arka: 'Ben varım',
      ornek: '¿Vamos al partido? - ¡Me apunto!',
      ornekTr: 'Maça gidelim mi? - Ben varım!',
      not: '"apuntarse" katılmak, kaydolmak demektir.',
    },
    {
      id: 'es-gun-45', on: 'Quedamos a las...', okunus: 'kedamos a las', tur: 'kalıp',
      arka: '... buluşuyoruz',
      ornek: 'Quedamos a las seis delante del instituto.',
      ornekTr: 'Altıda lisenin önünde buluşuyoruz.',
      not: '"quedar" buluşmak demektir; İspanya\'da çok kullanılır.',
    },
    {
      id: 'es-gun-46', on: 'Otro día', okunus: 'otro diya', tur: 'kalıp',
      arka: 'Başka bir gün',
      ornek: 'Hoy no puedo, otro día.',
      ornekTr: 'Bugün olmaz, başka bir gün.',
      not: 'Kibarca reddetmenin standart yoludur.',
    },
    {
      id: 'es-gun-47', on: 'No puedo', okunus: 'no puedo', tur: 'kalıp',
      arka: 'Yapamam, gelemem',
      ornek: 'No puedo esta noche, tengo examen.',
      ornekTr: 'Bu akşam gelemem, sınavım var.',
      not: 'Gerekçe eklemek nezaket gereğidir.',
    },
    {
      id: 'es-gun-48', on: 'Como quieras', okunus: 'komo kyeras', tur: 'kalıp',
      arka: 'Nasıl istersen',
      ornek: '¿Cine o parque? - Como quieras.',
      ornekTr: 'Sinema mı park mı? - Nasıl istersen.',
      not: 'Dilek kipi kullanılır: "quieras".',
    },
    {
      id: 'es-gun-49', on: 'Trato hecho', okunus: 'trato eço', tur: 'kalıp',
      arka: 'Anlaştık',
      ornek: '¿A las seis? ¡Trato hecho!',
      ornekTr: 'Altıda mı? Anlaştık!',
      not: '"el trato" anlaşma demektir.',
    },
    {
      id: 'es-gun-50', on: 'Te aviso', okunus: 'te aviso', tur: 'kalıp',
      arka: 'Sana haber veririm',
      ornek: 'Te aviso esta tarde.',
      ornekTr: 'Bu öğleden sonra sana haber veririm.',
      not: '"avisar" haber vermek demektir.',
    },
    /* --- Duygular --- */
    {
      id: 'es-gun-51', on: 'Estoy contento', okunus: 'estoy kontento', tur: 'kalıp',
      arka: 'Mutluyum',
      ornek: 'Estoy muy contento de verte.',
      ornekTr: 'Seni gördüğüme çok sevindim.',
      not: 'Sonrasında "de + mastar" gelir.',
    },
    {
      id: 'es-gun-52', on: 'Estoy harto de', okunus: 'estoy arto de', tur: 'kalıp',
      arka: 'Bıktım',
      ornek: 'Estoy harto de este tiempo.',
      ornekTr: 'Bu havadan bıktım.',
      not: 'Edatı "de"dir.',
    },
    {
      id: 'es-gun-53', on: 'Me molesta', okunus: 'me molesta', tur: 'kalıp',
      arka: 'Rahatsız ediyor',
      ornek: 'Me molesta ese ruido.',
      ornekTr: 'O gürültü beni rahatsız ediyor.',
      not: '"gustar" gibi çalışır: özne rahatsız eden şeydir.',
    },
    {
      id: 'es-gun-54', on: 'Estoy decepcionado', okunus: 'estoy desepsyonado', tur: 'kalıp',
      arka: 'Hayal kırıklığına uğradım',
      ornek: 'Estoy decepcionado con el resultado.',
      ornekTr: 'Sonuç beni hayal kırıklığına uğrattı.',
      not: '"la decepción" hayal kırıklığı demektir.',
    },
    {
      id: 'es-gun-55', on: '¡Qué suerte!', okunus: 'ke suerte', tur: 'ünlem',
      arka: 'Ne şans!',
      ornek: '¿Ganaste? ¡Qué suerte!',
      ornekTr: 'Kazandın mı? Ne şans!',
      not: '"¡Qué + isim!" ünlem kalıbıdır.',
    },
    {
      id: 'es-gun-56', on: '¡Qué pena!', okunus: 'ke pena', tur: 'ünlem',
      arka: 'Ne yazık!',
      ornek: '¿No vienes? ¡Qué pena!',
      ornekTr: 'Gelmiyor musun? Ne yazık!',
      not: '"la pena" acı, üzüntü demektir.',
    },
    {
      id: 'es-gun-57', on: 'Menos mal', okunus: 'menos mal', tur: 'kalıp',
      arka: 'Neyse ki',
      ornek: 'Menos mal que no llovió.',
      ornekTr: 'Neyse ki yağmur yağmadı.',
      not: 'Sonrasında "que" gelir.',
    },
    {
      id: 'es-gun-58', on: 'No te preocupes', okunus: 'no te preokupes', tur: 'kalıp',
      arka: 'Merak etme',
      ornek: 'No te preocupes, todo saldrá bien.',
      ornekTr: 'Merak etme, her şey yoluna girecek.',
      not: '"salir bien" iyi sonuçlanmak demektir.',
    },
    {
      id: 'es-gun-59', on: 'Me alegro', okunus: 'me alegro', tur: 'kalıp',
      arka: 'Sevindim',
      ornek: 'Me alegro mucho por ti.',
      ornekTr: 'Senin adına çok sevindim.',
      not: '"alegrarse" sevinmek demektir.',
    },
    {
      id: 'es-gun-60', on: 'Qué rabia', okunus: 'ke rabya', tur: 'ünlem',
      arka: 'Ne sinir!',
      ornek: 'Perdí el autobús, ¡qué rabia!',
      ornekTr: 'Otobüsü kaçırdım, ne sinir!',
      not: '"la rabia" öfke demektir.',
    },
    /* --- Şaşırma ve tepki --- */
    {
      id: 'es-gun-61', on: '¿En serio?', okunus: 'en seryo', tur: 'ünlem',
      arka: 'Ciddi misin?',
      ornek: '¿Te vas mañana? ¿En serio?',
      ornekTr: 'Yarın mı gidiyorsun? Ciddi misin?',
      not: '"serio" ciddi demektir.',
    },
    {
      id: 'es-gun-62', on: '¡No me digas!', okunus: 'no me digas', tur: 'ünlem',
      arka: 'Yok artık! Deme ya!',
      ornek: '¿Ganó? ¡No me digas!',
      ornekTr: 'Kazandı mı? Deme ya!',
      not: 'Şaşkınlığı ifade eder, susturma değildir.',
    },
    {
      id: 'es-gun-63', on: '¡Qué fuerte!', okunus: 'ke fuerte', tur: 'ünlem',
      arka: 'İnanılmaz! Vay be!',
      ornek: '¿Diez goles? ¡Qué fuerte!',
      ornekTr: 'On gol mü? İnanılmaz!',
      not: 'Hem olumlu hem olumsuz şaşkınlık için kullanılır.',
    },
    {
      id: 'es-gun-64', on: '¡Anda ya!', okunus: 'anda ya', tur: 'ünlem',
      arka: 'Hadi canım!',
      ornek: '¿Que no estudiaste? ¡Anda ya!',
      ornekTr: 'Çalışmadın mı? Hadi canım!',
      not: 'İnanmadığını esprili biçimde belirtir.',
    },
    {
      id: 'es-gun-65', on: '¡Enhorabuena!', okunus: 'enorabuena', tur: 'kalıp',
      arka: 'Tebrikler!',
      ornek: '¡Enhorabuena por tu nota!',
      ornekTr: 'Notun için tebrikler!',
      not: 'Latin Amerika\'da "¡Felicidades!" daha yaygındır.',
    },
    {
      id: 'es-gun-66', on: '¿Sabes qué?', okunus: 'sabes ke', tur: 'kalıp',
      arka: 'Bak ne diyeceğim?',
      ornek: '¿Sabes qué? Aprobé el examen.',
      ornekTr: 'Bak ne diyeceğim? Sınavı geçtim.',
      not: 'Haber vermeden önce merak uyandırır.',
    },
    {
      id: 'es-gun-67', on: 'No me lo puedo creer', okunus: 'no me lo puedo kreer', tur: 'kalıp',
      arka: 'İnanamıyorum',
      ornek: '¡No me lo puedo creer, es increíble!',
      ornekTr: 'İnanamıyorum, bu inanılmaz!',
      not: '"increíble" inanılmaz demektir.',
    },
    {
      id: 'es-gun-68', on: 'Tiene sentido', okunus: 'tyene sentido', tur: 'kalıp',
      arka: 'Mantıklı',
      ornek: 'Ahora tiene sentido.',
      ornekTr: 'Şimdi mantıklı geldi.',
      not: '"el sentido" anlam, duyu demektir.',
    },
    {
      id: 'es-gun-69', on: 'Me lo imaginaba', okunus: 'me lo imahinaba', tur: 'kalıp',
      arka: 'Tahmin etmiştim',
      ornek: '¿Llega tarde? Me lo imaginaba.',
      ornekTr: 'Geç mi kalıyor? Tahmin etmiştim.',
      not: '"imaginarse" hayal etmek, tahmin etmek demektir.',
    },
    {
      id: 'es-gun-70', on: '¡Ni de broma!', okunus: 'ni de broma', tur: 'ünlem',
      arka: 'Asla! Şakası bile olmaz!',
      ornek: '¿Saltar desde ahí? ¡Ni de broma!',
      ornekTr: 'Oradan atlamak mı? Asla!',
      not: '"la broma" şaka demektir.',
    },
    /* --- Telefon ve mesaj --- */
    {
      id: 'es-gun-71', on: '¿Diga?', okunus: 'diga', tur: 'kalıp',
      arka: 'Alo? (telefonu açarken)',
      ornek: '¿Diga? ¿Quién es?',
      ornekTr: 'Alo? Kimsiniz?',
      not: 'İspanya\'da "¿Sí?" ya da "¿Dígame?" de denir.',
    },
    {
      id: 'es-gun-72', on: 'No cuelgues', okunus: 'no kuelges', tur: 'kalıp',
      arka: 'Kapatma',
      ornek: 'No cuelgues, sigo aquí.',
      ornekTr: 'Kapatma, buradayım.',
      not: '"colgar" telefonu kapatmak demektir.',
    },
    {
      id: 'es-gun-73', on: 'Te llamo luego', okunus: 'te yamo luego', tur: 'kalıp',
      arka: 'Seni sonra ararım',
      ornek: 'Estoy ocupado, te llamo luego.',
      ornekTr: 'Meşgulüm, seni sonra ararım.',
      not: '"luego" sonra demektir.',
    },
    {
      id: 'es-gun-74', on: 'Se corta', okunus: 'se korta', tur: 'kalıp',
      arka: 'Ses kesiliyor',
      ornek: 'Se corta, te llamo desde fuera.',
      ornekTr: 'Ses kesiliyor, dışarıdan arayacağım.',
      not: '"cortarse" kesilmek demektir.',
    },
    {
      id: 'es-gun-75', on: 'mandar un mensaje', okunus: 'mandar un mensahe', tur: 'kalıp',
      arka: 'mesaj göndermek',
      ornek: 'Mándame un mensaje cuando llegues.',
      ornekTr: 'Varınca bana mesaj gönder.',
      not: 'Zaman yan cümlesinde dilek kipi gelir: "cuando llegues".',
    },
    {
      id: 'es-gun-76', on: 'pasarse por', okunus: 'pasarse por', tur: 'fiil (dönüşlü)',
      arka: 'uğramak',
      ornek: 'Pásate por mi casa esta tarde.',
      ornekTr: 'Bu öğleden sonra bana uğra.',
      not: '"pasar" geçmek demektir. Emir kipi: pásate.',
      kok: 'pásate',
    },
    {
      id: 'es-gun-77', on: 'recoger a alguien', okunus: 'rekoher a algyen', tur: 'kalıp',
      arka: 'birini almaya gitmek',
      ornek: 'Te recojo a las siete.',
      ornekTr: 'Seni yedide alırım.',
      not: '"recoger" toplamak, almak demektir.',
      kok: 'recojo',
    },
    {
      id: 'es-gun-78', on: 'darse prisa', okunus: 'darse prisa', tur: 'kalıp',
      arka: 'acele etmek',
      ornek: '¡Date prisa, llegamos tarde!',
      ornekTr: 'Acele et, geç kalıyoruz!',
      not: '"la prisa" acele demektir.',
    },
    {
      id: 'es-gun-79', on: 'estar localizable', okunus: 'estar lokalisable', tur: 'kalıp',
      arka: 'ulaşılabilir olmak',
      ornek: 'Estaré localizable toda la tarde.',
      ornekTr: 'Bütün öğleden sonra ulaşılabilir olacağım.',
      not: '"localizar" bulmak, ulaşmak demektir.',
    },
    {
      id: 'es-gun-80', on: 'mantener el contacto', okunus: 'mantener el kontakto', tur: 'kalıp',
      arka: 'iletişimi sürdürmek',
      ornek: 'Mantenemos el contacto por mensajes.',
      ornekTr: 'Mesajlarla iletişimi sürdürüyoruz.',
      not: '"mantener" sürdürmek demektir.',
    },
    /* --- Konuşma akışı --- */
    {
      id: 'es-gun-81', on: 'Pues', okunus: 'pues', tur: 'kalıp',
      arka: 'Şey, o zaman',
      ornek: 'Pues no sé qué decir.',
      ornekTr: 'Şey, ne diyeceğimi bilmiyorum.',
      not: 'İspanyolcanın en sık kullanılan bağlantı sözüdür.',
    },
    {
      id: 'es-gun-82', on: 'En realidad', okunus: 'en realidad', tur: 'kalıp',
      arka: 'Aslında',
      ornek: 'En realidad ya lo había leído.',
      ornekTr: 'Aslında onu zaten okumuştum.',
      not: '"la realidad" gerçeklik demektir.',
    },
    {
      id: 'es-gun-83', on: 'Aun así', okunus: 'aun asi', tur: 'kalıp',
      arka: 'Yine de',
      ornek: 'Era caro; aun así lo compré.',
      ornekTr: 'Pahalıydı; yine de aldım.',
      not: '"aún" hâlâ demektir ama bu kalıpta vurgusuzdur.',
    },
    {
      id: 'es-gun-84', on: 'Por cierto', okunus: 'por syerto', tur: 'kalıp',
      arka: 'Bu arada',
      ornek: 'Por cierto, ¿terminaste el libro?',
      ornekTr: 'Bu arada, kitabı bitirdin mi?',
      not: 'Yeni bir konu açarken kullanılır.',
    },
    {
      id: 'es-gun-85', on: 'Total, que', okunus: 'total ke', tur: 'kalıp',
      arka: 'Kısacası',
      ornek: 'Total, que no fuimos.',
      ornekTr: 'Kısacası gitmedik.',
      not: 'Uzun bir anlatımı toparlar.',
    },
    {
      id: 'es-gun-86', on: 'A ver', okunus: 'a ver', tur: 'kalıp',
      arka: 'Bir bakalım, dur bakalım',
      ornek: 'A ver, déjame pensar.',
      ornekTr: 'Dur bakalım, bir düşüneyim.',
      not: 'Konuşmaya zaman kazandıran çok yaygın bir kalıptır.',
    },
    {
      id: 'es-gun-87', on: 'Es que', okunus: 'es ke', tur: 'kalıp',
      arka: 'Şey, çünkü',
      ornek: 'Es que no tengo tiempo.',
      ornekTr: 'Şey, vaktim yok.',
      not: 'Gerekçe sunarken kullanılır ve çok doğaldır.',
    },
    {
      id: 'es-gun-88', on: '¿Cómo se dice?', okunus: 'komo se dise', tur: 'soru kalıbı',
      arka: 'Nasıl deniyor?',
      ornek: '¿Cómo se dice "kalem" en español?',
      ornekTr: 'İspanyolca "kalem" nasıl deniyor?',
      not: 'Dil öğrenirken en işe yarayan sorulardandır.',
    },
    {
      id: 'es-gun-89', on: 'Como decía', okunus: 'komo desiya', tur: 'kalıp',
      arka: 'Dediğim gibi',
      ornek: 'Como decía, necesitamos más tiempo.',
      ornekTr: 'Dediğim gibi, daha fazla zamana ihtiyacımız var.',
      not: 'Sözü kesildikten sonra devam etmek için kullanılır.',
    },
    {
      id: 'es-gun-90', on: 'No te he entendido', okunus: 'no te e entendido', tur: 'kalıp',
      arka: 'Seni anlamadım',
      ornek: 'Perdona, no te he entendido bien.',
      ornekTr: 'Pardon, seni iyi anlamadım.',
      not: 'Ardından "¿Puedes repetir?" denebilir.',
    },
    /* --- Gündelik kalıplar --- */
    {
      id: 'es-gun-91', on: 'tener ganas de', okunus: 'tener ganas de', tur: 'kalıp',
      arka: 'canı istemek',
      ornek: 'Tengo ganas de salir esta noche.',
      ornekTr: 'Bu akşam dışarı çıkmak istiyorum.',
      not: 'Sonrasında mastar gelir.',
    },
    {
      id: 'es-gun-92', on: 'hacer falta', okunus: 'aser falta', tur: 'kalıp',
      arka: 'gerekmek',
      ornek: 'Me hace falta tu ayuda.',
      ornekTr: 'Yardımına ihtiyacım var.',
      not: '"la falta" eksiklik demektir.',
    },
    {
      id: 'es-gun-93', on: 'estar a punto de', okunus: 'estar a punto de', tur: 'kalıp',
      arka: 'tam ... etmek üzere olmak',
      ornek: 'Estaba a punto de llamarte.',
      ornekTr: 'Tam seni arayacaktım.',
      not: 'Çok yakın geleceği anlatır.',
    },
    {
      id: 'es-gun-94', on: 'acabar de', okunus: 'akabar de', tur: 'kalıp',
      arka: 'az önce yapmış olmak',
      ornek: 'Acabo de terminar los deberes.',
      ornekTr: 'Ödevlerimi az önce bitirdim.',
      not: 'Yakın geçmişi anlatan temel kalıptır.',
      kok: 'acabo',
    },
    {
      id: 'es-gun-95', on: 'soler', okunus: 'soler', tur: 'fiil',
      arka: 'genelde yapmak',
      ornek: 'Suelo estudiar por la mañana.',
      ornekTr: 'Genelde sabahları çalışırım.',
      not: 'Sonrasında mastar gelir; çekimi düzensizdir.',
      kok: 'suelo',
    },
    {
      id: 'es-gun-96', on: 'llevar + zaman', okunus: 'yevar', tur: 'kalıp',
      arka: '... zamandır yapıyor olmak',
      ornek: 'Llevo dos años estudiando español.',
      ornekTr: 'İki yıldır İspanyolca çalışıyorum.',
      not: 'Sonrasında ulaç gelir: llevo ... estudiando.',
      kok: 'llevo',
    },
    {
      id: 'es-gun-97', on: 'de vez en cuando', okunus: 'de ves en kuando', tur: 'kalıp',
      arka: 'ara sıra',
      ornek: 'De vez en cuando juego al baloncesto.',
      ornekTr: 'Ara sıra basketbol oynuyorum.',
      not: 'Sıklık sıralaması: siempre, a menudo, a veces, nunca.',
    },
    {
      id: 'es-gun-98', on: 'dar igual', okunus: 'dar igual', tur: 'kalıp',
      arka: 'fark etmemek',
      ornek: 'Me da igual dónde comamos.',
      ornekTr: 'Nerede yediğimiz fark etmez.',
      not: '"igual" eşit, aynı demektir.',
    },
    {
      id: 'es-gun-99', on: 'valer', okunus: 'valer', tur: 'fiil',
      arka: 'tamam olmak; değerinde olmak',
      ornek: '¿A las seis? Vale.',
      ornekTr: 'Altıda mı? Tamam.',
      not: '"Vale" İspanya\'nın en çok kullanılan onay sözcüğüdür.',
      kok: 'vale',
    },
    {
      id: 'es-gun-100', on: 'poco a poco', okunus: 'poko a poko', tur: 'kalıp',
      arka: 'yavaş yavaş',
      ornek: 'Poco a poco entiendo mejor el español.',
      ornekTr: 'Yavaş yavaş İspanyolcayı daha iyi anlıyorum.',
      not: 'Dil öğrenme sürecini anlatmanın en güzel yoludur.',
    },
  ],
}

export default DESTE
