/**
 * DESTE — HAYVANLAR VE DOĞA (İspanyolca)
 *
 * Görsel olarak en kolay hatırlanan deste. İspanyolcada hayvan adları
 * çoğu zaman eril ve dişil biçimlidir (gato/gata); kartlarda bu ikilik
 * gösterildi.
 */

export const DESTE = {
  id: 'hayvanlar-doga',
  dil: 'es',
  ad: 'Hayvanlar ve doğa',
  simge: '🌿',
  aciklama: 'Hayvanlar, hava ve doğa; deyimleriyle birlikte.',
  seviye: 'A1–A2',
  kartlar: [
    {
      id: 'es-hay-01', on: 'el gato', okunus: 'el gato', tur: 'isim (eril)',
      arka: 'kedi',
      ornek: 'Mi gato duerme todo el día en el sofá.',
      ornekTr: 'Kedim bütün gün kanepede uyuyor.',
      not: 'Dişisi "la gata". Hayvan adlarının çoğu bu ikiliği taşır.',
    },
    {
      id: 'es-hay-02', on: 'el perro', okunus: 'el pero', tur: 'isim (eril)',
      arka: 'köpek',
      ornek: 'Saco a mi perro todas las mañanas.',
      ornekTr: 'Köpeğimi her sabah gezdiriyorum.',
      not: 'ÇİFT "rr" titrektir: "perro" (köpek) ≠ "pero" (ama). Fark anlamı değiştirir.',
    },
    {
      id: 'es-hay-03', on: 'el pájaro', okunus: 'el paharo', tur: 'isim (eril)',
      arka: 'kuş',
      ornek: 'Hay un pájaro en la ventana.',
      ornekTr: 'Pencerede bir kuş var.',
      not: 'Aksan zorunludur; vurgu sondan üçüncü hecededir.',
    },
    {
      id: 'es-hay-04', on: 'el árbol', okunus: 'el arbol', tur: 'isim (eril)',
      arka: 'ağaç',
      ornek: 'Hemos plantado un árbol en el jardín.',
      ornekTr: 'Bahçeye bir ağaç diktik.',
      not: 'Çoğulu "los árboles". Orman "el bosque".',
    },
    {
      id: 'es-hay-05', on: 'el mar', okunus: 'el mar', tur: 'isim (eril)',
      arka: 'deniz',
      ornek: 'En verano vamos al mar con mi familia.',
      ornekTr: 'Yazın ailemle denize gidiyoruz.',
      not: 'Şiirde ve denizcilikte dişil de olabilir ("la mar"); günlük dilde erildir.',
    },
    {
      id: 'es-hay-06', on: 'la montaña', okunus: 'la montanya', tur: 'isim (dişil)',
      arka: 'dağ',
      ornek: 'En invierno vamos a la montaña a esquiar.',
      ornekTr: 'Kışın kayak için dağa gidiyoruz.',
      not: '"ñ" harfi Türkçedeki "ny" gibi okunur.',
    },
    {
      id: 'es-hay-07', on: 'llueve', okunus: 'yuebe', tur: 'fiil (kişisiz)',
      arka: 'yağmur yağıyor',
      ornek: 'Coge el paraguas, llueve mucho.',
      ornekTr: 'Şemsiyeyi al, çok yağmur yağıyor.',
      not: 'Kişisi yoktur, tek biçimde kullanılır. Kar için "nieva".',
    },
    {
      id: 'es-hay-08', on: 'hace sol', kok: 'sol', okunus: 'ase sol', tur: 'kalıp',
      arka: 'güneşli',
      ornek: 'Hoy hace sol y no hace nada de frío.',
      ornekTr: 'Bugün güneşli ve hiç soğuk değil.',
      not: 'Hava durumu "hacer" ile kurulur: hace sol, hace frío, hace calor.',
    },
    {
      id: 'es-hay-09', on: 'la flor', okunus: 'la flor', tur: 'isim (dişil)',
      arka: 'çiçek',
      ornek: 'Me regaló flores por mi cumpleaños.',
      ornekTr: 'Doğum günümde bana çiçek hediye etti.',
      not: 'Çoğulu "las flores". Doğum günü "el cumpleaños".',
    },
    {
      id: 'es-hay-10', on: 'ser un gallina', kok: 'gallina', okunus: 'ser un gayina', tur: 'deyim',
      arka: 'korkak olmak',
      ornek: 'No seas gallina, ¡sube!',
      ornekTr: 'Korkak olma, çık yukarı!',
      not: 'Kelime kelime "tavuk olmak" demektir. Türkçedeki "tavşan yürekli" ile aynı mantık.',
    },
    /* --- Evcil hayvanlar --- */
    {
      id: 'es-hay-11', on: 'la mascota', okunus: 'la maskota', tur: 'isim (dişil)',
      arka: 'evcil hayvan',
      ornek: '¿Tienes alguna mascota en casa?',
      ornekTr: 'Evde evcil hayvanın var mı?',
      not: 'Takım maskotu için de aynı kelime kullanılır.',
    },
    {
      id: 'es-hay-12', on: 'el conejo', okunus: 'el koneho', tur: 'isim (eril)',
      arka: 'tavşan',
      ornek: 'A mi conejo le encantan las zanahorias.',
      ornekTr: 'Tavşanım havuca bayılıyor.',
      not: '"la zanahoria" havuç demektir.',
    },
    {
      id: 'es-hay-13', on: 'dar de comer', okunus: 'dar de komer', tur: 'kalıp',
      arka: 'yem vermek, beslemek',
      ornek: 'Doy de comer a los pájaros cada mañana.',
      ornekTr: 'Kuşlara her sabah yem veriyorum.',
      not: 'Kelimesi kelimesine "yemek vermek" demektir.',
    },
    {
      id: 'es-hay-14', on: 'acariciar', okunus: 'akarisyar', tur: 'fiil',
      arka: 'okşamak, sevmek',
      ornek: 'Al gato le gusta que lo acaricien.',
      ornekTr: 'Kedi sevilmeyi seviyor.',
      not: '"la caricia" okşama demektir.',
    },
    {
      id: 'es-hay-15', on: 'el veterinario', okunus: 'el veterinaryo', tur: 'isim (eril)',
      arka: 'veteriner',
      ornek: 'Llevamos al gato al veterinario.',
      ornekTr: 'Kediyi veterinere götürüyoruz.',
      not: '"llevar" götürmek demektir.',
    },
    {
      id: 'es-hay-16', on: 'la protectora', okunus: 'la protektora', tur: 'isim (dişil)',
      arka: 'hayvan barınağı',
      ornek: 'Adoptamos al perro en la protectora.',
      ornekTr: 'Köpeği barınaktan sahiplendik.',
      not: '"proteger" korumak demektir.',
    },
    {
      id: 'es-hay-17', on: 'ladrar', okunus: 'ladrar', tur: 'fiil',
      arka: 'havlamak',
      ornek: 'El perro ladra toda la noche.',
      ornekTr: 'Köpek bütün gece havlıyor.',
      not: 'Kedi "maullar", kuş "cantar" der.',
    },
    {
      id: 'es-hay-18', on: 'la cola', okunus: 'la kola', tur: 'isim (dişil)',
      arka: 'kuyruk; sıra',
      ornek: 'El perro mueve la cola.',
      ornekTr: 'Köpek kuyruğunu sallıyor.',
      not: '"hacer cola" sıraya girmek demektir.',
    },
    {
      id: 'es-hay-19', on: 'fiel', okunus: 'fyel', tur: 'sıfat',
      arka: 'sadık',
      ornek: 'Los perros son animales muy fieles.',
      ornekTr: 'Köpekler çok sadık hayvanlardır.',
      not: '"la fidelidad" sadakat demektir.',
    },
    {
      id: 'es-hay-20', on: 'pasear al perro', okunus: 'pasear al perro', tur: 'kalıp',
      arka: 'köpeği gezdirmek',
      ornek: 'Paseo al perro después del instituto.',
      ornekTr: 'Liseden sonra köpeği gezdiriyorum.',
      not: '"sacar al perro" da denir.',
    },
    /* --- Çiftlik ve yaban hayvanları --- */
    {
      id: 'es-hay-21', on: 'el caballo', okunus: 'el kabayo', tur: 'isim (eril)',
      arka: 'at',
      ornek: 'Monta a caballo los fines de semana.',
      ornekTr: 'Hafta sonları ata biniyor.',
      not: '"montar a caballo" ata binmek demektir.',
    },
    {
      id: 'es-hay-22', on: 'la vaca', okunus: 'la vaka', tur: 'isim (dişil)',
      arka: 'inek',
      ornek: 'Las vacas están en el prado.',
      ornekTr: 'İnekler çayırda.',
      not: 'Boğa güreşindeki boğa "el toro"dur.',
    },
    {
      id: 'es-hay-23', on: 'la oveja', okunus: 'la oveha', tur: 'isim (dişil)',
      arka: 'koyun',
      ornek: 'Hay muchas ovejas en la colina.',
      ornekTr: 'Tepede çok koyun var.',
      not: '"la colina" tepe demektir.',
    },
    {
      id: 'es-hay-24', on: 'la gallina', okunus: 'la gayina', tur: 'isim (dişil)',
      arka: 'tavuk',
      ornek: 'Las gallinas ponen huevos cada día.',
      ornekTr: 'Tavuklar her gün yumurtluyor.',
      not: '"poner huevos" yumurtlamak demektir.',
    },
    {
      id: 'es-hay-25', on: 'el oso', okunus: 'el oso', tur: 'isim (eril)',
      arka: 'ayı',
      ornek: 'Los osos hibernan en invierno.',
      ornekTr: 'Ayılar kışın uykuya yatar.',
      not: '"hibernar" kış uykusuna yatmak demektir.',
    },
    {
      id: 'es-hay-26', on: 'el zorro', okunus: 'el sorro', tur: 'isim (eril)',
      arka: 'tilki',
      ornek: 'Un zorro cruzó la carretera.',
      ornekTr: 'Bir tilki yoldan geçti.',
      not: 'Kurnaz kişiye de "un zorro" denir.',
    },
    {
      id: 'es-hay-27', on: 'la ardilla', okunus: 'la ardiya', tur: 'isim (dişil)',
      arka: 'sincap',
      ornek: 'En este parque viven muchas ardillas.',
      ornekTr: 'Bu parkta çok sincap yaşıyor.',
      not: 'Çevik kişiye "ágil como una ardilla" denir.',
    },
    {
      id: 'es-hay-28', on: 'la mariposa', okunus: 'la mariposa', tur: 'isim (dişil)',
      arka: 'kelebek',
      ornek: 'En primavera hay muchas mariposas.',
      ornekTr: 'İlkbaharda çok kelebek olur.',
      not: 'Yüzmede kelebek stili için de kullanılır.',
    },
    {
      id: 'es-hay-29', on: 'la abeja', okunus: 'la abeha', tur: 'isim (dişil)',
      arka: 'arı',
      ornek: 'Las abejas son esenciales para la naturaleza.',
      ornekTr: 'Arılar doğa için çok önemlidir.',
      not: 'Bal "la miel"dir.',
    },
    {
      id: 'es-hay-30', on: 'la especie', okunus: 'la espesye', tur: 'isim (dişil)',
      arka: 'tür',
      ornek: 'Esta especie vive solo en Turquía.',
      ornekTr: 'Bu tür sadece Türkiye\'de yaşar.',
      not: 'Biyoloji metinlerinin anahtar kelimesidir.',
    },
    /* --- Doğal alanlar --- */
    {
      id: 'es-hay-31', on: 'el bosque', okunus: 'el boske', tur: 'isim (eril)',
      arka: 'orman',
      ornek: 'Paseamos a menudo por el bosque.',
      ornekTr: 'Sık sık ormanda yürüyoruz.',
      not: '"a menudo" sık sık demektir.',
    },
    {
      id: 'es-hay-32', on: 'el prado', okunus: 'el prado', tur: 'isim (eril)',
      arka: 'çayır',
      ornek: 'El prado está lleno de flores.',
      ornekTr: 'Çayır çiçeklerle dolu.',
      not: 'Madrid\'in ünlü müzesi Prado adını buradan alır.',
    },
    {
      id: 'es-hay-33', on: 'el río', okunus: 'el riyo', tur: 'isim (eril)',
      arka: 'nehir',
      ornek: 'Un río cruza el pueblo.',
      ornekTr: 'Bir nehir köyün içinden geçiyor.',
      not: '"el pueblo" köy, kasaba demektir.',
    },
    {
      id: 'es-hay-34', on: 'el lago', okunus: 'el lago', tur: 'isim (eril)',
      arka: 'göl',
      ornek: 'Nos bañamos en el lago en verano.',
      ornekTr: 'Yazın gölde yüzüyoruz.',
      not: '"bañarse" yüzmek, banyo yapmak demektir.',
    },
    {
      id: 'es-hay-35', on: 'el valle', okunus: 'el vaye', tur: 'isim (eril)',
      arka: 'vadi',
      ornek: 'El pueblo está en un valle verde.',
      ornekTr: 'Köy yeşil bir vadide.',
      not: 'Coğrafya dersindeki vadi ile aynı kavramdır.',
    },
    {
      id: 'es-hay-36', on: 'la isla', okunus: 'la isla', tur: 'isim (dişil)',
      arka: 'ada',
      ornek: 'A la isla solo se llega en barco.',
      ornekTr: 'Adaya sadece tekneyle ulaşılıyor.',
      not: '"el barco" gemi, tekne demektir.',
    },
    {
      id: 'es-hay-37', on: 'la cueva', okunus: 'la kueva', tur: 'isim (dişil)',
      arka: 'mağara',
      ornek: 'La cueva está abierta a los visitantes.',
      ornekTr: 'Mağara ziyaretçilere açık.',
      not: 'Altamira İspanya\'nın en ünlü mağarasıdır.',
    },
    {
      id: 'es-hay-38', on: 'la cima', okunus: 'la sima', tur: 'isim (dişil)',
      arka: 'zirve',
      ornek: 'Llegamos a la cima al amanecer.',
      ornekTr: 'Zirveye şafakta ulaştık.',
      not: '"el amanecer" şafak demektir.',
    },
    {
      id: 'es-hay-39', on: 'el sendero', okunus: 'el sendero', tur: 'isim (eril)',
      arka: 'patika',
      ornek: 'Seguimos un sendero de montaña.',
      ornekTr: 'Bir dağ patikasını takip ettik.',
      not: '"el senderismo" doğa yürüyüşü demektir.',
      kok: 'sendero',
    },
    {
      id: 'es-hay-40', on: 'la costa', okunus: 'la kosta', tur: 'isim (dişil)',
      arka: 'kıyı',
      ornek: 'La costa mediterránea es preciosa.',
      ornekTr: 'Akdeniz kıyısı çok güzel.',
      not: 'İspanya\'nın turizm bölgeleri "costa" ile anılır.',
    },
    /* --- Bitkiler --- */
    {
      id: 'es-hay-41', on: 'la planta', okunus: 'la planta', tur: 'isim (dişil)',
      arka: 'bitki',
      ornek: 'Esta planta necesita más luz.',
      ornekTr: 'Bu bitkinin daha çok ışığa ihtiyacı var.',
      not: 'Aynı kelime binanın "katı" anlamına da gelir.',
    },
    {
      id: 'es-hay-42', on: 'la hoja', okunus: 'la oha', tur: 'isim (dişil)',
      arka: 'yaprak',
      ornek: 'En otoño caen las hojas.',
      ornekTr: 'Sonbaharda yapraklar dökülür.',
      not: 'Kâğıt yaprağı için de aynı kelime kullanılır.',
    },
    {
      id: 'es-hay-43', on: 'la raíz', okunus: 'la rais', tur: 'isim (dişil)',
      arka: 'kök',
      ornek: 'Las raíces llegan muy hondo.',
      ornekTr: 'Kökler çok derine iniyor.',
      not: 'Çoğulu "las raíces"tir.',
      kok: 'raíces',
    },
    {
      id: 'es-hay-44', on: 'la semilla', okunus: 'la semiya', tur: 'isim (dişil)',
      arka: 'tohum',
      ornek: 'Plantamos semillas en el huerto.',
      ornekTr: 'Bahçeye tohum ektik.',
      not: '"el huerto" sebze bahçesi demektir.',
    },
    {
      id: 'es-hay-45', on: 'la tierra', okunus: 'la tyerra', tur: 'isim (dişil)',
      arka: 'toprak; dünya',
      ornek: 'La tierra de aquí es muy fértil.',
      ornekTr: 'Buradaki toprak çok verimli.',
      not: 'Büyük harfle "la Tierra" gezegenimiz demektir.',
    },
    {
      id: 'es-hay-46', on: 'regar', okunus: 'regar', tur: 'fiil',
      arka: 'sulamak',
      ornek: 'No olvides regar las plantas.',
      ornekTr: 'Bitkileri sulamayı unutma.',
      not: '"el riego" sulama demektir.',
    },
    {
      id: 'es-hay-47', on: 'crecer', okunus: 'kreser', tur: 'fiil',
      arka: 'büyümek',
      ornek: 'El árbol crece muy despacio.',
      ornekTr: 'Ağaç çok yavaş büyüyor.',
      not: '"despacio" yavaş demektir.',
    },
    {
      id: 'es-hay-48', on: 'florecer', okunus: 'floreser', tur: 'fiil',
      arka: 'çiçek açmak',
      ornek: 'Los cerezos florecen en abril.',
      ornekTr: 'Kiraz ağaçları nisanda çiçek açar.',
      not: '"el cerezo" kiraz ağacı demektir.',
    },
    {
      id: 'es-hay-49', on: 'la cosecha', okunus: 'la koseça', tur: 'isim (dişil)',
      arka: 'hasat',
      ornek: 'La cosecha fue buena este año.',
      ornekTr: 'Bu yıl hasat iyiydi.',
      not: '"cosechar" hasat etmek demektir.',
    },
    {
      id: 'es-hay-50', on: 'el olivo', okunus: 'el olivo', tur: 'isim (eril)',
      arka: 'zeytin ağacı',
      ornek: 'En Andalucía hay millones de olivos.',
      ornekTr: 'Endülüs\'te milyonlarca zeytin ağacı var.',
      not: 'Zeytin "la aceituna", zeytinyağı "el aceite de oliva"dır.',
    },
    /* --- Mevsimler ve hava --- */
    {
      id: 'es-hay-51', on: 'la primavera', okunus: 'la primavera', tur: 'isim (dişil)',
      arka: 'ilkbahar',
      ornek: 'En primavera todo se pone verde.',
      ornekTr: 'İlkbaharda her yer yeşerir.',
      not: 'Mevsimlerde edat "en"dir: en verano, en invierno.',
    },
    {
      id: 'es-hay-52', on: 'el otoño', okunus: 'el otonyo', tur: 'isim (eril)',
      arka: 'sonbahar',
      ornek: 'El otoño es mi estación favorita.',
      ornekTr: 'Sonbahar en sevdiğim mevsim.',
      not: '"la estación" hem mevsim hem istasyon demektir.',
    },
    {
      id: 'es-hay-53', on: 'nevar', okunus: 'nevar', tur: 'fiil',
      arka: 'kar yağmak',
      ornek: 'Nieva desde anoche.',
      ornekTr: 'Dün geceden beri kar yağıyor.',
      not: 'Hava fiilleri kişisizdir; çekimi düzensizdir.',
      kok: 'nieva',
    },
    {
      id: 'es-hay-54', on: 'la niebla', okunus: 'la nyebla', tur: 'isim (dişil)',
      arka: 'sis',
      ornek: 'Esta mañana había mucha niebla.',
      ornekTr: 'Bu sabah çok sis vardı.',
      not: '"había" vardı demektir.',
    },
    {
      id: 'es-hay-55', on: 'la tormenta', okunus: 'la tormenta', tur: 'isim (dişil)',
      arka: 'fırtına',
      ornek: 'Se acerca una tormenta.',
      ornekTr: 'Bir fırtına yaklaşıyor.',
      not: '"acercarse" yaklaşmak demektir.',
    },
    {
      id: 'es-hay-56', on: 'el relámpago', okunus: 'el relampago', tur: 'isim (eril)',
      arka: 'şimşek',
      ornek: 'El relámpago iluminó el cielo.',
      ornekTr: 'Şimşek gökyüzünü aydınlattı.',
      not: 'Gök gürültüsü "el trueno"dur.',
    },
    {
      id: 'es-hay-57', on: 'el viento', okunus: 'el vyento', tur: 'isim (eril)',
      arka: 'rüzgâr',
      ornek: 'Hoy hace mucho viento.',
      ornekTr: 'Bugün çok rüzgâr var.',
      not: 'Hava durumu "hacer" fiiliyle kurulur: hace frío, hace sol.',
    },
    {
      id: 'es-hay-58', on: 'la inundación', okunus: 'la inundasyon', tur: 'isim (dişil)',
      arka: 'sel',
      ornek: 'La inundación afectó a todo el pueblo.',
      ornekTr: 'Sel bütün köyü etkiledi.',
      not: '"afectar a" etkilemek demektir.',
    },
    {
      id: 'es-hay-59', on: 'el terremoto', okunus: 'el terremoto', tur: 'isim (eril)',
      arka: 'deprem',
      ornek: 'Turquía es una zona de terremotos.',
      ornekTr: 'Türkiye bir deprem bölgesidir.',
      not: '"la tierra" toprak, "moto" hareket kökünden gelir.',
    },
    {
      id: 'es-hay-60', on: 'la sequía', okunus: 'la sekiya', tur: 'isim (dişil)',
      arka: 'kuraklık',
      ornek: 'La sequía arruinó la cosecha.',
      ornekTr: 'Kuraklık hasadı mahvetti.',
      not: '"seco" kuru demektir.',
    },
    /* --- Çevre --- */
    {
      id: 'es-hay-61', on: 'el medio ambiente', okunus: 'el medyo ambyente', tur: 'isim (eril)',
      arka: 'çevre',
      ornek: 'Hay que cuidar el medio ambiente.',
      ornekTr: 'Çevreye özen göstermek gerekiyor.',
      not: '"cuidar" özen göstermek demektir.',
    },
    {
      id: 'es-hay-62', on: 'los residuos', okunus: 'los residuos', tur: 'isim (çoğul)',
      arka: 'atıklar',
      ornek: 'Hay que reducir los residuos plásticos.',
      ornekTr: 'Plastik atıkları azaltmak gerekiyor.',
      not: 'Günlük dilde "la basura" (çöp) da kullanılır.',
    },
    {
      id: 'es-hay-63', on: 'reciclar', okunus: 'resiklar', tur: 'fiil',
      arka: 'geri dönüştürmek',
      ornek: 'Reciclamos papel y vidrio en el instituto.',
      ornekTr: 'Lisede kâğıt ve camı geri dönüştürüyoruz.',
      not: '"el vidrio" cam demektir.',
    },
    {
      id: 'es-hay-64', on: 'la contaminación', okunus: 'la kontaminasyon', tur: 'isim (dişil)',
      arka: 'kirlilik',
      ornek: 'La contaminación del aire es un problema grave.',
      ornekTr: 'Hava kirliliği ciddi bir sorun.',
      not: '"contaminar" kirletmek demektir.',
    },
    {
      id: 'es-hay-65', on: 'el cambio climático', okunus: 'el kambyo klimatiko', tur: 'isim (eril)',
      arka: 'iklim değişikliği',
      ornek: 'El cambio climático nos afecta a todos.',
      ornekTr: 'İklim değişikliği hepimizi etkiliyor.',
      not: '"el clima" iklim demektir.',
    },
    {
      id: 'es-hay-66', on: 'la deforestación', okunus: 'la deforestasyon', tur: 'isim (dişil)',
      arka: 'ormansızlaşma',
      ornek: 'La deforestación destruye el hábitat de los animales.',
      ornekTr: 'Ormansızlaşma hayvanların yaşam alanını yok ediyor.',
      not: '"destruir" yok etmek demektir.',
    },
    {
      id: 'es-hay-67', on: 'la energía renovable', okunus: 'la enerhiya renovable', tur: 'isim (dişil)',
      arka: 'yenilenebilir enerji',
      ornek: 'La energía solar es renovable.',
      ornekTr: 'Güneş enerjisi yenilenebilirdir.',
      not: 'İspanya rüzgâr enerjisinde Avrupa\'nın önde gelen ülkelerindendir.',
    },
    {
      id: 'es-hay-68', on: 'extinguirse', okunus: 'ekstingirse', tur: 'fiil (dönüşlü)',
      arka: 'nesli tükenmek',
      ornek: 'Muchas especies se extinguen cada año.',
      ornekTr: 'Her yıl birçok türün nesli tükeniyor.',
      not: '"en peligro de extinción" nesli tehlikede demektir.',
    },
    {
      id: 'es-hay-69', on: 'proteger', okunus: 'proteher', tur: 'fiil',
      arka: 'korumak',
      ornek: 'Todos podemos proteger la naturaleza.',
      ornekTr: 'Hepimiz doğayı koruyabiliriz.',
      not: '"la protección" koruma demektir.',
    },
    {
      id: 'es-hay-70', on: 'el reciclaje', okunus: 'el resiklahe', tur: 'isim (eril)',
      arka: 'geri dönüşüm',
      ornek: 'El reciclaje empieza en casa.',
      ornekTr: 'Geri dönüşüm evde başlar.',
      not: 'İspanya\'da çöp kutuları renklere göre ayrılır.',
    },
    /* --- Doğada zaman geçirmek --- */
    {
      id: 'es-hay-71', on: 'dar un paseo', okunus: 'dar un paseo', tur: 'kalıp',
      arka: 'yürüyüşe çıkmak',
      ornek: 'Damos un paseo después de cenar.',
      ornekTr: 'Akşam yemeğinden sonra yürüyüşe çıkıyoruz.',
      not: 'İspanya\'da akşam yürüyüşü bir gelenektir.',
    },
    {
      id: 'es-hay-72', on: 'el pícnic', okunus: 'el piknik', tur: 'isim (eril)',
      arka: 'piknik',
      ornek: 'Hacemos un pícnic junto al lago.',
      ornekTr: 'Gölün yanında piknik yapıyoruz.',
      not: '"junto a" yanında demektir.',
    },
    {
      id: 'es-hay-73', on: 'acampar', okunus: 'akampar', tur: 'fiil',
      arka: 'kamp yapmak',
      ornek: 'Acampamos en la montaña cada verano.',
      ornekTr: 'Her yaz dağda kamp yapıyoruz.',
      not: '"la tienda de campaña" çadır demektir.',
    },
    {
      id: 'es-hay-74', on: 'la hoguera', okunus: 'la ogera', tur: 'isim (dişil)',
      arka: 'kamp ateşi',
      ornek: 'Cantamos alrededor de la hoguera.',
      ornekTr: 'Kamp ateşinin etrafında şarkı söyledik.',
      not: '"alrededor de" etrafında demektir.',
    },
    {
      id: 'es-hay-75', on: 'tomar el aire', okunus: 'tomar el ayre', tur: 'kalıp',
      arka: 'hava almak',
      ornek: 'Vamos a tomar el aire cinco minutos.',
      ornekTr: 'Beş dakika hava alalım.',
      not: 'Ders molası önerirken çok kullanışlıdır.',
    },
    {
      id: 'es-hay-76', on: 'la tranquilidad', okunus: 'la trankilidad', tur: 'isim (dişil)',
      arka: 'huzur, sessizlik',
      ornek: 'En el bosque hay mucha tranquilidad.',
      ornekTr: 'Ormanda büyük bir huzur var.',
      not: '"tranquilo" sakin demektir.',
    },
    {
      id: 'es-hay-77', on: 'impresionante', okunus: 'impresyonante', tur: 'sıfat',
      arka: 'nefes kesici, etkileyici',
      ornek: 'Las vistas eran impresionantes.',
      ornekTr: 'Manzara nefes kesiciydi.',
      not: '"impresionar" etkilemek demektir.',
    },
    {
      id: 'es-hay-78', on: 'en plena naturaleza', okunus: 'en plena naturalesa', tur: 'kalıp',
      arka: 'doğanın ortasında',
      ornek: 'La casa está en plena naturaleza.',
      ornekTr: 'Ev doğanın ortasında.',
      not: '"pleno" tam, dolu demektir.',
    },
    {
      id: 'es-hay-79', on: 'no dejar rastro', okunus: 'no dehar rastro', tur: 'kalıp',
      arka: 'iz bırakmamak',
      ornek: 'Al acampar hay que no dejar rastro.',
      ornekTr: 'Kamp yaparken iz bırakmamak gerekir.',
      not: '"el rastro" iz demektir.',
    },
    {
      id: 'es-hay-80', on: 'disfrutar de la naturaleza', okunus: 'disfrutar de la naturalesa', tur: 'kalıp',
      arka: 'doğanın tadını çıkarmak',
      ornek: 'Disfrutamos de la naturaleza cada fin de semana.',
      ornekTr: 'Her hafta sonu doğanın tadını çıkarıyoruz.',
      not: 'Edatı "de"dir.',
    },
    /* --- Hayvanlı deyimler --- */
    {
      id: 'es-hay-81', on: 'estar como pez en el agua', okunus: 'estar komo pes en el agua', tur: 'deyim',
      arka: 'sudaki balık gibi rahat olmak',
      ornek: 'En el escenario está como pez en el agua.',
      ornekTr: 'Sahnede sudaki balık gibi rahat.',
      not: '"el pez" canlı balık demektir.',
    },
    {
      id: 'es-hay-82', on: 'tener un hambre de lobo', okunus: 'tener un ambre de lobo', tur: 'deyim',
      arka: 'kurt gibi acıkmak',
      ornek: 'Después del entrenamiento tengo un hambre de lobo.',
      ornekTr: 'Antrenmandan sonra kurt gibi acıkıyorum.',
      not: '"el lobo" kurt demektir.',
    },
    {
      id: 'es-hay-83', on: 'cuando las ranas críen pelo', okunus: 'kuando las ranas krien pelo', tur: 'deyim',
      arka: 'balık kavağa çıkınca',
      ornek: 'Ordenará su cuarto cuando las ranas críen pelo.',
      ornekTr: 'Odasını balık kavağa çıkınca toplar.',
      not: 'Kelimesi kelimesine "kurbağalar tüy çıkarınca" demektir.',
    },
    {
      id: 'es-hay-84', on: 'matar dos pájaros de un tiro', okunus: 'matar dos paharos de un tiro', tur: 'deyim',
      arka: 'bir taşla iki kuş vurmak',
      ornek: 'Así mato dos pájaros de un tiro.',
      ornekTr: 'Böylece bir taşla iki kuş vuruyorum.',
      not: '"el tiro" atış demektir.',
    },
    {
      id: 'es-hay-85', on: 'llover a cántaros', okunus: 'yover a kantaros', tur: 'deyim',
      arka: 'bardaktan boşanırcasına yağmak',
      ornek: 'Coge el paraguas, está lloviendo a cántaros.',
      ornekTr: 'Şemsiyeyi al, bardaktan boşanırcasına yağıyor.',
      not: '"el cántaro" testi demektir.',
      kok: 'lloviendo',
    },
    {
      id: 'es-hay-86', on: 'ser una mosquita muerta', okunus: 'ser una moskita muerta', tur: 'deyim',
      arka: 'masum görünüp öyle olmamak',
      ornek: 'Parece tímida pero es una mosquita muerta.',
      ornekTr: 'Utangaç görünüyor ama göründüğü gibi değil.',
      not: 'Kelimesi kelimesine "ölü sinekçik" demektir.',
    },
    {
      id: 'es-hay-87', on: 'buscarle tres pies al gato', okunus: 'buskarle tres pyes al gato', tur: 'deyim',
      arka: 'olmayan sorun aramak',
      ornek: 'No le busques tres pies al gato.',
      ornekTr: 'Olmayan sorunu arama.',
      not: 'Kelimesi kelimesine "kediye üç ayak aramak" demektir.',
    },
    {
      id: 'es-hay-88', on: 'estar en la luna', okunus: 'estar en la luna', tur: 'deyim',
      arka: 'aklı başka yerde olmak',
      ornek: 'Hoy estás en la luna.',
      ornekTr: 'Bugün aklın başka yerde.',
      not: '"la luna" ay demektir.',
    },
    {
      id: 'es-hay-89', on: 'no hay mal que por bien no venga', okunus: 'no ay mal ke por byen no venga', tur: 'atasözü',
      arka: 'Her şerde bir hayır vardır',
      ornek: 'Perdiste el autobús pero conociste a alguien: no hay mal que por bien no venga.',
      ornekTr: 'Otobüsü kaçırdın ama biriyle tanıştın: her şerde bir hayır vardır.',
      not: 'Türkçedeki karşılığıyla aynı işlevdedir.',
    },
    {
      id: 'es-hay-90', on: 'más vale prevenir que curar', okunus: 'mas vale prevenir ke kurar', tur: 'atasözü',
      arka: 'Önlemek tedaviden iyidir',
      ornek: 'Lleva chaqueta: más vale prevenir que curar.',
      ornekTr: 'Ceket al: önlemek tedaviden iyidir.',
      not: 'Sağlık ve çevre metinlerinde sık geçer.',
    },
    /* --- Doğa metinlerinin dili --- */
    {
      id: 'es-hay-91', on: 'la mayoría de', okunus: 'la mayoriya de', tur: 'kalıp',
      arka: 'çoğu',
      ornek: 'La mayoría de los animales vive en el bosque.',
      ornekTr: 'Hayvanların çoğu ormanda yaşıyor.',
      not: '"la mayoría" çoğunluk demektir.',
    },
    {
      id: 'es-hay-92', on: 'cada vez menos', okunus: 'kada ves menos', tur: 'kalıp',
      arka: 'gitgide daha az',
      ornek: 'Hay cada vez menos abejas.',
      ornekTr: 'Gitgide daha az arı var.',
      not: 'Tersi "cada vez más" = gitgide daha çok.',
    },
    {
      id: 'es-hay-93', on: 'antes', okunus: 'antes', tur: 'zarf',
      arka: 'eskiden, önce',
      ornek: 'Antes había más bosques aquí.',
      ornekTr: 'Eskiden burada daha çok orman vardı.',
      not: '"había" vardı demektir.',
    },
    {
      id: 'es-hay-94', on: 'es probable que', okunus: 'es probable ke', tur: 'kalıp',
      arka: 'muhtemeldir ki',
      ornek: 'Es probable que suban las temperaturas.',
      ornekTr: 'Sıcaklıkların artması muhtemel.',
      not: 'Sonrasında dilek kipi gelir: "suban".',
    },
    {
      id: 'es-hay-95', on: 'debido a', okunus: 'debido a', tur: 'kalıp',
      arka: '... nedeniyle',
      ornek: 'Muchas especies desaparecen debido a la contaminación.',
      ornekTr: 'Kirlilik nedeniyle birçok tür yok oluyor.',
      not: 'Resmî yazıda "por" yerine tercih edilir.',
    },
    {
      id: 'es-hay-96', on: 'por lo tanto', okunus: 'por lo tanto', tur: 'kalıp',
      arka: 'dolayısıyla',
      ornek: 'El hielo se derrite; por lo tanto, sube el nivel del mar.',
      ornekTr: 'Buzlar eriyor; dolayısıyla deniz seviyesi yükseliyor.',
      not: '"derretirse" erimek demektir.',
    },
    {
      id: 'es-hay-97', on: 'en peligro de extinción', okunus: 'en peligro de ekstinsyon', tur: 'kalıp',
      arka: 'nesli tükenme tehlikesinde',
      ornek: 'Esta especie está en peligro de extinción.',
      ornekTr: 'Bu türün nesli tükenme tehlikesinde.',
      not: 'Çevre metinlerinin standart ifadesidir.',
    },
    {
      id: 'es-hay-98', on: 'tomar medidas', okunus: 'tomar medidas', tur: 'kalıp',
      arka: 'önlem almak',
      ornek: 'Hay que tomar medidas ya.',
      ornekTr: 'Hemen önlem almak gerekiyor.',
      not: '"la medida" önlem, ölçü demektir.',
    },
    {
      id: 'es-hay-99', on: 'marcar la diferencia', okunus: 'markar la diferensya', tur: 'kalıp',
      arka: 'fark yaratmak',
      ornek: 'Los pequeños gestos marcan la diferencia.',
      ornekTr: 'Küçük davranışlar fark yaratır.',
      not: '"el gesto" davranış, jest demektir.',
    },
    {
      id: 'es-hay-100', on: 'cuidar el planeta', okunus: 'kuidar el planeta', tur: 'kalıp',
      arka: 'gezegene sahip çıkmak',
      ornek: 'Cuidar el planeta es cuidar el futuro.',
      ornekTr: 'Gezegene sahip çıkmak geleceğe sahip çıkmaktır.',
      not: '"el futuro" gelecek demektir.',
    },
  ],
}

export default DESTE
