/**
 * DESTE — MÜZİK, DİZİ VE FİLM (İspanyolca)
 *
 * İspanyolca müzik ve dizi dünyada çok dinleniyor ve izleniyor; öğrenci
 * bu kelimeleri şarkı sözlerinde zaten duyuyor. Kartlar o tanıdıklığı
 * anlama çevirir.
 */

export const DESTE = {
  id: 'muzik-dizi',
  dil: 'es',
  ad: 'Müzik, dizi ve film',
  simge: '🎬',
  aciklama: 'Şarkı sözlerinde ve dizilerde en çok geçen kelimeler.',
  seviye: 'A1–A2',
  kartlar: [
    {
      id: 'es-muz-01', on: 'la canción', okunus: 'la kansiyon', tur: 'isim (dişil)',
      arka: 'şarkı',
      ornek: 'Esta canción está en mi cabeza desde esta mañana.',
      ornekTr: 'Bu şarkı sabahtan beri aklımda.',
      not: '-ción ile biten bütün isimler dişildir. Çoğulu "canciones" (aksan düşer).',
    },
    {
      id: 'es-muz-02', on: 'la letra', okunus: 'la letra', tur: 'isim (dişil)',
      arka: 'şarkı sözü; harf',
      ornek: 'No entiendo la letra de esta canción.',
      ornekTr: 'Bu şarkının sözlerini anlamıyorum.',
      not: 'Aynı kelime "harf" demektir. Şarkı sözü için tekil kullanılır.',
    },
    {
      id: 'es-muz-03', on: 'la serie', okunus: 'la serye', tur: 'isim (dişil)',
      arka: 'dizi',
      ornek: 'Vi toda la serie en un fin de semana.',
      ornekTr: 'Bütün diziyi bir hafta sonunda izledim.',
      not: 'Bölüm "el capítulo", sezon "la temporada".',
    },
    {
      id: 'es-muz-04', on: 'la película', okunus: 'la pelikula', tur: 'isim (dişil)',
      arka: 'film',
      ornek: 'La película dura dos horas.',
      ornekTr: 'Film iki saat sürüyor.',
      not: 'Aksan zorunludur; vurgu sondan üçüncü hecededir.',
    },
    {
      id: 'es-muz-05', on: 'los subtítulos', okunus: 'los subtitulos', tur: 'isim (çoğul)',
      arka: 'altyazı',
      ornek: 'Veo las series con subtítulos en español.',
      ornekTr: 'Dizileri İspanyolca altyazıyla izliyorum.',
      not: 'Genelde çoğul kullanılır. Dil öğrenmenin en işe yarar ayarı.',
    },
    {
      id: 'es-muz-06', on: 'el personaje', okunus: 'el personahe', tur: 'isim (eril)',
      arka: 'karakter (film/dizi)',
      ornek: 'Mi personaje favorito muere al final.',
      ornekTr: 'En sevdiğim karakter sonda ölüyor.',
      not: 'Kişilik anlamındaki karakter "el carácter"dır; ikisi karışır.',
    },
    {
      id: 'es-muz-07', on: 'la voz', okunus: 'la bos', tur: 'isim (dişil)',
      arka: 'ses (insan sesi)',
      ornek: 'Tiene una voz increíble.',
      ornekTr: 'İnanılmaz bir sesi var.',
      not: 'Çoğulu "las voces" — z harfi c olur.',
    },
    {
      id: 'es-muz-08', on: 'el estreno', okunus: 'el estreno', tur: 'isim (eril)',
      arka: 'gösterime giriş, ilk yayın',
      ornek: 'El estreno de la película es el viernes.',
      ornekTr: 'Filmin gösterime girişi cuma.',
      not: 'Fiili "estrenar"dır: gösterime girmek, ilk kez kullanmak.',
    },
    {
      id: 'es-muz-09', on: 'pegadizo', okunus: 'pegadiso', tur: 'sıfat',
      arka: 'akılda kalıcı (şarkı)',
      ornek: 'El estribillo es muy pegadizo.',
      ornekTr: 'Nakarat çok akılda kalıcı.',
      not: '"pegar" (yapışmak) fiilinden gelir. Nakarat "el estribillo".',
    },
    {
      id: 'es-muz-10', on: 'está guay', okunus: 'esta guay', tur: 'kalıp (günlük)',
      arka: 'süper, çok iyi',
      ornek: 'Su nuevo disco está muy guay.',
      ornekTr: 'Yeni albümü çok iyi.',
      not: 'İspanya\'ya özgüdür; Latin Amerika\'da "chévere" ya da "padre" denir.',
    },
    /* --- Müzik --- */
    {
      id: 'es-muz-11', on: 'el cantante', okunus: 'el kantante', tur: 'isim (eril)',
      arka: 'şarkıcı',
      ornek: 'El cantante tiene una voz grave.',
      ornekTr: 'Şarkıcının kalın bir sesi var.',
      not: 'Kadın için "la cantante" denir; kelime değişmez, artikel değişir.',
    },
    {
      id: 'es-muz-12', on: 'el grupo', okunus: 'el grupo', tur: 'isim (eril)',
      arka: 'müzik grubu',
      ornek: 'Ese grupo toca esta noche.',
      ornekTr: 'O grup bu gece çalıyor.',
      not: '"la banda" da kullanılır.',
    },
    {
      id: 'es-muz-13', on: 'el concierto', okunus: 'el konsyerto', tur: 'isim (eril)',
      arka: 'konser',
      ornek: 'Vamos al concierto mañana.',
      ornekTr: 'Yarın konsere gidiyoruz.',
      not: '"ir a" kalıbı: al concierto, al cine.',
    },
    {
      id: 'es-muz-14', on: 'el disco', okunus: 'el disko', tur: 'isim (eril)',
      arka: 'albüm, plak',
      ornek: 'Su nuevo disco es buenísimo.',
      ornekTr: 'Yeni albümleri çok iyi.',
      not: '"-ísimo" eki en üst derecede anlamı verir.',
    },
    {
      id: 'es-muz-15', on: 'el estribillo', okunus: 'el estribiyo', tur: 'isim (eril)',
      arka: 'nakarat',
      ornek: 'Todos cantan el estribillo.',
      ornekTr: 'Herkes nakaratı söylüyor.',
      not: 'İspanyolcada "ll" harfi "y" gibi okunur.',
    },
    {
      id: 'es-muz-16', on: 'la melodía', okunus: 'la melodiya', tur: 'isim (dişil)',
      arka: 'melodi',
      ornek: 'Recuerdo la melodía pero no la letra.',
      ornekTr: 'Melodiyi hatırlıyorum ama sözleri değil.',
      not: '"la letra" şarkı sözü demektir.',
    },
    {
      id: 'es-muz-17', on: 'la versión', okunus: 'la versyon', tur: 'isim (dişil)',
      arka: 'cover, yeniden yorum',
      ornek: 'Hizo una versión de una canción antigua.',
      ornekTr: 'Eski bir şarkının coverını yaptı.',
      not: '"antiguo" eski demektir.',
    },
    {
      id: 'es-muz-18', on: 'el éxito', okunus: 'el eksito', tur: 'isim (eril)',
      arka: 'hit; başarı',
      ornek: 'Esa canción fue un gran éxito.',
      ornekTr: 'O şarkı büyük bir hit oldu.',
      not: 'İngilizce "exit" ile karıştırma; anlamı "başarı"dır.',
    },
    {
      id: 'es-muz-19', on: 'sacar un disco', okunus: 'sakar un disko', tur: 'kalıp',
      arka: 'albüm çıkarmak',
      ornek: 'Van a sacar un disco en marzo.',
      ornekTr: 'Martta albüm çıkaracaklar.',
      not: '"ir a + mastar" yakın gelecek kurar.',
    },
    {
      id: 'es-muz-20', on: 'la gira', okunus: 'la hira', tur: 'isim (dişil)',
      arka: 'turne',
      ornek: 'El grupo empieza una gira este verano.',
      ornekTr: 'Grup bu yaz turneye başlıyor.',
      not: '"girar" dönmek demektir.',
    },
    /* --- Dinleme --- */
    {
      id: 'es-muz-21', on: 'los auriculares', okunus: 'los aurikulares', tur: 'isim (çoğul)',
      arka: 'kulaklık',
      ornek: 'Nunca sale sin sus auriculares.',
      ornekTr: 'Kulaklığı olmadan asla çıkmaz.',
      not: 'Latin Amerika\'da "los audífonos" denir.',
    },
    {
      id: 'es-muz-22', on: 'la lista de reproducción', okunus: 'la lista de reproduksyon', tur: 'isim (dişil)',
      arka: 'çalma listesi',
      ornek: 'Tengo una lista de reproducción para estudiar.',
      ornekTr: 'Ders çalışmak için bir çalma listem var.',
      not: 'Konuşmada İngilizce "la playlist" de kullanılır.',
    },
    {
      id: 'es-muz-23', on: 'en bucle', okunus: 'en bukle', tur: 'kalıp',
      arka: 'sürekli tekrar tekrar',
      ornek: 'Escucho esa canción en bucle.',
      ornekTr: 'O şarkıyı sürekli tekrar dinliyorum.',
      not: '"el bucle" halka, döngü demektir.',
    },
    {
      id: 'es-muz-24', on: 'subir el volumen', okunus: 'subir el volumen', tur: 'kalıp',
      arka: 'sesi açmak',
      ornek: '¡Sube el volumen, me encanta esta canción!',
      ornekTr: 'Sesi aç, bu şarkıya bayılıyorum!',
      not: 'Sesi kısmak "bajar el volumen"dur.',
    },
    {
      id: 'es-muz-25', on: 'en directo', okunus: 'en direkto', tur: 'kalıp',
      arka: 'canlı',
      ornek: 'Nunca los he visto en directo.',
      ornekTr: 'Onları hiç canlı izlemedim.',
      not: 'Latin Amerika\'da "en vivo" denir.',
    },
    {
      id: 'es-muz-26', on: 'descubrir', okunus: 'deskubrir', tur: 'fiil',
      arka: 'keşfetmek',
      ornek: 'Me gusta descubrir artistas nuevos.',
      ornekTr: 'Yeni sanatçılar keşfetmeyi seviyorum.',
      not: '"cubrir" örtmek; "des-" ön eki tersini yapar.',
    },
    {
      id: 'es-muz-27', on: 'cantar a coro', okunus: 'kantar a koro', tur: 'kalıp',
      arka: 'hep birlikte söylemek',
      ornek: 'El público canta a coro.',
      ornekTr: 'Seyirci hep birlikte söylüyor.',
      not: '"el coro" koro demektir.',
    },
    {
      id: 'es-muz-28', on: 'ser fan de', okunus: 'ser fan de', tur: 'kalıp',
      arka: 'hayranı olmak',
      ornek: 'Soy fan de este grupo desde hace dos años.',
      ornekTr: 'İki yıldır bu grubun hayranıyım.',
      not: '"desde hace" ile süre bildirilir.',
    },
    {
      id: 'es-muz-29', on: 'el ritmo', okunus: 'el ritmo', tur: 'isim (eril)',
      arka: 'ritim',
      ornek: 'Esta canción tiene un ritmo pegadizo.',
      ornekTr: 'Bu şarkının akılda kalıcı bir ritmi var.',
      not: 'Latin müziğinin en çok konuşulan özelliğidir.',
    },
    {
      id: 'es-muz-30', on: 'bailar', okunus: 'baylar', tur: 'fiil',
      arka: 'dans etmek',
      ornek: 'En las fiestas todo el mundo baila.',
      ornekTr: 'Partilerde herkes dans ediyor.',
      not: '"el baile" dans demektir.',
    },
    /* --- Enstrüman ve sahne --- */
    {
      id: 'es-muz-31', on: 'tocar la guitarra', okunus: 'tokar la gitarra', tur: 'kalıp',
      arka: 'gitar çalmak',
      ornek: 'Toca la guitarra desde los seis años.',
      ornekTr: 'Altı yaşından beri gitar çalıyor.',
      not: 'Çalgı çalmak "tocar"dır; "jugar" oyun oynamaktır.',
    },
    {
      id: 'es-muz-32', on: 'el piano', okunus: 'el pyano', tur: 'isim (eril)',
      arka: 'piyano',
      ornek: 'Mi hermana aprende piano.',
      ornekTr: 'Kız kardeşim piyano öğreniyor.',
      not: '"aprender" öğrenmek demektir.',
    },
    {
      id: 'es-muz-33', on: 'la batería', okunus: 'la bateriya', tur: 'isim (dişil)',
      arka: 'bateri; pil',
      ornek: 'Mi hermano toca la batería.',
      ornekTr: 'Kardeşim bateri çalıyor.',
      not: 'Aynı kelime telefon pili anlamına da gelir.',
    },
    {
      id: 'es-muz-34', on: 'ensayar', okunus: 'ensayar', tur: 'fiil',
      arka: 'prova yapmak',
      ornek: 'El grupo ensaya todos los sábados.',
      ornekTr: 'Grup her cumartesi prova yapıyor.',
      not: '"el ensayo" prova ve deneme demektir.',
    },
    {
      id: 'es-muz-35', on: 'el escenario', okunus: 'el essenaryo', tur: 'isim (eril)',
      arka: 'sahne',
      ornek: 'Suben al escenario a las nueve.',
      ornekTr: 'Saat dokuzda sahneye çıkıyorlar.',
      not: '"subir al escenario" = sahneye çıkmak.',
    },
    {
      id: 'es-muz-36', on: 'los nervios', okunus: 'los nervyos', tur: 'isim (çoğul)',
      arka: 'heyecan, gerginlik',
      ornek: 'Tiene nervios antes de cada concierto.',
      ornekTr: 'Her konserden önce heyecanlanıyor.',
      not: '"tener nervios" gergin olmak demektir.',
    },
    {
      id: 'es-muz-37', on: 'desafinar', okunus: 'desafinar', tur: 'fiil',
      arka: 'akortsuz söylemek',
      ornek: 'Canto bien pero a veces desafino.',
      ornekTr: 'İyi söylüyorum ama bazen akortsuz oluyorum.',
      not: '"afinar" akort etmek demektir.',
    },
    {
      id: 'es-muz-38', on: 'aplaudir', okunus: 'aplaudir', tur: 'fiil',
      arka: 'alkışlamak',
      ornek: 'El público aplaudió cinco minutos.',
      ornekTr: 'Seyirci beş dakika alkışladı.',
      not: '"los aplausos" alkış demektir.',
    },
    {
      id: 'es-muz-39', on: 'la banda sonora', okunus: 'la banda sonora', tur: 'isim (dişil)',
      arka: 'film müziği',
      ornek: 'La banda sonora es mejor que la película.',
      ornekTr: 'Film müziği filmden iyi.',
      not: 'Kısaltması "la BSO"dur.',
    },
    {
      id: 'es-muz-40', on: 'el público', okunus: 'el publiko', tur: 'isim (eril)',
      arka: 'izleyici topluluğu',
      ornek: 'El público estaba entusiasmado.',
      ornekTr: 'İzleyiciler coşkuluydu.',
      not: '"entusiasmado" coşkulu demektir.',
    },
    /* --- Dizi ve film --- */
    {
      id: 'es-muz-41', on: 'el capítulo', okunus: 'el kapitulo', tur: 'isim (eril)',
      arka: 'bölüm',
      ornek: 'El último capítulo duró dos horas.',
      ornekTr: 'Son bölüm iki saat sürdü.',
      not: 'Kitap bölümü için de aynı kelime kullanılır.',
    },
    {
      id: 'es-muz-42', on: 'la temporada', okunus: 'la temporada', tur: 'isim (dişil)',
      arka: 'sezon',
      ornek: 'La tercera temporada sale en abril.',
      ornekTr: 'Üçüncü sezon nisanda çıkıyor.',
      not: 'Spor sezonu için de aynı kelime kullanılır.',
    },
    {
      id: 'es-muz-43', on: 'la trama', okunus: 'la trama', tur: 'isim (dişil)',
      arka: 'olay örgüsü',
      ornek: 'La trama es confusa al principio.',
      ornekTr: 'Olay örgüsü başta kafa karıştırıcı.',
      not: '"al principio" başlangıçta demektir.',
    },
    {
      id: 'es-muz-44', on: 'el director', okunus: 'el direktor', tur: 'isim (eril)',
      arka: 'yönetmen',
      ornek: 'El director ganó un premio.',
      ornekTr: 'Yönetmen bir ödül kazandı.',
      not: 'Okul müdürü için de aynı kelime kullanılır.',
    },
    {
      id: 'es-muz-45', on: 'el protagonista', okunus: 'el protagonista', tur: 'isim (eril)',
      arka: 'başkarakter',
      ornek: 'El protagonista muere al final.',
      ornekTr: 'Başkarakter sonunda ölüyor.',
      not: 'Kadın için "la protagonista" denir.',
    },
    {
      id: 'es-muz-46', on: 'el doblaje', okunus: 'el doblahe', tur: 'isim (eril)',
      arka: 'dublaj',
      ornek: 'En España el doblaje es muy común.',
      ornekTr: 'İspanya\'da dublaj çok yaygındır.',
      not: 'İspanya\'da filmler genellikle dublajlı gösterilir.',
    },
    {
      id: 'es-muz-47', on: 'la versión original', okunus: 'la versyon orihinal', tur: 'isim (dişil)',
      arka: 'orijinal dil',
      ornek: 'Veo las series en versión original.',
      ornekTr: 'Dizileri orijinal dilinde izliyorum.',
      not: 'Kısaltması "V.O."dur; altyazılı hâli "V.O.S.".',
    },
    {
      id: 'es-muz-48', on: 'el tráiler', okunus: 'el trayler', tur: 'isim (eril)',
      arka: 'fragman',
      ornek: 'El tráiler tiene muy buena pinta.',
      ornekTr: 'Fragman çok iyi görünüyor.',
      not: '"tener buena pinta" = iyi görünmek.',
    },
    {
      id: 'es-muz-49', on: 'el spoiler', okunus: 'el espoyler', tur: 'isim (eril)',
      arka: 'sürprizi bozan bilgi',
      ornek: '¡No me hagas spoiler!',
      ornekTr: 'Sakın sürprizi bozma!',
      not: 'İspanyolcada başına "e" sesi eklenerek okunur.',
    },
    {
      id: 'es-muz-50', on: 'el desenlace', okunus: 'el desenlase', tur: 'isim (eril)',
      arka: 'final, çözülme',
      ornek: 'El desenlace me sorprendió.',
      ornekTr: 'Final beni şaşırttı.',
      not: '"enlazar" bağlamak; "des-" çözmek anlamı katar.',
    },
    /* --- Türler --- */
    {
      id: 'es-muz-51', on: 'la comedia', okunus: 'la komedya', tur: 'isim (dişil)',
      arka: 'komedi',
      ornek: 'Prefiero las comedias a las de terror.',
      ornekTr: 'Komedileri korku filmlerine tercih ederim.',
      not: '"preferir A a B" kalıbında edat "a"dır.',
    },
    {
      id: 'es-muz-52', on: 'el suspense', okunus: 'el suspense', tur: 'isim (eril)',
      arka: 'gerilim',
      ornek: 'Es una película de suspense.',
      ornekTr: 'Gerilim filmi.',
      not: 'Latin Amerika\'da "el suspenso" denir.',
    },
    {
      id: 'es-muz-53', on: 'el documental', okunus: 'el dokumental', tur: 'isim (eril)',
      arka: 'belgesel',
      ornek: 'Vimos un documental sobre el océano.',
      ornekTr: 'Okyanusla ilgili bir belgesel izledik.',
      not: 'Konu edatı "sobre"dir.',
    },
    {
      id: 'es-muz-54', on: 'los dibujos animados', okunus: 'los dibuhos animados', tur: 'isim (çoğul)',
      arka: 'çizgi film',
      ornek: 'Los dibujos animados no son solo para niños.',
      ornekTr: 'Çizgi filmler sadece çocuklar için değil.',
      not: '"dibujar" çizmek demektir.',
    },
    {
      id: 'es-muz-55', on: 'la ciencia ficción', okunus: 'la syensya fiksyon', tur: 'isim (dişil)',
      arka: 'bilim kurgu',
      ornek: 'Solo ve ciencia ficción.',
      ornekTr: 'Sadece bilim kurgu izliyor.',
      not: '"la ciencia" bilim demektir.',
    },
    {
      id: 'es-muz-56', on: 'la película de terror', okunus: 'la pelikula de terror', tur: 'isim (dişil)',
      arka: 'korku filmi',
      ornek: 'No duermo después de una película de terror.',
      ornekTr: 'Korku filminden sonra uyuyamıyorum.',
      not: '"el terror" dehşet demektir.',
    },
    {
      id: 'es-muz-57', on: 'la secuela', okunus: 'la sekuela', tur: 'isim (dişil)',
      arka: 'devam filmi',
      ornek: 'La secuela es peor que la primera parte.',
      ornekTr: 'Devam filmi ilkinden kötü.',
      not: '"peor" daha kötü demektir.',
    },
    {
      id: 'es-muz-58', on: 'basada en hechos reales', okunus: 'basada en eços reales', tur: 'kalıp',
      arka: 'gerçek olaylardan uyarlanmış',
      ornek: 'La película está basada en hechos reales.',
      ornekTr: 'Film gerçek olaylardan uyarlanmış.',
      not: '"el hecho" olgu, olay demektir.',
    },
    {
      id: 'es-muz-59', on: 'el estreno', okunus: 'el estreno', tur: 'isim (eril)',
      arka: 'ilk gösterim, vizyona giriş',
      ornek: 'El estreno es el viernes.',
      ornekTr: 'İlk gösterim cuma.',
      not: '"estrenar" ilk kez kullanmak, giymek anlamına da gelir.',
    },
    {
      id: 'es-muz-60', on: 'el reparto', okunus: 'el reparto', tur: 'isim (eril)',
      arka: 'oyuncu kadrosu',
      ornek: 'El reparto está lleno de actores famosos.',
      ornekTr: 'Oyuncu kadrosu ünlü oyuncularla dolu.',
      not: '"repartir" dağıtmak demektir.',
    },
    /* --- İzleme ve değerlendirme --- */
    {
      id: 'es-muz-61', on: 'hacer un maratón', okunus: 'aser un maraton', tur: 'kalıp',
      arka: 'arka arkaya bölüm izlemek',
      ornek: 'Hice un maratón de la serie el fin de semana.',
      ornekTr: 'Hafta sonu diziyi arka arkaya izledim.',
      not: 'İngilizce "binge-watch" karşılığıdır.',
    },
    {
      id: 'es-muz-62', on: 'recomendar', okunus: 'rekomendar', tur: 'fiil',
      arka: 'tavsiye etmek',
      ornek: 'Te recomiendo esta serie.',
      ornekTr: 'Sana bu diziyi tavsiye ediyorum.',
      not: 'Çekimi düzensizdir: recomiendo, recomiendas.',
      kok: 'recomiendo',
    },
    {
      id: 'es-muz-63', on: 'la crítica', okunus: 'la kritika', tur: 'isim (dişil)',
      arka: 'eleştiri',
      ornek: 'Las críticas fueron muy buenas.',
      ornekTr: 'Eleştiriler çok iyiydi.',
      not: 'Eleştirmen "el crítico"dur.',
    },
    {
      id: 'es-muz-64', on: 'puntuar', okunus: 'puntuar', tur: 'fiil',
      arka: 'puan vermek',
      ornek: 'Yo la puntúo con un ocho sobre diez.',
      ornekTr: 'Ona on üzerinden sekiz veriyorum.',
      not: '"sobre" ile puan verilir: ocho sobre diez.',
      kok: 'puntúo',
    },
    {
      id: 'es-muz-65', on: 'valer la pena', okunus: 'valer la pena', tur: 'deyim',
      arka: 'değmek',
      ornek: 'Es larga, pero vale la pena.',
      ornekTr: 'Uzun ama buna değer.',
      not: '"la pena" acı, zahmet demektir.',
    },
    {
      id: 'es-muz-66', on: 'me encanta', okunus: 'me enkanta', tur: 'kalıp',
      arka: 'bayılıyorum',
      ornek: 'Me encanta esta actriz.',
      ornekTr: 'Bu oyuncuya bayılıyorum.',
      not: '"gustar" gibi çalışır: özne beğenilen şeydir.',
    },
    {
      id: 'es-muz-67', on: 'no es lo mío', okunus: 'no es lo miyo', tur: 'kalıp',
      arka: 'benim tarzım değil',
      ornek: 'Los musicales no son lo mío.',
      ornekTr: 'Müzikaller benim tarzım değil.',
      not: 'Kibar bir beğenmeme ifadesidir.',
    },
    {
      id: 'es-muz-68', on: 'ser un rollo', okunus: 'ser un royo', tur: 'deyim',
      arka: 'çok sıkıcı olmak',
      ornek: 'Esa película es un rollo.',
      ornekTr: 'O film çok sıkıcı.',
      not: '"el rollo" rulo demektir; gündelik dilde sıkıcılık anlatır.',
    },
    {
      id: 'es-muz-69', on: 'engancharse a', okunus: 'engançarse a', tur: 'fiil (dönüşlü)',
      arka: 'bir şeye kaptırmak',
      ornek: 'Me he enganchado a esta serie.',
      ornekTr: 'Bu diziye kaptırdım.',
      not: '"el gancho" kanca demektir.',
    },
    {
      id: 'es-muz-70', on: 'poner una serie', okunus: 'poner una serye', tur: 'kalıp',
      arka: 'dizi açmak, izlemeye başlamak',
      ornek: '¿Ponemos una serie esta noche?',
      ornekTr: 'Bu akşam dizi açalım mı?',
      not: '"poner" koymak, açmak demektir.',
    },
    /* --- Yorum sıfatları --- */
    {
      id: 'es-muz-71', on: 'emocionante', okunus: 'emosyonante', tur: 'sıfat',
      arka: 'heyecan verici, duygulandırıcı',
      ornek: 'Fue una historia muy emocionante.',
      ornekTr: 'Çok duygulandırıcı bir hikâyeydi.',
      not: '"emocionarse" duygulanmak demektir.',
    },
    {
      id: 'es-muz-72', on: 'divertido', okunus: 'divertido', tur: 'sıfat',
      arka: 'eğlenceli, komik',
      ornek: 'Esa escena es muy divertida.',
      ornekTr: 'O sahne çok eğlenceli.',
      not: '"divertirse" eğlenmek demektir.',
    },
    {
      id: 'es-muz-73', on: 'predecible', okunus: 'predesible', tur: 'sıfat',
      arka: 'tahmin edilebilir',
      ornek: 'El final era totalmente predecible.',
      ornekTr: 'Final tamamen tahmin edilebilirdi.',
      not: '"predecir" öngörmek demektir.',
    },
    {
      id: 'es-muz-74', on: 'aterrador', okunus: 'aterrador', tur: 'sıfat',
      arka: 'korkutucu',
      ornek: 'La casa de la película es aterradora.',
      ornekTr: 'Filmdeki ev korkutucu.',
      not: '"aterrar" dehşete düşürmek demektir.',
    },
    {
      id: 'es-muz-75', on: 'precioso', okunus: 'presyoso', tur: 'sıfat',
      arka: 'çok güzel',
      ornek: 'Los paisajes son preciosos.',
      ornekTr: 'Manzaralar çok güzel.',
      not: '"el precio" fiyat demektir; kelime "değerli" anlamından gelir.',
    },
    {
      id: 'es-muz-76', on: 'sobrevalorado', okunus: 'sobrevalorado', tur: 'sıfat',
      arka: 'hak ettiğinden fazla övülen',
      ornek: 'Esta serie está sobrevalorada.',
      ornekTr: 'Bu dizi hak ettiğinden fazla övülüyor.',
      not: 'Tersi "infravalorado" = hak ettiği değeri görmeyen.',
    },
    {
      id: 'es-muz-77', on: 'entretenido', okunus: 'entretenido', tur: 'sıfat',
      arka: 'eğlendirici, oyalayıcı',
      ornek: 'No es genial, pero es entretenida.',
      ornekTr: 'Harika değil ama eğlendirici.',
      not: '"entretener" oyalamak, eğlendirmek demektir.',
    },
    {
      id: 'es-muz-78', on: 'lento', okunus: 'lento', tur: 'sıfat',
      arka: 'yavaş',
      ornek: 'La parte del medio es un poco lenta.',
      ornekTr: 'Orta bölüm biraz yavaş.',
      not: 'Zarfı "lentamente"dir.',
    },
    {
      id: 'es-muz-79', on: 'bien hecho', okunus: 'byen eço', tur: 'kalıp',
      arka: 'iyi yapılmış',
      ornek: 'El guion está muy bien hecho.',
      ornekTr: 'Senaryo çok iyi yazılmış.',
      not: '"el guion" senaryo demektir.',
    },
    {
      id: 'es-muz-80', on: 'imprescindible', okunus: 'impressindible', tur: 'sıfat',
      arka: 'olmazsa olmaz, mutlaka görülmeli',
      ornek: 'Esta película es imprescindible.',
      ornekTr: 'Bu film mutlaka izlenmeli.',
      not: 'Uzun ama İspanyolcada çok kullanılan bir kelimedir.',
    },
    /* --- Deyimler --- */
    {
      id: 'es-muz-81', on: 'tener una canción metida en la cabeza', okunus: 'tener una kansyon metida en la kabesa', tur: 'deyim',
      arka: 'şarkı aklına takılmak',
      ornek: 'Tengo esa canción metida en la cabeza.',
      ornekTr: 'O şarkı aklıma takıldı.',
      not: '"meter" sokmak, koymak demektir.',
    },
    {
      id: 'es-muz-82', on: 'ser la estrella', okunus: 'ser la estreya', tur: 'deyim',
      arka: 'yıldız olmak, ilgiyi toplamak',
      ornek: 'El actor joven fue la estrella de la noche.',
      ornekTr: 'Genç oyuncu gecenin yıldızıydı.',
      not: '"la estrella" yıldız demektir.',
    },
    {
      id: 'es-muz-83', on: 'entre bastidores', okunus: 'entre bastidores', tur: 'deyim',
      arka: 'perde arkasında',
      ornek: 'Se trabaja mucho entre bastidores.',
      ornekTr: 'Perde arkasında çok iş dönüyor.',
      not: '"los bastidores" kulis demektir.',
    },
    {
      id: 'es-muz-84', on: 'hacerse viral', okunus: 'aserse viral', tur: 'kalıp',
      arka: 'internette hızla yayılmak',
      ornek: 'Su vídeo se hizo viral en una noche.',
      ornekTr: 'Videosu bir gecede yayıldı.',
      not: '"hacerse" bir hâle gelmek demektir.',
    },
    {
      id: 'es-muz-85', on: 'dar la nota', okunus: 'dar la nota', tur: 'deyim',
      arka: 'dikkat çekmek (olumsuz)',
      ornek: 'Siempre da la nota en clase.',
      ornekTr: 'Sınıfta hep dikkat çekiyor.',
      not: 'Olumsuz bir anlam taşır; övgü değildir.',
    },
    {
      id: 'es-muz-86', on: 'poco a poco', okunus: 'poko a poko', tur: 'kalıp',
      arka: 'yavaş yavaş',
      ornek: 'Poco a poco me gustó la serie.',
      ornekTr: 'Yavaş yavaş dizi hoşuma gitti.',
      not: 'İkileme biçiminde çok kullanılan bir zarftır.',
    },
    {
      id: 'es-muz-87', on: 'por suerte', okunus: 'por suerte', tur: 'kalıp',
      arka: 'neyse ki',
      ornek: 'Por suerte hay una segunda temporada.',
      ornekTr: 'Neyse ki ikinci sezon var.',
      not: 'Karşıtı "por desgracia" = maalesef.',
    },
    {
      id: 'es-muz-88', on: 'por desgracia', okunus: 'por desgrasya', tur: 'kalıp',
      arka: 'maalesef',
      ornek: 'Por desgracia no tengo tiempo para series.',
      ornekTr: 'Maalesef dizilere vaktim yok.',
      not: '"la desgracia" talihsizlik demektir.',
    },
    {
      id: 'es-muz-89', on: 'por fin', okunus: 'por fin', tur: 'kalıp',
      arka: 'nihayet',
      ornek: 'Por fin sale el nuevo capítulo.',
      ornekTr: 'Nihayet yeni bölüm çıkıyor.',
      not: '"el fin" son demektir.',
    },
    {
      id: 'es-muz-90', on: 'de todos modos', okunus: 'de todos modos', tur: 'kalıp',
      arka: 'her hâlükârda',
      ornek: 'De todos modos, la veré esta noche.',
      ornekTr: 'Her hâlükârda bu akşam izleyeceğim.',
      not: '"el modo" biçim, yol demektir.',
    },
    /* --- Zevk konuşmaları --- */
    {
      id: 'es-muz-91', on: '¿Qué música escuchas?', okunus: 'ke musika eskuças', tur: 'soru kalıbı',
      arka: 'Ne müzik dinliyorsun?',
      ornek: '¿Qué música escuchas normalmente?',
      ornekTr: 'Genelde ne müzik dinliyorsun?',
      not: 'Tanışma konuşmalarının klasik sorusudur.',
    },
    {
      id: 'es-muz-92', on: '¿De qué va?', okunus: 'de ke va', tur: 'soru kalıbı',
      arka: 'Konusu ne?',
      ornek: '¿De qué va la película?',
      ornekTr: 'Filmin konusu ne?',
      not: '"ir de" bir konu hakkında olmak demektir.',
    },
    {
      id: 'es-muz-93', on: 'Depende', okunus: 'depende', tur: 'kalıp',
      arka: 'Duruma göre değişir',
      ornek: 'Depende de mi estado de ánimo.',
      ornekTr: 'Ruh hâlime göre değişir.',
      not: '"el estado de ánimo" ruh hâli demektir.',
    },
    {
      id: 'es-muz-94', on: 'más bien', okunus: 'mas byen', tur: 'kalıp',
      arka: 'daha çok, ziyade',
      ornek: 'Soy más bien de rock que de rap.',
      ornekTr: 'Ben rap\'ten çok rock severim.',
      not: 'Tercih belirtirken kullanılır.',
    },
    {
      id: 'es-muz-95', on: 'tener debilidad por', okunus: 'tener debilidad por', tur: 'deyim',
      arka: 'bir şeye zaafı olmak',
      ornek: 'Tengo debilidad por las películas antiguas.',
      ornekTr: 'Eski filmlere zaafım var.',
      not: '"débil" zayıf demektir.',
    },
    {
      id: 'es-muz-96', on: 'tener ganas de', okunus: 'tener ganas de', tur: 'kalıp',
      arka: 'canı istemek, sabırsızlanmak',
      ornek: 'Tengo ganas de ver la nueva temporada.',
      ornekTr: 'Yeni sezonu görmek için sabırsızlanıyorum.',
      not: 'Sonrasında mastar gelir.',
    },
    {
      id: 'es-muz-97', on: 'me recuerda a', okunus: 'me rekuerda a', tur: 'kalıp',
      arka: 'bana ... hatırlatıyor',
      ornek: 'Ese grupo me recuerda a uno turco.',
      ornekTr: 'O grup bana bir Türk grubunu hatırlatıyor.',
      not: 'Edatı "a"dır.',
      kok: 'recuerda',
    },
    {
      id: 'es-muz-98', on: 'el mismo que', okunus: 'el mismo ke', tur: 'kalıp',
      arka: 'aynısı',
      ornek: 'Tiene el mismo gusto que yo.',
      ornekTr: 'Zevki benimkiyle aynı.',
      not: 'Karşılaştırma edatı "que"dur.',
    },
    {
      id: 'es-muz-99', on: 'sin duda', okunus: 'sin duda', tur: 'kalıp',
      arka: 'kuşkusuz',
      ornek: 'Sin duda es su mejor disco.',
      ornekTr: 'Kuşkusuz en iyi albümü.',
      not: '"la duda" şüphe demektir.',
    },
    {
      id: 'es-muz-100', on: 'sobre gustos no hay nada escrito', okunus: 'sobre gustos no ay nada eskrito', tur: 'atasözü',
      arka: 'Zevkler ve renkler tartışılmaz',
      ornek: '¿No te gusta? Sobre gustos no hay nada escrito.',
      ornekTr: 'Sevmedin mi? Zevkler ve renkler tartışılmaz.',
      not: 'Kelimesi kelimesine "zevkler hakkında yazılmış bir şey yok" demektir.',
    },
  ],
}

export default DESTE
