/**
 * DESTE — SEYAHAT VE ŞEHİR (İspanyolca)
 *
 * İspanyolca dünyada en çok konuşulan ikinci ana dildir; bu destedeki
 * kelimeler yirmiden fazla ülkede işe yarar. Bölgesel farklar
 * (billete / boleto) not olarak gösterildi.
 */

export const DESTE = {
  id: 'seyahat',
  dil: 'es',
  ad: 'Seyahat ve şehir',
  simge: '✈️',
  aciklama: 'İstasyonda, otelde ve sokakta ilk saatte lazım olanlar.',
  seviye: 'A1–A2',
  kartlar: [
    {
      id: 'es-sey-01', on: 'el billete', okunus: 'el biyete', tur: 'isim (eril)',
      arka: 'bilet',
      ornek: 'Compré el billete por internet.',
      ornekTr: 'Bileti internetten aldım.',
      not: 'İspanya kullanımıdır. Latin Amerika\'da "el boleto" ya da "el pasaje".',
    },
    {
      id: 'es-sey-02', on: 'la estación', okunus: 'la estasyon', tur: 'isim (dişil)',
      arka: 'istasyon, gar',
      ornek: 'La estación está a diez minutos a pie.',
      ornekTr: 'İstasyon yürüyerek on dakika.',
      not: 'Çoğulu "las estaciones" — aksan düşer. Aynı kelime "mevsim" de demektir.',
    },
    {
      id: 'es-sey-03', on: 'el andén', okunus: 'el anden', tur: 'isim (eril)',
      arka: 'peron',
      ornek: 'El tren sale del andén número tres.',
      ornekTr: 'Tren üç numaralı perondan kalkıyor.',
      not: 'Anonslarda sürekli duyulur. Çoğulu "los andenes" (aksan düşer).',
    },
    {
      id: 'es-sey-04', on: 'la maleta', okunus: 'la maleta', tur: 'isim (dişil)',
      arka: 'valiz, bavul',
      ornek: 'Mi maleta pesa demasiado.',
      ornekTr: 'Valizim çok fazla ağır.',
      not: 'Sırt çantası "la mochila". Valiz hazırlamak "hacer la maleta".',
    },
    {
      id: 'es-sey-05', on: 'perderse', kok: 'perd', okunus: 'perderse', tur: 'fiil (dönüşlü)',
      arka: 'kaybolmak',
      ornek: 'Perdona, me he perdido.',
      ornekTr: 'Affedersin, kayboldum.',
      not: 'Dönüşlüdür: me pierdo. Eşya kaybetmek ise dönüşsüz "perder"dir.',
    },
    {
      id: 'es-sey-06', on: 'todo recto', okunus: 'todo rekto', tur: 'kalıp',
      arka: 'dümdüz',
      ornek: 'Siga todo recto hasta el semáforo.',
      ornekTr: 'Işıklara kadar dümdüz devam edin.',
      not: 'Latin Amerika\'da "todo derecho" da denir. Yol tarifinin ilk kalıbı.',
    },
    {
      id: 'es-sey-07', on: 'el albergue', okunus: 'el alberge', tur: 'isim (eril)',
      arka: 'hostel, gençlik yurdu',
      ornek: 'Dormimos en un albergue muy barato.',
      ornekTr: 'Çok ucuz bir hostelde kaldık.',
      not: 'Camino de Santiago yürüyüşünün klasik konaklamasıdır.',
    },
    {
      id: 'es-sey-08', on: 'reservar', okunus: 'reserbar', tur: 'fiil',
      arka: 'rezervasyon yaptırmak',
      ornek: 'He reservado una habitación para dos noches.',
      ornekTr: 'İki gecelik bir oda ayırttım.',
      not: 'Oda "la habitación", gece "la noche".',
    },
    {
      id: 'es-sey-09', on: 'el retraso', okunus: 'el retraso', tur: 'isim (eril)',
      arka: 'rötar, gecikme',
      ornek: 'El vuelo tiene dos horas de retraso.',
      ornekTr: 'Uçuşun iki saat rötarı var.',
      not: 'Uçuş "el vuelo". Geç kalmak "llegar tarde".',
    },
    {
      id: 'es-sey-10', on: '¿Cómo se llega a…?', kok: 'llega', okunus: 'komo se yega a', tur: 'kalıp',
      arka: '… nasıl gidilir?',
      ornek: 'Perdone, ¿cómo se llega a la catedral?',
      ornekTr: 'Affedersiniz, katedrale nasıl gidilir?',
      not: 'Yol sormanın en doğal biçimi; "¿Dónde está…?" yalnız yeri söyler.',
    },
    /* --- Trenle yolculuk --- */
    {
      id: 'es-sey-11', on: 'el tren', okunus: 'el tren', tur: 'isim (eril)',
      arka: 'tren',
      ornek: 'El tren sale a las diez.',
      ornekTr: 'Tren saat onda kalkıyor.',
      not: '"salir" çıkmak, kalkmak demektir.',
    },
    {
      id: 'es-sey-12', on: 'el AVE', okunus: 'el ave', tur: 'isim (eril)',
      arka: 'yüksek hızlı tren',
      ornek: 'El AVE llega a Sevilla en dos horas y media.',
      ornekTr: 'Hızlı tren Sevilla\'ya iki buçuk saatte varıyor.',
      not: '"Alta Velocidad Española" kısaltmasıdır.',
    },
    {
      id: 'es-sey-13', on: 'llegar', okunus: 'yegar', tur: 'fiil',
      arka: 'varmak',
      ornek: 'Llegamos a Madrid al mediodía.',
      ornekTr: 'Madrid\'e öğlen varıyoruz.',
      not: '"la llegada" varış demektir.',
    },
    {
      id: 'es-sey-14', on: 'el horario', okunus: 'el oraryo', tur: 'isim (eril)',
      arka: 'sefer tarifesi, saat çizelgesi',
      ornek: 'Mira el horario en la aplicación.',
      ornekTr: 'Sefer tarifesine uygulamadan bak.',
      not: '"la hora" saat demektir.',
    },
    {
      id: 'es-sey-15', on: 'subir al tren', okunus: 'subir al tren', tur: 'kalıp',
      arka: 'trene binmek',
      ornek: 'Subimos al tren en Valencia.',
      ornekTr: 'Trene Valensiya\'da biniyoruz.',
      not: 'İnmek "bajar del tren"dir.',
    },
    {
      id: 'es-sey-16', on: 'el revisor', okunus: 'el revisor', tur: 'isim (eril)',
      arka: 'kondüktör',
      ornek: 'El revisor comprueba los billetes.',
      ornekTr: 'Kondüktör biletleri kontrol ediyor.',
      not: '"comprobar" doğrulamak demektir.',
    },
    {
      id: 'es-sey-17', on: 'el asiento', okunus: 'el asyento', tur: 'isim (eril)',
      arka: 'koltuk',
      ornek: '¿Está libre este asiento?',
      ornekTr: 'Bu koltuk boş mu?',
      not: '"libre" boş, serbest demektir.',
    },
    {
      id: 'es-sey-18', on: 'el trayecto', okunus: 'el trayekto', tur: 'isim (eril)',
      arka: 'yolculuk, güzergâh',
      ornek: 'El trayecto dura tres horas.',
      ornekTr: 'Yolculuk üç saat sürüyor.',
      not: '"durar" sürmek demektir.',
    },
    {
      id: 'es-sey-19', on: 'ida o ida y vuelta', okunus: 'ida o ida i vuelta', tur: 'kalıp',
      arka: 'tek yön mü gidiş-dönüş mü',
      ornek: '¿Ida o ida y vuelta? - Ida y vuelta, por favor.',
      ornekTr: 'Tek yön mü gidiş-dönüş mü? - Gidiş-dönüş lütfen.',
      not: 'Gişede sorulan standart sorudur.',
    },
    {
      id: 'es-sey-20', on: 'perder el tren', okunus: 'perder el tren', tur: 'kalıp',
      arka: 'treni kaçırmak',
      ornek: 'Casi perdemos el tren.',
      ornekTr: 'Neredeyse treni kaçırıyorduk.',
      not: '"casi" neredeyse demektir.',
    },
    /* --- Şehir içi ulaşım --- */
    {
      id: 'es-sey-21', on: 'el metro', okunus: 'el metro', tur: 'isim (eril)',
      arka: 'metro',
      ornek: 'Coge el metro, es más rápido.',
      ornekTr: 'Metroya bin, daha hızlı.',
      not: 'İspanya\'da "coger", Latin Amerika\'da "tomar" kullanılır.',
    },
    {
      id: 'es-sey-22', on: 'la parada', okunus: 'la parada', tur: 'isim (dişil)',
      arka: 'durak',
      ornek: 'Bájate en la tercera parada.',
      ornekTr: 'Üçüncü durakta in.',
      not: '"parar" durmak demektir.',
    },
    {
      id: 'es-sey-23', on: 'a pie', okunus: 'a pye', tur: 'kalıp',
      arka: 'yürüyerek',
      ornek: 'Está a diez minutos a pie.',
      ornekTr: 'Yürüyerek on dakika.',
      not: 'Diğer araçlar "en" alır: en autobús, en coche.',
    },
    {
      id: 'es-sey-24', on: 'el atasco', okunus: 'el atasko', tur: 'isim (eril)',
      arka: 'trafik sıkışıklığı',
      ornek: 'Estamos en un atasco desde hace una hora.',
      ornekTr: 'Bir saattir trafikte sıkıştık.',
      not: '"atascarse" tıkanmak demektir.',
    },
    {
      id: 'es-sey-25', on: 'la hora punta', okunus: 'la ora punta', tur: 'isim (dişil)',
      arka: 'yoğun saat',
      ornek: 'Evita el metro en hora punta.',
      ornekTr: 'Yoğun saatte metroya binme.',
      not: '"la punta" uç, zirve demektir.',
    },
    {
      id: 'es-sey-26', on: 'coger un taxi', okunus: 'koher un taksi', tur: 'kalıp',
      arka: 'taksiye binmek',
      ornek: 'Si llueve, cogemos un taxi.',
      ornekTr: 'Yağmur yağarsa taksiye biniyoruz.',
      not: 'Latin Amerika\'da "tomar un taxi" denir.',
    },
    {
      id: 'es-sey-27', on: 'acercar a alguien', okunus: 'aserkar a algyen', tur: 'kalıp',
      arka: 'birini bir yere bırakmak',
      ornek: '¿Me puedes acercar al instituto?',
      ornekTr: 'Beni liseye bırakabilir misin?',
      not: '"cerca" yakın demektir.',
    },
    {
      id: 'es-sey-28', on: 'la tarifa', okunus: 'la tarifa', tur: 'isim (dişil)',
      arka: 'ücret, tarife',
      ornek: 'La tarifa de estudiante es más barata.',
      ornekTr: 'Öğrenci ücreti daha ucuz.',
      not: '"barato" ucuz demektir.',
    },
    {
      id: 'es-sey-29', on: 'el autobús', okunus: 'el autobus', tur: 'isim (eril)',
      arka: 'otobüs',
      ornek: 'El autobús pasa cada quince minutos.',
      ornekTr: 'Otobüs on beş dakikada bir geçiyor.',
      not: 'Kısaca "el bus" da denir.',
    },
    {
      id: 'es-sey-30', on: 'el transporte público', okunus: 'el transporte publiko', tur: 'isim (eril)',
      arka: 'toplu taşıma',
      ornek: 'El transporte público es muy bueno aquí.',
      ornekTr: 'Buradaki toplu taşıma çok iyi.',
      not: '"público" kamusal demektir.',
    },
    /* --- Havaalanı --- */
    {
      id: 'es-sey-31', on: 'el aeropuerto', okunus: 'el aeropuerto', tur: 'isim (eril)',
      arka: 'havalimanı',
      ornek: 'Llegamos al aeropuerto dos horas antes.',
      ornekTr: 'Havalimanına iki saat önce varıyoruz.',
      not: '"el puerto" liman demektir.',
    },
    {
      id: 'es-sey-32', on: 'el vuelo', okunus: 'el vuelo', tur: 'isim (eril)',
      arka: 'uçuş',
      ornek: 'El vuelo dura tres horas.',
      ornekTr: 'Uçuş üç saat sürüyor.',
      not: '"volar" uçmak demektir.',
    },
    {
      id: 'es-sey-33', on: 'facturar', okunus: 'fakturar', tur: 'fiil',
      arka: 'bagaj vermek, check-in yapmak',
      ornek: 'Tengo que facturar la maleta.',
      ornekTr: 'Valizi bagaja vermem gerekiyor.',
      not: '"la factura" fatura demektir; havaalanında farklı anlam taşır.',
    },
    {
      id: 'es-sey-34', on: 'la tarjeta de embarque', okunus: 'la tarheta de embarke', tur: 'isim (dişil)',
      arka: 'biniş kartı',
      ornek: 'Guarda tu tarjeta de embarque.',
      ornekTr: 'Biniş kartını sakla.',
      not: '"embarcar" binmek (uçak, gemi) demektir.',
    },
    {
      id: 'es-sey-35', on: 'el equipaje de mano', okunus: 'el ekipahe de mano', tur: 'isim (eril)',
      arka: 'el bagajı',
      ornek: 'Solo viajo con equipaje de mano.',
      ornekTr: 'Sadece el bagajıyla seyahat ediyorum.',
      not: '"la mano" el demektir.',
    },
    {
      id: 'es-sey-36', on: 'la aduana', okunus: 'la aduana', tur: 'isim (dişil)',
      arka: 'gümrük',
      ornek: 'Pasamos la aduana rápido.',
      ornekTr: 'Gümrükten hızlıca geçtik.',
      not: 'Arapça kökenli bir kelimedir.',
    },
    {
      id: 'es-sey-37', on: 'el pasaporte', okunus: 'el pasaporte', tur: 'isim (eril)',
      arka: 'pasaport',
      ornek: 'Mi pasaporte sigue siendo válido.',
      ornekTr: 'Pasaportum hâlâ geçerli.',
      not: '"válido" geçerli demektir.',
    },
    {
      id: 'es-sey-38', on: 'la puerta de embarque', okunus: 'la puerta de embarke', tur: 'isim (dişil)',
      arka: 'biniş kapısı',
      ornek: 'La puerta de embarque cierra veinte minutos antes.',
      ornekTr: 'Biniş kapısı yirmi dakika önce kapanıyor.',
      not: '"cerrar" kapanmak demektir.',
    },
    {
      id: 'es-sey-39', on: 'despegar', okunus: 'despegar', tur: 'fiil',
      arka: 'havalanmak',
      ornek: 'El avión despega a la hora prevista.',
      ornekTr: 'Uçak planlanan saatte havalanıyor.',
      not: 'İnmek "aterrizar"dır; "la tierra" toprak demektir.',
    },
    {
      id: 'es-sey-40', on: 'el jet lag', okunus: 'el yet lag', tur: 'isim (eril)',
      arka: 'saat farkı yorgunluğu',
      ornek: 'Tuve jet lag durante tres días.',
      ornekTr: 'Üç gün saat farkı yorgunluğu yaşadım.',
      not: 'İngilizceden alınmıştır; "el desfase horario" da denir.',
    },
    /* --- Konaklama --- */
    {
      id: 'es-sey-41', on: 'el alojamiento', okunus: 'el alohamyento', tur: 'isim (eril)',
      arka: 'konaklama',
      ornek: 'El alojamiento era limpio y barato.',
      ornekTr: 'Konaklama temiz ve ucuzdu.',
      not: '"alojarse" konaklamak demektir.',
    },
    {
      id: 'es-sey-42', on: 'la habitación doble', okunus: 'la abitasyon doble', tur: 'isim (dişil)',
      arka: 'iki kişilik oda',
      ornek: 'Queríamos una habitación doble.',
      ornekTr: 'İki kişilik bir oda istiyorduk.',
      not: 'Tek kişilik "individual"dır.',
    },
    {
      id: 'es-sey-43', on: 'desayuno incluido', okunus: 'desayuno inkluido', tur: 'kalıp',
      arka: 'kahvaltı dâhil',
      ornek: '¿El precio es con desayuno incluido?',
      ornekTr: 'Fiyata kahvaltı dâhil mi?',
      not: '"incluir" içermek demektir.',
    },
    {
      id: 'es-sey-44', on: 'la recepción', okunus: 'la resepsyon', tur: 'isim (dişil)',
      arka: 'resepsiyon',
      ornek: 'La llave está en la recepción.',
      ornekTr: 'Anahtar resepsiyonda.',
      not: '"la llave" anahtar demektir.',
    },
    {
      id: 'es-sey-45', on: 'completo', okunus: 'kompleto', tur: 'sıfat',
      arka: 'dolu',
      ornek: 'El hotel está completo en agosto.',
      ornekTr: 'Otel ağustosta dolu.',
      not: 'Restoran ve otobüs için de kullanılır.',
    },
    {
      id: 'es-sey-46', on: 'cancelar', okunus: 'kanselar', tur: 'fiil',
      arka: 'iptal etmek',
      ornek: 'Quisiera cancelar la reserva.',
      ornekTr: 'Rezervasyonu iptal etmek istiyorum.',
      not: '"quisiera" en kibar istek biçimidir.',
    },
    {
      id: 'es-sey-47', on: 'la señal', okunus: 'la senyal', tur: 'isim (dişil)',
      arka: 'kapora; işaret',
      ornek: 'Piden una señal por adelantado.',
      ornekTr: 'Peşin kapora istiyorlar.',
      not: '"por adelantado" peşin demektir.',
    },
    {
      id: 'es-sey-48', on: 'el apartamento', okunus: 'el apartamento', tur: 'isim (eril)',
      arka: 'kiralık daire',
      ornek: 'Alquilamos un apartamento en la playa.',
      ornekTr: 'Plajda bir daire kiraladık.',
      not: '"alquilar" kiralamak demektir.',
    },
    {
      id: 'es-sey-49', on: 'la fianza', okunus: 'la fyansa', tur: 'isim (dişil)',
      arka: 'depozito',
      ornek: 'Hay que dejar una fianza.',
      ornekTr: 'Depozito bırakmak gerekiyor.',
      not: 'Ev kiralarken de aynı kelime kullanılır.',
    },
    {
      id: 'es-sey-50', on: 'la casa rural', okunus: 'la kasa rural', tur: 'isim (dişil)',
      arka: 'kırsal konaklama evi',
      ornek: 'Pasamos el fin de semana en una casa rural.',
      ornekTr: 'Hafta sonunu bir kır evinde geçirdik.',
      not: 'İspanya\'da çok yaygın bir tatil biçimidir.',
    },
    /* --- Yol tarifi --- */
    {
      id: 'es-sey-51', on: 'el cruce', okunus: 'el kruse', tur: 'isim (eril)',
      arka: 'kavşak',
      ornek: 'Gira a la derecha en el cruce.',
      ornekTr: 'Kavşaktan sağa dön.',
      not: '"cruzar" geçmek, kesişmek demektir.',
    },
    {
      id: 'es-sey-52', on: 'el semáforo', okunus: 'el semaforo', tur: 'isim (eril)',
      arka: 'trafik ışığı',
      ornek: 'Gira a la izquierda en el semáforo.',
      ornekTr: 'Trafik ışığından sola dön.',
      not: 'Türkçedeki "semafor" bu kelimeden gelir.',
    },
    {
      id: 'es-sey-53', on: 'enfrente de', okunus: 'enfrente de', tur: 'kalıp',
      arka: 'karşısında',
      ornek: 'El banco está enfrente de correos.',
      ornekTr: 'Banka postanenin karşısında.',
      not: '"correos" postane demektir.',
    },
    {
      id: 'es-sey-54', on: 'cerca de / lejos de', okunus: 'serka de / lehos de', tur: 'kalıp',
      arka: 'yakınında / uzağında',
      ornek: 'El hotel está cerca del museo.',
      ornekTr: 'Otel müzenin yakınında.',
      not: '"de + el" birleşip "del" olur.',
    },
    {
      id: 'es-sey-55', on: 'la esquina', okunus: 'la eskina', tur: 'isim (dişil)',
      arka: 'köşe',
      ornek: 'La farmacia está en la esquina.',
      ornekTr: 'Eczane köşede.',
      not: '"la farmacia" eczane demektir.',
    },
    {
      id: 'es-sey-56', on: 'el plano', okunus: 'el plano', tur: 'isim (eril)',
      arka: 'şehir haritası',
      ornek: '¿Tienes un plano de la ciudad?',
      ornekTr: 'Şehir haritan var mı?',
      not: '"el mapa" genel harita, "el plano" şehir planıdır.',
    },
    {
      id: 'es-sey-57', on: 'el paso de peatones', okunus: 'el paso de peatones', tur: 'isim (eril)',
      arka: 'yaya geçidi',
      ornek: 'Cruza por el paso de peatones.',
      ornekTr: 'Yaya geçidinden geç.',
      not: '"el peatón" yaya demektir.',
    },
    {
      id: 'es-sey-58', on: '¿Está lejos?', okunus: 'esta lehos', tur: 'soru kalıbı',
      arka: 'Uzak mı?',
      ornek: '¿Está lejos la playa de aquí?',
      ornekTr: 'Plaj buradan uzak mı?',
      not: 'Cevabı "a diez minutos" gibi verilir.',
    },
    {
      id: 'es-sey-59', on: 'seguir recto', okunus: 'segir rekto', tur: 'kalıp',
      arka: 'dümdüz devam etmek',
      ornek: 'Sigue recto doscientos metros.',
      ornekTr: 'İki yüz metre dümdüz devam et.',
      not: '"seguir" devam etmek demektir.',
      kok: 'sigue',
    },
    {
      id: 'es-sey-60', on: 'preguntar el camino', okunus: 'pregundar el kamino', tur: 'kalıp',
      arka: 'yol sormak',
      ornek: 'Vamos a preguntar el camino.',
      ornekTr: 'Yolu soralım.',
      not: '"el camino" yol demektir.',
    },
    /* --- Tatil ve gezi --- */
    {
      id: 'es-sey-61', on: 'las vacaciones', okunus: 'las vakasyones', tur: 'isim (çoğul)',
      arka: 'tatil',
      ornek: 'Nos vamos de vacaciones en julio.',
      ornekTr: 'Temmuzda tatile gidiyoruz.',
      not: 'Her zaman çoğuldur: "irse de vacaciones".',
    },
    {
      id: 'es-sey-62', on: 'la excursión', okunus: 'la ekskursyon', tur: 'isim (dişil)',
      arka: 'günübirlik gezi',
      ornek: 'Hicimos una excursión al lago.',
      ornekTr: 'Göle günübirlik bir gezi yaptık.',
      not: 'Fiili "hacer"dır.',
    },
    {
      id: 'es-sey-63', on: 'visitar', okunus: 'visitar', tur: 'fiil',
      arka: 'gezmek, ziyaret etmek',
      ornek: 'Mañana visitamos el castillo.',
      ornekTr: 'Yarın kaleyi geziyoruz.',
      not: 'Hem yer hem kişi için kullanılır.',
    },
    {
      id: 'es-sey-64', on: 'la visita guiada', okunus: 'la visita giyada', tur: 'isim (dişil)',
      arka: 'rehberli tur',
      ornek: 'La visita guiada dura una hora.',
      ornekTr: 'Rehberli tur bir saat sürüyor.',
      not: '"el guía" rehber demektir.',
    },
    {
      id: 'es-sey-65', on: 'la entrada', okunus: 'la entrada', tur: 'isim (dişil)',
      arka: 'giriş; bilet',
      ornek: 'La entrada es gratis para estudiantes.',
      ornekTr: 'Giriş öğrenciler için ücretsiz.',
      not: 'Konser bileti için de aynı kelime kullanılır.',
    },
    {
      id: 'es-sey-66', on: 'el senderismo', okunus: 'el senderismo', tur: 'isim (eril)',
      arka: 'doğa yürüyüşü',
      ornek: 'Hacemos senderismo en la montaña.',
      ornekTr: 'Dağda doğa yürüyüşü yapıyoruz.',
      not: '"el sendero" patika demektir.',
    },
    {
      id: 'es-sey-67', on: 'el recuerdo', okunus: 'el rekuerdo', tur: 'isim (eril)',
      arka: 'hatıra, hediyelik eşya',
      ornek: 'Compré un pequeño recuerdo.',
      ornekTr: 'Küçük bir hediyelik aldım.',
      not: '"recordar" hatırlamak demektir.',
    },
    {
      id: 'es-sey-68', on: 'la postal', okunus: 'la postal', tur: 'isim (dişil)',
      arka: 'kartpostal',
      ornek: 'Te mando una postal desde Granada.',
      ornekTr: 'Sana Granada\'dan bir kartpostal gönderiyorum.',
      not: '"mandar" göndermek demektir.',
    },
    {
      id: 'es-sey-69', on: 'la temporada alta', okunus: 'la temporada alta', tur: 'isim (dişil)',
      arka: 'yoğun sezon',
      ornek: 'Los precios suben en temporada alta.',
      ornekTr: 'Fiyatlar yoğun sezonda artıyor.',
      not: 'Sakin dönem "la temporada baja"dır.',
    },
    {
      id: 'es-sey-70', on: 'viajar ligero', okunus: 'vyahar lihero', tur: 'kalıp',
      arka: 'az eşyayla seyahat etmek',
      ornek: 'Siempre viajo ligero.',
      ornekTr: 'Her zaman az eşyayla seyahat ederim.',
      not: '"ligero" hafif demektir.',
    },
    /* --- Sorunlar --- */
    {
      id: 'es-sey-71', on: 'los objetos perdidos', okunus: 'los obhetos perdidos', tur: 'isim (çoğul)',
      arka: 'kayıp eşya bürosu',
      ornek: 'Pregunta en objetos perdidos.',
      ornekTr: 'Kayıp eşya bürosuna sor.',
      not: 'Kelimesi kelimesine "kayıp nesneler" demektir.',
    },
    {
      id: 'es-sey-72', on: 'robar', okunus: 'robar', tur: 'fiil',
      arka: 'çalmak',
      ornek: 'Me robaron el móvil en el metro.',
      ornekTr: 'Metroda telefonumu çaldılar.',
      not: 'İspanyolcada özne belirtilmeden çoğul çekim kullanılır.',
    },
    {
      id: 'es-sey-73', on: 'el seguro de viaje', okunus: 'el seguro de vyahe', tur: 'isim (eril)',
      arka: 'seyahat sigortası',
      ornek: 'Contrata un seguro de viaje.',
      ornekTr: 'Seyahat sigortası yaptır.',
      not: '"seguro" hem sigorta hem "emin" demektir.',
    },
    {
      id: 'es-sey-74', on: 'la emergencia', okunus: 'la emerhensya', tur: 'isim (dişil)',
      arka: 'acil durum',
      ornek: 'En caso de emergencia, llama al 112.',
      ornekTr: 'Acil durumda 112\'yi ara.',
      not: 'İspanya\'da acil numara 112\'dir.',
    },
    {
      id: 'es-sey-75', on: 'averiarse', okunus: 'averyarse', tur: 'fiil (dönüşlü)',
      arka: 'bozulmak (araç)',
      ornek: 'El coche se averió en la autopista.',
      ornekTr: 'Araba otoyolda bozuldu.',
      not: '"la avería" arıza demektir. Geçmiş hâli: se averió.',
      kok: 'averió',
    },
    {
      id: 'es-sey-76', on: 'quejarse de', okunus: 'keharse de', tur: 'fiil (dönüşlü)',
      arka: 'şikâyet etmek',
      ornek: 'Nos quejamos del ruido.',
      ornekTr: 'Gürültüden şikâyet ettik.',
      not: '"la queja" şikâyet demektir.',
    },
    {
      id: 'es-sey-77', on: 'tener cuidado con', okunus: 'tener kuidado kon', tur: 'kalıp',
      arka: 'dikkat etmek',
      ornek: 'Ten cuidado con los carteristas.',
      ornekTr: 'Yankesicilere dikkat et.',
      not: '"el carterista" yankesici demektir.',
    },
    {
      id: 'es-sey-78', on: 'la información', okunus: 'la informasyon', tur: 'isim (dişil)',
      arka: 'danışma, bilgi',
      ornek: 'Pregunta en información por el andén.',
      ornekTr: 'Peronu danışmaya sor.',
      not: '"el andén" peron demektir.',
    },
    {
      id: 'es-sey-79', on: 'resolver un problema', okunus: 'resolver un problema', tur: 'kalıp',
      arka: 'sorunu çözmek',
      ornek: 'Resolvieron el problema enseguida.',
      ornekTr: 'Sorunu hemen çözdüler.',
      not: '"enseguida" hemen demektir.',
    },
    {
      id: 'es-sey-80', on: 'echar una mano', okunus: 'eçar una mano', tur: 'deyim',
      arka: 'el atmak, yardım etmek',
      ornek: '¿Me echas una mano con la maleta?',
      ornekTr: 'Valize bir el atar mısın?',
      not: 'Kelimesi kelimesine "bir el atmak" demektir.',
    },
    /* --- Şehir ve mekân --- */
    {
      id: 'es-sey-81', on: 'el centro', okunus: 'el sentro', tur: 'isim (eril)',
      arka: 'şehir merkezi',
      ornek: 'Nuestro hotel está en el centro.',
      ornekTr: 'Otelimiz merkezde.',
      not: '"el centro de la ciudad" de denir.',
    },
    {
      id: 'es-sey-82', on: 'las afueras', okunus: 'las afueras', tur: 'isim (çoğul)',
      arka: 'şehrin dışı',
      ornek: 'Viven en las afueras.',
      ornekTr: 'Şehrin dışında oturuyorlar.',
      not: '"fuera" dışarı demektir.',
    },
    {
      id: 'es-sey-83', on: 'el casco antiguo', okunus: 'el kasko antiguo', tur: 'isim (eril)',
      arka: 'tarihî şehir merkezi',
      ornek: 'El casco antiguo es precioso.',
      ornekTr: 'Tarihî merkez çok güzel.',
      not: 'İspanyol şehirlerinin klasik gezi noktasıdır.',
    },
    {
      id: 'es-sey-84', on: 'abarrotado', okunus: 'abarrotado', tur: 'sıfat',
      arka: 'tıklım tıklım',
      ornek: 'El mercado estaba abarrotado.',
      ornekTr: 'Pazar tıklım tıklımdı.',
      not: 'Metro ve otobüs için de kullanılır.',
    },
    {
      id: 'es-sey-85', on: 'animado', okunus: 'animado', tur: 'sıfat',
      arka: 'hareketli, canlı',
      ornek: 'Este barrio es muy animado por la noche.',
      ornekTr: 'Bu mahalle geceleri çok hareketli.',
      not: '"el barrio" mahalle demektir.',
    },
    {
      id: 'es-sey-86', on: 'el paisaje', okunus: 'el paysahe', tur: 'isim (eril)',
      arka: 'manzara',
      ornek: 'El paisaje del camino era impresionante.',
      ornekTr: 'Yoldaki manzara etkileyiciydi.',
      not: '"impresionante" etkileyici demektir.',
    },
    {
      id: 'es-sey-87', on: 'las vistas', okunus: 'las vistas', tur: 'isim (çoğul)',
      arka: 'manzara (pencereden)',
      ornek: 'La habitación tiene vistas al mar.',
      ornekTr: 'Odanın deniz manzarası var.',
      not: 'Çoğul kullanılır: vistas al mar.',
    },
    {
      id: 'es-sey-88', on: 'merecer la pena', okunus: 'mereser la pena', tur: 'deyim',
      arka: 'değmek',
      ornek: 'Ese pueblo merece la pena.',
      ornekTr: 'O kasaba gidip görmeye değer.',
      not: '"el pueblo" köy, kasaba demektir.',
    },
    {
      id: 'es-sey-89', on: 'pasear', okunus: 'pasear', tur: 'fiil',
      arka: 'gezinmek',
      ornek: 'Paseamos todo el día por la ciudad.',
      ornekTr: 'Bütün gün şehirde gezindik.',
      not: '"el paseo" gezinti demektir.',
    },
    {
      id: 'es-sey-90', on: 'perderse', okunus: 'perderse', tur: 'fiil (dönüşlü)',
      arka: 'kaybolmak',
      ornek: 'Nos perdimos en el casco antiguo.',
      ornekTr: 'Tarihî merkezde kaybolduk.',
      not: 'Aynı fiil "bir şeyi kaçırmak" anlamına da gelir. Geçmiş hâli: nos perdimos.',
      kok: 'perdimos',
    },
    /* --- Yolculuk kalıpları --- */
    {
      id: 'es-sey-91', on: '¡Buen viaje!', okunus: 'buen vyahe', tur: 'kalıp',
      arka: 'İyi yolculuklar!',
      ornek: '¡Buen viaje y avísame al llegar!',
      ornekTr: 'İyi yolculuklar, varınca haber ver!',
      not: '"avisar" haber vermek demektir.',
    },
    {
      id: 'es-sey-92', on: '¿Dónde está...?', okunus: 'donde esta', tur: 'soru kalıbı',
      arka: '... nerede?',
      ornek: '¿Dónde está la parada más cercana?',
      ornekTr: 'En yakın durak nerede?',
      not: '"cercano" yakın demektir.',
    },
    {
      id: 'es-sey-93', on: '¿Me puede ayudar?', okunus: 'me puede ayudar', tur: 'soru kalıbı',
      arka: 'Bana yardım edebilir misiniz?',
      ornek: 'Perdone, ¿me puede ayudar?',
      ornekTr: 'Affedersiniz, bana yardım edebilir misiniz?',
      not: '"perdone" resmî af dileme biçimidir.',
    },
    {
      id: 'es-sey-94', on: 'No entiendo', okunus: 'no entyendo', tur: 'kalıp',
      arka: 'Anlamıyorum',
      ornek: 'Lo siento, no entiendo.',
      ornekTr: 'Üzgünüm, anlamıyorum.',
      not: 'Ardından "¿Puede repetir?" denebilir.',
      kok: 'entiendo',
    },
    {
      id: 'es-sey-95', on: '¿Habla inglés?', okunus: 'abla ingles', tur: 'soru kalıbı',
      arka: 'İngilizce biliyor musunuz?',
      ornek: 'Perdone, ¿habla inglés?',
      ornekTr: 'Affedersiniz, İngilizce biliyor musunuz?',
      not: 'Dil adları küçük harfle yazılır.',
    },
    {
      id: 'es-sey-96', on: '¿Cuánto se tarda?', okunus: 'kuanto se tarda', tur: 'soru kalıbı',
      arka: 'Ne kadar sürüyor?',
      ornek: '¿Cuánto se tarda en autobús?',
      ornekTr: 'Otobüsle ne kadar sürüyor?',
      not: '"tardar" zaman almak demektir.',
    },
    {
      id: 'es-sey-97', on: 'Quisiera...', okunus: 'kisyera', tur: 'kalıp',
      arka: '... istiyorum (kibar)',
      ornek: 'Quisiera un billete para Barcelona.',
      ornekTr: 'Barselona\'ya bir bilet istiyorum.',
      not: 'Gişede ve restoranda en kibar istek biçimidir.',
    },
    {
      id: 'es-sey-98', on: '¡Que tengas buen viaje!', okunus: 'ke tengas buen vyahe', tur: 'kalıp',
      arka: 'İyi yolculuklar dilerim!',
      ornek: '¡Que tengas buen viaje y disfrutes!',
      ornekTr: 'İyi yolculuklar, iyi eğlenceler!',
      not: '"disfrutar" keyfini çıkarmak demektir.',
    },
    {
      id: 'es-sey-99', on: '¿De dónde eres?', okunus: 'de donde eres', tur: 'soru kalıbı',
      arka: 'Nerelisin?',
      ornek: '¿De dónde eres exactamente?',
      ornekTr: 'Tam olarak nerelisin?',
      not: 'Resmî hâli "¿De dónde es usted?"tir.',
    },
    {
      id: 'es-sey-100', on: 'Quien va a Sevilla pierde su silla', okunus: 'kyen va a sevilya pyerde su siya', tur: 'atasözü',
      arka: 'Yerinden kalkan yerini kaybeder',
      ornek: 'Te levantaste: quien va a Sevilla pierde su silla.',
      ornekTr: 'Kalktın: yerinden kalkan yerini kaybeder.',
      not: 'Kafiyeli ve şakacı bir İspanyol atasözüdür.',
    },
  ],
}

export default DESTE
