/**
 * DESTE — YEMEK VE TATLAR (İspanyolca)
 *
 * İspanyol mutfağı kelimeleri Türkçeye de geçmiştir (paella, tapas) ama
 * yanlış sesle. Kartlarda okunuş ayrıca verildi. Ayrıca yemek yorumunun
 * "estar" ile yapıldığı her fırsatta hatırlatıldı.
 */

export const DESTE = {
  id: 'yemek',
  dil: 'es',
  ad: 'Yemek ve tatlar',
  simge: '🥘',
  aciklama: 'Barda, restoranda ve sofrada geçen kelimeler.',
  seviye: 'A1–A2',
  kartlar: [
    {
      id: 'es-yem-01', on: 'el desayuno', okunus: 'el desayuno', tur: 'isim (eril)',
      arka: 'kahvaltı',
      ornek: 'El desayuno más importante es el del domingo.',
      ornekTr: 'En önemli kahvaltı pazar kahvaltısıdır.',
      not: 'Fiili "desayunar"dır ve tek kelimedir.',
    },
    {
      id: 'es-yem-02', on: 'las tapas', okunus: 'las tapas', tur: 'isim (çoğul)',
      arka: 'küçük atıştırmalıklar',
      ornek: 'Vamos a tomar unas tapas antes de cenar.',
      ornekTr: 'Akşam yemeğinden önce biraz tapas yiyelim.',
      not: 'İspanya kültürünün merkezinde; "ir de tapas" bir sosyal etkinliktir.',
    },
    {
      id: 'es-yem-03', on: 'la paella', okunus: 'la paeya', tur: 'isim (dişil)',
      arka: 'paella (pirinçli yemek)',
      ornek: 'La paella está buenísima.',
      ornekTr: 'Paella çok lezzetli olmuş.',
      not: '"ll" → "y" okunur: "paeya". Yemek yorumu "estar" ile yapılır.',
    },
    {
      id: 'es-yem-04', on: 'tener hambre', kok: 'hambre', okunus: 'tener ambre', tur: 'kalıp',
      arka: 'acıkmak, aç olmak',
      ornek: 'Tengo hambre, ¿comemos algo?',
      ornekTr: 'Acıktım, bir şeyler yiyelim mi?',
      not: '"Soy hambre" ya da "Estoy hambre" YANLIŞTIR. Açlık "tener" ile kurulur.',
    },
    {
      id: 'es-yem-05', on: 'estar buenísimo', kok: 'buenísimo', okunus: 'estar buenisimo', tur: 'kalıp',
      arka: 'çok lezzetli olmak',
      ornek: 'Este pastel está buenísimo.',
      ornekTr: 'Bu pasta çok lezzetli.',
      not: '-ísimo eki "çok" anlamı katar ve İspanyolcada çok kullanılır.',
    },
    {
      id: 'es-yem-06', on: 'la cuenta', okunus: 'la kuenta', tur: 'isim (dişil)',
      arka: 'hesap (restoranda)',
      ornek: 'La cuenta, por favor.',
      ornekTr: 'Hesap, lütfen.',
      not: 'En kibar biçim budur; "Quiero la cuenta" biraz sert durur.',
    },
    {
      id: 'es-yem-07', on: 'probar', okunus: 'probar', tur: 'fiil (kök değişimli)',
      arka: 'tatmak, denemek',
      ornek: '¿Quieres probar mi helado?',
      ornekTr: 'Dondurmamı tatmak ister misin?',
      not: 'Kök değişir: pruebo, pruebas… Dondurma "el helado".',
    },
    {
      id: 'es-yem-08', on: 'para llevar', okunus: 'para yebar', tur: 'kalıp',
      arka: 'paket, götürmek için',
      ornek: 'Un café para llevar, por favor.',
      ornekTr: 'Bir kahve paket, lütfen.',
      not: 'Karşıtı "para tomar aquí" (burada içmek için).',
    },
    {
      id: 'es-yem-09', on: 'tener sed', kok: 'sed', okunus: 'tener sed', tur: 'kalıp',
      arka: 'susamak',
      ornek: 'Tengo sed, voy a beber agua.',
      ornekTr: 'Susadım, su içeceğim.',
      not: '"tener hambre" ile aynı mantık: susuzluğa da sahip olunur.',
    },
    {
      id: 'es-yem-10', on: '¡Que aproveche!', kok: 'aproveche', okunus: 'ke aproveçe', tur: 'kalıp',
      arka: 'Afiyet olsun!',
      ornek: 'Aquí tienes tu plato. ¡Que aproveche!',
      ornekTr: 'Buyur tabağın. Afiyet olsun!',
      not: 'Latin Amerika\'da "¡Buen provecho!" daha yaygındır.',
    },
    /* --- Temel yiyecekler --- */
    {
      id: 'es-yem-11', on: 'el pan', okunus: 'el pan', tur: 'isim (eril)',
      arka: 'ekmek',
      ornek: 'Compramos pan fresco cada mañana.',
      ornekTr: 'Her sabah taze ekmek alıyoruz.',
      not: '"fresco" taze demektir.',
    },
    {
      id: 'es-yem-12', on: 'el queso', okunus: 'el keso', tur: 'isim (eril)',
      arka: 'peynir',
      ornek: 'El queso manchego es muy conocido.',
      ornekTr: 'Manchego peyniri çok tanınmıştır.',
      not: 'Manchego İspanya\'nın en ünlü peyniridir.',
    },
    {
      id: 'es-yem-13', on: 'el aceite de oliva', okunus: 'el aseyte de oliva', tur: 'isim (eril)',
      arka: 'zeytinyağı',
      ornek: 'Usamos aceite de oliva para todo.',
      ornekTr: 'Her şey için zeytinyağı kullanıyoruz.',
      not: 'İspanya dünyanın en büyük zeytinyağı üreticisidir.',
    },
    {
      id: 'es-yem-14', on: 'la carne', okunus: 'la karne', tur: 'isim (dişil)',
      arka: 'et',
      ornek: 'Como poca carne.',
      ornekTr: 'Az et yiyorum.',
      not: '"poco" az demektir.',
    },
    {
      id: 'es-yem-15', on: 'el pescado', okunus: 'el peskado', tur: 'isim (eril)',
      arka: 'balık (yemek olarak)',
      ornek: 'El pescado está muy fresco aquí.',
      ornekTr: 'Balık burada çok taze.',
      not: 'Denizdeki canlı balık "el pez"dir; ikisi farklıdır.',
    },
    {
      id: 'es-yem-16', on: 'las verduras', okunus: 'las verduras', tur: 'isim (çoğul)',
      arka: 'sebzeler',
      ornek: '¡Come más verduras!',
      ornekTr: 'Daha çok sebze ye!',
      not: '"verde" yeşil demektir.',
    },
    {
      id: 'es-yem-17', on: 'la fruta', okunus: 'la fruta', tur: 'isim (dişil)',
      arka: 'meyve',
      ornek: 'La fruta es mejor que los dulces.',
      ornekTr: 'Meyve tatlılardan iyidir.',
      not: 'Genel olarak tekil kullanılır.',
    },
    {
      id: 'es-yem-18', on: 'el arroz', okunus: 'el arros', tur: 'isim (eril)',
      arka: 'pirinç, pilav',
      ornek: 'La paella se hace con arroz.',
      ornekTr: 'Paella pirinçle yapılır.',
      not: 'Paella İspanya\'nın en ünlü pirinç yemeğidir.',
    },
    {
      id: 'es-yem-19', on: 'el huevo', okunus: 'el uevo', tur: 'isim (eril)',
      arka: 'yumurta',
      ornek: 'Como un huevo cada mañana.',
      ornekTr: 'Her sabah bir yumurta yiyorum.',
      not: 'Baştaki "h" okunmaz.',
    },
    {
      id: 'es-yem-20', on: 'la sopa', okunus: 'la sopa', tur: 'isim (dişil)',
      arka: 'çorba',
      ornek: 'La sopa todavía está muy caliente.',
      ornekTr: 'Çorba hâlâ çok sıcak.',
      not: '"todavía" hâlâ demektir.',
    },
    /* --- Pişirme --- */
    {
      id: 'es-yem-21', on: 'cocinar', okunus: 'kosinar', tur: 'fiil',
      arka: 'yemek yapmak',
      ornek: 'Mi madre cocina muy bien.',
      ornekTr: 'Annem çok iyi yemek yapar.',
      not: '"la cocina" mutfak demektir.',
    },
    {
      id: 'es-yem-22', on: 'hervir', okunus: 'ervir', tur: 'fiil',
      arka: 'kaynatmak, haşlamak',
      ornek: 'Hierve el agua primero.',
      ornekTr: 'Önce suyu kaynat.',
      not: 'Çekimi düzensizdir: hiervo, hierves, hierve.',
      kok: 'hierve',
    },
    {
      id: 'es-yem-23', on: 'freír', okunus: 'freir', tur: 'fiil',
      arka: 'kızartmak',
      ornek: 'Fríe las patatas en aceite.',
      ornekTr: 'Patatesleri yağda kızart.',
      not: '"las patatas fritas" patates kızartması demektir.',
      kok: 'fríe',
    },
    {
      id: 'es-yem-24', on: 'asar', okunus: 'asar', tur: 'fiil',
      arka: 'fırında kızartmak',
      ornek: 'Asamos un pollo para la cena.',
      ornekTr: 'Akşam yemeği için tavuk kızarttık.',
      not: '"el asado" kızartma demektir.',
      kok: 'asamos',
    },
    {
      id: 'es-yem-25', on: 'cortar', okunus: 'kortar', tur: 'fiil',
      arka: 'kesmek, doğramak',
      ornek: 'Corta la cebolla en trozos pequeños.',
      ornekTr: 'Soğanı küçük parçalar hâlinde doğra.',
      not: '"el trozo" parça demektir.',
    },
    {
      id: 'es-yem-26', on: 'pelar', okunus: 'pelar', tur: 'fiil',
      arka: 'soymak',
      ornek: 'Pela las patatas antes de cocerlas.',
      ornekTr: 'Patatesleri pişirmeden önce soy.',
      not: '"la piel" kabuk, deri demektir.',
    },
    {
      id: 'es-yem-27', on: 'mezclar', okunus: 'meskla', tur: 'fiil',
      arka: 'karıştırmak',
      ornek: 'Mezcla bien todos los ingredientes.',
      ornekTr: 'Bütün malzemeleri iyice karıştır.',
      not: '"la mezcla" karışım demektir.',
    },
    {
      id: 'es-yem-28', on: 'la receta', okunus: 'la reseta', tur: 'isim (dişil)',
      arka: 'tarif',
      ornek: 'Es la receta de mi abuela.',
      ornekTr: 'Bu babaannemin tarifi.',
      not: 'Doktor reçetesi için de aynı kelime kullanılır.',
    },
    {
      id: 'es-yem-29', on: 'los ingredientes', okunus: 'los ingredyentes', tur: 'isim (çoğul)',
      arka: 'malzemeler',
      ornek: 'Solo hacen falta cinco ingredientes.',
      ornekTr: 'Sadece beş malzeme gerekiyor.',
      not: '"hacer falta" gerekmek demektir.',
    },
    {
      id: 'es-yem-30', on: 'el horno', okunus: 'el orno', tur: 'isim (eril)',
      arka: 'fırın',
      ornek: 'Precalienta el horno a ciento ochenta grados.',
      ornekTr: 'Fırını yüz seksen dereceye ısıt.',
      not: '"precalentar" önceden ısıtmak demektir.',
    },
    /* --- Tat ve doku --- */
    {
      id: 'es-yem-31', on: 'dulce', okunus: 'dulse', tur: 'sıfat',
      arka: 'tatlı',
      ornek: 'Este té está demasiado dulce.',
      ornekTr: 'Bu çay fazla tatlı.',
      not: 'İsim olarak "tatlı, şekerleme" demektir.',
    },
    {
      id: 'es-yem-32', on: 'salado', okunus: 'salado', tur: 'sıfat',
      arka: 'tuzlu',
      ornek: 'La sopa está un poco salada.',
      ornekTr: 'Çorba biraz tuzlu.',
      not: '"la sal" tuz demektir.',
    },
    {
      id: 'es-yem-33', on: 'picante', okunus: 'pikante', tur: 'sıfat',
      arka: 'acı (baharatlı)',
      ornek: 'Esta salsa está muy picante.',
      ornekTr: 'Bu sos çok acı.',
      not: '"picar" burada acı yakmak demektir.',
    },
    {
      id: 'es-yem-34', on: 'amargo', okunus: 'amargo', tur: 'sıfat',
      arka: 'acı (kahve gibi)',
      ornek: 'El café solo es amargo.',
      ornekTr: 'Sade kahve acıdır.',
      not: 'Biberin acısı "picante"dir; ikisi karıştırılır.',
    },
    {
      id: 'es-yem-35', on: 'ácido', okunus: 'asido', tur: 'sıfat',
      arka: 'ekşi',
      ornek: 'El limón es muy ácido.',
      ornekTr: 'Limon çok ekşi.',
      not: 'Kimyadaki "asit" ile aynı kelimedir.',
    },
    {
      id: 'es-yem-36', on: 'crujiente', okunus: 'kruhyente', tur: 'sıfat',
      arka: 'çıtır çıtır',
      ornek: 'La corteza está bien crujiente.',
      ornekTr: 'Kabuk güzelce çıtır çıtır.',
      not: '"crujir" çıtırdamak demektir.',
    },
    {
      id: 'es-yem-37', on: 'grasiento', okunus: 'grasyento', tur: 'sıfat',
      arka: 'yağlı',
      ornek: 'La comida estaba un poco grasienta.',
      ornekTr: 'Yemek biraz yağlıydı.',
      not: '"la grasa" yağ demektir.',
    },
    {
      id: 'es-yem-38', on: 'crudo', okunus: 'krudo', tur: 'sıfat',
      arka: 'çiğ',
      ornek: 'No se debe comer pollo crudo.',
      ornekTr: 'Çiğ tavuk yenmemeli.',
      not: '"no se debe" yapılmamalı demektir.',
    },
    {
      id: 'es-yem-39', on: 'estar rico', okunus: 'estar riko', tur: 'kalıp',
      arka: 'lezzetli olmak',
      ornek: 'Este plato está riquísimo.',
      ornekTr: 'Bu yemek çok lezzetli.',
      not: '"ser rico" zengin olmak, "estar rico" lezzetli olmaktır.',
      kok: 'riquísimo',
    },
    {
      id: 'es-yem-40', on: 'saber a', okunus: 'saber a', tur: 'kalıp',
      arka: 'tadı ... gibi olmak',
      ornek: 'Sabe a pizza fina.',
      ornekTr: 'Tadı ince pizza gibi.',
      not: '"saber" hem bilmek hem tat vermek demektir.',
      kok: 'sabe',
    },
    /* --- Öğünler --- */
    {
      id: 'es-yem-41', on: 'la comida', okunus: 'la komida', tur: 'isim (dişil)',
      arka: 'öğle yemeği; yemek',
      ornek: 'La comida es a las dos en España.',
      ornekTr: 'İspanya\'da öğle yemeği saat ikide.',
      not: 'İspanya\'da öğle yemeği geç ve ana öğündür.',
    },
    {
      id: 'es-yem-42', on: 'la cena', okunus: 'la sena', tur: 'isim (dişil)',
      arka: 'akşam yemeği',
      ornek: 'La cena suele ser a las nueve.',
      ornekTr: 'Akşam yemeği genelde dokuzda olur.',
      not: '"soler" genelde yapmak demektir.',
    },
    {
      id: 'es-yem-43', on: 'la merienda', okunus: 'la meryenda', tur: 'isim (dişil)',
      arka: 'ikindi atıştırması',
      ornek: 'Los niños toman la merienda a las cinco.',
      ornekTr: 'Çocuklar saat beşte ikindi atıştırması yapıyor.',
      not: 'İspanyol çocukluk kültürünün klasik öğünüdür.',
    },
    {
      id: 'es-yem-44', on: 'saltarse una comida', okunus: 'saltarse una komida', tur: 'kalıp',
      arka: 'öğün atlamak',
      ornek: 'Nunca te saltes el desayuno.',
      ornekTr: 'Kahvaltıyı asla atlama.',
      not: '"saltar" zıplamak demektir. Emir kipi: no te saltes.',
      kok: 'saltes',
    },
    {
      id: 'es-yem-45', on: 'las sobras', okunus: 'las sobras', tur: 'isim (çoğul)',
      arka: 'artan yemek',
      ornek: 'Nos comemos las sobras mañana.',
      ornekTr: 'Artanları yarın yeriz.',
      not: '"sobrar" artmak, fazla gelmek demektir.',
    },
    {
      id: 'es-yem-46', on: 'casero', okunus: 'kasero', tur: 'sıfat',
      arka: 'ev yapımı',
      ornek: 'Esta mermelada es casera.',
      ornekTr: 'Bu reçel ev yapımı.',
      not: '"la casa" ev demektir.',
    },
    {
      id: 'es-yem-47', on: 'estar lleno', okunus: 'estar yeno', tur: 'kalıp',
      arka: 'doymuş olmak',
      ornek: 'Gracias, estoy lleno.',
      ornekTr: 'Teşekkürler, doydum.',
      not: 'Kelimesi kelimesine "dolu olmak" demektir.',
    },
    {
      id: 'es-yem-48', on: 'picar algo', okunus: 'pikar algo', tur: 'kalıp',
      arka: 'bir şeyler atıştırmak',
      ornek: 'Vamos a picar algo antes del cine.',
      ornekTr: 'Sinemadan önce bir şeyler atıştıralım.',
      not: 'Tapas kültürünün temel fiilidir.',
    },
    {
      id: 'es-yem-49', on: 'ser goloso', okunus: 'ser goloso', tur: 'kalıp',
      arka: 'tatlı düşkünü olmak',
      ornek: 'Mi hermana es muy golosa.',
      ornekTr: 'Kız kardeşim çok tatlı düşkünüdür.',
      not: 'Sevecen bir nitelemedir, eleştiri değildir.',
    },
    {
      id: 'es-yem-50', on: 'comer fuera', okunus: 'komer fuera', tur: 'kalıp',
      arka: 'dışarıda yemek',
      ornek: 'Comemos fuera una vez a la semana.',
      ornekTr: 'Haftada bir dışarıda yiyoruz.',
      not: '"una vez a la semana" haftada bir demektir.',
    },
    /* --- Restoran --- */
    {
      id: 'es-yem-51', on: 'reservar una mesa', okunus: 'reservar una mesa', tur: 'kalıp',
      arka: 'masa ayırtmak',
      ornek: 'He reservado una mesa para cuatro.',
      ornekTr: 'Dört kişilik masa ayırttım.',
      not: '"para + sayı" kişi sayısını verir.',
    },
    {
      id: 'es-yem-52', on: 'la carta', okunus: 'la karta', tur: 'isim (dişil)',
      arka: 'menü',
      ornek: '¿Nos trae la carta, por favor?',
      ornekTr: 'Menüyü getirir misiniz lütfen?',
      not: 'Sabit menü "el menú del día"dır.',
    },
    {
      id: 'es-yem-53', on: 'el primer plato', okunus: 'el primer plato', tur: 'isim (eril)',
      arka: 'başlangıç yemeği',
      ornek: 'De primer plato tomo sopa.',
      ornekTr: 'Başlangıç olarak çorba alıyorum.',
      not: 'Ana yemek "el segundo plato"dur.',
    },
    {
      id: 'es-yem-54', on: 'el postre', okunus: 'el postre', tur: 'isim (eril)',
      arka: 'tatlı',
      ornek: 'De postre hay flan.',
      ornekTr: 'Tatlı olarak flan var.',
      not: '"el flan" İspanya\'nın klasik tatlısıdır.',
    },
    {
      id: 'es-yem-55', on: 'el camarero', okunus: 'el kamarero', tur: 'isim (eril)',
      arka: 'garson',
      ornek: 'El camarero fue muy amable.',
      ornekTr: 'Garson çok nazikti.',
      not: 'Kadın garson "la camarera"dır.',
    },
    {
      id: 'es-yem-56', on: 'la propina', okunus: 'la propina', tur: 'isim (dişil)',
      arka: 'bahşiş',
      ornek: 'Dejamos una pequeña propina.',
      ornekTr: 'Küçük bir bahşiş bıraktık.',
      not: 'İspanya\'da bahşiş zorunlu değildir.',
    },
    {
      id: 'es-yem-57', on: 'pagar a escote', okunus: 'pagar a eskote', tur: 'deyim',
      arka: 'hesabı paylaşmak',
      ornek: '¿Pagamos a escote?',
      ornekTr: 'Hesabı paylaşalım mı?',
      not: 'Gençler arasında çok kullanılan bir ifadedir.',
    },
    {
      id: 'es-yem-58', on: 'las tapas', okunus: 'las tapas', tur: 'isim (çoğul)',
      arka: 'küçük meze tabakları',
      ornek: 'Salimos a tomar unas tapas.',
      ornekTr: 'Tapas yemeye çıktık.',
      not: 'İspanyol yeme kültürünün simgesidir.',
    },
    {
      id: 'es-yem-59', on: 'la ración', okunus: 'la rasyon', tur: 'isim (dişil)',
      arka: 'porsiyon',
      ornek: 'Las raciones aquí son enormes.',
      ornekTr: 'Buradaki porsiyonlar kocaman.',
      not: '"enorme" devasa demektir.',
    },
    {
      id: 'es-yem-60', on: 'vegetariano', okunus: 'vehetaryano', tur: 'sıfat',
      arka: 'vejetaryen',
      ornek: '¿Tienen algún plato vegetariano?',
      ornekTr: 'Vejetaryen yemeğiniz var mı?',
      not: '"algún" herhangi bir demektir.',
    },
    /* --- Alışveriş --- */
    {
      id: 'es-yem-61', on: 'hacer la compra', okunus: 'aser la kompra', tur: 'kalıp',
      arka: 'market alışverişi yapmak',
      ornek: 'Hago la compra los sábados.',
      ornekTr: 'Market alışverişini cumartesileri yapıyorum.',
      not: '"ir de compras" giyim alışverişidir; ikisi farklıdır.',
    },
    {
      id: 'es-yem-62', on: 'el supermercado', okunus: 'el supermerkado', tur: 'isim (eril)',
      arka: 'süpermarket',
      ornek: 'El supermercado cierra a las nueve.',
      ornekTr: 'Süpermarket dokuzda kapanıyor.',
      not: '"el mercado" pazar demektir.',
    },
    {
      id: 'es-yem-63', on: 'la panadería', okunus: 'la panaderiya', tur: 'isim (dişil)',
      arka: 'fırın, ekmekçi',
      ornek: 'Compro el pan en la panadería.',
      ornekTr: 'Ekmeği fırından alıyorum.',
      not: '"-ería" eki dükkân bildirir: carnicería, pescadería.',
    },
    {
      id: 'es-yem-64', on: 'la carnicería', okunus: 'la karniseriya', tur: 'isim (dişil)',
      arka: 'kasap',
      ornek: 'La carne la compramos en la carnicería.',
      ornekTr: 'Eti kasaptan alıyoruz.',
      not: '"la carne" et demektir.',
    },
    {
      id: 'es-yem-65', on: 'la fecha de caducidad', okunus: 'la feça de kadusidad', tur: 'isim (dişil)',
      arka: 'son kullanma tarihi',
      ornek: 'Mira la fecha de caducidad del yogur.',
      ornekTr: 'Yoğurdun son kullanma tarihine bak.',
      not: '"caducar" süresi dolmak demektir.',
    },
    {
      id: 'es-yem-66', on: 'la lista de la compra', okunus: 'la lista de la kompra', tur: 'isim (dişil)',
      arka: 'alışveriş listesi',
      ornek: 'Escribo la lista de la compra.',
      ornekTr: 'Alışveriş listesini yazıyorum.',
      not: 'Alışverişi unutmadan yapmanın yoludur.',
    },
    {
      id: 'es-yem-67', on: 'estar de oferta', okunus: 'estar de oferta', tur: 'kalıp',
      arka: 'indirimde olmak',
      ornek: 'El queso está de oferta esta semana.',
      ornekTr: 'Peynir bu hafta indirimde.',
      not: '"ofrecer" sunmak demektir.',
    },
    {
      id: 'es-yem-68', on: 'caducado', okunus: 'kadukado', tur: 'sıfat',
      arka: 'tarihi geçmiş',
      ornek: 'La leche está caducada.',
      ornekTr: 'Sütün tarihi geçmiş.',
      not: 'Bozulmuş süt için "cortada" da denir.',
    },
    {
      id: 'es-yem-69', on: 'no queda', okunus: 'no keda', tur: 'kalıp',
      arka: '... kalmadı',
      ornek: 'No queda leche en la nevera.',
      ornekTr: 'Buzdolabında süt kalmadı.',
      not: '"la nevera" buzdolabı demektir.',
    },
    {
      id: 'es-yem-70', on: 'fregar los platos', okunus: 'fregar los platos', tur: 'kalıp',
      arka: 'bulaşık yıkamak',
      ornek: 'Yo friego los platos esta noche.',
      ornekTr: 'Bulaşığı bu akşam ben yıkıyorum.',
      not: 'Çekimi düzensizdir: friego, friegas.',
      kok: 'friego',
    },
    /* --- Sağlık ve beslenme --- */
    {
      id: 'es-yem-71', on: 'equilibrado', okunus: 'ekilibrado', tur: 'sıfat',
      arka: 'dengeli',
      ornek: 'Una dieta equilibrada es fundamental.',
      ornekTr: 'Dengeli beslenme çok önemlidir.',
      not: '"fundamental" temel, çok önemli demektir.',
    },
    {
      id: 'es-yem-72', on: 'estar a dieta', okunus: 'estar a dyeta', tur: 'kalıp',
      arka: 'diyette olmak',
      ornek: 'Está a dieta desde hace un mes.',
      ornekTr: 'Bir aydır diyette.',
      not: '"la dieta" hem diyet hem genel beslenme düzenidir.',
    },
    {
      id: 'es-yem-73', on: 'reducir', okunus: 'redusir', tur: 'fiil',
      arka: 'azaltmak',
      ornek: 'Deberías reducir el azúcar.',
      ornekTr: 'Şekeri azaltmalısın.',
      not: '"deberías" -meliydin, -malısın demektir.',
    },
    {
      id: 'es-yem-74', on: 'nutritivo', okunus: 'nutritivo', tur: 'sıfat',
      arka: 'besleyici',
      ornek: 'Las lentejas son baratas y nutritivas.',
      ornekTr: 'Mercimek ucuz ve besleyicidir.',
      not: '"barato" ucuz demektir.',
    },
    {
      id: 'es-yem-75', on: 'ser alérgico a', okunus: 'ser alerhiko a', tur: 'kalıp',
      arka: 'alerjisi olmak',
      ornek: 'Soy alérgico a los cacahuetes.',
      ornekTr: 'Fıstığa alerjim var.',
      not: 'Restoranda hayat kurtaran bir cümledir.',
    },
    {
      id: 'es-yem-76', on: 'adelgazar', okunus: 'adelgasar', tur: 'fiil',
      arka: 'kilo vermek',
      ornek: 'Quiere adelgazar antes del verano.',
      ornekTr: 'Yazdan önce kilo vermek istiyor.',
      not: 'Kilo almak "engordar"dır.',
    },
    {
      id: 'es-yem-77', on: 'ecológico', okunus: 'ekolohiko', tur: 'sıfat',
      arka: 'organik',
      ornek: 'Las verduras ecológicas cuestan más.',
      ornekTr: 'Organik sebzeler daha pahalı.',
      not: 'Kısaca "eco" da denir.',
    },
    {
      id: 'es-yem-78', on: 'beber agua', okunus: 'beber agua', tur: 'kalıp',
      arka: 'su içmek',
      ornek: 'Bebe agua con frecuencia en época de exámenes.',
      ornekTr: 'Sınav döneminde sık sık su iç.',
      not: '"con frecuencia" sık sık demektir.',
    },
    {
      id: 'es-yem-79', on: 'los alimentos procesados', okunus: 'los alimentos prosesados', tur: 'isim (çoğul)',
      arka: 'işlenmiş gıdalar',
      ornek: 'Evita los alimentos procesados.',
      ornekTr: 'İşlenmiş gıdalardan kaçın.',
      not: '"evitar" kaçınmak demektir.',
    },
    {
      id: 'es-yem-80', on: 'con moderación', okunus: 'kon moderasyon', tur: 'kalıp',
      arka: 'ölçülü biçimde',
      ornek: 'Los dulces están bien con moderación.',
      ornekTr: 'Tatlılar ölçülü olursa sorun değil.',
      not: 'Sağlık metinlerinde sık geçer.',
    },
    /* --- Mutfak kültürü --- */
    {
      id: 'es-yem-81', on: 'la especialidad', okunus: 'la espesyalidad', tur: 'isim (dişil)',
      arka: 'yöresel lezzet',
      ornek: 'El baklava es una especialidad turca.',
      ornekTr: 'Baklava bir Türk lezzetidir.',
      not: '"especial" özel demektir.',
    },
    {
      id: 'es-yem-82', on: 'relleno', okunus: 'reyeno', tur: 'sıfat',
      arka: 'doldurulmuş, dolma',
      ornek: 'Los pimientos rellenos son un clásico turco.',
      ornekTr: 'Biber dolması bir Türk klasiğidir.',
      not: '"rellenar" doldurmak demektir.',
    },
    {
      id: 'es-yem-83', on: 'la carne picada', okunus: 'la karne pikada', tur: 'isim (dişil)',
      arka: 'kıyma',
      ornek: 'El relleno se hace con carne picada.',
      ornekTr: 'İç harcı kıymayla yapılıyor.',
      not: '"picar" doğramak, kıymak demektir.',
    },
    {
      id: 'es-yem-84', on: 'la masa', okunus: 'la masa', tur: 'isim (dişil)',
      arka: 'hamur',
      ornek: 'La masa tiene que ser fina.',
      ornekTr: 'Hamur ince olmalı.',
      not: 'Börek anlatırken en gerekli kelimedir.',
    },
    {
      id: 'es-yem-85', on: 'ser famoso por', okunus: 'ser famoso por', tur: 'kalıp',
      arka: 'bir şeyle ünlü olmak',
      ornek: 'Gaziantep es famosa por su baklava.',
      ornekTr: 'Gaziantep baklavasıyla ünlüdür.',
      not: 'Edatı "por"dur.',
    },
    {
      id: 'es-yem-86', on: 'servirse con', okunus: 'servirse kon', tur: 'kalıp',
      arka: 'yanında ... ile servis edilmek',
      ornek: 'El plato se sirve con arroz.',
      ornekTr: 'Yemek pilavla servis edilir.',
      not: 'Kişisiz "se" yapısı kullanılır.',
      kok: 'sirve',
    },
    {
      id: 'es-yem-87', on: 'no te lo pierdas', okunus: 'no te lo pyerdas', tur: 'kalıp',
      arka: 'Sakın kaçırma',
      ornek: 'El menemen en el desayuno: no te lo pierdas.',
      ornekTr: 'Kahvaltıda menemen: sakın kaçırma.',
      not: '"perderse" kaçırmak demektir.',
    },
    {
      id: 'es-yem-88', on: 'sírvete', okunus: 'sirvete', tur: 'kalıp',
      arka: 'Buyur, kendin al',
      ornek: 'Sírvete, hay para todos.',
      ornekTr: 'Buyur al, herkese yeter.',
      not: '"servirse" kendine almak demektir.',
    },
    {
      id: 'es-yem-89', on: '¡Buen provecho!', okunus: 'buen proveço', tur: 'kalıp',
      arka: 'Afiyet olsun!',
      ornek: 'La comida está lista. ¡Buen provecho!',
      ornekTr: 'Yemek hazır. Afiyet olsun!',
      not: '"¡Que aproveche!" de aynı anlamda kullanılır.',
    },
    {
      id: 'es-yem-90', on: '¿Está bueno?', okunus: 'esta bueno', tur: 'soru kalıbı',
      arka: 'Güzel mi?',
      ornek: '¿Está bueno el postre?',
      ornekTr: 'Tatlı güzel mi?',
      not: '"estar bueno" lezzetli olmak demektir.',
    },
    /* --- Yemek deyimleri --- */
    {
      id: 'es-yem-91', on: 'ser pan comido', okunus: 'ser pan komido', tur: 'deyim',
      arka: 'çok kolay olmak',
      ornek: 'Ese examen fue pan comido.',
      ornekTr: 'O sınav çocuk oyuncağıydı.',
      not: 'Kelimesi kelimesine "yenmiş ekmek" demektir.',
    },
    {
      id: 'es-yem-92', on: 'ponerse las botas', okunus: 'ponerse las botas', tur: 'deyim',
      arka: 'karnını tıka basa doyurmak',
      ornek: 'En la fiesta nos pusimos las botas.',
      ornekTr: 'Partide karnımızı tıka basa doyurduk.',
      not: 'Kelimesi kelimesine "çizmeleri giymek" demektir.',
    },
    {
      id: 'es-yem-93', on: 'estar como un fideo', okunus: 'estar komo un fideo', tur: 'deyim',
      arka: 'çok zayıf olmak',
      ornek: 'Después del verano está como un fideo.',
      ornekTr: 'Yazdan sonra iyice zayıfladı.',
      not: '"el fideo" şehriye demektir.',
    },
    {
      id: 'es-yem-94', on: 'importar un pimiento', okunus: 'importar un pimyento', tur: 'deyim',
      arka: 'hiç umurunda olmamak',
      ornek: 'Me importa un pimiento lo que digan.',
      ornekTr: 'Ne derlerse desinler umurumda değil.',
      not: '"el pimiento" biber demektir.',
    },
    {
      id: 'es-yem-95', on: 'dar calabazas', okunus: 'dar kalabasas', tur: 'deyim',
      arka: 'birini reddetmek',
      ornek: 'Le dio calabazas muy educadamente.',
      ornekTr: 'Onu çok kibarca reddetti.',
      not: '"la calabaza" kabak demektir.',
    },
    {
      id: 'es-yem-96', on: 'estar de mala uva', okunus: 'estar de mala uva', tur: 'deyim',
      arka: 'keyfi kaçık olmak',
      ornek: 'Hoy está de mala uva.',
      ornekTr: 'Bugün keyfi kaçık.',
      not: '"la uva" üzüm demektir.',
    },
    {
      id: 'es-yem-97', on: 'ser la leche', okunus: 'ser la leçe', tur: 'deyim',
      arka: 'inanılmaz olmak',
      ornek: 'Ese jugador es la leche.',
      ornekTr: 'O oyuncu inanılmaz.',
      not: 'Bağlama göre hem övgü hem şikâyet olabilir.',
    },
    {
      id: 'es-yem-98', on: 'a buen hambre no hay pan duro', okunus: 'a buen ambre no ay pan duro', tur: 'atasözü',
      arka: 'Aç olana bayat ekmek de güzel gelir',
      ornek: 'Come lo que hay: a buen hambre no hay pan duro.',
      ornekTr: 'Ne varsa onu ye: aç olana bayat ekmek de güzel gelir.',
      not: '"duro" sert, bayat demektir.',
    },
    {
      id: 'es-yem-99', on: 'el apetito viene comiendo', okunus: 'el apetito vyene komyendo', tur: 'atasözü',
      arka: 'İştah yemekle açılır',
      ornek: 'Empieza: el apetito viene comiendo.',
      ornekTr: 'Sadece başla: iştah yemekle açılır.',
      not: 'Ders çalışmaya başlamak için de kullanılır.',
    },
    {
      id: 'es-yem-100', on: 'donde comen dos, comen tres', okunus: 'donde komen dos komen tres', tur: 'atasözü',
      arka: 'İki kişinin yediği yerde üç kişi de yer',
      ornek: 'Quédate a cenar: donde comen dos, comen tres.',
      ornekTr: 'Akşam yemeğine kal: iki kişinin yediği yerde üç kişi de yer.',
      not: 'İspanyol misafirperverliğini özetleyen bir sözdür.',
    },
  ],
}

export default DESTE
