import { useMemo, useState } from 'react'
import { RotateCcw } from 'lucide-react'
import { riskPuani } from '../../../lib/cografya/modeller.js'
import { BolgeBasligi, Kaydirici, Mekanizma, ModulKabugu, Olcumler } from '../ortak/index.js'

const EVRELER=['Risk azaltma','Hazırlık','Müdahale','İyileştirme']

export default function AfetBolgesi(){
  const [tehlike,setTehlike]=useState(75); const [maruziyet,setMaruziyet]=useState(70); const [kirilan,setKirilan]=useState(60); const [hazirlik,setHazirlik]=useState(25); const [sira,setSira]=useState([])
  const risk=useMemo(()=>riskPuani({tehlike,maruziyet,kirilganlik:kirilan,hazirlik}),[tehlike,maruziyet,kirilan,hazirlik])
  const seviye=risk>55?'çok yüksek':risk>30?'yüksek':risk>12?'orta':'düşük'
  return <div className="ca-bolge"><BolgeBasligi baslik="Afet ve Dirençlilik" aciklama="Tehlikeyi afetten ayır; maruziyet, kırılganlık ve hazırlık üzerinden azaltılabilir riski hesapla." renk="#ee6f6f" sayi="2"/>
    <ModulKabugu id="risk-katmanlari" bolge="afet" baslik="Risk katmanları laboratuvarı" aciklama="Aynı tehlikede yerleşim ve hazırlığı değiştir; afet sonucunun neden toplumsal olduğunu gözle." yanilgiId="tehlike-afet" tahmin={{soru:'Şiddetli deprem tehlikesi olan ama yapılaşma bulunmayan alanda afet kaybı nasıldır?',secenekler:['Maruziyet düşükse sınırlı olabilir','Her zaman en yüksektir','Hazırlıktan bağımsızdır']}} kontrol={{soru:'Afet riskini azaltmada hangisi doğrudan etkilidir?',secenekler:['Kırılgan yapıları güçlendirmek ve hazırlığı artırmak','Tehlikenin adını değiştirmek','Boylamı değiştirmek'],cevap:0,aciklama:'Tehlike her zaman engellenemese de maruziyet, kırılganlık ve hazırlık yönetilebilir.'}} transfer={{soru:'Aynı sel tehlikesindeki iki mahalleden hangisinin riski daha düşüktür?',secenekler:['Taşkın alanında plansız olan','Erken uyarı, geçirgen yüzey ve tahliye planı olan','Nüfusu daha yoğun olan'],cevap:1,aciklama:'Hazırlık ve risk azaltma önlemleri beklenen kaybı düşürür.'}}>{({kanitla})=><div className="ca-sim-grid"><div className="ca-kontrol-panel"><Kaydirici etiket="Tehlike" deger={tehlike} min={0} max={100} onChange={v=>{setTehlike(v);kanitla()}}/><Kaydirici etiket="Maruziyet" deger={maruziyet} min={0} max={100} onChange={v=>{setMaruziyet(v);kanitla()}}/><Kaydirici etiket="Kırılganlık" deger={kirilan} min={0} max={100} onChange={v=>{setKirilan(v);kanitla()}}/><Kaydirici etiket="Hazırlık" deger={hazirlik} min={0} max={100} onChange={v=>{setHazirlik(v);kanitla()}}/><Olcumler degerler={[{etiket:'Risk puanı',deger:risk,birim:'/100',vurgu:true},{etiket:'Risk düzeyi',deger:seviye}]}/></div><div className="ca-risk-sahne"><div className="risk-halkalari"><i style={{'--v':`${tehlike}%`}}>T</i><i style={{'--v':`${maruziyet}%`}}>M</i><i style={{'--v':`${kirilan}%`}}>K</i><strong style={{'--risk':`${risk}%`}}>{risk}</strong></div><div className="risk-formul">Tehlike × Maruziyet × Kırılganlık − Hazırlık</div><Mekanizma tur={risk>55?'uyari':'olumlu'}>{risk>55?'Beklenen kayıp yüksek. Yapı güvenliği, arazi kullanımı ve hazırlık birlikte güçlendirilmeli.':'Hazırlık ve düşük kırılganlık, tehlikeyi ortadan kaldırmadan riski azaltıyor.'}</Mekanizma></div></div>}</ModulKabugu>
    <ModulKabugu id="afet-dongusu" bolge="afet" baslik="Afet yönetimi döngüsü" aciklama="Müdahaleyi tek adım sanma; risk azaltmadan iyileştirmeye kesintisiz yönetim zinciri kur." yanilgiId="tehlike-afet" tahmin={{soru:'Afet yönetimi ne zaman başlamalıdır?',secenekler:['Afetten önce risk azaltmayla','Yalnız olay anında','Hasarlar bittikten yıllar sonra']}} kontrol={{soru:'Dayanıksız okul binalarını güçlendirmek hangi evrededir?',secenekler:['Risk azaltma','Müdahale','Yalnız iyileştirme'],cevap:0,aciklama:'Olay öncesi yapısal güçlendirme beklenen kaybı azaltır.'}} transfer={{soru:'Afetten sonra aynı riskli alana aynı biçimde yapı yapmak hangi ilkeye aykırıdır?',secenekler:['Daha iyi yeniden inşa etme','Yerel saat','Harita ölçeği'],cevap:0,aciklama:'İyileştirme, eski kırılganlığı yeniden üretmek yerine gelecekteki riski azaltmalıdır.'}}>{({kanitla})=><div className="ca-afet-dongu"><div className="ca-evre-secim">{EVRELER.map(e=><button type="button" key={e} disabled={sira.includes(e)} onClick={()=>{setSira(eski=>[...eski,e]);kanitla()}}>{e}</button>)}<button type="button" className="sifirla" onClick={()=>setSira([])}><RotateCcw size={15}/> Sıfırla</button></div><ol>{EVRELER.map((_,i)=><li key={i} className={sira[i]?'dolu':''}><span>{i+1}</span>{sira[i]||'Bir evre seç'}</li>)}</ol><Mekanizma tur={sira.join('|')===EVRELER.join('|')?'olumlu':'bilgi'}>{sira.length<4?'Evreleri neden-sonuç sırasına yerleştir. Döngü, iyileştirmeden yeniden risk azaltmaya döner.':sira.join('|')===EVRELER.join('|')?'Doğru zincir: riski azalt, hazırlan, olay anında müdahale et, daha dirençli iyileştir.':'Sıra mekanizmayı bozuyor; olaydan önce azaltma ve hazırlık gelmeli.'}</Mekanizma></div>}</ModulKabugu>
  </div>
}
