import { useMemo, useState } from 'react'
import { BolgeBasligi, Kaydirici, Mekanizma, ModulKabugu, Olcumler, Secim } from '../ortak/index.js'

const TESISLER={
  seker:{ad:'Şeker fabrikası',hammadde:95,pazar:55,enerji:55,liman:20,not:'Çabuk bozulan ve taşınırken kütle kaybeden pancara yakınlık öne çıkar.'},
  rafineri:{ad:'Petrol rafinerisi',hammadde:55,pazar:70,enerji:80,liman:95,not:'İthal girdi ve dağıtım ağı için liman/boru hattı bağlantısı önemlidir.'},
  yazilim:{ad:'Yazılım merkezi',hammadde:20,pazar:75,enerji:65,liman:10,not:'Nitelikli iş gücü, iletişim ve yenilik ağı fiziksel hammaddeden daha önemlidir.'},
}

export default function EkonomiBolgesi(){
  const [tesis,setTesis]=useState('seker'); const [konum,setKonum]=useState('hammadde'); const [mesafe,setMesafe]=useState(500); const [yuk,setYuk]=useState('hacimli'); const [yenilenebilir,setYenilenebilir]=useState(65); const [habitat,setHabitat]=useState(55)
  const t=TESISLER[tesis]
  const kurulus=useMemo(()=>{const eslesme={hammadde:t.hammadde,pazar:t.pazar,liman:t.liman}[konum]||50; return Math.round(eslesme*.7+t.enerji*.3)},[t,konum])
  const tasima=useMemo(()=>{const mod=yuk==='hacimli'?(mesafe>400?'demiryolu/denizyolu':'demiryolu'):yuk==='bozulabilir'?'karayolu + soğuk zincir':'çok modlu'; return {mod,maliyet:Math.round(mesafe*(yuk==='hacimli'?1.1:yuk==='bozulabilir'?1.4:.8)/10)}},[mesafe,yuk])
  const enerjiEtki=Math.round((100-yenilenebilir)*.55+habitat*.45)
  return <div className="ca-bolge"><BolgeBasligi bolge="ekonomi" aciklama="Üretim yerini, ulaşım ağını ve enerji kararını maliyet–erişim–çevre dengesiyle çöz."/>
    <ModulKabugu id="kurulus-yeri" bolge="ekonomi" baslik="Kuruluş yeri karar laboratuvarı" aciklama="Tesis türünü ve konumu değiştir; aynı ölçütün her ekonomik faaliyet için eşit olmadığını gör." yanilgiId="determinist" tahmin={{soru:'Şeker fabrikasında hangi konum etkeni daha baskındır?',secenekler:['Hammaddeye yakınlık','Kutup noktasına yakınlık','Yalnız turizm']}} kontrol={{soru:'Yazılım merkezinin yer seçiminde hangisi daha belirleyicidir?',secenekler:['Nitelikli iş gücü ve iletişim ağı','Maden ocağına yakınlık','Geniş tarım toprağı'],cevap:0,aciklama:'Bilgi yoğun üretimde insan sermayesi ve bağlantı ağları öne çıkar.'}} transfer={{soru:'Üretimde ağırlık kaybeden, çabuk bozulan ürün işleyen tesis nereye yaklaşmalıdır?',secenekler:['Hammadde alanına','Her durumda pazara','Saat dilimi sınırına'],cevap:0,aciklama:'Taşıma kaybı ve bozulma riski, hammaddenin kaynağında işlenmesini avantajlı kılar.'}}>{({kanitla})=><div className="ca-sim-grid"><div className="ca-kontrol-panel"><Secim etiket="Tesis" deger={tesis} secenekler={Object.entries(TESISLER).map(([value,v])=>({value,label:v.ad}))} onChange={v=>{setTesis(v);kanitla()}}/><Secim etiket="Aday konum" deger={konum} secenekler={[{value:'hammadde',label:'Hammadde sahası'},{value:'pazar',label:'Büyük pazar'},{value:'liman',label:'Liman düğümü'}]} onChange={v=>{setKonum(v);kanitla()}}/><Olcumler degerler={[{etiket:'Hammadde önemi',deger:t.hammadde},{etiket:'Pazar önemi',deger:t.pazar},{etiket:'Liman önemi',deger:t.liman},{etiket:'Konum uyumu',deger:kurulus,vurgu:true}]}/><Mekanizma>{t.not}</Mekanizma></div><div className="ca-uretim-agi"><span className="ham">Hammadde</span><span className="fabrika">{t.ad}</span><span className="pazar">Pazar</span><i className={`hat ${konum}`}/><strong>{kurulus>70?'Güçlü eşleşme':kurulus>50?'Koşullu eşleşme':'Zayıf eşleşme'}</strong></div></div>}</ModulKabugu>
    <ModulKabugu id="ulasim-enerji" bolge="ekonomi" baslik="Ulaşım ve enerji ağı" aciklama="Yük–mesafe kararını enerji tercihinin yerel etkisiyle birlikte değerlendir." yanilgiId="yenilenebilir-etkisiz" tahmin={{soru:'Çok hacimli yük uzun mesafeye taşınacaksa hangi türler genellikle avantajlıdır?',secenekler:['Demiryolu/denizyolu','Yalnız hava yolu','Ulaşım türü etkisiz']}} kontrol={{soru:'Yenilenebilir enerji için doğru ifade hangisidir?',secenekler:['Hiç çevresel etkisi yoktur','Emisyon avantajı vardır; yer ve ölçeğe bağlı etkileri yine değerlendirilir','Her yerde aynı verimi verir'],cevap:1,aciklama:'Kaynak yenilenebilir olsa da arazi, habitat ve iletim etkileri yerel olarak değişir.'}} transfer={{soru:'Rüzgâr santrali göç koridoruna kurulacaksa en iyi yaklaşım nedir?',secenekler:['Yer seçimini habitat verisiyle yeniden değerlendirmek','Etkisiz saymak','Rüzgârı tamamen yasaklamak'],cevap:0,aciklama:'Enerji ihtiyacı ile ekolojik hassasiyet, veriyle alternatif yer ve tasarım üzerinden dengelenir.'}}>{({kanitla})=><div><div className="ca-kontrol-dortlu"><Secim etiket="Yük türü" deger={yuk} secenekler={[{value:'hacimli',label:'Hacimli'},{value:'bozulabilir',label:'Bozulabilir'},{value:'degerli',label:'Değerli/hafif'}]} onChange={v=>{setYuk(v);kanitla()}}/><Kaydirici etiket="Mesafe" deger={mesafe} min={50} max={1500} adim={50} birim=" km" onChange={v=>{setMesafe(v);kanitla()}}/><Kaydirici etiket="Yenilenebilir payı" deger={yenilenebilir} min={0} max={100} birim="%" onChange={v=>{setYenilenebilir(v);kanitla()}}/><Kaydirici etiket="Habitat hassasiyeti" deger={habitat} min={0} max={100} onChange={v=>{setHabitat(v);kanitla()}}/></div><Olcumler degerler={[{etiket:'Önerilen taşıma',deger:tasima.mod,vurgu:true},{etiket:'Taşıma maliyet indeksi',deger:tasima.maliyet},{etiket:'Enerji etki indeksi',deger:enerjiEtki}]}/><Mekanizma tur={enerjiEtki>55?'uyari':'olumlu'}>Ulaşımda yük ve mesafe; enerjide kaynak, habitat ve yer seçimi birlikte değerlendirilir.</Mekanizma></div>}</ModulKabugu>
  </div>
}
