import { useMemo, useState } from 'react'
import { gunesModeli } from '../../../lib/cografya/modeller.js'
import { BolgeBasligi, Kaydirici, Mekanizma, ModulKabugu, Olcumler } from '../ortak/index.js'

const AYLAR = ['Oca', 'Şub', 'Mar', 'Nis', 'May', 'Haz', 'Tem', 'Ağu', 'Eyl', 'Eki', 'Kas', 'Ara']

export default function GezegenBolgesi() {
  const [enlem, setEnlem] = useState(40)
  const [ay, setAy] = useState(6)
  const model = useMemo(() => gunesModeli(enlem, ay), [enlem, ay])
  const golge = model?.ogleYuksekligi > 0 ? Math.min(8, 1 / Math.tan((model.ogleYuksekligi * Math.PI) / 180)) : 8
  return <div className="ca-bolge"><BolgeBasligi baslik="Gezegen Saati" aciklama="Tarih ve enlem değiştiğinde Güneş açısını, gölgeyi ve mevsimi birlikte izle." renk="#f0b55a" sayi="1"/><ModulKabugu id="gunes-modeli" bolge="gezegen" baslik="Dünya–Güneş modeli" aciklama="Eksen eğikliği ve yıllık dolanımın iki yarım kürede farklı sonuç ürettiğini modelle." yanilgiId="yakinlik-mevsim" tahmin={{ soru: '40° Kuzey’de hazirandan aralığa geçince öğle Güneş yüksekliği ne olur?', secenekler: ['Artar', 'Azalır', 'Değişmez'] }} kontrol={{ soru: 'Kuzey ve Güney Yarım Küre’de aynı tarihte mevsimlerin ters olmasının ana nedeni nedir?', secenekler: ['Dünya’nın Güneş’e uzaklığı', 'Eksen eğikliği ve ışın açısı', 'Boylam farkı'], cevap: 1, aciklama: 'Eksen eğikliği enerji geliş açısını ve gündüz süresini iki yarım kürede ters düzende değiştirir.' }} transfer={{ soru: '30° Güney’de aralık ayı için hangi sonuç beklenir?', secenekler: ['Yaz ve daha yüksek öğle Güneşi', 'Kış ve daha uzun gölge', 'Mevsim belirlenemez'], cevap: 0, aciklama: 'Güney Yarım Küre aralıkta Güneş’e daha dönüktür.' }}>{({ kanitla }) => <div className="ca-sim-grid"><div className="ca-kontrol-panel"><Kaydirici etiket="Enlem" deger={enlem} min={-70} max={70} birim="°" onChange={(v) => { setEnlem(v); kanitla() }} alt="70° G" ust="70° K"/><Kaydirici etiket="Ay" deger={ay} min={1} max={12} onChange={(v) => { setAy(v); kanitla() }} alt="Ocak" ust="Aralık"/><Olcumler degerler={[{ etiket: 'Ay', deger: AYLAR[ay - 1] }, { etiket: 'Yarım küre', deger: model.yarimKure }, { etiket: 'Mevsim', deger: model.mevsim }, { etiket: 'Öğle Güneşi', deger: model.ogleYuksekligi.toFixed(1), birim: '°', vurgu: true }]}/><Mekanizma>{model.yarimKure} Yarım Küre’de {AYLAR[ay - 1]}: ışın yüksekliği {model.ogleYuksekligi.toFixed(1)}°. Gölge {golge > 2 ? 'uzun' : 'kısa'} olur.</Mekanizma></div><div className="ca-gezegen-sahne" style={{ '--gunes-y': `${78 - model.ogleYuksekligi * 0.58}%`, '--golge': `${20 + golge * 12}%` }} role="img" aria-label={`Güneş yüksekliği ${model.ogleYuksekligi.toFixed(1)} derece; ${model.mevsim}`}><div className="gunes"/><div className="isinlar"/><div className="dunya"><i/><span>{enlem}°</span></div><div className="zemin"><i/></div><p>Model şematiktir · eksen eğikliği 23,44°</p></div></div>}</ModulKabugu></div>
}
