import { useMemo, useState } from 'react'
import { piramitOzeti, yogunluklar } from '../../../lib/cografya/nufus.js'
import { BolgeBasligi, Kaydirici, Mekanizma, ModulKabugu, Olcumler, SutunGrafigi } from '../ortak/index.js'

export default function NufusBolgesi(){
  const [nufus,setNufus]=useState(8); const [alan,setAlan]=useState(40); const [tarim,setTarim]=useState(12); const [ciftci,setCiftci]=useState(2)
  const [genc,setGenc]=useState(40); const [calisma,setCalisma]=useState(50); const [yasli,setYasli]=useState(10)
  const y=useMemo(()=>yogunluklar({nufus:nufus*1e6,toplamAlan:alan*1e3,tarimAlani:tarim*1e3,ciftciNufusu:ciftci*1e6}),[nufus,alan,tarim,ciftci])
  const p=useMemo(()=>piramitOzeti({genc,calisma,yasli}),[genc,calisma,yasli])
  return <div className="ca-bolge"><BolgeBasligi bolge="nufus" aciklama="Aynı nüfus verisinin alan türüne ve yaş yapısına göre nasıl farklı anlamlar ürettiğini keşfet."/>
    <ModulKabugu id="yogunluk-laboratuvari" bolge="nufus" baslik="Üç yoğunluk, üç soru" aciklama="Aritmetik, fizyolojik ve tarımsal yoğunluğu aynı veri üzerinde karşılaştır." yanilgiId="yogunluk-gelisme" tahmin={{soru:'Tarım alanı çok sınırlıysa fizyolojik yoğunluk nasıl etkilenir?',secenekler:['Yükselir','Düşer','Değişmez']}} kontrol={{soru:'Toplam nüfus / tarım alanı hangi yoğunluktur?',secenekler:['Aritmetik','Fizyolojik','Tarımsal'],cevap:1,aciklama:'Fizyolojik yoğunluk, nüfusun üretilebilir tarım alanı üzerindeki baskısını gösterir.'}} transfer={{soru:'Aritmetik yoğunluğu düşük ama fizyolojik yoğunluğu yüksek ülkede ne düşünülebilir?',secenekler:['Tarım alanı toplam alana göre sınırlıdır','Nüfus kesin azdır','Gelişmişlik kesin yüksektir'],cevap:0,aciklama:'Dağ, çöl gibi kullanılamayan geniş alanlar aritmetik değeri düşürürken tarım alanı baskısı yüksek kalabilir.'}}>{({kanitla})=><div><div className="ca-kontrol-dortlu"><Kaydirici etiket="Nüfus" deger={nufus} min={1} max={40} birim=" milyon" onChange={v=>{setNufus(v);kanitla()}}/><Kaydirici etiket="Toplam alan" deger={alan} min={5} max={100} birim=" bin km²" onChange={v=>{setAlan(v);kanitla()}}/><Kaydirici etiket="Tarım alanı" deger={tarim} min={2} max={40} birim=" bin km²" onChange={v=>{setTarim(v);kanitla()}}/><Kaydirici etiket="Çiftçi nüfusu" deger={ciftci} min={1} max={10} birim=" milyon" onChange={v=>{setCiftci(v);kanitla()}}/></div><Olcumler degerler={[{etiket:'Aritmetik',deger:y.aritmetik.toFixed(0),birim:' kişi/km²'},{etiket:'Fizyolojik',deger:y.fizyolojik.toFixed(0),birim:' kişi/km²',vurgu:true},{etiket:'Tarımsal',deger:y.tarimsal.toFixed(0),birim:' çiftçi/km²'}]}/><Mekanizma>Payda değiştiğinde cevaplanan soru da değişir: toplam alan, tarım alanı ve çiftçi baskısı aynı kavram değildir.</Mekanizma></div>}</ModulKabugu>
    <ModulKabugu id="nufus-piramidi" bolge="nufus" baslik="Nüfus piramidi stüdyosu" aciklama="Yaş gruplarını değiştir; bağımlılık oranı, hizmet ihtiyacı ve büyüme eğilimini birlikte yorumla." yanilgiId="determinist" tahmin={{soru:'Genç nüfus payı çok yüksekse kısa vadede hangi ihtiyaç öne çıkar?',secenekler:['Eğitim ve çocuk hizmetleri','Yalnız huzurevi','Liman kapasitesi']}} kontrol={{soru:'Tabanı geniş bir piramit en doğrudan neyi gösterir?',secenekler:['Genç yaş grubunun yüksek payını','Kesin yüksek gelir düzeyini','Kesin göç nedenini'],cevap:0,aciklama:'Piramidin tabanı çocuk ve genç yaş gruplarının göreli payını gösterir.'}} transfer={{soru:'Yaşlı payı artan bir yerde hangi planlama daha anlamlıdır?',secenekler:['Sağlık ve erişilebilirlik hizmetlerini güçlendirmek','Okulları koşulsuz iki katına çıkarmak','Tarım alanını küçültmek'],cevap:0,aciklama:'Yaş yapısı hizmet talebini değiştirir; planlama nüfus bileşimine dayanmalıdır.'}}>{({kanitla})=><div className="ca-sim-grid"><div className="ca-kontrol-panel"><Kaydirici etiket="Genç grup" deger={genc} min={5} max={70} onChange={v=>{setGenc(v);kanitla()}}/><Kaydirici etiket="Çalışma çağı" deger={calisma} min={20} max={75} onChange={v=>{setCalisma(v);kanitla()}}/><Kaydirici etiket="Yaşlı grup" deger={yasli} min={3} max={45} onChange={v=>{setYasli(v);kanitla()}}/><Olcumler degerler={[{etiket:'Piramit tipi',deger:p.tip,vurgu:true},{etiket:'Bağımlılık',deger:p.bagimlilik.toFixed(0),birim:'%'}]}/></div><div><SutunGrafigi veriler={p.paylar.map(v=>Math.round(v))} etiketler={['0–14','15–64','65+']} renk="#d9b35c" birim="%" aciklama="Yaş gruplarının normalize edilmiş payları."/><Mekanizma>{p.tip==='yaşlanan'?'Sağlık, bakım ve erişilebilirlik talebi öne çıkar.':p.tip.startsWith('genç')?'Eğitim ve gelecekte istihdam kapasitesi öne çıkar.':'Çalışma çağı payı fırsat yaratabilir; nitelik ve istihdam verisi de gerekir.'}</Mekanizma></div></div>}</ModulKabugu>
  </div>
}
