import { useState } from 'react'
import { Check, Compass, X } from 'lucide-react'
import { YANILGILAR } from '../../../data/cografya/yanilgilar.js'
import { BolgeBasligi } from '../ortak/index.js'

export default function PusulaBolgesi(){
  const [acik,setAcik]=useState(YANILGILAR[0].id); const [kararlar,setKararlar]=useState({})
  return <div className="ca-bolge"><BolgeBasligi bolge="pusula" etiket="Kavram Kliniği" aciklama="TYT’de sık görülen tek-nedenli çıkarımları durdur; iddiayı eksik kanıtıyla birlikte teşhis et." sayi={String(YANILGILAR.length)}/><section className="ca-pusula-ozet"><Compass size={26}/><div><h2>İddia mı, kanıt mı?</h2><p>Her kartta önce hüküm ver. Ardından doğru mekanizmayı ve atlanan kanıtı karşılaştır.</p></div><strong>{Object.keys(kararlar).length}/{YANILGILAR.length}</strong></section><div className="ca-pusula-grid">{YANILGILAR.map(y=>{const karar=kararlar[y.id];return <article key={y.id} className={acik===y.id?'acik':''}><button type="button" className="ca-pusula-baslik" aria-expanded={acik===y.id} onClick={()=>setAcik(acik===y.id?null:y.id)}><span>{y.bolge.replaceAll('-',' ')}</span><strong>{y.iddia}</strong></button>{acik===y.id?<div className="ca-pusula-icerik"><p>Bu iddia coğrafi kanıt açısından yeterli mi?</p><div><button type="button" className={karar===false?'secili':''} onClick={()=>setKararlar({...kararlar,[y.id]:false})}>Eksik / yanıltıcı</button><button type="button" className={karar===true?'secili':''} onClick={()=>setKararlar({...kararlar,[y.id]:true})}>Yeterli</button></div>{karar!==undefined?<aside className={karar?'yanlis':'dogru'}>{karar?<X size={18}/>:<Check size={18}/>}<div><strong>{karar?'Kanıt eksik':'Doğru teşhis'}</strong><p>{y.dogrusu}</p><small>Atlanan kanıt: {y.eksikKanit}</small></div></aside>:null}</div>:null}</article>})}</div></div>
}
