import { useMemo, useState } from 'react'
import { BolgeBasligi, Kaydirici, Mekanizma, ModulKabugu, Olcumler, Secim, SutunGrafigi } from '../ortak/index.js'

const BIYOMLAR = {
  tundra:{sicaklik:-8,yagis:220,bitki:'Yosun, liken ve bodur çalı',toprak:'Donmuş tabaka; yavaş ayrışma'},
  bozkir:{sicaklik:12,yagis:380,bitki:'Kısa boylu otlar',toprak:'Organik maddece görece zengin üst kat'},
  yagmur:{sicaklik:26,yagis:2200,bitki:'Çok katlı, gür orman',toprak:'Hızlı yıkanma ve ayrışma'},
}

export default function YasamKusaklariBolgesi(){
  const [yagis,setYagis]=useState(65); const [kar,setKar]=useState(35); const [gecirgenlik,setGecirgenlik]=useState(45); const [kent,setKent]=useState(25); const [biyom,setBiyom]=useState('bozkir')
  const havza=useMemo(()=>{const yuzey=Math.round(yagis*(.45+kent/200)*(1-gecirgenlik/160)); const yeralti=Math.round(yagis*gecirgenlik/130); const gecikmeli=Math.round(kar*.65); return {yuzey,yeralti,gecikmeli,toplam:yuzey+yeralti+gecikmeli}},[yagis,kar,gecirgenlik,kent])
  const b=BIYOMLAR[biyom]
  return <div className="ca-bolge"><BolgeBasligi baslik="Yaşam Kuşakları" aciklama="Su, toprak, bitki ve insanı aynı sistemde okuyarak mekânsal desenleri açıkla." renk="#71c97d" sayi="2"/>
    <ModulKabugu id="havza-rejimi" bolge="yasam-kusaklari" baslik="Havza ve akarsu rejimi" aciklama="Yağış, kar, geçirgenlik ve kentleşmenin akış bileşenlerini nasıl değiştirdiğini izle." yanilgiId="akarsu-guney" tahmin={{soru:'Geçirimsiz yüzey arttığında kısa süreli yüzey akışı nasıl değişir?',secenekler:['Artar','Azalır','Kesin sıfırlanır']}} kontrol={{soru:'Kar erimesiyle ilkbaharda yükselen akım neyin kanıtıdır?',secenekler:['Gecikmeli beslenmenin','Boylam farkının','Nüfus yoğunluğunun'],cevap:0,aciklama:'Kışın depolanan kar suyu, erime döneminde akarsuya gecikmeli katılır.'}} transfer={{soru:'Aynı yağış alan iki havzadan kentleşmiş olanda taşkın piki neden daha yüksek olabilir?',secenekler:['Sızma azalır, yüzey akışı hızlanır','Dağlar alçalır','Mutlak konum değişir'],cevap:0,aciklama:'Geçirimsiz yüzey suyu kısa sürede akarsu yatağına taşır.'}}>{({kanitla})=><div><div className="ca-kontrol-dortlu"><Kaydirici etiket="Yağış" deger={yagis} min={0} max={100} onChange={v=>{setYagis(v);kanitla()}}/><Kaydirici etiket="Kar deposu" deger={kar} min={0} max={100} onChange={v=>{setKar(v);kanitla()}}/><Kaydirici etiket="Geçirgenlik" deger={gecirgenlik} min={0} max={100} onChange={v=>{setGecirgenlik(v);kanitla()}}/><Kaydirici etiket="Kentleşme" deger={kent} min={0} max={100} onChange={v=>{setKent(v);kanitla()}}/></div><div className="ca-sim-grid"><SutunGrafigi veriler={[havza.yuzey,havza.yeralti,havza.gecikmeli]} etiketler={['Yüzey','Yer altı','Kar erimesi']} renk="#59b8df" birim=" akış" aciklama="Havzaya katılan şematik akış bileşenleri."/><div><Olcumler degerler={[{etiket:'Toplam akış indeksi',deger:havza.toplam,vurgu:true},{etiket:'Baskın beslenme',deger:havza.yuzey>havza.yeralti?'yüzey':'yer altı'}]}/><Mekanizma>Yağış girdisi → depolama/sızma → yüzey ve yer altı akışı → akarsu rejimi</Mekanizma></div></div></div>}</ModulKabugu>
    <ModulKabugu id="toprak-biyom" bolge="yasam-kusaklari" baslik="Toprak–biyom eşleştirme laboratuvarı" aciklama="Sıcaklık ve yağış deseninden bitki ile toprak süreçlerine uzanan zinciri kur." yanilgiId="ayni-enlem" tahmin={{soru:'Sıcak ve yıl boyu çok yağışlı ortamda ayrışma hızı nasıldır?',secenekler:['Genellikle hızlı','Daima yok','Yalnız enleme bağlı']}} kontrol={{soru:'Benzer enlemde farklı biyom görülmesini en iyi ne açıklar?',secenekler:['Yalnız Dünya’nın şekli','Yükselti, denizellik ve hava kütleleri gibi ek etkenler','Saat dilimi'],cevap:1,aciklama:'Enlem enerji dağılışını etkiler ama biyomu tek başına belirlemez.'}} transfer={{soru:'Yağışın azaldığı yarı kurak alanda ormanın yerini ne alabilir?',secenekler:['Bozkır/çalı topluluğu','Tropikal yağmur ormanı','Buzul örtüsü kesin'],cevap:0,aciklama:'Su kısıtı daha kısa ve seyrek bitki formasyonlarını destekler.'}}>{({kanitla})=><div className="ca-sim-grid"><div className="ca-kontrol-panel"><Secim etiket="Yaşam kuşağı" deger={biyom} secenekler={[{value:'tundra',label:'Tundra'},{value:'bozkir',label:'Bozkır'},{value:'yagmur',label:'Tropikal yağmur ormanı'}]} onChange={v=>{setBiyom(v);kanitla()}}/><Olcumler degerler={[{etiket:'Ort. sıcaklık',deger:b.sicaklik,birim:'°C'},{etiket:'Yıllık yağış',deger:b.yagis,birim:'mm',vurgu:true},{etiket:'Bitki',deger:b.bitki},{etiket:'Toprak süreci',deger:b.toprak}]}/><Mekanizma>İklim → ayrışma ve su bütçesi → toprak özellikleri → bitki topluluğu</Mekanizma></div><div className={`ca-biyom-sahne ${biyom}`}><div className="gunes">☀</div><div className="bitkiler"><i/><i/><i/><i/><i/></div><div className="toprak"><span>{b.toprak}</span></div></div></div>}</ModulKabugu>
  </div>
}
