import { useMemo, useState } from 'react'
import { BolgeBasligi, Kaydirici, Mekanizma, ModulKabugu, Olcumler, Secim } from '../ortak/index.js'

const SINIRLAR = {
  yaklasan: { ad: 'Yaklaşan levhalar', hareket: '→ ←', urun: 'Sıkışma, kıvrım/volkanizma ve deprem', renk: '#ef8b65' },
  uzaklasan: { ad: 'Uzaklaşan levhalar', hareket: '← →', urun: 'Yeni kabuk ve okyanus sırtı', renk: '#5cc9b2' },
  transform: { ad: 'Yanal hareket', hareket: '⇄', urun: 'Fay boyunca deprem', renk: '#b597ef' },
}

export default function YerkureBolgesi() {
  const [sinir, setSinir] = useState('yaklasan')
  const [egim, setEgim] = useState(55)
  const [yagis, setYagis] = useState(45)
  const [bitki, setBitki] = useState(35)
  const asindirma = useMemo(() => Math.round(egim * .45 + yagis * .4 + (100 - bitki) * .15), [egim, yagis, bitki])
  const aktif = SINIRLAR[sinir]
  return <div className="ca-bolge"><BolgeBasligi bolge="yerkure" aciklama="Yer şekillerini ezberlenmiş adlardan değil; enerji, süreç ve zaman ilişkisinden çöz."/>
    <ModulKabugu id="levha-surecleri" bolge="yerkure" baslik="Levha sınırları laboratuvarı" aciklama="Hareket yönünü değiştir; oluşabilecek yer şekli ve afet zincirini kanıtla." yanilgiId="sekil-ad" tahmin={{soru:'İki levha birbirine yaklaştığında hangi süreç daha olasıdır?',secenekler:['Sıkışma','Yeni kabuk açılması','Süreç oluşmaz']}} kontrol={{soru:'Transform sınırın en doğrudan sonucu hangisidir?',secenekler:['Yanal faylanma ve deprem','Mercan oluşumu','Delta büyümesi'],cevap:0,aciklama:'Yanal hareket fay boyunca gerilim biriktirir ve boşaltır.'}} transfer={{soru:'Okyanus ortası sırtında genç kayaçların bulunması neyi destekler?',secenekler:['Levhaların uzaklaştığını','Levhaların durduğunu','Akarsu aşındırmasını'],cevap:0,aciklama:'Uzaklaşan levhalar arasından yükselen magma yeni kabuk oluşturur.'}}>{({kanitla})=><div className="ca-sim-grid"><div className="ca-kontrol-panel"><Secim etiket="Levha sınırı" deger={sinir} secenekler={Object.entries(SINIRLAR).map(([value,v])=>({value,label:v.ad}))} onChange={v=>{setSinir(v);kanitla()}}/><Mekanizma tur="bilgi">Manto hareketleri → levha hareketi → gerilim/boşalma → yer şekli ve deprem/volkanizma</Mekanizma><Olcumler degerler={[{etiket:'Hareket',deger:aktif.hareket,vurgu:true},{etiket:'Olası sonuç',deger:aktif.urun}]}/></div><div className={`ca-levha-sahne ${sinir}`} style={{'--levha-renk':aktif.renk}}><div className="levha sol"><span>{aktif.hareket.split(' ')[0]}</span></div><i/><div className="levha sag"><span>{aktif.hareket.split(' ')[1] || '⇄'}</span></div><strong>{aktif.ad}</strong><p>{aktif.urun}</p></div></div>}</ModulKabugu>
    <ModulKabugu id="dis-kuvvetler" bolge="yerkure" baslik="Dış kuvvetler ve süreç dengesi" aciklama="Eğim, yağış ve bitki örtüsünü değiştir; aşındırma şiddetinin tek nedene bağlı olmadığını gör." yanilgiId="akarsu-guney" tahmin={{soru:'Eğim ve yağış artarken bitki örtüsü azalırsa yüzey aşındırması ne olur?',secenekler:['Genellikle artar','Kesin azalır','Değişmez']}} kontrol={{soru:'Bir akarsuyun akış yönünü belirleyen temel kanıt nedir?',secenekler:['Kuzey-güney yönü','Yükselti farkı ve eğim','Kentin nüfusu'],cevap:1,aciklama:'Su, pusula yönünden bağımsız olarak yüksekten alçağa akar.'}} transfer={{soru:'Aynı yağışta ormanlaştırılan yamaçta hangi değişim beklenir?',secenekler:['Yüzey akışı ve erozyon azalabilir','Eğim aniden artar','Akarsu ters akar'],cevap:0,aciklama:'Bitki kökleri toprağı tutar, yüzey akışını yavaşlatır.'}}>{({kanitla})=><div className="ca-sim-grid"><div className="ca-kontrol-panel"><Kaydirici etiket="Eğim" deger={egim} min={5} max={90} birim="%" onChange={v=>{setEgim(v);kanitla()}}/><Kaydirici etiket="Yağış şiddeti" deger={yagis} min={0} max={100} birim="" onChange={v=>{setYagis(v);kanitla()}}/><Kaydirici etiket="Bitki örtüsü" deger={bitki} min={0} max={100} birim="" onChange={v=>{setBitki(v);kanitla()}}/><Olcumler degerler={[{etiket:'Aşındırma indeksi',deger:asindirma,birim:'/100',vurgu:true},{etiket:'Baskın durum',deger:asindirma>65?'güçlü aşındırma':asindirma>35?'orta':'zayıf'}]}/></div><div className="ca-yamac-sahne" style={{'--egim':`${Math.max(12,egim*.55)}deg`,'--bitki':`${bitki}%`,'--akis':`${asindirma}%`}}><div className="bulut">☁</div><div className="yamac"><i/><i/><i/><span>Akış {asindirma}</span></div><Mekanizma>{asindirma>65?'Taşıma gücü yükseldi; çıplak yüzeyde oyulma hızlanır.':'Bitki ve düşük enerji, toprağın taşınmasını sınırlar.'}</Mekanizma></div></div>}</ModulKabugu>
  </div>
}
