import { useMemo, useState } from 'react'
import { yerSecimPuani } from '../../../lib/cografya/modeller.js'
import { BolgeBasligi, Kaydirici, Mekanizma, ModulKabugu, Olcumler, Secim } from '../ortak/index.js'

const ALANLAR={
  ova:{ad:'Akarsu ovası',su:95,ulasim:80,zemin:30,tarim:90,risk:35},
  plato:{ad:'Plato eşiği',su:55,ulasim:60,zemin:78,tarim:50,risk:75},
  korfez:{ad:'Körfez kıyısı',su:75,ulasim:90,zemin:48,tarim:35,risk:52},
}

export default function YerlesmeBolgesi(){
  const [alan,setAlan]=useState('ova'); const [is,setIs]=useState(55); const [konut,setKonut]=useState(50); const [ulasim,setUlasim]=useState(55); const [yesil,setYesil]=useState(40)
  const a=ALANLAR[alan]
  const puan=useMemo(()=>Math.round(yerSecimPuani({su:a.su,ulasim:a.ulasim,zemin:a.zemin,tarim:a.tarim,risk:a.risk},{zemin:1.4,risk:1.5,ulasim:1.2})),[a])
  const kent=useMemo(()=>({denge:Math.round((is+konut+ulasim+yesil)/4),baski:Math.max(0,Math.round((konut+ulasim)-(yesil+is)*.65))}),[is,konut,ulasim,yesil])
  return <div className="ca-bolge"><BolgeBasligi baslik="Yerleşme ve Kent Ağı" aciklama="Yer seçimini tek bir avantaja indirgemeden; kaynak, erişim, zemin ve risk bileşimiyle değerlendir." renk="#d684b2" sayi="2"/>
    <ModulKabugu id="yer-secimi" bolge="yerlesme" baslik="Yer seçimi karar masası" aciklama="Üç aday alanı karşılaştır; yerleşmenin neden çok ölçütlü bir karar olduğunu gör." yanilgiId="kiyi-liman" tahmin={{soru:'Ulaşımı çok iyi ama zemini zayıf bir alan otomatik olarak en iyi yerleşme yeri midir?',secenekler:['Hayır, risk ve zemin de gerekir','Evet, her zaman','Yalnız enlem belirler']}} kontrol={{soru:'Sürdürülebilir yer seçimi için hangi kanıt seti daha güçlüdür?',secenekler:['Yalnız manzara','Su, ulaşım, zemin, üretim alanı ve risk birlikte','Sadece nüfus'],cevap:1,aciklama:'Yer seçimi birden çok ihtiyaç ve kısıtın birlikte tartılmasıdır.'}} transfer={{soru:'Kıyıda doğal koyu bulunan küçük kentin büyük limana dönüşmesi için en kritik ek koşul nedir?',secenekler:['Güçlü hinterlant ve ulaşım ağı','Yalnız kıyıda olmak','Ekvatora yaklaşmak'],cevap:0,aciklama:'Liman işlevi, iç bölgelerle üretim ve ticaret bağlantısı kurulduğunda büyür.'}}>{({kanitla})=><div className="ca-sim-grid"><div className="ca-kontrol-panel"><Secim etiket="Aday alan" deger={alan} secenekler={Object.entries(ALANLAR).map(([value,v])=>({value,label:v.ad}))} onChange={v=>{setAlan(v);kanitla()}}/><Olcumler degerler={[{etiket:'Su',deger:a.su},{etiket:'Ulaşım',deger:a.ulasim},{etiket:'Zemin',deger:a.zemin},{etiket:'Tarım',deger:a.tarim},{etiket:'Risk güvenliği',deger:a.risk},{etiket:'Çok ölçütlü puan',deger:puan,vurgu:true}]}/><Mekanizma>{puan>70?'Birden çok ölçütte güçlü; yine de yerel etüt gerekir.':puan>55?'Bazı üstünlükler var, kısıtlar azaltılmalı.':'Tek avantaj karar için yeterli değil; risk ve altyapı zayıf.'}</Mekanizma></div><div className={`ca-yerlesme-sahne ${alan}`}><div className="su"/><div className="yol"/><div className="evler"><i/><i/><i/><i/></div><div className="arazi"/><span>{a.ad}</span></div></div>}</ModulKabugu>
    <ModulKabugu id="kent-agi" bolge="yerlesme" baslik="Kent planlama dengesi" aciklama="İş, konut, ulaşım ve yeşil alan kapasitesini değiştir; tek merkezli büyümenin baskısını izle." yanilgiId="determinist" tahmin={{soru:'Konut ve ulaşım büyürken yeşil alan sabit kalırsa hangi sorun artabilir?',secenekler:['Isı adası ve yaşam baskısı','Enlem değişimi','Levha hızı']}} kontrol={{soru:'Bir kentin etki alanını en iyi hangi kanıt gösterir?',secenekler:['Yalnız yüz ölçümü','Hizmet, ulaşım ve insan akışlarının ulaştığı çevre','Sadece rakım'],cevap:1,aciklama:'Kent ağı, düğümler arasındaki mal, hizmet ve insan akışıyla oluşur.'}} transfer={{soru:'Yeni raylı sistem çevre ilçelerin merkeze erişimini artırırsa ne değişebilir?',secenekler:['Kentin etki alanı genişleyebilir','Boylamı değişir','Dağlar aşınmaz'],cevap:0,aciklama:'Erişim süresi azaldığında günlük iş ve hizmet akışları daha geniş alana yayılabilir.'}}>{({kanitla})=><div className="ca-sim-grid"><div className="ca-kontrol-panel"><Kaydirici etiket="İş olanakları" deger={is} min={10} max={100} onChange={v=>{setIs(v);kanitla()}}/><Kaydirici etiket="Konut kapasitesi" deger={konut} min={10} max={100} onChange={v=>{setKonut(v);kanitla()}}/><Kaydirici etiket="Ulaşım kapasitesi" deger={ulasim} min={10} max={100} onChange={v=>{setUlasim(v);kanitla()}}/><Kaydirici etiket="Yeşil alan" deger={yesil} min={5} max={100} onChange={v=>{setYesil(v);kanitla()}}/><Olcumler degerler={[{etiket:'Denge indeksi',deger:kent.denge,vurgu:true},{etiket:'Kentsel baskı',deger:kent.baski}]}/></div><div className="ca-kent-agi"><div className="merkez" style={{'--boy':`${Math.max(35,is)}%`}}>Merkez</div>{['Konut','Üretim','Eğitim','Rekreasyon'].map((x,i)=><div className={`dugum d${i+1}`} key={x}><i style={{opacity:(i===0?konut:i===1?is:i===2?ulasim:yesil)/100}}/>{x}</div>)}<Mekanizma tur={kent.baski>40?'uyari':'olumlu'}>{kent.baski>40?'Konut ve ulaşım büyümesi kamusal/yeşil kapasiteyi aştı.':'İşlevler daha dengeli; çok merkezli bağlantı baskıyı dağıtabilir.'}</Mekanizma></div></div>}</ModulKabugu>
  </div>
}
