/**
 * DESTE — FUTBOL VE SPOR (Fransızca)
 *
 * Desteler MÜFREDATTAN bağımsızdır: burada seviye değil İLGİ belirleyici.
 * Futbol izleyen bir öğrenci "le but" kelimesini A1'de de öğrenebilir,
 * çünkü onu zaten duyuyor ve merak ediyor. Örnek cümleler gerçek maç
 * anlatımı diliyle yazıldı; ders kitabı cümlesi değil.
 */

export const DESTE = {
  id: 'futbol-spor',
  dil: 'fr',
  ad: 'Futbol ve spor',
  simge: '⚽',
  aciklama: 'Maç anlatımında, tribünde ve spor haberlerinde en çok geçen kelimeler.',
  seviye: 'A1–A2',
  kartlar: [
    {
      id: 'fr-fut-01', on: 'le but', okunus: 'lö bü', tur: 'isim',
      arka: 'gol; kale',
      ornek: 'Mbappé a marqué un but à la 90e minute.',
      ornekTr: 'Mbappé 90. dakikada gol attı.',
      not: 'Gol atmak "marquer un but"tur. Aynı kelime "amaç, hedef" anlamına da gelir.',
    },
    {
      id: 'fr-fut-02', on: 'le match', okunus: 'lö maç', tur: 'isim',
      arka: 'maç',
      ornek: 'Le match commence à vingt heures.',
      ornekTr: 'Maç saat sekizde başlıyor.',
      not: 'İngilizceden geçmiştir ama Fransızcada erildir: LE match.',
    },
    {
      id: 'fr-fut-03', on: "l'équipe", okunus: 'lekip', tur: 'isim (dişil)',
      arka: 'takım',
      ornek: "Mon équipe préférée a gagné hier soir.",
      ornekTr: 'En sevdiğim takım dün akşam kazandı.',
      not: 'Dişildir: UNE équipe. Türkçedeki "ekip" kelimesi buradan gelir.',
    },
    {
      id: 'fr-fut-04', on: 'gagner', okunus: 'ganye', tur: 'fiil',
      arka: 'kazanmak',
      ornek: "On va gagner ce match, j'en suis sûr.",
      ornekTr: 'Bu maçı kazanacağız, eminim.',
      not: 'Karşıtı "perdre" (kaybetmek). Para kazanmak için de aynı fiil kullanılır.',
    },
    {
      id: 'fr-fut-05', on: 'perdre', okunus: 'perdr', tur: 'fiil',
      arka: 'kaybetmek',
      ornek: "Ils ont perdu deux à zéro.",
      ornekTr: 'İki sıfır kaybettiler.',
      not: 'Skor "à" ile söylenir: deux à zéro (2-0).',
    },
    {
      id: 'fr-fut-06', on: "l'entraîneur", okunus: 'lantrenör', tur: 'isim',
      arka: 'teknik direktör, antrenör',
      ornek: "L'entraîneur a changé trois joueurs.",
      ornekTr: 'Teknik direktör üç oyuncu değiştirdi.',
      not: 'Dişili "l\'entraîneuse"dur. Antrenman ise "l\'entraînement".',
    },
    {
      id: 'fr-fut-07', on: 'le joueur', okunus: 'lö juvör', tur: 'isim',
      arka: 'oyuncu',
      ornek: "C'est le meilleur joueur du monde.",
      ornekTr: 'Dünyanın en iyi oyuncusu.',
      not: 'Dişili "la joueuse". "jouer" (oynamak) fiilinden gelir.',
    },
    {
      id: 'fr-fut-08', on: 'le terrain', okunus: 'lö teren', tur: 'isim',
      arka: 'saha',
      ornek: "Les joueurs entrent sur le terrain.",
      ornekTr: 'Oyuncular sahaya çıkıyor.',
      not: 'Sahaya çıkmak "entrer SUR le terrain"dır; "dans" değil.',
    },
    {
      id: 'fr-fut-09', on: 'supporter', okunus: 'süporte', tur: 'fiil',
      arka: 'tutmak (bir takımı desteklemek)',
      ornek: "Je supporte le PSG depuis que je suis petit.",
      ornekTr: 'Küçüklüğümden beri PSG tutuyorum.',
      not: 'Taraftar "un supporter"dır. Dikkat: bu fiil "katlanmak" anlamına da gelir.',
    },
    {
      id: 'fr-fut-10', on: "s'entraîner", okunus: 'santrene', tur: 'fiil (dönüşlü)',
      arka: 'antrenman yapmak',
      ornek: "Je m'entraîne trois fois par semaine.",
      ornekTr: 'Haftada üç kez antrenman yapıyorum.',
      not: 'Dönüşlü fiildir: je m\'entraîne, tu t\'entraînes…',
    },
    /* --- Mevkiler ve takım --- */
    {
      id: 'fr-fut-11', on: 'le gardien', okunus: 'lö gardiyen', tur: 'isim',
      arka: 'kaleci',
      ornek: 'Le gardien a arrêté trois tirs.',
      ornekTr: 'Kaleci üç şut kurtardı.',
      not: 'Tam hâli "le gardien de but"tur; kısaca "le gardien" denir.',
    },
    {
      id: 'fr-fut-12', on: 'l\'attaquant', okunus: 'latakan', tur: 'isim',
      arka: 'forvet',
      ornek: 'L\'attaquant est très rapide.',
      ornekTr: 'Forvet çok hızlı.',
      not: '"attaquer" (hücum etmek) fiilinden gelir.',
    },
    {
      id: 'fr-fut-13', on: 'le défenseur', okunus: 'lö defansör', tur: 'isim',
      arka: 'defans oyuncusu',
      ornek: 'Le défenseur joue très calmement.',
      ornekTr: 'Defans oyuncusu çok sakin oynuyor.',
      not: '"défendre" savunmak demektir.',
    },
    {
      id: 'fr-fut-14', on: 'l\'arbitre', okunus: 'larbitr', tur: 'isim',
      arka: 'hakem',
      ornek: 'L\'arbitre siffle la fin du match.',
      ornekTr: 'Hakem maçın bitiş düdüğünü çalıyor.',
      not: '"siffler" düdük çalmak demektir.',
    },
    {
      id: 'fr-fut-15', on: 'l\'entraîneur', okunus: 'lantrenör', tur: 'isim',
      arka: 'teknik direktör, antrenör',
      ornek: 'L\'entraîneur change de tactique.',
      ornekTr: 'Antrenör taktik değiştiriyor.',
      not: '"entraîner" çalıştırmak demektir.',
    },
    {
      id: 'fr-fut-16', on: 'le capitaine', okunus: 'lö kapiten', tur: 'isim',
      arka: 'kaptan',
      ornek: 'Le capitaine porte le brassard.',
      ornekTr: 'Kaptan pazubandı takıyor.',
      not: '"le brassard" pazuband demektir.',
    },
    {
      id: 'fr-fut-17', on: 'le remplaçant', okunus: 'lö ramplasan', tur: 'isim',
      arka: 'yedek oyuncu',
      ornek: 'Le remplaçant entre à la mi-temps.',
      ornekTr: 'Yedek oyuncu devrede oyuna giriyor.',
      not: '"remplacer" değiştirmek, yerine geçmek demektir.',
    },
    {
      id: 'fr-fut-18', on: 'l\'équipe', okunus: 'lekip', tur: 'isim',
      arka: 'takım',
      ornek: 'Notre équipe joue bien cette saison.',
      ornekTr: 'Takımımız bu sezon iyi oynuyor.',
      not: 'Dişildir: "une bonne équipe".',
    },
    {
      id: 'fr-fut-19', on: 'le maillot', okunus: 'lö mayo', tur: 'isim',
      arka: 'forma',
      ornek: 'Il porte le maillot numéro dix.',
      ornekTr: 'On numaralı formayı giyiyor.',
      not: 'Türkçedeki "mayo" bu kelimeden gelir ama anlamı formadır.',
    },
    {
      id: 'fr-fut-20', on: 'le club', okunus: 'lö klöb', tur: 'isim',
      arka: 'kulüp',
      ornek: 'Mon club a une longue histoire.',
      ornekTr: 'Kulübümün uzun bir tarihi var.',
      not: 'İngilizceden gelir ama Fransızca okunur.',
    },
    /* --- Maçın içi --- */
    {
      id: 'fr-fut-21', on: 'le coup d\'envoi', okunus: 'lö ku danvua', tur: 'isim',
      arka: 'başlama vuruşu',
      ornek: 'Le coup d\'envoi est à vingt heures.',
      ornekTr: 'Başlama vuruşu saat yirmide.',
      not: '"le coup" vuruş, "envoi" gönderme demektir.',
    },
    {
      id: 'fr-fut-22', on: 'la mi-temps', okunus: 'la mi tan', tur: 'isim',
      arka: 'devre arası; yarı',
      ornek: 'À la mi-temps, le score était de un partout.',
      ornekTr: 'Devre arasında skor birer birdi.',
      not: '"un partout" = birer bir, beraberlik skoru.',
    },
    {
      id: 'fr-fut-23', on: 'le penalty', okunus: 'lö penalti', tur: 'isim',
      arka: 'penaltı',
      ornek: 'L\'arbitre accorde un penalty.',
      ornekTr: 'Hakem penaltı veriyor.',
      not: 'Fransızcada "le coup de pied de réparation" da denir ama uzundur.',
    },
    {
      id: 'fr-fut-24', on: 'le coup franc', okunus: 'lö ku fran', tur: 'isim',
      arka: 'serbest vuruş, frikik',
      ornek: 'Il a marqué sur coup franc.',
      ornekTr: 'Frikikten gol attı.',
      not: 'Edatı "sur"dur: marquer sur coup franc.',
    },
    {
      id: 'fr-fut-25', on: 'le corner', okunus: 'lö kornér', tur: 'isim',
      arka: 'korner',
      ornek: 'Ils ont obtenu six corners.',
      ornekTr: 'Altı korner kazandılar.',
      not: '"obtenir" elde etmek demektir.',
    },
    {
      id: 'fr-fut-26', on: 'le hors-jeu', okunus: 'lö or jö', tur: 'isim',
      arka: 'ofsayt',
      ornek: 'Le but est refusé pour hors-jeu.',
      ornekTr: 'Gol ofsayt nedeniyle iptal edildi.',
      not: '"hors" dışında, "jeu" oyun demektir.',
    },
    {
      id: 'fr-fut-27', on: 'la faute', okunus: 'la fot', tur: 'isim',
      arka: 'faul; hata',
      ornek: 'C\'était une faute évidente.',
      ornekTr: 'Bu açık bir fauldü.',
      not: 'Aynı kelime yazım hatası anlamına da gelir: "une faute d\'orthographe".',
    },
    {
      id: 'fr-fut-28', on: 'le carton jaune', okunus: 'lö karton jon', tur: 'isim',
      arka: 'sarı kart',
      ornek: 'Il a reçu un carton jaune.',
      ornekTr: 'Sarı kart gördü.',
      not: 'Kırmızı kart "le carton rouge"dur.',
    },
    {
      id: 'fr-fut-29', on: 'les prolongations', okunus: 'le prolongasyon', tur: 'isim (çoğul)',
      arka: 'uzatmalar',
      ornek: 'Le match est allé aux prolongations.',
      ornekTr: 'Maç uzatmalara gitti.',
      not: 'Her zaman çoğul kullanılır.',
    },
    {
      id: 'fr-fut-30', on: 'le but contre son camp', okunus: 'lö bü kontr son kan', tur: 'isim',
      arka: 'kendi kalesine gol',
      ornek: 'Il a marqué un but contre son camp.',
      ornekTr: 'Kendi kalesine gol attı.',
      not: '"le camp" taraf, kamp demektir.',
    },
    /* --- Oyun fiilleri --- */
    {
      id: 'fr-fut-31', on: 'marquer', okunus: 'marke', tur: 'fiil',
      arka: 'gol atmak; işaretlemek',
      ornek: 'Il marque souvent en deuxième mi-temps.',
      ornekTr: 'Sık sık ikinci yarıda gol atıyor.',
      not: 'Gol için doğru fiil budur; "faire un but" doğal değildir.',
    },
    {
      id: 'fr-fut-32', on: 'tirer', okunus: 'tire', tur: 'fiil',
      arka: 'şut atmak; çekmek',
      ornek: 'Il tire de vingt mètres.',
      ornekTr: 'Yirmi metreden şut atıyor.',
      not: 'Şutun kendisi "le tir"dir.',
    },
    {
      id: 'fr-fut-33', on: 'passer le ballon', okunus: 'pase lö balon', tur: 'kalıp',
      arka: 'topu paslamak',
      ornek: 'Il passe le ballon à gauche.',
      ornekTr: 'Topu sola paslıyor.',
      not: '"le ballon" top, "la balle" küçük toptur (tenis gibi).',
    },
    {
      id: 'fr-fut-34', on: 'arrêter', okunus: 'arete', tur: 'fiil',
      arka: 'durdurmak, kurtarmak',
      ornek: 'Le gardien arrête le tir.',
      ornekTr: 'Kaleci şutu kurtarıyor.',
      not: 'Kurtarış "un arrêt"tir.',
    },
    {
      id: 'fr-fut-35', on: 'dribbler', okunus: 'drible', tur: 'fiil',
      arka: 'çalım atmak',
      ornek: 'Elle dribble deux défenseurs.',
      ornekTr: 'İki defans oyuncusunu çalımlıyor.',
      not: 'İngilizceden gelir ama Fransızca çekilir.',
    },
    {
      id: 'fr-fut-36', on: 'faire match nul', okunus: 'fer maç nül', tur: 'kalıp',
      arka: 'berabere kalmak',
      ornek: 'Nous faisons match nul assez souvent.',
      ornekTr: 'Oldukça sık berabere kalıyoruz.',
      not: '"nul" burada sıfırlı, sonuçsuz anlamındadır.',
    },
    {
      id: 'fr-fut-37', on: 'la victoire', okunus: 'la viktuar', tur: 'isim',
      arka: 'galibiyet',
      ornek: 'La victoire était importante pour nous.',
      ornekTr: 'Galibiyet bizim için önemliydi.',
      not: 'Karşıtı "la défaite" = yenilgi.',
    },
    {
      id: 'fr-fut-38', on: 'la défaite', okunus: 'la defet', tur: 'isim',
      arka: 'yenilgi',
      ornek: 'Après la défaite, tout le monde était triste.',
      ornekTr: 'Yenilgiden sonra herkes üzgündü.',
      not: '"défaire" bozmak fiilinden gelir.',
    },
    {
      id: 'fr-fut-39', on: 'le score', okunus: 'lö skor', tur: 'isim',
      arka: 'skor',
      ornek: 'Le score final est de deux à zéro.',
      ornekTr: 'Nihai skor iki sıfır.',
      not: 'Skor "de ... à ..." kalıbıyla söylenir.',
    },
    {
      id: 'fr-fut-40', on: 'le classement', okunus: 'lö klasman', tur: 'isim',
      arka: 'puan tablosu, sıralama',
      ornek: 'Nous sommes troisièmes au classement.',
      ornekTr: 'Sıralamada üçüncüyüz.',
      not: '"classer" sınıflandırmak, sıralamak demektir.',
    },
    /* --- Lig ve turnuva --- */
    {
      id: 'fr-fut-41', on: 'le championnat', okunus: 'lö şampiyona', tur: 'isim',
      arka: 'lig, şampiyona',
      ornek: 'Le championnat commence en août.',
      ornekTr: 'Lig ağustosta başlıyor.',
      not: 'Türkçedeki "şampiyona" bu kelimeden gelir.',
    },
    {
      id: 'fr-fut-42', on: 'la coupe', okunus: 'la kup', tur: 'isim',
      arka: 'kupa',
      ornek: 'Ils ont gagné la coupe.',
      ornekTr: 'Kupayı kazandılar.',
      not: 'Aynı kelime "kesim, saç kesimi" anlamına da gelir.',
    },
    {
      id: 'fr-fut-43', on: 'la finale', okunus: 'la final', tur: 'isim',
      arka: 'final',
      ornek: 'La finale aura lieu à Paris.',
      ornekTr: 'Final Paris\'te yapılacak.',
      not: '"avoir lieu" = gerçekleşmek.',
    },
    {
      id: 'fr-fut-44', on: 'le derby', okunus: 'lö derbi', tur: 'isim',
      arka: 'derbi',
      ornek: 'Le derby est toujours complet.',
      ornekTr: 'Derbi her zaman tıklım tıklım.',
      not: '"complet" burada biletleri tükenmiş demektir.',
    },
    {
      id: 'fr-fut-45', on: 'la descente', okunus: 'la desant', tur: 'isim',
      arka: 'küme düşme',
      ornek: 'Le club a évité la descente.',
      ornekTr: 'Kulüp küme düşmekten kurtuldu.',
      not: '"descendre" inmek demektir; çıkış "la montée"dir.',
    },
    {
      id: 'fr-fut-46', on: 'le tournoi', okunus: 'lö turnua', tur: 'isim',
      arka: 'turnuva',
      ornek: 'Notre école organise un tournoi.',
      ornekTr: 'Okulumuz bir turnuva düzenliyor.',
      not: 'Satranç ve tenis için de kullanılır.',
    },
    {
      id: 'fr-fut-47', on: 'la Coupe du monde', okunus: 'la kup dü mond', tur: 'isim',
      arka: 'Dünya Kupası',
      ornek: 'La Coupe du monde a lieu tous les quatre ans.',
      ornekTr: 'Dünya Kupası dört yılda bir yapılır.',
      not: '"tous les quatre ans" = dört yılda bir.',
    },
    {
      id: 'fr-fut-48', on: 'le match aller', okunus: 'lö maç ale', tur: 'isim',
      arka: 'ilk maç (gidiş)',
      ornek: 'Le match aller s\'est terminé zéro à zéro.',
      ornekTr: 'İlk maç sıfır sıfır bitti.',
      not: 'Rövanş "le match retour"dur.',
    },
    {
      id: 'fr-fut-49', on: 'l\'outsider', okunus: 'lutsaydör', tur: 'isim',
      arka: 'zayıf görülen taraf',
      ornek: 'L\'outsider a gagné contre toute attente.',
      ornekTr: 'Zayıf görülen taraf beklenmedik biçimde kazandı.',
      not: '"contre toute attente" = tüm beklentilerin aksine.',
    },
    {
      id: 'fr-fut-50', on: 'le triplé', okunus: 'lö triple', tur: 'isim',
      arka: 'bir maçta üç gol',
      ornek: 'Il a réalisé un triplé hier soir.',
      ornekTr: 'Dün akşam üç gol attı.',
      not: '"trois" (üç) kelimesinden türer.',
    },
    /* --- Taraftar ve stat --- */
    {
      id: 'fr-fut-51', on: 'le stade', okunus: 'lö stad', tur: 'isim',
      arka: 'stat',
      ornek: 'Le stade était plein.',
      ornekTr: 'Stat doluydu.',
      not: '"plein" dolu demektir.',
    },
    {
      id: 'fr-fut-52', on: 'les tribunes', okunus: 'le tribün', tur: 'isim (çoğul)',
      arka: 'tribünler',
      ornek: 'Nous étions dans les tribunes.',
      ornekTr: 'Tribünlerdeydik.',
      not: 'Edatı "dans"tır.',
    },
    {
      id: 'fr-fut-53', on: 'l\'ambiance', okunus: 'lambiyans', tur: 'isim',
      arka: 'atmosfer, ortam',
      ornek: 'L\'ambiance au stade était incroyable.',
      ornekTr: 'Stattaki atmosfer inanılmazdı.',
      not: 'Restoran ve parti için de kullanılır.',
    },
    {
      id: 'fr-fut-54', on: 'à domicile', okunus: 'a domisil', tur: 'kalıp',
      arka: 'iç sahada',
      ornek: 'Nous jouons à domicile samedi.',
      ornekTr: 'Cumartesi iç sahada oynuyoruz.',
      not: 'Deplasman "à l\'extérieur"dür.',
    },
    {
      id: 'fr-fut-55', on: 'l\'écharpe', okunus: 'leşarp', tur: 'isim',
      arka: 'atkı (takım atkısı)',
      ornek: 'Les supporters lèvent leurs écharpes.',
      ornekTr: 'Taraftarlar atkılarını kaldırıyor.',
      not: 'Kışlık atkı için de aynı kelime kullanılır.',
    },
    {
      id: 'fr-fut-56', on: 'le chant', okunus: 'lö şan', tur: 'isim',
      arka: 'tezahürat, marş',
      ornek: 'Les chants remplissent le stade.',
      ornekTr: 'Tezahüratlar stadı dolduruyor.',
      not: '"chanter" şarkı söylemek demektir.',
    },
    {
      id: 'fr-fut-57', on: 'siffler', okunus: 'sifle', tur: 'fiil',
      arka: 'ıslık çalmak; yuhalamak',
      ornek: 'Le public siffle la décision.',
      ornekTr: 'Seyirci kararı yuhalıyor.',
      not: 'Fransa\'da ıslık alkış değil protestodur.',
    },
    {
      id: 'fr-fut-58', on: 'le public', okunus: 'lö püblik', tur: 'isim',
      arka: 'seyirci, izleyiciler',
      ornek: 'Le public applaudit les joueurs.',
      ornekTr: 'Seyirci oyuncuları alkışlıyor.',
      not: 'Tekil kullanılır ama topluluk anlatır.',
    },
    {
      id: 'fr-fut-59', on: 'l\'abonnement', okunus: 'labonman', tur: 'isim',
      arka: 'kombine, abonelik',
      ornek: 'Mon oncle a un abonnement au stade.',
      ornekTr: 'Amcamın stat kombinesi var.',
      not: 'Dergi ve internet aboneliği için de kullanılır.',
    },
    {
      id: 'fr-fut-60', on: 'complet', okunus: 'komple', tur: 'sıfat',
      arka: 'dolu, biletleri tükenmiş',
      ornek: 'Le stade est complet ce soir.',
      ornekTr: 'Stat bu akşam tamamen dolu.',
      not: 'Otel ve tren için de kullanılır.',
    },
    /* --- Diğer sporlar --- */
    {
      id: 'fr-fut-61', on: 'le basket', okunus: 'lö basket', tur: 'isim',
      arka: 'basketbol',
      ornek: 'Je joue au basket le mercredi.',
      ornekTr: 'Çarşambaları basketbol oynuyorum.',
      not: 'Spor oynarken "jouer à" kalıbı kullanılır: jouer au foot.',
    },
    {
      id: 'fr-fut-62', on: 'le tennis', okunus: 'lö tenis', tur: 'isim',
      arka: 'tenis',
      ornek: 'Roland-Garros est un tournoi de tennis.',
      ornekTr: 'Roland-Garros bir tenis turnuvasıdır.',
      not: 'Fransa\'nın en ünlü spor organizasyonlarındandır.',
    },
    {
      id: 'fr-fut-63', on: 'la natation', okunus: 'la natasyon', tur: 'isim',
      arka: 'yüzme',
      ornek: 'La natation est bonne pour le dos.',
      ornekTr: 'Yüzme sırt için iyidir.',
      not: 'Fiili "nager"dir.',
    },
    {
      id: 'fr-fut-64', on: 'le vélo', okunus: 'lö velo', tur: 'isim',
      arka: 'bisiklet',
      ornek: 'Je fais du vélo tous les jours.',
      ornekTr: 'Her gün bisiklete biniyorum.',
      not: 'Spor yaparken "faire du" kalıbı kullanılır: faire du sport.',
    },
    {
      id: 'fr-fut-65', on: 'l\'athlétisme', okunus: 'latletism', tur: 'isim',
      arka: 'atletizm',
      ornek: 'L\'athlétisme demande beaucoup d\'endurance.',
      ornekTr: 'Atletizm çok dayanıklılık ister.',
      not: '"demander" burada gerektirmek anlamındadır.',
    },
    {
      id: 'fr-fut-66', on: 'la médaille', okunus: 'la meday', tur: 'isim',
      arka: 'madalya',
      ornek: 'Elle a gagné une médaille d\'or.',
      ornekTr: 'Altın madalya kazandı.',
      not: 'Altın "or", gümüş "argent", bronz "bronze"dur.',
    },
    {
      id: 'fr-fut-67', on: 'le record', okunus: 'lö rökor', tur: 'isim',
      arka: 'rekor',
      ornek: 'Il a battu le record de l\'école.',
      ornekTr: 'Okul rekorunu kırdı.',
      not: 'Rekor "battre" (kırmak) fiiliyle kullanılır. Sondaki "d" okunmaz.',
    },
    {
      id: 'fr-fut-68', on: 'la compétition', okunus: 'la kompetisyon', tur: 'isim',
      arka: 'yarışma, müsabaka',
      ornek: 'La compétition commence à dix heures.',
      ornekTr: 'Müsabaka saat onda başlıyor.',
      not: '"concourir" yarışmak demektir.',
    },
    {
      id: 'fr-fut-69', on: 'participer à', okunus: 'partisipe a', tur: 'fiil',
      arka: 'katılmak',
      ornek: 'Quarante écoles participent au tournoi.',
      ornekTr: 'Turnuvaya kırk okul katılıyor.',
      not: 'Edatı "à"dır ve düşmez.',
    },
    {
      id: 'fr-fut-70', on: 'le record personnel', okunus: 'lö rökor personel', tur: 'isim',
      arka: 'kişisel rekor',
      ornek: 'Il a amélioré son record personnel.',
      ornekTr: 'Kişisel rekorunu geliştirdi.',
      not: '"améliorer" iyileştirmek demektir.',
    },
    /* --- Antrenman ve beden --- */
    {
      id: 'fr-fut-71', on: 's\'entraîner', okunus: 'santrene', tur: 'fiil (dönüşlü)',
      arka: 'antrenman yapmak',
      ornek: 'Je m\'entraîne trois fois par semaine.',
      ornekTr: 'Haftada üç kez antrenman yapıyorum.',
      not: 'Dönüşlü fiildir: je m\'entraîne, tu t\'entraînes.',
    },
    {
      id: 'fr-fut-72', on: 's\'échauffer', okunus: 'seşofe', tur: 'fiil (dönüşlü)',
      arka: 'ısınmak',
      ornek: 'On s\'échauffe pendant dix minutes.',
      ornekTr: 'On dakika ısınıyoruz.',
      not: '"chaud" sıcak demektir; aynı kökten gelir.',
    },
    {
      id: 'fr-fut-73', on: 's\'étirer', okunus: 'setire', tur: 'fiil (dönüşlü)',
      arka: 'esnemek, germe yapmak',
      ornek: 'Il faut s\'étirer après le sport.',
      ornekTr: 'Spordan sonra germe yapmak gerekir.',
      not: '"il faut" = gerekir; sonrasında mastar gelir.',
    },
    {
      id: 'fr-fut-74', on: 'être en forme', okunus: 'etr an form', tur: 'kalıp',
      arka: 'formda olmak',
      ornek: 'Il est en pleine forme cette saison.',
      ornekTr: 'Bu sezon tam formda.',
      not: '"en pleine forme" = tam formda, çok iyi durumda.',
    },
    {
      id: 'fr-fut-75', on: 'l\'endurance', okunus: 'landürans', tur: 'isim',
      arka: 'dayanıklılık',
      ornek: 'La course développe l\'endurance.',
      ornekTr: 'Koşu dayanıklılığı geliştirir.',
      not: '"durer" sürmek fiilinden gelir.',
    },
    {
      id: 'fr-fut-76', on: 'la blessure', okunus: 'la blesür', tur: 'isim',
      arka: 'sakatlık, yaralanma',
      ornek: 'La blessure n\'était pas grave.',
      ornekTr: 'Sakatlık ciddi değildi.',
      not: 'Fiili "se blesser" = sakatlanmak.',
    },
    {
      id: 'fr-fut-77', on: 'se reposer', okunus: 'sö röpoze', tur: 'fiil (dönüşlü)',
      arka: 'dinlenmek',
      ornek: 'Il se repose après le match.',
      ornekTr: 'Maçtan sonra dinleniyor.',
      not: '"le repos" dinlenme demektir.',
    },
    {
      id: 'fr-fut-78', on: 'abandonner', okunus: 'abandone', tur: 'fiil',
      arka: 'pes etmek, bırakmak',
      ornek: 'Il n\'abandonne jamais.',
      ornekTr: 'Asla pes etmiyor.',
      not: '"ne ... jamais" = asla; iki parça fiili sarar.',
    },
    {
      id: 'fr-fut-79', on: 'se dépasser', okunus: 'sö depase', tur: 'fiil (dönüşlü)',
      arka: 'kendini aşmak',
      ornek: 'Il faut se dépasser à l\'entraînement.',
      ornekTr: 'Antrenmanda kendini aşman gerekir.',
      not: '"dépasser" geçmek, aşmak demektir.',
    },
    {
      id: 'fr-fut-80', on: 'transpirer', okunus: 'transpire', tur: 'fiil',
      arka: 'terlemek',
      ornek: 'On transpire beaucoup en été.',
      ornekTr: 'Yazın çok terleniyor.',
      not: 'Günlük dilde "suer" de kullanılır.',
    },
    /* --- Spor deyimleri --- */
    {
      id: 'fr-fut-81', on: 'avoir la pêche', okunus: 'avuar la peş', tur: 'deyim',
      arka: 'enerjik olmak, formda hissetmek',
      ornek: 'Ce matin, j\'ai la pêche !',
      ornekTr: 'Bu sabah enerji doluyum!',
      not: 'Kelimesi kelimesine "şeftaliye sahip olmak"tır.',
    },
    {
      id: 'fr-fut-82', on: 'jeter l\'éponge', okunus: 'jöte leponj', tur: 'deyim',
      arka: 'havlu atmak, pes etmek',
      ornek: 'Il était fatigué mais il n\'a pas jeté l\'éponge.',
      ornekTr: 'Yorgundu ama pes etmedi.',
      not: 'Boks kökenlidir; sünger atmak imgesinden gelir.',
    },
    {
      id: 'fr-fut-83', on: 'la balle est dans ton camp', okunus: 'la bal e dan ton kan', tur: 'deyim',
      arka: 'Top sende, karar senin',
      ornek: 'J\'ai fait ma part : la balle est dans ton camp.',
      ornekTr: 'Ben üzerime düşeni yaptım: top sende.',
      not: 'Tenisten gelir ve iş dilinde çok kullanılır.',
    },
    {
      id: 'fr-fut-84', on: 'marquer des points', okunus: 'marke de puan', tur: 'deyim',
      arka: 'puan kazanmak, izlenim bırakmak',
      ornek: 'Il a marqué des points avec sa présentation.',
      ornekTr: 'Sunumuyla puan kazandı.',
      not: 'Spor dışında da "iyi izlenim bırakmak" anlamındadır.',
    },
    {
      id: 'fr-fut-85', on: 'être au top', okunus: 'etr o top', tur: 'deyim',
      arka: 'zirvede olmak, çok iyi olmak',
      ornek: 'Cette semaine, elle est au top.',
      ornekTr: 'Bu hafta zirvede.',
      not: 'Gençler arasında çok yaygın bir ifadedir.',
    },
    {
      id: 'fr-fut-86', on: 'ne rien lâcher', okunus: 'nö riyen laşe', tur: 'deyim',
      arka: 'hiç bırakmamak, sonuna kadar direnmek',
      ornek: 'Jusqu\'à la fin, il ne faut rien lâcher.',
      ornekTr: 'Sonuna kadar hiç bırakmamak gerek.',
      not: 'Fransız sporcuların en sevdiği motivasyon sözüdür.',
    },
    {
      id: 'fr-fut-87', on: 'C\'est du sport !', okunus: 'se dü spor', tur: 'deyim',
      arka: 'Bu iş zormuş!',
      ornek: 'Monter ces escaliers, c\'est du sport !',
      ornekTr: 'Bu merdivenleri çıkmak zormuş!',
      not: 'Zorlu her iş için mecazi olarak kullanılır.',
    },
    {
      id: 'fr-fut-88', on: 'avoir le dernier mot', okunus: 'avuar lö dernye mo', tur: 'deyim',
      arka: 'son sözü söylemek',
      ornek: 'Notre équipe a eu le dernier mot.',
      ornekTr: 'Son sözü takımımız söyledi.',
      not: 'Tartışma ve rekabet için kullanılır.',
    },
    {
      id: 'fr-fut-89', on: 'à égalité', okunus: 'a egalite', tur: 'kalıp',
      arka: 'başa baş, eşit',
      ornek: 'Les deux équipes sont à égalité.',
      ornekTr: 'İki takım başa baş.',
      not: '"égal" eşit demektir.',
    },
    {
      id: 'fr-fut-90', on: 'le fair-play', okunus: 'lö fer ple', tur: 'isim',
      arka: 'centilmence oyun',
      ornek: 'Le fair-play compte plus que la victoire.',
      ornekTr: 'Centilmence oyun galibiyetten önemlidir.',
      not: '"compter" burada önemli olmak anlamındadır.',
    },
    /* --- Maç konuşmaları --- */
    {
      id: 'fr-fut-91', on: 'Quel est le score ?', okunus: 'kel e lö skor', tur: 'soru kalıbı',
      arka: 'Skor kaç?',
      ornek: 'Quel est le score à la mi-temps ?',
      ornekTr: 'Devrede skor kaç?',
      not: '"quel" burada "hangi, ne" anlamındadır.',
    },
    {
      id: 'fr-fut-92', on: 'Qui a gagné ?', okunus: 'ki a ganye', tur: 'soru kalıbı',
      arka: 'Kim kazandı?',
      ornek: 'Qui a gagné hier soir ?',
      ornekTr: 'Dün akşam kim kazandı?',
      not: 'Geçmiş zaman "avoir + participe" ile kurulur.',
    },
    {
      id: 'fr-fut-93', on: 'C\'était serré', okunus: 'sete sere', tur: 'kalıp',
      arka: 'Kıl payıydı',
      ornek: 'C\'était serré jusqu\'à la fin.',
      ornekTr: 'Sonuna kadar kıl payıydı.',
      not: '"serrer" sıkmak demektir; skorun sıkışıklığını anlatır.',
    },
    {
      id: 'fr-fut-94', on: 'Bonne chance !', okunus: 'bon şans', tur: 'kalıp',
      arka: 'Bol şans!',
      ornek: 'Bonne chance pour le match !',
      ornekTr: 'Maçta bol şans!',
      not: 'Sınav ve iş için de kullanılır.',
    },
    {
      id: 'fr-fut-95', on: 'On a gagné !', okunus: 'on a ganye', tur: 'kalıp',
      arka: 'Kazandık!',
      ornek: 'On a gagné trois à un !',
      ornekTr: 'Üç bir kazandık!',
      not: 'Günlük Fransızcada "nous" yerine "on" kullanılır.',
    },
    {
      id: 'fr-fut-96', on: 'passionnant', okunus: 'pasyonan', tur: 'sıfat',
      arka: 'heyecan verici',
      ornek: 'Le match était passionnant.',
      ornekTr: 'Maç heyecan vericiydi.',
      not: '"la passion" tutku demektir.',
    },
    {
      id: 'fr-fut-97', on: 'ennuyeux', okunus: 'anüyö', tur: 'sıfat',
      arka: 'sıkıcı',
      ornek: 'La première mi-temps était ennuyeuse.',
      ornekTr: 'İlk yarı sıkıcıydı.',
      not: 'Dişil hâli "ennuyeuse"dür.',
    },
    {
      id: 'fr-fut-98', on: 'mériter', okunus: 'merite', tur: 'fiil',
      arka: 'hak etmek',
      ornek: 'Ils méritent cette victoire.',
      ornekTr: 'Bu galibiyeti hak ediyorlar.',
      not: 'İsmi "le mérite" = liyakat.',
    },
    {
      id: 'fr-fut-99', on: 'dominer', okunus: 'domine', tur: 'fiil',
      arka: 'oyuna hâkim olmak',
      ornek: 'Nous dominons la deuxième mi-temps.',
      ornekTr: 'İkinci yarıya hâkimiz.',
      not: 'İsmi "la domination"dur.',
    },
    {
      id: 'fr-fut-100', on: 'la possession du ballon', okunus: 'la posesyon dü balon', tur: 'isim',
      arka: 'topa sahip olma oranı',
      ornek: 'Ils ont eu soixante pour cent de possession du ballon.',
      ornekTr: 'Topa sahip olma oranları yüzde altmıştı.',
      not: '"pour cent" = yüzde.',
    },
  ],
}

export default DESTE
