/**
 * DESTE — GÜNLÜK KONUŞMA (Fransızca)
 *
 * Ders kitaplarının öğretmediği ama Fransızların sürekli söylediği
 * kalıplar. Bunlar bilinmezse öğrenci gramerini bilse bile konuşulanı
 * anlamaz; bunlar bilinirse dili "yaşayan" hâliyle duymaya başlar.
 *
 * KAYIT UYARISI her kartta var: bu kalıpların çoğu SAMİMİDİR ve resmî
 * ortamda kullanılmaz. Öğrenci bunu bilmeden kullanırsa zor durumda kalır.
 */

export const DESTE = {
  id: 'gunluk-konusma',
  dil: 'fr',
  ad: 'Günlük konuşma',
  simge: '💬',
  aciklama: 'Kitapların yazmadığı, Fransızların sürekli söylediği kalıplar.',
  seviye: 'A2',
  kartlar: [
    {
      id: 'fr-gun-01', on: 'ça va ?', okunus: 'sa va', tur: 'kalıp',
      arka: 'nasılsın? / iyi misin?',
      ornek: "Salut ! Ça va ?",
      ornekTr: 'Selam! Nasılsın?',
      not: 'Hem soru hem cevaptır: "— Ça va ? — Ça va."',
    },
    {
      id: 'fr-gun-02', on: 'quoi de neuf', okunus: 'kua dö nöf', tur: 'kalıp',
      arka: 'ne var ne yok?',
      ornek: "Alors, quoi de neuf depuis la dernière fois ?",
      ornekTr: 'Ee, geçen seferden beri ne var ne yok?',
      not: 'Kelime kelime "yeni ne var" demektir.',
    },
    {
      id: 'fr-gun-03', on: "n'importe quoi", okunus: 'nemport kua', tur: 'kalıp',
      arka: 'saçmalık; her neyse',
      ornek: "Il raconte n'importe quoi.",
      ornekTr: 'Saçmalıyor.',
      not: 'Ton belirleyicidir: kızgın da olabilir şakacı da.',
    },
    {
      id: 'fr-gun-04', on: 'du coup', okunus: 'dü ku', tur: 'bağlaç (günlük)',
      arka: 'e haliyle, o yüzden',
      ornek: "Il pleuvait, du coup on est restés à la maison.",
      ornekTr: 'Yağmur yağıyordu, o yüzden evde kaldık.',
      not: 'Gençlerin en çok kullandığı bağlaç. Resmî yazıda kullanılmaz.',
    },
    {
      id: 'fr-gun-05', on: 'bref', okunus: 'bref', tur: 'kalıp',
      arka: 'kısacası, neyse',
      ornek: "Bref, on a raté le bus.",
      ornekTr: 'Kısacası, otobüsü kaçırdık.',
      not: 'Uzun bir hikâyeyi toparlarken kullanılır.',
    },
    {
      id: 'fr-gun-06', on: "j'ai la flemme", okunus: 'je la flem', tur: 'kalıp',
      arka: 'üşeniyorum, canım istemiyor',
      ornek: "J'ai la flemme de sortir ce soir.",
      ornekTr: 'Bu akşam çıkmaya üşeniyorum.',
      not: 'Çok yaygın ve tamamen samimidir; öğretmene söylenmez.',
    },
    {
      id: 'fr-gun-07', on: 'ça marche', okunus: 'sa marş', tur: 'kalıp',
      arka: 'tamam, olur; çalışıyor',
      ornek: "— On se voit à six heures ? — Ça marche !",
      ornekTr: '— Altıda buluşalım mı? — Olur!',
      not: 'Hem "anlaştık" hem "cihaz çalışıyor" anlamına gelir.',
    },
    {
      id: 'fr-gun-08', on: 'grave', okunus: 'grav', tur: 'zarf (argo)',
      arka: 'çok, kesinlikle',
      ornek: "— Ce film est nul. — Grave !",
      ornekTr: '— Bu film berbat. — Kesinlikle!',
      not: 'Sıfat olarak "ciddi, ağır" demektir; gençlerde onay ünlemidir.',
    },
    {
      id: 'fr-gun-09', on: 'ça me dit rien', okunus: 'sa mö di riyen', tur: 'kalıp',
      arka: 'canım istemiyor; hiç tanıdık gelmiyor',
      ornek: "Le cinéma ? Ça me dit rien ce soir.",
      ornekTr: 'Sinema mı? Bu akşam canım istemiyor.',
      not: 'İki anlamı da vardır; bağlam ayırır.',
    },
    {
      id: 'fr-gun-10', on: 'à plus', okunus: 'a plüs', tur: 'kalıp',
      arka: 'görüşürüz',
      ornek: "Je dois y aller, à plus !",
      ornekTr: 'Gitmem lazım, görüşürüz!',
      not: '"à plus tard"ın kısası. Yazışmada "A+" diye kısaltılır.',
    },
    /* --- Selamlaşma ve vedalaşma --- */
    {
      id: 'fr-gun-11', on: 'Bonjour', okunus: 'bonjur', tur: 'kalıp',
      arka: 'Günaydın / iyi günler',
      ornek: 'Bonjour madame, comment allez-vous ?',
      ornekTr: 'İyi günler hanımefendi, nasılsınız?',
      not: 'Akşamdan sonra "bonsoir" denir.',
    },
    {
      id: 'fr-gun-12', on: 'Coucou', okunus: 'kuku', tur: 'kalıp',
      arka: 'Selam (çok samimi)',
      ornek: 'Coucou, tu es là ?',
      ornekTr: 'Selam, orada mısın?',
      not: 'Yakın arkadaşlar ve aile arasında kullanılır.',
    },
    {
      id: 'fr-gun-13', on: 'Comment ça va ?', okunus: 'koman sa va', tur: 'soru kalıbı',
      arka: 'Nasılsın?',
      ornek: 'Salut ! Comment ça va aujourd\'hui ?',
      ornekTr: 'Selam! Bugün nasılsın?',
      not: 'Resmî hâli "Comment allez-vous ?"dur.',
    },
    {
      id: 'fr-gun-14', on: 'Ça va bien, merci', okunus: 'sa va biyen mersi', tur: 'kalıp',
      arka: 'İyiyim, teşekkürler',
      ornek: 'Ça va bien, merci. Et toi ?',
      ornekTr: 'İyiyim, teşekkürler. Ya sen?',
      not: 'Soruyu geri sormak nezaket gereğidir: "Et toi ?"',
    },
    {
      id: 'fr-gun-15', on: 'Ça fait longtemps', okunus: 'sa fe lontan', tur: 'kalıp',
      arka: 'Görüşmeyeli çok oldu',
      ornek: 'Ça fait longtemps qu\'on ne s\'est pas vus !',
      ornekTr: 'Görüşmeyeli çok oldu!',
      not: '"se voir" görüşmek demektir.',
    },
    {
      id: 'fr-gun-16', on: 'Bonne journée', okunus: 'bon jurne', tur: 'kalıp',
      arka: 'İyi günler',
      ornek: 'Au revoir et bonne journée !',
      ornekTr: 'Hoşça kal, iyi günler!',
      not: 'Akşam için "bonne soirée" denir.',
    },
    {
      id: 'fr-gun-17', on: 'À bientôt', okunus: 'a biyento', tur: 'kalıp',
      arka: 'Yakında görüşürüz',
      ornek: 'Je dois partir. À bientôt !',
      ornekTr: 'Gitmem lazım. Yakında görüşürüz!',
      not: '"à" ile veda kalıpları: à demain, à tout à l\'heure.',
    },
    {
      id: 'fr-gun-18', on: 'Je dois y aller', okunus: 'jö dua i ale', tur: 'kalıp',
      arka: 'Gitmem lazım',
      ornek: 'Désolé, je dois y aller.',
      ornekTr: 'Kusura bakma, gitmem lazım.',
      not: '"y" burada gidilecek yeri temsil eder.',
    },
    {
      id: 'fr-gun-19', on: 'Passe le bonjour à...', okunus: 'pas lö bonjur a', tur: 'kalıp',
      arka: '... selam söyle',
      ornek: 'Passe le bonjour à ton frère.',
      ornekTr: 'Kardeşine selam söyle.',
      not: '"passer" burada iletmek anlamındadır.',
    },
    {
      id: 'fr-gun-20', on: 'Prends soin de toi', okunus: 'pran suen dö tua', tur: 'kalıp',
      arka: 'Kendine iyi bak',
      ornek: 'À demain, prends soin de toi !',
      ornekTr: 'Yarın görüşürüz, kendine iyi bak!',
      not: '"le soin" bakım demektir.',
    },
    /* --- Fikir belirtmek --- */
    {
      id: 'fr-gun-21', on: 'Je pense que', okunus: 'jö pans kö', tur: 'kalıp',
      arka: 'Bence, düşünüyorum ki',
      ornek: 'Je pense qu\'il a raison.',
      ornekTr: 'Bence haklı.',
      not: '"que" sesli harften önce "qu\'" olur.',
    },
    {
      id: 'fr-gun-22', on: 'Je trouve que', okunus: 'jö truv kö', tur: 'kalıp',
      arka: 'Bana kalırsa',
      ornek: 'Je trouve que c\'est trop cher.',
      ornekTr: 'Bana kalırsa çok pahalı.',
      not: '"trouver" bulmak demektir; fikir bildirirken çok kullanılır.',
    },
    {
      id: 'fr-gun-23', on: 'Franchement', okunus: 'franşman', tur: 'zarf',
      arka: 'Açıkçası',
      ornek: 'Franchement, je n\'ai pas aimé.',
      ornekTr: 'Açıkçası beğenmedim.',
      not: '"franc" açık sözlü demektir.',
    },
    {
      id: 'fr-gun-24', on: 'Tu as raison', okunus: 'tü a rezon', tur: 'kalıp',
      arka: 'Haklısın',
      ornek: 'Tu as tout à fait raison.',
      ornekTr: 'Tamamen haklısın.',
      not: '"avoir raison" haklı olmak demektir; "être raison" YANLIŞTIR.',
    },
    {
      id: 'fr-gun-25', on: 'Je ne suis pas d\'accord', okunus: 'jö nö süi pa dakor', tur: 'kalıp',
      arka: 'Katılmıyorum',
      ornek: 'Désolé, je ne suis pas d\'accord.',
      ornekTr: 'Kusura bakma, katılmıyorum.',
      not: '"être d\'accord" hemfikir olmak demektir.',
    },
    {
      id: 'fr-gun-26', on: 'Tout à fait', okunus: 'tut a fe', tur: 'kalıp',
      arka: 'Kesinlikle, aynen',
      ornek: 'Tout à fait, c\'est exactement ça.',
      ornekTr: 'Kesinlikle, tam olarak öyle.',
      not: 'Güçlü bir onay ifadesidir.',
    },
    {
      id: 'fr-gun-27', on: 'd\'un côté... de l\'autre', okunus: 'dön kote... dö lotr', tur: 'kalıp',
      arka: 'bir yandan... öte yandan',
      ornek: 'D\'un côté c\'est cher, de l\'autre c\'est bien.',
      ornekTr: 'Bir yandan pahalı, öte yandan iyi.',
      not: 'Kompozisyonda iki yönü dengelemenin klasik yoludur.',
    },
    {
      id: 'fr-gun-28', on: 'ça se peut', okunus: 'sa sö pö', tur: 'kalıp',
      arka: 'Olabilir',
      ornek: 'Il va pleuvoir ? - Ça se peut.',
      ornekTr: 'Yağmur yağacak mı? - Olabilir.',
      not: '"c\'est possible" ile aynı anlamdadır.',
    },
    {
      id: 'fr-gun-29', on: 'Je ne suis pas sûr', okunus: 'jö nö süi pa sür', tur: 'kalıp',
      arka: 'Emin değilim',
      ornek: 'Je ne suis pas sûr de la réponse.',
      ornekTr: 'Cevaptan emin değilim.',
      not: 'Edatı "de"dir.',
    },
    {
      id: 'fr-gun-30', on: 'ça m\'étonnerait', okunus: 'sa metonre', tur: 'kalıp',
      arka: 'Şaşırırım, sanmıyorum',
      ornek: 'Il va venir ? Ça m\'étonnerait.',
      ornekTr: 'Gelecek mi? Sanmıyorum.',
      not: 'Kibarca şüphe belirtir.',
    },
    /* --- Rica, izin, teşekkür --- */
    {
      id: 'fr-gun-31', on: 'Tu peux...?', okunus: 'tü pö', tur: 'soru kalıbı',
      arka: '... yapabilir misin?',
      ornek: 'Tu peux m\'aider deux minutes ?',
      ornekTr: 'İki dakika bana yardım edebilir misin?',
      not: 'Resmî hâli "Pouvez-vous...?"dur.',
    },
    {
      id: 'fr-gun-32', on: 'Pourriez-vous...?', okunus: 'purye vu', tur: 'soru kalıbı',
      arka: '... yapabilir misiniz? (kibar)',
      ornek: 'Pourriez-vous répéter, s\'il vous plaît ?',
      ornekTr: 'Tekrar eder misiniz lütfen?',
      not: 'Koşul kipi ricayı kibarlaştırır.',
    },
    {
      id: 'fr-gun-33', on: 'Ça te dérange si...?', okunus: 'sa tö deranj si', tur: 'soru kalıbı',
      arka: '... yapsam rahatsız olur musun?',
      ornek: 'Ça te dérange si j\'ouvre la fenêtre ?',
      ornekTr: 'Pencereyi açsam rahatsız olur musun?',
      not: '"déranger" rahatsız etmek demektir.',
    },
    {
      id: 'fr-gun-34', on: 'Vas-y', okunus: 'va zi', tur: 'kalıp',
      arka: 'Buyur, hadi',
      ornek: 'Je peux prendre ton stylo ? - Vas-y.',
      ornekTr: 'Kalemini alabilir miyim? - Buyur.',
      not: 'İzin vermenin en kısa yoludur.',
    },
    {
      id: 'fr-gun-35', on: 'Avec plaisir', okunus: 'avek plezir', tur: 'kalıp',
      arka: 'Memnuniyetle',
      ornek: 'Tu viens avec nous ? - Avec plaisir !',
      ornekTr: 'Bizimle gelir misin? - Memnuniyetle!',
      not: '"le plaisir" zevk, keyif demektir.',
    },
    {
      id: 'fr-gun-36', on: 'De rien', okunus: 'dö riyen', tur: 'kalıp',
      arka: 'Rica ederim',
      ornek: 'Merci beaucoup ! - De rien.',
      ornekTr: 'Çok teşekkürler! - Rica ederim.',
      not: '"Je vous en prie" daha resmî bir karşılıktır.',
    },
    {
      id: 'fr-gun-37', on: 'Désolé', okunus: 'dezole', tur: 'kalıp',
      arka: 'Üzgünüm, kusura bakma',
      ornek: 'Désolé, j\'ai oublié.',
      ornekTr: 'Kusura bakma, unuttum.',
      not: 'Dişil hâli "désolée"dir ama okunuşu aynıdır.',
    },
    {
      id: 'fr-gun-38', on: 'C\'est pas grave', okunus: 'se pa grav', tur: 'kalıp',
      arka: 'Önemli değil',
      ornek: 'Désolé ! - C\'est pas grave.',
      ornekTr: 'Özür dilerim! - Önemli değil.',
      not: 'Konuşmada "ne" düşer; yazıda "ce n\'est pas grave" olur.',
    },
    {
      id: 'fr-gun-39', on: 'Excuse-moi de te déranger', okunus: 'ekskuz mua dö tö deranje', tur: 'kalıp',
      arka: 'Rahatsız ettiğim için kusura bakma',
      ornek: 'Excuse-moi de te déranger, j\'ai une question.',
      ornekTr: 'Rahatsız ettiğim için kusura bakma, bir sorum var.',
      not: 'Resmî hâlinde "Excusez-moi" kullanılır.',
    },
    {
      id: 'fr-gun-40', on: 'N\'hésite pas', okunus: 'nezit pa', tur: 'kalıp',
      arka: 'Çekinme',
      ornek: 'N\'hésite pas à poser des questions.',
      ornekTr: 'Soru sormaktan çekinme.',
      not: '"hésiter à + mastar" kalıbı kullanılır.',
    },
    /* --- Teklif ve plan --- */
    {
      id: 'fr-gun-41', on: 'Ça te dit ?', okunus: 'sa tö di', tur: 'soru kalıbı',
      arka: 'Ne dersin? Canın ister mi?',
      ornek: 'Un ciné ce soir, ça te dit ?',
      ornekTr: 'Bu akşam sinema, ne dersin?',
      not: 'Olumsuz hâli "ça me dit rien" = canım istemiyor.',
    },
    {
      id: 'fr-gun-42', on: 'On y va ?', okunus: 'on i va', tur: 'soru kalıbı',
      arka: 'Gidelim mi?',
      ornek: 'Il est tard, on y va ?',
      ornekTr: 'Geç oldu, gidelim mi?',
      not: 'Günlük Fransızcada "nous" yerine "on" kullanılır.',
    },
    {
      id: 'fr-gun-43', on: 'Pourquoi pas ?', okunus: 'purkua pa', tur: 'kalıp',
      arka: 'Neden olmasın?',
      ornek: 'Une balade ? Pourquoi pas !',
      ornekTr: 'Yürüyüş mü? Neden olmasın!',
      not: 'Teklifi olumlu ama rahat biçimde kabul eder.',
    },
    {
      id: 'fr-gun-44', on: 'Je suis partant', okunus: 'jö süi partan', tur: 'kalıp',
      arka: 'Ben varım',
      ornek: 'On va au match ? - Je suis partant !',
      ornekTr: 'Maça gidelim mi? - Ben varım!',
      not: '"partir" gitmek fiilinden gelir.',
    },
    {
      id: 'fr-gun-45', on: 'On se retrouve à...', okunus: 'on sö rötruv a', tur: 'kalıp',
      arka: '... buluşuyoruz',
      ornek: 'On se retrouve à six heures devant l\'école.',
      ornekTr: 'Altıda okulun önünde buluşuyoruz.',
      not: '"se retrouver" buluşmak demektir.',
    },
    {
      id: 'fr-gun-46', on: 'Une autre fois', okunus: 'ün otr fua', tur: 'kalıp',
      arka: 'Başka zaman',
      ornek: 'Pas aujourd\'hui, une autre fois.',
      ornekTr: 'Bugün olmaz, başka zaman.',
      not: 'Kibarca reddetmenin standart yoludur.',
    },
    {
      id: 'fr-gun-47', on: 'Je ne peux pas', okunus: 'jö nö pö pa', tur: 'kalıp',
      arka: 'Yapamam, gelemem',
      ornek: 'Je ne peux pas ce soir, j\'ai un contrôle.',
      ornekTr: 'Bu akşam gelemem, sınavım var.',
      not: 'Gerekçe eklemek nezaket gereğidir.',
    },
    {
      id: 'fr-gun-48', on: 'C\'est comme tu veux', okunus: 'se kom tü vö', tur: 'kalıp',
      arka: 'Nasıl istersen',
      ornek: 'Ciné ou parc ? - C\'est comme tu veux.',
      ornekTr: 'Sinema mı park mı? - Nasıl istersen.',
      not: 'Kararı karşı tarafa bırakır.',
    },
    {
      id: 'fr-gun-49', on: 'Ça marche', okunus: 'sa marş', tur: 'kalıp',
      arka: 'Tamam, anlaştık',
      ornek: 'Six heures ? Ça marche.',
      ornekTr: 'Altı mı? Tamam.',
      not: 'Anlaşmayı kesinleştiren kısa bir onaydır.',
    },
    {
      id: 'fr-gun-50', on: 'Je te préviens', okunus: 'jö tö previyen', tur: 'kalıp',
      arka: 'Sana haber veririm',
      ornek: 'Je te préviens ce soir.',
      ornekTr: 'Bu akşam sana haber veririm.',
      not: '"prévenir" önceden haber vermek demektir.',
    },
    /* --- Duygular --- */
    {
      id: 'fr-gun-51', on: 'Je suis content', okunus: 'jö süi kontan', tur: 'kalıp',
      arka: 'Mutluyum',
      ornek: 'Je suis content de te voir.',
      ornekTr: 'Seni gördüğüme sevindim.',
      not: 'Sonrasında "de + mastar" gelir.',
    },
    {
      id: 'fr-gun-52', on: 'J\'en ai marre', okunus: 'jan e mar', tur: 'kalıp',
      arka: 'Bıktım',
      ornek: 'J\'en ai marre de ce temps.',
      ornekTr: 'Bu havadan bıktım.',
      not: 'Edatı "de"dir ve çok yaygın bir ifadedir.',
    },
    {
      id: 'fr-gun-53', on: 'Ça m\'énerve', okunus: 'sa menerv', tur: 'kalıp',
      arka: 'Sinirimi bozuyor',
      ornek: 'Ce bruit, ça m\'énerve.',
      ornekTr: 'Bu gürültü sinirimi bozuyor.',
      not: '"les nerfs" sinirler demektir.',
    },
    {
      id: 'fr-gun-54', on: 'Je suis déçu', okunus: 'jö süi desü', tur: 'kalıp',
      arka: 'Hayal kırıklığına uğradım',
      ornek: 'Je suis déçu du résultat.',
      ornekTr: 'Sonuç beni hayal kırıklığına uğrattı.',
      not: '"décevoir" hayal kırıklığına uğratmak demektir.',
    },
    {
      id: 'fr-gun-55', on: 'Je suis stressé', okunus: 'jö süi strese', tur: 'kalıp',
      arka: 'Stresliyim',
      ornek: 'Je suis stressé à cause de l\'examen.',
      ornekTr: 'Sınav yüzünden stresliyim.',
      not: '"à cause de" = yüzünden (olumsuz sebep).',
    },
    {
      id: 'fr-gun-56', on: 'Quelle chance !', okunus: 'kel şans', tur: 'ünlem',
      arka: 'Ne şans!',
      ornek: 'Tu as gagné ? Quelle chance !',
      ornekTr: 'Kazandın mı? Ne şans!',
      not: '"la chance" şans demektir.',
    },
    {
      id: 'fr-gun-57', on: 'Dommage', okunus: 'domaj', tur: 'kalıp',
      arka: 'Yazık',
      ornek: 'Tu ne viens pas ? Dommage.',
      ornekTr: 'Gelmiyor musun? Yazık.',
      not: '"C\'est dommage" biçiminde de kullanılır.',
    },
    {
      id: 'fr-gun-58', on: 'Tant mieux', okunus: 'tan myö', tur: 'kalıp',
      arka: 'Ne iyi, daha iyi ya',
      ornek: 'Il fait beau ? Tant mieux !',
      ornekTr: 'Hava güzel mi? Ne iyi!',
      not: 'Tersi "tant pis" = boş ver, olsun.',
    },
    {
      id: 'fr-gun-59', on: 'Tant pis', okunus: 'tan pi', tur: 'kalıp',
      arka: 'Boş ver, olsun',
      ornek: 'Pas de places ? Tant pis.',
      ornekTr: 'Yer yok mu? Boş ver.',
      not: 'Kabullenmeyi anlatan çok kullanışlı bir ifadedir.',
    },
    {
      id: 'fr-gun-60', on: 'Ça me soulage', okunus: 'sa mö sulaj', tur: 'kalıp',
      arka: 'İçim rahatladı',
      ornek: 'Tout va bien ? Ça me soulage.',
      ornekTr: 'Her şey yolunda mı? İçim rahatladı.',
      not: '"soulager" rahatlatmak demektir.',
    },
    /* --- Şaşırma ve tepki --- */
    {
      id: 'fr-gun-61', on: 'Sérieux ?', okunus: 'seryö', tur: 'ünlem',
      arka: 'Ciddi misin?',
      ornek: 'Tu pars demain ? Sérieux ?',
      ornekTr: 'Yarın mı gidiyorsun? Ciddi misin?',
      not: 'Gündelik dilde çok kullanılır.',
    },
    {
      id: 'fr-gun-62', on: 'C\'est pas vrai !', okunus: 'se pa vre', tur: 'ünlem',
      arka: 'Olamaz! İnanmıyorum!',
      ornek: 'Il a gagné ? C\'est pas vrai !',
      ornekTr: 'Kazandı mı? İnanmıyorum!',
      not: 'Şaşkınlığı ifade eder; yalanlama değildir.',
    },
    {
      id: 'fr-gun-63', on: 'N\'importe quoi !', okunus: 'nenport kua', tur: 'ünlem',
      arka: 'Saçmalık!',
      ornek: 'Il dit n\'importe quoi.',
      ornekTr: 'Saçmalıyor.',
      not: 'Kelimesi kelimesine "her ne olursa" demektir.',
    },
    {
      id: 'fr-gun-64', on: 'Ça alors !', okunus: 'sa alor', tur: 'ünlem',
      arka: 'Vay canına!',
      ornek: 'Ça alors, quelle surprise !',
      ornekTr: 'Vay canına, ne sürpriz!',
      not: 'Şaşkınlığın klasik ifadesidir.',
    },
    {
      id: 'fr-gun-65', on: 'Bravo !', okunus: 'bravo', tur: 'ünlem',
      arka: 'Tebrikler!',
      ornek: 'Bravo pour ton exposé !',
      ornekTr: 'Sunumun için tebrikler!',
      not: 'İtalyancadan gelir ve Fransızcada çok kullanılır.',
    },
    {
      id: 'fr-gun-66', on: 'Félicitations', okunus: 'felisitasyon', tur: 'kalıp',
      arka: 'Tebrikler',
      ornek: 'Félicitations pour ton bac !',
      ornekTr: 'Bitirme sınavın için tebrikler!',
      not: 'Çoğul kullanılır ve daha resmîdir.',
    },
    {
      id: 'fr-gun-67', on: 'Devine quoi !', okunus: 'dövin kua', tur: 'kalıp',
      arka: 'Bil bakalım ne oldu!',
      ornek: 'Devine quoi ! J\'ai eu vingt sur vingt.',
      ornekTr: 'Bil bakalım ne oldu! Yirmi üzerinden yirmi aldım.',
      not: '"deviner" tahmin etmek demektir.',
    },
    {
      id: 'fr-gun-68', on: 'Je n\'en reviens pas', okunus: 'jö nan rövyen pa', tur: 'deyim',
      arka: 'İnanamıyorum',
      ornek: 'Je n\'en reviens pas, c\'est incroyable !',
      ornekTr: 'İnanamıyorum, bu inanılmaz!',
      not: 'Kelimesi kelimesine "bundan geri dönemiyorum" demektir.',
    },
    {
      id: 'fr-gun-69', on: 'Ça se tient', okunus: 'sa sö tiyen', tur: 'kalıp',
      arka: 'Mantıklı',
      ornek: 'Ce que tu dis, ça se tient.',
      ornekTr: 'Söylediğin mantıklı.',
      not: '"tenir" tutmak demektir; fikrin tutarlılığını anlatır.',
    },
    {
      id: 'fr-gun-70', on: 'Je m\'en doutais', okunus: 'jö man dute', tur: 'kalıp',
      arka: 'Tahmin etmiştim',
      ornek: 'Il est en retard ? Je m\'en doutais.',
      ornekTr: 'Geç mi kaldı? Tahmin etmiştim.',
      not: '"se douter de" sezmek, tahmin etmek demektir.',
    },
    /* --- Telefon ve mesaj --- */
    {
      id: 'fr-gun-71', on: 'Allô', okunus: 'alo', tur: 'kalıp',
      arka: 'Alo',
      ornek: 'Allô, tu m\'entends ?',
      ornekTr: 'Alo, beni duyuyor musun?',
      not: 'Sadece telefonda kullanılır, yüz yüze kullanılmaz.',
    },
    {
      id: 'fr-gun-72', on: 'Ne quitte pas', okunus: 'nö kit pa', tur: 'kalıp',
      arka: 'Ayrılma, bekle',
      ornek: 'Ne quitte pas, je vérifie.',
      ornekTr: 'Bekle, kontrol ediyorum.',
      not: 'Resmî hâli "Ne quittez pas"dır.',
    },
    {
      id: 'fr-gun-73', on: 'Je te rappelle', okunus: 'jö tö rapel', tur: 'kalıp',
      arka: 'Seni geri ararım',
      ornek: 'Je suis occupé, je te rappelle.',
      ornekTr: 'Meşgulüm, seni geri ararım.',
      not: '"rappeler" hem geri aramak hem hatırlatmak demektir.',
    },
    {
      id: 'fr-gun-74', on: 'Ça capte mal', okunus: 'sa kapt mal', tur: 'kalıp',
      arka: 'Çekmiyor, hat kötü',
      ornek: 'Ça capte mal ici, je te rappelle.',
      ornekTr: 'Burada çekmiyor, seni geri ararım.',
      not: '"capter" sinyal almak demektir.',
    },
    {
      id: 'fr-gun-75', on: 'raccrocher', okunus: 'rakroşe', tur: 'fiil',
      arka: 'telefonu kapatmak',
      ornek: 'Ne raccroche pas tout de suite.',
      ornekTr: 'Hemen kapatma.',
      not: 'Açmak "décrocher"dir.',
    },
    {
      id: 'fr-gun-76', on: 'envoyer un message', okunus: 'anvuaye ön mesaj', tur: 'kalıp',
      arka: 'mesaj göndermek',
      ornek: 'Envoie-moi un message en arrivant.',
      ornekTr: 'Varınca bana mesaj gönder.',
      not: '"en arrivant" = varırken, varınca.',
    },
    {
      id: 'fr-gun-77', on: 'passer chez quelqu\'un', okunus: 'pase şe kelkön', tur: 'kalıp',
      arka: 'birine uğramak',
      ornek: 'Passe chez moi ce soir.',
      ornekTr: 'Bu akşam bana uğra.',
      not: '"chez" birinin evi anlamı katar.',
    },
    {
      id: 'fr-gun-78', on: 'venir chercher', okunus: 'vönir şerşe', tur: 'kalıp',
      arka: 'almaya gelmek',
      ornek: 'Je viens te chercher à sept heures.',
      ornekTr: 'Seni yedide almaya geliyorum.',
      not: '"chercher" aramak, almaya gitmek demektir.',
    },
    {
      id: 'fr-gun-79', on: 'se dépêcher', okunus: 'sö depeşe', tur: 'fiil (dönüşlü)',
      arka: 'acele etmek',
      ornek: 'Dépêche-toi, on est en retard !',
      ornekTr: 'Acele et, geç kaldık!',
      not: 'Emir kipinde zamir sona gelir: dépêche-toi.',
    },
    {
      id: 'fr-gun-80', on: 'tenir au courant', okunus: 'tönir o kuran', tur: 'kalıp',
      arka: 'haberdar etmek',
      ornek: 'Tiens-moi au courant.',
      ornekTr: 'Beni haberdar et.',
      not: '"le courant" akım demektir; "au courant" güncel bilgi anlamı taşır.',
    },
    /* --- Konuşma akışı --- */
    {
      id: 'fr-gun-81', on: 'En fait', okunus: 'an fet', tur: 'kalıp',
      arka: 'Aslında',
      ornek: 'En fait, je l\'ai déjà lu.',
      ornekTr: 'Aslında onu zaten okudum.',
      not: 'Konuşmanın en sık kullanılan bağlantı sözlerindendir.',
    },
    {
      id: 'fr-gun-82', on: 'D\'ailleurs', okunus: 'dayör', tur: 'zarf',
      arka: 'Bu arada, kaldı ki',
      ornek: 'D\'ailleurs, tu as fini le livre ?',
      ornekTr: 'Bu arada, kitabı bitirdin mi?',
      not: 'Yeni bir konu ekler ya da fikri destekler.',
    },
    {
      id: 'fr-gun-83', on: 'Quand même', okunus: 'kan mem', tur: 'kalıp',
      arka: 'Yine de',
      ornek: 'C\'était cher, mais je l\'ai acheté quand même.',
      ornekTr: 'Pahalıydı ama yine de aldım.',
      not: 'Şaşkınlık pekiştirmesi olarak da kullanılır.',
    },
    {
      id: 'fr-gun-84', on: 'Du coup', okunus: 'dü ku', tur: 'kalıp',
      arka: 'Dolayısıyla, bu yüzden',
      ornek: 'Il pleut, du coup on reste ici.',
      ornekTr: 'Yağmur yağıyor, bu yüzden burada kalıyoruz.',
      not: 'Genç Fransızların en sık kullandığı bağlaçlardandır.',
    },
    {
      id: 'fr-gun-85', on: 'Bref', okunus: 'bref', tur: 'kalıp',
      arka: 'Kısacası',
      ornek: 'Bref, on n\'y est pas allés.',
      ornekTr: 'Kısacası oraya gitmedik.',
      not: 'Uzun bir anlatımı toparlar.',
    },
    {
      id: 'fr-gun-86', on: 'Enfin', okunus: 'anfen', tur: 'zarf',
      arka: 'Neyse, nihayet',
      ornek: 'Enfin, ce n\'est pas grave.',
      ornekTr: 'Neyse, önemli değil.',
      not: 'Hem "nihayet" hem "her neyse" anlamında kullanılır.',
    },
    {
      id: 'fr-gun-87', on: 'Attends', okunus: 'atan', tur: 'kalıp',
      arka: 'Dur bakalım, bekle',
      ornek: 'Attends, je réfléchis.',
      ornekTr: 'Dur, düşünüyorum.',
      not: '"réfléchir" düşünmek demektir.',
    },
    {
      id: 'fr-gun-88', on: 'Comment dire ?', okunus: 'koman dir', tur: 'kalıp',
      arka: 'Nasıl desem?',
      ornek: 'C\'était, comment dire, décevant.',
      ornekTr: 'Nasıl desem, hayal kırıklığıydı.',
      not: 'Doğru kelimeyi ararken doğal bir duraklama sağlar.',
    },
    {
      id: 'fr-gun-89', on: 'Je disais donc', okunus: 'jö dize donk', tur: 'kalıp',
      arka: 'Dediğim gibi',
      ornek: 'Je disais donc, il nous faut plus de temps.',
      ornekTr: 'Dediğim gibi, daha fazla zamana ihtiyacımız var.',
      not: 'Sözü kesildikten sonra devam etmek için kullanılır.',
    },
    {
      id: 'fr-gun-90', on: 'Je n\'ai pas compris', okunus: 'jö ne pa konpri', tur: 'kalıp',
      arka: 'Anlamadım',
      ornek: 'Désolé, je n\'ai pas compris la question.',
      ornekTr: 'Kusura bakma, soruyu anlamadım.',
      not: 'Ardından "Tu peux répéter ?" denebilir.',
    },
    /* --- Gündelik fiiller ve kalıplar --- */
    {
      id: 'fr-gun-91', on: 'avoir envie de', okunus: 'avuar anvi dö', tur: 'kalıp',
      arka: 'canı istemek',
      ornek: 'J\'ai envie de sortir ce soir.',
      ornekTr: 'Bu akşam dışarı çıkmak istiyorum.',
      not: 'Sonrasında "de + mastar" gelir.',
    },
    {
      id: 'fr-gun-92', on: 'avoir besoin de', okunus: 'avuar bözuen dö', tur: 'kalıp',
      arka: 'ihtiyacı olmak',
      ornek: 'J\'ai besoin de ton aide.',
      ornekTr: 'Yardımına ihtiyacım var.',
      not: '"le besoin" ihtiyaç demektir.',
    },
    {
      id: 'fr-gun-93', on: 's\'occuper de', okunus: 'sokupe dö', tur: 'fiil (dönüşlü)',
      arka: 'ilgilenmek, halletmek',
      ornek: 'Je m\'occupe des billets.',
      ornekTr: 'Biletlerle ben ilgileniyorum.',
      not: '"occupé" meşgul demektir.',
    },
    {
      id: 'fr-gun-94', on: 'faillir faire', okunus: 'fayir fer', tur: 'kalıp',
      arka: 'az kalsın yapmak',
      ornek: 'J\'ai failli tomber.',
      ornekTr: 'Az kalsın düşüyordum.',
      not: 'Sadece geçmiş zamanda kullanılır.',
    },
    {
      id: 'fr-gun-95', on: 'être en train de', okunus: 'etr an tren dö', tur: 'kalıp',
      arka: '... yapmakta olmak',
      ornek: 'Je suis en train de réviser.',
      ornekTr: 'Ders çalışmaktayım.',
      not: 'Fransızcada şimdiki zamanın süreklilik biçimidir.',
    },
    {
      id: 'fr-gun-96', on: 'venir de faire', okunus: 'vönir dö fer', tur: 'kalıp',
      arka: 'az önce yapmış olmak',
      ornek: 'Je viens de finir mes devoirs.',
      ornekTr: 'Ödevlerimi az önce bitirdim.',
      not: 'Yakın geçmişi anlatan tek kalıptır. Çekimi: je viens de.',
      kok: 'viens',
    },
    {
      id: 'fr-gun-97', on: 'ça vaut mieux', okunus: 'sa vo myö', tur: 'kalıp',
      arka: 'Böylesi daha iyi',
      ornek: 'Reste à la maison, ça vaut mieux.',
      ornekTr: 'Evde kal, böylesi daha iyi.',
      not: '"valoir" değmek fiilinden gelir.',
    },
    {
      id: 'fr-gun-98', on: 'de temps en temps', okunus: 'dö tan zan tan', tur: 'kalıp',
      arka: 'ara sıra',
      ornek: 'Je joue au basket de temps en temps.',
      ornekTr: 'Ara sıra basketbol oynuyorum.',
      not: 'Sıklık sıralaması: toujours, souvent, parfois, rarement, jamais.',
    },
    {
      id: 'fr-gun-99', on: 'tout à l\'heure', okunus: 'tut a lör', tur: 'kalıp',
      arka: 'birazdan; az önce',
      ornek: 'Je te vois tout à l\'heure.',
      ornekTr: 'Birazdan görüşürüz.',
      not: 'Hem yakın gelecek hem yakın geçmiş anlatır; zaman kipi belirler.',
    },
    {
      id: 'fr-gun-100', on: 'Petit à petit', okunus: 'pöti a pöti', tur: 'kalıp',
      arka: 'Yavaş yavaş',
      ornek: 'Petit à petit, je comprends mieux le français.',
      ornekTr: 'Yavaş yavaş Fransızcayı daha iyi anlıyorum.',
      not: 'Dil öğrenme sürecini anlatmanın en güzel yoludur.',
    },
  ],
}

export default DESTE
