/**
 * DESTE — HAYVANLAR VE DOĞA (Fransızca)
 *
 * Görsel olarak en kolay hatırlanan deste. Ayrıca Fransızcada hayvan
 * adlarının çoğu deyimlerde geçer; kartlarda o deyimler de not olarak
 * verildi, çünkü kelimeyi tek başına bilmek yetmez.
 */

export const DESTE = {
  id: 'hayvanlar-doga',
  dil: 'fr',
  ad: 'Hayvanlar ve doğa',
  simge: '🌿',
  aciklama: 'Hayvanlar, hava ve doğa; birlikte kullanıldıkları deyimlerle.',
  seviye: 'A1–A2',
  kartlar: [
    {
      id: 'fr-hay-01', on: 'le chat', okunus: 'lö şa', tur: 'isim',
      arka: 'kedi',
      ornek: "Mon chat dort sur le canapé toute la journée.",
      ornekTr: 'Kedim bütün gün kanepede uyuyor.',
      not: 'Sondaki "t" okunmaz. Dişisi "la chatte".',
    },
    {
      id: 'fr-hay-02', on: 'le chien', okunus: 'lö şiyen', tur: 'isim',
      arka: 'köpek',
      ornek: "Je promène mon chien tous les matins.",
      ornekTr: 'Köpeğimi her sabah gezdiriyorum.',
      not: '"Il fait un temps de chien" = hava berbat.',
    },
    {
      id: 'fr-hay-03', on: "l'oiseau", okunus: 'luazo', tur: 'isim',
      arka: 'kuş',
      ornek: "Il y a un oiseau sur la fenêtre.",
      ornekTr: 'Pencerede bir kuş var.',
      not: 'Çoğulu düzensizdir: des oiseaux.',
    },
    {
      id: 'fr-hay-04', on: "l'arbre", okunus: 'larbr', tur: 'isim',
      arka: 'ağaç',
      ornek: "On a planté un arbre dans le jardin.",
      ornekTr: 'Bahçeye bir ağaç diktik.',
      not: 'Orman "la forêt", yaprak "la feuille".',
    },
    {
      id: 'fr-hay-05', on: 'la mer', okunus: 'la mer', tur: 'isim (dişil)',
      arka: 'deniz',
      ornek: "En été, on va à la mer avec ma famille.",
      ornekTr: 'Yazın ailemle denize gidiyoruz.',
      not: 'Sesteşi "la mère" (anne) ile karışır; ikisi aynı okunur.',
    },
    {
      id: 'fr-hay-06', on: 'la montagne', okunus: 'la montany', tur: 'isim (dişil)',
      arka: 'dağ',
      ornek: "L'hiver, on va à la montagne pour skier.",
      ornekTr: 'Kışın kayak için dağa gidiyoruz.',
      not: '"gn" harf grubu Türkçedeki "ny" gibi okunur.',
    },
    {
      id: 'fr-hay-07', on: 'il pleut', okunus: 'il plö', tur: 'kalıp',
      arka: 'yağmur yağıyor',
      ornek: "Prends ton parapluie, il pleut.",
      ornekTr: 'Şemsiyeni al, yağmur yağıyor.',
      not: 'Öznesi olmayan bir fiildir; her zaman "il" ile kullanılır.',
    },
    {
      id: 'fr-hay-08', on: 'le soleil', okunus: 'lö soley', tur: 'isim',
      arka: 'güneş',
      ornek: "Il y a du soleil aujourd'hui.",
      ornekTr: 'Bugün güneş var.',
      not: 'Hava için "il fait soleil" de denir.',
    },
    {
      id: 'fr-hay-09', on: 'la fleur', okunus: 'la flör', tur: 'isim (dişil)',
      arka: 'çiçek',
      ornek: "Elle m'a offert des fleurs pour mon anniversaire.",
      ornekTr: 'Doğum günümde bana çiçek verdi.',
      not: '"eu" harf grubu Türkçedeki "ö" sesidir.',
    },
    {
      id: 'fr-hay-10', on: 'avoir un chat dans la gorge', okunus: 'avuar en şa dan la gorj', tur: 'deyim',
      arka: 'boğazı gıcıklanmak, sesi kısılmak',
      ornek: "Excusez-moi, j'ai un chat dans la gorge.",
      ornekTr: 'Affedersiniz, boğazım gıcıklandı.',
      not: 'Kelime kelime "boğazımda kedi var" demektir. Fransızların en sevdiği deyimlerden.',
    },
    /* --- Evcil hayvanlar --- */
    {
      id: 'fr-hay-11', on: 'l\'animal de compagnie', okunus: 'lanimal dö konpanyi', tur: 'isim',
      arka: 'evcil hayvan',
      ornek: 'Tu as un animal de compagnie ?',
      ornekTr: 'Evcil hayvanın var mı?',
      not: '"la compagnie" arkadaşlık, şirket demektir.',
    },
    {
      id: 'fr-hay-12', on: 'le lapin', okunus: 'lö lapen', tur: 'isim',
      arka: 'tavşan',
      ornek: 'Mon lapin adore les carottes.',
      ornekTr: 'Tavşanım havuca bayılıyor.',
      not: '"poser un lapin" deyimi "ekmek, sözünde durmamak" demektir.',
    },
    {
      id: 'fr-hay-13', on: 'nourrir', okunus: 'nurir', tur: 'fiil',
      arka: 'beslemek',
      ornek: 'Je nourris les oiseaux chaque matin.',
      ornekTr: 'Kuşları her sabah besliyorum.',
      not: '"la nourriture" yiyecek demektir.',
    },
    {
      id: 'fr-hay-14', on: 'caresser', okunus: 'karese', tur: 'fiil',
      arka: 'okşamak, sevmek',
      ornek: 'Le chat aime qu\'on le caresse.',
      ornekTr: 'Kedi sevilmeyi seviyor.',
      not: 'Sonrasında dilek kipi gelir: "aime qu\'on le caresse".',
    },
    {
      id: 'fr-hay-15', on: 'le vétérinaire', okunus: 'lö veteriner', tur: 'isim',
      arka: 'veteriner',
      ornek: 'On emmène le chat chez le vétérinaire.',
      ornekTr: 'Kediyi veterinere götürüyoruz.',
      not: 'Kısaca "le véto" denir.',
    },
    {
      id: 'fr-hay-16', on: 'le refuge', okunus: 'lö röfüj', tur: 'isim',
      arka: 'hayvan barınağı',
      ornek: 'Nous avons adopté le chien au refuge.',
      ornekTr: 'Köpeği barınaktan sahiplendik.',
      not: '"se réfugier" sığınmak demektir.',
    },
    {
      id: 'fr-hay-17', on: 'aboyer', okunus: 'abuaye', tur: 'fiil',
      arka: 'havlamak',
      ornek: 'Le chien aboie toute la nuit.',
      ornekTr: 'Köpek bütün gece havlıyor.',
      not: 'Kedi "miauler", kuş "chanter" der. Çekimi: il aboie.',
      kok: 'aboie',
    },
    {
      id: 'fr-hay-18', on: 'la queue', okunus: 'la kö', tur: 'isim',
      arka: 'kuyruk; sıra',
      ornek: 'Le chien remue la queue.',
      ornekTr: 'Köpek kuyruğunu sallıyor.',
      not: 'Aynı kelime "kuyruk (sıra)" anlamına da gelir: faire la queue.',
    },
    {
      id: 'fr-hay-19', on: 'fidèle', okunus: 'fidel', tur: 'sıfat',
      arka: 'sadık',
      ornek: 'Les chiens sont des animaux fidèles.',
      ornekTr: 'Köpekler sadık hayvanlardır.',
      not: '"la fidélité" sadakat demektir.',
    },
    {
      id: 'fr-hay-20', on: 'promener le chien', okunus: 'promöne lö şiyen', tur: 'kalıp',
      arka: 'köpeği gezdirmek',
      ornek: 'Je promène le chien après l\'école.',
      ornekTr: 'Okuldan sonra köpeği gezdiriyorum.',
      not: '"se promener" kendi gezinmek demektir.',
    },
    /* --- Çiftlik ve yaban hayvanları --- */
    {
      id: 'fr-hay-21', on: 'le cheval', okunus: 'lö şöval', tur: 'isim',
      arka: 'at',
      ornek: 'Elle monte à cheval le week-end.',
      ornekTr: 'Hafta sonu ata biniyor.',
      not: 'Çoğulu düzensizdir: "les chevaux".',
    },
    {
      id: 'fr-hay-22', on: 'la vache', okunus: 'la vaş', tur: 'isim',
      arka: 'inek',
      ornek: 'Les vaches sont dans le pré.',
      ornekTr: 'İnekler çayırda.',
      not: '"Oh la vache !" ünlemi "vay canına!" demektir.',
    },
    {
      id: 'fr-hay-23', on: 'le mouton', okunus: 'lö muton', tur: 'isim',
      arka: 'koyun',
      ornek: 'Il y a beaucoup de moutons sur la colline.',
      ornekTr: 'Tepede çok koyun var.',
      not: '"la colline" tepe demektir.',
    },
    {
      id: 'fr-hay-24', on: 'la poule', okunus: 'la pul', tur: 'isim',
      arka: 'tavuk',
      ornek: 'Les poules pondent des œufs chaque jour.',
      ornekTr: 'Tavuklar her gün yumurtluyor.',
      not: '"pondre" yumurtlamak demektir.',
    },
    {
      id: 'fr-hay-25', on: 'l\'ours', okunus: 'lurs', tur: 'isim',
      arka: 'ayı',
      ornek: 'Les ours hibernent en hiver.',
      ornekTr: 'Ayılar kışın uykuya yatar.',
      not: '"hiberner" kış uykusuna yatmak demektir.',
    },
    {
      id: 'fr-hay-26', on: 'le renard', okunus: 'lö rönar', tur: 'isim',
      arka: 'tilki',
      ornek: 'Un renard a traversé la route.',
      ornekTr: 'Bir tilki yoldan geçti.',
      not: 'Kurnaz kişiye "un vieux renard" denir.',
    },
    {
      id: 'fr-hay-27', on: 'l\'écureuil', okunus: 'leküröy', tur: 'isim',
      arka: 'sincap',
      ornek: 'Des écureuils vivent dans ce parc.',
      ornekTr: 'Bu parkta sincaplar yaşıyor.',
      not: 'Fransızcanın telaffuzu en zor kelimelerinden biridir.',
    },
    {
      id: 'fr-hay-28', on: 'le papillon', okunus: 'lö papiyon', tur: 'isim',
      arka: 'kelebek',
      ornek: 'Au printemps, il y a beaucoup de papillons.',
      ornekTr: 'İlkbaharda çok kelebek olur.',
      not: 'Papyon kravat da bu kelimeden gelir.',
    },
    {
      id: 'fr-hay-29', on: 'l\'abeille', okunus: 'labey', tur: 'isim',
      arka: 'arı',
      ornek: 'Les abeilles sont essentielles à la nature.',
      ornekTr: 'Arılar doğa için çok önemlidir.',
      not: 'Bal "le miel"dir.',
    },
    {
      id: 'fr-hay-30', on: 'l\'espèce', okunus: 'lespes', tur: 'isim',
      arka: 'tür',
      ornek: 'Cette espèce vit seulement en Turquie.',
      ornekTr: 'Bu tür sadece Türkiye\'de yaşıyor.',
      not: 'Dişildir ve biyoloji metinlerinin anahtar kelimesidir.',
    },
    /* --- Doğal alanlar --- */
    {
      id: 'fr-hay-31', on: 'la forêt', okunus: 'la fore', tur: 'isim',
      arka: 'orman',
      ornek: 'Nous marchons souvent dans la forêt.',
      ornekTr: 'Sık sık ormanda yürüyoruz.',
      not: 'İçindeki "s" tarih içinde düşmüş, aksan işareti kalmıştır.',
    },
    {
      id: 'fr-hay-32', on: 'le pré', okunus: 'lö pre', tur: 'isim',
      arka: 'çayır',
      ornek: 'Le pré est plein de fleurs.',
      ornekTr: 'Çayır çiçeklerle dolu.',
      not: '"la prairie" daha geniş çayır demektir.',
    },
    {
      id: 'fr-hay-33', on: 'la rivière', okunus: 'la rivyer', tur: 'isim',
      arka: 'nehir, ırmak',
      ornek: 'Une rivière traverse le village.',
      ornekTr: 'Bir ırmak köyün içinden geçiyor.',
      not: 'Denize dökülen büyük nehir "le fleuve"dür.',
    },
    {
      id: 'fr-hay-34', on: 'le lac', okunus: 'lö lak', tur: 'isim',
      arka: 'göl',
      ornek: 'On se baigne dans le lac en été.',
      ornekTr: 'Yazın gölde yüzüyoruz.',
      not: '"se baigner" yüzmek, banyo yapmak demektir.',
    },
    {
      id: 'fr-hay-35', on: 'la vallée', okunus: 'la vale', tur: 'isim',
      arka: 'vadi',
      ornek: 'Le village se trouve dans une vallée verte.',
      ornekTr: 'Köy yeşil bir vadide bulunuyor.',
      not: '"se trouver" bulunmak demektir.',
    },
    {
      id: 'fr-hay-36', on: 'l\'île', okunus: 'lil', tur: 'isim',
      arka: 'ada',
      ornek: 'On accède à l\'île seulement en bateau.',
      ornekTr: 'Adaya sadece tekneyle ulaşılıyor.',
      not: 'Baştaki "s" düşmüş, aksan işaretiyle işaretlenmiştir.',
    },
    {
      id: 'fr-hay-37', on: 'la plage', okunus: 'la plaj', tur: 'isim',
      arka: 'plaj, kumsal',
      ornek: 'Il y avait du vent sur la plage.',
      ornekTr: 'Plajda rüzgâr vardı.',
      not: 'Edatı "sur"dur: sur la plage.',
    },
    {
      id: 'fr-hay-38', on: 'la grotte', okunus: 'la grot', tur: 'isim',
      arka: 'mağara',
      ornek: 'La grotte est ouverte aux visiteurs.',
      ornekTr: 'Mağara ziyaretçilere açık.',
      not: 'Lascaux mağarası Fransa\'nın en ünlü mağarasıdır.',
    },
    {
      id: 'fr-hay-39', on: 'le sommet', okunus: 'lö some', tur: 'isim',
      arka: 'zirve',
      ornek: 'Nous avons atteint le sommet au lever du soleil.',
      ornekTr: 'Gün doğarken zirveye ulaştık.',
      not: '"le lever du soleil" gün doğumu demektir.',
    },
    {
      id: 'fr-hay-40', on: 'le sentier', okunus: 'lö santye', tur: 'isim',
      arka: 'patika',
      ornek: 'Nous avons suivi un sentier de montagne.',
      ornekTr: 'Bir dağ patikasını takip ettik.',
      not: '"suivre" takip etmek demektir.',
    },
    /* --- Bitkiler --- */
    {
      id: 'fr-hay-41', on: 'la plante', okunus: 'la plant', tur: 'isim',
      arka: 'bitki',
      ornek: 'Cette plante a besoin de plus de lumière.',
      ornekTr: 'Bu bitkinin daha çok ışığa ihtiyacı var.',
      not: '"planter" dikmek demektir.',
    },
    {
      id: 'fr-hay-42', on: 'la feuille', okunus: 'la föy', tur: 'isim',
      arka: 'yaprak',
      ornek: 'En automne, les feuilles tombent.',
      ornekTr: 'Sonbaharda yapraklar dökülür.',
      not: 'Kâğıt yaprağı için de aynı kelime kullanılır.',
    },
    {
      id: 'fr-hay-43', on: 'la racine', okunus: 'la rasin', tur: 'isim',
      arka: 'kök',
      ornek: 'Les racines descendent profondément.',
      ornekTr: 'Kökler derinlere iniyor.',
      not: 'Mecazi olarak "köken" anlamına da gelir.',
    },
    {
      id: 'fr-hay-44', on: 'la graine', okunus: 'la gren', tur: 'isim',
      arka: 'tohum',
      ornek: 'Nous avons planté des graines au jardin.',
      ornekTr: 'Bahçeye tohum ektik.',
      not: '"le grain" tane demektir; ikisi yakın akrabadır.',
    },
    {
      id: 'fr-hay-45', on: 'la terre', okunus: 'la ter', tur: 'isim',
      arka: 'toprak; dünya',
      ornek: 'La terre ici est très fertile.',
      ornekTr: 'Buradaki toprak çok verimli.',
      not: 'Büyük harfle "la Terre" gezegenimiz demektir.',
    },
    {
      id: 'fr-hay-46', on: 'arroser', okunus: 'aroze', tur: 'fiil',
      arka: 'sulamak',
      ornek: 'N\'oublie pas d\'arroser les fleurs.',
      ornekTr: 'Çiçekleri sulamayı unutma.',
      not: '"l\'arrosoir" sulama kabı demektir.',
    },
    {
      id: 'fr-hay-47', on: 'pousser', okunus: 'puse', tur: 'fiil',
      arka: 'büyümek (bitki); itmek',
      ornek: 'Les tomates poussent bien ici.',
      ornekTr: 'Domatesler burada iyi büyüyor.',
      not: 'Aynı fiil "itmek" anlamına da gelir.',
    },
    {
      id: 'fr-hay-48', on: 'fleurir', okunus: 'flörir', tur: 'fiil',
      arka: 'çiçek açmak',
      ornek: 'Les cerisiers fleurissent en avril.',
      ornekTr: 'Kiraz ağaçları nisanda çiçek açar.',
      not: '"le cerisier" kiraz ağacı demektir.',
    },
    {
      id: 'fr-hay-49', on: 'la récolte', okunus: 'la rekolt', tur: 'isim',
      arka: 'hasat',
      ornek: 'La récolte a été bonne cette année.',
      ornekTr: 'Bu yıl hasat iyi oldu.',
      not: '"récolter" hasat etmek demektir.',
    },
    {
      id: 'fr-hay-50', on: 'le potager', okunus: 'lö potaje', tur: 'isim',
      arka: 'sebze bahçesi',
      ornek: 'Mon grand-père a un petit potager.',
      ornekTr: 'Dedemin küçük bir sebze bahçesi var.',
      not: '"le pot" tencere demektir; tencerelik sebze bahçesidir.',
    },
    /* --- Mevsimler ve hava --- */
    {
      id: 'fr-hay-51', on: 'le printemps', okunus: 'lö prentan', tur: 'isim',
      arka: 'ilkbahar',
      ornek: 'Au printemps, tout devient vert.',
      ornekTr: 'İlkbaharda her yer yeşerir.',
      not: 'Tek mevsim "au" alır: au printemps, en été, en automne, en hiver.',
    },
    {
      id: 'fr-hay-52', on: 'l\'automne', okunus: 'loton', tur: 'isim',
      arka: 'sonbahar',
      ornek: 'L\'automne est ma saison préférée.',
      ornekTr: 'Sonbahar en sevdiğim mevsim.',
      not: 'Ortadaki "m" okunmaz.',
    },
    {
      id: 'fr-hay-53', on: 'neiger', okunus: 'neje', tur: 'fiil',
      arka: 'kar yağmak',
      ornek: 'Il neige depuis hier soir.',
      ornekTr: 'Dün akşamdan beri kar yağıyor.',
      not: 'Hava fiilleri daima "il" ile kullanılır.',
    },
    {
      id: 'fr-hay-54', on: 'le brouillard', okunus: 'lö bruyar', tur: 'isim',
      arka: 'sis',
      ornek: 'Il y avait un brouillard épais ce matin.',
      ornekTr: 'Bu sabah yoğun sis vardı.',
      not: '"épais" kalın, yoğun demektir.',
    },
    {
      id: 'fr-hay-55', on: 'l\'orage', okunus: 'loraj', tur: 'isim',
      arka: 'fırtına, gök gürültülü yağış',
      ornek: 'Un orage approche.',
      ornekTr: 'Fırtına yaklaşıyor.',
      not: '"approcher" yaklaşmak demektir.',
    },
    {
      id: 'fr-hay-56', on: 'l\'éclair', okunus: 'lekler', tur: 'isim',
      arka: 'şimşek',
      ornek: 'L\'éclair a illuminé le ciel.',
      ornekTr: 'Şimşek gökyüzünü aydınlattı.',
      not: 'Aynı adı taşıyan ünlü bir Fransız pastası da vardır.',
    },
    {
      id: 'fr-hay-57', on: 'le vent', okunus: 'lö van', tur: 'isim',
      arka: 'rüzgâr',
      ornek: 'Le vent est fort aujourd\'hui.',
      ornekTr: 'Rüzgâr bugün kuvvetli.',
      not: '"il y a du vent" = rüzgâr var.',
    },
    {
      id: 'fr-hay-58', on: 'l\'inondation', okunus: 'linondasyon', tur: 'isim',
      arka: 'sel',
      ornek: 'Le village a subi une inondation.',
      ornekTr: 'Köy sel yaşadı.',
      not: '"subir" maruz kalmak demektir.',
    },
    {
      id: 'fr-hay-59', on: 'le tremblement de terre', okunus: 'lö tranblıman dö ter', tur: 'isim',
      arka: 'deprem',
      ornek: 'La Turquie est une zone de tremblements de terre.',
      ornekTr: 'Türkiye bir deprem bölgesidir.',
      not: '"trembler" titremek demektir. "Le séisme" de kullanılır.',
    },
    {
      id: 'fr-hay-60', on: 'la sécheresse', okunus: 'la seşres', tur: 'isim',
      arka: 'kuraklık',
      ornek: 'La sécheresse a détruit la récolte.',
      ornekTr: 'Kuraklık hasadı yok etti.',
      not: '"sec" kuru demektir.',
    },
    /* --- Çevre --- */
    {
      id: 'fr-hay-61', on: 'l\'environnement', okunus: 'lanvironman', tur: 'isim',
      arka: 'çevre',
      ornek: 'Il faut protéger l\'environnement.',
      ornekTr: 'Çevreyi korumak gerekiyor.',
      not: '"environ" yaklaşık, etraf demektir.',
    },
    {
      id: 'fr-hay-62', on: 'les déchets', okunus: 'le deşe', tur: 'isim (çoğul)',
      arka: 'atıklar, çöp',
      ornek: 'Il faut réduire les déchets plastiques.',
      ornekTr: 'Plastik atıkları azaltmak gerekiyor.',
      not: 'Tekili "le déchet"dir ama genelde çoğul kullanılır.',
    },
    {
      id: 'fr-hay-63', on: 'le tri', okunus: 'lö tri', tur: 'isim',
      arka: 'çöp ayrıştırma',
      ornek: 'Le tri est obligatoire en France.',
      ornekTr: 'Fransa\'da çöp ayrıştırma zorunludur.',
      not: '"trier" ayırmak demektir.',
    },
    {
      id: 'fr-hay-64', on: 'recycler', okunus: 'rösikle', tur: 'fiil',
      arka: 'geri dönüştürmek',
      ornek: 'On recycle le papier et le verre à l\'école.',
      ornekTr: 'Okulda kâğıt ve camı geri dönüştürüyoruz.',
      not: '"le verre" cam ve bardak demektir.',
    },
    {
      id: 'fr-hay-65', on: 'la pollution', okunus: 'la polüsyon', tur: 'isim',
      arka: 'kirlilik',
      ornek: 'La pollution de l\'air est un grave problème.',
      ornekTr: 'Hava kirliliği ciddi bir sorun.',
      not: '"polluer" kirletmek demektir.',
    },
    {
      id: 'fr-hay-66', on: 'le changement climatique', okunus: 'lö şanjman klimatik', tur: 'isim',
      arka: 'iklim değişikliği',
      ornek: 'Le changement climatique nous concerne tous.',
      ornekTr: 'İklim değişikliği hepimizi ilgilendiriyor.',
      not: '"concerner" ilgilendirmek demektir.',
    },
    {
      id: 'fr-hay-67', on: 'la déforestation', okunus: 'la deforestasyon', tur: 'isim',
      arka: 'ormansızlaşma',
      ornek: 'La déforestation détruit les habitats.',
      ornekTr: 'Ormansızlaşma yaşam alanlarını yok ediyor.',
      not: '"l\'habitat" doğal yaşam alanı demektir.',
    },
    {
      id: 'fr-hay-68', on: 'l\'énergie renouvelable', okunus: 'lenerji rönuvölabl', tur: 'isim',
      arka: 'yenilenebilir enerji',
      ornek: 'Le solaire est une énergie renouvelable.',
      ornekTr: 'Güneş enerjisi yenilenebilir bir enerjidir.',
      not: '"renouveler" yenilemek demektir.',
    },
    {
      id: 'fr-hay-69', on: 'disparaître', okunus: 'disparetr', tur: 'fiil',
      arka: 'yok olmak',
      ornek: 'Beaucoup d\'espèces disparaissent.',
      ornekTr: 'Birçok türün nesli yok oluyor.',
      not: '"paraître" görünmek; "dis-" ön eki tersini yapar.',
    },
    {
      id: 'fr-hay-70', on: 'protéger', okunus: 'proteje', tur: 'fiil',
      arka: 'korumak',
      ornek: 'Chacun peut protéger la nature.',
      ornekTr: 'Herkes doğayı koruyabilir.',
      not: '"la protection" koruma demektir.',
    },
    /* --- Doğada zaman geçirmek --- */
    {
      id: 'fr-hay-71', on: 'se promener', okunus: 'sö promöne', tur: 'fiil (dönüşlü)',
      arka: 'gezinmek, yürüyüşe çıkmak',
      ornek: 'On se promène après le dîner.',
      ornekTr: 'Akşam yemeğinden sonra yürüyüşe çıkıyoruz.',
      not: '"la promenade" gezinti demektir. Çekimi: on se promène.',
      kok: 'promène',
    },
    {
      id: 'fr-hay-72', on: 'le pique-nique', okunus: 'lö pik nik', tur: 'isim',
      arka: 'piknik',
      ornek: 'On fait un pique-nique au bord du lac.',
      ornekTr: 'Göl kenarında piknik yapıyoruz.',
      not: '"au bord de" = kenarında.',
    },
    {
      id: 'fr-hay-73', on: 'camper', okunus: 'kanpe', tur: 'fiil',
      arka: 'kamp yapmak',
      ornek: 'Nous campons en montagne chaque été.',
      ornekTr: 'Her yaz dağda kamp yapıyoruz.',
      not: '"le camping" kamp alanı demektir.',
    },
    {
      id: 'fr-hay-74', on: 'le feu de camp', okunus: 'lö fö dö kan', tur: 'isim',
      arka: 'kamp ateşi',
      ornek: 'On a chanté autour du feu de camp.',
      ornekTr: 'Kamp ateşinin etrafında şarkı söyledik.',
      not: '"autour de" = etrafında.',
    },
    {
      id: 'fr-hay-75', on: 'prendre l\'air', okunus: 'prandr ler', tur: 'kalıp',
      arka: 'temiz hava almak',
      ornek: 'Sortons prendre l\'air cinq minutes.',
      ornekTr: 'Beş dakika temiz hava almaya çıkalım.',
      not: 'Ders molası önerirken çok kullanışlıdır.',
    },
    {
      id: 'fr-hay-76', on: 'le calme', okunus: 'lö kalm', tur: 'isim',
      arka: 'sessizlik, huzur',
      ornek: 'On trouve le calme dans la forêt.',
      ornekTr: 'Ormanda huzur bulunur.',
      not: 'Sıfat olarak "sakin" demektir.',
    },
    {
      id: 'fr-hay-77', on: 'à couper le souffle', okunus: 'a kupe lö sufl', tur: 'deyim',
      arka: 'nefes kesici',
      ornek: 'La vue était à couper le souffle.',
      ornekTr: 'Manzara nefes kesiciydi.',
      not: '"le souffle" nefes demektir.',
    },
    {
      id: 'fr-hay-78', on: 'en pleine nature', okunus: 'an plen natür', tur: 'kalıp',
      arka: 'doğanın ortasında',
      ornek: 'La cabane est en pleine nature.',
      ornekTr: 'Kulübe doğanın ortasında.',
      not: '"plein" dolu, tam demektir.',
    },
    {
      id: 'fr-hay-79', on: 'ne laisser aucune trace', okunus: 'nö lese okün tras', tur: 'kalıp',
      arka: 'hiç iz bırakmamak',
      ornek: 'En camping, il faut ne laisser aucune trace.',
      ornekTr: 'Kamp yaparken hiç iz bırakmamak gerekir.',
      not: '"la trace" iz demektir.',
    },
    {
      id: 'fr-hay-80', on: 'profiter de la nature', okunus: 'profite dö la natür', tur: 'kalıp',
      arka: 'doğanın tadını çıkarmak',
      ornek: 'On profite de la nature chaque week-end.',
      ornekTr: 'Her hafta sonu doğanın tadını çıkarıyoruz.',
      not: '"profiter de" bir şeyden yararlanmak demektir.',
    },
    /* --- Hayvanlı deyimler --- */
    {
      id: 'fr-hay-81', on: 'poser un lapin', okunus: 'poze ön lapen', tur: 'deyim',
      arka: 'randevuya gitmemek, ekmek',
      ornek: 'Il m\'a posé un lapin hier.',
      ornekTr: 'Dün beni ekti.',
      not: 'Kelimesi kelimesine "tavşan koymak" demektir.',
    },
    {
      id: 'fr-hay-82', on: 'il fait un temps de chien', okunus: 'il fe ön tan dö şiyen', tur: 'deyim',
      arka: 'Hava berbat',
      ornek: 'Reste à la maison, il fait un temps de chien.',
      ornekTr: 'Evde kal, hava berbat.',
      not: 'Kelimesi kelimesine "köpek havası" demektir.',
    },
    {
      id: 'fr-hay-83', on: 'être comme un poisson dans l\'eau', okunus: 'etr kom ön puason dan lo', tur: 'deyim',
      arka: 'sudaki balık gibi rahat olmak',
      ornek: 'Sur scène, elle est comme un poisson dans l\'eau.',
      ornekTr: 'Sahnede sudaki balık gibi rahat.',
      not: 'Türkçedeki karşılığıyla birebir aynıdır.',
    },
    {
      id: 'fr-hay-84', on: 'avoir une faim de loup', okunus: 'avuar ün fen dö lu', tur: 'deyim',
      arka: 'kurt gibi acıkmak',
      ornek: 'Après le sport, j\'ai une faim de loup.',
      ornekTr: 'Spordan sonra kurt gibi acıkıyorum.',
      not: '"le loup" kurt demektir.',
    },
    {
      id: 'fr-hay-85', on: 'quand les poules auront des dents', okunus: 'kan le pul oron de dan', tur: 'deyim',
      arka: 'balık kavağa çıkınca',
      ornek: 'Il rangera sa chambre quand les poules auront des dents.',
      ornekTr: 'Odasını balık kavağa çıkınca toplar.',
      not: 'Kelimesi kelimesine "tavukların dişi çıkınca" demektir.',
    },
    {
      id: 'fr-hay-86', on: 'revenons à nos moutons', okunus: 'rövönon a no muton', tur: 'deyim',
      arka: 'konumuza dönelim',
      ornek: 'Bon, revenons à nos moutons.',
      ornekTr: 'Neyse, konumuza dönelim.',
      not: 'Ortaçağ tiyatrosundan gelen çok eski bir deyimdir.',
    },
    {
      id: 'fr-hay-87', on: 'un froid de canard', okunus: 'ön frua dö kanar', tur: 'deyim',
      arka: 'dondurucu soğuk',
      ornek: 'Il fait un froid de canard dehors.',
      ornekTr: 'Dışarıda dondurucu bir soğuk var.',
      not: '"le canard" ördek demektir.',
    },
    {
      id: 'fr-hay-88', on: 'donner sa langue au chat', okunus: 'done sa lang o şa', tur: 'deyim',
      arka: 'pes etmek (bilmecede)',
      ornek: 'Tu ne devines pas ? Tu donnes ta langue au chat ?',
      ornekTr: 'Tahmin edemiyor musun? Pes mi ediyorsun?',
      not: 'Sadece bilmece ve tahmin oyunlarında kullanılır.',
    },
    {
      id: 'fr-hay-89', on: 'il pleut des cordes', okunus: 'il plö de kord', tur: 'deyim',
      arka: 'Bardaktan boşanırcasına yağıyor',
      ornek: 'Prends un parapluie, il pleut des cordes.',
      ornekTr: 'Şemsiye al, bardaktan boşanırcasına yağıyor.',
      not: '"la corde" ip demektir.',
    },
    {
      id: 'fr-hay-90', on: 'petit à petit, l\'oiseau fait son nid', okunus: 'pöti a pöti luazo fe son ni', tur: 'atasözü',
      arka: 'Damlaya damlaya göl olur',
      ornek: 'Continue : petit à petit, l\'oiseau fait son nid.',
      ornekTr: 'Devam et: damlaya damlaya göl olur.',
      not: '"le nid" yuva demektir.',
    },
    /* --- Doğa metinlerinin dili --- */
    {
      id: 'fr-hay-91', on: 'la plupart de', okunus: 'la plüpar dö', tur: 'kalıp',
      arka: 'çoğu',
      ornek: 'La plupart des animaux vivent dans la forêt.',
      ornekTr: 'Hayvanların çoğu ormanda yaşıyor.',
      not: 'Sonrasında çoğul fiil gelir.',
    },
    {
      id: 'fr-hay-92', on: 'de moins en moins', okunus: 'dö muen an muen', tur: 'kalıp',
      arka: 'gitgide daha az',
      ornek: 'Il y a de moins en moins d\'abeilles.',
      ornekTr: 'Gitgide daha az arı var.',
      not: 'Tersi "de plus en plus" = gitgide daha çok.',
    },
    {
      id: 'fr-hay-93', on: 'autrefois', okunus: 'otröfua', tur: 'zarf',
      arka: 'eskiden',
      ornek: 'Autrefois, il y avait plus de forêts ici.',
      ornekTr: 'Eskiden burada daha çok orman vardı.',
      not: '"il y avait" = vardı; geçmişteki durumu anlatır.',
    },
    {
      id: 'fr-hay-94', on: 'il est probable que', okunus: 'il e probabl kö', tur: 'kalıp',
      arka: 'muhtemeldir ki',
      ornek: 'Il est probable que les températures augmentent.',
      ornekTr: 'Sıcaklıkların artması muhtemel.',
      not: '"augmenter" artmak demektir.',
    },
    {
      id: 'fr-hay-95', on: 'à cause de', okunus: 'a koz dö', tur: 'kalıp',
      arka: '... yüzünden',
      ornek: 'Beaucoup d\'espèces disparaissent à cause de la pollution.',
      ornekTr: 'Kirlilik yüzünden birçok tür yok oluyor.',
      not: 'Olumlu sebep için "grâce à" kullanılır.',
    },
    {
      id: 'fr-hay-96', on: 'par conséquent', okunus: 'par konsekan', tur: 'kalıp',
      arka: 'sonuç olarak',
      ornek: 'La glace fond ; par conséquent, le niveau de la mer monte.',
      ornekTr: 'Buzlar eriyor; sonuç olarak deniz seviyesi yükseliyor.',
      not: 'Yazma bölümünde sebep-sonuç kurmanın resmî yoludur.',
    },
    {
      id: 'fr-hay-97', on: 'en voie de disparition', okunus: 'an vua dö disparisyon', tur: 'kalıp',
      arka: 'nesli tükenmekte olan',
      ornek: 'Cette espèce est en voie de disparition.',
      ornekTr: 'Bu türün nesli tükenmekte.',
      not: 'Çevre metinlerinin standart ifadesidir.',
    },
    {
      id: 'fr-hay-98', on: 'agir', okunus: 'ajir', tur: 'fiil',
      arka: 'harekete geçmek',
      ornek: 'Il faut agir maintenant.',
      ornekTr: 'Şimdi harekete geçmek gerekiyor.',
      not: '"l\'action" eylem demektir.',
    },
    {
      id: 'fr-hay-99', on: 'faire la différence', okunus: 'fer la diferans', tur: 'kalıp',
      arka: 'fark yaratmak',
      ornek: 'Les petits gestes font la différence.',
      ornekTr: 'Küçük davranışlar fark yaratır.',
      not: '"le geste" hareket, davranış demektir.',
    },
    {
      id: 'fr-hay-100', on: 'respecter la nature', okunus: 'respekte la natür', tur: 'kalıp',
      arka: 'doğaya saygı göstermek',
      ornek: 'Respecter la nature, c\'est respecter l\'avenir.',
      ornekTr: 'Doğaya saygı geleceğe saygıdır.',
      not: '"l\'avenir" gelecek demektir.',
    },
  ],
}

export default DESTE
