/**
 * DESTE — MÜZİK, DİZİ VE FİLM (Fransızca)
 *
 * Öğrencinin zaten tükettiği içerikten gelen kelimeler. Bir dizi altyazısında
 * ya da şarkı sözünde karşısına çıkan kelime, ders kitabındaki kelimeden
 * daha kolay yerleşir.
 */

export const DESTE = {
  id: 'muzik-dizi',
  dil: 'fr',
  ad: 'Müzik, dizi ve film',
  simge: '🎬',
  aciklama: 'Şarkı sözlerinde, altyazılarda ve dizi konuşmalarında duyacakların.',
  seviye: 'A1–A2',
  kartlar: [
    {
      id: 'fr-muz-01', on: 'la chanson', okunus: 'la şanson', tur: 'isim',
      arka: 'şarkı',
      ornek: "Cette chanson est dans ma tête depuis ce matin.",
      ornekTr: 'Bu şarkı sabahtan beri aklımda.',
      not: 'Şarkıcı "le chanteur / la chanteuse", söylemek "chanter".',
    },
    {
      id: 'fr-muz-02', on: 'les paroles', okunus: 'le parol', tur: 'isim (çoğul)',
      arka: 'şarkı sözleri',
      ornek: "Je ne comprends pas les paroles de cette chanson.",
      ornekTr: 'Bu şarkının sözlerini anlamıyorum.',
      not: 'Tekili "une parole" = söz. Şarkı sözü için HER ZAMAN çoğul kullanılır.',
    },
    {
      id: 'fr-muz-03', on: 'la série', okunus: 'la seri', tur: 'isim',
      arka: 'dizi',
      ornek: "J'ai regardé toute la série en un week-end.",
      ornekTr: 'Bütün diziyi bir hafta sonunda izledim.',
      not: 'Bölüm "un épisode", sezon "une saison".',
    },
    {
      id: 'fr-muz-04', on: 'le film', okunus: 'lö film', tur: 'isim',
      arka: 'film',
      ornek: "Le film dure deux heures.",
      ornekTr: 'Film iki saat sürüyor.',
      not: 'İzlemek "regarder"dır. Sinemada izlemek: "voir un film".',
    },
    {
      id: 'fr-muz-05', on: 'les sous-titres', okunus: 'le su-titr', tur: 'isim (çoğul)',
      arka: 'altyazı',
      ornek: "Je regarde avec les sous-titres en français.",
      ornekTr: 'Fransızca altyazıyla izliyorum.',
      not: '"sous" (alt) + "titre" (başlık). Dil öğrenirken en işe yarayan ayar.',
    },
    {
      id: 'fr-muz-06', on: "l'histoire", okunus: 'listuar', tur: 'isim (dişil)',
      arka: 'hikâye; tarih',
      ornek: "L'histoire de ce film est vraiment bizarre.",
      ornekTr: 'Bu filmin hikâyesi gerçekten tuhaf.',
      not: 'Aynı kelime hem "hikâye" hem "tarih" demektir; bağlam ayırır.',
    },
    {
      id: 'fr-muz-07', on: 'écouter', okunus: 'ekute', tur: 'fiil',
      arka: 'dinlemek',
      ornek: "J'écoute de la musique française pour apprendre.",
      ornekTr: 'Öğrenmek için Fransızca müzik dinliyorum.',
      not: '"entendre" duymak, "écouter" bilerek dinlemektir.',
    },
    {
      id: 'fr-muz-08', on: 'la voix', okunus: 'la vua', tur: 'isim (dişil)',
      arka: 'ses (insan sesi)',
      ornek: "Elle a une voix incroyable.",
      ornekTr: 'İnanılmaz bir sesi var.',
      not: 'Sondaki "x" okunmaz. Cihaz sesi için "le son" kullanılır.',
    },
    {
      id: 'fr-muz-09', on: 'le personnage', okunus: 'lö personaj', tur: 'isim',
      arka: 'karakter (film/dizi)',
      ornek: "Mon personnage préféré meurt à la fin.",
      ornekTr: 'En sevdiğim karakter sonda ölüyor.',
      not: 'Kişilik anlamındaki karakter ise "le caractère"dır. İkisi karışır.',
    },
    {
      id: 'fr-muz-10', on: 'ça déchire', okunus: 'sa deşir', tur: 'kalıp (günlük)',
      arka: 'harika, çok iyi (argo)',
      ornek: "Leur nouvel album, ça déchire !",
      ornekTr: 'Yeni albümleri harika!',
      not: 'Gençler arasında çok yaygın. Resmî ortamda kullanılmaz.',
    },
    /* --- Müzik ve şarkılar --- */
    {
      id: 'fr-muz-11', on: 'le chanteur', okunus: 'lö şantör', tur: 'isim',
      arka: 'şarkıcı (erkek)',
      ornek: 'Le chanteur a une voix grave.',
      ornekTr: 'Şarkıcının kalın bir sesi var.',
      not: 'Kadın şarkıcı "la chanteuse"dür.',
    },
    {
      id: 'fr-muz-12', on: 'le groupe', okunus: 'lö grup', tur: 'isim',
      arka: 'müzik grubu',
      ornek: 'Ce groupe joue ce soir.',
      ornekTr: 'Bu grup bu akşam çalıyor.',
      not: 'Aynı kelime her türlü grup için kullanılır.',
    },
    {
      id: 'fr-muz-13', on: 'le concert', okunus: 'lö konser', tur: 'isim',
      arka: 'konser',
      ornek: 'Nous allons au concert demain.',
      ornekTr: 'Yarın konsere gidiyoruz.',
      not: '"aller à" kalıbı: au concert, au cinéma.',
    },
    {
      id: 'fr-muz-14', on: 'l\'album', okunus: 'lalbom', tur: 'isim',
      arka: 'albüm',
      ornek: 'Leur nouvel album est excellent.',
      ornekTr: 'Yeni albümleri mükemmel.',
      not: 'Sesli harfle başlayan eril isimlerde "nouvel" kullanılır.',
    },
    {
      id: 'fr-muz-15', on: 'le refrain', okunus: 'lö röfren', tur: 'isim',
      arka: 'nakarat',
      ornek: 'Tout le monde chante le refrain.',
      ornekTr: 'Herkes nakaratı söylüyor.',
      not: 'Türkçedeki "refren" bu kelimeden gelir.',
    },
    {
      id: 'fr-muz-16', on: 'entraînant', okunus: 'antrenan', tur: 'sıfat',
      arka: 'sürükleyici, akılda kalıcı (melodi)',
      ornek: 'C\'est une chanson très entraînante.',
      ornekTr: 'Çok sürükleyici bir şarkı.',
      not: '"entraîner" sürüklemek demektir.',
    },
    {
      id: 'fr-muz-17', on: 'la reprise', okunus: 'la röpriz', tur: 'isim',
      arka: 'cover, yeniden yorum',
      ornek: 'Elle a fait une reprise d\'une vieille chanson.',
      ornekTr: 'Eski bir şarkının coverını yaptı.',
      not: '"reprendre" tekrar almak demektir.',
    },
    {
      id: 'fr-muz-18', on: 'le tube', okunus: 'lö tüb', tur: 'isim',
      arka: 'hit şarkı',
      ornek: 'C\'est le tube de l\'été.',
      ornekTr: 'Bu yazın hit şarkısı.',
      not: 'Kelimenin ilk anlamı "boru"dur; müzikte hit demektir.',
    },
    {
      id: 'fr-muz-19', on: 'la mélodie', okunus: 'la melodi', tur: 'isim',
      arka: 'melodi',
      ornek: 'Je me souviens de la mélodie, pas des paroles.',
      ornekTr: 'Melodiyi hatırlıyorum, sözleri değil.',
      not: '"se souvenir de" = hatırlamak; edatı "de"dir.',
    },
    {
      id: 'fr-muz-20', on: 'sortir un album', okunus: 'sortir ön albom', tur: 'kalıp',
      arka: 'albüm çıkarmak',
      ornek: 'Ils vont sortir un album en mars.',
      ornekTr: 'Martta albüm çıkaracaklar.',
      not: '"aller + mastar" yakın gelecek kurar.',
    },
    /* --- Dinleme alışkanlıkları --- */
    {
      id: 'fr-muz-21', on: 'le casque', okunus: 'lö kask', tur: 'isim',
      arka: 'kulaklık',
      ornek: 'Il ne sort jamais sans son casque.',
      ornekTr: 'Kulaklığı olmadan asla çıkmaz.',
      not: 'Kulak içi olanlara "les écouteurs" denir.',
    },
    {
      id: 'fr-muz-22', on: 'la playlist', okunus: 'la pleylist', tur: 'isim',
      arka: 'çalma listesi',
      ornek: 'J\'ai une playlist pour réviser.',
      ornekTr: 'Ders çalışmak için bir çalma listem var.',
      not: 'İngilizceden gelir; Fransızcası "la liste de lecture"tür.',
    },
    {
      id: 'fr-muz-23', on: 'en boucle', okunus: 'an bukl', tur: 'kalıp',
      arka: 'sürekli tekrar tekrar',
      ornek: 'J\'écoute cette chanson en boucle.',
      ornekTr: 'Bu şarkıyı sürekli tekrar dinliyorum.',
      not: '"la boucle" halka, döngü demektir.',
    },
    {
      id: 'fr-muz-24', on: 'monter le son', okunus: 'monte lö son', tur: 'kalıp',
      arka: 'sesi açmak',
      ornek: 'Monte le son, j\'adore ce morceau !',
      ornekTr: 'Sesi aç, bu parçaya bayılıyorum!',
      not: 'Sesi kısmak "baisser le son"dur.',
    },
    {
      id: 'fr-muz-25', on: 'le morceau', okunus: 'lö morso', tur: 'isim',
      arka: 'parça (müzik)',
      ornek: 'Le troisième morceau est mon préféré.',
      ornekTr: 'Üçüncü parça favorim.',
      not: 'Çoğulu "les morceaux"dur; "-eau" sonu "x" alır.',
    },
    {
      id: 'fr-muz-26', on: 'découvrir', okunus: 'dekuvrir', tur: 'fiil',
      arka: 'keşfetmek',
      ornek: 'J\'aime découvrir de nouveaux artistes.',
      ornekTr: 'Yeni sanatçılar keşfetmeyi seviyorum.',
      not: '"couvrir" örtmek; "dé-" ön eki tersini yapar.',
    },
    {
      id: 'fr-muz-27', on: 'en direct', okunus: 'an direkt', tur: 'kalıp',
      arka: 'canlı (yayın)',
      ornek: 'Le concert est diffusé en direct.',
      ornekTr: 'Konser canlı yayınlanıyor.',
      not: '"diffuser" yayınlamak demektir.',
    },
    {
      id: 'fr-muz-28', on: 'la tournée', okunus: 'la turne', tur: 'isim',
      arka: 'turne',
      ornek: 'Le groupe part en tournée cet été.',
      ornekTr: 'Grup bu yaz turneye çıkıyor.',
      not: 'Türkçedeki "turne" bu kelimeden gelir.',
    },
    {
      id: 'fr-muz-29', on: 'chanter en chœur', okunus: 'şante an kör', tur: 'kalıp',
      arka: 'hep birlikte şarkı söylemek',
      ornek: 'Le public chante en chœur.',
      ornekTr: 'Seyirci hep birlikte söylüyor.',
      not: '"le chœur" koro demektir ve "kör" okunur.',
    },
    {
      id: 'fr-muz-30', on: 'être fan de', okunus: 'etr fan dö', tur: 'kalıp',
      arka: 'hayranı olmak',
      ornek: 'Je suis fan de ce groupe depuis deux ans.',
      ornekTr: 'İki yıldır bu grubun hayranıyım.',
      not: '"depuis" ile şimdiki zaman kullanılır, geçmiş değil.',
    },
    /* --- Enstrüman ve müzik yapmak --- */
    {
      id: 'fr-muz-31', on: 'jouer de la guitare', okunus: 'jue dö la gitar', tur: 'kalıp',
      arka: 'gitar çalmak',
      ornek: 'Elle joue de la guitare depuis six ans.',
      ornekTr: 'Altı yıldır gitar çalıyor.',
      not: 'Enstrümanda "jouer de", sporda "jouer à" kullanılır.',
    },
    {
      id: 'fr-muz-32', on: 'le piano', okunus: 'lö piyano', tur: 'isim',
      arka: 'piyano',
      ornek: 'Ma sœur apprend le piano.',
      ornekTr: 'Kız kardeşim piyano öğreniyor.',
      not: '"apprendre" öğrenmek demektir.',
    },
    {
      id: 'fr-muz-33', on: 'la batterie', okunus: 'la batri', tur: 'isim',
      arka: 'bateri; pil',
      ornek: 'Mon frère joue de la batterie.',
      ornekTr: 'Kardeşim bateri çalıyor.',
      not: 'Aynı kelime telefon pili anlamına da gelir.',
    },
    {
      id: 'fr-muz-34', on: 'répéter', okunus: 'repete', tur: 'fiil',
      arka: 'prova yapmak; tekrar etmek',
      ornek: 'Le groupe répète tous les samedis.',
      ornekTr: 'Grup her cumartesi prova yapıyor.',
      not: 'Prova "la répétition"dur.',
      kok: 'répète',
    },
    {
      id: 'fr-muz-35', on: 'la scène', okunus: 'la sen', tur: 'isim',
      arka: 'sahne',
      ornek: 'Ils montent sur scène à vingt heures.',
      ornekTr: 'Saat yirmide sahneye çıkıyorlar.',
      not: '"monter sur scène" = sahneye çıkmak.',
    },
    {
      id: 'fr-muz-36', on: 'le trac', okunus: 'lö trak', tur: 'isim',
      arka: 'sahne heyecanı',
      ornek: 'Elle a le trac avant chaque concert.',
      ornekTr: 'Her konserden önce sahne heyecanı yaşıyor.',
      not: 'Fiili "avoir"dır: avoir le trac.',
    },
    {
      id: 'fr-muz-37', on: 'faux / juste', okunus: 'fo / jüst', tur: 'sıfat',
      arka: 'akortsuz / akortlu, doğru',
      ornek: 'Il chante faux mais il s\'amuse.',
      ornekTr: 'Akortsuz söylüyor ama eğleniyor.',
      not: '"chanter juste" = doğru perdeden söylemek.',
    },
    {
      id: 'fr-muz-38', on: 'l\'ambiance', okunus: 'lambiyans', tur: 'isim',
      arka: 'atmosfer',
      ornek: 'L\'ambiance du concert était magique.',
      ornekTr: 'Konserin atmosferi büyülüydü.',
      not: 'Restoran ve sınıf ortamı için de kullanılır.',
    },
    {
      id: 'fr-muz-39', on: 'applaudir', okunus: 'aplodir', tur: 'fiil',
      arka: 'alkışlamak',
      ornek: 'Le public applaudit pendant cinq minutes.',
      ornekTr: 'Seyirci beş dakika alkışlıyor.',
      not: 'Alkış "les applaudissements"dır.',
    },
    {
      id: 'fr-muz-40', on: 'la bande originale', okunus: 'la band orijinal', tur: 'isim',
      arka: 'film müziği',
      ornek: 'La bande originale est meilleure que le film.',
      ornekTr: 'Film müziği filmden iyi.',
      not: 'Kısaltması "la BO"dur.',
    },
    /* --- Dizi ve film --- */
    {
      id: 'fr-muz-41', on: 'l\'épisode', okunus: 'lepizod', tur: 'isim',
      arka: 'bölüm',
      ornek: 'Le dernier épisode durait deux heures.',
      ornekTr: 'Son bölüm iki saatti.',
      not: 'Eril bir isimdir: "un épisode".',
    },
    {
      id: 'fr-muz-42', on: 'la saison', okunus: 'la sezon', tur: 'isim',
      arka: 'sezon',
      ornek: 'La saison trois sort en avril.',
      ornekTr: 'Üçüncü sezon nisanda çıkıyor.',
      not: 'Aynı kelime mevsim anlamına da gelir.',
    },
    {
      id: 'fr-muz-43', on: 'l\'intrigue', okunus: 'lentrig', tur: 'isim',
      arka: 'olay örgüsü',
      ornek: 'L\'intrigue est compliquée au début.',
      ornekTr: 'Olay örgüsü başta karmaşık.',
      not: '"le sujet" konu, "l\'intrigue" olayların akışıdır.',
    },
    {
      id: 'fr-muz-44', on: 'le réalisateur', okunus: 'lö realizatör', tur: 'isim',
      arka: 'yönetmen',
      ornek: 'Le réalisateur a reçu un prix.',
      ornekTr: 'Yönetmen bir ödül aldı.',
      not: '"réaliser" gerçekleştirmek demektir.',
    },
    {
      id: 'fr-muz-45', on: 'l\'acteur', okunus: 'laktör', tur: 'isim',
      arka: 'oyuncu (erkek)',
      ornek: 'Cet acteur joue dans beaucoup de films.',
      ornekTr: 'Bu oyuncu birçok filmde oynuyor.',
      not: 'Kadın oyuncu "l\'actrice"tir.',
    },
    {
      id: 'fr-muz-46', on: 'en VO', okunus: 'an ve o', tur: 'kalıp',
      arka: 'orijinal dilinde',
      ornek: 'Je regarde les séries en VO.',
      ornekTr: 'Dizileri orijinal dilinde izliyorum.',
      not: '"version originale" kısaltmasıdır; dublajlı "en VF"tir.',
    },
    {
      id: 'fr-muz-47', on: 'le doublage', okunus: 'lö dublaj', tur: 'isim',
      arka: 'dublaj',
      ornek: 'Le doublage français est très bon.',
      ornekTr: 'Fransızca dublaj çok iyi.',
      not: 'Fransa\'da dublaj geleneği güçlüdür.',
    },
    {
      id: 'fr-muz-48', on: 'la bande-annonce', okunus: 'la band anons', tur: 'isim',
      arka: 'fragman',
      ornek: 'La bande-annonce donne envie.',
      ornekTr: 'Fragman iştah kabartıyor.',
      not: '"donner envie" = canını çekmek, istek uyandırmak.',
    },
    {
      id: 'fr-muz-49', on: 'le personnage principal', okunus: 'lö personaj prensipal', tur: 'isim',
      arka: 'başkarakter',
      ornek: 'Le personnage principal meurt à la fin.',
      ornekTr: 'Başkarakter sonunda ölüyor.',
      not: '"principal" ana, baş demektir.',
    },
    {
      id: 'fr-muz-50', on: 'le dénouement', okunus: 'lö denuman', tur: 'isim',
      arka: 'final, çözülme',
      ornek: 'Le dénouement m\'a surpris.',
      ornekTr: 'Final beni şaşırttı.',
      not: '"le nœud" düğüm demektir; düğümün çözülmesidir.',
    },
    /* --- Türler --- */
    {
      id: 'fr-muz-51', on: 'la comédie', okunus: 'la komedi', tur: 'isim',
      arka: 'komedi',
      ornek: 'Je préfère les comédies aux films d\'horreur.',
      ornekTr: 'Komedileri korku filmlerine tercih ederim.',
      not: '"préférer A à B" kalıbında edat "à"dır.',
    },
    {
      id: 'fr-muz-52', on: 'le policier', okunus: 'lö polisye', tur: 'isim',
      arka: 'polisiye',
      ornek: 'C\'est un policier avec beaucoup de suspense.',
      ornekTr: 'Bol gerilimli bir polisiye.',
      not: 'Aynı kelime "polis memuru" anlamına da gelir.',
    },
    {
      id: 'fr-muz-53', on: 'le documentaire', okunus: 'lö dokümanter', tur: 'isim',
      arka: 'belgesel',
      ornek: 'Nous avons vu un documentaire sur l\'océan.',
      ornekTr: 'Okyanusla ilgili bir belgesel izledik.',
      not: 'Konu edatı "sur"dur.',
    },
    {
      id: 'fr-muz-54', on: 'le dessin animé', okunus: 'lö desen anime', tur: 'isim',
      arka: 'çizgi film',
      ornek: 'Les dessins animés ne sont pas que pour les enfants.',
      ornekTr: 'Çizgi filmler sadece çocuklar için değil.',
      not: '"ne ... que" = sadece.',
    },
    {
      id: 'fr-muz-55', on: 'la science-fiction', okunus: 'la siyans fiksiyon', tur: 'isim',
      arka: 'bilim kurgu',
      ornek: 'Il ne regarde que de la science-fiction.',
      ornekTr: 'Sadece bilim kurgu izliyor.',
      not: 'Kısaltması "la SF"tir.',
    },
    {
      id: 'fr-muz-56', on: 'le film d\'horreur', okunus: 'lö film dorör', tur: 'isim',
      arka: 'korku filmi',
      ornek: 'Je ne dors pas après un film d\'horreur.',
      ornekTr: 'Korku filminden sonra uyuyamıyorum.',
      not: '"l\'horreur" dehşet demektir.',
    },
    {
      id: 'fr-muz-57', on: 'la suite', okunus: 'la süit', tur: 'isim',
      arka: 'devam filmi',
      ornek: 'La suite est moins bonne que le premier film.',
      ornekTr: 'Devam filmi ilkinden daha az iyi.',
      not: '"suivre" takip etmek fiilinden gelir.',
    },
    {
      id: 'fr-muz-58', on: 'tiré d\'une histoire vraie', okunus: 'tire dün istuar vre', tur: 'kalıp',
      arka: 'gerçek bir hikâyeden uyarlanmış',
      ornek: 'Le film est tiré d\'une histoire vraie.',
      ornekTr: 'Film gerçek bir hikâyeden uyarlanmış.',
      not: '"tirer de" burada uyarlamak anlamındadır.',
    },
    {
      id: 'fr-muz-59', on: 'le suspense', okunus: 'lö süspans', tur: 'isim',
      arka: 'gerilim, merak',
      ornek: 'Il y a du suspense jusqu\'à la fin.',
      ornekTr: 'Sonuna kadar gerilim var.',
      not: '"il y a" = vardır; en çok kullanılan kalıplardandır.',
    },
    {
      id: 'fr-muz-60', on: 'le navet', okunus: 'lö nave', tur: 'isim',
      arka: 'çok kötü film',
      ornek: 'Franchement, c\'est un navet.',
      ornekTr: 'Açıkçası bu berbat bir film.',
      not: 'Kelimenin asıl anlamı "şalgam"dır; sinemada kötü film demektir.',
    },
    /* --- İzleme ve değerlendirme --- */
    {
      id: 'fr-muz-61', on: 'enchaîner les épisodes', okunus: 'anşene lez epizod', tur: 'kalıp',
      arka: 'arka arkaya bölüm izlemek',
      ornek: 'J\'ai enchaîné les épisodes toute la nuit.',
      ornekTr: 'Bütün gece arka arkaya bölüm izledim.',
      not: '"la chaîne" zincir demektir; bölümleri zincirlemektir.',
    },
    {
      id: 'fr-muz-62', on: 'sortir', okunus: 'sortir', tur: 'fiil',
      arka: 'çıkmak (vizyona girmek)',
      ornek: 'Le film sort en juin.',
      ornekTr: 'Film haziranda çıkıyor.',
      not: 'Aynı fiil "dışarı çıkmak" anlamına da gelir.',
    },
    {
      id: 'fr-muz-63', on: 'recommander', okunus: 'rökomande', tur: 'fiil',
      arka: 'tavsiye etmek',
      ornek: 'Je te recommande cette série.',
      ornekTr: 'Sana bu diziyi tavsiye ediyorum.',
      not: 'Kişi zamiri fiilden önce gelir: "je te recommande".',
    },
    {
      id: 'fr-muz-64', on: 'la critique', okunus: 'la kritik', tur: 'isim',
      arka: 'eleştiri',
      ornek: 'Les critiques étaient très bonnes.',
      ornekTr: 'Eleştiriler çok iyiydi.',
      not: 'Eleştirmen "le critique" (eril) olur; artikel anlamı ayırır.',
    },
    {
      id: 'fr-muz-65', on: 'noter', okunus: 'note', tur: 'fiil',
      arka: 'puan vermek',
      ornek: 'Je le note huit sur dix.',
      ornekTr: 'Ona on üzerinden sekiz veriyorum.',
      not: '"sur" ile puan verilir: huit sur dix.',
    },
    {
      id: 'fr-muz-66', on: 'ça vaut le coup', okunus: 'sa vo lö ku', tur: 'deyim',
      arka: 'buna değer',
      ornek: 'C\'est long, mais ça vaut le coup.',
      ornekTr: 'Uzun ama buna değer.',
      not: '"valoir" değmek fiilinden gelir.',
    },
    {
      id: 'fr-muz-67', on: 'ça me plaît', okunus: 'sa mö ple', tur: 'kalıp',
      arka: 'hoşuma gidiyor',
      ornek: 'Cette chanson me plaît beaucoup.',
      ornekTr: 'Bu şarkı çok hoşuma gidiyor.',
      not: '"plaire" fiilinde özne beğenilen şeydir, kişi değil.',
    },
    {
      id: 'fr-muz-68', on: 'c\'est pas mon truc', okunus: 'se pa mon trük', tur: 'kalıp',
      arka: 'benim tarzım değil',
      ornek: 'Les comédies musicales, c\'est pas mon truc.',
      ornekTr: 'Müzikaller benim tarzım değil.',
      not: 'Konuşmada "ne" düşer; yazıda "ce n\'est pas" olur.',
    },
    {
      id: 'fr-muz-69', on: 'j\'adore', okunus: 'jador', tur: 'kalıp',
      arka: 'bayılıyorum',
      ornek: 'J\'adore cette actrice !',
      ornekTr: 'Bu oyuncuya bayılıyorum!',
      not: '"aimer"den güçlüdür; günlük dilde çok kullanılır.',
    },
    {
      id: 'fr-muz-70', on: 'c\'est nul', okunus: 'se nül', tur: 'kalıp',
      arka: 'berbat',
      ornek: 'La fin est nulle, franchement.',
      ornekTr: 'Final berbat, açıkçası.',
      not: 'Gündelik ve serttir; resmî yazıda kullanılmaz.',
    },
    /* --- Yorum sıfatları --- */
    {
      id: 'fr-muz-71', on: 'émouvant', okunus: 'emuvan', tur: 'sıfat',
      arka: 'duygulandırıcı',
      ornek: 'C\'était une histoire très émouvante.',
      ornekTr: 'Çok duygulandırıcı bir hikâyeydi.',
      not: '"émouvoir" duygulandırmak demektir.',
    },
    {
      id: 'fr-muz-72', on: 'drôle', okunus: 'drol', tur: 'sıfat',
      arka: 'komik',
      ornek: 'Cette scène est vraiment drôle.',
      ornekTr: 'Bu sahne gerçekten komik.',
      not: 'İsimden önce gelirse "tuhaf" anlamına gelir: "une drôle d\'histoire".',
    },
    {
      id: 'fr-muz-73', on: 'prévisible', okunus: 'previzibl', tur: 'sıfat',
      arka: 'tahmin edilebilir',
      ornek: 'La fin était complètement prévisible.',
      ornekTr: 'Final tamamen tahmin edilebilirdi.',
      not: '"prévoir" öngörmek demektir.',
    },
    {
      id: 'fr-muz-74', on: 'effrayant', okunus: 'efreyan', tur: 'sıfat',
      arka: 'korkutucu',
      ornek: 'La maison dans le film est effrayante.',
      ornekTr: 'Filmdeki ev korkutucu.',
      not: '"faire peur" korkutmak demektir.',
    },
    {
      id: 'fr-muz-75', on: 'magnifique', okunus: 'manyifik', tur: 'sıfat',
      arka: 'muhteşem',
      ornek: 'Les paysages sont magnifiques.',
      ornekTr: 'Manzaralar muhteşem.',
      not: 'Görsel güzellik için en çok kullanılan sıfattır.',
    },
    {
      id: 'fr-muz-76', on: 'surestimé', okunus: 'sürestime', tur: 'sıfat',
      arka: 'hak ettiğinden fazla övülen',
      ornek: 'Cette série est surestimée.',
      ornekTr: 'Bu dizi hak ettiğinden fazla övülüyor.',
      not: 'Tersi "sous-estimé" = hak ettiği değeri görmeyen.',
    },
    {
      id: 'fr-muz-77', on: 'prenant', okunus: 'prönan', tur: 'sıfat',
      arka: 'sürükleyici',
      ornek: 'Le premier épisode est très prenant.',
      ornekTr: 'İlk bölüm çok sürükleyici.',
      not: '"prendre" almak, tutmak fiilinden gelir.',
    },
    {
      id: 'fr-muz-78', on: 'lent', okunus: 'lan', tur: 'sıfat',
      arka: 'yavaş',
      ornek: 'Le milieu du film est un peu lent.',
      ornekTr: 'Filmin ortası biraz yavaş.',
      not: 'Zarfı "lentement" = yavaşça.',
    },
    {
      id: 'fr-muz-79', on: 'bien joué', okunus: 'biyen jue', tur: 'kalıp',
      arka: 'iyi oynanmış',
      ornek: 'Le rôle est très bien joué.',
      ornekTr: 'Rol çok iyi oynanmış.',
      not: 'Aynı ifade "aferin!" anlamında da kullanılır.',
    },
    {
      id: 'fr-muz-80', on: 'à voir absolument', okunus: 'a vuar absolüman', tur: 'kalıp',
      arka: 'mutlaka izlenmeli',
      ornek: 'Ce film est à voir absolument.',
      ornekTr: 'Bu film mutlaka izlenmeli.',
      not: '"à + mastar" bir zorunluluk ya da öneri bildirir.',
    },
    /* --- Deyimler --- */
    {
      id: 'fr-muz-81', on: 'avoir un air dans la tête', okunus: 'avuar ön er dan la tet', tur: 'deyim',
      arka: 'melodi aklına takılmak',
      ornek: 'J\'ai cet air dans la tête depuis ce matin.',
      ornekTr: 'Bu melodi sabahtan beri aklıma takıldı.',
      not: '"un air" burada melodi demektir.',
    },
    {
      id: 'fr-muz-82', on: 'faire un carton', okunus: 'fer ön karton', tur: 'deyim',
      arka: 'büyük başarı kazanmak',
      ornek: 'Leur nouvelle chanson fait un carton.',
      ornekTr: 'Yeni şarkıları büyük başarı kazandı.',
      not: 'Atış poligonundaki karton hedeften gelir.',
    },
    {
      id: 'fr-muz-83', on: 'être à fond', okunus: 'etr a fon', tur: 'deyim',
      arka: 'tam kaptırmak, sonuna kadar dalmak',
      ornek: 'Je suis à fond dans cette série.',
      ornekTr: 'Bu diziye tam kaptırdım.',
      not: '"le fond" dip demektir; dibine kadar anlamı taşır.',
    },
    {
      id: 'fr-muz-84', on: 'voler la vedette', okunus: 'vole la vödet', tur: 'deyim',
      arka: 'bütün ilgiyi toplamak',
      ornek: 'Le jeune acteur a volé la vedette.',
      ornekTr: 'Genç oyuncu bütün ilgiyi topladı.',
      not: '"la vedette" yıldız oyuncu demektir.',
    },
    {
      id: 'fr-muz-85', on: 'les coulisses', okunus: 'le kulis', tur: 'isim (çoğul)',
      arka: 'kulis, perde arkası',
      ornek: 'Beaucoup de travail se fait dans les coulisses.',
      ornekTr: 'Perde arkasında çok iş dönüyor.',
      not: 'Türkçedeki "kulis" bu kelimeden gelir.',
    },
    {
      id: 'fr-muz-86', on: 'ça déchire', okunus: 'sa deşir', tur: 'deyim',
      arka: 'çok iyi, harika',
      ornek: 'Leur concert, ça déchire !',
      ornekTr: 'Konserleri harika!',
      not: 'Çok gündelik bir gençlik ifadesidir.',
    },
    {
      id: 'fr-muz-87', on: 'donner le ton', okunus: 'done lö ton', tur: 'deyim',
      arka: 'havayı belirlemek',
      ornek: 'La première scène donne le ton.',
      ornekTr: 'İlk sahne havayı belirliyor.',
      not: 'Müzikten gelir; koroya ton vermekten türer.',
    },
    {
      id: 'fr-muz-88', on: 'faire salle comble', okunus: 'fer sal konbl', tur: 'deyim',
      arka: 'salonu tıklım tıklım doldurmak',
      ornek: 'Le spectacle a fait salle comble.',
      ornekTr: 'Gösteri salonu tıklım tıklım doldurdu.',
      not: '"comble" ağzına kadar dolu demektir.',
    },
    {
      id: 'fr-muz-89', on: 'devenir viral', okunus: 'dövönir viral', tur: 'kalıp',
      arka: 'internette hızla yayılmak',
      ornek: 'Leur vidéo est devenue virale en une nuit.',
      ornekTr: 'Videoları bir gecede yayıldı.',
      not: '"devenir" olmak fiilidir ve "être" ile çekilir.',
    },
    {
      id: 'fr-muz-90', on: 'accro à', okunus: 'akro a', tur: 'sıfat',
      arka: 'bağımlı, kaptırmış',
      ornek: 'Je suis accro à cette série.',
      ornekTr: 'Bu diziye kaptırdım.',
      not: 'Gündelik dilde bağımlılığı esprili biçimde anlatır.',
    },
    /* --- Zevk konuşmaları --- */
    {
      id: 'fr-muz-91', on: 'Tu écoutes quoi ?', okunus: 'tü ekut kua', tur: 'soru kalıbı',
      arka: 'Ne dinliyorsun?',
      ornek: 'Tu écoutes quoi comme musique ?',
      ornekTr: 'Ne tür müzik dinliyorsun?',
      not: 'Konuşmada soru kelimesi sona gelebilir.',
    },
    {
      id: 'fr-muz-92', on: 'ça parle de quoi ?', okunus: 'sa parl dö kua', tur: 'soru kalıbı',
      arka: 'Konusu ne?',
      ornek: 'Ce film, ça parle de quoi ?',
      ornekTr: 'Bu filmin konusu ne?',
      not: '"parler de" bir konudan bahsetmek demektir.',
    },
    {
      id: 'fr-muz-93', on: 'ça dépend', okunus: 'sa depan', tur: 'kalıp',
      arka: 'Duruma göre değişir',
      ornek: 'Ça dépend de mon humeur.',
      ornekTr: 'Ruh hâlime göre değişir.',
      not: 'Edatı "de"dir: dépendre de.',
    },
    {
      id: 'fr-muz-94', on: 'plutôt', okunus: 'plüto', tur: 'zarf',
      arka: 'daha çok, ziyade',
      ornek: 'Je suis plutôt rock que rap.',
      ornekTr: 'Ben rap\'ten çok rock severim.',
      not: 'Tercih belirtirken çok kullanılır.',
    },
    {
      id: 'fr-muz-95', on: 'avoir un faible pour', okunus: 'avuar ön febl pur', tur: 'deyim',
      arka: 'bir şeye zaafı olmak',
      ornek: 'J\'ai un faible pour les vieux films.',
      ornekTr: 'Eski filmlere zaafım var.',
      not: '"faible" zayıf demektir; zayıf noktayı anlatır.',
    },
    {
      id: 'fr-muz-96', on: 'à la longue', okunus: 'a la long', tur: 'kalıp',
      arka: 'zamanla, uzun vadede',
      ornek: 'À la longue, j\'ai aimé cette chanson.',
      ornekTr: 'Zamanla bu şarkıyı sevdim.',
      not: 'Zamanla oluşan değişimi anlatır.',
    },
    {
      id: 'fr-muz-97', on: 'avoir hâte de', okunus: 'avuar at dö', tur: 'kalıp',
      arka: 'sabırsızlanmak',
      ornek: 'J\'ai hâte de voir la nouvelle saison.',
      ornekTr: 'Yeni sezonu görmek için sabırsızlanıyorum.',
      not: 'Sonrasında "de + mastar" gelir.',
    },
    {
      id: 'fr-muz-98', on: 'ça me rappelle', okunus: 'sa mö rapel', tur: 'kalıp',
      arka: 'bana ... hatırlatıyor',
      ornek: 'Ce groupe me rappelle un vieux groupe turc.',
      ornekTr: 'Bu grup bana eski bir Türk grubunu hatırlatıyor.',
      not: '"rappeler" hatırlatmak demektir.',
    },
    {
      id: 'fr-muz-99', on: 'le même que', okunus: 'lö mem kö', tur: 'kalıp',
      arka: 'aynısı',
      ornek: 'Elle a le même goût que moi.',
      ornekTr: 'Onun zevki benimkiyle aynı.',
      not: 'Karşılaştırma edatı "que"dur.',
    },
    {
      id: 'fr-muz-100', on: 'des goûts et des couleurs', okunus: 'de gu e de kulör', tur: 'atasözü',
      arka: 'Zevkler ve renkler tartışılmaz',
      ornek: 'Tu n\'aimes pas ? Des goûts et des couleurs !',
      ornekTr: 'Sevmedin mi? Zevkler ve renkler tartışılmaz!',
      not: 'Tam hâli "des goûts et des couleurs, on ne discute pas"tır.',
    },
  ],
}

export default DESTE
