/**
 * DESTE — SEYAHAT VE ŞEHİR (Fransızca)
 *
 * Bir gün Fransa'ya gitse ilk saatinde ihtiyaç duyacağı kelimeler:
 * havaalanı, bilet, yol sorma, otel. Kartlar "turist ne der" değil,
 * "turist ne DUYAR" mantığıyla da seçildi.
 */

export const DESTE = {
  id: 'seyahat',
  dil: 'fr',
  ad: 'Seyahat ve şehir',
  simge: '✈️',
  aciklama: 'Havaalanında, istasyonda ve sokakta ilk saatte lazım olanlar.',
  seviye: 'A1–A2',
  kartlar: [
    {
      id: 'fr-sey-01', on: 'le billet', okunus: 'lö biye', tur: 'isim',
      arka: 'bilet',
      ornek: "J'ai acheté mon billet en ligne.",
      ornekTr: 'Biletimi internetten aldım.',
      not: '"ll" burada "y" okunur. Kâğıt para da "un billet"dir.',
    },
    {
      id: 'fr-sey-02', on: 'la gare', okunus: 'la gar', tur: 'isim (dişil)',
      arka: 'tren garı',
      ornek: "La gare est à dix minutes à pied.",
      ornekTr: 'Gar yürüyerek on dakika.',
      not: 'Otogar "la gare routière", havaalanı "l\'aéroport".',
    },
    {
      id: 'fr-sey-03', on: 'le quai', okunus: 'lö ke', tur: 'isim',
      arka: 'peron',
      ornek: "Le train part du quai numéro trois.",
      ornekTr: 'Tren üç numaralı perondan kalkıyor.',
      not: 'Anonslarda en çok duyacağın kelimelerden biri.',
    },
    {
      id: 'fr-sey-04', on: 'la valise', okunus: 'la valiz', tur: 'isim (dişil)',
      arka: 'valiz, bavul',
      ornek: "Ma valise est trop lourde.",
      ornekTr: 'Valizim çok ağır.',
      not: 'Sırt çantası "un sac à dos".',
    },
    {
      id: 'fr-sey-05', on: 'perdu', okunus: 'perdü', tur: 'sıfat',
      arka: 'kaybolmuş',
      ornek: "Excusez-moi, je suis perdu.",
      ornekTr: 'Affedersiniz, kayboldum.',
      not: 'Dişil biçimi "perdue". Yol sorarken en işe yarayan cümledir.',
    },
    {
      id: 'fr-sey-06', on: 'tout droit', okunus: 'tu drua', tur: 'kalıp',
      arka: 'dümdüz',
      ornek: "Allez tout droit jusqu'au feu.",
      ornekTr: 'Işığa kadar dümdüz gidin.',
      not: 'Dikkat: "droite" (sağ) ile karışır. "tout droit" = dümdüz.',
    },
    {
      id: 'fr-sey-07', on: "l'auberge de jeunesse", okunus: 'loberj dö jönes', tur: 'isim (dişil)',
      arka: 'gençlik yurdu, hostel',
      ornek: "On dort dans une auberge de jeunesse.",
      ornekTr: 'Bir gençlik yurdunda kalıyoruz.',
      not: 'Öğrenci bütçesiyle seyahatin standart konaklaması.',
    },
    {
      id: 'fr-sey-08', on: 'réserver', okunus: 'rezerve', tur: 'fiil',
      arka: 'rezervasyon yaptırmak',
      ornek: "J'ai réservé une chambre pour deux nuits.",
      ornekTr: 'İki gecelik bir oda ayırttım.',
      not: 'Oda "une chambre", gece "une nuit".',
    },
    {
      id: 'fr-sey-09', on: 'la carte', okunus: 'la kart', tur: 'isim (dişil)',
      arka: 'harita; menü; kart',
      ornek: "Tu as une carte de la ville ?",
      ornekTr: 'Şehir haritan var mı?',
      not: 'Üç anlamı da çok kullanılır: harita, restoran menüsü ve banka kartı.',
    },
    {
      id: 'fr-sey-10', on: 'ça coûte combien', okunus: 'sa kut kombiyen', tur: 'kalıp',
      arka: 'ne kadar tutuyor?',
      ornek: "Ça coûte combien, le ticket de métro ?",
      ornekTr: 'Metro bileti ne kadar tutuyor?',
      not: 'Daha kısası "C\'est combien ?"dir ve günlük dilde daha sık duyulur.',
    },
    /* --- Trenle yolculuk --- */
    {
      id: 'fr-sey-11', on: 'le train', okunus: 'lö tren', tur: 'isim',
      arka: 'tren',
      ornek: 'Le train part à dix heures.',
      ornekTr: 'Tren saat onda kalkıyor.',
      not: '"partir" kalkmak, hareket etmek demektir.',
    },
    {
      id: 'fr-sey-12', on: 'le TGV', okunus: 'lö te je ve', tur: 'isim',
      arka: 'yüksek hızlı tren',
      ornek: 'Le TGV va à Marseille en trois heures.',
      ornekTr: 'Hızlı tren Marsilya\'ya üç saatte gidiyor.',
      not: '"Train à Grande Vitesse" kısaltmasıdır.',
    },
    {
      id: 'fr-sey-13', on: 'arriver', okunus: 'arive', tur: 'fiil',
      arka: 'varmak',
      ornek: 'Nous arrivons à Paris à midi.',
      ornekTr: 'Paris\'e öğlen varıyoruz.',
      not: 'Geçmiş zamanda "être" ile çekilir: je suis arrivé.',
    },
    {
      id: 'fr-sey-14', on: 'le retard', okunus: 'lö rötar', tur: 'isim',
      arka: 'gecikme',
      ornek: 'Le train a vingt minutes de retard.',
      ornekTr: 'Trenin yirmi dakika gecikmesi var.',
      not: '"être en retard" = geç kalmış olmak.',
    },
    {
      id: 'fr-sey-15', on: 'les horaires', okunus: 'lez orer', tur: 'isim (çoğul)',
      arka: 'sefer saatleri',
      ornek: 'Regarde les horaires sur ton téléphone.',
      ornekTr: 'Sefer saatlerine telefonundan bak.',
      not: '"l\'heure" saat demektir.',
    },
    {
      id: 'fr-sey-16', on: 'monter dans le train', okunus: 'monte dan lö tren', tur: 'kalıp',
      arka: 'trene binmek',
      ornek: 'On monte dans le train à Lyon.',
      ornekTr: 'Trene Lyon\'da biniyoruz.',
      not: 'İnmek "descendre du train"dir.',
    },
    {
      id: 'fr-sey-17', on: 'composter', okunus: 'konposte', tur: 'fiil',
      arka: 'bileti damgalatmak',
      ornek: 'N\'oublie pas de composter ton billet.',
      ornekTr: 'Biletini damgalatmayı unutma.',
      not: 'Fransa\'da damgalanmamış bilet cezaya yol açar.',
    },
    {
      id: 'fr-sey-18', on: 'le contrôleur', okunus: 'lö kontrolör', tur: 'isim',
      arka: 'kondüktör',
      ornek: 'Le contrôleur vérifie les billets.',
      ornekTr: 'Kondüktör biletleri kontrol ediyor.',
      not: '"vérifier" doğrulamak, kontrol etmek demektir.',
    },
    {
      id: 'fr-sey-19', on: 'la place', okunus: 'la plas', tur: 'isim',
      arka: 'koltuk, yer',
      ornek: 'Cette place est libre ?',
      ornekTr: 'Bu koltuk boş mu?',
      not: 'Aynı kelime "meydan" anlamına da gelir.',
    },
    {
      id: 'fr-sey-20', on: 'le trajet', okunus: 'lö traje', tur: 'isim',
      arka: 'yol, güzergâh',
      ornek: 'Le trajet dure trois heures.',
      ornekTr: 'Yolculuk üç saat sürüyor.',
      not: '"le voyage" uzun seyahat, "le trajet" gidiş yoludur.',
    },
    /* --- Şehir içi ulaşım --- */
    {
      id: 'fr-sey-21', on: 'le métro', okunus: 'lö metro', tur: 'isim',
      arka: 'metro',
      ornek: 'Prends le métro, c\'est plus rapide.',
      ornekTr: 'Metroya bin, daha hızlı.',
      not: 'Araç için fiil "prendre"dir: prendre le bus.',
    },
    {
      id: 'fr-sey-22', on: 'l\'arrêt', okunus: 'lare', tur: 'isim',
      arka: 'durak',
      ornek: 'Descends au troisième arrêt.',
      ornekTr: 'Üçüncü durakta in.',
      not: '"arrêter" durdurmak fiilinden gelir.',
    },
    {
      id: 'fr-sey-23', on: 'à pied', okunus: 'a pye', tur: 'kalıp',
      arka: 'yürüyerek',
      ornek: 'C\'est à dix minutes à pied.',
      ornekTr: 'Yürüyerek on dakika.',
      not: 'Diğer araçlar "en" alır: en bus, en voiture.',
    },
    {
      id: 'fr-sey-24', on: 'les embouteillages', okunus: 'lez anbutiyaj', tur: 'isim (çoğul)',
      arka: 'trafik sıkışıklığı',
      ornek: 'On est coincés dans les embouteillages.',
      ornekTr: 'Trafikte sıkışıp kaldık.',
      not: '"coincé" sıkışmış demektir.',
    },
    {
      id: 'fr-sey-25', on: 'l\'heure de pointe', okunus: 'lör dö puant', tur: 'isim',
      arka: 'yoğun saat',
      ornek: 'Évite le métro à l\'heure de pointe.',
      ornekTr: 'Yoğun saatte metroya binme.',
      not: '"la pointe" uç, zirve demektir.',
    },
    {
      id: 'fr-sey-26', on: 'le billet', okunus: 'lö biye', tur: 'isim',
      arka: 'bilet',
      ornek: 'J\'achète les billets en ligne.',
      ornekTr: 'Biletleri internetten alıyorum.',
      not: 'Aynı kelime kâğıt para anlamına da gelir.',
    },
    {
      id: 'fr-sey-27', on: 'aller simple ou aller-retour', okunus: 'ale sempl u ale rötur', tur: 'kalıp',
      arka: 'tek yön mü gidiş-dönüş mü',
      ornek: 'Aller simple ou aller-retour ? - Aller-retour, merci.',
      ornekTr: 'Tek yön mü gidiş-dönüş mü? - Gidiş-dönüş, teşekkürler.',
      not: 'Gişede sorulan standart sorudur.',
    },
    {
      id: 'fr-sey-28', on: 'prendre un taxi', okunus: 'prandr ön taksi', tur: 'kalıp',
      arka: 'taksiye binmek',
      ornek: 'S\'il pleut, on prend un taxi.',
      ornekTr: 'Yağmur yağarsa taksiye biniyoruz.',
      not: '"s\'il pleut" = yağmur yağarsa.',
    },
    {
      id: 'fr-sey-29', on: 'déposer quelqu\'un', okunus: 'depoze kelkön', tur: 'kalıp',
      arka: 'birini bir yere bırakmak',
      ornek: 'Tu peux me déposer à l\'école ?',
      ornekTr: 'Beni okula bırakabilir misin?',
      not: '"déposer" bırakmak, koymak demektir.',
    },
    {
      id: 'fr-sey-30', on: 'le tarif', okunus: 'lö tarif', tur: 'isim',
      arka: 'ücret, tarife',
      ornek: 'Le tarif étudiant est moins cher.',
      ornekTr: 'Öğrenci ücreti daha ucuz.',
      not: '"moins cher" daha ucuz demektir.',
    },
    /* --- Havaalanı --- */
    {
      id: 'fr-sey-31', on: 'l\'aéroport', okunus: 'laeropor', tur: 'isim',
      arka: 'havalimanı',
      ornek: 'On arrive à l\'aéroport deux heures avant.',
      ornekTr: 'Havalimanına iki saat önce varıyoruz.',
      not: '"avant" önce demektir.',
    },
    {
      id: 'fr-sey-32', on: 'le vol', okunus: 'lö vol', tur: 'isim',
      arka: 'uçuş',
      ornek: 'Le vol dure trois heures.',
      ornekTr: 'Uçuş üç saat sürüyor.',
      not: 'Aynı kelime "hırsızlık" anlamına da gelir; bağlam ayırır.',
    },
    {
      id: 'fr-sey-33', on: 'l\'enregistrement', okunus: 'lanröjiströman', tur: 'isim',
      arka: 'check-in, giriş işlemi',
      ornek: 'L\'enregistrement ouvre à six heures.',
      ornekTr: 'Giriş işlemleri altıda açılıyor.',
      not: '"enregistrer" kaydetmek demektir.',
    },
    {
      id: 'fr-sey-34', on: 'la carte d\'embarquement', okunus: 'la kart danbarkıman', tur: 'isim',
      arka: 'biniş kartı',
      ornek: 'Garde ta carte d\'embarquement.',
      ornekTr: 'Biniş kartını sakla.',
      not: '"embarquer" binmek (uçak, gemi) demektir.',
    },
    {
      id: 'fr-sey-35', on: 'les bagages', okunus: 'le bagaj', tur: 'isim (çoğul)',
      arka: 'bagaj',
      ornek: 'Je voyage avec un seul bagage.',
      ornekTr: 'Tek bagajla seyahat ediyorum.',
      not: 'El bagajı "le bagage à main"dir.',
    },
    {
      id: 'fr-sey-36', on: 'la douane', okunus: 'la duan', tur: 'isim',
      arka: 'gümrük',
      ornek: 'On passe la douane rapidement.',
      ornekTr: 'Gümrükten hızlıca geçiyoruz.',
      not: 'Gümrük memuru "le douanier"dir.',
    },
    {
      id: 'fr-sey-37', on: 'le passeport', okunus: 'lö paspor', tur: 'isim',
      arka: 'pasaport',
      ornek: 'Mon passeport est encore valable.',
      ornekTr: 'Pasaportum hâlâ geçerli.',
      not: '"valable" geçerli demektir.',
    },
    {
      id: 'fr-sey-38', on: 'le décalage horaire', okunus: 'lö dekalaj orer', tur: 'isim',
      arka: 'saat farkı, jet lag',
      ornek: 'J\'ai eu du décalage horaire pendant trois jours.',
      ornekTr: 'Üç gün saat farkı yorgunluğu yaşadım.',
      not: '"décaler" kaydırmak demektir.',
    },
    {
      id: 'fr-sey-39', on: 'la porte d\'embarquement', okunus: 'la port danbarkıman', tur: 'isim',
      arka: 'biniş kapısı',
      ornek: 'La porte d\'embarquement ferme vingt minutes avant.',
      ornekTr: 'Biniş kapısı yirmi dakika önce kapanıyor.',
      not: 'Kısaca "la porte" denir.',
    },
    {
      id: 'fr-sey-40', on: 'décoller', okunus: 'dekole', tur: 'fiil',
      arka: 'havalanmak',
      ornek: 'L\'avion décolle à l\'heure.',
      ornekTr: 'Uçak zamanında havalanıyor.',
      not: 'İnmek "atterrir"dir; "la terre" toprak demektir.',
    },
    /* --- Konaklama --- */
    {
      id: 'fr-sey-41', on: 'l\'hébergement', okunus: 'leberjıman', tur: 'isim',
      arka: 'konaklama',
      ornek: 'L\'hébergement était propre et pas cher.',
      ornekTr: 'Konaklama temiz ve ucuzdu.',
      not: '"héberger" barındırmak demektir.',
    },
    {
      id: 'fr-sey-42', on: 'la chambre double', okunus: 'la şanbr dubl', tur: 'isim',
      arka: 'iki kişilik oda',
      ornek: 'Nous voudrions une chambre double.',
      ornekTr: 'İki kişilik bir oda istiyoruz.',
      not: '"nous voudrions" en kibar istek biçimidir.',
    },
    {
      id: 'fr-sey-43', on: 'la nuitée', okunus: 'la nüite', tur: 'isim',
      arka: 'geceleme',
      ornek: 'La nuitée coûte cinquante euros.',
      ornekTr: 'Geceleme elli avro.',
      not: '"la nuit" gece demektir.',
    },
    {
      id: 'fr-sey-44', on: 'petit-déjeuner compris', okunus: 'pöti dejöne konpri', tur: 'kalıp',
      arka: 'kahvaltı dâhil',
      ornek: 'Le prix est petit-déjeuner compris.',
      ornekTr: 'Fiyata kahvaltı dâhil.',
      not: '"comprendre" burada içermek anlamındadır.',
    },
    {
      id: 'fr-sey-45', on: 'la réception', okunus: 'la resepsyon', tur: 'isim',
      arka: 'resepsiyon',
      ornek: 'La clé est à la réception.',
      ornekTr: 'Anahtar resepsiyonda.',
      not: '"recevoir" kabul etmek fiilinden gelir.',
    },
    {
      id: 'fr-sey-46', on: 'complet', okunus: 'konple', tur: 'sıfat',
      arka: 'dolu',
      ornek: 'L\'hôtel est complet en août.',
      ornekTr: 'Otel ağustosta dolu.',
      not: 'Restoran ve tren için de kullanılır.',
    },
    {
      id: 'fr-sey-47', on: 'annuler', okunus: 'anüle', tur: 'fiil',
      arka: 'iptal etmek',
      ornek: 'Je voudrais annuler ma réservation.',
      ornekTr: 'Rezervasyonumu iptal etmek istiyorum.',
      not: '"l\'annulation" iptal demektir.',
    },
    {
      id: 'fr-sey-48', on: 'les arrhes', okunus: 'lez ar', tur: 'isim (çoğul)',
      arka: 'kapora',
      ornek: 'Ils demandent des arrhes.',
      ornekTr: 'Kapora istiyorlar.',
      not: 'Baştaki "h" okunmaz ve kelime çoğuldur.',
    },
    {
      id: 'fr-sey-49', on: 'l\'auberge de jeunesse', okunus: 'loberj dö jönes', tur: 'isim',
      arka: 'gençlik hosteli',
      ornek: 'Les auberges de jeunesse sont moins chères.',
      ornekTr: 'Gençlik hostelleri daha ucuz.',
      not: '"la jeunesse" gençlik demektir.',
    },
    {
      id: 'fr-sey-50', on: 'le gîte', okunus: 'lö jit', tur: 'isim',
      arka: 'kırsal konaklama evi',
      ornek: 'Nous louons un gîte à la campagne.',
      ornekTr: 'Kırsalda bir ev kiralıyoruz.',
      not: 'Fransa\'da çok yaygın bir tatil konaklama biçimidir.',
    },
    /* --- Yol tarifi --- */
    {
      id: 'fr-sey-51', on: 'Comment aller à...?', okunus: 'koman ale a', tur: 'soru kalıbı',
      arka: '... nasıl gidilir?',
      ornek: 'Comment aller à la gare, s\'il vous plaît ?',
      ornekTr: 'Gara nasıl gidilir lütfen?',
      not: 'Kibar biçimde "s\'il vous plaît" eklenir.',
    },
    {
      id: 'fr-sey-52', on: 'le carrefour', okunus: 'lö karfur', tur: 'isim',
      arka: 'kavşak',
      ornek: 'Tourne à droite au carrefour.',
      ornekTr: 'Kavşaktan sağa dön.',
      not: 'Ünlü market zinciri adını bu kelimeden alır.',
    },
    {
      id: 'fr-sey-53', on: 'le feu rouge', okunus: 'lö fö ruj', tur: 'isim',
      arka: 'trafik ışığı',
      ornek: 'Tourne à gauche au feu rouge.',
      ornekTr: 'Trafik ışığından sola dön.',
      not: '"le feu" ateş, ışık demektir.',
    },
    {
      id: 'fr-sey-54', on: 'en face de', okunus: 'an fas dö', tur: 'kalıp',
      arka: 'karşısında',
      ornek: 'La banque est en face de la poste.',
      ornekTr: 'Banka postanenin karşısında.',
      not: 'Yan yana olan "à côté de"dir.',
    },
    {
      id: 'fr-sey-55', on: 'près de / loin de', okunus: 'pre dö / luen dö', tur: 'kalıp',
      arka: 'yakınında / uzağında',
      ornek: 'L\'hôtel est près du musée.',
      ornekTr: 'Otel müzenin yakınında.',
      not: '"de + le" birleşip "du" olur.',
    },
    {
      id: 'fr-sey-56', on: 'au coin de la rue', okunus: 'o kuen dö la rü', tur: 'kalıp',
      arka: 'sokağın köşesinde',
      ornek: 'La pharmacie est au coin de la rue.',
      ornekTr: 'Eczane sokağın köşesinde.',
      not: '"le coin" köşe demektir.',
    },
    {
      id: 'fr-sey-57', on: 'se perdre', okunus: 'sö perdr', tur: 'fiil (dönüşlü)',
      arka: 'kaybolmak',
      ornek: 'On s\'est perdus dans la vieille ville.',
      ornekTr: 'Eski şehirde kaybolduk.',
      not: 'Geçmiş zamanda "être" ile çekilir.',
    },
    {
      id: 'fr-sey-58', on: 'le plan de la ville', okunus: 'lö plan dö la vil', tur: 'isim',
      arka: 'şehir haritası',
      ornek: 'Tu as un plan de la ville ?',
      ornekTr: 'Şehir haritan var mı?',
      not: '"la carte" genel harita, "le plan" şehir planıdır.',
    },
    {
      id: 'fr-sey-59', on: 'le passage piéton', okunus: 'lö pasaj piyeton', tur: 'isim',
      arka: 'yaya geçidi',
      ornek: 'Utilise le passage piéton.',
      ornekTr: 'Yaya geçidini kullan.',
      not: '"le piéton" yaya demektir.',
    },
    {
      id: 'fr-sey-60', on: 'C\'est loin ?', okunus: 'se luen', tur: 'soru kalıbı',
      arka: 'Uzak mı?',
      ornek: 'La plage, c\'est loin d\'ici ?',
      ornekTr: 'Plaj buradan uzak mı?',
      not: 'Cevabı "à dix minutes" gibi verilir.',
    },
    /* --- Tatil ve gezi --- */
    {
      id: 'fr-sey-61', on: 'les vacances', okunus: 'le vakans', tur: 'isim (çoğul)',
      arka: 'tatil',
      ornek: 'On part en vacances en juillet.',
      ornekTr: 'Temmuzda tatile çıkıyoruz.',
      not: 'Her zaman çoğuldur ve "partir en vacances" kalıbı kullanılır.',
    },
    {
      id: 'fr-sey-62', on: 'l\'excursion', okunus: 'lekskürsyon', tur: 'isim',
      arka: 'günübirlik gezi',
      ornek: 'Nous avons fait une excursion au lac.',
      ornekTr: 'Göle günübirlik bir gezi yaptık.',
      not: 'Fiili "faire"dir.',
    },
    {
      id: 'fr-sey-63', on: 'visiter', okunus: 'vizite', tur: 'fiil',
      arka: 'gezmek (yer)',
      ornek: 'Nous visitons le château demain.',
      ornekTr: 'Yarın şatoyu geziyoruz.',
      not: 'Kişiyi ziyaret için "rendre visite à" kullanılır.',
    },
    {
      id: 'fr-sey-64', on: 'la visite guidée', okunus: 'la vizit gide', tur: 'isim',
      arka: 'rehberli tur',
      ornek: 'La visite guidée dure une heure.',
      ornekTr: 'Rehberli tur bir saat sürüyor.',
      not: '"le guide" rehber demektir.',
    },
    {
      id: 'fr-sey-65', on: 'l\'entrée est gratuite', okunus: 'lantre e gratüit', tur: 'kalıp',
      arka: 'Giriş ücretsiz',
      ornek: 'Pour les étudiants, l\'entrée est gratuite.',
      ornekTr: 'Öğrenciler için giriş ücretsiz.',
      not: '"gratuit" bedava demektir.',
    },
    {
      id: 'fr-sey-66', on: 'la randonnée', okunus: 'la randone', tur: 'isim',
      arka: 'doğa yürüyüşü',
      ornek: 'On fait de la randonnée en montagne.',
      ornekTr: 'Dağda doğa yürüyüşü yapıyoruz.',
      not: '"faire de la randonnée" kalıbı kullanılır.',
    },
    {
      id: 'fr-sey-67', on: 'le souvenir', okunus: 'lö suvönir', tur: 'isim',
      arka: 'hatıra, hediyelik eşya',
      ornek: 'J\'ai acheté un petit souvenir.',
      ornekTr: 'Küçük bir hediyelik aldım.',
      not: 'Aynı kelime "anı" anlamına da gelir.',
    },
    {
      id: 'fr-sey-68', on: 'la carte postale', okunus: 'la kart postal', tur: 'isim',
      arka: 'kartpostal',
      ornek: 'Je t\'envoie une carte postale.',
      ornekTr: 'Sana bir kartpostal gönderiyorum.',
      not: '"envoyer" göndermek demektir.',
    },
    {
      id: 'fr-sey-69', on: 'la haute saison', okunus: 'la ot sezon', tur: 'isim',
      arka: 'yoğun sezon',
      ornek: 'Les prix doublent en haute saison.',
      ornekTr: 'Fiyatlar yoğun sezonda ikiye katlanıyor.',
      not: 'Sakin dönem "la basse saison"dur.',
    },
    {
      id: 'fr-sey-70', on: 'voyager léger', okunus: 'vuayaje leje', tur: 'kalıp',
      arka: 'az eşyayla seyahat etmek',
      ornek: 'Je préfère voyager léger.',
      ornekTr: 'Az eşyayla seyahat etmeyi tercih ediyorum.',
      not: '"léger" hafif demektir.',
    },
    /* --- Sorunlar --- */
    {
      id: 'fr-sey-71', on: 'rater le train', okunus: 'rate lö tren', tur: 'kalıp',
      arka: 'treni kaçırmak',
      ornek: 'On a failli rater le train.',
      ornekTr: 'Neredeyse treni kaçırıyorduk.',
      not: '"faillir + mastar" = az kalsın yapmak.',
    },
    {
      id: 'fr-sey-72', on: 'les objets trouvés', okunus: 'lez obje truve', tur: 'isim (çoğul)',
      arka: 'kayıp eşya bürosu',
      ornek: 'Demande aux objets trouvés.',
      ornekTr: 'Kayıp eşya bürosuna sor.',
      not: 'Kelimesi kelimesine "bulunmuş eşyalar" demektir.',
    },
    {
      id: 'fr-sey-73', on: 'se faire voler', okunus: 'sö fer vole', tur: 'kalıp',
      arka: 'çaldırmak',
      ornek: 'Je me suis fait voler mon téléphone.',
      ornekTr: 'Telefonumu çaldırdım.',
      not: '"se faire + mastar" başına gelen bir şeyi anlatır.',
    },
    {
      id: 'fr-sey-74', on: 'l\'assurance voyage', okunus: 'lasürans vuayaj', tur: 'isim',
      arka: 'seyahat sigortası',
      ornek: 'Prends une assurance voyage.',
      ornekTr: 'Seyahat sigortası yaptır.',
      not: '"assurer" güvence altına almak demektir.',
    },
    {
      id: 'fr-sey-75', on: 'l\'urgence', okunus: 'lürjans', tur: 'isim',
      arka: 'acil durum',
      ornek: 'En cas d\'urgence, appelle le 112.',
      ornekTr: 'Acil durumda 112\'yi ara.',
      not: '"en cas de" = ... durumunda.',
    },
    {
      id: 'fr-sey-76', on: 'tomber en panne', okunus: 'tonbe an pan', tur: 'kalıp',
      arka: 'bozulmak (araç)',
      ornek: 'Notre voiture est tombée en panne.',
      ornekTr: 'Arabamız bozuldu.',
      not: '"la panne" arıza demektir.',
    },
    {
      id: 'fr-sey-77', on: 'se plaindre de', okunus: 'sö plendr dö', tur: 'fiil (dönüşlü)',
      arka: 'şikâyet etmek',
      ornek: 'Nous nous sommes plaints du bruit.',
      ornekTr: 'Gürültüden şikâyet ettik.',
      not: 'Edatı "de"dir.',
    },
    {
      id: 'fr-sey-78', on: 'faire attention à', okunus: 'fer atansyon a', tur: 'kalıp',
      arka: 'dikkat etmek',
      ornek: 'Fais attention aux pickpockets.',
      ornekTr: 'Yankesicilere dikkat et.',
      not: '"à + les" birleşip "aux" olur.',
    },
    {
      id: 'fr-sey-79', on: 'le renseignement', okunus: 'lö ransenyıman', tur: 'isim',
      arka: 'bilgi, danışma',
      ornek: 'Demande un renseignement au guichet.',
      ornekTr: 'Gişeden bilgi al.',
      not: '"le guichet" gişe demektir.',
    },
    {
      id: 'fr-sey-80', on: 'régler un problème', okunus: 'regle ön problem', tur: 'kalıp',
      arka: 'sorunu halletmek',
      ornek: 'Ils ont réglé le problème rapidement.',
      ornekTr: 'Sorunu hızlıca hallettiler.',
      not: '"régler" ayarlamak, ödemek anlamına da gelir.',
    },
    /* --- Şehir ve mekân --- */
    {
      id: 'fr-sey-81', on: 'le centre-ville', okunus: 'lö santr vil', tur: 'isim',
      arka: 'şehir merkezi',
      ornek: 'Notre hôtel est au centre-ville.',
      ornekTr: 'Otelimiz şehir merkezinde.',
      not: 'Edatı "au"dur: au centre-ville.',
    },
    {
      id: 'fr-sey-82', on: 'la banlieue', okunus: 'la banliyö', tur: 'isim',
      arka: 'şehrin dış mahalleleri',
      ornek: 'Ils habitent en banlieue.',
      ornekTr: 'Şehrin dışında oturuyorlar.',
      not: 'Fransız şehir yaşamının önemli bir kavramıdır.',
    },
    {
      id: 'fr-sey-83', on: 'la vieille ville', okunus: 'la viyey vil', tur: 'isim',
      arka: 'tarihî şehir merkezi',
      ornek: 'La vieille ville est magnifique.',
      ornekTr: 'Tarihî merkez muhteşem.',
      not: '"vieux" sıfatının dişil hâli "vieille"dir.',
    },
    {
      id: 'fr-sey-84', on: 'bondé', okunus: 'bonde', tur: 'sıfat',
      arka: 'tıklım tıklım',
      ornek: 'Le marché était bondé.',
      ornekTr: 'Pazar tıklım tıklımdı.',
      not: 'Metro ve otobüs için de kullanılır.',
    },
    {
      id: 'fr-sey-85', on: 'animé', okunus: 'anime', tur: 'sıfat',
      arka: 'hareketli, canlı (yer)',
      ornek: 'Ce quartier est très animé le soir.',
      ornekTr: 'Bu mahalle akşamları çok hareketli.',
      not: '"le quartier" mahalle demektir.',
    },
    {
      id: 'fr-sey-86', on: 'le paysage', okunus: 'lö peyzaj', tur: 'isim',
      arka: 'manzara, peyzaj',
      ornek: 'Le paysage sur la route était superbe.',
      ornekTr: 'Yoldaki manzara harikaydı.',
      not: 'Türkçedeki "peyzaj" bu kelimeden gelir.',
    },
    {
      id: 'fr-sey-87', on: 'la vue sur', okunus: 'la vü sür', tur: 'kalıp',
      arka: '... manzarası',
      ornek: 'La chambre a une vue sur la mer.',
      ornekTr: 'Odanın deniz manzarası var.',
      not: 'Edatı "sur"dur.',
    },
    {
      id: 'fr-sey-88', on: 'ça vaut le détour', okunus: 'sa vo lö detur', tur: 'deyim',
      arka: 'gidip görmeye değer',
      ornek: 'Ce village vaut vraiment le détour.',
      ornekTr: 'Bu köy gerçekten gidip görmeye değer.',
      not: '"le détour" yoldan sapma demektir.',
    },
    {
      id: 'fr-sey-89', on: 'se balader', okunus: 'sö balade', tur: 'fiil (dönüşlü)',
      arka: 'gezinmek, dolaşmak',
      ornek: 'On s\'est baladés toute la journée.',
      ornekTr: 'Bütün gün dolaştık.',
      not: '"la balade" gezinti demektir.',
    },
    {
      id: 'fr-sey-90', on: 'dépaysant', okunus: 'depeyizan', tur: 'sıfat',
      arka: 'insanı bambaşka bir yerde hissettiren',
      ornek: 'Ce voyage était très dépaysant.',
      ornekTr: 'Bu yolculuk insanı bambaşka bir dünyaya taşıdı.',
      not: '"le pays" ülke demektir; Türkçede tek kelimelik karşılığı yoktur.',
    },
    /* --- Yolculuk kalıpları --- */
    {
      id: 'fr-sey-91', on: 'Bon voyage !', okunus: 'bon vuayaj', tur: 'kalıp',
      arka: 'İyi yolculuklar!',
      ornek: 'Bon voyage et donne-moi des nouvelles !',
      ornekTr: 'İyi yolculuklar, haber ver!',
      not: '"donner des nouvelles" = haber vermek.',
    },
    {
      id: 'fr-sey-92', on: 'Où est...?', okunus: 'u e', tur: 'soru kalıbı',
      arka: '... nerede?',
      ornek: 'Où est l\'arrêt de bus le plus proche ?',
      ornekTr: 'En yakın otobüs durağı nerede?',
      not: '"le plus proche" en yakın demektir.',
    },
    {
      id: 'fr-sey-93', on: 'Vous pouvez m\'aider ?', okunus: 'vu puve mede', tur: 'soru kalıbı',
      arka: 'Bana yardım edebilir misiniz?',
      ornek: 'Excusez-moi, vous pouvez m\'aider ?',
      ornekTr: 'Affedersiniz, bana yardım edebilir misiniz?',
      not: 'Yabancıya "vous" ile hitap edilir.',
    },
    {
      id: 'fr-sey-94', on: 'Je ne comprends pas', okunus: 'jö nö konpran pa', tur: 'kalıp',
      arka: 'Anlamıyorum',
      ornek: 'Désolé, je ne comprends pas.',
      ornekTr: 'Üzgünüm, anlamıyorum.',
      not: 'Ardından "Pouvez-vous répéter ?" denebilir.',
    },
    {
      id: 'fr-sey-95', on: 'Vous parlez anglais ?', okunus: 'vu parle angle', tur: 'soru kalıbı',
      arka: 'İngilizce biliyor musunuz?',
      ornek: 'Excusez-moi, vous parlez anglais ?',
      ornekTr: 'Affedersiniz, İngilizce biliyor musunuz?',
      not: 'Dil adları küçük harfle yazılır: anglais, turc.',
    },
    {
      id: 'fr-sey-96', on: 'Ça prend combien de temps ?', okunus: 'sa pran konbiyen dö tan', tur: 'soru kalıbı',
      arka: 'Ne kadar sürüyor?',
      ornek: 'Ça prend combien de temps en bus ?',
      ornekTr: 'Otobüsle ne kadar sürüyor?',
      not: '"prendre du temps" = zaman almak.',
    },
    {
      id: 'fr-sey-97', on: 'Je voudrais...', okunus: 'jö vudre', tur: 'kalıp',
      arka: '... istiyorum (kibar)',
      ornek: 'Je voudrais un billet pour Lyon.',
      ornekTr: 'Lyon\'a bir bilet istiyorum.',
      not: 'Gişede ve restoranda en kibar istek biçimidir.',
    },
    {
      id: 'fr-sey-98', on: 'Bon séjour !', okunus: 'bon sejur', tur: 'kalıp',
      arka: 'İyi konaklamalar!',
      ornek: 'Voici votre clé. Bon séjour !',
      ornekTr: 'Anahtarınız burada. İyi konaklamalar!',
      not: '"le séjour" kalış süresi demektir.',
    },
    {
      id: 'fr-sey-99', on: 'D\'où venez-vous ?', okunus: 'du vöne vu', tur: 'soru kalıbı',
      arka: 'Nerelisiniz?',
      ornek: 'D\'où venez-vous exactement ?',
      ornekTr: 'Tam olarak nerelisiniz?',
      not: 'Samimi hâli "Tu viens d\'où ?"dur.',
    },
    {
      id: 'fr-sey-100', on: 'Les voyages forment la jeunesse', okunus: 'le vuayaj form la jönes', tur: 'atasözü',
      arka: 'Seyahat gençliği yetiştirir',
      ornek: 'Pars découvrir : les voyages forment la jeunesse.',
      ornekTr: 'Keşfetmeye çık: seyahat gençliği yetiştirir.',
      not: 'Fransızların en bilinen seyahat atasözüdür.',
    },
  ],
}

export default DESTE
