/**
 * DESTE — YEMEK VE TATLAR (Fransızca)
 *
 * Fransız mutfağı kelimeleri dünyaya yayılmıştır; öğrenci bunların çoğunu
 * zaten biliyor ama YANLIŞ sesle biliyor (croissant, crêpe). Kartlarda
 * okunuş bilgisi bu yüzden ayrıca verildi.
 */

export const DESTE = {
  id: 'yemek',
  dil: 'fr',
  ad: 'Yemek ve tatlar',
  simge: '🥐',
  aciklama: 'Kafede, fırında ve sofrada geçen kelimeler; bildiğini sandıkların dâhil.',
  seviye: 'A1–A2',
  kartlar: [
    {
      id: 'fr-yem-01', on: 'le petit-déjeuner', okunus: 'lö pöti dejöne', tur: 'isim',
      arka: 'kahvaltı',
      ornek: "Je prends mon petit-déjeuner à sept heures.",
      ornekTr: 'Kahvaltımı yedide yapıyorum.',
      not: 'Kahvaltı yapmak "prendre le petit-déjeuner"dır; "faire" değil.',
    },
    {
      id: 'fr-yem-02', on: 'le croissant', okunus: 'lö kruasan', tur: 'isim',
      arka: 'kruvasan',
      ornek: "Un croissant et un café, s'il vous plaît.",
      ornekTr: 'Bir kruvasan ve bir kahve, lütfen.',
      not: 'Sondaki "t" okunmaz ve "oi" → "ua"dır: "kruasan".',
    },
    {
      id: 'fr-yem-03', on: 'la crêpe', okunus: 'la krep', tur: 'isim (dişil)',
      arka: 'krep',
      ornek: "On mange des crêpes tous les mardis.",
      ornekTr: 'Her salı krep yiyoruz.',
      not: 'Dişildir: UNE crêpe. Şapkalı "ê" açık okunur.',
    },
    {
      id: 'fr-yem-04', on: 'avoir faim', okunus: 'avuar fen', tur: 'kalıp',
      arka: 'acıkmak, aç olmak',
      ornek: "J'ai faim, on mange quelque chose ?",
      ornekTr: 'Acıktım, bir şeyler yiyelim mi?',
      not: '"Je suis faim" YANLIŞTIR. Açlık sahip olunan bir şeydir: J\'AI faim.',
    },
    {
      id: 'fr-yem-05', on: 'délicieux', okunus: 'delisyö', tur: 'sıfat',
      arka: 'çok lezzetli',
      ornek: "Ce gâteau est délicieux !",
      ornekTr: 'Bu pasta çok lezzetli!',
      not: 'Dişili "délicieuse". Günlük dilde "trop bon" da denir.',
    },
    {
      id: 'fr-yem-06', on: "l'addition", okunus: 'ladisyon', tur: 'isim (dişil)',
      arka: 'hesap (restoranda)',
      ornek: "L'addition, s'il vous plaît.",
      ornekTr: 'Hesap, lütfen.',
      not: 'Matematikteki "toplama" ile aynı kelimedir.',
    },
    {
      id: 'fr-yem-07', on: 'la boulangerie', okunus: 'la bulanjri', tur: 'isim (dişil)',
      arka: 'fırın, ekmekçi',
      ornek: "Je passe à la boulangerie avant l'école.",
      ornekTr: 'Okuldan önce fırına uğruyorum.',
      not: 'Pastane "la pâtisserie"dir; ikisi çoğu zaman aynı dükkândır.',
    },
    {
      id: 'fr-yem-08', on: 'goûter', okunus: 'gute', tur: 'fiil',
      arka: 'tatmak',
      ornek: "Tu veux goûter ma glace ?",
      ornekTr: 'Dondurmamı tatmak ister misin?',
      not: 'İsim hâli "le goûter" ikindi atıştırması demektir.',
    },
    {
      id: 'fr-yem-09', on: 'à emporter', okunus: 'a amporte', tur: 'kalıp',
      arka: 'paket, dışarı (götürmek için)',
      ornek: "Un sandwich à emporter, s'il vous plaît.",
      ornekTr: 'Bir sandviç paket, lütfen.',
      not: 'Karşıtı "sur place" (burada yemek).',
    },
    {
      id: 'fr-yem-10', on: 'avoir soif', okunus: 'avuar suaf', tur: 'kalıp',
      arka: 'susamak',
      ornek: "J'ai soif, je vais boire de l'eau.",
      ornekTr: 'Susadım, su içeceğim.',
      not: '"avoir faim" ile aynı mantık: susuzluk da sahip olunur.',
    },
    /* --- Temel yiyecekler --- */
    {
      id: 'fr-yem-11', on: 'le pain', okunus: 'lö pen', tur: 'isim',
      arka: 'ekmek',
      ornek: 'On achète du pain frais chaque matin.',
      ornekTr: 'Her sabah taze ekmek alıyoruz.',
      not: 'Baget "la baguette"tir ve Fransız kültürünün simgesidir.',
    },
    {
      id: 'fr-yem-12', on: 'le fromage', okunus: 'lö fromaj', tur: 'isim',
      arka: 'peynir',
      ornek: 'La France produit des centaines de fromages.',
      ornekTr: 'Fransa yüzlerce peynir üretiyor.',
      not: 'Fransa\'da peynir yemekten sonra, tatlıdan önce yenir.',
    },
    {
      id: 'fr-yem-13', on: 'le beurre', okunus: 'lö bör', tur: 'isim',
      arka: 'tereyağı',
      ornek: 'Passe-moi le beurre, s\'il te plaît.',
      ornekTr: 'Tereyağını uzatır mısın lütfen?',
      not: '"passer" burada uzatmak anlamındadır.',
    },
    {
      id: 'fr-yem-14', on: 'la viande', okunus: 'la viyand', tur: 'isim',
      arka: 'et',
      ornek: 'Je mange peu de viande.',
      ornekTr: 'Az et yiyorum.',
      not: 'Miktar sonrası "de" gelir: peu de viande, beaucoup de viande.',
    },
    {
      id: 'fr-yem-15', on: 'le poisson', okunus: 'lö puason', tur: 'isim',
      arka: 'balık',
      ornek: 'Le poisson est très frais ici.',
      ornekTr: 'Balık burada çok taze.',
      not: '"le poison" (zehir) ile karıştırma; tek "s" farkı vardır.',
    },
    {
      id: 'fr-yem-16', on: 'les légumes', okunus: 'le legüm', tur: 'isim (çoğul)',
      arka: 'sebzeler',
      ornek: 'Mange plus de légumes !',
      ornekTr: 'Daha çok sebze ye!',
      not: 'Eril bir isimdir: "un légume".',
    },
    {
      id: 'fr-yem-17', on: 'les pâtes', okunus: 'le pat', tur: 'isim (çoğul)',
      arka: 'makarna',
      ornek: 'On fait des pâtes ce soir.',
      ornekTr: 'Bu akşam makarna yapıyoruz.',
      not: 'Tekil "la pâte" hamur demektir; çoğulu makarnadır.',
    },
    {
      id: 'fr-yem-18', on: 'le riz', okunus: 'lö ri', tur: 'isim',
      arka: 'pirinç, pilav',
      ornek: 'Le riz accompagne bien ce plat.',
      ornekTr: 'Pilav bu yemeğin yanına iyi gider.',
      not: '"accompagner" eşlik etmek demektir. Sondaki "z" okunmaz.',
    },
    {
      id: 'fr-yem-19', on: 'l\'œuf', okunus: 'löf', tur: 'isim',
      arka: 'yumurta',
      ornek: 'Je mange un œuf chaque matin.',
      ornekTr: 'Her sabah bir yumurta yiyorum.',
      not: 'Tekilde "öf", çoğulda "le zö" okunur; okunuş değişir.',
    },
    {
      id: 'fr-yem-20', on: 'la soupe', okunus: 'la sup', tur: 'isim',
      arka: 'çorba',
      ornek: 'La soupe est encore trop chaude.',
      ornekTr: 'Çorba hâlâ çok sıcak.',
      not: 'Çorba "manger" ile yenir, "boire" ile içilmez.',
    },
    /* --- Pişirme --- */
    {
      id: 'fr-yem-21', on: 'cuire', okunus: 'küir', tur: 'fiil',
      arka: 'pişirmek',
      ornek: 'Fais cuire les pommes de terre vingt minutes.',
      ornekTr: 'Patatesleri yirmi dakika pişir.',
      not: '"faire cuire" kalıbı çok kullanılır.',
    },
    {
      id: 'fr-yem-22', on: 'bouillir', okunus: 'buyir', tur: 'fiil',
      arka: 'kaynamak, haşlamak',
      ornek: 'Fais bouillir l\'eau d\'abord.',
      ornekTr: 'Önce suyu kaynat.',
      not: '"d\'abord" önce, ilk olarak demektir.',
    },
    {
      id: 'fr-yem-23', on: 'frire', okunus: 'frir', tur: 'fiil',
      arka: 'kızartmak',
      ornek: 'Elle fait frire les pommes de terre.',
      ornekTr: 'Patatesleri kızartıyor.',
      not: 'Patates kızartması "les frites"tir.',
    },
    {
      id: 'fr-yem-24', on: 'couper', okunus: 'kupe', tur: 'fiil',
      arka: 'kesmek, doğramak',
      ornek: 'Coupe les oignons finement.',
      ornekTr: 'Soğanları ince doğra.',
      not: '"finement" ince ince demektir.',
    },
    {
      id: 'fr-yem-25', on: 'éplucher', okunus: 'eplüşe', tur: 'fiil',
      arka: 'soymak',
      ornek: 'Épluche les carottes avant de les cuire.',
      ornekTr: 'Havuçları pişirmeden önce soy.',
      not: '"avant de + mastar" = -meden önce.',
    },
    {
      id: 'fr-yem-26', on: 'mélanger', okunus: 'melanje', tur: 'fiil',
      arka: 'karıştırmak',
      ornek: 'Mélange bien tous les ingrédients.',
      ornekTr: 'Bütün malzemeleri iyice karıştır.',
      not: '"le mélange" karışım demektir.',
    },
    {
      id: 'fr-yem-27', on: 'assaisonner', okunus: 'asezone', tur: 'fiil',
      arka: 'baharatlamak, tatlandırmak',
      ornek: 'Assaisonne avec du sel et du poivre.',
      ornekTr: 'Tuz ve karabiberle tatlandır.',
      not: '"la saison" mevsim demektir; kelime oradan türer.',
    },
    {
      id: 'fr-yem-28', on: 'la recette', okunus: 'la rösset', tur: 'isim',
      arka: 'tarif',
      ornek: 'C\'est la recette de ma grand-mère.',
      ornekTr: 'Bu babaannemin tarifi.',
      not: 'Aynı kelime doktor reçetesi için kullanılmaz; o "l\'ordonnance"tır.',
    },
    {
      id: 'fr-yem-29', on: 'les ingrédients', okunus: 'lez engredyan', tur: 'isim (çoğul)',
      arka: 'malzemeler',
      ornek: 'Il faut seulement cinq ingrédients.',
      ornekTr: 'Sadece beş malzeme gerekiyor.',
      not: '"il faut" gerekir demektir.',
    },
    {
      id: 'fr-yem-30', on: 'le four', okunus: 'lö fur', tur: 'isim',
      arka: 'fırın',
      ornek: 'Préchauffe le four à cent quatre-vingts degrés.',
      ornekTr: 'Fırını yüz seksen dereceye ısıt.',
      not: '"préchauffer" önceden ısıtmak demektir.',
    },
    /* --- Tat ve doku --- */
    {
      id: 'fr-yem-31', on: 'sucré', okunus: 'sükre', tur: 'sıfat',
      arka: 'tatlı',
      ornek: 'Ce thé est trop sucré pour moi.',
      ornekTr: 'Bu çay benim için fazla tatlı.',
      not: '"le sucre" şeker demektir.',
    },
    {
      id: 'fr-yem-32', on: 'salé', okunus: 'sale', tur: 'sıfat',
      arka: 'tuzlu',
      ornek: 'La soupe est un peu trop salée.',
      ornekTr: 'Çorba biraz fazla tuzlu.',
      not: 'Fransa\'da tuzlu atıştırmalıklar "le salé" diye anılır.',
    },
    {
      id: 'fr-yem-33', on: 'épicé', okunus: 'epise', tur: 'sıfat',
      arka: 'baharatlı, acı',
      ornek: 'Cette sauce est très épicée.',
      ornekTr: 'Bu sos çok acı.',
      not: '"les épices" baharat demektir.',
    },
    {
      id: 'fr-yem-34', on: 'amer', okunus: 'amer', tur: 'sıfat',
      arka: 'acı (kahve gibi)',
      ornek: 'Le café noir est amer.',
      ornekTr: 'Sade kahve acıdır.',
      not: 'Biberin acısı "épicé"dir; ikisi karıştırılır.',
    },
    {
      id: 'fr-yem-35', on: 'acide', okunus: 'asid', tur: 'sıfat',
      arka: 'ekşi',
      ornek: 'Le citron est très acide.',
      ornekTr: 'Limon çok ekşi.',
      not: 'Kimyadaki "asit" ile aynı kelimedir.',
    },
    {
      id: 'fr-yem-36', on: 'croustillant', okunus: 'krustiyan', tur: 'sıfat',
      arka: 'çıtır çıtır',
      ornek: 'La croûte est bien croustillante.',
      ornekTr: 'Kabuk güzelce çıtır çıtır.',
      not: '"la croûte" ekmek kabuğu demektir.',
    },
    {
      id: 'fr-yem-37', on: 'fondant', okunus: 'fondan', tur: 'sıfat',
      arka: 'ağızda dağılan',
      ornek: 'Ce gâteau est fondant.',
      ornekTr: 'Bu kek ağızda dağılıyor.',
      not: '"fondre" erimek demektir.',
    },
    {
      id: 'fr-yem-38', on: 'gras', okunus: 'gra', tur: 'sıfat',
      arka: 'yağlı',
      ornek: 'C\'était un peu trop gras.',
      ornekTr: 'Biraz fazla yağlıydı.',
      not: 'Dişil hâli "grasse"tır.',
    },
    {
      id: 'fr-yem-39', on: 'cru', okunus: 'krü', tur: 'sıfat',
      arka: 'çiğ',
      ornek: 'Il ne faut pas manger le poulet cru.',
      ornekTr: 'Çiğ tavuk yenmemeli.',
      not: '"il ne faut pas" = yapmamak gerekir.',
    },
    {
      id: 'fr-yem-40', on: 'avoir bon goût', okunus: 'avuar bon gu', tur: 'kalıp',
      arka: 'tadı güzel olmak',
      ornek: 'Ce plat a très bon goût.',
      ornekTr: 'Bu yemeğin tadı çok güzel.',
      not: '"le goût" tat demektir; "goûter" tatmak.',
    },
    /* --- Öğünler --- */
    {
      id: 'fr-yem-41', on: 'le déjeuner', okunus: 'lö dejöne', tur: 'isim',
      arka: 'öğle yemeği',
      ornek: 'Le déjeuner est à midi.',
      ornekTr: 'Öğle yemeği öğlen.',
      not: 'Fiil olarak "öğle yemeği yemek" anlamına da gelir.',
    },
    {
      id: 'fr-yem-42', on: 'le dîner', okunus: 'lö dine', tur: 'isim',
      arka: 'akşam yemeği',
      ornek: 'Le dîner est prêt !',
      ornekTr: 'Akşam yemeği hazır!',
      not: 'Fransa\'da akşam yemeği genellikle geç saatte yenir.',
    },
    {
      id: 'fr-yem-43', on: 'le goûter', okunus: 'lö gute', tur: 'isim',
      arka: 'ikindi atıştırması',
      ornek: 'Les enfants prennent le goûter à quatre heures.',
      ornekTr: 'Çocuklar saat dörtte ikindi atıştırması yapıyor.',
      not: 'Fransız çocukluk kültürünün klasik öğünüdür.',
    },
    {
      id: 'fr-yem-44', on: 'sauter un repas', okunus: 'sote ön röpa', tur: 'kalıp',
      arka: 'öğün atlamak',
      ornek: 'Ne saute jamais le petit-déjeuner.',
      ornekTr: 'Kahvaltıyı asla atlama.',
      not: '"sauter" zıplamak, atlamak demektir.',
    },
    {
      id: 'fr-yem-45', on: 'les restes', okunus: 'le rest', tur: 'isim (çoğul)',
      arka: 'artan yemek',
      ornek: 'On mange les restes demain.',
      ornekTr: 'Artanları yarın yeriz.',
      not: '"rester" kalmak fiilinden gelir.',
    },
    {
      id: 'fr-yem-46', on: 'fait maison', okunus: 'fe mezon', tur: 'kalıp',
      arka: 'ev yapımı',
      ornek: 'Cette confiture est faite maison.',
      ornekTr: 'Bu reçel ev yapımı.',
      not: 'Fransız restoranlarında bir kalite işaretidir.',
    },
    {
      id: 'fr-yem-47', on: 'être rassasié', okunus: 'etr rasazye', tur: 'kalıp',
      arka: 'doymuş olmak',
      ornek: 'Merci, je suis rassasié.',
      ornekTr: 'Teşekkürler, doydum.',
      not: 'Günlük dilde "je n\'ai plus faim" da denir.',
    },
    {
      id: 'fr-yem-48', on: 'grignoter', okunus: 'grinyote', tur: 'fiil',
      arka: 'atıştırmak',
      ornek: 'J\'ai envie de grignoter quelque chose.',
      ornekTr: 'Canım bir şeyler atıştırmak istiyor.',
      not: '"avoir envie de" = canı istemek.',
    },
    {
      id: 'fr-yem-49', on: 'être gourmand', okunus: 'etr gurman', tur: 'kalıp',
      arka: 'tatlı ve yemek düşkünü olmak',
      ornek: 'Ma sœur est très gourmande.',
      ornekTr: 'Kız kardeşim çok tatlı düşkünüdür.',
      not: 'Olumsuz değil, sevecen bir nitelemedir.',
    },
    {
      id: 'fr-yem-50', on: 'manger dehors', okunus: 'manje döor', tur: 'kalıp',
      arka: 'dışarıda yemek',
      ornek: 'On mange dehors une fois par semaine.',
      ornekTr: 'Haftada bir dışarıda yiyoruz.',
      not: '"au restaurant" da aynı anlamda kullanılır.',
    },
    /* --- Restoran --- */
    {
      id: 'fr-yem-51', on: 'réserver une table', okunus: 'rezerve ün tabl', tur: 'kalıp',
      arka: 'masa ayırtmak',
      ornek: 'J\'ai réservé une table pour quatre.',
      ornekTr: 'Dört kişilik masa ayırttım.',
      not: '"pour + sayı" kişi sayısını verir.',
    },
    {
      id: 'fr-yem-52', on: 'la carte', okunus: 'la kart', tur: 'isim',
      arka: 'menü',
      ornek: 'On peut voir la carte, s\'il vous plaît ?',
      ornekTr: 'Menüyü görebilir miyiz lütfen?',
      not: 'Sabit menü "le menu"dür; "la carte" seçmeli listedir.',
    },
    {
      id: 'fr-yem-53', on: 'l\'entrée', okunus: 'lantre', tur: 'isim',
      arka: 'başlangıç yemeği',
      ornek: 'Comme entrée, je prends une soupe.',
      ornekTr: 'Başlangıç olarak çorba alıyorum.',
      not: 'Aynı kelime "giriş" anlamına da gelir.',
    },
    {
      id: 'fr-yem-54', on: 'le plat principal', okunus: 'lö pla prensipal', tur: 'isim',
      arka: 'ana yemek',
      ornek: 'Le plat principal arrive tout de suite.',
      ornekTr: 'Ana yemek hemen geliyor.',
      not: '"tout de suite" = hemen.',
    },
    {
      id: 'fr-yem-55', on: 'le dessert', okunus: 'lö deser', tur: 'isim',
      arka: 'tatlı',
      ornek: 'Comme dessert, il y a de la tarte.',
      ornekTr: 'Tatlı olarak turta var.',
      not: 'Fransız menüsü: entrée, plat, dessert sırasını izler.',
    },
    {
      id: 'fr-yem-56', on: 'l\'addition', okunus: 'ladisyon', tur: 'isim',
      arka: 'hesap',
      ornek: 'L\'addition, s\'il vous plaît !',
      ornekTr: 'Hesap lütfen!',
      not: 'Matematikteki toplama işlemi de aynı kelimedir.',
    },
    {
      id: 'fr-yem-57', on: 'le pourboire', okunus: 'lö purbuar', tur: 'isim',
      arka: 'bahşiş',
      ornek: 'On a laissé un petit pourboire.',
      ornekTr: 'Küçük bir bahşiş bıraktık.',
      not: 'Kelimesi kelimesine "içmek için" demektir.',
    },
    {
      id: 'fr-yem-58', on: 'partager l\'addition', okunus: 'partaje ladisyon', tur: 'kalıp',
      arka: 'hesabı paylaşmak',
      ornek: 'On partage l\'addition ?',
      ornekTr: 'Hesabı paylaşalım mı?',
      not: 'Fransa\'da "chacun paie sa part" da denir.',
    },
    {
      id: 'fr-yem-59', on: 'le serveur', okunus: 'lö servör', tur: 'isim',
      arka: 'garson',
      ornek: 'Le serveur était très aimable.',
      ornekTr: 'Garson çok nazikti.',
      not: 'Kadın garson "la serveuse"dür.',
    },
    {
      id: 'fr-yem-60', on: 'végétarien', okunus: 'vejetaryen', tur: 'sıfat',
      arka: 'vejetaryen',
      ornek: 'Vous avez un plat végétarien ?',
      ornekTr: 'Vejetaryen yemeğiniz var mı?',
      not: 'Dişil hâli "végétarienne"dir.',
    },
    /* --- Alışveriş --- */
    {
      id: 'fr-yem-61', on: 'faire les courses', okunus: 'fer le kurs', tur: 'kalıp',
      arka: 'market alışverişi yapmak',
      ornek: 'Je fais les courses le samedi.',
      ornekTr: 'Market alışverişini cumartesi yapıyorum.',
      not: '"faire du shopping" giyim alışverişidir; ikisi farklıdır.',
    },
    {
      id: 'fr-yem-62', on: 'le supermarché', okunus: 'lö süpermarşe', tur: 'isim',
      arka: 'süpermarket',
      ornek: 'Le supermarché ferme à vingt heures.',
      ornekTr: 'Süpermarket saat yirmide kapanıyor.',
      not: '"le marché" pazar demektir.',
    },
    {
      id: 'fr-yem-63', on: 'la boucherie', okunus: 'la buşri', tur: 'isim',
      arka: 'kasap',
      ornek: 'On achète la viande à la boucherie.',
      ornekTr: 'Eti kasaptan alıyoruz.',
      not: '"-erie" eki dükkân bildirir: boulangerie, pâtisserie.',
    },
    {
      id: 'fr-yem-64', on: 'la pâtisserie', okunus: 'la patisri', tur: 'isim',
      arka: 'pastane',
      ornek: 'La pâtisserie du coin est excellente.',
      ornekTr: 'Köşedeki pastane mükemmel.',
      not: '"du coin" = mahalledeki, köşedeki.',
    },
    {
      id: 'fr-yem-65', on: 'la date de péremption', okunus: 'la dat dö perampsyon', tur: 'isim',
      arka: 'son kullanma tarihi',
      ornek: 'Regarde la date de péremption du yaourt.',
      ornekTr: 'Yoğurdun son kullanma tarihine bak.',
      not: 'Ambalajlarda "à consommer avant le ..." yazar.',
    },
    {
      id: 'fr-yem-66', on: 'la liste de courses', okunus: 'la list dö kurs', tur: 'isim',
      arka: 'alışveriş listesi',
      ornek: 'J\'écris une liste de courses.',
      ornekTr: 'Bir alışveriş listesi yazıyorum.',
      not: '"les courses" market alışverişi demektir.',
    },
    {
      id: 'fr-yem-67', on: 'en promotion', okunus: 'an promosyon', tur: 'kalıp',
      arka: 'indirimde',
      ornek: 'Le fromage est en promotion cette semaine.',
      ornekTr: 'Peynir bu hafta indirimde.',
      not: 'Kısaca "en promo" denir.',
    },
    {
      id: 'fr-yem-68', on: 'périmé', okunus: 'perime', tur: 'sıfat',
      arka: 'tarihi geçmiş',
      ornek: 'Le lait est périmé.',
      ornekTr: 'Sütün tarihi geçmiş.',
      not: 'Bozulmuş süt için "tourné" de denir.',
    },
    {
      id: 'fr-yem-69', on: 'il n\'y a plus de', okunus: 'il ni a plü dö', tur: 'kalıp',
      arka: '... kalmadı',
      ornek: 'Il n\'y a plus de lait.',
      ornekTr: 'Süt kalmadı.',
      not: 'Olumsuzda "du/de la" yerine sadece "de" gelir.',
    },
    {
      id: 'fr-yem-70', on: 'faire la vaisselle', okunus: 'fer la vesel', tur: 'kalıp',
      arka: 'bulaşık yıkamak',
      ornek: 'Je fais la vaisselle ce soir.',
      ornekTr: 'Bulaşığı bu akşam ben yıkıyorum.',
      not: '"la vaisselle" tabak çanak demektir.',
    },
    /* --- Sağlık ve beslenme --- */
    {
      id: 'fr-yem-71', on: 'équilibré', okunus: 'ekilibre', tur: 'sıfat',
      arka: 'dengeli',
      ornek: 'Une alimentation équilibrée est essentielle.',
      ornekTr: 'Dengeli beslenme çok önemlidir.',
      not: '"l\'alimentation" beslenme demektir.',
    },
    {
      id: 'fr-yem-72', on: 'le régime', okunus: 'lö rejim', tur: 'isim',
      arka: 'diyet',
      ornek: 'Elle est au régime depuis un mois.',
      ornekTr: 'Bir aydır diyette.',
      not: 'Kalıbı "être au régime"dir.',
    },
    {
      id: 'fr-yem-73', on: 'réduire', okunus: 'redüir', tur: 'fiil',
      arka: 'azaltmak',
      ornek: 'Tu devrais réduire le sucre.',
      ornekTr: 'Şekeri azaltmalısın.',
      not: '"devrais" = -meli, -malı (koşul kipi).',
    },
    {
      id: 'fr-yem-74', on: 'nourrissant', okunus: 'nurisan', tur: 'sıfat',
      arka: 'besleyici',
      ornek: 'Les lentilles sont nourrissantes et pas chères.',
      ornekTr: 'Mercimek besleyici ve ucuz.',
      not: '"nourrir" beslemek demektir.',
    },
    {
      id: 'fr-yem-75', on: 'être allergique à', okunus: 'etr alerjik a', tur: 'kalıp',
      arka: 'alerjisi olmak',
      ornek: 'Je suis allergique aux cacahuètes.',
      ornekTr: 'Fıstığa alerjim var.',
      not: 'Restoranda hayat kurtaran bir cümledir.',
    },
    {
      id: 'fr-yem-76', on: 'maigrir', okunus: 'megrir', tur: 'fiil',
      arka: 'kilo vermek',
      ornek: 'Il veut maigrir avant l\'été.',
      ornekTr: 'Yazdan önce kilo vermek istiyor.',
      not: 'Kilo almak "grossir"dir.',
    },
    {
      id: 'fr-yem-77', on: 'bio', okunus: 'biyo', tur: 'sıfat',
      arka: 'organik',
      ornek: 'Les légumes bio coûtent plus cher.',
      ornekTr: 'Organik sebzeler daha pahalı.',
      not: '"biologique" kelimesinin kısaltmasıdır ve değişmez.',
    },
    {
      id: 'fr-yem-78', on: 'la portion', okunus: 'la porsyon', tur: 'isim',
      arka: 'porsiyon',
      ornek: 'Les portions sont énormes ici.',
      ornekTr: 'Buradaki porsiyonlar kocaman.',
      not: '"énorme" devasa demektir.',
    },
    {
      id: 'fr-yem-79', on: 'boire de l\'eau', okunus: 'buar dö lo', tur: 'kalıp',
      arka: 'su içmek',
      ornek: 'Bois de l\'eau régulièrement pendant les examens.',
      ornekTr: 'Sınav döneminde düzenli su iç.',
      not: '"régulièrement" düzenli olarak demektir. Emir kipi: bois.',
      kok: 'bois',
    },
    {
      id: 'fr-yem-80', on: 'les produits transformés', okunus: 'le prodüi transforme', tur: 'isim (çoğul)',
      arka: 'işlenmiş gıdalar',
      ornek: 'Évite les produits transformés.',
      ornekTr: 'İşlenmiş gıdalardan kaçın.',
      not: '"éviter" kaçınmak demektir.',
    },
    /* --- Mutfak kültürü --- */
    {
      id: 'fr-yem-81', on: 'la spécialité', okunus: 'la spesyalite', tur: 'isim',
      arka: 'yöresel lezzet',
      ornek: 'Le baklava est une spécialité turque.',
      ornekTr: 'Baklava bir Türk lezzetidir.',
      not: 'Fransızlar yöresel mutfağa büyük değer verir.',
    },
    {
      id: 'fr-yem-82', on: 'farci', okunus: 'farsi', tur: 'sıfat',
      arka: 'doldurulmuş, dolma',
      ornek: 'Les poivrons farcis sont un classique turc.',
      ornekTr: 'Biber dolması bir Türk klasiğidir.',
      not: '"la farce" iç harç demektir.',
    },
    {
      id: 'fr-yem-83', on: 'la viande hachée', okunus: 'la viyand aşe', tur: 'isim',
      arka: 'kıyma',
      ornek: 'La farce est faite avec de la viande hachée.',
      ornekTr: 'İç harcı kıymayla yapılıyor.',
      not: '"hacher" kıymak demektir.',
    },
    {
      id: 'fr-yem-84', on: 'la pâte feuilletée', okunus: 'la pat föyte', tur: 'isim',
      arka: 'yufka, milföy hamuru',
      ornek: 'Le börek se fait avec de la pâte feuilletée.',
      ornekTr: 'Börek yufkayla yapılır.',
      not: '"la feuille" yaprak demektir; kat kat hamurdur.',
    },
    {
      id: 'fr-yem-85', on: 'être connu pour', okunus: 'etr konü pur', tur: 'kalıp',
      arka: 'bir şeyle ünlü olmak',
      ornek: 'Gaziantep est connue pour son baklava.',
      ornekTr: 'Gaziantep baklavasıyla ünlüdür.',
      not: 'Edatı "pour"dur.',
    },
    {
      id: 'fr-yem-86', on: 'servi avec', okunus: 'servi avek', tur: 'kalıp',
      arka: 'yanında ... ile servis edilen',
      ornek: 'Ce plat est servi avec du riz.',
      ornekTr: 'Bu yemek pilavla servis edilir.',
      not: 'Yemek tarif ederken en kullanışlı kalıptır.',
    },
    {
      id: 'fr-yem-87', on: 'ça a le goût de', okunus: 'sa a lö gu dö', tur: 'kalıp',
      arka: 'tadı ... gibi',
      ornek: 'Ça a le goût d\'une pizza fine.',
      ornekTr: 'Tadı ince bir pizza gibi.',
      not: 'Bilinmeyen bir yemeği anlatmanın en pratik yoludur.',
    },
    {
      id: 'fr-yem-88', on: 'à ne pas manquer', okunus: 'a nö pa manke', tur: 'kalıp',
      arka: 'mutlaka denenmeli',
      ornek: 'Le menemen est à ne pas manquer au petit-déjeuner.',
      ornekTr: 'Kahvaltıda menemen mutlaka denenmeli.',
      not: '"manquer" kaçırmak demektir.',
    },
    {
      id: 'fr-yem-89', on: 'Sers-toi !', okunus: 'ser tua', tur: 'kalıp',
      arka: 'Buyur, kendin al!',
      ornek: 'Sers-toi, il y en a assez pour tout le monde.',
      ornekTr: 'Buyur al, herkese yetecek kadar var.',
      not: '"se servir" kendine almak demektir.',
    },
    {
      id: 'fr-yem-90', on: 'Bon appétit !', okunus: 'bon apeti', tur: 'kalıp',
      arka: 'Afiyet olsun!',
      ornek: 'C\'est prêt. Bon appétit !',
      ornekTr: 'Hazır. Afiyet olsun!',
      not: 'Fransa\'da yemeğe başlamadan mutlaka söylenir.',
    },
    /* --- Yemek deyimleri --- */
    {
      id: 'fr-yem-91', on: 'ce n\'est pas de la tarte', okunus: 'sö ne pa dö la tart', tur: 'deyim',
      arka: 'kolay iş değil',
      ornek: 'Apprendre le français, ce n\'est pas de la tarte.',
      ornekTr: 'Fransızca öğrenmek kolay iş değil.',
      not: '"la tarte" turta demektir; kolaylık imgesidir.',
    },
    {
      id: 'fr-yem-92', on: 'la cerise sur le gâteau', okunus: 'la söriz sür lö gato', tur: 'deyim',
      arka: 'işin en güzel yanı',
      ornek: 'Et la cerise sur le gâteau : on a gagné !',
      ornekTr: 'Ve işin en güzel yanı: kazandık!',
      not: 'İngilizcedeki "the icing on the cake" ile aynıdır.',
    },
    {
      id: 'fr-yem-93', on: 'raconter des salades', okunus: 'rakonte de salad', tur: 'deyim',
      arka: 'palavra atmak',
      ornek: 'Arrête de raconter des salades !',
      ornekTr: 'Palavra atmayı bırak!',
      not: 'Kelimesi kelimesine "salatalar anlatmak"tır.',
    },
    {
      id: 'fr-yem-94', on: 'mettre son grain de sel', okunus: 'metr son gren dö sel', tur: 'deyim',
      arka: 'söze karışmak',
      ornek: 'Il met toujours son grain de sel.',
      ornekTr: 'Her zaman söze karışıyor.',
      not: 'Hafif sitem içeren bir ifadedir.',
    },
    {
      id: 'fr-yem-95', on: 'avoir un appétit d\'oiseau', okunus: 'avuar ön apeti duazo', tur: 'deyim',
      arka: 'kuş kadar yemek',
      ornek: 'Elle a un appétit d\'oiseau.',
      ornekTr: 'Kuş kadar yiyor.',
      not: 'Türkçedeki "kuş kadar yemek" ile aynıdır.',
    },
    {
      id: 'fr-yem-96', on: 'être dans le pétrin', okunus: 'etr dan lö petren', tur: 'deyim',
      arka: 'başı dertte olmak',
      ornek: 'Sans mes notes, je suis dans le pétrin.',
      ornekTr: 'Notlarım olmadan başım dertte.',
      not: '"le pétrin" hamur teknesi demektir.',
    },
    {
      id: 'fr-yem-97', on: 'tomber dans les pommes', okunus: 'tonbe dan le pom', tur: 'deyim',
      arka: 'bayılmak',
      ornek: 'Il est tombé dans les pommes de fatigue.',
      ornekTr: 'Yorgunluktan bayıldı.',
      not: 'Kelimesi kelimesine "elmaların içine düşmek"tir.',
    },
    {
      id: 'fr-yem-98', on: 'avoir la frite', okunus: 'avuar la frit', tur: 'deyim',
      arka: 'enerjik olmak',
      ornek: 'Ce matin, j\'ai la frite !',
      ornekTr: 'Bu sabah enerji doluyum!',
      not: '"la frite" patates kızartması demektir.',
    },
    {
      id: 'fr-yem-99', on: 'l\'appétit vient en mangeant', okunus: 'lapeti viyen an manjan', tur: 'atasözü',
      arka: 'İştah yemekle açılır',
      ornek: 'Commence : l\'appétit vient en mangeant.',
      ornekTr: 'Sadece başla: iştah yemekle açılır.',
      not: 'Ders çalışmaya başlamak için de kullanılır.',
    },
    {
      id: 'fr-yem-100', on: 'à chacun son goût', okunus: 'a şaken son gu', tur: 'atasözü',
      arka: 'Herkesin zevki kendine',
      ornek: 'Tu n\'aimes pas ? À chacun son goût.',
      ornekTr: 'Sevmedin mi? Herkesin zevki kendine.',
      not: 'Tartışmayı kibarca bitiren bir kapanış cümlesidir.',
    },
  ],
}

export default DESTE
