/**
 * A1 — AİLE VE EŞYALAR KELİMELERİ
 * ==================================================================
 *
 * Bu setin özel bir yükü var: Almancada cinsiyetin (der/die/das) ilk
 * ciddi sınavı aile kelimeleridir. Öğrenci burada "das Mädchen" gibi
 * mantığa aykırı görünen bir kaydı da öğrenmek zorunda kalır ve
 * artikelin anlamla değil, KELİMEYLE geldiğini kavrar.
 *
 * Bu yüzden her kayıtta artikel, çoğul ve mümkün olduğunda cinsiyeti
 * tahmin ettiren kural (`hatirlatma`) verilir.
 */

export const KELIMELER = [
  {
    id: 'de-familie',
    dil: 'de',
    kelime: 'Familie',
    artikel: 'die',
    cogul: 'die Familien',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Eltern, Kinder und Verwandte zusammen.',
    turkceDestek: 'aile',
    ipa: '/faˈmiːli̯ə/',
    heceler: 'Fa-mi-li-e (dört hece, sondaki -ie ayrı okunur)',
    ornekler: [
      { de: 'Meine Familie ist nicht sehr groß.', tr: 'Ailem çok büyük değil.' },
      { de: 'Wir sind eine Familie mit fünf Personen.', tr: 'Beş kişilik bir aileyiz.' },
    ],
    esdizim: ['die ganze Familie', 'eine große Familie', 'der Familienname'],
    aile: ['die Familienfeier', 'familiär'],
    hata: 'Son hece "-lie" tek hece gibi okunmaz: Fa-mi-li-e (dört hece).',
    hatirlatma: '-ie ile biten kelimeler neredeyse her zaman "die" alır.',
    uretim: {
      yonerge: 'Ailenin kaç kişi olduğunu yaz.',
      kabul: ['Meine Familie hat', 'Wir sind', 'Meine Familie ist'],
    },
  },
  {
    id: 'de-mutter',
    dil: 'de',
    kelime: 'Mutter',
    artikel: 'die',
    cogul: 'die Mütter',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Die weibliche Person, die ein Kind bekommen hat.',
    turkceDestek: 'anne',
    ipa: '/ˈmʊtɐ/',
    heceler: 'Mut-ter (kısa u, sonda "a" gibi biten -er)',
    ornekler: [
      { de: 'Meine Mutter arbeitet als Ärztin.', tr: 'Annem doktor olarak çalışıyor.' },
      { de: 'Das ist ein Geschenk für meine Mutter.', tr: 'Bu, annem için bir hediye.' },
    ],
    esdizim: ['die Muttersprache', 'der Muttertag'],
    zitAnlam: ['der Vater'],
    aile: ['die Mama', 'mütterlich', 'die Muttersprache'],
    hata: 'Çoğulu "Mutters" değil "Mütter"dir — umlaut eklenir, ek gelmez.',
    hatirlatma: 'Sondaki "-er" Almancada "a" gibi okunur: Mutter → "muta".',
    uretim: {
      yonerge: 'Annenin ne iş yaptığını ya da neyi sevdiğini yaz.',
      kabul: ['Meine Mutter'],
    },
  },
  {
    id: 'de-vater',
    dil: 'de',
    kelime: 'Vater',
    artikel: 'der',
    cogul: 'die Väter',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Die männliche Person, die ein Kind hat.',
    turkceDestek: 'baba',
    ipa: '/ˈfaːtɐ/',
    heceler: 'Va-ter (V → "f" okunur)',
    ornekler: [
      { de: 'Mein Vater kommt aus Izmir.', tr: 'Babam İzmirli.' },
      { de: 'Ich helfe meinem Vater im Garten.', tr: 'Bahçede babama yardım ediyorum.' },
    ],
    esdizim: ['der Vatertag', 'die Väter und Mütter'],
    zitAnlam: ['die Mutter'],
    aile: ['der Papa', 'väterlich'],
    hata: '"V" harfi Almanca kelimelerde "f" okunur: Vater → "faata". Yabancı kökenli kelimelerde (Vase, Video) "v" okunur.',
    hatirlatma: 'Dativ\'de "meinem Vater" olur — helfen fiili Dativ ister.',
    uretim: {
      yonerge: 'Babanın nereli olduğunu yaz.',
      kabul: ['Mein Vater kommt aus', 'Mein Vater ist'],
    },
  },
  {
    id: 'de-eltern',
    dil: 'de',
    kelime: 'Eltern',
    artikel: 'die',
    cogul: 'çoğulu yok — kelime zaten çoğuldur',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Mutter und Vater zusammen.',
    turkceDestek: 'anne baba, ebeveyn',
    ipa: '/ˈɛltɐn/',
    heceler: 'El-tern',
    ornekler: [
      { de: 'Meine Eltern sind sehr nett.', tr: 'Annem babam çok kibar.' },
      { de: 'Ich wohne noch bei meinen Eltern.', tr: 'Hâlâ ailemle birlikte oturuyorum.' },
    ],
    esdizim: ['bei den Eltern wohnen', 'der Elternabend'],
    aile: ['elterlich', 'der Elternabend'],
    hata: 'Bu kelimenin TEKİLİ YOKTUR. "ein Eltern" diye bir şey olmaz; tek kişi için Mutter ya da Vater denir.',
    hatirlatma: 'Hep çoğul olduğu için fiil de çoğul çekilir: Meine Eltern SIND (ist değil).',
    uretim: {
      yonerge: 'Anne babanı bir sıfatla anlat.',
      kabul: ['Meine Eltern sind'],
    },
  },
  {
    id: 'de-bruder',
    dil: 'de',
    kelime: 'Bruder',
    artikel: 'der',
    cogul: 'die Brüder',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Der Sohn derselben Eltern.',
    turkceDestek: 'erkek kardeş, abi',
    ipa: '/ˈbʁuːdɐ/',
    heceler: 'Bru-der (uzun u)',
    ornekler: [
      { de: 'Ich habe einen Bruder und zwei Schwestern.', tr: 'Bir erkek kardeşim, iki kız kardeşim var.' },
      { de: 'Mein großer Bruder studiert in Berlin.', tr: 'Ağabeyim Berlin’de üniversite okuyor.' },
    ],
    esdizim: ['der große Bruder', 'der kleine Bruder', 'einen Bruder haben'],
    aile: ['die Geschwister', 'brüderlich'],
    hata: 'Eril isim olduğu için "haben" ile Akkusativ\'e girer: "Ich habe EINEN Bruder" (ein Bruder değil).',
    hatirlatma: 'Almancada "abi / kardeş" ayrımı tek kelimede yoktur; yaş farkı "groß/klein" ile söylenir.',
    uretim: {
      yonerge: 'Kaç kardeşin olduğunu yaz (yoksa onu yaz).',
      kabul: ['Ich habe einen Bruder', 'Ich habe zwei Brüder', 'Ich habe keinen Bruder', 'Ich habe keine Geschwister'],
    },
  },
  {
    id: 'de-schwester',
    dil: 'de',
    kelime: 'Schwester',
    artikel: 'die',
    cogul: 'die Schwestern',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Die Tochter derselben Eltern.',
    turkceDestek: 'kız kardeş, abla',
    ipa: '/ˈʃvɛstɐ/',
    heceler: 'Schwes-ter (schw → "şv")',
    ornekler: [
      { de: 'Meine Schwester ist zehn Jahre alt.', tr: 'Kız kardeşim on yaşında.' },
      { de: 'Ich gehe mit meiner Schwester ins Kino.', tr: 'Kız kardeşimle sinemaya gidiyorum.' },
    ],
    esdizim: ['die große Schwester', 'die kleine Schwester'],
    aile: ['die Geschwister', 'der Bruder'],
    hata: '"sch" üç harf ama TEK sestir: "ş". Öğrenci "s-ch" diye ayırıp okuyor.',
    hatirlatma: 'Çoğulu -n ekiyle: Schwester → Schwestern.',
    uretim: {
      yonerge: 'Kız kardeşin varsa yaşını yaz; yoksa olmadığını yaz.',
      kabul: ['Meine Schwester ist', 'Ich habe keine Schwester'],
    },
  },
  {
    id: 'de-geschwister',
    dil: 'de',
    kelime: 'Geschwister',
    artikel: 'die',
    cogul: 'çoğulu yok — kelime zaten çoğuldur',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Brüder und Schwestern zusammen.',
    turkceDestek: 'kardeşler',
    ipa: '/ɡəˈʃvɪstɐ/',
    heceler: 'Ge-schwis-ter (vurgu: SCHWIS)',
    ornekler: [
      { de: 'Hast du Geschwister?', tr: 'Kardeşin var mı?' },
      { de: 'Ich habe drei Geschwister.', tr: 'Üç kardeşim var.' },
    ],
    esdizim: ['Geschwister haben', 'keine Geschwister'],
    aile: ['der Bruder', 'die Schwester'],
    hata: 'Türkçedeki "kardeşim var mı" sorusunun karşılığı budur; öğrenci "Hast du Bruder oder Schwester?" diye uzun yoldan sorar.',
    hatirlatma: 'Ge- ön eki toplayıcıdır: Geschwister = kardeşlerin tamamı, Gebäude = binalar bütünü.',
    uretim: {
      yonerge: 'Bir arkadaşına kardeşi olup olmadığını sor.',
      kabul: ['Hast du Geschwister'],
    },
  },
  {
    id: 'de-kind',
    dil: 'de',
    kelime: 'Kind',
    artikel: 'das',
    cogul: 'die Kinder',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Ein junger Mensch, noch nicht erwachsen.',
    turkceDestek: 'çocuk',
    ipa: '/kɪnt/',
    heceler: 'Kind (sondaki d → "t")',
    ornekler: [
      { de: 'Das Kind spielt im Garten.', tr: 'Çocuk bahçede oynuyor.' },
      { de: 'Sie haben zwei Kinder.', tr: 'İki çocukları var.' },
    ],
    esdizim: ['ein kleines Kind', 'Kinder haben', 'der Kindergarten'],
    aile: ['der Kindergarten', 'kindlich', 'das Enkelkind'],
    hata: 'Çoğulu "Kinds" değil "Kinder"dir. -er çoğulu Almancada sık görülür ve genelde "das" artikelli kelimelerde çıkar.',
    hatirlatma: 'Türkçeye geçmiş "kindergarten" kelimesi buradan gelir: Kinder + Garten = çocuk bahçesi.',
    uretim: {
      yonerge: 'Bir ailede kaç çocuk olduğunu anlatan cümle yaz.',
      kabul: ['Sie haben', 'Wir sind', 'Meine Eltern haben'],
    },
  },
  {
    id: 'de-maedchen',
    dil: 'de',
    kelime: 'Mädchen',
    artikel: 'das',
    cogul: 'die Mädchen',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Ein weibliches Kind.',
    turkceDestek: 'kız çocuk',
    ipa: '/ˈmɛːtçən/',
    heceler: 'Mäd-chen (ä → geniş "e", -chen yumuşak "hyen")',
    ornekler: [
      { de: 'Das Mädchen heißt Zeynep.', tr: 'Kızın adı Zeynep.' },
      { de: 'Zwei Mädchen warten vor der Schule.', tr: 'İki kız okulun önünde bekliyor.' },
    ],
    esdizim: ['ein kleines Mädchen', 'das Mädchen von nebenan'],
    aile: ['der Junge', 'das Kind'],
    hata: 'Kız çocuğu olmasına rağmen artikeli "das"tır. Bu, Almancada cinsiyetin ANLAMLA değil KELİMEYLE geldiğinin en ünlü örneğidir.',
    hatirlatma: '-chen ile biten her kelime "das" alır ve küçültme bildirir: das Mädchen, das Brötchen, das Häuschen.',
    uretim: {
      yonerge: '"-chen" kuralını gösteren kendi cümleni yaz.',
      kabul: ['Das Mädchen', 'Das Mädchen ist', 'Das Maedchen'],
    },
  },
  {
    id: 'de-junge',
    dil: 'de',
    kelime: 'Junge',
    artikel: 'der',
    cogul: 'die Jungen',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Ein männliches Kind.',
    turkceDestek: 'erkek çocuk, oğlan',
    ipa: '/ˈjʊŋə/',
    heceler: 'Jun-ge (J → "y", ng → genizden tek ses)',
    ornekler: [
      { de: 'Der Junge spielt Fußball.', tr: 'Çocuk futbol oynuyor.' },
      { de: 'Die Jungen sind in der Klasse.', tr: 'Erkek çocuklar sınıfta.' },
    ],
    esdizim: ['ein kleiner Junge', 'die Jungen und die Mädchen'],
    zitAnlam: ['das Mädchen'],
    aile: ['jung', 'die Jugend'],
    hata: '"ng" burada iki ayrı ses değildir; genizden gelen tek bir sestir: "yunge" değil "yuŋe".',
    hatirlatma: 'Mädchen "das" iken Junge "der"dir — bu çift, artikelin ezberlenmesi gerektiğini gösterir.',
    uretim: {
      yonerge: 'Bir erkek çocuğun ne yaptığını anlatan cümle yaz.',
      kabul: ['Der Junge'],
    },
  },
  {
    id: 'de-grossmutter',
    dil: 'de',
    kelime: 'Großmutter',
    artikel: 'die',
    cogul: 'die Großmütter',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Die Mutter der Mutter oder des Vaters.',
    turkceDestek: 'büyükanne, babaanne/anneanne',
    ipa: '/ˈɡʁoːsˌmʊtɐ/',
    heceler: 'Groß-mut-ter (ß → "ss")',
    ornekler: [
      { de: 'Meine Großmutter kocht sehr gut.', tr: 'Büyükannem çok iyi yemek yapar.' },
      { de: 'Am Wochenende besuchen wir die Großeltern.', tr: 'Hafta sonu büyüklerimizi ziyaret ediyoruz.' },
    ],
    esdizim: ['die Großeltern', 'die Oma (gündelik)'],
    aile: ['der Großvater', 'die Großeltern', 'die Oma'],
    hata: 'Almancada "babaanne / anneanne" ayrımı yoktur; ikisi de Großmutter\'dır. Gerekirse "die Mutter meines Vaters" denir.',
    kayit: 'resmi',
    hatirlatma: 'Günlük konuşmada neredeyse herkes "Oma" der; Großmutter yazı dilidir.',
    uretim: {
      yonerge: 'Büyükannen hakkında bir cümle yaz.',
      kabul: ['Meine Großmutter', 'Meine Oma', 'Meine Grossmutter'],
    },
  },
  {
    id: 'de-grossvater',
    dil: 'de',
    kelime: 'Großvater',
    artikel: 'der',
    cogul: 'die Großväter',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Der Vater der Mutter oder des Vaters.',
    turkceDestek: 'büyükbaba, dede',
    ipa: '/ˈɡʁoːsˌfaːtɐ/',
    heceler: 'Groß-va-ter',
    ornekler: [
      { de: 'Mein Großvater ist achtzig Jahre alt.', tr: 'Dedem seksen yaşında.' },
      { de: 'Mein Opa erzählt gern alte Geschichten.', tr: 'Dedem eski hikâyeler anlatmayı sever.' },
    ],
    esdizim: ['die Großeltern', 'der Opa (gündelik)'],
    aile: ['die Großmutter', 'der Opa'],
    hata: 'Birleşik kelimenin artikeli SON parçadan gelir: Groß + Vater → der Großvater.',
    kayit: 'resmi',
    hatirlatma: 'Bu kural bütün birleşik kelimeler için geçerlidir; Almancanın en işine yarayan kuralıdır.',
    uretim: {
      yonerge: 'Dedenin yaşını ya da bir özelliğini yaz.',
      kabul: ['Mein Großvater ist', 'Mein Opa ist', 'Mein Grossvater ist'],
    },
  },
  {
    id: 'de-onkel',
    dil: 'de',
    kelime: 'Onkel',
    artikel: 'der',
    cogul: 'die Onkel',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Der Bruder der Mutter oder des Vaters.',
    turkceDestek: 'amca, dayı, enişte',
    ipa: '/ˈɔŋkl̩/',
    heceler: 'On-kel',
    ornekler: [
      { de: 'Mein Onkel wohnt in Hamburg.', tr: 'Amcam Hamburg’da oturuyor.' },
      { de: 'Ich besuche meinen Onkel im Sommer.', tr: 'Yazın amcamı ziyaret ediyorum.' },
    ],
    esdizim: ['der Onkel und die Tante'],
    aile: ['die Tante', 'der Cousin'],
    hata: 'Türkçedeki amca/dayı/enişte ayrımı Almancada YOKTUR; hepsi Onkel\'dir. Bu, kelime kelime çeviri yapan öğrenciyi zorlar.',
    hatirlatma: 'Çoğulu tekiliyle aynıdır: der Onkel → die Onkel.',
    uretim: {
      yonerge: 'Amcan/dayın hakkında bir cümle yaz.',
      kabul: ['Mein Onkel'],
    },
  },
  {
    id: 'de-tante',
    dil: 'de',
    kelime: 'Tante',
    artikel: 'die',
    cogul: 'die Tanten',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Die Schwester der Mutter oder des Vaters.',
    turkceDestek: 'teyze, hala, yenge',
    ipa: '/ˈtantə/',
    heceler: 'Tan-te',
    ornekler: [
      { de: 'Meine Tante hat drei Kinder.', tr: 'Teyzemin üç çocuğu var.' },
      { de: 'Wir fahren zu meiner Tante.', tr: 'Teyzemlere gidiyoruz.' },
    ],
    esdizim: ['zu meiner Tante fahren'],
    aile: ['der Onkel', 'die Cousine'],
    hata: 'Teyze/hala/yenge ayrımı yoktur. Ayrıca "zu" edatı Dativ ister: zu meiner Tante.',
    hatirlatma: '-e ile biten kelimelerin çoğu "die" alır: die Tante, die Schule, die Lampe.',
    uretim: {
      yonerge: 'Teyzen/halan hakkında bir cümle yaz.',
      kabul: ['Meine Tante'],
    },
  },
  {
    id: 'de-hund',
    dil: 'de',
    kelime: 'Hund',
    artikel: 'der',
    cogul: 'die Hunde',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Ein Haustier, das bellt.',
    turkceDestek: 'köpek',
    ipa: '/hʊnt/',
    heceler: 'Hund (sondaki d → "t")',
    ornekler: [
      { de: 'Wir haben einen Hund.', tr: 'Bir köpeğimiz var.' },
      { de: 'Der Hund heißt Karabaş.', tr: 'Köpeğin adı Karabaş.' },
    ],
    esdizim: ['einen Hund haben', 'mit dem Hund spazieren gehen'],
    aile: ['das Haustier', 'die Katze'],
    hata: 'Eril olduğu için Akkusativ\'de "einen Hund" olur. Öğrenci "ein Hund" yazıp nesne işaretini atlıyor.',
    hatirlatma: 'Sözcük sonundaki b, d, g Almancada hep sert okunur: Hund → "hunt".',
    uretim: {
      yonerge: 'Evcil hayvanın var mı, yaz.',
      kabul: ['Ich habe einen Hund', 'Wir haben einen Hund', 'Ich habe keinen Hund', 'Ich habe kein Haustier'],
    },
  },
  {
    id: 'de-katze',
    dil: 'de',
    kelime: 'Katze',
    artikel: 'die',
    cogul: 'die Katzen',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Ein kleines Haustier, das miaut.',
    turkceDestek: 'kedi',
    ipa: '/ˈkatsə/',
    heceler: 'Kat-ze (z → "ts")',
    ornekler: [
      { de: 'Meine Katze schläft den ganzen Tag.', tr: 'Kedim bütün gün uyuyor.' },
      { de: 'Hast du eine Katze?', tr: 'Kedin var mı?' },
    ],
    esdizim: ['eine Katze haben', 'die Katze füttern'],
    aile: ['das Kätzchen', 'das Haustier'],
    hata: 'Almancada "z" harfi her zaman "ts" okunur: Katze → "katsı", Zeit → "tsayt".',
    hatirlatma: 'Bu ses Türkçede yok; alışması zaman alır ama kuralı istisnasızdır.',
    uretim: {
      yonerge: 'Kedin olup olmadığını yaz.',
      kabul: ['Ich habe eine Katze', 'Ich habe keine Katze'],
    },
  },
  {
    id: 'de-haus',
    dil: 'de',
    kelime: 'Haus',
    artikel: 'das',
    cogul: 'die Häuser',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Ein Gebäude, in dem Menschen wohnen.',
    turkceDestek: 'ev, bina',
    ipa: '/haʊ̯s/',
    heceler: 'Haus (au → "au")',
    ornekler: [
      { de: 'Unser Haus ist nicht groß.', tr: 'Evimiz büyük değil.' },
      { de: 'Ich gehe nach Hause.', tr: 'Eve gidiyorum.' },
    ],
    esdizim: ['nach Hause gehen', 'zu Hause sein', 'die Hausaufgabe'],
    aile: ['die Hausaufgabe', 'zu Hause', 'das Häuschen'],
    hata: '"nach Hause" (eve doğru) ile "zu Hause" (evde) karıştırılır. Türkçede tek ekle ayrılan bu fark Almancada iki ayrı kalıptır.',
    hatirlatma: 'Çoğulunda hem umlaut hem -er eki var: Haus → Häuser.',
    uretim: {
      yonerge: '"Eve gidiyorum." cümlesini yaz.',
      kabul: ['Ich gehe nach Hause'],
    },
  },
  {
    id: 'de-zimmer',
    dil: 'de',
    kelime: 'Zimmer',
    artikel: 'das',
    cogul: 'die Zimmer',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Ein Raum in einer Wohnung oder in einem Haus.',
    turkceDestek: 'oda',
    ipa: '/ˈtsɪmɐ/',
    heceler: 'Zim-mer (Z → "ts")',
    ornekler: [
      { de: 'Mein Zimmer ist klein, aber gemütlich.', tr: 'Odam küçük ama rahat.' },
      { de: 'Die Wohnung hat drei Zimmer.', tr: 'Dairenin üç odası var.' },
    ],
    esdizim: ['das Kinderzimmer', 'das Wohnzimmer', 'das Zimmer aufräumen'],
    aile: ['das Wohnzimmer', 'das Schlafzimmer', 'das Badezimmer'],
    hata: 'Çoğulu tekiliyle aynıdır: das Zimmer → die Zimmer. Öğrenci "Zimmers" yazıyor.',
    hatirlatma: 'Sonu -er olan "das" kelimelerinin çoğu çoğulda değişmez.',
    uretim: {
      yonerge: 'Odanı iki sıfatla anlat.',
      kabul: ['Mein Zimmer ist'],
    },
  },
  {
    id: 'de-handy',
    dil: 'de',
    kelime: 'Handy',
    artikel: 'das',
    cogul: 'die Handys',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Ein Telefon, das man mitnehmen kann.',
    turkceDestek: 'cep telefonu',
    ipa: '/ˈhɛndi/',
    heceler: 'Han-dy (İngilizce gibi "hendi")',
    ornekler: [
      { de: 'Mein Handy ist kaputt.', tr: 'Telefonum bozuk.' },
      { de: 'Ich habe kein Handy dabei.', tr: 'Yanımda telefon yok.' },
    ],
    esdizim: ['die Handynummer', 'das Handy aufladen'],
    aile: ['das Telefon', 'die Handynummer'],
    hata: 'İngilizce gibi görünür ama İngilizcede "handy" cep telefonu demek DEĞİLDİR (mobile phone denir). Bu, Almancanın kendi ürettiği bir kelimedir.',
    hatirlatma: 'Yabancı kökenli kelimeler çoğulu -s ile yapar: Handys, Autos, Kinos.',
    uretim: {
      yonerge: 'Telefonun hakkında bir cümle yaz.',
      kabul: ['Mein Handy ist', 'Ich habe ein Handy'],
    },
  },
  {
    id: 'de-buch',
    dil: 'de',
    kelime: 'Buch',
    artikel: 'das',
    cogul: 'die Bücher',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Viele Seiten mit Text, zusammen gebunden.',
    turkceDestek: 'kitap',
    ipa: '/buːx/',
    heceler: 'Buch (ch → gırtlaktan sert "h")',
    ornekler: [
      { de: 'Ich lese gern Bücher.', tr: 'Kitap okumayı severim.' },
      { de: 'Das Buch liegt auf dem Tisch.', tr: 'Kitap masanın üstünde.' },
    ],
    esdizim: ['ein Buch lesen', 'das Wörterbuch', 'das Schulbuch'],
    aile: ['die Buchhandlung', 'das Wörterbuch', 'buchstabieren'],
    hata: 'Çoğulunda hem umlaut hem -er var: Buch → Bücher. "Buchs" diye bir biçim yoktur.',
    hatirlatma: 'a, o, u\'dan sonra gelen "ch" gırtlaktan sert okunur (Buch, doch, auch); e, i\'den sonra yumuşak (ich, nicht).',
    uretim: {
      yonerge: 'Kitap okumayı sevip sevmediğini "gern" ile yaz.',
      kabul: ['Ich lese gern Bücher', 'Ich lese gern', 'Ich lese nicht gern'],
    },
  },
  {
    id: 'de-tisch',
    dil: 'de',
    kelime: 'Tisch',
    artikel: 'der',
    cogul: 'die Tische',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Ein Möbel mit einer Platte und Beinen.',
    turkceDestek: 'masa',
    ipa: '/tɪʃ/',
    heceler: 'Tisch (sch → "ş")',
    ornekler: [
      { de: 'Das Heft ist auf dem Tisch.', tr: 'Defter masanın üstünde.' },
      { de: 'Wir kaufen einen neuen Tisch.', tr: 'Yeni bir masa alıyoruz.' },
    ],
    esdizim: ['auf dem Tisch', 'der Schreibtisch', 'den Tisch decken'],
    aile: ['der Schreibtisch', 'das Tischtuch'],
    hata: 'Eril olduğu için "auf dem Tisch" (Dativ, yer) ama "auf den Tisch" (Akkusativ, hareket) olur.',
    hatirlatma: '"Tisch" ile İngilizce "dish" benzer görünür ama akraba değildir; anlamları da farklıdır.',
    uretim: {
      yonerge: 'Masanın üstünde ne olduğunu yaz.',
      kabul: ['Auf dem Tisch ist', 'Auf dem Tisch sind', 'Das Buch ist auf dem Tisch'],
    },
  },
  {
    id: 'de-nett',
    dil: 'de',
    kelime: 'nett',
    tur: 'sıfat',
    seviye: 'A1',
    almancaTanim: 'Freundlich und angenehm zu anderen Menschen.',
    turkceDestek: 'kibar, cana yakın, hoş',
    ipa: '/nɛt/',
    heceler: 'nett (kısa e, çift t)',
    ornekler: [
      { de: 'Meine Lehrerin ist sehr nett.', tr: 'Öğretmenim çok kibar.' },
      { de: 'Das war ein netter Abend.', tr: 'Hoş bir akşamdı.' },
    ],
    esdizim: ['sehr nett', 'ein netter Mensch', 'nett sein zu'],
    esAnlam: ['freundlich', 'sympathisch'],
    zitAnlam: ['unfreundlich'],
    aile: ['die Nettigkeit'],
    hata: 'İsimden önce geldiğinde EK ALIR: "ein netter Mensch". Yüklem olduğunda ek almaz: "Er ist nett".',
    hatirlatma: 'Almancanın en çok kullanılan iltifat sıfatıdır; insanlar için "schön" değil "nett" denir.',
    uretim: {
      yonerge: 'Sevdiğin birini "nett" ile anlat.',
      kabul: ['ist sehr nett', 'ist nett'],
    },
  },
]
