/**
 * A1 — OKUL VE DERS KELİMELERİ
 * ==================================================================
 *
 * Okul kelimeleri Almancanın iki ayrı zorluğunu aynı anda çalıştırır:
 * artikel (das Heft / der Stift / die Tafel) ve BİRLEŞİK KELİME
 * (Hausaufgabe, Klassenzimmer, Stundenplan). İkincisi Türk öğrenci için
 * aslında kolaydır — Türkçe de kelime birleştirir — ama artikelin son
 * parçadan geldiği kuralı öğrenilmelidir.
 */

export const KELIMELER = [
  {
    id: 'de-schule',
    dil: 'de',
    kelime: 'Schule',
    artikel: 'die',
    cogul: 'die Schulen',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Der Ort, wo Kinder und Jugendliche lernen.',
    turkceDestek: 'okul',
    ipa: '/ˈʃuːlə/',
    heceler: 'Schu-le (sch → tek "ş")',
    ornekler: [
      { de: 'Die Schule beginnt um acht Uhr.', tr: 'Okul saat sekizde başlıyor.' },
      { de: 'Ich gehe gern in die Schule.', tr: 'Okula gitmeyi severim.' },
    ],
    esdizim: ['in die Schule gehen', 'die Schule beginnt', 'nach der Schule'],
    aile: ['der Schüler', 'das Schuljahr', 'die Grundschule'],
    hata: '"in die Schule gehen" (hareket, Akkusativ) ile "in der Schule sein" (yer, Dativ) karışır. Türkçede ikisi de "okula/okulda" ekiyle kurulur.',
    hatirlatma: 'Almanca okul sistemi üç kola ayrılır: Hauptschule, Realschule, Gymnasium. Gymnasium spor salonu DEĞİL, lisedir.',
    uretim: {
      yonerge: 'Okulunun kaçta başladığını yaz.',
      kabul: ['Die Schule beginnt um', 'Meine Schule beginnt um'],
    },
  },
  {
    id: 'de-klasse',
    dil: 'de',
    kelime: 'Klasse',
    artikel: 'die',
    cogul: 'die Klassen',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Eine Gruppe von Schülern, die zusammen lernen; auch die Jahrgangsstufe.',
    turkceDestek: 'sınıf (grup ve seviye)',
    ipa: '/ˈklasə/',
    heceler: 'Klas-se',
    ornekler: [
      { de: 'Ich bin in der neunten Klasse.', tr: 'Dokuzuncu sınıftayım.' },
      { de: 'Unsere Klasse hat 28 Schüler.', tr: 'Sınıfımızda 28 öğrenci var.' },
    ],
    esdizim: ['in der … Klasse sein', 'die Klassenarbeit', 'der Klassenlehrer'],
    aile: ['das Klassenzimmer', 'der Klassenkamerad'],
    hata: 'Sınıf ODASI için "Klassenzimmer" kullanılır; "Klasse" öğrenci grubu ya da seviyedir.',
    hatirlatma: 'Sıra sayıları -ten/-sten ekiyle kurulur ve Dativ\'de -n alır: in der neunten Klasse.',
    uretim: {
      yonerge: 'Kaçıncı sınıfta olduğunu yaz.',
      kabul: ['Ich bin in der'],
    },
  },
  {
    id: 'de-lehrerin',
    dil: 'de',
    kelime: 'Lehrerin',
    artikel: 'die',
    cogul: 'die Lehrerinnen',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Eine Frau, die in der Schule unterrichtet.',
    turkceDestek: 'kadın öğretmen',
    ipa: '/ˈleːʁəʁɪn/',
    heceler: 'Leh-re-rin',
    ornekler: [
      { de: 'Meine Deutschlehrerin heißt Frau Wagner.', tr: 'Almanca öğretmenimin adı Wagner Hanım.' },
      { de: 'Die Lehrerin erklärt die Aufgabe.', tr: 'Öğretmen ödevi açıklıyor.' },
    ],
    esdizim: ['die Deutschlehrerin', 'die Klassenlehrerin'],
    aile: ['der Lehrer', 'lehren'],
    hata: 'Çoğulunda "n" ikilenir: Lehrerin → LehrerinNEN. -in ile biten bütün meslek adlarında böyledir.',
    hatirlatma: 'Almancada öğretmene adıyla değil soyadıyla hitap edilir: Frau Wagner, Herr Schmidt.',
    uretim: {
      yonerge: 'Almanca öğretmeninin adını yaz.',
      kabul: ['Meine Lehrerin heißt', 'Mein Lehrer heißt', 'Meine Deutschlehrerin heißt'],
    },
  },
  {
    id: 'de-heft',
    dil: 'de',
    kelime: 'Heft',
    artikel: 'das',
    cogul: 'die Hefte',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Dünnes Buch mit leeren Seiten zum Schreiben.',
    turkceDestek: 'defter',
    ipa: '/hɛft/',
    heceler: 'Heft (kısa e)',
    ornekler: [
      { de: 'Mein Heft ist in der Tasche.', tr: 'Defterim çantada.' },
      { de: 'Öffnet bitte eure Hefte!', tr: 'Lütfen defterlerinizi açın!' },
    ],
    esdizim: ['das Heft öffnen', 'ins Heft schreiben'],
    aile: ['das Schulheft', 'heften'],
    hata: 'Türkçedeki "defter" ile "kitap" farkı Almancada da vardır: Heft = defter, Buch = kitap. Öğrenci ikisine de "Buch" diyor.',
    hatirlatma: '"Deftere yazmak" hareket bildirir ve Akkusativ ister: INS Heft schreiben.',
    uretim: {
      yonerge: 'Defterinin nerede olduğunu yaz.',
      kabul: ['Mein Heft ist'],
    },
  },
  {
    id: 'de-stift',
    dil: 'de',
    kelime: 'Stift',
    artikel: 'der',
    cogul: 'die Stifte',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Ein Gegenstand zum Schreiben oder Malen.',
    turkceDestek: 'kalem (genel)',
    ipa: '/ʃtɪft/',
    heceler: 'Stift (St → "şt")',
    ornekler: [
      { de: 'Hast du einen Stift für mich?', tr: 'Bana bir kalem verir misin?' },
      { de: 'Der Stift schreibt nicht mehr.', tr: 'Kalem artık yazmıyor.' },
    ],
    esdizim: ['der Bleistift', 'der Kugelschreiber', 'einen Stift leihen'],
    aile: ['der Bleistift', 'der Buntstift'],
    hata: 'Kurşun kalem "Bleistift", tükenmez "Kugelschreiber" (kısaca "Kuli")dir. "Stift" hepsinin genel adıdır.',
    hatirlatma: 'Kelime başındaki st/sp her zaman "şt/şp" okunur: Stift → "ştift".',
    uretim: {
      yonerge: 'Birinden kalem iste (nazik biçimde).',
      kabul: ['Hast du einen Stift', 'Haben Sie einen Stift', 'Kannst du mir einen Stift geben'],
    },
  },
  {
    id: 'de-tafel',
    dil: 'de',
    kelime: 'Tafel',
    artikel: 'die',
    cogul: 'die Tafeln',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Die große Fläche in der Klasse, auf die der Lehrer schreibt.',
    turkceDestek: 'tahta (sınıf tahtası)',
    ipa: '/ˈtaːfl̩/',
    heceler: 'Ta-fel',
    ornekler: [
      { de: 'Der Lehrer schreibt an die Tafel.', tr: 'Öğretmen tahtaya yazıyor.' },
      { de: 'Was steht an der Tafel?', tr: 'Tahtada ne yazıyor?' },
    ],
    esdizim: ['an die Tafel schreiben', 'an der Tafel stehen'],
    aile: ['die Schultafel', 'die Tafel Schokolade'],
    hata: '"an die Tafel" (yazarken, hareket) ile "an der Tafel" (dururken, yer) ayrımı yapılmalı.',
    hatirlatma: 'Aynı kelime çikolata için de kullanılır: eine Tafel Schokolade = bir tablet çikolata.',
    uretim: {
      yonerge: 'Tahtada ne yazdığını soran bir cümle yaz.',
      kabul: ['Was steht an der Tafel'],
    },
  },
  {
    id: 'de-hausaufgabe',
    dil: 'de',
    kelime: 'Hausaufgabe',
    artikel: 'die',
    cogul: 'die Hausaufgaben',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Die Aufgaben, die man zu Hause für die Schule macht.',
    turkceDestek: 'ev ödevi',
    ipa: '/ˈhaʊ̯sˌʔaʊ̯fɡaːbə/',
    heceler: 'Haus-auf-ga-be',
    ornekler: [
      { de: 'Ich mache meine Hausaufgaben am Abend.', tr: 'Ödevlerimi akşam yapıyorum.' },
      { de: 'Hast du die Hausaufgaben gemacht?', tr: 'Ödevleri yaptın mı?' },
    ],
    esdizim: ['Hausaufgaben machen', 'die Hausaufgaben vergessen'],
    aile: ['das Haus', 'die Aufgabe'],
    hata: 'Neredeyse her zaman ÇOĞUL kullanılır: "die Hausaufgaben machen". Tekil biçim tek bir soru için kullanılır.',
    hatirlatma: 'Bu, "machen" fiilinin doğru kullanıldığı yerlerden biridir — Hausaufgaben MACHEN.',
    uretim: {
      yonerge: 'Ödevlerini ne zaman yaptığını yaz.',
      kabul: ['Ich mache meine Hausaufgaben'],
    },
  },
  {
    id: 'de-pruefung',
    dil: 'de',
    kelime: 'Prüfung',
    artikel: 'die',
    cogul: 'die Prüfungen',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Ein Test, der zeigt, was man gelernt hat.',
    turkceDestek: 'sınav',
    ipa: '/ˈpʁyːfʊŋ/',
    heceler: 'Prü-fung',
    ornekler: [
      { de: 'Morgen habe ich eine Prüfung in Mathe.', tr: 'Yarın matematik sınavım var.' },
      { de: 'Ich lerne für die Prüfung.', tr: 'Sınava çalışıyorum.' },
    ],
    esdizim: ['eine Prüfung haben', 'für eine Prüfung lernen', 'die Prüfung bestehen'],
    aile: ['prüfen', 'der Prüfer', 'die Klassenarbeit'],
    hata: '"Sınava çalışmak" için "auf" değil "FÜR" kullanılır: für die Prüfung lernen.',
    hatirlatma: '-ung ile biten bütün kelimeler "die" alır. Bu, artikel tahmininde en güvenilir kurallardan biridir.',
    uretim: {
      yonerge: 'Yakında bir sınavın olup olmadığını yaz.',
      kabul: ['Ich habe eine Prüfung', 'Morgen habe ich eine Prüfung', 'Ich habe keine Prüfung'],
    },
  },
  {
    id: 'de-note',
    dil: 'de',
    kelime: 'Note',
    artikel: 'die',
    cogul: 'die Noten',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Die Bewertung einer Leistung in der Schule.',
    turkceDestek: 'not (karne notu)',
    ipa: '/ˈnoːtə/',
    heceler: 'No-te',
    ornekler: [
      { de: 'Ich habe eine gute Note bekommen.', tr: 'İyi bir not aldım.' },
      { de: 'Meine Noten sind dieses Jahr besser.', tr: 'Notlarım bu yıl daha iyi.' },
    ],
    esdizim: ['eine gute Note', 'eine schlechte Note', 'Noten bekommen'],
    aile: ['das Zeugnis', 'benoten'],
    hata: 'Almanya\'da not sistemi TERSTİR: 1 en iyi, 6 en kötüdür. Türkiye\'deki 100\'lük sisteme alışkın öğrenci bunu ters okur.',
    hatirlatma: 'Not "almak" için "bekommen" kullanılır — "nehmen" değil.',
    uretim: {
      yonerge: 'Son sınavdan aldığın notu anlatan bir cümle yaz.',
      kabul: ['Ich habe eine', 'Ich habe eine gute Note bekommen'],
    },
  },
  {
    id: 'de-fach',
    dil: 'de',
    kelime: 'Fach',
    artikel: 'das',
    cogul: 'die Fächer',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Ein Bereich, den man in der Schule lernt, zum Beispiel Mathe.',
    turkceDestek: 'ders (branş)',
    ipa: '/fax/',
    heceler: 'Fach (ch → gırtlaktan)',
    ornekler: [
      { de: 'Mein Lieblingsfach ist Biologie.', tr: 'En sevdiğim ders biyoloji.' },
      { de: 'Wie viele Fächer habt ihr?', tr: 'Kaç dersiniz var?' },
    ],
    esdizim: ['das Lieblingsfach', 'ein schweres Fach'],
    aile: ['das Lieblingsfach', 'fachlich'],
    hata: 'Ders SAATİ için "Stunde", branş için "Fach" kullanılır. Türkçede ikisi de "ders"tir.',
    hatirlatma: 'Çoğulunda umlaut var: Fach → Fächer.',
    uretim: {
      yonerge: 'En sevdiğin dersi yaz.',
      kabul: ['Mein Lieblingsfach ist'],
    },
  },
  {
    id: 'de-mathe',
    dil: 'de',
    kelime: 'Mathe',
    artikel: 'die',
    cogul: 'çoğulu yok',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Kurzform von Mathematik: das Fach mit Zahlen und Rechnen.',
    turkceDestek: 'matematik (kısaltma)',
    ipa: '/ˈmatə/',
    heceler: 'Ma-the (th → tek "t")',
    ornekler: [
      { de: 'In Mathe bin ich ziemlich gut.', tr: 'Matematikte oldukça iyiyim.' },
      { de: 'Wir haben heute zwei Stunden Mathe.', tr: 'Bugün iki saat matematiğimiz var.' },
    ],
    esdizim: ['in Mathe gut sein', 'die Mathearbeit'],
    aile: ['die Mathematik'],
    hata: 'Ders adları söylenirken artikel KULLANILMAZ: "Ich habe Mathe" (die Mathe değil).',
    hatirlatma: 'Almancada "th" tek "t" okunur: Mathe → "matı", Theater → "teatır".',
    uretim: {
      yonerge: 'Hangi derste iyi olduğunu yaz.',
      kabul: ['In Mathe bin ich', 'Ich bin gut in'],
    },
  },
  {
    id: 'de-stundenplan',
    dil: 'de',
    kelime: 'Stundenplan',
    artikel: 'der',
    cogul: 'die Stundenpläne',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Eine Tabelle, die zeigt, wann welches Fach ist.',
    turkceDestek: 'ders programı',
    ipa: '/ˈʃtʊndn̩ˌplaːn/',
    heceler: 'Stun-den-plan',
    ornekler: [
      { de: 'Unser Stundenplan hängt an der Wand.', tr: 'Ders programımız duvarda asılı.' },
      { de: 'Am Montag habe ich sechs Stunden.', tr: 'Pazartesi altı dersim var.' },
    ],
    esdizim: ['der neue Stundenplan', 'im Stundenplan stehen'],
    aile: ['die Stunde', 'der Plan'],
    hata: 'Artikel son parçadan gelir: der Plan → der Stundenplan. Öğrenci ilk parçaya (die Stunde) bakıp "die" diyor.',
    hatirlatma: 'Bu kural bütün birleşik kelimeler için geçerlidir ve artikel öğrenmenin en pratik kısayoludur.',
    uretim: {
      yonerge: 'Pazartesi kaç dersin olduğunu yaz.',
      kabul: ['Am Montag habe ich'],
    },
  },
  {
    id: 'de-pause',
    dil: 'de',
    kelime: 'Pause',
    artikel: 'die',
    cogul: 'die Pausen',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Eine kurze Zeit ohne Arbeit oder Unterricht.',
    turkceDestek: 'teneffüs, mola',
    ipa: '/ˈpaʊ̯zə/',
    heceler: 'Pau-se (s → "z" okunur)',
    ornekler: [
      { de: 'In der Pause esse ich ein Brötchen.', tr: 'Teneffüste bir sandviç yiyorum.' },
      { de: 'Wir machen jetzt eine Pause.', tr: 'Şimdi bir mola veriyoruz.' },
    ],
    esdizim: ['eine Pause machen', 'in der Pause', 'die große Pause'],
    aile: ['pausieren'],
    hata: 'İki ünlü arasındaki "s" Almancada "z" okunur: Pause → "pauzı", lesen → "leezın".',
    hatirlatma: 'Mola "vermek" için machen kullanılır: eine Pause machen.',
    uretim: {
      yonerge: 'Teneffüste ne yaptığını yaz.',
      kabul: ['In der Pause'],
    },
  },
  {
    id: 'de-lesen',
    dil: 'de',
    kelime: 'lesen',
    cekim: 'liest · las · hat gelesen',
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    almancaTanim: 'Geschriebene Wörter mit den Augen verstehen.',
    turkceDestek: 'okumak',
    ipa: '/ˈleːzn̩/',
    heceler: 'le-sen (s → "z")',
    ornekler: [
      { de: 'Ich lese jeden Abend ein bisschen.', tr: 'Her akşam biraz okuyorum.' },
      { de: 'Er liest gern Krimis.', tr: 'Polisiye okumayı sever.' },
    ],
    esdizim: ['ein Buch lesen', 'laut lesen', 'gern lesen'],
    aile: ['der Leser', 'die Lesung', 'vorlesen'],
    hata: 'Kök ünlüsü değişir: du liest, er liest. 2. ve 3. tekil AYNIDIR — çünkü kök zaten -s ile biter.',
    hatirlatma: 'Okulda okumak "lesen"dir; üniversitede okumak "studieren".',
    uretim: {
      yonerge: 'Ne okumayı sevdiğini "gern" ile yaz.',
      kabul: ['Ich lese gern'],
    },
  },
  {
    id: 'de-schreiben',
    dil: 'de',
    kelime: 'schreiben',
    cekim: 'schreibt · schrieb · hat geschrieben',
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    almancaTanim: 'Wörter mit einem Stift oder auf dem Computer machen.',
    turkceDestek: 'yazmak',
    ipa: '/ˈʃʁaɪ̯bn̩/',
    heceler: 'schrei-ben (schr → "şr")',
    ornekler: [
      { de: 'Ich schreibe eine E-Mail an meine Lehrerin.', tr: 'Öğretmenime bir e-posta yazıyorum.' },
      { de: 'Wie schreibt man das?', tr: 'Bu nasıl yazılır?' },
    ],
    esdizim: ['eine E-Mail schreiben', 'einen Test schreiben', 'richtig schreiben'],
    aile: ['der Schreibtisch', 'die Schrift', 'aufschreiben'],
    hata: 'Almancada sınav "yazılır": "einen Test schreiben". Türkçedeki "sınava girmek" birebir çevrilmez.',
    hatirlatma: '"Wie schreibt man das?" bir kelimenin yazımını sormanın en doğal yoludur.',
    uretim: {
      yonerge: 'Bir kelimenin nasıl yazıldığını sor.',
      kabul: ['Wie schreibt man das'],
    },
  },
  {
    id: 'de-verstehen',
    dil: 'de',
    kelime: 'verstehen',
    cekim: 'versteht · verstand · hat verstanden',
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    almancaTanim: 'Den Sinn von etwas erfassen.',
    turkceDestek: 'anlamak',
    ipa: '/fɛɐ̯ˈʃteːən/',
    heceler: 'ver-ste-hen (vurgu: STE)',
    ornekler: [
      { de: 'Ich verstehe das nicht.', tr: 'Bunu anlamıyorum.' },
      { de: 'Verstehst du mich?', tr: 'Beni anlıyor musun?' },
    ],
    esdizim: ['nicht verstehen', 'gut verstehen', 'falsch verstehen'],
    aile: ['das Verständnis', 'verständlich'],
    hata: 'Ayrılabilen fiil DEĞİLDİR: ver- ön eki asla ayrılmaz ve vurgu almaz. "Ich stehe ver" diye bir şey yoktur.',
    hatirlatma: 'Vurgusuz ön ekler (be-, ge-, er-, ver-, ent-, zer-) hiçbir zaman ayrılmaz. Bu, ayrılabilen fiil kuralının diğer yarısıdır.',
    uretim: {
      yonerge: 'Anlamadığını söyleyen bir cümle yaz.',
      kabul: ['Ich verstehe das nicht', 'Ich verstehe nicht'],
    },
  },
  {
    id: 'de-fragen',
    dil: 'de',
    kelime: 'fragen',
    cekim: 'fragt · fragte · hat gefragt',
    tur: 'fiil',
    seviye: 'A1',
    almancaTanim: 'Etwas wissen wollen und deshalb sprechen.',
    turkceDestek: 'sormak',
    ipa: '/ˈfʁaːɡn̩/',
    heceler: 'fra-gen',
    ornekler: [
      { de: 'Ich frage die Lehrerin.', tr: 'Öğretmene soruyorum.' },
      { de: 'Darf ich etwas fragen?', tr: 'Bir şey sorabilir miyim?' },
    ],
    esdizim: ['eine Frage stellen', 'nach dem Weg fragen'],
    zitAnlam: ['antworten'],
    aile: ['die Frage', 'die Antwort'],
    hata: 'Soru "sormak" için isimle kurulan doğru kalıp "eine Frage STELLEN"dir; "eine Frage machen" yanlıştır.',
    hatirlatma: 'Kişiyi doğrudan alır (Akkusativ): Ich frage DICH. Ama "antworten" Dativ ister: Ich antworte DIR.',
    uretim: {
      yonerge: 'Nazikçe soru sormak için izin iste.',
      kabul: ['Darf ich etwas fragen', 'Kann ich etwas fragen'],
    },
  },
  {
    id: 'de-antworten',
    dil: 'de',
    kelime: 'antworten',
    cekim: 'antwortet · antwortete · hat geantwortet',
    tur: 'fiil',
    seviye: 'A1',
    almancaTanim: 'Auf eine Frage etwas sagen.',
    turkceDestek: 'cevap vermek',
    ipa: '/ˈantvɔʁtn̩/',
    heceler: 'ant-wor-ten (w → "v")',
    ornekler: [
      { de: 'Bitte antworte mir!', tr: 'Lütfen bana cevap ver!' },
      { de: 'Er antwortet nicht auf meine Frage.', tr: 'Soruma cevap vermiyor.' },
    ],
    esdizim: ['auf eine Frage antworten', 'jemandem antworten'],
    zitAnlam: ['fragen'],
    aile: ['die Antwort'],
    hata: 'Kişi Dativ, soru ise "auf" + Akkusativ alır: "Ich antworte DIR auf DEINE Frage." Türkçede tek ekle kurulan bu iki ilişki Almancada ayrılır.',
    hatirlatma: 'Kökü -t ile bittiği için araya "e" girer: er antwortEt.',
    uretim: {
      yonerge: 'Birinden cevap vermesini nazikçe iste.',
      kabul: ['Bitte antworte mir', 'Bitte antworten Sie mir'],
    },
  },
  {
    id: 'de-koennen',
    dil: 'de',
    kelime: 'können',
    cekim: 'kann · konnte · hat gekonnt',
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    almancaTanim: 'Modalverb: eine Fähigkeit oder Möglichkeit haben.',
    turkceDestek: '-ebilmek (yetenek, olasılık)',
    ipa: '/ˈkœnən/',
    heceler: 'kön-nen (ö kısa)',
    ornekler: [
      { de: 'Ich kann gut schwimmen.', tr: 'İyi yüzebiliyorum.' },
      { de: 'Kannst du mir helfen?', tr: 'Bana yardım edebilir misin?' },
    ],
    esdizim: ['gut können', 'Kannst du…?', 'Ich kann nicht'],
    aile: ['die Fähigkeit', 'möglich'],
    hata: 'Tekil kişilerde umlaut DÜŞER: ich kann, du kannst, er kann (ich könne değil). Çoğulda geri gelir: wir können.',
    hatirlatma: 'Modal fiil ikinci sırada, asıl fiil MASTAR hâlinde cümlenin sonundadır: "Ich kann gut Deutsch sprechen."',
    uretim: {
      yonerge: 'Yapabildiğin bir şeyi "können" ile yaz (mastar sonda!).',
      kabul: ['Ich kann'],
    },
  },
  {
    id: 'de-muessen',
    dil: 'de',
    kelime: 'müssen',
    cekim: 'muss · musste · hat gemusst',
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    almancaTanim: 'Modalverb: etwas ist notwendig.',
    turkceDestek: 'zorunda olmak, -meli/-malı',
    ipa: '/ˈmʏsn̩/',
    heceler: 'müs-sen',
    ornekler: [
      { de: 'Ich muss heute lernen.', tr: 'Bugün ders çalışmam gerek.' },
      { de: 'Wir müssen um acht da sein.', tr: 'Sekizde orada olmalıyız.' },
    ],
    esdizim: ['Ich muss…', 'Musst du…?'],
    aile: ['das Muss', 'notwendig'],
    hata: 'Olumsuzu "nicht müssen" DEĞİL, "nicht brauchen zu" ya da "nicht dürfen"dir. "Du musst nicht kommen" = gelmene gerek yok (yasak değil).',
    hatirlatma: 'Tekilde umlaut düşer: ich muss, du musst, er muss.',
    uretim: {
      yonerge: 'Bugün yapman gereken bir şeyi yaz.',
      kabul: ['Ich muss'],
    },
  },
  {
    id: 'de-lieblings',
    dil: 'de',
    kelime: 'Lieblings-',
    tur: 'ön ek',
    seviye: 'A1',
    almancaTanim: 'Vorsilbe: das, was man am liebsten mag.',
    turkceDestek: 'en sevdiği … (ön ek)',
    ipa: '/ˈliːplɪŋs/',
    heceler: 'Lieb-lings (ie → uzun "i")',
    ornekler: [
      { de: 'Mein Lieblingsfach ist Physik.', tr: 'En sevdiğim ders fizik.' },
      { de: 'Was ist dein Lieblingsessen?', tr: 'En sevdiğin yemek ne?' },
    ],
    esdizim: ['das Lieblingsfach', 'das Lieblingsessen', 'die Lieblingsfarbe'],
    aile: ['lieb', 'lieben', 'am liebsten'],
    hata: 'Ayrı yazılmaz, bitişik yazılır: Lieblingsfach (Lieblings Fach değil). Artikel son parçadan gelir.',
    hatirlatma: 'Bu ön ek Almancada "en sevdiğim"i tek kelimede söylemenin yoludur; Türkçede üç kelime gerekir.',
    uretim: {
      yonerge: 'En sevdiğin bir şeyi "Lieblings-" ile yaz.',
      kabul: ['Mein Lieblings', 'Meine Lieblings'],
    },
  },
  {
    id: 'de-schwierig',
    dil: 'de',
    kelime: 'schwierig',
    tur: 'sıfat',
    seviye: 'A1',
    almancaTanim: 'Nicht leicht; man braucht viel Mühe.',
    turkceDestek: 'zor',
    ipa: '/ˈʃviːʁɪç/',
    heceler: 'schwie-rig (sondaki -ig → "iç")',
    ornekler: [
      { de: 'Deutsch ist am Anfang schwierig.', tr: 'Almanca başta zor.' },
      { de: 'Die Aufgabe war nicht schwierig.', tr: 'Ödev zor değildi.' },
    ],
    esdizim: ['sehr schwierig', 'eine schwierige Aufgabe'],
    esAnlam: ['schwer'],
    zitAnlam: ['leicht', 'einfach'],
    aile: ['die Schwierigkeit'],
    hata: 'Sondaki "-ig" Almancada "ik" değil "iç" okunur: schwierig → "şviiriç", richtig → "riçtiç".',
    hatirlatma: '"schwer" hem "zor" hem "ağır" demektir; "schwierig" yalnız "zor"dur.',
    uretim: {
      yonerge: 'Almancanın senin için zor olup olmadığını yaz.',
      kabul: ['Deutsch ist', 'Für mich ist Deutsch'],
    },
  },
]
