/**
 * A1 — GÜNLÜK RUTİN KELİMELERİ
 * ==================================================================
 *
 * Bu setteki fiillerin çoğu ya AYRILABİLEN fiildir (aufstehen) ya da
 * kök ünlüsü değişir (fahren → fährt). İkisi de Türkçede karşılığı
 * olmayan davranışlardır; bu yüzden her kayıtta `cekim` alanı ve
 * ayrılma bilgisi açıkça verilmiştir.
 */

export const KELIMELER = [
  {
    id: 'de-aufstehen',
    dil: 'de',
    kelime: 'aufstehen',
    cekim: 'steht auf · stand auf · ist aufgestanden',
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    almancaTanim: 'Aus dem Bett kommen; sich vom Sitzen erheben.',
    turkceDestek: 'kalkmak, yataktan çıkmak',
    ipa: '/ˈaʊ̯fˌʃteːən/',
    heceler: 'auf-ste-hen (vurgu ÖN EKTE: AUF)',
    ornekler: [
      { de: 'Ich stehe um sieben Uhr auf.', tr: 'Saat yedide kalkıyorum.' },
      { de: 'Am Wochenende stehe ich spät auf.', tr: 'Hafta sonu geç kalkıyorum.' },
    ],
    esdizim: ['früh aufstehen', 'spät aufstehen'],
    aile: ['stehen', 'der Aufstand'],
    hata: 'Ana cümlede İKİYE AYRILIR: "Ich stehe … auf". Öğrenci Türkçedeki tek parçalı "kalkmak" fiilinden yola çıkıp "Ich aufstehe" yazıyor.',
    hatirlatma: 'Vurgu ön ektedir; vurgu ön ekteyse fiil ayrılır. Bu kural neredeyse istisnasızdır.',
    uretim: {
      yonerge: 'Kaçta kalktığını yaz (fiili ayırmayı unutma).',
      kabul: ['Ich stehe um', 'Ich stehe um sieben Uhr auf'],
    },
  },
  {
    id: 'de-fruehstuecken',
    dil: 'de',
    kelime: 'frühstücken',
    cekim: 'frühstückt · frühstückte · hat gefrühstückt',
    tur: 'fiil',
    seviye: 'A1',
    almancaTanim: 'Am Morgen die erste Mahlzeit essen.',
    turkceDestek: 'kahvaltı yapmak',
    ipa: '/ˈfʁyːˌʃtʏkn̩/',
    heceler: 'früh-stü-cken (ü iki kez geçer)',
    ornekler: [
      { de: 'Ich frühstücke um halb acht.', tr: 'Yedi buçukta kahvaltı yapıyorum.' },
      { de: 'Wir frühstücken zusammen.', tr: 'Birlikte kahvaltı yapıyoruz.' },
    ],
    esdizim: ['das Frühstück', 'zum Frühstück'],
    aile: ['das Frühstück', 'früh'],
    hata: 'Ayrılabilen fiil DEĞİLDİR: "Ich stücke früh" olmaz. Bileşik görünmesine rağmen tek parça çekilir.',
    hatirlatma: 'Türkçede "kahvaltı yapmak" iki kelime, Almancada tek fiil: frühstücken.',
    uretim: {
      yonerge: 'Kaçta kahvaltı yaptığını yaz.',
      kabul: ['Ich frühstücke um', 'Ich fruehstuecke um'],
    },
  },
  {
    id: 'de-gehen',
    dil: 'de',
    kelime: 'gehen',
    cekim: 'geht · ging · ist gegangen',
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    almancaTanim: 'Sich zu Fuß fortbewegen.',
    turkceDestek: 'gitmek, yürümek',
    ipa: '/ˈɡeːən/',
    heceler: 'ge-hen (h okunmaz, e uzar)',
    ornekler: [
      { de: 'Ich gehe zu Fuß zur Schule.', tr: 'Okula yürüyerek gidiyorum.' },
      { de: 'Wie geht es dir?', tr: 'Nasılsın?' },
    ],
    esdizim: ['zu Fuß gehen', 'nach Hause gehen', 'ins Kino gehen'],
    aile: ['der Gang', 'weggehen', 'mitgehen'],
    hata: 'Araçla gidiliyorsa "gehen" değil "fahren" kullanılır. Almancada yürümek ile taşıtla gitmek AYRI fiillerdir.',
    hatirlatma: 'Perfekt\'i "sein" ile kurulur: Ich bin gegangen.',
    uretim: {
      yonerge: 'Okula nasıl gittiğini yaz.',
      kabul: ['Ich gehe zu Fuß zur Schule', 'Ich gehe zur Schule', 'Ich fahre mit dem Bus zur Schule'],
    },
  },
  {
    id: 'de-fahren',
    dil: 'de',
    kelime: 'fahren',
    cekim: 'fährt · fuhr · ist gefahren',
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    almancaTanim: 'Mit einem Fahrzeug irgendwohin kommen.',
    turkceDestek: '(taşıtla) gitmek; sürmek',
    ipa: '/ˈfaːʁən/',
    heceler: 'fah-ren',
    ornekler: [
      { de: 'Ich fahre mit dem Bus zur Schule.', tr: 'Okula otobüsle gidiyorum.' },
      { de: 'Er fährt sehr schnell.', tr: 'O çok hızlı sürüyor.' },
    ],
    esdizim: ['mit dem Bus fahren', 'Fahrrad fahren', 'nach Berlin fahren'],
    aile: ['das Fahrrad', 'die Fahrt', 'abfahren'],
    hata: 'Kök ünlüsü 2. ve 3. tekilde değişir: du fährst, er fährt. "du fahrst" yanlıştır.',
    hatirlatma: 'Taşıt "mit dem/der" ile söylenir: mit dem Bus, mit dem Auto, mit der Bahn.',
    uretim: {
      yonerge: 'Hangi araçla bir yere gittiğini yaz.',
      kabul: ['Ich fahre mit dem'],
    },
  },
  {
    id: 'de-essen',
    dil: 'de',
    kelime: 'essen',
    cekim: 'isst · aß · hat gegessen',
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    almancaTanim: 'Speisen zu sich nehmen.',
    turkceDestek: 'yemek (yemek yemek)',
    ipa: '/ˈɛsn̩/',
    heceler: 'es-sen (kısa e)',
    ornekler: [
      { de: 'Ich esse jeden Morgen ein Ei.', tr: 'Her sabah bir yumurta yiyorum.' },
      { de: 'Was isst du zu Mittag?', tr: 'Öğlen ne yiyorsun?' },
    ],
    esdizim: ['zu Mittag essen', 'Frühstück essen', 'das Essen'],
    aile: ['das Essen', 'der Esstisch'],
    hata: '3. tekilde "esst" değil "isst" olur — kök ünlüsü değişir ve "ist" (olmak) ile karışır. Fark: "er isst" (yiyor) / "er ist" (dır).',
    hatirlatma: 'Yazımdaki tek harf farkı anlamı tamamen değiştirir: isst ≠ ist.',
    uretim: {
      yonerge: 'Sabah ne yediğini yaz.',
      kabul: ['Ich esse'],
    },
  },
  {
    id: 'de-trinken',
    dil: 'de',
    kelime: 'trinken',
    cekim: 'trinkt · trank · hat getrunken',
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    almancaTanim: 'Eine Flüssigkeit zu sich nehmen.',
    turkceDestek: 'içmek',
    ipa: '/ˈtʁɪŋkn̩/',
    heceler: 'trin-ken (nk → genizden)',
    ornekler: [
      { de: 'Ich trinke morgens Tee.', tr: 'Sabahları çay içerim.' },
      { de: 'Trinkst du Kaffee oder Tee?', tr: 'Kahve mi içersin, çay mı?' },
    ],
    esdizim: ['Wasser trinken', 'Kaffee trinken', 'etwas zu trinken'],
    aile: ['das Getränk', 'der Trinker'],
    hata: 'Türkçede "sigara içmek" denir; Almancada sigara için "rauchen" kullanılır, "trinken" değil.',
    hatirlatma: 'Çorba da Almancada "içilmez", yenir: die Suppe ESSEN.',
    uretim: {
      yonerge: 'Sabahları ne içtiğini yaz.',
      kabul: ['Ich trinke'],
    },
  },
  {
    id: 'de-lernen',
    dil: 'de',
    kelime: 'lernen',
    cekim: 'lernt · lernte · hat gelernt',
    tur: 'fiil',
    seviye: 'A1',
    almancaTanim: 'Neues Wissen oder eine Fähigkeit bekommen.',
    turkceDestek: 'öğrenmek; ders çalışmak',
    ipa: '/ˈlɛʁnən/',
    heceler: 'ler-nen',
    ornekler: [
      { de: 'Ich lerne seit zwei Jahren Deutsch.', tr: 'İki yıldır Almanca öğreniyorum.' },
      { de: 'Am Abend lerne ich für die Prüfung.', tr: 'Akşam sınav için çalışıyorum.' },
    ],
    esdizim: ['Deutsch lernen', 'für eine Prüfung lernen', 'auswendig lernen'],
    aile: ['der Lerner', 'lehren'],
    hata: 'Almancada "ders çalışmak" da "lernen"dir. "studieren" ise ÜNİVERSİTEDE okumak demektir; lise öğrencisi "Ich studiere" diyemez.',
    hatirlatma: 'Süre "seit" ile söylenir ve Dativ ister: seit zwei Jahren.',
    uretim: {
      yonerge: 'Ne kadar zamandır Almanca öğrendiğini yaz.',
      kabul: ['Ich lerne seit', 'Ich lerne Deutsch seit'],
    },
  },
  {
    id: 'de-arbeiten',
    dil: 'de',
    kelime: 'arbeiten',
    cekim: 'arbeitet · arbeitete · hat gearbeitet',
    tur: 'fiil',
    seviye: 'A1',
    almancaTanim: 'Eine Tätigkeit für Geld oder als Aufgabe machen.',
    turkceDestek: 'çalışmak (iş)',
    ipa: '/ˈaʁbaɪ̯tn̩/',
    heceler: 'ar-bei-ten (ei → "ay")',
    ornekler: [
      { de: 'Meine Mutter arbeitet im Krankenhaus.', tr: 'Annem hastanede çalışıyor.' },
      { de: 'Er arbeitet als Ingenieur.', tr: 'Mühendis olarak çalışıyor.' },
    ],
    esdizim: ['als … arbeiten', 'bei … arbeiten', 'die Arbeit'],
    aile: ['die Arbeit', 'der Arbeiter', 'arbeitslos'],
    hata: 'Kökü -t ile bittiği için araya "e" girer: du arbeitEst, er arbeitEt. "er arbeitt" yanlıştır.',
    hatirlatma: 'Ders çalışmak "lernen"dir; "arbeiten" para kazanılan iştir.',
    uretim: {
      yonerge: 'Ailenden birinin nerede çalıştığını yaz.',
      kabul: ['Mein Vater arbeitet', 'Meine Mutter arbeitet'],
    },
  },
  {
    id: 'de-schlafen',
    dil: 'de',
    kelime: 'schlafen',
    cekim: 'schläft · schlief · hat geschlafen',
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    almancaTanim: 'Nachts mit geschlossenen Augen ruhen.',
    turkceDestek: 'uyumak',
    ipa: '/ˈʃlaːfn̩/',
    heceler: 'schla-fen',
    ornekler: [
      { de: 'Ich schlafe acht Stunden.', tr: 'Sekiz saat uyuyorum.' },
      { de: 'Das Kind schläft schon.', tr: 'Çocuk çoktan uyudu.' },
    ],
    esdizim: ['gut schlafen', 'einschlafen', 'das Schlafzimmer'],
    aile: ['das Schlafzimmer', 'einschlafen', 'der Schlaf'],
    hata: 'Kök ünlüsü değişir: du schläfst, er schläft. Ayrıca "uyuyakalmak" ayrı bir fiildir: einschlafen.',
    hatirlatma: '"schl" üçlüsü tek nefeste söylenir: "şlaafen".',
    uretim: {
      yonerge: 'Kaç saat uyuduğunu yaz.',
      kabul: ['Ich schlafe'],
    },
  },
  {
    id: 'de-uhr',
    dil: 'de',
    kelime: 'Uhr',
    artikel: 'die',
    cogul: 'die Uhren',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Ein Gerät, das die Zeit zeigt; auch das Wort für die Stunde.',
    turkceDestek: 'saat (alet ve saat bildirimi)',
    ipa: '/uːɐ̯/',
    heceler: 'Uhr (h okunmaz, u uzar)',
    ornekler: [
      { de: 'Es ist acht Uhr.', tr: 'Saat sekiz.' },
      { de: 'Meine Uhr geht falsch.', tr: 'Saatim yanlış çalışıyor.' },
    ],
    esdizim: ['um … Uhr', 'Wie viel Uhr ist es?', 'die Armbanduhr'],
    aile: ['die Uhrzeit', 'der Wecker'],
    hata: 'Saat sorulurken "Wie viel Uhr ist es?" ya da "Wie spät ist es?" denir. "Was ist die Uhr?" diye bir kalıp yoktur.',
    hatirlatma: 'Saat bildirirken sayıdan sonra "Uhr" gelir: um acht Uhr.',
    uretim: {
      yonerge: 'Şu anki saati Almanca yaz.',
      kabul: ['Es ist'],
    },
  },
  {
    id: 'de-zeit',
    dil: 'de',
    kelime: 'Zeit',
    artikel: 'die',
    cogul: 'die Zeiten',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Was man an der Uhr misst; auch: freie Stunden.',
    turkceDestek: 'zaman, vakit',
    ipa: '/tsaɪ̯t/',
    heceler: 'Zeit (Z → "ts", ei → "ay")',
    ornekler: [
      { de: 'Hast du heute Zeit?', tr: 'Bugün vaktin var mı?' },
      { de: 'Ich habe keine Zeit.', tr: 'Vaktim yok.' },
    ],
    esdizim: ['Zeit haben', 'keine Zeit haben', 'in letzter Zeit'],
    aile: ['die Freizeit', 'rechtzeitig', 'die Uhrzeit'],
    hata: 'Olumsuzu "nicht Zeit" değil "keine Zeit"tır — isim olduğu için kein ile olumsuzlanır.',
    hatirlatma: 'Almancanın en sık kullanılan kelimelerindendir; "Zeit" sesini doğru çıkarmak ("tsayt") aksanını hemen düzeltir.',
    uretim: {
      yonerge: 'Bir arkadaşına bugün vakti olup olmadığını sor.',
      kabul: ['Hast du heute Zeit', 'Hast du Zeit'],
    },
  },
  {
    id: 'de-morgen',
    dil: 'de',
    kelime: 'Morgen',
    artikel: 'der',
    cogul: 'die Morgen',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Die erste Zeit des Tages.',
    turkceDestek: 'sabah',
    ipa: '/ˈmɔʁɡn̩/',
    heceler: 'Mor-gen',
    ornekler: [
      { de: 'Am Morgen trinke ich Tee.', tr: 'Sabahları çay içerim.' },
      { de: 'Guten Morgen!', tr: 'Günaydın!' },
    ],
    esdizim: ['am Morgen', 'Guten Morgen', 'morgens'],
    aile: ['morgens', 'das Frühstück'],
    hata: 'Büyük harfle "Morgen" = sabah; küçük harfle "morgen" = yarın. Tek harf farkı iki ayrı kelime demektir.',
    hatirlatma: 'Günün bölümleri "am" ile söylenir: am Morgen, am Abend — ama "in der Nacht".',
    uretim: {
      yonerge: 'Sabahları ne yaptığını "Am Morgen" ile başlayarak yaz (fiil ikinci sırada!).',
      kabul: ['Am Morgen'],
    },
  },
  {
    id: 'de-abend',
    dil: 'de',
    kelime: 'Abend',
    artikel: 'der',
    cogul: 'die Abende',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Die Zeit nach dem Nachmittag und vor der Nacht.',
    turkceDestek: 'akşam',
    ipa: '/ˈaːbn̩t/',
    heceler: 'A-bend (sondaki d → "t")',
    ornekler: [
      { de: 'Am Abend mache ich meine Hausaufgaben.', tr: 'Akşam ödevlerimi yapıyorum.' },
      { de: 'Guten Abend! Wie geht es Ihnen?', tr: 'İyi akşamlar! Nasılsınız?' },
    ],
    esdizim: ['am Abend', 'Guten Abend', 'das Abendessen'],
    aile: ['das Abendessen', 'abends'],
    hata: '"Guten Abend" saat 18\'den sonra kullanılır; öğleden sonra "Guten Tag" denir. Zaman dilimleri Türkçedekinden farklı bölünür.',
    hatirlatma: 'Akşam yemeği "das Abendessen"dir; Almanlar çoğunlukla soğuk yer ve buna "Abendbrot" da denir.',
    uretim: {
      yonerge: 'Akşamları ne yaptığını "Am Abend" ile yaz.',
      kabul: ['Am Abend'],
    },
  },
  {
    id: 'de-nacht',
    dil: 'de',
    kelime: 'Nacht',
    artikel: 'die',
    cogul: 'die Nächte',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Die dunkle Zeit, wenn die Menschen schlafen.',
    turkceDestek: 'gece',
    ipa: '/naxt/',
    heceler: 'Nacht (ch → gırtlaktan sert)',
    ornekler: [
      { de: 'In der Nacht ist es sehr ruhig.', tr: 'Geceleri çok sakin oluyor.' },
      { de: 'Gute Nacht!', tr: 'İyi geceler!' },
    ],
    esdizim: ['in der Nacht', 'Gute Nacht', 'die ganze Nacht'],
    aile: ['nachts', 'die Mitternacht'],
    hata: 'Diğer zaman dilimleri "am" alırken gece "in der" alır: in der Nacht. Bu bir istisnadır ve ezberlenir.',
    hatirlatma: '"Gute Nacht" yalnızca yatmadan önce söylenir; veda için "Auf Wiedersehen" ya da "Tschüss" kullanılır.',
    uretim: {
      yonerge: 'Geceleri ne yaptığını "In der Nacht" ile yaz.',
      kabul: ['In der Nacht'],
    },
  },
  {
    id: 'de-woche',
    dil: 'de',
    kelime: 'Woche',
    artikel: 'die',
    cogul: 'die Wochen',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Sieben Tage von Montag bis Sonntag.',
    turkceDestek: 'hafta',
    ipa: '/ˈvɔxə/',
    heceler: 'Wo-che (W → "v")',
    ornekler: [
      { de: 'Diese Woche habe ich viel zu tun.', tr: 'Bu hafta çok işim var.' },
      { de: 'Wir sehen uns nächste Woche.', tr: 'Gelecek hafta görüşürüz.' },
    ],
    esdizim: ['diese Woche', 'nächste Woche', 'das Wochenende'],
    aile: ['das Wochenende', 'der Wochentag', 'wöchentlich'],
    hata: 'Zaman ifadesi cümle başına gelince fiil hemen arkasından gelir: "Diese Woche HABE ich…" — özne fiilin arkasına geçer.',
    hatirlatma: 'Almancada hafta pazartesi başlar; "das Wochenende" cumartesi-pazardır.',
    uretim: {
      yonerge: 'Bu hafta ne yapacağını "Diese Woche" ile başlat.',
      kabul: ['Diese Woche'],
    },
  },
  {
    id: 'de-wochenende',
    dil: 'de',
    kelime: 'Wochenende',
    artikel: 'das',
    cogul: 'die Wochenenden',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Samstag und Sonntag.',
    turkceDestek: 'hafta sonu',
    ipa: '/ˈvɔxn̩ˌʔɛndə/',
    heceler: 'Wo-chen-en-de',
    ornekler: [
      { de: 'Am Wochenende spiele ich Fußball.', tr: 'Hafta sonu futbol oynuyorum.' },
      { de: 'Schönes Wochenende!', tr: 'İyi hafta sonları!' },
    ],
    esdizim: ['am Wochenende', 'jedes Wochenende', 'Schönes Wochenende!'],
    aile: ['die Woche', 'das Ende'],
    hata: '"in Wochenende" değil "AM Wochenende" denir. Edat kelimeyle birlikte ezberlenmelidir.',
    hatirlatma: 'Birleşik kelimenin artikeli sondan gelir: das Ende → das Wochenende.',
    uretim: {
      yonerge: 'Hafta sonu ne yaptığını yaz.',
      kabul: ['Am Wochenende'],
    },
  },
  {
    id: 'de-immer',
    dil: 'de',
    kelime: 'immer',
    tur: 'zarf',
    seviye: 'A1',
    almancaTanim: 'Jedes Mal, ohne Ausnahme.',
    turkceDestek: 'her zaman, daima',
    ipa: '/ˈɪmɐ/',
    heceler: 'im-mer',
    ornekler: [
      { de: 'Ich stehe immer früh auf.', tr: 'Her zaman erken kalkarım.' },
      { de: 'Er kommt immer zu spät.', tr: 'O hep geç kalıyor.' },
    ],
    esdizim: ['fast immer', 'immer noch', 'wie immer'],
    zitAnlam: ['nie', 'niemals'],
    aile: ['immer noch'],
    hata: 'Sıklık zarfı özneden hemen SONRA, fiilden sonra gelir: "Ich stehe immer früh auf." Cümle başına konursa fiil öne geçmelidir.',
    hatirlatma: 'Sıklık sırası: immer → oft → manchmal → selten → nie.',
    uretim: {
      yonerge: '"immer" kullanarak bir alışkanlığını yaz.',
      kabul: ['Ich', 'Ich stehe immer'],
    },
  },
  {
    id: 'de-oft',
    dil: 'de',
    kelime: 'oft',
    tur: 'zarf',
    seviye: 'A1',
    almancaTanim: 'Viele Male, aber nicht immer.',
    turkceDestek: 'sık sık',
    ipa: '/ɔft/',
    heceler: 'oft (kısa o)',
    ornekler: [
      { de: 'Ich gehe oft ins Kino.', tr: 'Sık sık sinemaya giderim.' },
      { de: 'Wie oft machst du Sport?', tr: 'Ne sıklıkta spor yapıyorsun?' },
    ],
    esdizim: ['sehr oft', 'nicht oft', 'Wie oft…?'],
    zitAnlam: ['selten'],
    aile: ['öfter'],
    hata: '"Wie oft?" sıklık sorar; "Wie viel?" miktar sorar. Türkçede ikisi de "ne kadar" olabildiği için karışıyor.',
    hatirlatma: 'Karşılaştırması düzensizdir: oft → öfter → am häufigsten.',
    uretim: {
      yonerge: 'Sık yaptığın bir şeyi yaz.',
      kabul: ['Ich', 'Ich gehe oft'],
    },
  },
  {
    id: 'de-manchmal',
    dil: 'de',
    kelime: 'manchmal',
    tur: 'zarf',
    seviye: 'A1',
    almancaTanim: 'Nicht oft und nicht nie; ab und zu.',
    turkceDestek: 'bazen',
    ipa: '/ˈmançmaːl/',
    heceler: 'manch-mal',
    ornekler: [
      { de: 'Manchmal koche ich für meine Familie.', tr: 'Bazen ailem için yemek yapıyorum.' },
      { de: 'Ich bin manchmal müde.', tr: 'Bazen yorgun oluyorum.' },
    ],
    esdizim: ['manchmal auch', 'nur manchmal'],
    esAnlam: ['ab und zu'],
    aile: ['manch'],
    hata: 'Cümle başına gelince fiil hemen arkasından gelir: "Manchmal KOCHE ich…" — Türkçedeki sıra korunmaz.',
    hatirlatma: 'Bu kelime cümle başında en çok kullanılan sıklık zarfıdır; fiil ikinci kuralını pekiştirmek için birebirdir.',
    uretim: {
      yonerge: '"Manchmal" ile başlayan bir cümle yaz (fiili ikinci sıraya koy).',
      kabul: ['Manchmal'],
    },
  },
  {
    id: 'de-nie',
    dil: 'de',
    kelime: 'nie',
    tur: 'zarf',
    seviye: 'A1',
    almancaTanim: 'Zu keiner Zeit, kein einziges Mal.',
    turkceDestek: 'hiçbir zaman, asla',
    ipa: '/niː/',
    heceler: 'nie (ie → uzun "i")',
    ornekler: [
      { de: 'Ich trinke nie Kaffee.', tr: 'Hiç kahve içmem.' },
      { de: 'Er kommt nie zu spät.', tr: 'O asla geç kalmaz.' },
    ],
    esdizim: ['fast nie', 'nie wieder'],
    zitAnlam: ['immer'],
    aile: ['niemals', 'niemand'],
    hata: 'Cümlede zaten olumsuzluk taşır; ayrıca "nicht" eklenmez. "Ich trinke nicht nie Kaffee" yanlıştır.',
    hatirlatma: '"ie" ikilisi uzun "i" okunur: nie → "nii", Liebe → "liibı". "ei" ise "ay" okunur.',
    uretim: {
      yonerge: 'Hiç yapmadığın bir şeyi yaz.',
      kabul: ['Ich', 'Ich trinke nie', 'Ich esse nie'],
    },
  },
  {
    id: 'de-frueh',
    dil: 'de',
    kelime: 'früh',
    tur: 'sıfat',
    seviye: 'A1',
    almancaTanim: 'Am Anfang einer Zeit; vor der üblichen Zeit.',
    turkceDestek: 'erken',
    ipa: '/fʁyː/',
    heceler: 'früh (ü uzun)',
    ornekler: [
      { de: 'Ich stehe früh auf.', tr: 'Erken kalkıyorum.' },
      { de: 'Es ist noch früh.', tr: 'Daha erken.' },
    ],
    esdizim: ['früh aufstehen', 'zu früh', 'früher'],
    zitAnlam: ['spät'],
    aile: ['das Frühstück', 'der Frühling', 'früher'],
    hata: '"ü" sesi Türkçedeki "ü" ile aynıdır — bu Türk öğrencinin AVANTAJIDIR. Çoğu dilde olmayan bu ses sende zaten var.',
    hatirlatma: 'Karşılaştırması "früher" hem "daha erken" hem "eskiden" demektir.',
    uretim: {
      yonerge: 'Erken kalkıp kalkmadığını yaz.',
      kabul: ['Ich stehe früh auf', 'Ich stehe nicht früh auf', 'Ich stehe frueh auf'],
    },
  },
  {
    id: 'de-spaet',
    dil: 'de',
    kelime: 'spät',
    tur: 'sıfat',
    seviye: 'A1',
    almancaTanim: 'Nach der üblichen Zeit; am Ende einer Zeit.',
    turkceDestek: 'geç',
    ipa: '/ʃpɛːt/',
    heceler: 'spät (sp → "şp", ä → geniş "e")',
    ornekler: [
      { de: 'Wie spät ist es?', tr: 'Saat kaç?' },
      { de: 'Ich komme heute spät nach Hause.', tr: 'Bugün eve geç geliyorum.' },
    ],
    esdizim: ['zu spät kommen', 'Wie spät ist es?', 'später'],
    zitAnlam: ['früh'],
    aile: ['später', 'die Verspätung'],
    hata: 'Saati sormanın en yaygın yolu budur: "Wie spät ist es?" Kelime kelime çevrilirse "ne kadar geç" gibi görünür ama anlamı "saat kaç"tır.',
    hatirlatma: '"Geç kalmak" ayrı bir kalıptır: zu spät kommen.',
    uretim: {
      yonerge: 'Birine saati sor.',
      kabul: ['Wie spät ist es', 'Wie spaet ist es', 'Wie viel Uhr ist es'],
    },
  },
]
