/**
 * A1 — ŞEHİR, YOL VE YÖN KELİMELERİ
 * ==================================================================
 *
 * Bu set Dativ'in doğal evidir: "nerede" sorusunun cevabı hep Dativ'dir
 * (in der Stadt, am Bahnhof, neben dem Kino). Bu yüzden örnekler
 * bilinçli olarak yer bildirimiyle kurulmuştur — öğrenci hâl ekini
 * tablodan değil, yol tarif ederken öğrenir.
 */

export const KELIMELER = [
  {
    id: 'de-bahnhof',
    dil: 'de',
    kelime: 'Bahnhof',
    artikel: 'der',
    cogul: 'die Bahnhöfe',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Der Ort, wo die Züge ankommen und abfahren.',
    turkceDestek: 'tren garı, istasyon',
    ipa: '/ˈbaːnhoːf/',
    heceler: 'Bahn-hof (h okunmaz, a uzar)',
    ornekler: [
      { de: 'Entschuldigung, wo ist der Bahnhof?', tr: 'Affedersiniz, tren garı nerede?' },
      { de: 'Wir treffen uns am Bahnhof.', tr: 'Garda buluşuyoruz.' },
    ],
    esdizim: ['am Bahnhof', 'zum Bahnhof gehen', 'der Hauptbahnhof'],
    aile: ['die Bahn', 'der Hauptbahnhof', 'die U-Bahn'],
    hata: '"am Bahnhof" = an dem Bahnhof (Dativ, yer). Hareket varsa "zum Bahnhof" (zu dem) olur. Türkçede ikisi de "gara" ile karşılanır.',
    hatirlatma: 'Ana gar "Hauptbahnhof"tur ve tabelalarda "Hbf" diye kısaltılır.',
    uretim: {
      yonerge: 'Yoldan birine tren garının yerini sor.',
      kabul: ['Entschuldigung, wo ist der Bahnhof', 'Wo ist der Bahnhof'],
    },
  },
  {
    id: 'de-strasse',
    dil: 'de',
    kelime: 'Straße',
    artikel: 'die',
    cogul: 'die Straßen',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Der Weg in der Stadt, auf dem Autos fahren.',
    turkceDestek: 'cadde, sokak',
    ipa: '/ˈʃtʁaːsə/',
    heceler: 'Stra-ße (Str → "ştr", ß → "ss")',
    ornekler: [
      { de: 'Ich wohne in der Goethestraße.', tr: 'Goethe Caddesi’nde oturuyorum.' },
      { de: 'Gehen Sie diese Straße geradeaus.', tr: 'Bu caddeden düz gidin.' },
    ],
    esdizim: ['in der … straße', 'die Straße überqueren'],
    aile: ['die Hauptstraße', 'die Einbahnstraße'],
    hata: 'Adreste cadde adı ve "-straße" BİTİŞİK yazılır: Goethestraße. Ayrıca tabelalarda "Str." diye kısaltılır.',
    bolgesel: { de: 'Straße (ß ile)', ch: 'Strasse (İsviçre ß kullanmaz)' },
    hatirlatma: 'İsviçre Almancasında "ß" harfi hiç kullanılmaz; her zaman "ss" yazılır.',
    uretim: {
      yonerge: 'Hangi caddede oturduğunu yaz.',
      kabul: ['Ich wohne in der'],
    },
  },
  {
    id: 'de-platz',
    dil: 'de',
    kelime: 'Platz',
    artikel: 'der',
    cogul: 'die Plätze',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Eine offene Fläche in der Stadt; auch: ein freier Sitz.',
    turkceDestek: 'meydan; yer, koltuk',
    ipa: '/plats/',
    heceler: 'Platz (tz → "ts")',
    ornekler: [
      { de: 'Der Markt ist auf dem Platz.', tr: 'Pazar meydanda.' },
      { de: 'Ist dieser Platz frei?', tr: 'Bu yer boş mu?' },
    ],
    esdizim: ['der Marktplatz', 'auf dem Platz', 'Platz nehmen'],
    aile: ['der Marktplatz', 'der Parkplatz'],
    hata: 'İki anlamı vardır: şehir meydanı ve oturulacak yer. Bağlam ayırır.',
    hatirlatma: '"Platz nehmen" = oturmak (nazik biçim). Restoranda ve resmî yerlerde bunu duyarsın.',
    uretim: {
      yonerge: 'Bir yerin boş olup olmadığını sor.',
      kabul: ['Ist dieser Platz frei', 'Ist hier frei'],
    },
  },
  {
    id: 'de-park',
    dil: 'de',
    kelime: 'Park',
    artikel: 'der',
    cogul: 'die Parks',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Ein grüner Ort in der Stadt mit Bäumen und Wegen.',
    turkceDestek: 'park',
    ipa: '/paʁk/',
    heceler: 'Park',
    ornekler: [
      { de: 'In der Nähe gibt es einen Park.', tr: 'Yakında bir park var.' },
      { de: 'Wir gehen in den Park.', tr: 'Parka gidiyoruz.' },
    ],
    esdizim: ['in den Park gehen', 'im Park spazieren'],
    aile: ['der Parkplatz', 'parken'],
    hata: '"es gibt" her zaman Akkusativ ister ve Park eril olduğu için "einen Park" olur. En sık yapılan hata "es gibt ein Park"tır.',
    hatirlatma: 'Yabancı kökenli olduğu için çoğulu -s ile yapılır: die Parks.',
    uretim: {
      yonerge: 'Yakınında park olduğunu "es gibt" ile yaz.',
      kabul: ['Es gibt einen Park', 'In der Nähe gibt es einen Park', 'Hier gibt es einen Park'],
    },
  },
  {
    id: 'de-kino',
    dil: 'de',
    kelime: 'Kino',
    artikel: 'das',
    cogul: 'die Kinos',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Der Ort, wo man Filme sieht.',
    turkceDestek: 'sinema',
    ipa: '/ˈkiːno/',
    heceler: 'Ki-no',
    ornekler: [
      { de: 'Wir gehen heute ins Kino.', tr: 'Bugün sinemaya gidiyoruz.' },
      { de: 'Das Kino ist neben der Post.', tr: 'Sinema postanenin yanında.' },
    ],
    esdizim: ['ins Kino gehen', 'im Kino sein'],
    aile: ['der Film', 'der Kinofilm'],
    hata: '"ins Kino" (hareket) ile "im Kino" (bulunma) ayrımı yapılmalı: ins = in das, im = in dem.',
    hatirlatma: 'Bu ikili, Almancadaki hareket/duruş farkını gösteren en kolay örnektir; ezberlemek yerine mantığını kur.',
    uretim: {
      yonerge: 'Sinemaya gittiğini söyleyen bir cümle yaz.',
      kabul: ['Ich gehe ins Kino', 'Wir gehen ins Kino'],
    },
  },
  {
    id: 'de-post',
    dil: 'de',
    kelime: 'Post',
    artikel: 'die',
    cogul: 'çoğulu yok',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Der Ort, wo man Briefe und Pakete abgibt.',
    turkceDestek: 'postane; posta',
    ipa: '/pɔst/',
    heceler: 'Post (kısa o)',
    ornekler: [
      { de: 'Die Post ist gegenüber vom Bahnhof.', tr: 'Postane garın karşısında.' },
      { de: 'Ich gehe zur Post.', tr: 'Postaneye gidiyorum.' },
    ],
    esdizim: ['zur Post gehen', 'bei der Post'],
    aile: ['die Postleitzahl', 'der Briefkasten'],
    hata: 'Dişil olduğu için "zur Post" (zu der) olur; "zum Post" yanlıştır.',
    hatirlatma: '"Postleitzahl" (PLZ) posta kodudur ve adres yazarken şehirden ÖNCE gelir.',
    uretim: {
      yonerge: 'Postaneye gittiğini yaz.',
      kabul: ['Ich gehe zur Post'],
    },
  },
  {
    id: 'de-bus',
    dil: 'de',
    kelime: 'Bus',
    artikel: 'der',
    cogul: 'die Busse',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Ein großes Fahrzeug für viele Personen.',
    turkceDestek: 'otobüs',
    ipa: '/bʊs/',
    heceler: 'Bus (kısa u)',
    ornekler: [
      { de: 'Ich fahre mit dem Bus.', tr: 'Otobüsle gidiyorum.' },
      { de: 'Der Bus kommt in fünf Minuten.', tr: 'Otobüs beş dakikaya geliyor.' },
    ],
    esdizim: ['mit dem Bus fahren', 'die Bushaltestelle'],
    aile: ['die Bushaltestelle', 'der Busfahrer'],
    hata: 'Taşıtla gitmek "mit dem Bus" kalıbıyla söylenir ve "mit" Dativ ister. "in dem Bus" yer bildirir, "mit dem Bus" yolculuk.',
    hatirlatma: 'Çoğulda "s" ikilenir: Bus → Busse.',
    uretim: {
      yonerge: 'Otobüsle bir yere gittiğini yaz.',
      kabul: ['Ich fahre mit dem Bus'],
    },
  },
  {
    id: 'de-haltestelle',
    dil: 'de',
    kelime: 'Haltestelle',
    artikel: 'die',
    cogul: 'die Haltestellen',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Der Ort, wo der Bus oder die Bahn hält.',
    turkceDestek: 'durak',
    ipa: '/ˈhaltəˌʃtɛlə/',
    heceler: 'Hal-te-stel-le',
    ornekler: [
      { de: 'Die Haltestelle ist dort drüben.', tr: 'Durak şurada.' },
      { de: 'Steigen Sie an der nächsten Haltestelle aus.', tr: 'Bir sonraki durakta inin.' },
    ],
    esdizim: ['an der Haltestelle', 'die nächste Haltestelle'],
    aile: ['halten', 'die Bushaltestelle'],
    hata: '"an der Haltestelle" (Dativ) doğrudur; "in der Haltestelle" denmez — durak kapalı bir mekân değildir.',
    hatirlatma: 'İnmek "aussteigen", binmek "einsteigen", aktarma yapmak "umsteigen" — üçü de ayrılabilen fiildir.',
    uretim: {
      yonerge: 'Durağın nerede olduğunu sor.',
      kabul: ['Wo ist die Haltestelle', 'Wo ist die nächste Haltestelle'],
    },
  },
  {
    id: 'de-weg',
    dil: 'de',
    kelime: 'Weg',
    artikel: 'der',
    cogul: 'die Wege',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Die Strecke, die man geht oder fährt.',
    turkceDestek: 'yol',
    ipa: '/veːk/',
    heceler: 'Weg (W → "v", sondaki g → "k")',
    ornekler: [
      { de: 'Können Sie mir den Weg zeigen?', tr: 'Bana yolu gösterebilir misiniz?' },
      { de: 'Der Weg ist nicht weit.', tr: 'Yol uzak değil.' },
    ],
    esdizim: ['nach dem Weg fragen', 'der kürzeste Weg', 'auf dem Weg'],
    aile: ['unterwegs', 'der Fußweg'],
    hata: 'Büyük harfle "der Weg" = yol; küçük harfle "weg" = uzakta/gitmiş. Yazımdaki fark anlamı tamamen değiştirir.',
    hatirlatma: 'Yol sormanın kalıbı: "Entschuldigung, wie komme ich zum/zur …?"',
    uretim: {
      yonerge: 'Birinden yolu göstermesini nazikçe iste.',
      kabul: ['Können Sie mir den Weg zeigen', 'Kannst du mir den Weg zeigen'],
    },
  },
  {
    id: 'de-links',
    dil: 'de',
    kelime: 'links',
    tur: 'zarf',
    seviye: 'A1',
    almancaTanim: 'Auf der Seite, wo bei den meisten Menschen das Herz ist.',
    turkceDestek: 'solda, sola',
    ipa: '/lɪŋks/',
    heceler: 'links',
    ornekler: [
      { de: 'Gehen Sie hier links.', tr: 'Buradan sola gidin.' },
      { de: 'Die Bank ist links von der Post.', tr: 'Banka postanenin solunda.' },
    ],
    esdizim: ['nach links', 'links abbiegen', 'links von'],
    zitAnlam: ['rechts'],
    aile: ['linke', 'nach links'],
    hata: 'Dönüş için "nach links abbiegen" kullanılır; sadece "links gehen" de yaygındır. "zu links" diye bir kalıp yoktur.',
    hatirlatma: 'Yol tarifinde en çok duyacağın üç kelime: links, rechts, geradeaus.',
    uretim: {
      yonerge: 'Birine sola dönmesini söyle (nazik biçim).',
      kabul: ['Gehen Sie links', 'Gehen Sie nach links', 'Biegen Sie links ab'],
    },
  },
  {
    id: 'de-rechts',
    dil: 'de',
    kelime: 'rechts',
    tur: 'zarf',
    seviye: 'A1',
    almancaTanim: 'Die Seite gegenüber von links.',
    turkceDestek: 'sağda, sağa',
    ipa: '/ʁɛçts/',
    heceler: 'rechts (chts → "çts")',
    ornekler: [
      { de: 'Biegen Sie rechts ab.', tr: 'Sağa dönün.' },
      { de: 'Rechts sehen Sie die Kirche.', tr: 'Sağda kiliseyi göreceksiniz.' },
    ],
    esdizim: ['nach rechts', 'rechts abbiegen', 'rechts von'],
    zitAnlam: ['links'],
    aile: ['die rechte Seite'],
    hata: '"rechts" (sağda) ile "richtig" (doğru) karıştırılır. İkisi de "doğru/sağ" ile ilgili görünür ama farklı kelimelerdir.',
    hatirlatma: '"abbiegen" ayrılabilen fiildir: "Biegen Sie rechts AB" — ön ek sona gider.',
    uretim: {
      yonerge: 'Birine sağa dönmesini söyle.',
      kabul: ['Biegen Sie rechts ab', 'Gehen Sie rechts', 'Gehen Sie nach rechts'],
    },
  },
  {
    id: 'de-geradeaus',
    dil: 'de',
    kelime: 'geradeaus',
    tur: 'zarf',
    seviye: 'A1',
    almancaTanim: 'Immer weiter nach vorne, ohne abzubiegen.',
    turkceDestek: 'dosdoğru, düz',
    ipa: '/ɡəˈʁaːdəˈʔaʊ̯s/',
    heceler: 'ge-ra-de-aus',
    ornekler: [
      { de: 'Gehen Sie geradeaus bis zur Ampel.', tr: 'Trafik ışığına kadar düz gidin.' },
      { de: 'Immer geradeaus, dann links.', tr: 'Hep düz, sonra sola.' },
    ],
    esdizim: ['immer geradeaus', 'geradeaus gehen'],
    aile: ['gerade'],
    hata: 'Tek kelime olarak bitişik yazılır: geradeaus (gerade aus değil).',
    hatirlatma: '"bis zur Ampel" (ışığa kadar) kalıbında "bis zu" Dativ ister.',
    uretim: {
      yonerge: 'Birine düz gitmesini söyle.',
      kabul: ['Gehen Sie geradeaus', 'Geh geradeaus', 'Immer geradeaus'],
    },
  },
  {
    id: 'de-neben',
    dil: 'de',
    kelime: 'neben',
    tur: 'edat',
    seviye: 'A1',
    almancaTanim: 'An der Seite von etwas.',
    turkceDestek: 'yanında, yanına',
    ipa: '/ˈneːbn̩/',
    heceler: 'ne-ben',
    ornekler: [
      { de: 'Die Apotheke ist neben dem Supermarkt.', tr: 'Eczane süpermarketin yanında.' },
      { de: 'Setz dich neben mich!', tr: 'Yanıma otur!' },
    ],
    esdizim: ['neben dem/der', 'direkt neben'],
    aile: ['nebenan', 'der Nachbar'],
    hata: 'Yer bildirirken Dativ (neben dem Supermarkt), hareket bildirirken Akkusativ (neben den Tisch) alır. Bu, Wechselpräposition denen edat grubudur.',
    hatirlatma: '"Wo?" sorusu → Dativ; "Wohin?" sorusu → Akkusativ. Bu tek soru, dokuz edatın hepsini çözer.',
    uretim: {
      yonerge: 'Bir yerin neyin yanında olduğunu yaz.',
      kabul: ['ist neben dem', 'ist neben der'],
    },
  },
  {
    id: 'de-zwischen',
    dil: 'de',
    kelime: 'zwischen',
    tur: 'edat',
    seviye: 'A1',
    almancaTanim: 'In der Mitte von zwei Dingen.',
    turkceDestek: 'arasında',
    ipa: '/ˈtsvɪʃn̩/',
    heceler: 'zwi-schen (zw → "tsv")',
    ornekler: [
      { de: 'Die Bank ist zwischen der Post und dem Kino.', tr: 'Banka postane ile sinemanın arasında.' },
      { de: 'Ich sitze zwischen meinen Freunden.', tr: 'Arkadaşlarımın arasında oturuyorum.' },
    ],
    esdizim: ['zwischen … und …', 'mitten zwischen'],
    aile: ['dazwischen', 'inzwischen'],
    hata: 'İki isim de aynı hâle girer: "zwischen DER Post und DEM Kino" — her ikisi de Dativ.',
    hatirlatma: '"zw" ikilisi "tsv" okunur: zwischen → "tsvişen", zwei → "tsvay".',
    uretim: {
      yonerge: 'Bir yerin iki şey arasında olduğunu yaz.',
      kabul: ['zwischen dem', 'zwischen der', 'ist zwischen'],
    },
  },
  {
    id: 'de-gegenueber',
    dil: 'de',
    kelime: 'gegenüber',
    tur: 'edat',
    seviye: 'A1',
    almancaTanim: 'Auf der anderen Seite von etwas.',
    turkceDestek: 'karşısında',
    ipa: '/ɡeːɡn̩ˈʔyːbɐ/',
    heceler: 'ge-gen-ü-ber (vurgu: Ü)',
    ornekler: [
      { de: 'Die Schule ist gegenüber vom Park.', tr: 'Okul parkın karşısında.' },
      { de: 'Gegenüber dem Bahnhof gibt es ein Café.', tr: 'Garın karşısında bir kafe var.' },
    ],
    esdizim: ['gegenüber vom', 'direkt gegenüber'],
    aile: ['gegen', 'über'],
    hata: 'Her zaman Dativ ister. Günlük dilde "gegenüber von + Dativ" biçimi daha yaygındır.',
    hatirlatma: 'Yol tarifinde en çok kullanılan konum kelimelerinden biridir; "gegenüber vom" kalıbını olduğu gibi ezberle.',
    uretim: {
      yonerge: 'Bir yerin neyin karşısında olduğunu yaz.',
      kabul: ['gegenüber vom', 'gegenüber von der', 'ist gegenüber'],
    },
  },
  {
    id: 'de-naehe',
    dil: 'de',
    kelime: 'Nähe',
    artikel: 'die',
    cogul: 'çoğulu yok',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Der Bereich, der nicht weit weg ist.',
    turkceDestek: 'yakın (yakınlık)',
    ipa: '/ˈnɛːə/',
    heceler: 'Nä-he (h okunmaz)',
    ornekler: [
      { de: 'In der Nähe gibt es eine Apotheke.', tr: 'Yakında bir eczane var.' },
      { de: 'Wohnst du hier in der Nähe?', tr: 'Buralarda mı oturuyorsun?' },
    ],
    esdizim: ['in der Nähe', 'ganz in der Nähe', 'in der Nähe von'],
    zitAnlam: ['die Ferne'],
    aile: ['nah', 'näher'],
    hata: 'Kalıp olarak ezberlenmeli: "in der Nähe" — artikel her zaman "der"dir (Dativ, dişil).',
    hatirlatma: 'Bir şeyin yakınında olduğunu söylemek için: "in der Nähe von + Dativ".',
    uretim: {
      yonerge: 'Yakınında ne olduğunu "in der Nähe" ile yaz.',
      kabul: ['In der Nähe gibt es', 'In der Naehe gibt es'],
    },
  },
  {
    id: 'de-weit',
    dil: 'de',
    kelime: 'weit',
    tur: 'sıfat',
    seviye: 'A1',
    almancaTanim: 'Eine große Entfernung von hier.',
    turkceDestek: 'uzak',
    ipa: '/vaɪ̯t/',
    heceler: 'weit (W → "v", ei → "ay")',
    ornekler: [
      { de: 'Ist es weit von hier?', tr: 'Buradan uzak mı?' },
      { de: 'Nein, das ist nicht weit.', tr: 'Hayır, uzak değil.' },
    ],
    esdizim: ['zu weit', 'nicht weit von hier', 'wie weit'],
    zitAnlam: ['nah'],
    aile: ['die Weite', 'weiter'],
    hata: 'Sıfat olduğu için "nicht" ile olumsuzlanır: "nicht weit" (kein weit değil).',
    hatirlatma: 'Yol sorduktan sonra en çok kullanacağın kontrol sorusu: "Ist es weit?"',
    uretim: {
      yonerge: 'Bir yerin uzak olup olmadığını sor.',
      kabul: ['Ist es weit', 'Ist es weit von hier'],
    },
  },
  {
    id: 'de-hier',
    dil: 'de',
    kelime: 'hier',
    tur: 'zarf',
    seviye: 'A1',
    almancaTanim: 'An diesem Ort, wo ich bin.',
    turkceDestek: 'burada',
    ipa: '/hiːɐ̯/',
    heceler: 'hier (ie → uzun "i")',
    ornekler: [
      { de: 'Hier ist meine Schule.', tr: 'İşte okulum burada.' },
      { de: 'Ich warte hier auf dich.', tr: 'Seni burada bekliyorum.' },
    ],
    esdizim: ['hier ist', 'hier in der Nähe', 'von hier'],
    zitAnlam: ['dort'],
    aile: ['hierher', 'hierhin'],
    hata: 'Cümle başına gelince fiil hemen arkasından gelir: "Hier IST meine Schule." Fiil ikinci kuralı burada da işler.',
    hatirlatma: '"hier" duruş, "hierher" ise buraya doğru hareket bildirir.',
    uretim: {
      yonerge: '"Hier" ile başlayan bir cümle yaz (fiil ikinci sırada!).',
      kabul: ['Hier ist', 'Hier gibt es'],
    },
  },
  {
    id: 'de-fahrrad',
    dil: 'de',
    kelime: 'Fahrrad',
    artikel: 'das',
    cogul: 'die Fahrräder',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Ein Fahrzeug mit zwei Rädern, das man mit den Beinen fährt.',
    turkceDestek: 'bisiklet',
    ipa: '/ˈfaːɐ̯ˌʁaːt/',
    heceler: 'Fahr-rad (çift r, sondaki d → "t")',
    ornekler: [
      { de: 'Ich fahre mit dem Fahrrad zur Schule.', tr: 'Okula bisikletle gidiyorum.' },
      { de: 'Mein Fahrrad ist kaputt.', tr: 'Bisikletim bozuk.' },
    ],
    esdizim: ['Fahrrad fahren', 'mit dem Fahrrad'],
    aile: ['fahren', 'das Rad'],
    bolgesel: { de: 'das Fahrrad / das Rad', at: 'das Radl', ch: 'das Velo' },
    hata: 'İsviçre\'de bisiklete "Velo" denir ve "Fahrrad" pek kullanılmaz. Bu, üç ülke arasındaki en bilinen kelime farklarından biridir.',
    hatirlatma: 'Birleşik yazımda iki "r" yan yana gelir ve ikisi de yazılır: Fahr + Rad = Fahrrad.',
    uretim: {
      yonerge: 'Bisikletle bir yere gittiğini yaz.',
      kabul: ['Ich fahre mit dem Fahrrad'],
    },
  },
  {
    id: 'de-apotheke',
    dil: 'de',
    kelime: 'Apotheke',
    artikel: 'die',
    cogul: 'die Apotheken',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Das Geschäft, wo man Medikamente bekommt.',
    turkceDestek: 'eczane',
    ipa: '/apoˈteːkə/',
    heceler: 'A-po-the-ke (th → tek "t", vurgu: THE)',
    ornekler: [
      { de: 'Wo ist die nächste Apotheke?', tr: 'En yakın eczane nerede?' },
      { de: 'Die Apotheke ist bis 18 Uhr offen.', tr: 'Eczane akşam altıya kadar açık.' },
    ],
    esdizim: ['die nächste Apotheke', 'in die Apotheke gehen'],
    aile: ['der Apotheker', 'das Medikament'],
    hata: 'Almanya\'da ağrı kesici bile yalnız eczaneden alınır; süpermarkette satılmaz. "Drogerie" ise kozmetik ve temizlik ürünü satar, ilaç satmaz.',
    hatirlatma: '"die nächste" burada "en yakın" demektir; "bir sonraki" anlamı da vardır ve bağlam ayırır.',
    uretim: {
      yonerge: 'En yakın eczanenin yerini sor.',
      kabul: ['Wo ist die nächste Apotheke', 'Wo ist die naechste Apotheke', 'Wo ist eine Apotheke'],
    },
  },
  {
    id: 'de-links-rechts-ampel',
    dil: 'de',
    kelime: 'Ampel',
    artikel: 'die',
    cogul: 'die Ampeln',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Das Licht an der Straße: rot, gelb, grün.',
    turkceDestek: 'trafik ışığı',
    ipa: '/ˈampl̩/',
    heceler: 'Am-pel',
    ornekler: [
      { de: 'An der Ampel gehen Sie rechts.', tr: 'Işıkta sağa gidin.' },
      { de: 'Die Ampel ist rot.', tr: 'Işık kırmızı.' },
    ],
    esdizim: ['an der Ampel', 'bis zur Ampel'],
    aile: ['die Verkehrsampel'],
    hata: 'Yol tarifinde referans noktası olarak çok kullanılır: "bis zur Ampel" (ışığa kadar), "an der Ampel" (ışıkta).',
    hatirlatma: 'Almanya\'da yayalar kırmızı ışıkta beklemeye çok dikkat eder; bu bir kültür farkıdır.',
    uretim: {
      yonerge: 'Işığa kadar gitmesini söyleyen bir tarif yaz.',
      kabul: ['Gehen Sie bis zur Ampel', 'Geh bis zur Ampel'],
    },
  },
  {
    id: 'de-wohin',
    dil: 'de',
    kelime: 'wohin',
    tur: 'soru sözcüğü',
    seviye: 'A1',
    almancaTanim: 'Fragewort nach dem Ziel einer Bewegung.',
    turkceDestek: 'nereye',
    ipa: '/voˈhɪn/',
    heceler: 'wo-hin (vurgu: HIN)',
    ornekler: [
      { de: 'Wohin gehst du?', tr: 'Nereye gidiyorsun?' },
      { de: 'Wohin fahrt ihr im Sommer?', tr: 'Yazın nereye gidiyorsunuz?' },
    ],
    esdizim: ['Wohin gehst du?', 'Wohin fährst du?'],
    aile: ['wo', 'woher', 'hin'],
    hata: 'Üçlüyü ayırmak şart: wo = nerede, wohin = nereye, woher = nereden. Türkçede tek kökün üç ekidir; Almancada üç ayrı kelimedir.',
    hatirlatma: 'wohin sorusunun cevabı hareket bildirir ve Akkusativ ya da nach/zu alır.',
    uretim: {
      yonerge: 'Birine nereye gittiğini sor.',
      kabul: ['Wohin gehst du', 'Wohin fährst du'],
    },
  },
]
