/**
 * A1 — TANIŞMA KELİMELERİ
 * ==================================================================
 *
 * Bir kelimeyi "bilmek" burada dört şey demektir: anlamını bilmek,
 * bağlamda tanımak, doğru biçimde yazmak, kendi cümlende kullanmak.
 * Bu yüzden her kayıtta tanım, örnek, eşdizim ve üretim görevi var.
 *
 * ALMANCAYA ÖZGÜ ZORUNLULUK: her isimde `artikel` ve `cogul` alanı
 * doldurulmuştur. Artikelsiz öğrenilen isim yarım öğrenilmiş isimdir —
 * öğrenci onu hiçbir cümlede doğru kullanamaz. Fiillerde kök ünlüsü
 * değişiyorsa `cekim` alanında 3. tekil biçim verilir.
 *
 * `hata` alanı Türk öğrencilerin o kelimede yaptığı EN SIK hatadır;
 * uydurulmamış, ders veren öğretmenin gördüğü hatalardır.
 */

export const KELIMELER = [
  {
    id: 'de-name',
    dil: 'de',
    kelime: 'Name',
    artikel: 'der',
    cogul: 'die Namen',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Das Wort, mit dem man eine Person ruft.',
    turkceDestek: 'ad, isim',
    ipa: '/ˈnaːmə/',
    heceler: 'Na-me (vurgu: NA)',
    ornekler: [
      { de: 'Mein Name ist Elif.', tr: 'Benim adım Elif.' },
      { de: 'Wie ist Ihr Name, bitte?', tr: 'Adınız nedir, lütfen?' },
    ],
    esdizim: ['mein Name ist', 'Wie ist Ihr Name?', 'der Vorname', 'der Nachname'],
    aile: ['der Vorname', 'der Nachname', 'namens'],
    hata: '"Was ist dein Name?" dilbilgisi olarak yanlış değil ama Almancada doğal soru "Wie heißt du?" ya da "Wie ist dein Name?" biçimindedir — "Was" değil "Wie".',
    hatirlatma: 'Türkçedeki "nam" (ün, ad) kelimesiyle aynı kökten gelir.',
    uretim: {
      yonerge: 'Kendi adını "Mein Name ist…" kalıbıyla yaz.',
      kabul: ['Mein Name ist', 'Mein Name ist '],
    },
  },
  {
    id: 'de-heissen',
    dil: 'de',
    kelime: 'heißen',
    cekim: 'heißt · hieß · hat geheißen',
    tur: 'fiil',
    seviye: 'A1',
    almancaTanim: 'Einen bestimmten Namen haben.',
    turkceDestek: 'adı … olmak, … diye adlandırılmak',
    ipa: '/ˈhaɪ̯sn̩/',
    heceler: 'hei-ßen (ei → "ay" okunur)',
    ornekler: [
      { de: 'Ich heiße Mert. Und du?', tr: 'Benim adım Mert. Ya senin?' },
      { de: 'Wie heißt deine Schwester?', tr: 'Kız kardeşinin adı ne?' },
    ],
    esdizim: ['Wie heißt du?', 'Ich heiße…', 'Wie heißen Sie?'],
    aile: ['der Name'],
    hata: 'Türkçede "adım Mert" derken fiil yoktur; bu yüzden öğrenci "Ich Mert" ya da "Mein Name Mert" yazar. Almancada mutlaka bir fiil olmalı: heiße ya da ist.',
    hatirlatma: '"ß" iki "s" demektir: heißen = heissen. İkisi de doğrudur (İsviçre hep "ss" yazar).',
    uretim: {
      yonerge: '"Adım …" cümlesini heißen fiiliyle yaz.',
      kabul: ['Ich heiße', 'Ich heisse'],
    },
  },
  {
    id: 'de-kommen',
    dil: 'de',
    kelime: 'kommen',
    cekim: 'kommt · kam · ist gekommen',
    tur: 'fiil',
    seviye: 'A1',
    almancaTanim: 'Sich zu einem Ort bewegen; von einem Ort stammen.',
    turkceDestek: 'gelmek; (aus ile) …lı olmak',
    ipa: '/ˈkɔmən/',
    heceler: 'kom-men (kısa o)',
    ornekler: [
      { de: 'Ich komme aus der Türkei.', tr: 'Türkiyeliyim. / Türkiye’den geliyorum.' },
      { de: 'Woher kommst du?', tr: 'Nerelisin?' },
    ],
    esdizim: ['aus … kommen', 'nach Hause kommen', 'zu spät kommen'],
    aile: ['ankommen', 'mitkommen', 'die Ankunft'],
    hata: 'Ülke adının artikeli varsa "aus der Türkei / aus dem Iran" denir; artikelsiz ülkelerde ise sadece "aus Deutschland". Öğrenci hepsine aynı kalıbı uygular.',
    hatirlatma: 'Perfekt’i "sein" ile kurulur: Ich bin gekommen — çünkü yer değiştirme bildirir.',
    uretim: {
      yonerge: 'Nereli olduğunu "Ich komme aus…" ile yaz.',
      kabul: ['Ich komme aus', 'Ich komme aus der Türkei'],
    },
  },
  {
    id: 'de-wohnen',
    dil: 'de',
    kelime: 'wohnen',
    cekim: 'wohnt · wohnte · hat gewohnt',
    tur: 'fiil',
    seviye: 'A1',
    almancaTanim: 'An einem Ort leben, seine Wohnung haben.',
    turkceDestek: 'oturmak, ikamet etmek',
    ipa: '/ˈvoːnən/',
    heceler: 'woh-nen (w → "v" okunur)',
    ornekler: [
      { de: 'Ich wohne in Ankara.', tr: 'Ankara’da oturuyorum.' },
      { de: 'Wo wohnst du genau?', tr: 'Tam olarak nerede oturuyorsun?' },
    ],
    esdizim: ['in … wohnen', 'bei den Eltern wohnen', 'allein wohnen'],
    aile: ['die Wohnung', 'der Wohnort', 'die Einwohner'],
    hata: '"wohnen" ile "leben" karışır: wohnen bir adresi, leben ise yaşamı anlatır. "Ich lebe in Ankara" da doğrudur ama adres sorulduğunda wohnen kullanılır.',
    hatirlatma: 'w harfi Almancada her zaman "v" okunur: wohnen → "vonın".',
    uretim: {
      yonerge: 'Nerede oturduğunu yaz.',
      kabul: ['Ich wohne in'],
    },
  },
  {
    id: 'de-stadt',
    dil: 'de',
    kelime: 'Stadt',
    artikel: 'die',
    cogul: 'die Städte',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Ein großer Ort mit vielen Häusern und Menschen.',
    turkceDestek: 'şehir, kent',
    ipa: '/ʃtat/',
    heceler: 'Stadt (St- → "şt" okunur)',
    ornekler: [
      { de: 'Istanbul ist eine große Stadt.', tr: 'İstanbul büyük bir şehir.' },
      { de: 'In welcher Stadt wohnst du?', tr: 'Hangi şehirde oturuyorsun?' },
    ],
    esdizim: ['in die Stadt gehen', 'eine große Stadt', 'die Stadtmitte'],
    aile: ['die Innenstadt', 'das Stadtzentrum', 'städtisch'],
    hata: 'Çoğulu "Stadts" değil "Städte"dir; umlaut eklenir. Ayrıca "Staat" (devlet) ile karıştırılır — Stadt = şehir, Staat = devlet.',
    hatirlatma: 'Kelime başındaki "st" her zaman "şt" okunur: Stadt → "ştat".',
    uretim: {
      yonerge: 'Yaşadığın şehri "Meine Stadt heißt…" ile tanıt.',
      kabul: ['Meine Stadt heißt', 'Meine Stadt heisst', 'Meine Stadt ist'],
    },
  },
  {
    id: 'de-land',
    dil: 'de',
    kelime: 'Land',
    artikel: 'das',
    cogul: 'die Länder',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Ein Gebiet mit eigener Regierung, zum Beispiel Deutschland.',
    turkceDestek: 'ülke; kırsal bölge',
    ipa: '/lant/',
    heceler: 'Land (sondaki d → "t" okunur)',
    ornekler: [
      { de: 'Deutschland ist ein schönes Land.', tr: 'Almanya güzel bir ülke.' },
      { de: 'Aus welchem Land kommst du?', tr: 'Hangi ülkeden geliyorsun?' },
    ],
    esdizim: ['auf dem Land', 'das Heimatland', 'das Nachbarland'],
    aile: ['die Landschaft', 'der Landsmann', 'ausländisch'],
    hata: 'Sondaki "d" Almancada sert okunur ("lant"). Öğrenci "land" diye yumuşak söyleyince kelime anlaşılmaz hâle gelmez ama aksan hemen belli olur.',
    hatirlatma: '"auf dem Land" = kırsalda; "in dem Land" = o ülkede. İki farklı anlam, iki farklı edat.',
    uretim: {
      yonerge: 'Ülkeni "Mein Land ist…" ile yaz.',
      kabul: ['Mein Land ist'],
    },
  },
  {
    id: 'de-sprache',
    dil: 'de',
    kelime: 'Sprache',
    artikel: 'die',
    cogul: 'die Sprachen',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Das System aus Wörtern, mit dem Menschen sprechen.',
    turkceDestek: 'dil (konuşulan dil)',
    ipa: '/ˈʃpʁaːxə/',
    heceler: 'Spra-che (Sp- → "şp", ch → gırtlaktan "h")',
    ornekler: [
      { de: 'Deutsch ist eine schöne Sprache.', tr: 'Almanca güzel bir dil.' },
      { de: 'Wie viele Sprachen sprichst du?', tr: 'Kaç dil konuşuyorsun?' },
    ],
    esdizim: ['eine Sprache lernen', 'die Muttersprache', 'die Fremdsprache'],
    aile: ['sprechen', 'das Gespräch', 'sprachlos'],
    hata: 'Dil adları artikelsiz ve büyük harfle yazılır: "Ich spreche Türkisch" (die Türkisch değil).',
    hatirlatma: 'Kelime başındaki "sp" her zaman "şp" okunur: Sprache → "şpraahı".',
    uretim: {
      yonerge: 'Konuştuğun dilleri bir cümlede yaz.',
      kabul: ['Ich spreche'],
    },
  },
  {
    id: 'de-sprechen',
    dil: 'de',
    kelime: 'sprechen',
    cekim: 'spricht · sprach · hat gesprochen',
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    almancaTanim: 'Wörter mit dem Mund sagen; eine Sprache können.',
    turkceDestek: 'konuşmak',
    ipa: '/ˈʃpʁɛçn̩/',
    heceler: 'spre-chen',
    ornekler: [
      { de: 'Sprichst du Deutsch?', tr: 'Almanca konuşuyor musun?' },
      { de: 'Er spricht sehr schnell.', tr: 'O çok hızlı konuşuyor.' },
    ],
    esdizim: ['Deutsch sprechen', 'mit jemandem sprechen', 'über etwas sprechen'],
    aile: ['die Sprache', 'das Gespräch', 'der Sprecher'],
    hata: 'Kök ünlüsü 2. ve 3. tekilde değişir: du sprichst, er spricht (du sprechst DEĞİL).',
    hatirlatma: 'Kiminle konuştuğunu "mit" ile, ne hakkında konuştuğunu "über" ile söylersin.',
    uretim: {
      yonerge: '"Türkçe ve biraz Almanca konuşuyorum." cümlesini yaz.',
      kabul: [
        'Ich spreche Türkisch und ein bisschen Deutsch',
        'Ich spreche Tuerkisch und ein bisschen Deutsch',
      ],
    },
  },
  {
    id: 'de-freund',
    dil: 'de',
    kelime: 'Freund',
    artikel: 'der',
    cogul: 'die Freunde',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Eine Person, die man gut kennt und mag.',
    turkceDestek: 'arkadaş (erkek); erkek sevgili',
    ipa: '/fʁɔɪ̯nt/',
    heceler: 'Freund (eu → "oy" okunur)',
    ornekler: [
      { de: 'Mein Freund heißt Emre.', tr: 'Arkadaşımın adı Emre.' },
      { de: 'Ich treffe meine Freunde am Wochenende.', tr: 'Hafta sonu arkadaşlarımla buluşuyorum.' },
    ],
    esdizim: ['ein guter Freund', 'Freunde treffen', 'mit Freunden'],
    esAnlam: ['der Kumpel (gündelik)'],
    aile: ['die Freundin', 'freundlich', 'die Freundschaft'],
    hata: '"mein Freund" bağlama göre "erkek sevgilim" anlamına da gelir. Sadece arkadaş demek için "ein Freund von mir" denir.',
    kayit: 'gundelik',
    hatirlatma: 'eu ikilisi Almancada her zaman "oy" okunur: Freund → "froynt".',
    uretim: {
      yonerge: 'En yakın arkadaşını tanıtan bir cümle yaz.',
      kabul: ['Mein Freund heißt', 'Meine Freundin heißt', 'Mein bester Freund heißt'],
    },
  },
  {
    id: 'de-beruf',
    dil: 'de',
    kelime: 'Beruf',
    artikel: 'der',
    cogul: 'die Berufe',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Die Arbeit, die man gelernt hat und macht.',
    turkceDestek: 'meslek',
    ipa: '/bəˈʁuːf/',
    heceler: 'Be-ruf (vurgu: RUF)',
    ornekler: [
      { de: 'Was sind Sie von Beruf?', tr: 'Mesleğiniz nedir?' },
      { de: 'Mein Vater ist Lehrer von Beruf.', tr: 'Babam meslekten öğretmen.' },
    ],
    esdizim: ['von Beruf sein', 'einen Beruf lernen', 'der Traumberuf'],
    aile: ['beruflich', 'die Berufsschule'],
    hata: 'Meslek söylenirken artikel KULLANILMAZ: "Ich bin Lehrer" (Ich bin ein Lehrer değil). Bu, İngilizceden gelen bir alışkanlıktır.',
    hatirlatma: 'Vurgu ikinci hecededir: be-RUF.',
    uretim: {
      yonerge: 'Anne ya da babanın mesleğini bir cümlede yaz.',
      kabul: ['Mein Vater ist', 'Meine Mutter ist'],
    },
  },
  {
    id: 'de-schueler',
    dil: 'de',
    kelime: 'Schüler',
    artikel: 'der',
    cogul: 'die Schüler',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Ein Kind oder Jugendlicher, der zur Schule geht.',
    turkceDestek: 'öğrenci (okul öğrencisi)',
    ipa: '/ˈʃyːlɐ/',
    heceler: 'Schü-ler (sch → tek "ş" sesi)',
    ornekler: [
      { de: 'Ich bin Schüler in der neunten Klasse.', tr: 'Dokuzuncu sınıf öğrencisiyim.' },
      { de: 'Die Schüler warten vor der Tür.', tr: 'Öğrenciler kapının önünde bekliyor.' },
    ],
    esdizim: ['ein guter Schüler', 'die Schülerin', 'der Austauschschüler'],
    aile: ['die Schule', 'die Schülerin'],
    hata: 'Üniversite öğrencisi "Student"tır, "Schüler" değil. Kız öğrenci için "Schülerin" kullanılır.',
    hatirlatma: 'Çoğulu tekiliyle AYNIDIR: der Schüler → die Schüler. Farkı artikel gösterir.',
    uretim: {
      yonerge: 'Kaçıncı sınıf öğrencisi olduğunu yaz.',
      kabul: ['Ich bin Schüler', 'Ich bin Schülerin', 'Ich bin Schueler', 'Ich bin Schuelerin'],
    },
  },
  {
    id: 'de-lehrer',
    dil: 'de',
    kelime: 'Lehrer',
    artikel: 'der',
    cogul: 'die Lehrer',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Eine Person, die in der Schule unterrichtet.',
    turkceDestek: 'öğretmen (erkek)',
    ipa: '/ˈleːʁɐ/',
    heceler: 'Leh-rer (h okunmaz, önceki ünlüyü uzatır)',
    ornekler: [
      { de: 'Unser Lehrer ist sehr nett.', tr: 'Öğretmenimiz çok kibar.' },
      { de: 'Frau Yılmaz ist meine Lehrerin.', tr: 'Yılmaz Hanım benim öğretmenim.' },
    ],
    esdizim: ['der Deutschlehrer', 'die Lehrerin', 'der Klassenlehrer'],
    aile: ['lehren', 'die Lehre', 'die Lehrerin'],
    hata: 'Kadın öğretmene "Lehrer" denmez, "Lehrerin" denir. Almancada meslek adlarının dişil biçimi -in ekiyle kurulur.',
    hatirlatma: 'Kelime içindeki "h" okunmaz, sadece önündeki ünlüyü uzatır: Leh-rer → "leeeraa".',
    uretim: {
      yonerge: 'Sevdiğin bir öğretmenini tanıtan cümle yaz.',
      kabul: ['Mein Lehrer', 'Meine Lehrerin'],
    },
  },
  {
    id: 'de-buchstabieren',
    dil: 'de',
    kelime: 'buchstabieren',
    cekim: 'buchstabiert · buchstabierte · hat buchstabiert',
    tur: 'fiil',
    seviye: 'A1',
    almancaTanim: 'Ein Wort Buchstabe für Buchstabe sagen.',
    turkceDestek: 'harf harf söylemek, hecelemek',
    ipa: '/ˌbuːxʃtaˈbiːʁən/',
    heceler: 'buch-sta-bie-ren (vurgu: BIE)',
    ornekler: [
      { de: 'Können Sie das bitte buchstabieren?', tr: 'Bunu harf harf söyleyebilir misiniz?' },
      { de: 'Ich buchstabiere meinen Namen: Y-A-Z.', tr: 'Adımı hecelerim: Y-A-Z.' },
    ],
    esdizim: ['den Namen buchstabieren', 'Wie buchstabiert man das?'],
    aile: ['der Buchstabe', 'das Buch'],
    hata: 'Türkçede "hecelemek" heceye böler; Almancada buchstabieren HARF harf söylemektir.',
    hatirlatma: 'Telefonda ve resmî işlerde en çok duyacağın fiillerden biri budur — adını Almanca harflerle söylemeyi ezberle.',
    uretim: {
      yonerge: 'Birinden adını hecelemesini nazikçe iste.',
      kabul: [
        'Können Sie das bitte buchstabieren',
        'Kannst du das bitte buchstabieren',
        'Koennen Sie das bitte buchstabieren',
      ],
    },
  },
  {
    id: 'de-nummer',
    dil: 'de',
    kelime: 'Nummer',
    artikel: 'die',
    cogul: 'die Nummern',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Eine Zahl, die etwas oder jemanden bezeichnet.',
    turkceDestek: 'numara',
    ipa: '/ˈnʊmɐ/',
    heceler: 'Num-mer',
    ornekler: [
      { de: 'Wie ist deine Handynummer?', tr: 'Cep telefonu numaran nedir?' },
      { de: 'Meine Nummer ist 0532 …', tr: 'Numaram 0532 …' },
    ],
    esdizim: ['die Telefonnummer', 'die Handynummer', 'die Hausnummer'],
    aile: ['die Zahl', 'nummerieren'],
    hata: '"Nummer" belirli bir numaradır (telefon, ev); "Zahl" ise soyut sayıdır. İkisi Türkçede tek kelimeyle karşılanır.',
    hatirlatma: 'Almancada telefon numarası çoğunlukla ikişerli okunur: 32 → zweiunddreißig.',
    uretim: {
      yonerge: 'Birinden telefon numarasını iste.',
      kabul: ['Wie ist deine Nummer', 'Wie ist deine Telefonnummer', 'Wie ist Ihre Telefonnummer'],
    },
  },
  {
    id: 'de-adresse',
    dil: 'de',
    kelime: 'Adresse',
    artikel: 'die',
    cogul: 'die Adressen',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Straße, Hausnummer und Ort, wo jemand wohnt.',
    turkceDestek: 'adres',
    ipa: '/aˈdʁɛsə/',
    heceler: 'A-dres-se (vurgu: DRES)',
    ornekler: [
      { de: 'Wie ist deine Adresse?', tr: 'Adresin nedir?' },
      { de: 'Ich schreibe dir meine Adresse.', tr: 'Sana adresimi yazıyorum.' },
    ],
    esdizim: ['die E-Mail-Adresse', 'die Adresse angeben'],
    aile: ['die E-Mail-Adresse'],
    hata: 'Almancada adres sırası Türkçenin tersidir: önce sokak ve numara, sonra posta kodu ve şehir.',
    hatirlatma: 'Tek "d", çift "s": A-d-r-e-s-s-e.',
    uretim: {
      yonerge: 'Birinden adresini nazikçe iste.',
      kabul: ['Wie ist deine Adresse', 'Wie ist Ihre Adresse'],
    },
  },
  {
    id: 'de-jahr',
    dil: 'de',
    kelime: 'Jahr',
    artikel: 'das',
    cogul: 'die Jahre',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Ein Zeitraum von zwölf Monaten.',
    turkceDestek: 'yıl, sene',
    ipa: '/jaːɐ̯/',
    heceler: 'Jahr (J → "y" okunur)',
    ornekler: [
      { de: 'Ich bin fünfzehn Jahre alt.', tr: 'On beş yaşındayım.' },
      { de: 'Nächstes Jahr fahre ich nach Berlin.', tr: 'Gelecek yıl Berlin’e gideceğim.' },
    ],
    esdizim: ['… Jahre alt sein', 'nächstes Jahr', 'jedes Jahr'],
    aile: ['jährlich', 'das Schuljahr'],
    hata: 'Yaş "haben" ile söylenmez: "Ich habe 15 Jahre" YANLIŞ. Doğrusu "Ich bin 15 Jahre alt".',
    hatirlatma: 'Almancada J harfi her zaman "y" okunur: Jahr → "yaar", ja → "ya".',
    uretim: {
      yonerge: 'Yaşını tam bir cümleyle yaz.',
      kabul: ['Ich bin', 'Ich bin 15 Jahre alt'],
    },
  },
  {
    id: 'de-danke',
    dil: 'de',
    kelime: 'danke',
    tur: 'kalıp',
    seviye: 'A1',
    almancaTanim: 'Wort, mit dem man sich bedankt.',
    turkceDestek: 'teşekkürler',
    ipa: '/ˈdaŋkə/',
    heceler: 'dan-ke (nk → genizden "ng")',
    ornekler: [
      { de: 'Danke schön! — Bitte schön!', tr: 'Çok teşekkürler! — Rica ederim!' },
      { de: 'Vielen Dank für deine Hilfe.', tr: 'Yardımın için çok teşekkürler.' },
    ],
    esdizim: ['danke schön', 'vielen Dank', 'danke sehr'],
    aile: ['danken', 'der Dank', 'dankbar'],
    hata: '"Danke" bir teklife cevap olarak tek başına söylenirse Almancada çoğu zaman "hayır, istemem" anlamına gelir. Kabul etmek için "Ja, bitte" denir.',
    hatirlatma: 'Cevabı "bitte"dir: hem "lütfen" hem "rica ederim" demektir.',
    uretim: {
      yonerge: 'Birine yardımı için teşekkür et.',
      kabul: ['Vielen Dank für deine Hilfe', 'Danke für deine Hilfe', 'Vielen Dank fuer deine Hilfe'],
    },
  },
  {
    id: 'de-bitte',
    dil: 'de',
    kelime: 'bitte',
    tur: 'kalıp',
    seviye: 'A1',
    almancaTanim: 'Wort für eine höfliche Bitte und für die Antwort auf "danke".',
    turkceDestek: 'lütfen; rica ederim; buyurun',
    ipa: '/ˈbɪtə/',
    heceler: 'bit-te',
    ornekler: [
      { de: 'Einen Kaffee, bitte.', tr: 'Bir kahve, lütfen.' },
      { de: 'Wie bitte? Ich habe das nicht verstanden.', tr: 'Efendim? Anlamadım.' },
    ],
    esdizim: ['bitte schön', 'Wie bitte?', 'Ja, bitte'],
    aile: ['bitten', 'die Bitte'],
    hata: 'Tek kelimeyle üç iş görür: rica ("lütfen"), cevap ("rica ederim") ve anlamadığını belirtme ("Wie bitte?"). Öğrenci sadece ilkini bilir.',
    hatirlatma: 'Anlamadığında "Was?" deme — kaba durur. "Wie bitte?" de.',
    uretim: {
      yonerge: 'Bir kahve isteyen nazik bir cümle yaz.',
      kabul: ['Einen Kaffee, bitte', 'Einen Kaffee bitte', 'Ich hätte gern einen Kaffee'],
    },
  },
  {
    id: 'de-entschuldigung',
    dil: 'de',
    kelime: 'Entschuldigung',
    artikel: 'die',
    cogul: 'die Entschuldigungen',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Wort, mit dem man um Verzeihung bittet oder jemanden anspricht.',
    turkceDestek: 'affedersiniz, pardon; özür',
    ipa: '/ɛntˈʃʊldɪɡʊŋ/',
    heceler: 'Ent-schul-di-gung (vurgu: SCHUL)',
    ornekler: [
      { de: 'Entschuldigung, wo ist der Bahnhof?', tr: 'Affedersiniz, tren garı nerede?' },
      { de: 'Entschuldigung, ich bin zu spät.', tr: 'Özür dilerim, geç kaldım.' },
    ],
    esdizim: ['Entschuldigung, wo ist…?', 'um Entschuldigung bitten'],
    aile: ['entschuldigen', 'die Schuld'],
    hata: 'Bir yabancıya soru sormaya başlarken Türkçedeki "pardon"un karşılığı budur; öğrenci çoğu zaman doğrudan soruya girer ve kaba durur.',
    hatirlatma: 'Sokakta birine bir şey soracaksan cümlen her zaman bununla başlasın.',
    uretim: {
      yonerge: 'Yoldan birine tren garını sor (nazik başlangıçla).',
      kabul: ['Entschuldigung, wo ist der Bahnhof', 'Entschuldigung wo ist der Bahnhof'],
    },
  },
  {
    id: 'de-gern',
    dil: 'de',
    kelime: 'gern',
    tur: 'zarf',
    seviye: 'A1',
    almancaTanim: 'Wort, das zeigt, dass man etwas mag oder gerne macht.',
    turkceDestek: 'severek, memnuniyetle ("… sevmek" anlamını verir)',
    ipa: '/ɡɛʁn/',
    heceler: 'gern (gerne biçimi de doğrudur)',
    ornekler: [
      { de: 'Ich spiele gern Fußball.', tr: 'Futbol oynamayı severim.' },
      { de: 'Trinkst du gern Tee?', tr: 'Çay içmeyi sever misin?' },
    ],
    esdizim: ['gern haben', 'sehr gern', 'nicht gern'],
    zitAnlam: ['nicht gern', 'ungern'],
    aile: ['gerne', 'lieber', 'am liebsten'],
    hata: 'Türkçedeki "oynamayı severim" cümlesi "Ich liebe zu spielen" diye çevrilir — bu Almancada yanlıştır. Doğru yol fiile "gern" eklemektir.',
    hatirlatma: 'Karşılaştırması var: gern → lieber → am liebsten (severim → daha çok severim → en çok severim).',
    uretim: {
      yonerge: 'Yapmayı sevdiğin bir şeyi "gern" ile yaz.',
      kabul: ['Ich spiele gern', 'Ich lese gern', 'Ich höre gern', 'Ich esse gern', 'Ich mache gern'],
    },
  },
  {
    id: 'de-verheiratet',
    dil: 'de',
    kelime: 'verheiratet',
    tur: 'sıfat',
    seviye: 'A1',
    almancaTanim: 'Eine Ehe haben; nicht ledig sein.',
    turkceDestek: 'evli',
    ipa: '/fɛɐ̯ˈhaɪ̯ʁaːtət/',
    heceler: 'ver-hei-ra-tet (v → "f" okunur)',
    ornekler: [
      { de: 'Meine Eltern sind verheiratet.', tr: 'Annemle babam evli.' },
      { de: 'Sind Sie verheiratet oder ledig?', tr: 'Evli misiniz, bekâr mı?' },
    ],
    esdizim: ['verheiratet sein', 'seit … Jahren verheiratet'],
    zitAnlam: ['ledig', 'geschieden'],
    aile: ['heiraten', 'die Heirat', 'die Ehe'],
    hata: 'Almancada "v" harfi genelde "f" okunur: verheiratet → "ferhayraatet". Öğrenci "v" der ve kelime tanınmaz.',
    hatirlatma: 'Formlarda en sık karşına çıkan üç seçenek: ledig (bekâr), verheiratet (evli), geschieden (boşanmış).',
    uretim: {
      yonerge: 'Ailenden birinin medeni durumunu yaz.',
      kabul: ['Meine Eltern sind verheiratet', 'Mein Bruder ist ledig', 'Meine Schwester ist ledig'],
    },
  },
  {
    id: 'de-willkommen',
    dil: 'de',
    kelime: 'willkommen',
    tur: 'kalıp',
    seviye: 'A1',
    almancaTanim: 'Gruß für jemanden, der neu ankommt.',
    turkceDestek: 'hoş geldin(iz)',
    ipa: '/vɪlˈkɔmən/',
    heceler: 'will-kom-men (vurgu: KOM)',
    ornekler: [
      { de: 'Herzlich willkommen in Deutschland!', tr: 'Almanya’ya hoş geldiniz!' },
      { de: 'Willkommen zu Hause!', tr: 'Eve hoş geldin!' },
    ],
    esdizim: ['herzlich willkommen', 'willkommen in …'],
    aile: ['der Wille', 'kommen'],
    hata: 'Türkçede "hoş geldin"e "hoş bulduk" diye karşılık verilir; Almancada böyle bir kalıp yoktur. Cevap "Danke!"dir.',
    hatirlatma: '"Willkommen" iki "l" ile yazılır: will-kommen.',
    uretim: {
      yonerge: 'Yeni gelen bir arkadaşını Almanca karşıla.',
      kabul: ['Herzlich willkommen', 'Willkommen'],
    },
  },
]
