/**
 * A1 — YEMEK VE ALIŞVERİŞ KELİMELERİ
 * ==================================================================
 *
 * Bu set Akkusativ\'in en doğal çalıştığı yerdir: alınan, istenen, yenen
 * her şey nesnedir. Bu yüzden örneklerin çoğu bilinçli olarak
 * "Ich möchte einen/eine/ein …" kalıbıyla kurulmuştur — öğrenci hâl
 * ekini tabloda değil, sipariş verirken öğrenir.
 */

export const KELIMELER = [
  {
    id: 'de-brot',
    dil: 'de',
    kelime: 'Brot',
    artikel: 'das',
    cogul: 'die Brote',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Ein Lebensmittel aus Mehl, das man backt.',
    turkceDestek: 'ekmek',
    ipa: '/bʁoːt/',
    heceler: 'Brot (uzun o)',
    ornekler: [
      { de: 'Ich esse morgens Brot mit Käse.', tr: 'Sabahları peynirli ekmek yiyorum.' },
      { de: 'Wir kaufen Brot beim Bäcker.', tr: 'Ekmeği fırından alıyoruz.' },
    ],
    esdizim: ['das Brot schneiden', 'beim Bäcker', 'das Brötchen'],
    aile: ['das Brötchen', 'der Bäcker', 'das Abendbrot'],
    hata: 'Küçük ekmek "das Brötchen"dir ve -chen eki yüzünden mutlaka "das" alır.',
    hatirlatma: 'Almanya\'da yüzlerce ekmek çeşidi vardır; "Brot" genel addır, market ve fırın adları değişir.',
    uretim: {
      yonerge: 'Sabah ne yediğini "Brot" ile yaz.',
      kabul: ['Ich esse Brot', 'Ich esse morgens Brot'],
    },
  },
  {
    id: 'de-wasser',
    dil: 'de',
    kelime: 'Wasser',
    artikel: 'das',
    cogul: 'die Wässer (nadiren kullanılır)',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Die klare Flüssigkeit, die man trinkt.',
    turkceDestek: 'su',
    ipa: '/ˈvasɐ/',
    heceler: 'Was-ser (W → "v")',
    ornekler: [
      { de: 'Ein Wasser, bitte.', tr: 'Bir su, lütfen.' },
      { de: 'Ich trinke viel Wasser.', tr: 'Çok su içiyorum.' },
    ],
    esdizim: ['stilles Wasser', 'Wasser mit Kohlensäure', 'ein Glas Wasser'],
    aile: ['das Mineralwasser', 'wässrig'],
    hata: 'Almanya\'da restoranda "Wasser" istersen çoğunlukla MADEN SUYU (gazlı) gelir. Sade su için "stilles Wasser" denir.',
    bolgesel: { de: 'Sprudel / Mineralwasser', at: 'Prickelwasser', ch: 'Mineral mit Gas' },
    hatirlatma: 'Sayılamayan isim olduğu için genelde artikelsiz kullanılır: "Ich trinke Wasser."',
    uretim: {
      yonerge: 'Sade su isteyen nazik bir cümle yaz.',
      kabul: ['Ein stilles Wasser, bitte', 'Ich hätte gern ein stilles Wasser', 'Ein Wasser, bitte'],
    },
  },
  {
    id: 'de-milch',
    dil: 'de',
    kelime: 'Milch',
    artikel: 'die',
    cogul: 'çoğulu yok',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Das weiße Getränk von der Kuh.',
    turkceDestek: 'süt',
    ipa: '/mɪlç/',
    heceler: 'Milch (ch yumuşak "ç")',
    ornekler: [
      { de: 'Ich trinke Kaffee mit Milch.', tr: 'Kahveyi sütlü içerim.' },
      { de: 'Die Milch ist im Kühlschrank.', tr: 'Süt buzdolabında.' },
    ],
    esdizim: ['Kaffee mit Milch', 'eine Flasche Milch'],
    aile: ['der Milchkaffee', 'das Milchprodukt'],
    hata: 'Sayılamayan isim olduğu için çoğulu yoktur; miktar "eine Flasche / ein Liter Milch" ile söylenir.',
    hatirlatma: 'i, e, ä, ö, ü\'den sonra gelen "ch" yumuşak okunur: Milch, ich, nicht.',
    uretim: {
      yonerge: 'Kahveni nasıl içtiğini yaz.',
      kabul: ['Ich trinke Kaffee mit Milch', 'Ich trinke Kaffee ohne Milch'],
    },
  },
  {
    id: 'de-kaese',
    dil: 'de',
    kelime: 'Käse',
    artikel: 'der',
    cogul: 'die Käse',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Ein Lebensmittel aus Milch.',
    turkceDestek: 'peynir',
    ipa: '/ˈkɛːzə/',
    heceler: 'Kä-se (ä geniş "e", s → "z")',
    ornekler: [
      { de: 'Ich möchte ein Brot mit Käse.', tr: 'Peynirli bir ekmek istiyorum.' },
      { de: 'Der Käse schmeckt sehr gut.', tr: 'Peynir çok lezzetli.' },
    ],
    esdizim: ['Brot mit Käse', 'ein Stück Käse'],
    aile: ['das Käsebrot', 'der Frischkäse'],
    hata: 'Eril olduğu için "mit dem Käse" (Dativ) olur; "mit" her zaman Dativ ister.',
    hatirlatma: '"ä" harfi Türkçedeki geniş "e" gibidir; "a" değil.',
    uretim: {
      yonerge: 'Peynirli bir şey isteyen cümle yaz.',
      kabul: ['Ich möchte ein Brot mit Käse', 'Ich hätte gern Käse', 'Ich möchte Käse'],
    },
  },
  {
    id: 'de-apfel',
    dil: 'de',
    kelime: 'Apfel',
    artikel: 'der',
    cogul: 'die Äpfel',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Eine runde Frucht, meistens rot oder grün.',
    turkceDestek: 'elma',
    ipa: '/ˈap͡fl̩/',
    heceler: 'Ap-fel (pf tek nefeste)',
    ornekler: [
      { de: 'Ich esse jeden Tag einen Apfel.', tr: 'Her gün bir elma yiyorum.' },
      { de: 'Ein Kilo Äpfel, bitte.', tr: 'Bir kilo elma, lütfen.' },
    ],
    esdizim: ['ein Kilo Äpfel', 'der Apfelsaft'],
    aile: ['der Apfelsaft', 'der Apfelkuchen'],
    hata: 'Çoğulda yalnız umlaut değişir, ek gelmez: Apfel → Äpfel. Ayrıca eril olduğu için "einen Apfel" (Akkusativ).',
    hatirlatma: '"pf" Almancaya özgü ikili sestir: p ve f birlikte, tek nefeste söylenir.',
    uretim: {
      yonerge: 'Manavdan bir kilo elma iste.',
      kabul: ['Ein Kilo Äpfel, bitte', 'Ein Kilo Äpfel bitte', 'Ich möchte ein Kilo Äpfel'],
    },
  },
  {
    id: 'de-suppe',
    dil: 'de',
    kelime: 'Suppe',
    artikel: 'die',
    cogul: 'die Suppen',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Eine warme flüssige Speise, die man löffelt.',
    turkceDestek: 'çorba',
    ipa: '/ˈzʊpə/',
    heceler: 'Sup-pe (baştaki S → "z")',
    ornekler: [
      { de: 'Ich esse gern Suppe.', tr: 'Çorba içmeyi severim.' },
      { de: 'Die Suppe ist noch heiß.', tr: 'Çorba hâlâ sıcak.' },
    ],
    esdizim: ['Suppe essen', 'die Tomatensuppe'],
    aile: ['der Suppenlöffel'],
    hata: 'Almancada çorba İÇİLMEZ, YENİR: "Suppe essen". Türkçeden gelen "Suppe trinken" yanlıştır.',
    hatirlatma: 'Kelime başındaki "s" ünlüden önce "z" okunur: Suppe → "zupı", sagen → "zaagen".',
    uretim: {
      yonerge: 'Çorba sevip sevmediğini doğru fiille yaz.',
      kabul: ['Ich esse gern Suppe', 'Ich esse nicht gern Suppe'],
    },
  },
  {
    id: 'de-fleisch',
    dil: 'de',
    kelime: 'Fleisch',
    artikel: 'das',
    cogul: 'çoğulu yok',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Das Essen, das vom Tier kommt.',
    turkceDestek: 'et',
    ipa: '/flaɪ̯ʃ/',
    heceler: 'Fleisch (ei → "ay", sch → "ş")',
    ornekler: [
      { de: 'Ich esse kein Fleisch.', tr: 'Et yemiyorum.' },
      { de: 'Das Fleisch ist sehr lecker.', tr: 'Et çok lezzetli.' },
    ],
    esdizim: ['kein Fleisch essen', 'das Hackfleisch'],
    aile: ['der Fleischer', 'das Hackfleisch'],
    hata: 'Olumsuzu "nicht Fleisch" değil "KEIN Fleisch"tir — isim olduğu için kein ile olumsuzlanır.',
    hatirlatma: 'Kasap "der Metzger" (güney) ya da "der Fleischer" (kuzey) diye anılır.',
    bolgesel: { de: 'Metzger / Fleischer', at: 'Fleischhauer', ch: 'Metzger' },
    uretim: {
      yonerge: 'Et yiyip yemediğini yaz.',
      kabul: ['Ich esse Fleisch', 'Ich esse kein Fleisch'],
    },
  },
  {
    id: 'de-gemuese',
    dil: 'de',
    kelime: 'Gemüse',
    artikel: 'das',
    cogul: 'çoğulu yok',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Pflanzen, die man isst, zum Beispiel Tomaten und Karotten.',
    turkceDestek: 'sebze',
    ipa: '/ɡəˈmyːzə/',
    heceler: 'Ge-mü-se (vurgu: MÜ)',
    ornekler: [
      { de: 'Ich esse viel Gemüse.', tr: 'Çok sebze yiyorum.' },
      { de: 'Gemüse ist gesund.', tr: 'Sebze sağlıklıdır.' },
    ],
    esdizim: ['frisches Gemüse', 'Obst und Gemüse'],
    aile: ['der Gemüsehändler'],
    hata: 'Türkçede "sebzeler" çoğul yapılabilir; Almancada Gemüse toplu bir isimdir ve çoğulu kullanılmaz.',
    hatirlatma: 'Ge- ön eki toplayıcıdır ve bu tür kelimeler "das" alır: das Gemüse, das Gebäude, das Gepäck.',
    uretim: {
      yonerge: 'Sebze yeme alışkanlığını yaz.',
      kabul: ['Ich esse viel Gemüse', 'Ich esse gern Gemüse', 'Ich esse nicht viel Gemüse'],
    },
  },
  {
    id: 'de-restaurant',
    dil: 'de',
    kelime: 'Restaurant',
    artikel: 'das',
    cogul: 'die Restaurants',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Ein Ort, wo man essen und trinken kann.',
    turkceDestek: 'restoran, lokanta',
    ipa: '/ʁɛstoˈʁɑ̃ː/',
    heceler: 'Res-tau-rant (Fransızca gibi, son hece genizden)',
    ornekler: [
      { de: 'Wir gehen heute ins Restaurant.', tr: 'Bugün restorana gidiyoruz.' },
      { de: 'Das Restaurant ist am Marktplatz.', tr: 'Restoran meydanda.' },
    ],
    esdizim: ['ins Restaurant gehen', 'im Restaurant essen'],
    aile: ['das Lokal', 'die Gaststätte'],
    hata: 'Fransızcadan geldiği için son hece genizden ve "t" okunmadan söylenir: "restorãã".',
    hatirlatma: 'Yabancı kökenli kelimeler çoğulu -s ile yapar: Restaurants, Handys, Autos.',
    uretim: {
      yonerge: 'Restorana gitmekle ilgili bir cümle yaz.',
      kabul: ['Ich gehe ins Restaurant', 'Wir gehen ins Restaurant'],
    },
  },
  {
    id: 'de-rechnung',
    dil: 'de',
    kelime: 'Rechnung',
    artikel: 'die',
    cogul: 'die Rechnungen',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Das Papier, auf dem steht, was man bezahlen muss.',
    turkceDestek: 'hesap, fatura',
    ipa: '/ˈʁɛçnʊŋ/',
    heceler: 'Rech-nung',
    ornekler: [
      { de: 'Die Rechnung, bitte!', tr: 'Hesap, lütfen!' },
      { de: 'Zusammen oder getrennt?', tr: 'Birlikte mi, ayrı ayrı mı?' },
    ],
    esdizim: ['die Rechnung bezahlen', 'Die Rechnung, bitte'],
    aile: ['rechnen', 'die Rechnung bezahlen'],
    hata: 'Restoranda garson "Zusammen oder getrennt?" diye sorar; bu, hesabın birlikte mi ayrı mı ödeneceğidir. Öğrenci soruyu anlamayınca donup kalır.',
    hatirlatma: '-ung ile biten bütün kelimeler "die" alır.',
    uretim: {
      yonerge: 'Restoranda hesabı iste.',
      kabul: ['Die Rechnung, bitte', 'Die Rechnung bitte', 'Ich möchte bezahlen'],
    },
  },
  {
    id: 'de-preis',
    dil: 'de',
    kelime: 'Preis',
    artikel: 'der',
    cogul: 'die Preise',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Wie viel Geld etwas kostet.',
    turkceDestek: 'fiyat; ödül',
    ipa: '/pʁaɪ̯s/',
    heceler: 'Preis (ei → "ay")',
    ornekler: [
      { de: 'Der Preis ist zu hoch.', tr: 'Fiyat çok yüksek.' },
      { de: 'Was kostet das?', tr: 'Bu ne kadar?' },
    ],
    esdizim: ['der Preis ist hoch', 'ein guter Preis'],
    aile: ['preiswert', 'kosten'],
    hata: 'Fiyat sorarken "Wie viel ist der Preis?" değil, doğrudan "Was kostet das?" ya da "Wie viel kostet das?" denir.',
    hatirlatma: 'Aynı kelime "ödül" anlamına da gelir: der Nobelpreis.',
    uretim: {
      yonerge: 'Bir şeyin fiyatını sor.',
      kabul: ['Was kostet das', 'Wie viel kostet das'],
    },
  },
  {
    id: 'de-geld',
    dil: 'de',
    kelime: 'Geld',
    artikel: 'das',
    cogul: 'die Gelder (nadiren)',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Münzen und Scheine, mit denen man bezahlt.',
    turkceDestek: 'para',
    ipa: '/ɡɛlt/',
    heceler: 'Geld (sondaki d → "t")',
    ornekler: [
      { de: 'Ich habe kein Geld dabei.', tr: 'Yanımda param yok.' },
      { de: 'Das kostet viel Geld.', tr: 'Bu çok paraya mal oluyor.' },
    ],
    esdizim: ['Geld haben', 'Geld ausgeben', 'kein Geld'],
    aile: ['die Geldbörse', 'bezahlen'],
    hata: 'Sayılamayan isimdir; "viele Gelder" denmez, "viel Geld" denir.',
    hatirlatma: 'Almanya, Avusturya ve Almanca konuşulan bölgelerin çoğu Euro kullanır; İsviçre ise Frank (CHF) kullanır.',
    bolgesel: { de: 'Euro', at: 'Euro', ch: 'Franken' },
    uretim: {
      yonerge: 'Yanında para olup olmadığını yaz.',
      kabul: ['Ich habe Geld', 'Ich habe kein Geld'],
    },
  },
  {
    id: 'de-kaufen',
    dil: 'de',
    kelime: 'kaufen',
    cekim: 'kauft · kaufte · hat gekauft',
    tur: 'fiil',
    seviye: 'A1',
    almancaTanim: 'Etwas mit Geld bekommen.',
    turkceDestek: 'satın almak',
    ipa: '/ˈkaʊ̯fn̩/',
    heceler: 'kau-fen',
    ornekler: [
      { de: 'Ich kaufe einen Kuchen.', tr: 'Bir pasta alıyorum.' },
      { de: 'Wo kann man hier Obst kaufen?', tr: 'Burada nereden meyve alınır?' },
    ],
    esdizim: ['einkaufen gehen', 'etwas kaufen'],
    zitAnlam: ['verkaufen'],
    aile: ['einkaufen', 'der Verkäufer', 'das Kaufhaus'],
    hata: '"kaufen" bir şey satın almaktır; "einkaufen" alışverişe çıkmaktır ve ayrılabilen fiildir: "Ich kaufe ein."',
    hatirlatma: 'Nesnesi Akkusativ\'dir: einen Kuchen, eine Tasche, ein Buch.',
    uretim: {
      yonerge: 'Ne satın aldığını yaz (Akkusativ\'e dikkat).',
      kabul: ['Ich kaufe einen', 'Ich kaufe eine', 'Ich kaufe ein'],
    },
  },
  {
    id: 'de-bezahlen',
    dil: 'de',
    kelime: 'bezahlen',
    cekim: 'bezahlt · bezahlte · hat bezahlt',
    tur: 'fiil',
    seviye: 'A1',
    almancaTanim: 'Geld für etwas geben.',
    turkceDestek: 'ödemek',
    ipa: '/bəˈtsaːlən/',
    heceler: 'be-zah-len (vurgu: ZAH)',
    ornekler: [
      { de: 'Ich möchte bezahlen, bitte.', tr: 'Ödemek istiyorum, lütfen.' },
      { de: 'Kann ich mit Karte bezahlen?', tr: 'Kartla ödeyebilir miyim?' },
    ],
    esdizim: ['mit Karte bezahlen', 'bar bezahlen', 'die Rechnung bezahlen'],
    aile: ['die Zahlung', 'zahlen'],
    hata: 'be- ön eki AYRILMAZ ve vurgu almaz. "Ich zahle be" diye bir şey yoktur.',
    hatirlatma: 'Almanya\'da hâlâ birçok yerde nakit (bar) ödenir; "Nur Bargeld" yazısını görmeye hazır ol.',
    uretim: {
      yonerge: 'Kartla ödeyip ödeyemeyeceğini sor.',
      kabul: ['Kann ich mit Karte bezahlen', 'Kann ich mit Karte zahlen'],
    },
  },
  {
    id: 'de-moechten',
    dil: 'de',
    kelime: 'möchten',
    cekim: 'möchte · wollte · hat gewollt',
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    almancaTanim: 'Höfliche Form von "wollen": etwas gerne haben wollen.',
    turkceDestek: 'istemek (nazik biçim)',
    ipa: '/ˈmœçtn̩/',
    heceler: 'möch-ten',
    ornekler: [
      { de: 'Ich möchte einen Tee, bitte.', tr: 'Bir çay istiyorum, lütfen.' },
      { de: 'Was möchtest du trinken?', tr: 'Ne içmek istersin?' },
    ],
    esdizim: ['Ich möchte…', 'Was möchten Sie?'],
    aile: ['mögen', 'wollen'],
    hata: '1. ve 3. tekil AYNIDIR ve ek almaz: ich möchte, er möchte (ich möchtE değil möcht-e biter, "möchtet" yanlış).',
    hatirlatma: '"wollen" doğrudan ve serttir ("istiyorum"); sipariş verirken hep "möchten" kullanılır.',
    uretim: {
      yonerge: 'Nazikçe bir çay sipariş et.',
      kabul: ['Ich möchte einen Tee', 'Ich möchte einen Tee, bitte', 'Ich hätte gern einen Tee'],
    },
  },
  {
    id: 'de-schmecken',
    dil: 'de',
    kelime: 'schmecken',
    cekim: 'schmeckt · schmeckte · hat geschmeckt',
    tur: 'fiil',
    seviye: 'A1',
    almancaTanim: 'Einen bestimmten Geschmack haben; gut sein zum Essen.',
    turkceDestek: 'tadı … olmak, lezzetli gelmek',
    ipa: '/ˈʃmɛkn̩/',
    heceler: 'schme-cken',
    ornekler: [
      { de: 'Das Essen schmeckt sehr gut.', tr: 'Yemek çok lezzetli.' },
      { de: 'Schmeckt dir der Kuchen?', tr: 'Pastayı beğendin mi?' },
    ],
    esdizim: ['gut schmecken', 'Schmeckt es dir?'],
    aile: ['der Geschmack', 'lecker'],
    hata: 'Özne YEMEKTİR, kişi değil: "Das Essen schmeckt mir" (Ich schmecke das Essen değil). Kişi Dativ\'e girer.',
    hatirlatma: 'Türkçedeki "beğenmek" burada tersine döner; aynı yapı "gefallen" fiilinde de vardır.',
    uretim: {
      yonerge: 'Bir yemeğin lezzetli olduğunu söyle.',
      kabul: ['Das Essen schmeckt gut', 'Das schmeckt sehr gut', 'Es schmeckt gut'],
    },
  },
  {
    id: 'de-lecker',
    dil: 'de',
    kelime: 'lecker',
    tur: 'sıfat',
    seviye: 'A1',
    almancaTanim: 'Sehr gut im Geschmack.',
    turkceDestek: 'lezzetli, nefis',
    ipa: '/ˈlɛkɐ/',
    heceler: 'lec-ker',
    ornekler: [
      { de: 'Der Kuchen ist sehr lecker!', tr: 'Pasta çok lezzetli!' },
      { de: 'Das riecht lecker.', tr: 'Kokusu nefis.' },
    ],
    esdizim: ['sehr lecker', 'lecker aussehen'],
    esAnlam: ['köstlich'],
    aile: ['schmecken'],
    hata: 'Yalnız yiyecek-içecek için kullanılır. Bir film ya da kitap için "lecker" denmez.',
    hatirlatma: 'Günlük konuşmada en çok duyacağın iltifattır; resmî yazıda "köstlich" tercih edilir.',
    kayit: 'gundelik',
    uretim: {
      yonerge: 'Sevdiğin bir yemeği "lecker" ile anlat.',
      kabul: ['ist sehr lecker', 'ist lecker'],
    },
  },
  {
    id: 'de-hunger',
    dil: 'de',
    kelime: 'Hunger',
    artikel: 'der',
    cogul: 'çoğulu yok',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Das Gefühl, wenn man essen möchte.',
    turkceDestek: 'açlık',
    ipa: '/ˈhʊŋɐ/',
    heceler: 'Hun-ger (ng genizden)',
    ornekler: [
      { de: 'Ich habe Hunger.', tr: 'Acıktım.' },
      { de: 'Hast du Hunger?', tr: 'Acıktın mı?' },
    ],
    esdizim: ['Hunger haben', 'großen Hunger haben'],
    zitAnlam: ['der Durst'],
    aile: ['hungrig'],
    hata: 'Almancada açlık "HABEN" ile söylenir: "Ich habe Hunger". Türkçedeki "acıktım" fiilden gelir, birebir çevrilmez.',
    hatirlatma: 'Aynı kalıp susuzluk için de geçerli: Ich habe Durst.',
    uretim: {
      yonerge: 'Acıktığını Almanca söyle.',
      kabul: ['Ich habe Hunger'],
    },
  },
  {
    id: 'de-durst',
    dil: 'de',
    kelime: 'Durst',
    artikel: 'der',
    cogul: 'çoğulu yok',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Das Gefühl, wenn man trinken möchte.',
    turkceDestek: 'susuzluk',
    ipa: '/dʊʁst/',
    heceler: 'Durst',
    ornekler: [
      { de: 'Ich habe großen Durst.', tr: 'Çok susadım.' },
      { de: 'Hast du Durst? Möchtest du Wasser?', tr: 'Susadın mı? Su ister misin?' },
    ],
    esdizim: ['Durst haben', 'den Durst löschen'],
    zitAnlam: ['der Hunger'],
    aile: ['durstig'],
    hata: '"Ich bin durstig" de doğrudur ama günlük dilde "Ich habe Durst" çok daha yaygındır.',
    hatirlatma: 'Hunger ve Durst ikilisi hep birlikte öğrenilir; ikisi de "haben" ile kullanılır.',
    uretim: {
      yonerge: 'Susadığını Almanca söyle.',
      kabul: ['Ich habe Durst'],
    },
  },
  {
    id: 'de-flasche',
    dil: 'de',
    kelime: 'Flasche',
    artikel: 'die',
    cogul: 'die Flaschen',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Ein Behälter aus Glas oder Plastik für Getränke.',
    turkceDestek: 'şişe',
    ipa: '/ˈflaʃə/',
    heceler: 'Fla-sche',
    ornekler: [
      { de: 'Eine Flasche Wasser, bitte.', tr: 'Bir şişe su, lütfen.' },
      { de: 'Die Flasche ist leer.', tr: 'Şişe boş.' },
    ],
    esdizim: ['eine Flasche Wasser', 'die Pfandflasche'],
    aile: ['das Pfand', 'die Wasserflasche'],
    hata: 'Miktar ifadesinden sonra ikinci isim ARTİKELSİZ gelir: "eine Flasche Wasser" (eine Flasche das Wasser değil).',
    hatirlatma: 'Almanya\'da şişelerin depozitosu (Pfand) vardır; boş şişeleri markete götürüp para alırsın.',
    uretim: {
      yonerge: 'Bir şişe su iste.',
      kabul: ['Eine Flasche Wasser, bitte', 'Eine Flasche Wasser bitte', 'Ich möchte eine Flasche Wasser'],
    },
  },
  {
    id: 'de-kilo',
    dil: 'de',
    kelime: 'Kilo',
    artikel: 'das',
    cogul: 'die Kilos',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Eine Maßeinheit für Gewicht: 1000 Gramm.',
    turkceDestek: 'kilo',
    ipa: '/ˈkiːlo/',
    heceler: 'Ki-lo',
    ornekler: [
      { de: 'Ich nehme zwei Kilo Tomaten.', tr: 'İki kilo domates alıyorum.' },
      { de: 'Ein Kilo kostet drei Euro.', tr: 'Kilosu üç euro.' },
    ],
    esdizim: ['ein Kilo Äpfel', 'ein halbes Kilo'],
    aile: ['das Kilogramm', 'das Gramm'],
    hata: 'Miktar birimleri sayıdan sonra ÇOĞUL YAPILMAZ: "zwei Kilo" (zwei Kilos değil). Aynı kural Gramm, Euro, Meter için de geçerli.',
    hatirlatma: 'Almanya\'da yarım kiloya "ein Pfund" da denir (500 g).',
    uretim: {
      yonerge: 'İki kilo bir şey iste.',
      kabul: ['Ich möchte zwei Kilo', 'Zwei Kilo', 'Ich nehme zwei Kilo'],
    },
  },
  {
    id: 'de-supermarkt',
    dil: 'de',
    kelime: 'Supermarkt',
    artikel: 'der',
    cogul: 'die Supermärkte',
    tur: 'isim',
    seviye: 'A1',
    almancaTanim: 'Ein großes Geschäft für Lebensmittel.',
    turkceDestek: 'süpermarket',
    ipa: '/ˈzuːpɐˌmaʁkt/',
    heceler: 'Su-per-markt (baştaki S → "z")',
    ornekler: [
      { de: 'Ich gehe in den Supermarkt.', tr: 'Süpermarkete gidiyorum.' },
      { de: 'Der Supermarkt ist bis 20 Uhr offen.', tr: 'Süpermarket akşam sekize kadar açık.' },
    ],
    esdizim: ['in den Supermarkt gehen', 'im Supermarkt einkaufen'],
    aile: ['der Markt', 'einkaufen'],
    hata: 'Eril olduğu için hareket bildirirken "in DEN Supermarkt" (Akkusativ), bulunma bildirirken "im Supermarkt" (Dativ) olur.',
    hatirlatma: 'Almanya\'da marketler pazar günü KAPALIDIR; bu, günlük planı doğrudan etkileyen bir kültür farkıdır.',
    uretim: {
      yonerge: 'Süpermarkete gittiğini söyleyen cümle yaz.',
      kabul: ['Ich gehe in den Supermarkt'],
    },
  },
]
