/**
 * DRKOÇ — KELİME KAYITLARI: A2 / Modül 1 — Geçmişi anlatmak
 *
 * Bu modülün zorluğu kelime değil, geçmişin İKİ PARÇAYA bölünmesidir:
 * yardımcı fiil cümlenin ikinci sırasında, asıl fiil (Partizip II) en
 * sonda durur. Türkçede geçmiş tek ekle ve tek yerde kurulduğu için
 * öğrenci cümlenin sonunu boş bırakır. Bu yüzden her fiil kaydında
 * Perfekt biçimi yardımcı fiiliyle birlikte yazar.
 */

export const KELIMELER = [
  {
    id: 'de-gestern',
    dil: 'de',
    kelime: 'gestern',
    tur: 'zarf',
    seviye: 'A2',
    almancaTanim: 'Der Tag vor heute.',
    turkceDestek: 'dün',
    ipa: '/ˈɡɛstɐn/',
    heceler: 'ges-tern (vurgu ilk hecede)',
    ornekler: [
      { de: 'Gestern habe ich einen Film gesehen.', tr: 'Dün bir film izledim.' },
      { de: 'Wir waren gestern im Kino.', tr: 'Dün sinemadaydık.' },
    ],
    esdizim: ['gestern Abend', 'gestern Morgen', 'vorgestern'],
    aile: ['vorgestern'],
    hata: 'Cümle başında kullanılırsa fiil hemen arkasından gelir: "Gestern habe ich…" — "Gestern ich habe" YANLIŞTIR.',
    hatirlatma: 'Evvelki gün "vorgestern"dir; tek kelimeyle karşılanır.',
    uretim: {
      yonerge: '"Dün futbol oynadım." cümlesini yaz.',
      kabul: ['Gestern habe ich Fußball gespielt', 'Ich habe gestern Fußball gespielt'],
    },
  },
  {
    id: 'de-letzte-woche',
    dil: 'de',
    kelime: 'letzte Woche',
    tur: 'zaman ifadesi',
    seviye: 'A2',
    almancaTanim: 'Die Woche vor dieser Woche.',
    turkceDestek: 'geçen hafta',
    ipa: '/ˈlɛtstə ˈvɔxə/',
    heceler: 'letz-te Wo-che',
    ornekler: [
      { de: 'Letzte Woche waren wir in Izmir.', tr: 'Geçen hafta İzmir\'deydik.' },
      { de: 'Ich habe letzte Woche viel gelernt.', tr: 'Geçen hafta çok çalıştım.' },
    ],
    esdizim: ['letztes Jahr', 'letzten Monat', 'letzten Sommer'],
    aile: [],
    hata: 'Bu zaman ifadeleri edat almaz: "in letzte Woche" YANLIŞTIR, doğrudan "letzte Woche" denir.',
    hatirlatma: 'Eril isimlerde biçim değişir: letzten Monat, letzten Sommer.',
    uretim: {
      yonerge: '"Geçen hafta çok çalıştım." cümlesini yaz.',
      kabul: ['Letzte Woche habe ich viel gelernt', 'Ich habe letzte Woche viel gelernt'],
    },
  },
  {
    id: 'de-vor-jahren',
    dil: 'de',
    kelime: 'vor zwei Jahren',
    tur: 'zaman ifadesi',
    seviye: 'A2',
    almancaTanim: 'Zwei Jahre in der Vergangenheit.',
    turkceDestek: 'iki yıl önce',
    ipa: '/foːɐ̯ tsvaɪ ˈjaːrən/',
    heceler: 'vor zwei Jah-ren',
    ornekler: [
      { de: 'Vor zwei Jahren sind wir umgezogen.', tr: 'İki yıl önce taşındık.' },
      { de: 'Er hat vor drei Tagen angerufen.', tr: 'Üç gün önce aradı.' },
    ],
    esdizim: ['vor einer Woche', 'vor langer Zeit', 'vor einem Monat'],
    aile: [],
    hata: 'Türkçede "önce" sona gelir, Almancada "vor" BAŞA gelir ve Dativ ister: vor zwei Jahren, vor einer Woche.',
    hatirlatma: 'Çoğul isimlerde sona "-n" eklenir: Jahren, Tagen, Wochen.',
    uretim: {
      yonerge: '"Üç gün önce hastaydım." cümlesini yaz.',
      kabul: ['Vor drei Tagen war ich krank', 'Ich war vor drei Tagen krank'],
    },
  },
  {
    id: 'de-dann',
    dil: 'de',
    kelime: 'dann',
    tur: 'zarf',
    seviye: 'A2',
    almancaTanim: 'Danach, als nächster Schritt.',
    turkceDestek: 'sonra',
    ipa: '/dan/',
    heceler: 'dann (tek hece)',
    ornekler: [
      { de: 'Zuerst haben wir gefrühstückt, dann sind wir losgegangen.', tr: 'Önce kahvaltı ettik, sonra yola çıktık.' },
      { de: 'Dann hat es angefangen zu regnen.', tr: 'Sonra yağmur başladı.' },
    ],
    esdizim: ['zuerst … dann', 'und dann', 'dann endlich'],
    aile: ['danach'],
    hata: 'Cümle başında kullanılırsa fiil hemen arkasından gelir: "Dann sind wir…" — "Dann wir sind" YANLIŞTIR.',
    hatirlatma: 'Anlatı iskeleti: zuerst → dann → danach → schließlich.',
    uretim: {
      yonerge: '"Önce ders çalıştım, sonra dışarı çıktım." cümlesini yaz.',
      kabul: ['Zuerst habe ich gelernt, dann bin ich rausgegangen', 'Zuerst habe ich gelernt dann bin ich rausgegangen'],
    },
  },
  {
    id: 'de-schliesslich',
    dil: 'de',
    kelime: 'schließlich',
    tur: 'zarf',
    seviye: 'A2',
    almancaTanim: 'Am Ende, als letzter Schritt.',
    turkceDestek: 'sonunda, nihayet',
    ipa: '/ˈʃliːslɪç/',
    heceler: 'schließ-lich (vurgu ilk hecede)',
    ornekler: [
      { de: 'Schließlich haben wir die Adresse gefunden.', tr: 'Sonunda adresi bulduk.' },
      { de: 'Der Bus kam schließlich um neun.', tr: 'Otobüs sonunda dokuzda geldi.' },
    ],
    esdizim: ['und schließlich', 'schließlich doch', 'am Ende'],
    aile: ['der Schluss'],
    hata: '"Endlich" ile karıştırılır: "endlich" beklenen bir şeyin gelmesindeki rahatlamayı, "schließlich" sıralamanın son adımını anlatır.',
    hatirlatma: 'Kompozisyonda kapanış cümlesini açar.',
    uretim: {
      yonerge: '"Sonunda otobüsü bulduk." cümlesini yaz.',
      kabul: ['Schließlich haben wir den Bus gefunden'],
    },
  },
  {
    id: 'de-plotzlich',
    dil: 'de',
    kelime: 'plötzlich',
    tur: 'zarf',
    seviye: 'A2',
    almancaTanim: 'Sehr schnell und ohne Warnung.',
    turkceDestek: 'aniden, birdenbire',
    ipa: '/ˈplœtslɪç/',
    heceler: 'plötz-lich (vurgu ilk hecede)',
    ornekler: [
      { de: 'Plötzlich hat es angefangen zu regnen.', tr: 'Birdenbire yağmur başladı.' },
      { de: 'Das Auto ist plötzlich stehen geblieben.', tr: 'Araba aniden durdu.' },
    ],
    esdizim: ['ganz plötzlich', 'plötzlich stehen bleiben'],
    aile: [],
    hata: 'Cümle başında kullanıldığında fiil ikinci sırada kalır: "Plötzlich hat es…" — özne fiilden sonra gelir.',
    hatirlatma: 'Hikâyenin dönüm noktasını işaretler.',
    uretim: {
      yonerge: '"Birdenbire yağmur başladı." cümlesini yaz.',
      kabul: ['Plötzlich hat es angefangen zu regnen', 'Plötzlich hat es geregnet'],
    },
  },
  {
    id: 'de-passieren',
    dil: 'de',
    kelime: 'passieren',
    tur: 'fiil',
    seviye: 'A2',
    duzensiz: false,
    cekim: 'passiert · ist passiert',
    almancaTanim: 'Geschehen, sich ereignen.',
    turkceDestek: 'olmak, meydana gelmek',
    ipa: '/paˈsiːrən/',
    heceler: 'pas-sie-ren (vurgu ikinci hecede)',
    ornekler: [
      { de: 'Was ist gestern passiert?', tr: 'Dün ne oldu?' },
      { de: 'Der Unfall ist neben der Schule passiert.', tr: 'Kaza okulun yanında oldu.' },
    ],
    esdizim: ['was ist passiert', 'nichts ist passiert'],
    aie: [],
    aile: [],
    hata: 'Perfekt\'te "sein" ile çekilir: "ist passiert". "hat passiert" YANLIŞTIR.',
    hatirlatma: '-ieren ile biten fiiller Partizip II\'de "ge-" almaz: passiert, studiert, telefoniert.',
    uretim: {
      yonerge: '"Dün ne oldu?" sorusunu yaz.',
      kabul: ['Was ist gestern passiert'],
    },
  },
  {
    id: 'de-sich-erinnern',
    dil: 'de',
    kelime: 'sich erinnern',
    tur: 'fiil',
    seviye: 'A2',
    duzensiz: false,
    cekim: 'erinnert sich · hat sich erinnert',
    almancaTanim: 'Etwas wieder im Kopf haben.',
    turkceDestek: 'hatırlamak',
    ipa: '/zɪç ʔɛɐ̯ˈʔɪnɐn/',
    heceler: 'er-in-nern (vurgu ikinci hecede)',
    ornekler: [
      { de: 'Ich erinnere mich gut an diesen Tag.', tr: 'O günü iyi hatırlıyorum.' },
      { de: 'Erinnerst du dich an unsere Reise?', tr: 'Yolculuğumuzu hatırlıyor musun?' },
    ],
    esdizim: ['sich an etwas erinnern', 'soweit ich mich erinnere'],
    aile: ['die Erinnerung'],
    hata: 'Dönüşlü zamir ve edat birlikte gerekir: "sich an etwas erinnern". Edat "an"dır ve Akkusativ ister.',
    hatirlatma: 'Anı anlatan metinlerin kapanış fiilidir.',
    uretim: {
      yonerge: '"O günü iyi hatırlıyorum." cümlesini yaz.',
      kabul: ['Ich erinnere mich gut an diesen Tag'],
    },
  },
  {
    id: 'de-reise',
    dil: 'de',
    kelime: 'Reise',
    artikel: 'die',
    cogul: 'die Reisen',
    tur: 'isim',
    seviye: 'A2',
    almancaTanim: 'Eine Fahrt von einem Ort zu einem anderen.',
    turkceDestek: 'yolculuk, seyahat',
    ipa: '/ˈraɪzə/',
    heceler: 'Rei-se (vurgu ilk hecede)',
    ornekler: [
      { de: 'Die Reise hat vier Stunden gedauert.', tr: 'Yolculuk dört saat sürdü.' },
      { de: 'Wir haben eine lange Reise gemacht.', tr: 'Uzun bir yolculuk yaptık.' },
    ],
    esdizim: ['eine Reise machen', 'gute Reise', 'die Reise dauert'],
    aile: ['reisen', 'der Reisepass'],
    hata: 'Yolculuk "yapılır": "eine Reise machen". "Eine Reise tun" YANLIŞTIR.',
    hatirlatma: 'Kısa gidiş gelişe "die Fahrt", uzun seyahate "die Reise" denir.',
    uretim: {
      yonerge: '"Yolculuk üç saat sürdü." cümlesini yaz.',
      kabul: ['Die Reise hat drei Stunden gedauert'],
    },
  },
  {
    id: 'de-aufregend',
    dil: 'de',
    kelime: 'aufregend',
    tur: 'sıfat',
    seviye: 'A2',
    almancaTanim: 'So, dass man sich freut und Energie spürt.',
    turkceDestek: 'heyecan verici',
    ipa: '/ˈaʊfreːɡənt/',
    heceler: 'auf-re-gend (vurgu ilk hecede)',
    ornekler: [
      { de: 'Das war ein aufregendes Spiel.', tr: 'Heyecan verici bir maçtı.' },
      { de: 'Die Reise war wirklich aufregend.', tr: 'Yolculuk gerçekten heyecan vericiydi.' },
    ],
    esdizim: ['ein aufregender Tag', 'aufregend finden'],
    aile: ['sich aufregen', 'die Aufregung'],
    hata: '"sich aufregen" sinirlenmek demektir; sıfat olan "aufregend" ise olumludur. İkisini karıştırma.',
    hatirlatma: 'Karşıtı "langweilig" = sıkıcı.',
    uretim: {
      yonerge: '"Heyecan verici bir maçtı." cümlesini yaz.',
      kabul: ['Das war ein aufregendes Spiel'],
    },
  },
  {
    id: 'de-schrecklich',
    dil: 'de',
    kelime: 'schrecklich',
    tur: 'sıfat',
    seviye: 'A2',
    almancaTanim: 'Sehr schlecht oder unangenehm.',
    turkceDestek: 'berbat, korkunç',
    ipa: '/ˈʃrɛklɪç/',
    heceler: 'schreck-lich (vurgu ilk hecede)',
    ornekler: [
      { de: 'Das Wetter war die ganze Woche schrecklich.', tr: 'Hava bütün hafta berbattı.' },
      { de: 'Ich hatte schreckliche Kopfschmerzen.', tr: 'Berbat bir baş ağrım vardı.' },
    ],
    esdizim: ['schreckliches Wetter', 'schrecklich müde'],
    aile: ['der Schreck', 'erschrecken'],
    hata: 'Zarf olarak güçlendirici de olabilir: "schrecklich müde" = berbat yorgun. Bu kullanımda olumsuz anlam taşımaz.',
    hatirlatma: 'Anlatıda olumsuz dönüm noktasını işaretler.',
    uretim: {
      yonerge: '"Hava berbattı." cümlesini yaz.',
      kabul: ['Das Wetter war schrecklich'],
    },
  },
  {
    id: 'de-erlebnis',
    dil: 'de',
    kelime: 'Erlebnis',
    artikel: 'das',
    cogul: 'die Erlebnisse',
    tur: 'isim',
    seviye: 'A2',
    almancaTanim: 'Etwas Besonderes, das man erlebt hat.',
    turkceDestek: 'yaşanmış olay, deneyim',
    ipa: '/ɛɐ̯ˈleːpnɪs/',
    heceler: 'Er-leb-nis (vurgu ikinci hecede)',
    ornekler: [
      { de: 'Das war ein schönes Erlebnis.', tr: 'Bu güzel bir deneyimdi.' },
      { de: 'Ich erzähle euch von einem Erlebnis aus meiner Kindheit.', tr: 'Size çocukluğumdan bir olay anlatayım.' },
    ],
    esdizim: ['ein schönes Erlebnis', 'ein Erlebnis haben'],
    aile: ['erleben', 'das Leben'],
    hata: '"die Erfahrung" ile karıştırılır: "Erlebnis" tek bir olaydır, "Erfahrung" zamanla biriken tecrübedir.',
    hatirlatma: 'Anı yazısının başlığı için en uygun kelimedir.',
    uretim: {
      yonerge: '"Bu güzel bir deneyimdi." cümlesini yaz.',
      kabul: ['Das war ein schönes Erlebnis'],
    },
  },
]

export default KELIMELER
