/**
 * A1 — AİLE VE EŞYALAR
 * ==================================================================
 *
 * Bu havuzun asıl işi kelime öğretmek değil, CİNSİYET öğretmektir.
 * Fransızcada "kardeş" kelimesini bilmek yetmez; onun eril mi dişil mi
 * olduğunu bilmeyen öğrenci ne sıfatı uydurabilir, ne iyelik sıfatını
 * seçebilir, ne de zamiri doğru kurabilir.
 *
 * Bu yüzden her isimde `artikel`, `cins` ve `cogul` doludur ve örnek
 * cümleler kelimeyi HER ZAMAN artikeliyle birlikte gösterir.
 */

export const KELIMELER = [
  {
    id: 'fr-famille',
    dil: 'fr',
    kelime: 'famille',
    artikel: 'la',
    cins: 'disil',
    cogul: 'les familles',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Les personnes qui vivent ensemble : les parents et les enfants.',
    turkceDestek: 'aile',
    ipa: '/fa.mij/',
    heceler: 'fa-mille ("ill" burada "iy" okunur: fa-MİY)',
    ornekler: [
      { fr: 'Ma famille habite à Ankara.', tr: 'Ailem Ankara’da oturuyor.' },
      { fr: 'Nous sommes une famille de cinq personnes.', tr: 'Beş kişilik bir aileyiz.' },
    ],
    esdizim: ['une grande famille', 'en famille', 'un nom de famille'],
    aile: ['les parents', 'familial'],
    hata: '"ville" kelimesindeki gibi "vil" okumak. "famille" kelimesinde "ill" → "iy" okunur; "ville" istisnadır.',
    hatirlatma: 'Fransızcada "ailem" derken iyelik sıfatı isme uyar: ma famille (dişil).',
    uretim: {
      yonerge: '"Ailem İstanbul’da oturuyor." cümlesini yaz.',
      kabul: ['Ma famille habite à Istanbul', 'Ma famille habite a Istanbul'],
    },
  },
  {
    id: 'fr-pere',
    dil: 'fr',
    kelime: 'père',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les pères',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'L’homme qui a un enfant.',
    turkceDestek: 'baba',
    ipa: '/pɛʁ/',
    heceler: 'pè-re (è açık "e", sondaki e okunmaz)',
    ornekler: [
      { fr: 'Mon père est ingénieur.', tr: 'Babam mühendis.' },
      { fr: 'Le père de Léa travaille à Lyon.', tr: 'Léa’nın babası Lyon’da çalışıyor.' },
    ],
    esdizim: ['mon père', 'le père de', 'papa'],
    aile: ['la mère', 'les parents', 'paternel'],
    hata: 'Sahiplik kurarken Türkçedeki sırayı korumak: "Léa’nın babası" → "Léa père" değil, "le père DE Léa". Fransızcada sahiplik "de" ile ve TERS sırayla kurulur.',
    hatirlatma: 'Günlük dilde "papa" denir; "père" biraz daha resmîdir.',
    uretim: {
      yonerge: '"Babam öğretmen." cümlesini yaz.',
      kabul: ['Mon père est professeur', 'Mon pere est professeur', 'Mon père est prof'],
    },
  },
  {
    id: 'fr-mere',
    dil: 'fr',
    kelime: 'mère',
    artikel: 'la',
    cins: 'disil',
    cogul: 'les mères',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'La femme qui a un enfant.',
    turkceDestek: 'anne',
    ipa: '/mɛʁ/',
    heceler: 'mè-re ("mer" gibi okunur)',
    ornekler: [
      { fr: 'Ma mère est médecin.', tr: 'Annem doktor.' },
      { fr: 'Ma mère est très gentille.', tr: 'Annem çok kibar.' },
    ],
    esdizim: ['ma mère', 'la mère de', 'maman'],
    aile: ['le père', 'les parents', 'maternel'],
    hata: 'Sıfatı dişile uydurmayı unutmak: "Ma mère est gentil" değil, "gentille". Sıfat annenin cinsine uyar.',
    hatirlatma: '"mer" (deniz) ve "mère" (anne) aynı okunur, yazımları farklıdır.',
    uretim: {
      yonerge: '"Annem çok kibar." cümlesini yaz (sıfat uyumuna dikkat).',
      kabul: ['Ma mère est très gentille', 'Ma mere est tres gentille'],
    },
  },
  {
    id: 'fr-parents',
    dil: 'fr',
    kelime: 'parent',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les parents (bu anlamda hep çoğul kullanılır)',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Le père et la mère ensemble.',
    turkceDestek: 'anne baba, ebeveynler',
    ipa: '/pa.ʁɑ̃/',
    heceler: 'pa-rents (sondaki -ents nazal "an", s okunmaz)',
    ornekler: [
      { fr: 'Mes parents travaillent tous les deux.', tr: 'Annem de babam da çalışıyor.' },
      { fr: 'Je vis avec mes parents.', tr: 'Ailemle yaşıyorum.' },
    ],
    esdizim: ['mes parents', 'chez mes parents'],
    aile: ['le père', 'la mère', 'la famille'],
    hata: 'İngilizcedeki "parents" ile karıştırıp "akrabalar" sanmak. Fransızcada "les parents" hem anne-baba hem (bağlama göre) akraba olabilir; A1 düzeyinde anne-baba anlamındadır.',
    hatirlatma: '"Anne baba" anlamında her zaman ÇOĞUL kullanılır: mes parents. Tekil "le parent" ise "ebeveyn" demektir ve resmî metinlerde geçer.',
    uretim: {
      yonerge: '"Annem babam Bursa’da oturuyor." cümlesini yaz.',
      kabul: ['Mes parents habitent à Bursa', 'Mes parents habitent a Bursa'],
    },
  },
  {
    id: 'fr-frere',
    dil: 'fr',
    kelime: 'frère',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les frères',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Le garçon qui a les mêmes parents que toi.',
    turkceDestek: 'erkek kardeş',
    ipa: '/fʁɛʁ/',
    heceler: 'frè-re (iki "r" de gırtlaktan)',
    ornekler: [
      { fr: 'J’ai un frère et deux sœurs.', tr: 'Bir erkek kardeşim ve iki kız kardeşim var.' },
      { fr: 'Mon frère aîné a vingt ans.', tr: 'Ağabeyim yirmi yaşında.' },
    ],
    esdizim: ['un frère aîné', 'un petit frère', 'mon grand frère'],
    aile: ['la sœur', 'fraternel'],
    hata: 'Türkçedeki "kardeş" kelimesi cinsiyet belirtmez; öğrenci de "frère" ile "sœur"ü ayırmadan kullanır. Fransızcada bu ayrım zorunludur.',
    hatirlatma: 'Ağabey = le frère aîné, küçük erkek kardeş = le petit frère.',
    uretim: {
      yonerge: '"Bir erkek kardeşim var." cümlesini yaz.',
      kabul: ['J’ai un frère', "J'ai un frère", 'J ai un frere'],
    },
  },
  {
    id: 'fr-soeur',
    dil: 'fr',
    kelime: 'sœur',
    artikel: 'la',
    cins: 'disil',
    cogul: 'les sœurs',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'La fille qui a les mêmes parents que toi.',
    turkceDestek: 'kız kardeş',
    ipa: '/sœʁ/',
    heceler: 'sœur (tek hece · œ bitişik yazılır)',
    ornekler: [
      { fr: 'Ma sœur est plus jeune que moi.', tr: 'Kız kardeşim benden küçük.' },
      { fr: 'J’ai deux sœurs.', tr: 'İki kız kardeşim var.' },
    ],
    esdizim: ['ma grande sœur', 'ma petite sœur'],
    aile: ['le frère', 'la famille'],
    hata: '"œ" harfini "oe" diye ayrı yazmak. Yazımı "sœur"dur; klavyede œ yoksa "soeur" kabul edilir ama doğru biçim bitişiktir.',
    hatirlatma: 'Okunuşu "ör" gibidir; Türkçedeki "ö" sesine çok yakın.',
    uretim: {
      yonerge: '"İki kız kardeşim var." cümlesini yaz.',
      kabul: ['J’ai deux sœurs', "J'ai deux soeurs", 'J ai deux soeurs'],
    },
  },
  {
    id: 'fr-fils',
    dil: 'fr',
    kelime: 'fils',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les fils (değişmez)',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'L’enfant garçon de quelqu’un.',
    turkceDestek: 'oğul',
    ipa: '/fis/',
    heceler: 'fils ("fis" okunur · l HİÇ okunmaz)',
    ornekler: [
      { fr: 'Mon oncle a deux fils.', tr: 'Amcamın iki oğlu var.' },
      { fr: 'C’est le fils de mon voisin.', tr: 'Bu komşumun oğlu.' },
    ],
    esdizim: ['le fils aîné', 'père et fils'],
    aile: ['la fille', 'les enfants'],
    hata: 'Yazıldığı gibi "fils" diye okumak. Doğru okunuş "fis"tir; "l" okunmaz ve sondaki "s" OKUNUR — çoğu kelimenin tersi.',
    hatirlatma: 'Çoğulu da aynı yazılır: le fils → les fils. Fark yalnız artikelden anlaşılır.',
    uretim: {
      yonerge: '"Bu komşumun oğlu." cümlesini yaz.',
      kabul: ['C’est le fils de mon voisin', "C'est le fils de mon voisin"],
    },
  },
  {
    id: 'fr-fille',
    dil: 'fr',
    kelime: 'fille',
    artikel: 'la',
    cins: 'disil',
    cogul: 'les filles',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Un enfant de sexe féminin ; aussi : l’enfant fille de quelqu’un.',
    turkceDestek: 'kız; kız evlat',
    ipa: '/fij/',
    heceler: 'fil-le ("fiy" okunur)',
    ornekler: [
      { fr: 'C’est une fille très sympa.', tr: 'Çok cana yakın bir kız.' },
      { fr: 'Ils ont une fille et un fils.', tr: 'Bir kızları ve bir oğulları var.' },
    ],
    esdizim: ['une petite fille', 'une jeune fille'],
    aile: ['le fils', 'le garçon'],
    hata: 'Bağlamı ayırmamak: "la fille" hem "kız" hem "kız evlat" demektir. Hangisi olduğu cümleden anlaşılır.',
    hatirlatma: '"fille" → "fiy", ama "ville" → "vil". Bu ikisi karıştırılır; ezberlenmesi gereken bir çifttir.',
    uretim: {
      yonerge: '"Bir kız kardeşim ve bir erkek kardeşim var." cümlesini yaz.',
      kabul: ['J’ai une sœur et un frère', "J'ai une soeur et un frere"],
    },
  },
  {
    id: 'fr-maison',
    dil: 'fr',
    kelime: 'maison',
    artikel: 'la',
    cins: 'disil',
    cogul: 'les maisons',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Le bâtiment où une famille habite.',
    turkceDestek: 'ev',
    ipa: '/mɛ.zɔ̃/',
    heceler: 'mai-son ("ai" → "e", "on" nazal)',
    ornekler: [
      { fr: 'Notre maison est près de l’école.', tr: 'Evimiz okula yakın.' },
      { fr: 'Je rentre à la maison à six heures.', tr: 'Eve saat altıda dönüyorum.' },
    ],
    esdizim: ['à la maison', 'rentrer à la maison', 'une maison blanche'],
    aile: ['l’appartement', 'la chambre', 'le foyer'],
    hata: '"evde" demek için "dans la maison" kullanmak. Doğal biçim "à la maison"dur.',
    hatirlatma: 'İki sesli harf yan yana gelince tek ses olur: "ai" → "e". Bu kural yüzlerce kelimede geçerlidir.',
    uretim: {
      yonerge: '"Saat altıda eve dönüyorum." cümlesini yaz.',
      kabul: ['Je rentre à la maison à six heures', 'Je rentre a la maison a six heures'],
    },
  },
  {
    id: 'fr-chambre',
    dil: 'fr',
    kelime: 'chambre',
    artikel: 'la',
    cins: 'disil',
    cogul: 'les chambres',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'La pièce où on dort.',
    turkceDestek: 'oda (yatak odası)',
    ipa: '/ʃɑ̃bʁ/',
    heceler: 'cham-bre ("ch" → "ş", "am" nazal)',
    ornekler: [
      { fr: 'Ma chambre est petite mais jolie.', tr: 'Odam küçük ama şirin.' },
      { fr: 'Range ta chambre, s’il te plaît !', tr: 'Odanı topla, lütfen!' },
    ],
    esdizim: ['ranger sa chambre', 'une chambre d’hôtel'],
    aile: ['la maison', 'le salon', 'la cuisine'],
    hata: '"ch" harflerini "ç" okumak. Fransızcada "ch" her zaman "ş" sesidir: chambre → "şambr".',
    hatirlatma: 'Otelde "une chambre" oda demektir; ev içindeki her oda değil, YATAK odasıdır.',
    uretim: {
      yonerge: '"Odam küçük." cümlesini yaz (sıfat uyumuna dikkat).',
      kabul: ['Ma chambre est petite'],
    },
  },
  {
    id: 'fr-livre',
    dil: 'fr',
    kelime: 'livre',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les livres',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Un objet fait de pages, que l’on lit.',
    turkceDestek: 'kitap',
    ipa: '/livʁ/',
    heceler: 'li-vre (tek hece gibi: "livr")',
    ornekler: [
      { fr: 'Je lis un livre français.', tr: 'Fransızca bir kitap okuyorum.' },
      { fr: 'Le livre est sur la table.', tr: 'Kitap masanın üstünde.' },
    ],
    esdizim: ['lire un livre', 'un livre de français'],
    aile: ['lire', 'la librairie', 'la bibliothèque'],
    hata: '"la librairie" kelimesini "kütüphane" sanmak. Librairie = kitapçı, bibliothèque = kütüphane. Bu klasik bir yanlış dosttur.',
    hatirlatma: 'Dişil biçimi "la livre" başka bir kelimedir: yarım kilo / sterlin. Artikel anlamı değiştirir.',
    uretim: {
      yonerge: '"Bir kitap okuyorum." cümlesini yaz.',
      kabul: ['Je lis un livre'],
    },
  },
  {
    id: 'fr-stylo',
    dil: 'fr',
    kelime: 'stylo',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les stylos',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'L’objet avec lequel on écrit.',
    turkceDestek: 'tükenmez kalem',
    ipa: '/sti.lo/',
    heceler: 'sty-lo ("y" burada "i" okunur)',
    ornekler: [
      { fr: 'Tu as un stylo, s’il te plaît ?', tr: 'Kalemin var mı, lütfen?' },
      { fr: 'Je cherche mon stylo bleu.', tr: 'Mavi kalemimi arıyorum.' },
    ],
    esdizim: ['un stylo bleu', 'prêter un stylo'],
    aile: ['le crayon', 'écrire', 'la trousse'],
    hata: '"chercher pour" demek. İngilizcedeki "look for" edatı Fransızcaya taşınmaz: "Je cherche mon stylo".',
    hatirlatma: 'Kurşun kalem "le crayon"dur; ikisi farklı kelimelerdir.',
    uretim: {
      yonerge: '"Kalemimi arıyorum." cümlesini yaz.',
      kabul: ['Je cherche mon stylo'],
    },
  },
  {
    id: 'fr-sac',
    dil: 'fr',
    kelime: 'sac',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les sacs',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Un objet dans lequel on met ses affaires pour les transporter.',
    turkceDestek: 'çanta',
    ipa: '/sak/',
    heceler: 'sac (sondaki c OKUNUR — istisna)',
    ornekler: [
      { fr: 'Mon sac est très lourd aujourd’hui.', tr: 'Çantam bugün çok ağır.' },
      { fr: 'Où est ton sac à dos ?', tr: 'Sırt çantan nerede?' },
    ],
    esdizim: ['un sac à dos', 'un sac à main'],
    aile: ['la valise', 'la trousse'],
    hata: 'Son sessizlerin okunmadığı kuralını buraya da uygulamak. "sac" kelimesinde "c" okunur; c, r, f, l harfleri sonda çoğu zaman okunur.',
    hatirlatma: 'Hatırlatıcı kısaltma: C-R-F-L ("careful" kelimesindeki sessizler) sonda genelde okunur.',
    uretim: {
      yonerge: '"Çantam ağır." cümlesini yaz.',
      kabul: ['Mon sac est lourd'],
    },
  },
  {
    id: 'fr-table',
    dil: 'fr',
    kelime: 'table',
    artikel: 'la',
    cins: 'disil',
    cogul: 'les tables',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Un meuble avec un plateau et des pieds, où l’on mange ou travaille.',
    turkceDestek: 'masa',
    ipa: '/tabl/',
    heceler: 'ta-ble (sondaki e okunmaz: "tabl")',
    ornekler: [
      { fr: 'Il y a un livre sur la table.', tr: 'Masanın üstünde bir kitap var.' },
      { fr: 'On mange à table à sept heures.', tr: 'Saat yedide sofraya oturuyoruz.' },
    ],
    esdizim: ['sur la table', 'mettre la table', 'à table !'],
    aile: ['la chaise', 'le bureau'],
    hata: '"var" demek için "il est" kullanmak: "Il est un livre sur la table" yanlıştır; doğrusu "Il y a un livre sur la table".',
    hatirlatma: '"À table !" tek başına "sofraya!" anlamında bir çağrıdır.',
    uretim: {
      yonerge: '"Masanın üstünde bir kitap var." cümlesini yaz.',
      kabul: ['Il y a un livre sur la table'],
    },
  },
  {
    id: 'fr-chien',
    dil: 'fr',
    kelime: 'chien',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les chiens',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Un animal domestique qui aboie.',
    turkceDestek: 'köpek',
    ipa: '/ʃjɛ̃/',
    heceler: 'chien ("şiyen" · sonu nazal)',
    ornekler: [
      { fr: 'Nous avons un chien noir.', tr: 'Siyah bir köpeğimiz var.' },
      { fr: 'Le chien de mon voisin est gentil.', tr: 'Komşumun köpeği uysal.' },
    ],
    esdizim: ['promener le chien', 'un chien de garde'],
    aile: ['le chat', 'l’animal'],
    hata: 'Renk sıfatını ismin önüne koymak: "un noir chien" değil, "un chien noir". Renkler her zaman isimden SONRA gelir.',
    hatirlatma: 'Dişil biçimi "la chienne"dir; sondaki sessiz ikizlenip -e eklenir.',
    uretim: {
      yonerge: '"Siyah bir köpeğimiz var." cümlesini yaz.',
      kabul: ['Nous avons un chien noir', 'On a un chien noir'],
    },
  },
  {
    id: 'fr-chat',
    dil: 'fr',
    kelime: 'chat',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les chats',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Un petit animal domestique qui miaule.',
    turkceDestek: 'kedi',
    ipa: '/ʃa/',
    heceler: 'chat ("şa" · sondaki t okunmaz)',
    ornekler: [
      { fr: 'Mon chat dort sur le canapé.', tr: 'Kedim kanepede uyuyor.' },
      { fr: 'J’aime beaucoup les chats.', tr: 'Kedileri çok seviyorum.' },
    ],
    esdizim: ['un chat noir', 'nourrir le chat'],
    aile: ['le chien', 'la chatte'],
    hata: 'Genel bir şeyi sevdiğini söylerken artikeli atlamak: "J’aime chats" değil, "J’aime LES chats". Fransızcada genel anlamda belirli artikel kullanılır.',
    hatirlatma: 'Sondaki "t" okunmaz ama dişilinde okunur: la chatte → "şat".',
    uretim: {
      yonerge: '"Kedileri seviyorum." cümlesini yaz.',
      kabul: ['J’aime les chats', "J'aime les chats"],
    },
  },
  {
    id: 'fr-voiture',
    dil: 'fr',
    kelime: 'voiture',
    artikel: 'la',
    cins: 'disil',
    cogul: 'les voitures',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Un véhicule à quatre roues pour transporter des personnes.',
    turkceDestek: 'araba',
    ipa: '/vwa.tyʁ/',
    heceler: 'voi-ture ("oi" → "ua": vua-TÜR)',
    ornekler: [
      { fr: 'Mon père a une voiture rouge.', tr: 'Babamın kırmızı bir arabası var.' },
      { fr: 'Je vais au lycée en voiture.', tr: 'Liseye arabayla gidiyorum.' },
    ],
    esdizim: ['en voiture', 'conduire une voiture'],
    aile: ['le bus', 'le train', 'conduire'],
    hata: 'Ulaşım aracıyla giderken "avec" kullanmak: "avec voiture" değil, "EN voiture".',
    hatirlatma: '"oi" harf ikilisi her zaman "ua" okunur: voiture, moi, trois, boire.',
    uretim: {
      yonerge: '"Kırmızı bir araba" ifadesini yaz.',
      kabul: ['une voiture rouge'],
    },
  },
  {
    id: 'fr-grand',
    dil: 'fr',
    kelime: 'grand / grande',
    tur: 'sifat',
    seviye: 'A1',
    fransizcaTanim: 'Qui a une taille importante ; le contraire de petit.',
    turkceDestek: 'büyük, uzun boylu',
    ipa: '/ɡʁɑ̃/ · dişil /ɡʁɑ̃d/',
    heceler: 'grand (eril: nazal, d okunmaz) · gran-de (dişil: d OKUNUR)',
    ornekler: [
      { fr: 'Paris est une grande ville.', tr: 'Paris büyük bir şehir.' },
      { fr: 'Mon frère est grand.', tr: 'Ağabeyim uzun boylu.' },
    ],
    esdizim: ['une grande ville', 'un grand frère', 'grand-mère'],
    aile: ['petit', 'la grandeur'],
    hata: 'Dişilde -e eklemeyi unutmak. Fark yalnız yazıda değil SESTE de vardır: "grand" → "gran", "grande" → "grand".',
    hatirlatma: 'İsimden ÖNCE gelen az sayıdaki sıfattan biridir: une grande ville (doğru), une ville grande (yanlış).',
    uretim: {
      yonerge: '"Büyük bir şehir" ifadesini yaz.',
      kabul: ['une grande ville'],
    },
  },
  {
    id: 'fr-petit',
    dil: 'fr',
    kelime: 'petit / petite',
    tur: 'sifat',
    seviye: 'A1',
    fransizcaTanim: 'Qui a une taille réduite ; le contraire de grand.',
    turkceDestek: 'küçük',
    ipa: '/pə.ti/ · dişil /pə.tit/',
    heceler: 'pe-tit (t okunmaz) · pe-ti-te (t OKUNUR)',
    ornekler: [
      { fr: 'J’habite dans un petit appartement.', tr: 'Küçük bir dairede oturuyorum.' },
      { fr: 'Ma petite sœur a huit ans.', tr: 'Küçük kız kardeşim sekiz yaşında.' },
    ],
    esdizim: ['un petit frère', 'une petite ville', 'petit à petit'],
    aile: ['grand', 'la petitesse'],
    hata: 'Dişilde "petite" yerine "petit" yazmak. Sondaki -e sesi de değiştirir; kulak farkı duyar.',
    hatirlatma: 'İsimden ÖNCE gelir. Önce gelen sıfatları hatırlamak için: Beauté-Âge-Nombre-Bonté-Taille (BANBT).',
    uretim: {
      yonerge: '"Odam küçük." cümlesini yaz.',
      kabul: ['Ma chambre est petite'],
    },
  },
  {
    id: 'fr-beau',
    dil: 'fr',
    kelime: 'beau / belle',
    tur: 'sifat',
    seviye: 'A1',
    fransizcaTanim: 'Qui plaît aux yeux ; agréable à regarder.',
    turkceDestek: 'güzel, yakışıklı',
    ipa: '/bo/ · dişil /bɛl/',
    heceler: 'beau ("bo") · bel-le ("bel")',
    ornekler: [
      { fr: 'C’est une belle maison.', tr: 'Bu güzel bir ev.' },
      { fr: 'Il fait beau aujourd’hui.', tr: 'Bugün hava güzel.' },
    ],
    esdizim: ['il fait beau', 'un bel homme', 'une belle journée'],
    aile: ['la beauté', 'joli'],
    hata: 'Dişilde "beaue" gibi bir biçim uydurmak. Bu sıfat tamamen biçim değiştirir: beau → belle.',
    hatirlatma: 'Sesli harfle başlayan eril isimden önce "bel" olur: un bel appartement.',
    uretim: {
      yonerge: '"Bu güzel bir ev." cümlesini yaz.',
      kabul: ['C’est une belle maison', "C'est une belle maison"],
    },
  },
  {
    id: 'fr-joli',
    dil: 'fr',
    kelime: 'joli / jolie',
    tur: 'sifat',
    seviye: 'A1',
    fransizcaTanim: 'Agréable à regarder, mignon.',
    turkceDestek: 'şirin, hoş',
    ipa: '/ʒɔ.li/',
    heceler: 'jo-li ("j" Türkçedeki gibi yumuşak)',
    ornekler: [
      { fr: 'Elle a une jolie robe bleue.', tr: 'Üzerinde şirin mavi bir elbise var.' },
      { fr: 'C’est un joli prénom.', tr: 'Bu hoş bir isim.' },
    ],
    esdizim: ['une jolie fille', 'un joli jardin'],
    aile: ['beau', 'mignon'],
    hata: 'Sıfat sırasını karıştırmak: "une jolie robe bleue" — "jolie" isimden önce, renk isimden sonra gelir. İkisi aynı cümlede farklı yerlerdedir.',
    hatirlatma: 'Dişilinde okunuş değişmez, yalnız yazım değişir: joli / jolie.',
    uretim: {
      yonerge: '"Şirin mavi bir elbise" ifadesini yaz.',
      kabul: ['une jolie robe bleue'],
    },
  },
  {
    id: 'fr-il-y-a',
    dil: 'fr',
    kelime: 'il y a',
    tur: 'kalip',
    seviye: 'A1',
    fransizcaTanim: 'Expression qui sert à dire qu’une chose existe quelque part.',
    turkceDestek: 'var',
    ipa: '/i.lja/',
    heceler: 'il-y-a (bitişik okunur: "i-lya")',
    ornekler: [
      { fr: 'Il y a trois chambres dans notre maison.', tr: 'Evimizde üç oda var.' },
      { fr: 'Il n’y a pas de pain.', tr: 'Ekmek yok.' },
    ],
    esdizim: ['il y a … dans', 'il n’y a pas de', 'qu’est-ce qu’il y a ?'],
    aile: ['avoir', 'être'],
    hata: 'Tekil-çoğul için ayrı biçim aramak. "Il y a" hiç değişmez: il y a un livre / il y a des livres.',
    hatirlatma: 'Olumsuzu "il n’y a pas DE"dir; olumsuzda artikel "de"ye döner.',
    uretim: {
      yonerge: '"Evimizde üç oda var." cümlesini yaz.',
      kabul: ['Il y a trois chambres dans notre maison', 'Il y a trois chambres'],
    },
  },
]
