/**
 * A1 — GÜNLÜK RUTİN VE ZAMAN
 * ==================================================================
 *
 * Bu havuzun iki özel yükü var:
 *   1. DÖNÜŞLÜ FİİLLER (se lever, se coucher). Türkçede karşılığı yok;
 *      fiilin önündeki zamir özneye göre değişir ve düşürülemez.
 *   2. SIKLIK ZARFLARI. Türkçede zarf cümlenin başına ya da fiilin önüne
 *      gelir; Fransızcada çekimli fiilden SONRA gelir.
 *
 * Her isimde artikel, cins ve çoğul; her düzensiz fiilde çekim doludur.
 */

export const KELIMELER = [
  {
    id: 'fr-se-lever',
    dil: 'fr',
    kelime: 'se lever',
    cekim: 'je me lève · tu te lèves · il se lève · nous nous levons · vous vous levez · ils se lèvent',
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    fransizcaTanim: 'Sortir du lit ; se mettre debout.',
    turkceDestek: 'kalkmak (yataktan)',
    ipa: '/sə lə.ve/',
    heceler: 'se le-ver (je me lève: "mö LEV")',
    ornekler: [
      { fr: 'Je me lève à sept heures.', tr: 'Saat yedide kalkıyorum.' },
      { fr: 'Le week-end, on se lève tard.', tr: 'Hafta sonu geç kalkıyoruz.' },
    ],
    esdizim: ['se lever tôt', 'se lever tard'],
    aile: ['se coucher', 'lever'],
    hata: 'Dönüşlü zamiri düşürmek: "Je lève à sept heures" yanlıştır. Zamir fiilin parçasıdır ve özneye göre değişir.',
    hatirlatma: 'Çekimde "e" harfi "è" olur: je me LÈVE. Bu, vurgunun oraya kaymasındandır.',
    uretim: { yonerge: '"Saat yedide kalkıyorum." cümlesini yaz.', kabul: ['Je me lève à sept heures', 'Je me leve a sept heures'] },
  },
  {
    id: 'fr-se-coucher',
    dil: 'fr',
    kelime: 'se coucher',
    cekim: 'je me couche · tu te couches · il se couche · nous nous couchons · vous vous couchez · ils se couchent',
    tur: 'fiil',
    seviye: 'A1',
    fransizcaTanim: 'Aller au lit pour dormir.',
    turkceDestek: 'yatmak',
    ipa: '/sə ku.ʃe/',
    heceler: 'se cou-cher ("ku-ŞE")',
    ornekler: [
      { fr: 'Je me couche à onze heures.', tr: 'Saat on birde yatıyorum.' },
      { fr: 'Couche-toi tôt ce soir !', tr: 'Bu akşam erken yat!' },
    ],
    esdizim: ['se coucher tôt', 'se coucher tard'],
    aile: ['se lever', 'dormir', 'le lit'],
    hata: '"se coucher" (yatmak) ile "dormir" (uyumak) karıştırılır. Yatağa girmek ile uyumak ayrı fiillerdir.',
    hatirlatma: 'Emir kipinde zamir fiilden SONRA gelir ve tire alır: Couche-toi !',
    uretim: { yonerge: '"Saat on birde yatıyorum." cümlesini yaz.', kabul: ['Je me couche à onze heures', 'Je me couche a onze heures'] },
  },
  {
    id: 'fr-heure',
    dil: 'fr',
    kelime: 'heure',
    artikel: "l'",
    cins: 'disil',
    cogul: 'les heures',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Unité de temps de soixante minutes ; aussi le moment de la journée.',
    turkceDestek: 'saat',
    ipa: '/œʁ/',
    heceler: 'heu-re (baştaki h okunmaz: "ör")',
    ornekler: [
      { fr: 'Il est trois heures et demie.', tr: 'Saat üç buçuk.' },
      { fr: 'Le cours dure deux heures.', tr: 'Ders iki saat sürüyor.' },
    ],
    esdizim: ['Quelle heure est-il ?', 'à quelle heure', 'une demi-heure'],
    aile: ['la minute', 'le temps'],
    hata: 'Saat söylerken "heures" kelimesini düşürmek: "Il est trois" değil, "Il est trois heures".',
    hatirlatma: 'Sesli harfle başladığı için liaison olur: "deux heures" → "dö-zör", "trois heures" → "trua-zör".',
    uretim: { yonerge: '"Saat üç." cümlesini yaz.', kabul: ['Il est trois heures'] },
  },
  {
    id: 'fr-matin',
    dil: 'fr',
    kelime: 'matin',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les matins',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'La première partie de la journée, avant midi.',
    turkceDestek: 'sabah',
    ipa: '/ma.tɛ̃/',
    heceler: 'ma-tin (sonu nazal "en")',
    ornekler: [
      { fr: 'Le matin, je prends un café.', tr: 'Sabahları kahve içerim.' },
      { fr: 'À demain matin !', tr: 'Yarın sabah görüşürüz!' },
    ],
    esdizim: ['le matin', 'ce matin', 'demain matin'],
    aile: ['le soir', 'la matinée', "l'après-midi"],
    hata: 'Alışkanlık anlatırken artikeli düşürmek: "Matin je travaille" değil, "LE matin je travaille". Belirli artikel burada "her sabah" anlamı verir.',
    hatirlatma: '"le matin" = her sabah (alışkanlık) · "ce matin" = bu sabah (tek sefer).',
    uretim: { yonerge: '"Sabahları kahve içerim." cümlesini yaz.', kabul: ['Le matin je prends un café', 'Le matin, je prends un café'] },
  },
  {
    id: 'fr-soir',
    dil: 'fr',
    kelime: 'soir',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les soirs',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'La fin de la journée, après le coucher du soleil.',
    turkceDestek: 'akşam',
    ipa: '/swaʁ/',
    heceler: 'soir ("suar" · oi → ua)',
    ornekler: [
      { fr: 'Le soir, je fais mes devoirs.', tr: 'Akşamları ödevlerimi yaparım.' },
      { fr: 'On se voit ce soir ?', tr: 'Bu akşam görüşelim mi?' },
    ],
    esdizim: ['ce soir', 'le soir', 'bonne soirée'],
    aile: ['le matin', 'la soirée', 'la nuit'],
    hata: '"le soir" (akşam) ile "la soirée" (akşam boyu, davet) karıştırılır. İkincisi süreyi ya da etkinliği anlatır.',
    hatirlatma: '"Bonsoir" (selam) ile "bonne soirée" (iyi akşamlar dileği) farklıdır: biri karşılaşma, diğeri veda.',
    uretim: { yonerge: '"Akşamları ödev yaparım." cümlesini yaz.', kabul: ['Le soir je fais mes devoirs', 'Le soir, je fais mes devoirs'] },
  },
  {
    id: 'fr-journee',
    dil: 'fr',
    kelime: 'journée',
    artikel: 'la',
    cins: 'disil',
    cogul: 'les journées',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Le temps entre le matin et le soir, considéré dans sa durée.',
    turkceDestek: 'gün (baştan sona)',
    ipa: '/ʒuʁ.ne/',
    heceler: 'jour-née ("jur-NE")',
    ornekler: [
      { fr: 'Bonne journée !', tr: 'İyi günler!' },
      { fr: 'J’ai passé une bonne journée.', tr: 'Güzel bir gün geçirdim.' },
    ],
    esdizim: ['bonne journée', 'toute la journée'],
    aile: ['le jour', 'la soirée', 'la matinée'],
    hata: 'İngilizcedeki "journey" ile karıştırıp "yolculuk" sanmak. Bu klasik bir yanlış dosttur: journée = gün, yolculuk = le voyage.',
    hatirlatma: '"le jour" günü bir NOKTA olarak, "la journée" bir SÜRE olarak anlatır.',
    uretim: { yonerge: 'Birine "iyi günler" dile.', kabul: ['Bonne journée', 'Bonne journée !'] },
  },
  {
    id: 'fr-semaine',
    dil: 'fr',
    kelime: 'semaine',
    artikel: 'la',
    cins: 'disil',
    cogul: 'les semaines',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Une période de sept jours.',
    turkceDestek: 'hafta',
    ipa: '/sə.mɛn/',
    heceler: 'se-mai-ne ("sö-MEN")',
    ornekler: [
      { fr: 'Cette semaine, j’ai trois examens.', tr: 'Bu hafta üç sınavım var.' },
      { fr: 'Je fais du sport deux fois par semaine.', tr: 'Haftada iki kez spor yapıyorum.' },
    ],
    esdizim: ['cette semaine', 'la semaine dernière', 'par semaine'],
    aile: ['le week-end', 'le mois'],
    hata: '"haftada iki kez" derken "dans la semaine" demek. Doğru kalıp "deux fois PAR semaine"dir.',
    hatirlatma: '"la semaine prochaine" = gelecek hafta · "la semaine dernière" = geçen hafta.',
    uretim: { yonerge: '"Haftada iki kez spor yapıyorum." cümlesini yaz.', kabul: ['Je fais du sport deux fois par semaine'] },
  },
  {
    id: 'fr-week-end',
    dil: 'fr',
    kelime: 'week-end',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les week-ends',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Le samedi et le dimanche.',
    turkceDestek: 'hafta sonu',
    ipa: '/wi.kɛnd/',
    heceler: 'week-end ("vi-KEND")',
    ornekler: [
      { fr: 'Le week-end, je reste à la maison.', tr: 'Hafta sonu evde kalıyorum.' },
      { fr: 'Bon week-end !', tr: 'İyi hafta sonları!' },
    ],
    esdizim: ['ce week-end', 'le week-end', 'bon week-end'],
    aile: ['samedi', 'dimanche', 'la semaine'],
    hata: 'İngilizceden geldiği için "the weekend" gibi kullanmak. Fransızcada artikel zorunludur ve tire ile yazılır: LE week-end.',
    hatirlatma: 'Fransızcaya İngilizceden geçmiş kelimelerden biridir; okunuşu da İngilizceye yakındır.',
    uretim: { yonerge: '"Hafta sonu evde kalıyorum." cümlesini yaz.', kabul: ['Le week-end je reste à la maison', 'Le week-end, je reste à la maison'] },
  },
  {
    id: 'fr-aller',
    dil: 'fr',
    kelime: 'aller',
    cekim: 'je vais · tu vas · il va · nous allons · vous allez · ils vont',
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    fransizcaTanim: 'Se déplacer vers un endroit.',
    turkceDestek: 'gitmek',
    ipa: '/a.le/',
    heceler: 'al-ler ("a-LE")',
    ornekler: [
      { fr: 'Je vais au lycée en bus.', tr: 'Liseye otobüsle gidiyorum.' },
      { fr: 'Nous allons à Paris cet été.', tr: 'Bu yaz Paris’e gidiyoruz.' },
    ],
    esdizim: ['aller à', 'aller en', 'ça va ?', 'aller + mastar (yakın gelecek)'],
    aile: ['venir', "s'en aller"],
    hata: 'Çekimi düzenli sanmak: "je alle" diye bir biçim yoktur. Bu fiil tamamen düzensizdir ve ezberlenmelidir.',
    hatirlatma: 'Yakın geleceği de bu fiil kurar: "Je vais manger" = "yemek yiyeceğim".',
    uretim: { yonerge: '"Liseye gidiyorum." cümlesini yaz.', kabul: ['Je vais au lycée', 'Je vais au lycee'] },
  },
  {
    id: 'fr-faire',
    dil: 'fr',
    kelime: 'faire',
    cekim: 'je fais · tu fais · il fait · nous faisons · vous faites · ils font',
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    fransizcaTanim: 'Réaliser une action, fabriquer ou pratiquer quelque chose.',
    turkceDestek: 'yapmak',
    ipa: '/fɛʁ/',
    heceler: 'fai-re ("fer")',
    ornekler: [
      { fr: 'Je fais mes devoirs le soir.', tr: 'Ödevlerimi akşam yapıyorum.' },
      { fr: 'Qu’est-ce que tu fais ?', tr: 'Ne yapıyorsun?' },
    ],
    esdizim: ['faire du sport', 'faire les courses', 'faire attention', 'il fait beau'],
    aile: ['refaire', 'le fait'],
    hata: '"vous faites" biçimini "vous faisez" diye düzenli çekmek. Bu, Fransızcadaki üç düzensiz "vous" biçiminden biridir (êtes, faites, dites).',
    hatirlatma: 'Hava durumu da bu fiille kurulur: "Il fait beau", "Il fait froid".',
    uretim: { yonerge: '"Ödevlerimi yapıyorum." cümlesini yaz.', kabul: ['Je fais mes devoirs'] },
  },
  {
    id: 'fr-prendre',
    dil: 'fr',
    kelime: 'prendre',
    cekim: 'je prends · tu prends · il prend · nous prenons · vous prenez · ils prennent',
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    fransizcaTanim: 'Saisir quelque chose ; utiliser un moyen de transport ; consommer.',
    turkceDestek: 'almak; (araca) binmek; (yiyecek) yemek/içmek',
    ipa: '/pʁɑ̃dʁ/',
    heceler: 'pren-dre (ilk hece nazal)',
    ornekler: [
      { fr: 'Je prends le bus tous les matins.', tr: 'Her sabah otobüse biniyorum.' },
      { fr: 'Tu prends un café ?', tr: 'Kahve alır mısın?' },
    ],
    esdizim: ['prendre le bus', 'prendre le petit-déjeuner', 'prendre une décision'],
    aile: ['apprendre', 'comprendre', 'reprendre'],
    hata: 'Otobüse binmek için "monter" kullanmak. Fransızcada ulaşım aracıyla gitmek "prendre" fiiliyle anlatılır: prendre le bus.',
    hatirlatma: 'Aynı kökten iki önemli fiil: apprendre (öğrenmek), comprendre (anlamak). Üçü de aynı çekilir.',
    uretim: { yonerge: '"Otobüse biniyorum." cümlesini yaz.', kabul: ['Je prends le bus'] },
  },
  {
    id: 'fr-manger',
    dil: 'fr',
    kelime: 'manger',
    cekim: 'je mange · tu manges · il mange · nous mangeons · vous mangez · ils mangent',
    tur: 'fiil',
    seviye: 'A1',
    fransizcaTanim: 'Mettre de la nourriture dans sa bouche et l’avaler.',
    turkceDestek: 'yemek',
    ipa: '/mɑ̃.ʒe/',
    heceler: 'man-ger (ilk hece nazal, "je" sesi)',
    ornekler: [
      { fr: 'Je mange à la cantine à midi.', tr: 'Öğlen kantinde yemek yiyorum.' },
      { fr: 'Nous mangeons du poisson le vendredi.', tr: 'Cuma günleri balık yeriz.' },
    ],
    esdizim: ['manger à la cantine', 'manger dehors'],
    aile: ['le repas', 'la nourriture'],
    hata: '"nous mangeons" biçiminde "e" harfini düşürmek. "g" harfinin yumuşak kalması için araya "e" konur: mangEons.',
    hatirlatma: 'Türkçedeki "yemek yemek" ikilemesi Fransızcada yoktur; tek fiil yeter.',
    uretim: { yonerge: '"Kantinde yemek yiyorum." cümlesini yaz.', kabul: ['Je mange à la cantine', 'Je mange a la cantine'] },
  },
  {
    id: 'fr-travailler',
    dil: 'fr',
    kelime: 'travailler',
    cekim: 'je travaille · tu travailles · il travaille · nous travaillons · vous travaillez · ils travaillent',
    tur: 'fiil',
    seviye: 'A1',
    fransizcaTanim: 'Faire un métier ; étudier avec effort.',
    turkceDestek: 'çalışmak',
    ipa: '/tʁa.va.je/',
    heceler: 'tra-vail-ler ("ail" → "ay")',
    ornekler: [
      { fr: 'Ma mère travaille à l’hôpital.', tr: 'Annem hastanede çalışıyor.' },
      { fr: 'Je travaille mon français tous les jours.', tr: 'Her gün Fransızca çalışıyorum.' },
    ],
    esdizim: ['travailler dur', 'travailler à', 'le travail'],
    aile: ['le travail', 'le travailleur'],
    hata: 'Ders çalışmak için her zaman "étudier" aramak. Fransızcada "travailler" hem iş hem ders çalışmayı anlatır.',
    hatirlatma: 'İsim biçimi "le travail"dir ve çoğulu düzensizdir: les travaux.',
    uretim: { yonerge: '"Annem hastanede çalışıyor." cümlesini yaz.', kabul: ["Ma mère travaille à l'hôpital", 'Ma mère travaille à l’hôpital'] },
  },
  {
    id: 'fr-etudier',
    dil: 'fr',
    kelime: 'étudier',
    cekim: "j'étudie · tu étudies · il étudie · nous étudions · vous étudiez · ils étudient",
    tur: 'fiil',
    seviye: 'A1',
    fransizcaTanim: 'Apprendre une matière de façon régulière.',
    turkceDestek: 'ders çalışmak, okumak (bölüm)',
    ipa: '/e.ty.dje/',
    heceler: 'é-tu-di-er ("e-tü-DYE")',
    ornekler: [
      { fr: 'J’étudie le français depuis un an.', tr: 'Bir yıldır Fransızca çalışıyorum.' },
      { fr: 'Elle étudie la médecine.', tr: 'Tıp okuyor.' },
    ],
    esdizim: ['étudier une langue', 'étudier à l’université'],
    aile: ["l'étudiant", "l'étude"],
    hata: 'Sesli harfle başladığı için elizyon zorunludur: "je étudie" değil, "j’étudie".',
    hatirlatma: '"étudier" daha çok bir alanı, "travailler" ise çalışma eylemini anlatır.',
    uretim: { yonerge: '"Fransızca çalışıyorum." cümlesini yaz.', kabul: ["J'étudie le français", 'J’étudie le français'] },
  },
  {
    id: 'fr-dormir',
    dil: 'fr',
    kelime: 'dormir',
    cekim: 'je dors · tu dors · il dort · nous dormons · vous dormez · ils dorment',
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    fransizcaTanim: 'Se reposer les yeux fermés, sans conscience.',
    turkceDestek: 'uyumak',
    ipa: '/dɔʁ.miʁ/',
    heceler: 'dor-mir (iki "r" de gırtlaktan)',
    ornekler: [
      { fr: 'Je dors huit heures par nuit.', tr: 'Gecede sekiz saat uyuyorum.' },
      { fr: 'Le chat dort sur le canapé.', tr: 'Kedi kanepede uyuyor.' },
    ],
    esdizim: ['bien dormir', 'dormir tard'],
    aile: ['se coucher', "s'endormir", 'le sommeil'],
    hata: '"se coucher" (yatmak) ile karıştırmak. Yatağa girmek ile uyumak Fransızcada iki ayrı fiildir.',
    hatirlatma: 'Tekil çekimlerde kökün "m" harfi düşer: je DORS, ama nous DORMons.',
    uretim: { yonerge: '"Sekiz saat uyuyorum." cümlesini yaz.', kabul: ['Je dors huit heures'] },
  },
  {
    id: 'fr-commencer',
    dil: 'fr',
    kelime: 'commencer',
    cekim: 'je commence · nous commençons · ils commencent',
    tur: 'fiil',
    seviye: 'A1',
    fransizcaTanim: 'Faire le premier moment d’une action.',
    turkceDestek: 'başlamak',
    ipa: '/kɔ.mɑ̃.se/',
    heceler: 'com-men-cer (iki nazal arka arkaya)',
    ornekler: [
      { fr: 'Les cours commencent à huit heures.', tr: 'Dersler saat sekizde başlıyor.' },
      { fr: 'Nous commençons le livre demain.', tr: 'Kitaba yarın başlıyoruz.' },
    ],
    esdizim: ['commencer à + mastar', 'commencer par'],
    aile: ['le commencement', 'finir'],
    hata: '"nous commençons" biçiminde cédille (ç) unutulur. "c" harfinin "s" okunması için "o" önünde ç yazılır.',
    hatirlatma: 'Bir eyleme başlamak "commencer À + mastar" ile kurulur: Je commence à comprendre.',
    uretim: { yonerge: '"Dersler sekizde başlıyor." cümlesini yaz.', kabul: ['Les cours commencent à huit heures'] },
  },
  {
    id: 'fr-finir',
    dil: 'fr',
    kelime: 'finir',
    cekim: 'je finis · tu finis · il finit · nous finissons · vous finissez · ils finissent',
    tur: 'fiil',
    seviye: 'A1',
    fransizcaTanim: 'Arriver à la fin de quelque chose.',
    turkceDestek: 'bitirmek, bitmek',
    ipa: '/fi.niʁ/',
    heceler: 'fi-nir',
    ornekler: [
      { fr: 'Les cours finissent à cinq heures.', tr: 'Dersler saat beşte bitiyor.' },
      { fr: 'Je finis mes devoirs avant le dîner.', tr: 'Ödevlerimi akşam yemeğinden önce bitiriyorum.' },
    ],
    esdizim: ['finir de + mastar', 'finir ses devoirs'],
    aile: ['la fin', 'commencer'],
    hata: 'Çoğul kişilerde "-iss-" hecesini unutmak: "nous finons" değil, "nous finiSSons". Bu, -ir grubunun ayırt edici işaretidir.',
    hatirlatma: '-ir ile biten fiillerin en yaygın grubudur; choisir, réussir, grandir aynı biçimde çekilir.',
    uretim: { yonerge: '"Dersler beşte bitiyor." cümlesini yaz.', kabul: ['Les cours finissent à cinq heures'] },
  },
  {
    id: 'fr-cours',
    dil: 'fr',
    kelime: 'cours',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les cours (değişmez)',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Une leçon donnée par un professeur.',
    turkceDestek: 'ders',
    ipa: '/kuʁ/',
    heceler: 'cours ("kur" · sondaki s okunmaz)',
    ornekler: [
      { fr: 'J’ai cours de maths à dix heures.', tr: 'Saat onda matematik dersim var.' },
      { fr: 'Le cours de français est intéressant.', tr: 'Fransızca dersi ilginç.' },
    ],
    esdizim: ['avoir cours', 'le cours de', 'suivre un cours'],
    aile: ['la leçon', "l'école", 'le professeur'],
    hata: 'Çoğul yaparken -s eklemek: kelime zaten -s ile biter ve çoğulu değişmez.',
    hatirlatma: '"J’ai cours" kalıbında artikel kullanılmaz — "dersim var" demenin standart biçimidir.',
    uretim: { yonerge: '"Saat onda matematik dersim var." cümlesini yaz.', kabul: ['J’ai cours de maths à dix heures', "J'ai cours de maths à dix heures"] },
  },
  {
    id: 'fr-souvent',
    dil: 'fr',
    kelime: 'souvent',
    tur: 'zarf',
    seviye: 'A1',
    fransizcaTanim: 'De nombreuses fois, régulièrement.',
    turkceDestek: 'sık sık',
    ipa: '/su.vɑ̃/',
    heceler: 'sou-vent (sonu nazal)',
    ornekler: [
      { fr: 'Je vais souvent au cinéma.', tr: 'Sık sık sinemaya giderim.' },
      { fr: 'Il est souvent en retard.', tr: 'Sık sık geç kalıyor.' },
    ],
    esdizim: ['assez souvent', 'très souvent'],
    aile: ['toujours', 'parfois', 'jamais'],
    hata: 'Zarfı cümlenin başına koymak: "Souvent je vais" biçimi mümkün ama doğal değildir. Sıklık zarfı çekimli fiilden SONRA gelir.',
    hatirlatma: 'Sıralama: toujours (her zaman) > souvent (sık sık) > parfois (bazen) > rarement (nadiren) > jamais (asla).',
    uretim: { yonerge: '"Sık sık sinemaya giderim." cümlesini yaz.', kabul: ['Je vais souvent au cinéma', 'Je vais souvent au cinema'] },
  },
  {
    id: 'fr-toujours',
    dil: 'fr',
    kelime: 'toujours',
    tur: 'zarf',
    seviye: 'A1',
    fransizcaTanim: 'À chaque fois, sans exception.',
    turkceDestek: 'her zaman, hâlâ',
    ipa: '/tu.ʒuʁ/',
    heceler: 'tou-jours ("tu-JUR")',
    ornekler: [
      { fr: 'Je prends toujours le bus de huit heures.', tr: 'Her zaman sekiz otobüsüne binerim.' },
      { fr: 'Tu es toujours là ?', tr: 'Hâlâ orada mısın?' },
    ],
    esdizim: ['presque toujours', 'comme toujours'],
    aile: ['souvent', 'jamais'],
    hata: 'İki anlamını ayırmamak: bağlama göre "her zaman" ya da "hâlâ" demektir.',
    hatirlatma: 'Fiilden sonra gelir: "Je prends TOUJOURS…", "Toujours je prends" değil.',
    uretim: { yonerge: '"Her zaman otobüse binerim." cümlesini yaz.', kabul: ['Je prends toujours le bus'] },
  },
  {
    id: 'fr-tot',
    dil: 'fr',
    kelime: 'tôt',
    tur: 'zarf',
    seviye: 'A1',
    fransizcaTanim: 'Avant le moment habituel.',
    turkceDestek: 'erken',
    ipa: '/to/',
    heceler: 'tôt ("to" · şapkalı o)',
    ornekler: [
      { fr: 'Je me lève tôt le matin.', tr: 'Sabah erken kalkarım.' },
      { fr: 'Il est trop tôt pour partir.', tr: 'Gitmek için çok erken.' },
    ],
    esdizim: ['trop tôt', 'plus tôt', 'se lever tôt'],
    aile: ['tard', "l'heure"],
    hata: '"tôt" (erken) ile "bientôt" (yakında) karıştırılır. İkincisi zamanı değil, yakınlığı anlatır.',
    hatirlatma: 'Şapka (ê, ô) çoğu zaman kaybolmuş bir "s"in izidir; burada da eski yazımdan kalmadır.',
    uretim: { yonerge: '"Erken kalkarım." cümlesini yaz.', kabul: ['Je me lève tôt', 'Je me leve tot'] },
  },
  {
    id: 'fr-tard',
    dil: 'fr',
    kelime: 'tard',
    tur: 'zarf',
    seviye: 'A1',
    fransizcaTanim: 'Après le moment habituel.',
    turkceDestek: 'geç',
    ipa: '/taʁ/',
    heceler: 'tard (sondaki d okunmaz)',
    ornekler: [
      { fr: 'Le week-end, je me couche tard.', tr: 'Hafta sonu geç yatarım.' },
      { fr: 'Il est arrivé trop tard.', tr: 'Çok geç geldi.' },
    ],
    esdizim: ['trop tard', 'plus tard', 'à plus tard'],
    aile: ['tôt', 'en retard'],
    hata: '"tard" (geç, zaman olarak) ile "en retard" (gecikmiş) karıştırılır: "Je suis tard" değil, "Je suis EN RETARD".',
    hatirlatma: '"À plus tard !" = "sonra görüşürüz" demektir; günlük vedalaşmada çok kullanılır.',
    uretim: { yonerge: '"Geç yatıyorum." cümlesini yaz.', kabul: ['Je me couche tard'] },
  },
]
