/**
 * A1 — ŞEHİR, YER VE ULAŞIM
 * ==================================================================
 *
 * Bu havuzun özel yükü EDATLARDIR. Türkçede yer bildirmek tek bir ekle
 * yapılır ("okulda", "okula", "okuldan"). Fransızcada bunun için ayrı
 * kelimeler vardır ve seçim ismin cinsine göre değişir (au / à la / à l’).
 *
 * Bu yüzden her yer isminde artikel ve cins özellikle önemlidir: öğrenci
 * cinsi bilmeden edatı seçemez.
 */

export const KELIMELER = [
  {
    id: 'fr-gare',
    dil: 'fr',
    kelime: 'gare',
    artikel: 'la',
    cins: 'disil',
    cogul: 'les gares',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'L’endroit où les trains arrivent et partent.',
    turkceDestek: 'tren garı',
    ipa: '/ɡaʁ/',
    heceler: 'ga-re ("gar")',
    ornekler: [
      { fr: 'Le train part de la gare à huit heures.', tr: 'Tren gardan saat sekizde kalkıyor.' },
      { fr: 'Excusez-moi, où est la gare ?', tr: 'Affedersiniz, gar nerede?' },
    ],
    esdizim: ['aller à la gare', 'la gare routière'],
    aile: ['le train', "l'aéroport", 'la station'],
    hata: 'Dişil olduğu için "au" kullanmak: "au gare" değil, "À LA gare". Cins bilinmezse edat da yanlış seçilir.',
    hatirlatma: 'Otobüs terminali "la gare routière"dir; aynı kelime yolla da kullanılır.',
    uretim: { yonerge: '"Gara gidiyorum." cümlesini yaz.', kabul: ['Je vais à la gare', 'Je vais a la gare'] },
  },
  {
    id: 'fr-bus',
    dil: 'fr',
    kelime: 'bus',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les bus (değişmez)',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Un grand véhicule public qui transporte beaucoup de personnes.',
    turkceDestek: 'otobüs',
    ipa: '/bys/',
    heceler: 'bus ("büs" · sondaki s OKUNUR)',
    ornekler: [
      { fr: 'Je prends le bus tous les matins.', tr: 'Her sabah otobüse biniyorum.' },
      { fr: 'Le bus numéro douze va au centre-ville.', tr: 'On iki numaralı otobüs şehir merkezine gidiyor.' },
    ],
    esdizim: ['prendre le bus', 'en bus', "l'arrêt de bus"],
    aile: ['le métro', 'le train', 'le tram'],
    hata: '"avec le bus" demek. Ulaşım aracıyla gitmek "EN bus" biçiminde söylenir.',
    hatirlatma: 'Sondaki "s" burada okunur; bu, Fransızcanın "son sessiz okunmaz" kuralının istisnalarındandır.',
    uretim: { yonerge: '"Otobüsle gidiyorum." cümlesini yaz.', kabul: ['Je vais en bus', 'Je prends le bus'] },
  },
  {
    id: 'fr-metro',
    dil: 'fr',
    kelime: 'métro',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les métros',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Le train souterrain d’une grande ville.',
    turkceDestek: 'metro',
    ipa: '/me.tʁo/',
    heceler: 'mé-tro',
    ornekler: [
      { fr: 'À Paris, je prends toujours le métro.', tr: 'Paris’te hep metroya binerim.' },
      { fr: 'La station de métro est près d’ici.', tr: 'Metro istasyonu buraya yakın.' },
    ],
    esdizim: ['prendre le métro', 'en métro', 'la station de métro'],
    aile: ['le bus', 'le RER', 'la station'],
    hata: 'Metro durağı için "l’arrêt" demek. Metro ve tren için "la station", otobüs için "l’arrêt" kullanılır.',
    hatirlatma: 'Paris metrosunda hatlar numarayla, yön ise son durağın adıyla söylenir.',
    uretim: { yonerge: '"Metroya biniyorum." cümlesini yaz.', kabul: ['Je prends le métro', 'Je prends le metro'] },
  },
  {
    id: 'fr-rue',
    dil: 'fr',
    kelime: 'rue',
    artikel: 'la',
    cins: 'disil',
    cogul: 'les rues',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Un chemin dans une ville, avec des maisons des deux côtés.',
    turkceDestek: 'sokak, cadde',
    ipa: '/ʁy/',
    heceler: 'rue ("rü" · gırtlaktan r + ü)',
    ornekler: [
      { fr: 'J’habite dans la rue Victor Hugo.', tr: 'Victor Hugo sokağında oturuyorum.' },
      { fr: 'Traversez la rue et tournez à droite.', tr: 'Caddeyi geçin ve sağa dönün.' },
    ],
    esdizim: ['dans la rue', 'traverser la rue', 'au coin de la rue'],
    aile: ['l’avenue', 'le boulevard', 'la place'],
    hata: 'Adres verirken "sur la rue" demek (İngilizce "on the street" etkisi). Fransızcada "DANS la rue" denir.',
    hatirlatma: 'Fransızca adreslerde numara önce gelir: "12, rue Victor Hugo".',
    uretim: { yonerge: '"Bu sokakta oturuyorum." cümlesini yaz.', kabul: ['J’habite dans cette rue', "J'habite dans cette rue"] },
  },
  {
    id: 'fr-place',
    dil: 'fr',
    kelime: 'place',
    artikel: 'la',
    cins: 'disil',
    cogul: 'les places',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Un espace ouvert dans une ville, souvent avec des cafés.',
    turkceDestek: 'meydan; yer, koltuk',
    ipa: '/plas/',
    heceler: 'pla-ce ("plas")',
    ornekler: [
      { fr: 'On se retrouve sur la place à midi.', tr: 'Öğlen meydanda buluşuyoruz.' },
      { fr: 'Il n’y a plus de places dans le bus.', tr: 'Otobüste yer kalmadı.' },
    ],
    esdizim: ['sur la place', 'une place assise', 'la place principale'],
    aile: ['la rue', 'le parc'],
    hata: 'İki anlamını karıştırmak: hem "meydan" hem "oturacak yer" demektir. Bağlam ayırır.',
    hatirlatma: 'Meydanda "sur la place" denir, sokakta ise "dans la rue" — edatlar farklıdır.',
    uretim: { yonerge: '"Meydanda buluşalım." cümlesini yaz.', kabul: ['On se retrouve sur la place', 'Rendez-vous sur la place'] },
  },
  {
    id: 'fr-magasin',
    dil: 'fr',
    kelime: 'magasin',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les magasins',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'L’endroit où on achète des choses.',
    turkceDestek: 'mağaza, dükkân',
    ipa: '/ma.ɡa.zɛ̃/',
    heceler: 'ma-ga-sin (sonu nazal "en")',
    ornekler: [
      { fr: 'Le magasin ouvre à neuf heures.', tr: 'Mağaza dokuzda açılıyor.' },
      { fr: 'Je vais au magasin acheter du pain.', tr: 'Ekmek almak için dükkâna gidiyorum.' },
    ],
    esdizim: ['aller au magasin', 'un grand magasin'],
    aile: ['la boutique', 'le supermarché'],
    hata: '"le magasin" (mağaza) ile "le magazine" (dergi) karıştırılır; yazımları ve anlamları farklıdır.',
    hatirlatma: 'Eril olduğu için "au magasin" denir (à + le).',
    uretim: { yonerge: '"Mağazaya gidiyorum." cümlesini yaz.', kabul: ['Je vais au magasin'] },
  },
  {
    id: 'fr-ecole',
    dil: 'fr',
    kelime: 'école',
    artikel: "l'",
    cins: 'disil',
    cogul: 'les écoles',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'L’endroit où les enfants apprennent.',
    turkceDestek: 'okul',
    ipa: '/e.kɔl/',
    heceler: 'é-co-le ("e-KOL")',
    ornekler: [
      { fr: 'Je vais à l’école à pied.', tr: 'Okula yürüyerek gidiyorum.' },
      { fr: 'L’école commence à huit heures.', tr: 'Okul saat sekizde başlıyor.' },
    ],
    esdizim: ["aller à l'école", "l'école primaire"],
    aile: ['le lycée', 'le collège', "l'université"],
    hata: 'Artikeli "l’" olduğu için cinsiyetsiz sanmak. Kelime DİŞİLDİR: "une grande école".',
    hatirlatma: 'Fransız sisteminde école ilkokul, collège ortaokul, lycée lisedir.',
    uretim: { yonerge: '"Okula gidiyorum." cümlesini yaz.', kabul: ["Je vais à l'école", 'Je vais à l’école', 'Je vais a l ecole'] },
  },
  {
    id: 'fr-lycee',
    dil: 'fr',
    kelime: 'lycée',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les lycées',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'L’établissement scolaire après le collège, avant l’université.',
    turkceDestek: 'lise',
    ipa: '/li.se/',
    heceler: 'ly-cée ("li-SE")',
    ornekler: [
      { fr: 'Je suis élève au lycée.', tr: 'Lisede öğrenciyim.' },
      { fr: 'Mon lycée est près de la gare.', tr: 'Lisem gara yakın.' },
    ],
    esdizim: ['aller au lycée', 'au lycée', 'un lycéen'],
    aile: ["l'école", 'le collège', "l'élève"],
    hata: '-ée ile bitmesine rağmen ERİL olması. "-ée" genelde dişildir ama lycée ve musée istisnadır.',
    hatirlatma: 'Öğrencisine "un lycéen / une lycéenne" denir.',
    uretim: { yonerge: '"Liseye gidiyorum." cümlesini yaz.', kabul: ['Je vais au lycée', 'Je vais au lycee'] },
  },
  {
    id: 'fr-parc',
    dil: 'fr',
    kelime: 'parc',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les parcs',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Un grand jardin public où on se promène.',
    turkceDestek: 'park',
    ipa: '/paʁk/',
    heceler: 'parc (sondaki c OKUNUR)',
    ornekler: [
      { fr: 'Le dimanche, je vais au parc avec mes amis.', tr: 'Pazar günleri arkadaşlarımla parka giderim.' },
      { fr: 'Il y a un grand parc près de chez moi.', tr: 'Evimin yakınında büyük bir park var.' },
    ],
    esdizim: ['aller au parc', 'se promener dans le parc'],
    aile: ['le jardin', 'la place'],
    hata: 'Sondaki "c" harfini okumamak. C, R, F, L harfleri kelime sonunda genelde okunur.',
    hatirlatma: '"près de chez moi" = evimin yakınında — çok kullanılan bir kalıptır.',
    uretim: { yonerge: '"Parka gidiyorum." cümlesini yaz.', kabul: ['Je vais au parc'] },
  },
  {
    id: 'fr-droite',
    dil: 'fr',
    kelime: 'droite',
    artikel: 'la',
    cins: 'disil',
    cogul: 'çoğulu kullanılmaz',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Le côté opposé à la gauche.',
    turkceDestek: 'sağ',
    ipa: '/dʁwat/',
    heceler: 'droi-te ("druat")',
    ornekler: [
      { fr: 'Tournez à droite après la banque.', tr: 'Bankadan sonra sağa dönün.' },
      { fr: 'La pharmacie est à droite.', tr: 'Eczane sağda.' },
    ],
    esdizim: ['à droite', 'tourner à droite', 'sur votre droite'],
    aile: ['la gauche', 'tout droit'],
    hata: '"à droite" (sağa/sağda) ile "tout droit" (dosdoğru) karıştırılır. İkisi tamamen farklı yön verir.',
    hatirlatma: 'Yön tarifinde en çok karışan çift budur: "tout droit" = düz devam.',
    uretim: { yonerge: '"Sağa dönün." cümlesini yaz.', kabul: ['Tournez à droite', 'Tournez a droite'] },
  },
  {
    id: 'fr-gauche',
    dil: 'fr',
    kelime: 'gauche',
    artikel: 'la',
    cins: 'disil',
    cogul: 'çoğulu kullanılmaz',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Le côté opposé à la droite.',
    turkceDestek: 'sol',
    ipa: '/ɡoʃ/',
    heceler: 'gau-che ("goş")',
    ornekler: [
      { fr: 'Tournez à gauche au feu.', tr: 'Işıkta sola dönün.' },
      { fr: 'Le musée est à gauche.', tr: 'Müze solda.' },
    ],
    esdizim: ['à gauche', 'tourner à gauche'],
    aile: ['la droite', 'tout droit'],
    hata: '"au" edatını kullanmak: "au gauche" değil, "À gauche".',
    hatirlatma: '"au feu" = ışıkta (trafik ışığı) demektir; yön tarifinde çok geçer.',
    uretim: { yonerge: '"Sola dönün." cümlesini yaz.', kabul: ['Tournez à gauche', 'Tournez a gauche'] },
  },
  {
    id: 'fr-tout-droit',
    dil: 'fr',
    kelime: 'tout droit',
    tur: 'kalip',
    seviye: 'A1',
    fransizcaTanim: 'Sans tourner, dans la même direction.',
    turkceDestek: 'dosdoğru, düz',
    ipa: '/tu dʁwa/',
    heceler: 'tout droit ("tu drua")',
    ornekler: [
      { fr: 'Allez tout droit jusqu’à la place.', tr: 'Meydana kadar dosdoğru gidin.' },
      { fr: 'Continuez tout droit, c’est à cent mètres.', tr: 'Düz devam edin, yüz metre ileride.' },
    ],
    esdizim: ['aller tout droit', 'continuer tout droit'],
    aile: ['à droite', 'à gauche'],
    hata: '"à droite" ile karıştırmak. "tout droit" dönmeden devam etmektir; "à droite" sağa dönmektir.',
    hatirlatma: 'Sondaki "t" harflerinin ikisi de okunmaz: "tu drua".',
    uretim: { yonerge: '"Dosdoğru gidin." cümlesini yaz.', kabul: ['Allez tout droit', 'Continuez tout droit'] },
  },
  {
    id: 'fr-loin',
    dil: 'fr',
    kelime: 'loin',
    tur: 'zarf',
    seviye: 'A1',
    fransizcaTanim: 'À une grande distance.',
    turkceDestek: 'uzak',
    ipa: '/lwɛ̃/',
    heceler: 'loin ("luen" · nazal)',
    ornekler: [
      { fr: 'C’est loin d’ici ?', tr: 'Buraya uzak mı?' },
      { fr: 'Le lycée n’est pas loin de la maison.', tr: 'Lise evden uzak değil.' },
    ],
    esdizim: ['loin de', 'pas loin', 'trop loin'],
    aile: ['près', 'à côté de'],
    hata: '"loin" ile "près" kullanırken "de" edatını unutmak: "loin la gare" değil, "loin DE la gare".',
    hatirlatma: 'Karşıtı "près"tir: "près de la gare" = gara yakın.',
    uretim: { yonerge: '"Buraya uzak mı?" sorusunu yaz.', kabul: ["C'est loin d'ici", 'C’est loin d’ici'] },
  },
  {
    id: 'fr-pres',
    dil: 'fr',
    kelime: 'près (de)',
    tur: 'zarf',
    seviye: 'A1',
    fransizcaTanim: 'À une petite distance.',
    turkceDestek: 'yakın',
    ipa: '/pʁɛ/',
    heceler: 'près ("pre" · sondaki s okunmaz)',
    ornekler: [
      { fr: 'J’habite près du lycée.', tr: 'Liseye yakın oturuyorum.' },
      { fr: 'Il y a une pharmacie près d’ici.', tr: 'Buraya yakın bir eczane var.' },
    ],
    esdizim: ['près de', 'tout près', 'près d’ici'],
    aile: ['loin', 'à côté de'],
    hata: '"près de + le" birleşimini yazmamak: "près de le lycée" değil, "près DU lycée".',
    hatirlatma: 'de + le = du kaynaşması burada da geçerlidir.',
    uretim: { yonerge: '"Liseye yakın oturuyorum." cümlesini yaz.', kabul: ['J’habite près du lycée', "J'habite près du lycée"] },
  },
  {
    id: 'fr-billet',
    dil: 'fr',
    kelime: 'billet',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les billets',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Le papier qu’on achète pour voyager ou entrer quelque part.',
    turkceDestek: 'bilet',
    ipa: '/bi.jɛ/',
    heceler: 'bil-let ("bi-YE" · sondaki t okunmaz)',
    ornekler: [
      { fr: 'Je voudrais un billet pour Lyon, s’il vous plaît.', tr: 'Lyon için bir bilet istiyorum, lütfen.' },
      { fr: 'Le billet coûte quinze euros.', tr: 'Bilet on beş euro.' },
    ],
    esdizim: ['un billet aller-retour', 'acheter un billet'],
    aile: ['le ticket', 'la gare', 'le train'],
    hata: '"le billet" (tren/uçak/konser bileti) ile "le ticket" (otobüs/metro bileti) karıştırılır.',
    hatirlatma: 'Gidiş-dönüş bileti: "un billet aller-retour"; tek yön: "un aller simple".',
    uretim: { yonerge: '"Bir bilet istiyorum." cümlesini yaz.', kabul: ['Je voudrais un billet', "Je voudrais un billet s'il vous plaît"] },
  },
  {
    id: 'fr-arret',
    dil: 'fr',
    kelime: 'arrêt',
    artikel: "l'",
    cins: 'eril',
    cogul: 'les arrêts',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'L’endroit où le bus s’arrête pour prendre des passagers.',
    turkceDestek: 'durak',
    ipa: '/a.ʁɛ/',
    heceler: 'ar-rêt ("a-RE" · sondaki t okunmaz)',
    ornekler: [
      { fr: 'L’arrêt de bus est devant la pharmacie.', tr: 'Otobüs durağı eczanenin önünde.' },
      { fr: 'Je descends au prochain arrêt.', tr: 'Bir sonraki durakta iniyorum.' },
    ],
    esdizim: ['l’arrêt de bus', 'le prochain arrêt'],
    aile: ['la station', 'le bus', "s'arrêter"],
    hata: 'Metro için "arrêt" kullanmak. Otobüsün durağı "l’arrêt", metronun durağı "la station"dır.',
    hatirlatma: 'Artikeli "l’" olduğu için cinsi görünmez; ERİLDİR.',
    uretim: { yonerge: '"Otobüs durağı nerede?" sorusunu yaz.', kabul: ["Où est l'arrêt de bus", 'Où est l’arrêt de bus'] },
  },
  {
    id: 'fr-centre-ville',
    dil: 'fr',
    kelime: 'centre-ville',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les centres-villes',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'La partie centrale d’une ville, avec les magasins et les cafés.',
    turkceDestek: 'şehir merkezi',
    ipa: '/sɑ̃tʁə.vil/',
    heceler: 'cen-tre-ville (ilk hece nazal)',
    ornekler: [
      { fr: 'Le samedi, je vais au centre-ville.', tr: 'Cumartesi günleri şehir merkezine giderim.' },
      { fr: 'Le centre-ville est très animé le soir.', tr: 'Şehir merkezi akşamları çok hareketli.' },
    ],
    esdizim: ['aller au centre-ville', 'en centre-ville'],
    aile: ['la ville', 'le quartier'],
    hata: 'Tireyi unutmak. Bileşik kelimedir ve tireli yazılır: centre-ville.',
    hatirlatma: '"en ville" ifadesi de aynı anlamda kullanılır ve artikel almaz.',
    uretim: { yonerge: '"Şehir merkezine gidiyorum." cümlesini yaz.', kabul: ['Je vais au centre-ville'] },
  },
  {
    id: 'fr-a-pied',
    dil: 'fr',
    kelime: 'à pied',
    tur: 'kalip',
    seviye: 'A1',
    fransizcaTanim: 'En marchant, sans véhicule.',
    turkceDestek: 'yürüyerek, yaya',
    ipa: '/a pje/',
    heceler: 'à pied ("a pye" · sondaki d okunmaz)',
    ornekler: [
      { fr: 'Je vais au lycée à pied.', tr: 'Liseye yürüyerek gidiyorum.' },
      { fr: 'C’est à dix minutes à pied.', tr: 'Yürüyerek on dakika.' },
    ],
    esdizim: ['aller à pied', 'à dix minutes à pied'],
    aile: ['en bus', 'en voiture', 'à vélo'],
    hata: 'Ulaşımda hep "en" kullanmak. Araç İÇİNE biniliyorsa "en", üstüne biniliyorsa ya da yürünüyorsa "à" kullanılır: à pied, à vélo, à cheval.',
    hatirlatma: 'Kural: içine giriliyorsa EN (en bus, en voiture, en train), üstüne biniliyorsa À (à pied, à vélo).',
    uretim: { yonerge: '"Yürüyerek gidiyorum." cümlesini yaz.', kabul: ['Je vais à pied', 'Je vais a pied'] },
  },
  {
    id: 'fr-tourner',
    dil: 'fr',
    kelime: 'tourner',
    cekim: 'je tourne · nous tournons · vous tournez · ils tournent',
    tur: 'fiil',
    seviye: 'A1',
    fransizcaTanim: 'Changer de direction.',
    turkceDestek: 'dönmek',
    ipa: '/tuʁ.ne/',
    heceler: 'tour-ner ("tur-NE")',
    ornekler: [
      { fr: 'Tournez à droite après le pont.', tr: 'Köprüden sonra sağa dönün.' },
      { fr: 'Je tourne à gauche ici.', tr: 'Burada sola dönüyorum.' },
    ],
    esdizim: ['tourner à droite', 'tourner à gauche'],
    aile: ['le tour', 'continuer', 'traverser'],
    hata: 'Yön tarifinde emir kipini kullanmayı unutmak. Tarif verirken "vous" biçimi kullanılır: "Tournez", "Tourne" değil.',
    hatirlatma: 'Yön tarifinin üç fiili: tournez (dönün), continuez (devam edin), traversez (geçin).',
    uretim: { yonerge: '"Sağa dönün." cümlesini yaz.', kabul: ['Tournez à droite', 'Tournez a droite'] },
  },
  {
    id: 'fr-traverser',
    dil: 'fr',
    kelime: 'traverser',
    cekim: 'je traverse · nous traversons · vous traversez',
    tur: 'fiil',
    seviye: 'A1',
    fransizcaTanim: 'Aller d’un côté à l’autre.',
    turkceDestek: 'geçmek (karşıya)',
    ipa: '/tʁa.vɛʁ.se/',
    heceler: 'tra-ver-ser',
    ornekler: [
      { fr: 'Traversez la rue au feu.', tr: 'Işıkta caddeyi geçin.' },
      { fr: 'Nous traversons le pont à pied.', tr: 'Köprüyü yürüyerek geçiyoruz.' },
    ],
    esdizim: ['traverser la rue', 'traverser le pont'],
    aile: ['tourner', 'continuer'],
    hata: 'Araya edat koymak: "traverser DANS la rue" değil, doğrudan "traverser la rue". Bu fiil nesnesini edatsız alır.',
    hatirlatma: 'Yön tarifinde çok geçer; "au feu" (ışıkta) ile birlikte kullanılır.',
    uretim: { yonerge: '"Caddeyi geçin." cümlesini yaz.', kabul: ['Traversez la rue'] },
  },
  {
    id: 'fr-cinema',
    dil: 'fr',
    kelime: 'cinéma',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les cinémas',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'L’endroit où on regarde des films.',
    turkceDestek: 'sinema',
    ipa: '/si.ne.ma/',
    heceler: 'ci-né-ma ("si-ne-MA")',
    ornekler: [
      { fr: 'On va au cinéma ce soir ?', tr: 'Bu akşam sinemaya gidelim mi?' },
      { fr: 'Le cinéma est en face de la banque.', tr: 'Sinema bankanın karşısında.' },
    ],
    esdizim: ['aller au cinéma', 'au cinéma'],
    aile: ['le film', 'le théâtre'],
    hata: 'Kaynaşmayı yapmamak: "à le cinéma" değil, "AU cinéma". Bu, en sık tekrar eden kaynaşma hatasıdır.',
    hatirlatma: 'Baştaki "c" ince sesli harften önce "s" okunur: si-ne-ma.',
    uretim: { yonerge: '"Sinemaya gidiyorum." cümlesini yaz.', kabul: ['Je vais au cinéma', 'Je vais au cinema'] },
  },
  {
    id: 'fr-banque',
    dil: 'fr',
    kelime: 'banque',
    artikel: 'la',
    cins: 'disil',
    cogul: 'les banques',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'L’endroit où on garde et retire son argent.',
    turkceDestek: 'banka',
    ipa: '/bɑ̃k/',
    heceler: 'ban-que ("bank" · nazal)',
    ornekler: [
      { fr: 'La banque ferme à dix-sept heures.', tr: 'Banka on yedide kapanıyor.' },
      { fr: 'Il y a une banque en face de la gare.', tr: 'Garın karşısında bir banka var.' },
    ],
    esdizim: ['aller à la banque', 'en face de la banque'],
    aile: ["l'argent", 'la poste'],
    hata: 'Dişil olduğu için "au" değil "à la" kullanılır: "à la banque".',
    hatirlatma: '"en face de" = karşısında — yön tarifinde çok kullanılır.',
    uretim: { yonerge: '"Bankaya gidiyorum." cümlesini yaz.', kabul: ['Je vais à la banque', 'Je vais a la banque'] },
  },
]
