/**
 * A1 — TANIŞMA KELİMELERİ
 * ==================================================================
 *
 * Bir kelimeyi "bilmek" burada dört şey demektir: anlamını bilmek,
 * bağlamda tanımak, doğru biçimde yazmak, kendi cümlende kullanmak.
 * Bu yüzden her kayıtta tanım, örnek, eşdizim ve üretim görevi var.
 *
 * FRANSIZCAYA ÖZGÜ ZORUNLULUK: her isimde `artikel`, `cins` ve `cogul`
 * alanı doldurulmuştur. Cinsiyetsiz öğrenilen isim yarım öğrenilmiş
 * isimdir — öğrenci onu hiçbir cümlede doğru kullanamaz, çünkü sıfat
 * uyumu, iyelik sıfatı ve zamir seçimi cinsiyete bağlıdır.
 *
 * `cins` neden ayrı bir alan: sesli harfle başlayan isimlerde artikel
 * "l'" olur (l'ami, l'école) ve cinsiyeti GİZLER. Öğrenci yalnız
 * artikele bakarak öğrenemeyeceği için cins açıkça yazılır.
 *
 * `hata` alanı Türk öğrencilerin o kelimede yaptığı EN SIK hatadır;
 * uydurulmamış, ders veren öğretmenin gördüğü hatalardır.
 */

export const KELIMELER = [
  {
    id: 'fr-bonjour',
    dil: 'fr',
    kelime: 'bonjour',
    tur: 'kalip',
    seviye: 'A1',
    fransizcaTanim: 'Mot que l’on dit pour saluer quelqu’un pendant la journée.',
    turkceDestek: 'merhaba, günaydın, iyi günler',
    ipa: '/bɔ̃.ʒuʁ/',
    heceler: 'bon-jour (ilk hece nazal: "bon" burundan)',
    ornekler: [
      { fr: 'Bonjour, madame ! Comment allez-vous ?', tr: 'Merhaba hanımefendi! Nasılsınız?' },
      { fr: 'Bonjour, je m’appelle Deniz.', tr: 'Merhaba, adım Deniz.' },
    ],
    esdizim: ['dire bonjour', 'bonjour à tous', 'Bonjour, monsieur'],
    aile: ['bonsoir', 'bonne journée', 'bonne nuit'],
    hata: 'Akşam "bonjour" demek. Fransızcada saat 18:00 civarından sonra "bonsoir" denir; "bonjour" gündüz selamıdır.',
    hatirlatma: 'İki parçadan oluşur: bon (iyi) + jour (gün). Yani "iyi günler".',
    uretim: {
      yonerge: 'Sabah öğretmenini gördün. Onu selamla.',
      kabul: ['Bonjour', 'Bonjour madame', 'Bonjour monsieur', 'Bonjour, madame'],
    },
  },
  {
    id: 'fr-salut',
    dil: 'fr',
    kelime: 'salut',
    tur: 'kalip',
    seviye: 'A1',
    fransizcaTanim: 'Salutation amicale entre amis, entre jeunes ou en famille.',
    turkceDestek: 'selam (samimi)',
    ipa: '/sa.ly/',
    heceler: 'sa-lut (sondaki t OKUNMAZ · "u" değil "ü")',
    ornekler: [
      { fr: 'Salut Kerem ! Ça va ?', tr: 'Selam Kerem! Nasılsın?' },
      { fr: 'Salut, à demain !', tr: 'Selam, yarın görüşürüz!' },
    ],
    esdizim: ['Salut, ça va ?', 'Salut tout le monde'],
    aile: ['saluer', 'la salutation'],
    hata: 'Öğretmene ya da tanımadığı bir yetişkine "salut" demek. Bu kelime yalnız samimi ilişkide kullanılır; resmî durumda kabalık sayılır.',
    hatirlatma: 'Hem "merhaba" hem "hoşça kal" yerine geçer — geldiğinde de giderken de söylenir.',
    uretim: {
      yonerge: 'Sınıf arkadaşını gördün. Ona samimi biçimde selam ver.',
      kabul: ['Salut', 'Salut !', 'Salut ça va'],
    },
  },
  {
    id: 'fr-merci',
    dil: 'fr',
    kelime: 'merci',
    tur: 'kalip',
    seviye: 'A1',
    fransizcaTanim: 'Mot que l’on dit quand quelqu’un nous aide ou nous donne quelque chose.',
    turkceDestek: 'teşekkürler',
    ipa: '/mɛʁ.si/',
    heceler: 'mer-ci ("r" gırtlaktan)',
    ornekler: [
      { fr: 'Merci beaucoup pour ton aide.', tr: 'Yardımın için çok teşekkürler.' },
      { fr: '— Voilà ton livre. — Merci !', tr: '— Al kitabın. — Teşekkürler!' },
    ],
    esdizim: ['merci beaucoup', 'merci bien', 'non, merci'],
    aile: ['remercier', 'le remerciement'],
    hata: 'Bir teklife tek başına "merci" demek Fransızcada çoğu zaman REDDİR. Kabul için "oui, merci", ret için "non, merci" denir.',
    hatirlatma: 'Karşılığı "de rien" ya da "je vous en prie"dir (resmî).',
    uretim: {
      yonerge: 'Biri sana yardım etti. Ona çok teşekkür et.',
      kabul: ['Merci beaucoup', 'Merci', 'Merci bien'],
    },
  },
  {
    id: 'fr-sil-vous-plait',
    dil: 'fr',
    kelime: 's’il vous plaît',
    tur: 'kalip',
    seviye: 'A1',
    fransizcaTanim: 'Formule de politesse pour demander quelque chose.',
    turkceDestek: 'lütfen (resmî ya da birden çok kişiye)',
    ipa: '/sil vu plɛ/',
    heceler: 's’il-vous-plaît (sondaki t okunmaz)',
    ornekler: [
      { fr: 'Un café, s’il vous plaît.', tr: 'Bir kahve, lütfen.' },
      { fr: 'Répétez, s’il vous plaît.', tr: 'Tekrar eder misiniz, lütfen.' },
    ],
    esdizim: ['s’il te plaît', 'oui, s’il vous plaît'],
    aile: ['plaire', 'la politesse'],
    hata: 'Arkadaşa "s’il vous plaît" demek. Samimi biçimi "s’il te plaît"dir; hitap değişince kalıp da değişir.',
    hatirlatma: 'Kelime kelime "eğer size hoş gelirse" demektir — bu yüzden içinde "vous" vardır.',
    uretim: {
      yonerge: 'Garsondan bir kahve iste (kibar biçimde).',
      kabul: ['Un café, s’il vous plaît', 'Un cafe s il vous plait', 'Un café s’il vous plaît'],
    },
  },
  {
    id: 'fr-excusez-moi',
    dil: 'fr',
    kelime: 'excusez-moi',
    tur: 'kalip',
    seviye: 'A1',
    fransizcaTanim: 'Formule pour attirer l’attention de quelqu’un avant de demander quelque chose.',
    turkceDestek: 'affedersiniz, pardon',
    ipa: '/ɛks.ky.ze mwa/',
    heceler: 'ex-cu-sez-moi ("oi" → "ua" okunur)',
    ornekler: [
      { fr: 'Excusez-moi, où est la gare ?', tr: 'Affedersiniz, gar nerede?' },
      { fr: 'Excusez-moi, je suis en retard.', tr: 'Affedersiniz, geç kaldım.' },
    ],
    esdizim: ['excuse-moi', 'excusez-moi de vous déranger'],
    aile: ['excuser', 'l’excuse', 'pardon'],
    hata: 'Bir şey OLDUKTAN sonra "excusez-moi" ile yetinmek. Gerçek bir özür için "je suis désolé(e)" daha uygundur.',
    hatirlatma: 'Bir şey SORMADAN ÖNCE dikkat çekmek için kullanılır; yol sorarken cümlenin ilk sözü çoğu zaman budur.',
    uretim: {
      yonerge: 'Sokakta birine yol soracaksın. Cümleye nasıl başlarsın?',
      kabul: ['Excusez-moi', 'Pardon', 'Excusez-moi, madame', 'Excusez moi'],
    },
  },
  {
    id: 'fr-au-revoir',
    dil: 'fr',
    kelime: 'au revoir',
    tur: 'kalip',
    seviye: 'A1',
    fransizcaTanim: 'Ce que l’on dit quand on quitte quelqu’un.',
    turkceDestek: 'hoşça kalın, güle güle',
    ipa: '/o ʁə.vwaʁ/',
    heceler: 'au-re-voir ("au" → "o" okunur)',
    ornekler: [
      { fr: 'Au revoir, madame. À demain !', tr: 'Hoşça kalın hanımefendi. Yarın görüşürüz!' },
      { fr: 'Au revoir et bonne journée.', tr: 'Hoşça kalın, iyi günler.' },
    ],
    esdizim: ['au revoir et merci', 'à bientôt', 'à demain'],
    aile: ['revoir', 'à plus tard'],
    hata: '"Bonne nuit" ile karıştırmak. "Bonne nuit" yalnız yatmadan önce söylenir; ayrılırken "au revoir" ya da "bonne soirée" denir.',
    hatirlatma: 'Kelime kelime "yeniden görmeye" demektir — Türkçedeki "görüşmek üzere" ile aynı mantık.',
    uretim: {
      yonerge: 'Dersten çıkıyorsun. Öğretmenine veda et.',
      kabul: ['Au revoir', 'Au revoir madame', 'Au revoir, monsieur'],
    },
  },
  {
    id: 'fr-enchante',
    dil: 'fr',
    kelime: 'enchanté(e)',
    tur: 'sifat',
    seviye: 'A1',
    fransizcaTanim: 'Ce que l’on dit quand on rencontre quelqu’un pour la première fois.',
    turkceDestek: 'memnun oldum',
    ipa: '/ɑ̃.ʃɑ̃.te/',
    heceler: 'en-chan-té (iki nazal ses arka arkaya)',
    ornekler: [
      { fr: '— Je suis Léa. — Enchanté !', tr: '— Ben Léa. — Memnun oldum!' },
      { fr: 'Enchantée de faire votre connaissance.', tr: 'Tanıştığımıza memnun oldum.' },
    ],
    esdizim: ['enchanté de vous rencontrer', 'ravi de vous connaître'],
    aile: ['enchanter', 'la connaissance'],
    hata: 'Kadın konuşuyorsa sonuna -e eklemeyi unutmak: "enchantée". Fransızcada bu sıfat KONUŞANA uyar, karşıdakine değil.',
    hatirlatma: 'Yalnız İLK tanışmada söylenir; her karşılaşmada değil.',
    uretim: {
      yonerge: 'Yeni biriyle tanıştın. Ona ne dersin?',
      kabul: ['Enchanté', 'Enchantée', 'Enchanté !'],
    },
  },
  {
    id: 'fr-appeler',
    dil: 'fr',
    kelime: 's’appeler',
    cekim: 'je m’appelle · tu t’appelles · il s’appelle · nous nous appelons · vous vous appelez · ils s’appellent',
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    fransizcaTanim: 'Avoir tel nom ; porter un nom.',
    turkceDestek: 'adı … olmak',
    ipa: '/sa.p(ə).le/',
    heceler: 's’ap-pe-ler (je m’appelle: "ma-PEL")',
    ornekler: [
      { fr: 'Je m’appelle Mert. Et toi ?', tr: 'Benim adım Mert. Ya senin?' },
      { fr: 'Comment s’appelle ta sœur ?', tr: 'Kız kardeşinin adı ne?' },
    ],
    esdizim: ['Comment tu t’appelles ?', 'Comment vous appelez-vous ?', 'Il s’appelle…'],
    aile: ['appeler', 'le nom', 'le prénom'],
    hata: 'Türkçede "adım Mert" derken fiil yoktur; öğrenci "Je Mert" ya da "Mon nom Mert" yazar. Fransızcada mutlaka bir fiil olmalı: m’appelle ya da est.',
    hatirlatma: 'Dönüşlü fiildir: özneye ait bir zamir (me/te/se) her zaman fiilin önünde durur.',
    uretim: {
      yonerge: 'Adını "Je m’appelle …" kalıbıyla yaz.',
      kabul: ['Je m’appelle', "Je m'appelle", 'Je m appelle'],
    },
  },
  {
    id: 'fr-etre',
    dil: 'fr',
    kelime: 'être',
    cekim: 'je suis · tu es · il/elle est · nous sommes · vous êtes · ils/elles sont',
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    fransizcaTanim: 'Verbe qui sert à dire ce que quelqu’un ou quelque chose EST.',
    turkceDestek: 'olmak (-dır, -im, -sin)',
    ipa: '/ɛtʁ/',
    heceler: 'ê-tre (tek hece gibi okunur: "etr")',
    ornekler: [
      { fr: 'Je suis élève au lycée.', tr: 'Lisede öğrenciyim.' },
      { fr: 'Nous sommes turcs.', tr: 'Biz Türk’üz.' },
    ],
    esdizim: ['être fatigué', 'être en retard', 'être d’accord'],
    aile: ['c’est', 'ce sont', 'l’être'],
    hata: 'Yaş, açlık ve soğuk için "être" kullanmak. Fransızcada bunlar "avoir" ile kurulur: j’ai 17 ans, j’ai faim, j’ai froid.',
    hatirlatma: 'Fransızcanın en düzensiz fiilidir ve en çok kullanılanıdır; çekimi ezberlenmek zorundadır.',
    uretim: {
      yonerge: '"Öğrenciyim." cümlesini yaz.',
      kabul: ['Je suis élève', 'Je suis étudiant', 'Je suis etudiant', 'Je suis eleve'],
    },
  },
  {
    id: 'fr-avoir',
    dil: 'fr',
    kelime: 'avoir',
    cekim: 'j’ai · tu as · il/elle a · nous avons · vous avez · ils/elles ont',
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    fransizcaTanim: 'Verbe qui exprime la possession et certains états du corps.',
    turkceDestek: 'sahip olmak; (yaş, açlık, soğuk için) …-mak',
    ipa: '/a.vwaʁ/',
    heceler: 'a-voir ("oi" → "ua")',
    ornekler: [
      { fr: 'J’ai deux frères et une sœur.', tr: 'İki erkek kardeşim ve bir kız kardeşim var.' },
      { fr: 'Elle a seize ans.', tr: 'O on altı yaşında.' },
    ],
    esdizim: ['avoir … ans', 'avoir faim', 'avoir froid', 'avoir peur'],
    aile: ['il y a', 'avoir besoin de'],
    hata: 'Türkçede "iki kardeşim var" cümlesinde "var" kelimesi vardır; öğrenci bunu "il y a" ile çevirir. Sahiplikte "avoir" kullanılır: J’ai deux frères.',
    hatirlatma: '"J’ai" biçiminde elizyon zorunludur: je + ai → j’ai.',
    uretim: {
      yonerge: '"On yedi yaşındayım." cümlesini yaz.',
      kabul: ['J’ai dix-sept ans', "J'ai dix-sept ans", 'J ai 17 ans', 'J’ai 17 ans'],
    },
  },
  {
    id: 'fr-nom',
    dil: 'fr',
    kelime: 'nom',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les noms',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Le mot par lequel on appelle une personne ou une chose.',
    turkceDestek: 'ad, soyadı',
    ipa: '/nɔ̃/',
    heceler: 'nom (tek hece · nazal, sondaki m okunmaz)',
    ornekler: [
      { fr: 'Mon nom est Yılmaz et mon prénom est Ada.', tr: 'Soyadım Yılmaz, adım Ada.' },
      { fr: 'Quel est votre nom, s’il vous plaît ?', tr: 'Soyadınız nedir, lütfen?' },
    ],
    esdizim: ['le nom de famille', 'quel est votre nom ?'],
    aile: ['le prénom', 'nommer', 's’appeler'],
    hata: 'Fransızcada "le nom" çoğu formda SOYADI demektir; ad için "le prénom" kullanılır. Öğrenci ikisini karıştırır.',
    hatirlatma: 'prénom = pré (önce) + nom → soyadından önce gelen ad.',
    uretim: {
      yonerge: 'Birinin soyadını kibarca sor.',
      kabul: ['Quel est votre nom', 'Quel est votre nom ?', 'Comment vous appelez-vous'],
    },
  },
  {
    id: 'fr-prenom',
    dil: 'fr',
    kelime: 'prénom',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les prénoms',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Le nom que les parents donnent à un enfant.',
    turkceDestek: 'ad (ilk isim)',
    ipa: '/pʁe.nɔ̃/',
    heceler: 'pré-nom (é açık "e", nom nazal)',
    ornekler: [
      { fr: 'Mon prénom est Elif.', tr: 'Adım Elif.' },
      { fr: 'Écris ton prénom ici, s’il te plaît.', tr: 'Adını buraya yaz, lütfen.' },
    ],
    esdizim: ['écrire son prénom', 'un prénom français'],
    aile: ['le nom', 's’appeler'],
    hata: 'Formlarda "nom" yazan yere adını yazmak. "Nom" soyadı, "prénom" addır.',
    hatirlatma: 'Fransız formlarında her zaman önce NOM (soyadı), sonra PRÉNOM (ad) sorulur.',
    uretim: {
      yonerge: 'Adını "Mon prénom est …" kalıbıyla yaz.',
      kabul: ['Mon prénom est', 'Mon prenom est'],
    },
  },
  {
    id: 'fr-venir',
    dil: 'fr',
    kelime: 'venir',
    cekim: 'je viens · tu viens · il vient · nous venons · vous venez · ils viennent',
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    fransizcaTanim: 'Se déplacer vers celui qui parle ; être originaire d’un endroit.',
    turkceDestek: 'gelmek; (de ile) …lı olmak',
    ipa: '/və.niʁ/',
    heceler: 've-nir (je viens: "vyen")',
    ornekler: [
      { fr: 'Je viens de Turquie, de Bursa.', tr: 'Türkiyeliyim, Bursalıyım.' },
      { fr: 'Tu viens avec nous ?', tr: 'Bizimle geliyor musun?' },
    ],
    esdizim: ['venir de + ülke', 'venir avec', 'je viens de + mastar (yeni yaptım)'],
    aile: ['revenir', 'devenir', 'la venue'],
    hata: 'Ülke adının artikelini atlamak: "Je viens de la Turquie" değil "Je viens de Turquie"; ama "Je viens du Maroc". Ülkenin cinsi kalıbı değiştirir.',
    hatirlatma: '"Je viens de manger" = "az önce yedim" demektir; aynı fiil yakın geçmişi de kurar.',
    uretim: {
      yonerge: 'Nereli olduğunu "Je viens de…" ile yaz.',
      kabul: ['Je viens de Turquie', 'Je viens de'],
    },
  },
  {
    id: 'fr-habiter',
    dil: 'fr',
    kelime: 'habiter',
    cekim: 'j’habite · tu habites · il habite · nous habitons · vous habitez · ils habitent',
    tur: 'fiil',
    seviye: 'A1',
    fransizcaTanim: 'Vivre dans un endroit, avoir sa maison quelque part.',
    turkceDestek: 'oturmak, yaşamak',
    ipa: '/a.bi.te/',
    heceler: 'ha-bi-ter (baştaki h HİÇ okunmaz)',
    ornekler: [
      { fr: 'J’habite à Istanbul avec ma famille.', tr: 'Ailemle İstanbul’da oturuyorum.' },
      { fr: 'Où est-ce que tu habites ?', tr: 'Nerede oturuyorsun?' },
    ],
    esdizim: ['habiter à + şehir', 'habiter en France', 'habiter chez'],
    aile: ['l’habitant', 'l’habitation'],
    hata: 'Baştaki "h" sessiz olduğu için elizyon zorunludur: "je habite" değil "j’habite". Öğrenci h harfini gördüğü için elizyonu atlar.',
    hatirlatma: 'Şehirde "à", ülkede "en/au" kullanılır: à Paris, en France, au Maroc.',
    uretim: {
      yonerge: 'Nerede oturduğunu yaz.',
      kabul: ['J’habite à', "J'habite à", 'J habite a', 'J’habite'],
    },
  },
  {
    id: 'fr-parler',
    dil: 'fr',
    kelime: 'parler',
    cekim: 'je parle · tu parles · il parle · nous parlons · vous parlez · ils parlent',
    tur: 'fiil',
    seviye: 'A1',
    fransizcaTanim: 'Dire des mots ; utiliser une langue.',
    turkceDestek: 'konuşmak',
    ipa: '/paʁ.le/',
    heceler: 'par-ler ("r" gırtlaktan, sondaki -er "e" okunur)',
    ornekler: [
      { fr: 'Je parle turc, anglais et un peu français.', tr: 'Türkçe, İngilizce ve biraz Fransızca konuşuyorum.' },
      { fr: 'Vous parlez trop vite !', tr: 'Çok hızlı konuşuyorsunuz!' },
    ],
    esdizim: ['parler français', 'parler de', 'parler à quelqu’un'],
    aile: ['la parole', 'le parleur'],
    hata: 'Dil adının önüne artikel koymak: "Je parle le français" da doğrudur ama "parler" ile en doğal biçim artikelsizdir: "Je parle français."',
    hatirlatma: 'Bütün -er fiillerinin çekim örneğidir; bu tabloyu bilen yüzlerce fiili bilir.',
    uretim: {
      yonerge: 'Hangi dilleri konuştuğunu yaz.',
      kabul: ['Je parle turc', 'Je parle français', 'Je parle turc et anglais'],
    },
  },
  {
    id: 'fr-pays',
    dil: 'fr',
    kelime: 'pays',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les pays (değişmez)',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Un territoire avec ses frontières et son gouvernement.',
    turkceDestek: 'ülke',
    ipa: '/pe.i/',
    heceler: 'pa-ys ("pei" okunur, sondaki s okunmaz)',
    ornekler: [
      { fr: 'La Turquie est un grand pays.', tr: 'Türkiye büyük bir ülke.' },
      { fr: 'Dans quel pays est-ce que tu habites ?', tr: 'Hangi ülkede oturuyorsun?' },
    ],
    esdizim: ['un pays étranger', 'dans mon pays'],
    aile: ['le paysage', 'la nationalité'],
    hata: 'Çoğul yaparken -s eklemek: kelime zaten -s ile biter, çoğulu değişmez (le pays → les pays).',
    hatirlatma: 'Ülke adlarının çoğu dişildir ve -e ile biter: la France, la Turquie, la Suisse. İstisna: le Mexique.',
    uretim: {
      yonerge: '"Türkiye güzel bir ülke." cümlesini yaz.',
      kabul: ['La Turquie est un beau pays', 'La Turquie est un joli pays'],
    },
  },
  {
    id: 'fr-ville',
    dil: 'fr',
    kelime: 'ville',
    artikel: 'la',
    cins: 'disil',
    cogul: 'les villes',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Un endroit avec beaucoup de maisons, de rues et d’habitants.',
    turkceDestek: 'şehir',
    ipa: '/vil/',
    heceler: 'vil-le (sondaki e okunmaz · "ill" burada "iy" DEĞİL, "il")',
    ornekler: [
      { fr: 'Ma ville s’appelle Izmir.', tr: 'Şehrimin adı İzmir.' },
      { fr: 'Paris est une grande ville.', tr: 'Paris büyük bir şehir.' },
    ],
    esdizim: ['le centre-ville', 'une grande ville', 'en ville'],
    aile: ['le village', 'le villageois'],
    hata: '"ville" kelimesindeki "ill" çoğu kelimede "iy" okunur (famille, fille) ama bu kelimede "il" okunur. Kural değil istisnadır, ezberlenir.',
    hatirlatma: '"en ville" = şehir merkezine/merkezde demektir, artikel almaz.',
    uretim: {
      yonerge: 'Yaşadığın şehri tanıt: "Ma ville …"',
      kabul: ['Ma ville s’appelle', 'Ma ville est'],
    },
  },
  {
    id: 'fr-ami',
    dil: 'fr',
    kelime: 'ami / amie',
    artikel: "l'",
    cins: 'eril',
    cogul: 'les amis / les amies',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Une personne que l’on aime bien et que l’on voit souvent.',
    turkceDestek: 'arkadaş',
    ipa: '/a.mi/',
    heceler: 'a-mi (l’ami: "la-Mİ")',
    ornekler: [
      { fr: 'C’est mon ami Kaan.', tr: 'Bu arkadaşım Kaan.' },
      { fr: 'J’ai une amie française.', tr: 'Fransız bir kız arkadaşım var.' },
    ],
    esdizim: ['un ami proche', 'mon meilleur ami', 'être ami avec'],
    aile: ['l’amitié', 'amical'],
    hata: 'Kız arkadaş için "mon amie" derken iyelik sıfatını "ma" yapmak. Sesli harfle başladığı için dişilde bile "mon amie" denir.',
    hatirlatma: 'Artikeli "l’" olduğu için cinsiyeti görünmez; kelimeyi cinsiyetiyle birlikte öğrenmek şart.',
    uretim: {
      yonerge: 'Bir arkadaşını tanıt: "C’est mon ami …"',
      kabul: ['C’est mon ami', "C'est mon ami", 'C’est mon amie'],
    },
  },
  {
    id: 'fr-professeur',
    dil: 'fr',
    kelime: 'professeur',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les professeurs',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Une personne qui enseigne dans une école ou un lycée.',
    turkceDestek: 'öğretmen',
    ipa: '/pʁɔ.fɛ.sœʁ/',
    heceler: 'pro-fes-seur (günlük dilde kısaca "prof")',
    ornekler: [
      { fr: 'Mon professeur de français est très gentil.', tr: 'Fransızca öğretmenim çok kibar.' },
      { fr: 'Le professeur explique la leçon.', tr: 'Öğretmen dersi anlatıyor.' },
    ],
    esdizim: ['le professeur de français', 'un prof sympa'],
    aile: ['la profession', 'enseigner', "l'élève"],
    hata: 'Meslek söylerken artikel kullanmak: "Je suis un professeur" değil, "Je suis professeur".',
    hatirlatma: 'Klasik kullanımda kelime kadın öğretmen için de erildir; günümüzde "la professeure" biçimi de yaygınlaşmıştır.',
    uretim: {
      yonerge: '"Fransızca öğretmenim kibar." cümlesini yaz.',
      kabul: ['Mon professeur de français est gentil', 'Mon prof de français est gentil'],
    },
  },
  {
    id: 'fr-eleve',
    dil: 'fr',
    kelime: 'élève',
    artikel: "l'",
    cins: 'eril',
    cogul: 'les élèves',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Une personne qui apprend à l’école ou au lycée.',
    turkceDestek: 'öğrenci (okul/lise)',
    ipa: '/e.lɛv/',
    heceler: 'é-lè-ve (é kapalı, è açık — iki farklı "e")',
    ornekler: [
      { fr: 'Je suis élève en terminale.', tr: 'Son sınıf öğrencisiyim.' },
      { fr: 'Les élèves écoutent le professeur.', tr: 'Öğrenciler öğretmeni dinliyor.' },
    ],
    esdizim: ['un bon élève', 'les élèves de la classe'],
    aile: ['l’école', 'apprendre', 'étudier'],
    hata: '"élève" ile "étudiant" karıştırılır: élève okul/lise öğrencisi, étudiant ÜNİVERSİTE öğrencisidir.',
    hatirlatma: 'Aynı biçim hem erkek hem kız için kullanılır; ayrım artikelden anlaşılır: un élève / une élève.',
    uretim: {
      yonerge: '"Lisede öğrenciyim." cümlesini yaz.',
      kabul: ['Je suis élève au lycée', 'Je suis eleve au lycee', 'Je suis lycéen', 'Je suis lycéenne'],
    },
  },
  {
    id: 'fr-comment',
    dil: 'fr',
    kelime: 'comment',
    tur: 'soru',
    seviye: 'A1',
    fransizcaTanim: 'Mot que l’on utilise pour demander la manière.',
    turkceDestek: 'nasıl',
    ipa: '/kɔ.mɑ̃/',
    heceler: 'com-ment (sondaki -ent nazal "an" okunur)',
    ornekler: [
      { fr: 'Comment tu t’appelles ?', tr: 'Adın ne?' },
      { fr: 'Comment allez-vous ?', tr: 'Nasılsınız?' },
    ],
    esdizim: ['Comment ça va ?', 'Comment ça s’écrit ?', 'Comment dit-on … ?'],
    aile: ['pourquoi', 'quand', 'où'],
    hata: 'Türkçede "adın ne?" sorusu "ne" ile kurulduğu için öğrenci "Quel est ton nom ?" yerine "Que est ton nom ?" gibi biçimler dener. Ad sorarken doğal kalıp "Comment tu t’appelles ?"dir.',
    hatirlatma: 'Sondaki -ent burada FİİL çekimi değildir, bu yüzden okunur (nazal): "ko-MAN".',
    uretim: {
      yonerge: 'Bir arkadaşına adını sor.',
      kabul: ['Comment tu t’appelles', 'Comment tu t appelles', "Comment tu t'appelles", 'Tu t’appelles comment'],
    },
  },
  {
    id: 'fr-ou',
    dil: 'fr',
    kelime: 'où',
    tur: 'soru',
    seviye: 'A1',
    fransizcaTanim: 'Mot que l’on utilise pour demander le lieu.',
    turkceDestek: 'nerede, nereye',
    ipa: '/u/',
    heceler: 'où (tek hece · "u" okunur)',
    ornekler: [
      { fr: 'Où est-ce que tu habites ?', tr: 'Nerede oturuyorsun?' },
      { fr: 'Où sont mes clés ?', tr: 'Anahtarlarım nerede?' },
    ],
    esdizim: ['Où est … ?', 'D’où viens-tu ?', 'Où vas-tu ?'],
    aile: ['ici', 'là', 'là-bas'],
    hata: 'Aksanı atlamak. Aksansız "ou" = "veya" demektir; aksanlı "où" = "nerede". Bu iki kelimeyi ayıran tek şey aksandır.',
    hatirlatma: 'Fransızcada aksan taşıyan tek "u" harfi budur; başka yerde ù kullanılmaz.',
    uretim: {
      yonerge: '"Nerede oturuyorsun?" sorusunu yaz.',
      kabul: ['Où est-ce que tu habites', 'Où habites-tu', 'Tu habites où'],
    },
  },
]
