/**
 * A1 — YEMEK, İÇECEK VE ALIŞVERİŞ
 * ==================================================================
 *
 * Bu havuzun özel yükü KISMİ ARTİKELDİR (du / de la / de l’). Türkçede
 * "ekmek yiyorum" derken miktar belirtilmez; Fransızcada belirtilmek
 * zorundadır. Bu yüzden yiyecek isimlerinin örnekleri her zaman kısmi
 * artikelle verilir — öğrenci kelimeyi artikeliyle birlikte kaydeder.
 */

export const KELIMELER = [
  {
    id: 'fr-pain',
    dil: 'fr',
    kelime: 'pain',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les pains',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Un aliment fait avec de la farine, de l’eau et de la levure.',
    turkceDestek: 'ekmek',
    ipa: '/pɛ̃/',
    heceler: 'pain (tek hece · ince nazal)',
    ornekler: [
      { fr: 'Je mange du pain au petit-déjeuner.', tr: 'Kahvaltıda ekmek yerim.' },
      { fr: 'Il n’y a plus de pain.', tr: 'Ekmek kalmadı.' },
    ],
    esdizim: ['du pain', 'une baguette', 'le pain frais'],
    aile: ['la boulangerie', 'la baguette'],
    hata: 'Kısmi artikeli atlamak: "Je mange pain" yanlıştır. Sayılamayan yiyeceklerde "du" zorunludur.',
    hatirlatma: '"main" (el) ile aynı nazal sesi taşır; ikisi de "pen" gibi okunur.',
    uretim: { yonerge: '"Ekmek yiyorum." cümlesini yaz.', kabul: ['Je mange du pain'] },
  },
  {
    id: 'fr-eau',
    dil: 'fr',
    kelime: 'eau',
    artikel: "l'",
    cins: 'disil',
    cogul: 'les eaux',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Le liquide transparent que l’on boit tous les jours.',
    turkceDestek: 'su',
    ipa: '/o/',
    heceler: 'eau (tek ses: "o")',
    ornekler: [
      { fr: 'Je bois de l’eau.', tr: 'Su içiyorum.' },
      { fr: 'Une bouteille d’eau, s’il vous plaît.', tr: 'Bir şişe su, lütfen.' },
    ],
    esdizim: ["de l'eau", 'une bouteille d’eau', 'l’eau minérale'],
    aile: ['boire', 'la boisson'],
    hata: 'Üç harfin tek ses verdiğini unutup "e-a-u" diye okumak. "eau" her zaman "o" okunur.',
    hatirlatma: 'Sesli harfle başladığı için kısmi artikel "de l’" olur: de l’eau.',
    uretim: { yonerge: '"Su içiyorum." cümlesini yaz.', kabul: ["Je bois de l'eau", 'Je bois de l’eau'] },
  },
  {
    id: 'fr-cafe',
    dil: 'fr',
    kelime: 'café',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les cafés',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Une boisson chaude noire ; aussi l’endroit où on la boit.',
    turkceDestek: 'kahve; kafe',
    ipa: '/ka.fe/',
    heceler: 'ca-fé ("ka-FE")',
    ornekler: [
      { fr: 'Un café, s’il vous plaît.', tr: 'Bir kahve, lütfen.' },
      { fr: 'On se retrouve au café à cinq heures.', tr: 'Saat beşte kafede buluşuyoruz.' },
    ],
    esdizim: ['un café', 'du café', 'au café'],
    aile: ['le thé', 'la boisson'],
    hata: 'Sipariş verirken kısmi artikel kullanmak: bir fincan kahve isterken "un café" denir, "du café" değil. "du café" genel olarak kahve içmeyi anlatır.',
    hatirlatma: 'Aynı kelime hem içeceği hem mekânı anlatır; "au café" mekândır.',
    uretim: { yonerge: 'Garsondan bir kahve iste.', kabul: ["Un café s'il vous plaît", 'Je voudrais un café', 'Un café, s’il vous plaît'] },
  },
  {
    id: 'fr-lait',
    dil: 'fr',
    kelime: 'lait',
    artikel: 'le',
    cins: 'eril',
    cogul: 'çoğulu kullanılmaz',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'La boisson blanche que donnent les vaches.',
    turkceDestek: 'süt',
    ipa: '/lɛ/',
    heceler: 'lait ("le" · sondaki t okunmaz)',
    ornekler: [
      { fr: 'Je bois du lait le matin.', tr: 'Sabahları süt içerim.' },
      { fr: 'Il n’y a pas de lait dans le frigo.', tr: 'Buzdolabında süt yok.' },
    ],
    esdizim: ['du lait', 'un café au lait'],
    aile: ['le fromage', 'le beurre'],
    hata: 'Olumsuzda artikeli değiştirmemek: "pas du lait" değil, "pas DE lait".',
    hatirlatma: '"ai" harf ikilisi "e" okunur; sondaki "t" okunmaz.',
    uretim: { yonerge: '"Süt içiyorum." cümlesini yaz.', kabul: ['Je bois du lait'] },
  },
  {
    id: 'fr-fromage',
    dil: 'fr',
    kelime: 'fromage',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les fromages',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Un aliment fait avec du lait.',
    turkceDestek: 'peynir',
    ipa: '/fʁɔ.maʒ/',
    heceler: 'fro-ma-ge (sonu "j" sesiyle biter)',
    ornekler: [
      { fr: 'Je mange du fromage tous les jours.', tr: 'Her gün peynir yerim.' },
      { fr: 'La France a beaucoup de fromages.', tr: 'Fransa’da çok çeşit peynir var.' },
    ],
    esdizim: ['du fromage', 'un plateau de fromages'],
    aile: ['le lait', 'le beurre'],
    hata: '-age eki yüzünden dişil sanmak: -age erildir (le fromage, le voyage, le message).',
    hatirlatma: 'Miktar belirtilirse "de" kullanılır: beaucoup DE fromage.',
    uretim: { yonerge: '"Peynir yiyorum." cümlesini yaz.', kabul: ['Je mange du fromage'] },
  },
  {
    id: 'fr-viande',
    dil: 'fr',
    kelime: 'viande',
    artikel: 'la',
    cins: 'disil',
    cogul: 'les viandes',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'La chair des animaux que l’on mange.',
    turkceDestek: 'et',
    ipa: '/vjɑ̃d/',
    heceler: 'vian-de (nazal "an")',
    ornekler: [
      { fr: 'Je ne mange pas de viande.', tr: 'Et yemiyorum.' },
      { fr: 'Tu veux de la viande ou du poisson ?', tr: 'Et mi istersin balık mı?' },
    ],
    esdizim: ['de la viande', 'la viande rouge'],
    aile: ['le poisson', 'le poulet'],
    hata: 'Dişil olduğu için kısmi artikel "de la"dır: "du viande" değil, "DE LA viande".',
    hatirlatma: 'Olumsuzda ikisi de "de" olur: pas de viande.',
    uretim: { yonerge: '"Et yemiyorum." cümlesini yaz.', kabul: ['Je ne mange pas de viande'] },
  },
  {
    id: 'fr-poisson',
    dil: 'fr',
    kelime: 'poisson',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les poissons',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Un animal qui vit dans l’eau et qu’on peut manger.',
    turkceDestek: 'balık',
    ipa: '/pwa.sɔ̃/',
    heceler: 'pois-son ("pua-SON" · sonu nazal)',
    ornekler: [
      { fr: 'Le vendredi, nous mangeons du poisson.', tr: 'Cuma günleri balık yeriz.' },
      { fr: 'J’aime beaucoup le poisson.', tr: 'Balığı çok severim.' },
    ],
    esdizim: ['du poisson', 'le poisson frais'],
    aile: ['la viande', 'la mer'],
    hata: '"poisson" (balık) ile "poison" (zehir) karıştırılır; tek "s" ile yazılırsa anlam tamamen değişir.',
    hatirlatma: 'Genel beğeni bildirirken belirli artikel kullanılır: "J’aime LE poisson".',
    uretim: { yonerge: '"Balık yiyoruz." cümlesini yaz.', kabul: ['Nous mangeons du poisson', 'On mange du poisson'] },
  },
  {
    id: 'fr-pomme',
    dil: 'fr',
    kelime: 'pomme',
    artikel: 'la',
    cins: 'disil',
    cogul: 'les pommes',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Un fruit rond, souvent rouge ou vert.',
    turkceDestek: 'elma',
    ipa: '/pɔm/',
    heceler: 'pom-me ("pom")',
    ornekler: [
      { fr: 'Je mange une pomme chaque jour.', tr: 'Her gün bir elma yerim.' },
      { fr: 'Un kilo de pommes, s’il vous plaît.', tr: 'Bir kilo elma, lütfen.' },
    ],
    esdizim: ['une pomme', 'un kilo de pommes', 'le jus de pomme'],
    aile: ['le fruit', "l'orange"],
    hata: 'Sayılabilir olduğu için "du" değil "une" kullanılır: "une pomme". Kısmi artikel sayılamayanlar içindir.',
    hatirlatma: '"la pomme de terre" patates demektir — kelime kelime "toprak elması".',
    uretim: { yonerge: '"Bir elma yiyorum." cümlesini yaz.', kabul: ['Je mange une pomme'] },
  },
  {
    id: 'fr-legume',
    dil: 'fr',
    kelime: 'légume',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les légumes',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Une plante que l’on mange, comme la carotte ou la tomate.',
    turkceDestek: 'sebze',
    ipa: '/le.ɡym/',
    heceler: 'lé-gu-me ("le-GÜM")',
    ornekler: [
      { fr: 'Je mange des légumes tous les jours.', tr: 'Her gün sebze yerim.' },
      { fr: 'Les légumes sont bons pour la santé.', tr: 'Sebzeler sağlık için iyidir.' },
    ],
    esdizim: ['des légumes', 'les légumes frais'],
    aile: ['le fruit', 'la salade'],
    hata: 'Çoğulda "des" düşürmek: "Je mange légumes" yanlıştır. Çoğul belirsiz artikel zorunludur.',
    hatirlatma: '"u" harfi burada da "ü" okunur: lé-GÜM.',
    uretim: { yonerge: '"Sebze yiyorum." cümlesini yaz.', kabul: ['Je mange des légumes'] },
  },
  {
    id: 'fr-restaurant',
    dil: 'fr',
    kelime: 'restaurant',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les restaurants',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'L’endroit où on va manger et où on paie le repas.',
    turkceDestek: 'restoran',
    ipa: '/ʁɛs.to.ʁɑ̃/',
    heceler: 'res-tau-rant (sonu nazal)',
    ornekler: [
      { fr: 'On va au restaurant ce soir ?', tr: 'Bu akşam restorana gidelim mi?' },
      { fr: 'Ce restaurant est très bon.', tr: 'Bu restoran çok iyi.' },
    ],
    esdizim: ['au restaurant', 'un bon restaurant'],
    aile: ['le café', 'la cantine', 'le menu'],
    hata: 'Kaynaşmayı yapmamak: "à le restaurant" değil, "AU restaurant".',
    hatirlatma: '"au" ile kullanıldığında hem "restorana" hem "restoranda" anlamına gelir; bağlam ayırır.',
    uretim: { yonerge: '"Restorana gidiyoruz." cümlesini yaz.', kabul: ['Nous allons au restaurant', 'On va au restaurant'] },
  },
  {
    id: 'fr-addition',
    dil: 'fr',
    kelime: 'addition',
    artikel: "l'",
    cins: 'disil',
    cogul: 'les additions',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Le papier qui montre combien il faut payer au restaurant.',
    turkceDestek: 'hesap (restoranda)',
    ipa: '/a.di.sjɔ̃/',
    heceler: 'ad-di-tion (sonu nazal "syon")',
    ornekler: [
      { fr: 'L’addition, s’il vous plaît !', tr: 'Hesap, lütfen!' },
      { fr: 'On partage l’addition ?', tr: 'Hesabı paylaşalım mı?' },
    ],
    esdizim: ["l'addition s'il vous plaît", "payer l'addition"],
    aile: ['payer', 'le prix'],
    hata: 'İngilizcedeki "bill" karşılığı olarak "la note" aramak. Restoranda standart kelime "l’addition"dur.',
    hatirlatma: '-tion eki dişildir; artikel "l’" olsa da kelime DİŞİLDİR.',
    uretim: { yonerge: 'Garsondan hesabı iste.', kabul: ["L'addition s'il vous plaît", 'L’addition, s’il vous plaît'] },
  },
  {
    id: 'fr-menu',
    dil: 'fr',
    kelime: 'menu',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les menus',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'La liste des plats d’un restaurant ; aussi une formule à prix fixe.',
    turkceDestek: 'menü',
    ipa: '/mə.ny/',
    heceler: 'me-nu ("mö-NÜ")',
    ornekler: [
      { fr: 'Je prends le menu à quinze euros.', tr: 'On beş euroluk menüyü alıyorum.' },
      { fr: 'Vous avez la carte, s’il vous plaît ?', tr: 'Menü kartını alabilir miyim?' },
    ],
    esdizim: ['le menu du jour', 'la carte'],
    aile: ['le restaurant', 'le plat'],
    hata: '"le menu" ile "la carte" karıştırılır: "la carte" bütün yemeklerin listesi, "le menu" sabit fiyatlı bir settir.',
    hatirlatma: 'Fransız restoranlarında "menu du jour" günün menüsüdür ve genelde daha ucuzdur.',
    uretim: { yonerge: '"Menüyü alıyorum." cümlesini yaz.', kabul: ['Je prends le menu'] },
  },
  {
    id: 'fr-boire',
    dil: 'fr',
    kelime: 'boire',
    cekim: 'je bois · tu bois · il boit · nous buvons · vous buvez · ils boivent',
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    fransizcaTanim: 'Faire entrer un liquide dans sa bouche.',
    turkceDestek: 'içmek',
    ipa: '/bwaʁ/',
    heceler: 'boi-re ("buar")',
    ornekler: [
      { fr: 'Je bois de l’eau.', tr: 'Su içiyorum.' },
      { fr: 'Nous buvons du thé le soir.', tr: 'Akşamları çay içeriz.' },
    ],
    esdizim: ['boire de l’eau', 'boire un café'],
    aile: ['la boisson', 'manger'],
    hata: 'Çoğul kişilerde kök değişimini unutmak: "nous boivons" değil, "nous BUVons".',
    hatirlatma: 'Türkçede sigara "içilir" ama Fransızcada "fumer" (tütmek) fiili kullanılır; "boire" yalnız sıvı içindir.',
    uretim: { yonerge: '"Çay içiyoruz." cümlesini yaz.', kabul: ['Nous buvons du thé', 'On boit du thé'] },
  },
  {
    id: 'fr-acheter',
    dil: 'fr',
    kelime: 'acheter',
    cekim: "j'achète · tu achètes · il achète · nous achetons · vous achetez · ils achètent",
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    fransizcaTanim: 'Payer pour obtenir quelque chose.',
    turkceDestek: 'satın almak',
    ipa: '/aʃ.te/',
    heceler: 'a-che-ter ("aş-TE")',
    ornekler: [
      { fr: 'J’achète du pain à la boulangerie.', tr: 'Fırından ekmek alıyorum.' },
      { fr: 'Nous achetons des légumes au marché.', tr: 'Pazardan sebze alıyoruz.' },
    ],
    esdizim: ['acheter du pain', 'acheter un billet'],
    aile: ["l'achat", 'vendre', 'payer'],
    hata: 'Tekil çekimlerde aksanı unutmak: "j’achete" değil, "j’achÈte". Vurgu oraya kaydığı için aksan gerekir.',
    hatirlatma: '"nous" ve "vous" biçimlerinde aksan YOKTUR: nous achetons.',
    uretim: { yonerge: '"Ekmek alıyorum." cümlesini yaz.', kabul: ["J'achète du pain", 'J’achète du pain'] },
  },
  {
    id: 'fr-payer',
    dil: 'fr',
    kelime: 'payer',
    cekim: 'je paie · nous payons · vous payez · ils paient',
    tur: 'fiil',
    seviye: 'A1',
    fransizcaTanim: 'Donner de l’argent pour quelque chose.',
    turkceDestek: 'ödemek',
    ipa: '/pe.je/',
    heceler: 'pa-yer ("pe-YE")',
    ornekler: [
      { fr: 'Je paie par carte.', tr: 'Kartla ödüyorum.' },
      { fr: 'Vous payez en espèces ?', tr: 'Nakit mi ödeyeceksiniz?' },
    ],
    esdizim: ['payer par carte', 'payer en espèces', "payer l'addition"],
    aile: ['le paiement', 'acheter'],
    hata: 'Türkçedeki "kartla" ifadesini "avec la carte" diye çevirmek. Ödeme biçimi "PAR carte" ya da "EN espèces" olarak söylenir.',
    hatirlatma: 'İki yazım da doğrudur: "je paie" ve "je paye".',
    uretim: { yonerge: '"Kartla ödüyorum." cümlesini yaz.', kabul: ['Je paie par carte', 'Je paye par carte'] },
  },
  {
    id: 'fr-euro',
    dil: 'fr',
    kelime: 'euro',
    artikel: "l'",
    cins: 'eril',
    cogul: 'les euros',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'La monnaie de la France et de plusieurs pays européens.',
    turkceDestek: 'euro',
    ipa: '/ø.ʁo/',
    heceler: 'eu-ro ("ö-RO")',
    ornekler: [
      { fr: 'Ça fait douze euros cinquante.', tr: 'On iki euro elli oldu.' },
      { fr: 'Le billet coûte quarante euros.', tr: 'Bilet kırk euro.' },
    ],
    esdizim: ['… euros', 'ça fait … euros'],
    aile: ["l'argent", 'le prix'],
    hata: 'Kuruşları söylerken "centimes" eklemek. Fransızcada genelde yalnız sayı söylenir: "douze euros cinquante".',
    hatirlatma: 'Baştaki "eu" Türkçedeki "ö" sesidir: ö-RO.',
    uretim: { yonerge: '"On beş euro." cümlesini yaz.', kabul: ['Quinze euros', 'Ça fait quinze euros'] },
  },
  {
    id: 'fr-prix',
    dil: 'fr',
    kelime: 'prix',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les prix (değişmez)',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Ce qu’il faut payer pour avoir quelque chose.',
    turkceDestek: 'fiyat',
    ipa: '/pʁi/',
    heceler: 'prix ("pri" · sondaki x okunmaz)',
    ornekler: [
      { fr: 'Les prix sont élevés ici.', tr: 'Burada fiyatlar yüksek.' },
      { fr: 'Quel est le prix de ce livre ?', tr: 'Bu kitabın fiyatı ne?' },
    ],
    esdizim: ['le prix de', 'à bon prix'],
    aile: ['coûter', 'payer', "l'argent"],
    hata: 'Günlük konuşmada "Quel est le prix ?" demek. Doğaldır ama resmîdir; sokakta "C’est combien ?" kullanılır.',
    hatirlatma: 'Aynı kelime "ödül" anlamına da gelir: le prix Nobel.',
    uretim: { yonerge: '"Bu ne kadar?" sorusunu günlük dille yaz.', kabul: ["C'est combien", 'Ça coûte combien', 'C’est combien'] },
  },
  {
    id: 'fr-marche',
    dil: 'fr',
    kelime: 'marché',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les marchés',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'L’endroit en plein air où on achète des fruits et des légumes.',
    turkceDestek: 'pazar (semt pazarı)',
    ipa: '/maʁ.ʃe/',
    heceler: 'mar-ché ("mar-ŞE")',
    ornekler: [
      { fr: 'Le samedi, je vais au marché.', tr: 'Cumartesi günleri pazara giderim.' },
      { fr: 'Les fruits sont moins chers au marché.', tr: 'Meyveler pazarda daha ucuz.' },
    ],
    esdizim: ['aller au marché', 'le marché du samedi'],
    aile: ['le supermarché', 'les courses'],
    hata: '"le marché" (semt pazarı) ile "le supermarché" (süpermarket) karıştırılır.',
    hatirlatma: 'Haftanın günüyle birlikte söylenir: "le marché du mardi".',
    uretim: { yonerge: '"Pazara gidiyorum." cümlesini yaz.', kabul: ['Je vais au marché', 'Je vais au marche'] },
  },
  {
    id: 'fr-boulangerie',
    dil: 'fr',
    kelime: 'boulangerie',
    artikel: 'la',
    cins: 'disil',
    cogul: 'les boulangeries',
    tur: 'isim',
    seviye: 'A1',
    fransizcaTanim: 'Le magasin où on achète du pain.',
    turkceDestek: 'fırın, ekmekçi',
    ipa: '/bu.lɑ̃.ʒʁi/',
    heceler: 'bou-lan-ge-rie (ikinci hece nazal)',
    ornekler: [
      { fr: 'Je passe à la boulangerie avant les cours.', tr: 'Derslerden önce fırına uğruyorum.' },
      { fr: 'La boulangerie ouvre à sept heures.', tr: 'Fırın yedide açılıyor.' },
    ],
    esdizim: ['à la boulangerie', 'le boulanger'],
    aile: ['le pain', 'la pâtisserie'],
    hata: 'Dişil olduğu için "au" değil "à la" kullanılır: "à la boulangerie".',
    hatirlatma: '-erie eki dükkân adı yapar: boulangerie, pâtisserie, librairie.',
    uretim: { yonerge: '"Fırına gidiyorum." cümlesini yaz.', kabul: ['Je vais à la boulangerie', 'Je vais a la boulangerie'] },
  },
  {
    id: 'fr-vouloir',
    dil: 'fr',
    kelime: 'vouloir',
    cekim: 'je veux · tu veux · il veut · nous voulons · vous voulez · ils veulent',
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    fransizcaTanim: 'Avoir le désir de quelque chose.',
    turkceDestek: 'istemek',
    ipa: '/vu.lwaʁ/',
    heceler: 'vou-loir ("vu-LUAR")',
    ornekler: [
      { fr: 'Je veux apprendre le français.', tr: 'Fransızca öğrenmek istiyorum.' },
      { fr: 'Tu veux du thé ?', tr: 'Çay ister misin?' },
    ],
    esdizim: ['vouloir + mastar', 'je voudrais'],
    aile: ['pouvoir', 'devoir'],
    hata: 'Sipariş verirken "je veux" kullanmak. Bu biçim emir gibi duyulur; kibar biçim "je voudrais"dir.',
    hatirlatma: '"je voudrais" bu fiilin kibar (koşul) biçimidir ve A1’de kalıp olarak öğrenilir.',
    uretim: { yonerge: 'Kibar biçimde bir kahve iste.', kabul: ['Je voudrais un café', "Je voudrais un café s'il vous plaît"] },
  },
  {
    id: 'fr-beaucoup',
    dil: 'fr',
    kelime: 'beaucoup (de)',
    tur: 'zarf',
    seviye: 'A1',
    fransizcaTanim: 'Une grande quantité.',
    turkceDestek: 'çok',
    ipa: '/bo.ku/',
    heceler: 'beau-coup ("bo-KU")',
    ornekler: [
      { fr: 'Il y a beaucoup de monde au marché.', tr: 'Pazarda çok insan var.' },
      { fr: 'Merci beaucoup !', tr: 'Çok teşekkürler!' },
    ],
    esdizim: ['beaucoup de', 'merci beaucoup'],
    aile: ['un peu', 'trop', 'assez'],
    hata: 'Miktar ifadesinden sonra artikel kullanmak: "beaucoup DU pain" değil, "beaucoup DE pain".',
    hatirlatma: 'Kural: bütün miktar ifadelerinden sonra yalnız "de" gelir (beaucoup de, un peu de, un kilo de).',
    uretim: { yonerge: '"Çok arkadaşım var." cümlesini yaz.', kabul: ["J'ai beaucoup d'amis", 'J’ai beaucoup d’amis'] },
  },
  {
    id: 'fr-un-peu',
    dil: 'fr',
    kelime: 'un peu (de)',
    tur: 'zarf',
    seviye: 'A1',
    fransizcaTanim: 'Une petite quantité.',
    turkceDestek: 'biraz',
    ipa: '/œ̃ pø/',
    heceler: 'un peu ("ön pö")',
    ornekler: [
      { fr: 'Je parle un peu français.', tr: 'Biraz Fransızca konuşuyorum.' },
      { fr: 'Je voudrais un peu de sucre.', tr: 'Biraz şeker istiyorum.' },
    ],
    esdizim: ['un peu de', 'un peu plus'],
    aile: ['beaucoup', 'assez'],
    hata: 'İsimden önce "de" eklemeyi unutmak: "un peu sucre" değil, "un peu DE sucre".',
    hatirlatma: 'Sıfat ya da zarf önünde "de" gelmez: "un peu fatigué" (biraz yorgun).',
    uretim: { yonerge: '"Biraz Fransızca konuşuyorum." cümlesini yaz.', kabul: ['Je parle un peu français', 'Je parle un peu le français'] },
  },
]
