/**
 * DRKOÇ — KELİME KAYITLARI: A2 / Modül 1 — Anılar ve alışkanlıklar
 *
 * Bu modülün zorluğu kelime değil, GEÇMİŞİN İKİYE BÖLÜNMESİDİR:
 * passé composé olan biteni, imparfait süren durumu anlatır. Türkçede
 * ikisi de "-di / -yordu" ile karşılanır ama seçim bağlamdan doğar.
 * Bu yüzden her kayıtta kelimenin hangi geçmiş zamanla birlikte
 * kullanıldığı yazar.
 */

export const KELIMELER = [
  {
    id: 'fr-dabord',
    dil: 'fr',
    kelime: 'd’abord',
    tur: 'zarf',
    seviye: 'A2',
    fransizcaTanim: 'En premier, avant les autres choses.',
    turkceDestek: 'önce, ilk olarak',
    ipa: '/da.bɔʁ/',
    heceler: 'd’a-bord',
    ornekler: [
      { fr: 'D’abord, j’ai fini mes devoirs.', tr: 'Önce ödevimi bitirdim.' },
      { fr: 'D’abord nous avons mangé, puis nous sommes sortis.', tr: 'Önce yemek yedik, sonra dışarı çıktık.' },
    ],
    esdizim: ['d’abord … puis', 'tout d’abord', 'd’abord … ensuite'],
    aile: ['le bord'],
    hata: 'Anlatının ilk adımını işaretler; cümle başında kullanılır ve virgülle ayrılır.',
    hatirlatma: 'Anlatı iskeleti: d’abord → puis → ensuite → enfin.',
    uretim: { yonerge: '"Önce ödevimi bitirdim." cümlesini yaz.', kabul: ["D'abord j'ai fini mes devoirs"] },
  },
  {
    id: 'fr-semaine-derniere',
    dil: 'fr',
    kelime: 'la semaine dernière',
    artikel: 'la',
    cins: 'disil',
    cogul: 'les semaines dernières',
    tur: 'isim',
    seviye: 'A2',
    fransizcaTanim: 'La semaine avant cette semaine.',
    turkceDestek: 'geçen hafta',
    ipa: '/la sə.mɛn dɛʁ.njɛʁ/',
    heceler: 'la se-maine der-nière',
    ornekler: [
      { fr: 'La semaine dernière, nous sommes allés à Izmir.', tr: 'Geçen hafta İzmir\'e gittik.' },
      { fr: 'J’ai beaucoup travaillé la semaine dernière.', tr: 'Geçen hafta çok çalıştım.' },
    ],
    esdizim: ['l’année dernière', 'le mois dernier', 'l’été dernier'],
    aile: ['dernier'],
    hata: 'Sıfat isimden SONRA gelir: "la semaine dernière". "La dernière semaine" başka anlama gelir (bir dizinin son haftası).',
    hatirlatma: 'Eril isimlerde biçim değişir: le mois dernier, l’an dernier.',
    uretim: { yonerge: '"Geçen hafta çok çalıştım." cümlesini yaz.', kabul: ["J'ai beaucoup travaillé la semaine dernière", "La semaine dernière j'ai beaucoup travaillé"] },
  },
  {
    id: 'fr-ensuite',
    dil: 'fr',
    kelime: 'ensuite',
    tur: 'zarf',
    seviye: 'A2',
    fransizcaTanim: 'Après cela, dans la suite des événements.',
    turkceDestek: 'ardından, daha sonra',
    ipa: '/ɑ̃.sɥit/',
    heceler: 'en-sui-te',
    ornekler: [
      { fr: 'Ensuite, nous sommes montés dans le bus.', tr: 'Ardından otobüse bindik.' },
      { fr: 'J’ai rangé ma chambre et ensuite j’ai lu un livre.', tr: 'Odamı topladım ve ardından kitap okudum.' },
    ],
    esdizim: ['et ensuite', 'puis ensuite', 'd’abord … ensuite'],
    aile: ['la suite', 'suivre'],
    hata: '"Puis" ile neredeyse aynıdır; "ensuite" biraz daha resmî ve yazıda tercih edilir.',
    hatirlatma: 'Anlatıda ikinci ve üçüncü adımı işaretler.',
    uretim: { yonerge: '"Ardından otobüse bindik." cümlesini yaz.', kabul: ['Ensuite nous sommes montés dans le bus'] },
  },
  {
    id: 'fr-puis',
    dil: 'fr',
    kelime: 'puis',
    tur: 'bağlaç',
    seviye: 'A2',
    fransizcaTanim: 'Après cela, comme étape suivante.',
    turkceDestek: 'sonra',
    ipa: '/pɥi/',
    heceler: 'puis (tek hece)',
    ornekler: [
      { fr: 'Nous avons déjeuné, puis nous sommes sortis.', tr: 'Öğle yemeği yedik, sonra dışarı çıktık.' },
      { fr: 'D’abord j’ai fini mes devoirs, puis j’ai regardé la télé.', tr: 'Önce ödevimi bitirdim, sonra televizyon izledim.' },
    ],
    esdizim: ['et puis', 'd’abord … puis', 'puis ensuite'],
    aie: [],
    aile: ['ensuite'],
    hata: '"Puis" ile "depuis" karıştırılır: "depuis" bir başlangıç noktasından beri süren zamanı anlatır.',
    hatirlatma: 'Anlatı iskeleti: d’abord → puis → ensuite → enfin.',
    uretim: { yonerge: '"Önce ders çalıştım, sonra dışarı çıktım." cümlesini yaz.', kabul: ["D'abord j'ai étudié, puis je suis sorti", "D'abord j'ai étudié puis je suis sorti"] },
  },
  {
    id: 'fr-enfin',
    dil: 'fr',
    kelime: 'enfin',
    tur: 'zarf',
    seviye: 'A2',
    fransizcaTanim: 'À la fin, comme dernière étape.',
    turkceDestek: 'sonunda, nihayet',
    ipa: '/ɑ̃.fɛ̃/',
    heceler: 'en-fin (iki burun sesi)',
    ornekler: [
      { fr: 'Enfin, nous avons trouvé l’adresse.', tr: 'Sonunda adresi bulduk.' },
      { fr: 'Le bus est enfin arrivé à neuf heures.', tr: 'Otobüs sonunda dokuzda geldi.' },
    ],
    esdizim: ['et enfin', 'enfin bref', 'enfin arriver'],
    aile: ['la fin', 'finalement'],
    hata: '"À la fin" yerin ya da metnin sonunu, "enfin" olay sırasının son adımını gösterir.',
    hatirlatma: 'Konuşmada "enfin bref" sözü "kısacası" anlamında kullanılır.',
    uretim: { yonerge: '"Sonunda otobüsü bulduk." cümlesini yaz.', kabul: ['Enfin nous avons trouvé le bus', 'Nous avons enfin trouvé le bus'] },
  },
  {
    id: 'fr-soudain',
    dil: 'fr',
    kelime: 'soudain',
    tur: 'zarf',
    seviye: 'A2',
    fransizcaTanim: 'Très vite et sans prévenir.',
    turkceDestek: 'aniden, birdenbire',
    ipa: '/su.dɛ̃/',
    heceler: 'sou-dain (sondaki burun sesi)',
    ornekler: [
      { fr: 'Soudain, il a commencé à pleuvoir.', tr: 'Birdenbire yağmur başladı.' },
      { fr: 'La voiture s’est arrêtée soudain.', tr: 'Araba aniden durdu.' },
    ],
    esdizim: ['tout à coup', 'soudain il', 'et soudain'],
    aile: ['soudainement'],
    hata: 'Anlatıda dönüm noktasını işaretler ve daima passé composé ile kullanılır; imparfait ile birlikte gelmez.',
    hatirlatma: '"Tout à coup" ile eşanlamlıdır ve konuşmada daha sık duyulur.',
    uretim: { yonerge: '"Birdenbire yağmur başladı." cümlesini yaz.', kabul: ['Soudain il a commencé à pleuvoir', 'Tout à coup il a commencé à pleuvoir'] },
  },
  {
    id: 'fr-se-passer',
    dil: 'fr',
    kelime: 'se passer',
    tur: 'fiil',
    seviye: 'A2',
    fransizcaTanim: 'Arriver, avoir lieu.',
    turkceDestek: 'olmak, meydana gelmek',
    ipa: '/sə pa.se/',
    heceler: 'se pas-ser',
    ornekler: [
      { fr: 'Qu’est-ce qui s’est passé hier ?', tr: 'Dün ne oldu?' },
      { fr: 'L’accident s’est passé près de l’école.', tr: 'Kaza okulun yakınında oldu.' },
    ],
    esdizim: ['qu’est-ce qui se passe', 'il ne s’est rien passé'],
    aile: ['passer', 'le passé'],
    hata: 'Dönüşlü fiildir ve passé composé\'de "être" ile çekilir: "s’est passé". "a passé" farklı anlam verir (vakit geçirmek).',
    hatirlatma: 'Günlük konuşmanın en sık sorusu: "Qu’est-ce qui se passe ?" = Ne oluyor?',
    uretim: { yonerge: '"Dün ne oldu?" sorusunu yaz.', kabul: ["Qu'est-ce qui s'est passé hier"] },
  },
  {
    id: 'fr-se-souvenir',
    dil: 'fr',
    kelime: 'se souvenir de',
    tur: 'fiil',
    seviye: 'A2',
    fransizcaTanim: 'Garder quelque chose dans la mémoire.',
    turkceDestek: 'hatırlamak',
    ipa: '/sə su.və.niʁ/',
    heceler: 'se sou-ve-nir',
    ornekler: [
      { fr: 'Je me souviens très bien de ce jour.', tr: 'O günü çok iyi hatırlıyorum.' },
      { fr: 'Tu te souviens de notre voyage ?', tr: 'Yolculuğumuzu hatırlıyor musun?' },
    ],
    esdizim: ['se souvenir de quelque chose', 'si je me souviens bien'],
    aile: ['le souvenir'],
    hata: 'Dönüşlü zamir ve "de" edatı birlikte gerekir: "je me souviens DE ce jour".',
    hatirlatma: '"Se rappeler" aynı anlamdadır ama edat almaz: "je me rappelle ce jour".',
    uretim: { yonerge: '"O günü çok iyi hatırlıyorum." cümlesini yaz.', kabul: ['Je me souviens très bien de ce jour'] },
  },
  {
    id: 'fr-voyage',
    dil: 'fr',
    kelime: 'voyage',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les voyages',
    tur: 'isim',
    seviye: 'A2',
    fransizcaTanim: 'Le fait d’aller d’un endroit à un autre.',
    turkceDestek: 'yolculuk, seyahat',
    ipa: '/vwa.jaʒ/',
    heceler: 'vo-ya-ge',
    ornekler: [
      { fr: 'Le voyage a duré quatre heures.', tr: 'Yolculuk dört saat sürdü.' },
      { fr: 'Nous avons fait un long voyage en bus.', tr: 'Otobüsle uzun bir yolculuk yaptık.' },
    ],
    esdizim: ['faire un voyage', 'bon voyage', 'un voyage scolaire'],
    aile: ['voyager', 'le voyageur'],
    hata: 'Yolculuk "yapılır": "faire un voyage". "Avoir un voyage" YANLIŞTIR.',
    hatirlatma: 'Kısa gezi "une excursion", günlük gidiş geliş "le trajet"dir.',
    uretim: { yonerge: '"Yolculuk üç saat sürdü." cümlesini yaz.', kabul: ['Le voyage a duré trois heures'] },
  },
  {
    id: 'fr-souvenir-isim',
    dil: 'fr',
    kelime: 'souvenir',
    artikel: 'le',
    cins: 'eril',
    cogul: 'les souvenirs',
    tur: 'isim',
    seviye: 'A2',
    fransizcaTanim: 'Ce qu’on garde dans la mémoire d’un moment passé.',
    turkceDestek: 'anı, hatıra',
    ipa: '/su.və.niʁ/',
    heceler: 'sou-ve-nir',
    ornekler: [
      { fr: 'J’ai un très bon souvenir de cet été.', tr: 'O yaza dair çok güzel bir anım var.' },
      { fr: 'Ce sont mes souvenirs d’enfance.', tr: 'Bunlar çocukluk anılarım.' },
    ],
    esdizim: ['un bon souvenir', 'des souvenirs d’enfance', 'garder un souvenir'],
    aile: ['se souvenir'],
    hata: 'Aynı kelime "hediyelik eşya" anlamına da gelir; bağlam ayırır.',
    hatirlatma: 'Anı yazısının başlığı için en uygun kelimedir: "Un souvenir d’enfance".',
    uretim: { yonerge: '"Bunlar çocukluk anılarım." cümlesini yaz.', kabul: ["Ce sont mes souvenirs d'enfance"] },
  },
  {
    id: 'fr-passionnant',
    dil: 'fr',
    kelime: 'passionnant',
    tur: 'sıfat',
    seviye: 'A2',
    fransizcaTanim: 'Très intéressant, qui donne envie de continuer.',
    turkceDestek: 'heyecan verici, sürükleyici',
    ipa: '/pa.sjɔ.nɑ̃/',
    heceler: 'pas-sion-nant',
    ornekler: [
      { fr: 'C’était un match passionnant.', tr: 'Heyecan verici bir maçtı.' },
      { fr: 'Le voyage était vraiment passionnant.', tr: 'Yolculuk gerçekten sürükleyiciydi.' },
    ],
    esdizim: ['un livre passionnant', 'trouver passionnant'],
    aile: ['la passion', 'se passionner'],
    hata: 'Kişi için "passionné" kullanılır: "je suis passionné de football" = futbol tutkunuyum.',
    hatirlatma: 'Karşıtı "ennuyeux" = sıkıcı.',
    uretim: { yonerge: '"Heyecan verici bir maçtı." cümlesini yaz.', kabul: ["C'était un match passionnant"] },
  },
  {
    id: 'fr-affreux',
    dil: 'fr',
    kelime: 'affreux',
    tur: 'sıfat',
    seviye: 'A2',
    fransizcaTanim: 'Très mauvais ou désagréable.',
    turkceDestek: 'berbat, korkunç',
    ipa: '/a.fʁø/',
    heceler: 'af-freux',
    ornekler: [
      { fr: 'Le temps était affreux toute la semaine.', tr: 'Hava bütün hafta berbattı.' },
      { fr: 'J’ai passé une nuit affreuse.', tr: 'Berbat bir gece geçirdim.' },
    ],
    esdizim: ['un temps affreux', 'une journée affreuse'],
    aile: [],
    hata: 'Dişil hâli "affreuse"dür; sonu değişir. "Affreux" eril biçimdir.',
    hatirlatma: '"Terrible" ile eşanlamlıdır ama konuşmada "terrible" bazen olumlu da kullanılır.',
    uretim: { yonerge: '"Hava berbattı." cümlesini yaz.', kabul: ['Le temps était affreux'] },
  },
]

export default KELIMELER
