import { createChemistryLesson } from './factory.js'

export default createChemistryLesson({
  slug: 'karisimlar',
  topic: 'Karışımlar',
  order: 0,
  partLabel: 'Gold Standard · 8. Konu',
  title: 'Karışımlar: Tanecik Dağılımından Ayırma Stratejisine',
  subtitle: 'Karışımı görünüşünden değil faz ve tanecik dağılımından tanı; çözünmeyi etkileşimle, derişimi oranla ve ayırmayı fiziksel özellik farkıyla açıkla.',
  minutes: 116,
  prerequisites: [
    'Saf madde, element ve bileşik kavramlarını ayırabilmek',
    'Polar–apolar yapı ve moleküller arası etkileşimleri hatırlamak',
    'Mol, kütle ve yüzde oranı hesaplayabilmek',
    'Kaynama, buhar basıncı ve hâl değişimi ilişkisini bilmek',
  ],
  outcomes: [
    'Saf madde ile karışımı bileşim ve ayırma davranışı üzerinden ayırt eder.',
    'Homojen ve heterojen karışımları faz sayısı ve tanecik dağılımıyla sınıflandırır.',
    'Çözelti, süspansiyon, emülsiyon, aerosol ve kolloidi örnekleriyle tanır.',
    'Çözünmeyi çözücü–çözünen etkileşimleri ve benzerlik ilkesiyle açıklar.',
    'Kütlece yüzde, hacimce yüzde ve ppm derişim ifadelerini yorumlar ve hesaplar.',
    'Seyreltme ve karıştırma işlemlerinde çözünen miktarının nasıl değiştiğini açıklar.',
    'Uçucu olmayan çözünenin buhar basıncı, kaynama ve donma davranışına etkisini yorumlar.',
    'Osmoz ve osmotik basıncı tanecik hareketiyle açıklar.',
    'Karışımın bileşenlerini tanecik boyutu, yoğunluk, kaynama noktası, çözünürlük, erime noktası ve manyetik özellik farkıyla ayırır.',
    'Çok bileşenli bir karışım için doğru işlem sırasını kurar.',
  ],
  sections: [
    {
      id: 'kar-hazirlik',
      kind: 'prepare',
      title: 'Bu konuyu öğrenmeden önce: Berrak olan her madde saf mıdır?',
      lead: 'Hava, kolonya ve tuzlu su berrak görünebilir; fakat birden fazla kimyasal tür içerir. Görünüş tek başına saflık kanıtı değildir.',
      blocks: [
        {
          id: 'kar-entry',
          type: 'prose',
          body: 'Saf maddenin bileşimi ve ayırt edici özellikleri belirli koşullarda sabittir. Karışımda ise iki veya daha çok madde kimyasal kimliklerini büyük ölçüde koruyarak bir araya gelir; bileşim değişebilir ve uygun **fiziksel özellik farklarından** yararlanılarak ayrılabilir. Tuzlu suyun tuz oranı değişebilir, ama saf NaCl bileşiğinin sodyum–klor oranı değişmez.\n\nKarışımın homojen veya heterojen olduğunu yalnız çıplak gözle karar vermek güvenli değildir. Süt tek biçimli görünse de mikroskobik yağ damlacıkları içerir; duman gaz içinde katı taneciklerin dağılmasıdır. Bu nedenle sınıflandırmada üç soru soracağız: **Kaç faz var? Dağılan taneciklerin boyutu ve kararlılığı nasıl? Zamanla çökme veya faz ayrımı oluyor mu?**\n\nBu derste önce karışımları sınıflandıracak, sonra çözünmenin tanecik mantığını ve derişim ifadelerini kuracağız. Ardından çözeltilerin kaynama–donma davranışını nitel olarak açıklayıp karışımı ayırmak için hangi özelliğin farklı olması gerektiğini seçeceğiz. Ayırma yöntemini ezberlemek yerine “hangi fark işe yarıyor?” sorusunu yöneteceğiz.',
        },
        {
          id: 'kar-prior',
          type: 'checkpoint',
          prompt: 'Şeker suda tamamen çözündüğünde şeker molekülleri yok olur mu? Çözeltiyi buharlaştırırsak ne beklenir?',
          hint: 'Çözünme kimyasal kimliği zorunlu olarak değiştirir mi, yoksa tanecikleri dağıtır mı?',
          answer: 'Şeker molekülleri yok olmaz; su molekülleri arasında moleküler düzeyde dağılır. Su buharlaştırıldığında uçucu olmayan şeker geride kalabilir ve uygun koşulda kristallenebilir. Bu, çözünmenin çoğunlukla fiziksel bir dağılma süreci olduğunu gösterir.',
        },
        {
          id: 'kar-first-trap',
          type: 'trap',
          title: 'Tek faz görüneni saf madde sanmak',
          wrong: '“Kolonya saydam ve tek fazlıdır; o hâlde saf maddedir.” demek.',
          right: 'Kolonya su, etanol ve koku bileşenlerinden oluşan homojen karışımdır. Tek fazlı görünmek saflığı değil, bileşenlerin moleküler düzeyde eşit dağılmasını gösterebilir.',
        },
      ],
    },
    {
      id: 'kar-sinif',
      kind: 'teach',
      title: 'Karışımları sınıflandır: Faz sayısı görünüşten daha güvenilir',
      lead: 'Homojen karışım her noktasında aynı özellik gösterir; heterojen karışımda dağılım veya fazlar aynı değildir.',
      blocks: [
        {
          id: 'kar-classification-figure',
          type: 'figure',
          kind: 'karisim-siniflandirma-atlasi',
          width: 'full',
          title: 'Çözeltiden aerosole dört dağılım modeli',
          purpose: 'Çözelti, süspansiyon, emülsiyon ve aerosol–kolloid örneklerini tanecik boyutu, faz ve kararlılıkla ayırmak.',
          complexity: 'high',
          caption: 'Dağılan tanecik büyüdükçe ışık saçılması, süzülme ve zamanla ayrılma eğilimi genellikle belirginleşir.',
          focus: [
            { title: 'Çözelti', body: 'Çözünen atom, iyon veya moleküller çözücü içinde homojen dağılır; tek fazlıdır, çökelmez ve normal süzgeçle ayrılmaz.' },
            { title: 'Süspansiyon', body: 'Katı tanecikler sıvıda heterojen dağılır; zamanla çökebilir ve uygun filtreyle ayrılabilir. Çamurlu su örnektir.' },
            { title: 'Emülsiyon', body: 'Birbiri içinde çözünmeyen iki sıvıdan biri diğerinde damlacıklar hâlinde dağılır. Süt ve mayonez örnektir.' },
            { title: 'Aerosol ve kolloid', body: 'Aerosolde katı veya sıvı, gaz içinde dağılır; sis ve duman örnektir. Kolloid tanecikleri çözeltiyle süspansiyon arasında boyuttadır ve ışığı saçabilir.' },
          ],
          audio_script: 'Çözeltide tanecikler moleküler veya iyonik düzeyde dağılır ve çökelmez. Süspansiyonda katı tanecikler daha büyüktür; zamanla çökme ve süzülme görülebilir. Emülsiyon, birbiri içinde çözünmeyen sıvı damlacıklarının dağılımıdır. Aerosolde dağıtıcı faz gazdır; sis sıvı damlacık, duman katı tanecik içerir. Kolloid tek biçimli görünse de dağılan tanecikler ışığı saçabilecek büyüklüktedir.',
        },
        {
          id: 'kar-classification-table',
          type: 'compare',
          interactive: true,
          title: 'Dağılım türlerini kanıtlarıyla karşılaştır',
          columns: ['Dağılan–dağıtıcı', 'Faz davranışı', 'Çökme / süzme', 'Örnek'],
          rows: [
            { label: 'Çözelti', values: ['Molekül/iyon düzeyinde', 'Homojen, tek faz', 'Çökmez; normal filtre tutmaz', 'Tuzlu su, hava, alaşım'] },
            { label: 'Süspansiyon', values: ['Katı–sıvı', 'Heterojen', 'Çökebilir; süzülebilir', 'Çamurlu su'] },
            { label: 'Emülsiyon', values: ['Sıvı–sıvı', 'Heterojen damlacık', 'Zamanla ayrılabilir', 'Süt, mayonez'] },
            { label: 'Aerosol', values: ['Katı/sıvı–gaz', 'Heterojen dağılım', 'Havada asılı kalabilir', 'Duman, sis'] },
            { label: 'Kolloid', values: ['Orta boy dağılan tanecik', 'Mikroheterojen', 'Kolay çökmez; ışığı saçar', 'Jelatin, köpük'] },
          ],
          insight: 'Alaşım katı olmasına rağmen homojen karışım olabilir; “çözelti yalnız sıvıdır” genellemesi yanlıştır.',
        },
        {
          id: 'kar-phase-why',
          type: 'why',
          question: 'Süt neden çıplak gözle homojen görünmesine rağmen heterojen kabul edilir?',
          body: 'Sütte yağ damlacıkları su temelli faz içinde çok küçük parçacıklar hâlinde dağılmıştır. Damlacıklar tek tek çıplak gözle seçilemeyebilir; fakat ikinci bir faz oluşturur ve ışığı saçar. Emülgatörler damlacıkların birleşmesini yavaşlatabilir. Homojenlik gözün ayırt etme sınırına değil, maddenin her noktasında moleküler düzeyde tek faz olup olmamasına bağlıdır.',
        },
      ],
    },
    {
      id: 'kar-cozunme-derisim',
      kind: 'teach',
      title: 'Çözünme ve derişim: Dağılımın nedeni, miktarın dili',
      lead: 'Çözünme için eski çekimlerin yerini yeterince güçlü çözücü–çözünen etkileşimleri almalıdır.',
      blocks: [
        {
          id: 'kar-solution-figure',
          type: 'figure',
          kind: 'cozunme-derisim-haritasi',
          width: 'full',
          title: 'Çözünmeden seyreltmeye tanecik ve oran haritası',
          purpose: 'Solvatasyon, benzer etkileşimler, yüzde derişim ve seyreltmeyi aynı çözeltide ilişkilendirmek.',
          complexity: 'high',
          caption: 'Seyreltmede çözünen miktarı korunur; çözücü ve toplam çözelti miktarı artar, birim miktardaki çözünen azalır.',
          focus: [
            { title: 'Solvatasyon', body: 'Çözücü tanecikleri çözünen taneciklerin çevresini sarar. Çözücü su ise süreç hidratasyon olarak adlandırılır.' },
            { title: 'Benzer benzeri çözer', body: 'Polar–iyonik türler polar çözücülerle, apolar türler apolar çözücülerle daha uygun etkileşim kurar; ilke kesin “her şeyi çözer” kuralı değildir.' },
            { title: 'Derişim oranı', body: 'Derişim, belirli miktar çözeltideki çözünen payıdır. Kütlece ve hacimce yüzde, aynı tür niceliklerin oranını yüzle ifade eder.' },
            { title: 'Seyreltme', body: 'Çözücü eklendiğinde çözünen miktarı değişmez; toplam hacim veya kütle arttığı için derişim azalır.' },
          ],
          audio_script: 'Çözünmede çözünen tanecikler birbirinden ayrılırken çözücü tanecikleri de aralanır ve aralarında yeni çekimler kurulur. Polar ve iyonik türler polar suyla, apolar türler apolar çözücülerle genellikle daha iyi karışır. Derişim, çözeltinin ne kadar çözünen taşıdığını oranla anlatır. Seyreltmede çözünen kaybolmaz; yalnız daha büyük çözelti miktarına dağıldığı için derişim düşer.',
        },
        {
          id: 'kar-concentration-formula',
          type: 'formula',
          title: 'TYT derişim ifadeleri',
          formulas: [
            { label: 'Kütlece yüzde', expression: '% m/m = [m(çözünen) / m(çözelti)] × 100' },
            { label: 'Hacimce yüzde', expression: '% V/V = [V(çözünen) / V(çözelti)] × 100' },
            { label: 'Çok seyreltik çözelti', expression: 'ppm = [m(çözünen) / m(çözelti)] × 10⁶' },
            { label: 'Çözelti kütlesi', expression: 'm(çözelti) = m(çözünen) + m(çözücü)' },
          ],
          note: 'Kütlece yüzde hesabında payda çözücü değil çözeltidir. ppm, milyon birim çözeltideki çözünen birimini anlatır.',
        },
        {
          id: 'kar-concentration-example',
          type: 'worked_example',
          title: 'Çözüneni ve çözücüyü karıştırma',
          prompt: '40 g tuz, 160 g suyla çözülüyor. Çözeltinin kütlece yüzde derişimini ve 50 g çözeltideki tuz kütlesini bul.',
          steps: [
            { label: 'Çözelti kütlesini bul', body: '40 + 160 = 200 g çözelti.' },
            { label: 'Yüzdeyi hesapla', body: '% m/m = 40/200 × 100 = %20.' },
            { label: 'Yeni örneğe uygula', body: 'Homojen çözeltinin her kısmı aynı orandadır: 50 × 0,20 = 10 g tuz.' },
            { label: 'Çözücüyü denetle', body: '50 g örneğin kalan 40 gramı sudur.' },
          ],
          result: 'Çözelti kütlece %20 tuz içerir; 50 gramında 10 g tuz vardır.',
        },
        {
          id: 'kar-dilution-example',
          type: 'worked_example',
          title: 'Seyreltmede korunan çözüneni izle',
          prompt: 'Kütlece %30’luk 100 g şeker çözeltisine 50 g su ekleniyor. Son derişimi bul.',
          steps: [
            { label: 'İlk çözüneni bul', body: '100 g çözeltinin %30’u, yani 30 g şekerdir.' },
            { label: 'Ekleneni tanı', body: 'Yalnız su eklendiği için şeker kütlesi 30 g olarak kalır.' },
            { label: 'Yeni toplamı bul', body: 'Çözelti kütlesi 100 + 50 = 150 g olur.' },
            { label: 'Yeni yüzdeyi hesapla', body: '30/150 × 100 = %20.' },
          ],
          result: 'Seyreltilmiş çözelti kütlece %20 şekerdir.',
        },
        {
          id: 'kar-concentration-trap',
          type: 'trap',
          title: 'Paydada yalnız çözücüyü kullanmak',
          wrong: '40 g tuz + 160 g su için 40/160 × 100 ile %25 bulmak.',
          right: 'Kütlece yüzde, çözünenin **çözelti toplamına** oranıdır: 40/(40+160) × 100 = %20.',
        },
      ],
    },
    {
      id: 'kar-koligatif',
      kind: 'connect',
      title: 'Çözelti özellikleri: Uçucu olmayan çözünen dengeyi nasıl değiştirir?',
      lead: 'Koligatif etki çözünenin kimliğinden çok çözeltideki tanecik sayısına bağlıdır; bu bölümde nitel ilişki kurulur, hesap yapılmaz.',
      blocks: [
        {
          id: 'kar-colligative-figure',
          type: 'figure',
          kind: 'koligatif-ozellikler-sistemi',
          width: 'full',
          title: 'Buhar basıncından osmoza dört çözelti etkisi',
          purpose: 'Uçucu olmayan çözünenin buharlaşma yüzeyi, kaynama, donma ve zar üzerinden su hareketine etkisini ilişkilendirmek.',
          complexity: 'high',
          caption: 'Aynı çözücüde tanecik derişimi arttıkça buhar basıncı düşer; kaynama sıcaklığı yükselir, donma sıcaklığı düşer.',
          focus: [
            { title: 'Buhar basıncı düşmesi', body: 'Uçucu olmayan çözünen yüzeyde çözücü taneciklerinin payını azaltır; birim zamanda gaz fazına kaçan çözücü sayısı azalabilir.' },
            { title: 'Kaynama noktası yükselmesi', body: 'Daha düşük buhar basıncının dış basınca eşit olması için daha yüksek sıcaklık gerekir.' },
            { title: 'Donma noktası düşmesi', body: 'Çözünen tanecikler çözücünün düzenli katı yapıyı kurmasını zorlaştırır; donma daha düşük sıcaklıkta başlar.' },
            { title: 'Osmoz ve osmotik basınç', body: 'Yarı geçirgen zardan çözücü, daha seyreltik taraftan daha derişik tarafa net geçer; geçişi durduran basınç osmotik basınçtır.' },
          ],
          audio_script: 'Uçucu olmayan çözünen, çözeltinin yüzeyinde çözücü taneciklerinin oranını azaltır ve buhar basıncını düşürür. Dış basınca ulaşmak için daha çok ısıtmak gerekir; kaynama sıcaklığı yükselir. Çözünen düzenli kristal oluşumunu da zorlaştırır; donma sıcaklığı düşer. Yarı geçirgen zarda ise çözücü daha seyreltik taraftan daha derişik tarafa net hareket eder.',
        },
        {
          id: 'kar-colligative-table',
          type: 'table',
          interactive: true,
          title: 'Saf çözücüye uçucu olmayan madde eklenirse',
          columns: ['Özellik', 'Değişim', 'Tanecik gerekçesi', 'Günlük örnek'],
          rows: [
            ['Buhar basıncı', 'Azalır', 'Yüzeyde çözücü payı azalır', 'Tuzlu su'],
            ['Kaynama sıcaklığı', 'Artar', 'Dış basınca ulaşmak için daha yüksek T gerekir', 'Yoğun şeker çözeltisi'],
            ['Donma sıcaklığı', 'Azalır', 'Kristal örgü kurulması zorlaşır', 'Yola tuz, radyatöre antifriz'],
            ['Osmotik basınç', 'Derişimle artar', 'Çözücü geçişini durdurmak için daha çok basınç gerekir', 'Hücre ve damar sıvıları'],
          ],
          insight: 'Yola tuz atmak buzu “ısıtmaz”; suyun donma noktasını düşüren bir çözelti oluşturur. Aşırı tuz çevre ve yapılara zarar verebilir.',
        },
        {
          id: 'kar-osmosis-why',
          type: 'why',
          question: 'Osmozda su neden “tuzun olduğu tarafa çekiliyor” diye tek cümleyle açıklanmamalıdır?',
          body: 'Yarı geçirgen zarın iki yanında su molekülleri iki yönde de hareket eder. Net geçiş, suyun kimyasal potansiyelinin daha yüksek olduğu seyreltik taraftan daha düşük olduğu derişik tarafa doğrudur. Basit TYT diliyle çözücü, seyreltik çözeltiden derişik çözeltiye geçer. Çözünenin zardan geçemediği ve sıcaklık gibi koşulların karşılaştırılabilir olduğu unutulmamalıdır.',
        },
        {
          id: 'kar-colligative-quiz',
          type: 'quiz',
          purpose: 'analyze',
          question: 'Aynı basınçta saf su ile uçucu olmayan tuz içeren su karşılaştırıldığında tuzlu su için hangisi beklenir?',
          options: ['Buhar basıncı daha yüksek, kaynama sıcaklığı daha düşük', 'Buhar basıncı daha düşük, kaynama sıcaklığı daha yüksek', 'Donma sıcaklığı daha yüksek', 'Bütün özellikler aynı'],
          answer_index: 1,
          explanation: 'Uçucu olmayan çözünen buhar basıncını düşürür. Dış basınca eşit buhar basıncına ulaşmak için daha yüksek sıcaklık gerekir; kaynama noktası yükselir ve donma noktası düşer.',
        },
      ],
    },
    {
      id: 'kar-ayirma',
      kind: 'teach',
      title: 'Ayırma ve saflaştırma: Yöntemi değil farkı seç',
      lead: 'Karışım bileşenleri kimliklerini koruduğu için tanecik boyutu, yoğunluk, kaynama noktası, çözünürlük, erime noktası veya manyetik özellik farkı kullanılabilir.',
      blocks: [
        {
          id: 'kar-separation-figure',
          type: 'figure',
          kind: 'karisim-ayirma-laboratuvari',
          width: 'full',
          title: 'Dört özellik farkından ayırma yöntemi seç',
          purpose: 'Tanecik boyutu–manyetik özellik, yoğunluk, kaynama noktası ve çözünürlük farklarını uygun tekniklerle eşleştirmek.',
          complexity: 'high',
          caption: 'En uygun yöntem, karışımın fazına ve bileşenler arasında ölçülebilir hangi farkın bulunduğuna bağlıdır.',
          focus: [
            { title: 'Tanecik boyutu ve mıknatıs', body: 'Eleme, süzme ve diyaliz boyut farkını; mıknatıs Fe, Ni, Co gibi güçlü çekilen bileşenlerin ayrımını kullanır.' },
            { title: 'Yoğunluk farkı', body: 'Birbiri içinde çözünmeyen sıvılar ayırma hunisiyle; uygun katılar yüzdürme veya çöktürmeyle ayrılabilir.' },
            { title: 'Kaynama noktası farkı', body: 'Basit damıtma çözelti çözücüsünü; ayrımsal damıtma birbirinde çözünen uçucu sıvıları kaynama farkıyla ayırır.' },
            { title: 'Çözünürlük farkı', body: 'Özütleme seçici çözünmeyi; kristallendirme sıcaklıkla çözünürlük değişimini; ayrımsal kristallendirme iki katının farklı çözünürlüğünü kullanır.' },
          ],
          audio_script: 'Ayırma sorusunda önce karışımın fazlarını belirle. İri katıyı boyut farkıyla ele veya süz. Birbiri içinde çözünmeyen sıvıları yoğunluk farkıyla ayırma hunisinde ayır. Tuzlu sudan hem suyu hem tuzu istiyorsan damıt; yalnız tuz isteniyorsa buharlaştırma düşünülebilir. İki uçucu sıvı için ayrımsal damıtma, seçici çözücü için özütleme, sıcaklıkla değişen çözünürlük için kristallendirme kullan.',
        },
        {
          id: 'kar-separation-table',
          type: 'compare',
          interactive: true,
          title: 'Yöntem–özellik–örnek sözlüğü',
          columns: ['Yararlanılan fark', 'Yöntem', 'Uygun karışım', 'Kritik ayrım'],
          rows: [
            { label: 'Tanecik boyutu', values: ['Eleme / süzme / diyaliz', 'Kum–çakıl; çamurlu su; kan–atık', 'Zar veya gözenek uygun boyutta olmalı'] },
            { label: 'Yoğunluk', values: ['Ayırma hunisi / yüzdürme', 'Yağ–su; cevher zenginleştirme', 'Sıvılar birbirinde çözünmemeli'] },
            { label: 'Kaynama noktası', values: ['Basit / ayrımsal damıtma', 'Tuzlu su; alkol–su; ham petrol', 'Uçuculuk ve kaynama farkı gerekir'] },
            { label: 'Çözünürlük', values: ['Özütleme / kristallendirme', 'Çay demleme; şeker üretimi', 'Seçici çözücü veya sıcaklık etkisi'] },
            { label: 'Manyetik özellik', values: ['Mıknatıs', 'Demir tozu–kum', 'Bileşenlerden biri güçlü çekilmeli'] },
            { label: 'Erime noktası', values: ['Kontrollü eritme', 'Bazı metal karışımları', 'Erime noktaları yeterince farklı olmalı'] },
          ],
          insight: 'Buharlaştırmada çözücü genellikle geri kazanılmaz; basit damıtmada buhar yoğunlaştırılarak çözücü de toplanır.',
        },
        {
          id: 'kar-multistep-example',
          type: 'worked_example',
          title: 'Demir tozu–kum–tuz karışımını sırayla ayır',
          prompt: 'Üç katıyı da ayrı ayrı geri kazanacak işlem dizisini kur.',
          steps: [
            { label: 'Manyetik bileşeni ayır', body: 'Mıknatısla demir tozu karışımdan alınır.' },
            { label: 'Seçici çöz', body: 'Kalan kum–tuz karışımına su eklenir; tuz çözünür, kum çözünmez.' },
            { label: 'Süz', body: 'Kum filtrede kalır; tuzlu su süzüntüye geçer. Kum kurutularak geri kazanılır.' },
            { label: 'Tuzu geri kazan', body: 'Tuzlu su buharlaştırılır veya kristallendirilir; tuz kristalleri elde edilir.' },
          ],
          result: 'Sıra: mıknatıs → suda çözme → süzme → buharlaştırma/kristallendirme.',
        },
        {
          id: 'kar-distillation-trap',
          type: 'trap',
          title: 'Ayırma hunisi ile alkol–suyu ayırmak',
          wrong: 'Yoğunlukları farklı olduğu için alkol ve suyu ayırma hunisine koymak.',
          right: 'Alkol ve su birbirinde çözünür, tek fazlıdır; ayırma hunisi iki ayrı sıvı faz gerektirir. Kaynama noktası farkından yararlanan ayrımsal damıtma uygundur.',
        },
      ],
    },
    {
      id: 'kar-osym',
      kind: 'exam',
      title: 'ÖSYM sentezi: Fazı tanı, oranı kur, farkı seç',
      lead: 'Karışımlar sorusu çoğu zaman sınıflandırma, derişim ve ayırma bilgisini aynı günlük yaşam düzeninde birleştirir.',
      blocks: [
        {
          id: 'kar-osym-insight',
          type: 'osym_insight',
          title: 'Üç katmanlı çözüm protokolü',
          body: 'Önce **yapıyı** belirle: saf madde mi karışım mı, homojen mi heterojen mi, kaç faz var? Sonra **oranı** oku: payda çözelti mi çözücü mü, kütle mi hacim mi, ppm mi yüzde mi? Son olarak **özellik farkını** seç: tanecik boyutu, yoğunluk, kaynama, çözünürlük, erime veya manyetik davranış. Yöntem adı bu farkın doğal sonucudur.',
          measures: [
            'Berrak görünüş ile saflığı ayırma',
            'Çözelti, süspansiyon, emülsiyon ve aerosolu tanıma',
            'Kütlece yüzde ve seyreltmede çözünen korunumu',
            'Derişimle kaynama–donma davranışını nitel yorumlama',
            'Ayırma yöntemini kullanılan fiziksel özellik farkıyla eşleştirme',
            'Çok bileşenli karışımda işlem sırasını kurma',
          ],
        },
        {
          id: 'kar-simulation',
          type: 'osym_simulation',
          title: 'Mini TYT simülasyonu',
          stimulus: 'Demir tozu, zeytinyağı, su ve yemek tuzu içeren bir karışımın bütün bileşenleri geri kazanılmak isteniyor.',
          question: 'Aşağıdaki işlemlerden hangisi uygun dizinin bir parçası olamaz?',
          options: [
            'Demir tozunu mıknatısla ayırma',
            'Yağ ve tuzlu su fazlarını ayırma hunisiyle ayırma',
            'Tuzlu sudan suyu basit damıtmayla toplama',
            'Tuzu kristallendirme ile geri kazanma',
            'Yağ ve suyu ayrımsal damıtmayla tek faz hâlinde ayırma',
          ],
          answer_index: 4,
          explanation: 'Yağ ve su birbirinde çözünmeyen iki faz oluşturur; ayırma hunisi uygundur. Ayrımsal damıtma birbirinde çözünen uçucu sıvı karışımları için kullanılır.',
          strategy: 'Yöntemden önce faz ilişkisini kontrol et: “birbirinde çözünmeyen sıvılar” ifadesi ayırma hunisinin doğrudan kanıtıdır.',
        },
        {
          id: 'kar-final-quiz',
          type: 'quiz',
          purpose: 'synthesize',
          question: 'I. Uçucu olmayan çözünen eklenmesi çözeltinin buhar basıncını düşürebilir. II. Seyreltmede çözünen kütlesi zorunlu olarak azalır. III. Basit damıtma kaynama noktası farkından yararlanır. Hangileri doğrudur?',
          options: ['Yalnız I', 'I ve II', 'I ve III', 'I, II ve III'],
          answer_index: 2,
          explanation: 'I ve III doğrudur. Seyreltmede yalnız çözücü eklenirse çözünen miktarı aynı kalır; toplam çözelti miktarı arttığı için derişim azalır.',
        },
        {
          id: 'kar-summary',
          type: 'summary',
          title: 'Konunun kısa sentezi',
          items: [
            'Karışımlar değişken bileşimlidir ve uygun fiziksel özellik farklarıyla ayrılabilir.',
            'Homojen karışım tek fazlıdır; heterojen karışımda dağılım veya fazlar aynı değildir.',
            'Çözelti çökelmez; süspansiyon çökebilir, emülsiyon sıvı damlacık, aerosol gaz içinde dağılan faz içerir.',
            'Çözünmede çözücü–çözünen etkileşimi eski çekimlerin yerini alır; polarite benzerliği çözünürlüğü destekler.',
            'Kütlece yüzde paydasında çözelti toplamı bulunur; ppm milyon birim çözeltideki çözüneni anlatır.',
            'Seyreltmede çözünen korunur, toplam çözelti artar ve derişim düşer.',
            'Uçucu olmayan çözünen buhar basıncını ve donma sıcaklığını düşürür, kaynama sıcaklığını yükseltir.',
            'Osmozda çözücü yarı geçirgen zardan seyreltik taraftan derişik tarafa net geçer.',
            'Ayırma yöntemi tanecik boyutu, yoğunluk, kaynama, çözünürlük, erime veya manyetik özellik farkından seçilir.',
          ],
        },
        {
          id: 'kar-next',
          type: 'next',
          title: 'Sıradaki bağ: Asit, Baz ve Tuz',
          body: 'Çözelti, derişim ve iyonların suda dağılma mantığını kurdun. Sıradaki konuda asit ve bazların sulu çözelti davranışını, pH göstergelerini, nötralleşmeyi ve tuzların günlük yaşam bağlantılarını bu altyapıyla açıklayacaksın.',
        },
      ],
    },
  ],
})
