import { createChemistryLesson } from './factory.js'

const firstTwenty = [
  ['Hidrojen', 'H', 'Helyum', 'He'],
  ['Lityum', 'Li', 'Berilyum', 'Be'],
  ['Bor', 'B', 'Karbon', 'C'],
  ['Azot', 'N', 'Oksijen', 'O'],
  ['Flor', 'F', 'Neon', 'Ne'],
  ['Sodyum', 'Na', 'Magnezyum', 'Mg'],
  ['Alüminyum', 'Al', 'Silisyum', 'Si'],
  ['Fosfor', 'P', 'Kükürt', 'S'],
  ['Klor', 'Cl', 'Argon', 'Ar'],
  ['Potasyum', 'K', 'Kalsiyum', 'Ca'],
]

const frequentElements = [
  ['Krom', 'Cr', 'Mangan', 'Mn'],
  ['Demir', 'Fe', 'Kobalt', 'Co'],
  ['Nikel', 'Ni', 'Bakır', 'Cu'],
  ['Çinko', 'Zn', 'Brom', 'Br'],
  ['Gümüş', 'Ag', 'Kalay', 'Sn'],
  ['İyot', 'I', 'Baryum', 'Ba'],
  ['Platin', 'Pt', 'Altın', 'Au'],
  ['Cıva', 'Hg', 'Kurşun', 'Pb'],
]

const commonCompounds = [
  ['H₂O', 'Su', 'İçme suyu ve çözücü'],
  ['HCl', 'Tuz ruhu', 'Suda hidroklorik asit; temizlikte dikkatli kullanım'],
  ['H₂SO₄', 'Zaç yağı', 'Akü ve kimya sanayisi'],
  ['HNO₃', 'Kezzap', 'Gübre ve kimya sanayisi'],
  ['CH₃COOH', 'Sirke asidi', 'Sirkenin asit bileşeni'],
  ['CaCO₃', 'Kireç taşı', 'Mermer, tebeşir ve yapı malzemeleri'],
  ['NaHCO₃', 'Yemek sodası', 'Kabartma ve temizlik uygulamaları'],
  ['NH₃', 'Amonyak', 'Gübre ve temizlik ürünleri'],
  ['Ca(OH)₂', 'Sönmüş kireç', 'Harç, badana ve su arıtımı'],
  ['NaOH', 'Sud kostik', 'Sabun ve kimya sanayisi'],
  ['KOH', 'Potas kostik', 'Yumuşak/sıvı sabun üretimi'],
  ['CaO', 'Sönmemiş kireç', 'Çimento ve yapı uygulamaları'],
  ['NaCl', 'Yemek tuzu', 'Beslenme ve kimya sanayisi'],
]

export default createChemistryLesson({
  slug: 'kimya-bilimi',
  topic: 'Kimya Bilimi',
  order: 0,
  partLabel: 'Gold Standard · 1. Konu',
  title: 'Kimya Bilimi: Maddeden Kanıta, Sembolden Güvenli Kullanıma',
  subtitle: 'Kimyayı bir ezber listesi olarak değil; maddeyi gözlemleyen, taneciklerle açıklayan ve sembollerle anlatan bir bilim olarak kur.',
  minutes: 58,
  prerequisites: [
    {
      topic: 'Ön bilgi zorunlu değil',
      why: 'Element, atom, bileşik ve formül kavramları bu ders içinde sıfırdan kurulacak.',
    },
    {
      topic: 'Gözlem ile yorum ayrımı',
      why: '“Renk değişti” gözlem; “yeni madde oluştu” ise kanıta dayalı yorumdur.',
    },
  ],
  outcomes: [
    'Simya ile modern kimyayı amaç, yöntem ve kanıt bakımından ayırabileceksin.',
    'Kimyanın yedi temel alt disiplinini gerçek bir problemle eşleştirebileceksin.',
    'Element, bileşik, sembol ve formül kavramlarını tanecik düzeyiyle ilişkilendirebileceksin.',
    'TYT kapsamındaki element sembollerini ve yaygın bileşik formüllerini okuyabileceksin.',
    'Tehlike piktogramını görüp uygun güvenlik davranışını seçebileceksin.',
    'Temel laboratuvar araçlarını görev ve ölçüm hassasiyetine göre ayırabileceksin.',
    'Kimyasal maddelerin yarar ve zararını madde, doz, maruz kalma yolu ve koşulla birlikte değerlendirebileceksin.',
  ],
  sections: [
    {
      id: 'kb-hazirlik',
      kind: 'opening',
      title: 'Bu konuyu öğrenmeden önce: Kimya zaten hayatının içinde',
      lead: 'Diş macununun aşındırıcılığı, ekmeğin kabarması, suyun arıtılması ve bir pilin çalışması farklı görünür; hepsi maddenin yapısı ve dönüşümüyle ilgilidir.',
      blocks: [
        {
          id: 'kb-hazirlik-prose',
          type: 'prose',
          body: 'Kimya; **maddenin yapısını, özelliklerini, başka maddelerle etkileşimini ve geçirdiği dönüşümleri** inceler. Buradaki “madde” yalnız laboratuvardaki renkli sıvılar değildir. Soluduğun hava, telefon ekranı, ilaç, deterjan, toprak, kan ve içtiğin su da kimyanın konusudur.\n\nBu derste önce kimyanın nasıl bilim hâline geldiğini göreceksin. Sonra aynı olayı üç dilde okumayı öğreneceksin: çıplak gözle gördüğün **makroskobik** düzey, taneciklerle açıkladığın **alt mikroskobik** düzey ve sembol/formülle yazdığın **sembolik** düzey. Son bölümde bu bilginin güvenli davranışa nasıl dönüştüğünü uygulayacaksın.\n\nKonu ileride **Atom ve Periyodik Sistem** için alfabeyi, **Kimyasal Türler Arası Etkileşimler** için tanecik fikrini, **Mol Kavramı** için formül okuryazarlığını ve **Asit–Baz–Tuz** için güvenli madde kullanımını kurar.',
        },
        {
          id: 'kb-hazirlik-check',
          type: 'checkpoint',
          prompt: 'Bir öğrenci, üzerinde “doğal” yazdığı için bir temizlik ürününün zararsız olduğunu söylüyor. Bu yargıyı kabul etmek için hangi bilgileri görmek istersin?',
          hint: 'Bir maddenin kaynağı tek başına güvenliği belirler mi? Etiket, miktar ve kullanım biçimini düşün.',
          answer: '“Doğal” sözcüğü güvenlik kanıtı değildir. Maddenin içeriği, derişimi/dozu, maruz kalma yolu, tehlike piktogramı, kullanım talimatı ve başka maddelerle karıştırılıp karıştırılmadığı bilinmelidir.',
        },
        {
          id: 'kb-hazirlik-trap',
          type: 'trap',
          title: 'Kimyasal sözcüğünü “zararlı” ile eşitlemek',
          wrong: '“Doğal maddeler kimyasal değildir; yalnız yapay maddeler kimyasaldır.” demek.',
          right: 'Maddelerin tamamı kimyasal yapıya sahiptir. Güvenliği belirleyen doğal/yapay etiketi değil; maddenin özelliği, miktarı ve kullanım koşuludur.',
          body: 'Su da oksijen de kimyasal maddedir. Buna karşılık doğal kökenli bazı maddeler toksik, sentetik bazı maddeler ise doğru kullanımda güvenli olabilir.',
        },
      ],
    },
    {
      id: 'kb-bilim',
      kind: 'build',
      title: 'Simyadan kimyaya: El becerisi ne zaman bilime dönüştü?',
      lead: 'Simya değersiz bir uğraş değildi; fakat sistematik ölçüm, sınanabilir açıklama ve tekrarlanabilir deney olmadan modern bilim sayılmaz.',
      blocks: [
        {
          id: 'kb-bilim-concept',
          type: 'concept',
          term: 'Simya',
          body: 'Maddeleri dönüştürme, değersiz metalleri altına çevirme ve ölümsüzlük iksiri bulma gibi amaçlarla yürütülen tarihsel uğraşların genel adıdır. Simyacılar damıtma, süzme, kristallendirme, özütleme ve alaşım hazırlama gibi birçok **uygulama tekniğini** geliştirdi; cam, seramik, boya, sabun, parfüm ve metal işleme birikimine katkı sağladı.\n\nAncak bilgi çoğu zaman gizli tutuluyor, nicel ölçüm sınırlı kalıyor ve açıklamalar sınanabilir bir kurama dayanmıyordu. Bu nedenle simya, kimyanın doğrudan kendisi değil; kimyaya araç, madde ve deneyim bırakan tarihsel bir hazırlık alanıdır.',
        },
        {
          id: 'kb-bilim-why',
          type: 'why',
          question: 'Bir işlem işe yarıyorsa neden tek başına bilim sayılmaz?',
          body: 'Bir sonucun tesadüf mü, koşullara bağlı mı, yoksa genel bir ilişki mi olduğunu anlamak için yöntem açıklanmalı; değişkenler kontrol edilmeli; ölçümler kaydedilmeli ve başka kişiler aynı koşullarda benzer sonuca ulaşabilmelidir. Bilim yalnız “ne yaptım?” demez; **neden böyle olduğunu ve hangi kanıtın bunu desteklediğini** de gösterir.\n\nModern kimyada iddia sınanabilir, deney tekrarlanabilir, veriler ölçülebilir ve yeni kanıt geldiğinde açıklama değişebilir. Bilimsel bilginin değişebilmesi onun zayıflığı değil, kanıta açık oluşudur.',
        },
        {
          id: 'kb-bilim-compare',
          type: 'compare',
          interactive: true,
          title: 'Simya ve kimya aynı tezgâhta, farklı yöntemle',
          columns: ['Simya', 'Modern kimya'],
          rows: [
            { label: 'Amaç', values: ['Altın/iksir arayışı ve pratik ürünler', 'Maddenin yapısını ve dönüşümünü açıklama, öngörme ve uygulama'] },
            { label: 'Yöntem', values: ['Deneme-yanılma ve ustalık geleneği ağırlıklı', 'Kontrollü deney, ölçme ve sistematik gözlem'] },
            { label: 'Bilginin paylaşımı', values: ['Sembolik, kişisel veya gizli olabilir', 'Yöntem ve sonuç denetlenebilir biçimde yayımlanır'] },
            { label: 'Sınanabilirlik', values: ['Her iddia test edilebilir değildir', 'İddia kanıtla desteklenir veya çürütülebilir'] },
            { label: 'Ortak nokta', values: ['Maddeyle çalışır, araç ve teknik geliştirir', 'Tarihsel teknik birikimden yararlanır'] },
          ],
          insight: 'Ayırıcı çizgi “deney yapmak” değil; deneyi **ölçülebilir, tekrarlanabilir ve açıklanabilir** hâle getirmektir.',
        },
        {
          id: 'kb-bilim-timeline',
          type: 'timeline',
          title: 'Fikirden ölçüye uzanan kısa yol',
          intro: 'Bu isimleri biyografi listesi olarak değil, madde hakkındaki düşünme biçimini nasıl değiştirdikleriyle tanı.',
          items: [
            { title: 'Empedokles ve Aristoteles', body: 'Maddeyi dört unsur ve niteliklerle açıklayan görüşler geliştirdi. Tarihsel olarak etkiliydi; modern element kavramı değildir.' },
            { title: 'Demokritos', body: 'Maddenin daha fazla bölünemeyen “atomos” parçacıklarından oluştuğunu düşünsel bir model olarak ileri sürdü; deneysel kanıt sunmadı.' },
            { title: 'Câbir bin Hayyan', body: 'Maddelerle sistemli çalışma, araçlar ve ayırma teknikleri geleneğinin gelişmesine katkıda bulundu.' },
            { title: 'Ebû Bekir er-Râzî', body: 'Maddelerin ve laboratuvar araçlarının sınıflandırılmasına, deneysel uygulamaların düzenlenmesine katkı sağladı.' },
            { title: 'Robert Boyle', body: 'Elementi dört unsur anlayışından ayıran deneysel yaklaşımı güçlendirdi; gazların basınç–hacim ilişkisini nicel olarak inceledi.' },
            { title: 'Antoine Lavoisier', body: 'Hassas kütle ölçümleriyle yanmayı oksijenle açıkladı, kütlenin korunmasını temellendirdi ve sistematik adlandırmayı geliştirdi.' },
          ],
          takeaway: 'Kimyaya geçiş tek bir kişinin bir günde yaptığı devrim değildir; açıklamanın giderek daha ölçülebilir ve denetlenebilir hâle gelmesidir.',
        },
        {
          id: 'kb-bilim-quiz',
          type: 'quiz',
          purpose: 'concept',
          question: 'Aşağıdakilerden hangisi bir çalışmayı modern kimyaya en güçlü biçimde yaklaştırır?',
          options: ['Sonucun yalnız ustanın bildiği simgelerle saklanması', 'Bir karışımın birçok kez denenmesi fakat miktarların yazılmaması', 'Koşulların, ölçümlerin ve yöntemin başkalarınca denetlenebilir biçimde kaydedilmesi', 'Amaç olarak değersiz metali altına dönüştürmenin seçilmesi'],
          answer_index: 2,
          explanation: 'Bilimsel yöntemin ayırıcı yanı yalnız deney yapmak değil; koşul, ölçüm ve yöntemi **denetlenebilir ve tekrarlanabilir** kılmaktır.',
        },
      ],
    },
    {
      id: 'kb-disiplin',
      kind: 'deepen',
      title: 'Kimya tek bir oda değil: Alt disiplinler ve çalışma alanları',
      lead: 'Gerçek bir problem çoğu zaman birkaç alt disiplinin iş birliğini gerektirir; soru, problemin baskın yönünü tanımaktır.',
      blocks: [
        {
          id: 'kb-disiplin-table',
          type: 'table',
          interactive: true,
          title: '“Hangi kimya?” karar tablosu',
          columns: ['Alt disiplin', 'Temel sorusu', 'Örnek çalışma'],
          rows: [
            ['Analitik kimya', 'Ne var, ne kadar var?', 'İçme suyundaki kurşun miktarını belirleme'],
            ['Organik kimya', 'Karbon temelli bileşikler nasıl yapı ve tepkime gösterir?', 'İlaç etken maddesi veya boya molekülü sentezi'],
            ['Anorganik kimya', 'Metaller, mineraller, tuzlar ve karbon dışı sistemler nasıl davranır?', 'Seramik, alaşım ve koordinasyon bileşikleri'],
            ['Biyokimya', 'Canlılardaki molekül ve tepkimeler nasıl işler?', 'Enzim, kan glikozu veya DNA incelemesi'],
            ['Fizikokimya', 'Enerji, hız ve denge maddenin davranışını nasıl belirler?', 'Pil gerilimi, tepkime hızı veya faz dengesi'],
            ['Polimer kimyası', 'Tekrarlanan birimlerden uzun zincirli malzeme nasıl tasarlanır?', 'Naylon, kauçuk veya biyobozunur plastik'],
            ['Endüstriyel kimya', 'Laboratuvar süreci güvenli ve verimli büyük üretime nasıl taşınır?', 'Gübre, çimento, deterjan veya petrokimya üretimi'],
          ],
          caption: 'Sınırların geçirgen olduğunu unutma: Bir ilacın saflığını analitik kimya ölçebilir, organik kimya molekülü sentezleyebilir, biyokimya canlıdaki etkisini inceleyebilir.',
        },
        {
          id: 'kb-disiplin-case',
          type: 'worked_example',
          title: 'Bir su arıtma probleminde disiplinleri eşleştir',
          prompt: 'Bir belediye, şebeke suyunda istenmeyen metal iyonları bulunduğunu saptıyor; miktarı belirlemek, uygun tutucu malzeme geliştirmek ve yöntemi tesise ölçeklemek istiyor. Hangi disiplin hangi işi üstlenir?',
          steps: [
            { title: 'Soruyu “ne var, ne kadar?” diye ayır', body: 'Metal iyonunun türü ve derişimi **analitik kimyanın** ölçüm problemidir.' },
            { title: 'Malzemenin yapısını seç', body: 'İyonu tutacak mineral/anorganik yüzey **anorganik kimya**; polimer filtre ise **polimer kimyası** bilgisi gerektirir.' },
            { title: 'Koşulları optimize et', body: 'Tutunmanın sıcaklık, denge ve hızla ilişkisi **fizikokimyanın** alanına girer.' },
            { title: 'Tesise taşı', body: 'Maliyet, güvenlik, atık ve sürekli üretim koşulları **endüstriyel kimya** yaklaşımıyla düzenlenir.' },
          ],
          answer: 'Gerçek problem tek etiket taşımaz; baskın soruya göre disiplin seçilir ve sonuçlar birleştirilir.',
          takeaway: 'Alt disiplin sorusunda anahtar kelime ezberlemek yerine yapılan işlemin amacını sor.',
        },
        {
          id: 'kb-meslek-compare',
          type: 'compare',
          interactive: true,
          title: 'Meslek adından önce görevi ayır',
          columns: ['Temel odak', 'Tipik görev'],
          rows: [
            { label: 'Kimyager', values: ['Maddenin analizi, sentezi ve araştırılması', 'Numune incelemek, yöntem geliştirmek, laboratuvar verisini yorumlamak'] },
            { label: 'Kimya mühendisi', values: ['Sürecin tasarımı ve büyük ölçekli üretim', 'Reaktör, enerji, verim, güvenlik ve üretim hattını yönetmek'] },
            { label: 'Eczacı', values: ['İlacın güvenli hazırlanması ve doğru kullanımı', 'İlaç sunumu, etkileşim ve hasta danışmanlığı'] },
            { label: 'Metalurji ve malzeme mühendisi', values: ['Metal ve diğer malzemelerin üretim/özellik ilişkisi', 'Alaşım, ısıl işlem, dayanım ve üretim yöntemi tasarlamak'] },
            { label: 'Kimya öğretmeni', values: ['Kimya bilgisinin güvenli ve anlamlı öğretilmesi', 'Deney, model, ölçme ve kavram gelişimini planlamak'] },
          ],
          insight: 'Kimyager “maddeyi ve veriyi”, kimya mühendisi çoğunlukla “süreci ve ölçeği” merkezine alır; ikisi birçok projede birlikte çalışır.',
        },
        {
          id: 'kb-disiplin-exam',
          type: 'exam',
          title: 'Alt disiplin sorusunda fiili yakala',
          body: '“Belirlemek/ölçmek” analitik; “canlıdaki etkisini incelemek” biyokimya; “karbon temelli molekül sentezlemek” organik; “uzun zincirli malzeme geliştirmek” polimer; “enerji–hız–dengeyi açıklamak” fizikokimya; “büyük ölçekte üretmek” endüstriyel kimya yönünde güçlü ipucudur. Yine de bağlamı okumadan yalnız kelimeye karar verme.',
          patterns: ['İçme suyu analizi', 'İlaç molekülü ve canlı etkisi', 'Plastik türü geliştirme', 'Üretim hattını ölçekleme'],
        },
      ],
    },
    {
      id: 'kb-dil',
      kind: 'build',
      title: 'Kimyanın üç dili: Gözlem, tanecik ve sembol',
      lead: 'Bir formülü gerçekten anlamak, onu ezberden yazmak değil; gözlenen madde ve görünmeyen tanecik modeliyle bağlamaktır.',
      blocks: [
        {
          id: 'kb-dil-figure',
          type: 'figure',
          kind: 'kimya-gosterim-duzeyleri',
          width: 'full',
          title: 'Aynı maddeyi üç düzeyde okumak',
          purpose: 'Makroskobik gözlem, tanecik modeli ve sembolik gösterim arasındaki bağı su örneğiyle kurmak.',
          complexity: 'medium',
          caption: 'Kimyasal sembol, görünür maddenin kısaltması olmaktan fazlasıdır; tanecik türü ve oranı hakkında bilgi taşır.',
          focus: [
            { title: 'Makroskobik düzey', body: 'Duyu organı veya ölçüm aracıyla gözlenen özellikler: hâl, renk, sıcaklık, hacim, kütle, gaz çıkışı gibi.' },
            { title: 'Alt mikroskobik düzey', body: 'Atom, iyon ve molekül gibi doğrudan gözlenemeyen taneciklerle kurulan açıklama modeli.' },
            { title: 'Sembolik düzey', body: 'Element sembolü, kimyasal formül ve denklemle yapılan kısa ve evrensel temsil.' },
          ],
          audio_script: 'Bir bardak suya baktığında renksiz bir sıvı görürsün; bu makroskobik düzeydir. Tanecik modeline geçtiğinde her su taneciğini iki hidrojen ve bir oksijen atomuyla açıklarsın. H₂O yazdığında bu modeli sembolik dile çevirirsin. Sınavda hata genellikle bu üç düzeyden biri diğerinin yerine konduğunda çıkar: formül taneciğin fotoğrafı değildir, tanecik modeli de çıplak gözle gördüğün görüntü değildir.',
        },
        {
          id: 'kb-element-compound',
          type: 'compare',
          interactive: true,
          title: 'Element ve bileşik: “Saf” olmak aynı olmak değildir',
          columns: ['Element', 'Bileşik'],
          rows: [
            { label: 'Tanecik türündeki atom', values: ['Tek tür atom içerir', 'En az iki farklı element atomu içerir'] },
            { label: 'Gösterim', values: ['Sembol: Fe, O, Na', 'Formül: H₂O, CO₂, NaCl'] },
            { label: 'Kimyasal ayrıştırma', values: ['Daha basit saf maddelere ayrılamaz', 'Elementlerine veya daha basit maddelere ayrılabilir'] },
            { label: 'Oran', values: ['Farklı element oranı yoktur', 'Elementler belirli ve sabit oranda birleşir'] },
            { label: 'Örnek uyarısı', values: ['O₂ bir elementtir; molekül olması bileşik yapmaz', 'NaCl bileşiktir; ayrı Na ve Cl özelliklerini göstermez'] },
          ],
          insight: '“Molekül” taneciğin yapısını, “element/bileşik” ise hangi atom türlerini içerdiğini anlatır. O₂ molekül yapılı element; H₂O molekül yapılı bileşiktir.',
        },
        {
          id: 'kb-symbol-rule',
          type: 'process',
          title: 'Bir sembolü ve formülü doğru oku',
          intro: 'Kimyasal dil büyük–küçük harfe ve sayıların yerine duyarlıdır.',
          steps: [
            { title: 'Sembolün ilk harfi büyük yazılır', body: 'Karbon **C**, kalsiyum **Ca**, kobalt **Co**. “CO” ise C ve O içeren başka bir gösterimdir; **Co** ile aynı değildir.' },
            { title: 'İkinci harf varsa küçüktür', body: 'Klor **Cl**, krom **Cr**, bakır **Cu**. Sembol her zaman Türkçe adın ilk harfi olmak zorunda değildir: sodyum **Na**, potasyum **K**, demir **Fe**.' },
            { title: 'Alt indis, bir tanecikteki atom sayısını gösterir', body: 'H₂O’da iki H ve bir O vardır. “1” yazılmaz. Parantez dışındaki alt indis parantez içindeki grubun tamamına etki eder: Ca(OH)₂’de iki O ve iki H bulunur.' },
            { title: 'Formül, sabit oranı gösterir', body: 'H₂O ile H₂O₂ aynı elementleri içerir ama oranları ve maddeleri farklıdır. Formüldeki küçük sayı “önemsiz ayrıntı” değildir.' },
          ],
        },
        {
          id: 'kb-dil-trap',
          type: 'trap',
          title: 'Sembolde büyük–küçük harfi önemsiz sanmak',
          wrong: '“Co, CO ve Co₂ aynı şeyi anlatır; harfler aynı.” diye düşünmek.',
          right: '**Co** kobalt elementinin sembolüdür. **CO**, karbon ve oksijen içeren karbon monoksit formülüdür. **Co₂** ise bu bağlamda kobalt sembolüne alt indis eklenmiş farklı bir gösterim olur.',
          body: 'Kimyasal yazım bir dilbilgisi taşır; harfin büyüklüğü ve sayının konumu anlamı değiştirir.',
        },
        {
          id: 'kb-dil-quiz',
          type: 'quiz',
          purpose: 'apply',
          question: 'Aşağıdaki yorumlardan hangisi doğrudur?',
          options: ['O₂ iki atom türü içerdiği için bileşiktir.', 'NaCl semboldür; tek elementi gösterir.', 'Ca(OH)₂ formülündeki alt indis hem O hem H için ikişer atom bulunduğunu gösterir.', 'Co ve CO yalnız yazım biçimi farklı olan aynı elementtir.'],
          answer_index: 2,
          explanation: 'Parantez dışındaki 2, OH grubunun tamamını iki kez saydırır. O₂ tek atom türü içerdiği için elementtir; NaCl bileşik formülüdür; Co ve CO farklı gösterimlerdir.',
        },
      ],
    },
    {
      id: 'kb-semboller',
      kind: 'deepen',
      title: 'TYT sembol ve formül atlası',
      lead: 'Bu bölüm ezberden kaçamaz; ama örüntü, köken ve sık karşılaştırmayla ezberi daha güvenilir hâle getirebilirsin.',
      blocks: [
        {
          id: 'kb-first20',
          type: 'table',
          interactive: true,
          title: 'Periyodik sistemde ilk 20 element',
          columns: ['Element', 'Sembol', 'Element', 'Sembol'],
          rows: firstTwenty,
          caption: 'İlk 20 sıra H’den Ca’ya kadar ilerler. İki harfli sembolde yalnız ilk harf büyüktür.',
        },
        {
          id: 'kb-symbol-memory',
          type: 'memory',
          title: 'Adıyla doğrudan eşleşmeyenleri kümeyle',
          body: '**Na–sodyum, K–potasyum, Fe–demir, Cu–bakır, Ag–gümüş, Sn–kalay, Au–altın, Hg–cıva, Pb–kurşun.** Bunları tek tek rastgele değil, günlük metal grubu olarak birlikte tekrar et.',
        },
        {
          id: 'kb-frequent',
          type: 'table',
          interactive: true,
          title: 'Günlük hayatta sık karşılaşılan ek elementler',
          columns: ['Element', 'Sembol', 'Element', 'Sembol'],
          rows: frequentElements,
          caption: 'MEB–TYT kapsamındaki sık kullanılan elementler. Sembolü Türkçe addan çıkmayanlar tarihsel/Latince ad kökeni taşır.',
        },
        {
          id: 'kb-compounds',
          type: 'table',
          interactive: true,
          title: 'Yaygın bileşikler: formül, günlük ad ve bağlam',
          columns: ['Formül', 'Yaygın ad', 'Günlük/teknolojik bağlam'],
          rows: commonCompounds,
          caption: 'Yaygın ad, güvenli kullanım talimatı değildir. Tuz ruhu, kezzap, zaç yağı ve kostikler aşındırıcı olabilir; etiketsiz kapta saklanmaz.',
        },
        {
          id: 'kb-formula-worked',
          type: 'worked_example',
          title: 'Formülü sayıya çevir: Ca(OH)₂',
          prompt: 'Bir Ca(OH)₂ taneciğinde/formül biriminde her elementten kaç atom bulunduğunu belirle.',
          steps: [
            { title: 'Parantez dışını bul', body: 'Parantezin dışındaki 2, içerideki **O ve H’nin her ikisini** çarpar.' },
            { title: 'Yazılmayan 1’leri gör', body: 'Ca’nın yanında sayı yoktur: 1 Ca. Parantez içindeki O ve H’nin kendi alt indisi yoktur: her grupta 1 O ve 1 H.' },
            { title: 'Toplamı yaz', body: '1 Ca, 2 O ve 2 H atomu bulunur; toplam atom sayısı 5’tir.' },
          ],
          answer: 'Ca: 1, O: 2, H: 2; toplam 5 atom.',
          takeaway: 'Alt indis yalnız hemen solundaki sembole; parantez dışındaysa parantezdeki grubun tamamına etki eder.',
        },
        {
          id: 'kb-symbol-exam',
          type: 'exam',
          title: 'Sembol sorusu yalnız hafıza ölçmez',
          body: 'ÖSYM, sembolü tanecik modeli veya formül okuma ile birleştirebilir. Önce kaç **element türü**, sonra her türden kaç **atom** bulunduğunu ayır. “Molekül” sözcüğünü otomatik olarak “bileşik” sanma.',
          patterns: ['Büyük–küçük harf ayrımı', 'Element türü sayısı', 'Alt indis ve parantez', 'Element–bileşik–molekül sınıflandırması'],
        },
      ],
    },
    {
      id: 'kb-guvenlik',
      kind: 'deepen',
      title: 'Kimyasal güvenlik: Piktogramı davranışa çevir',
      lead: 'Bir işareti adlandırmak başlangıçtır; asıl beceri riski tanıyıp doğru önlemi seçmektir.',
      blocks: [
        {
          id: 'kb-guvenlik-figure',
          type: 'figure',
          kind: 'kimya-guvenlik-piktogramlari',
          width: 'full',
          title: 'Kimyasal tehlike piktogramlarını risk aileleriyle oku',
          purpose: 'Temel güvenlik işaretlerini ayrı resimler olarak ezberletmek yerine risk ve davranış gruplarıyla ilişkilendirmek.',
          complexity: 'high',
          caption: 'Piktogram tehlikenin türünü bildirir; riskin düzeyi ve alınacak ayrıntılı önlem için etiket ile güvenlik bilgi formu birlikte okunur.',
          focus: [
            { title: 'Yangın ve tepkime riski', body: 'Patlayıcıyı darbe/ısıdan, yanıcıyı kıvılcım ve alevden uzak tut; oksitleyicinin yanmayı şiddetlendirebileceğini unutma.' },
            { title: 'Vücuda maruziyet riski', body: 'Toksik, tahriş edici ve ciddi sağlık tehlikesi aynı düzeyde değildir; tümünde temas ve solumayı önleyen uygun koruma gerekir.' },
            { title: 'Aşındırma ve çevre riski', body: 'Korozif madde cilt/göz ve metallere zarar verebilir. Çevre için tehlikeli madde lavaboya veya doğaya dökülmez.' },
            { title: 'Basınç ve radyasyon riski', body: 'Basınçlı kap ısıtılmaz/delinmez. Radyoaktif kaynak yalnız yetkili kişi ve özel koruma prosedürüyle kullanılır.' },
          ],
          audio_script: 'Piktogramlara tek tek resim adı gibi bakma. Önce dört aileye ayır. Alev ve patlama grubu enerji açığa çıkmasıyla; kafatası, ünlem ve göğüsteki yıldız insanın maddeye maruz kalmasıyla; korozif ve çevre işaretleri temas ve atık yönetimiyle; tüp ve radyasyon işaretleri ise özel fiziksel tehlikeyle ilgilidir. İşareti gördüğünde ilk soru “adı ne?” değil, “hangi teması veya koşulu önlemeliyim?” olmalı.',
        },
        {
          id: 'kb-safety-process',
          type: 'process',
          title: 'Laboratuvarda güvenli karar sırası',
          intro: 'Kurallar bağımsız yasaklar değil, maruz kalmayı önleyen bir sistemdir.',
          steps: [
            { title: 'Başlamadan oku ve hazırlan', body: 'Etiketi, piktogramı ve talimatı oku; gözlük, önlük ve gerekiyorsa uygun eldiveni kullan. Uzun saçı topla, çalışma alanını düzenle.' },
            { title: 'Maddeyi tanımadığın davranışla sınama', body: 'Tatma; doğrudan koklama; ağızla pipetleme; etiketsiz maddeyi kullanma. Koku kontrolü özellikle istenmişse doğrudan solumak yerine öğretmen yönergesini izle.' },
            { title: 'Karıştırma ve seyreltmede yönergeyi izle', body: 'Ev temizlik ürünlerini birbirine karıştırma. Asit seyreltilirken **asit yavaşça suya** eklenir; suyu derişik aside dökmek sıçramaya yol açabilir.' },
            { title: 'Kazayı gizleme, doğaçlama nötrleştirme yapma', body: 'Dökülme veya temas durumunda hemen öğretmene/yetkiliye haber ver; etiket ve güvenlik prosedürüne göre göz duşu, güvenlik duşu veya uygun dökülme kiti kullanılır.' },
            { title: 'Atığı doğru kaba ver', body: 'Kimyasal atık rastgele lavaboya dökülmez; artan madde stok şişesine geri konmaz. Etiketli atık kabı ve yerel prosedür izlenir.' },
          ],
        },
        {
          id: 'kb-safety-trap',
          type: 'trap',
          title: 'Temizlik ürünlerini birleştirince daha güçlü olacağını sanmak',
          wrong: 'Çamaşır suyu ile asitli kireç çözücü veya amonyaklı ürünü karıştırıp etkisini artırmaya çalışmak.',
          right: 'Ev kimyasalları yalnız etiketindeki kullanım biçimine göre ve **birbirine karıştırılmadan** kullanılır. Uygunsuz karışım zehirli/tahriş edici gaz oluşturabilir.',
          body: 'Keskin koku güvenliğin göstergesi değildir. Böyle bir karışım olduysa ortamdan uzaklaş, başkalarını da uzak tut ve acil yardım/zehir danışma yönlendirmesini izle; karışıma başka madde ekleme.',
        },
        {
          id: 'kb-safety-quiz',
          type: 'quiz',
          purpose: 'apply',
          question: 'Korozif piktogramlı derişik bir asit seyreltilirken aşağıdaki davranışlardan hangisi uygundur?',
          options: ['Suyu hızla derişik aside dökmek', 'Koruyucu ekipman ve yönergeyle asidi yavaşça suya eklemek', 'Asidin kokusunu doğrudan içine çekerek türünü belirlemek', 'Artan asidi etiketsiz içecek şişesinde saklamak'],
          answer_index: 1,
          explanation: 'Seyreltme ısı açığa çıkarabilir. Sıçrama riskini azaltmak için uygun ekipmanla **asit suya yavaşça eklenir**; doğrudan koklama ve etiketsiz saklama yapılmaz.',
        },
      ],
    },
    {
      id: 'kb-araclar',
      kind: 'build',
      title: 'Laboratuvar araçları: Şekli değil, görevi seç',
      lead: 'Bir kabın üzerinde çizgi bulunması onu otomatik olarak hassas ölçüm aracı yapmaz.',
      blocks: [
        {
          id: 'kb-tools-figure',
          type: 'figure',
          kind: 'kimya-laboratuvar-araclari',
          width: 'full',
          title: 'Temel laboratuvar araçlarını işlem türüne göre sınıflandır',
          purpose: 'Araç adını görsel biçim ve temel işlevle eşleştirip hacim ölçümü yanılgılarını önlemek.',
          complexity: 'high',
          caption: 'Araç seçiminde önce işlem belirlenir: karıştırma/ısıtma, hacim ölçme-aktarma, belirli hacimde çözelti hazırlama veya karışmayan sıvıları ayırma.',
          focus: [
            { title: 'Karıştırma ve ısıtma', body: 'Beher geniş ağızlıdır; erlenmayer çalkalamada sıçramayı azaltır; cam balon düzenli ısıtma ve tepkime işlemlerinde kullanılır.' },
            { title: 'Hacim ölçme ve aktarma', body: 'Mezür hacim ölçer; pipet belirli küçük hacmi hassas aktarır; büret musluğuyla verilen değişken hacmi hassas izler.' },
            { title: 'Belirli hacimde çözelti hazırlama', body: 'Balon joje yalnız üzerindeki çizgide belirtilen hacme tamamlamak için kalibre edilmiştir; ısıtma kabı değildir.' },
            { title: 'Karışmayan sıvıları ayırma', body: 'Ayırma hunisinde daha yoğun faz altta kalır ve musluktan önce alınır; su–yağ gibi sıvılar için uygundur.' },
          ],
          audio_script: 'Araçları soldan sağa isim listesi olarak ezberleme. Beher, erlenmayer ve cam balon daha çok karıştırma ve ısıtma ailesindedir. Mezür, pipet ve büret hacim işidir fakat hassasiyet ve aktarım biçimleri farklıdır. Balon joje tek bir kesin hacimde çözelti hazırlamak için kullanılır. Ayırma hunisi ise hacim ölçmekten çok birbirine karışmayan iki sıvıyı yoğunluk farkıyla ayırır.',
        },
        {
          id: 'kb-tools-compare',
          type: 'compare',
          interactive: true,
          title: 'Benzer görünen araçların asıl farkı',
          columns: ['Ne için seçilir?', 'Ne için seçilmez?'],
          rows: [
            { label: 'Beher', values: ['Karıştırma, aktarma, yaklaşık hacim ve uygun koşulda ısıtma', 'Hassas hacim ölçümü'] },
            { label: 'Erlenmayer', values: ['Çalkalayarak karıştırma, tepkime kabı, titrasyonda alıcı kap', 'Tek başına hassas hacim belirleme'] },
            { label: 'Mezür', values: ['Sıvı hacmini dereceli ölçekten ölçme', 'Balon joje veya pipet düzeyinde hassas hazırlama'] },
            { label: 'Pipet', values: ['Belirli küçük hacmi hassas aktarma', 'Ağızla sıvı çekme; mutlaka pipet doldurucu kullanılır'] },
            { label: 'Büret', values: ['Muslukla verilen hacmi hassas ve kontrollü ölçme', 'Sıvıyı depolama veya ısıtma'] },
            { label: 'Balon joje', values: ['Çözeltiyi çizgiye kadar tamamlayıp kesin hacim hazırlama', 'Doğrudan ısıtma'] },
            { label: 'Ayırma hunisi', values: ['Karışmayan sıvı fazlarını ayırma', 'Birbirinde çözünen sıvıları ayırma'] },
          ],
          insight: 'Hacim için genel sıra bağlama göre değişse de beher/erlenmayer yaklaşık; mezür ölçüm; pipet–büret–balon joje hassas hacim işlerinde düşünülür.',
        },
        {
          id: 'kb-tools-check',
          type: 'checkpoint',
          prompt: '100,0 mL belirli derişimde çözelti hazırlamak isteyen öğrenci, son hacmi beherin çizgisine kadar tamamlıyor. Hata nedir; hangi araç seçilmeliydi?',
          hint: 'Karıştırma kabı ile tek bir kesin hacme kalibre edilen kabı ayır.',
          answer: 'Beher çizgileri yaklaşık hacim gösterir. Çözelti uygun biçimde hazırlanıp **100,0 mL balon jojede** işaret çizgisine kadar tamamlanmalıdır.',
        },
      ],
    },
    {
      id: 'kb-saglik',
      kind: 'deepen',
      title: 'Yarar mı zarar mı? Maddenin adı tek başına cevap vermez',
      lead: 'Kimyasal etkiyi değerlendirirken maddeyi, kimyasal biçimi, dozu/derişimi, maruz kalma yolunu ve süreyi birlikte düşün.',
      blocks: [
        {
          id: 'kb-health-why',
          type: 'why',
          question: 'Sodyum yaşam için gerekli olduğu hâlde neden “sodyum tehlikelidir” denebilir?',
          body: 'Beslenmede gerekli olan, saf **sodyum metali** değil; vücut sıvılarında kontrollü miktarda bulunan **Na⁺ iyonudur**. Sodyum metali suyla şiddetli tepkime verir. Benzer biçimde klorür iyonu sofra tuzunda bulunurken Cl₂ gazı zehirli ve tahriş edicidir.\n\nBu örnek kimyanın temel düşünme biçimini gösterir: Aynı elementin farklı kimyasal türleri aynı özelliği göstermez. “İçinde sodyum var” cümlesi, maddenin formu ve miktarı bilinmeden güvenlik kararı vermeye yetmez.',
        },
        {
          id: 'kb-health-table',
          type: 'table',
          interactive: true,
          title: 'Yaşam için gerekli türler: doğru biçim ve uygun miktar',
          columns: ['Madde/tür', 'Temel rol', 'Denge bozulursa'],
          rows: [
            ['Na⁺', 'Sıvı dengesi, sinir iletimi ve kas işlevi', 'Fazlası/eksikliği vücut dengesini bozabilir'],
            ['K⁺', 'Hücre içi sıvı dengesi, sinir ve kas işlevi', 'Özellikle kalp ritmi açısından düzey önemlidir'],
            ['Fe içeren biyolojik yapılar', 'Hemoglobinde oksijen taşınmasına katkı', 'Eksiklik kansızlıkla; aşırı alım toksisiteyle ilişkilidir'],
            ['Ca²⁺', 'Kemik/diş yapısı, kasılma ve hücresel sinyal', 'Denge bozukluğu kemik ve kas işlevini etkiler'],
            ['Mg²⁺', 'Çok sayıda enzimin çalışmasına katkı', 'Eksiklik veya aşırı alım fizyolojik sorun oluşturabilir'],
            ['H₂O', 'Çözücü, taşıma ve sıcaklık düzenleme ortamı', 'Hem susuzluk hem aşırı su alımı dengeyi bozabilir'],
          ],
          caption: '“Gerekli” sözcüğü “sınırsızca alınabilir” anlamına gelmez. Doz ve biyolojik düzenleme her zaman önemlidir.',
        },
        {
          id: 'kb-harm-table',
          type: 'table',
          interactive: true,
          title: 'Sağlık ve çevre açısından dikkat gerektiren maddeler',
          columns: ['Madde', 'Başlıca risk', 'Kritik ayrım'],
          rows: [
            ['Hg (cıva)', 'Sinir sistemi hasarı ve besin zincirinde birikim', 'Dökülen cıva çıplak elle toplanmaz; yetkili prosedür gerekir'],
            ['Pb (kurşun)', 'Özellikle çocuklarda sinir sistemi gelişimine zarar', 'Eski boya, tesisat ve kirlenmiş toz kaynak olabilir'],
            ['CO', 'Hemoglobine bağlanarak oksijen taşınmasını engelleme', 'Renksiz ve kokusuzdur; kokuya güvenilmez, dedektör ve havalandırma gerekir'],
            ['Cl₂', 'Göz ve solunum yollarında güçlü tahriş/toksik etki', 'Çamaşır suyunun asitli ürünle karışması risk oluşturabilir'],
            ['NO₂', 'Solunum yolu tahrişi ve hava kirliliği', 'Yanma süreçleriyle oluşabilir; atmosferde asit oluşumuna katkı sağlar'],
            ['SO₃', 'Suyla tepkime ve asidik aerosol/çevre etkisi', 'Nemli ortamda aşındırıcı asit oluşumuyla ilişkilidir'],
            ['CO₂', 'Yüksek derişimde boğucu etki; sera etkisine katkı', 'Normal atmosfer düzeyinde zehir diye sınıflandırmak doğru değildir; derişim ve ortam belirleyicidir'],
          ],
          caption: 'Tehlike, maddenin özelliğidir; risk ise maruz kalma olasılığı ve düzeyiyle birlikte değerlendirilir.',
        },
        {
          id: 'kb-health-connection',
          type: 'connection',
          title: 'Bu düşünme biçimi sonraki konulara nasıl taşınır?',
          body: 'İyon ile element metalini ayırmak Atom ve Periyodik Sistem’de; Cl₂ ile Cl⁻ gibi türleri ayırmak Kimyasal Türler’de; derişimin etkisini görmek Karışımlar ve Asit–Baz–Tuz’da yeniden kullanılacak.',
          links: ['Kimyasal tür', 'İyon oluşumu', 'Derişim ve doz', 'Çevre kimyası'],
        },
        {
          id: 'kb-health-exam',
          type: 'exam',
          title: 'Mutlak ifadeye dikkat',
          body: '“Her kimyasal zararlıdır”, “doğal olan güvenlidir”, “gerekli mineralin fazlası zarar vermez” veya “CO₂ her miktarda zehirlidir” gibi bağlamdan kopuk yargılar genellikle yanlıştır. Maddenin türü, kimyasal biçimi, miktarı ve maruz kalma koşulu verilmeden kesin hüküm kurma.',
          patterns: ['Element–iyon ayrımı', 'Doz/derişim', 'Maruz kalma yolu', 'Biyobirikim', 'Hava ve su kirliliği'],
        },
      ],
    },
    {
      id: 'kb-uygulama',
      kind: 'practice',
      title: 'Bilgiyi soruya çevir: Kanıtı, dili ve güvenliği birlikte kullan',
      lead: 'Son bölümde tek tek tanımları değil, hangi bilginin hangi sonuca izin verdiğini sınayacaksın.',
      blocks: [
        {
          id: 'kb-osym-insight',
          type: 'osym_insight',
          title: 'Ezberi bağlama taşıma becerisi',
          body: 'Bu konuda ölçülen yalnız isim ve sembol hatırlama değildir. Bir laboratuvar senaryosunda güvenli davranışı seçmek, verilen çalışmayı alt disiplinle eşleştirmek, tanecik modelini element/bileşik olarak sınıflandırmak ve mutlak ifadelerin sınırını görmek gerekir.',
          measures: ['Yöntemden bilimsel niteliğe ulaşma', 'Problemden alt disiplin seçme', 'Sembol ve formül okuma', 'Piktogramdan önlem çıkarma', 'Madde–doz–koşul ilişkisi'],
        },
        {
          id: 'kb-osym-sim',
          type: 'osym_simulation',
          title: 'Mini TYT simülasyonu',
          passage: 'Bir araştırma ekibi, yeni geliştirilen polimer su filtresinin şebeke suyundaki Pb²⁺ iyonlarını tutma başarısını inceliyor. Ekip önce sudaki Pb²⁺ derişimini ölçüyor, farklı filtre örneklerini aynı koşullarda deniyor, sonuçları kaydediyor ve en başarılı örneği büyük ölçekli üretime uyarlıyor.',
          question: 'Bu çalışma ile ilgili aşağıdaki yorumlardan hangisi yanlıştır?',
          options: [
            { text: 'Pb²⁺ miktarının belirlenmesinde analitik kimyadan yararlanılır.', explanation: 'Doğru. “Ne kadar var?” sorusu analitik kimyanın temel sorusudur.' },
            { text: 'Filtre malzemesinin uzun zincirli yapısı polimer kimyasıyla ilişkilidir.', explanation: 'Doğru. Polimerlerin yapısı ve özellikleri polimer kimyasının alanındadır.' },
            { text: 'Koşulların eşit tutulması sonuçların karşılaştırılabilirliğini güçlendirir.', explanation: 'Doğru. Kontrollü koşullar değişkenin etkisini ayırmaya yardım eder.' },
            { text: 'Pb²⁺ iyonu ile saf kurşun metali aynı kimyasal tür ve aynı özelliklere sahiptir.', explanation: 'Yanlış. Aynı elemente ait olsalar da iyon ve metal farklı kimyasal türlerdir; özellikleri aynı kabul edilemez.' },
            { text: 'Yöntemin büyük üretime uyarlanması endüstriyel kimya ve mühendislik yaklaşımı gerektirir.', explanation: 'Doğru. Ölçek, verim, güvenlik ve süreç tasarımı bu aşamada öne çıkar.' },
          ],
          answer_index: 3,
          stem_analysis: 'Parçada dört katman var: ölçme, malzeme, kontrollü deney ve ölçekleme. Yanlış seçenek, “aynı element” bilgisini “aynı kimyasal tür” sonucuna taşır.',
          critical_point: 'Element kimliği proton sayısıyla korunabilir; fakat iyonlaşma ve bağlanma maddenin davranışını değiştirir.',
          takeaway: 'Soru kökünde verilen her fiili uygun kimya diliyle eşleştir; sonra seçenek mutlak bir özdeşlik kuruyor mu diye kontrol et.',
        },
        {
          id: 'kb-final-quiz',
          type: 'quiz',
          purpose: 'error',
          question: 'Aşağıdaki ifadelerden hangisi yanlıştır?',
          options: ['O₂ molekül yapılı bir elementtir.', 'Na ve Na⁺ aynı elementle ilişkili olsa da aynı kimyasal tür değildir.', 'Balon joje, belirli hacimde çözelti hazırlamak için kullanılır.', 'Korozif piktogramlı bir maddenin doğal kökenli olması onu otomatik olarak güvenli yapar.', 'Analitik kimya bir numunede ne bulunduğunu ve miktarını araştırabilir.'],
          answer_index: 3,
          explanation: 'Doğal köken güvenlik garantisi değildir. Korozif piktogram, maddenin cilt/göz veya malzemeler üzerinde aşındırıcı tehlike taşıdığını bildirir.',
        },
        {
          id: 'kb-final-summary',
          type: 'summary',
          title: 'Konunun kısa sentezi',
          points: [
            'Kimya; maddenin yapısını, özelliklerini, etkileşimlerini ve dönüşümlerini kanıta dayalı inceler.',
            'Simya kimyaya teknik birikim bırakmıştır; modern kimyayı ayıran kontrollü ölçüm, sınanabilirlik ve tekrarlanabilirliktir.',
            'Alt disiplin seçiminde ezber kelime değil, yapılan işlemin amacı belirleyicidir.',
            'Element tek atom türü; bileşik en az iki elementin sabit oranlı kimyasal birleşimidir.',
            'Kimyasal dil büyük–küçük harfe, alt indise ve paranteze duyarlıdır.',
            'Piktogram risk ailesini tanıtır; doğru davranış etiket ve güvenlik prosedürüyle seçilir.',
            'Beher/erlenmayer karıştırma; mezür ölçme; pipet–büret–balon joje hassas hacim; ayırma hunisi faz ayırma odaklıdır.',
            'Bir maddenin etkisi kimyasal biçim, doz/derişim, maruz kalma yolu ve süreyle birlikte değerlendirilir.',
          ],
          body: 'Kendini sınamak için kitabı kapat ve şu zinciri kur: **Gözlem → tanecik açıklaması → sembolik gösterim → güvenli uygulama.** Bu dört halkadan biri eksikse konu henüz tamamlanmamıştır.',
        },
        {
          id: 'kb-next',
          type: 'next_step',
          body: 'Sıradaki TYT Kimya konusu **Atom ve Periyodik Sistem**. Burada kullandığın element sembollerini atom modelleri, proton–nötron–elektron ve periyodik düzenle açıklayacaksın.',
          topics: ['Atom modelleri', 'Atomun yapısı', 'Periyodik sistem', 'İyonlar ve periyodik özellikler'],
        },
      ],
    },
  ],
})
