import { createChemistryLesson } from './factory.js'

export default createChemistryLesson({
  slug: 'maddenin-halleri',
  topic: 'Maddenin Halleri',
  order: 0,
  partLabel: 'Gold Standard · 4. Konu',
  title: 'Maddenin Hâlleri: Tanecik Düzeninden Gözlenebilir Özelliğe',
  subtitle: 'Katı, sıvı, gaz ve plazmayı tanecik modeliyle oku; hâl değişimini, viskoziteyi ve buhar basıncını nedenleriyle ilişkilendir.',
  minutes: 98,
  prerequisites: [
    'Taneciklerin sürekli hareket ettiğini ve aralarında boşluk bulunduğunu bilmek',
    'Güçlü bağlarla moleküller arası zayıf etkileşimleri ayırabilmek',
    'Sıcaklık, ısı ve basıncın aynı kavram olmadığını hatırlamak',
  ],
  outcomes: [
    'Katı, sıvı, gaz ve plazmayı taneciklerin düzeni, hareketi ve etkileşimiyle karşılaştırır.',
    'Maddenin farklı hâllerinin günlük yaşam ve endüstrideki önemini örneklerle açıklar.',
    'Katıları amorf, iyonik, moleküler, kovalent ağ ve metalik katı olarak sınıflandırır.',
    'Viskoziteyi tanecikler arası etkileşim, molekül yapısı ve sıcaklıkla ilişkilendirir.',
    'Buharlaşma–yoğuşma dinamik dengesini ve denge buhar basıncını tanecik düzeyinde açıklar.',
    'Buharlaşma ile kaynamayı ayırır; dış basıncın kaynama sıcaklığına etkisini yorumlar.',
    'Nem, bağıl nem ve hissedilen sıcaklık arasındaki ilişkiyi nitel olarak açıklar.',
    'Gaz değişkenlerini ve ısıtma–soğutma eğrilerini hesaplama yapmadan yorumlar.',
    'Plazmanın oluşumunu, elektriksel davranışını ve gazdan farkını açıklar.',
  ],
  sections: [
    {
      id: 'mh-hazirlik',
      kind: 'prepare',
      title: 'Bu konuyu öğrenmeden önce: Aynı madde neden bambaşka davranır?',
      lead: 'Buz, sıvı su ve su buharında H₂O kimliği aynıdır; değişen, taneciklerin birbirine göre düzeni ve hareket özgürlüğüdür.',
      blocks: [
        {
          id: 'mh-entry',
          type: 'prose',
          body: 'Bir buz küpü belirli biçimini korur, bardaktaki su kabın şeklini alır, su buharı ise bulunduğu hacme yayılır. Üç durumda da tanecik **H₂O molekülüdür**; yeni bir kimyasal tür oluşmaz. Değişen, moleküllerin sahip olduğu enerji ile moleküller arası çekimin göreli etkisidir. Bu nedenle hâl değişimi, kimyasal kimliği değiştirmeyen fiziksel bir olaydır.\n\nBu konuda her gözlemi üç soruyla açıklayacaksın: **Tanecikler ne kadar yakın ve düzenli? Hangi hareketleri yapabiliyor? Aralarındaki çekim, hareket enerjisine göre ne kadar etkili?** Böylece “katı sıkışmaz”, “sıvı akar” veya “gaz kabı doldurur” cümleleri ezber olmaktan çıkar.\n\nKurduğun model sonraki Karışımlar konusundaki çözünme ve ayırma süreçlerine, günlük yaşamda LPG–LNG kullanımına ve sıvıların kaynama davranışına altyapı sağlar. Bu derste gaz yasası hesabı, faz diyagramı veya gizli ısı hesabı yapmayacağız; TYT düzeyinde değişkenleri ve grafikleri **nitel olarak** okuyacağız.',
        },
        {
          id: 'mh-prior',
          type: 'checkpoint',
          prompt: 'Kapalı bir kaptaki buz tamamen eridiğinde taneciklerin kimliği, ortalama uzaklığı ve hareket biçimi için neler söylersin?',
          hint: 'Hâl değişiminde güçlü O–H bağlarının mı, moleküller arası çekimlerin mi etkilendiğini düşün.',
          answer: 'H₂O moleküllerinin kimliği korunur. Düzenli kristal yapı bozulur; moleküller birbirlerinin üzerinden kayabilecek hareket özgürlüğü kazanır. Ortalama uzaklık genel olarak biraz değişebilir, fakat gazdaki kadar büyük boşluk oluşmaz. O–H kovalent bağı kopmaz; moleküller arası düzen yeniden kurulur.',
        },
        {
          id: 'mh-first-trap',
          type: 'trap',
          title: 'Hâl değişiminde molekülün parçalandığını sanmak',
          wrong: '“Su kaynayınca H₂ ve O₂ gazlarına ayrılır.” diye düşünmek.',
          right: 'Kaynamada sıvı H₂O molekülleri gaz hâlindeki H₂O moleküllerine dönüşür. H₂ ve O₂ oluşması kimyasal bağların değişmesini gerektiren ayrı bir kimyasal süreçtir.',
        },
      ],
    },
    {
      id: 'mh-haller',
      kind: 'teach',
      title: 'Dört hâli tek tanecik modeliyle karşılaştır',
      lead: 'Hâl, yalnız tanecikler arası uzaklık değil; düzen, hareket ve elektriksel yapı birlikte düşünülerek tanımlanır.',
      blocks: [
        {
          id: 'mh-state-figure',
          type: 'figure',
          kind: 'madde-halleri-tanecik-haritasi',
          width: 'full',
          title: 'Katıdan plazmaya tanecik özgürlüğü',
          purpose: 'Dört hâli taneciklerin yakınlığı, düzeni, hareket türü ve elektriksel yapısıyla karşılaştırmak.',
          complexity: 'high',
          caption: 'Enerji arttıkça düzen ve çekimin sınırlayıcı etkisi genellikle azalır; plazmada tanecikler iyonlaşmıştır.',
          focus: [
            { title: 'Katı', body: 'Tanecikler çok yakın ve çoğu kristalde düzenlidir; sabit konum çevresinde titreşir. Belirli şekil ve hacim korunur.' },
            { title: 'Sıvı', body: 'Tanecikler yakın kalır fakat birbirlerinin üzerinden kayabilir. Hacim yaklaşık sabit, şekil kabın biçimine bağlıdır.' },
            { title: 'Gaz', body: 'Tanecikler arası boşluk çok büyüktür ve hızlı, rastgele hareket eder. Gaz sıkışabilir ve bulunduğu kabı doldurur.' },
            { title: 'Plazma', body: 'Yüksek enerjiyle iyonlaşmış pozitif iyonlar ve serbest elektronlardan oluşur; elektrik iletir, elektrik ve manyetik alandan etkilenir.' },
          ],
          audio_script: 'Katıda tanecikler durmaz; denge konumları çevresinde titreşir. Sıvıda tanecikler yine yakındır, bu yüzden sıvının hacmi büyük ölçüde korunur; fakat düzenli konumlara bağlı olmadıkları için akar. Gazda tanecikler arası uzaklık, tanecik boyutuna göre çok büyüktür. Bu boşluk gazın kolay sıkışmasını ve kabı doldurmasını açıklar. Plazma yalnız sıcak gaz değildir; enerjinin bir bölümü elektronları atomlardan ayırmış, yük taşıyan parçacıklar oluşturmuştur.',
        },
        {
          id: 'mh-state-compare',
          type: 'compare',
          interactive: true,
          title: 'Makroskobik özelliği tanecik nedenine bağla',
          columns: ['Tanecik düzeni ve hareketi', 'Şekil–hacim', 'Sıkışma', 'Akış'],
          rows: [
            { label: 'Katı', values: ['Yakın; konum çevresinde titreşim', 'Belirli şekil ve hacim', 'Çok az', 'Akmaz'] },
            { label: 'Sıvı', values: ['Yakın; öteleme ve kayma', 'Kabın şeklini alır, hacmi belirli', 'Çok az', 'Akar'] },
            { label: 'Gaz', values: ['Uzak; hızlı rastgele hareket', 'Kabın şekil ve hacmini alır', 'Belirgin', 'Akar ve yayılır'] },
            { label: 'Plazma', values: ['İyon ve elektronların ortak hareketi', 'Bulunduğu ortama yayılır', 'Gaz benzeri', 'Akışkan; alanlardan etkilenir'] },
          ],
          insight: 'Sıvı ve gazın ikisi de akışkandır; fakat sıvıda tanecikler yakın olduğu için belirli hacim korunur, gazda büyük boşluklar nedeniyle hacim kabın tamamına genişler.',
        },
        {
          id: 'mh-state-why',
          type: 'why',
          question: 'Gaz neden kolay sıkışırken sıvı neredeyse sıkışmaz?',
          body: 'Gaz hacminin büyük bölümü tanecikler arasındaki boşluktur. Basınç uygulandığında taneciklerin kendisi küçülmez; aralarındaki uzaklık azalır. Sıvıda tanecikler zaten birbirine çok yakındır, azaltılabilecek boşluk azdır. Aynı nedenle gaz yoğunluğu basınçla belirgin değişebilirken sıvının yoğunluğu normal koşullarda çok az değişir. “Gaz taneciği yumuşaktır” açıklaması yanlıştır; belirleyici olan boşluktur.',
        },
      ],
    },
    {
      id: 'mh-onem',
      kind: 'connect',
      title: 'Hâller neden önemlidir? Depolama, taşıma ve işlev',
      lead: 'Maddenin hâlini değiştirmek, kimliğini değiştirmeden hacmi, akışı ve kullanım biçimini yönetmeyi sağlar.',
      blocks: [
        {
          id: 'mh-importance-figure',
          type: 'figure',
          kind: 'madde-halleri-gunluk-yasam',
          width: 'full',
          title: 'Hâl bilgisinin günlük yaşam ve endüstrideki karşılığı',
          purpose: 'Suyun döngüsü, LPG–LNG, soğutucu akışkan ve havadan gaz ayırma örneklerini hâl özellikleriyle bağlamak.',
          complexity: 'high',
          caption: 'Hâl değişimi; depolama hacmini küçültmek, enerji taşımak veya bir bileşeni ayırmak için kullanılabilir.',
          focus: [
            { title: 'Su ve iklim', body: 'Suyun üç hâlde doğal olarak bulunması su döngüsünü, yağışı ve canlıların ısı dengesini mümkün kılar.' },
            { title: 'LPG ve LNG', body: 'Gazlar basınç veya soğutmayla sıvılaştırıldığında daha küçük hacimde depolanır; kap açılınca yeniden gazlaşabilir.' },
            { title: 'Soğutucu ve itici akışkan', body: 'Kolay buharlaşan sıvı çevreden enerji alarak soğutma sağlar; basınçlı kapta sıvı–gaz dengesi itici işlevi verir.' },
            { title: 'Havadan N₂ ve O₂', body: 'Hava sıvılaştırılıp bileşenlerin farklı kaynama sıcaklıklarından yararlanılarak azot ve oksijen ayrılabilir.' },
          ],
          audio_script: 'Sıvılaştırma gazın kimliğini değiştirmez; yalnız tanecikleri birbirine yaklaştırır ve depolama hacmini küçültür. LPG çoğunlukla propan ve bütan gibi petrol gazlarının basınçla sıvılaştırılmış karışımıdır. LNG ise büyük oranda metandır ve çok düşük sıcaklıkta sıvı tutulur. Soğutucu akışkan buharlaşırken çevreden enerji alır, yoğunlaşırken bu enerjiyi dışarı verir. Sıvı hava bileşenleri de farklı kaynama davranışları sayesinde ayrılır.',
        },
        {
          id: 'mh-importance-table',
          type: 'table',
          interactive: true,
          title: 'Teknolojiyi hangi hâl özelliği mümkün kılar?',
          columns: ['Uygulama', 'Kullanılan özellik', 'Kimyasal kimlik', 'Güvenlik notu'],
          rows: [
            ['LPG tüpü', 'Basınçla sıvılaşma; küçük hacimde depolama', 'Propan/bütan korunur', 'Isınma basıncı artırabilir; kap kapalı ve uygun tutulur'],
            ['LNG tankı', 'Çok düşük sıcaklıkta sıvılaştırma', 'Metan korunur', 'İyi yalıtım ve kontrollü gaz çıkışı gerekir'],
            ['Buzdolabı', 'Buharlaşırken enerji alma, yoğunlaşırken verme', 'Akışkan çevrim boyunca korunur', 'Sızdırmaz devre gerekir'],
            ['Sıvı hava ayrımı', 'Farklı kaynama sıcaklıkları', 'N₂ ve O₂ ayrılır', 'Çok soğuk sıvılar dokuya zarar verebilir'],
          ],
          insight: 'LPG ile LNG aynı değildir. LPG propan–bütan ağırlıklı ve basınçla sıvı; LNG metan ağırlıklı ve çok düşük sıcaklıkta sıvıdır.',
        },
        {
          id: 'mh-importance-check',
          type: 'checkpoint',
          prompt: 'Bir gazın sıvılaştırılması neden taşıma kolaylığı sağlar ve bu işlem neden kimyasal değişim sayılmaz?',
          hint: 'Aynı sayıda taneciğin gaz ve sıvı hâlde kapladığı hacmi, ayrıca tanecik kimliğini düşün.',
          answer: 'Sıvıda tanecikler çok daha yakın olduğundan aynı miktar madde daha küçük hacimde depolanabilir. Sıvılaşmada molekül türü değişmez; yalnız hareket ve tanecikler arası düzen değiştiği için olay fizikseldir.',
        },
      ],
    },
    {
      id: 'mh-katilar',
      kind: 'teach',
      title: 'Katılar: Düzen ve bağ türü özelliği belirler',
      lead: '“Katı” tek bir yapı değildir; kristal örgüyü hangi tanecik ve etkileşimin kurduğu belirleyicidir.',
      blocks: [
        {
          id: 'mh-solid-figure',
          type: 'figure',
          kind: 'kati-turleri-yapi-haritasi',
          width: 'full',
          title: 'Dört kristal katıyı örgü kurucusundan tanı',
          purpose: 'İyonik, moleküler, kovalent ağ ve metalik katıları bağ–özellik ilişkisiyle karşılaştırmak.',
          complexity: 'high',
          caption: 'Katının türünü formülden önce örgüdeki birim ve onu tutan etkileşim belirler.',
          focus: [
            { title: 'İyonik katı', body: 'Katyon ve anyonların elektrostatik örgüsüdür. Sert ve kırılgan; eriyik veya çözeltide hareketli iyon varsa iletkendir.' },
            { title: 'Moleküler katı', body: 'Ayrı molekülleri zayıf etkileşimler tutar. Genellikle düşük erime sıcaklıklı ve elektrikçe yalıtkandır; iyot örnektir.' },
            { title: 'Kovalent ağ katısı', body: 'Atomlar bütün yapı boyunca kovalent bağla bağlıdır. Elmas çok serttir ve yüksek sıcaklıkta erir; ayrı molekül yoktur.' },
            { title: 'Metalik katı', body: 'Metal merkezleri delokalize elektron deniziyle tutulur. Katıda iletken, parlak ve çoğunlukla şekil verilebilirdir; çinko örnektir.' },
          ],
          audio_script: 'Sodyum klorürde örgü birimleri iyonlardır. İyot katısında ayrı I₂ molekülleri korunur ve aralarında London kuvvetleri bulunur. Elmasta her karbon güçlü kovalent bağlarla üç boyutlu ağa katılır; tek bir elmas molekülünden söz edilmez. Çinkoda metal merkezleri hareketli elektron deniziyle tutulur. Katıların sertlik, erime ve iletkenlik farkı, örgüyü kuran tanecik ve etkileşimden doğar.',
        },
        {
          id: 'mh-solid-compare',
          type: 'compare',
          interactive: true,
          title: 'Kristal katıları bağ–özellik zinciriyle karşılaştır',
          columns: ['Örgü birimi', 'Tutucu etkileşim', 'İletkenlik', 'Örnek'],
          rows: [
            { label: 'İyonik', values: ['Katyon + anyon', 'İyonik çekim', 'Katıda hayır; eriyik/çözeltide olabilir', 'NaCl'] },
            { label: 'Moleküler', values: ['Molekül', 'Zayıf etkileşim', 'Genellikle hayır', 'I₂, buz'] },
            { label: 'Kovalent ağ', values: ['Atom', 'Yapı boyunca kovalent bağ', 'Genellikle hayır; grafit istisna', 'Elmas, SiO₂'] },
            { label: 'Metalik', values: ['Metal merkezi + elektron denizi', 'Metalik bağ', 'Katı ve sıvıda', 'Zn, Cu'] },
          ],
          insight: 'Erime sıcaklığı tek başına katı türünü kesinleştirmez; tanecik türü, iletkenlik ve mekanik özelliklerle birlikte değerlendirilir.',
        },
        {
          id: 'mh-amorphous',
          type: 'concept',
          title: 'Kristal ve amorf ayrımı',
          body: 'Kristal katıda tanecikler uzun mesafeli, tekrarlayan bir düzene sahiptir ve uygun koşulda belirgin bir erime sıcaklığı gösterir. **Amorf katıda** uzun mesafeli düzen yoktur; cam ve birçok plastik belirli bir aralıkta yumuşar. Amorf katıya “çok akışkan sıvı” demek lise düzeyinde doğru sınıflandırma değildir; mekanik olarak katı davranır, fakat kristal örgü düzeni taşımaz.\n\nAynı kimyasal tür farklı katı düzenlerinde farklı özellik gösterebilir. Karbonun elmas ve grafit yapıları buna örnektir. Bu fark, atom çeşidinden değil atomların bağlanma ve diziliş biçiminden kaynaklanır.',
        },
        {
          id: 'mh-solid-trap',
          type: 'trap',
          title: 'Bütün sert katıları iyonik sanmak',
          wrong: '“Elmas çok serttir; o hâlde pozitif ve negatif iyonlardan oluşmalıdır.” demek.',
          right: 'Elmas, karbon atomlarının üç boyutlu kovalent ağ katısıdır. Sertliğin nedeni yapı boyunca uzanan güçlü, yönlü C–C bağlarıdır; iyon içermez.',
        },
      ],
    },
    {
      id: 'mh-sivilar',
      kind: 'teach',
      title: 'Sıvılar: Akış, yüzeyden kaçış ve dinamik denge',
      lead: 'Sıvı özellikleri taneciklerin yakın kalırken yer değiştirebilmesinden ve çekimlerin gücünden doğar.',
      blocks: [
        {
          id: 'mh-liquid-figure',
          type: 'figure',
          kind: 'sivi-dinamikleri-haritasi',
          width: 'full',
          title: 'Viskoziteden neme dört sıvı olayı',
          purpose: 'Akış direnci, buharlaşma–yoğuşma dengesi, kaynama ve nemi aynı tanecik modeli içinde görmek.',
          complexity: 'high',
          caption: 'Buharlaşma her sıcaklıkta yüzeyden; kaynama, buhar basıncı dış basınca eşit olduğunda sıvının her yerinde gerçekleşir.',
          focus: [
            { title: 'Viskozite', body: 'Sıvının akmaya karşı direncidir. Güçlü çekim ve dolaşabilen uzun moleküller viskoziteyi artırabilir; sıcaklık artışı genellikle azaltır.' },
            { title: 'Dinamik denge', body: 'Kapalı kapta bir süre sonra birim zamanda buharlaşan ve yoğuşan tanecik sayıları eşitlenir; olaylar durmaz.' },
            { title: 'Buhar basıncı ve kaynama', body: 'Denge buharının kaba uyguladığı basınçtır. Buhar basıncı dış basınca eşit olduğunda sıvı boyunca kabarcıklarla kaynama başlar.' },
            { title: 'Nem ve hissedilen sıcaklık', body: 'Hava su buharına yaklaştıkça terin buharlaşması zorlaşır; sıcak havada vücudun soğuması azalır ve daha sıcak hissedilir.' },
          ],
          audio_script: 'Viskozite büyük olmak akışın zor olmasıdır; balın viskozitesi sudan büyüktür. Sıcaklık artınca sıvı tanecikleri çekimlere karşı daha kolay yer değiştirir ve viskozite genellikle düşer. Kapalı kapta yüzeyden kaçan taneciklerin bir bölümü geri döner. Buharlaşma ve yoğuşma hızları eşitlendiğinde dinamik denge oluşur. Kaynama ise sıvının buhar basıncının dış basınca eşit olduğu sıcaklıktadır. Nemli havada ter daha yavaş buharlaştığı için vücut daha az soğur.',
        },
        {
          id: 'mh-viscosity',
          type: 'concept',
          title: 'Viskoziteyi “yoğunluk” ile karıştırma',
          body: '**Viskozite**, akmaya karşı dirençtir; **yoğunluk**, birim hacimdeki kütledir. Bir sıvının daha yoğun olması mutlaka daha yavaş akacağı anlamına gelmez. Viskoziteyi tanecikler arası çekim, molekül büyüklüğü/şekli ve sıcaklık birlikte belirler. Gliserolün çok sayıda hidrojen bağı kurabilmesi akış direncini büyütür. Uzun zincirli moleküller birbirine dolanarak da akışı zorlaştırabilir.\n\nSıvılarda sıcaklık arttıkça taneciklerin hareket enerjisi artar; çekimlerin sınırlayıcı etkisi görece azalır ve viskozite **genellikle düşer**. Bu ilişki gaz viskozitesi için aynı biçimde genellenmez; TYT sorusunda sıvı verildiğini kontrol et.',
        },
        {
          id: 'mh-equilibrium',
          type: 'mechanism',
          title: 'Kapalı kapta denge buhar basıncı nasıl kurulur?',
          intro: 'Sabit sıcaklıkta bir miktar sıvıyı boşluk bulunan kapalı kaba koy.',
          steps: [
            { title: 'Hızlı tanecikler yüzeyden kaçar', body: 'Yeterli enerji ve uygun yöne sahip sıvı tanecikleri her sıcaklıkta buharlaşabilir.' },
            { title: 'Buhar tanecikleri kapta birikir', body: 'Gaz tanecikleri duvarlara çarpar ve basınç uygular; bir kısmı yeniden sıvı yüzeyine gelir.' },
            { title: 'Yoğuşma hızı artar', body: 'Buhar taneciği sayısı arttıkça sıvıya geri dönenlerin sayısı da artar.' },
            { title: 'Hızlar eşitlenir', body: 'Buharlaşma ve yoğuşma hızları eşit olduğunda makroskobik sıvı miktarı sabit görünür. Mikroskobik geçişler devam eder.' },
            { title: 'Denge buhar basıncı sabitlenir', body: 'Saf sıvı için denge değeri sıvının cinsine ve sıcaklığa bağlıdır; kap hacmi ve sıvı miktarı, iki faz birlikte kaldığı sürece denge değerini belirlemez.' },
          ],
        },
        {
          id: 'mh-vapor-table',
          type: 'table',
          interactive: true,
          title: 'Buharlaşma, buhar basıncı ve kaynamayı ayır',
          columns: ['Olay', 'Nerede?', 'Hangi koşulda?', 'Sıcaklığa etkisi / ölçüt'],
          rows: [
            ['Buharlaşma', 'Yalnız yüzeyde', 'Her sıcaklıkta', 'Yüksek enerjili tanecikler ayrılır; sıvı soğuyabilir'],
            ['Yoğuşma', 'Buhar–sıvı sınırında', 'Buhar enerji verdiğinde', 'Gazdan sıvıya geçiş'],
            ['Denge buhar basıncı', 'Kapalı kapta buhar fazında', 'Dinamik dengede', 'Sıcaklık artınca artar; çekim güçlüyse aynı sıcaklıkta genellikle küçüktür'],
            ['Kaynama', 'Sıvının her yerinde', 'Buhar basıncı = dış basınç', 'Saf sıvı, sabit dış basınçta belirli sıcaklıkta kaynar'],
          ],
          insight: 'Kaynama hızlanmış buharlaşma değildir. Buharlaşma yüzey olayıdır; kaynamada sıvı içinde kararlı buhar kabarcıkları oluşur.',
        },
      ],
    },
    {
      id: 'mh-kaynama-nem',
      kind: 'connect',
      title: 'Dış basınç ve nem: Çevre koşulu sonucu değiştirir',
      lead: 'Aynı sıvının kaynama sıcaklığı ve terin soğutma etkisi bulunduğu ortamdan bağımsız değildir.',
      blocks: [
        {
          id: 'mh-pressure-why',
          type: 'why',
          question: 'Dağda su neden daha düşük sıcaklıkta kaynar; düdüklü tencerede yemek neden daha hızlı pişer?',
          body: 'Yükseğe çıkıldıkça atmosfer basıncı azalır. Sıvının buhar basıncının daha küçük dış basınca eşit olması için daha düşük sıcaklık yeter; su daha düşük sıcaklıkta kaynar. Kaynama başlaması “çok sıcak” anlamına gelmez, eşitlik koşuludur. Düdüklü tencerede su buharı dışarı kolay çıkamadığı için iç basınç yükselir. Kaynama için daha yüksek sıcaklık gerekir; su ve buhar daha yüksek sıcaklıkta bulunduğundan yiyeceğe enerji aktarımı hızlanabilir. Basınç sıvının kimliğini değiştirmez, kaynama koşulunu değiştirir.',
        },
        {
          id: 'mh-pressure-example',
          type: 'worked_example',
          title: 'Üç kapta kaynama sırasını denklem kurmadan bul',
          prompt: 'Aynı saf sıvı; dış basıncı düşük K, normal L ve yüksek M ortamında ısıtılıyor. Kaynamaya başlama sıcaklıklarını karşılaştır.',
          steps: [
            { label: 'Ortak ölçüt', body: 'Üç kapta da kaynama, sıvının buhar basıncı dış basınca eşit olduğunda başlar.' },
            { label: 'K ortamı', body: 'Dış basınç en küçük olduğundan eşitlik daha düşük buhar basıncında ve dolayısıyla daha düşük sıcaklıkta kurulur.' },
            { label: 'L ortamı', body: 'Normal dış basınçta sıvının normal kaynama sıcaklığı gözlenir.' },
            { label: 'M ortamı', body: 'Daha büyük dış basınca ulaşmak için sıvının daha yüksek sıcaklığa çıkıp daha büyük buhar basıncı oluşturması gerekir.' },
          ],
          result: 'Kaynama sıcaklığı sırası K < L < M olur; sıvının cinsi değil dış basınç değiştirilmiştir.',
        },
        {
          id: 'mh-pressure-compare',
          type: 'compare',
          interactive: true,
          title: 'Dış basıncı kaynama sıcaklığına çevir',
          columns: ['Dış basınç', 'Eşitlik için gereken buhar basıncı', 'Kaynama sıcaklığı', 'Günlük örnek'],
          rows: [
            { label: 'Düşük', values: ['Daha küçük', 'Daha düşük', 'Yüksek dağ'] },
            { label: 'Normal', values: ['Atmosfer basıncı', 'Normal kaynama sıcaklığı', 'Açık tencere'] },
            { label: 'Yüksek', values: ['Daha büyük', 'Daha yüksek', 'Düdüklü tencere'] },
          ],
          insight: 'Bir sıvının “kaynama noktası” söylenirken dış basınç belirtilmelidir. Normal kaynama noktası, dış basıncın 1 atm olduğu değerdir.',
        },
        {
          id: 'mh-humidity-concept',
          type: 'concept',
          title: 'Bağıl nem ve hissedilen sıcaklık',
          body: 'Havadaki su buharı miktarı **mutlak nem** fikrini; mevcut su buharının o sıcaklıkta taşınabilecek en yüksek miktara oranı ise **bağıl nemi** anlatır. Sıcak hava daha fazla su buharı taşıyabildiği için hava soğutulduğunda bağıl nem artabilir ve doygunluğa ulaşınca yoğuşma görülebilir. Bu derste bağıl nem hesabı yapmadan ilişkileri yorumlamak yeterlidir.\n\nVücut teri buharlaştırırken enerji kaybeder ve serinler. Sıcak ve bağıl nemi yüksek havada çevre zaten su buharına yakındır; ter daha yavaş buharlaşır, soğutma zayıflar ve **hissedilen sıcaklık** gerçek hava sıcaklığından yüksek olabilir. Soğukta rüzgâr ise deri çevresindeki ısınmış havayı uzaklaştırarak daha soğuk hissettirebilir; nem–sıcaklık bağlantısını tek başına her duruma genelleme.',
        },
        {
          id: 'mh-humidity-quiz',
          type: 'quiz',
          purpose: 'apply',
          question: 'Aynı sıcaklıktaki iki günden bağıl nemi daha yüksek olanında, diğer koşullar eşitken terin soğutma etkisi için hangisi beklenir?',
          options: ['Buharlaşma hızlanır, daha serin hissedilir', 'Buharlaşma zorlaşır, daha sıcak hissedilebilir', 'Ter anında donar', 'Hava sıcaklığı zorunlu olarak düşer'],
          answer_index: 1,
          explanation: 'Yüksek bağıl nem, havanın daha fazla su buharı almaya yatkınlığını azaltır. Ter daha yavaş buharlaşır; vücuttan daha az enerji uzaklaştırıldığı için hava daha sıcak hissedilebilir.',
        },
      ],
    },
    {
      id: 'mh-gazlar',
      kind: 'teach',
      title: 'Gazlar: Ölçülebilir dört değişken ve tanecik davranışı',
      lead: 'Gaz yasası hesabına girmeden basınç, sıcaklık, hacim ve miktarın neyi ölçtüğünü doğru oku.',
      blocks: [
        {
          id: 'mh-gas-variables',
          type: 'formula',
          title: 'Gaz durumunu tanımlayan dört büyüklük',
          formulas: [
            { label: 'Basınç', expression: 'P · Pa, kPa, atm, mmHg' },
            { label: 'Hacim', expression: 'V · L, mL, m³' },
            { label: 'Sıcaklık', expression: 'T · K' },
            { label: 'Madde miktarı', expression: 'n · mol' },
          ],
          note: 'Bu bölümde birim dönüşümü veya gaz yasası hesabı yapılmaz. Sıcaklık karşılaştırmalarında mutlak sıcaklık ölçeği Kelvin kullanılır; 0 K, tanecik hareketi için kuramsal alt sınırdır.',
        },
        {
          id: 'mh-gas-concept',
          type: 'concept',
          title: 'Gaz basıncı duvara çarpışmaların sonucudur',
          body: 'Gaz tanecikleri rastgele hareket ederken kap duvarına çarpar ve momentum aktarır; çok sayıdaki çarpışmanın birim yüzeye etkisi basınç olarak ölçülür. Sabit hacimli bir kap ısıtıldığında taneciklerin ortalama hareket enerjisi artar; duvara daha sık ve daha etkili çarpışmaları basıncı artırabilir. Hareketli pistonlu kapta ise piston dışarı kayarak hacmi büyütebilir. Sonucun hangi değişkenlerin sabit tutulduğuna bağlı olduğunu her soruda kontrol et.\n\nGazların kolay yayılması ve birbirine karışması taneciklerin sürekli, rastgele hareketinden; kolay sıkışması büyük boşluklardan kaynaklanır. Gazın hacmi taneciklerin kendi hacmi değil, erişebildiği kabın hacmidir. İdeal gaz ayrıntıları ve kinetik teori denklemleri bu notun kapsamı dışındadır.',
        },
        {
          id: 'mh-gas-check',
          type: 'checkpoint',
          prompt: 'Sabit hacimli, kapalı bir metal kapta gaz ısıtılıyor. Tanecik sayısı değişmiyorsa basıncın artmasını hangi tanecik gözlemiyle açıklarsın?',
          hint: 'Kap büyümüyor; değişen taneciklerin ortalama hareket enerjisidir.',
          answer: 'Isıtılan gaz tanecikleri ortalama olarak daha hızlı hareket eder. Duvarla çarpışmalar daha sık ve daha etkili olur; birim yüzeye aktarılan etki arttığı için basınç yükselir. Tanecikler büyümez ve yeni tanecik oluşmaz.',
        },
        {
          id: 'mh-gas-trap',
          type: 'trap',
          title: 'Isıtılan taneciğin büyüdüğünü sanmak',
          wrong: '“Gaz ısınınca moleküller şişer, bu nedenle hacim artar.” demek.',
          right: 'Taneciğin boyutu anlamlı biçimde büyümez; hareket enerjisi ve ortalama uzaklık değişir. Esnek sınır varsa daha geniş hacme yayılabilir.',
        },
      ],
    },
    {
      id: 'mh-hal-degisimi',
      kind: 'connect',
      title: 'Isıtma–soğutma eğrisi: Enerji nereye gider?',
      lead: 'Grafikte eğik bölüm tek hâli, yatay bölüm hâl değişimini temsil eder; enerji akışı hâlâ sürer.',
      blocks: [
        {
          id: 'mh-curve-concept',
          type: 'concept',
          title: 'Sıcaklık artmıyorsa enerji kaybolmaz',
          body: 'Saf bir madde sabit basınçta tek hâlde ısıtılırken verilen enerji taneciklerin ortalama hareket enerjisini artırır; sıcaklık yükselir ve grafikte eğik parça görülür. Erime veya kaynama sırasında iki hâl birlikte bulunur. Verilen enerji, tanecikler arası çekimlere karşı düzeni değiştirmeye gider; ortalama hareket enerjisi ve sıcaklık hâl değişimi tamamlanana kadar sabit kalır.\n\nSoğutma eğrisi ters yönde okunur. Yoğuşma ve donma sırasında madde çevreye enerji verir; saf madde ve sabit basınç koşulunda sıcaklık geçiş tamamlanana kadar sabit kalabilir. Yatay parçanın uzunluğu madde miktarı ve ısıtıcı gücü gibi verilere bağlıdır; bu derste erime veya buharlaşma ısısı hesabı yapılmaz.',
        },
        {
          id: 'mh-curve-mechanism',
          type: 'mechanism',
          title: 'Bir ısıtma eğrisini beş durakta oku',
          intro: 'Başlangıçta katı olan saf madde sabit basınçta sürekli ısıtılıyor.',
          steps: [
            { title: 'Katı ısınır', body: 'Taneciklerin titreşim enerjisi artar; sıcaklık yükselir. Tek faz katıdır.' },
            { title: 'Erime', body: 'Katı ve sıvı birlikte bulunur. Enerji düzeni bozmaya gider; sıcaklık sabittir.' },
            { title: 'Sıvı ısınır', body: 'Taneciklerin ortalama hareket enerjisi ve sıcaklık yeniden artar.' },
            { title: 'Kaynama', body: 'Sıvı ve gaz birlikte bulunur. Enerji tanecikleri ayırmaya gider; dış basınç sabitse sıcaklık sabittir.' },
            { title: 'Gaz ısınır', body: 'Tamamı gaz olduktan sonra ek enerji ortalama hareket enerjisini artırır; sıcaklık yükselir.' },
          ],
        },
        {
          id: 'mh-curve-quiz',
          type: 'quiz',
          purpose: 'analyze',
          question: 'Saf bir sıvı sabit dış basınçta kaynarken ısıtıcı çalışmaya devam ettiği hâlde sıcaklığın sabit kalmasının temel nedeni nedir?',
          options: ['Enerjinin ortamdan tamamen yok olması', 'Moleküllerin hareketinin durması', 'Enerjinin tanecikler arası çekimlere karşı gaz hâlini oluşturmada kullanılması', 'Kimyasal bağların kopup yeni elementler oluşturması'],
          answer_index: 2,
          explanation: 'Kaynama boyunca verilen enerji molekülleri birbirinden uzaklaştırıp sıvı–gaz dönüşümünü sürdürür. Ortalama hareket enerjisi değişmediğinden sıcaklık sabit kalır; tanecik hareketi durmaz.',
        },
      ],
    },
    {
      id: 'mh-plazma-osym',
      kind: 'exam',
      title: 'Plazma ve ÖSYM sentezi: Özellikten tanecik modeline dön',
      lead: 'Soruda verilen makroskobik kanıtı, onu üreten hâl ve tanecik davranışıyla eşleştir.',
      blocks: [
        {
          id: 'mh-plasma',
          type: 'concept',
          title: 'Plazma neden yalnızca gaz değildir?',
          body: 'Bir gaz yeterince enerji aldığında atom veya moleküllerin elektronlarından bir bölümü ayrılabilir. Ortamda pozitif iyonlar, serbest elektronlar ve nötr tanecikler birlikte bulunur; buna **plazma** denir. Toplam sistem yaklaşık nötr olsa da hareketli yüklü tanecikler nedeniyle elektrik iletir ve elektrik–manyetik alanlara toplu yanıt verir. Güneş ve yıldızların büyük bölümü, şimşek kanalı, kutup ışıkları ve floresan lambadaki iletken ortam plazma örnekleridir.\n\nHer alevi bütünüyle plazma kabul etmek veya “plazma maddenin en sıcak hâlidir” diye tek sıcaklık sınırı ezberlemek doğru değildir. Ayırt edici özellik yeterli iyonlaşma ve buna bağlı elektriksel davranıştır. Plazmadan gaza dönüşmede elektronlar iyonlarla yeniden birleşebilir; bu da fiziksel hâl sınıflandırması içinde ele alınır.',
        },
        {
          id: 'mh-osym-insight',
          type: 'osym_insight',
          title: 'Özelliğin arkasındaki iki değişkeni ara',
          body: 'ÖSYM bu konuda çoğu kez tanımı doğrudan sormak yerine bir düzenek veya günlük yaşam örneği verir. Katı türünde önce örgü birimini ve bağ türünü; sıvıda önce sıcaklık ile tanecikler arası çekimi; kaynamada dış basıncı; gazda sabit tutulan P, V, T veya n değişkenini belirle. “Sıcaklık arttı” cümlesini otomatik olarak her özelliği artırır diye yorumlama: sıvı viskozitesi düşerken buhar basıncı artar.',
        },
        {
          id: 'mh-simulation',
          type: 'osym_simulation',
          title: 'Mini TYT simülasyonu',
          stimulus: 'Aynı saf sıvı eşit miktarlarda K ve L kaplarına konuyor. K kabı deniz seviyesinde açık, L kabı dış basıncı daha düşük bir ortamda açıktır. Sıvılar özdeş ısıtıcılarla ısıtılıyor.',
          question: 'Buna göre aşağıdaki yargılardan hangisi kesinlikle doğrudur?',
          options: [
            'L kabındaki sıvının kaynaması için daha büyük buhar basıncı gerekir.',
            'K kabındaki sıvı daha düşük sıcaklıkta kaynar.',
            'L kabındaki sıvı daha düşük sıcaklıkta kaynamaya başlayabilir.',
            'Kaynama sırasında sıvının kimyasal türü değişir.',
            'Her iki sıvının denge buhar basıncı sıcaklıktan bağımsızdır.',
          ],
          answer_index: 2,
          explanation: 'Kaynama, sıvının buhar basıncının dış basınca eşit olmasıyla başlar. L’de dış basınç daha küçük olduğundan eşitliğe daha düşük sıcaklıkta ulaşılabilir.',
          strategy: 'Önce kaynama eşitliğini yazılı olarak kur: buhar basıncı = dış basınç. Sonra hangi taraftaki dış basıncın daha küçük olduğuna bak.',
        },
        {
          id: 'mh-final-quiz',
          type: 'quiz',
          purpose: 'synthesize',
          question: 'I. Kapalı kapta buharlaşma–yoğuşma dengesi kurulduğunda iki olay da sürer. II. Saf sıvının denge buhar basıncı sıcaklık arttıkça artar. III. Sıvı kaynarken molekül içi güçlü bağlar zorunlu olarak kopar. yargılarından hangileri doğrudur?',
          options: ['Yalnız I', 'I ve II', 'I ve III', 'I, II ve III'],
          answer_index: 1,
          explanation: 'Dinamik dengede iki yönlü olay sürer ve hızlar eşittir. Sıcaklık artınca daha çok tanecik buhar fazına geçebildiği için denge buhar basıncı artar. Kaynama fiziksel değişimdir; molekül kimliği korunur.',
        },
        {
          id: 'mh-summary',
          type: 'summary',
          title: 'Konunun kısa sentezi',
          items: [
            'Katı titreşir; sıvı yakın taneciklerle akar; gaz büyük boşluklarla yayılır; plazma hareketli iyon ve elektron içerir.',
            'Hâl değişiminde kimyasal tür korunur; tanecik düzeni ve hareket özgürlüğü değişir.',
            'İyonik, moleküler, kovalent ağ ve metalik katıların özelliğini örgü birimi ve etkileşim belirler.',
            'Sıvıda çekim ve molekül yapısı viskoziteyi artırabilir; sıcaklık artışı viskoziteyi genellikle düşürür.',
            'Kapalı kapta buharlaşma ve yoğuşma hızları eşitlenince dinamik denge ve denge buhar basıncı oluşur.',
            'Buharlaşma her sıcaklıkta yüzeyden; kaynama buhar basıncı dış basınca eşit olduğunda her noktada gerçekleşir.',
            'Dış basınç azalınca kaynama sıcaklığı azalır; yüksek nem sıcak havada terin soğutmasını zorlaştırır.',
            'Isıtma eğrisinde eğik bölüm tek hâli, yatay bölüm iki hâlin birlikte bulunduğu dönüşümü gösterir.',
            'Plazmayı gazdan ayıran temel özellik iyonlaşma ve buna bağlı elektriksel davranıştır.',
          ],
        },
        {
          id: 'mh-next',
          type: 'next',
          title: 'Sıradaki bağ: Doğa ve Kimya',
          body: 'Maddenin hâlini ve fiziksel özelliklerini tanecik düzeyinde okuyabiliyorsun. Sıradaki konuda su, hava ve topraktaki kimyasal süreçlerin çevre ve insan yaşamıyla ilişkisini inceleyeceksin.',
        },
      ],
    },
  ],
})
