import { createChemistryLesson } from './factory.js'

export default createChemistryLesson({
  slug: 'mol-kavrami',
  topic: 'Mol Kavramı',
  order: 0,
  partLabel: 'Gold Standard · 7. Konu',
  title: 'Mol Kavramı: Görünmeyen Tanecikten Ölçülebilir Tepkimeye',
  subtitle: 'Molü bir formül değil sayma birimi olarak kur; kütle, tanecik ve gaz hacmini dönüştür, denklemi denkleştir ve katsayıları tepkime oranına çevir.',
  minutes: 112,
  prerequisites: [
    'Atom, molekül, iyon ve formül birimini ayırt edebilmek',
    'Bağıl atom kütlesini periyodik tablodan okuyabilmek',
    'Kütlenin korunumu ve sabit oranlar kanununu açıklayabilmek',
    'Oran–orantı ve bilimsel gösterim kullanabilmek',
  ],
  outcomes: [
    'Molü belirli sayıda kimyasal tanecik içeren sayma birimi olarak açıklar.',
    'Avogadro sabitini atom, molekül, iyon ve formül birimi bağlamında doğru kullanır.',
    'Molar kütleyi kimyasal formülden hesaplar ve birimini doğru yazar.',
    'Mol, kütle, tanecik sayısı ve normal koşullardaki gaz hacmi arasında dönüşüm yapar.',
    'Bir bileşikteki toplam ve element türüne ait atom sayılarını hesaplar.',
    'Kimyasal tepkime denklemini atom türü ve sayısını koruyarak denkleştirir.',
    'Denklem katsayılarını mol ve tanecik oranı olarak yorumlar.',
    'Kütle, mol, tanecik ve gaz hacmi içeren tepkime hesaplamaları yapar.',
    'Verilen bilginin madde miktarı mı, tanecik sayısı mı yoksa kütle mi olduğunu ayırt eder.',
  ],
  sections: [
    {
      id: 'mol-hazirlik',
      kind: 'prepare',
      title: 'Bu konuyu öğrenmeden önce: Bir taneciği tartmadan trilyonlarcasını nasıl sayarız?',
      lead: 'Kimyacı tek tek atom saymaz; tanecik sayısını ölçülebilir kütleye bağlayan mol birimini kullanır.',
      blocks: [
        {
          id: 'mol-entry',
          type: 'prose',
          body: 'Bir düzine kalem dediğimizde kalemlerin rengi veya kütlesi değişse de **12 tane** anlarız. Mol de bir sayma birimidir; fakat kimyasal tanecikler çok küçük olduğu için bir mol yaklaşık **6,02 × 10²³ tane** içerir. Bir mol demir atomu ile bir mol su molekülünün tanecik sayısı eşittir, kütleleri eşit değildir. Çünkü tek tek taneciklerinin kütleleri farklıdır.\n\nMol, mikroskobik tanecik dünyası ile laboratuvarda ölçtüğümüz gram dünyası arasında köprüdür. Kimyasal formül hangi taneciği saydığımızı; molar kütle bir molün kaç gram olduğunu; Avogadro sabiti kaç tanecik bulunduğunu söyler. Gazlarda uygun koşul bilgisi verildiğinde hacim de bu köprüye eklenir.\n\nBu not platformdaki “Mol Kavramı” başlığı altında TYT’nin ilgili devamını da kapsar: kimyasal tepkime denklemlerinin denkleştirilmesi ve denklem katsayılarından kütle–mol–tanecik–gaz hacmi hesapları. Sınırlayıcı bileşen, yüzde verim ve ileri gaz yasası hesabına girmeyeceğiz; katsayıların anlattığı temel stokiyometrik oranı kuracağız.',
        },
        {
          id: 'mol-prior',
          type: 'checkpoint',
          prompt: 'Bir mol H₂O ile bir mol CO₂ örneği için tanecik sayısı, toplam atom sayısı ve kütle aynı mıdır?',
          hint: 'Her molekülde kaç atom bulunduğunu ve formül kütlelerini ayrı ayrı düşün.',
          answer: 'Molekül sayıları aynıdır: her biri bir mol molekül içerir. H₂O molekülünde 3, CO₂ molekülünde de 3 atom bulunduğundan toplam atom sayıları da eşittir. Kütleleri ise farklıdır; H₂O yaklaşık 18 g/mol, CO₂ yaklaşık 44 g/mol molar kütleye sahiptir.',
        },
        {
          id: 'mol-first-trap',
          type: 'trap',
          title: 'Molü kütle birimi sanmak',
          wrong: '“Bir mol her madde için aynı gramdır.” demek.',
          right: 'Bir mol her madde için aynı **tanecik sayısını** anlatır. Gram değeri taneciğin kimliğine, yani molar kütlesine bağlıdır.',
        },
      ],
    },
    {
      id: 'mol-anlam',
      kind: 'teach',
      title: 'Mol: Kimyasal taneciğin dev sayma paketi',
      lead: 'Mol sayısı kadar, “neyin molü?” sorusunun cevabı da önemlidir.',
      blocks: [
        {
          id: 'mol-counting-figure',
          type: 'figure',
          kind: 'mol-sayma-koprusu',
          width: 'full',
          title: 'Düzineden mole, tanecikten molar kütleye',
          purpose: 'Sayma birimi, Avogadro sabiti, tanecik türü ve molar kütleyi tek modelde ilişkilendirmek.',
          complexity: 'high',
          caption: 'Bir molün tanecik sayısı sabittir; bir molün gram cinsinden kütlesi taneciğin kimliğine göre değişir.',
          focus: [
            { title: 'Sayma birimi', body: 'Düzine 12 nesne, mol ise 6,02 × 10²³ kimyasal tanecik demektir. İkisi de nesnenin türünden bağımsız sayma paketidir.' },
            { title: 'Avogadro sabiti', body: 'NA = 6,02 × 10²³ mol⁻¹, mol başına düşen tanecik sayısını verir; tanecik sayısı N = n·NA ile bulunur.' },
            { title: 'Taneciğin kimliği', body: 'Fe için atom, H₂O için molekül, NaCl için formül birimi sayılır. “Bir mol tanecik” ifadesinde tanecik türü belirtilmelidir.' },
            { title: 'Molar kütle', body: 'Bir mol maddenin gram cinsinden kütlesidir. Formüldeki atomların bağıl kütleleri toplanır ve birim g/mol yazılır.' },
          ],
          audio_script: 'Mol, tıpkı düzine gibi bir sayma birimidir; yalnız paket çok büyüktür. Avogadro sabiti bir moldeki tanecik sayısını verir. Sayılan şey maddeye göre atom, molekül, iyon veya formül birimi olabilir. Bir molün tanecik sayısı her madde için aynı, gram kütlesi farklıdır. Molar kütleyi formüldeki bütün atomların bağıl atom kütlelerini toplayarak buluruz.',
        },
        {
          id: 'mol-entity-table',
          type: 'table',
          interactive: true,
          title: 'Bir mol dediğinde neyi sayıyorsun?',
          columns: ['Madde', 'Temel tanecik', '1 molde ana tanecik', 'Toplam atom ilişkisi'],
          rows: [
            ['He', 'Atom', 'NA He atomu', 'NA atom'],
            ['O₂', 'Molekül', 'NA O₂ molekülü', '2NA O atomu'],
            ['H₂O', 'Molekül', 'NA H₂O molekülü', '3NA toplam atom'],
            ['NaCl', 'Formül birimi', 'NA NaCl formül birimi', 'NA Na⁺ + NA Cl⁻'],
            ['CaCl₂', 'Formül birimi', 'NA CaCl₂ formül birimi', 'NA Ca²⁺ + 2NA Cl⁻'],
          ],
          insight: 'Molekül sayısı ile atom sayısını eşitleme. Alt indis, her ana tanecikte ilgili atom veya iyon türünden kaç tane bulunduğunu gösterir.',
        },
        {
          id: 'mol-mass-example',
          type: 'worked_example',
          title: 'Molar kütleyi formülden kur',
          prompt: 'H₂SO₄ için H = 1, S = 32, O = 16 alınırsa molar kütleyi ve 0,50 mol örneğin kütlesini bul.',
          steps: [
            { label: 'Alt indisleri oku', body: 'Formül bir H₂SO₄ molekülünde 2 H, 1 S ve 4 O atomu içerir.' },
            { label: 'Molar kütleyi topla', body: 'M = 2·1 + 1·32 + 4·16 = 98 g/mol.' },
            { label: 'Molü kütleye çevir', body: 'm = n·M = 0,50 mol × 98 g/mol = 49 g.' },
            { label: 'Birimi denetle', body: 'Mol birimleri sadeleşir ve sonuç gram kalır.' },
          ],
          result: 'H₂SO₄’ün molar kütlesi 98 g/mol; 0,50 molünün kütlesi 49 g’dır.',
        },
        {
          id: 'mol-entity-why',
          type: 'why',
          question: 'Bir mol O₂ neden iki mol O atomu içerir?',
          body: 'Bir mol O₂, NA tane O₂ molekülüdür. Her molekülde iki O atomu bulunduğu için toplam O atomu sayısı 2NA olur; bu da iki mol O atomuna karşılık gelir. Molekülün önündeki mol sayısı bütün formülü, alt indis ise bir molekülün içindeki atom sayısını çarpar.',
        },
      ],
    },
    {
      id: 'mol-donusum',
      kind: 'teach',
      title: 'Mol dönüşüm haritası: Her yolun ortak durağı mol',
      lead: 'Gramı doğrudan taneciğe çevirmek yerine önce mole, sonra istenen büyüklüğe geç.',
      blocks: [
        {
          id: 'mol-conversion-figure',
          type: 'figure',
          kind: 'mol-donusum-haritasi',
          width: 'full',
          title: 'Kütle, tanecik, gaz hacmi ve atom içeriği',
          purpose: 'Dört farklı niceliği mol üzerinden çift yönlü dönüştürmek.',
          complexity: 'high',
          caption: 'Dönüşümün merkezinde mol vardır; her okta kullanılan çarpan ve birim farklıdır.',
          focus: [
            { title: 'Kütle ↔ mol', body: 'n = m/M ve m = n·M. Molar kütle g/mol birimindedir ve maddenin formülüne bağlıdır.' },
            { title: 'Tanecik ↔ mol', body: 'N = n·NA ve n = N/NA. Tanecik atom, molekül, iyon veya formül birimi olabilir.' },
            { title: 'Gaz hacmi ↔ mol', body: 'Normal koşullarda ideal davranışa yakın gazların 1 molü yaklaşık 22,4 L hacim kaplar; koşul değişirse bu değer kullanılmaz.' },
            { title: 'Bileşen atomu', body: 'Ana tanecik sayısı formüldeki alt indisle çarpılır. 2 mol CO₂, 4 mol O atomu içerir.' },
          ],
          audio_script: 'Dönüşüm sorularında güvenli merkez moldür. Gramdan mole geçerken molar kütleye böl; molden grama geçerken çarp. Tanecik sayısında Avogadro sabitini kullan. Gaz hacmi için 22,4 litre yalnız normal koşul bilgisi varsa geçerlidir. Bir moleküldeki belirli atomu sayarken ana tanecik sayısını alt indisle çarp.',
        },
        {
          id: 'mol-formulas',
          type: 'formula',
          title: 'Mol dönüşüm eşitlikleri',
          formulas: [
            { label: 'Kütleden mol', expression: 'n = m / M' },
            { label: 'Tanecik sayısı', expression: 'N = n × Nₐ' },
            { label: 'Normal koşulda gaz', expression: 'V ≈ n × 22,4 L' },
            { label: 'Belirli atom türü', expression: 'N(atom) = N(ana tanecik) × alt indis' },
          ],
          note: 'NA ≈ 6,02 × 10²³ mol⁻¹. 22,4 L/mol değeri 0 °C ve 1 atm olarak kullanılan normal koşul yaklaşımı içindir.',
        },
        {
          id: 'mol-conversion-example',
          type: 'worked_example',
          title: 'Kütleden molekül ve atom sayısına geç',
          prompt: '9 g H₂O örneğinde kaç mol H₂O, kaç molekül ve kaç mol H atomu vardır? H₂O = 18 g/mol.',
          steps: [
            { label: 'Kütleden mole geç', body: 'n(H₂O) = 9/18 = 0,50 mol.' },
            { label: 'Molekül sayısını bul', body: 'N(H₂O) = 0,50NA = 3,01 × 10²³ molekül.' },
            { label: 'H alt indisini uygula', body: 'Her H₂O’da 2 H atomu vardır: n(H atomu) = 0,50 × 2 = 1,00 mol.' },
            { label: 'Oksijeni de denetle', body: 'Aynı örnekte 0,50 mol O atomu bulunur; toplam atom miktarı 1,50 moldür.' },
          ],
          result: '0,50 mol H₂O, 3,01 × 10²³ H₂O molekülü ve 1,00 mol H atomu.',
        },
        {
          id: 'mol-gas-trap',
          type: 'trap',
          title: 'Her koşulda bir mol gazı 22,4 L sanmak',
          wrong: 'Sıcaklık ve basınç ne olursa olsun bütün gazların bir molünün 22,4 L olduğunu kabul etmek.',
          right: '22,4 L/mol normal koşul yaklaşımıdır. Gaz hacmi sıcaklık ve basınca bağlıdır; soru farklı koşul veriyorsa bu değer doğrudan kullanılmaz.',
        },
        {
          id: 'mol-conversion-quiz',
          type: 'quiz',
          purpose: 'apply',
          question: '0,25 mol CO₂ örneğinde toplam kaç mol atom bulunur?',
          options: ['0,25', '0,50', '0,75', '1,00'],
          answer_index: 2,
          explanation: 'Her CO₂ molekülünde 1 C + 2 O = 3 atom vardır. 0,25 mol molekül × 3 = 0,75 mol toplam atom.',
        },
      ],
    },
    {
      id: 'mol-denklem',
      kind: 'teach',
      title: 'Kimyasal denklem: Atom bilançosunu sembolik dilde kur',
      lead: 'Denkleştirme, formülleri değiştirmek değil aynı atomları iki tarafta eşit sayıda göstermektir.',
      blocks: [
        {
          id: 'mol-equation-figure',
          type: 'figure',
          kind: 'tepkime-denklestirme-atlasi',
          width: 'full',
          title: 'Gözlemden dengelenmiş denkleme dört durak',
          purpose: 'Giren–ürün ayrımını, atom sayımını, katsayı seçimini ve hâl sembollerini ilişkilendirmek.',
          complexity: 'high',
          caption: 'Katsayı bütün formülü çarpar; alt indis maddenin kimliğinin parçasıdır ve denkleştirmek için değiştirilmez.',
          focus: [
            { title: 'Girenler ve ürünler', body: 'Okun solunda tepkimeye girenler, sağında ürünler bulunur. Ok dönüşüm yönünü gösterir.' },
            { title: 'Atom envanteri', body: 'Her element için iki taraftaki atom sayısı ayrı sayılır. Amaç bütün elementlerde eşitlik kurmaktır.' },
            { title: 'Katsayılarla denkleştirme', body: 'Formüllerin önüne en küçük tam sayı katsayıları yazılır. Alt indis değiştirilirse başka madde tanımlanır.' },
            { title: 'Hâl ve koşul', body: '(k), (s), (g), (aq) fiziksel hâli; okun üzerindeki ısı veya katalizör tepkime koşulunu belirtir ve katsayı değildir.' },
          ],
          audio_script: 'Önce giren ve ürün formüllerini doğru yaz. Sonra her elementin atomlarını iki tarafta say. Eşitliği yalnız formüllerin önündeki katsayılarla kur; alt indis maddenin kimliğidir. En sonunda katsayıları en küçük tam sayılara indir ve hâl sembollerinin atom sayımına katılmadığını unutma.',
        },
        {
          id: 'mol-balance-process',
          type: 'mechanism',
          title: 'Denkleştirme algoritması',
          intro: 'Al + O₂ → Al₂O₃ tepkimesini denkleştir.',
          steps: [
            { title: 'Zor görünen elementi seç', body: 'Üründe 2 Al, 3 O vardır. O sayıları için 2 ve 3’ün ortak katı 6 uygundur.' },
            { title: 'Oksijeni eşitle', body: 'O₂’nin önüne 3, Al₂O₃’ün önüne 2 yaz: solda ve sağda 6 O olur.' },
            { title: 'Alüminyumu eşitle', body: 'Sağda 2 × 2 = 4 Al vardır; Al’ın önüne 4 yaz.' },
            { title: 'Denetle ve sadeleştir', body: '4Al + 3O₂ → 2Al₂O₃. Al: 4=4, O: 6=6; katsayıların ortak böleni yoktur.' },
          ],
        },
        {
          id: 'mol-coefficient-concept',
          type: 'concept',
          title: 'Katsayı hangi oranları verir?',
          body: 'Dengelenmiş 2H₂ + O₂ → 2H₂O denklemi; **2 mol H₂ : 1 mol O₂ : 2 mol H₂O** oranını verir. Aynı oran molekül sayıları için de geçerlidir: 2 H₂ molekülü ile 1 O₂ molekülü tepkimeye girerken 2 H₂O molekülü oluşur. Gazların hepsi aynı sıcaklık ve basınçta ölçülürse hacim oranları da katsayı oranına eşit olabilir.\n\nKatsayılar doğrudan gram oranı değildir. Gram oranı için önce katsayıyı molar kütleyle çarpmak gerekir: 2 mol H₂ yaklaşık 4 g, 1 mol O₂ yaklaşık 32 g ve 2 mol H₂O yaklaşık 36 g’dır.',
        },
        {
          id: 'mol-balance-trap',
          type: 'trap',
          title: 'Alt indisi değiştirerek denkleştirmek',
          wrong: 'H₂ + O₂ → H₂O denkleminde oksijeni eşitlemek için ürünü H₂O₂ yapmak.',
          right: 'H₂O₂, sudan farklı bir maddedir. Doğru işlem formülleri koruyup katsayı yazmaktır: 2H₂ + O₂ → 2H₂O.',
        },
      ],
    },
    {
      id: 'mol-stokiyometri',
      kind: 'connect',
      title: 'Tepkime hesabı: Verileni mole çevir, katsayı köprüsünden geçir',
      lead: 'Kütle, tanecik veya hacim ne verilirse verilsin tepkimeler arasındaki geçiş katsayıların mol oranında yapılır.',
      blocks: [
        {
          id: 'mol-stoich-figure',
          type: 'figure',
          kind: 'stokiyometri-yol-haritasi',
          width: 'full',
          title: 'Verilenden istenene dört duraklı yol',
          purpose: 'Verilen niceliği mole çevirme, katsayı oranını uygulama, istenen birime dönme ve sonucu denetleme.',
          complexity: 'high',
          caption: 'Tepkime oku üzerinden gramdan grama doğrudan atlama; iki madde arasındaki ortak dil moldür.',
          focus: [
            { title: 'Verileni mole çevir', body: 'Gramı molar kütleye böl; taneciği NA’ya böl; normal koşul gaz hacmini 22,4 L’ye böl.' },
            { title: 'Katsayı oranını uygula', body: 'Dengelenmiş denklemde istenen maddenin katsayısını verilen maddenin katsayısına oranla.' },
            { title: 'İstenen birime dön', body: 'Bulduğun molü gram, tanecik veya uygun koşuldaki gaz hacmine çevir.' },
            { title: 'Korunumla denetle', body: 'Kütle toplamını, birimleri ve büyüklük mertebesini kontrol et; denklem dengeli değilse oran güvenilir değildir.' },
          ],
          audio_script: 'Önce denklemi denkleştir. Verilen kütleyse molar kütleye bölerek mole geç. Mol oranını yalnız dengelenmiş katsayılardan al. Bulduğun hedef molünü istenen gram, tanecik veya gaz hacmine çevir. En son birim ve kütle korunumu denetimi yap. Bu dört durak, bütün temel stokiyometri sorularının omurgasıdır.',
        },
        {
          id: 'mol-stoich-example',
          type: 'worked_example',
          title: 'Gramdan grama tepkime hesabı',
          prompt: 'CH₄ + 2O₂ → CO₂ + 2H₂O tepkimesinde yeterli O₂ ile 8 g CH₄ tamamen yakılıyor. Kaç gram CO₂ oluşur? CH₄ = 16 g/mol, CO₂ = 44 g/mol.',
          steps: [
            { label: 'Verileni mole çevir', body: 'n(CH₄) = 8/16 = 0,50 mol.' },
            { label: 'Katsayı oranını uygula', body: 'CH₄/CO₂ katsayı oranı 1/1’dir; 0,50 mol CH₄ → 0,50 mol CO₂.' },
            { label: 'Molden grama dön', body: 'm(CO₂) = 0,50 × 44 = 22 g.' },
            { label: 'Bütün tepkimeyi denetle', body: '0,50 mol CH₄ için 1,00 mol O₂ gerekir ve 1,00 mol H₂O oluşur. Atom bilançosu korunur.' },
          ],
          result: '8 g CH₄’ün tam yanmasından 22 g CO₂ oluşur.',
        },
        {
          id: 'mol-volume-example',
          type: 'worked_example',
          title: 'Gaz hacmini katsayı oranıyla karşılaştır',
          prompt: '2H₂(g) + O₂(g) → 2H₂O(g) tepkimesinde aynı sıcaklık ve basınçta 10 L H₂ tamamen tepkimeye girerse kaç litre O₂ gerekir ve kaç litre su buharı oluşur?',
          steps: [
            { label: 'Koşulu doğrula', body: 'Bütün gazlar aynı sıcaklık ve basınçta verildiği için hacim oranı katsayı oranına eşittir.' },
            { label: 'Oksijeni bul', body: 'H₂/O₂ = 2/1 olduğundan 10 L H₂ için 5 L O₂ gerekir.' },
            { label: 'Su buharını bul', body: 'H₂/H₂O = 2/2 = 1 olduğundan 10 L H₂O(g) oluşur.' },
            { label: 'Sıvı su tuzağını önle', body: 'Ürün sıvı su olsaydı hacmi gaz katsayı oranıyla bulunamazdı; burada özellikle H₂O(g) verilmiştir.' },
          ],
          result: '5 L O₂ gerekir ve aynı koşullarda 10 L H₂O(g) oluşur.',
        },
        {
          id: 'mol-stoich-check',
          type: 'checkpoint',
          prompt: 'Bir tepkime denkleminde katsayıları bilmeden yalnız girenlerin molar kütlelerinden ürün miktarı hesaplanabilir mi?',
          hint: 'Molar kütle tek maddenin mol–gram ilişkisini verir; maddeler arasındaki ilişkiyi ne verir?',
          answer: 'Hayır. Molar kütle her madde için mol ile gramı bağlar; maddeler arasındaki tüketim–oluşum oranını dengelenmiş denklemin katsayıları verir. Önce denklem denkleştirilmelidir.',
        },
      ],
    },
    {
      id: 'mol-osym',
      kind: 'exam',
      title: 'ÖSYM sentezi: Önce varlığın türünü, sonra dönüşüm yolunu seç',
      lead: 'Sorular çoğu kez aynı anda molekül, atom, mol ve gram sözcüklerini kullanarak kavram sınırlarını yoklar.',
      blocks: [
        {
          id: 'mol-osym-insight',
          type: 'osym_insight',
          title: 'Üç ayrımı her soruda görünür yap',
          body: 'Önce **ana tanecik–bileşen atomu** ayrımını yap: 1 mol CO₂, 1 mol molekül ama 3 mol toplam atom içerir. Sonra **mol–kütle** ayrımını yap: eşit mol sayıları eşit tanecik sayısıdır, eşit kütle değildir. Son olarak **katsayı–alt indis** ayrımını yap: katsayı tepkime miktar oranını, alt indis tek taneciğin bileşimini gösterir. Bu üç ayrım kurulduğunda uzun görünen soru birkaç birim dönüşümüne iner.',
          measures: [
            'Sayma birimi olarak molü yorumlama',
            'Formülden molar kütle ve bileşen atom sayısı çıkarma',
            'Normal koşul bilgisini doğru yerde kullanma',
            'Denklemi alt indisleri değiştirmeden denkleştirme',
            'Katsayı oranını mol, tanecik ve aynı koşuldaki gaz hacmine uygulama',
            'Kütle–mol–tanecik zincirinde birim denetimi yapma',
          ],
        },
        {
          id: 'mol-simulation',
          type: 'osym_simulation',
          title: 'Mini TYT simülasyonu',
          stimulus: 'CaCO₃(k) → CaO(k) + CO₂(g) tepkimesine göre 0,20 mol saf CaCO₃ tamamen ayrışıyor.',
          question: 'Buna göre aşağıdakilerden hangisi yanlıştır?',
          options: [
            '0,20 mol CaO oluşur.',
            '0,20 mol CO₂ oluşur.',
            'Oluşan CO₂, 0,40 mol O atomu içerir.',
            'Normal koşullarda CO₂ hacmi yaklaşık 4,48 L’dir.',
            'Oluşan CaO ve CO₂’nin kütleleri birbirine eşittir.',
          ],
          answer_index: 4,
          explanation: 'Katsayı oranı 1:1:1 olduğu için ürünlerin mol sayıları eşittir; molar kütleleri eşit değildir. CaO yaklaşık 56 g/mol, CO₂ yaklaşık 44 g/mol olduğundan kütleleri farklıdır.',
          strategy: 'Eşit katsayıdan eşit mol çıkar; eşit gram sonucu çıkarmadan önce molar kütleleri karşılaştır.',
        },
        {
          id: 'mol-final-quiz',
          type: 'quiz',
          purpose: 'synthesize',
          question: 'I. Eşit moldaki farklı maddeler eşit sayıda ana tanecik içerir. II. Bir tepkimeyi denkleştirirken alt indisler değiştirilebilir. III. Aynı koşullardaki gazların hacim oranı dengelenmiş denklem katsayı oranına eşit olabilir. Hangileri doğrudur?',
          options: ['Yalnız I', 'I ve II', 'I ve III', 'I, II ve III'],
          answer_index: 2,
          explanation: 'I ve III doğrudur. Alt indis maddenin kimliğini belirlediği için denkleştirme sırasında değiştirilmez; yalnız katsayı kullanılır.',
        },
        {
          id: 'mol-summary',
          type: 'summary',
          title: 'Konunun kısa sentezi',
          items: [
            'Mol, 6,02 × 10²³ ana taneciği ifade eden sayma birimidir; gram birimi değildir.',
            'Ana tanecik atom, molekül, iyon veya formül birimi olabilir.',
            'Molar kütle formüldeki atom kütlelerinin toplamıdır ve g/mol birimiyle yazılır.',
            'Kütle–mol dönüşümünde molar kütle, tanecik–mol dönüşümünde Avogadro sabiti kullanılır.',
            'Normal koşuldaki ideal davranışa yakın 1 mol gaz yaklaşık 22,4 L kabul edilir; değer koşula bağlıdır.',
            'Toplam veya belirli atom sayısı bulunurken ana tanecik sayısı formüldeki alt indisle çarpılır.',
            'Denkleştirmede alt indis değil, formülün önündeki katsayı değiştirilir.',
            'Dengelenmiş katsayılar mol ve tanecik oranını; aynı sıcaklık ve basınçtaki gazlar için hacim oranını verir.',
            'Tepkime hesabı yolu: verileni mole çevir → katsayı oranı → istenen birim → denetim.',
          ],
        },
        {
          id: 'mol-next',
          type: 'next',
          title: 'Sıradaki bağ: Karışımlar',
          body: 'Mol ile artık tanecik miktarını ve kütleyi aynı dilde okuyabiliyorsun. Sıradaki konuda bu dili çözelti derişimini, çözünürlüğü ve karışımları ayırma yöntemlerini nicel ve tanecik düzeyinde açıklamak için kullanacaksın.',
        },
      ],
    },
  ],
})
