import { useEffect, useMemo, useRef, useState } from 'react'
import { Dna } from 'lucide-react'
import { BOLUNME_Evreleri, bolunmeAdim, bolunmeBaslat, bolunmeSifirla, dnaGrafikDogrula } from '../../../lib/biyoloji/bolunme.js'
import { E } from '../../../data/biyoloji/etkilesimler.js'
import BiyolojiModulKabugu from '../ortak/BiyolojiModulKabugu.jsx'
import BiyolojiGrafik from '../ortak/BiyolojiGrafik.jsx'
import OlcumPaneli from '../ortak/OlcumPaneli.jsx'
import { DurumRozeti, SecimSeridi, SimKontrol } from '../ortak/Kontroller.jsx'

export default function BolunmeZamanMakinesi(){
  const [s,setS]=useState(()=>bolunmeBaslat('mitoz'));const [oynuyor,setOynuyor]=useState(false);const [hiz,setHiz]=useState(1);const gecmis=useRef([]);const son=BOLUNME_Evreleri[s.tur].length-1
  const ileri=()=>setS(x=>{if(x.adim>=son){setOynuyor(false);return x}gecmis.current.push(x);return bolunmeAdim(x,1)})
  useEffect(()=>{if(!oynuyor)return;const z=setInterval(ileri,900/Math.max(.25,hiz));return()=>clearInterval(z)},[oynuyor,hiz,s.tur])
  const turSec=(tur)=>{setOynuyor(false);gecmis.current=[];setS(bolunmeBaslat(tur))};const geri=()=>{setOynuyor(false);const x=gecmis.current.pop();if(x)setS(x)};const sifirla=()=>{setOynuyor(false);gecmis.current=[];setS(bolunmeSifirla(s.tur))}
  const evreler=BOLUNME_Evreleri[s.tur];const grafik=evreler.slice(0,s.adim+1).map((e,i)=>({x:i,y:e.dna}));const cift=s.kromatit>s.kromozom;const crossing=s.ad==='Profaz I';const anafaz=s.ad.includes('Anafaz')
  return <BiyolojiModulKabugu id={E.BOLUNME_ZAMAN} bolge="bolunme" baslik="Mitoz–mayoz zaman makinesi" soru="DNA eşlendiğinde kromozom sayısı neden hemen iki katına çıkmaz?" tahminler={['Kromozom sayısını sentromer sayısı belirler; S evresinde kromatit/DNA artar.','X biçimindeki her yapı iki kromozomdur.']} aciklama="S evresinde her kromozom iki kardeş kromatit kazanır ama tek sentromerle bağlıdır. Kardeşler anafazda ayrılınca kromozom sayısı hücre içinde geçici olarak artar." yanilgi="Kromozom çiziminin kol sayısını saymak, kromozom ile kromatit kavramlarını karıştırır." gorevTamam={s.adim===son} kontrol={{soru:'Mayoz I sonunda ayrılmış olan yapılar hangileridir?',secenekler:['Homolog kromozomlar','Kardeş kromatitler','DNA nükleotitleri'],dogru:0,ipucu:'Mayoz I indirgeme bölünmesidir; sentromerler henüz ayrılmaz.',cozum:'Profaz I’de eşleşen homolog çifti izle; Anafaz I’de iki bütün X’in farklı kutuplara gittiğine bak.'}} modelVarsayimi="2n=2 örnek hücre kullanılır. Kromozom boyları ve evre süreleri ölçekli değildir; sayaçlar hücre başınadır." olcek="Tek hücre ve iki homolog kromozom çifti temsili">
    <div className="ba-sim-grid bolunme"><aside className="ba-kontrol-panel"><div className="ba-panel-bas"><span><Dna/> Süreç seçimi</span><DurumRozeti durum={s.durum}/></div><SecimSeridi etiket="Bölünme türü" deger={s.tur} secenekler={[{value:'mitoz',label:'Mitoz'},{value:'mayoz',label:'Mayoz'}]} onChange={turSec}/><ol className="ba-evre-listesi">{evreler.map((e,i)=><li key={e.ad} className={i===s.adim?'etkin':i<s.adim?'bitti':''}><button onClick={()=>{setOynuyor(false);setS({...bolunmeBaslat(s.tur),adim:i,...e,durum:i===son?'dengeye ulaştı':'çalışıyor'})}}><span>{i+1}</span><b>{e.ad}</b></button></li>)}</ol><SimKontrol oynuyor={oynuyor} onOynat={()=>setOynuyor(o=>!o)} onAdim={ileri} onGeri={geri} onSifirla={sifirla} hiz={hiz} onHiz={setHiz} geri={s.adim>0} ileri={s.adim<son}/></aside><section className="ba-sahne-panel"><div className={`ba-bolunme-sahne ${crossing?'crossing':''} ${anafaz?'anafaz':''} ${s.hucre>1?'cok-hucre':''}`} data-testid="bolunme-sahnesi"><svg viewBox="0 0 620 300" role="img" aria-label={`${s.ad} evresinde ${s.kromozom} kromozom, ${s.kromatit} kromatit`}><ellipse className="hucre-zari" cx="310" cy="150" rx={s.hucre>1?125:260} ry="125"/><line className="ekvator" x1="310" y1="28" x2="310" y2="272"/>{[0,1].map((x)=><g key={x} className={`kromozom k${x}`} transform={`translate(${anafaz?(x?455:165):(x?345:275)} 150)`}><path className="kromatit anne" d={cift?'M-22-72 Q0-30 0 0 Q0 30-22 72':'M0-72V72'}/>{cift?<path className="kromatit baba" d="M22-72 Q0-30 0 0 Q0 30 22 72"/>:null}<circle className="sentromer" r="8"/>{crossing?<><path className="degisen" d="M-17-44L15-18"/><path className="degisen" d="M17-44L-15-18"/></>:null}<line className="ig" x1={x?230:-230} y1="0" x2="0" y2="0"/></g>)}{s.hucre>1?<line className="sitokinez" x1="310" y1="26" x2="310" y2="274"/>:null}<text x="310" y="286" textAnchor="middle">{s.ad} · {s.olay}</text></svg><div className="ba-sahne-legend"><span><i className="anne"/>Bir homolog</span><span><i className="baba"/>Diğer homolog</span><span><i className="ig"/>İğ ipliği</span></div></div><OlcumPaneli olcumler={[{etiket:'Kromozom / hücre',deger:s.kromozom},{etiket:'Kromatit / hücre',deger:s.kromatit},{etiket:'Bağıl DNA',deger:s.dna,birim:'C',vurgu:true},{etiket:'Ploidy',deger:s.ploidy},{etiket:'Hücre sayısı',deger:s.hucre}]}/><BiyolojiGrafik noktalar={grafik} xEtiket="Evre indeksi" yEtiket="DNA / hücre" birim="C" ust={4} ariaLabel={`${s.tur} sürecinde hücre başına DNA miktarı`}/><p className="ba-mekanizma olumlu"><b>Ayrılan yapı:</b> {s.ayrilan}. {s.olay}</p></section></div>
  </BiyolojiModulKabugu>
}

export function DnaGrafikKurucu(){const [tur,setTur]=useState('mitoz');const beklenen=BOLUNME_Evreleri[tur];const [noktalar,setNoktalar]=useState(()=>beklenen.map(()=>1));const sonuc=useMemo(()=>dnaGrafikDogrula(tur,noktalar),[tur,noktalar]);const sec=(i,v)=>setNoktalar(n=>n.map((x,j)=>j===i?v:x));const turDegis=(v)=>{setTur(v);setNoktalar(BOLUNME_Evreleri[v].map(()=>1))};return <BiyolojiModulKabugu id={E.DNA_GRAFIK} bolge="bolunme" baslik="DNA grafiğini kendin kur" soru="Hazır çizgiyi izlemek yerine her evreye hücre başına kaç C DNA yerleştirirsin?" tahminler={['DNA S evresinde artar; bölünme sonlarında hücre başına azalır.','DNA yalnız kromozom sayısı artınca değişir.']} aciklama="DNA miktarı ve kromozom sayısı aynı ölçüm değildir; S evresi DNA’yı eşlerken sentromer sayısını değiştirmez." yanilgi="Her X’i iki kromozom saymak grafiği S evresinde yanlış yükseltir." gorevTamam={sonuc.dogru} kontrol={{soru:'S evresinin sonunda hücre başına bağıl DNA kaç C’dir?',secenekler:['4C','2C','1C'],dogru:0,ipucu:'Başlangıç 2C idi ve DNA bir kez eşlendi.',cozum:'Kromozom sayısını değil, toplam DNA kopyasını takip et.'}} modelVarsayimi="Grafik hücre başına bağıl DNA miktarını gösterir; gerçek DNA kütlesi türlere göre değişir."><div className="ba-grafik-kurucu"><SecimSeridi etiket="Süreç" deger={tur} secenekler={['mitoz','mayoz']} onChange={turDegis}/><div className="ba-nokta-girdileri">{beklenen.map((e,i)=><label key={e.ad}><span>{e.ad}</span><input aria-label={`${e.ad} DNA değeri`} type="range" min="1" max="4" step="1" value={noktalar[i]} onChange={(x)=>sec(i,Number(x.target.value))}/><output>{noktalar[i]}C</output></label>)}</div><BiyolojiGrafik noktalar={noktalar.map((y,x)=>({x,y}))} xEtiket="Evre indeksi" yEtiket="Öğrencinin DNA değeri" birim="C" ust={4}/><p className={sonuc.dogru?'ba-mekanizma olumlu':'ba-mekanizma uyari'}>{sonuc.mesaj}</p></div></BiyolojiModulKabugu>}

