import { useEffect, useRef, useState } from 'react'
import { FlaskConical } from 'lucide-react'
import { enzimAdim, enzimBaslat, enzimSifirla } from '../../../lib/biyoloji/enzim.js'
import BiyolojiModulKabugu from '../ortak/BiyolojiModulKabugu.jsx'
import BiyolojiGrafik from '../ortak/BiyolojiGrafik.jsx'
import OlcumPaneli from '../ortak/OlcumPaneli.jsx'
import { DurumRozeti, Kaydirici, SimKontrol } from '../ortak/Kontroller.jsx'
import { E } from '../../../data/biyoloji/etkilesimler.js'

export default function EnzimLaboratuvari(){
  const [s,setS]=useState(()=>enzimBaslat()); const [oynuyor,setOynuyor]=useState(false); const [hiz,setHiz]=useState(1); const gecmis=useRef([])
  const adimla=()=>setS(eski=>{gecmis.current.push(eski);return enzimAdim(eski,1)})
  useEffect(()=>{if(!oynuyor)return; const z=setInterval(adimla,700/Math.max(.25,hiz));return()=>clearInterval(z)},[oynuyor,hiz])
  const ayarla=(alan,deger)=>{setOynuyor(false);gecmis.current=[];setS(enzimBaslat({...s,[alan]:deger}))}
  const sifirla=()=>{setOynuyor(false);gecmis.current=[];setS(enzimSifirla())}
  const geri=()=>{setOynuyor(false);const once=gecmis.current.pop();if(once)setS(once)}
  const nokta=(i,n,tip)=>({x:22+((i*47+s.zaman*7)%500),y:24+((i*71+s.zaman*(tip==='enzim'?3:6))%190),n})
  const enzimler=Array.from({length:Math.min(18,Math.ceil(s.enzim/4))},(_,i)=>nokta(i,i,'enzim')); const substratlar=Array.from({length:Math.min(24,Math.ceil(s.kalanSubstrat/4))},(_,i)=>nokta(i+3,i,'substrat')); const urunler=Array.from({length:Math.min(24,Math.ceil(s.urun/4))},(_,i)=>nokta(i+9,i,'urun'))
  return <BiyolojiModulKabugu id={E.ENZIM_LAB} bolge="molekul" baslik="Enzim–substrat çarpışma laboratuvarı" soru="Sıcaklık arttıkça ürün oluşumu neden sonsuza dek hızlanmaz?" tahminler={['Optimumdan sonra enzim biçimi bozulur ve hız düşer.','Daha sıcak ortam her zaman daha hızlı ürün üretir.']} aciklama="Sıcaklık önce çarpışmayı artırır; aşırı sıcaklık aktif bölgenin biçimini bozduğu için verimli çarpışma azalır." yanilgi="Hareket hızını tek değişken sanmak denatürasyonu gözden kaçırır. 37 °C ve 60 °C koşullarını çalıştırıp ürün eğrilerini karşılaştır." gorevTamam={s.zaman>=5} kontrol={{soru:'60 °C’de ürün eğrisinin 37 °C’ye göre yataylaşmasının temel nedeni nedir?',secenekler:['Aktif bölge uyumunun denatürasyonla azalması','Enzimin ürüne dönüşüp tükenmesi','Substratın enzim olması'],dogru:0,ipucu:'Enzim tepkimede harcanmaz; biçimi çalışma yeteneğini belirler.',cozum:'Aynı enzim/substrat miktarında yalnız sıcaklığı karşılaştır ve aktif bölge biçimini izle.'}} modelVarsayimi="Tek enzim türü, tek substrat ve iyi karışan bir ortam modellenir; çarpışma sayıları temsili, hız eğrileri biyolojik eğilimi korur." olcek="Moleküler olayların yavaşlatılmış temsili">
    <div className="ba-sim-grid">
      <aside className="ba-kontrol-panel"><div className="ba-panel-bas"><span><FlaskConical/> Deney koşulları</span><DurumRozeti durum={s.durum}/></div><Kaydirici etiket="Sıcaklık" deger={s.sicaklik} birim="°C" min={5} max={70} onChange={(v)=>ayarla('sicaklik',v)}/><div className="ba-hizli-kosul" aria-label="Sıcaklık karşılaştırma kısayolları"><button onClick={()=>ayarla('sicaklik',37)} className={s.sicaklik===37?'etkin':''}>37 °C · optimum</button><button onClick={()=>ayarla('sicaklik',60)} className={s.sicaklik===60?'etkin':''}>60 °C · aşırı</button></div><Kaydirici etiket="pH" deger={s.ph} min={2} max={12} step={.5} onChange={(v)=>ayarla('ph',v)}/><Kaydirici etiket="Enzim derişimi" deger={s.enzim} birim="%" min={10} max={100} onChange={(v)=>ayarla('enzim',v)}/><Kaydirici etiket="Substrat derişimi" deger={s.substrat} birim="%" min={10} max={100} onChange={(v)=>ayarla('substrat',v)}/><SimKontrol oynuyor={oynuyor} onOynat={()=>setOynuyor(o=>!o)} onAdim={adimla} onGeri={geri} onSifirla={sifirla} hiz={hiz} onHiz={setHiz} geri={gecmis.current.length>0}/></aside>
      <section className="ba-sahne-panel"><div className={`ba-enzim-sahne ${oynuyor?'oynuyor':''}`} data-testid="enzim-sahnesi"><svg viewBox="0 0 560 240" role="img" aria-label={`${enzimler.length} enzim, ${substratlar.length} substrat ve ${urunler.length} ürün parçacığı`}><rect width="560" height="240" rx="18" className="sivi"/>{enzimler.map(p=><g key={`e${p.n}`} transform={`translate(${p.x} ${p.y})`} className={s.model?.denature?'enzim denature':'enzim'}><path d="M-12-9h24v7h-8v11h-16z"/><circle r="3" cx="6" cy="-5"/></g>)}{substratlar.map(p=><circle key={`s${p.n}`} className="substrat" cx={p.x} cy={p.y} r="6"/>)}{urunler.map(p=><g key={`u${p.n}`} className="urun" transform={`translate(${p.x} ${p.y})`}><circle cx="-4" r="4"/><circle cx="4" r="4"/></g>)}</svg><div className="ba-sahne-legend"><span><i className="enzim"/>Enzim</span><span><i className="substrat"/>Substrat</span><span><i className="urun"/>Ürün</span></div></div><OlcumPaneli olcumler={[{etiket:'Zaman',deger:s.zaman.toFixed(0),birim:'sn'},{etiket:'Ürün',deger:s.urun.toFixed(1),birim:'birim',vurgu:true},{etiket:'Kalan substrat',deger:s.kalanSubstrat.toFixed(1),birim:'birim'},{etiket:'Çarpışma',deger:s.carpismalar,birim:'kez'}]}/><BiyolojiGrafik noktalar={s.grafik} xEtiket="Zaman (sn)" yEtiket="Birikimli ürün" birim="birim" ariaLabel="Enzim deneyinde zamana göre biriken ürün"/></section>
    </div><p className={`ba-mekanizma ${s.model?.denature?'uyari':'olumlu'}`}><b>Mekanizma:</b> {s.model?.denature?'Aşırı sıcaklıkta enzim şekilleri bozuldu; hareket sürse de verimli çarpışma azaldı.':'Enzim ürün olmaz ve tükenmez; uygun aktif bölgeye gelen substratı ürüne dönüştürüp yeniden kullanılabilir.'}</p>
  </BiyolojiModulKabugu>
}
