import { useMemo, useState } from 'react'
import { ArrowRight, CheckCircle2, GitCompareArrows, Network, RotateCcw } from 'lucide-react'
import { ALT_BASLIKLAR } from '../../../data/biyoloji/kapsam.js'
import { E } from '../../../data/biyoloji/etkilesimler.js'
import BiyolojiModulKabugu from '../ortak/BiyolojiModulKabugu.jsx'
import { Kaydirici, SecimSeridi } from '../ortak/Kontroller.jsx'

const V={
 [E.ZAR_DEGISKEN]:{m:'karsilastir',baslik:'Zar değişken dedektifi',soru:'Molekülün boyutu, yükü ve kanal varlığı geçiş yolunu nasıl değiştirir?',t:['Molekül özelliği ve zar proteinleri birlikte yol seçtirir.','Yalnız derişim farkı bütün yolları belirler.'],a:'O₂ fosfolipitten; glikoz taşıyıcıyla; protein vezikülle geçer.',y:'Tüm maddeleri difüzyonla geçirmek zarın seçiciliğini yok sayar.',satir:[['O₂','Küçük apolar','Basit difüzyon'],['Glikoz','Polar/büyükçe','Taşıyıcı protein'],['Protein','Çok büyük','Vezikül']],kontrol:['Protein neden kanaldan geçmez?',['Boyutu kanal geçişine uygun değildir','ATP içermediği için','Su olduğu için'],0]},
 [E.VEZIKUL_SIRALA]:{m:'sirala',baslik:'Endositoz–ekzositoz zar şekli sahnesi',soru:'Büyük bir yük zar boyunca hangi biçim değişiklikleriyle taşınır?',t:['Zar kıvrılır, vezikül kapanır ve yük sitoplazmaya alınır.','Protein fosfolipitlerin arasından kayar.'],a:'Endositozda zar yükü sarar; ekzositozda vezikül zarla birleşir.',y:'Büyük maddeleri kanal boyutunda sanmak vezikül gereksinimini kaçırır.',sira:['Yük zara yaklaşır','Zar içe kıvrılır','Vezikül kapanır','Vezikül sitoplazmaya geçer'],kontrol:['Ekzositozda son adım nedir?',['Vezikülün zarla birleşmesi','Çekirdeğin açılması','Ribozomun parçalanması'],0]},
 [E.KROMOZOM_KUR]:{m:'sirala',baslik:'Homolog ve crossing-over kurucu',soru:'Crossing-over hangi kromatitler arasında gerçekleşir?',t:['Homologların kardeş olmayan kromatitleri arasında.','Aynı kromozomun kardeşleri arasında zorunlu olarak.'],a:'Sinapsis homologları yan yana getirir; kardeş olmayan kromatit parçaları değişebilir.',y:'Kardeş kromatit ile homolog kromozomu aynı sanmak çeşitlilik kaynağını gizler.',sira:['Homologlar eşleşir','Kiyazma oluşur','Kardeş olmayan parçalar değişir','Rekombinant kromatitler ayrılır'],kontrol:['Crossing-over hangi evrede görünür?', ['Profaz I','Metafaz II','G1'],0]},
 [E.BOLUNME_KARSILASTIR]:{m:'karsilastir',baslik:'Mitoz–mayoz sonuç karşılaştırması',soru:'İki süreç ürün hücre sayısı, ploidy ve çeşitlilik bakımından nasıl ayrılır?',t:['Mitoz iki benzer; mayoz dört çeşitli haploit hücre oluşturur.','İkisi de aynı sonucu oluşturur.'],a:'Mayoz homolog ayrılması ve crossing-over nedeniyle indirgeme ve çeşitlilik üretir.',y:'Süreçlerin yalnız evre adlarını bilmek sonuçlarını eşitleyebilir.',satir:[['Mitoz','2 hücre','2n','Genellikle benzer'],['Mayoz','4 hücre','n','Çeşitli']],kontrol:['Mayoz II sonunda ayrılan yapı nedir?',['Kardeş kromatitler','Homolog kromozomlar','Hücre duvarı'],0]},
 [E.UREME_SINIFLA]:{m:'sinifla',baslik:'Üreme örneklerini mekanizmaya göre sınıflandır',soru:'Tomurcuklanma, rejenerasyon ve sporla üremeyi hangi mekanizma kanıtıyla ayırırsın?',t:['Yeni bireyin oluşma biçimine bakarım.','Yalnız canlı adını ezberlerim.'],a:'Örnekler sonuç etiketiyle değil hücresel/organizmal mekanizmayla sınıflandırılır.',y:'Rejenerasyonu her doku onarımıyla eşeysiz üreme sanmak yeni birey koşulunu kaçırır.',ogeler:[['Hidra tomurcuğu','Eşeysiz'],['Çilek sürünücü gövde','Eşeysiz'],['İnsan gamet birleşimi','Eşeyli'],['Mantar sporu','Eşeysiz'],['Planaryadan yeni birey','Eşeysiz'],['Kuş döllenmesi','Eşeyli']],kategoriler:['Eşeyli','Eşeysiz'],kontrol:['Eşeysiz yavrular neden mutlak biçimde aynı olmak zorunda değildir?',['Mutasyonlar yeni farklılık oluşturabilir','Her zaman mayoz olur','İki ebeveyn zorunludur'],0]},
 [E.UREME_STRATEJI]:{m:'senaryo',baslik:'Üreme stratejisi koşul simülasyonu',soru:'Hızla değişen çevre ve yüksek eş bulma olasılığı hangi stratejinin avantajını artırır?',t:['Çeşitlilik sağlayan eşeyli üremenin göreli avantajı artabilir.','Eşeysiz üreme her koşulda üstündür.'],a:'Strateji başarısı çevre kararlılığı, enerji maliyeti ve eş bulmaya bağlıdır.',y:'Bir stratejiyi mutlak iyi/kötü ilan etmek bağlamı yok sayar.',degisken:['Çevre değişim hızı','Eş bulma olasılığı'],kontrol:['Kararlı çevre ve düşük eş bulma olasılığında hangisi hız avantajı sağlayabilir?',['Eşeysiz üreme','Yalnız eşeyli üreme','Hiçbiri çoğalamaz'],0]},
 [E.YASAM_DONGU]:{m:'sirala',baslik:'Temel yaşam döngüsü kurucu',soru:'Gamet oluşumundan yeni bireye hangi sıra kurulur?',t:['Mayoz → gamet → döllenme → zigot → mitoz/gelişme.','Döllenme → mayoz → gamet.'],a:'Mayoz gametleri, döllenme zigotu; mitoz gelişmeyi üretir.',y:'Mayoz ve mitozu yer değiştirmek ploidy değişimini ters çevirir.',sira:['Mayoz','Gamet','Döllenme','Zigot','Mitoz ve gelişme'],kontrol:['Diploit sayı döngüde hangi olayla geri kurulur?',['Döllenme','Mayoz','G1'],0]},
 [E.KALITIM_KAVRAM]:{m:'eslestir',baslik:'Kalıtım kavram ağı',soru:'Baskın alel neden daha güçlü veya daha yaygın demek değildir?',t:['Baskınlık heterozigottaki fenotip ifadesini anlatır.','Baskın alel popülasyonda mutlaka en yaygındır.'],a:'Genotip alel birleşimi, fenotip gözlenen özellik; baskınlık yalnız ifade ilişkisidir.',y:'Günlük dilde baskın sözcüğünü biyolojik güç sanmak frekans çıkarımını bozar.',ogeler:[['AA','Homozigot baskın'],['Aa','Heterozigot'],['aa','Homozigot çekinik'],['Gözlenen özellik','Fenotip']],kategoriler:['Homozigot baskın','Heterozigot','Homozigot çekinik','Fenotip'],kontrol:['Heterozigot neyi anlatır?',['Bir gen için iki farklı alel','İki aynı çekinik alel','Yalnız görünen özellik'],0]},
 [E.KEMOFOTO_KARSILASTIR]:{m:'karsilastir',baslik:'Fotosentez–kemosentez kanıt karşılaştırması',soru:'Işık yokken hangi üretim yolu sürdürülebilir ve enerji kaynağı nedir?',t:['Kemosentez, inorganik maddelerin kimyasal enerjisini kullanabilir.','Fotosentez ve kemosentez ışığa eşit bağımlıdır.'],a:'İki yol da organik madde sentezleyebilir; enerji kaynağı farklıdır.',y:'Üretici kavramını yalnız bitki ve ışıkla sınırlandırmak kemosentetik canlıları dışlar.',satir:[['Fotosentez','Işık','CO₂','O₂ çoğu örnekte oluşabilir'],['Kemosentez','İnorganik madde oksidasyonu','CO₂','Işık gerekmez']],kontrol:['İki sürecin ortak yönü nedir?',['CO₂ kullanarak organik madde sentezleyebilme','İkisi de kloroplastta olur','İkisi de ışık üretir'],0]},
 [E.ORGANIZASYON_ESLE]:{m:'eslestir',baslik:'Organizasyon, habitat ve niş eşlemesi',soru:'Habitat ile niş neden aynı kavram değildir?',t:['Habitat yaşanan yer; niş sistemdeki rol ve ilişkiler bütünüdür.','İkisi de yalnız coğrafi ad demektir.'],a:'Aynı habitatta farklı nişlere sahip türler bulunabilir.',y:'Canlının bulunduğu yeri yaptığı işle aynı saymak ekolojik rolü gizler.',ogeler:[['Tek kurt','Organizma'],['Aynı tür kurtlar','Popülasyon'],['Orman türleri','Komünite'],['Orman ve iklim/toprak','Ekosistem']],kategoriler:['Organizma','Popülasyon','Komünite','Ekosistem'],kontrol:['Arının çiçeklerle tozlaşma ilişkisi hangi kavrama yakındır?',['Niş','Habitat','Biyom adı'],0]},
 [E.ILISKI_SENARYO]:{m:'senaryo',baslik:'Tür etkileşimi kazanç–kayıp laboratuvarı',soru:'İki türün kazanç/kayıp işaretlerinden ilişki türü nasıl çıkarılır?',t:['Her türün uygunluk değişimini ayrı izlerim.','Birlikte bulunmaları mutlaka karşılıklı yarardır.'],a:'+/+, +/0, +/− ve −/− örüntüleri ilişkiyi ayırır.',y:'Bir türün yararını görüp diğerinin maliyetini yok saymak ilişkiyi yanlış adlandırır.',degisken:['1. tür kazancı','2. tür kazancı'],kontrol:['+/− işareti hangi ilişkiye uyar?',['Avcılık/parazitlik','Mutualizm','Rekabet'],0]},
 [E.DONGU_TAMAMLA]:{m:'sirala',baslik:'Karbon ve azot döngüsü bağlantı kurucu',soru:'Madde döngülerinde eksik süreç etiketi ağın hangi akışını keser?',t:['Süreçleri kaynak ve hedef depolar arasında kurarım.','Enerji gibi maddenin de sistemden tek yönde kaybolduğunu varsayarım.'],a:'Madde depolar arasında döner; enerji ise akış sırasında ısı olarak dağılır.',y:'Madde döngüsü ile enerji akışını aynı oklarla açıklamak sistemi bozar.',sira:['Atmosferik depo','Üretici alımı','Tüketiciye aktarım','Ayrıştırma','Atmosfere/toprağa dönüş'],kontrol:['Azotu bitkilerin kullanabileceği biçime çeviren temel biyolojik grup hangisidir?',['Azot bağlayıcı bakteriler','Tepe avcılar','Virüsler'],0]},
 [E.CEVRE_AGI]:{m:'sirala',baslik:'Ötrofikasyon neden–sonuç ağı',soru:'Fazla gübreden balık ölümüne hangi mekanizma zinciri uzanır?',t:['Besin tuzu → alg artışı → ayrışma → O₂ düşüşü → canlı kaybı.','Gübre doğrudan bütün oksijeni yok eder.'],a:'Dolaylı zincir ayrıştırıcı solunumuyla çözünmüş oksijeni azaltır.',y:'Son olayı ilk nedene tek okla bağlamak aradaki biyolojik mekanizmayı siler.',sira:['Besin tuzu artar','Alg çoğalır','Ölü organik madde artar','Ayrıştırıcı solunumu artar','Çözünmüş O₂ azalır'],kontrol:['Oksijen düşüşünün doğrudan biyolojik nedeni hangisidir?',['Ayrıştırıcı solunumunun artması','Alglerin yeşil olması','Suyun saydamlığı'],0]},
 [E.ATIK_KARAR]:{m:'sinifla',baslik:'Atık yönetimi karar istasyonu',soru:'Bir atığın malzemesi kadar kirlenme durumu neden rotayı değiştirir?',t:['Kirlenme geri dönüşüm uygunluğunu değiştirebilir.','Plastik etiketli her şey aynı kutuya gider.'],a:'Azaltma/yeniden kullanım önceliklidir; geri dönüşüm malzeme ve kirlilik koşuluna bağlıdır.',y:'Geri dönüşümü sınırsız çözüm sanmak azaltma basamağını görünmez kılar.',ogeler:[['Temiz cam şişe','Geri dönüşüm'],['Kullanılabilir bez çanta','Yeniden kullanım'],['Atık pil','Özel toplama'],['Kirli peçete','Genel/organik koşula göre']],kategoriler:['Geri dönüşüm','Yeniden kullanım','Özel toplama','Genel/organik koşula göre'],kontrol:['Atık hiyerarşisinde ilk tercih hangisidir?',['Oluşumu azaltmak','Yakmak','Her şeyi karıştırmak'],0]},
 [E.AYAK_IZI]:{m:'senaryo',baslik:'Ekolojik ayak izi senaryo karşılaştırması',soru:'Tek bir puan yerine hangi uygulanabilir değişkenin en büyük farkı yarattığını nasıl bulursun?',t:['Aynı kişi için senaryoları değişken değişken karşılaştırırım.','Puanı ahlak notu olarak kullanırım.'],a:'Ulaşım ve enerji gibi etkiler göreli modelde ayrı ayrı denenir.',y:'Bağlamı olmayan tek puan erişim, altyapı ve coğrafyayı gizler.',degisken:['Ulaşım etkisi','Ev enerjisi etkisi'],kontrol:['Model puanı ne olarak yorumlanmalıdır?',['Varsayımları açık göreli karşılaştırma','Kesin kişilik notu','Tıbbi ölçüm'],0]},
 [E.YEREL_VERI]:{m:'veri',baslik:'Yerel çevre verisi yorumlama',soru:'Tek bir günün ölçümü ile uzun dönem eğilimi neden ayırmalısın?',t:['Değişkenlik ve eğilim için zaman serisini incelerim.','En yüksek tek değeri bütün yıl sayarım.'],a:'Dönem seçimi ortalama, tepe ve eğilim yorumunu değiştirir.',y:'Tek gözlemi iklim veya uzun dönem kirlilik eğilimi sanmak örneklem hatasıdır.',satir:[['İlkbahar',42,58],['Yaz',68,31],['Sonbahar',51,49],['Kış',35,72]],kontrol:['Uzun dönem eğilim için en uygun kanıt hangisidir?',['Birçok dönem boyunca aynı yöntemle ölçüm','Tek bir yüksek gün','Sosyal medya yorumu'],0]},
}

function Istasyon({id,bolge,veri}){const [sira,setSira]=useState([]);const [sinif,setSinif]=useState({});const [a,setA]=useState(50);const [b,setB]=useState(50);const [satir,setSatir]=useState(0);const sec=(x)=>setSira(q=>q.includes(x)?q:[...q,x]);const sirali=veri.sira?.every((x,i)=>sira[i]===x);const sinifDogru=veri.ogeler?.every(([x,y])=>sinif[x]===y);const gorev=veri.m==='sirala'?sirali:veri.m==='sinifla'||veri.m==='eslestir'?sinifDogru:veri.m==='senaryo'?a!==50&&b!==50:veri.m==='veri'?satir>0:veri.m==='karsilastir'?satir>0:false;const kontrol={soru:veri.kontrol[0],secenekler:veri.kontrol[1],dogru:veri.kontrol[2],ipucu:'Sahnedeki değişen kanıtı ve mekanizma yönünü birlikte izle.',cozum:'Başlangıç koşulunu tek değişken değiştirerek karşılaştır ve ölçüm farkını kullan.'};return <BiyolojiModulKabugu id={id} bolge={bolge} baslik={veri.baslik} soru={veri.soru} tahminler={veri.t} aciklama={veri.a} yanilgi={veri.y} gorevTamam={gorev} kontrol={kontrol} modelVarsayimi="Bu istasyonun veri ve katsayıları konuya özgü eğitim modelidir; gerçek sistemde daha fazla değişken bulunur."><div className={`ba-tamamlayici ${veri.m}`}>{veri.m==='sirala'?<><div className="ba-sirala">{veri.sira.filter(x=>!sira.includes(x)).map(x=><button key={x} onClick={()=>sec(x)}>{x}</button>)}</div><div className="ba-zaman-cizgisi">{veri.sira.map((x,i)=><span key={x} className={sira[i]===x?'dogru':sira[i]?'yanlis':''}><b>{i+1}</b>{sira[i]??'Adım seç'}{i<veri.sira.length-1?<ArrowRight/>:null}</span>)}</div><button onClick={()=>setSira([])}><RotateCcw/> Sıfırla</button></>:null}{['sinifla','eslestir'].includes(veri.m)?<div className="ba-esleme-lab">{veri.ogeler.map(([x])=><label key={x}><b>{x}</b><select value={sinif[x]??''} onChange={e=>setSinif(q=>({...q,[x]:e.target.value}))}><option value="">Kategori seç</option>{veri.kategoriler.map(y=><option key={y}>{y}</option>)}</select>{sinif[x]?<span className={sinif[x]===veri.ogeler.find(z=>z[0]===x)[1]?'dogru':'yanlis'}>{sinif[x]===veri.ogeler.find(z=>z[0]===x)[1]?'Kanıtla uyumlu':'Mekanizmayı yeniden izle'}</span>:null}</label>)}</div>:null}{veri.m==='senaryo'?<div className="ba-senaryo-lab"><Kaydirici etiket={veri.degisken[0]} deger={a} birim="%" onChange={setA}/><Kaydirici etiket={veri.degisken[1]} deger={b} birim="%" onChange={setB}/><div className="ba-senaryo-sonuc"><GitCompareArrows/><b>{a>b?'1. değişken baskın':a<b?'2. değişken baskın':'Koşullar dengeli'}</b><span>Fark: {Math.abs(a-b)} puan</span></div></div>:null}{['karsilastir','veri'].includes(veri.m)?<div className="ba-veri-lab"><div>{veri.satir.map((r,i)=><button key={i} className={satir===i?'etkin':''} onClick={()=>setSatir(i)}>{r[0]}</button>)}</div><article>{veri.satir[satir].map((x,i)=><span key={i}>{i?<b>{x}</b>:<strong>{x}</strong>}</span>)}</article><p>Satırlar dekoratif değildir: seçimin görünen veri/özellik kümesini değiştirir.</p></div>:null}</div></BiyolojiModulKabugu>}

export default function TamamlayiciIstasyonlar({bolge,haric=[]}){const liste=useMemo(()=>ALT_BASLIKLAR.filter(x=>x.bolge===bolge&&!haric.includes(x.etkilesimId)&&V[x.etkilesimId]),[bolge,haric]);return <>{liste.map(x=><Istasyon key={x.etkilesimId} id={x.etkilesimId} bolge={bolge} veri={V[x.etkilesimId]}/>)}</>}

