import { useEffect, useRef, useState } from 'react'
import { Atom, Waves } from 'lucide-react'
import { MOLEKULLER, tonisiteAdim, zarAdim, zarBaslat, zarSifirla } from '../../../lib/biyoloji/zar.js'
import { E } from '../../../data/biyoloji/etkilesimler.js'
import BiyolojiModulKabugu from '../ortak/BiyolojiModulKabugu.jsx'
import BiyolojiGrafik from '../ortak/BiyolojiGrafik.jsx'
import OlcumPaneli from '../ortak/OlcumPaneli.jsx'
import { Anahtar, DurumRozeti, Kaydirici, SecimSeridi, SimKontrol } from '../ortak/Kontroller.jsx'

const secenekler=Object.entries(MOLEKULLER).map(([value,x])=>({value,label:x.ad}))
export default function ZarTasinimLaboratuvari(){
  const [s,setS]=useState(()=>zarBaslat());const [oynuyor,setOynuyor]=useState(false);const [hiz,setHiz]=useState(1);const gecmis=useRef([])
  const adimla=()=>setS(eski=>{gecmis.current.push(eski);return zarAdim(eski,1)})
  useEffect(()=>{if(!oynuyor)return;const z=setInterval(adimla,650/Math.max(.25,hiz));return()=>clearInterval(z)},[oynuyor,hiz])
  const ayarla=(alan,deger)=>{setOynuyor(false);gecmis.current=[];setS(zarBaslat({...s,[alan]:deger}))};const sifirla=()=>{setOynuyor(false);gecmis.current=[];setS(zarSifirla())};const geri=()=>{setOynuyor(false);const x=gecmis.current.pop();if(x)setS(x)}
  const mekanizma=s.mekanizma??{ad:'Koşulları ayarla',neden:'Deneyi çalıştırınca taşıma mekanizması görünür.'}; const sol=Array.from({length:Math.min(24,Math.round(s.dis))},(_,i)=>i); const sag=Array.from({length:Math.min(24,Math.round(s.ic))},(_,i)=>i)
  return <BiyolojiModulKabugu id={E.ZAR_LAB} bolge="hucre" baslik="Zar taşınım laboratuvarı" soru="Aynı derişim farkı neden her molekülü aynı yoldan geçirmez?" tahminler={['Molekül yapısı, gradyan, protein ve ATP birlikte mekanizmayı belirler.','Tüm moleküller daima yoğundan aza doğrudan geçer.']} aciklama="Küçük apolar moleküller fosfolipitlerden, polar/yüklü tanecikler proteinlerden; büyük yükler vezikülle geçer. Gradyana karşı taşıma ATP ister." yanilgi="Derişim farkı yönü açıklar ama zarın seçiciliğini ve enerji gereksinimini tek başına açıklamaz." gorevTamam={s.zaman>=4&&s.toplamHareket>0} kontrol={{soru:'İyonu düşük derişimden yüksek derişime taşımak için hangi ikili zorunludur?',secenekler:['Uygun taşıyıcı ve ATP','Yalnız fosfolipit tabaka','Yalnız derişim eşitliği'],dogru:0,ipucu:'Gradyana karşı yolculuk hem bir kapı hem enerji ister.',cozum:'İyonu seç, hedef yönü düşükten yükseğe ayarla; ATP’yi kapatıp açarak net akışı karşılaştır.'}} modelVarsayimi="İki iyi karışan bölme ve tek molekül türü modellenir. Elektriksel gradyan ve eş-taşıma ayrıntıları TYT düzeyi dışında tutulur." olcek="Zarın iki yanındaki parçacıkların temsili görünümü">
    <div className="ba-sim-grid zar">
      <aside className="ba-kontrol-panel"><div className="ba-panel-bas"><span><Atom/> Taşıma koşulları</span><DurumRozeti durum={s.durum}/></div><SecimSeridi etiket="Molekül" deger={s.molekul} secenekler={secenekler} onChange={(v)=>ayarla('molekul',v)}/><SecimSeridi etiket="Hedef yön" deger={s.hedef} secenekler={[{value:'iceri',label:'Hücre içine'},{value:'disari',label:'Hücre dışına'}]} onChange={(v)=>ayarla('hedef',v)}/><Kaydirici etiket="Dış derişim" deger={Math.round(s.dis)} birim="tanecik" min={0} max={24} onChange={(v)=>ayarla('dis',v)}/><Kaydirici etiket="İç derişim" deger={Math.round(s.ic)} birim="tanecik" min={0} max={24} onChange={(v)=>ayarla('ic',v)}/><div className="ba-anahtarlar"><Anahtar etiket="Kanal / taşıyıcı" acik={s.kanal} onChange={(v)=>ayarla('kanal',v)}/><Anahtar etiket="ATP" acik={s.atp} onChange={(v)=>ayarla('atp',v)}/></div><SimKontrol oynuyor={oynuyor} onOynat={()=>setOynuyor(o=>!o)} onAdim={adimla} onGeri={geri} onSifirla={sifirla} hiz={hiz} onHiz={setHiz} geri={gecmis.current.length>0}/></aside>
      <section className="ba-sahne-panel"><div className={`ba-zar-canli ${oynuyor?'oynuyor':''} ${mekanizma.ad.toLocaleLowerCase('tr').replaceAll(' ','-')}`} data-testid="zar-sahnesi"><div className="bolme dis"><b>Dış ortam</b>{sol.map(i=><i key={`d${i}`} style={{'--x':`${12+(i*31)%42}%`,'--y':`${18+(i*47+s.faz*8)%70}%`}}><span>{MOLEKULLER[s.molekul].ad}</span></i>)}</div><div className="fosfolipit"><span/><span/><em>{s.kanal?'protein kanalı':'kapalı zar'}</em></div><div className="bolme ic"><b>Hücre içi</b>{sag.map(i=><i key={`i${i}`} style={{'--x':`${55+(i*37)%40}%`,'--y':`${16+(i*43+s.faz*6)%72}%`}}><span>{MOLEKULLER[s.molekul].ad}</span></i>)}</div>{['Endositoz','Ekzositoz'].includes(mekanizma.ad)?<div className="vezikul"><Waves/><span>Zar kıvrılıyor</span></div>:null}<strong>{mekanizma.ad}</strong></div><OlcumPaneli olcumler={[{etiket:'Dış',deger:s.dis.toFixed(1),birim:'tanecik'},{etiket:'İç',deger:s.ic.toFixed(1),birim:'tanecik'},{etiket:'Net akış',deger:s.netAkis.toFixed(2),birim:'/adım',vurgu:true},{etiket:'Toplam hareket',deger:s.toplamHareket.toFixed(1),birim:'geçiş'}]}/><BiyolojiGrafik noktalar={s.grafik} seriler={[{key:'dis',ad:'Dış',renk:'#ffb45b'},{key:'ic',ad:'İç',renk:'#61d7b0'}]} xEtiket="Zaman (adım)" yEtiket="Tanecik" birim="adet" ariaLabel="Zarın iki yanındaki tanecik sayılarının zamanla değişimi"/></section>
    </div><p className={`ba-mekanizma ${s.durum==='koşul uygun değil'?'uyari':'olumlu'}`}><b>{mekanizma.ad}:</b> {mekanizma.neden} {s.durum==='dengeye ulaştı'?'Denge oluştu; iki yönlü moleküler hareket sürerken net akış yaklaşık sıfırdır.':''}</p>
  </BiyolojiModulKabugu>
}

export function TonisiteLaboratuvari(){const [ortam,setOrtam]=useState('izotonik');const [hucre,setHucre]=useState('hayvan');const [adim,setAdim]=useState(0);const d=tonisiteAdim({ortam,hucre,adim});return <BiyolojiModulKabugu id={E.TONISITE_LAB} bolge="hucre" baslik="Tonisite ve hücre biçimi" soru="Bitki ve hayvan hücresi aynı hipotonik ortamda neden aynı sonucu vermez?" tahminler={['Hücre duvarı bitkide aşırı genişlemeyi sınırlar.','Su yalnız hayvan hücresine girer.']} aciklama="Her iki hücreye de su girebilir; bitki hücresinin duvarı turgor basıncına karşı mekanik destek sağlar." yanilgi="Ozmoz hücre tipine göre kapanıp açılmaz; yapısal sonuç hücre duvarı nedeniyle değişir." gorevTamam={adim>=5} kontrol={{soru:'Hipertonik ortamda bitki hücresinde beklenen durum nedir?',secenekler:['Plazmoliz: zarın duvardan ayrılması','Lizis: duvarın patlaması','Kloroplast oluşumu'],dogru:0,ipucu:'Su hücre dışına çıkar; duvar korunurken iç kısım küçülür.',cozum:'Ortamı hipertonik seç, adımla ve zar ile duvar arasındaki boşluğu izle.'}} modelVarsayimi="Çözünen türü ayrıştırılmadan yalnız göreli su potansiyeli ve hücre duvarının mekanik etkisi temsil edilir."><div className="ba-kompakt-deney"><div className="ba-kontrol-satiri"><SecimSeridi etiket="Ortam" deger={ortam} secenekler={['hipotonik','izotonik','hipertonik']} onChange={(v)=>{setOrtam(v);setAdim(0)}}/><SecimSeridi etiket="Hücre" deger={hucre} secenekler={['hayvan','bitki']} onChange={(v)=>{setHucre(v);setAdim(0)}}/></div><div className={`ba-tonisite ${hucre} ${ortam}`}><div className="duvar"><div className="hucre" style={{transform:`scale(${d.hacim})`}}><i/></div></div><strong>{d.durum}</strong><span>Net su yönü: {d.suYonu}</span></div><SimKontrol oynuyor={false} onOynat={()=>setAdim(a=>Math.min(8,a+1))} onAdim={()=>setAdim(a=>Math.min(8,a+1))} onGeri={()=>setAdim(a=>Math.max(0,a-1))} onSifirla={()=>setAdim(0)} geri={adim>0}/></div></BiyolojiModulKabugu>}

