/**
 * DESTE — FUTBOL VE SPOR (İngilizce)
 *
 * İngilizcede öğrencinin zorlandığı yer kelime değil, EŞ DİZİMDİR:
 * "score a goal" mi "make a goal" mu? Bu destede kartların çoğu tek
 * kelime değil, birlikte kullanılan kelime çiftidir — çünkü sınavda ve
 * konuşmada ölçülen budur.
 */

export const DESTE = {
  id: 'futbol-spor',
  dil: 'en',
  ad: 'Futbol ve spor',
  simge: '⚽',
  aciklama: 'Maç anlatımında geçen kelimeler ve hangi fiille kullanıldıkları.',
  seviye: 'A2–B1',
  kartlar: [
    {
      id: 'en-fut-01', on: 'score a goal', okunus: 'skor ı goul', tur: 'eş dizim',
      arka: 'gol atmak',
      ornek: 'He scored a goal in the last minute.',
      ornekTr: 'Son dakikada gol attı.',
      not: '"make a goal" YANLIŞTIR. Doğru fiil "score"dur.',
    },
    {
      id: 'en-fut-02', on: 'the referee', okunus: 'dı referi', tur: 'isim',
      arka: 'hakem',
      ornek: 'The referee showed him a red card.',
      ornekTr: 'Hakem ona kırmızı kart gösterdi.',
      not: 'Kısaltması "ref"tir ve konuşmada çok kullanılır.',
    },
    {
      id: 'en-fut-03', on: 'draw', okunus: 'dro', tur: 'isim / fiil',
      arka: 'beraberlik; berabere kalmak',
      ornek: 'The match ended in a draw.',
      ornekTr: 'Maç beraberlikle bitti.',
      not: 'Aynı kelime "çizmek" anlamına da gelir; bağlam ayırır.',
    },
    {
      id: 'en-fut-04', on: 'beat', okunus: 'biit', tur: 'fiil (düzensiz)',
      arka: 'yenmek (rakibi)',
      ornek: 'We beat them three-nil last week.',
      ornekTr: 'Geçen hafta onları 3-0 yendik.',
      not: 'Rakibi yenersin ("beat them"), maçı kazanırsın ("win the match"). Karıştırma.',
    },
    {
      id: 'en-fut-05', on: 'win', okunus: 'vin', tur: 'fiil (düzensiz)',
      arka: 'kazanmak (maçı, kupayı)',
      ornek: 'They won the cup for the first time.',
      ornekTr: 'Kupayı ilk kez kazandılar.',
      not: 'Nesnesi maç ya da kupadır, rakip DEĞİLDİR: "win the match", "beat the team".',
    },
    {
      id: 'en-fut-06', on: 'the pitch', okunus: 'dı piç', tur: 'isim',
      arka: 'saha (futbol)',
      ornek: 'The players are coming onto the pitch.',
      ornekTr: 'Oyuncular sahaya çıkıyor.',
      not: 'İngiltere\'de "pitch", Amerika\'da "field" denir.',
    },
    {
      id: 'en-fut-07', on: 'support a team', okunus: 'sıport ı tiim', tur: 'eş dizim',
      arka: 'bir takımı tutmak',
      ornek: 'I have supported this team since I was six.',
      ornekTr: 'Altı yaşımdan beri bu takımı tutuyorum.',
      not: 'Taraftar "a supporter" ya da "a fan"dir.',
    },
    {
      id: 'en-fut-08', on: 'work out', okunus: 'vörk aut', tur: 'öbek fiil',
      arka: 'spor yapmak, çalışmak (vücut)',
      ornek: 'I work out three times a week.',
      ornekTr: 'Haftada üç kez spor yapıyorum.',
      not: 'Aynı öbek "sonuç vermek" anlamına da gelir: "It worked out well."',
    },
    {
      id: 'en-fut-09', on: 'be into something', okunus: 'bi intu samthing', tur: 'kalıp',
      arka: 'bir şeye meraklı olmak',
      ornek: 'I am really into basketball these days.',
      ornekTr: 'Bu aralar basketbola çok meraklıyım.',
      not: 'Günlük konuşmada "hobim" demenin en doğal yolu.',
    },
    {
      id: 'en-fut-10', on: 'get injured', okunus: 'get incırd', tur: 'kalıp',
      arka: 'sakatlanmak',
      ornek: 'Our best player got injured in training.',
      ornekTr: 'En iyi oyuncumuz antrenmanda sakatlandı.',
      not: 'Sakatlık "an injury"dir. "Get + sıfat" kalıbı "olmak" anlamı verir.',
    },
    /* --- Takım ve pozisyonlar --- */
    {
      id: 'en-fut-11', on: 'goalkeeper', okunus: 'goulkiipır', tur: 'isim',
      arka: 'kaleci',
      ornek: 'Their goalkeeper saved three shots in the first half.',
      ornekTr: 'Kalecileri ilk yarıda üç şut kurtardı.',
      not: 'Konuşmada kısaca "keeper" denir. "Goalman" diye bir kelime yoktur.',
    },
    {
      id: 'en-fut-12', on: 'defender', okunus: 'difendır', tur: 'isim',
      arka: 'defans oyuncusu',
      ornek: 'He plays as a defender for the school team.',
      ornekTr: 'Okul takımında defans oynuyor.',
      not: 'Mevki söylerken "play as a + mevki" kalıbı kullanılır.',
    },
    {
      id: 'en-fut-13', on: 'midfielder', okunus: 'midfiildır', tur: 'isim',
      arka: 'orta saha oyuncusu',
      ornek: 'Our midfielder controls the whole game.',
      ornekTr: 'Orta saha oyuncumuz bütün oyunu yönetiyor.',
      not: 'Saha bölgesi "the midfield", oyuncu "midfielder"dır.',
    },
    {
      id: 'en-fut-14', on: 'striker', okunus: 'straykır', tur: 'isim',
      arka: 'forvet, golcü',
      ornek: 'They signed a new striker last summer.',
      ornekTr: 'Geçen yaz yeni bir forvet transfer ettiler.',
      not: '"Forward" da denir. Türkçedeki "forvet" bu kelimeden gelir.',
    },
    {
      id: 'en-fut-15', on: 'substitute', okunus: 'sabstityut', tur: 'isim / fiil',
      arka: 'yedek oyuncu; oyuncu değiştirmek',
      ornek: 'He came on as a substitute in the second half.',
      ornekTr: 'İkinci yarıda yedek olarak oyuna girdi.',
      not: 'Konuşmada "sub" diye kısaltılır. Oyuna girmek "come on"dur.',
    },
    {
      id: 'en-fut-16', on: 'captain', okunus: 'keptin', tur: 'isim',
      arka: 'takım kaptanı',
      ornek: 'The captain wears the armband.',
      ornekTr: 'Kaptan pazubandı takar.',
      not: 'Aynı kelime gemi kaptanı için de kullanılır.',
    },
    {
      id: 'en-fut-17', on: 'manager', okunus: 'menıcır', tur: 'isim',
      arka: 'teknik direktör',
      ornek: 'The manager changed the tactics at half-time.',
      ornekTr: 'Teknik direktör devrede taktiği değiştirdi.',
      not: 'İngiltere\'de "manager", Amerika\'da "head coach" denir.',
    },
    {
      id: 'en-fut-18', on: 'squad', okunus: 'skuad', tur: 'isim',
      arka: 'kadro (tüm oyuncular)',
      ornek: 'There are 25 players in the squad.',
      ornekTr: 'Kadroda 25 oyuncu var.',
      not: '"Squad" tüm kadrodur, "line-up" o maça çıkan on birdir.',
    },
    {
      id: 'en-fut-19', on: 'line-up', okunus: 'layn ap', tur: 'isim',
      arka: 'ilk on bir, çıkış kadrosu',
      ornek: 'The coach announced the line-up an hour before the match.',
      ornekTr: 'Antrenör çıkış kadrosunu maçtan bir saat önce açıkladı.',
      not: 'Fiil hâli tireyi kaybeder: "The team lined up in a 4-4-2."',
    },
    {
      id: 'en-fut-20', on: 'kick-off', okunus: 'kik of', tur: 'isim',
      arka: 'başlama vuruşu, maçın başlaması',
      ornek: 'Kick-off is at eight o\'clock.',
      ornekTr: 'Maç saat sekizde başlıyor.',
      not: 'Toplantı için de kullanılır: "kick off the meeting" = toplantıyı başlatmak.',
    },
    /* --- Maç içindeki anlar --- */
    {
      id: 'en-fut-21', on: 'penalty', okunus: 'penılti', tur: 'isim',
      arka: 'penaltı',
      ornek: 'The referee gave a penalty in the last minute.',
      ornekTr: 'Hakem son dakikada penaltı verdi.',
      not: 'Penaltı "atılmaz", "kullanılır": take a penalty.',
    },
    {
      id: 'en-fut-22', on: 'free kick', okunus: 'frii kik', tur: 'isim',
      arka: 'serbest vuruş, frikik',
      ornek: 'He scored from a free kick outside the box.',
      ornekTr: 'Ceza sahası dışından frikikten gol attı.',
      not: '"From a free kick" = frikikten. Buradaki edat "from"dur.',
    },
    {
      id: 'en-fut-23', on: 'corner', okunus: 'kornır', tur: 'isim',
      arka: 'korner',
      ornek: 'They won six corners in the first half.',
      ornekTr: 'İlk yarıda altı korner kazandılar.',
      not: 'Korner "kazanılır" (win a corner), "alınmaz".',
    },
    {
      id: 'en-fut-24', on: 'offside', okunus: 'ofsayd', tur: 'sıfat / isim',
      arka: 'ofsayt',
      ornek: 'The goal was disallowed because he was offside.',
      ornekTr: 'Ofsaytta olduğu için gol iptal edildi.',
      not: 'Sıfattır: "he was offside". "He made offside" YANLIŞTIR.',
    },
    {
      id: 'en-fut-25', on: 'foul', okunus: 'faul', tur: 'isim / fiil',
      arka: 'faul; faul yapmak',
      ornek: 'He committed a foul near the penalty area.',
      ornekTr: 'Ceza sahasının yakınında faul yaptı.',
      not: 'Faul "yapılır" derken fiil "commit" ya da doğrudan "foul"dur.',
    },
    {
      id: 'en-fut-26', on: 'half-time', okunus: 'haf taym', tur: 'isim',
      arka: 'devre arası',
      ornek: 'The score was 1-1 at half-time.',
      ornekTr: 'Devre arasında skor 1-1\'di.',
      not: 'İki yarının her biri "half"tir: the first half, the second half.',
    },
    {
      id: 'en-fut-27', on: 'injury time', okunus: 'incıri taym', tur: 'isim',
      arka: 'uzatma dakikaları',
      ornek: 'They equalised in injury time.',
      ornekTr: 'Uzatma dakikalarında beraberliği yakaladılar.',
      not: '"Stoppage time" da denir. Uzatma devreleri ise "extra time"dır.',
    },
    {
      id: 'en-fut-28', on: 'extra time', okunus: 'ekstra taym', tur: 'isim',
      arka: 'uzatma devreleri',
      ornek: 'The match went to extra time.',
      ornekTr: 'Maç uzatmalara gitti.',
      not: 'Sonrasında penaltılar gelir: "a penalty shoot-out".',
    },
    {
      id: 'en-fut-29', on: 'own goal', okunus: 'oun goul', tur: 'isim',
      arka: 'kendi kalesine gol',
      ornek: 'The defender scored an own goal.',
      ornekTr: 'Defans oyuncusu kendi kalesine gol attı.',
      not: 'Günlük dilde "kendi ayağına sıkmak" anlamında da kullanılır.',
    },
    {
      id: 'en-fut-30', on: 'equalise', okunus: 'iikuılayz', tur: 'fiil',
      arka: 'beraberliği yakalamak',
      ornek: 'We equalised five minutes before the end.',
      ornekTr: 'Bitişten beş dakika önce beraberliği yakaladık.',
      not: 'Amerika\'da "equalize" yazılır. Golün adı "the equaliser"dır.',
    },
    /* --- Eş dizimler (hangi fiil hangi isimle) --- */
    {
      id: 'en-fut-31', on: 'save a shot', okunus: 'seyv ı şat', tur: 'eş dizim',
      arka: 'şutu kurtarmak',
      ornek: 'The keeper saved a shot with one hand.',
      ornekTr: 'Kaleci şutu tek eliyle kurtardı.',
      not: 'Kurtarışın kendisi "a save"dir: "He made a great save."',
    },
    {
      id: 'en-fut-32', on: 'miss a chance', okunus: 'mis ı çans', tur: 'eş dizim',
      arka: 'fırsatı kaçırmak',
      ornek: 'He missed an easy chance in front of the goal.',
      ornekTr: 'Kale önünde kolay bir fırsatı kaçırdı.',
      not: '"Lose a chance" denmez; doğru fiil "miss"tir.',
    },
    {
      id: 'en-fut-33', on: 'cross the ball', okunus: 'kros dı bol', tur: 'eş dizim',
      arka: 'ortalamak',
      ornek: 'He crossed the ball into the box.',
      ornekTr: 'Topu ceza sahasına ortaladı.',
      not: 'Ortanın kendisi isim olarak "a cross"tur.',
    },
    {
      id: 'en-fut-34', on: 'head the ball', okunus: 'hed dı bol', tur: 'eş dizim',
      arka: 'kafa vurmak',
      ornek: 'He headed the ball into the net.',
      ornekTr: 'Topa kafa vurup ağlara gönderdi.',
      not: 'Golün adı "a header"dır: "a great header".',
    },
    {
      id: 'en-fut-35', on: 'dribble past', okunus: 'dribıl past', tur: 'eş dizim',
      arka: 'çalım atıp geçmek',
      ornek: 'She dribbled past two defenders.',
      ornekTr: 'İki defans oyuncusunu çalımlayıp geçti.',
      not: 'Basketbolda "dribble" topu sektirmek anlamına gelir.',
    },
    {
      id: 'en-fut-36', on: 'tackle', okunus: 'tekıl', tur: 'fiil / isim',
      arka: 'müdahale etmek, topu kesmek',
      ornek: 'He tackled the striker cleanly.',
      ornekTr: 'Forvete temiz bir müdahale yaptı.',
      not: 'Günlük dilde "bir sorunla uğraşmak" anlamına gelir: "tackle a problem".',
    },
    {
      id: 'en-fut-37', on: 'set up a goal', okunus: 'set ap ı goul', tur: 'eş dizim',
      arka: 'gol pası vermek, golü hazırlamak',
      ornek: 'He set up two goals in that match.',
      ornekTr: 'O maçta iki gol pası verdi.',
      not: 'Asistin adı "an assist"tir: "He got an assist."',
    },
    {
      id: 'en-fut-38', on: 'keep a clean sheet', okunus: 'kiip ı kliin şiit', tur: 'deyim',
      arka: 'gol yememek (kalesini kapatmak)',
      ornek: 'Our keeper has kept four clean sheets this season.',
      ornekTr: 'Kalecimiz bu sezon dört maçta gol yemedi.',
      not: 'Kelimesi kelimesine "temiz kâğıt tutmak"tır; yani kâğıtta hiç gol yazmaz.',
    },
    {
      id: 'en-fut-39', on: 'be sent off', okunus: 'bi sent of', tur: 'kalıp',
      arka: 'kırmızı kart görüp oyundan atılmak',
      ornek: 'He was sent off for a bad foul.',
      ornekTr: 'Kötü bir faulden dolayı oyundan atıldı.',
      not: 'Edilgen kullanılır. Hakem tarafından yapılan bir iştir.',
    },
    {
      id: 'en-fut-40', on: 'come from behind', okunus: 'kam from bihaynd', tur: 'deyim',
      arka: 'geriden gelip öne geçmek',
      ornek: 'They came from behind to win 3-2.',
      ornekTr: 'Geriden gelip 3-2 kazandılar.',
      not: 'Böyle bir dönüşün adı "a comeback"tir.',
    },
    /* --- Lig, kupa ve sonuçlar --- */
    {
      id: 'en-fut-41', on: 'the league', okunus: 'dı liig', tur: 'isim',
      arka: 'lig',
      ornek: 'They are top of the league.',
      ornekTr: 'Ligin zirvesindeler.',
      not: 'Puan tablosu "the table"dır: "second in the table".',
    },
    {
      id: 'en-fut-42', on: 'fixture', okunus: 'fiksçır', tur: 'isim',
      arka: 'fikstür, maç programı',
      ornek: 'We have a difficult fixture on Sunday.',
      ornekTr: 'Pazar günü zor bir maçımız var.',
      not: 'Tek bir maç için de kullanılır, tüm program için de.',
    },
    {
      id: 'en-fut-43', on: 'derby', okunus: 'daabi', tur: 'isim',
      arka: 'derbi (şehir içi rekabet maçı)',
      ornek: 'The derby is always sold out.',
      ornekTr: 'Derbi her zaman tükeniyor.',
      not: 'İngilizler "daabi", Amerikalılar "dırbi" okur.',
    },
    {
      id: 'en-fut-44', on: 'be relegated', okunus: 'bi religeytid', tur: 'kalıp',
      arka: 'küme düşmek',
      ornek: 'The team was relegated last season.',
      ornekTr: 'Takım geçen sezon küme düştü.',
      not: 'Tersi "be promoted" = üst lige çıkmak.',
    },
    {
      id: 'en-fut-45', on: 'runner-up', okunus: 'ranır ap', tur: 'isim',
      arka: 'ikinci olan takım/kişi',
      ornek: 'They finished as runners-up.',
      ornekTr: 'İkinci olarak bitirdiler.',
      not: 'Çoğulu "runners-up"tır, ilk kelime çoğul olur.',
    },
    {
      id: 'en-fut-46', on: 'trophy', okunus: 'troufi', tur: 'isim',
      arka: 'kupa (ödül olarak)',
      ornek: 'They lifted the trophy in front of their fans.',
      ornekTr: 'Kupayı taraftarlarının önünde kaldırdılar.',
      not: 'Kupayı "kaldırmak" fiili "lift"tir. Turnuvanın adı ise "the cup"tır.',
    },
    {
      id: 'en-fut-47', on: 'knockout stage', okunus: 'nokaut steyc', tur: 'isim',
      arka: 'eleme turu',
      ornek: 'They reached the knockout stage for the first time.',
      ornekTr: 'İlk kez eleme turuna kaldılar.',
      not: 'Öncesi grup aşamasıdır: "the group stage".',
    },
    {
      id: 'en-fut-48', on: 'aggregate', okunus: 'egrigıt', tur: 'isim',
      arka: 'iki maçın toplam skoru',
      ornek: 'They won 4-3 on aggregate.',
      ornekTr: 'İki maçın toplamında 4-3 kazandılar.',
      not: 'Kalıbı "on aggregate"tir, edat değişmez.',
    },
    {
      id: 'en-fut-49', on: 'underdog', okunus: 'andırdog', tur: 'isim',
      arka: 'zayıf görülen taraf',
      ornek: 'Nobody expected the underdogs to win.',
      ornekTr: 'Kimse zayıf görülen tarafın kazanmasını beklemiyordu.',
      not: 'Favori taraf "the favourite"tir. Sınav metinlerinde sık geçer.',
    },
    {
      id: 'en-fut-50', on: 'hat-trick', okunus: 'het trik', tur: 'isim',
      arka: 'bir maçta üç gol',
      ornek: 'He scored a hat-trick against his old team.',
      ornekTr: 'Eski takımına karşı üç gol attı.',
      not: 'Fiili "score"dur: score a hat-trick.',
    },
    /* --- Taraftar ve stat --- */
    {
      id: 'en-fut-51', on: 'supporter', okunus: 'sıportır', tur: 'isim',
      arka: 'taraftar',
      ornek: 'Away supporters filled the corner of the stadium.',
      ornekTr: 'Deplasman taraftarları stadın köşesini doldurdu.',
      not: '"Fan" daha genel, "supporter" bir takıma bağlılığı anlatır.',
    },
    {
      id: 'en-fut-52', on: 'home and away', okunus: 'houm end ıvey', tur: 'kalıp',
      arka: 'iç saha ve deplasman',
      ornek: 'We play them home and away.',
      ornekTr: 'Onlarla iç sahada ve deplasmanda oynuyoruz.',
      not: '"At home" = kendi sahasında, "away" = deplasmanda.',
    },
    {
      id: 'en-fut-53', on: 'the stands', okunus: 'dı stendz', tur: 'isim',
      arka: 'tribünler',
      ornek: 'The stands were full an hour before kick-off.',
      ornekTr: 'Tribünler maçtan bir saat önce doluydu.',
      not: 'Çoğul kullanılır. Tekil "stand" tek bir tribün bölümüdür.',
    },
    {
      id: 'en-fut-54', on: 'sold out', okunus: 'sould aut', tur: 'sıfat',
      arka: 'biletleri tükenmiş',
      ornek: 'The match is completely sold out.',
      ornekTr: 'Maçın biletleri tamamen tükendi.',
      not: 'Konser ve sinema için de aynı kalıp kullanılır.',
    },
    {
      id: 'en-fut-55', on: 'chant', okunus: 'çant', tur: 'isim / fiil',
      arka: 'tezahürat; tezahürat yapmak',
      ornek: 'The fans chanted his name all night.',
      ornekTr: 'Taraftarlar bütün gece onun adını haykırdı.',
      not: 'Tek seslik bir bağırış "a shout", ritimli olan "a chant"tir.',
    },
    {
      id: 'en-fut-56', on: 'cheer someone on', okunus: 'çir samvan on', tur: 'öbek fiil',
      arka: 'birini tezahüratla desteklemek',
      ornek: 'We went to the stadium to cheer them on.',
      ornekTr: 'Onları desteklemek için stada gittik.',
      not: 'Nesne araya girer: "cheer them on", "cheer on the team".',
    },
    {
      id: 'en-fut-57', on: 'atmosphere', okunus: 'etmısfir', tur: 'isim',
      arka: 'ortam, hava (duygusal)',
      ornek: 'The atmosphere in the stadium was incredible.',
      ornekTr: 'Stattaki hava inanılmazdı.',
      not: 'Aynı kelime "atmosfer" (hava katmanı) anlamına da gelir.',
    },
    {
      id: 'en-fut-58', on: 'season ticket', okunus: 'siizın tikit', tur: 'isim',
      arka: 'kombine bilet',
      ornek: 'My uncle has a season ticket.',
      ornekTr: 'Amcamın kombine bileti var.',
      not: 'Otobüs ve tren için de kullanılır: aylık/yıllık abonman.',
    },
    {
      id: 'en-fut-59', on: 'boo', okunus: 'buu', tur: 'fiil / isim',
      arka: 'yuhalamak',
      ornek: 'The crowd booed the decision.',
      ornekTr: 'Seyirci kararı yuhaladı.',
      not: 'Tersi "cheer"dir. Tiyatroda da kullanılır.',
    },
    {
      id: 'en-fut-60', on: 'crowd', okunus: 'kraud', tur: 'isim',
      arka: 'kalabalık, seyirci topluluğu',
      ornek: 'A crowd of 40,000 watched the game.',
      ornekTr: 'Kırk bin kişilik bir seyirci maçı izledi.',
      not: 'Tekil görünür ama İngiltere\'de çoğul fiil de alabilir.',
    },
    /* --- Diğer spor dalları --- */
    {
      id: 'en-fut-61', on: 'court', okunus: 'kort', tur: 'isim',
      arka: 'kort/saha (basketbol, tenis, voleybol)',
      ornek: 'The basketball court is next to the school.',
      ornekTr: 'Basketbol sahası okulun yanında.',
      not: 'Futbol sahası "pitch/field", bunlar ise "court"tur. Karıştırma.',
    },
    {
      id: 'en-fut-62', on: 'serve', okunus: 'sörv', tur: 'fiil / isim',
      arka: 'servis atmak (tenis, voleybol)',
      ornek: 'She has a very fast serve.',
      ornekTr: 'Çok hızlı bir servisi var.',
      not: 'Aynı fiil "yemek servis etmek" anlamına da gelir.',
    },
    {
      id: 'en-fut-63', on: 'match point', okunus: 'meç poynt', tur: 'isim',
      arka: 'maç sayısı (teniste)',
      ornek: 'He saved three match points.',
      ornekTr: 'Üç maç sayısı kurtardı.',
      not: 'Set için "set point", oyun için "game point" denir.',
    },
    {
      id: 'en-fut-64', on: 'lap', okunus: 'lep', tur: 'isim',
      arka: 'tur (pist veya havuzda)',
      ornek: 'He swims twenty laps every morning.',
      ornekTr: 'Her sabah yirmi tur yüzüyor.',
      not: 'Yarışta "son tur" = "the final lap".',
    },
    {
      id: 'en-fut-65', on: 'sprint', okunus: 'sprint', tur: 'fiil / isim',
      arka: 'kısa mesafeyi çok hızlı koşmak',
      ornek: 'He sprinted the last hundred metres.',
      ornekTr: 'Son yüz metreyi tam hızla koştu.',
      not: 'Uzun ve tempolu koşu ise "jog"dur.',
    },
    {
      id: 'en-fut-66', on: 'marathon', okunus: 'merıtın', tur: 'isim',
      arka: 'maraton',
      ornek: 'She is training for her first marathon.',
      ornekTr: 'İlk maratonuna hazırlanıyor.',
      not: 'Mecazi kullanımı da vardır: "a marathon meeting" = bitmeyen toplantı.',
    },
    {
      id: 'en-fut-67', on: 'referee vs umpire', okunus: 'referi vörsıs ampayır', tur: 'ayrım',
      arka: 'hakem (futbol) / hakem (tenis, kriket)',
      ornek: 'A football match has a referee; a tennis match has an umpire.',
      ornekTr: 'Futbolda "referee", teniste "umpire" vardır.',
      not: 'Sınavda ikisi karıştırılarak sorulur. Futbol = referee.',
    },
    {
      id: 'en-fut-68', on: 'take part in', okunus: 'teyk part in', tur: 'öbek fiil',
      arka: 'katılmak (bir etkinliğe)',
      ornek: 'Forty schools took part in the tournament.',
      ornekTr: 'Turnuvaya kırk okul katıldı.',
      not: '"Attend" bir yerde bulunmak, "take part in" ise etkin katılmaktır.',
    },
    {
      id: 'en-fut-69', on: 'break a record', okunus: 'breyk ı rekord', tur: 'eş dizim',
      arka: 'rekor kırmak',
      ornek: 'She broke the school record last week.',
      ornekTr: 'Geçen hafta okul rekorunu kırdı.',
      not: 'Rekoru elinde tutmak "hold a record"tur.',
    },
    {
      id: 'en-fut-70', on: 'personal best', okunus: 'pörsınıl best', tur: 'isim',
      arka: 'kişisel rekor',
      ornek: 'He ran a personal best in the 800 metres.',
      ornekTr: '800 metrede kişisel rekorunu kırdı.',
      not: 'Kısaltması "PB"dir ve sporcular arasında çok kullanılır.',
    },
    /* --- Antrenman, kondisyon, sakatlık --- */
    {
      id: 'en-fut-71', on: 'work out', okunus: 'vörk aut', tur: 'öbek fiil',
      arka: 'spor yapmak, antrenman yapmak',
      ornek: 'I work out three times a week.',
      ornekTr: 'Haftada üç kez spor yapıyorum.',
      not: 'İsim hâli bitişiktir: "a good workout".',
    },
    {
      id: 'en-fut-72', on: 'warm up', okunus: 'vorm ap', tur: 'öbek fiil',
      arka: 'ısınmak',
      ornek: 'Always warm up before you run.',
      ornekTr: 'Koşmadan önce mutlaka ısın.',
      not: 'Sonrasında soğuma vardır: "cool down".',
    },
    {
      id: 'en-fut-73', on: 'stretch', okunus: 'streç', tur: 'fiil',
      arka: 'esnemek, germe hareketi yapmak',
      ornek: 'Stretch your legs for five minutes.',
      ornekTr: 'Beş dakika bacaklarını ger.',
      not: 'Uyku sonrası "gerinmek" için de aynı fiil kullanılır.',
    },
    {
      id: 'en-fut-74', on: 'be in shape', okunus: 'bi in şeyp', tur: 'kalıp',
      arka: 'formda olmak',
      ornek: 'He is in great shape this season.',
      ornekTr: 'Bu sezon çok formda.',
      not: 'Tersi "be out of shape" = formsuz olmak.',
    },
    {
      id: 'en-fut-75', on: 'stamina', okunus: 'stemını', tur: 'isim',
      arka: 'dayanıklılık',
      ornek: 'Long runs build stamina.',
      ornekTr: 'Uzun koşular dayanıklılık kazandırır.',
      not: 'Sayılamayan bir isimdir: "a stamina" denmez.',
    },
    {
      id: 'en-fut-76', on: 'recover', okunus: 'rikavır', tur: 'fiil',
      arka: 'iyileşmek, toparlanmak',
      ornek: 'He is recovering from an injury.',
      ornekTr: 'Bir sakatlıktan dolayı iyileşme sürecinde.',
      not: 'Edatı "from"dur: recover from something.',
    },
    {
      id: 'en-fut-77', on: 'be out for', okunus: 'bi aut for', tur: 'kalıp',
      arka: 'belirli bir süre sahalardan uzak kalmak',
      ornek: 'He will be out for six weeks.',
      ornekTr: 'Altı hafta sahalardan uzak kalacak.',
      not: 'Süre "for" ile verilir: out for two months.',
    },
    {
      id: 'en-fut-78', on: 'give up', okunus: 'giv ap', tur: 'öbek fiil',
      arka: 'pes etmek, bırakmak',
      ornek: 'Do not give up after one bad match.',
      ornekTr: 'Kötü bir maçtan sonra pes etme.',
      not: 'Bir alışkanlığı bırakmak için de kullanılır: "give up sugar".',
    },
    {
      id: 'en-fut-79', on: 'push yourself', okunus: 'puş yorself', tur: 'kalıp',
      arka: 'kendini zorlamak',
      ornek: 'You have to push yourself in training.',
      ornekTr: 'Antrenmanda kendini zorlaman gerekiyor.',
      not: 'Dönüşlü zamir zorunludur: myself, yourself, himself.',
    },
    {
      id: 'en-fut-80', on: 'keep fit', okunus: 'kiip fit', tur: 'kalıp',
      arka: 'formda kalmak',
      ornek: 'I cycle to school to keep fit.',
      ornekTr: 'Formda kalmak için okula bisikletle gidiyorum.',
      not: '"Get fit" forma girmek, "keep fit" formda kalmaktır.',
    },
    /* --- Spordan doğmuş günlük deyimler --- */
    {
      id: 'en-fut-81', on: 'a level playing field', okunus: 'ı levıl pleying fiild', tur: 'deyim',
      arka: 'herkese eşit şartlar',
      ornek: 'The exam gives everyone a level playing field.',
      ornekTr: 'Sınav herkese eşit şartlar sunuyor.',
      not: 'Sınav okuma metinlerinde adalet konusunda sık geçer.',
    },
    {
      id: 'en-fut-82', on: 'move the goalposts', okunus: 'muv dı goulpousts', tur: 'deyim',
      arka: 'kuralları iş sırasında değiştirmek',
      ornek: 'They moved the goalposts after we started.',
      ornekTr: 'Biz başladıktan sonra kuralları değiştirdiler.',
      not: 'Olumsuz bir eleştiri anlamı taşır.',
    },
    {
      id: 'en-fut-83', on: 'throw in the towel', okunus: 'trou in dı tauıl', tur: 'deyim',
      arka: 'havlu atmak, pes etmek',
      ornek: 'He was tired but he did not throw in the towel.',
      ornekTr: 'Yorgundu ama pes etmedi.',
      not: 'Boks kökenlidir; Türkçedeki "havlu atmak" ile birebir aynıdır.',
    },
    {
      id: 'en-fut-84', on: 'be on the ball', okunus: 'bi on dı bol', tur: 'deyim',
      arka: 'uyanık ve hazırlıklı olmak',
      ornek: 'She is really on the ball in maths lessons.',
      ornekTr: 'Matematik derslerinde gerçekten çok uyanık.',
      not: 'Futboldaki "topla oynamak" anlamıyla karıştırılmamalı.',
    },
    {
      id: 'en-fut-85', on: 'a game changer', okunus: 'ı geym çeyncır', tur: 'deyim',
      arka: 'her şeyi değiştiren gelişme',
      ornek: 'The new app was a game changer for students.',
      ornekTr: 'Yeni uygulama öğrenciler için her şeyi değiştirdi.',
      not: 'Teknoloji ve iş metinlerinde çok sık kullanılır.',
    },
    {
      id: 'en-fut-86', on: 'out of my league', okunus: 'aut ıv may liig', tur: 'deyim',
      arka: 'benim seviyemin üstünde',
      ornek: 'That competition is out of my league.',
      ornekTr: 'O yarışma benim seviyemin üstünde.',
      not: 'İyimser değil, alçakgönüllü ya da çekingen bir ifadedir.',
    },
    {
      id: 'en-fut-87', on: 'get the ball rolling', okunus: 'get dı bol rouling', tur: 'deyim',
      arka: 'işi başlatmak',
      ornek: 'Let us get the ball rolling with a short question.',
      ornekTr: 'Kısa bir soruyla işi başlatalım.',
      not: 'Toplantı ve proje başlangıcında kullanılır.',
    },
    {
      id: 'en-fut-88', on: 'neck and neck', okunus: 'nek end nek', tur: 'deyim',
      arka: 'başa baş',
      ornek: 'The two teams are neck and neck at the top.',
      ornekTr: 'İki takım zirvede başa baş gidiyor.',
      not: 'At yarışı kökenlidir; yarış ve seçim haberlerinde geçer.',
    },
    {
      id: 'en-fut-89', on: 'raise the bar', okunus: 'reyz dı bar', tur: 'deyim',
      arka: 'çıtayı yükseltmek',
      ornek: 'Their new album raised the bar.',
      ornekTr: 'Yeni albümleri çıtayı yükseltti.',
      not: 'Yüksek atlama kökenlidir, Türkçesiyle birebir örtüşür.',
    },
    {
      id: 'en-fut-90', on: 'root for', okunus: 'ruut for', tur: 'öbek fiil',
      arka: 'birini tutmak, desteklemek',
      ornek: 'I am rooting for you in the final.',
      ornekTr: 'Finalde seni tutuyorum.',
      not: 'Amerikan İngilizcesinde çok yaygındır; "support" ile eşanlamlıdır.',
    },
    /* --- Maç anlatımı ve yorum dili --- */
    {
      id: 'en-fut-91', on: 'thrilling', okunus: 'triling', tur: 'sıfat',
      arka: 'heyecan verici',
      ornek: 'It was a thrilling match from start to finish.',
      ornekTr: 'Baştan sona heyecan verici bir maçtı.',
      not: 'Kişi için "thrilled" (heyecanlanmış) kullanılır. -ing nesne, -ed kişi.',
    },
    {
      id: 'en-fut-92', on: 'dull', okunus: 'dal', tur: 'sıfat',
      arka: 'sıkıcı, tatsız',
      ornek: 'The first half was really dull.',
      ornekTr: 'İlk yarı gerçekten sıkıcıydı.',
      not: '"Boring" ile eşanlamlıdır ama yazıda daha ağır durur.',
    },
    {
      id: 'en-fut-93', on: 'deserve to win', okunus: 'dizörv tu vin', tur: 'eş dizim',
      arka: 'kazanmayı hak etmek',
      ornek: 'They deserved to win the match.',
      ornekTr: 'Maçı kazanmayı hak ettiler.',
      not: 'Sonrasında "to + fiil" gelir: deserve to win, deserve to know.',
    },
    {
      id: 'en-fut-94', on: 'dominate', okunus: 'domineyt', tur: 'fiil',
      arka: 'oyuna hâkim olmak',
      ornek: 'We dominated the second half.',
      ornekTr: 'İkinci yarıya hâkim olduk.',
      not: 'İsmi "domination", sıfatı "dominant"tır.',
    },
    {
      id: 'en-fut-95', on: 'possession', okunus: 'pızeşın', tur: 'isim',
      arka: 'topa sahip olma oranı',
      ornek: 'They had 60% possession.',
      ornekTr: 'Topa sahip olma oranları yüzde 60\'tı.',
      not: 'Aynı kelime "sahip olunan eşya" anlamına da gelir.',
    },
    {
      id: 'en-fut-96', on: 'narrow win', okunus: 'nerou vin', tur: 'eş dizim',
      arka: 'kıl payı galibiyet',
      ornek: 'It was a narrow win, just 1-0.',
      ornekTr: 'Kıl payı bir galibiyetti, sadece 1-0.',
      not: 'Tersi "a comfortable win" = rahat galibiyet.',
    },
    {
      id: 'en-fut-97', on: 'thrash', okunus: 'treş', tur: 'fiil',
      arka: 'farklı skorla yenmek',
      ornek: 'They thrashed us 5-0.',
      ornekTr: 'Bizi 5-0 dağıttılar.',
      not: 'Gazete başlıklarında çok kullanılır; günlük konuşmada serttir.',
    },
    {
      id: 'en-fut-98', on: 'unbeaten', okunus: 'anbiitın', tur: 'sıfat',
      arka: 'yenilmemiş',
      ornek: 'They are still unbeaten this season.',
      ornekTr: 'Bu sezon hâlâ yenilmediler.',
      not: '"Undefeated" ile aynıdır; ikisi de "beat/defeat" fiilinden gelir.',
    },
    {
      id: 'en-fut-99', on: 'sportsmanship', okunus: 'sportsmınşip', tur: 'isim',
      arka: 'sportmenlik',
      ornek: 'He showed great sportsmanship after losing.',
      ornekTr: 'Yenildikten sonra büyük bir sportmenlik gösterdi.',
      not: '-ship eki "hâl, durum" katar: friendship, leadership, sportsmanship.',
    },
    {
      id: 'en-fut-100', on: 'take it seriously', okunus: 'teyk it siriıusli', tur: 'kalıp',
      arka: 'ciddiye almak',
      ornek: 'He takes his training very seriously.',
      ornekTr: 'Antrenmanını çok ciddiye alıyor.',
      not: 'Nesne araya girer: take it seriously, take the exam seriously.',
    },
  ],
}

export default DESTE
