/**
 * DESTE — GÜNLÜK KONUŞMA (İngilizce)
 *
 * Ders kitabı İngilizcesi ile konuşulan İngilizce arasındaki fark bu
 * destededir. Öğrenci "How are you?" öğrenir ama karşısındaki "What have
 * you been up to?" der ve donar. Kartlar tam olarak o boşluğu hedefler.
 */

export const DESTE = {
  id: 'gunluk-konusma',
  dil: 'en',
  ad: 'Günlük konuşma',
  simge: '💬',
  aciklama: 'Kitapların yazmadığı, anadili konuşanların sürekli kullandığı kalıplar.',
  seviye: 'B1',
  kartlar: [
    {
      id: 'en-gun-01', on: 'What have you been up to?', okunus: 'vot hev yu bin ap tu', tur: 'kalıp',
      arka: 'Neler yapıyordun? Ne var ne yok?',
      ornek: 'Hey, long time no see! What have you been up to?',
      ornekTr: 'Selam, görüşmeyeli çok oldu! Ne var ne yok?',
      not: '"How are you"dan çok daha doğal bir açılış.',
    },
    {
      id: 'en-gun-02', on: 'never mind', okunus: 'nevır maynd', tur: 'kalıp',
      arka: 'boş ver, önemli değil',
      ornek: 'Never mind, I will do it myself.',
      ornekTr: 'Boş ver, ben kendim yaparım.',
      not: 'İki kelime yazılır. "Nevermind" yaygın bir yazım hatasıdır.',
    },
    {
      id: 'en-gun-03', on: 'no worries', okunus: 'nou vöriz', tur: 'kalıp',
      arka: 'sorun değil, önemli değil',
      ornek: 'You are late? No worries, we just started.',
      ornekTr: 'Geç mi kaldın? Sorun değil, daha yeni başladık.',
      not: 'Teşekküre cevap olarak da kullanılır: "Thanks!" — "No worries."',
    },
    {
      id: 'en-gun-04', on: 'I am not sure', okunus: 'ay em not şur', tur: 'kalıp',
      arka: 'emin değilim',
      ornek: 'I am not sure, let me check.',
      ornekTr: 'Emin değilim, bir bakayım.',
      not: 'Bilmediğini söylemenin en kibar yolu; "I do not know" biraz sert durur.',
    },
    {
      id: 'en-gun-05', on: 'kind of', okunus: 'kaynd ıv', tur: 'kalıp',
      arka: 'biraz, bir bakıma',
      ornek: 'I kind of like it, but not really.',
      ornekTr: 'Bir bakıma hoşuma gidiyor ama tam olarak değil.',
      not: 'Konuşmada "kinda" diye kısaltılır. Yazıda kısaltılmaz.',
    },
    {
      id: 'en-gun-06', on: 'to be honest', okunus: 'tu bi onıst', tur: 'kalıp',
      arka: 'açıkçası, dürüst olmak gerekirse',
      ornek: 'To be honest, I did not like the ending.',
      ornekTr: 'Açıkçası sonu hoşuma gitmedi.',
      not: 'Kısaltması "TBH" olarak yazışmalarda çok kullanılır.',
    },
    {
      id: 'en-gun-07', on: 'I feel like', okunus: 'ay fiil layk', tur: 'kalıp',
      arka: 'canım … istiyor',
      ornek: 'I feel like watching a film tonight.',
      ornekTr: 'Bu akşam canım film izlemek istiyor.',
      not: 'Ardından fiil gelirse -ing alır: feel like WATCHING.',
    },
    {
      id: 'en-gun-08', on: 'make sense', okunus: 'meyk sens', tur: 'eş dizim',
      arka: 'mantıklı olmak, anlaşılır olmak',
      ornek: 'That does not make sense to me.',
      ornekTr: 'Bu bana mantıklı gelmiyor.',
      not: '"do sense" ya da "have sense" YANLIŞTIR; fiil "make"tir.',
    },
    {
      id: 'en-gun-09', on: 'by the way', okunus: 'bay dı vey', tur: 'kalıp',
      arka: 'bu arada, aklıma gelmişken',
      ornek: 'By the way, did you finish the homework?',
      ornekTr: 'Bu arada, ödevi bitirdin mi?',
      not: 'Yazışmada "BTW" diye kısaltılır.',
    },
    {
      id: 'en-gun-10', on: 'fair enough', okunus: 'feır inaf', tur: 'kalıp',
      arka: 'haklısın, olur, kabul',
      ornek: 'You are tired? Fair enough, we can go home.',
      ornekTr: 'Yorgun musun? Haklısın, eve gidebiliriz.',
      not: 'Karşı tarafın gerekçesini kabul ettiğini gösterir.',
    },
    /* --- Selamlaşma ve küçük sohbet --- */
    {
      id: 'en-gun-11', on: 'How is it going?', okunus: 'hau iz it gouing', tur: 'kalıp',
      arka: 'Nasıl gidiyor?',
      ornek: 'Hey, how is it going?',
      ornekTr: 'Selam, nasıl gidiyor?',
      not: 'Cevabı "Not bad" ya da "Pretty good" olabilir.',
    },
    {
      id: 'en-gun-12', on: 'Long time no see', okunus: 'long taym nou sii', tur: 'kalıp',
      arka: 'Görüşmeyeli çok oldu',
      ornek: 'Long time no see! How have you been?',
      ornekTr: 'Görüşmeyeli çok oldu! Nasılsın?',
      not: 'Dil bilgisi kuralına uymaz ama tamamen doğal bir kalıptır.',
    },
    {
      id: 'en-gun-13', on: 'What have you been up to?', okunus: 'vot hev yu bin ap tu', tur: 'kalıp',
      arka: 'Neler yapıyorsun son zamanlarda?',
      ornek: 'What have you been up to lately?',
      ornekTr: 'Son zamanlarda neler yapıyorsun?',
      not: 'Yakın geçmişi sorar; cevabı da present perfect ile verilir.',
    },
    {
      id: 'en-gun-14', on: 'Not much', okunus: 'not maç', tur: 'kalıp',
      arka: 'Pek bir şey yok',
      ornek: 'What is new? - Not much.',
      ornekTr: 'Ne var ne yok? - Pek bir şey yok.',
      not: 'Yukarıdaki sorunun en yaygın cevabıdır.',
    },
    {
      id: 'en-gun-15', on: 'Take care', okunus: 'teyk keır', tur: 'kalıp',
      arka: 'Kendine iyi bak',
      ornek: 'See you tomorrow, take care!',
      ornekTr: 'Yarın görüşürüz, kendine iyi bak!',
      not: 'Vedalaşmanın sıcak ve doğal biçimidir.',
    },
    {
      id: 'en-gun-16', on: 'Catch you later', okunus: 'keç yu leytır', tur: 'kalıp',
      arka: 'Sonra görüşürüz',
      ornek: 'I have to run. Catch you later!',
      ornekTr: 'Kaçmam lazım. Sonra görüşürüz!',
      not: 'Gündelik ve samimidir; resmî ortamda kullanılmaz.',
    },
    {
      id: 'en-gun-17', on: 'It has been ages', okunus: 'its bin eyciz', tur: 'kalıp',
      arka: 'Çok uzun zaman oldu',
      ornek: 'It has been ages since we met.',
      ornekTr: 'Görüşmeyeli çok uzun zaman oldu.',
      not: '"Ages" abartma amacıyla kullanılır: yıllar anlamında.',
    },
    {
      id: 'en-gun-18', on: 'How are things?', okunus: 'hau ar tingz', tur: 'kalıp',
      arka: 'İşler nasıl?',
      ornek: 'How are things at school?',
      ornekTr: 'Okulda işler nasıl?',
      not: '"How are you?" ile aynı işlevdedir ama daha doğaldır.',
    },
    {
      id: 'en-gun-19', on: 'Say hi to...', okunus: 'sey hay tu', tur: 'kalıp',
      arka: '... selam söyle',
      ornek: 'Say hi to your brother for me.',
      ornekTr: 'Kardeşine benden selam söyle.',
      not: '"For me" eklemek daha samimi yapar.',
    },
    {
      id: 'en-gun-20', on: 'nice to see you again', okunus: 'nays tu sii yu ıgen', tur: 'kalıp',
      arka: 'Seni tekrar görmek güzel',
      ornek: 'Nice to see you again after all this time.',
      ornekTr: 'Bunca zamandan sonra seni tekrar görmek güzel.',
      not: 'İlk tanışmada "nice to meet you" denir; ikisi karıştırılır.',
    },
    /* --- Fikir belirtmek --- */
    {
      id: 'en-gun-21', on: 'If you ask me', okunus: 'if yu ask mi', tur: 'kalıp',
      arka: 'Bana sorarsan',
      ornek: 'If you ask me, it is too expensive.',
      ornekTr: 'Bana sorarsan çok pahalı.',
      not: 'Fikri yumuşatarak sunar.',
    },
    {
      id: 'en-gun-22', on: 'The way I see it', okunus: 'dı vey ay sii it', tur: 'kalıp',
      arka: 'Benim görüşüme göre',
      ornek: 'The way I see it, we have no choice.',
      ornekTr: 'Benim görüşüme göre başka seçeneğimiz yok.',
      not: 'Yazma bölümünde "In my opinion" tekrarından kurtarır.',
    },
    {
      id: 'en-gun-23', on: 'I reckon', okunus: 'ay rekın', tur: 'kalıp',
      arka: 'Bence, sanırım',
      ornek: 'I reckon it will rain later.',
      ornekTr: 'Bence sonra yağmur yağacak.',
      not: 'İngiliz İngilizcesinde çok yaygın, gündelik bir ifadedir.',
    },
    {
      id: 'en-gun-24', on: 'To be honest', okunus: 'tu bi onıst', tur: 'kalıp',
      arka: 'Açıkçası',
      ornek: 'To be honest, I did not like it.',
      ornekTr: 'Açıkçası beğenmedim.',
      not: 'Kısaltması "TBH"dir ve mesajlaşmada kullanılır.',
    },
    {
      id: 'en-gun-25', on: 'It seems to me', okunus: 'it siimz tu mi', tur: 'kalıp',
      arka: 'Bana öyle geliyor ki',
      ornek: 'It seems to me that he is tired.',
      ornekTr: 'Bana öyle geliyor ki yorgun.',
      not: 'Kesin konuşmadan fikir sunmanın kibar yoludur.',
    },
    {
      id: 'en-gun-26', on: 'I could not agree more', okunus: 'ay kud not ıgrii mor', tur: 'kalıp',
      arka: 'Kesinlikle katılıyorum',
      ornek: 'I could not agree more with you.',
      ornekTr: 'Sana kesinlikle katılıyorum.',
      not: 'Olumsuz görünse de en güçlü katılma ifadesidir.',
    },
    {
      id: 'en-gun-27', on: 'I see your point, but...', okunus: 'ay sii yor poynt bat', tur: 'kalıp',
      arka: 'Ne demek istediğini anlıyorum ama...',
      ornek: 'I see your point, but I still disagree.',
      ornekTr: 'Ne demek istediğini anlıyorum ama yine de katılmıyorum.',
      not: 'Karşı çıkarken nezaketi korur; tartışma dilinin temelidir.',
    },
    {
      id: 'en-gun-28', on: 'Fair enough', okunus: 'feır inaf', tur: 'kalıp',
      arka: 'Anlaşılır, kabul',
      ornek: 'Fair enough, we will do it your way.',
      ornekTr: 'Kabul, senin dediğin gibi yapalım.',
      not: 'Tam katılmasan da karşıdakini haklı bulmayı anlatır.',
    },
    {
      id: 'en-gun-29', on: 'It depends', okunus: 'it dipendz', tur: 'kalıp',
      arka: 'Duruma göre değişir',
      ornek: 'It depends on how much time we have.',
      ornekTr: 'Ne kadar vaktimiz olduğuna bağlı.',
      not: 'Edatı "on"dur ve düşmez.',
    },
    {
      id: 'en-gun-30', on: 'I am not so sure about that', okunus: 'ay em not sou şuır ıbaut det', tur: 'kalıp',
      arka: 'Bundan pek emin değilim',
      ornek: 'I am not so sure about that idea.',
      ornekTr: 'O fikirden pek emin değilim.',
      not: 'Kibarca karşı çıkmanın en güvenli yoludur.',
    },
    /* --- Rica ve izin --- */
    {
      id: 'en-gun-31', on: 'Would you mind...?', okunus: 'vud yu maynd', tur: 'soru kalıbı',
      arka: 'Sakıncası var mı?',
      ornek: 'Would you mind opening the window?',
      ornekTr: 'Pencereyi açmanızın sakıncası var mı?',
      not: 'Sonrasında -ing gelir. Olumlu cevap "Not at all"dur.',
    },
    {
      id: 'en-gun-32', on: 'Do you mind if I...?', okunus: 'du yu maynd if ay', tur: 'soru kalıbı',
      arka: '... yapsam sorun olur mu?',
      ornek: 'Do you mind if I sit here?',
      ornekTr: 'Buraya otursam sorun olur mu?',
      not: 'Bu kalıpta -ing değil, yalın fiil gelir.',
    },
    {
      id: 'en-gun-33', on: 'Could you possibly...?', okunus: 'kud yu posıbli', tur: 'soru kalıbı',
      arka: 'Acaba ... yapabilir misiniz?',
      ornek: 'Could you possibly help me with this?',
      ornekTr: 'Acaba bu konuda bana yardım edebilir misiniz?',
      not: '"Possibly" ricayı daha da kibarlaştırır.',
    },
    {
      id: 'en-gun-34', on: 'Is it OK if I...?', okunus: 'iz it oukey if ay', tur: 'soru kalıbı',
      arka: '... yapmam sorun olur mu?',
      ornek: 'Is it OK if I call you later?',
      ornekTr: 'Seni sonra arasam sorun olur mu?',
      not: 'Gündelik ve rahat bir izin isteme biçimidir.',
    },
    {
      id: 'en-gun-35', on: 'Go ahead', okunus: 'gou ıhed', tur: 'kalıp',
      arka: 'Buyur, tabii ki',
      ornek: 'Can I borrow your pen? - Go ahead.',
      ornekTr: 'Kalemini alabilir miyim? - Buyur.',
      not: 'İzin vermenin en doğal karşılığıdır.',
    },
    {
      id: 'en-gun-36', on: 'No problem', okunus: 'nou problım', tur: 'kalıp',
      arka: 'Sorun değil',
      ornek: 'Thanks for waiting. - No problem.',
      ornekTr: 'Beklediğin için teşekkürler. - Sorun değil.',
      not: 'Hem teşekküre hem özre cevap olur.',
    },
    {
      id: 'en-gun-37', on: 'I would rather not', okunus: 'ay vud radır not', tur: 'kalıp',
      arka: 'Tercihen yapmasam',
      ornek: 'I would rather not talk about it.',
      ornekTr: 'Bu konuda konuşmasam daha iyi.',
      not: '"Would rather" sonrası yalın fiil gelir, "to" almaz.',
    },
    {
      id: 'en-gun-38', on: 'Sorry to bother you', okunus: 'sori tu bodır yu', tur: 'kalıp',
      arka: 'Rahatsız ettiğim için özür dilerim',
      ornek: 'Sorry to bother you, but I have a question.',
      ornekTr: 'Rahatsız ettiğim için özür dilerim ama bir sorum var.',
      not: 'Öğretmene ya da yabancıya yaklaşırken idealdir.',
    },
    {
      id: 'en-gun-39', on: 'Could you do me a favour?', okunus: 'kud yu du mi ı feyvır', tur: 'kalıp',
      arka: 'Bir iyilik yapar mısın?',
      ornek: 'Could you do me a favour and hold this?',
      ornekTr: 'Bir iyilik yapıp bunu tutar mısın?',
      not: 'Amerika\'da "favor" yazılır.',
    },
    {
      id: 'en-gun-40', on: 'Feel free to...', okunus: 'fiil frii tu', tur: 'kalıp',
      arka: 'Çekinmeden ... yapabilirsin',
      ornek: 'Feel free to ask any question.',
      ornekTr: 'Çekinmeden her soruyu sorabilirsin.',
      not: 'Karşıdakini rahatlatan sıcak bir davettir.',
    },
    /* --- Teklif ve öneri --- */
    {
      id: 'en-gun-41', on: 'Why do not we...?', okunus: 'vay dount vi', tur: 'soru kalıbı',
      arka: 'Neden ... yapmıyoruz?',
      ornek: 'Why do not we meet at six?',
      ornekTr: 'Neden altıda buluşmuyoruz?',
      not: 'Öneri sunar; sonrasında yalın fiil gelir.',
    },
    {
      id: 'en-gun-42', on: 'How about...?', okunus: 'hau ıbaut', tur: 'soru kalıbı',
      arka: '... nasıl olur?',
      ornek: 'How about going to the cinema?',
      ornekTr: 'Sinemaya gitmeye ne dersin?',
      not: 'Sonrasında -ing ya da isim gelir, yalın fiil gelmez.',
    },
    {
      id: 'en-gun-43', on: 'Shall we...?', okunus: 'şel vi', tur: 'soru kalıbı',
      arka: '... yapalım mı?',
      ornek: 'Shall we start now?',
      ornekTr: 'Şimdi başlayalım mı?',
      not: 'İngiliz İngilizcesine özgü kibar bir teklif kalıbıdır.',
    },
    {
      id: 'en-gun-44', on: 'Let us say...', okunus: 'lets sey', tur: 'kalıp',
      arka: 'Diyelim ki, mesela',
      ornek: 'Let us say seven o\'clock, then.',
      ornekTr: 'O zaman diyelim ki saat yedi.',
      not: 'Bir teklifi kesinleştirirken kullanılır.',
    },
    {
      id: 'en-gun-45', on: 'That sounds great', okunus: 'det saundz greyt', tur: 'kalıp',
      arka: 'Kulağa harika geliyor',
      ornek: 'Pizza tonight? - That sounds great.',
      ornekTr: 'Bu akşam pizza? - Kulağa harika geliyor.',
      not: 'Teklifi kabul etmenin en doğal yoludur.',
    },
    {
      id: 'en-gun-46', on: 'I am up for it', okunus: 'ay em ap for it', tur: 'kalıp',
      arka: 'Ben varım',
      ornek: 'A walk after dinner? I am up for it.',
      ornekTr: 'Yemekten sonra yürüyüş? Ben varım.',
      not: '"Be up for" bir şeye istekli olmayı anlatır.',
    },
    {
      id: 'en-gun-47', on: 'Maybe another time', okunus: 'meybi ınadır taym', tur: 'kalıp',
      arka: 'Belki başka zaman',
      ornek: 'I cannot today, maybe another time.',
      ornekTr: 'Bugün olmaz, belki başka zaman.',
      not: 'Kibarca reddetmenin standart yoludur.',
    },
    {
      id: 'en-gun-48', on: 'I will pass', okunus: 'ayl pas', tur: 'kalıp',
      arka: 'Ben almayayım, pas geçeyim',
      ornek: 'Coffee? - I will pass, thanks.',
      ornekTr: 'Kahve? - Ben almayayım, sağ ol.',
      not: 'Kısa ve nazik bir ret ifadesidir.',
    },
    {
      id: 'en-gun-49', on: 'Count me in', okunus: 'kaunt mi in', tur: 'kalıp',
      arka: 'Beni de yaz, ben de varım',
      ornek: 'We are going to the match. - Count me in!',
      ornekTr: 'Maça gidiyoruz. - Beni de yaz!',
      not: 'Tersi "count me out" = beni karıştırma.',
    },
    {
      id: 'en-gun-50', on: 'It is up to you', okunus: 'its ap tu yu', tur: 'kalıp',
      arka: 'Sana kalmış',
      ornek: 'Cinema or park? - It is up to you.',
      ornekTr: 'Sinema mı park mı? - Sana kalmış.',
      not: 'Kararı karşı tarafa bırakır.',
    },
    /* --- Duyguları anlatmak --- */
    {
      id: 'en-gun-51', on: 'I am over the moon', okunus: 'ay em ouvır dı muun', tur: 'deyim',
      arka: 'Çok mutluyum',
      ornek: 'She was over the moon about the result.',
      ornekTr: 'Sonuca çok sevindi.',
      not: 'Mutluluğun en güçlü deyimsel anlatımıdır.',
    },
    {
      id: 'en-gun-52', on: 'I am gutted', okunus: 'ay em gatıd', tur: 'kalıp',
      arka: 'Çok üzgünüm, yıkıldım',
      ornek: 'I was gutted when we lost.',
      ornekTr: 'Kaybettiğimizde yıkıldım.',
      not: 'İngiliz İngilizcesine özgü güçlü bir üzüntü ifadesidir.',
    },
    {
      id: 'en-gun-53', on: 'be fed up with', okunus: 'bi fed ap vit', tur: 'kalıp',
      arka: 'bıkmak, usanmak',
      ornek: 'I am fed up with this weather.',
      ornekTr: 'Bu havadan bıktım.',
      not: 'Edatı "with"tir ve sonrasında isim ya da -ing gelir.',
    },
    {
      id: 'en-gun-54', on: 'be stressed out', okunus: 'bi stresd aut', tur: 'kalıp',
      arka: 'çok stresli olmak',
      ornek: 'She is stressed out about the exam.',
      ornekTr: 'Sınav yüzünden çok stresli.',
      not: 'Konu edatı "about"tur.',
    },
    {
      id: 'en-gun-55', on: 'cheer up', okunus: 'çir ap', tur: 'öbek fiil',
      arka: 'neşelenmek, neşelendirmek',
      ornek: 'Cheer up, it is not the end of the world.',
      ornekTr: 'Neşelen, dünyanın sonu değil.',
      not: 'Hem emir hem geçişli fiil olarak kullanılır: "cheer him up".',
    },
    {
      id: 'en-gun-56', on: 'calm down', okunus: 'kam daun', tur: 'öbek fiil',
      arka: 'sakinleşmek',
      ornek: 'Calm down and tell me what happened.',
      ornekTr: 'Sakinleş ve ne olduğunu anlat.',
      not: '"Calm" içindeki "l" okunmaz.',
    },
    {
      id: 'en-gun-57', on: 'get on my nerves', okunus: 'get on may nörvz', tur: 'deyim',
      arka: 'sinirime dokunmak',
      ornek: 'That sound gets on my nerves.',
      ornekTr: 'O ses sinirime dokunuyor.',
      not: 'Öznesi rahatsız eden şeydir, kişi değil.',
    },
    {
      id: 'en-gun-58', on: 'I cannot be bothered', okunus: 'ay kant bi bodırd', tur: 'kalıp',
      arka: 'Canım istemiyor, üşeniyorum',
      ornek: 'I cannot be bothered to cook tonight.',
      ornekTr: 'Bu akşam yemek yapmaya üşeniyorum.',
      not: 'Çok yaygın bir İngiliz konuşma kalıbıdır.',
    },
    {
      id: 'en-gun-59', on: 'to be relieved', okunus: 'tu bi riliivd', tur: 'sıfat',
      arka: 'içi rahatlamış',
      ornek: 'I was relieved when I saw my results.',
      ornekTr: 'Sonuçlarımı görünce içim rahatladı.',
      not: 'Endişenin bitmesini anlatır; mutluluktan farklıdır.',
    },
    {
      id: 'en-gun-60', on: 'I feel like...', okunus: 'ay fiil layk', tur: 'kalıp',
      arka: 'Canım ... istiyor',
      ornek: 'I feel like going for a walk.',
      ornekTr: 'Canım yürüyüşe çıkmak istiyor.',
      not: 'Sonrasında -ing gelir; "feel like to go" YANLIŞTIR.',
    },
    /* --- Şaşırma ve tepki --- */
    {
      id: 'en-gun-61', on: 'No way!', okunus: 'nou vey', tur: 'ünlem',
      arka: 'Olamaz! / Asla!',
      ornek: 'You won? No way!',
      ornekTr: 'Kazandın mı? Olamaz!',
      not: 'Hem şaşkınlık hem kesin ret anlatır; ton belirler.',
    },
    {
      id: 'en-gun-62', on: 'You are kidding!', okunus: 'yor kiding', tur: 'ünlem',
      arka: 'Şaka yapıyorsun!',
      ornek: 'You are kidding! That is amazing.',
      ornekTr: 'Şaka yapıyorsun! Bu harika.',
      not: '"Kid" fiil olarak "şaka yapmak" demektir.',
    },
    {
      id: 'en-gun-63', on: 'That is a shame', okunus: 'dets ı şeym', tur: 'kalıp',
      arka: 'Çok yazık',
      ornek: 'You cannot come? That is a shame.',
      ornekTr: 'Gelemiyor musun? Çok yazık.',
      not: 'Utanma anlamı taşımaz, üzüntü bildirir.',
    },
    {
      id: 'en-gun-64', on: 'Never mind', okunus: 'nevır maynd', tur: 'kalıp',
      arka: 'Boş ver, önemli değil',
      ornek: 'I forgot the book. - Never mind.',
      ornekTr: 'Kitabı unuttum. - Boş ver.',
      not: 'Hem teselli hem konuyu kapatma işlevi görür.',
    },
    {
      id: 'en-gun-65', on: 'Good for you!', okunus: 'gud for yu', tur: 'kalıp',
      arka: 'Aferin sana!',
      ornek: 'You passed? Good for you!',
      ornekTr: 'Geçtin mi? Aferin sana!',
      not: 'Samimi bir tebrik ifadesidir.',
    },
    {
      id: 'en-gun-66', on: 'Well done', okunus: 'vel dan', tur: 'kalıp',
      arka: 'Tebrikler, iyi iş',
      ornek: 'Well done on your presentation.',
      ornekTr: 'Sunumun için tebrikler.',
      not: 'Etin pişme derecesi için de aynı ifade kullanılır.',
    },
    {
      id: 'en-gun-67', on: 'Guess what!', okunus: 'ges vot', tur: 'kalıp',
      arka: 'Bil bakalım ne oldu!',
      ornek: 'Guess what! I got the job.',
      ornekTr: 'Bil bakalım ne oldu! İşi aldım.',
      not: 'Haber vermeden önce merak uyandırır.',
    },
    {
      id: 'en-gun-68', on: 'Are you serious?', okunus: 'ar yu siriıs', tur: 'kalıp',
      arka: 'Ciddi misin?',
      ornek: 'Are you serious about moving?',
      ornekTr: 'Taşınma konusunda ciddi misin?',
      not: 'Edatı "about"tur.',
    },
    {
      id: 'en-gun-69', on: 'I had no idea', okunus: 'ay hed nou aydiı', tur: 'kalıp',
      arka: 'Hiç haberim yoktu',
      ornek: 'I had no idea you played the piano.',
      ornekTr: 'Piyano çaldığından hiç haberim yoktu.',
      not: '"I did not know" ile aynı ama daha vurguludur.',
    },
    {
      id: 'en-gun-70', on: 'That makes sense', okunus: 'det meyks sens', tur: 'kalıp',
      arka: 'Mantıklı',
      ornek: 'Ah, that makes sense now.',
      ornekTr: 'Ha, şimdi mantıklı geldi.',
      not: '"Make sense" öznesi açıklamadır, kişi değildir.',
    },
    /* --- Telefon ve mesajlaşma --- */
    {
      id: 'en-gun-71', on: 'Hold on a second', okunus: 'hould on ı sekınd', tur: 'kalıp',
      arka: 'Bir saniye bekle',
      ornek: 'Hold on a second, I will check.',
      ornekTr: 'Bir saniye bekle, kontrol edeceğim.',
      not: 'Telefonda "hold the line" da denir.',
    },
    {
      id: 'en-gun-72', on: 'Can I call you back?', okunus: 'ken ay kol yu bek', tur: 'kalıp',
      arka: 'Seni geri arayabilir miyim?',
      ornek: 'I am busy now, can I call you back?',
      ornekTr: 'Şu an meşgulüm, seni geri arayabilir miyim?',
      not: '"Call back" tek bir öbek fiildir.',
    },
    {
      id: 'en-gun-73', on: 'You are breaking up', okunus: 'yor breyking ap', tur: 'kalıp',
      arka: 'Sesin kesiliyor',
      ornek: 'Sorry, you are breaking up. Can you repeat?',
      ornekTr: 'Pardon, sesin kesiliyor. Tekrar eder misin?',
      not: 'Aynı öbek "ayrılmak" anlamına da gelir.',
    },
    {
      id: 'en-gun-74', on: 'text someone', okunus: 'tekst samvan', tur: 'fiil',
      arka: 'birine mesaj atmak',
      ornek: 'Text me when you get home.',
      ornekTr: 'Eve varınca bana mesaj at.',
      not: 'İsim de fiil de aynıdır: "send a text" veya "text me".',
    },
    {
      id: 'en-gun-75', on: 'get back to someone', okunus: 'get bek tu samvan', tur: 'öbek fiil',
      arka: 'birine geri dönüş yapmak',
      ornek: 'I will get back to you tomorrow.',
      ornekTr: 'Yarın sana dönüş yapacağım.',
      not: 'İş yazışmalarında en sık kullanılan öbeklerdendir.',
    },
    {
      id: 'en-gun-76', on: 'hang up', okunus: 'heng ap', tur: 'öbek fiil',
      arka: 'telefonu kapatmak',
      ornek: 'Do not hang up, I am still talking.',
      ornekTr: 'Kapatma, hâlâ konuşuyorum.',
      not: 'Yüzüne kapatmak "hang up on someone"dır.',
    },
    {
      id: 'en-gun-77', on: 'leave a message', okunus: 'liiv ı mesıc', tur: 'eş dizim',
      arka: 'mesaj bırakmak',
      ornek: 'She left a message on my phone.',
      ornekTr: 'Telefonuma mesaj bıraktı.',
      not: 'Fiili "leave"dir: "put a message" denmez.',
    },
    {
      id: 'en-gun-78', on: 'be on the phone', okunus: 'bi on dı foun', tur: 'kalıp',
      arka: 'telefonda olmak',
      ornek: 'She is on the phone right now.',
      ornekTr: 'Şu an telefonda.',
      not: 'Edatı "on"dur: "in the phone" YANLIŞTIR.',
    },
    {
      id: 'en-gun-79', on: 'speak up', okunus: 'spiik ap', tur: 'öbek fiil',
      arka: 'daha yüksek sesle konuşmak',
      ornek: 'Could you speak up, please?',
      ornekTr: 'Biraz daha yüksek sesle konuşur musunuz?',
      not: 'Aynı öbek "sesini yükseltmek, itiraz etmek" anlamına da gelir.',
    },
    {
      id: 'en-gun-80', on: 'I will let you know', okunus: 'ayl let yu nou', tur: 'kalıp',
      arka: 'Sana haber veririm',
      ornek: 'I will let you know as soon as I hear.',
      ornekTr: 'Haber alır almaz sana bildiririm.',
      not: '"Let someone know" haber vermenin en doğal yoludur.',
    },
    /* --- Konuşma akışını yönetmek --- */
    {
      id: 'en-gun-81', on: 'By the way', okunus: 'bay dı vey', tur: 'kalıp',
      arka: 'Bu arada, aklıma gelmişken',
      ornek: 'By the way, did you finish the book?',
      ornekTr: 'Bu arada, kitabı bitirdin mi?',
      not: 'Kısaltması "BTW"dir.',
    },
    {
      id: 'en-gun-82', on: 'Anyway', okunus: 'eniwey', tur: 'bağlaç',
      arka: 'Her neyse',
      ornek: 'Anyway, let us go back to the topic.',
      ornekTr: 'Her neyse, konuya dönelim.',
      not: 'Konuyu toparlayıp asıl noktaya dönmek için kullanılır.',
    },
    {
      id: 'en-gun-83', on: 'Actually', okunus: 'ekçuıli', tur: 'zarf',
      arka: 'Aslında',
      ornek: 'Actually, I have already read it.',
      ornekTr: 'Aslında onu zaten okudum.',
      not: '"Şu anda" demek DEĞİLDİR; o "currently"dir. Sık yapılan hatadır.',
    },
    {
      id: 'en-gun-84', on: 'I mean', okunus: 'ay miin', tur: 'kalıp',
      arka: 'Yani, demek istediğim',
      ornek: 'It is cheap, I mean, not expensive at all.',
      ornekTr: 'Ucuz, yani hiç pahalı değil.',
      not: 'Kendini düzeltmek ve açıklamak için kullanılır.',
    },
    {
      id: 'en-gun-85', on: 'You know what I mean?', okunus: 'yu nou vot ay miin', tur: 'kalıp',
      arka: 'Ne demek istediğimi anlıyor musun?',
      ornek: 'It is complicated, you know what I mean?',
      ornekTr: 'Karışık bir durum, anlatabiliyor muyum?',
      not: 'Dinleyiciyi konuşmaya dâhil eder.',
    },
    {
      id: 'en-gun-86', on: 'Let me think', okunus: 'let mi tink', tur: 'kalıp',
      arka: 'Bir düşüneyim',
      ornek: 'Let me think for a second.',
      ornekTr: 'Bir saniye düşüneyim.',
      not: 'Konuşma sınavında sessiz kalmak yerine zaman kazandırır.',
    },
    {
      id: 'en-gun-87', on: 'How can I put it?', okunus: 'hau ken ay put it', tur: 'kalıp',
      arka: 'Nasıl desem?',
      ornek: 'It was, how can I put it, disappointing.',
      ornekTr: 'Nasıl desem, hayal kırıklığıydı.',
      not: 'Doğru kelimeyi ararken doğal bir duraklama sağlar.',
    },
    {
      id: 'en-gun-88', on: 'as I was saying', okunus: 'ez ay voz seying', tur: 'kalıp',
      arka: 'Dediğim gibi',
      ornek: 'As I was saying, we need more time.',
      ornekTr: 'Dediğim gibi, daha fazla zamana ihtiyacımız var.',
      not: 'Sözü kesildikten sonra devam etmek için kullanılır.',
    },
    {
      id: 'en-gun-89', on: 'to cut a long story short', okunus: 'tu kat ı long stori şort', tur: 'deyim',
      arka: 'Uzun lafın kısası',
      ornek: 'To cut a long story short, we missed the bus.',
      ornekTr: 'Uzun lafın kısası, otobüsü kaçırdık.',
      not: 'Amerika\'da "long story short" kısaltması kullanılır.',
    },
    {
      id: 'en-gun-90', on: 'Sorry, I did not catch that', okunus: 'sori ay didınt keç det', tur: 'kalıp',
      arka: 'Pardon, anlayamadım',
      ornek: 'Sorry, I did not catch that. Could you say it again?',
      ornekTr: 'Pardon, anlayamadım. Tekrar söyler misiniz?',
      not: '"Catch" burada duyup anlamak demektir.',
    },
    /* --- Gündelik öbek fiiller --- */
    {
      id: 'en-gun-91', on: 'come across', okunus: 'kam ıkros', tur: 'öbek fiil',
      arka: 'tesadüfen rastlamak',
      ornek: 'I came across an old photo yesterday.',
      ornekTr: 'Dün eski bir fotoğrafa rastladım.',
      not: 'Aynı öbek "izlenim bırakmak" anlamına da gelir.',
    },
    {
      id: 'en-gun-92', on: 'run into someone', okunus: 'ran intu samvan', tur: 'öbek fiil',
      arka: 'birine tesadüfen rastlamak',
      ornek: 'I ran into my old teacher at the mall.',
      ornekTr: 'Alışveriş merkezinde eski öğretmenime rastladım.',
      not: '"Bump into" ile aynı anlamdadır.',
    },
    {
      id: 'en-gun-93', on: 'put off', okunus: 'put of', tur: 'öbek fiil',
      arka: 'ertelemek',
      ornek: 'They put off the meeting until Friday.',
      ornekTr: 'Toplantıyı cumaya ertelediler.',
      not: '"Postpone" ile aynıdır ama konuşmada bu tercih edilir.',
    },
    {
      id: 'en-gun-94', on: 'work out', okunus: 'vörk aut', tur: 'öbek fiil',
      arka: 'yoluna girmek; hesaplamak',
      ornek: 'Do not worry, it will work out.',
      ornekTr: 'Merak etme, yoluna girecek.',
      not: 'Üçüncü anlamı "spor yapmak"tır; bağlam ayırır.',
    },
    {
      id: 'en-gun-95', on: 'turn up', okunus: 'törn ap', tur: 'öbek fiil',
      arka: 'çıkagelmek',
      ornek: 'He turned up an hour late.',
      ornekTr: 'Bir saat geç çıkageldi.',
      not: 'Kaybolan bir eşyanın bulunması için de kullanılır.',
    },
    {
      id: 'en-gun-96', on: 'get over', okunus: 'get ouvır', tur: 'öbek fiil',
      arka: 'atlatmak (hastalık, üzüntü)',
      ornek: 'It took a week to get over the flu.',
      ornekTr: 'Gribi atlatmak bir hafta sürdü.',
      not: 'Duygusal atlatma için de kullanılır.',
    },
    {
      id: 'en-gun-97', on: 'look after', okunus: 'luk aftır', tur: 'öbek fiil',
      arka: 'bakmak, ilgilenmek',
      ornek: 'She looks after her little brother.',
      ornekTr: 'Küçük kardeşine bakıyor.',
      not: '"Look for" aramak, "look after" bakmaktır. Karıştırma.',
    },
    {
      id: 'en-gun-98', on: 'find out', okunus: 'faynd aut', tur: 'öbek fiil',
      arka: 'öğrenmek (araştırarak)',
      ornek: 'I want to find out the truth.',
      ornekTr: 'Gerçeği öğrenmek istiyorum.',
      not: '"Learn" ders çalışarak, "find out" bilgi edinerek öğrenmektir.',
    },
    {
      id: 'en-gun-99', on: 'end up', okunus: 'end ap', tur: 'öbek fiil',
      arka: 'sonunda bir yerde/durumda olmak',
      ornek: 'We ended up staying at home.',
      ornekTr: 'Sonunda evde kaldık.',
      not: 'Sonrasında -ing gelir: end up doing something.',
    },
    {
      id: 'en-gun-100', on: 'be about to', okunus: 'bi ıbaut tu', tur: 'kalıp',
      arka: 'tam ... etmek üzere olmak',
      ornek: 'I was about to call you.',
      ornekTr: 'Tam seni arayacaktım.',
      not: 'Çok yakın gelecek anlatır; sonrasında yalın fiil gelir.',
    },
  ],
}

export default DESTE
