/**
 * DESTE — HAYVANLAR VE DOĞA (İngilizce)
 *
 * Kelimelerin kendisi kolay, deyimleri zordur. Bu destede her hayvan
 * kartında o hayvanın geçtiği deyim de not olarak verildi; sınav
 * metinlerinde ve dizilerde karşına deyim olarak çıkar.
 */

export const DESTE = {
  id: 'hayvanlar-doga',
  dil: 'en',
  ad: 'Hayvanlar ve doğa',
  simge: '🌿',
  aciklama: 'Hayvanlar, hava ve doğa; içinde geçtikleri deyimlerle.',
  seviye: 'A2–B1',
  kartlar: [
    {
      id: 'en-hay-01', on: 'pet', okunus: 'pet', tur: 'isim',
      arka: 'evcil hayvan',
      ornek: 'Do you have any pets at home?',
      ornekTr: 'Evde hiç evcil hayvanın var mı?',
      not: '"animal" genel, "pet" evde beslenendir.',
    },
    {
      id: 'en-hay-02', on: 'It is raining cats and dogs', okunus: 'its reyning kets end dogz', tur: 'deyim',
      arka: 'bardaktan boşanırcasına yağıyor',
      ornek: 'Take an umbrella, it is raining cats and dogs.',
      ornekTr: 'Şemsiye al, bardaktan boşanırcasına yağıyor.',
      not: 'Kelime kelime "kedi köpek yağıyor" demektir.',
    },
    {
      id: 'en-hay-03', on: 'the weather', okunus: 'dı vedır', tur: 'isim (sayılamayan)',
      arka: 'hava durumu',
      ornek: 'The weather is lovely today.',
      ornekTr: 'Bugün hava çok güzel.',
      not: 'SAYILAMAZ: "a weather" YANLIŞTIR. Sesteşi "whether" (… olup olmadığı).',
    },
    {
      id: 'en-hay-04', on: 'freezing', okunus: 'friizing', tur: 'sıfat',
      arka: 'dondurucu soğuk',
      ornek: 'It is freezing outside, wear a coat.',
      ornekTr: 'Dışarısı buz gibi, mont giy.',
      not: 'Karşıtı "boiling" (kavurucu sıcak). İkisi de abartma sıfatıdır.',
    },
    {
      id: 'en-hay-05', on: 'the countryside', okunus: 'dı kantrisayd', tur: 'isim',
      arka: 'kırsal, köy tarafı',
      ornek: 'My grandparents live in the countryside.',
      ornekTr: 'Büyükannemler kırsalda yaşıyor.',
      not: '"country" hem ülke hem kırsal demektir; artikel ayırır.',
    },
    {
      id: 'en-hay-06', on: 'a bird\'s-eye view', okunus: 'ı börds ay vyu', tur: 'deyim',
      arka: 'kuşbakışı',
      ornek: 'From the tower you get a bird\'s-eye view of the city.',
      ornekTr: 'Kuleden şehri kuşbakışı görüyorsun.',
      not: 'Türkçedeki "kuşbakışı" ile birebir aynı mantık.',
    },
    {
      id: 'en-hay-07', on: 'go for a walk', okunus: 'gou for ı vok', tur: 'eş dizim',
      arka: 'yürüyüşe çıkmak',
      ornek: 'Let us go for a walk by the sea.',
      ornekTr: 'Deniz kenarında yürüyüşe çıkalım.',
      not: '"make a walk" YANLIŞTIR. Aynı kalıp: go for a run / a swim / a drive.',
    },
    {
      id: 'en-hay-08', on: 'wildlife', okunus: 'vayldlayf', tur: 'isim (sayılamayan)',
      arka: 'yaban hayatı',
      ornek: 'This forest is full of wildlife.',
      ornekTr: 'Bu orman yaban hayatıyla dolu.',
      not: 'Belgesellerde ve okuma metinlerinde çok geçer.',
    },
    {
      id: 'en-hay-09', on: 'endangered', okunus: 'indeyncırd', tur: 'sıfat',
      arka: 'nesli tehlikede olan',
      ornek: 'Pandas are still an endangered species.',
      ornekTr: 'Pandaların nesli hâlâ tehlikede.',
      not: 'Tür "species"tir ve tekili de çoğulu da aynıdır.',
    },
    {
      id: 'en-hay-10', on: 'get some fresh air', okunus: 'get sam freş eır', tur: 'kalıp',
      arka: 'hava almak',
      ornek: 'I am going outside to get some fresh air.',
      ornekTr: 'Biraz hava almak için dışarı çıkıyorum.',
      not: 'Türkçedeki "hava almak" ile tam olarak aynı kullanım.',
    },
    /* --- Evcil hayvanlar --- */
    {
      id: 'en-hay-11', on: 'pet', okunus: 'pet', tur: 'isim',
      arka: 'evcil hayvan',
      ornek: 'Do you have any pets at home?',
      ornekTr: 'Evde hiç evcil hayvanın var mı?',
      not: 'Fiil olarak "sevmek, okşamak" anlamına gelir.',
    },
    {
      id: 'en-hay-12', on: 'puppy / kitten', okunus: 'papi / kitın', tur: 'isim',
      arka: 'köpek yavrusu / kedi yavrusu',
      ornek: 'They adopted a puppy last week.',
      ornekTr: 'Geçen hafta bir köpek yavrusu sahiplendiler.',
      not: 'Hayvan yavrularının çoğunun ayrı adı vardır: calf, lamb, chick.',
    },
    {
      id: 'en-hay-13', on: 'adopt', okunus: 'ıdopt', tur: 'fiil',
      arka: 'sahiplenmek',
      ornek: 'Adopt, do not buy.',
      ornekTr: 'Satın alma, sahiplen.',
      not: 'Çocuk evlat edinmek için de aynı fiil kullanılır.',
    },
    {
      id: 'en-hay-14', on: 'stray', okunus: 'strey', tur: 'sıfat / isim',
      arka: 'sokak hayvanı, sahipsiz',
      ornek: 'There are many stray cats in our street.',
      ornekTr: 'Sokağımızda çok sokak kedisi var.',
      not: 'Fiil olarak "yolunu şaşırmak" demektir.',
    },
    {
      id: 'en-hay-15', on: 'feed', okunus: 'fiid', tur: 'fiil',
      arka: 'beslemek, yemek vermek',
      ornek: 'I feed the birds every morning.',
      ornekTr: 'Her sabah kuşları besliyorum.',
      not: 'Düzensiz fiildir: feed - fed - fed.',
    },
    {
      id: 'en-hay-16', on: 'take the dog for a walk', okunus: 'teyk dı dog for ı vok', tur: 'eş dizim',
      arka: 'köpeği gezdirmek',
      ornek: 'I take the dog for a walk after school.',
      ornekTr: 'Okuldan sonra köpeği gezdiriyorum.',
      not: 'Kısaca "walk the dog" da denir.',
    },
    {
      id: 'en-hay-17', on: 'vet', okunus: 'vet', tur: 'isim',
      arka: 'veteriner',
      ornek: 'We took the cat to the vet.',
      ornekTr: 'Kediyi veterinere götürdük.',
      not: 'Uzun hâli "veterinarian"dır ama konuşmada "vet" kullanılır.',
    },
    {
      id: 'en-hay-18', on: 'bark / meow', okunus: 'bark / miau', tur: 'fiil',
      arka: 'havlamak / miyavlamak',
      ornek: 'The dog barked all night.',
      ornekTr: 'Köpek bütün gece havladı.',
      not: 'Hayvan sesleri dilden dile değişir; İngilizcede köpek "woof" der.',
    },
    {
      id: 'en-hay-19', on: 'tail', okunus: 'teyl', tur: 'isim',
      arka: 'kuyruk',
      ornek: 'The dog wagged its tail.',
      ornekTr: 'Köpek kuyruğunu salladı.',
      not: 'Hayvanlar için "it" kullanılır; sahibi "he/she" de diyebilir.',
    },
    {
      id: 'en-hay-20', on: 'loyal', okunus: 'loyıl', tur: 'sıfat',
      arka: 'sadık',
      ornek: 'Dogs are very loyal animals.',
      ornekTr: 'Köpekler çok sadık hayvanlardır.',
      not: 'İsmi "loyalty" = sadakat.',
    },
    /* --- Yaban hayatı --- */
    {
      id: 'en-hay-21', on: 'wildlife', okunus: 'vayldlayf', tur: 'isim',
      arka: 'yaban hayatı',
      ornek: 'The park protects local wildlife.',
      ornekTr: 'Park yerel yaban hayatını koruyor.',
      not: 'Sayılamayan bir isimdir: "wildlifes" YANLIŞTIR.',
    },
    {
      id: 'en-hay-22', on: 'mammal', okunus: 'memıl', tur: 'isim',
      arka: 'memeli',
      ornek: 'Whales are mammals, not fish.',
      ornekTr: 'Balinalar balık değil, memelidir.',
      not: 'Biyoloji dersinde de aynı sınıflandırma kullanılır.',
    },
    {
      id: 'en-hay-23', on: 'reptile', okunus: 'reptayl', tur: 'isim',
      arka: 'sürüngen',
      ornek: 'Snakes and lizards are reptiles.',
      ornekTr: 'Yılanlar ve kertenkeleler sürüngendir.',
      not: 'Kurbağa sürüngen değil, iki yaşamlıdır: "amphibian".',
    },
    {
      id: 'en-hay-24', on: 'predator / prey', okunus: 'predıtır / prey', tur: 'ayrım',
      arka: 'avcı / av',
      ornek: 'The lion is a predator; the deer is its prey.',
      ornekTr: 'Aslan avcıdır; geyik onun avıdır.',
      not: '"Prey" çoğul almaz; okunuşu "pray" ile aynıdır.',
    },
    {
      id: 'en-hay-25', on: 'herd / flock', okunus: 'hörd / flok', tur: 'ayrım',
      arka: 'sürü (büyükbaş) / sürü (kuş, koyun)',
      ornek: 'A herd of cows and a flock of birds.',
      ornekTr: 'Bir inek sürüsü ve bir kuş sürüsü.',
      not: 'Balık için "a school of fish" denir. Sınavda sorulur.',
    },
    {
      id: 'en-hay-26', on: 'migrate', okunus: 'maygreyt', tur: 'fiil',
      arka: 'göç etmek',
      ornek: 'Birds migrate south in winter.',
      ornekTr: 'Kuşlar kışın güneye göç eder.',
      not: 'İsmi "migration"dır; insan göçü için de kullanılır.',
    },
    {
      id: 'en-hay-27', on: 'hibernate', okunus: 'haybırneyt', tur: 'fiil',
      arka: 'kış uykusuna yatmak',
      ornek: 'Bears hibernate through the winter.',
      ornekTr: 'Ayılar kış boyunca uykuya yatar.',
      not: 'İsmi "hibernation"dır; bilgisayarda da aynı terim kullanılır.',
    },
    {
      id: 'en-hay-28', on: 'habitat', okunus: 'hebitet', tur: 'isim',
      arka: 'doğal yaşam alanı',
      ornek: 'Their natural habitat is disappearing.',
      ornekTr: 'Doğal yaşam alanları yok oluyor.',
      not: 'Çevre metinlerinin anahtar kelimesidir.',
    },
    {
      id: 'en-hay-29', on: 'species', okunus: 'spiişiiz', tur: 'isim',
      arka: 'tür',
      ornek: 'This species lives only in Turkey.',
      ornekTr: 'Bu tür yalnızca Türkiye\'de yaşar.',
      not: 'Tekili ve çoğulu aynıdır: one species, two species.',
    },
    {
      id: 'en-hay-30', on: 'endangered', okunus: 'indeyncırd', tur: 'sıfat',
      arka: 'nesli tehlike altında',
      ornek: 'Sea turtles are an endangered species.',
      ornekTr: 'Deniz kaplumbağaları nesli tehlike altındaki bir türdür.',
      not: 'Nesli tükenmiş olan "extinct"tir.',
    },
    /* --- Doğal alanlar --- */
    {
      id: 'en-hay-31', on: 'forest / wood', okunus: 'forıst / vud', tur: 'ayrım',
      arka: 'orman (büyük) / koru (küçük)',
      ornek: 'We walked through the woods.',
      ornekTr: 'Korunun içinden geçtik.',
      not: '"Wood" ayrıca "odun, ahşap" demektir.',
    },
    {
      id: 'en-hay-32', on: 'valley', okunus: 'veli', tur: 'isim',
      arka: 'vadi',
      ornek: 'The village lies in a green valley.',
      ornekTr: 'Köy yeşil bir vadide yer alıyor.',
      not: 'Coğrafya dersindeki "vadi" ile aynı kavramdır.',
    },
    {
      id: 'en-hay-33', on: 'stream', okunus: 'striim', tur: 'isim',
      arka: 'dere',
      ornek: 'A small stream runs behind the house.',
      ornekTr: 'Evin arkasından küçük bir dere akıyor.',
      not: 'Nehir "river", dere "stream", göl "lake"tir.',
    },
    {
      id: 'en-hay-34', on: 'cliff', okunus: 'klif', tur: 'isim',
      arka: 'uçurum, yalıyar',
      ornek: 'The path goes along the cliff.',
      ornekTr: 'Patika uçurum boyunca gidiyor.',
      not: 'Deniz kenarındaki dik kayalık için kullanılır.',
    },
    {
      id: 'en-hay-35', on: 'shore', okunus: 'şor', tur: 'isim',
      arka: 'kıyı',
      ornek: 'We walked along the shore.',
      ornekTr: 'Kıyı boyunca yürüdük.',
      not: '"Beach" kumsaldır, "shore" genel kıyı hattıdır.',
    },
    {
      id: 'en-hay-36', on: 'field', okunus: 'fiild', tur: 'isim',
      arka: 'tarla, kır',
      ornek: 'The fields are full of flowers in spring.',
      ornekTr: 'İlkbaharda tarlalar çiçeklerle dolu.',
      not: 'Amerika\'da futbol sahası için de kullanılır.',
    },
    {
      id: 'en-hay-37', on: 'countryside', okunus: 'kantrisayd', tur: 'isim',
      arka: 'kırsal, taşra',
      ornek: 'We spent the summer in the countryside.',
      ornekTr: 'Yazı kırsalda geçirdik.',
      not: 'Şehir olan "the city"dir; "the" ile kullanılır.',
    },
    {
      id: 'en-hay-38', on: 'peak', okunus: 'piik', tur: 'isim',
      arka: 'zirve',
      ornek: 'They reached the peak at sunrise.',
      ornekTr: 'Gün doğarken zirveye ulaştılar.',
      not: 'Mecazi olarak "en yüksek nokta" anlamına da gelir.',
    },
    {
      id: 'en-hay-39', on: 'cave', okunus: 'keyv', tur: 'isim',
      arka: 'mağara',
      ornek: 'The cave is open to visitors.',
      ornekTr: 'Mağara ziyaretçilere açık.',
      not: 'Türkiye\'nin turizm metinlerinde çok geçer.',
    },
    {
      id: 'en-hay-40', on: 'trail', okunus: 'treyl', tur: 'isim',
      arka: 'patika, yürüyüş rotası',
      ornek: 'We followed a mountain trail.',
      ornekTr: 'Bir dağ patikasını takip ettik.',
      not: 'Yürüyüş yapmak "go hiking"tir.',
    },
    /* --- Bitkiler ve mevsimler --- */
    {
      id: 'en-hay-41', on: 'branch', okunus: 'brançı', tur: 'isim',
      arka: 'dal',
      ornek: 'A bird sat on the branch.',
      ornekTr: 'Bir kuş dala kondu.',
      not: 'Şube anlamına da gelir: "a branch of the bank".',
    },
    {
      id: 'en-hay-42', on: 'root', okunus: 'ruut', tur: 'isim',
      arka: 'kök',
      ornek: 'The roots go deep into the soil.',
      ornekTr: 'Kökler toprağın derinlerine iniyor.',
      not: 'Mecazi olarak "kökeni" anlamına gelir: "his Turkish roots".',
    },
    {
      id: 'en-hay-43', on: 'soil', okunus: 'soyl', tur: 'isim',
      arka: 'toprak (verimli)',
      ornek: 'The soil here is very rich.',
      ornekTr: 'Buradaki toprak çok verimli.',
      not: '"Ground" üzerinde durduğumuz zemindir, "soil" ekim toprağıdır.',
    },
    {
      id: 'en-hay-44', on: 'seed', okunus: 'siid', tur: 'isim',
      arka: 'tohum',
      ornek: 'We planted seeds in the garden.',
      ornekTr: 'Bahçeye tohum ektik.',
      not: 'Ekmek fiili "plant" ya da "sow"dur.',
    },
    {
      id: 'en-hay-45', on: 'blossom', okunus: 'blosım', tur: 'isim / fiil',
      arka: 'çiçek açmak (ağaçta)',
      ornek: 'The cherry trees blossom in April.',
      ornekTr: 'Kiraz ağaçları nisanda çiçek açar.',
      not: 'Meyve ağaçlarına özgüdür; genel çiçek "flower"dır.',
    },
    {
      id: 'en-hay-46', on: 'leaves fall', okunus: 'liivz fol', tur: 'kalıp',
      arka: 'yapraklar dökülür',
      ornek: 'The leaves fall in October.',
      ornekTr: 'Yapraklar ekimde dökülür.',
      not: 'Tekili "leaf"tir; çoğulu düzensizdir: leaf → leaves.',
    },
    {
      id: 'en-hay-47', on: 'grow', okunus: 'grou', tur: 'fiil',
      arka: 'büyümek, yetiştirmek',
      ornek: 'They grow tomatoes in the garden.',
      ornekTr: 'Bahçede domates yetiştiriyorlar.',
      not: 'Düzensizdir: grow - grew - grown.',
    },
    {
      id: 'en-hay-48', on: 'water the plants', okunus: 'votır dı plants', tur: 'eş dizim',
      arka: 'bitkileri sulamak',
      ornek: 'Do not forget to water the plants.',
      ornekTr: 'Bitkileri sulamayı unutma.',
      not: '"Water" burada fiildir; isimden fiil olan yaygın örneklerdendir.',
    },
    {
      id: 'en-hay-49', on: 'harvest', okunus: 'harvıst', tur: 'isim / fiil',
      arka: 'hasat; hasat etmek',
      ornek: 'The harvest was good this year.',
      ornekTr: 'Bu yıl hasat iyiydi.',
      not: 'Tarım metinlerinde anahtar kelimedir.',
    },
    {
      id: 'en-hay-50', on: 'greenhouse', okunus: 'griinhaus', tur: 'isim',
      arka: 'sera',
      ornek: 'They grow vegetables in a greenhouse.',
      ornekTr: 'Serada sebze yetiştiriyorlar.',
      not: '"Greenhouse effect" = sera etkisi; iklim metinlerinde geçer.',
    },
    /* --- Çevre sorunları --- */
    {
      id: 'en-hay-51', on: 'pollution', okunus: 'pıluşın', tur: 'isim',
      arka: 'kirlilik',
      ornek: 'Air pollution is a serious problem.',
      ornekTr: 'Hava kirliliği ciddi bir sorun.',
      not: 'Sayılamazdır. Fiili "pollute" = kirletmek.',
    },
    {
      id: 'en-hay-52', on: 'climate change', okunus: 'klaymıt çeync', tur: 'isim',
      arka: 'iklim değişikliği',
      ornek: 'Climate change affects everyone.',
      ornekTr: 'İklim değişikliği herkesi etkiliyor.',
      not: '"Weather" günlük hava, "climate" uzun dönem iklimdir.',
    },
    {
      id: 'en-hay-53', on: 'global warming', okunus: 'gloubıl vorming', tur: 'isim',
      arka: 'küresel ısınma',
      ornek: 'Global warming is melting the ice.',
      ornekTr: 'Küresel ısınma buzları eritiyor.',
      not: 'Sınav okuma metinlerinin klasik konusudur.',
    },
    {
      id: 'en-hay-54', on: 'recycle', okunus: 'risaykıl', tur: 'fiil',
      arka: 'geri dönüştürmek',
      ornek: 'We recycle paper and plastic at school.',
      ornekTr: 'Okulda kâğıt ve plastiği geri dönüştürüyoruz.',
      not: 'İsmi "recycling"dir; kutu "a recycling bin"dir.',
    },
    {
      id: 'en-hay-55', on: 'waste', okunus: 'veyst', tur: 'isim / fiil',
      arka: 'atık; israf etmek',
      ornek: 'Do not waste water.',
      ornekTr: 'Suyu israf etme.',
      not: 'Hem "çöp" hem "boşa harcamak" anlamına gelir.',
    },
    {
      id: 'en-hay-56', on: 'deforestation', okunus: 'diforısteyşın', tur: 'isim',
      arka: 'ormansızlaşma',
      ornek: 'Deforestation destroys animal habitats.',
      ornekTr: 'Ormansızlaşma hayvan yaşam alanlarını yok ediyor.',
      not: 'Uzun ama okuma metinlerinde sık geçen bir kelimedir.',
    },
    {
      id: 'en-hay-57', on: 'renewable energy', okunus: 'rinyuıbıl enırci', tur: 'isim',
      arka: 'yenilenebilir enerji',
      ornek: 'Solar power is renewable energy.',
      ornekTr: 'Güneş enerjisi yenilenebilir enerjidir.',
      not: 'Karşıtı "fossil fuels" = fosil yakıtlar.',
    },
    {
      id: 'en-hay-58', on: 'reduce', okunus: 'ridyus', tur: 'fiil',
      arka: 'azaltmak',
      ornek: 'We must reduce plastic use.',
      ornekTr: 'Plastik kullanımını azaltmalıyız.',
      not: 'Üçlü slogan: reduce, reuse, recycle.',
    },
    {
      id: 'en-hay-59', on: 'eco-friendly', okunus: 'ikou frendli', tur: 'sıfat',
      arka: 'çevre dostu',
      ornek: 'These bags are eco-friendly.',
      ornekTr: 'Bu poşetler çevre dostu.',
      not: '"Environmentally friendly" ile aynıdır.',
    },
    {
      id: 'en-hay-60', on: 'litter', okunus: 'litır', tur: 'isim / fiil',
      arka: 'çöp (yere atılan)',
      ornek: 'Do not drop litter in the park.',
      ornekTr: 'Parka çöp atma.',
      not: '"Rubbish" evdeki çöptür, "litter" yere atılandır.',
    },
    /* --- Hava olayları ve doğa güçleri --- */
    {
      id: 'en-hay-61', on: 'thunderstorm', okunus: 'tandırstorm', tur: 'isim',
      arka: 'gök gürültülü fırtına',
      ornek: 'A thunderstorm woke us up.',
      ornekTr: 'Gök gürültülü bir fırtına bizi uyandırdı.',
      not: 'Şimşek "lightning", gök gürültüsü "thunder"dır.',
    },
    {
      id: 'en-hay-62', on: 'flood', okunus: 'flad', tur: 'isim / fiil',
      arka: 'sel',
      ornek: 'The village was hit by a flood.',
      ornekTr: 'Köyü sel vurdu.',
      not: 'Okunuşu tuzaktır: "fluud" değil, "flad".',
    },
    {
      id: 'en-hay-63', on: 'drought', okunus: 'draut', tur: 'isim',
      arka: 'kuraklık',
      ornek: 'The region suffered a long drought.',
      ornekTr: 'Bölge uzun bir kuraklık yaşadı.',
      not: 'Okunuşu zordur: "drot" değil, "draut".',
    },
    {
      id: 'en-hay-64', on: 'earthquake', okunus: 'örtkueyk', tur: 'isim',
      arka: 'deprem',
      ornek: 'Turkey is an earthquake zone.',
      ornekTr: 'Türkiye bir deprem bölgesidir.',
      not: 'Artçı sarsıntı "an aftershock"tur.',
    },
    {
      id: 'en-hay-65', on: 'wildfire', okunus: 'vayldfayır', tur: 'isim',
      arka: 'orman yangını',
      ornek: 'Wildfires are common in summer.',
      ornekTr: 'Orman yangınları yazın sık görülür.',
      not: '"Forest fire" ile aynıdır.',
    },
    {
      id: 'en-hay-66', on: 'breeze', okunus: 'briiz', tur: 'isim',
      arka: 'meltem, hafif rüzgâr',
      ornek: 'There was a cool breeze in the evening.',
      ornekTr: 'Akşam serin bir meltem vardı.',
      not: 'Deyim olarak "çok kolay iş" anlamına da gelir.',
    },
    {
      id: 'en-hay-67', on: 'fog / mist', okunus: 'fog / mist', tur: 'ayrım',
      arka: 'sis (yoğun) / pus (hafif)',
      ornek: 'Thick fog and light mist covered the road.',
      ornekTr: 'Yoğun sis ve hafif pus yolu kapladı.',
      not: 'Sisli hava "foggy", puslu "misty"dir.',
    },
    {
      id: 'en-hay-68', on: 'sunrise / sunset', okunus: 'sanrayz / sanset', tur: 'isim',
      arka: 'gün doğumu / gün batımı',
      ornek: 'We watched the sunset from the hill.',
      ornekTr: 'Gün batımını tepeden izledik.',
      not: 'Edatı "at"tir: at sunset, at sunrise.',
    },
    {
      id: 'en-hay-69', on: 'tide', okunus: 'tayd', tur: 'isim',
      arka: 'gelgit',
      ornek: 'The tide comes in twice a day.',
      ornekTr: 'Gelgit günde iki kez olur.',
      not: 'Coğrafya dersindeki gelgit olayının İngilizce karşılığıdır.',
    },
    {
      id: 'en-hay-70', on: 'shelter', okunus: 'şeltır', tur: 'isim / fiil',
      arka: 'barınak; korunmak',
      ornek: 'We took shelter under a tree.',
      ornekTr: 'Bir ağacın altına sığındık.',
      not: 'Hayvan barınağı için de kullanılır: "an animal shelter".',
    },
    /* --- Doğada zaman geçirmek --- */
    {
      id: 'en-hay-71', on: 'go hiking', okunus: 'gou hayking', tur: 'eş dizim',
      arka: 'doğa yürüyüşüne çıkmak',
      ornek: 'We go hiking every spring.',
      ornekTr: 'Her ilkbahar doğa yürüyüşüne çıkarız.',
      not: 'Etkinliklerde "go + -ing" kalıbı kullanılır: go camping, go fishing.',
    },
    {
      id: 'en-hay-72', on: 'set up a tent', okunus: 'set ap ı tent', tur: 'eş dizim',
      arka: 'çadır kurmak',
      ornek: 'We set up the tent near the river.',
      ornekTr: 'Çadırı nehrin yanına kurduk.',
      not: '"Pitch a tent" de denir.',
    },
    {
      id: 'en-hay-73', on: 'campfire', okunus: 'kempfayır', tur: 'isim',
      arka: 'kamp ateşi',
      ornek: 'We sang songs around the campfire.',
      ornekTr: 'Kamp ateşinin etrafında şarkı söyledik.',
      not: 'Ateş yakmak "make a fire"dır.',
    },
    {
      id: 'en-hay-74', on: 'get some fresh air', okunus: 'get sam freş eır', tur: 'kalıp',
      arka: 'temiz hava almak',
      ornek: 'Let us go out and get some fresh air.',
      ornekTr: 'Hadi çıkıp biraz temiz hava alalım.',
      not: 'Ders molası önerirken çok kullanışlıdır.',
    },
    {
      id: 'en-hay-75', on: 'birdwatching', okunus: 'bördvoçing', tur: 'isim',
      arka: 'kuş gözlemi',
      ornek: 'Birdwatching is a peaceful hobby.',
      ornekTr: 'Kuş gözlemi huzurlu bir hobidir.',
      not: 'Bir hobi anlatırken güzel bir örnektir.',
    },
    {
      id: 'en-hay-76', on: 'peaceful', okunus: 'piisful', tur: 'sıfat',
      arka: 'huzurlu, sakin',
      ornek: 'The forest was quiet and peaceful.',
      ornekTr: 'Orman sessiz ve huzurluydu.',
      not: 'İsmi "peace" = barış, huzur.',
    },
    {
      id: 'en-hay-77', on: 'breathtaking', okunus: 'brettteyking', tur: 'sıfat',
      arka: 'nefes kesici',
      ornek: 'The view was breathtaking.',
      ornekTr: 'Manzara nefes kesiciydi.',
      not: 'Kelimesi kelimesine "nefes alan" demektir; Türkçesiyle örtüşür.',
    },
    {
      id: 'en-hay-78', on: 'in the middle of nowhere', okunus: 'in dı midıl ıv nouveır', tur: 'deyim',
      arka: 'ıssız bir yerde',
      ornek: 'The cabin is in the middle of nowhere.',
      ornekTr: 'Kulübe ıssız bir yerde.',
      not: 'Uzaklığı ve tenhalığı vurgular.',
    },
    {
      id: 'en-hay-79', on: 'get back to nature', okunus: 'get bek tu neyçır', tur: 'kalıp',
      arka: 'doğaya dönmek',
      ornek: 'City people want to get back to nature.',
      ornekTr: 'Şehirdekiler doğaya dönmek istiyor.',
      not: '"Nature" sayılamaz ve "the" almaz.',
    },
    {
      id: 'en-hay-80', on: 'leave no trace', okunus: 'liiv nou treys', tur: 'kalıp',
      arka: 'iz bırakmamak',
      ornek: 'Camp carefully and leave no trace.',
      ornekTr: 'Dikkatli kamp yap ve iz bırakma.',
      not: 'Doğa etiği kurallarının sloganıdır.',
    },
    /* --- Hayvanlı deyimler --- */
    {
      id: 'en-hay-81', on: 'let the cat out of the bag', okunus: 'let dı ket aut ıv dı beg', tur: 'deyim',
      arka: 'sırrı ağzından kaçırmak',
      ornek: 'He let the cat out of the bag about the party.',
      ornekTr: 'Parti konusunda ağzından kaçırdı.',
      not: '"Spill the beans" ile aynı anlamdadır.',
    },
    {
      id: 'en-hay-82', on: 'a fish out of water', okunus: 'ı fiş aut ıv votır', tur: 'deyim',
      arka: 'yabancısı olduğu ortamda',
      ornek: 'I felt like a fish out of water at the party.',
      ornekTr: 'Partide kendimi yabancı gibi hissettim.',
      not: 'Uyumsuzluk hissini anlatır.',
    },
    {
      id: 'en-hay-83', on: 'kill two birds with one stone', okunus: 'kil tu bördz vit van stoun', tur: 'deyim',
      arka: 'bir taşla iki kuş vurmak',
      ornek: 'I study on the bus and kill two birds with one stone.',
      ornekTr: 'Otobüste çalışıp bir taşla iki kuş vuruyorum.',
      not: 'Türkçesiyle birebir aynıdır.',
    },
    {
      id: 'en-hay-84', on: 'the elephant in the room', okunus: 'di elifınt in dı rum', tur: 'deyim',
      arka: 'herkesin gördüğü ama konuşmadığı sorun',
      ornek: 'Nobody mentioned the elephant in the room.',
      ornekTr: 'Kimse ortadaki asıl sorundan bahsetmedi.',
      not: 'Tartışma metinlerinde sık kullanılır.',
    },
    {
      id: 'en-hay-85', on: 'hold your horses', okunus: 'hould yor horsız', tur: 'deyim',
      arka: 'acele etme, sakin ol',
      ornek: 'Hold your horses, we have plenty of time.',
      ornekTr: 'Acele etme, bol bol vaktimiz var.',
      not: 'Dostane bir uyarı tonu taşır.',
    },
    {
      id: 'en-hay-86', on: 'a night owl', okunus: 'ı nayt aul', tur: 'deyim',
      arka: 'gece kuşu',
      ornek: 'I am a night owl, I study best at midnight.',
      ornekTr: 'Ben gece kuşuyum, en iyi gece yarısı çalışırım.',
      not: 'Sabahçı olan "an early bird"tür.',
    },
    {
      id: 'en-hay-87', on: 'the early bird catches the worm', okunus: 'di örli börd keçız dı vörm', tur: 'atasözü',
      arka: 'erken kalkan yol alır',
      ornek: 'Start early: the early bird catches the worm.',
      ornekTr: 'Erken başla: erken kalkan yol alır.',
      not: 'Türkçedeki "erken kalkan yol alır" ile aynı işlevdedir.',
    },
    {
      id: 'en-hay-88', on: 'busy as a bee', okunus: 'bizi ez ı bii', tur: 'deyim',
      arka: 'arı gibi çalışkan',
      ornek: 'She has been as busy as a bee all week.',
      ornekTr: 'Bütün hafta arı gibi çalıştı.',
      not: 'Benzetme kalıbı "as ... as"tir.',
    },
    {
      id: 'en-hay-89', on: 'take the bull by the horns', okunus: 'teyk dı bul bay dı hornz', tur: 'deyim',
      arka: 'sorunun üstüne gitmek',
      ornek: 'He took the bull by the horns and asked for help.',
      ornekTr: 'Sorunun üstüne gidip yardım istedi.',
      not: 'Cesaret ve kararlılığı anlatır.',
    },
    {
      id: 'en-hay-90', on: 'when pigs fly', okunus: 'ven pigz flay', tur: 'deyim',
      arka: 'balık kavağa çıkınca',
      ornek: 'He will tidy his room when pigs fly.',
      ornekTr: 'Odasını balık kavağa çıkınca toplar.',
      not: 'İmkânsızlığı esprili biçimde anlatır.',
    },
    /* --- Doğa anlatımında dil bilgisi tuzakları --- */
    {
      id: 'en-hay-91', on: 'a lot of animals', okunus: 'ı lot ıv enimılz', tur: 'kalıp',
      arka: 'çok sayıda hayvan',
      ornek: 'A lot of animals live in this forest.',
      ornekTr: 'Bu ormanda çok sayıda hayvan yaşar.',
      not: '"A lot of" hem sayılabilir hem sayılamayanla kullanılır.',
    },
    {
      id: 'en-hay-92', on: 'fewer / less', okunus: 'fyuır / les', tur: 'ayrım',
      arka: 'daha az (sayılabilir / sayılamayan)',
      ornek: 'Fewer birds and less rain this year.',
      ornekTr: 'Bu yıl daha az kuş ve daha az yağmur.',
      not: 'Sayabiliyorsan "fewer", sayamıyorsan "less". Sınav klasiğidir.',
    },
    {
      id: 'en-hay-93', on: 'used to', okunus: 'yustu', tur: 'kalıp',
      arka: 'eskiden ... yapardı',
      ornek: 'There used to be more forests here.',
      ornekTr: 'Eskiden burada daha çok orman vardı.',
      not: 'Geçmişteki alışkanlığı anlatır; sonrasında yalın fiil gelir.',
    },
    {
      id: 'en-hay-94', on: 'is likely to', okunus: 'iz laykli tu', tur: 'kalıp',
      arka: 'olması muhtemel',
      ornek: 'Temperatures are likely to rise.',
      ornekTr: 'Sıcaklıkların yükselmesi muhtemel.',
      not: 'Bilimsel metinlerde tahmin bildirmenin standart yoludur.',
    },
    {
      id: 'en-hay-95', on: 'due to', okunus: 'dyu tu', tur: 'edat',
      arka: '... nedeniyle',
      ornek: 'Many species are disappearing due to pollution.',
      ornekTr: 'Kirlilik nedeniyle birçok tür yok oluyor.',
      not: 'Sonrasında isim gelir, cümle gelmez: "due to the fact that" istisnadır.',
    },
    {
      id: 'en-hay-96', on: 'as a result', okunus: 'ez ı rizalt', tur: 'bağlaç',
      arka: 'sonuç olarak',
      ornek: 'The ice is melting; as a result, sea levels are rising.',
      ornekTr: 'Buzlar eriyor; sonuç olarak deniz seviyeleri yükseliyor.',
      not: 'Yazma bölümünde sebep-sonuç kurmanın en net yoludur.',
    },
    {
      id: 'en-hay-97', on: 'in danger of', okunus: 'in deyncır ıv', tur: 'kalıp',
      arka: '... tehlikesiyle karşı karşıya',
      ornek: 'This species is in danger of extinction.',
      ornekTr: 'Bu tür yok olma tehlikesiyle karşı karşıya.',
      not: 'Edatı "of"tur.',
    },
    {
      id: 'en-hay-98', on: 'take action', okunus: 'teyk ekşın', tur: 'eş dizim',
      arka: 'harekete geçmek',
      ornek: 'We must take action now.',
      ornekTr: 'Şimdi harekete geçmeliyiz.',
      not: '"Make action" YANLIŞTIR. Doğru fiil "take"tir.',
    },
    {
      id: 'en-hay-99', on: 'make a difference', okunus: 'meyk ı difrıns', tur: 'eş dizim',
      arka: 'fark yaratmak',
      ornek: 'Small changes can make a difference.',
      ornekTr: 'Küçük değişiklikler fark yaratabilir.',
      not: 'Kompozisyon sonucu için güçlü bir kapanış cümlesidir.',
    },
    {
      id: 'en-hay-100', on: 'protect the environment', okunus: 'prıtekt di invayrınmınt', tur: 'eş dizim',
      arka: 'çevreyi korumak',
      ornek: 'Everyone should protect the environment.',
      ornekTr: 'Herkes çevreyi korumalı.',
      not: '"Environment" daima "the" ile kullanılır.',
    },
  ],
}

export default DESTE
