/**
 * DESTE — MÜZİK, DİZİ VE FİLM (İngilizce)
 *
 * Öğrenci bu alanda zaten çok İngilizce duyuyor ama duyduğunu YANLIŞ
 * hatırlıyor. Kartlar bu yüzden ağırlıklı olarak öbek fiiller ve
 * kalıplardan seçildi: dizi konuşmalarının dili budur.
 */

export const DESTE = {
  id: 'muzik-dizi',
  dil: 'en',
  ad: 'Müzik, dizi ve film',
  simge: '🎬',
  aciklama: 'Dizi konuşmalarında ve şarkı sözlerinde geçen kalıplar.',
  seviye: 'A2–B1',
  kartlar: [
    {
      id: 'en-muz-01', on: 'binge-watch', okunus: 'binc voç', tur: 'fiil',
      arka: 'arka arkaya izlemek',
      ornek: 'I binge-watched the whole season in two days.',
      ornekTr: 'Bütün sezonu iki günde arka arkaya izledim.',
      not: 'Yeni bir kelime ama artık tamamen standart.',
    },
    {
      id: 'en-muz-02', on: 'spoiler', okunus: 'spoylır', tur: 'isim',
      arka: 'sonu açık eden bilgi',
      ornek: 'Do not tell me the ending, no spoilers!',
      ornekTr: 'Sonunu söyleme, spoiler yok!',
      not: '"spoil" bozmak demektir; keyfi bozan bilgi.',
    },
    {
      id: 'en-muz-03', on: 'catchy', okunus: 'keçi', tur: 'sıfat',
      arka: 'akılda kalıcı (şarkı)',
      ornek: 'That chorus is really catchy.',
      ornekTr: 'O nakarat gerçekten akılda kalıcı.',
      not: '"catch" (yakalamak) fiilinden gelir: kulağı yakalayan.',
    },
    {
      id: 'en-muz-04', on: 'the lyrics', okunus: 'dı liriks', tur: 'isim (çoğul)',
      arka: 'şarkı sözleri',
      ornek: 'I looked up the lyrics because I could not understand them.',
      ornekTr: 'Anlayamadığım için şarkı sözlerine baktım.',
      not: 'Her zaman çoğuldur. Tekil "lyric" edebiyat terimidir.',
    },
    {
      id: 'en-muz-05', on: 'come out', okunus: 'kam aut', tur: 'öbek fiil',
      arka: 'çıkmak (yayımlanmak)',
      ornek: 'Their new album comes out next Friday.',
      ornekTr: 'Yeni albümleri gelecek cuma çıkıyor.',
      not: '"be released" ile aynı anlamda ama çok daha günlük.',
    },
    {
      id: 'en-muz-06', on: 'turn out', okunus: 'törn aut', tur: 'öbek fiil',
      arka: 'meğerse … çıkmak',
      ornek: 'It turned out that he was the killer.',
      ornekTr: 'Meğerse katil oymuş.',
      not: 'Dizi konuşmalarının en sık öbeklerinden.',
    },
    {
      id: 'en-muz-07', on: 'the plot', okunus: 'dı plot', tur: 'isim',
      arka: 'konu, olay örgüsü',
      ornek: 'The plot gets confusing in the second season.',
      ornekTr: 'İkinci sezonda konu karışıyor.',
      not: 'Karakter "character", sahne "scene", bölüm "episode".',
    },
    {
      id: 'en-muz-08', on: 'be based on', okunus: 'bi beysd on', tur: 'kalıp',
      arka: '-e dayanmak, -den uyarlanmak',
      ornek: 'The film is based on a true story.',
      ornekTr: 'Film gerçek bir hikâyeye dayanıyor.',
      not: 'Edat "on"dur: "based ON", "based in" değil.',
    },
    {
      id: 'en-muz-09', on: 'overrated', okunus: 'ouvırreytid', tur: 'sıfat',
      arka: 'hak ettiğinden fazla övülen',
      ornek: 'Honestly, that series is a bit overrated.',
      ornekTr: 'Açıkçası o dizi biraz fazla övülüyor.',
      not: 'Karşıtı "underrated" (hak ettiği değeri görmeyen).',
    },
    {
      id: 'en-muz-10', on: 'I am hooked', okunus: 'ay em hukd', tur: 'kalıp',
      arka: 'bağımlısı oldum, kaptırdım',
      ornek: 'I watched one episode and now I am hooked.',
      ornekTr: 'Bir bölüm izledim, şimdi kaptırdım.',
      not: '"hook" olta kancasıdır; kancaya takılmak anlamı taşır.',
    },
    /* --- Şarkı ve albüm dili --- */
    {
      id: 'en-muz-11', on: 'release an album', okunus: 'riliis ın elbım', tur: 'eş dizim',
      arka: 'albüm çıkarmak',
      ornek: 'The band released a new album last month.',
      ornekTr: 'Grup geçen ay yeni bir albüm çıkardı.',
      not: '"Publish an album" YANLIŞTIR. Müzikte doğru fiil "release"tir.',
    },
    {
      id: 'en-muz-12', on: 'single', okunus: 'singıl', tur: 'isim',
      arka: 'tekli şarkı',
      ornek: 'Their first single became a huge hit.',
      ornekTr: 'İlk teklileri büyük bir hit oldu.',
      not: 'Aynı kelime "bekâr" ve "tek kişilik" anlamlarına da gelir.',
    },
    {
      id: 'en-muz-13', on: 'track', okunus: 'trek', tur: 'isim',
      arka: 'albümdeki parça',
      ornek: 'The third track is my favourite.',
      ornekTr: 'Üçüncü parça favorim.',
      not: 'Sporda "track" koşu pistidir; bağlam ayırır.',
    },
    {
      id: 'en-muz-14', on: 'lyrics', okunus: 'liriks', tur: 'isim (çoğul)',
      arka: 'şarkı sözleri',
      ornek: 'I do not understand the lyrics of this song.',
      ornekTr: 'Bu şarkının sözlerini anlamıyorum.',
      not: 'Her zaman çoğuldur: "a lyric" tek başına kullanılmaz.',
    },
    {
      id: 'en-muz-15', on: 'chorus', okunus: 'korıs', tur: 'isim',
      arka: 'nakarat',
      ornek: 'Everyone sings along in the chorus.',
      ornekTr: 'Nakaratta herkes eşlik ediyor.',
      not: 'Nakarat arası bölümler "verse"tür.',
    },
    {
      id: 'en-muz-16', on: 'catchy', okunus: 'keçi', tur: 'sıfat',
      arka: 'akılda kalıcı (melodi)',
      ornek: 'It is a very catchy tune.',
      ornekTr: 'Çok akılda kalıcı bir melodi.',
      not: 'Sadece melodi ve slogan için kullanılır, insan için kullanılmaz.',
    },
    {
      id: 'en-muz-17', on: 'cover', okunus: 'kavır', tur: 'isim / fiil',
      arka: 'başka birinin şarkısını yeniden yorumlamak',
      ornek: 'She covered an old Turkish song.',
      ornekTr: 'Eski bir Türkçe şarkıyı yeniden yorumladı.',
      not: 'Aynı kelime "kapak" ve "örtmek" anlamlarına da gelir.',
    },
    {
      id: 'en-muz-18', on: 'be in the charts', okunus: 'bi in dı çarts', tur: 'kalıp',
      arka: 'listelerde olmak',
      ornek: 'Their song has been in the charts for ten weeks.',
      ornekTr: 'Şarkıları on haftadır listelerde.',
      not: 'Zirve için "top the charts" = listelerin başına geçmek.',
    },
    {
      id: 'en-muz-19', on: 'hit', okunus: 'hit', tur: 'isim',
      arka: 'çok tutulan şarkı ya da film',
      ornek: 'That film was a big hit in Turkey.',
      ornekTr: 'O film Türkiye\'de büyük bir hit oldu.',
      not: 'Fiil hâli "vurmak"tır. İsim olarak başarı anlamı taşır.',
    },
    {
      id: 'en-muz-20', on: 'tune', okunus: 'tyun', tur: 'isim',
      arka: 'melodi, ezgi',
      ornek: 'I cannot remember the words but I know the tune.',
      ornekTr: 'Sözleri hatırlamıyorum ama melodiyi biliyorum.',
      not: '"Song" sözlü bütün, "tune" melodinin kendisidir.',
    },
    /* --- Dinleme alışkanlıkları --- */
    {
      id: 'en-muz-21', on: 'stream', okunus: 'striim', tur: 'fiil / isim',
      arka: 'internetten dinlemek/izlemek',
      ornek: 'I stream music on my phone every day.',
      ornekTr: 'Her gün telefonumdan müzik dinliyorum.',
      not: 'Kelimenin ilk anlamı "dere"dir; veri akışı için ödünç alınmıştır.',
    },
    {
      id: 'en-muz-22', on: 'playlist', okunus: 'pleylist', tur: 'isim',
      arka: 'çalma listesi',
      ornek: 'I made a playlist for studying.',
      ornekTr: 'Ders çalışmak için bir çalma listesi yaptım.',
      not: 'Liste "yapılır" (make/create a playlist).',
    },
    {
      id: 'en-muz-23', on: 'on repeat', okunus: 'on ripiit', tur: 'kalıp',
      arka: 'sürekli tekrar tekrar (dinlemek)',
      ornek: 'That song has been on repeat all week.',
      ornekTr: 'O şarkı bütün hafta tekrar tekrar çaldı.',
      not: 'Edat "on"dur: "in repeat" YANLIŞTIR.',
    },
    {
      id: 'en-muz-24', on: 'turn it up', okunus: 'törn it ap', tur: 'öbek fiil',
      arka: 'sesi açmak',
      ornek: 'I love this song, turn it up!',
      ornekTr: 'Bu şarkıya bayılıyorum, sesi aç!',
      not: 'Tersi "turn it down" = sesi kısmak.',
    },
    {
      id: 'en-muz-25', on: 'headphones', okunus: 'hedfounz', tur: 'isim (çoğul)',
      arka: 'kulaklık',
      ornek: 'He never goes out without his headphones.',
      ornekTr: 'Kulaklığı olmadan asla dışarı çıkmaz.',
      not: 'Çoğuldur. Kulak içi olanlara "earphones/earbuds" denir.',
    },
    {
      id: 'en-muz-26', on: 'live', okunus: 'layv', tur: 'sıfat / zarf',
      arka: 'canlı (performans)',
      ornek: 'I have never seen them live.',
      ornekTr: 'Onları hiç canlı izlemedim.',
      not: 'Sıfat "layv", fiil hâli ("yaşamak") "liv" okunur.',
    },
    {
      id: 'en-muz-27', on: 'gig', okunus: 'gig', tur: 'isim',
      arka: 'küçük konser',
      ornek: 'They played a gig at a small club.',
      ornekTr: 'Küçük bir kulüpte konser verdiler.',
      not: 'Büyük olan "concert"tir; "gig" gündelik ve samimidir.',
    },
    {
      id: 'en-muz-28', on: 'go on tour', okunus: 'gou on tur', tur: 'eş dizim',
      arka: 'turneye çıkmak',
      ornek: 'The band is going on tour next summer.',
      ornekTr: 'Grup gelecek yaz turneye çıkıyor.',
      not: 'Turne sırasında olmak için "be on tour" denir.',
    },
    {
      id: 'en-muz-29', on: 'sing along', okunus: 'sing ılong', tur: 'öbek fiil',
      arka: 'şarkıya eşlik etmek',
      ornek: 'The whole crowd sang along.',
      ornekTr: 'Bütün seyirci şarkıya eşlik etti.',
      not: '"Along" birlikte yapma anlamı katar: dance along, play along.',
    },
    {
      id: 'en-muz-30', on: 'be into a band', okunus: 'bi intu ı bend', tur: 'kalıp',
      arka: 'bir gruba meraklı olmak',
      ornek: 'I am really into this band at the moment.',
      ornekTr: 'Şu sıralar bu gruba çok takıldım.',
      not: 'Zevkleri anlatmanın en doğal yolu budur.',
    },
    /* --- Dizi ve film yapısı --- */
    {
      id: 'en-muz-31', on: 'episode', okunus: 'episoud', tur: 'isim',
      arka: 'bölüm',
      ornek: 'The last episode was two hours long.',
      ornekTr: 'Son bölüm iki saatti.',
      not: 'Sezon "season", tüm dizi "series"tir. Üçünü karıştırma.',
    },
    {
      id: 'en-muz-32', on: 'season', okunus: 'siizın', tur: 'isim',
      arka: 'sezon',
      ornek: 'Season three comes out in April.',
      ornekTr: 'Üçüncü sezon nisanda çıkıyor.',
      not: 'İngiltere\'de bazen "series" sezon anlamında kullanılır.',
    },
    {
      id: 'en-muz-33', on: 'plot', okunus: 'plot', tur: 'isim',
      arka: 'olay örgüsü, konu',
      ornek: 'The plot is confusing at the beginning.',
      ornekTr: 'Olay örgüsü başlangıçta kafa karıştırıcı.',
      not: '"Subject" konuyu, "plot" olayların akışını anlatır.',
    },
    {
      id: 'en-muz-34', on: 'spoiler', okunus: 'spoylır', tur: 'isim',
      arka: 'sürprizi bozan bilgi',
      ornek: 'Do not tell me, no spoilers!',
      ornekTr: 'Söyleme, sürprizi bozma!',
      not: 'Fiili "spoil" = bozmak, mahvetmek.',
    },
    {
      id: 'en-muz-35', on: 'subtitles', okunus: 'sabtaytıls', tur: 'isim (çoğul)',
      arka: 'altyazı',
      ornek: 'I watch films with English subtitles.',
      ornekTr: 'Filmleri İngilizce altyazıyla izliyorum.',
      not: 'Dil öğrenirken en etkili yol: ses ve altyazı aynı dilde olsun.',
    },
    {
      id: 'en-muz-36', on: 'dubbed', okunus: 'dabd', tur: 'sıfat',
      arka: 'dublajlı',
      ornek: 'I hate watching dubbed films.',
      ornekTr: 'Dublajlı film izlemekten nefret ediyorum.',
      not: 'Orijinal sesli olan "in the original language"dır.',
    },
    {
      id: 'en-muz-37', on: 'the cast', okunus: 'dı kast', tur: 'isim',
      arka: 'oyuncu kadrosu',
      ornek: 'The cast is full of famous actors.',
      ornekTr: 'Oyuncu kadrosu ünlü oyuncularla dolu.',
      not: 'Tek oyuncu "an actor", kadronun tamamı "the cast"tir.',
    },
    {
      id: 'en-muz-38', on: 'character', okunus: 'kerıktır', tur: 'isim',
      arka: 'karakter (film/kitaptaki kişi)',
      ornek: 'My favourite character dies in season two.',
      ornekTr: 'Favori karakterim ikinci sezonda ölüyor.',
      not: 'Aynı kelime kişilik anlamına da gelir: "She has a strong character."',
    },
    {
      id: 'en-muz-39', on: 'director', okunus: 'dayrektır', tur: 'isim',
      arka: 'yönetmen',
      ornek: 'The director won an award for this film.',
      ornekTr: 'Yönetmen bu filmle ödül kazandı.',
      not: 'Şirket müdürü için de aynı kelime kullanılır.',
    },
    {
      id: 'en-muz-40', on: 'soundtrack', okunus: 'saundtrek', tur: 'isim',
      arka: 'film müziği',
      ornek: 'The soundtrack is better than the film.',
      ornekTr: 'Film müziği filmden daha iyi.',
      not: '"Score" da denir ama o daha çok orkestra müziğidir.',
    },
    /* --- Türler --- */
    {
      id: 'en-muz-41', on: 'comedy', okunus: 'komıdi', tur: 'isim',
      arka: 'komedi',
      ornek: 'I prefer comedies to horror films.',
      ornekTr: 'Korku filmlerine komedileri tercih ederim.',
      not: '"Prefer A to B" kalıbında edat "to"dur, "than" değil.',
    },
    {
      id: 'en-muz-42', on: 'thriller', okunus: 'trilır', tur: 'isim',
      arka: 'gerilim filmi',
      ornek: 'It is a thriller about a missing girl.',
      ornekTr: 'Kayıp bir kızla ilgili bir gerilim filmi.',
      not: '"Thrill" heyecan demektir; korkudan çok gerilim anlatır.',
    },
    {
      id: 'en-muz-43', on: 'sci-fi', okunus: 'say fay', tur: 'isim',
      arka: 'bilim kurgu',
      ornek: 'He only watches sci-fi.',
      ornekTr: 'Sadece bilim kurgu izliyor.',
      not: '"Science fiction"ın kısaltmasıdır, konuşmada bu hâli kullanılır.',
    },
    {
      id: 'en-muz-44', on: 'documentary', okunus: 'dokyumentıri', tur: 'isim',
      arka: 'belgesel',
      ornek: 'We watched a documentary about the ocean.',
      ornekTr: 'Okyanusla ilgili bir belgesel izledik.',
      not: 'Konu edatı "about"tur: a documentary about/on something.',
    },
    {
      id: 'en-muz-45', on: 'animation', okunus: 'enimeyşın', tur: 'isim',
      arka: 'animasyon',
      ornek: 'This animation is not only for children.',
      ornekTr: 'Bu animasyon sadece çocuklar için değil.',
      not: 'Japon animasyonu için ayrıca "anime" kullanılır.',
    },
    {
      id: 'en-muz-46', on: 'horror film', okunus: 'horır film', tur: 'isim',
      arka: 'korku filmi',
      ornek: 'I cannot sleep after horror films.',
      ornekTr: 'Korku filmlerinden sonra uyuyamıyorum.',
      not: 'Amerika\'da "movie", İngiltere\'de "film" denir.',
    },
    {
      id: 'en-muz-47', on: 'rom-com', okunus: 'rom kom', tur: 'isim',
      arka: 'romantik komedi',
      ornek: 'We watched a rom-com on Friday night.',
      ornekTr: 'Cuma akşamı bir romantik komedi izledik.',
      not: '"Romantic comedy"nin gündelik kısaltmasıdır.',
    },
    {
      id: 'en-muz-48', on: 'sequel', okunus: 'siikuıl', tur: 'isim',
      arka: 'devam filmi',
      ornek: 'The sequel was worse than the first film.',
      ornekTr: 'Devam filmi ilkinden kötüydü.',
      not: 'Öncesini anlatan film ise "prequel"dir.',
    },
    {
      id: 'en-muz-49', on: 'based on a true story', okunus: 'beysd on ı tru stori', tur: 'kalıp',
      arka: 'gerçek bir olaydan uyarlanmış',
      ornek: 'The film is based on a true story.',
      ornekTr: 'Film gerçek bir olaydan uyarlanmış.',
      not: 'Kitaptan uyarlama için "based on a novel" denir.',
    },
    {
      id: 'en-muz-50', on: 'cliffhanger', okunus: 'klifhengır', tur: 'isim',
      arka: 'merak uyandıran bölüm sonu',
      ornek: 'The season ended on a cliffhanger.',
      ornekTr: 'Sezon merak uyandıran bir sahneyle bitti.',
      not: 'Kelime "uçurumdan sarkan" anlamından gelir.',
    },
    /* --- İzleme alışkanlıkları --- */
    {
      id: 'en-muz-51', on: 'binge-watch', okunus: 'binc voç', tur: 'fiil',
      arka: 'arka arkaya bölüm izlemek',
      ornek: 'I binge-watched the whole season in two days.',
      ornekTr: 'Bütün sezonu iki günde arka arkaya izledim.',
      not: 'Yeni bir kelimedir, dizi platformlarıyla yaygınlaştı.',
    },
    {
      id: 'en-muz-52', on: 'trailer', okunus: 'treylır', tur: 'isim',
      arka: 'fragman',
      ornek: 'The trailer looks amazing.',
      ornekTr: 'Fragman harika görünüyor.',
      not: 'Aynı kelime "römork" anlamına da gelir.',
    },
    {
      id: 'en-muz-53', on: 'come out', okunus: 'kam aut', tur: 'öbek fiil',
      arka: 'çıkmak (yayımlanmak)',
      ornek: 'The new film comes out in June.',
      ornekTr: 'Yeni film haziranda çıkıyor.',
      not: 'Film, kitap ve albüm için kullanılır. Resmî hâli "be released"tir.',
    },
    {
      id: 'en-muz-54', on: 'recommend', okunus: 'rekımend', tur: 'fiil',
      arka: 'tavsiye etmek',
      ornek: 'I recommend this series to everyone.',
      ornekTr: 'Bu diziyi herkese tavsiye ediyorum.',
      not: '"Recommend me a film" yerine "recommend a film to me" doğrudur.',
    },
    {
      id: 'en-muz-55', on: 'review', okunus: 'rivyu', tur: 'isim / fiil',
      arka: 'eleştiri yazısı; değerlendirmek',
      ornek: 'The reviews were very positive.',
      ornekTr: 'Eleştiriler çok olumluydu.',
      not: 'Ders tekrarı anlamına da gelir: "review your notes".',
    },
    {
      id: 'en-muz-56', on: 'rate', okunus: 'reyt', tur: 'fiil',
      arka: 'puan vermek',
      ornek: 'I would rate it eight out of ten.',
      ornekTr: 'Ona on üzerinden sekiz veririm.',
      not: 'Puan kalıbı "out of"tur: eight out of ten.',
    },
    {
      id: 'en-muz-57', on: 'turn out to be', okunus: 'törn aut tu bi', tur: 'kalıp',
      arka: 'sonradan öyle olduğu anlaşılmak',
      ornek: 'The film turned out to be really good.',
      ornekTr: 'Film sonradan gerçekten iyi çıktı.',
      not: 'Beklenti ile sonucun farklı olduğunu anlatır.',
    },
    {
      id: 'en-muz-58', on: 'give it a go', okunus: 'giv it ı gou', tur: 'deyim',
      arka: 'bir şans vermek, denemek',
      ornek: 'It is not my type of film, but I always give it a go.',
      ornekTr: 'Benim tarzım değil ama yine de her zaman bir şans veririm.',
      not: '"Give it a try" ile aynıdır.',
    },
    {
      id: 'en-muz-59', on: 'not my thing', okunus: 'not may ting', tur: 'kalıp',
      arka: 'benim tarzım değil',
      ornek: 'Musicals are not really my thing.',
      ornekTr: 'Müzikaller pek benim tarzım değil.',
      not: 'Kibar bir beğenmeme ifadesidir; "I hate it" kadar sert değildir.',
    },
    {
      id: 'en-muz-60', on: 'can\'t stand', okunus: 'kant stend', tur: 'kalıp',
      arka: 'hiç katlanamamak',
      ornek: 'I cannot stand loud music in the morning.',
      ornekTr: 'Sabahları yüksek sesli müziğe hiç katlanamıyorum.',
      not: 'Sonrasında -ing gelir: "cannot stand waiting".',
    },
    /* --- Yorum sıfatları --- */
    {
      id: 'en-muz-61', on: 'moving', okunus: 'muving', tur: 'sıfat',
      arka: 'duygulandırıcı',
      ornek: 'It was a very moving story.',
      ornekTr: 'Çok duygulandırıcı bir hikâyeydi.',
      not: 'Kişi için "moved" kullanılır: "I was moved by the film."',
    },
    {
      id: 'en-muz-62', on: 'predictable', okunus: 'pridiktıbıl', tur: 'sıfat',
      arka: 'tahmin edilebilir, sürprizsiz',
      ornek: 'The ending was completely predictable.',
      ornekTr: 'Son tamamen tahmin edilebilirdi.',
      not: 'Fiili "predict" = tahmin etmek.',
    },
    {
      id: 'en-muz-63', on: 'hilarious', okunus: 'hileriıs', tur: 'sıfat',
      arka: 'çok komik',
      ornek: 'That scene was absolutely hilarious.',
      ornekTr: 'O sahne kesinlikle çok komikti.',
      not: '"Funny"den daha güçlüdür; "very hilarious" denmez, zaten uçtur.',
    },
    {
      id: 'en-muz-64', on: 'creepy', okunus: 'kriipi', tur: 'sıfat',
      arka: 'tüyler ürpertici',
      ornek: 'The house in that film is really creepy.',
      ornekTr: 'O filmdeki ev gerçekten tüyler ürpertici.',
      not: 'Korkudan çok rahatsızlık verici bir his anlatır.',
    },
    {
      id: 'en-muz-65', on: 'stunning', okunus: 'staning', tur: 'sıfat',
      arka: 'nefes kesici (görsel olarak)',
      ornek: 'The scenery in the film is stunning.',
      ornekTr: 'Filmdeki manzara nefes kesici.',
      not: 'Genellikle görüntü, manzara ve tasarım için kullanılır.',
    },
    {
      id: 'en-muz-66', on: 'overrated', okunus: 'ouvırreytid', tur: 'sıfat',
      arka: 'hak ettiğinden fazla övülen',
      ornek: 'Honestly, that series is overrated.',
      ornekTr: 'Açıkçası o dizi hak ettiğinden fazla övülüyor.',
      not: 'Tersi "underrated" = hak ettiği değeri görmeyen.',
    },
    {
      id: 'en-muz-67', on: 'gripping', okunus: 'griping', tur: 'sıfat',
      arka: 'ekrandan koparmayan, sürükleyici',
      ornek: 'The first episode is really gripping.',
      ornekTr: 'İlk bölüm gerçekten sürükleyici.',
      not: '"Grip" tutmak demektir; kelime "seni tutar" imgesinden gelir.',
    },
    {
      id: 'en-muz-68', on: 'slow-paced', okunus: 'slou peysd', tur: 'sıfat',
      arka: 'ağır tempolu',
      ornek: 'The middle part is a bit slow-paced.',
      ornekTr: 'Orta bölüm biraz ağır tempolu.',
      not: 'Tersi "fast-paced"tir. "Pace" tempo demektir.',
    },
    {
      id: 'en-muz-69', on: 'well-written', okunus: 'vel ritın', tur: 'sıfat',
      arka: 'iyi yazılmış',
      ornek: 'The dialogue is very well-written.',
      ornekTr: 'Diyaloglar çok iyi yazılmış.',
      not: 'Aynı kalıpla: well-made, well-acted, well-known.',
    },
    {
      id: 'en-muz-70', on: 'worth watching', okunus: 'vört voçing', tur: 'kalıp',
      arka: 'izlemeye değer',
      ornek: 'It is long but definitely worth watching.',
      ornekTr: 'Uzun ama kesinlikle izlemeye değer.',
      not: '"Worth" sonrası daima -ing gelir: worth reading, worth trying.',
    },
    /* --- Enstrüman ve müzik yapma --- */
    {
      id: 'en-muz-71', on: 'play the guitar', okunus: 'pley dı gitar', tur: 'eş dizim',
      arka: 'gitar çalmak',
      ornek: 'She has played the guitar since she was six.',
      ornekTr: 'Altı yaşından beri gitar çalıyor.',
      not: 'Enstrümanlarda "the" kullanılır: play the piano, play the violin.',
    },
    {
      id: 'en-muz-72', on: 'drums', okunus: 'dramz', tur: 'isim (çoğul)',
      arka: 'bateri',
      ornek: 'My brother plays the drums in a band.',
      ornekTr: 'Kardeşim bir grupta bateri çalıyor.',
      not: 'Bateri her zaman çoğuldur; tek davul "a drum"dır.',
    },
    {
      id: 'en-muz-73', on: 'take lessons', okunus: 'teyk lesınz', tur: 'eş dizim',
      arka: 'ders almak',
      ornek: 'I take piano lessons on Saturdays.',
      ornekTr: 'Cumartesileri piyano dersi alıyorum.',
      not: 'Ders "alınır" (take), öğretmen "verir" (give).',
    },
    {
      id: 'en-muz-74', on: 'practise', okunus: 'prektis', tur: 'fiil',
      arka: 'çalışmak, alıştırma yapmak',
      ornek: 'You have to practise every day.',
      ornekTr: 'Her gün çalışman gerekiyor.',
      not: 'İngiltere\'de fiil "practise", isim "practice" yazılır.',
    },
    {
      id: 'en-muz-75', on: 'be tone-deaf', okunus: 'bi toun def', tur: 'kalıp',
      arka: 'müzik kulağı olmamak',
      ornek: 'I love singing but I am tone-deaf.',
      ornekTr: 'Şarkı söylemeyi seviyorum ama müzik kulağım yok.',
      not: 'Şaka yollu kendini anlatmak için sık kullanılır.',
    },
    {
      id: 'en-muz-76', on: 'in tune', okunus: 'in tyun', tur: 'kalıp',
      arka: 'akortlu, doğru perdeden',
      ornek: 'The guitar is not in tune.',
      ornekTr: 'Gitar akortlu değil.',
      not: 'Tersi "out of tune"dur.',
    },
    {
      id: 'en-muz-77', on: 'band', okunus: 'bend', tur: 'isim',
      arka: 'müzik grubu',
      ornek: 'They started a band at school.',
      ornekTr: 'Okulda bir grup kurdular.',
      not: 'Grup "kurulur": start/form a band.',
    },
    {
      id: 'en-muz-78', on: 'perform', okunus: 'pırform', tur: 'fiil',
      arka: 'sahne almak, icra etmek',
      ornek: 'They performed in front of 5,000 people.',
      ornekTr: 'Beş bin kişinin önünde sahne aldılar.',
      not: 'İsmi "a performance"tır; sınavlarda "performans" anlamıyla da geçer.',
    },
    {
      id: 'en-muz-79', on: 'audience', okunus: 'odiıns', tur: 'isim',
      arka: 'izleyici topluluğu',
      ornek: 'The audience clapped for five minutes.',
      ornekTr: 'İzleyiciler beş dakika alkışladı.',
      not: 'Topluluk ismidir; tekil görünse de insan grubunu anlatır.',
    },
    {
      id: 'en-muz-80', on: 'stage fright', okunus: 'steyc frayt', tur: 'isim',
      arka: 'sahne korkusu',
      ornek: 'She gets stage fright before every concert.',
      ornekTr: 'Her konserden önce sahne korkusu yaşıyor.',
      not: 'Fiili "get"tir: get stage fright.',
    },
    /* --- Müzik ve sahneden doğmuş deyimler --- */
    {
      id: 'en-muz-81', on: 'face the music', okunus: 'feys dı myuzik', tur: 'deyim',
      arka: 'sonuçlarına katlanmak',
      ornek: 'He broke the window and had to face the music.',
      ornekTr: 'Camı kırdı ve sonuçlarına katlanmak zorunda kaldı.',
      not: 'Müzik dinlemekle ilgisi yoktur; hesap vermeyi anlatır.',
    },
    {
      id: 'en-muz-82', on: 'ring a bell', okunus: 'ring ı bel', tur: 'deyim',
      arka: 'kulağa tanıdık gelmek',
      ornek: 'That name rings a bell.',
      ornekTr: 'O isim kulağa tanıdık geliyor.',
      not: 'Tam hatırlamadığını ama tanıdık geldiğini anlatır.',
    },
    {
      id: 'en-muz-83', on: 'steal the show', okunus: 'stiil dı şou', tur: 'deyim',
      arka: 'bütün ilgiyi toplamak',
      ornek: 'The young actor stole the show.',
      ornekTr: 'Genç oyuncu bütün ilgiyi topladı.',
      not: 'Olumlu bir ifadedir, hırsızlıkla ilgisi yoktur.',
    },
    {
      id: 'en-muz-84', on: 'behind the scenes', okunus: 'bihaynd dı siinz', tur: 'deyim',
      arka: 'perde arkasında',
      ornek: 'A lot of work happens behind the scenes.',
      ornekTr: 'Perde arkasında çok iş dönüyor.',
      not: 'Kamera arkası görüntüleri için de kullanılır.',
    },
    {
      id: 'en-muz-85', on: 'play it by ear', okunus: 'pley it bay ir', tur: 'deyim',
      arka: 'duruma göre karar vermek',
      ornek: 'We do not have a plan, we will play it by ear.',
      ornekTr: 'Planımız yok, duruma göre karar veririz.',
      not: 'Notasız, kulaktan çalmak imgesinden gelir.',
    },
    {
      id: 'en-muz-86', on: 'jump on the bandwagon', okunus: 'camp on dı bendvegın', tur: 'deyim',
      arka: 'popüler olana sonradan katılmak',
      ornek: 'Everyone jumped on the bandwagon after they won.',
      ornekTr: 'Kazandıktan sonra herkes o tarafa geçti.',
      not: 'Hafif alaycı bir anlam taşır.',
    },
    {
      id: 'en-muz-87', on: 'blow someone away', okunus: 'blou samvan ıvey', tur: 'deyim',
      arka: 'birini çok etkilemek',
      ornek: 'The ending blew me away.',
      ornekTr: 'Final beni çok etkiledi.',
      not: 'Şaşkınlıkla karışık hayranlığı anlatır.',
    },
    {
      id: 'en-muz-88', on: 'a blockbuster', okunus: 'ı blokbastır', tur: 'isim',
      arka: 'gişe rekortmeni film',
      ornek: 'It was the blockbuster of the summer.',
      ornekTr: 'Yazın gişe rekortmeni filmiydi.',
      not: 'Sadece çok satan filmler için kullanılır.',
    },
    {
      id: 'en-muz-89', on: 'go viral', okunus: 'gou vayrıl', tur: 'kalıp',
      arka: 'internette hızla yayılmak',
      ornek: 'Their video went viral in one night.',
      ornekTr: 'Videoları bir gecede internette yayıldı.',
      not: '"Virus" kelimesinden gelir: hızla bulaşma imgesi.',
    },
    {
      id: 'en-muz-90', on: 'be hooked on', okunus: 'bi hukd on', tur: 'kalıp',
      arka: 'bir şeye bağlanmak, kaptırmak',
      ornek: 'I am completely hooked on this series.',
      ornekTr: 'Bu diziye tamamen kaptırdım.',
      not: 'Edatı "on"dur ve sonrasında isim ya da -ing gelir.',
    },
    /* --- Konuşmada zevk anlatma --- */
    {
      id: 'en-muz-91', on: 'What are you into?', okunus: 'vot ar yu intu', tur: 'soru kalıbı',
      arka: 'Neye meraklısın?',
      ornek: 'What kind of music are you into?',
      ornekTr: 'Ne tür müziğe meraklısın?',
      not: 'Tanışma konuşmalarının en doğal sorularından biridir.',
    },
    {
      id: 'en-muz-92', on: 'I am more of a...', okunus: 'ay em mor ıv ı', tur: 'kalıp',
      arka: 'Ben daha çok ... tipiyim',
      ornek: 'I am more of a rock person.',
      ornekTr: 'Ben daha çok rock seven biriyim.',
      not: 'Kendi zevkini yumuşak bir dille anlatır.',
    },
    {
      id: 'en-muz-93', on: 'It depends', okunus: 'it dipendz', tur: 'kalıp',
      arka: 'Duruma göre değişir',
      ornek: 'It depends on my mood.',
      ornekTr: 'Ruh hâlime göre değişir.',
      not: 'Edatı "on"dur: "depend from" YANLIŞTIR.',
    },
    {
      id: 'en-muz-94', on: 'have a soft spot for', okunus: 'hev ı soft spot for', tur: 'deyim',
      arka: 'bir şeye zaafı olmak',
      ornek: 'I have a soft spot for old films.',
      ornekTr: 'Eski filmlere zaafım var.',
      not: 'Sevimli, itiraf niteliğinde bir ifadedir.',
    },
    {
      id: 'en-muz-95', on: 'grow on someone', okunus: 'grou on samvan', tur: 'öbek fiil',
      arka: 'zamanla sevilmeye başlamak',
      ornek: 'I did not like the song at first, but it is growing on me.',
      ornekTr: 'Şarkıyı önce sevmedim ama yavaş yavaş seviyorum.',
      not: 'Özne şarkıdır, kişi değil. Kalıbı bozma.',
    },
    {
      id: 'en-muz-96', on: 'get into', okunus: 'get intu', tur: 'öbek fiil',
      arka: 'bir şeye merak salmak',
      ornek: 'I got into jazz last year.',
      ornekTr: 'Geçen yıl caza merak saldım.',
      not: '"Be into" hâlihazırdaki ilgi, "get into" ilginin başlangıcıdır.',
    },
    {
      id: 'en-muz-97', on: 'stuck in my head', okunus: 'stak in may hed', tur: 'kalıp',
      arka: 'aklıma takıldı (şarkı)',
      ornek: 'That song has been stuck in my head all day.',
      ornekTr: 'O şarkı bütün gün aklıma takıldı.',
      not: 'Bu duruma İngilizcede "an earworm" da denir.',
    },
    {
      id: 'en-muz-98', on: 'look forward to', okunus: 'luk forvırd tu', tur: 'öbek fiil',
      arka: 'dört gözle beklemek',
      ornek: 'I am looking forward to the new season.',
      ornekTr: 'Yeni sezonu dört gözle bekliyorum.',
      not: 'Sonrasında -ing gelir: "looking forward to watching it".',
    },
    {
      id: 'en-muz-99', on: 'sound like', okunus: 'saund layk', tur: 'kalıp',
      arka: 'benzemek (kulağa)',
      ornek: 'This band sounds like an old Turkish group.',
      ornekTr: 'Bu grup eski bir Türk grubuna benziyor.',
      not: 'Duyusal fiiller "like" alır: look like, sound like, taste like.',
    },
    {
      id: 'en-muz-100', on: 'the same as', okunus: 'dı seym ez', tur: 'kalıp',
      arka: 'aynısı',
      ornek: 'Her taste in music is the same as mine.',
      ornekTr: 'Müzik zevki benimkiyle aynı.',
      not: '"Same with" YANLIŞTIR. Doğru edat "as"tir.',
    },
  ],
}

export default DESTE
