/**
 * DESTE — SEYAHAT VE ŞEHİR (İngilizce)
 *
 * Havaalanı ve otel İngilizcesi standarttır: aynı cümleler dünyanın her
 * yerinde duyulur. Bu destedeki kalıplar bir kez öğrenilirse ömür boyu
 * aynen işe yarar.
 */

export const DESTE = {
  id: 'seyahat',
  dil: 'en',
  ad: 'Seyahat ve şehir',
  simge: '✈️',
  aciklama: 'Havaalanında, otelde ve sokakta duyacağın standart kalıplar.',
  seviye: 'A2–B1',
  kartlar: [
    {
      id: 'en-sey-01', on: 'check in', okunus: 'çek in', tur: 'öbek fiil',
      arka: 'giriş işlemi yaptırmak',
      ornek: 'We need to check in two hours before the flight.',
      ornekTr: 'Uçuştan iki saat önce giriş yaptırmamız gerek.',
      not: 'Fiil ayrı, isim tireli: "the check-in desk".',
    },
    {
      id: 'en-sey-02', on: 'boarding pass', okunus: 'bording pes', tur: 'isim',
      arka: 'biniş kartı',
      ornek: 'Please have your boarding pass ready.',
      ornekTr: 'Lütfen biniş kartınızı hazır bulundurun.',
      not: 'Anonslarda en sık duyulan ifadelerden biri.',
    },
    {
      id: 'en-sey-03', on: 'luggage', okunus: 'lagic', tur: 'isim (sayılamayan)',
      arka: 'bagaj',
      ornek: 'I lost my luggage at the airport.',
      ornekTr: 'Bagajımı havaalanında kaybettim.',
      not: 'SAYILAMAZ: "a luggage" ve "luggages" YANLIŞTIR. "a piece of luggage" denir.',
    },
    {
      id: 'en-sey-04', on: 'get lost', okunus: 'get lost', tur: 'kalıp',
      arka: 'kaybolmak',
      ornek: 'We got lost on the way to the museum.',
      ornekTr: 'Müzeye giderken kaybolduk.',
      not: '"Get + sıfat" kalıbı: get tired, get ready, get lost.',
    },
    {
      id: 'en-sey-05', on: 'straight ahead', okunus: 'streyt ıhed', tur: 'kalıp',
      arka: 'dümdüz ileri',
      ornek: 'Go straight ahead and turn left at the lights.',
      ornekTr: 'Dümdüz git, ışıklardan sola dön.',
      not: 'Yol tarifinin üç kalıbı: straight ahead, turn left, turn right.',
    },
    {
      id: 'en-sey-06', on: 'How do I get to…?', okunus: 'hau du ay get tu', tur: 'kalıp',
      arka: '… nasıl giderim?',
      ornek: 'Excuse me, how do I get to the train station?',
      ornekTr: 'Affedersiniz, tren garına nasıl giderim?',
      not: 'Yol sormanın en doğal biçimi. "Where is…" daha kısadır ama tarif getirmez.',
    },
    {
      id: 'en-sey-07', on: 'book', okunus: 'buk', tur: 'fiil',
      arka: 'rezervasyon yaptırmak',
      ornek: 'I booked a room for three nights.',
      ornekTr: 'Üç gecelik oda ayırttım.',
      not: 'Aynı kelime "kitap" demektir; burada fiildir.',
    },
    {
      id: 'en-sey-08', on: 'delayed', okunus: 'dileyd', tur: 'sıfat',
      arka: 'rötarlı, gecikmiş',
      ornek: 'Our flight is delayed by two hours.',
      ornekTr: 'Uçuşumuz iki saat rötarlı.',
      not: 'İptal ise "cancelled". Havaalanı ekranlarında ikisi de yazar.',
    },
    {
      id: 'en-sey-09', on: 'sightseeing', okunus: 'saytsiing', tur: 'isim',
      arka: 'gezip görme, turistik gezi',
      ornek: 'We spent the whole day sightseeing.',
      ornekTr: 'Bütün günü gezerek geçirdik.',
      not: 'Kalıp hâli: "go sightseeing".',
    },
    {
      id: 'en-sey-10', on: 'jet lag', okunus: 'cet leg', tur: 'isim',
      arka: 'saat farkı yorgunluğu',
      ornek: 'I still have jet lag from the flight.',
      ornekTr: 'Uçuştan kalan saat farkı yorgunluğum hâlâ sürüyor.',
      not: 'Türkçede tam karşılığı yoktur; olduğu gibi kullanılır.',
    },
    /* --- Havalimanı ve uçuş --- */
    {
      id: 'en-sey-11', on: 'check in', okunus: 'çek in', tur: 'öbek fiil',
      arka: 'giriş işlemi yaptırmak',
      ornek: 'You should check in two hours before the flight.',
      ornekTr: 'Uçuştan iki saat önce giriş işlemi yaptırmalısın.',
      not: 'Otelde de kullanılır. İsim hâli bitişiktir: "the check-in desk".',
    },
    {
      id: 'en-sey-12', on: 'boarding pass', okunus: 'bording pas', tur: 'isim',
      arka: 'biniş kartı',
      ornek: 'Keep your boarding pass with you.',
      ornekTr: 'Biniş kartını yanında tut.',
      not: 'Uçağa binmek fiili "board"tur.',
    },
    {
      id: 'en-sey-13', on: 'gate', okunus: 'geyt', tur: 'isim',
      arka: 'kapı (uçuş çıkış kapısı)',
      ornek: 'The gate closes twenty minutes before departure.',
      ornekTr: 'Kapı kalkıştan yirmi dakika önce kapanıyor.',
      not: 'Bahçe kapısı için de aynı kelime kullanılır.',
    },
    {
      id: 'en-sey-14', on: 'departure', okunus: 'dipartçır', tur: 'isim',
      arka: 'kalkış, gidiş',
      ornek: 'Departures are on the upper floor.',
      ornekTr: 'Gidiş katı üst kattadır.',
      not: 'Karşıtı "arrival" = varış.',
    },
    {
      id: 'en-sey-15', on: 'take off', okunus: 'teyk of', tur: 'öbek fiil',
      arka: 'kalkmak (uçak)',
      ornek: 'The plane took off on time.',
      ornekTr: 'Uçak zamanında kalktı.',
      not: 'İniş "land"dir. Aynı öbek "kıyafeti çıkarmak" anlamına da gelir.',
    },
    {
      id: 'en-sey-16', on: 'delayed', okunus: 'dileyd', tur: 'sıfat',
      arka: 'gecikmiş',
      ornek: 'Our flight was delayed by three hours.',
      ornekTr: 'Uçuşumuz üç saat gecikti.',
      not: 'İptal edilmiş ise "cancelled"dır.',
    },
    {
      id: 'en-sey-17', on: 'hand luggage', okunus: 'hend lagıc', tur: 'isim',
      arka: 'el bagajı',
      ornek: 'I only travel with hand luggage.',
      ornekTr: 'Sadece el bagajıyla seyahat ediyorum.',
      not: '"Luggage" sayılamaz: "two luggages" YANLIŞTIR, "two bags" denir.',
    },
    {
      id: 'en-sey-18', on: 'baggage claim', okunus: 'begıc kleym', tur: 'isim',
      arka: 'bagaj alma bandı',
      ornek: 'Wait for me at baggage claim.',
      ornekTr: 'Beni bagaj alma bandında bekle.',
      not: 'İngiltere\'de "baggage reclaim" de denir.',
    },
    {
      id: 'en-sey-19', on: 'customs', okunus: 'kastımz', tur: 'isim (çoğul)',
      arka: 'gümrük',
      ornek: 'We went through customs quickly.',
      ornekTr: 'Gümrükten hızlıca geçtik.',
      not: 'Tekil "custom" ise "gelenek" demektir. Dikkat.',
    },
    {
      id: 'en-sey-20', on: 'jet lag', okunus: 'cet leg', tur: 'isim',
      arka: 'saat farkı yorgunluğu',
      ornek: 'I had jet lag for three days.',
      ornekTr: 'Üç gün saat farkı yorgunluğu yaşadım.',
      not: 'Fiili "have" ya da "get"tir.',
    },
    /* --- Konaklama --- */
    {
      id: 'en-sey-21', on: 'book a room', okunus: 'buk ı rum', tur: 'eş dizim',
      arka: 'oda ayırtmak',
      ornek: 'I booked a room for two nights.',
      ornekTr: 'İki geceliğine oda ayırttım.',
      not: 'Süre "for" ile verilir: for two nights.',
    },
    {
      id: 'en-sey-22', on: 'a single room', okunus: 'ı singıl rum', tur: 'isim',
      arka: 'tek kişilik oda',
      ornek: 'Do you have a single room available?',
      ornekTr: 'Müsait tek kişilik odanız var mı?',
      not: 'İki kişilik "a double room", iki yataklı "a twin room"dur.',
    },
    {
      id: 'en-sey-23', on: 'available', okunus: 'ıveylıbıl', tur: 'sıfat',
      arka: 'müsait, boş',
      ornek: 'There are no rooms available tonight.',
      ornekTr: 'Bu gece boş oda yok.',
      not: 'Kişi için de kullanılır: "Are you available on Friday?"',
    },
    {
      id: 'en-sey-24', on: 'fully booked', okunus: 'fuli bukd', tur: 'sıfat',
      arka: 'tamamen dolu',
      ornek: 'The hotel is fully booked in August.',
      ornekTr: 'Otel ağustosta tamamen dolu.',
      not: 'Restoran ve uçuş için de kullanılır.',
    },
    {
      id: 'en-sey-25', on: 'included', okunus: 'inkludıd', tur: 'sıfat',
      arka: 'dâhil',
      ornek: 'Is breakfast included?',
      ornekTr: 'Kahvaltı dâhil mi?',
      not: 'Otelde ilk sorulacak sorulardan biridir.',
    },
    {
      id: 'en-sey-26', on: 'check out', okunus: 'çek aut', tur: 'öbek fiil',
      arka: 'otelden çıkış yapmak',
      ornek: 'We have to check out by eleven.',
      ornekTr: 'Saat on bire kadar çıkış yapmamız gerekiyor.',
      not: '"By eleven" = on birden geç olmamak üzere.',
    },
    {
      id: 'en-sey-27', on: 'stay at / stay in', okunus: 'stey et / stey in', tur: 'ayrım',
      arka: 'otelde kalmak / şehirde kalmak',
      ornek: 'We stayed at a small hotel in Rome.',
      ornekTr: 'Roma\'da küçük bir otelde kaldık.',
      not: 'Bina "at", şehir ve ülke "in" alır.',
    },
    {
      id: 'en-sey-28', on: 'guesthouse', okunus: 'gesthaus', tur: 'isim',
      arka: 'pansiyon',
      ornek: 'We stayed in a family guesthouse.',
      ornekTr: 'Aile işletmesi bir pansiyonda kaldık.',
      not: 'Otelden küçük ve daha samimidir.',
    },
    {
      id: 'en-sey-29', on: 'a deposit', okunus: 'ı dipozit', tur: 'isim',
      arka: 'kapora, depozito',
      ornek: 'They asked for a deposit.',
      ornekTr: 'Kapora istediler.',
      not: 'Bankaya para yatırmak için de aynı kelime kullanılır.',
    },
    {
      id: 'en-sey-30', on: 'refund', okunus: 'rifand', tur: 'isim / fiil',
      arka: 'para iadesi',
      ornek: 'Can I get a refund?',
      ornekTr: 'Para iadesi alabilir miyim?',
      not: 'İade edilebilir "refundable", edilemez "non-refundable"dır.',
    },
    /* --- Ulaşım --- */
    {
      id: 'en-sey-31', on: 'catch a train', okunus: 'keç ı treyn', tur: 'eş dizim',
      arka: 'trene yetişmek',
      ornek: 'I need to catch the 8:15 train.',
      ornekTr: '8:15 trenine yetişmem gerekiyor.',
      not: 'Kaçırmak "miss the train"dir.',
    },
    {
      id: 'en-sey-32', on: 'get on / get off', okunus: 'get on / get of', tur: 'öbek fiil',
      arka: 'binmek / inmek (otobüs, tren)',
      ornek: 'Get off at the third stop.',
      ornekTr: 'Üçüncü durakta in.',
      not: 'Araba ve taksi için "get in / get out of" kullanılır.',
    },
    {
      id: 'en-sey-33', on: 'a return ticket', okunus: 'ı ritörn tikit', tur: 'isim',
      arka: 'gidiş-dönüş bileti',
      ornek: 'Two return tickets, please.',
      ornekTr: 'İki gidiş-dönüş bileti lütfen.',
      not: 'Tek yön "a single ticket"tir. Amerika\'da "round-trip" denir.',
    },
    {
      id: 'en-sey-34', on: 'platform', okunus: 'pletform', tur: 'isim',
      arka: 'peron',
      ornek: 'The train leaves from platform four.',
      ornekTr: 'Tren dört numaralı perondan kalkıyor.',
      not: 'Edatı "from"dur.',
    },
    {
      id: 'en-sey-35', on: 'change trains', okunus: 'çeync treynz', tur: 'eş dizim',
      arka: 'aktarma yapmak',
      ornek: 'You have to change trains in Ankara.',
      ornekTr: 'Ankara\'da aktarma yapman gerekiyor.',
      not: 'Çoğul kullanılır: change trains, change buses.',
    },
    {
      id: 'en-sey-36', on: 'rush hour', okunus: 'raş auır', tur: 'isim',
      arka: 'yoğun saat',
      ornek: 'Avoid the metro at rush hour.',
      ornekTr: 'Yoğun saatte metroya binme.',
      not: 'Tekil kullanılır, "rush hours" denmez.',
    },
    {
      id: 'en-sey-37', on: 'traffic jam', okunus: 'trefik cem', tur: 'isim',
      arka: 'trafik sıkışıklığı',
      ornek: 'We were stuck in a traffic jam.',
      ornekTr: 'Trafikte sıkışıp kaldık.',
      not: '"Be stuck in" kalıbı sıkışmayı anlatır.',
    },
    {
      id: 'en-sey-38', on: 'on foot', okunus: 'on fut', tur: 'kalıp',
      arka: 'yürüyerek',
      ornek: 'It is ten minutes on foot.',
      ornekTr: 'Yürüyerek on dakika.',
      not: '"By foot" YANLIŞTIR. Diğer araçlar "by" alır: by bus, by car.',
    },
    {
      id: 'en-sey-39', on: 'give someone a lift', okunus: 'giv samvan ı lift', tur: 'deyim',
      arka: 'birini arabayla bırakmak',
      ornek: 'Can you give me a lift to school?',
      ornekTr: 'Beni okula bırakabilir misin?',
      not: 'Amerika\'da "give a ride" denir.',
    },
    {
      id: 'en-sey-40', on: 'fare', okunus: 'feır', tur: 'isim',
      arka: 'yol ücreti',
      ornek: 'The bus fare went up again.',
      ornekTr: 'Otobüs ücreti yine arttı.',
      not: 'Bilet "ticket", ücret "fare"dir.',
    },
    /* --- Yol tarifi --- */
    {
      id: 'en-sey-41', on: 'go straight on', okunus: 'gou streyt on', tur: 'kalıp',
      arka: 'dümdüz devam etmek',
      ornek: 'Go straight on for two hundred metres.',
      ornekTr: 'İki yüz metre dümdüz devam et.',
      not: 'Amerika\'da "go straight ahead" denir.',
    },
    {
      id: 'en-sey-42', on: 'turn left / right', okunus: 'törn left / rayt', tur: 'kalıp',
      arka: 'sola / sağa dönmek',
      ornek: 'Turn left at the traffic lights.',
      ornekTr: 'Trafik ışıklarından sola dön.',
      not: 'Yön edatı "at"tir: at the corner, at the lights.',
    },
    {
      id: 'en-sey-43', on: 'opposite', okunus: 'opızit', tur: 'edat',
      arka: 'tam karşısında',
      ornek: 'The bank is opposite the post office.',
      ornekTr: 'Banka postanenin tam karşısında.',
      not: 'Yan yana olan "next to"dur.',
    },
    {
      id: 'en-sey-44', on: 'around the corner', okunus: 'ıraund dı kornır', tur: 'kalıp',
      arka: 'köşeyi dönünce',
      ornek: 'The pharmacy is just around the corner.',
      ornekTr: 'Eczane hemen köşeyi dönünce.',
      not: 'Mecazi olarak "çok yakında" anlamı da vardır.',
    },
    {
      id: 'en-sey-45', on: 'get lost', okunus: 'get lost', tur: 'kalıp',
      arka: 'kaybolmak',
      ornek: 'We got lost in the old town.',
      ornekTr: 'Eski şehirde kaybolduk.',
      not: 'Fiil "get"tir; "be lost" kaybolmuş durumda olmaktır.',
    },
    {
      id: 'en-sey-46', on: 'How do I get to...?', okunus: 'hau du ay get tu', tur: 'soru kalıbı',
      arka: '... nasıl giderim?',
      ornek: 'How do I get to the museum?',
      ornekTr: 'Müzeye nasıl giderim?',
      not: 'Yol sorarken en doğal kalıptır. "Get to" ulaşmak demektir.',
    },
    {
      id: 'en-sey-47', on: 'Is it far from here?', okunus: 'iz it far from hir', tur: 'soru kalıbı',
      arka: 'Buradan uzak mı?',
      ornek: 'Is the beach far from here?',
      ornekTr: 'Plaj buradan uzak mı?',
      not: 'Cevabı "It is about ten minutes away." olabilir.',
    },
    {
      id: 'en-sey-48', on: 'landmark', okunus: 'lendmark', tur: 'isim',
      arka: 'göze çarpan yapı, işaret noktası',
      ornek: 'The tower is a famous landmark.',
      ornekTr: 'Kule ünlü bir işaret noktasıdır.',
      not: 'Yol tarif ederken referans nokta olarak kullanılır.',
    },
    {
      id: 'en-sey-49', on: 'crossroads', okunus: 'krosroudz', tur: 'isim',
      arka: 'kavşak',
      ornek: 'Turn right at the crossroads.',
      ornekTr: 'Kavşaktan sağa dön.',
      not: 'Tekil de olsa sonunda "s" vardır.',
    },
    {
      id: 'en-sey-50', on: 'pedestrian crossing', okunus: 'pıdestriın krosing', tur: 'isim',
      arka: 'yaya geçidi',
      ornek: 'Use the pedestrian crossing.',
      ornekTr: 'Yaya geçidini kullan.',
      not: 'İngiltere\'de "zebra crossing" de denir.',
    },
    /* --- Tatil türleri --- */
    {
      id: 'en-sey-51', on: 'go on holiday', okunus: 'gou on holıdey', tur: 'eş dizim',
      arka: 'tatile gitmek',
      ornek: 'We go on holiday every July.',
      ornekTr: 'Her temmuz tatile gidiyoruz.',
      not: 'Amerika\'da "go on vacation" denir. Edat "on"dur.',
    },
    {
      id: 'en-sey-52', on: 'a day trip', okunus: 'ı dey trip', tur: 'isim',
      arka: 'günübirlik gezi',
      ornek: 'We took a day trip to the lake.',
      ornekTr: 'Göle günübirlik bir gezi yaptık.',
      not: 'Fiili "take" ya da "go on"dur.',
    },
    {
      id: 'en-sey-53', on: 'sightseeing', okunus: 'saytsiiing', tur: 'isim',
      arka: 'gezip görme, turistik gezi',
      ornek: 'We did some sightseeing in the morning.',
      ornekTr: 'Sabah biraz gezdik.',
      not: 'Fiili "do"dur: do some sightseeing.',
    },
    {
      id: 'en-sey-54', on: 'guided tour', okunus: 'gaydıd tur', tur: 'isim',
      arka: 'rehberli tur',
      ornek: 'We joined a guided tour of the castle.',
      ornekTr: 'Kalenin rehberli turuna katıldık.',
      not: 'Rehber "a guide"dır.',
    },
    {
      id: 'en-sey-55', on: 'backpacking', okunus: 'bekpeking', tur: 'isim',
      arka: 'sırt çantasıyla gezmek',
      ornek: 'They went backpacking around Europe.',
      ornekTr: 'Sırt çantasıyla Avrupa\'yı gezdiler.',
      not: 'Ucuz ve serbest seyahat tarzını anlatır.',
    },
    {
      id: 'en-sey-56', on: 'off the beaten track', okunus: 'of dı biitın trek', tur: 'deyim',
      arka: 'turistik olmayan, bilinmeyen yerler',
      ornek: 'We like places off the beaten track.',
      ornekTr: 'Turistik olmayan yerleri seviyoruz.',
      not: 'Seyahat yazılarında çok geçen bir ifadedir.',
    },
    {
      id: 'en-sey-57', on: 'peak season', okunus: 'piik siizın', tur: 'isim',
      arka: 'sezonun en yoğun dönemi',
      ornek: 'Prices double in peak season.',
      ornekTr: 'Fiyatlar yoğun sezonda ikiye katlanıyor.',
      not: 'Sakin dönem "off-season"dur.',
    },
    {
      id: 'en-sey-58', on: 'souvenir', okunus: 'suvınir', tur: 'isim',
      arka: 'hediyelik eşya',
      ornek: 'I bought a small souvenir for my sister.',
      ornekTr: 'Kız kardeşime küçük bir hediyelik aldım.',
      not: 'Fransızcadan gelir; "hatıra" anlamı taşır.',
    },
    {
      id: 'en-sey-59', on: 'itinerary', okunus: 'aytinırıri', tur: 'isim',
      arka: 'gezi programı',
      ornek: 'Our itinerary includes three cities.',
      ornekTr: 'Gezi programımızda üç şehir var.',
      not: 'Resmî bir kelimedir; sınav okuma metinlerinde geçer.',
    },
    {
      id: 'en-sey-60', on: 'travel light', okunus: 'trevıl layt', tur: 'kalıp',
      arka: 'az eşyayla seyahat etmek',
      ornek: 'I always travel light.',
      ornekTr: 'Her zaman az eşyayla seyahat ederim.',
      not: '"Light" burada sıfat değil zarf gibi kullanılır.',
    },
    /* --- Şehir ve mekân --- */
    {
      id: 'en-sey-61', on: 'city centre', okunus: 'siti sentır', tur: 'isim',
      arka: 'şehir merkezi',
      ornek: 'Our hotel is in the city centre.',
      ornekTr: 'Otelimiz şehir merkezinde.',
      not: 'Amerika\'da "downtown" denir ve "the" almaz.',
    },
    {
      id: 'en-sey-62', on: 'the outskirts', okunus: 'di autskörts', tur: 'isim (çoğul)',
      arka: 'şehrin dış mahalleleri',
      ornek: 'They live on the outskirts of the city.',
      ornekTr: 'Şehrin dışında oturuyorlar.',
      not: 'Edatı "on"dur: on the outskirts of.',
    },
    {
      id: 'en-sey-63', on: 'crowded', okunus: 'kraudıd', tur: 'sıfat',
      arka: 'kalabalık',
      ornek: 'The market was very crowded.',
      ornekTr: 'Pazar çok kalabalıktı.',
      not: 'Sakin olan "quiet" ya da "peaceful"dır.',
    },
    {
      id: 'en-sey-64', on: 'lively', okunus: 'layvli', tur: 'sıfat',
      arka: 'hareketli, canlı (yer)',
      ornek: 'It is a lively neighbourhood at night.',
      ornekTr: 'Geceleri hareketli bir mahalle.',
      not: 'Sonu "-ly" olsa da zarf değil sıfattır. Sınav tuzağıdır.',
    },
    {
      id: 'en-sey-65', on: 'scenery', okunus: 'siinıri', tur: 'isim',
      arka: 'doğal manzara',
      ornek: 'The scenery on the road was beautiful.',
      ornekTr: 'Yoldaki manzara çok güzeldi.',
      not: 'Sayılamayan bir isimdir: "sceneries" denmez.',
    },
    {
      id: 'en-sey-66', on: 'a view of', okunus: 'ı vyu ıv', tur: 'kalıp',
      arka: '... manzarası',
      ornek: 'The room has a view of the sea.',
      ornekTr: 'Odanın deniz manzarası var.',
      not: '"Scenery" doğanın kendisidir, "view" bakınca görünendir.',
    },
    {
      id: 'en-sey-67', on: 'the seaside', okunus: 'dı siisayd', tur: 'isim',
      arka: 'deniz kıyısı',
      ornek: 'We spent the weekend at the seaside.',
      ornekTr: 'Hafta sonunu deniz kıyısında geçirdik.',
      not: 'Edatı "at"tir: at the seaside.',
    },
    {
      id: 'en-sey-68', on: 'accommodation', okunus: 'ıkomıdeyşın', tur: 'isim',
      arka: 'konaklama',
      ornek: 'Accommodation is expensive in summer.',
      ornekTr: 'Yazın konaklama pahalı.',
      not: 'İngiltere\'de sayılamaz kullanılır: "accommodations" denmez.',
    },
    {
      id: 'en-sey-69', on: 'local', okunus: 'loukıl', tur: 'sıfat / isim',
      arka: 'yerel; yerli halktan biri',
      ornek: 'We ate at a local restaurant.',
      ornekTr: 'Yerel bir restoranda yedik.',
      not: 'İsim olarak "the locals" = yöre halkı.',
    },
    {
      id: 'en-sey-70', on: 'get around', okunus: 'get ıraund', tur: 'öbek fiil',
      arka: 'bir yerde dolaşmak, ulaşımı sağlamak',
      ornek: 'It is easy to get around by tram.',
      ornekTr: 'Tramvayla dolaşmak kolay.',
      not: 'Ulaşım kolaylığını anlatan en doğal öbektir.',
    },
    /* --- Sorunlar ve acil durumlar --- */
    {
      id: 'en-sey-71', on: 'miss a flight', okunus: 'mis ı flayt', tur: 'eş dizim',
      arka: 'uçağı kaçırmak',
      ornek: 'We almost missed our flight.',
      ornekTr: 'Neredeyse uçağımızı kaçırıyorduk.',
      not: '"Lose a flight" YANLIŞTIR. Doğru fiil "miss"tir.',
    },
    {
      id: 'en-sey-72', on: 'lost property', okunus: 'lost propırti', tur: 'isim',
      arka: 'kayıp eşya bürosu',
      ornek: 'Ask at lost property.',
      ornekTr: 'Kayıp eşya bürosuna sor.',
      not: 'Amerika\'da "lost and found" denir.',
    },
    {
      id: 'en-sey-73', on: 'travel insurance', okunus: 'trevıl inşurıns', tur: 'isim',
      arka: 'seyahat sigortası',
      ornek: 'Do not travel without insurance.',
      ornekTr: 'Sigortasız seyahat etme.',
      not: '"Insurance" sayılamayan bir isimdir.',
    },
    {
      id: 'en-sey-74', on: 'pickpocket', okunus: 'pikpokit', tur: 'isim',
      arka: 'yankesici',
      ornek: 'Watch out for pickpockets in crowded places.',
      ornekTr: 'Kalabalık yerlerde yankesicilere dikkat et.',
      not: '"Watch out for" = dikkat etmek, tetikte olmak.',
    },
    {
      id: 'en-sey-75', on: 'emergency', okunus: 'imörcınsi', tur: 'isim',
      arka: 'acil durum',
      ornek: 'Call this number in an emergency.',
      ornekTr: 'Acil durumda bu numarayı ara.',
      not: 'Acil çıkış "the emergency exit"tir.',
    },
    {
      id: 'en-sey-76', on: 'break down', okunus: 'breyk daun', tur: 'öbek fiil',
      arka: 'bozulmak (araç)',
      ornek: 'Our car broke down on the motorway.',
      ornekTr: 'Arabamız otoyolda bozuldu.',
      not: 'Yalnız makineler için kullanılır; insan için "break down" ağlamaktır.',
    },
    {
      id: 'en-sey-77', on: 'run late', okunus: 'ran leyt', tur: 'kalıp',
      arka: 'gecikmek',
      ornek: 'We are running late for the bus.',
      ornekTr: 'Otobüse geç kalıyoruz.',
      not: 'Süregelen bir gecikmeyi anlatır, şimdiki zamanla kullanılır.',
    },
    {
      id: 'en-sey-78', on: 'be stranded', okunus: 'bi strendıd', tur: 'kalıp',
      arka: 'mahsur kalmak',
      ornek: 'We were stranded at the airport for a night.',
      ornekTr: 'Bir gece havalimanında mahsur kaldık.',
      not: 'Sınav okuma metinlerinde sık geçen ileri düzey bir kelimedir.',
    },
    {
      id: 'en-sey-79', on: 'complain about', okunus: 'kımpleyn ıbaut', tur: 'öbek fiil',
      arka: 'şikâyet etmek',
      ornek: 'We complained about the noise.',
      ornekTr: 'Gürültüden şikâyet ettik.',
      not: 'Edatı "about"tur; kişi "to" ile verilir: complain to the manager.',
    },
    {
      id: 'en-sey-80', on: 'sort out a problem', okunus: 'sort aut ı problım', tur: 'eş dizim',
      arka: 'sorunu halletmek',
      ornek: 'They sorted out the problem quickly.',
      ornekTr: 'Sorunu hızlıca hallettiler.',
      not: 'Otel ve havayolu konuşmalarında çok kullanılır.',
    },
    /* --- Hava ve mevsim --- */
    {
      id: 'en-sey-81', on: 'weather forecast', okunus: 'vedır forkast', tur: 'isim',
      arka: 'hava tahmini',
      ornek: 'The weather forecast says it will rain.',
      ornekTr: 'Hava tahmini yağmur yağacağını söylüyor.',
      not: '"Weather" sayılamazdır: "a weather" denmez.',
    },
    {
      id: 'en-sey-82', on: 'humid', okunus: 'hyumid', tur: 'sıfat',
      arka: 'nemli',
      ornek: 'It gets very humid in August.',
      ornekTr: 'Ağustosta hava çok nemli oluyor.',
      not: 'Kuru hava "dry"dır. İsmi "humidity".',
    },
    {
      id: 'en-sey-83', on: 'boiling hot', okunus: 'boyling hot', tur: 'kalıp',
      arka: 'aşırı sıcak',
      ornek: 'It was boiling hot at noon.',
      ornekTr: 'Öğlen hava aşırı sıcaktı.',
      not: 'Aşırı soğuk için "freezing cold" denir.',
    },
    {
      id: 'en-sey-84', on: 'a shower', okunus: 'ı şauır', tur: 'isim',
      arka: 'sağanak (kısa süreli yağmur)',
      ornek: 'There were a few showers in the afternoon.',
      ornekTr: 'Öğleden sonra birkaç sağanak vardı.',
      not: 'Aynı kelime "duş" anlamına da gelir.',
    },
    {
      id: 'en-sey-85', on: 'pour down', okunus: 'por daun', tur: 'öbek fiil',
      arka: 'bardaktan boşanırcasına yağmak',
      ornek: 'It poured down all night.',
      ornekTr: 'Bütün gece bardaktan boşanırcasına yağdı.',
      not: 'Deyimi "It is raining cats and dogs" artık eskimiştir.',
    },
    {
      id: 'en-sey-86', on: 'mild', okunus: 'mayld', tur: 'sıfat',
      arka: 'ılıman',
      ornek: 'Winters are mild on the coast.',
      ornekTr: 'Kıyıda kışlar ılımandır.',
      not: 'Yemek için "acı olmayan" anlamına gelir.',
    },
    {
      id: 'en-sey-87', on: 'pack', okunus: 'pek', tur: 'fiil',
      arka: 'bavul hazırlamak',
      ornek: 'I packed my bag last night.',
      ornekTr: 'Çantamı dün gece hazırladım.',
      not: 'Boşaltmak "unpack"tir.',
    },
    {
      id: 'en-sey-88', on: 'sunscreen', okunus: 'sanskriin', tur: 'isim',
      arka: 'güneş kremi',
      ornek: 'Do not forget your sunscreen.',
      ornekTr: 'Güneş kremini unutma.',
      not: '"Sun cream" de denir; ikisi de doğrudur.',
    },
    {
      id: 'en-sey-89', on: 'get sunburnt', okunus: 'get sanbörnt', tur: 'kalıp',
      arka: 'güneş yanığı olmak',
      ornek: 'I got sunburnt on the first day.',
      ornekTr: 'İlk gün güneşten yandım.',
      not: 'Bronzlaşmak ise "get a tan"dir; ikisi farklıdır.',
    },
    {
      id: 'en-sey-90', on: 'It depends on the weather', okunus: 'it dipendz on dı vedır', tur: 'kalıp',
      arka: 'Havaya bağlı',
      ornek: 'We may go to the beach; it depends on the weather.',
      ornekTr: 'Plaja gidebiliriz, havaya bağlı.',
      not: 'Plan yaparken en çok kullanılan çekince cümlesidir.',
    },
    /* --- Seyahat deyimleri ve konuşma kalıpları --- */
    {
      id: 'en-sey-91', on: 'hit the road', okunus: 'hit dı roud', tur: 'deyim',
      arka: 'yola çıkmak',
      ornek: 'We hit the road at six in the morning.',
      ornekTr: 'Sabah altıda yola çıktık.',
      not: 'Gündelik ve enerjik bir ifadedir.',
    },
    {
      id: 'en-sey-92', on: 'be on the move', okunus: 'bi on dı muv', tur: 'deyim',
      arka: 'sürekli hareket hâlinde olmak',
      ornek: 'We were on the move every day.',
      ornekTr: 'Her gün hareket hâlindeydik.',
      not: 'Yorucu ama dolu dolu bir geziyi anlatır.',
    },
    {
      id: 'en-sey-93', on: 'get away from it all', okunus: 'get ıvey from it ol', tur: 'deyim',
      arka: 'her şeyden uzaklaşmak',
      ornek: 'I need a weekend to get away from it all.',
      ornekTr: 'Her şeyden uzaklaşmak için bir hafta sonuna ihtiyacım var.',
      not: 'Tatilin amacını anlatan klasik bir ifadedir.',
    },
    {
      id: 'en-sey-94', on: 'live out of a suitcase', okunus: 'liv aut ıv ı suutkeys', tur: 'deyim',
      arka: 'sürekli valizle yaşamak',
      ornek: 'He lives out of a suitcase for work.',
      ornekTr: 'İşi yüzünden sürekli valizle yaşıyor.',
      not: 'Çok seyahat eden kişileri anlatır.',
    },
    {
      id: 'en-sey-95', on: 'a change of scene', okunus: 'ı çeync ıv siin', tur: 'deyim',
      arka: 'ortam değişikliği',
      ornek: 'You need a change of scene.',
      ornekTr: 'Ortam değişikliğine ihtiyacın var.',
      not: 'Ruh hâli için kullanılan bir tavsiye cümlesidir.',
    },
    {
      id: 'en-sey-96', on: 'Have a safe trip', okunus: 'hev ı seyf trip', tur: 'kalıp',
      arka: 'İyi yolculuklar',
      ornek: 'Have a safe trip and text me when you arrive.',
      ornekTr: 'İyi yolculuklar, varınca mesaj at.',
      not: '"Have a good journey" de denir.',
    },
    {
      id: 'en-sey-97', on: 'Enjoy your stay', okunus: 'incoy yor stey', tur: 'kalıp',
      arka: 'İyi konaklamalar',
      ornek: 'Here is your key. Enjoy your stay.',
      ornekTr: 'Anahtarınız burada. İyi konaklamalar.',
      not: 'Otel görevlilerinin standart cümlesidir.',
    },
    {
      id: 'en-sey-98', on: 'Where are you from?', okunus: 'veır ar yu from', tur: 'soru kalıbı',
      arka: 'Nerelisin?',
      ornek: 'Where are you from originally?',
      ornekTr: 'Aslen nerelisin?',
      not: '"Where do you come from?" de aynı anlamdadır.',
    },
    {
      id: 'en-sey-99', on: 'How long are you staying?', okunus: 'hau long ar yu steying', tur: 'soru kalıbı',
      arka: 'Ne kadar kalacaksın?',
      ornek: 'How long are you staying in Istanbul?',
      ornekTr: 'İstanbul\'da ne kadar kalacaksın?',
      not: 'Plan için şimdiki zaman kullanılır; gelecek anlamı taşır.',
    },
    {
      id: 'en-sey-100', on: 'worth a visit', okunus: 'vört ı vizit', tur: 'kalıp',
      arka: 'gidip görmeye değer',
      ornek: 'The old castle is worth a visit.',
      ornekTr: 'Eski kale gidip görmeye değer.',
      not: '"Worth visiting" de doğrudur; ikisi de yaygındır.',
    },
  ],
}

export default DESTE
