/**
 * DESTE — YEMEK VE TATLAR (İngilizce)
 *
 * Kafede ve restoranda gerçekten kurulan cümleler. Ayrıca Türk
 * öğrencilerin en sık yaptığı iki hata bu destede hedef alındı:
 * "I am hungry" yerine "I have hunger" ve sayılamayan isimlerde
 * yanlış miktar ifadesi.
 */

export const DESTE = {
  id: 'yemek',
  dil: 'en',
  ad: 'Yemek ve tatlar',
  simge: '🍽️',
  aciklama: 'Kafede sipariş verirken ve yemek anlatırken kullanılan kalıplar.',
  seviye: 'A1–B1',
  kartlar: [
    {
      id: 'en-yem-01', on: 'be starving', okunus: 'bi starving', tur: 'kalıp',
      arka: 'çok acıkmış olmak',
      ornek: 'I skipped lunch, so I am starving.',
      ornekTr: 'Öğle yemeğini atladım, açlıktan ölüyorum.',
      not: '"I have hunger" YANLIŞTIR. Açlık "be" ile kurulur: I am hungry / starving.',
    },
    {
      id: 'en-yem-02', on: 'a slice of', okunus: 'ı slays ıv', tur: 'miktar ifadesi',
      arka: 'bir dilim',
      ornek: 'Can I have a slice of cake, please?',
      ornekTr: 'Bir dilim pasta alabilir miyim?',
      not: 'Sayılamayan isimler sayı almaz; araya miktar ifadesi girer.',
    },
    {
      id: 'en-yem-03', on: 'takeaway', okunus: 'teykıvey', tur: 'isim / sıfat',
      arka: 'paket (götürmek için)',
      ornek: 'We ordered a takeaway last night.',
      ornekTr: 'Dün gece paket söyledik.',
      not: 'Amerika\'da "takeout" denir. Restoranda yemek "eat in / dine in".',
    },
    {
      id: 'en-yem-04', on: 'the bill', okunus: 'dı bil', tur: 'isim',
      arka: 'hesap (restoranda)',
      ornek: 'Could we have the bill, please?',
      ornekTr: 'Hesabı alabilir miyiz?',
      not: 'Amerika\'da "the check". "the account" burada YANLIŞTIR.',
    },
    {
      id: 'en-yem-05', on: 'try', okunus: 'tray', tur: 'fiil',
      arka: 'tatmak, denemek',
      ornek: 'You should try the soup, it is amazing.',
      ornekTr: 'Çorbayı denemelisin, harika.',
      not: 'Yemek tatmak için "taste" değil çoğu zaman "try" kullanılır.',
    },
    {
      id: 'en-yem-06', on: 'be allergic to', okunus: 'bi ılörcik tu', tur: 'kalıp',
      arka: '-e alerjisi olmak',
      ornek: 'I am allergic to nuts.',
      ornekTr: 'Kuruyemişe alerjim var.',
      not: 'Edat "to"dur. Yurt dışında ilk gün lazım olabilecek cümle.',
    },
    {
      id: 'en-yem-07', on: 'eat out', okunus: 'iit aut', tur: 'öbek fiil',
      arka: 'dışarıda yemek yemek',
      ornek: 'We eat out once a week.',
      ornekTr: 'Haftada bir dışarıda yiyoruz.',
      not: 'Karşıtı "eat in" ya da "cook at home".',
    },
    {
      id: 'en-yem-08', on: 'leftovers', okunus: 'leftouvırz', tur: 'isim (çoğul)',
      arka: 'artan yemek',
      ornek: 'I had the leftovers for lunch.',
      ornekTr: 'Öğlen artan yemeği yedim.',
      not: '"left over" (artmak) fiilinden gelir; her zaman çoğuldur.',
    },
    {
      id: 'en-yem-09', on: 'craving', okunus: 'kreyving', tur: 'isim',
      arka: 'canının çok çekmesi',
      ornek: 'I have a craving for chocolate.',
      ornekTr: 'Canım çok çikolata çekiyor.',
      not: 'Fiil hâli: "I am craving chocolate."',
    },
    {
      id: 'en-yem-10', on: 'it tastes like', okunus: 'it teysts layk', tur: 'kalıp',
      arka: '… gibi tadı var',
      ornek: 'It tastes like something my grandmother makes.',
      ornekTr: 'Tadı anneannemin yaptığı bir şey gibi.',
      not: '"taste" duyu fiilidir ve "like" ile benzetme kurar.',
    },
    /* --- Pişirme fiilleri --- */
    {
      id: 'en-yem-11', on: 'boil', okunus: 'boyl', tur: 'fiil',
      arka: 'kaynatmak, haşlamak',
      ornek: 'Boil the eggs for ten minutes.',
      ornekTr: 'Yumurtaları on dakika haşla.',
      not: 'Suda pişirmedir. Yağda pişirme "fry"dır.',
    },
    {
      id: 'en-yem-12', on: 'fry', okunus: 'fray', tur: 'fiil',
      arka: 'yağda kızartmak',
      ornek: 'She fried the potatoes in olive oil.',
      ornekTr: 'Patatesleri zeytinyağında kızarttı.',
      not: 'Az yağda "stir-fry", bol yağda "deep-fry" denir.',
    },
    {
      id: 'en-yem-13', on: 'bake', okunus: 'beyk', tur: 'fiil',
      arka: 'fırında pişirmek (hamur işi)',
      ornek: 'My mother bakes bread every Sunday.',
      ornekTr: 'Annem her pazar ekmek yapar.',
      not: 'Et için "roast", hamur için "bake" kullanılır.',
    },
    {
      id: 'en-yem-14', on: 'roast', okunus: 'roust', tur: 'fiil',
      arka: 'fırında kızartmak (et, sebze)',
      ornek: 'We roasted a chicken for dinner.',
      ornekTr: 'Akşam yemeği için tavuk kızarttık.',
      not: 'Kahve kavurmak için de kullanılır: "roasted coffee".',
    },
    {
      id: 'en-yem-15', on: 'grill', okunus: 'gril', tur: 'fiil / isim',
      arka: 'ızgarada pişirmek',
      ornek: 'They grilled the meat outside.',
      ornekTr: 'Eti dışarıda ızgarada pişirdiler.',
      not: 'Amerika\'da açık ateşte pişirmeye "barbecue" denir.',
    },
    {
      id: 'en-yem-16', on: 'chop', okunus: 'çop', tur: 'fiil',
      arka: 'doğramak',
      ornek: 'Chop the onions finely.',
      ornekTr: 'Soğanları ince ince doğra.',
      not: 'Dilim dilim kesmek "slice"tır.',
    },
    {
      id: 'en-yem-17', on: 'peel', okunus: 'piil', tur: 'fiil / isim',
      arka: 'soymak; kabuk',
      ornek: 'Peel the potatoes before you boil them.',
      ornekTr: 'Patatesleri haşlamadan önce soy.',
      not: 'Ceviz gibi sert kabuk "shell"dir.',
    },
    {
      id: 'en-yem-18', on: 'stir', okunus: 'stör', tur: 'fiil',
      arka: 'karıştırmak (kaşıkla)',
      ornek: 'Stir the soup slowly.',
      ornekTr: 'Çorbayı yavaşça karıştır.',
      not: 'Malzemeleri birleştirmek "mix"tir; "stir" kaşıkla çevirmektir.',
    },
    {
      id: 'en-yem-19', on: 'melt', okunus: 'melt', tur: 'fiil',
      arka: 'eritmek, erimek',
      ornek: 'Melt the butter in a pan.',
      ornekTr: 'Tereyağını tavada erit.',
      not: 'Buz ve çikolata için de aynı fiil kullanılır.',
    },
    {
      id: 'en-yem-20', on: 'defrost', okunus: 'difrost', tur: 'fiil',
      arka: 'buzunu çözmek',
      ornek: 'Defrost the meat before cooking.',
      ornekTr: 'Pişirmeden önce etin buzunu çöz.',
      not: 'Dondurmak "freeze"dir; donmuş hâli "frozen".',
    },
    /* --- Tat ve doku --- */
    {
      id: 'en-yem-21', on: 'tasty', okunus: 'teysti', tur: 'sıfat',
      arka: 'lezzetli',
      ornek: 'That soup was really tasty.',
      ornekTr: 'O çorba gerçekten lezzetliydi.',
      not: '"Delicious" daha güçlüdür ve "very delicious" denmez.',
    },
    {
      id: 'en-yem-22', on: 'spicy', okunus: 'spaysi', tur: 'sıfat',
      arka: 'acı, baharatlı',
      ornek: 'This sauce is too spicy for me.',
      ornekTr: 'Bu sos benim için fazla acı.',
      not: 'Tat olarak acı "spicy/hot"tur; "bitter" ise kahve acılığıdır.',
    },
    {
      id: 'en-yem-23', on: 'bitter', okunus: 'bitır', tur: 'sıfat',
      arka: 'acı (kahve gibi)',
      ornek: 'Black coffee is quite bitter.',
      ornekTr: 'Sade kahve oldukça acıdır.',
      not: 'Biberin acısı "spicy"dir, bu ikisi karıştırılır.',
    },
    {
      id: 'en-yem-24', on: 'sour', okunus: 'sauır', tur: 'sıfat',
      arka: 'ekşi',
      ornek: 'Lemons are very sour.',
      ornekTr: 'Limonlar çok ekşidir.',
      not: 'Bozulmuş süt için de kullanılır: "The milk went sour."',
    },
    {
      id: 'en-yem-25', on: 'salty', okunus: 'solti', tur: 'sıfat',
      arka: 'tuzlu',
      ornek: 'The chips are too salty.',
      ornekTr: 'Cipsler fazla tuzlu.',
      not: 'Tuz "salt", sıfatı "-y" ekiyle kurulur.',
    },
    {
      id: 'en-yem-26', on: 'crispy', okunus: 'krispi', tur: 'sıfat',
      arka: 'çıtır çıtır',
      ornek: 'I like my toast crispy.',
      ornekTr: 'Tostumu çıtır seviyorum.',
      not: 'Yumuşak olan "soggy"dir ve olumsuz anlam taşır.',
    },
    {
      id: 'en-yem-27', on: 'creamy', okunus: 'kriimi', tur: 'sıfat',
      arka: 'kremamsı, yumuşak dokulu',
      ornek: 'The sauce is thick and creamy.',
      ornekTr: 'Sos koyu ve kremamsı.',
      not: 'Krema "cream"dir; sıfatı doku anlatır.',
    },
    {
      id: 'en-yem-28', on: 'raw', okunus: 'ro', tur: 'sıfat',
      arka: 'çiğ',
      ornek: 'Do not eat raw chicken.',
      ornekTr: 'Çiğ tavuk yeme.',
      not: 'Az pişmiş et "rare", iyi pişmiş "well done"dır.',
    },
    {
      id: 'en-yem-29', on: 'stale', okunus: 'steyl', tur: 'sıfat',
      arka: 'bayat',
      ornek: 'The bread is stale.',
      ornekTr: 'Ekmek bayat.',
      not: 'Bozulmuş için "off" ya da "gone bad" kullanılır.',
    },
    {
      id: 'en-yem-30', on: 'filling', okunus: 'filing', tur: 'sıfat',
      arka: 'doyurucu',
      ornek: 'Rice is very filling.',
      ornekTr: 'Pilav çok doyurucu.',
      not: 'Aynı kelime "iç harcı" anlamına da gelir.',
    },
    /* --- Öğünler ve kahvaltı --- */
    {
      id: 'en-yem-31', on: 'have breakfast', okunus: 'hev brekfıst', tur: 'eş dizim',
      arka: 'kahvaltı yapmak',
      ornek: 'I have breakfast at seven.',
      ornekTr: 'Saat yedide kahvaltı yapıyorum.',
      not: 'Öğünlerde "the" kullanılmaz: have lunch, have dinner.',
    },
    {
      id: 'en-yem-32', on: 'skip a meal', okunus: 'skip ı miil', tur: 'eş dizim',
      arka: 'öğün atlamak',
      ornek: 'Never skip breakfast before an exam.',
      ornekTr: 'Sınavdan önce asla kahvaltıyı atlama.',
      not: 'Ders kaçırmak için de aynı fiil: "skip a lesson".',
    },
    {
      id: 'en-yem-33', on: 'snack', okunus: 'snek', tur: 'isim / fiil',
      arka: 'atıştırmalık',
      ornek: 'I need a snack before training.',
      ornekTr: 'Antrenmandan önce bir atıştırmalık lazım.',
      not: 'Fiil hâli "atıştırmak"tır: "stop snacking".',
    },
    {
      id: 'en-yem-34', on: 'leftovers', okunus: 'leftouvırz', tur: 'isim (çoğul)',
      arka: 'artan yemek',
      ornek: 'We ate the leftovers for lunch.',
      ornekTr: 'Öğlen artan yemeği yedik.',
      not: 'Her zaman çoğuldur.',
    },
    {
      id: 'en-yem-35', on: 'homemade', okunus: 'hoummeyd', tur: 'sıfat',
      arka: 'ev yapımı',
      ornek: 'This is homemade lemonade.',
      ornekTr: 'Bu ev yapımı limonata.',
      not: 'Hazır olan "ready-made" ya da "shop-bought"tur.',
    },
    {
      id: 'en-yem-36', on: 'be starving', okunus: 'bi starving', tur: 'kalıp',
      arka: 'çok acıkmış olmak',
      ornek: 'I skipped lunch, so I am starving now.',
      ornekTr: 'Öğle yemeğini atladım, şimdi açlıktan ölüyorum.',
      not: '"Hungry"nin en güçlü hâlidir; "very starving" denmez.',
    },
    {
      id: 'en-yem-37', on: 'be full', okunus: 'bi ful', tur: 'kalıp',
      arka: 'doymuş olmak',
      ornek: 'No thanks, I am full.',
      ornekTr: 'Hayır teşekkürler, doydum.',
      not: '"I am satisfied" bu anlamda kullanılmaz, doğal değildir.',
    },
    {
      id: 'en-yem-38', on: 'have a sweet tooth', okunus: 'hev ı suiit tut', tur: 'deyim',
      arka: 'tatlı sevmek',
      ornek: 'My sister has a sweet tooth.',
      ornekTr: 'Kız kardeşim tatlı düşkünüdür.',
      not: 'Kelimesi kelimesine "tatlı dişi olmak"tır, diş ile ilgisi yoktur.',
    },
    {
      id: 'en-yem-39', on: 'grab a bite', okunus: 'greb ı bayt', tur: 'deyim',
      arka: 'hızlıca bir şeyler yemek',
      ornek: 'Let us grab a bite before the film.',
      ornekTr: 'Filmden önce bir şeyler atıştıralım.',
      not: 'Gündelik ve samimi bir ifadedir.',
    },
    {
      id: 'en-yem-40', on: 'eat out', okunus: 'iit aut', tur: 'öbek fiil',
      arka: 'dışarıda yemek yemek',
      ornek: 'We eat out once a week.',
      ornekTr: 'Haftada bir kez dışarıda yiyoruz.',
      not: 'Evde yemek "eat in" ya da "have dinner at home"dur.',
    },
    /* --- Restoran ve kafe --- */
    {
      id: 'en-yem-41', on: 'book a table', okunus: 'buk ı teybıl', tur: 'eş dizim',
      arka: 'masa ayırtmak',
      ornek: 'I booked a table for four.',
      ornekTr: 'Dört kişilik masa ayırttım.',
      not: 'Amerika\'da "make a reservation" daha yaygındır.',
    },
    {
      id: 'en-yem-42', on: 'the menu', okunus: 'dı menyu', tur: 'isim',
      arka: 'menü',
      ornek: 'Could we see the menu, please?',
      ornekTr: 'Menüyü görebilir miyiz lütfen?',
      not: 'Türkçedeki "mönü" bu kelimeden gelir ama "menyu" okunur.',
    },
    {
      id: 'en-yem-43', on: 'starter', okunus: 'startır', tur: 'isim',
      arka: 'başlangıç yemeği',
      ornek: 'We ordered soup as a starter.',
      ornekTr: 'Başlangıç olarak çorba söyledik.',
      not: 'Amerika\'da "appetizer" denir. Ana yemek "main course"tur.',
    },
    {
      id: 'en-yem-44', on: 'side dish', okunus: 'sayd diş', tur: 'isim',
      arka: 'garnitür, yan yemek',
      ornek: 'Rice comes as a side dish.',
      ornekTr: 'Pilav yan yemek olarak geliyor.',
      not: 'Kısaca "a side" da denir: "with a side of salad".',
    },
    {
      id: 'en-yem-45', on: 'order', okunus: 'ordır', tur: 'fiil / isim',
      arka: 'sipariş vermek; sipariş',
      ornek: 'Are you ready to order?',
      ornekTr: 'Sipariş vermeye hazır mısınız?',
      not: 'Aynı kelime "düzen" ve "emir" anlamlarına da gelir.',
    },
    {
      id: 'en-yem-46', on: 'the bill', okunus: 'dı bil', tur: 'isim',
      arka: 'hesap',
      ornek: 'Could we have the bill, please?',
      ornekTr: 'Hesabı alabilir miyiz lütfen?',
      not: 'Amerika\'da "the check" denir.',
    },
    {
      id: 'en-yem-47', on: 'tip', okunus: 'tip', tur: 'isim / fiil',
      arka: 'bahşiş',
      ornek: 'We left a small tip.',
      ornekTr: 'Küçük bir bahşiş bıraktık.',
      not: 'Aynı kelime "ipucu" anlamına da gelir: "a useful tip".',
    },
    {
      id: 'en-yem-48', on: 'split the bill', okunus: 'split dı bil', tur: 'deyim',
      arka: 'hesabı paylaşmak',
      ornek: 'Shall we split the bill?',
      ornekTr: 'Hesabı paylaşalım mı?',
      not: 'Herkes kendi payını öderse "go Dutch" da denir.',
    },
    {
      id: 'en-yem-49', on: 'takeaway', okunus: 'teykıvey', tur: 'isim',
      arka: 'paket servis',
      ornek: 'We ordered a takeaway last night.',
      ornekTr: 'Dün gece paket söyledik.',
      not: 'Amerika\'da "takeout" denir; yerinde yemek "eat in"dir.',
    },
    {
      id: 'en-yem-50', on: 'vegetarian', okunus: 'vecıteriın', tur: 'sıfat / isim',
      arka: 'vejetaryen',
      ornek: 'Do you have a vegetarian option?',
      ornekTr: 'Vejetaryen seçeneğiniz var mı?',
      not: 'Hiçbir hayvansal ürün yemeyen kişi "vegan"dır.',
    },
    /* --- Miktar ifadeleri --- */
    {
      id: 'en-yem-51', on: 'a loaf of bread', okunus: 'ı louf ıv bred', tur: 'miktar ifadesi',
      arka: 'bir somun ekmek',
      ornek: 'I bought two loaves of bread.',
      ornekTr: 'İki somun ekmek aldım.',
      not: 'Çoğulu düzensizdir: loaf → loaves.',
    },
    {
      id: 'en-yem-52', on: 'a bar of chocolate', okunus: 'ı bar ıv çoklıt', tur: 'miktar ifadesi',
      arka: 'bir kalıp çikolata',
      ornek: 'She ate a whole bar of chocolate.',
      ornekTr: 'Bir kalıp çikolatanın tamamını yedi.',
      not: 'Sabun için de "a bar of soap" denir.',
    },
    {
      id: 'en-yem-53', on: 'a bunch of grapes', okunus: 'ı banç ıv greyps', tur: 'miktar ifadesi',
      arka: 'bir salkım üzüm',
      ornek: 'He bought a bunch of grapes.',
      ornekTr: 'Bir salkım üzüm aldı.',
      not: 'Çiçek için de kullanılır: "a bunch of flowers".',
    },
    {
      id: 'en-yem-54', on: 'a jar of jam', okunus: 'ı car ıv cem', tur: 'miktar ifadesi',
      arka: 'bir kavanoz reçel',
      ornek: 'There is a jar of jam in the fridge.',
      ornekTr: 'Buzdolabında bir kavanoz reçel var.',
      not: 'Kavanoz "jar", şişe "bottle", kutu "tin/can"dir.',
    },
    {
      id: 'en-yem-55', on: 'a pinch of salt', okunus: 'ı pinç ıv solt', tur: 'miktar ifadesi',
      arka: 'bir tutam tuz',
      ornek: 'Add a pinch of salt.',
      ornekTr: 'Bir tutam tuz ekle.',
      not: 'Tariflerde çok geçer; "pinch" parmak arası demektir.',
    },
    {
      id: 'en-yem-56', on: 'a couple of', okunus: 'ı kapıl ıv', tur: 'miktar ifadesi',
      arka: 'birkaç (iki üç)',
      ornek: 'Add a couple of eggs.',
      ornekTr: 'Birkaç yumurta ekle.',
      not: 'Sayılabilir isimlerle kullanılır ve "of" düşmez.',
    },
    {
      id: 'en-yem-57', on: 'a bit of', okunus: 'ı bit ıv', tur: 'miktar ifadesi',
      arka: 'birazcık',
      ornek: 'Just a bit of sugar, please.',
      ornekTr: 'Sadece birazcık şeker lütfen.',
      not: 'Sayılamayan isimlerle kullanılır: a bit of milk, a bit of time.',
    },
    {
      id: 'en-yem-58', on: 'plenty of', okunus: 'plenti ıv', tur: 'miktar ifadesi',
      arka: 'bol bol, yeterinden fazla',
      ornek: 'Drink plenty of water.',
      ornekTr: 'Bol bol su iç.',
      not: 'Hem sayılabilir hem sayılamayan isimlerle kullanılır.',
    },
    {
      id: 'en-yem-59', on: 'a few / a little', okunus: 'ı fyu / ı litıl', tur: 'ayrım',
      arka: 'birkaç (sayılabilir) / biraz (sayılamayan)',
      ornek: 'A few apples and a little milk.',
      ornekTr: 'Birkaç elma ve biraz süt.',
      not: 'Sınavda en sık sorulan ayrımlardan biridir. Sayabiliyorsan "few".',
    },
    {
      id: 'en-yem-60', on: 'too much / too many', okunus: 'tu maç / tu meni', tur: 'ayrım',
      arka: 'çok fazla (sayılamayan / sayılabilir)',
      ornek: 'Too much sugar and too many biscuits.',
      ornekTr: 'Çok fazla şeker ve çok fazla bisküvi.',
      not: '"Much" sayılamayan, "many" sayılabilir isimle gider.',
    },
    /* --- Alışveriş ve mutfak --- */
    {
      id: 'en-yem-61', on: 'grocery shopping', okunus: 'grousıri şoping', tur: 'isim',
      arka: 'market alışverişi',
      ornek: 'I do the grocery shopping on Saturdays.',
      ornekTr: 'Market alışverişini cumartesileri yaparım.',
      not: 'Fiili "do"dur: do the shopping.',
    },
    {
      id: 'en-yem-62', on: 'ingredient', okunus: 'ingriidiınt', tur: 'isim',
      arka: 'malzeme (yemek)',
      ornek: 'You only need five ingredients.',
      ornekTr: 'Sadece beş malzemeye ihtiyacın var.',
      not: 'Tarif ise "a recipe"dir; ikisi karıştırılmamalı.',
    },
    {
      id: 'en-yem-63', on: 'recipe', okunus: 'resıpi', tur: 'isim',
      arka: 'tarif',
      ornek: 'This is my grandmother\'s recipe.',
      ornekTr: 'Bu babaannemin tarifi.',
      not: 'Okunuşu tuzaktır: "risayp" değil, "resıpi".',
    },
    {
      id: 'en-yem-64', on: 'fridge', okunus: 'fric', tur: 'isim',
      arka: 'buzdolabı',
      ornek: 'Put the milk in the fridge.',
      ornekTr: 'Sütü buzdolabına koy.',
      not: 'Uzun hâli "refrigerator"dır ama konuşmada "fridge" kullanılır.',
    },
    {
      id: 'en-yem-65', on: 'oven', okunus: 'avın', tur: 'isim',
      arka: 'fırın',
      ornek: 'Preheat the oven to 180 degrees.',
      ornekTr: 'Fırını 180 dereceye ısıt.',
      not: 'Okunuşu tuzaktır: "ouven" değil, "avın".',
    },
    {
      id: 'en-yem-66', on: 'saucepan', okunus: 'sospen', tur: 'isim',
      arka: 'tencere',
      ornek: 'Heat the water in a saucepan.',
      ornekTr: 'Suyu tencerede ısıt.',
      not: 'Tava "a frying pan"dir.',
    },
    {
      id: 'en-yem-67', on: 'go off', okunus: 'gou of', tur: 'öbek fiil',
      arka: 'bozulmak (yiyecek)',
      ornek: 'The milk has gone off.',
      ornekTr: 'Süt bozulmuş.',
      not: 'Aynı öbek "alarm çalmak" anlamına da gelir.',
    },
    {
      id: 'en-yem-68', on: 'use-by date', okunus: 'yuz bay deyt', tur: 'isim',
      arka: 'son kullanma tarihi',
      ornek: 'Check the use-by date on the yoghurt.',
      ornekTr: 'Yoğurdun son kullanma tarihine bak.',
      not: '"Best before" tavsiye edilen tarihtir, daha esnektir.',
    },
    {
      id: 'en-yem-69', on: 'run out of milk', okunus: 'ran aut ıv milk', tur: 'kalıp',
      arka: 'sütü bitmek',
      ornek: 'We have run out of milk again.',
      ornekTr: 'Sütümüz yine bitti.',
      not: 'Kalıp her tükenen şey için kullanılır.',
    },
    {
      id: 'en-yem-70', on: 'do the washing-up', okunus: 'du dı voşing ap', tur: 'eş dizim',
      arka: 'bulaşık yıkamak',
      ornek: 'I will do the washing-up tonight.',
      ornekTr: 'Bulaşığı bu akşam ben yıkayacağım.',
      not: 'Amerika\'da "do the dishes" denir.',
    },
    /* --- Sağlık ve beslenme --- */
    {
      id: 'en-yem-71', on: 'a balanced diet', okunus: 'ı belınsd dayıt', tur: 'eş dizim',
      arka: 'dengeli beslenme',
      ornek: 'A balanced diet keeps you healthy.',
      ornekTr: 'Dengeli beslenme seni sağlıklı tutar.',
      not: '"Diet" sadece zayıflama değil, genel beslenme düzenidir.',
    },
    {
      id: 'en-yem-72', on: 'be on a diet', okunus: 'bi on ı dayıt', tur: 'kalıp',
      arka: 'diyette olmak',
      ornek: 'She has been on a diet for a month.',
      ornekTr: 'Bir aydır diyette.',
      not: 'Edatı "on"dur: "in a diet" YANLIŞTIR.',
    },
    {
      id: 'en-yem-73', on: 'cut down on', okunus: 'kat daun on', tur: 'öbek fiil',
      arka: 'azaltmak',
      ornek: 'You should cut down on sugar.',
      ornekTr: 'Şekeri azaltmalısın.',
      not: 'Tamamen bırakmak "cut out"tur.',
    },
    {
      id: 'en-yem-74', on: 'nutritious', okunus: 'nutrişıs', tur: 'sıfat',
      arka: 'besleyici',
      ornek: 'Lentils are cheap and nutritious.',
      ornekTr: 'Mercimek ucuz ve besleyicidir.',
      not: 'İsmi "nutrition" = beslenme.',
    },
    {
      id: 'en-yem-75', on: 'be allergic to', okunus: 'bi ılörcik tu', tur: 'kalıp',
      arka: 'alerjisi olmak',
      ornek: 'I am allergic to peanuts.',
      ornekTr: 'Fıstığa alerjim var.',
      not: 'Edatı "to"dur. Restoranda hayat kurtaran bir cümledir.',
    },
    {
      id: 'en-yem-76', on: 'lose weight', okunus: 'luz veyt', tur: 'eş dizim',
      arka: 'kilo vermek',
      ornek: 'He wants to lose weight before the summer.',
      ornekTr: 'Yazdan önce kilo vermek istiyor.',
      not: 'Tersi "put on weight" = kilo almak.',
    },
    {
      id: 'en-yem-77', on: 'processed food', okunus: 'prousesd fud', tur: 'isim',
      arka: 'işlenmiş gıda',
      ornek: 'Try to avoid processed food.',
      ornekTr: 'İşlenmiş gıdadan kaçınmaya çalış.',
      not: 'Karşıtı "fresh food" ya da "whole food"tur.',
    },
    {
      id: 'en-yem-78', on: 'organic', okunus: 'orgenik', tur: 'sıfat',
      arka: 'organik',
      ornek: 'Organic vegetables are more expensive.',
      ornekTr: 'Organik sebzeler daha pahalı.',
      not: 'Kimyada "organik kimya" için de aynı kelime kullanılır.',
    },
    {
      id: 'en-yem-79', on: 'portion', okunus: 'porşın', tur: 'isim',
      arka: 'porsiyon',
      ornek: 'The portions here are huge.',
      ornekTr: 'Buradaki porsiyonlar kocaman.',
      not: 'Tabak "a plate", porsiyon miktarı "a portion"dır.',
    },
    {
      id: 'en-yem-80', on: 'stay hydrated', okunus: 'stey haydreytid', tur: 'kalıp',
      arka: 'su tüketimini sürdürmek',
      ornek: 'Stay hydrated during exams.',
      ornekTr: 'Sınav döneminde suyunu iç.',
      not: 'Sağlık metinlerinde çok geçen resmî bir ifadedir.',
    },
    /* --- Türk mutfağını anlatmak --- */
    {
      id: 'en-yem-81', on: 'stuffed', okunus: 'stafd', tur: 'sıfat',
      arka: 'doldurulmuş (dolma)',
      ornek: 'Stuffed peppers are a Turkish classic.',
      ornekTr: 'Biber dolması bir Türk klasiğidir.',
      not: 'Aynı kelime "tıka basa doymuş" anlamına da gelir.',
    },
    {
      id: 'en-yem-82', on: 'minced meat', okunus: 'minsd miit', tur: 'isim',
      arka: 'kıyma',
      ornek: 'The filling is made with minced meat.',
      ornekTr: 'İç harcı kıymayla yapılıyor.',
      not: 'Amerika\'da "ground beef" denir.',
    },
    {
      id: 'en-yem-83', on: 'pastry', okunus: 'peystri', tur: 'isim',
      arka: 'hamur işi',
      ornek: 'Turkish pastries are famous.',
      ornekTr: 'Türk hamur işleri meşhurdur.',
      not: 'Böreği anlatmak için "a savoury pastry" denebilir.',
    },
    {
      id: 'en-yem-84', on: 'savoury', okunus: 'seyvıri', tur: 'sıfat',
      arka: 'tuzlu (tatlı olmayan)',
      ornek: 'I prefer savoury snacks to sweet ones.',
      ornekTr: 'Tuzlu atıştırmalıkları tatlılara tercih ederim.',
      not: 'Karşıtı "sweet"tir. Amerika\'da "savory" yazılır.',
    },
    {
      id: 'en-yem-85', on: 'yoghurt-based', okunus: 'yogırt beysd', tur: 'sıfat',
      arka: 'yoğurt esaslı',
      ornek: 'Ayran is a yoghurt-based drink.',
      ornekTr: 'Ayran yoğurt esaslı bir içecektir.',
      not: '"-based" eki bir şeyin temelini anlatır: tomato-based sauce.',
    },
    {
      id: 'en-yem-86', on: 'be famous for', okunus: 'bi feymıs for', tur: 'kalıp',
      arka: 'bir şeyle ünlü olmak',
      ornek: 'Gaziantep is famous for its baklava.',
      ornekTr: 'Gaziantep baklavasıyla ünlüdür.',
      not: 'Edatı "for"dur: "famous with" YANLIŞTIR.',
    },
    {
      id: 'en-yem-87', on: 'be served with', okunus: 'bi sörvd vit', tur: 'kalıp',
      arka: 'yanında ... ile servis edilmek',
      ornek: 'It is usually served with rice.',
      ornekTr: 'Genellikle pilavla servis edilir.',
      not: 'Yemek tarif ederken en kullanışlı kalıptır.',
    },
    {
      id: 'en-yem-88', on: 'It tastes like...', okunus: 'it teysts layk', tur: 'kalıp',
      arka: 'Tadı ... gibi',
      ornek: 'It tastes like a thin pizza.',
      ornekTr: 'Tadı ince bir pizza gibi.',
      not: 'Bilinmeyen bir yemeği anlatmanın en kolay yoludur.',
    },
    {
      id: 'en-yem-89', on: 'a must-try', okunus: 'ı mast tray', tur: 'isim',
      arka: 'mutlaka denenmesi gereken',
      ornek: 'Menemen is a must-try for breakfast.',
      ornekTr: 'Menemen kahvaltıda mutlaka denenmeli.',
      not: 'Aynı kalıpla: a must-see, a must-read.',
    },
    {
      id: 'en-yem-90', on: 'help yourself', okunus: 'help yorself', tur: 'kalıp',
      arka: 'buyur, kendin al',
      ornek: 'Help yourself to some more salad.',
      ornekTr: 'Biraz daha salata al, buyur.',
      not: 'Edatı "to"dur: help yourself to something.',
    },
    /* --- Yemekten doğmuş deyimler --- */
    {
      id: 'en-yem-91', on: 'a piece of cake', okunus: 'ı piis ıv keyk', tur: 'deyim',
      arka: 'çok kolay iş',
      ornek: 'The test was a piece of cake.',
      ornekTr: 'Sınav çocuk oyuncağıydı.',
      not: 'Türkçedeki "çocuk oyuncağı" ile aynı işlevdedir.',
    },
    {
      id: 'en-yem-92', on: 'spill the beans', okunus: 'spil dı biinz', tur: 'deyim',
      arka: 'sırrı ağzından kaçırmak',
      ornek: 'Do not spill the beans about the surprise.',
      ornekTr: 'Sürprizi ağzından kaçırma.',
      not: 'Fasulye dökmekle ilgisi yoktur; sır ifşasıdır.',
    },
    {
      id: 'en-yem-93', on: 'bread and butter', okunus: 'bred end batır', tur: 'deyim',
      arka: 'geçim kaynağı',
      ornek: 'Teaching is his bread and butter.',
      ornekTr: 'Öğretmenlik onun geçim kaynağı.',
      not: 'Kelime kelime çevrilirse anlamsızdır; kalıp olarak öğrenilir.',
    },
    {
      id: 'en-yem-94', on: 'take it with a pinch of salt', okunus: 'teyk it vit ı pinç ıv solt', tur: 'deyim',
      arka: 'söylenene tam güvenmemek',
      ornek: 'Take that news with a pinch of salt.',
      ornekTr: 'O habere tam güvenme.',
      not: 'Amerika\'da "a grain of salt" denir.',
    },
    {
      id: 'en-yem-95', on: 'have a lot on my plate', okunus: 'hev ı lot on may pleyt', tur: 'deyim',
      arka: 'başından aşkın işi olmak',
      ornek: 'I cannot help now, I have a lot on my plate.',
      ornekTr: 'Şimdi yardım edemem, işim başımdan aşkın.',
      not: 'Yemekle ilgisi yoktur; yoğunluğu anlatır.',
    },
    {
      id: 'en-yem-96', on: 'food for thought', okunus: 'fud for tot', tur: 'deyim',
      arka: 'düşündürücü şey',
      ornek: 'His question gave me food for thought.',
      ornekTr: 'Sorusu beni düşündürdü.',
      not: 'Yazılı metinlerde sık kullanılan bir kapanış ifadesidir.',
    },
    {
      id: 'en-yem-97', on: 'in a nutshell', okunus: 'in ı natşel', tur: 'deyim',
      arka: 'kısacası, özetle',
      ornek: 'In a nutshell, the plan did not work.',
      ornekTr: 'Kısacası plan işe yaramadı.',
      not: 'Yazma bölümünde özet cümlesi kurmak için idealdir.',
    },
    {
      id: 'en-yem-98', on: 'butterflies in my stomach', okunus: 'batırflayz in may stamık', tur: 'deyim',
      arka: 'heyecandan midesi düğümlenmek',
      ornek: 'I had butterflies in my stomach before the exam.',
      ornekTr: 'Sınavdan önce heyecandan midem düğümlenmişti.',
      not: 'Korkudan çok tatlı bir heyecanı anlatır.',
    },
    {
      id: 'en-yem-99', on: 'cool as a cucumber', okunus: 'kuul ez ı kyukambır', tur: 'deyim',
      arka: 'buz gibi sakin',
      ornek: 'He stayed cool as a cucumber during the interview.',
      ornekTr: 'Mülakat boyunca buz gibi sakin kaldı.',
      not: 'Benzetme kalıbı "as ... as"tir.',
    },
    {
      id: 'en-yem-100', on: 'save it for a rainy day', okunus: 'seyv it for ı reyni dey', tur: 'deyim',
      arka: 'kara gün için saklamak',
      ornek: 'Save some money for a rainy day.',
      ornekTr: 'Biraz parayı kara gün için sakla.',
      not: 'Türkçedeki "kara gün" ile birebir aynı mantıktadır.',
    },
  ],
}

export default DESTE
