/**
 * DESTE — FUTBOL VE SPOR (Almanca)
 *
 * Almancada her isim ARTİKELİYLE öğrenilir; kartların ön yüzünde artikel
 * bu yüzden her zaman var. Artikelsiz öğrenilen bir Almanca isim, o ismi
 * kullanan hiçbir cümlede doğru kurulamaz.
 */

export const DESTE = {
  id: 'futbol-spor',
  dil: 'de',
  ad: 'Futbol ve spor',
  simge: '⚽',
  aciklama: 'Maç anlatımında ve spor haberlerinde geçen kelimeler — artikelleriyle.',
  seviye: 'A1–A2',
  kartlar: [
    {
      id: 'de-fut-01', on: 'das Tor', okunus: 'das tor', tur: 'isim (nötr)',
      arka: 'gol; kale',
      ornek: 'Er hat in der letzten Minute ein Tor geschossen.',
      ornekTr: 'Son dakikada bir gol attı.',
      not: 'Gol atmak "ein Tor schießen"dir. Aynı kelime "kapı" anlamına da gelir.',
    },
    {
      id: 'de-fut-02', on: 'das Spiel', okunus: 'das şpiil', tur: 'isim (nötr)',
      arka: 'maç; oyun',
      ornek: 'Das Spiel beginnt um acht Uhr.',
      ornekTr: 'Maç saat sekizde başlıyor.',
      not: 'Hem maç hem oyun demektir; "spielen" (oynamak) fiilinden gelir.',
    },
    {
      id: 'de-fut-03', on: 'die Mannschaft', okunus: 'di manşaft', tur: 'isim (dişil)',
      arka: 'takım',
      ornek: 'Meine Mannschaft hat gestern gewonnen.',
      ornekTr: 'Takımım dün kazandı.',
      not: 'Milli takım "die Nationalmannschaft". Uzun kelimelerden korkma, birleşiktir.',
    },
    {
      id: 'de-fut-04', on: 'gewinnen', okunus: 'gevinın', tur: 'fiil (düzensiz)',
      arka: 'kazanmak',
      ornek: 'Wir werden dieses Spiel gewinnen.',
      ornekTr: 'Bu maçı kazanacağız.',
      not: 'Geçmiş hâli "gewonnen"dır. Karşıtı "verlieren".',
    },
    {
      id: 'de-fut-05', on: 'verlieren', kok: 'verl', okunus: 'ferliirın', tur: 'fiil (düzensiz)',
      arka: 'kaybetmek',
      ornek: 'Sie haben zwei zu null verloren.',
      ornekTr: 'İki sıfır kaybettiler.',
      not: 'Skor "zu" ile söylenir: zwei zu null (2-0).',
    },
    {
      id: 'de-fut-06', on: 'der Trainer', okunus: 'der trenır', tur: 'isim (eril)',
      arka: 'teknik direktör, antrenör',
      ornek: 'Der Trainer hat drei Spieler ausgewechselt.',
      ornekTr: 'Teknik direktör üç oyuncu değiştirdi.',
      not: 'Dişili "die Trainerin". Meslek adlarının çoğu "-in" ile dişilleşir.',
    },
    {
      id: 'de-fut-07', on: 'der Spieler', okunus: 'der şpiilır', tur: 'isim (eril)',
      arka: 'oyuncu',
      ornek: 'Er ist der beste Spieler der Welt.',
      ornekTr: 'O dünyanın en iyi oyuncusu.',
      not: 'Çoğulu değişmez: die Spieler. "-er" ile biten eril isimlerde sık görülür.',
    },
    {
      id: 'de-fut-08', on: 'trainieren', okunus: 'trenirın', tur: 'fiil',
      arka: 'antrenman yapmak',
      ornek: 'Ich trainiere dreimal pro Woche.',
      ornekTr: 'Haftada üç kez antrenman yapıyorum.',
      not: 'Sıklık "pro Woche" ile söylenir: haftada …',
    },
    {
      id: 'de-fut-09', on: 'der Fan', okunus: 'der fen', tur: 'isim (eril)',
      arka: 'taraftar',
      ornek: 'Ich bin seit meiner Kindheit Fan von diesem Verein.',
      ornekTr: 'Çocukluğumdan beri bu kulübün taraftarıyım.',
      not: 'Kulüp "der Verein". "Fan von + Dativ" kalıbıyla kullanılır.',
    },
    {
      id: 'de-fut-10', on: 'sich verletzen', okunus: 'zih ferletsın', tur: 'fiil (dönüşlü)',
      arka: 'sakatlanmak',
      ornek: 'Er hat sich im Training verletzt.',
      ornekTr: 'Antrenmanda sakatlandı.',
      not: 'Dönüşlü fiildir: ich verletze MICH. Sakatlık "die Verletzung".',
    },
    /* --- Mevkiler ve takım --- */
    {
      id: 'de-fut-11', on: 'der Torwart', okunus: 'der torvart', tur: 'isim (eril)',
      arka: 'kaleci',
      ornek: 'Der Torwart hat den Ball gehalten.',
      ornekTr: 'Kaleci topu tuttu.',
      not: 'Çoğulu "die Torwarte"dir. "Torhüter" de aynı anlama gelir.',
    },
    {
      id: 'de-fut-12', on: 'der Stürmer', okunus: 'der ştürmır', tur: 'isim (eril)',
      arka: 'forvet',
      ornek: 'Der Stürmer ist sehr schnell.',
      ornekTr: 'Forvet çok hızlı.',
      not: '"stürmen" (hücum etmek) fiilinden gelir.',
    },
    {
      id: 'de-fut-13', on: 'der Verteidiger', okunus: 'der fertaydigır', tur: 'isim (eril)',
      arka: 'defans oyuncusu',
      ornek: 'Der Verteidiger spielt sehr ruhig.',
      ornekTr: 'Defans oyuncusu çok sakin oynuyor.',
      not: '"verteidigen" (savunmak) fiilinden türer.',
    },
    {
      id: 'de-fut-14', on: 'der Schiedsrichter', okunus: 'der şiidsrihtır', tur: 'isim (eril)',
      arka: 'hakem',
      ornek: 'Der Schiedsrichter zeigt die rote Karte.',
      ornekTr: 'Hakem kırmızı kart gösteriyor.',
      not: 'Uzun bir kelimedir: Schieds + Richter (yargıç).',
    },
    {
      id: 'de-fut-15', on: 'der Kapitän', okunus: 'der kapiten', tur: 'isim (eril)',
      arka: 'kaptan',
      ornek: 'Unser Kapitän spielt seit zehn Jahren hier.',
      ornekTr: 'Kaptanımız on yıldır burada oynuyor.',
      not: 'Vurgu son hecededir: Kapi-TÄN.',
    },
    {
      id: 'de-fut-16', on: 'die Auswechslung', okunus: 'di ausvekslung', tur: 'isim (dişil)',
      arka: 'oyuncu değişikliği',
      ornek: 'Die Auswechslung kam zu spät.',
      ornekTr: 'Oyuncu değişikliği çok geç geldi.',
      not: 'Fiili "auswechseln"dir ve ayrılabilir bir fiildir.',
    },
    {
      id: 'de-fut-17', on: 'der Verein', okunus: 'der ferayn', tur: 'isim (eril)',
      arka: 'kulüp, dernek',
      ornek: 'Mein Verein hat eine lange Geschichte.',
      ornekTr: 'Kulübümün uzun bir tarihi var.',
      not: 'Spor dışı dernekler için de kullanılır.',
    },
    {
      id: 'de-fut-18', on: 'das Trikot', okunus: 'das trikoo', tur: 'isim (nötr)',
      arka: 'forma',
      ornek: 'Er trägt das Trikot mit der Nummer zehn.',
      ornekTr: 'On numaralı formayı giyiyor.',
      not: 'Fransızcadan gelir, sondaki "t" okunmaz.',
    },
    {
      id: 'de-fut-19', on: 'die Aufstellung', okunus: 'di aufştelung', tur: 'isim (dişil)',
      arka: 'ilk on bir, kadro dizilişi',
      ornek: 'Die Aufstellung steht seit heute Morgen fest.',
      ornekTr: 'Kadro bu sabahtan beri belli.',
      not: '"aufstellen" (dizmek) fiilinden gelir.',
    },
    {
      id: 'de-fut-20', on: 'die Ersatzbank', okunus: 'di erzatsbank', tur: 'isim (dişil)',
      arka: 'yedek kulübesi',
      ornek: 'Er sitzt heute auf der Ersatzbank.',
      ornekTr: 'Bugün yedek kulübesinde oturuyor.',
      not: '"Ersatz" yedek, "Bank" bank demektir.',
    },
    /* --- Maçın içi --- */
    {
      id: 'de-fut-21', on: 'der Anpfiff', okunus: 'der anpfif', tur: 'isim (eril)',
      arka: 'başlama düdüğü',
      ornek: 'Der Anpfiff ist um halb neun.',
      ornekTr: 'Başlama düdüğü sekiz buçukta.',
      not: 'Bitiş düdüğü "der Abpfiff"tir.',
    },
    {
      id: 'de-fut-22', on: 'die Halbzeit', okunus: 'di halptsayt', tur: 'isim (dişil)',
      arka: 'devre, devre arası',
      ornek: 'In der Halbzeit stand es null zu null.',
      ornekTr: 'Devre arasında skor sıfır sıfırdı.',
      not: '"halb" yarım, "Zeit" zaman demektir.',
    },
    {
      id: 'de-fut-23', on: 'der Elfmeter', okunus: 'der elfmeetır', tur: 'isim (eril)',
      arka: 'penaltı',
      ornek: 'Der Schiedsrichter gibt einen Elfmeter.',
      ornekTr: 'Hakem penaltı veriyor.',
      not: 'Kelimenin anlamı "on bir metre"dir; mesafeden gelir.',
    },
    {
      id: 'de-fut-24', on: 'die Ecke', okunus: 'di ekı', tur: 'isim (dişil)',
      arka: 'korner',
      ornek: 'Sie haben eine Ecke bekommen.',
      ornekTr: 'Korner kazandılar.',
      not: 'Günlük dilde "köşe" anlamına da gelir.',
    },
    {
      id: 'de-fut-25', on: 'das Abseits', okunus: 'das apzayts', tur: 'isim (nötr)',
      arka: 'ofsayt',
      ornek: 'Das Tor zählt nicht, es war Abseits.',
      ornekTr: 'Gol sayılmıyor, ofsayttı.',
      not: '"abseits" kelimesi "kenarda, dışarıda" demektir.',
    },
    {
      id: 'de-fut-26', on: 'das Foul', okunus: 'das faul', tur: 'isim (nötr)',
      arka: 'faul',
      ornek: 'Das war ein klares Foul.',
      ornekTr: 'Bu açık bir fauldü.',
      not: 'İngilizceden alınmıştır ve aynı okunur.',
    },
    {
      id: 'de-fut-27', on: 'die gelbe Karte', okunus: 'di gelbı kartı', tur: 'isim (dişil)',
      arka: 'sarı kart',
      ornek: 'Er hat die gelbe Karte bekommen.',
      ornekTr: 'Sarı kart gördü.',
      not: 'Kart "almak" fiili "bekommen"dır, "sehen" değil.',
    },
    {
      id: 'de-fut-28', on: 'die Verlängerung', okunus: 'di ferlengırung', tur: 'isim (dişil)',
      arka: 'uzatma',
      ornek: 'Das Spiel ging in die Verlängerung.',
      ornekTr: 'Maç uzatmalara gitti.',
      not: '"verlängern" (uzatmak) fiilinden gelir.',
    },
    {
      id: 'de-fut-29', on: 'das Elfmeterschießen', okunus: 'das elfmeetırşiisın', tur: 'isim (nötr)',
      arka: 'penaltı atışları',
      ornek: 'Im Elfmeterschießen haben wir verloren.',
      ornekTr: 'Penaltı atışlarında kaybettik.',
      not: 'Üç kelimeden oluşan tipik bir Almanca birleşik isimdir.',
    },
    {
      id: 'de-fut-30', on: 'das Eigentor', okunus: 'das aygıntor', tur: 'isim (nötr)',
      arka: 'kendi kalesine gol',
      ornek: 'Er hat leider ein Eigentor geschossen.',
      ornekTr: 'Maalesef kendi kalesine gol attı.',
      not: 'Günlük dilde "kendi ayağına sıkmak" anlamında da kullanılır.',
    },
    /* --- Oyun fiilleri --- */
    {
      id: 'de-fut-31', on: 'schießen', okunus: 'şiisın', tur: 'fiil (kuvvetli)',
      arka: 'şut atmak, vurmak',
      ornek: 'Er schießt aus zwanzig Metern.',
      ornekTr: 'Yirmi metreden şut atıyor.',
      not: 'Çekimi: schießt · hat geschossen. Gol "schießen" ile atılır.',
    },
    {
      id: 'de-fut-32', on: 'passen', okunus: 'pasın', tur: 'fiil',
      arka: 'pas vermek; uymak',
      ornek: 'Er passt den Ball nach links.',
      ornekTr: 'Topu sola pas veriyor.',
      not: 'Aynı fiil "uymak" anlamına da gelir: "Das passt mir."',
    },
    {
      id: 'de-fut-33', on: 'verteidigen', okunus: 'fertaydigın', tur: 'fiil',
      arka: 'savunmak',
      ornek: 'Wir verteidigen heute sehr gut.',
      ornekTr: 'Bugün çok iyi savunuyoruz.',
      not: 'Mahkemede "savunmak" için de aynı fiil kullanılır.',
    },
    {
      id: 'de-fut-34', on: 'angreifen', okunus: 'angrayfın', tur: 'fiil (ayrılabilir)',
      arka: 'hücum etmek',
      ornek: 'Die Mannschaft greift von der rechten Seite an.',
      ornekTr: 'Takım sağ taraftan hücum ediyor.',
      not: 'Ayrılabilir fiildir: "greift ... an" biçiminde bölünür.',
      kok: 'greif',
    },
    {
      id: 'de-fut-35', on: 'unentschieden spielen', okunus: 'unentşiidın şpiilın', tur: 'kalıp',
      arka: 'berabere kalmak',
      ornek: 'Wir haben unentschieden gespielt.',
      ornekTr: 'Berabere kaldık.',
      not: '"unentschieden" karara bağlanmamış demektir.',
    },
    {
      id: 'de-fut-36', on: 'der Sieg', okunus: 'der ziik', tur: 'isim (eril)',
      arka: 'galibiyet',
      ornek: 'Der Sieg war wichtig für uns.',
      ornekTr: 'Galibiyet bizim için önemliydi.',
      not: 'Fiili "siegen"dir. Yenilgi "die Niederlage"dır.',
    },
    {
      id: 'de-fut-37', on: 'die Niederlage', okunus: 'di niidırlaagı', tur: 'isim (dişil)',
      arka: 'yenilgi',
      ornek: 'Nach der Niederlage waren alle still.',
      ornekTr: 'Yenilgiden sonra herkes sessizdi.',
      not: '"nieder" aşağı, "Lage" durum demektir.',
    },
    {
      id: 'de-fut-38', on: 'der Ball', okunus: 'der bal', tur: 'isim (eril)',
      arka: 'top',
      ornek: 'Der Ball ist im Tor.',
      ornekTr: 'Top kalede.',
      not: 'Çoğulu "die Bälle"dir; Umlaut alır.',
    },
    {
      id: 'de-fut-39', on: 'das Spielfeld', okunus: 'das şpiilfelt', tur: 'isim (nötr)',
      arka: 'saha',
      ornek: 'Die Spieler kommen auf das Spielfeld.',
      ornekTr: 'Oyuncular sahaya çıkıyor.',
      not: '"Platz" da saha anlamında kullanılır.',
    },
    {
      id: 'de-fut-40', on: 'der Punkt', okunus: 'der punkt', tur: 'isim (eril)',
      arka: 'puan',
      ornek: 'Wir brauchen noch drei Punkte.',
      ornekTr: 'Üç puana daha ihtiyacımız var.',
      not: 'Aynı kelime "nokta" anlamına da gelir.',
    },
    /* --- Lig ve turnuva --- */
    {
      id: 'de-fut-41', on: 'die Bundesliga', okunus: 'di bundesliiga', tur: 'isim (dişil)',
      arka: 'Almanya birinci futbol ligi',
      ornek: 'Die Bundesliga beginnt im August.',
      ornekTr: 'Bundesliga ağustosta başlıyor.',
      not: '"Bund" federasyon demektir; Almanya\'nın en üst ligidir.',
    },
    {
      id: 'de-fut-42', on: 'die Tabelle', okunus: 'di tabelı', tur: 'isim (dişil)',
      arka: 'puan tablosu',
      ornek: 'Wir stehen auf Platz drei in der Tabelle.',
      ornekTr: 'Puan tablosunda üçüncü sıradayız.',
      not: 'Sıra bildirirken "auf Platz + sayı" kalıbı kullanılır.',
    },
    {
      id: 'de-fut-43', on: 'der Meister', okunus: 'der maystır', tur: 'isim (eril)',
      arka: 'şampiyon',
      ornek: 'Wer wird dieses Jahr Meister?',
      ornekTr: 'Bu yıl kim şampiyon olacak?',
      not: 'Şampiyonluk "die Meisterschaft"tır.',
    },
    {
      id: 'de-fut-44', on: 'absteigen', okunus: 'apştaygın', tur: 'fiil (ayrılabilir)',
      arka: 'küme düşmek',
      ornek: 'Der Verein steigt in die zweite Liga ab.',
      ornekTr: 'Kulüp ikinci lige düşüyor.',
      not: 'Tersi "aufsteigen" = üst lige çıkmak.',
      kok: 'steig',
    },
    {
      id: 'de-fut-45', on: 'das Derby', okunus: 'das derbi', tur: 'isim (nötr)',
      arka: 'derbi',
      ornek: 'Das Derby ist immer ausverkauft.',
      ornekTr: 'Derbi her zaman tükeniyor.',
      not: '"ausverkauft" = biletleri tükenmiş.',
    },
    {
      id: 'de-fut-46', on: 'der Pokal', okunus: 'der pokaal', tur: 'isim (eril)',
      arka: 'kupa',
      ornek: 'Sie haben den Pokal gewonnen.',
      ornekTr: 'Kupayı kazandılar.',
      not: 'Turnuva adı olarak da kullanılır: "der DFB-Pokal".',
    },
    {
      id: 'de-fut-47', on: 'das Finale', okunus: 'das finaalı', tur: 'isim (nötr)',
      arka: 'final',
      ornek: 'Das Finale findet in Berlin statt.',
      ornekTr: 'Final Berlin\'de yapılıyor.',
      not: '"stattfinden" = gerçekleşmek, ayrılabilir fiildir.',
    },
    {
      id: 'de-fut-48', on: 'das Turnier', okunus: 'das turniir', tur: 'isim (nötr)',
      arka: 'turnuva',
      ornek: 'Unsere Schule organisiert ein Turnier.',
      ornekTr: 'Okulumuz bir turnuva düzenliyor.',
      not: 'Satranç ve tenis için de kullanılır.',
    },
    {
      id: 'de-fut-49', on: 'die Weltmeisterschaft', okunus: 'di veltmaystırşaft', tur: 'isim (dişil)',
      arka: 'dünya kupası',
      ornek: 'Die Weltmeisterschaft ist alle vier Jahre.',
      ornekTr: 'Dünya Kupası dört yılda bir yapılır.',
      not: 'Kısaltması "die WM"dir.',
    },
    {
      id: 'de-fut-50', on: 'das Heimspiel', okunus: 'das haymşpiil', tur: 'isim (nötr)',
      arka: 'iç saha maçı',
      ornek: 'Am Samstag haben wir ein Heimspiel.',
      ornekTr: 'Cumartesi iç saha maçımız var.',
      not: 'Deplasman maçı "das Auswärtsspiel"dir.',
    },
    /* --- Taraftar ve stat --- */
    {
      id: 'de-fut-51', on: 'das Stadion', okunus: 'das ştaadyon', tur: 'isim (nötr)',
      arka: 'stat',
      ornek: 'Das Stadion war voll.',
      ornekTr: 'Stat doluydu.',
      not: 'Çoğulu düzensizdir: "die Stadien".',
    },
    {
      id: 'de-fut-52', on: 'die Tribüne', okunus: 'di tribüünı', tur: 'isim (dişil)',
      arka: 'tribün',
      ornek: 'Wir sitzen auf der Tribüne.',
      ornekTr: 'Tribünde oturuyoruz.',
      not: 'Yer bildirirken "auf" edatı kullanılır.',
    },
    {
      id: 'de-fut-53', on: 'jubeln', okunus: 'yuubıln', tur: 'fiil',
      arka: 'sevinçle bağırmak, tezahürat yapmak',
      ornek: 'Die Fans jubeln nach dem Tor.',
      ornekTr: 'Taraftarlar golden sonra tezahürat yapıyor.',
      not: 'İsmi "der Jubel"dir.',
    },
    {
      id: 'de-fut-54', on: 'pfeifen', okunus: 'pfayfın', tur: 'fiil (kuvvetli)',
      arka: 'ıslık çalmak; düdük çalmak',
      ornek: 'Der Schiedsrichter pfeift ein Foul.',
      ornekTr: 'Hakem faul düdüğü çalıyor.',
      not: 'Çekimi: pfeift · hat gepfiffen.',
    },
    {
      id: 'de-fut-55', on: 'die Stimmung', okunus: 'di ştimung', tur: 'isim (dişil)',
      arka: 'atmosfer, hava',
      ornek: 'Die Stimmung im Stadion war super.',
      ornekTr: 'Stattaki hava harikaydı.',
      not: '"Stimme" ses demektir; "Stimmung" ise ruh hâli ve ortamdır.',
    },
    {
      id: 'de-fut-56', on: 'die Karte', okunus: 'di kartı', tur: 'isim (dişil)',
      arka: 'bilet; kart',
      ornek: 'Ich habe zwei Karten für das Spiel.',
      ornekTr: 'Maç için iki biletim var.',
      not: 'Hem bilet hem harita hem kart anlamına gelir.',
    },
    {
      id: 'de-fut-57', on: 'ausverkauft', okunus: 'ausferkauft', tur: 'sıfat',
      arka: 'biletleri tükenmiş',
      ornek: 'Das Konzert ist ausverkauft.',
      ornekTr: 'Konserin biletleri tükendi.',
      not: 'Konser ve tiyatro için de kullanılır.',
    },
    {
      id: 'de-fut-58', on: 'die Fahne', okunus: 'di faanı', tur: 'isim (dişil)',
      arka: 'bayrak, flama',
      ornek: 'Die Fans schwenken ihre Fahnen.',
      ornekTr: 'Taraftarlar bayraklarını sallıyor.',
      not: '"Flagge" resmî bayrak, "Fahne" taşınan bayraktır.',
    },
    {
      id: 'de-fut-59', on: 'der Zuschauer', okunus: 'der tsuuşauır', tur: 'isim (eril)',
      arka: 'seyirci',
      ornek: 'Vierzigtausend Zuschauer waren im Stadion.',
      ornekTr: 'Statta kırk bin seyirci vardı.',
      not: '"zuschauen" (izlemek) fiilinden gelir.',
    },
    {
      id: 'de-fut-60', on: 'die Mannschaftskasse', okunus: 'di manşaftskası', tur: 'isim (dişil)',
      arka: 'takım kasası',
      ornek: 'Er zahlt zehn Euro in die Mannschaftskasse.',
      ornekTr: 'Takım kasasına on avro ödüyor.',
      not: 'Amatör kulüplerde ceza parası için kullanılır.',
    },
    /* --- Diğer sporlar --- */
    {
      id: 'de-fut-61', on: 'der Handball', okunus: 'der hantbal', tur: 'isim (eril)',
      arka: 'hentbol',
      ornek: 'In Deutschland ist Handball sehr beliebt.',
      ornekTr: 'Almanya\'da hentbol çok popülerdir.',
      not: 'Almanya hentbolde dünya çapında güçlüdür.',
    },
    {
      id: 'de-fut-62', on: 'das Schwimmen', okunus: 'das şvimın', tur: 'isim (nötr)',
      arka: 'yüzme',
      ornek: 'Schwimmen ist gut für den Rücken.',
      ornekTr: 'Yüzmek sırt için iyidir.',
      not: 'Fiilden isim yapılınca daima nötr olur ve büyük yazılır.',
    },
    {
      id: 'de-fut-63', on: 'das Radfahren', okunus: 'das raatfaarın', tur: 'isim (nötr)',
      arka: 'bisiklete binmek',
      ornek: 'Radfahren macht mir Spaß.',
      ornekTr: 'Bisiklete binmek bana keyif veriyor.',
      not: '"Spaß machen" kalıbı "keyif vermek" demektir.',
    },
    {
      id: 'de-fut-64', on: 'die Leichtathletik', okunus: 'di layhtatleetik', tur: 'isim (dişil)',
      arka: 'atletizm',
      ornek: 'Leichtathletik trainiert man am besten draußen.',
      ornekTr: 'Atletizm en iyi dışarıda çalışılır.',
      not: '"leicht" hafif demektir; ağır atletizm "Schwerathletik"tir.',
    },
    {
      id: 'de-fut-65', on: 'der Wettkampf', okunus: 'der vetkampf', tur: 'isim (eril)',
      arka: 'yarışma, müsabaka',
      ornek: 'Der Wettkampf beginnt um zehn.',
      ornekTr: 'Müsabaka saat onda başlıyor.',
      not: '"Wette" bahis, "Kampf" mücadele demektir.',
    },
    {
      id: 'de-fut-66', on: 'die Medaille', okunus: 'di medaalyı', tur: 'isim (dişil)',
      arka: 'madalya',
      ornek: 'Sie hat eine Medaille gewonnen.',
      ornekTr: 'Bir madalya kazandı.',
      not: 'Fransızca kökenlidir; "-aille" bölümü "alyı" okunur.',
    },
    {
      id: 'de-fut-67', on: 'der Rekord', okunus: 'der rekort', tur: 'isim (eril)',
      arka: 'rekor',
      ornek: 'Er hat einen neuen Rekord aufgestellt.',
      ornekTr: 'Yeni bir rekor kırdı.',
      not: 'Rekor "aufstellen" ile kurulur, "brechen" ile kırılır.',
    },
    {
      id: 'de-fut-68', on: 'die Mitgliedschaft', okunus: 'di mitgliitşaft', tur: 'isim (dişil)',
      arka: 'üyelik',
      ornek: 'Die Mitgliedschaft im Verein kostet wenig.',
      ornekTr: 'Kulüpteki üyelik az tutuyor.',
      not: '"Mitglied" üye demektir; "-schaft" eki durum bildirir.',
    },
    {
      id: 'de-fut-69', on: 'die Sporthalle', okunus: 'di şporthalı', tur: 'isim (dişil)',
      arka: 'spor salonu',
      ornek: 'Wir trainieren in der Sporthalle.',
      ornekTr: 'Spor salonunda antrenman yapıyoruz.',
      not: 'Fitness salonu için "das Fitnessstudio" denir.',
    },
    {
      id: 'de-fut-70', on: 'Sport treiben', okunus: 'şport traybın', tur: 'kalıp',
      arka: 'spor yapmak',
      ornek: 'Man soll dreimal pro Woche Sport treiben.',
      ornekTr: 'Haftada üç kez spor yapmak gerekir.',
      not: '"Sport machen" da kullanılır ama "treiben" daha doğrudur.',
    },
    /* --- Antrenman ve beden --- */
    {
      id: 'de-fut-71', on: 'das Training', okunus: 'das treening', tur: 'isim (nötr)',
      arka: 'antrenman',
      ornek: 'Das Training fällt heute aus.',
      ornekTr: 'Antrenman bugün iptal.',
      not: '"ausfallen" = iptal olmak, ayrılabilir fiildir.',
    },
    {
      id: 'de-fut-72', on: 'sich aufwärmen', okunus: 'zih aufvermın', tur: 'fiil (dönüşlü)',
      arka: 'ısınmak',
      ornek: 'Wir wärmen uns zehn Minuten auf.',
      ornekTr: 'On dakika ısınıyoruz.',
      not: 'Hem dönüşlü hem ayrılabilir bir fiildir: "wärmen uns ... auf".',
      kok: 'wärm',
    },
    {
      id: 'de-fut-73', on: 'die Ausdauer', okunus: 'di ausdauır', tur: 'isim (dişil)',
      arka: 'dayanıklılık',
      ornek: 'Laufen verbessert die Ausdauer.',
      ornekTr: 'Koşmak dayanıklılığı artırır.',
      not: '"dauern" (sürmek) fiilinden gelir.',
    },
    {
      id: 'de-fut-74', on: 'die Verletzung', okunus: 'di ferletsung', tur: 'isim (dişil)',
      arka: 'sakatlık, yaralanma',
      ornek: 'Die Verletzung war zum Glück nicht schlimm.',
      ornekTr: 'Sakatlık neyse ki ciddi değildi.',
      not: '"zum Glück" = neyse ki.',
    },
    {
      id: 'de-fut-75', on: 'sich erholen', okunus: 'zih erhoolın', tur: 'fiil (dönüşlü)',
      arka: 'dinlenmek, toparlanmak',
      ornek: 'Er erholt sich nach dem Spiel.',
      ornekTr: 'Maçtan sonra toparlanıyor.',
      not: 'Dönüşlü zamir zorunludur: sich erholen.',
    },
    {
      id: 'de-fut-76', on: 'der Muskelkater', okunus: 'der muskılkaatır', tur: 'isim (eril)',
      arka: 'kas ağrısı (spor sonrası)',
      ornek: 'Ich habe Muskelkater vom Training.',
      ornekTr: 'Antrenmandan kas ağrım var.',
      not: 'Kelimesi kelimesine "kas kedisi"dir; şaşırtıcı ama doğrudur.',
    },
    {
      id: 'de-fut-77', on: 'fit sein', okunus: 'fit zayn', tur: 'kalıp',
      arka: 'formda olmak',
      ornek: 'Er ist wieder fit.',
      ornekTr: 'Yeniden formda.',
      not: 'İngilizceden alınmış bir sıfattır ve çok yaygındır.',
    },
    {
      id: 'de-fut-78', on: 'aufgeben', okunus: 'aufgeebın', tur: 'fiil (ayrılabilir)',
      arka: 'pes etmek, vazgeçmek',
      ornek: 'Er gibt niemals auf.',
      ornekTr: 'Asla pes etmiyor.',
      not: 'Ayrılabilir fiildir: "gibt ... auf".',
      kok: 'gib',
    },
    {
      id: 'de-fut-79', on: 'sich anstrengen', okunus: 'zih anştrengın', tur: 'fiil (dönüşlü)',
      arka: 'kendini zorlamak, çabalamak',
      ornek: 'Du musst dich mehr anstrengen.',
      ornekTr: 'Daha çok çabalaman gerekiyor.',
      not: 'Sıfatı "anstrengend" = yorucu.',
    },
    {
      id: 'de-fut-80', on: 'schwitzen', okunus: 'şvitsın', tur: 'fiil',
      arka: 'terlemek',
      ornek: 'Beim Training schwitzt man viel.',
      ornekTr: 'Antrenmanda çok terlenir.',
      not: '"beim + isim" kalıbı "... sırasında" demektir.',
    },
    /* --- Konuşma kalıpları --- */
    {
      id: 'de-fut-81', on: 'Wie steht es?', okunus: 'vii şteet es', tur: 'soru kalıbı',
      arka: 'Skor kaç?',
      ornek: 'Wie steht es? - Zwei zu eins.',
      ornekTr: 'Skor kaç? - İki bir.',
      not: 'Skor "zwei zu eins" biçiminde söylenir.',
    },
    {
      id: 'de-fut-82', on: 'Wer hat gewonnen?', okunus: 'veer hat gıvonın', tur: 'soru kalıbı',
      arka: 'Kim kazandı?',
      ornek: 'Wer hat gestern gewonnen?',
      ornekTr: 'Dün kim kazandı?',
      not: 'Geçmiş zaman "haben + Partizip" ile kurulur.',
    },
    {
      id: 'de-fut-83', on: 'Ich drücke dir die Daumen', okunus: 'ih drükı dir di daumın', tur: 'deyim',
      arka: 'Sana şans diliyorum',
      ornek: 'Viel Erfolg! Ich drücke dir die Daumen.',
      ornekTr: 'Bol şans! Sana şans diliyorum.',
      not: 'Kelimesi kelimesine "başparmaklarını sıkıyorum" demektir.',
    },
    {
      id: 'de-fut-84', on: 'Das war knapp', okunus: 'das var knap', tur: 'kalıp',
      arka: 'Kıl payıydı',
      ornek: 'Das war knapp, nur ein Tor Unterschied.',
      ornekTr: 'Kıl payıydı, sadece bir gol farkı.',
      not: '"knapp" az, dar, kıt anlamına gelir.',
    },
    {
      id: 'de-fut-85', on: 'am Ball bleiben', okunus: 'am bal blaybın', tur: 'deyim',
      arka: 'peşini bırakmamak, ısrarla sürdürmek',
      ornek: 'Bleib am Ball, du schaffst das!',
      ornekTr: 'Peşini bırakma, başaracaksın!',
      not: 'Futboldan gelir ama iş ve ders için de kullanılır.',
    },
    {
      id: 'de-fut-86', on: 'die Nase vorn haben', okunus: 'di naazı forn haabın', tur: 'deyim',
      arka: 'önde olmak, üstün gelmek',
      ornek: 'In der zweiten Halbzeit hatten wir die Nase vorn.',
      ornekTr: 'İkinci yarıda biz öndeydik.',
      not: 'At yarışından gelir; burun farkı imgesidir.',
    },
    {
      id: 'de-fut-87', on: 'das Handtuch werfen', okunus: 'das hanttuuh verfın', tur: 'deyim',
      arka: 'havlu atmak, pes etmek',
      ornek: 'Er wollte das Handtuch werfen, machte aber weiter.',
      ornekTr: 'Havlu atmak istedi ama devam etti.',
      not: 'Türkçedeki "havlu atmak" ile birebir aynıdır.',
    },
    {
      id: 'de-fut-88', on: 'ins Schwarze treffen', okunus: 'ins şvartsı trefın', tur: 'deyim',
      arka: 'tam on ikiden vurmak',
      ornek: 'Mit dieser Antwort hat er ins Schwarze getroffen.',
      ornekTr: 'Bu cevapla tam on ikiden vurdu.',
      not: 'Okçuluktaki hedefin siyah merkezinden gelir.',
    },
    {
      id: 'de-fut-89', on: 'der Außenseiter', okunus: 'der ausınzaytır', tur: 'isim (eril)',
      arka: 'zayıf görülen taraf',
      ornek: 'Der Außenseiter hat überraschend gewonnen.',
      ornekTr: 'Zayıf görülen taraf sürpriz bir galibiyet aldı.',
      not: 'Favori taraf "der Favorit"tir.',
    },
    {
      id: 'de-fut-90', on: 'die Mannschaftsleistung', okunus: 'di manşaftslaystung', tur: 'isim (dişil)',
      arka: 'takım performansı',
      ornek: 'Das war eine starke Mannschaftsleistung.',
      ornekTr: 'Bu güçlü bir takım performansıydı.',
      not: '"Leistung" performans, başarım demektir.',
    },
    /* --- Spor haberleri dili --- */
    {
      id: 'de-fut-91', on: 'der Wechsel', okunus: 'der vekısıl', tur: 'isim (eril)',
      arka: 'transfer, değişim',
      ornek: 'Der Wechsel zu einem großen Verein war teuer.',
      ornekTr: 'Büyük bir kulübe transfer pahalıydı.',
      not: '"wechseln" (değiştirmek) fiilinden gelir.',
    },
    {
      id: 'de-fut-92', on: 'die Saison', okunus: 'di zezoong', tur: 'isim (dişil)',
      arka: 'sezon',
      ornek: 'Die Saison endet im Mai.',
      ornekTr: 'Sezon mayısta bitiyor.',
      not: 'Fransızca kökenlidir, burun sesiyle okunur.',
    },
    {
      id: 'de-fut-93', on: 'der Gegner', okunus: 'der geegnır', tur: 'isim (eril)',
      arka: 'rakip',
      ornek: 'Unser Gegner ist sehr stark.',
      ornekTr: 'Rakibimiz çok güçlü.',
      not: '"gegen" (karşı) edatından gelir.',
    },
    {
      id: 'de-fut-94', on: 'überraschend', okunus: 'übırraşınt', tur: 'sıfat',
      arka: 'şaşırtıcı',
      ornek: 'Das Ergebnis war überraschend.',
      ornekTr: 'Sonuç şaşırtıcıydı.',
      not: 'Fiili "überraschen" = şaşırtmak.',
    },
    {
      id: 'de-fut-95', on: 'das Ergebnis', okunus: 'das ergeepnis', tur: 'isim (nötr)',
      arka: 'sonuç',
      ornek: 'Das Ergebnis war zwei zu null.',
      ornekTr: 'Sonuç iki sıfırdı.',
      not: 'Sınav sonucu için de aynı kelime kullanılır.',
    },
    {
      id: 'de-fut-96', on: 'spannend', okunus: 'şpanınt', tur: 'sıfat',
      arka: 'heyecanlı, sürükleyici',
      ornek: 'Das Spiel war sehr spannend.',
      ornekTr: 'Maç çok heyecanlıydı.',
      not: 'Kitap ve film için de kullanılır.',
    },
    {
      id: 'de-fut-97', on: 'langweilig', okunus: 'langvaylih', tur: 'sıfat',
      arka: 'sıkıcı',
      ornek: 'Die erste Halbzeit war langweilig.',
      ornekTr: 'İlk yarı sıkıcıydı.',
      not: '"lange Weile" (uzun süre) ifadesinden gelir.',
    },
    {
      id: 'de-fut-98', on: 'verdient', okunus: 'ferdiint', tur: 'sıfat',
      arka: 'hak edilmiş',
      ornek: 'Der Sieg war verdient.',
      ornekTr: 'Galibiyet hak edilmişti.',
      not: 'Fiili "verdienen" = hak etmek, kazanmak.',
    },
    {
      id: 'de-fut-99', on: 'die Leidenschaft', okunus: 'di laydınşaft', tur: 'isim (dişil)',
      arka: 'tutku',
      ornek: 'Fußball ist seine große Leidenschaft.',
      ornekTr: 'Futbol onun büyük tutkusu.',
      not: '"Leiden" acı çekmek demektir; tutku acıyla akrabadır.',
    },
    {
      id: 'de-fut-100', on: 'Fair Play', okunus: 'feer pley', tur: 'isim (nötr)',
      arka: 'centilmence oyun',
      ornek: 'Fair Play ist wichtiger als der Sieg.',
      ornekTr: 'Centilmence oyun galibiyetten önemlidir.',
      not: 'İngilizceden alınmıştır ve Almancada da aynı yazılır.',
    },
  ],
}

export default DESTE
