/**
 * DESTE — GÜNLÜK KONUŞMA (Almanca)
 *
 * Almanca ders kitapları resmî dili öğretir; sokakta konuşulan Almanca
 * daha kısadır ve kalıplarla ilerler. Bu deste o boşluğu kapatır.
 *
 * Her kartta KAYIT uyarısı var: bu kalıpların çoğu samimidir, resmî
 * ortamda ve "Sie" ile konuşurken kullanılmaz.
 */

export const DESTE = {
  id: 'gunluk-konusma',
  dil: 'de',
  ad: 'Günlük konuşma',
  simge: '💬',
  aciklama: 'Kitapların yazmadığı, Almanların sürekli söylediği kalıplar.',
  seviye: 'A2',
  kartlar: [
    {
      id: 'de-gun-01', on: 'Alles klar?', okunus: 'alıs klaar', tur: 'kalıp',
      arka: 'Her şey yolunda mı? / Tamam mı?',
      ornek: 'Hey, alles klar bei dir?',
      ornekTr: 'Selam, sende her şey yolunda mı?',
      not: 'Hem soru hem onaydır: "— Alles klar? — Alles klar."',
    },
    {
      id: 'de-gun-02', on: 'Was geht?', okunus: 'vas geet', tur: 'kalıp (argo)',
      arka: 'Naber?',
      ornek: 'Was geht, wie war dein Wochenende?',
      ornekTr: 'Naber, hafta sonun nasıldı?',
      not: 'Çok samimidir; yalnız yakın arkadaşa söylenir.',
    },
    {
      id: 'de-gun-03', on: 'Quatsch!', okunus: 'kvaç', tur: 'ünlem',
      arka: 'Saçmalık!',
      ornek: 'Quatsch, das stimmt überhaupt nicht!',
      ornekTr: 'Saçmalık, bu hiç doğru değil!',
      not: '"Unsinn" daha kibar, "Quatsch" daha günlük biçimdir.',
    },
    {
      id: 'de-gun-04', on: 'Genau', okunus: 'genau', tur: 'zarf',
      arka: 'Aynen, kesinlikle',
      ornek: 'Genau, das wollte ich auch sagen.',
      ornekTr: 'Aynen, ben de onu söyleyecektim.',
      not: 'Almanların en çok kullandığı onay kelimesi. Sohbette sürekli duyulur.',
    },
    {
      id: 'de-gun-05', on: 'Keine Ahnung', okunus: 'kaynı aanung', tur: 'kalıp',
      arka: 'Hiçbir fikrim yok',
      ornek: 'Keine Ahnung, frag lieber den Lehrer.',
      ornekTr: 'Hiçbir fikrim yok, en iyisi öğretmene sor.',
      not: '"Ich weiß nicht"ten daha doğal ve daha sık kullanılır.',
    },
    {
      id: 'de-gun-06', on: 'Ich habe keine Lust', okunus: 'ih haabı kaynı lust', tur: 'kalıp',
      arka: 'Canım istemiyor',
      ornek: 'Ich habe heute keine Lust auszugehen.',
      ornekTr: 'Bugün dışarı çıkmak istemiyorum.',
      not: 'Karşıtı "Ich habe Lust auf…" (canım … istiyor).',
    },
    {
      id: 'de-gun-07', on: 'Passt', okunus: 'past', tur: 'kalıp',
      arka: 'Uyar, olur',
      ornek: 'Um sechs? Passt!',
      ornekTr: 'Altıda mı? Olur!',
      not: '"passen" (uymak) fiilinden. Kısa onay için tek kelime yeter.',
    },
    {
      id: 'de-gun-08', on: 'echt', okunus: 'eht', tur: 'zarf',
      arka: 'gerçekten, cidden',
      ornek: 'Das war echt gut!',
      ornekTr: 'Bu cidden iyiydi!',
      not: '"wirklich" ile aynı anlamdadır ama konuşmada çok daha sık duyulur.',
    },
    {
      id: 'de-gun-09', on: 'Mach\'s gut', okunus: 'mahs guut', tur: 'kalıp',
      arka: 'Kendine iyi bak, görüşürüz',
      ornek: 'Ich muss los. Mach\'s gut!',
      ornekTr: 'Gitmem lazım. Kendine iyi bak!',
      not: 'Vedalaşmanın samimi biçimi. Cevabı "Du auch!"tur.',
    },
    {
      id: 'de-gun-10', on: 'Bis dann', okunus: 'bis dan', tur: 'kalıp',
      arka: 'Görüşürüz',
      ornek: 'Okay, bis dann!',
      ornekTr: 'Tamam, görüşürüz!',
      not: 'Ailesi: bis später (sonra), bis morgen (yarın), bis bald (yakında).',
    },
    /* --- Selamlaşma ve vedalaşma --- */
    {
      id: 'de-gun-11', on: 'Wie geht es dir?', okunus: 'vii geet es dir', tur: 'soru kalıbı',
      arka: 'Nasılsın?',
      ornek: 'Hallo Ali, wie geht es dir?',
      ornekTr: 'Merhaba Ali, nasılsın?',
      not: 'Konuşmada "Wie geht\'s?" diye kısaltılır. Resmî hâli "Wie geht es Ihnen?"',
    },
    {
      id: 'de-gun-12', on: 'Mir geht es gut', okunus: 'mir geet es guut', tur: 'kalıp',
      arka: 'İyiyim',
      ornek: 'Danke, mir geht es gut.',
      ornekTr: 'Teşekkürler, iyiyim.',
      not: 'Kişi Dativ olur: mir, dir, ihm. "Ich bin gut" YANLIŞTIR.',
    },
    {
      id: 'de-gun-13', on: 'Es geht so', okunus: 'es geet zoo', tur: 'kalıp',
      arka: 'Şöyle böyle',
      ornek: 'Wie geht\'s? - Es geht so.',
      ornekTr: 'Nasılsın? - Şöyle böyle.',
      not: 'Ne iyi ne kötü anlamına gelen dürüst bir cevaptır.',
    },
    {
      id: 'de-gun-14', on: 'Grüß dich', okunus: 'grüüs dih', tur: 'kalıp',
      arka: 'Selam',
      ornek: 'Grüß dich, lange nicht gesehen!',
      ornekTr: 'Selam, görüşmeyeli çok oldu!',
      not: 'Güney Almanya\'da yaygındır; kuzeyde "Hallo" denir.',
    },
    {
      id: 'de-gun-15', on: 'Servus', okunus: 'zervus', tur: 'kalıp',
      arka: 'Selam / hoşça kal (Güney)',
      ornek: 'Servus, bis morgen!',
      ornekTr: 'Selam, yarın görüşürüz!',
      not: 'Bavyera ve Avusturya\'da hem selam hem veda olarak kullanılır.',
    },
    {
      id: 'de-gun-16', on: 'Auf Wiedersehen', okunus: 'auf viidırzeeın', tur: 'kalıp',
      arka: 'Hoşça kalın (resmî)',
      ornek: 'Auf Wiedersehen, Frau Meier.',
      ornekTr: 'Hoşça kalın Bayan Meier.',
      not: 'Telefonda "Auf Wiederhören" denir; "hören" duymaktır.',
    },
    {
      id: 'de-gun-17', on: 'Schönes Wochenende', okunus: 'şöönıs vohınendı', tur: 'kalıp',
      arka: 'İyi hafta sonları',
      ornek: 'Schönes Wochenende! - Danke, gleichfalls.',
      ornekTr: 'İyi hafta sonları! - Sağ ol, sana da.',
      not: '"gleichfalls" = sana da, size de.',
    },
    {
      id: 'de-gun-18', on: 'Bis bald', okunus: 'bis balt', tur: 'kalıp',
      arka: 'Yakında görüşürüz',
      ornek: 'Ich muss los. Bis bald!',
      ornekTr: 'Gitmem lazım. Yakında görüşürüz!',
      not: '"bis" ile veda kalıpları: bis morgen, bis später, bis nachher.',
    },
    {
      id: 'de-gun-19', on: 'Ich muss los', okunus: 'ih mus loos', tur: 'kalıp',
      arka: 'Gitmem lazım',
      ornek: 'Sorry, ich muss los, mein Bus kommt.',
      ornekTr: 'Kusura bakma, gitmem lazım, otobüsüm geliyor.',
      not: '"losmüssen" gitmek zorunda olmak demektir; fiil düşer.',
    },
    {
      id: 'de-gun-20', on: 'Lange nicht gesehen', okunus: 'langı niht gızeeın', tur: 'kalıp',
      arka: 'Görüşmeyeli çok oldu',
      ornek: 'Mensch, lange nicht gesehen!',
      ornekTr: 'Vay, görüşmeyeli çok oldu!',
      not: '"Mensch!" burada şaşkınlık ünlemidir.',
    },
    /* --- Fikir ve görüş --- */
    {
      id: 'de-gun-21', on: 'Ich glaube', okunus: 'ih glaubı', tur: 'kalıp',
      arka: 'Sanırım',
      ornek: 'Ich glaube, er kommt später.',
      ornekTr: 'Sanırım daha sonra gelir.',
      not: 'Sonrasında virgül gelir ve yan cümle kurulur.',
    },
    {
      id: 'de-gun-22', on: 'Ich denke schon', okunus: 'ih denkı şoon', tur: 'kalıp',
      arka: 'Bence öyle',
      ornek: 'Kommt sie mit? - Ich denke schon.',
      ornekTr: 'O da geliyor mu? - Bence öyle.',
      not: '"schon" burada onay pekiştirir.',
    },
    {
      id: 'de-gun-23', on: 'Ehrlich gesagt', okunus: 'eerlih gızaakt', tur: 'kalıp',
      arka: 'Açıkçası',
      ornek: 'Ehrlich gesagt, das gefällt mir nicht.',
      ornekTr: 'Açıkçası bu hoşuma gitmiyor.',
      not: 'Cümle başında kullanılır ve virgülle ayrılır.',
    },
    {
      id: 'de-gun-24', on: 'Da hast du recht', okunus: 'da hast du reht', tur: 'kalıp',
      arka: 'Bu konuda haklısın',
      ornek: 'Da hast du völlig recht.',
      ornekTr: 'Bu konuda tamamen haklısın.',
      not: '"recht haben" = haklı olmak; "recht sein" farklı anlamdadır.',
    },
    {
      id: 'de-gun-25', on: 'Das stimmt', okunus: 'das ştimt', tur: 'kalıp',
      arka: 'Doğru',
      ornek: 'Das stimmt, ich habe es vergessen.',
      ornekTr: 'Doğru, unutmuşum.',
      not: 'Karşıtı "Das stimmt nicht" = bu doğru değil.',
    },
    {
      id: 'de-gun-26', on: 'Ich sehe das anders', okunus: 'ih zeeı das andırs', tur: 'kalıp',
      arka: 'Ben farklı düşünüyorum',
      ornek: 'Ich sehe das ein bisschen anders.',
      ornekTr: 'Ben bunu biraz farklı görüyorum.',
      not: 'Kibarca karşı çıkmanın en güvenli yoludur.',
    },
    {
      id: 'de-gun-27', on: 'einerseits ... andererseits', okunus: 'aynırzayts ... andırırzayts', tur: 'bağlaç',
      arka: 'bir yandan ... öte yandan',
      ornek: 'Einerseits ist es teuer, andererseits ist es gut.',
      ornekTr: 'Bir yandan pahalı, öte yandan iyi.',
      not: 'Kompozisyonda iki yönü dengelemenin klasik kalıbıdır.',
    },
    {
      id: 'de-gun-28', on: 'Es kommt darauf an', okunus: 'es komt darauf an', tur: 'kalıp',
      arka: 'Duruma bağlı',
      ornek: 'Es kommt darauf an, wie viel Zeit wir haben.',
      ornekTr: 'Ne kadar vaktimiz olduğuna bağlı.',
      not: 'Kesin cevap vermekten kaçınmanın doğal yoludur.',
    },
    {
      id: 'de-gun-29', on: 'Kein Wunder', okunus: 'kayn vundır', tur: 'kalıp',
      arka: 'Şaşırmadım, doğal',
      ornek: 'Kein Wunder, dass du müde bist.',
      ornekTr: 'Yorgun olmana şaşmamalı.',
      not: '"das Wunder" mucize demektir.',
    },
    {
      id: 'de-gun-30', on: 'Auf jeden Fall', okunus: 'auf yeedın fal', tur: 'kalıp',
      arka: 'Kesinlikle',
      ornek: 'Auf jeden Fall komme ich mit.',
      ornekTr: 'Kesinlikle ben de geliyorum.',
      not: 'Cümle başında kullanılırsa fiil hemen arkasından gelir.',
    },
    /* --- Rica ve izin --- */
    {
      id: 'de-gun-31', on: 'Könntest du...?', okunus: 'köntıst du', tur: 'soru kalıbı',
      arka: '... yapabilir misin?',
      ornek: 'Könntest du mir kurz helfen?',
      ornekTr: 'Bana kısaca yardım edebilir misin?',
      not: '"kannst du" doğrudandır; "könntest du" daha kibardır.',
    },
    {
      id: 'de-gun-32', on: 'Darf ich...?', okunus: 'darf ih', tur: 'soru kalıbı',
      arka: '... yapabilir miyim? (izin)',
      ornek: 'Darf ich hier sitzen?',
      ornekTr: 'Buraya oturabilir miyim?',
      not: '"dürfen" izin, "können" yeterlilik bildirir.',
    },
    {
      id: 'de-gun-33', on: 'Wärst du so nett...?', okunus: 'veerst du zoo net', tur: 'soru kalıbı',
      arka: 'Şu iyiliği yapar mısın?',
      ornek: 'Wärst du so nett und machst das Fenster zu?',
      ornekTr: 'Bir iyilik yapıp pencereyi kapatır mısın?',
      not: 'En kibar rica kalıplarından biridir.',
    },
    {
      id: 'de-gun-34', on: 'Kein Problem', okunus: 'kayn problem', tur: 'kalıp',
      arka: 'Sorun değil',
      ornek: 'Danke fürs Warten. - Kein Problem.',
      ornekTr: 'Beklediğin için sağ ol. - Sorun değil.',
      not: 'Hem teşekküre hem özre cevap olur.',
    },
    {
      id: 'de-gun-35', on: 'Gern geschehen', okunus: 'gern gışeeın', tur: 'kalıp',
      arka: 'Rica ederim',
      ornek: 'Vielen Dank! - Gern geschehen.',
      ornekTr: 'Çok teşekkürler! - Rica ederim.',
      not: '"Bitte" de aynı işlevi görür ve daha kısadır.',
    },
    {
      id: 'de-gun-36', on: 'Entschuldigung', okunus: 'entşuldigung', tur: 'kalıp',
      arka: 'Affedersiniz / pardon',
      ornek: 'Entschuldigung, wo ist die Post?',
      ornekTr: 'Affedersiniz, postane nerede?',
      not: 'Hem özür hem yabancıya seslenme işlevi görür.',
    },
    {
      id: 'de-gun-37', on: 'Es tut mir leid', okunus: 'es tuut mir layt', tur: 'kalıp',
      arka: 'Üzgünüm',
      ornek: 'Es tut mir leid, ich habe es vergessen.',
      ornekTr: 'Üzgünüm, unuttum.',
      not: '"Entschuldigung" küçük şeyler, "Es tut mir leid" gerçek üzüntü içindir.',
    },
    {
      id: 'de-gun-38', on: 'Macht nichts', okunus: 'maht nihts', tur: 'kalıp',
      arka: 'Önemli değil',
      ornek: 'Tut mir leid! - Macht nichts.',
      ornekTr: 'Özür dilerim! - Önemli değil.',
      not: 'Özrü kabul etmenin en kısa yoludur.',
    },
    {
      id: 'de-gun-39', on: 'Bescheid sagen', okunus: 'bışayt zaagın', tur: 'kalıp',
      arka: 'haber vermek',
      ornek: 'Sag mir bitte Bescheid.',
      ornekTr: 'Lütfen bana haber ver.',
      not: '"Bescheid" büyük harfle yazılır ve artikel almaz.',
    },
    {
      id: 'de-gun-40', on: 'Bitte schön', okunus: 'bitı şöön', tur: 'kalıp',
      arka: 'Buyurun / rica ederim',
      ornek: 'Hier ist dein Kaffee. - Danke! - Bitte schön.',
      ornekTr: 'Kahven burada. - Sağ ol! - Rica ederim.',
      not: 'Bir şey uzatırken de teşekküre cevap verirken de kullanılır.',
    },
    /* --- Teklif ve plan --- */
    {
      id: 'de-gun-41', on: 'Wollen wir...?', okunus: 'volın vir', tur: 'soru kalıbı',
      arka: '... yapalım mı?',
      ornek: 'Wollen wir einen Kaffee trinken?',
      ornekTr: 'Kahve içelim mi?',
      not: 'Teklif sunmanın en doğal yoludur.',
    },
    {
      id: 'de-gun-42', on: 'Hast du Lust?', okunus: 'hast du lust', tur: 'soru kalıbı',
      arka: 'Canın ister mi?',
      ornek: 'Hast du Lust auf ein Eis?',
      ornekTr: 'Dondurma ister misin?',
      not: 'Edatı "auf"tur ve Akkusativ ister.',
    },
    {
      id: 'de-gun-43', on: 'Was hältst du davon?', okunus: 'vas heltst du dafon', tur: 'soru kalıbı',
      arka: 'Ne dersin?',
      ornek: 'Wir treffen uns um sechs. Was hältst du davon?',
      ornekTr: 'Altıda buluşuruz. Ne dersin?',
      not: '"halten von" = bir şey hakkında görüş sahibi olmak.',
    },
    {
      id: 'de-gun-44', on: 'Gerne!', okunus: 'gernı', tur: 'kalıp',
      arka: 'Memnuniyetle!',
      ornek: 'Kommst du mit? - Gerne!',
      ornekTr: 'Sen de gelir misin? - Memnuniyetle!',
      not: 'Teklifi kabul etmenin en kısa ve sıcak yoludur.',
    },
    {
      id: 'de-gun-45', on: 'Klingt gut', okunus: 'klingt guut', tur: 'kalıp',
      arka: 'Kulağa hoş geliyor',
      ornek: 'Pizza heute Abend? - Klingt gut!',
      ornekTr: 'Bu akşam pizza? - Kulağa hoş geliyor!',
      not: '"klingen" ses vermek, kulağa gelmek demektir.',
    },
    {
      id: 'de-gun-46', on: 'Leider nicht', okunus: 'laydır niht', tur: 'kalıp',
      arka: 'Maalesef olmaz',
      ornek: 'Kommst du morgen? - Leider nicht.',
      ornekTr: 'Yarın geliyor musun? - Maalesef olmaz.',
      not: 'Kibarca reddetmenin kısa yoludur.',
    },
    {
      id: 'de-gun-47', on: 'Vielleicht ein anderes Mal', okunus: 'fiilayht ayn andırıs maal', tur: 'kalıp',
      arka: 'Belki başka bir zaman',
      ornek: 'Heute geht es nicht, vielleicht ein anderes Mal.',
      ornekTr: 'Bugün olmuyor, belki başka bir zaman.',
      not: 'Reddi yumuşatan bir kapanış cümlesidir.',
    },
    {
      id: 'de-gun-48', on: 'abmachen', okunus: 'apmahın', tur: 'fiil (ayrılabilir)',
      arka: 'kararlaştırmak',
      ornek: 'Wir machen das für Samstag ab.',
      ornekTr: 'Bunu cumartesi için kararlaştırıyoruz.',
      not: '"Abgemacht!" = anlaştık, tamam.',
      kok: 'mach',
    },
    {
      id: 'de-gun-49', on: 'Es passt mir', okunus: 'es past mir', tur: 'kalıp',
      arka: 'Bana uyar',
      ornek: 'Sechs Uhr passt mir gut.',
      ornekTr: 'Saat altı bana iyi uyar.',
      not: '"passen" Dativ ister: "Das passt mir."',
    },
    {
      id: 'de-gun-50', on: 'Ich melde mich', okunus: 'ih meldı mih', tur: 'kalıp',
      arka: 'Sana haber veririm',
      ornek: 'Ich melde mich heute Abend.',
      ornekTr: 'Bu akşam haber veririm.',
      not: 'Dönüşlü fiildir ve çok sık kullanılır.',
    },
    /* --- Duygular --- */
    {
      id: 'de-gun-51', on: 'sich freuen auf', okunus: 'zih froyın auf', tur: 'fiil (dönüşlü)',
      arka: 'dört gözle beklemek',
      ornek: 'Ich freue mich auf die Ferien.',
      ornekTr: 'Tatili dört gözle bekliyorum.',
      not: '"auf" gelecekteki bir şey, "über" olmuş bir şey içindir.',
    },
    {
      id: 'de-gun-52', on: 'sich ärgern über', okunus: 'zih ergırn übır', tur: 'fiil (dönüşlü)',
      arka: 'bir şeye kızmak',
      ornek: 'Ich ärgere mich über den Lärm.',
      ornekTr: 'Gürültüye kızıyorum.',
      not: 'Edatı "über"dir ve Akkusativ ister.',
    },
    {
      id: 'de-gun-53', on: 'Schade!', okunus: 'şaadı', tur: 'ünlem',
      arka: 'Yazık!',
      ornek: 'Du kannst nicht kommen? Schade!',
      ornekTr: 'Gelemiyor musun? Yazık!',
      not: 'Hayal kırıklığını kısa yoldan anlatır.',
    },
    {
      id: 'de-gun-54', on: 'Ich bin gespannt', okunus: 'ih bin gışpant', tur: 'kalıp',
      arka: 'Merakla bekliyorum',
      ornek: 'Ich bin gespannt auf das Ergebnis.',
      ornekTr: 'Sonucu merakla bekliyorum.',
      not: '"spannend" heyecanlı demektir; aynı kökten gelir.',
    },
    {
      id: 'de-gun-55', on: 'Ich bin fertig', okunus: 'ih bin fertih', tur: 'kalıp',
      arka: 'Bitirdim; çok yorgunum',
      ornek: 'Ich bin mit den Hausaufgaben fertig.',
      ornekTr: 'Ödevlerimi bitirdim.',
      not: 'Bağlama göre "bittim, çok yoruldum" anlamına da gelir.',
    },
    {
      id: 'de-gun-56', on: 'Mir ist langweilig', okunus: 'mir ist langvaylih', tur: 'kalıp',
      arka: 'Canım sıkılıyor',
      ornek: 'Mir ist langweilig, machen wir was?',
      ornekTr: 'Canım sıkılıyor, bir şeyler yapalım mı?',
      not: 'Kişi Dativ olur: "Ich bin langweilig" = ben sıkıcı biriyim (yanlış anlam).',
    },
    {
      id: 'de-gun-57', on: 'Ich habe die Nase voll', okunus: 'ih haabı di naazı fol', tur: 'deyim',
      arka: 'Bıktım',
      ornek: 'Ich habe die Nase voll von dem Lärm.',
      ornekTr: 'Bu gürültüden bıktım.',
      not: 'Edatı "von"dur.',
    },
    {
      id: 'de-gun-58', on: 'Zum Glück', okunus: 'tsum glük', tur: 'kalıp',
      arka: 'Neyse ki',
      ornek: 'Zum Glück hat es nicht geregnet.',
      ornekTr: 'Neyse ki yağmur yağmadı.',
      not: 'Cümle başında fiil hemen arkasından gelir.',
    },
    {
      id: 'de-gun-59', on: 'Kopf hoch!', okunus: 'kopf hooh', tur: 'kalıp',
      arka: 'Başını dik tut, moralini bozma!',
      ornek: 'Kopf hoch, das wird schon!',
      ornekTr: 'Moralini bozma, düzelecek!',
      not: '"Das wird schon" = düzelir, olacak.',
    },
    {
      id: 'de-gun-60', on: 'Mach dir nichts draus', okunus: 'mah dir nihts draus', tur: 'kalıp',
      arka: 'Takma kafana',
      ornek: 'Eine Vier ist nicht schlimm, mach dir nichts draus.',
      ornekTr: 'Dört fena değil, kafana takma.',
      not: 'Teselli etmenin gündelik yoludur.',
    },
    /* --- Şaşırma ve tepki --- */
    {
      id: 'de-gun-61', on: 'Wirklich?', okunus: 'virklih', tur: 'ünlem',
      arka: 'Gerçekten mi?',
      ornek: 'Du hast gewonnen? Wirklich?',
      ornekTr: 'Kazandın mı? Gerçekten mi?',
      not: 'Şaşkınlığın en yaygın ifadesidir.',
    },
    {
      id: 'de-gun-62', on: 'Im Ernst?', okunus: 'im ernst', tur: 'ünlem',
      arka: 'Ciddi misin?',
      ornek: 'Im Ernst? Das glaube ich nicht!',
      ornekTr: 'Ciddi misin? Buna inanmıyorum!',
      not: '"der Ernst" ciddiyet demektir.',
    },
    {
      id: 'de-gun-63', on: 'Wahnsinn!', okunus: 'vaanzin', tur: 'ünlem',
      arka: 'İnanılmaz!',
      ornek: 'Zehn Tore? Wahnsinn!',
      ornekTr: 'On gol mü? İnanılmaz!',
      not: 'Kelimenin asıl anlamı "delilik"tir; hayranlık bildirir.',
    },
    {
      id: 'de-gun-64', on: 'Oje!', okunus: 'ooyee', tur: 'ünlem',
      arka: 'Eyvah!',
      ornek: 'Oje, ich habe den Schlüssel vergessen.',
      ornekTr: 'Eyvah, anahtarı unuttum.',
      not: 'Küçük talihsizliklerde kullanılır.',
    },
    {
      id: 'de-gun-65', on: 'Na endlich!', okunus: 'na entlih', tur: 'ünlem',
      arka: 'Nihayet!',
      ornek: 'Na endlich, wir warten seit einer Stunde.',
      ornekTr: 'Nihayet, bir saattir bekliyoruz.',
      not: '"na" konuşmaya duygu katan bir başlangıç sözcüğüdür.',
    },
    {
      id: 'de-gun-66', on: 'Glückwunsch!', okunus: 'glükvunş', tur: 'kalıp',
      arka: 'Tebrikler!',
      ornek: 'Herzlichen Glückwunsch zum Geburtstag!',
      ornekTr: 'Doğum günün kutlu olsun!',
      not: 'Uzun hâli "Herzlichen Glückwunsch"tur.',
    },
    {
      id: 'de-gun-67', on: 'Toi, toi, toi!', okunus: 'toy toy toy', tur: 'kalıp',
      arka: 'Şansın açık olsun!',
      ornek: 'Morgen ist die Prüfung? Toi, toi, toi!',
      ornekTr: 'Yarın sınav mı? Şansın açık olsun!',
      not: 'Tahtaya vurmanın yerini tutan bir uğur ifadesidir.',
    },
    {
      id: 'de-gun-68', on: 'Ach so!', okunus: 'ah zoo', tur: 'ünlem',
      arka: 'Haa, anladım!',
      ornek: 'Ach so, jetzt verstehe ich.',
      ornekTr: 'Haa, şimdi anladım.',
      not: 'Yeni bilgiyi kavradığını gösterir; çok sık kullanılır.',
    },
    {
      id: 'de-gun-69', on: 'Na klar!', okunus: 'na klaar', tur: 'kalıp',
      arka: 'Tabii ki!',
      ornek: 'Hilfst du mir? - Na klar!',
      ornekTr: 'Bana yardım eder misin? - Tabii ki!',
      not: '"Klar" tek başına da kullanılır.',
    },
    {
      id: 'de-gun-70', on: 'Von wegen!', okunus: 'fon veegın', tur: 'ünlem',
      arka: 'Ne münasebet!',
      ornek: 'Er ist müde? Von wegen, er spielt seit Stunden.',
      ornekTr: 'Yorgun mu? Ne münasebet, saatlerdir oynuyor.',
      not: 'Söyleneni kesin biçimde yalanlar.',
    },
    /* --- Telefon ve mesaj --- */
    {
      id: 'de-gun-71', on: 'anrufen', okunus: 'anruufın', tur: 'fiil (ayrılabilir)',
      arka: 'telefonla aramak',
      ornek: 'Ich rufe dich später an.',
      ornekTr: 'Seni sonra ararım.',
      not: 'Ayrılabilir fiildir ve Akkusativ ister: "Ich rufe dich an."',
      kok: 'ruf',
    },
    {
      id: 'de-gun-72', on: 'zurückrufen', okunus: 'tsurükruufın', tur: 'fiil (ayrılabilir)',
      arka: 'geri aramak',
      ornek: 'Kannst du mich zurückrufen?',
      ornekTr: 'Beni geri arayabilir misin?',
      not: '"zurück" geri demektir.',
      kok: 'ruf',
    },
    {
      id: 'de-gun-73', on: 'Einen Moment bitte', okunus: 'aynın momınt bitı', tur: 'kalıp',
      arka: 'Bir dakika lütfen',
      ornek: 'Einen Moment bitte, ich schaue nach.',
      ornekTr: 'Bir dakika lütfen, bakıyorum.',
      not: '"nachschauen" = bakıp kontrol etmek.',
    },
    {
      id: 'de-gun-74', on: 'Ich verstehe dich schlecht', okunus: 'ih ferşteeı dih şleht', tur: 'kalıp',
      arka: 'Seni iyi duyamıyorum',
      ornek: 'Ich verstehe dich schlecht, die Verbindung ist schlecht.',
      ornekTr: 'Seni iyi duyamıyorum, bağlantı kötü.',
      not: 'Telefon görüşmelerinin standart cümlesidir.',
    },
    {
      id: 'de-gun-75', on: 'auflegen', okunus: 'auflegın', tur: 'fiil (ayrılabilir)',
      arka: 'telefonu kapatmak',
      ornek: 'Leg bitte nicht auf.',
      ornekTr: 'Lütfen kapatma.',
      not: 'Ayrılabilir fiildir: "leg ... auf".',
      kok: 'leg',
    },
    {
      id: 'de-gun-76', on: 'schreiben', okunus: 'şraybın', tur: 'fiil (kuvvetli)',
      arka: 'yazmak, mesaj atmak',
      ornek: 'Schreib mir, wenn du da bist.',
      ornekTr: 'Vardığında bana yaz.',
      not: 'Mesajlaşma için de aynı fiil kullanılır.',
    },
    {
      id: 'de-gun-77', on: 'vorbeikommen', okunus: 'forbaykomın', tur: 'fiil (ayrılabilir)',
      arka: 'uğramak',
      ornek: 'Komm doch heute Abend vorbei.',
      ornekTr: 'Bu akşam bir uğra.',
      not: '"doch" burada daveti sıcaklaştırır.',
      kok: 'komm',
    },
    {
      id: 'de-gun-78', on: 'abholen', okunus: 'aphoolın', tur: 'fiil (ayrılabilir)',
      arka: 'almaya gitmek, alıp getirmek',
      ornek: 'Ich hole dich um sieben ab.',
      ornekTr: 'Seni yedide alırım.',
      not: 'Ayrılabilir fiildir: "hole ... ab".',
      kok: 'hol',
    },
    {
      id: 'de-gun-79', on: 'sich beeilen', okunus: 'zih bıaylın', tur: 'fiil (dönüşlü)',
      arka: 'acele etmek',
      ornek: 'Beeil dich, wir sind spät dran!',
      ornekTr: 'Acele et, geç kaldık!',
      not: '"spät dran sein" = geç kalmış olmak.',
    },
    {
      id: 'de-gun-80', on: 'klappen', okunus: 'klapın', tur: 'fiil',
      arka: 'yolunda gitmek, olmak',
      ornek: 'Hat alles geklappt?',
      ornekTr: 'Her şey yolunda gitti mi?',
      not: 'Günlük dilde çok kullanılır: "Es klappt nicht" = olmuyor.',
    },
    /* --- Konuşma akışı ve parçacıklar --- */
    {
      id: 'de-gun-81', on: 'übrigens', okunus: 'übrigıns', tur: 'zarf',
      arka: 'bu arada',
      ornek: 'Übrigens, hast du das Buch gelesen?',
      ornekTr: 'Bu arada, kitabı okudun mu?',
      not: 'Yeni bir konu açarken kullanılır.',
    },
    {
      id: 'de-gun-82', on: 'eigentlich', okunus: 'aygıntlih', tur: 'zarf',
      arka: 'aslında',
      ornek: 'Eigentlich wollte ich früher kommen.',
      ornekTr: 'Aslında daha erken gelmek istiyordum.',
      not: 'Beklenti ile gerçek arasındaki farkı anlatır.',
    },
    {
      id: 'de-gun-83', on: 'trotzdem', okunus: 'trotsdeem', tur: 'zarf',
      arka: 'yine de',
      ornek: 'Es war teuer, trotzdem habe ich es gekauft.',
      ornekTr: 'Pahalıydı, yine de aldım.',
      not: 'Sonrasında fiil öne gelir: "trotzdem habe ich".',
    },
    {
      id: 'de-gun-84', on: 'deshalb', okunus: 'deshalp', tur: 'zarf',
      arka: 'bu yüzden',
      ornek: 'Ich war krank, deshalb bin ich nicht gekommen.',
      ornekTr: 'Hastaydım, bu yüzden gelmedim.',
      not: 'Sebep-sonuç kurmanın en yaygın yoludur.',
    },
    {
      id: 'de-gun-85', on: 'also', okunus: 'alzo', tur: 'zarf',
      arka: 'yani, o hâlde',
      ornek: 'Also, was machen wir jetzt?',
      ornekTr: 'Yani, şimdi ne yapıyoruz?',
      not: 'İngilizce "also" ile karıştırma; o "auch"tur.',
    },
    {
      id: 'de-gun-86', on: 'mal (parçacık)', okunus: 'maal', tur: 'parçacık',
      arka: 'ricayı yumuşatan sözcük',
      ornek: 'Schau mal, was ich gefunden habe.',
      ornekTr: 'Bak hele, ne buldum.',
      not: 'Almancanın kalbi olan modal parçacıklardandır; emri yumuşatır.',
      kok: 'mal',
    },
    {
      id: 'de-gun-87', on: 'doch (parçacık)', okunus: 'doh', tur: 'parçacık',
      arka: 'vurgu ve ısrar katan sözcük',
      ornek: 'Komm doch mit!',
      ornekTr: 'Hadi sen de gel!',
      not: 'Olumsuz soruya olumlu cevap olarak da kullanılır: "Doch!"',
    },
    {
      id: 'de-gun-88', on: 'denn (parçacık)', okunus: 'den', tur: 'parçacık',
      arka: 'soruyu yumuşatan sözcük',
      ornek: 'Wo warst du denn?',
      ornekTr: 'Nerelerdeydin peki?',
      not: 'Soruyu meraklı ve samimi yapar; sorgu havasını alır.',
    },
    {
      id: 'de-gun-89', on: 'ja (parçacık)', okunus: 'yaa', tur: 'parçacık',
      arka: 'bilinen bir şeyi vurgular',
      ornek: 'Das ist ja super!',
      ornekTr: 'Bu harika ya!',
      not: 'Burada "evet" demek değildir; şaşkınlık ya da pekiştirme katar.',
      kok: 'ja',
    },
    {
      id: 'de-gun-90', on: 'halt / eben', okunus: 'halt / eebın', tur: 'parçacık',
      arka: 'işte, öyle',
      ornek: 'Das ist halt so.',
      ornekTr: 'İşte böyle, elden bir şey gelmez.',
      not: 'Kabullenmeyi anlatır; güneyde "halt", kuzeyde "eben" yaygındır.',
    },
    /* --- Gündelik durumlar --- */
    {
      id: 'de-gun-91', on: 'Wie spät ist es?', okunus: 'vii şpeet ist es', tur: 'soru kalıbı',
      arka: 'Saat kaç?',
      ornek: 'Entschuldigung, wie spät ist es?',
      ornekTr: 'Affedersiniz, saat kaç?',
      not: '"Wie viel Uhr ist es?" de aynı anlamdadır.',
    },
    {
      id: 'de-gun-92', on: 'Es ist Viertel nach drei', okunus: 'es ist firtıl naah dray', tur: 'kalıp',
      arka: 'Saat üçü çeyrek geçiyor',
      ornek: 'Es ist Viertel nach drei.',
      ornekTr: 'Saat üçü çeyrek geçiyor.',
      not: '"nach" geçiyor, "vor" var demektir: Viertel vor vier.',
    },
    {
      id: 'de-gun-93', on: 'Wie oft?', okunus: 'vii oft', tur: 'soru kalıbı',
      arka: 'Ne sıklıkta?',
      ornek: 'Wie oft gehst du ins Kino?',
      ornekTr: 'Ne sıklıkta sinemaya gidiyorsun?',
      not: 'Cevabı "einmal die Woche" gibi verilir.',
    },
    {
      id: 'de-gun-94', on: 'ab und zu', okunus: 'ap unt tsuu', tur: 'kalıp',
      arka: 'ara sıra',
      ornek: 'Ab und zu spiele ich Basketball.',
      ornekTr: 'Ara sıra basketbol oynuyorum.',
      not: 'Sıklık sıralaması: immer, oft, manchmal, ab und zu, nie.',
    },
    {
      id: 'de-gun-95', on: 'auf keinen Fall', okunus: 'auf kaynın fal', tur: 'kalıp',
      arka: 'kesinlikle olmaz',
      ornek: 'Auf keinen Fall gehe ich da allein hin.',
      ornekTr: 'Oraya kesinlikle yalnız gitmem.',
      not: '"auf jeden Fall" ile tam zıttır.',
    },
    {
      id: 'de-gun-96', on: 'so gut wie', okunus: 'zoo guut vii', tur: 'kalıp',
      arka: 'neredeyse',
      ornek: 'Ich bin so gut wie fertig.',
      ornekTr: 'Neredeyse bitirdim.',
      not: '"fast" ile eşanlamlıdır ama daha vurguludur.',
    },
    {
      id: 'de-gun-97', on: 'Wie bitte?', okunus: 'vii bitı', tur: 'soru kalıbı',
      arka: 'Efendim? Anlayamadım?',
      ornek: 'Wie bitte? Können Sie das wiederholen?',
      ornekTr: 'Efendim? Tekrar eder misiniz?',
      not: 'Kibarca "duyamadım" demenin standart yoludur.',
    },
    {
      id: 'de-gun-98', on: 'Wie sagt man ... auf Deutsch?', okunus: 'vii zaakt man ... auf doyç', tur: 'soru kalıbı',
      arka: 'Almanca ... nasıl denir?',
      ornek: 'Wie sagt man "kalem" auf Deutsch?',
      ornekTr: 'Almanca "kalem" nasıl denir?',
      not: 'Dil öğrenirken en işe yarayan sorulardan biridir.',
    },
    {
      id: 'de-gun-99', on: 'Ich lerne noch', okunus: 'ih lernı noh', tur: 'kalıp',
      arka: 'Hâlâ öğreniyorum',
      ornek: 'Mein Deutsch ist nicht perfekt, ich lerne noch.',
      ornekTr: 'Almancam mükemmel değil, hâlâ öğreniyorum.',
      not: 'Hata yapma korkusunu azaltan faydalı bir cümledir.',
    },
    {
      id: 'de-gun-100', on: 'Alles Gute!', okunus: 'alıs guutı', tur: 'kalıp',
      arka: 'Her şey gönlünce olsun!',
      ornek: 'Alles Gute für die Prüfung!',
      ornekTr: 'Sınav için her şey gönlünce olsun!',
      not: 'Doğum günü ve veda dâhil pek çok durumda kullanılır.',
    },
  ],
}

export default DESTE
