/**
 * DESTE — HAYVANLAR VE DOĞA (Almanca)
 *
 * Görsel olarak en kolay hatırlanan deste, ama Almancada her isim
 * artikeliyle gelir. Bu destede artikeller bilinçli olarak karışık
 * dağıtıldı: öğrenci "hayvanlar hep eril" gibi yanlış bir kural
 * çıkarmasın.
 */

export const DESTE = {
  id: 'hayvanlar-doga',
  dil: 'de',
  ad: 'Hayvanlar ve doğa',
  simge: '🌿',
  aciklama: 'Hayvanlar, hava ve doğa; her isim artikeliyle.',
  seviye: 'A1–A2',
  kartlar: [
    {
      id: 'de-hay-01', on: 'die Katze', okunus: 'di katsı', tur: 'isim (dişil)',
      arka: 'kedi',
      ornek: 'Meine Katze schläft den ganzen Tag auf dem Sofa.',
      ornekTr: 'Kedim bütün gün kanepede uyuyor.',
      not: 'DİŞİLDİR. Erkek kedi "der Kater"dır.',
    },
    {
      id: 'de-hay-02', on: 'der Hund', okunus: 'der hund', tur: 'isim (eril)',
      arka: 'köpek',
      ornek: 'Ich gehe jeden Morgen mit meinem Hund spazieren.',
      ornekTr: 'Her sabah köpeğimle yürüyüşe çıkıyorum.',
      not: 'Yürüyüşe çıkmak "spazieren gehen"dır.',
    },
    {
      id: 'de-hay-03', on: 'der Vogel', okunus: 'der foogıl', tur: 'isim (eril)',
      arka: 'kuş',
      ornek: 'Ein Vogel sitzt auf dem Fenster.',
      ornekTr: 'Pencerede bir kuş oturuyor.',
      not: 'Çoğulu "die Vögel" — sesli harf değişir (Umlaut).',
    },
    {
      id: 'de-hay-04', on: 'der Baum', okunus: 'der baum', tur: 'isim (eril)',
      arka: 'ağaç',
      ornek: 'Wir haben einen Baum im Garten gepflanzt.',
      ornekTr: 'Bahçeye bir ağaç diktik.',
      not: 'Çoğulu "die Bäume". Orman "der Wald".',
    },
    {
      id: 'de-hay-05', on: 'das Meer', okunus: 'das meer', tur: 'isim (nötr)',
      arka: 'deniz',
      ornek: 'Im Sommer fahren wir ans Meer.',
      ornekTr: 'Yazın denize gidiyoruz.',
      not: '"die See" de deniz demektir; "der See" ise GÖLDÜR. Artikel anlamı değiştirir.',
    },
    {
      id: 'de-hay-06', on: 'der Berg', okunus: 'der berg', tur: 'isim (eril)',
      arka: 'dağ',
      ornek: 'Im Winter fahren wir in die Berge zum Skifahren.',
      ornekTr: 'Kışın kayak için dağlara gidiyoruz.',
      not: 'Dağlara gitmek çoğul kullanılır: "in die Berge".',
    },
    {
      id: 'de-hay-07', on: 'Es regnet', okunus: 'es regnıt', tur: 'kalıp',
      arka: 'Yağmur yağıyor',
      ornek: 'Nimm einen Schirm mit, es regnet.',
      ornekTr: 'Şemsiye al, yağmur yağıyor.',
      not: 'Öznesi olmayan fiillerdendir; her zaman "es" ile kullanılır.',
    },
    {
      id: 'de-hay-08', on: 'die Sonne', okunus: 'di zonı', tur: 'isim (dişil)',
      arka: 'güneş',
      ornek: 'Heute scheint die Sonne.',
      ornekTr: 'Bugün güneş var.',
      not: 'DİŞİLDİR — ay ise ERİLDİR (der Mond). Türkçede böyle bir ayrım yok.',
    },
    {
      id: 'de-hay-09', on: 'die Blume', okunus: 'di bluumı', tur: 'isim (dişil)',
      arka: 'çiçek',
      ornek: 'Sie hat mir zum Geburtstag Blumen geschenkt.',
      ornekTr: 'Doğum günümde bana çiçek hediye etti.',
      not: 'Hediye etmek "schenken". Doğum günü "der Geburtstag".',
    },
    {
      id: 'de-hay-10', on: 'Schwein haben', okunus: 'şvayn haabın', tur: 'deyim',
      arka: 'şansı yaver gitmek',
      ornek: 'Da hast du aber Schwein gehabt!',
      ornekTr: 'Şansın varmış!',
      not: 'Kelime kelime "domuza sahip olmak" demektir. Almancanın en bilinen deyimlerinden.',
    },
    /* --- Evcil hayvanlar --- */
    {
      id: 'de-hay-11', on: 'das Haustier', okunus: 'das haustiir', tur: 'isim (nötr)',
      arka: 'evcil hayvan',
      ornek: 'Habt ihr ein Haustier zu Hause?',
      ornekTr: 'Evde evcil hayvanınız var mı?',
      not: '"das Tier" hayvan, "das Haus" ev demektir.',
    },
    {
      id: 'de-hay-12', on: 'das Kaninchen', okunus: 'das kaniinhın', tur: 'isim (nötr)',
      arka: 'tavşan',
      ornek: 'Mein Kaninchen frisst gern Karotten.',
      ornekTr: 'Tavşanım havuç yemeyi seviyor.',
      not: 'Hayvanlar için "fressen", insanlar için "essen" kullanılır.',
    },
    {
      id: 'de-hay-13', on: 'füttern', okunus: 'fütırn', tur: 'fiil',
      arka: 'yem vermek, beslemek',
      ornek: 'Ich füttere die Vögel jeden Morgen.',
      ornekTr: 'Kuşları her sabah besliyorum.',
      not: 'Sadece hayvanlar ve bebekler için kullanılır.',
    },
    {
      id: 'de-hay-14', on: 'streicheln', okunus: 'ştrayhıln', tur: 'fiil',
      arka: 'okşamak, sevmek',
      ornek: 'Die Katze lässt sich gern streicheln.',
      ornekTr: 'Kedi sevilmeyi seviyor.',
      not: '"sich lassen" burada izin verme anlamı taşır.',
    },
    {
      id: 'de-hay-15', on: 'der Tierarzt', okunus: 'der tiirartst', tur: 'isim (eril)',
      arka: 'veteriner',
      ornek: 'Wir gehen morgen zum Tierarzt.',
      ornekTr: 'Yarın veterinere gidiyoruz.',
      not: '"der Arzt" doktor demektir.',
    },
    {
      id: 'de-hay-16', on: 'das Tierheim', okunus: 'das tiirhaym', tur: 'isim (nötr)',
      arka: 'hayvan barınağı',
      ornek: 'Wir haben den Hund aus dem Tierheim geholt.',
      ornekTr: 'Köpeği barınaktan aldık.',
      not: '"das Heim" yuva, sığınak demektir.',
    },
    {
      id: 'de-hay-17', on: 'bellen', okunus: 'belın', tur: 'fiil',
      arka: 'havlamak',
      ornek: 'Der Hund bellt die ganze Nacht.',
      ornekTr: 'Köpek bütün gece havlıyor.',
      not: 'Kedi "miauen", kuş "zwitschern" der.',
    },
    {
      id: 'de-hay-18', on: 'der Schwanz', okunus: 'der şvants', tur: 'isim (eril)',
      arka: 'kuyruk',
      ornek: 'Der Hund wedelt mit dem Schwanz.',
      ornekTr: 'Köpek kuyruğunu sallıyor.',
      not: '"wedeln mit" = sallamak; Dativ ister.',
    },
    {
      id: 'de-hay-19', on: 'treu', okunus: 'troy', tur: 'sıfat',
      arka: 'sadık',
      ornek: 'Hunde sind sehr treue Tiere.',
      ornekTr: 'Köpekler çok sadık hayvanlardır.',
      not: '"die Treue" sadakat demektir.',
    },
    {
      id: 'de-hay-20', on: 'Gassi gehen', okunus: 'gasi geeın', tur: 'kalıp',
      arka: 'köpeği gezdirmek',
      ornek: 'Ich gehe mit dem Hund Gassi.',
      ornekTr: 'Köpeği gezdirmeye çıkıyorum.',
      not: 'Almancaya özgü bir deyimdir; kelime kelime çevrilemez.',
    },
    /* --- Çiftlik ve yaban hayvanları --- */
    {
      id: 'de-hay-21', on: 'das Pferd', okunus: 'das pfeert', tur: 'isim (nötr)',
      arka: 'at',
      ornek: 'Sie reitet gern auf dem Pferd.',
      ornekTr: 'Ata binmeyi seviyor.',
      not: '"reiten" ata binmek demektir.',
    },
    {
      id: 'de-hay-22', on: 'die Kuh', okunus: 'di kuu', tur: 'isim (dişil)',
      arka: 'inek',
      ornek: 'Die Kühe stehen auf der Wiese.',
      ornekTr: 'İnekler çayırda duruyor.',
      not: 'Çoğulu "die Kühe"dir; Umlaut alır.',
    },
    {
      id: 'de-hay-23', on: 'das Schaf', okunus: 'das şaaf', tur: 'isim (nötr)',
      arka: 'koyun',
      ornek: 'Auf dem Hügel sind viele Schafe.',
      ornekTr: 'Tepede çok koyun var.',
      not: 'Sürü "die Herde"dir.',
    },
    {
      id: 'de-hay-24', on: 'das Huhn', okunus: 'das huun', tur: 'isim (nötr)',
      arka: 'tavuk',
      ornek: 'Die Hühner legen jeden Tag Eier.',
      ornekTr: 'Tavuklar her gün yumurta yumurtluyor.',
      not: '"Eier legen" = yumurtlamak. Çoğulu "die Hühner"dir.',
      kok: 'Hühner',
    },
    {
      id: 'de-hay-25', on: 'der Bär', okunus: 'der beer', tur: 'isim (eril)',
      arka: 'ayı',
      ornek: 'Bären halten Winterschlaf.',
      ornekTr: 'Ayılar kış uykusuna yatar.',
      not: '"der Winterschlaf" kış uykusu demektir.',
    },
    {
      id: 'de-hay-26', on: 'der Fuchs', okunus: 'der fuks', tur: 'isim (eril)',
      arka: 'tilki',
      ornek: 'Ein Fuchs lief über die Straße.',
      ornekTr: 'Bir tilki yolun karşısına koştu.',
      not: 'Kurnaz kişiye de "ein schlauer Fuchs" denir.',
    },
    {
      id: 'de-hay-27', on: 'das Eichhörnchen', okunus: 'das ayhhörnhın', tur: 'isim (nötr)',
      arka: 'sincap',
      ornek: 'Im Park leben viele Eichhörnchen.',
      ornekTr: 'Parkta çok sincap yaşıyor.',
      not: '"die Eiche" meşe ağacı demektir.',
    },
    {
      id: 'de-hay-28', on: 'der Schmetterling', okunus: 'der şmetırling', tur: 'isim (eril)',
      arka: 'kelebek',
      ornek: 'Im Frühling sieht man viele Schmetterlinge.',
      ornekTr: 'İlkbaharda çok kelebek görülür.',
      not: '"man sieht" = görülür, insan görür.',
    },
    {
      id: 'de-hay-29', on: 'die Biene', okunus: 'di biinı', tur: 'isim (dişil)',
      arka: 'arı',
      ornek: 'Bienen sind wichtig für die Natur.',
      ornekTr: 'Arılar doğa için önemlidir.',
      not: 'Bal "der Honig"tir.',
    },
    {
      id: 'de-hay-30', on: 'wild lebende Tiere', okunus: 'vilt leebındı tiirı', tur: 'kalıp',
      arka: 'yabani hayvanlar',
      ornek: 'Wild lebende Tiere brauchen Schutz.',
      ornekTr: 'Yabani hayvanların korunmaya ihtiyacı var.',
      not: '"der Schutz" koruma demektir.',
    },
    /* --- Doğal alanlar --- */
    {
      id: 'de-hay-31', on: 'der Wald', okunus: 'der valt', tur: 'isim (eril)',
      arka: 'orman',
      ornek: 'Wir spazieren gern im Wald.',
      ornekTr: 'Ormanda yürümeyi seviyoruz.',
      not: 'Almanya\'da orman yürüyüşü çok yaygın bir alışkanlıktır.',
    },
    {
      id: 'de-hay-32', on: 'die Wiese', okunus: 'di viizı', tur: 'isim (dişil)',
      arka: 'çayır',
      ornek: 'Die Wiese ist voller Blumen.',
      ornekTr: 'Çayır çiçeklerle dolu.',
      not: '"voller" = dolu; Genitiv ya da yalın isim alır.',
    },
    {
      id: 'de-hay-33', on: 'der Fluss', okunus: 'der flus', tur: 'isim (eril)',
      arka: 'nehir',
      ornek: 'Der Fluss fließt durch die Stadt.',
      ornekTr: 'Nehir şehrin içinden geçiyor.',
      not: '"fließen" akmak demektir; aynı kökten gelir.',
    },
    {
      id: 'de-hay-34', on: 'der See', okunus: 'der zee', tur: 'isim (eril)',
      arka: 'göl',
      ornek: 'Wir schwimmen im See.',
      ornekTr: 'Gölde yüzüyoruz.',
      not: 'Dikkat: "der See" göl, "die See" denizdir. Artikel anlamı değiştirir.',
    },
    {
      id: 'de-hay-35', on: 'das Tal', okunus: 'das taal', tur: 'isim (nötr)',
      arka: 'vadi',
      ornek: 'Das Dorf liegt in einem grünen Tal.',
      ornekTr: 'Köy yeşil bir vadide yer alıyor.',
      not: '"liegen" bir yerde bulunmak demektir.',
    },
    {
      id: 'de-hay-36', on: 'die Insel', okunus: 'di inzıl', tur: 'isim (dişil)',
      arka: 'ada',
      ornek: 'Die Insel ist nur mit dem Schiff erreichbar.',
      ornekTr: 'Adaya sadece gemiyle ulaşılabiliyor.',
      not: '"erreichbar" ulaşılabilir demektir.',
    },
    {
      id: 'de-hay-37', on: 'der Strand', okunus: 'der ştrant', tur: 'isim (eril)',
      arka: 'plaj, kumsal',
      ornek: 'Am Strand war es sehr windig.',
      ornekTr: 'Plajda hava çok rüzgârlıydı.',
      not: 'Edatı "an"dır: am Strand.',
    },
    {
      id: 'de-hay-38', on: 'die Höhle', okunus: 'di hööulı', tur: 'isim (dişil)',
      arka: 'mağara',
      ornek: 'Die Höhle ist für Besucher geöffnet.',
      ornekTr: 'Mağara ziyaretçilere açık.',
      not: '"der Besucher" ziyaretçi demektir.',
    },
    {
      id: 'de-hay-39', on: 'der Gipfel', okunus: 'der gipfıl', tur: 'isim (eril)',
      arka: 'zirve',
      ornek: 'Wir haben den Gipfel am Morgen erreicht.',
      ornekTr: 'Zirveye sabah ulaştık.',
      not: 'Mecazi olarak "doruk noktası" anlamına da gelir.',
    },
    {
      id: 'de-hay-40', on: 'der Weg', okunus: 'der veek', tur: 'isim (eril)',
      arka: 'yol, patika',
      ornek: 'Der Weg führt zum Wasserfall.',
      ornekTr: 'Yol şelaleye çıkıyor.',
      not: '"führen zu" = bir yere götürmek.',
    },
    /* --- Bitkiler --- */
    {
      id: 'de-hay-41', on: 'die Pflanze', okunus: 'di pflantsı', tur: 'isim (dişil)',
      arka: 'bitki',
      ornek: 'Die Pflanze braucht mehr Licht.',
      ornekTr: 'Bitkinin daha çok ışığa ihtiyacı var.',
      not: 'Fiili "pflanzen" = dikmek.',
    },
    {
      id: 'de-hay-42', on: 'das Blatt', okunus: 'das blat', tur: 'isim (nötr)',
      arka: 'yaprak',
      ornek: 'Im Herbst fallen die Blätter.',
      ornekTr: 'Sonbaharda yapraklar dökülür.',
      not: 'Çoğulu "die Blätter"dir. Kâğıt yaprağı için de kullanılır.',
      kok: 'Blätter',
    },
    {
      id: 'de-hay-43', on: 'die Wurzel', okunus: 'di vurtsıl', tur: 'isim (dişil)',
      arka: 'kök',
      ornek: 'Die Wurzeln gehen tief in die Erde.',
      ornekTr: 'Kökler toprağın derinlerine iniyor.',
      not: 'Matematikte karekök için de aynı kelime kullanılır.',
    },
    {
      id: 'de-hay-44', on: 'der Samen', okunus: 'der zaamın', tur: 'isim (eril)',
      arka: 'tohum',
      ornek: 'Wir haben Samen in die Erde gesteckt.',
      ornekTr: 'Toprağa tohum ektik.',
      not: '"stecken" sokmak, koymak demektir.',
    },
    {
      id: 'de-hay-45', on: 'die Erde', okunus: 'di eerdı', tur: 'isim (dişil)',
      arka: 'toprak; dünya',
      ornek: 'Die Erde hier ist sehr fruchtbar.',
      ornekTr: 'Buradaki toprak çok verimli.',
      not: 'Büyük harfle "die Erde" gezegenimiz demektir.',
    },
    {
      id: 'de-hay-46', on: 'gießen', okunus: 'giisın', tur: 'fiil (kuvvetli)',
      arka: 'sulamak',
      ornek: 'Vergiss nicht, die Blumen zu gießen.',
      ornekTr: 'Çiçekleri sulamayı unutma.',
      not: 'Çekimi: gießt · hat gegossen.',
    },
    {
      id: 'de-hay-47', on: 'wachsen', okunus: 'vaksın', tur: 'fiil (kuvvetli)',
      arka: 'büyümek',
      ornek: 'Der Baum wächst sehr langsam.',
      ornekTr: 'Ağaç çok yavaş büyüyor.',
      not: 'Çekimi: wächst · ist gewachsen.',
      kok: 'wächs',
    },
    {
      id: 'de-hay-48', on: 'blühen', okunus: 'blüüın', tur: 'fiil',
      arka: 'çiçek açmak',
      ornek: 'Die Kirschbäume blühen im April.',
      ornekTr: 'Kiraz ağaçları nisanda çiçek açar.',
      not: '"die Blüte" çiçek (ağaçta) demektir.',
    },
    {
      id: 'de-hay-49', on: 'die Ernte', okunus: 'di erntı', tur: 'isim (dişil)',
      arka: 'hasat',
      ornek: 'Die Ernte war dieses Jahr gut.',
      ornekTr: 'Bu yıl hasat iyiydi.',
      not: 'Fiili "ernten" = hasat etmek.',
    },
    {
      id: 'de-hay-50', on: 'der Garten', okunus: 'der gartın', tur: 'isim (eril)',
      arka: 'bahçe',
      ornek: 'Im Garten wachsen Tomaten.',
      ornekTr: 'Bahçede domates yetişiyor.',
      not: 'Almanya\'da şehirdeki bahçelere "der Schrebergarten" denir.',
    },
    /* --- Mevsimler ve hava --- */
    {
      id: 'de-hay-51', on: 'der Frühling', okunus: 'der früüling', tur: 'isim (eril)',
      arka: 'ilkbahar',
      ornek: 'Im Frühling wird alles grün.',
      ornekTr: 'İlkbaharda her yer yeşerir.',
      not: 'Mevsimlerde edat "im"dir: im Sommer, im Winter.',
    },
    {
      id: 'de-hay-52', on: 'der Herbst', okunus: 'der herpst', tur: 'isim (eril)',
      arka: 'sonbahar',
      ornek: 'Der Herbst ist meine Lieblingsjahreszeit.',
      ornekTr: 'Sonbahar en sevdiğim mevsim.',
      not: '"die Jahreszeit" mevsim demektir.',
    },
    {
      id: 'de-hay-53', on: 'schneien', okunus: 'şnayın', tur: 'fiil',
      arka: 'kar yağmak',
      ornek: 'Es schneit seit gestern Abend.',
      ornekTr: 'Dün akşamdan beri kar yağıyor.',
      not: 'Hava fiilleri daima "es" ile kullanılır.',
    },
    {
      id: 'de-hay-54', on: 'der Nebel', okunus: 'der neebıl', tur: 'isim (eril)',
      arka: 'sis',
      ornek: 'Am Morgen war dichter Nebel.',
      ornekTr: 'Sabah yoğun sis vardı.',
      not: '"dicht" yoğun demektir. Sıfatı "neblig".',
    },
    {
      id: 'de-hay-55', on: 'das Gewitter', okunus: 'das gıvitır', tur: 'isim (nötr)',
      arka: 'gök gürültülü fırtına',
      ornek: 'Ein Gewitter zieht auf.',
      ornekTr: 'Fırtına yaklaşıyor.',
      not: '"aufziehen" hava için "yaklaşmak" demektir.',
    },
    {
      id: 'de-hay-56', on: 'der Blitz', okunus: 'der blits', tur: 'isim (eril)',
      arka: 'şimşek',
      ornek: 'Der Blitz war sehr hell.',
      ornekTr: 'Şimşek çok parlaktı.',
      not: 'Gök gürültüsü "der Donner"dır.',
    },
    {
      id: 'de-hay-57', on: 'der Wind', okunus: 'der vint', tur: 'isim (eril)',
      arka: 'rüzgâr',
      ornek: 'Der Wind ist heute stark.',
      ornekTr: 'Rüzgâr bugün kuvvetli.',
      not: 'Sıfatı "windig" = rüzgârlı.',
    },
    {
      id: 'de-hay-58', on: 'die Überschwemmung', okunus: 'di übırşvemung', tur: 'isim (dişil)',
      arka: 'sel',
      ornek: 'Nach dem Regen gab es eine Überschwemmung.',
      ornekTr: 'Yağmurdan sonra sel oldu.',
      not: '"schwimmen" yüzmek fiiliyle akrabadır.',
    },
    {
      id: 'de-hay-59', on: 'das Erdbeben', okunus: 'das eertbeebın', tur: 'isim (nötr)',
      arka: 'deprem',
      ornek: 'Die Türkei ist ein Erdbebengebiet.',
      ornekTr: 'Türkiye bir deprem bölgesidir.',
      not: '"beben" titremek demektir.',
    },
    {
      id: 'de-hay-60', on: 'die Dürre', okunus: 'di dürı', tur: 'isim (dişil)',
      arka: 'kuraklık',
      ornek: 'Die Dürre hat die Ernte zerstört.',
      ornekTr: 'Kuraklık hasadı mahvetti.',
      not: '"zerstören" yok etmek demektir.',
    },
    /* --- Çevre --- */
    {
      id: 'de-hay-61', on: 'die Umwelt', okunus: 'di umvelt', tur: 'isim (dişil)',
      arka: 'çevre',
      ornek: 'Wir müssen die Umwelt schützen.',
      ornekTr: 'Çevreyi korumalıyız.',
      not: '"um" etraf, "die Welt" dünya demektir.',
    },
    {
      id: 'de-hay-62', on: 'der Umweltschutz', okunus: 'der umveltşuts', tur: 'isim (eril)',
      arka: 'çevre koruma',
      ornek: 'Umweltschutz beginnt zu Hause.',
      ornekTr: 'Çevre koruma evde başlar.',
      not: 'Almanya\'da politika ve okul metinlerinin ana konusudur.',
    },
    {
      id: 'de-hay-63', on: 'der Müll', okunus: 'der mül', tur: 'isim (eril)',
      arka: 'çöp',
      ornek: 'Wirf den Müll bitte in den Eimer.',
      ornekTr: 'Çöpü lütfen kovaya at.',
      not: '"werfen" atmak, "der Eimer" kova demektir.',
    },
    {
      id: 'de-hay-64', on: 'der Müll trennen', okunus: 'der mül trenın', tur: 'kalıp',
      arka: 'çöp ayrıştırmak',
      ornek: 'In Deutschland muss man den Müll trennen.',
      ornekTr: 'Almanya\'da çöp ayrıştırmak zorunludur.',
      not: 'Kâğıt, cam, plastik ve organik atık ayrı kutulara atılır.',
    },
    {
      id: 'de-hay-65', on: 'das Pfand', okunus: 'das pfant', tur: 'isim (nötr)',
      arka: 'depozito (şişe)',
      ornek: 'Auf die Flasche gibt es fünfundzwanzig Cent Pfand.',
      ornekTr: 'Şişede yirmi beş sent depozito var.',
      not: 'Almanya\'nın en bilinen geri dönüşüm uygulamasıdır.',
    },
    {
      id: 'de-hay-66', on: 'die Verschmutzung', okunus: 'di ferşmutsung', tur: 'isim (dişil)',
      arka: 'kirlilik',
      ornek: 'Die Luftverschmutzung ist ein großes Problem.',
      ornekTr: 'Hava kirliliği büyük bir sorun.',
      not: '"schmutzig" kirli demektir.',
    },
    {
      id: 'de-hay-67', on: 'der Klimawandel', okunus: 'der kliimavandıl', tur: 'isim (eril)',
      arka: 'iklim değişikliği',
      ornek: 'Der Klimawandel betrifft uns alle.',
      ornekTr: 'İklim değişikliği hepimizi ilgilendiriyor.',
      not: '"betreffen" ilgilendirmek, etkilemek demektir.',
    },
    {
      id: 'de-hay-68', on: 'erneuerbare Energie', okunus: 'ernoyırbaarı enırgii', tur: 'kalıp',
      arka: 'yenilenebilir enerji',
      ornek: 'Windkraft ist erneuerbare Energie.',
      ornekTr: 'Rüzgâr enerjisi yenilenebilir enerjidir.',
      not: '"erneuern" yenilemek demektir.',
    },
    {
      id: 'de-hay-69', on: 'aussterben', okunus: 'ausştarbın', tur: 'fiil (ayrılabilir)',
      arka: 'nesli tükenmek',
      ornek: 'Viele Arten sterben aus.',
      ornekTr: 'Birçok türün nesli tükeniyor.',
      not: 'Ayrılabilir fiildir: "sterben ... aus".',
      kok: 'sterb',
    },
    {
      id: 'de-hay-70', on: 'die Art', okunus: 'di art', tur: 'isim (dişil)',
      arka: 'tür',
      ornek: 'Diese Art lebt nur in der Türkei.',
      ornekTr: 'Bu tür sadece Türkiye\'de yaşar.',
      not: 'Aynı kelime "biçim, tarz" anlamına da gelir.',
    },
    /* --- Doğada zaman geçirmek --- */
    {
      id: 'de-hay-71', on: 'spazieren gehen', okunus: 'şpatsiirın geeın', tur: 'kalıp',
      arka: 'yürüyüşe çıkmak',
      ornek: 'Nach dem Essen gehen wir spazieren.',
      ornekTr: 'Yemekten sonra yürüyüşe çıkıyoruz.',
      not: 'Almanya\'da pazar günü yürüyüşü bir gelenektir.',
    },
    {
      id: 'de-hay-72', on: 'das Picknick', okunus: 'das piknik', tur: 'isim (nötr)',
      arka: 'piknik',
      ornek: 'Wir machen ein Picknick am See.',
      ornekTr: 'Gölün kenarında piknik yapıyoruz.',
      not: 'Fiili "machen"dır.',
    },
    {
      id: 'de-hay-73', on: 'zelten', okunus: 'tseltın', tur: 'fiil',
      arka: 'çadırda kalmak',
      ornek: 'Im Sommer zelten wir in den Bergen.',
      ornekTr: 'Yazın dağlarda çadırda kalıyoruz.',
      not: '"das Zelt" çadır demektir.',
    },
    {
      id: 'de-hay-74', on: 'das Lagerfeuer', okunus: 'das laagırfoyır', tur: 'isim (nötr)',
      arka: 'kamp ateşi',
      ornek: 'Am Lagerfeuer haben wir gesungen.',
      ornekTr: 'Kamp ateşinin başında şarkı söyledik.',
      not: '"das Feuer" ateş demektir.',
    },
    {
      id: 'de-hay-75', on: 'frische Luft', okunus: 'frişı luft', tur: 'kalıp',
      arka: 'temiz hava',
      ornek: 'Geh raus und hol frische Luft.',
      ornekTr: 'Dışarı çık ve temiz hava al.',
      not: '"rausgehen" dışarı çıkmak demektir.',
    },
    {
      id: 'de-hay-76', on: 'die Ruhe', okunus: 'di ruuı', tur: 'isim (dişil)',
      arka: 'huzur, sessizlik',
      ornek: 'Im Wald findet man Ruhe.',
      ornekTr: 'Ormanda huzur bulunur.',
      not: 'Sıfatı "ruhig" = sakin.',
    },
    {
      id: 'de-hay-77', on: 'atemberaubend', okunus: 'aatımbıraubınt', tur: 'sıfat',
      arka: 'nefes kesici',
      ornek: 'Die Aussicht war atemberaubend.',
      ornekTr: 'Manzara nefes kesiciydi.',
      not: '"der Atem" nefes, "rauben" çalmak demektir.',
    },
    {
      id: 'de-hay-78', on: 'mitten im Nirgendwo', okunus: 'mitın im nirgıntvoo', tur: 'kalıp',
      arka: 'ıssızın ortasında',
      ornek: 'Die Hütte steht mitten im Nirgendwo.',
      ornekTr: 'Kulübe ıssızın ortasında.',
      not: '"nirgendwo" hiçbir yer demektir.',
    },
    {
      id: 'de-hay-79', on: 'keine Spuren hinterlassen', okunus: 'kaynı şpuurın hintırlasın', tur: 'kalıp',
      arka: 'iz bırakmamak',
      ornek: 'Beim Camping soll man keine Spuren hinterlassen.',
      ornekTr: 'Kamp yaparken iz bırakmamak gerekir.',
      not: '"die Spur" iz demektir.',
    },
    {
      id: 'de-hay-80', on: 'die Natur genießen', okunus: 'di natuur gıniisın', tur: 'kalıp',
      arka: 'doğanın tadını çıkarmak',
      ornek: 'Wir genießen die Natur jedes Wochenende.',
      ornekTr: 'Her hafta sonu doğanın tadını çıkarıyoruz.',
      not: '"genießen" tadını çıkarmak demektir.',
    },
    /* --- Hayvanlı deyimler --- */
    {
      id: 'de-hay-81', on: 'einen Bärenhunger haben', okunus: 'aynın beerınhungır haabın', tur: 'deyim',
      arka: 'kurt gibi acıkmış olmak',
      ornek: 'Nach dem Training habe ich einen Bärenhunger.',
      ornekTr: 'Antrenmandan sonra kurt gibi acıkıyorum.',
      not: 'Kelimesi kelimesine "ayı açlığı"dır.',
    },
    {
      id: 'de-hay-82', on: 'wie ein Fisch im Wasser', okunus: 'vii ayn fiş im vasır', tur: 'deyim',
      arka: 'suda balık gibi, çok rahat',
      ornek: 'Auf der Bühne ist sie wie ein Fisch im Wasser.',
      ornekTr: 'Sahnede sudaki balık gibi rahat.',
      not: 'Türkçedeki karşılığıyla birebir örtüşür.',
    },
    {
      id: 'de-hay-83', on: 'den Vogel abschießen', okunus: 'deen foogıl apşiisın', tur: 'deyim',
      arka: 'hepsini geçmek, zirveye çıkmak',
      ornek: 'Mit dieser Idee hat er den Vogel abgeschossen.',
      ornekTr: 'Bu fikirle hepsini geçti.',
      not: 'Bazen alaycı bir anlamda da kullanılır.',
      kok: 'schoss',
    },
    {
      id: 'de-hay-84', on: 'Da liegt der Hund begraben', okunus: 'da liikt der hunt bıgraabın', tur: 'deyim',
      arka: 'İşin püf noktası burada',
      ornek: 'Kein Geld für Bücher: da liegt der Hund begraben.',
      ornekTr: 'Kitaplara para yok: işin püf noktası burada.',
      not: 'Sorunun asıl kaynağını gösterir.',
    },
    {
      id: 'de-hay-85', on: 'fleißig wie eine Biene', okunus: 'flaysih vii aynı biinı', tur: 'deyim',
      arka: 'arı gibi çalışkan',
      ornek: 'Sie ist fleißig wie eine Biene.',
      ornekTr: 'Arı gibi çalışkan.',
      not: 'Benzetme kalıbı "wie" ile kurulur.',
    },
    {
      id: 'de-hay-86', on: 'zwei Fliegen mit einer Klappe schlagen', okunus: 'tsvay fliigın mit aynır klapı şlaagın', tur: 'deyim',
      arka: 'bir taşla iki kuş vurmak',
      ornek: 'So schlage ich zwei Fliegen mit einer Klappe.',
      ornekTr: 'Böylece bir taşla iki kuş vuruyorum.',
      not: 'Almancada kuş değil sinek vardır; imge farklıdır.',
    },
    {
      id: 'de-hay-87', on: 'auf dem Holzweg sein', okunus: 'auf deem holtsveek zayn', tur: 'deyim',
      arka: 'yanlış yolda olmak',
      ornek: 'Wenn du das denkst, bist du auf dem Holzweg.',
      ornekTr: 'Böyle düşünüyorsan yanlış yoldasın.',
      not: 'Ormancıların çıkmaz odun yolundan gelir.',
    },
    {
      id: 'de-hay-88', on: 'ins Wasser fallen', okunus: 'ins vasır falın', tur: 'deyim',
      arka: 'suya düşmek (plan)',
      ornek: 'Unser Ausflug ist ins Wasser gefallen.',
      ornekTr: 'Gezimiz suya düştü.',
      not: 'Türkçedeki "suya düşmek" ile aynıdır.',
    },
    {
      id: 'de-hay-89', on: 'Es gießt wie aus Eimern', okunus: 'es giist vii aus aymırn', tur: 'deyim',
      arka: 'Bardaktan boşanırcasına yağıyor',
      ornek: 'Nimm den Schirm, es gießt wie aus Eimern.',
      ornekTr: 'Şemsiyeyi al, bardaktan boşanırcasına yağıyor.',
      not: 'Kelimesi kelimesine "kovalardan dökülüyor" demektir.',
    },
    {
      id: 'de-hay-90', on: 'Es gibt kein schlechtes Wetter', okunus: 'es gipt kayn şlehtıs vetır', tur: 'atasözü',
      arka: 'Kötü hava yoktur, yanlış kıyafet vardır',
      ornek: 'Zieh dich warm an: Es gibt kein schlechtes Wetter, nur schlechte Kleidung.',
      ornekTr: 'Kalın giyin: kötü hava yoktur, yanlış kıyafet vardır.',
      not: 'Almanların doğa yürüyüşü felsefesini özetler.',
    },
    /* --- Doğa metinlerinin dili --- */
    {
      id: 'de-hay-91', on: 'die Mehrheit', okunus: 'di meerhayt', tur: 'isim (dişil)',
      arka: 'çoğunluk',
      ornek: 'Die Mehrheit der Tiere lebt im Wald.',
      ornekTr: 'Hayvanların çoğunluğu ormanda yaşıyor.',
      not: 'Genitiv ister: "die Mehrheit der Tiere".',
    },
    {
      id: 'de-hay-92', on: 'immer weniger', okunus: 'imır veenigır', tur: 'kalıp',
      arka: 'gitgide daha az',
      ornek: 'Es gibt immer weniger Bienen.',
      ornekTr: 'Gitgide daha az arı var.',
      not: 'Tersi "immer mehr" = gitgide daha çok.',
    },
    {
      id: 'de-hay-93', on: 'früher', okunus: 'früüır', tur: 'zarf',
      arka: 'eskiden',
      ornek: 'Früher gab es hier mehr Wälder.',
      ornekTr: 'Eskiden burada daha çok orman vardı.',
      not: '"es gab" = vardı; "es gibt"in geçmiş hâlidir.',
    },
    {
      id: 'de-hay-94', on: 'wahrscheinlich', okunus: 'vaarşaynlih', tur: 'zarf',
      arka: 'muhtemelen',
      ornek: 'Die Temperaturen steigen wahrscheinlich weiter.',
      ornekTr: 'Sıcaklıklar muhtemelen artmaya devam edecek.',
      not: 'Bilimsel metinlerde tahmin bildirir.',
    },
    {
      id: 'de-hay-95', on: 'wegen', okunus: 'veegın', tur: 'edat',
      arka: '... yüzünden',
      ornek: 'Wegen der Verschmutzung sterben viele Fische.',
      ornekTr: 'Kirlilik yüzünden çok balık ölüyor.',
      not: 'Genitiv ister: wegen des Regens.',
    },
    {
      id: 'de-hay-96', on: 'deswegen', okunus: 'desveegın', tur: 'zarf',
      arka: 'bu yüzden',
      ornek: 'Das Eis schmilzt, deswegen steigt der Meeresspiegel.',
      ornekTr: 'Buzlar eriyor, bu yüzden deniz seviyesi yükseliyor.',
      not: 'Sonuç bildirir ve sonrasında fiil öne gelir.',
    },
    {
      id: 'de-hay-97', on: 'in Gefahr sein', okunus: 'in gıfaar zayn', tur: 'kalıp',
      arka: 'tehlikede olmak',
      ornek: 'Diese Art ist in Gefahr.',
      ornekTr: 'Bu tür tehlikede.',
      not: '"die Gefahr" tehlike demektir.',
    },
    {
      id: 'de-hay-98', on: 'etwas tun gegen', okunus: 'etvas tuun geegın', tur: 'kalıp',
      arka: 'bir şeye karşı harekete geçmek',
      ornek: 'Wir müssen etwas gegen den Müll tun.',
      ornekTr: 'Çöp sorununa karşı bir şey yapmalıyız.',
      not: '"gegen" Akkusativ ister.',
    },
    {
      id: 'de-hay-99', on: 'einen Unterschied machen', okunus: 'aynın untırşiit mahın', tur: 'kalıp',
      arka: 'fark yaratmak',
      ornek: 'Kleine Schritte machen einen Unterschied.',
      ornekTr: 'Küçük adımlar fark yaratır.',
      not: 'Kompozisyon sonucu için güçlü bir kapanıştır.',
    },
    {
      id: 'de-hay-100', on: 'die Natur schützen', okunus: 'di natuur şütsın', tur: 'kalıp',
      arka: 'doğayı korumak',
      ornek: 'Jeder kann die Natur schützen.',
      ornekTr: 'Herkes doğayı koruyabilir.',
      not: '"schützen vor" = bir şeyden korumak.',
    },
  ],
}

export default DESTE
