/**
 * DESTE — MÜZİK, DİZİ VE FİLM (Almanca)
 *
 * Almanca dizi ve müzik kelimelerinin çoğu İngilizceden gelir ama
 * ARTİKEL alır ve Almanca çekilir. Öğrencinin şaşırdığı yer burasıdır:
 * kelimeyi tanır ama cümleye yerleştiremez.
 */

export const DESTE = {
  id: 'muzik-dizi',
  dil: 'de',
  ad: 'Müzik, dizi ve film',
  simge: '🎬',
  aciklama: 'Dizi, film ve müzik konuşurken gereken kelimeler.',
  seviye: 'A1–A2',
  kartlar: [
    {
      id: 'de-muz-01', on: 'das Lied', okunus: 'das liit', tur: 'isim (nötr)',
      arka: 'şarkı',
      ornek: 'Dieses Lied höre ich jeden Tag.',
      ornekTr: 'Bu şarkıyı her gün dinliyorum.',
      not: 'Çoğulu "die Lieder". "der Song" da kullanılır ama "Lied" daha Almancadır.',
    },
    {
      id: 'de-muz-02', on: 'die Serie', okunus: 'di zerye', tur: 'isim (dişil)',
      arka: 'dizi',
      ornek: 'Ich habe die ganze Serie an einem Wochenende gesehen.',
      ornekTr: 'Bütün diziyi bir hafta sonunda izledim.',
      not: 'Bölüm "die Folge", sezon "die Staffel".',
    },
    {
      id: 'de-muz-03', on: 'der Film', okunus: 'der film', tur: 'isim (eril)',
      arka: 'film',
      ornek: 'Der Film dauert zwei Stunden.',
      ornekTr: 'Film iki saat sürüyor.',
      not: 'İzlemek "sehen" ya da "anschauen". Süre "dauern" fiiliyle söylenir.',
    },
    {
      id: 'de-muz-04', on: 'der Untertitel', okunus: 'der untırtitıl', tur: 'isim (eril)',
      arka: 'altyazı',
      ornek: 'Ich schaue Filme mit deutschen Untertiteln.',
      ornekTr: 'Filmleri Almanca altyazıyla izliyorum.',
      not: '"unter" (alt) + "Titel" (başlık). Genelde çoğul kullanılır.',
    },
    {
      id: 'de-muz-05', on: 'die Handlung', okunus: 'di handlung', tur: 'isim (dişil)',
      arka: 'konu, olay örgüsü',
      ornek: 'Die Handlung wird in der zweiten Staffel kompliziert.',
      ornekTr: 'İkinci sezonda konu karmaşıklaşıyor.',
      not: '"handeln" (davranmak, konu almak) fiilinden gelir.',
    },
    {
      id: 'de-muz-06', on: 'die Stimme', okunus: 'di ştimı', tur: 'isim (dişil)',
      arka: 'ses (insan sesi)',
      ornek: 'Sie hat eine unglaubliche Stimme.',
      ornekTr: 'İnanılmaz bir sesi var.',
      not: 'Cihaz sesi "der Ton"dur. "die Stimme" yalnız insan ve hayvan sesidir.',
    },
    {
      id: 'de-muz-07', on: 'die Figur', okunus: 'di figuur', tur: 'isim (dişil)',
      arka: 'karakter (film/dizi)',
      ornek: 'Meine Lieblingsfigur stirbt am Ende.',
      ornekTr: 'En sevdiğim karakter sonda ölüyor.',
      not: '"Lieblings-" öneki "en sevdiğim" demektir ve her isme eklenebilir.',
    },
    {
      id: 'de-muz-08', on: 'anschauen', kok: 'schau', okunus: 'anşauın', tur: 'fiil (ayrılabilir)',
      arka: 'izlemek, seyretmek',
      ornek: 'Wir schauen heute Abend einen Film an.',
      ornekTr: 'Bu akşam bir film izliyoruz.',
      not: 'AYRILABİLİR fiildir: ön ek "an" cümlenin SONUNA gider.',
    },
    {
      id: 'de-muz-09', on: 'der Ohrwurm', okunus: 'der oorvurm', tur: 'isim (eril)',
      arka: 'akıldan çıkmayan şarkı',
      ornek: 'Dieses Lied ist ein richtiger Ohrwurm.',
      ornekTr: 'Bu şarkı tam bir akıl kurdu.',
      not: 'Kelime kelime "kulak kurdu" demektir. Almancanın en sevilen kelimelerinden.',
    },
    {
      id: 'de-muz-10', on: 'krass', okunus: 'kras', tur: 'sıfat (argo)',
      arka: 'inanılmaz, acayip',
      ornek: 'Das Konzert war echt krass!',
      ornekTr: 'Konser gerçekten acayipti!',
      not: 'Gençlerin en çok kullandığı kelime. Hem olumlu hem olumsuz olabilir.',
    },
    /* --- Müzik dinlemek --- */
    {
      id: 'de-muz-11', on: 'die Musik', okunus: 'di muziik', tur: 'isim (dişil)',
      arka: 'müzik',
      ornek: 'Ich höre Musik beim Lernen.',
      ornekTr: 'Ders çalışırken müzik dinliyorum.',
      not: 'Müzik "hören" ile dinlenir; "zuhören" ise birine kulak vermektir.',
    },
    {
      id: 'de-muz-12', on: 'der Sänger', okunus: 'der zengır', tur: 'isim (eril)',
      arka: 'şarkıcı (erkek)',
      ornek: 'Der Sänger hat eine tiefe Stimme.',
      ornekTr: 'Şarkıcının kalın bir sesi var.',
      not: 'Kadın şarkıcı "die Sängerin"dir; meslek adları "-in" ile dişil olur.',
    },
    {
      id: 'de-muz-13', on: 'die Band', okunus: 'di bent', tur: 'isim (dişil)',
      arka: 'müzik grubu',
      ornek: 'Die Band spielt heute Abend.',
      ornekTr: 'Grup bu akşam çalıyor.',
      not: 'İngilizceden alınmıştır ama artikeli dişildir.',
    },
    {
      id: 'de-muz-14', on: 'das Konzert', okunus: 'das kontsert', tur: 'isim (nötr)',
      arka: 'konser',
      ornek: 'Wir gehen morgen ins Konzert.',
      ornekTr: 'Yarın konsere gidiyoruz.',
      not: '"ins" = in das kısaltmasıdır ve yön bildirir.',
    },
    {
      id: 'de-muz-15', on: 'das Album', okunus: 'das album', tur: 'isim (nötr)',
      arka: 'albüm',
      ornek: 'Ihr neues Album ist super.',
      ornekTr: 'Yeni albümleri harika.',
      not: 'Çoğulu düzensizdir: "die Alben".',
    },
    {
      id: 'de-muz-16', on: 'der Liedtext', okunus: 'der liittekst', tur: 'isim (eril)',
      arka: 'şarkı sözü',
      ornek: 'Ich verstehe den Liedtext nicht.',
      ornekTr: 'Şarkı sözünü anlamıyorum.',
      not: 'Kısaca "der Text" de denir.',
    },
    {
      id: 'de-muz-17', on: 'der Refrain', okunus: 'der refreng', tur: 'isim (eril)',
      arka: 'nakarat',
      ornek: 'Alle singen den Refrain mit.',
      ornekTr: 'Herkes nakarata eşlik ediyor.',
      not: 'Fransızca kökenlidir, sonu burundan okunur.',
    },
    {
      id: 'de-muz-18', on: 'die Playlist', okunus: 'di pleylist', tur: 'isim (dişil)',
      arka: 'çalma listesi',
      ornek: 'Ich habe eine Playlist zum Lernen.',
      ornekTr: 'Ders çalışmak için bir çalma listem var.',
      not: '"zum + isim" amaç bildirir: zum Lernen = çalışmak için.',
    },
    {
      id: 'de-muz-19', on: 'streamen', okunus: 'ştriimın', tur: 'fiil',
      arka: 'internetten dinlemek/izlemek',
      ornek: 'Wir streamen die Serie am Wochenende.',
      ornekTr: 'Diziyi hafta sonu izliyoruz.',
      not: 'Yeni bir fiildir ve düzenli çekilir: streamt · hat gestreamt.',
    },
    {
      id: 'de-muz-20', on: 'der Kopfhörer', okunus: 'der kopfhöörır', tur: 'isim (eril)',
      arka: 'kulaklık',
      ornek: 'Ohne Kopfhörer höre ich keine Musik.',
      ornekTr: 'Kulaklıksız müzik dinlemem.',
      not: '"Kopf" baş, "Hörer" dinleyen demektir.',
    },
    /* --- Enstrüman ve müzik yapmak --- */
    {
      id: 'de-muz-21', on: 'das Instrument', okunus: 'das instrument', tur: 'isim (nötr)',
      arka: 'çalgı',
      ornek: 'Spielst du ein Instrument?',
      ornekTr: 'Bir çalgı çalıyor musun?',
      not: 'Çalgı çalmak için fiil "spielen"dir.',
    },
    {
      id: 'de-muz-22', on: 'die Gitarre', okunus: 'di gitarrı', tur: 'isim (dişil)',
      arka: 'gitar',
      ornek: 'Er spielt seit drei Jahren Gitarre.',
      ornekTr: 'Üç yıldır gitar çalıyor.',
      not: 'Çalgı adları artikelsiz kullanılır: "Gitarre spielen".',
    },
    {
      id: 'de-muz-23', on: 'das Klavier', okunus: 'das klaviir', tur: 'isim (nötr)',
      arka: 'piyano',
      ornek: 'Meine Schwester lernt Klavier.',
      ornekTr: 'Kız kardeşim piyano öğreniyor.',
      not: 'Türkçedeki "klavye" ile karıştırma; o "die Tastatur"dur.',
    },
    {
      id: 'de-muz-24', on: 'das Schlagzeug', okunus: 'das şlaaktsoyk', tur: 'isim (nötr)',
      arka: 'bateri',
      ornek: 'Das Schlagzeug ist zu laut für die Wohnung.',
      ornekTr: 'Bateri daire için fazla gürültülü.',
      not: '"schlagen" vurmak, "Zeug" alet demektir.',
    },
    {
      id: 'de-muz-25', on: 'üben', okunus: 'üübın', tur: 'fiil',
      arka: 'alıştırma yapmak, çalışmak',
      ornek: 'Ich muss jeden Tag eine Stunde üben.',
      ornekTr: 'Her gün bir saat çalışmam gerekiyor.',
      not: '"lernen" öğrenmek, "üben" tekrar ederek pekiştirmektir.',
    },
    {
      id: 'de-muz-26', on: 'singen', okunus: 'zingın', tur: 'fiil (kuvvetli)',
      arka: 'şarkı söylemek',
      ornek: 'Wir singen zusammen im Chor.',
      ornekTr: 'Koroda birlikte şarkı söylüyoruz.',
      not: 'Çekimi: singt · hat gesungen.',
    },
    {
      id: 'de-muz-27', on: 'der Chor', okunus: 'der koor', tur: 'isim (eril)',
      arka: 'koro',
      ornek: 'Der Chor tritt am Freitag auf.',
      ornekTr: 'Koro cuma günü sahne alıyor.',
      not: '"ch" burada "k" okunur; Yunanca kökenli kelimelerde böyledir.',
    },
    {
      id: 'de-muz-28', on: 'auftreten', okunus: 'auftreetın', tur: 'fiil (ayrılabilir)',
      arka: 'sahne almak',
      ornek: 'Die Band tritt heute Abend auf.',
      ornekTr: 'Grup bu akşam sahne alıyor.',
      not: 'Ayrılabilir fiildir: "tritt ... auf".',
      kok: 'tritt',
    },
    {
      id: 'de-muz-29', on: 'das Lampenfieber', okunus: 'das lampınfiibır', tur: 'isim (nötr)',
      arka: 'sahne heyecanı',
      ornek: 'Vor dem Konzert hatte sie Lampenfieber.',
      ornekTr: 'Konserden önce sahne heyecanı yaşadı.',
      not: 'Kelimesi kelimesine "lamba ateşi"dir; sahne ışıklarından gelir.',
    },
    {
      id: 'de-muz-30', on: 'laut / leise', okunus: 'laut / layzı', tur: 'sıfat',
      arka: 'gürültülü / sessiz',
      ornek: 'Mach die Musik bitte leiser.',
      ornekTr: 'Lütfen müziğin sesini kıs.',
      not: 'Karşılaştırma "-er" ile yapılır: leiser = daha sessiz.',
    },
    /* --- Dizi ve film yapısı --- */
    {
      id: 'de-muz-31', on: 'die Folge', okunus: 'di folgı', tur: 'isim (dişil)',
      arka: 'bölüm',
      ornek: 'Die letzte Folge war sehr spannend.',
      ornekTr: 'Son bölüm çok heyecanlıydı.',
      not: '"folgen" (takip etmek) fiilinden gelir; sonuç anlamı da vardır.',
    },
    {
      id: 'de-muz-32', on: 'die Staffel', okunus: 'di ştafıl', tur: 'isim (dişil)',
      arka: 'sezon',
      ornek: 'Die dritte Staffel kommt im Herbst.',
      ornekTr: 'Üçüncü sezon sonbaharda geliyor.',
      not: 'Atletizmde bayrak yarışı anlamına da gelir.',
    },
    {
      id: 'de-muz-33', on: 'der Schauspieler', okunus: 'der şauşpiilır', tur: 'isim (eril)',
      arka: 'oyuncu (erkek)',
      ornek: 'Der Schauspieler hat einen Preis bekommen.',
      ornekTr: 'Oyuncu bir ödül aldı.',
      not: '"schauen" bakmak, "spielen" oynamak demektir.',
    },
    {
      id: 'de-muz-34', on: 'der Regisseur', okunus: 'der rejisöör', tur: 'isim (eril)',
      arka: 'yönetmen',
      ornek: 'Der Regisseur ist bekannt für ruhige Filme.',
      ornekTr: 'Yönetmen sakin filmleriyle tanınıyor.',
      not: 'Fransızca kökenlidir; "g" yumuşak okunur.',
    },
    {
      id: 'de-muz-35', on: 'die Synchronisation', okunus: 'di zünkronizatsyoon', tur: 'isim (dişil)',
      arka: 'dublaj',
      ornek: 'In Deutschland ist die Synchronisation üblich.',
      ornekTr: 'Almanya\'da dublaj yaygındır.',
      not: 'Almanya\'da yabancı filmler genellikle dublajla gösterilir.',
    },
    {
      id: 'de-muz-36', on: 'das Kino', okunus: 'das kiino', tur: 'isim (nötr)',
      arka: 'sinema',
      ornek: 'Gehen wir heute ins Kino?',
      ornekTr: 'Bugün sinemaya gidelim mi?',
      not: 'Yön için "ins Kino", bulunma için "im Kino" denir.',
    },
    {
      id: 'de-muz-37', on: 'die Vorstellung', okunus: 'di forştelung', tur: 'isim (dişil)',
      arka: 'gösterim, seans',
      ornek: 'Die Vorstellung beginnt um acht.',
      ornekTr: 'Gösterim saat sekizde başlıyor.',
      not: 'Aynı kelime "hayal, tasavvur" anlamına da gelir.',
    },
    {
      id: 'de-muz-38', on: 'der Trailer', okunus: 'der treylır', tur: 'isim (eril)',
      arka: 'fragman',
      ornek: 'Der Trailer sieht vielversprechend aus.',
      ornekTr: 'Fragman umut verici görünüyor.',
      not: '"aussehen" = görünmek, ayrılabilir fiildir.',
    },
    {
      id: 'de-muz-39', on: 'der Held', okunus: 'der helt', tur: 'isim (eril)',
      arka: 'kahraman',
      ornek: 'Der Held rettet am Ende die Stadt.',
      ornekTr: 'Kahraman sonunda şehri kurtarıyor.',
      not: 'Kadın kahraman "die Heldin"dir. Kötü karakter "der Bösewicht".',
    },
    {
      id: 'de-muz-40', on: 'das Ende', okunus: 'das endı', tur: 'isim (nötr)',
      arka: 'son, final',
      ornek: 'Das Ende hat mich überrascht.',
      ornekTr: 'Final beni şaşırttı.',
      not: '"am Ende" = sonunda; çok kullanılan bir kalıptır.',
    },
    /* --- Türler --- */
    {
      id: 'de-muz-41', on: 'die Komödie', okunus: 'di komöödyı', tur: 'isim (dişil)',
      arka: 'komedi',
      ornek: 'Ich mag Komödien lieber als Krimis.',
      ornekTr: 'Komedileri polisiyelerden daha çok seviyorum.',
      not: '"lieber als" = -den daha çok (tercih).',
    },
    {
      id: 'de-muz-42', on: 'der Krimi', okunus: 'der krimi', tur: 'isim (eril)',
      arka: 'polisiye',
      ornek: 'Sonntagabend läuft immer ein Krimi.',
      ornekTr: 'Pazar akşamı hep bir polisiye oynar.',
      not: '"Kriminalfilm" kelimesinin kısaltmasıdır; Almanya\'da çok sevilir.',
    },
    {
      id: 'de-muz-43', on: 'der Horrorfilm', okunus: 'der horrorfilm', tur: 'isim (eril)',
      arka: 'korku filmi',
      ornek: 'Horrorfilme schaue ich nie allein.',
      ornekTr: 'Korku filmlerini asla yalnız izlemem.',
      not: 'Cümle nesneyle başlayabilir; fiil yine ikinci sırada kalır.',
    },
    {
      id: 'de-muz-44', on: 'die Dokumentation', okunus: 'di dokumentatsyoon', tur: 'isim (dişil)',
      arka: 'belgesel',
      ornek: 'Wir haben eine Dokumentation über Wale gesehen.',
      ornekTr: 'Balinalar hakkında bir belgesel izledik.',
      not: 'Konuşmada kısaca "die Doku" denir.',
    },
    {
      id: 'de-muz-45', on: 'der Zeichentrickfilm', okunus: 'der tsayhıntrikfilm', tur: 'isim (eril)',
      arka: 'çizgi film',
      ornek: 'Als Kind liebte ich Zeichentrickfilme.',
      ornekTr: 'Çocukken çizgi filmlere bayılırdım.',
      not: '"zeichnen" çizmek demektir. "Anime" için "der Anime" kullanılır.',
    },
    {
      id: 'de-muz-46', on: 'die Fortsetzung', okunus: 'di fortzetsung', tur: 'isim (dişil)',
      arka: 'devam filmi, devamı',
      ornek: 'Die Fortsetzung war schlechter als der erste Teil.',
      ornekTr: 'Devam filmi ilk bölümden kötüydü.',
      not: '"fortsetzen" = devam ettirmek.',
    },
    {
      id: 'de-muz-47', on: 'die Hauptrolle', okunus: 'di hauptrolı', tur: 'isim (dişil)',
      arka: 'başrol',
      ornek: 'Sie spielt die Hauptrolle in dem Film.',
      ornekTr: 'Filmde başrolü oynuyor.',
      not: '"Haupt-" ön eki "ana, baş" anlamı katar.',
    },
    {
      id: 'de-muz-48', on: 'die Musik zum Film', okunus: 'di muziik tsum film', tur: 'kalıp',
      arka: 'film müziği',
      ornek: 'Die Musik zum Film ist wunderschön.',
      ornekTr: 'Filmin müziği çok güzel.',
      not: '"der Soundtrack" da yaygın olarak kullanılır.',
    },
    {
      id: 'de-muz-49', on: 'basiert auf', okunus: 'baziirt auf', tur: 'kalıp',
      arka: '... dayanıyor, ...den uyarlanmış',
      ornek: 'Der Film basiert auf einem Roman.',
      ornekTr: 'Film bir romandan uyarlanmış.',
      not: 'Edatı "auf"tur ve Dativ ister.',
    },
    {
      id: 'de-muz-50', on: 'der Spoiler', okunus: 'der şpoylır', tur: 'isim (eril)',
      arka: 'sürprizi bozan bilgi',
      ornek: 'Kein Spoiler bitte, ich habe es noch nicht gesehen.',
      ornekTr: 'Lütfen sürprizi bozma, henüz izlemedim.',
      not: 'Almancada da İngilizce biçimiyle kullanılır.',
    },
    /* --- Beğeni anlatmak --- */
    {
      id: 'de-muz-51', on: 'gefallen', okunus: 'gıfalın', tur: 'fiil (Dativ)',
      arka: 'hoşuna gitmek',
      ornek: 'Der Film gefällt mir sehr.',
      ornekTr: 'Film çok hoşuma gidiyor.',
      not: 'Özne beğenilen şeydir, kişi Dativ olur: "mir gefällt".',
      kok: 'gefäll',
    },
    {
      id: 'de-muz-52', on: 'mögen', okunus: 'möögın', tur: 'fiil (kural dışı)',
      arka: 'sevmek, hoşlanmak',
      ornek: 'Ich mag diese Band sehr.',
      ornekTr: 'Bu grubu çok seviyorum.',
      not: '"gefallen"dan farkı: burada özne kişidir. Çekimi: mag · hat gemocht.',
      kok: 'mag',
    },
    {
      id: 'de-muz-53', on: 'Ich finde es gut', okunus: 'ih findı es guut', tur: 'kalıp',
      arka: 'Bence iyi',
      ornek: 'Ich finde es gut, dass die Serie kurz ist.',
      ornekTr: 'Dizinin kısa olması bence iyi.',
      not: 'Fikir belirtmenin en doğal Almanca yoludur.',
    },
    {
      id: 'de-muz-54', on: 'toll', okunus: 'tol', tur: 'sıfat',
      arka: 'harika',
      ornek: 'Das Konzert war einfach toll.',
      ornekTr: 'Konser gerçekten harikaydı.',
      not: 'Günlük dilde çok kullanılır; "super" ile eşanlamlıdır.',
    },
    {
      id: 'de-muz-55', on: 'mies', okunus: 'miis', tur: 'sıfat',
      arka: 'berbat',
      ornek: 'Der zweite Teil war ziemlich mies.',
      ornekTr: 'İkinci bölüm oldukça berbattı.',
      not: 'Gündelik ve serttir; resmî yazıda kullanılmaz.',
    },
    {
      id: 'de-muz-56', on: 'empfehlen', okunus: 'empfeelın', tur: 'fiil (kuvvetli)',
      arka: 'tavsiye etmek',
      ornek: 'Ich empfehle dir diese Serie.',
      ornekTr: 'Sana bu diziyi tavsiye ediyorum.',
      not: 'Kişi Dativ, şey Akkusativ olur: "empfehle dir die Serie".',
    },
    {
      id: 'de-muz-57', on: 'die Kritik', okunus: 'di kritiik', tur: 'isim (dişil)',
      arka: 'eleştiri',
      ornek: 'Die Kritiken waren sehr gut.',
      ornekTr: 'Eleştiriler çok iyiydi.',
      not: 'Eleştirmen "der Kritiker"dır.',
    },
    {
      id: 'de-muz-58', on: 'die Meinung', okunus: 'di maynung', tur: 'isim (dişil)',
      arka: 'görüş, fikir',
      ornek: 'Meiner Meinung nach ist das Buch besser.',
      ornekTr: 'Bence kitap daha iyi.',
      not: '"meiner Meinung nach" kalıbı "bence" demektir; sıra sabittir.',
    },
    {
      id: 'de-muz-59', on: 'Geschmackssache', okunus: 'gışmaksazı', tur: 'isim (dişil)',
      arka: 'zevk meselesi',
      ornek: 'Das ist Geschmackssache.',
      ornekTr: 'Bu bir zevk meselesi.',
      not: '"Geschmack" tat, zevk demektir.',
    },
    {
      id: 'de-muz-60', on: 'Es kommt darauf an', okunus: 'es komt darauf an', tur: 'kalıp',
      arka: 'Duruma bağlı',
      ornek: 'Es kommt darauf an, wie viel Zeit ich habe.',
      ornekTr: 'Ne kadar vaktim olduğuna bağlı.',
      not: '"ankommen auf" = bağlı olmak; ayrılabilir fiildir.',
    },
    /* --- İzleme alışkanlıkları --- */
    {
      id: 'de-muz-61', on: 'das Abo', okunus: 'das aboo', tur: 'isim (nötr)',
      arka: 'abonelik',
      ornek: 'Mein Abo läuft nächsten Monat aus.',
      ornekTr: 'Aboneliğim gelecek ay bitiyor.',
      not: '"das Abonnement" kelimesinin kısaltmasıdır.',
    },
    {
      id: 'de-muz-62', on: 'die Werbung', okunus: 'di verbung', tur: 'isim (dişil)',
      arka: 'reklam',
      ornek: 'Die Werbung nervt mich.',
      ornekTr: 'Reklamlar sinirimi bozuyor.',
      not: '"nerven" = sinir etmek; günlük dilde çok kullanılır.',
    },
    {
      id: 'de-muz-63', on: 'die Fernbedienung', okunus: 'di fernbıdiinung', tur: 'isim (dişil)',
      arka: 'uzaktan kumanda',
      ornek: 'Wo ist die Fernbedienung?',
      ornekTr: 'Kumanda nerede?',
      not: '"fern" uzak, "bedienen" kullanmak demektir.',
    },
    {
      id: 'de-muz-64', on: 'einschalten', okunus: 'aynşaltın', tur: 'fiil (ayrılabilir)',
      arka: 'açmak (cihazı)',
      ornek: 'Schalt bitte den Fernseher ein.',
      ornekTr: 'Lütfen televizyonu aç.',
      not: 'Tersi "ausschalten" = kapatmak.',
      kok: 'schalt',
    },
    {
      id: 'de-muz-65', on: 'die Lieblingsserie', okunus: 'di liiplingszeerye', tur: 'isim (dişil)',
      arka: 'en sevdiği dizi',
      ornek: 'Das ist meine Lieblingsserie.',
      ornekTr: 'Bu benim en sevdiğim dizi.',
      not: '"Lieblings-" ön eki her isme eklenebilir: Lieblingsfach, Lieblingsessen.',
    },
    {
      id: 'de-muz-66', on: 'noch einmal', okunus: 'noh aynmaal', tur: 'kalıp',
      arka: 'bir kez daha',
      ornek: 'Ich schaue die Folge noch einmal.',
      ornekTr: 'Bölümü bir kez daha izliyorum.',
      not: 'Günlük dilde "nochmal" diye kısaltılır.',
    },
    {
      id: 'de-muz-67', on: 'zu Ende schauen', okunus: 'tsu endı şauın', tur: 'kalıp',
      arka: 'sonuna kadar izlemek',
      ornek: 'Wir schauen den Film zu Ende.',
      ornekTr: 'Filmi sonuna kadar izliyoruz.',
      not: '"zu Ende" kalıbı bitirmeyi anlatır: zu Ende lesen, zu Ende hören.',
    },
    {
      id: 'de-muz-68', on: 'verpassen', okunus: 'ferpasın', tur: 'fiil',
      arka: 'kaçırmak',
      ornek: 'Ich habe die letzte Folge verpasst.',
      ornekTr: 'Son bölümü kaçırdım.',
      not: 'Otobüs ve tren için de kullanılır: "den Bus verpassen".',
    },
    {
      id: 'de-muz-69', on: 'die Untertitel', okunus: 'di untırtiitıl', tur: 'isim (çoğul)',
      arka: 'altyazılar',
      ornek: 'Ich schaue Serien mit deutschen Untertiteln.',
      ornekTr: 'Dizileri Almanca altyazıyla izliyorum.',
      not: 'Dil öğrenirken en etkili yöntemlerden biridir.',
    },
    {
      id: 'de-muz-70', on: 'auf Deutsch', okunus: 'auf doyç', tur: 'kalıp',
      arka: 'Almanca olarak',
      ornek: 'Ich schaue den Film auf Deutsch.',
      ornekTr: 'Filmi Almanca izliyorum.',
      not: 'Dil bildirirken edat "auf"tur ve dil büyük yazılır.',
    },
    /* --- Sıfatlarla anlatmak --- */
    {
      id: 'de-muz-71', on: 'traurig', okunus: 'traurih', tur: 'sıfat',
      arka: 'hüzünlü',
      ornek: 'Das Ende war sehr traurig.',
      ornekTr: 'Final çok hüzünlüydü.',
      not: 'İsmi "die Trauer" = yas, keder.',
    },
    {
      id: 'de-muz-72', on: 'lustig', okunus: 'lustih', tur: 'sıfat',
      arka: 'komik',
      ornek: 'Die Serie ist wirklich lustig.',
      ornekTr: 'Dizi gerçekten komik.',
      not: '"Lust" keyif, istek demektir.',
    },
    {
      id: 'de-muz-73', on: 'gruselig', okunus: 'gruuzılih', tur: 'sıfat',
      arka: 'tüyler ürpertici',
      ornek: 'Der Anfang war ziemlich gruselig.',
      ornekTr: 'Başlangıç oldukça tüyler ürperticiydi.',
      not: '"Gruseln" ürpermek demektir.',
    },
    {
      id: 'de-muz-74', on: 'kitschig', okunus: 'kiçih', tur: 'sıfat',
      arka: 'aşırı duygusal, yavan',
      ornek: 'Der Film war mir zu kitschig.',
      ornekTr: 'Film bana fazla yavan geldi.',
      not: '"zu + sıfat" = fazlasıyla; "mir zu" kişisel ölçüyü anlatır.',
    },
    {
      id: 'de-muz-75', on: 'vorhersehbar', okunus: 'forheerzeebar', tur: 'sıfat',
      arka: 'tahmin edilebilir',
      ornek: 'Die Handlung war leider vorhersehbar.',
      ornekTr: 'Olay örgüsü maalesef tahmin edilebilirdi.',
      not: '"vorhersehen" = önceden görmek.',
    },
    {
      id: 'de-muz-76', on: 'beeindruckend', okunus: 'bıayndrukınt', tur: 'sıfat',
      arka: 'etkileyici',
      ornek: 'Die Bilder waren beeindruckend.',
      ornekTr: 'Görüntüler etkileyiciydi.',
      not: '"Eindruck" izlenim demektir.',
    },
    {
      id: 'de-muz-77', on: 'überbewertet', okunus: 'übırbıveertıt', tur: 'sıfat',
      arka: 'hak ettiğinden fazla övülen',
      ornek: 'Diese Serie ist überbewertet.',
      ornekTr: 'Bu dizi hak ettiğinden fazla övülüyor.',
      not: 'Tersi "unterbewertet" = hak ettiği değeri görmeyen.',
    },
    {
      id: 'de-muz-78', on: 'die Handlung ist verwirrend', okunus: 'di handlung ist fervirınt', tur: 'kalıp',
      arka: 'Olay örgüsü kafa karıştırıcı',
      ornek: 'Am Anfang ist die Handlung verwirrend.',
      ornekTr: 'Başlangıçta olay örgüsü kafa karıştırıcı.',
      not: '"verwirren" = kafasını karıştırmak.',
    },
    {
      id: 'de-muz-79', on: 'es lohnt sich', okunus: 'es loont zih', tur: 'kalıp',
      arka: 'değer, buna değer',
      ornek: 'Der Film ist lang, aber es lohnt sich.',
      ornekTr: 'Film uzun ama buna değer.',
      not: 'Dönüşlü bir fiildir: "sich lohnen".',
    },
    {
      id: 'de-muz-80', on: 'auf jeden Fall', okunus: 'auf yeedın fal', tur: 'kalıp',
      arka: 'kesinlikle, her hâlükârda',
      ornek: 'Das solltest du auf jeden Fall sehen.',
      ornekTr: 'Bunu kesinlikle izlemelisin.',
      not: 'Tersi "auf keinen Fall" = kesinlikle hayır.',
    },
    /* --- Müzik ve sahne deyimleri --- */
    {
      id: 'de-muz-81', on: 'die Nase voll haben', okunus: 'di naazı fol haabın', tur: 'deyim',
      arka: 'bıkmak, gına gelmek',
      ornek: 'Ich habe die Nase voll von dieser Werbung.',
      ornekTr: 'Bu reklamdan gına geldi.',
      not: 'Edatı "von"dur.',
    },
    {
      id: 'de-muz-82', on: 'aus dem Häuschen sein', okunus: 'aus deem hoyshın zayn', tur: 'deyim',
      arka: 'sevinçten havalara uçmak',
      ornek: 'Die Fans waren völlig aus dem Häuschen.',
      ornekTr: 'Taraftarlar sevinçten havalara uçtu.',
      not: 'Kelimesi kelimesine "evciğinden çıkmak"tır.',
    },
    {
      id: 'de-muz-83', on: 'den Ton angeben', okunus: 'deen toon angeebın', tur: 'deyim',
      arka: 'havayı belirlemek, yön vermek',
      ornek: 'In der Gruppe gibt sie den Ton an.',
      ornekTr: 'Grupta yönü o belirliyor.',
      not: 'Müzikten gelir; koroya tonu vermekten türemiştir.',
      kok: 'gib',
    },
    {
      id: 'de-muz-84', on: 'ins Schwärmen geraten', okunus: 'ins şvermın gıraatın', tur: 'deyim',
      arka: 'hayranlıkla anlatmaya başlamak',
      ornek: 'Er gerät bei diesem Album ins Schwärmen.',
      ornekTr: 'Bu albüm söz konusu olunca hayranlıkla anlatmaya başlıyor.',
      not: '"schwärmen für" = birine hayran olmak.',
    },
    {
      id: 'de-muz-85', on: 'Musik im Ohr haben', okunus: 'muziik im oor haabın', tur: 'kalıp',
      arka: 'melodi aklına takılmak',
      ornek: 'Ich habe die Musik den ganzen Tag im Ohr.',
      ornekTr: 'Melodi bütün gün aklıma takıldı.',
      not: 'Bu duruma Almancada "der Ohrwurm" da denir.',
    },
    {
      id: 'de-muz-86', on: 'nach und nach', okunus: 'naah unt naah', tur: 'kalıp',
      arka: 'yavaş yavaş',
      ornek: 'Nach und nach gefällt mir die Serie.',
      ornekTr: 'Yavaş yavaş dizi hoşuma gitmeye başladı.',
      not: 'İkileme biçimindeki sık kullanılan bir zarftır.',
    },
    {
      id: 'de-muz-87', on: 'zum Glück', okunus: 'tsum glük', tur: 'kalıp',
      arka: 'neyse ki',
      ornek: 'Zum Glück gibt es eine zweite Staffel.',
      ornekTr: 'Neyse ki ikinci sezon var.',
      not: 'Cümle başında kullanılınca fiil hemen arkasından gelir.',
    },
    {
      id: 'de-muz-88', on: 'leider', okunus: 'laydır', tur: 'zarf',
      arka: 'maalesef',
      ornek: 'Leider habe ich keine Zeit für Serien.',
      ornekTr: 'Maalesef dizilere vaktim yok.',
      not: 'Cümle başına gelirse fiil ikinci sırada kalır: "Leider habe ich".',
    },
    {
      id: 'de-muz-89', on: 'endlich', okunus: 'entlih', tur: 'zarf',
      arka: 'nihayet',
      ornek: 'Endlich kommt die neue Folge.',
      ornekTr: 'Nihayet yeni bölüm geliyor.',
      not: '"endlos" sonsuz demektir; karıştırma.',
    },
    {
      id: 'de-muz-90', on: 'sowieso', okunus: 'zoviizoo', tur: 'zarf',
      arka: 'zaten, nasılsa',
      ornek: 'Ich schaue sowieso jeden Abend etwas.',
      ornekTr: 'Zaten her akşam bir şeyler izliyorum.',
      not: 'Konuşma dilinde çok sık geçer.',
    },
    /* --- Konuşma soruları --- */
    {
      id: 'de-muz-91', on: 'Was für Musik hörst du?', okunus: 'vas füür muziik hörst du', tur: 'soru kalıbı',
      arka: 'Ne tür müzik dinliyorsun?',
      ornek: 'Was für Musik hörst du am liebsten?',
      ornekTr: 'En çok ne tür müzik dinliyorsun?',
      not: '"Was für" = ne tür; sonrasında artikelsiz isim gelir.',
    },
    {
      id: 'de-muz-92', on: 'am liebsten', okunus: 'am liipstın', tur: 'kalıp',
      arka: 'en çok, en sevdiği biçimde',
      ornek: 'Am liebsten höre ich Rockmusik.',
      ornekTr: 'En çok rock müzik dinlerim.',
      not: 'gern - lieber - am liebsten sıralamasının en üst basamağıdır.',
    },
    {
      id: 'de-muz-93', on: 'Worum geht es?', okunus: 'voruum geet es', tur: 'soru kalıbı',
      arka: 'Konusu ne?',
      ornek: 'Worum geht es in dem Film?',
      ornekTr: 'Filmin konusu ne?',
      not: '"Es geht um ..." = konusu ... hakkındadır.',
    },
    {
      id: 'de-muz-94', on: 'Es geht um', okunus: 'es geet um', tur: 'kalıp',
      arka: '... hakkında',
      ornek: 'Es geht um eine Familie in Berlin.',
      ornekTr: 'Berlin\'deki bir aileyi anlatıyor.',
      not: 'Konu anlatmanın en yaygın Almanca kalıbıdır.',
    },
    {
      id: 'de-muz-95', on: 'Hast du das gesehen?', okunus: 'hast du das gızeeın', tur: 'soru kalıbı',
      arka: 'Bunu izledin mi?',
      ornek: 'Hast du die neue Staffel gesehen?',
      ornekTr: 'Yeni sezonu izledin mi?',
      not: '"sehen" fiilinin geçmiş ortacı "gesehen"dir.',
    },
    {
      id: 'de-muz-96', on: 'Ich kann es nur empfehlen', okunus: 'ih kan es nuur empfeelın', tur: 'kalıp',
      arka: 'Kesinlikle tavsiye ederim',
      ornek: 'Der Film ist toll, ich kann ihn nur empfehlen.',
      ornekTr: 'Film harika, kesinlikle tavsiye ederim.',
      not: '"nur" burada vurgu katar, "sadece" anlamına gelmez.',
    },
    {
      id: 'de-muz-97', on: 'Mir hat es gefallen', okunus: 'mir hat es gıfalın', tur: 'kalıp',
      arka: 'Hoşuma gitti',
      ornek: 'Mir hat der zweite Teil besser gefallen.',
      ornekTr: 'İkinci bölüm daha çok hoşuma gitti.',
      not: 'Kişi Dativ ile başlar; Almancanın tipik cümle sırasıdır.',
    },
    {
      id: 'de-muz-98', on: 'Wie fandest du...?', okunus: 'vii fandıst du', tur: 'soru kalıbı',
      arka: '... nasıl buldun?',
      ornek: 'Wie fandest du das Konzert?',
      ornekTr: 'Konseri nasıl buldun?',
      not: '"finden" fiilinin geçmiş hâli "fand"dır.',
    },
    {
      id: 'de-muz-99', on: 'nicht so mein Ding', okunus: 'niht zo mayn ding', tur: 'kalıp',
      arka: 'pek benim tarzım değil',
      ornek: 'Horrorfilme sind nicht so mein Ding.',
      ornekTr: 'Korku filmleri pek benim tarzım değil.',
      not: 'Gündelik ve kibar bir beğenmeme ifadesidir.',
    },
    {
      id: 'de-muz-100', on: 'Geschmäcker sind verschieden', okunus: 'gışmekır zint ferşiidın', tur: 'atasözü',
      arka: 'Zevkler ve renkler tartışılmaz',
      ornek: 'Du magst es nicht? Geschmäcker sind verschieden.',
      ornekTr: 'Sevmedin mi? Zevkler ve renkler tartışılmaz.',
      not: 'Türkçedeki atasözüyle aynı işlevdedir.',
    },
  ],
}

export default DESTE
