/**
 * DESTE — SEYAHAT VE ŞEHİR (Almanca)
 *
 * Almanya'da tren ve istasyon anonsları standarttır. Bu destedeki
 * kelimeler bir kez öğrenilirse her istasyonda aynen işe yarar.
 */

export const DESTE = {
  id: 'seyahat',
  dil: 'de',
  ad: 'Seyahat ve şehir',
  simge: '✈️',
  aciklama: 'İstasyonda, otelde ve sokakta ilk saatte lazım olanlar.',
  seviye: 'A1–A2',
  kartlar: [
    {
      id: 'de-sey-01', on: 'die Fahrkarte', okunus: 'di faarkartı', tur: 'isim (dişil)',
      arka: 'bilet (ulaşım)',
      ornek: 'Ich habe meine Fahrkarte online gekauft.',
      ornekTr: 'Biletimi internetten aldım.',
      not: 'Uçak bileti "das Ticket" ya da "das Flugticket"tir.',
    },
    {
      id: 'de-sey-02', on: 'der Bahnhof', okunus: 'der baanhoof', tur: 'isim (eril)',
      arka: 'tren garı',
      ornek: 'Der Bahnhof ist zehn Minuten zu Fuß entfernt.',
      ornekTr: 'Gar yürüyerek on dakika uzaklıkta.',
      not: 'Ana gar "der Hauptbahnhof"tur ve "Hbf" diye kısaltılır.',
    },
    {
      id: 'de-sey-03', on: 'das Gleis', okunus: 'das glays', tur: 'isim (nötr)',
      arka: 'peron',
      ornek: 'Der Zug fährt von Gleis drei ab.',
      ornekTr: 'Tren üç numaralı perondan kalkıyor.',
      not: 'Anonslarda en çok duyacağın kelime. Kalkmak "abfahren" (ayrılabilir).',
    },
    {
      id: 'de-sey-04', on: 'der Koffer', okunus: 'der kofır', tur: 'isim (eril)',
      arka: 'valiz, bavul',
      ornek: 'Mein Koffer ist viel zu schwer.',
      ornekTr: 'Valizim çok fazla ağır.',
      not: 'Sırt çantası "der Rucksack". "viel zu" = çok fazla.',
    },
    {
      id: 'de-sey-05', on: 'sich verlaufen', kok: 'verlauf', okunus: 'zih ferlaufın', tur: 'fiil (dönüşlü)',
      arka: 'yolunu kaybetmek',
      ornek: 'Entschuldigung, ich habe mich verlaufen.',
      ornekTr: 'Affedersiniz, kayboldum.',
      not: 'Yürürken kaybolmak içindir; eşya kaybetmek "verlieren"dır.',
    },
    {
      id: 'de-sey-06', on: 'geradeaus', okunus: 'geradeaus', tur: 'zarf',
      arka: 'dümdüz',
      ornek: 'Gehen Sie geradeaus bis zur Ampel.',
      ornekTr: 'Işıklara kadar dümdüz gidin.',
      not: 'Yol tarifinin üçlüsü: geradeaus, links (sol), rechts (sağ).',
    },
    {
      id: 'de-sey-07', on: 'die Jugendherberge', okunus: 'di yugendherbergı', tur: 'isim (dişil)',
      arka: 'gençlik yurdu, hostel',
      ornek: 'Wir schlafen in einer Jugendherberge.',
      ornekTr: 'Bir gençlik yurdunda kalıyoruz.',
      not: '"Jugend" (gençlik) + "Herberge" (konaklama). Öğrenci bütçesinin standardı.',
    },
    {
      id: 'de-sey-08', on: 'buchen', okunus: 'buuhın', tur: 'fiil',
      arka: 'rezervasyon yaptırmak',
      ornek: 'Ich habe ein Zimmer für zwei Nächte gebucht.',
      ornekTr: 'İki gecelik bir oda ayırttım.',
      not: 'Oda "das Zimmer", gece "die Nacht" (çoğulu "Nächte").',
    },
    {
      id: 'de-sey-09', on: 'umsteigen', kok: 'steig', okunus: 'umştaygın', tur: 'fiil (ayrılabilir)',
      arka: 'aktarma yapmak',
      ornek: 'In Köln steigen wir um.',
      ornekTr: 'Köln\'de aktarma yapıyoruz.',
      not: 'Ayrılabilir fiil: ön ek "um" cümlenin sonuna gider.',
    },
    {
      id: 'de-sey-10', on: 'Wie viel kostet das?', okunus: 'vii fiil kostıt das', tur: 'kalıp',
      arka: 'Bu ne kadar?',
      ornek: 'Entschuldigung, wie viel kostet das?',
      ornekTr: 'Affedersiniz, bu ne kadar?',
      not: '"Wie viel" ayrı yazılır. Fiyat sormanın standart biçimi.',
    },
    /* --- Trenle yolculuk --- */
    {
      id: 'de-sey-11', on: 'der Zug', okunus: 'der tsuuk', tur: 'isim (eril)',
      arka: 'tren',
      ornek: 'Der Zug fährt um zehn Uhr ab.',
      ornekTr: 'Tren saat onda kalkıyor.',
      not: 'Çoğulu "die Züge"dir. Kalkmak "abfahren"dır.',
    },
    {
      id: 'de-sey-12', on: 'abfahren', okunus: 'apfaarın', tur: 'fiil (ayrılabilir)',
      arka: 'kalkmak, hareket etmek',
      ornek: 'Wann fährt der nächste Bus ab?',
      ornekTr: 'Bir sonraki otobüs ne zaman kalkıyor?',
      not: 'Ayrılabilir fiildir: "fährt ... ab".',
      kok: 'fähr',
    },
    {
      id: 'de-sey-13', on: 'ankommen', okunus: 'ankomın', tur: 'fiil (ayrılabilir)',
      arka: 'varmak',
      ornek: 'Wir kommen um sechs in München an.',
      ornekTr: 'Münih\'e altıda varıyoruz.',
      not: 'Varış "die Ankunft", kalkış "die Abfahrt"tır.',
      kok: 'komm',
    },
    {
      id: 'de-sey-14', on: 'die Verspätung', okunus: 'di ferşpeetung', tur: 'isim (dişil)',
      arka: 'gecikme',
      ornek: 'Der Zug hat zwanzig Minuten Verspätung.',
      ornekTr: 'Trenin yirmi dakika gecikmesi var.',
      not: 'Gecikme "haben" ile söylenir: "Verspätung haben".',
    },
    {
      id: 'de-sey-15', on: 'der Fahrplan', okunus: 'der faarplaan', tur: 'isim (eril)',
      arka: 'sefer tarifesi',
      ornek: 'Schau mal auf den Fahrplan.',
      ornekTr: 'Sefer tarifesine bir bak.',
      not: '"fahren" gitmek, "Plan" plan demektir.',
    },
    {
      id: 'de-sey-16', on: 'einsteigen', okunus: 'aynştaygın', tur: 'fiil (ayrılabilir)',
      arka: 'binmek',
      ornek: 'Wir steigen in den Zug ein.',
      ornekTr: 'Trene biniyoruz.',
      not: 'İnmek "aussteigen", aktarma "umsteigen"dır.',
      kok: 'steig',
    },
    {
      id: 'de-sey-17', on: 'die Fahrkarte entwerten', okunus: 'di faarkartı entveertın', tur: 'kalıp',
      arka: 'bileti damgalatmak',
      ornek: 'Du musst die Fahrkarte entwerten.',
      ornekTr: 'Bileti damgalatman gerekiyor.',
      not: 'Almanya\'da damgalanmamış bilet geçersiz sayılır ve ceza kesilir.',
    },
    {
      id: 'de-sey-18', on: 'der Schaffner', okunus: 'der şafnır', tur: 'isim (eril)',
      arka: 'kondüktör',
      ornek: 'Der Schaffner kontrolliert die Tickets.',
      ornekTr: 'Kondüktör biletleri kontrol ediyor.',
      not: '"kontrollieren" denetlemek demektir.',
    },
    {
      id: 'de-sey-19', on: 'der Sitzplatz', okunus: 'der zitsplats', tur: 'isim (eril)',
      arka: 'oturma yeri, koltuk',
      ornek: 'Ist dieser Sitzplatz frei?',
      ornekTr: 'Bu koltuk boş mu?',
      not: '"frei" burada boş demektir; "besetzt" dolu demektir.',
    },
    {
      id: 'de-sey-20', on: 'die Fahrt', okunus: 'di faart', tur: 'isim (dişil)',
      arka: 'yolculuk (araçla)',
      ornek: 'Die Fahrt dauert drei Stunden.',
      ornekTr: 'Yolculuk üç saat sürüyor.',
      not: 'Uzun seyahat "die Reise", araçla gidiş "die Fahrt"tır.',
    },
    /* --- Şehir içi ulaşım --- */
    {
      id: 'de-sey-21', on: 'die U-Bahn', okunus: 'di uu baan', tur: 'isim (dişil)',
      arka: 'metro',
      ornek: 'Nimm die U-Bahn, das geht schneller.',
      ornekTr: 'Metroya bin, daha hızlı olur.',
      not: '"Untergrundbahn" kısaltmasıdır: yer altı treni.',
    },
    {
      id: 'de-sey-22', on: 'die Straßenbahn', okunus: 'di ştraasınbaan', tur: 'isim (dişil)',
      arka: 'tramvay',
      ornek: 'Die Straßenbahn hält direkt vor dem Museum.',
      ornekTr: 'Tramvay tam müzenin önünde duruyor.',
      not: '"halten" durmak demektir; durak "die Haltestelle"dir.',
    },
    {
      id: 'de-sey-23', on: 'die Haltestelle', okunus: 'di haltıştelı', tur: 'isim (dişil)',
      arka: 'durak',
      ornek: 'Steig an der dritten Haltestelle aus.',
      ornekTr: 'Üçüncü durakta in.',
      not: 'Sıra sayıları "-ten" ekiyle çekilir: an der dritten.',
    },
    {
      id: 'de-sey-24', on: 'zu Fuß gehen', okunus: 'tsu fuus geeın', tur: 'kalıp',
      arka: 'yürüyerek gitmek',
      ornek: 'Wir gehen lieber zu Fuß.',
      ornekTr: 'Biz yürümeyi tercih ediyoruz.',
      not: 'Diğer araçlar "mit" alır: mit dem Bus, mit dem Auto.',
    },
    {
      id: 'de-sey-25', on: 'der Stau', okunus: 'der ştau', tur: 'isim (eril)',
      arka: 'trafik sıkışıklığı',
      ornek: 'Wir stehen seit einer Stunde im Stau.',
      ornekTr: 'Bir saattir trafikte bekliyoruz.',
      not: '"im Stau stehen" = trafikte kalmak.',
    },
    {
      id: 'de-sey-26', on: 'der Berufsverkehr', okunus: 'der bıruufsferkeer', tur: 'isim (eril)',
      arka: 'yoğun saat trafiği',
      ornek: 'Vermeide den Berufsverkehr.',
      ornekTr: 'Yoğun saat trafiğinden kaçın.',
      not: '"der Beruf" meslek, "der Verkehr" trafik demektir.',
    },
    {
      id: 'de-sey-27', on: 'das Ticket', okunus: 'das tikıt', tur: 'isim (nötr)',
      arka: 'bilet',
      ornek: 'Ich kaufe das Ticket online.',
      ornekTr: 'Bileti internetten alıyorum.',
      not: '"die Fahrkarte" ile aynı anlamdadır.',
    },
    {
      id: 'de-sey-28', on: 'der Fahrschein-Automat', okunus: 'der faarşayn automaat', tur: 'isim (eril)',
      arka: 'bilet otomatı',
      ornek: 'Der Fahrschein-Automat ist kaputt.',
      ornekTr: 'Bilet otomatı bozuk.',
      not: 'Kısaca "der Automat" denir.',
    },
    {
      id: 'de-sey-29', on: 'das Taxi nehmen', okunus: 'das taksi neemın', tur: 'kalıp',
      arka: 'taksiye binmek',
      ornek: 'Bei Regen nehmen wir ein Taxi.',
      ornekTr: 'Yağmurda taksiye biniyoruz.',
      not: 'Araç için fiil "nehmen"dir: "den Bus nehmen".',
    },
    {
      id: 'de-sey-30', on: 'mitnehmen', okunus: 'mitneemın', tur: 'fiil (ayrılabilir)',
      arka: 'yanına almak, arabaya almak',
      ornek: 'Kannst du mich mitnehmen?',
      ornekTr: 'Beni de alabilir misin?',
      not: 'Ayrılabilir fiildir: "nimmst ... mit".',
    },
    /* --- Havaalanı --- */
    {
      id: 'de-sey-31', on: 'der Flughafen', okunus: 'der fluukhaafın', tur: 'isim (eril)',
      arka: 'havalimanı',
      ornek: 'Wir sind zwei Stunden vorher am Flughafen.',
      ornekTr: 'Havalimanında iki saat önce olacağız.',
      not: '"der Hafen" liman demektir; uçak limanı anlamındadır.',
    },
    {
      id: 'de-sey-32', on: 'der Flug', okunus: 'der fluuk', tur: 'isim (eril)',
      arka: 'uçuş',
      ornek: 'Der Flug dauert drei Stunden.',
      ornekTr: 'Uçuş üç saat sürüyor.',
      not: 'Fiili "fliegen"dir: fliegt · ist geflogen.',
    },
    {
      id: 'de-sey-33', on: 'einchecken', okunus: 'aynçekın', tur: 'fiil (ayrılabilir)',
      arka: 'giriş işlemi yaptırmak',
      ornek: 'Ich checke online ein.',
      ornekTr: 'İnternetten giriş işlemi yapıyorum.',
      not: 'İngilizceden geçmiştir ama Almanca kurallarla çekilir.',
      kok: 'check',
    },
    {
      id: 'de-sey-34', on: 'die Bordkarte', okunus: 'di bortkartı', tur: 'isim (dişil)',
      arka: 'biniş kartı',
      ornek: 'Zeig bitte deine Bordkarte.',
      ornekTr: 'Lütfen biniş kartını göster.',
      not: '"an Bord" = uçakta, gemide.',
    },
    {
      id: 'de-sey-35', on: 'das Handgepäck', okunus: 'das hantgıpek', tur: 'isim (nötr)',
      arka: 'el bagajı',
      ornek: 'Ich reise nur mit Handgepäck.',
      ornekTr: 'Sadece el bagajıyla seyahat ediyorum.',
      not: '"das Gepäck" sayılamaz: "Gepäcke" YANLIŞTIR.',
    },
    {
      id: 'de-sey-36', on: 'die Gepäckausgabe', okunus: 'di gıpekausgaabı', tur: 'isim (dişil)',
      arka: 'bagaj alma bandı',
      ornek: 'Warte auf mich bei der Gepäckausgabe.',
      ornekTr: 'Beni bagaj alma bandında bekle.',
      not: '"ausgeben" vermek, dağıtmak demektir.',
    },
    {
      id: 'de-sey-37', on: 'der Zoll', okunus: 'der tsol', tur: 'isim (eril)',
      arka: 'gümrük',
      ornek: 'Wir gehen durch den Zoll.',
      ornekTr: 'Gümrükten geçiyoruz.',
      not: 'Gümrük vergisi anlamına da gelir.',
    },
    {
      id: 'de-sey-38', on: 'der Reisepass', okunus: 'der rayzıpas', tur: 'isim (eril)',
      arka: 'pasaport',
      ornek: 'Mein Reisepass ist noch gültig.',
      ornekTr: 'Pasaportum hâlâ geçerli.',
      not: '"gültig" geçerli demektir; süresi dolmuşsa "abgelaufen".',
    },
    {
      id: 'de-sey-39', on: 'das Visum', okunus: 'das viizum', tur: 'isim (nötr)',
      arka: 'vize',
      ornek: 'Für dieses Land braucht man ein Visum.',
      ornekTr: 'Bu ülke için vize gerekiyor.',
      not: 'Çoğulu düzensizdir: "die Visa".',
    },
    {
      id: 'de-sey-40', on: 'der Jetlag', okunus: 'der cetlek', tur: 'isim (eril)',
      arka: 'saat farkı yorgunluğu',
      ornek: 'Ich hatte drei Tage Jetlag.',
      ornekTr: 'Üç gün saat farkı yorgunluğu yaşadım.',
      not: 'İngilizceden alınmıştır ve aynı biçimde kullanılır.',
    },
    /* --- Konaklama --- */
    {
      id: 'de-sey-41', on: 'die Unterkunft', okunus: 'di untırkunft', tur: 'isim (dişil)',
      arka: 'konaklama yeri',
      ornek: 'Die Unterkunft war sauber und günstig.',
      ornekTr: 'Konaklama yeri temiz ve uygun fiyatlıydı.',
      not: '"günstig" ucuz ve uygun demektir; "billig" ise kalitesiz çağrışımı taşır.',
    },
    {
      id: 'de-sey-42', on: 'das Doppelzimmer', okunus: 'das dopıltsimır', tur: 'isim (nötr)',
      arka: 'iki kişilik oda',
      ornek: 'Wir hätten gern ein Doppelzimmer.',
      ornekTr: 'İki kişilik bir oda istiyoruz.',
      not: '"hätten gern" en kibar istek kalıbıdır.',
    },
    {
      id: 'de-sey-43', on: 'die Übernachtung', okunus: 'di übırnahtung', tur: 'isim (dişil)',
      arka: 'geceleme',
      ornek: 'Die Übernachtung kostet fünfzig Euro.',
      ornekTr: 'Geceleme elli avro.',
      not: '"übernachten" = geceyi geçirmek.',
    },
    {
      id: 'de-sey-44', on: 'inklusive', okunus: 'inkluziivı', tur: 'sıfat',
      arka: 'dâhil',
      ornek: 'Ist das Frühstück inklusive?',
      ornekTr: 'Kahvaltı dâhil mi?',
      not: 'Kısaltması "inkl."dir; menülerde sık görülür.',
    },
    {
      id: 'de-sey-45', on: 'die Rezeption', okunus: 'di retseptsyoon', tur: 'isim (dişil)',
      arka: 'resepsiyon',
      ornek: 'Der Schlüssel ist an der Rezeption.',
      ornekTr: 'Anahtar resepsiyonda.',
      not: 'Edatı "an"dır ve Dativ ister.',
    },
    {
      id: 'de-sey-46', on: 'ausgebucht', okunus: 'ausgıbuuht', tur: 'sıfat',
      arka: 'tamamen dolu',
      ornek: 'Das Hotel ist im August ausgebucht.',
      ornekTr: 'Otel ağustosta tamamen dolu.',
      not: '"buchen" (rezervasyon yapmak) fiilinden gelir.',
    },
    {
      id: 'de-sey-47', on: 'die Anzahlung', okunus: 'di antsaalung', tur: 'isim (dişil)',
      arka: 'kapora',
      ornek: 'Sie verlangen eine Anzahlung.',
      ornekTr: 'Kapora istiyorlar.',
      not: '"verlangen" talep etmek demektir.',
    },
    {
      id: 'de-sey-48', on: 'stornieren', okunus: 'ştorniirın', tur: 'fiil',
      arka: 'iptal etmek (rezervasyon)',
      ornek: 'Ich möchte die Buchung stornieren.',
      ornekTr: 'Rezervasyonu iptal etmek istiyorum.',
      not: 'Ders ve etkinlik iptali için "absagen" kullanılır.',
    },
    {
      id: 'de-sey-49', on: 'die Jugendherberge', okunus: 'di yuugınt herbergı', tur: 'isim (dişil)',
      arka: 'gençlik hosteli',
      ornek: 'Jugendherbergen sind billiger als Hotels.',
      ornekTr: 'Gençlik hostelleri otellerden ucuzdur.',
      not: 'Almanya\'da öğrenci seyahatinin klasik konaklama biçimidir.',
    },
    {
      id: 'de-sey-50', on: 'die Ferienwohnung', okunus: 'di feeriınvoonung', tur: 'isim (dişil)',
      arka: 'tatil dairesi',
      ornek: 'Wir mieten eine Ferienwohnung am Meer.',
      ornekTr: 'Deniz kenarında bir tatil dairesi kiralıyoruz.',
      not: '"mieten" kiralamak, "vermieten" kiraya vermektir.',
    },
    /* --- Yol tarifi --- */
    {
      id: 'de-sey-51', on: 'Wie komme ich zu...?', okunus: 'vii komı ih tsu', tur: 'soru kalıbı',
      arka: '... nasıl giderim?',
      ornek: 'Wie komme ich zum Bahnhof?',
      ornekTr: 'Gara nasıl giderim?',
      not: '"zu" Dativ ister: zum Bahnhof, zur Post.',
    },
    {
      id: 'de-sey-52', on: 'die Kreuzung', okunus: 'di kroytsung', tur: 'isim (dişil)',
      arka: 'kavşak',
      ornek: 'An der Kreuzung rechts abbiegen.',
      ornekTr: 'Kavşaktan sağa dön.',
      not: '"abbiegen" = dönmek (yolda).',
    },
    {
      id: 'de-sey-53', on: 'die Ampel', okunus: 'di ampıl', tur: 'isim (dişil)',
      arka: 'trafik ışığı',
      ornek: 'Gehen Sie bis zur Ampel.',
      ornekTr: 'Trafik ışığına kadar gidin.',
      not: '"bis zu" = -e kadar; Dativ ister.',
    },
    {
      id: 'de-sey-54', on: 'gegenüber', okunus: 'geegınüübır', tur: 'edat',
      arka: 'karşısında',
      ornek: 'Die Bank ist gegenüber der Post.',
      ornekTr: 'Banka postanenin karşısında.',
      not: 'Dativ ister ve ismin arkasına da gelebilir.',
    },
    {
      id: 'de-sey-55', on: 'in der Nähe von', okunus: 'in der neeı fon', tur: 'kalıp',
      arka: '... yakınında',
      ornek: 'Das Hotel ist in der Nähe vom Museum.',
      ornekTr: 'Otel müzenin yakınında.',
      not: '"nah" yakın demektir; "die Nähe" yakınlık.',
    },
    {
      id: 'de-sey-56', on: 'entfernt', okunus: 'entfernt', tur: 'sıfat',
      arka: 'uzakta',
      ornek: 'Der Strand ist zwei Kilometer entfernt.',
      ornekTr: 'Plaj iki kilometre uzakta.',
      not: 'Mesafe önce, "entfernt" sonra gelir.',
    },
    {
      id: 'de-sey-57', on: 'um die Ecke', okunus: 'um di ekı', tur: 'kalıp',
      arka: 'köşeyi dönünce',
      ornek: 'Die Apotheke ist gleich um die Ecke.',
      ornekTr: 'Eczane hemen köşeyi dönünce.',
      not: '"gleich" burada "hemen" anlamındadır.',
    },
    {
      id: 'de-sey-58', on: 'der Fußgängerüberweg', okunus: 'der fuusgengırübırveek', tur: 'isim (eril)',
      arka: 'yaya geçidi',
      ornek: 'Benutze den Fußgängerüberweg.',
      ornekTr: 'Yaya geçidini kullan.',
      not: 'Günlük dilde "der Zebrastreifen" denir.',
    },
    {
      id: 'de-sey-59', on: 'der Stadtplan', okunus: 'der ştatplaan', tur: 'isim (eril)',
      arka: 'şehir haritası',
      ornek: 'Hast du einen Stadtplan dabei?',
      ornekTr: 'Yanında şehir haritası var mı?',
      not: '"die Karte" genel harita, "der Stadtplan" şehir planıdır.',
    },
    {
      id: 'de-sey-60', on: 'sich verfahren', okunus: 'zih ferfaarın', tur: 'fiil (dönüşlü)',
      arka: 'yolu şaşırmak (araçla)',
      ornek: 'Wir haben uns verfahren.',
      ornekTr: 'Yolu şaşırdık.',
      not: 'Yürürken kaybolmak "sich verlaufen"dır.',
    },
    /* --- Tatil ve gezi --- */
    {
      id: 'de-sey-61', on: 'der Urlaub', okunus: 'der uurlaup', tur: 'isim (eril)',
      arka: 'tatil (izin)',
      ornek: 'Wir fahren im Juli in den Urlaub.',
      ornekTr: 'Temmuzda tatile gidiyoruz.',
      not: 'Okul tatili "die Ferien"dir; ikisi farklıdır.',
    },
    {
      id: 'de-sey-62', on: 'die Sehenswürdigkeit', okunus: 'di zeeınsvürdihkayt', tur: 'isim (dişil)',
      arka: 'gezilecek yer, tarihî mekân',
      ornek: 'Die Stadt hat viele Sehenswürdigkeiten.',
      ornekTr: 'Şehirde gezilecek çok yer var.',
      not: 'Kelimesi kelimesine "görülmeye değer olan"dır.',
    },
    {
      id: 'de-sey-63', on: 'besichtigen', okunus: 'bızihtigın', tur: 'fiil',
      arka: 'gezmek, ziyaret etmek',
      ornek: 'Wir besichtigen morgen das Schloss.',
      ornekTr: 'Yarın sarayı gezeceğiz.',
      not: 'Kişiyi ziyaret için "besuchen" kullanılır.',
    },
    {
      id: 'de-sey-64', on: 'die Führung', okunus: 'di füürung', tur: 'isim (dişil)',
      arka: 'rehberli tur',
      ornek: 'Die Führung dauert eine Stunde.',
      ornekTr: 'Rehberli tur bir saat sürüyor.',
      not: '"führen" yönlendirmek, "der Führer" rehber demektir.',
    },
    {
      id: 'de-sey-65', on: 'der Eintritt', okunus: 'der ayntrit', tur: 'isim (eril)',
      arka: 'giriş ücreti',
      ornek: 'Der Eintritt ist für Schüler frei.',
      ornekTr: 'Giriş öğrenciler için ücretsiz.',
      not: '"frei" burada ücretsiz demektir.',
    },
    {
      id: 'de-sey-66', on: 'wandern', okunus: 'vandırn', tur: 'fiil',
      arka: 'doğa yürüyüşü yapmak',
      ornek: 'Im Sommer wandern wir in den Bergen.',
      ornekTr: 'Yazın dağlarda yürüyüş yapıyoruz.',
      not: 'Almanya\'da çok yaygın bir hafta sonu etkinliğidir.',
    },
    {
      id: 'de-sey-67', on: 'das Andenken', okunus: 'das andenkın', tur: 'isim (nötr)',
      arka: 'hatıra eşyası',
      ornek: 'Ich habe ein kleines Andenken gekauft.',
      ornekTr: 'Küçük bir hatıra eşyası aldım.',
      not: '"das Souvenir" de kullanılır.',
    },
    {
      id: 'de-sey-68', on: 'die Postkarte', okunus: 'di postkartı', tur: 'isim (dişil)',
      arka: 'kartpostal',
      ornek: 'Ich schicke dir eine Postkarte.',
      ornekTr: 'Sana bir kartpostal göndereceğim.',
      not: '"schicken" göndermek demektir.',
    },
    {
      id: 'de-sey-69', on: 'die Hauptsaison', okunus: 'di hauptzezoong', tur: 'isim (dişil)',
      arka: 'yoğun sezon',
      ornek: 'In der Hauptsaison ist alles teurer.',
      ornekTr: 'Yoğun sezonda her şey daha pahalı.',
      not: 'Sakin dönem "die Nebensaison"dur.',
    },
    {
      id: 'de-sey-70', on: 'die Reise planen', okunus: 'di rayzı plaanın', tur: 'kalıp',
      arka: 'seyahat planlamak',
      ornek: 'Wir planen die Reise seit Januar.',
      ornekTr: 'Seyahati ocaktan beri planlıyoruz.',
      not: '"seit" ile şimdiki zaman kullanılır, geçmiş değil.',
    },
    /* --- Sorunlar --- */
    {
      id: 'de-sey-71', on: 'verpassen', okunus: 'ferpasın', tur: 'fiil',
      arka: 'kaçırmak',
      ornek: 'Wir haben fast den Zug verpasst.',
      ornekTr: 'Neredeyse treni kaçırıyorduk.',
      not: '"fast" neredeyse demektir.',
    },
    {
      id: 'de-sey-72', on: 'das Fundbüro', okunus: 'das funtbüroo', tur: 'isim (nötr)',
      arka: 'kayıp eşya bürosu',
      ornek: 'Frag im Fundbüro nach deiner Tasche.',
      ornekTr: 'Çantanı kayıp eşya bürosuna sor.',
      not: '"finden" bulmak, "das Büro" ofis demektir.',
    },
    {
      id: 'de-sey-73', on: 'gestohlen werden', okunus: 'gıştoolın verdın', tur: 'kalıp',
      arka: 'çalınmak',
      ornek: 'Mein Handy ist gestohlen worden.',
      ornekTr: 'Telefonum çalındı.',
      not: '"stehlen" çalmak fiilinin edilgen hâlidir.',
    },
    {
      id: 'de-sey-74', on: 'die Versicherung', okunus: 'di ferzihırung', tur: 'isim (dişil)',
      arka: 'sigorta',
      ornek: 'Hast du eine Reiseversicherung?',
      ornekTr: 'Seyahat sigortan var mı?',
      not: '"sicher" güvenli demektir.',
    },
    {
      id: 'de-sey-75', on: 'der Notfall', okunus: 'der nootfal', tur: 'isim (eril)',
      arka: 'acil durum',
      ornek: 'Im Notfall ruf die 112.',
      ornekTr: 'Acil durumda 112\'yi ara.',
      not: 'Almanya\'da acil numara 112\'dir.',
    },
    {
      id: 'de-sey-76', on: 'sich beschweren', okunus: 'zih bışveerın', tur: 'fiil (dönüşlü)',
      arka: 'şikâyet etmek',
      ornek: 'Wir haben uns über den Lärm beschwert.',
      ornekTr: 'Gürültüden şikâyet ettik.',
      not: 'Konu edatı "über"dir ve Akkusativ ister.',
    },
    {
      id: 'de-sey-77', on: 'die Panne', okunus: 'di panı', tur: 'isim (dişil)',
      arka: 'arıza (araçta)',
      ornek: 'Wir hatten eine Panne auf der Autobahn.',
      ornekTr: 'Otoyolda arıza yaptık.',
      not: '"die Autobahn" Almanya\'nın ünlü otoyoludur.',
    },
    {
      id: 'de-sey-78', on: 'sich verspäten', okunus: 'zih ferşpeetın', tur: 'fiil (dönüşlü)',
      arka: 'gecikmek',
      ornek: 'Entschuldigung, ich habe mich verspätet.',
      ornekTr: 'Özür dilerim, geciktim.',
      not: 'Dönüşlü zamir zorunludur.',
    },
    {
      id: 'de-sey-79', on: 'die Auskunft', okunus: 'di auskunft', tur: 'isim (dişil)',
      arka: 'danışma, bilgi',
      ornek: 'Frag an der Auskunft nach dem Gleis.',
      ornekTr: 'Peronu danışmaya sor.',
      not: '"nach etwas fragen" = bir şeyi sormak.',
    },
    {
      id: 'de-sey-80', on: 'weiterhelfen', okunus: 'vaytırhelfın', tur: 'fiil (ayrılabilir)',
      arka: 'yardımcı olmak',
      ornek: 'Können Sie mir weiterhelfen?',
      ornekTr: 'Bana yardımcı olabilir misiniz?',
      not: 'Resmî ortamlarda çok kullanılan kibar bir ifadedir.',
      kok: 'helf',
    },
    /* --- Şehir ve mekân anlatmak --- */
    {
      id: 'de-sey-81', on: 'die Altstadt', okunus: 'di altştat', tur: 'isim (dişil)',
      arka: 'tarihî şehir merkezi',
      ornek: 'Die Altstadt ist wunderschön.',
      ornekTr: 'Tarihî merkez çok güzel.',
      not: 'Alman şehirlerinin klasik gezi noktasıdır.',
    },
    {
      id: 'de-sey-82', on: 'die Innenstadt', okunus: 'di inınştat', tur: 'isim (dişil)',
      arka: 'şehir merkezi',
      ornek: 'Wir wohnen in der Innenstadt.',
      ornekTr: 'Şehir merkezinde oturuyoruz.',
      not: '"innen" iç, "Stadt" şehir demektir.',
    },
    {
      id: 'de-sey-83', on: 'der Stadtrand', okunus: 'der ştatrant', tur: 'isim (eril)',
      arka: 'şehrin kenarı',
      ornek: 'Sie wohnen am Stadtrand.',
      ornekTr: 'Şehrin kenarında oturuyorlar.',
      not: '"der Rand" kenar demektir.',
    },
    {
      id: 'de-sey-84', on: 'überfüllt', okunus: 'übırfült', tur: 'sıfat',
      arka: 'aşırı kalabalık',
      ornek: 'Der Markt war völlig überfüllt.',
      ornekTr: 'Pazar tamamen tıklım tıklımdı.',
      not: '"füllen" doldurmak demektir; "über-" aşırılık katar.',
    },
    {
      id: 'de-sey-85', on: 'die Aussicht', okunus: 'di auszihtı', tur: 'isim (dişil)',
      arka: 'manzara',
      ornek: 'Das Zimmer hat eine schöne Aussicht.',
      ornekTr: 'Odanın güzel bir manzarası var.',
      not: '"die Landschaft" doğal peyzaj, "die Aussicht" bakınca görülendir.',
    },
    {
      id: 'de-sey-86', on: 'gemütlich', okunus: 'gımüütlih', tur: 'sıfat',
      arka: 'huzurlu, sıcak (ortam)',
      ornek: 'Das Café ist sehr gemütlich.',
      ornekTr: 'Kafe çok huzurlu.',
      not: 'Almancanın en tipik kelimelerindendir; tam Türkçe karşılığı yoktur.',
    },
    {
      id: 'de-sey-87', on: 'sich lohnen', okunus: 'zih loonın', tur: 'fiil (dönüşlü)',
      arka: 'değmek',
      ornek: 'Der Ausflug lohnt sich wirklich.',
      ornekTr: 'Gezi gerçekten değer.',
      not: '"der Ausflug" günübirlik gezi demektir.',
    },
    {
      id: 'de-sey-88', on: 'einen Ausflug machen', okunus: 'aynın ausfluuk mahın', tur: 'kalıp',
      arka: 'günübirlik geziye çıkmak',
      ornek: 'Am Sonntag machen wir einen Ausflug.',
      ornekTr: 'Pazar günü geziye çıkıyoruz.',
      not: 'Fiili "machen"dır.',
    },
    {
      id: 'de-sey-89', on: 'das Wetter', okunus: 'das vetır', tur: 'isim (nötr)',
      arka: 'hava durumu',
      ornek: 'Das Wetter war die ganze Woche gut.',
      ornekTr: 'Hava bütün hafta iyiydi.',
      not: 'Sayılamaz; "die Wetter" biçimi kullanılmaz.',
    },
    {
      id: 'de-sey-90', on: 'die Vorhersage', okunus: 'di forheerzaagı', tur: 'isim (dişil)',
      arka: 'tahmin (hava)',
      ornek: 'Die Vorhersage verspricht Sonne.',
      ornekTr: 'Tahmin güneşli hava vaat ediyor.',
      not: '"vorhersagen" = önceden söylemek.',
    },
    /* --- Yolculuk kalıpları --- */
    {
      id: 'de-sey-91', on: 'Gute Reise!', okunus: 'guutı rayzı', tur: 'kalıp',
      arka: 'İyi yolculuklar!',
      ornek: 'Gute Reise und melde dich!',
      ornekTr: 'İyi yolculuklar, haber ver!',
      not: '"sich melden" = haber vermek.',
    },
    {
      id: 'de-sey-92', on: 'Wo ist...?', okunus: 'voo ist', tur: 'soru kalıbı',
      arka: '... nerede?',
      ornek: 'Wo ist die nächste Bushaltestelle?',
      ornekTr: 'En yakın otobüs durağı nerede?',
      not: '"nächst" en yakın demektir.',
    },
    {
      id: 'de-sey-93', on: 'Können Sie mir helfen?', okunus: 'könın zii mir helfın', tur: 'kalıp',
      arka: 'Bana yardım edebilir misiniz?',
      ornek: 'Entschuldigung, können Sie mir helfen?',
      ornekTr: 'Affedersiniz, bana yardım edebilir misiniz?',
      not: '"helfen" Dativ ister: "mir helfen".',
    },
    {
      id: 'de-sey-94', on: 'Ich verstehe nicht', okunus: 'ih ferşteeı niht', tur: 'kalıp',
      arka: 'Anlamıyorum',
      ornek: 'Entschuldigung, ich verstehe nicht.',
      ornekTr: 'Affedersiniz, anlamıyorum.',
      not: 'Ardından "Können Sie das wiederholen?" denebilir.',
    },
    {
      id: 'de-sey-95', on: 'Sprechen Sie Englisch?', okunus: 'şprehın zii englirş', tur: 'soru kalıbı',
      arka: 'İngilizce biliyor musunuz?',
      ornek: 'Entschuldigung, sprechen Sie Englisch?',
      ornekTr: 'Affedersiniz, İngilizce biliyor musunuz?',
      not: 'Dil adları büyük harfle yazılır.',
    },
    {
      id: 'de-sey-96', on: 'Wie lange dauert es?', okunus: 'vii langı dauırt es', tur: 'soru kalıbı',
      arka: 'Ne kadar sürüyor?',
      ornek: 'Wie lange dauert die Fahrt?',
      ornekTr: 'Yolculuk ne kadar sürüyor?',
      not: '"dauern" sürmek demektir.',
    },
    {
      id: 'de-sey-97', on: 'Ist dieser Platz frei?', okunus: 'ist diizır plats fray', tur: 'soru kalıbı',
      arka: 'Bu yer boş mu?',
      ornek: 'Entschuldigung, ist dieser Platz frei?',
      ornekTr: 'Affedersiniz, bu yer boş mu?',
      not: 'Trende ve kafede en çok kullanılan sorulardandır.',
    },
    {
      id: 'de-sey-98', on: 'Ich hätte gern...', okunus: 'ih hetı gern', tur: 'kalıp',
      arka: '... istiyorum (kibar)',
      ornek: 'Ich hätte gern eine Fahrkarte nach Köln.',
      ornekTr: 'Köln\'e bir bilet istiyorum.',
      not: 'Gişede ve restoranda en kibar istek biçimidir.',
    },
    {
      id: 'de-sey-99', on: 'einfach oder hin und zurück', okunus: 'aynfah oodır hin unt tsurük', tur: 'kalıp',
      arka: 'tek yön mü gidiş-dönüş mü',
      ornek: 'Einfach oder hin und zurück? - Hin und zurück, bitte.',
      ornekTr: 'Tek yön mü gidiş-dönüş mü? - Gidiş-dönüş lütfen.',
      not: 'Bilet gişesinde sorulan standart sorudur.',
    },
    {
      id: 'de-sey-100', on: 'Andere Länder, andere Sitten', okunus: 'andırı lendır andırı zitın', tur: 'atasözü',
      arka: 'Her yerin âdeti başka',
      ornek: 'In Deutschland isst man früh: andere Länder, andere Sitten.',
      ornekTr: 'Almanya\'da erken yenir: her yerin âdeti başka.',
      not: 'Kültür farkını anlatmanın en klasik Almanca yoludur.',
    },
  ],
}

export default DESTE
