/**
 * DESTE — YEMEK VE TATLAR (Almanca)
 *
 * Almanya'da yaşayan ya da gidecek olan bir öğrencinin ilk haftasında
 * lazım olacak kelimeler. "Türkçedeki döner Almancada da döner" gibi
 * kolaylıklar da not olarak gösterildi.
 */

export const DESTE = {
  id: 'yemek',
  dil: 'de',
  ad: 'Yemek ve tatlar',
  simge: '🥨',
  aciklama: 'Fırında, markette ve sofrada geçen kelimeler.',
  seviye: 'A1–A2',
  kartlar: [
    {
      id: 'de-yem-01', on: 'das Frühstück', okunus: 'das früştük', tur: 'isim (nötr)',
      arka: 'kahvaltı',
      ornek: 'Ich mache jeden Morgen ein großes Frühstück.',
      ornekTr: 'Her sabah büyük bir kahvaltı hazırlıyorum.',
      not: 'Kahvaltı yapmak "frühstücken" tek fiiliyle de söylenir.',
    },
    {
      id: 'de-yem-02', on: 'das Brot', okunus: 'das broot', tur: 'isim (nötr)',
      arka: 'ekmek',
      ornek: 'Ich kaufe jeden Tag frisches Brot.',
      ornekTr: 'Her gün taze ekmek alıyorum.',
      not: 'Almanya\'da yüzlerce ekmek çeşidi vardır; "die Bäckerei" fırındır.',
    },
    {
      id: 'de-yem-03', on: 'Hunger haben', okunus: 'hungır haabın', tur: 'kalıp',
      arka: 'acıkmak, aç olmak',
      ornek: 'Ich habe Hunger, essen wir etwas?',
      ornekTr: 'Acıktım, bir şeyler yiyelim mi?',
      not: '"Ich bin hungrig" de doğrudur ama "Hunger haben" daha yaygındır.',
    },
    {
      id: 'de-yem-04', on: 'lecker', okunus: 'lekır', tur: 'sıfat',
      arka: 'lezzetli',
      ornek: 'Der Kuchen ist wirklich lecker!',
      ornekTr: 'Pasta gerçekten lezzetli!',
      not: 'Tek başına ünlem olarak da kullanılır: "Lecker!"',
    },
    {
      id: 'de-yem-05', on: 'die Rechnung', okunus: 'di rehnung', tur: 'isim (dişil)',
      arka: 'hesap (restoranda)',
      ornek: 'Die Rechnung, bitte!',
      ornekTr: 'Hesap, lütfen!',
      not: '"rechnen" (hesaplamak) fiilinden gelir.',
    },
    {
      id: 'de-yem-06', on: 'bestellen', okunus: 'beştelın', tur: 'fiil',
      arka: 'sipariş vermek',
      ornek: 'Was möchtest du bestellen?',
      ornekTr: 'Ne sipariş etmek istersin?',
      not: 'Kibar istek "Ich möchte…" ile kurulur; "Ich will" sert durur.',
    },
    {
      id: 'de-yem-07', on: 'probieren', okunus: 'probiirın', tur: 'fiil',
      arka: 'tatmak, denemek',
      ornek: 'Möchtest du mein Eis probieren?',
      ornekTr: 'Dondurmamı tatmak ister misin?',
      not: 'Dondurma "das Eis"tır ve aynı zamanda "buz" demektir.',
    },
    {
      id: 'de-yem-08', on: 'zum Mitnehmen', okunus: 'tsum mitneemın', tur: 'kalıp',
      arka: 'paket, götürmek için',
      ornek: 'Einen Kaffee zum Mitnehmen, bitte.',
      ornekTr: 'Bir kahve paket, lütfen.',
      not: 'Karşıtı "zum Hier-Essen" (burada yemek için).',
    },
    {
      id: 'de-yem-09', on: 'Durst haben', okunus: 'durst haabın', tur: 'kalıp',
      arka: 'susamak',
      ornek: 'Ich habe Durst, ich trinke ein Wasser.',
      ornekTr: 'Susadım, bir su içeceğim.',
      not: '"Hunger haben" ile aynı mantık: susuzluğa da sahip olunur.',
    },
    {
      id: 'de-yem-10', on: 'Guten Appetit', okunus: 'gutın apetiit', tur: 'kalıp',
      arka: 'afiyet olsun',
      ornek: 'Guten Appetit, lass es dir schmecken!',
      ornekTr: 'Afiyet olsun, yemeğin tadını çıkar!',
      not: 'Sofraya oturulduğunda söylenmesi neredeyse zorunludur.',
    },
    /* --- Temel yiyecekler --- */
    {
      id: 'de-yem-11', on: 'das Brötchen', okunus: 'das bröötçın', tur: 'isim (nötr)',
      arka: 'küçük ekmek, sandviç ekmeği',
      ornek: 'Zum Frühstück esse ich zwei Brötchen.',
      ornekTr: 'Kahvaltıda iki küçük ekmek yiyorum.',
      not: '"-chen" küçültme ekidir ve eklendiği kelimeyi nötr yapar.',
    },
    {
      id: 'de-yem-12', on: 'die Butter', okunus: 'di butır', tur: 'isim (dişil)',
      arka: 'tereyağı',
      ornek: 'Bitte gib mir die Butter.',
      ornekTr: 'Lütfen tereyağını uzat.',
      not: 'Sayılamayan bir isimdir, çoğulu kullanılmaz.',
    },
    {
      id: 'de-yem-13', on: 'der Käse', okunus: 'der keezı', tur: 'isim (eril)',
      arka: 'peynir',
      ornek: 'Der Käse schmeckt sehr gut.',
      ornekTr: 'Peynirin tadı çok güzel.',
      not: '"schmecken" = tadı olmak; yemek için en doğal fiildir.',
    },
    {
      id: 'de-yem-14', on: 'die Wurst', okunus: 'di vurst', tur: 'isim (dişil)',
      arka: 'sosis, sucuk',
      ornek: 'In Deutschland gibt es hunderte Wurstsorten.',
      ornekTr: 'Almanya\'da yüzlerce sosis çeşidi var.',
      not: 'Çoğulu "die Würste"dir; Alman mutfağının simgesidir.',
    },
    {
      id: 'de-yem-15', on: 'das Ei', okunus: 'das ay', tur: 'isim (nötr)',
      arka: 'yumurta',
      ornek: 'Ich esse jeden Morgen ein Ei.',
      ornekTr: 'Her sabah bir yumurta yiyorum.',
      not: 'Çoğulu "die Eier"dir.',
    },
    {
      id: 'de-yem-16', on: 'das Gemüse', okunus: 'das gımüüzı', tur: 'isim (nötr)',
      arka: 'sebze',
      ornek: 'Iss mehr Gemüse!',
      ornekTr: 'Daha çok sebze ye!',
      not: 'Topluluk ismidir, tekil kullanılır: "Gemüse ist gesund."',
    },
    {
      id: 'de-yem-17', on: 'das Obst', okunus: 'das oopst', tur: 'isim (nötr)',
      arka: 'meyve',
      ornek: 'Obst ist besser als Süßigkeiten.',
      ornekTr: 'Meyve şekerlemelerden iyidir.',
      not: 'Sayılamaz. Tek meyve için "die Frucht" kullanılır.',
    },
    {
      id: 'de-yem-18', on: 'die Kartoffel', okunus: 'di kartofıl', tur: 'isim (dişil)',
      arka: 'patates',
      ornek: 'Kartoffeln gehören zur deutschen Küche.',
      ornekTr: 'Patates Alman mutfağının parçasıdır.',
      not: '"gehören zu" = bir şeye ait olmak.',
    },
    {
      id: 'de-yem-19', on: 'die Nudeln', okunus: 'di nuudıln', tur: 'isim (çoğul)',
      arka: 'makarna',
      ornek: 'Wir kochen heute Nudeln mit Soße.',
      ornekTr: 'Bugün soslu makarna yapıyoruz.',
      not: 'Çoğul kullanılır; tekil "die Nudel" tek bir makarnadır.',
    },
    {
      id: 'de-yem-20', on: 'die Suppe', okunus: 'di zupı', tur: 'isim (dişil)',
      arka: 'çorba',
      ornek: 'Die Suppe ist noch zu heiß.',
      ornekTr: 'Çorba hâlâ çok sıcak.',
      not: 'Çorba "essen" ile yenir, "trinken" ile içilmez.',
    },
    /* --- Pişirme --- */
    {
      id: 'de-yem-21', on: 'kochen', okunus: 'kohın', tur: 'fiil',
      arka: 'yemek pişirmek; kaynatmak',
      ornek: 'Meine Mutter kocht sehr gut.',
      ornekTr: 'Annem çok iyi yemek yapar.',
      not: 'Hem genel pişirme hem suda kaynatma anlamına gelir.',
    },
    {
      id: 'de-yem-22', on: 'backen', okunus: 'bakın', tur: 'fiil',
      arka: 'fırında pişirmek',
      ornek: 'Wir backen einen Kuchen.',
      ornekTr: 'Bir kek yapıyoruz.',
      not: 'Hamur işleri için kullanılır; fırın "der Backofen"dır.',
    },
    {
      id: 'de-yem-23', on: 'braten', okunus: 'braatın', tur: 'fiil (kuvvetli)',
      arka: 'kızartmak (tavada)',
      ornek: 'Brate das Fleisch fünf Minuten.',
      ornekTr: 'Eti beş dakika kızart.',
      not: 'Çekimi: brät · hat gebraten.',
    },
    {
      id: 'de-yem-24', on: 'schneiden', okunus: 'şnaydın', tur: 'fiil (kuvvetli)',
      arka: 'kesmek, doğramak',
      ornek: 'Schneide die Zwiebel klein.',
      ornekTr: 'Soğanı küçük doğra.',
      not: 'Çekimi: schneidet · hat geschnitten.',
    },
    {
      id: 'de-yem-25', on: 'schälen', okunus: 'şeelın', tur: 'fiil',
      arka: 'soymak',
      ornek: 'Schäle bitte die Kartoffeln.',
      ornekTr: 'Lütfen patatesleri soy.',
      not: '"die Schale" kabuk demektir.',
    },
    {
      id: 'de-yem-26', on: 'rühren', okunus: 'rüürın', tur: 'fiil',
      arka: 'karıştırmak (kaşıkla)',
      ornek: 'Rühre die Soße langsam.',
      ornekTr: 'Sosu yavaşça karıştır.',
      not: 'Çırpma yumurta "das Rührei"dir.',
    },
    {
      id: 'de-yem-27', on: 'würzen', okunus: 'vürtsın', tur: 'fiil',
      arka: 'baharatlamak',
      ornek: 'Würze das Essen mit Salz und Pfeffer.',
      ornekTr: 'Yemeği tuz ve karabiberle baharatla.',
      not: '"das Gewürz" baharat demektir.',
    },
    {
      id: 'de-yem-28', on: 'das Rezept', okunus: 'das retsept', tur: 'isim (nötr)',
      arka: 'tarif; reçete',
      ornek: 'Ich habe das Rezept von meiner Oma.',
      ornekTr: 'Tarifi babaannemden aldım.',
      not: 'Doktor reçetesi için de aynı kelime kullanılır.',
    },
    {
      id: 'de-yem-29', on: 'die Zutat', okunus: 'di tsuutaat', tur: 'isim (dişil)',
      arka: 'malzeme',
      ornek: 'Man braucht nur fünf Zutaten.',
      ornekTr: 'Sadece beş malzeme gerekiyor.',
      not: '"man braucht" = gerekir, insan ihtiyaç duyar.',
    },
    {
      id: 'de-yem-30', on: 'der Herd', okunus: 'der heert', tur: 'isim (eril)',
      arka: 'ocak',
      ornek: 'Der Herd ist noch heiß.',
      ornekTr: 'Ocak hâlâ sıcak.',
      not: 'Buzdolabı "der Kühlschrank"tır.',
    },
    /* --- Tat ve doku --- */
    {
      id: 'de-yem-31', on: 'süß', okunus: 'züüs', tur: 'sıfat',
      arka: 'tatlı',
      ornek: 'Der Tee ist mir zu süß.',
      ornekTr: 'Çay bana fazla tatlı.',
      not: 'İnsan için "sevimli, şirin" anlamına da gelir.',
    },
    {
      id: 'de-yem-32', on: 'salzig', okunus: 'zaltsih', tur: 'sıfat',
      arka: 'tuzlu',
      ornek: 'Die Suppe ist zu salzig.',
      ornekTr: 'Çorba fazla tuzlu.',
      not: '"das Salz" tuz demektir.',
    },
    {
      id: 'de-yem-33', on: 'sauer', okunus: 'zauır', tur: 'sıfat',
      arka: 'ekşi; kızgın',
      ornek: 'Die Zitrone ist sehr sauer.',
      ornekTr: 'Limon çok ekşi.',
      not: 'İnsan için "sauer sein" kızgın olmak demektir.',
    },
    {
      id: 'de-yem-34', on: 'scharf', okunus: 'şarf', tur: 'sıfat',
      arka: 'acı (baharatlı); keskin',
      ornek: 'Ich mag es nicht so scharf.',
      ornekTr: 'Çok acı sevmiyorum.',
      not: 'Bıçak için "keskin" anlamına da gelir.',
    },
    {
      id: 'de-yem-35', on: 'bitter', okunus: 'bitır', tur: 'sıfat',
      arka: 'acı (kahve gibi)',
      ornek: 'Schwarzer Kaffee ist bitter.',
      ornekTr: 'Sade kahve acıdır.',
      not: 'Biberin acısı "scharf", kahvenin acısı "bitter"dır.',
    },
    {
      id: 'de-yem-36', on: 'frisch', okunus: 'friş', tur: 'sıfat',
      arka: 'taze',
      ornek: 'Das Brot ist ganz frisch.',
      ornekTr: 'Ekmek çok taze.',
      not: 'Bayat "altbacken" ya da "nicht mehr frisch"tir.',
    },
    {
      id: 'de-yem-37', on: 'knusprig', okunus: 'knusprih', tur: 'sıfat',
      arka: 'çıtır çıtır',
      ornek: 'Die Kruste ist schön knusprig.',
      ornekTr: 'Kabuğu güzelce çıtır çıtır.',
      not: '"die Kruste" = ekmek kabuğu.',
    },
    {
      id: 'de-yem-38', on: 'fettig', okunus: 'fetih', tur: 'sıfat',
      arka: 'yağlı',
      ornek: 'Das Essen war mir zu fettig.',
      ornekTr: 'Yemek bana fazla yağlı geldi.',
      not: '"das Fett" yağ demektir.',
    },
    {
      id: 'de-yem-39', on: 'roh', okunus: 'roo', tur: 'sıfat',
      arka: 'çiğ',
      ornek: 'Rohes Hähnchen darf man nicht essen.',
      ornekTr: 'Çiğ tavuk yenmez.',
      not: '"dürfen" burada izin/yasak bildirir.',
    },
    {
      id: 'de-yem-40', on: 'schmecken', okunus: 'şmekın', tur: 'fiil (Dativ)',
      arka: 'tadı gelmek, lezzetli gelmek',
      ornek: 'Das Essen schmeckt mir sehr gut.',
      ornekTr: 'Yemek çok hoşuma gidiyor.',
      not: '"gefallen" gibi çalışır: kişi Dativ, yemek özne olur.',
    },
    /* --- Öğünler --- */
    {
      id: 'de-yem-41', on: 'das Mittagessen', okunus: 'das mitaakesın', tur: 'isim (nötr)',
      arka: 'öğle yemeği',
      ornek: 'Das Mittagessen gibt es um eins.',
      ornekTr: 'Öğle yemeği saat birde.',
      not: 'Almanya\'da sıcak yemek genellikle öğlendir.',
    },
    {
      id: 'de-yem-42', on: 'das Abendessen', okunus: 'das aabıntesın', tur: 'isim (nötr)',
      arka: 'akşam yemeği',
      ornek: 'Zum Abendessen essen wir oft Brot und Käse.',
      ornekTr: 'Akşam yemeğinde sık sık ekmek ve peynir yiyoruz.',
      not: 'Almanya\'da akşam yemeği soğuk olabilir: "das Abendbrot".',
    },
    {
      id: 'de-yem-43', on: 'satt sein', okunus: 'zat zayn', tur: 'kalıp',
      arka: 'doymuş olmak',
      ornek: 'Danke, ich bin satt.',
      ornekTr: 'Teşekkürler, doydum.',
      not: 'Karşıtı "Hunger haben" = acıkmış olmak.',
    },
    {
      id: 'de-yem-44', on: 'der Appetit', okunus: 'der apetiit', tur: 'isim (eril)',
      arka: 'iştah',
      ornek: 'Ich habe heute keinen Appetit.',
      ornekTr: 'Bugün iştahım yok.',
      not: '"Guten Appetit!" sofrada söylenen kalıptır.',
    },
    {
      id: 'de-yem-45', on: 'die Zwischenmahlzeit', okunus: 'di tsvişınmaaltsayt', tur: 'isim (dişil)',
      arka: 'ara öğün, atıştırmalık',
      ornek: 'Ein Apfel ist eine gute Zwischenmahlzeit.',
      ornekTr: 'Elma iyi bir ara öğündür.',
      not: '"zwischen" arasında, "Mahlzeit" öğün demektir.',
    },
    {
      id: 'de-yem-46', on: 'die Reste', okunus: 'di restı', tur: 'isim (çoğul)',
      arka: 'artan yemek',
      ornek: 'Die Reste essen wir morgen.',
      ornekTr: 'Artanları yarın yeriz.',
      not: 'Tekili "der Rest" = kalan, geriye kalan.',
    },
    {
      id: 'de-yem-47', on: 'selbst gemacht', okunus: 'zelpst gımaht', tur: 'kalıp',
      arka: 'ev yapımı',
      ornek: 'Die Marmelade ist selbst gemacht.',
      ornekTr: 'Reçel ev yapımı.',
      not: '"selbst" kendi demektir; "hausgemacht" da kullanılır.',
    },
    {
      id: 'de-yem-48', on: 'auslassen', okunus: 'auslasın', tur: 'fiil (ayrılabilir)',
      arka: 'atlamak (öğün)',
      ornek: 'Lass das Frühstück nicht aus.',
      ornekTr: 'Kahvaltıyı atlama.',
      not: 'Ayrılabilir fiildir: "lass ... aus".',
      kok: 'lass',
    },
    {
      id: 'de-yem-49', on: 'naschen', okunus: 'naşın', tur: 'fiil',
      arka: 'tatlı atıştırmak',
      ornek: 'Er nascht gern Schokolade.',
      ornekTr: 'Çikolata atıştırmayı seviyor.',
      not: 'Sadece tatlılar için kullanılır.',
    },
    {
      id: 'de-yem-50', on: 'der Nachtisch', okunus: 'der naahtiş', tur: 'isim (eril)',
      arka: 'tatlı (yemek sonrası)',
      ornek: 'Zum Nachtisch gibt es Eis.',
      ornekTr: 'Tatlı olarak dondurma var.',
      not: 'Kelimesi kelimesine "masadan sonra" demektir.',
    },
    /* --- Restoran --- */
    {
      id: 'de-yem-51', on: 'die Speisekarte', okunus: 'di şpayzıkartı', tur: 'isim (dişil)',
      arka: 'menü',
      ornek: 'Können wir die Speisekarte haben?',
      ornekTr: 'Menüyü alabilir miyiz?',
      not: '"die Speise" yemek demektir.',
    },
    {
      id: 'de-yem-52', on: 'die Vorspeise', okunus: 'di forşpayzı', tur: 'isim (dişil)',
      arka: 'başlangıç yemeği',
      ornek: 'Als Vorspeise nehme ich Suppe.',
      ornekTr: 'Başlangıç olarak çorba alıyorum.',
      not: 'Ana yemek "das Hauptgericht"tir.',
    },
    {
      id: 'de-yem-53', on: 'das Hauptgericht', okunus: 'das hauptgıriht', tur: 'isim (nötr)',
      arka: 'ana yemek',
      ornek: 'Das Hauptgericht kommt gleich.',
      ornekTr: 'Ana yemek birazdan geliyor.',
      not: '"das Gericht" yemek ve mahkeme anlamına gelir.',
    },
    {
      id: 'de-yem-54', on: 'die Beilage', okunus: 'di baylaagı', tur: 'isim (dişil)',
      arka: 'garnitür',
      ornek: 'Als Beilage gibt es Reis oder Salat.',
      ornekTr: 'Garnitür olarak pilav ya da salata var.',
      not: '"bei" yanında, "legen" koymak demektir.',
    },
    {
      id: 'de-yem-55', on: 'reservieren', okunus: 'rezerviirın', tur: 'fiil',
      arka: 'rezervasyon yaptırmak',
      ornek: 'Ich möchte einen Tisch reservieren.',
      ornekTr: 'Bir masa ayırtmak istiyorum.',
      not: '"möchte" kibar istek bildirir.',
    },
    {
      id: 'de-yem-56', on: 'das Trinkgeld', okunus: 'das trinkgelt', tur: 'isim (nötr)',
      arka: 'bahşiş',
      ornek: 'Wir haben zwei Euro Trinkgeld gegeben.',
      ornekTr: 'İki avro bahşiş bıraktık.',
      not: 'Kelimesi kelimesine "içki parası" demektir.',
    },
    {
      id: 'de-yem-57', on: 'getrennt zahlen', okunus: 'gıtrent tsaalın', tur: 'kalıp',
      arka: 'ayrı ayrı ödemek',
      ornek: 'Wir möchten getrennt zahlen.',
      ornekTr: 'Ayrı ayrı ödemek istiyoruz.',
      not: 'Almanya\'da garson "Zusammen oder getrennt?" diye sorar.',
    },
    {
      id: 'de-yem-58', on: 'die Bedienung', okunus: 'di bıdiinung', tur: 'isim (dişil)',
      arka: 'servis; garson',
      ornek: 'Die Bedienung war sehr freundlich.',
      ornekTr: 'Servis çok güler yüzlüydü.',
      not: '"bedienen" hizmet etmek demektir.',
    },
    {
      id: 'de-yem-59', on: 'die Portion', okunus: 'di portsyoon', tur: 'isim (dişil)',
      arka: 'porsiyon',
      ornek: 'Die Portionen sind hier riesig.',
      ornekTr: 'Buradaki porsiyonlar kocaman.',
      not: '"riesig" devasa demektir.',
    },
    {
      id: 'de-yem-60', on: 'die Bestellung', okunus: 'di bıştelung', tur: 'isim (dişil)',
      arka: 'sipariş',
      ornek: 'Ihre Bestellung kommt in fünf Minuten.',
      ornekTr: 'Siparişiniz beş dakikaya geliyor.',
      not: 'Fiili "bestellen"dir.',
    },
    /* --- Alışveriş --- */
    {
      id: 'de-yem-61', on: 'der Supermarkt', okunus: 'der zuupırmarkt', tur: 'isim (eril)',
      arka: 'süpermarket',
      ornek: 'Der Supermarkt schließt um acht.',
      ornekTr: 'Süpermarket sekizde kapanıyor.',
      not: 'Almanya\'da pazar günleri marketler kapalıdır.',
    },
    {
      id: 'de-yem-62', on: 'die Bäckerei', okunus: 'di bekıray', tur: 'isim (dişil)',
      arka: 'fırın, ekmekçi',
      ornek: 'Ich hole Brötchen aus der Bäckerei.',
      ornekTr: 'Fırından ekmek alıyorum.',
      not: '"-erei" eki iş yeri bildirir: Metzgerei, Konditorei.',
    },
    {
      id: 'de-yem-63', on: 'die Metzgerei', okunus: 'di metsgıray', tur: 'isim (dişil)',
      arka: 'kasap',
      ornek: 'Das Fleisch kaufen wir in der Metzgerei.',
      ornekTr: 'Eti kasaptan alıyoruz.',
      not: 'Kuzey Almanya\'da "die Fleischerei" denir.',
    },
    {
      id: 'de-yem-64', on: 'das Angebot', okunus: 'das angıboot', tur: 'isim (nötr)',
      arka: 'indirim, kampanya',
      ornek: 'Heute ist Käse im Angebot.',
      ornekTr: 'Bugün peynir indirimde.',
      not: '"anbieten" sunmak demektir.',
    },
    {
      id: 'de-yem-65', on: 'das Mindesthaltbarkeitsdatum', okunus: 'das mindesthaltbarkaytsdaatum', tur: 'isim (nötr)',
      arka: 'son tüketim tarihi',
      ornek: 'Schau auf das Mindesthaltbarkeitsdatum.',
      ornekTr: 'Son tüketim tarihine bak.',
      not: 'Kısaltması "MHD"dir; Almancanın en uzun günlük kelimelerindendir.',
    },
    {
      id: 'de-yem-66', on: 'die Tüte', okunus: 'di tüütı', tur: 'isim (dişil)',
      arka: 'poşet',
      ornek: 'Brauchen Sie eine Tüte?',
      ornekTr: 'Poşet ister misiniz?',
      not: 'Almanya\'da poşet çoğunlukla ücretlidir.',
    },
    {
      id: 'de-yem-67', on: 'der Einkaufszettel', okunus: 'der aynkaufstsetıl', tur: 'isim (eril)',
      arka: 'alışveriş listesi',
      ornek: 'Ich schreibe einen Einkaufszettel.',
      ornekTr: 'Bir alışveriş listesi yazıyorum.',
      not: '"der Zettel" küçük kâğıt demektir.',
    },
    {
      id: 'de-yem-68', on: 'ausgehen', okunus: 'ausgeeın', tur: 'fiil (ayrılabilir)',
      arka: 'tükenmek; dışarı çıkmak',
      ornek: 'Uns geht die Milch aus.',
      ornekTr: 'Sütümüz tükeniyor.',
      not: 'Ayrılabilir fiildir: "geht ... aus".',
      kok: 'geh',
    },
    {
      id: 'de-yem-69', on: 'haltbar', okunus: 'haltbaar', tur: 'sıfat',
      arka: 'dayanıklı, bozulmayan',
      ornek: 'Die Konserve ist zwei Jahre haltbar.',
      ornekTr: 'Konserve iki yıl dayanır.',
      not: '"halten" tutmak, dayanmak demektir.',
    },
    {
      id: 'de-yem-70', on: 'schlecht werden', okunus: 'şleht verdın', tur: 'kalıp',
      arka: 'bozulmak',
      ornek: 'Die Milch ist schlecht geworden.',
      ornekTr: 'Süt bozulmuş.',
      not: '"werden" burada durum değişimini anlatır.',
    },
    /* --- Sağlık ve beslenme --- */
    {
      id: 'de-yem-71', on: 'gesund', okunus: 'gızunt', tur: 'sıfat',
      arka: 'sağlıklı',
      ornek: 'Gemüse ist gesund.',
      ornekTr: 'Sebze sağlıklıdır.',
      not: 'Karşıtı "ungesund"dur.',
    },
    {
      id: 'de-yem-72', on: 'die Ernährung', okunus: 'di ernerung', tur: 'isim (dişil)',
      arka: 'beslenme',
      ornek: 'Eine gute Ernährung ist wichtig.',
      ornekTr: 'İyi beslenme önemlidir.',
      not: '"sich ernähren" = beslenmek.',
    },
    {
      id: 'de-yem-73', on: 'vegetarisch', okunus: 'vegetaariş', tur: 'sıfat',
      arka: 'vejetaryen',
      ornek: 'Haben Sie vegetarische Gerichte?',
      ornekTr: 'Vejetaryen yemekleriniz var mı?',
      not: 'Tamamen hayvansız beslenen kişi "vegan"dır.',
    },
    {
      id: 'de-yem-74', on: 'die Allergie', okunus: 'di alergii', tur: 'isim (dişil)',
      arka: 'alerji',
      ornek: 'Ich habe eine Allergie gegen Nüsse.',
      ornekTr: 'Fındık alerjim var.',
      not: 'Edatı "gegen"dir ve Akkusativ ister.',
    },
    {
      id: 'de-yem-75', on: 'abnehmen', okunus: 'apneemın', tur: 'fiil (ayrılabilir)',
      arka: 'kilo vermek',
      ornek: 'Er hat fünf Kilo abgenommen.',
      ornekTr: 'Beş kilo verdi.',
      not: 'Tersi "zunehmen" = kilo almak. Telefonu açmak anlamı da vardır.',
      kok: 'genommen',
    },
    {
      id: 'de-yem-76', on: 'verzichten auf', okunus: 'fertsihtın auf', tur: 'fiil',
      arka: 'vazgeçmek, bırakmak',
      ornek: 'Ich verzichte auf Zucker.',
      ornekTr: 'Şekerden vazgeçiyorum.',
      not: 'Edatı "auf"tur ve Akkusativ ister.',
    },
    {
      id: 'de-yem-77', on: 'die Kalorien', okunus: 'di kaloriyın', tur: 'isim (çoğul)',
      arka: 'kaloriler',
      ornek: 'Diese Pizza hat viele Kalorien.',
      ornekTr: 'Bu pizzanın kalorisi yüksek.',
      not: 'Tekili "die Kalorie"dir.',
    },
    {
      id: 'de-yem-78', on: 'genug trinken', okunus: 'gınuuk trinkın', tur: 'kalıp',
      arka: 'yeterince su içmek',
      ornek: 'Du musst genug trinken.',
      ornekTr: 'Yeterince su içmelisin.',
      not: 'Almancada "su içmek" için sadece "trinken" yeter.',
    },
    {
      id: 'de-yem-79', on: 'die Ballaststoffe', okunus: 'di balastştofı', tur: 'isim (çoğul)',
      arka: 'lif',
      ornek: 'Vollkornbrot enthält viele Ballaststoffe.',
      ornekTr: 'Tam tahıllı ekmek çok lif içerir.',
      not: '"enthalten" = içermek.',
    },
    {
      id: 'de-yem-80', on: 'in Maßen', okunus: 'in maasın', tur: 'kalıp',
      arka: 'ölçülü biçimde',
      ornek: 'Süßigkeiten sind in Maßen okay.',
      ornekTr: 'Şekerlemeler ölçülü olursa sorun değil.',
      not: '"in Massen" (kitleler hâlinde) ile karıştırma; uzun "a" ölçüyü anlatır.',
    },
    /* --- Mutfak kültürü --- */
    {
      id: 'de-yem-81', on: 'die Küche', okunus: 'di kühı', tur: 'isim (dişil)',
      arka: 'mutfak; mutfak kültürü',
      ornek: 'Die türkische Küche ist sehr vielfältig.',
      ornekTr: 'Türk mutfağı çok çeşitlidir.',
      not: '"vielfältig" = çeşitli, zengin.',
    },
    {
      id: 'de-yem-82', on: 'die Spezialität', okunus: 'di şpetsyaliteet', tur: 'isim (dişil)',
      arka: 'yöresel özel yemek',
      ornek: 'Baklava ist eine türkische Spezialität.',
      ornekTr: 'Baklava bir Türk lezzetidir.',
      not: 'Vurgu son hecededir: Speziali-TÄT.',
    },
    {
      id: 'de-yem-83', on: 'gefüllt', okunus: 'gıfült', tur: 'sıfat',
      arka: 'doldurulmuş, dolma',
      ornek: 'Gefüllte Paprika ist ein klassisches Gericht.',
      ornekTr: 'Biber dolması klasik bir yemektir.',
      not: '"füllen" doldurmak demektir.',
    },
    {
      id: 'de-yem-84', on: 'das Hackfleisch', okunus: 'das hakflayş', tur: 'isim (nötr)',
      arka: 'kıyma',
      ornek: 'Für die Füllung braucht man Hackfleisch.',
      ornekTr: 'İç harcı için kıyma gerekir.',
      not: '"hacken" doğramak demektir.',
    },
    {
      id: 'de-yem-85', on: 'der Teig', okunus: 'der tayk', tur: 'isim (eril)',
      arka: 'hamur',
      ornek: 'Der Teig muss dünn sein.',
      ornekTr: 'Hamur ince olmalı.',
      not: 'Börek anlatırken en gerekli kelimedir.',
    },
    {
      id: 'de-yem-86', on: 'berühmt für', okunus: 'bırüümt füür', tur: 'kalıp',
      arka: 'bir şeyle ünlü',
      ornek: 'Gaziantep ist berühmt für Baklava.',
      ornekTr: 'Gaziantep baklavasıyla ünlüdür.',
      not: 'Edatı "für"dür ve Akkusativ ister.',
    },
    {
      id: 'de-yem-87', on: 'serviert werden mit', okunus: 'zerviirt verdın mit', tur: 'kalıp',
      arka: 'yanında ... ile servis edilmek',
      ornek: 'Das Gericht wird mit Reis serviert.',
      ornekTr: 'Yemek pilavla servis edilir.',
      not: 'Edilgen çatı: "werden + Partizip".',
    },
    {
      id: 'de-yem-88', on: 'Es schmeckt wie...', okunus: 'es şmekt vii', tur: 'kalıp',
      arka: 'Tadı ... gibi',
      ornek: 'Es schmeckt wie eine dünne Pizza.',
      ornekTr: 'Tadı ince bir pizza gibi.',
      not: 'Bilinmeyen bir yemeği anlatmanın en pratik yoludur.',
    },
    {
      id: 'de-yem-89', on: 'unbedingt probieren', okunus: 'unbıdingt probiirın', tur: 'kalıp',
      arka: 'mutlaka denemek',
      ornek: 'Das musst du unbedingt probieren.',
      ornekTr: 'Bunu mutlaka denemelisin.',
      not: '"unbedingt" = kesinlikle, mutlaka.',
    },
    {
      id: 'de-yem-90', on: 'Greif zu!', okunus: 'grayf tsuu', tur: 'kalıp',
      arka: 'Buyur, al!',
      ornek: 'Greif zu, es ist genug für alle da.',
      ornekTr: 'Buyur al, herkese yetecek kadar var.',
      not: '"zugreifen" sofrada kendine almak demektir.',
      kok: 'greif',
    },
    /* --- Yemek deyimleri --- */
    {
      id: 'de-yem-91', on: 'Das ist mir Wurst', okunus: 'das ist mir vurst', tur: 'deyim',
      arka: 'Bana fark etmez',
      ornek: 'Pizza oder Nudeln? Das ist mir Wurst.',
      ornekTr: 'Pizza mı makarna mı? Bana fark etmez.',
      not: 'Almancanın en bilinen deyimlerinden biridir.',
    },
    {
      id: 'de-yem-92', on: 'Es geht um die Wurst', okunus: 'es geet um di vurst', tur: 'deyim',
      arka: 'İş ciddiye bindi, karar anı',
      ornek: 'Im Finale geht es um die Wurst.',
      ornekTr: 'Finalde iş ciddiye biniyor.',
      not: 'Eski panayır yarışmalarından gelir; ödül sosisti.',
    },
    {
      id: 'de-yem-93', on: 'in den sauren Apfel beißen', okunus: 'in deen zaurın apfıl baysın', tur: 'deyim',
      arka: 'acı gerçeği kabullenmek',
      ornek: 'Ich muss in den sauren Apfel beißen und lernen.',
      ornekTr: 'Acı gerçeği kabullenip çalışmam gerekiyor.',
      not: 'Kelimesi kelimesine "ekşi elmayı ısırmak"tır.',
    },
    {
      id: 'de-yem-94', on: 'Das ist nicht mein Geschmack', okunus: 'das ist niht mayn gışmak', tur: 'kalıp',
      arka: 'Bu benim zevkim değil',
      ornek: 'Der Kuchen ist gut, aber nicht mein Geschmack.',
      ornekTr: 'Kek güzel ama benim zevkim değil.',
      not: 'Kibarca beğenmediğini söylemenin yoludur.',
    },
    {
      id: 'de-yem-95', on: 'Hunger ist der beste Koch', okunus: 'hungır ist der bestı koh', tur: 'atasözü',
      arka: 'Açlık en iyi aşçıdır',
      ornek: 'Alles schmeckt gut: Hunger ist der beste Koch.',
      ornekTr: 'Her şey güzel geliyor: açlık en iyi aşçıdır.',
      not: 'Türkçedeki "aç olana her şey güzel gelir" mantığındadır.',
    },
    {
      id: 'de-yem-96', on: 'Der Appetit kommt beim Essen', okunus: 'der apetiit komt baym esın', tur: 'atasözü',
      arka: 'İştah yemekle açılır',
      ornek: 'Fang einfach an: Der Appetit kommt beim Essen.',
      ornekTr: 'Sadece başla: iştah yemekle açılır.',
      not: 'Ders çalışmaya başlamak için de kullanılır.',
    },
    {
      id: 'de-yem-97', on: 'Guten Appetit!', okunus: 'guutın apetiit', tur: 'kalıp',
      arka: 'Afiyet olsun!',
      ornek: 'Das Essen ist fertig. Guten Appetit!',
      ornekTr: 'Yemek hazır. Afiyet olsun!',
      not: 'Yemekten önce söylenir; sonrasında "Hat es geschmeckt?" sorulur.',
    },
    {
      id: 'de-yem-98', on: 'Hat es geschmeckt?', okunus: 'hat es gışmekt', tur: 'soru kalıbı',
      arka: 'Beğendiniz mi?',
      ornek: 'Hat es Ihnen geschmeckt?',
      ornekTr: 'Beğendiniz mi?',
      not: 'Garsonun yemek sonrası standart sorusudur.',
    },
    {
      id: 'de-yem-99', on: 'Noch ein bisschen?', okunus: 'noh ayn bishın', tur: 'soru kalıbı',
      arka: 'Biraz daha?',
      ornek: 'Möchtest du noch ein bisschen Suppe?',
      ornekTr: 'Biraz daha çorba ister misin?',
      not: '"ein bisschen" sayılamayan isimlerle kullanılır.',
    },
    {
      id: 'de-yem-100', on: 'Nein danke, ich bin satt', okunus: 'nayn dankı ih bin zat', tur: 'kalıp',
      arka: 'Hayır teşekkürler, doydum',
      ornek: 'Nein danke, ich bin wirklich satt.',
      ornekTr: 'Hayır teşekkürler, gerçekten doydum.',
      not: 'Kibarca reddetmenin en doğal sofra cümlesidir.',
    },
  ],
}

export default DESTE
