import InteractiveIllustration from './InteractiveIllustration'
const zones=[{x:0,y:0,width:768,height:512},{x:768,y:0,width:768,height:512},{x:0,y:512,width:768,height:512},{x:768,y:512,width:768,height:512}]
const pos=[{x:70,y:78,targetX:360,targetY:265},{x:845,y:78,targetX:1165,targetY:265},{x:70,y:946,targetX:360,targetY:760},{x:845,y:946,targetX:1165,targetY:760}]
function Plate({src,alt,items,activeRegion}){const regions=items.map((i,n)=>({...i,shape:zones[n],zoom:{x:n%2?75:25,y:n<2?25:75,scale:1.45}}));const markers=items.map((i,n)=>({key:i.key,title:i.marker,width:i.width??370,...pos[n]}));return <InteractiveIllustration src={`/lesson-assets/canlilar-cevre/${src}.jpg`} srcSet={`/lesson-assets/canlilar-cevre/${src}-900.jpg 900w, /lesson-assets/canlilar-cevre/${src}.jpg 1536w`} alt={alt} activeRegion={activeRegion} regions={regions} markers={markers}/>}
const d=(file,title,alt,note)=>({src:`/lesson-assets/canlilar-cevre/details/${file}.jpg`,title,alt,note})

export function VariationPlate({activeRegion=null}){const items=[
 {key:'mayoz-kombinasyon',marker:'Mayoz · döllenme · kombinasyon',detail:d('mayoz-kombinasyon','Var olan alelleri her yavruda yeniden karıştır','Krossing-over, bağımsız dağılım ve rastgele döllenmeyle farklı yavrular.','Krossing-over yeni alel üretmez; homologlar arasında parça değiştirir. Bağımsız dağılım ve rastgele döllenmeyle birlikte var olan alelleri yeni genotiplerde birleştirir.')},
 {key:'germ-soma',marker:'Üreme hücresi · vücut hücresi',detail:d('germ-soma','Mutasyonun kalıtsallığını gerçekleştiği hücreyle belirle','Germ hattı mutasyonunun yavrulara, somatik mutasyonun hücre klonuna aktarımı.','Germ hattındaki mutasyon gamete ve sonraki nesle geçebilir. Somatik mutasyon bireyin ilgili hücre soyunda kalır; eşeysiz üreme gibi özel durumlar dışında yavruya aktarılmaz.')},
 {key:'cevre-fenotip',marker:'Çevre · fenotip · modifikasyon',detail:d('cevre-fenotip','Aynı genotipin farklı çevrelerde farklı görünmesini izle','Aynı genotipli bitkilerin ışık, besin ve pH koşullarında değişen fenotipleri.','Fenotip genotip ile çevrenin etkileşimidir. Çevresel değişim DNA dizisini değiştirmeden fenotipi değiştirebilir; bu kazanılmış görünüm çoğunlukla kalıtsal değildir.')},
 {key:'surekli-kesikli',marker:'Sürekli · kesikli varyasyon',detail:d('surekli-kesikli','Ölçülebilir dağılımı kategori farkından ayır','Boy gibi çan eğrili sürekli özellik ve kan grubu gibi ayrı kategoriler.','Boy ve kütle çok genli-çevre etkili sürekli dağılım gösterebilir. Kan grubu gibi özellikler ayrı kategorilidir; ikisi de popülasyon içi varyasyondur.')},
];return <Plate src="varyasyon-v1" alt="Genetik ve çevresel varyasyon kaynaklarını gösteren AYT levhası." items={items} activeRegion={activeRegion}/>}

export function MutationPlate({activeRegion=null}){const items=[
 {key:'gen-mutasyonu',marker:'Baz değişimi · ekleme · silme',detail:d('gen-mutasyonu','Dizideki küçük değişimin okuma çerçevesine etkisini gör','Baz değişimi ile ekleme-silmenin mRNA ve proteine farklı etkileri.','Baz değişimi sessiz, yanlış anlamlı veya dur kodu etkili olabilir. Üçün katı olmayan ekleme-silme okuma çerçevesini kaydırıp sonraki kodonların çoğunu değiştirebilir.')},
 {key:'kromozom-mutasyonu',marker:'Yapı · sayı · ayrılmama',detail:d('kromozom-mutasyonu','Kromozom parçası değişimini ayrılmama hatasından ayır','Delesyon, duplikasyon, inversiyon, translokasyon ve mayoz ayrılmaması.','Yapı mutasyonları parçanın kaybı, tekrarı, ters dönmesi veya yer değiştirmesidir. Ayrılmama kromozom sayısı farklı gametler oluşturabilir.')},
 {key:'baglama-gore-etki',marker:'Yararlı · zararlı · nötr',detail:d('baglama-gore-etki','Mutasyon etkisini çevre ve üreme başarısıyla değerlendir','Aynı mutasyonun üç çevrede farklı uyum başarısı sonucu.','Mutasyon amaçlı oluşmaz ve mutlak yararlı/zararlı olmak zorunda değildir. Fenotip etkisi ve çevre, taşıyıcının üreme başarısını belirler.')},
 {key:'mutajen-onarim',marker:'Mutajen · onarım · hücre kaderi',detail:d('mutajen-onarim','DNA hasarını mutasyonla aynı şey sanma','UV, radyasyon, kimyasal ve virüs hasarı; onarım, apoptoz, somatik ve germ hattı sonuçları.','Mutajen hasar olasılığını artırır; her hasar kalıcı mutasyon olmaz. Onarım başarısız ve değişim DNA’da sabitlenirse mutasyon oluşur; hücre tipi kalıtsallığı belirler.')},
];return <Plate src="mutasyon-v1" alt="Gen ve kromozom mutasyonlarını, etkilerini ve mutajenleri gösteren AYT levhası." items={items} activeRegion={activeRegion}/>}

export function NaturalSelectionPlate({activeRegion=null}){const items=[
 {key:'onceden-varyasyon',marker:'Önceden var olan varyasyon',detail:d('onceden-varyasyon','Seçilim başlamadan önce farkların bulunduğunu gör','Çevre değişmeden önce farklı renk ve dayanıklılık taşıyan böcek popülasyonu.','Doğal seçilim ihtiyaç üzerine uygun özellik üretmez. Mutasyon ve rekombinasyonla oluşmuş kalıtsal farklar popülasyonda önceden bulunur.')},
 {key:'cevre-filtresi',marker:'Çevre filtresi · diferansiyel yaşam',detail:d('cevre-filtresi','Çevrenin bireyi dönüştürmediğini, farklıları elediğini göster','Avcı veya ilaç etkisinde fenotiplere göre farklı hayatta kalma.','Çevre bir seçilim baskısıdır. Dirençsizler daha çok elenir; dirençli bireyler ilaca maruz kalınca direnç geliştirmez, zaten taşıdıkları özellik nedeniyle görece avantaj kazanır.')},
 {key:'nesiller-frekans',marker:'Üreme · nesiller · alel frekansı',detail:d('nesiller-frekans','Bireyde değil popülasyonda nesiller boyunca değişimi izle','Hayatta kalanların üremesiyle dayanıklı fenotip ve alelin artışı.','Seçilim bireyler üzerinde işler, evrimsel sonuç popülasyonda alel frekansının nesiller boyunca değişmesidir. Kalıtsal avantaj daha çok yavruya aktarılır.')},
 {key:'uyum-basarisi',marker:'Uyum başarısı · yavru katkısı',detail:d('uyum-basarisi','Yalnız yaşam süresini değil üreme katkısını ölç','Uzun yaşayan fakat üremeyen birey ile çok yavru veren bireyin karşılaştırması.','Biyolojik uyum başarısı yalnız güçlü veya uzun ömürlü olmak değildir; sonraki neslin gen havuzuna yapılan üreme katkısıdır ve çevre değişince avantaj da değişebilir.')},
];return <Plate src="dogal-secilim-v1" alt="Doğal seçilimin varyasyondan alel frekansı değişimine mekanizmasını gösteren AYT levhası." items={items} activeRegion={activeRegion}/>}

export function AdaptationPlate({activeRegion=null}){const items=[
 {key:'yapisal-adaptasyon',marker:'Yapısal adaptasyon',detail:d('yapisal-adaptasyon','Vücut biçimini habitat problemine bağla','Kaktüs, kutup memelisi ve sucul canlılarda yapısal uyumlar.','Su depolayan gövde-diken, kalın yalıtım ve akıcı vücut gibi kalıtsal yapılar belirli ortamda yaşama-üreme başarısını artırabilir.')},
 {key:'fizyolojik-adaptasyon',marker:'Fizyolojik adaptasyon',detail:d('fizyolojik-adaptasyon','İç işleyişteki kalıtsal çözümü tanı','Yoğun idrar, antifriz proteini, zehir ve gece açılan stomalar.','Enzim, metabolizma ve su dengesi düzenekleri dış görünüşten bağımsız uyum sağlayabilir. Fizyolojik adaptasyon da kalıtsal popülasyon özelliğidir.')},
 {key:'davranissal-adaptasyon',marker:'Davranışsal adaptasyon',detail:d('davranissal-adaptasyon','Davranışın enerji ve üreme sonucunu izle','Göç, kış uykusu, kur davranışı ve grup savunması.','Göç, kış uykusu ve kur gibi kalıtsal bileşenli davranışlar kaynak bulma, enerji koruma veya eşleşme başarısını artırabilir.')},
 {key:'adaptasyon-aklimasyon',marker:'Adaptasyon · aklimasyon',detail:d('adaptasyon-aklimasyon','Nesiller süren kalıtsal uyumu bireysel ayarlamadan ayır','Popülasyonda nesiller boyu çöl uyumu ve bireyde geçici yüksek irtifa yanıtı.','Adaptasyon popülasyonda nesiller boyu seçilen kalıtsal özelliktir. Aklimasyon bireyin yaşamında çevreye verdiği çoğunlukla geri dönüşlü fizyolojik yanıttır.')},
];return <Plate src="adaptasyon-v1" alt="Yapısal, fizyolojik ve davranışsal adaptasyonları aklimasyondan ayıran AYT levhası." items={items} activeRegion={activeRegion}/>}

export function HumanSelectionPlate({activeRegion=null}){const items=[
 {key:'tarim-yapay-secilim',marker:'Yabani tür · seçilen organ · kültür',detail:d('tarim-yapay-secilim','İnsan tercihinin aynı türden farklı kültürler üretmesini izle','Yabani hardaldan yaprak, tomurcuk, gövde ve çiçek seçimiyle tarım çeşitleri.','İnsan belirli fenotipleri eşleştirerek istenen alellerin sıklığını artırır. Lahana, brokoli ve karnabahar farklı organların seçilmesinin ürünleridir.')},
 {key:'hayvan-yapay-secilim',marker:'Verim · ırk · genetik daralma',detail:d('hayvan-yapay-secilim','Kazancı çeşitlilik ve sağlık bedeliyle birlikte değerlendir','Köpek ve sığır ırklarında seçilen özellikler ve azalan genetik çeşitlilik.','Yapay seçilim verim veya davranışı güçlendirebilir; dar damızlık havuzu zararlı alellerin birikmesi ve çevresel değişime kırılganlık riskini artırabilir.')},
 {key:'antibiyotik-direnci',marker:'Antibiyotik · direnç · gen aktarımı',detail:d('antibiyotik-direnci','İlacın direnci üretmediğini seçtiğini gör','Karışık bakterilerde duyarlıların ölmesi, dirençlilerin çoğalması ve plazmid aktarımı.','Antibiyotik dirençli mutasyonu ihtiyaca göre oluşturmaz; var olan dirençlileri seçer. Hayatta kalanlar bölünür ve direnç genleri yatay aktarılabilir.')},
 {key:'pestisit-yonetimi',marker:'Pestisit · direnç · seçilim baskısı',detail:d('pestisit-yonetimi','Tekrarlanan aynı baskının popülasyonu nasıl değiştirdiğini izle','İlaçlamayla dirençli böceklerin artışı ve dönüşümlü-biyolojik mücadele.','Aynı pestisitin sık kullanımı dirençlilere sürekli avantaj sağlar. Dönüşümlü yöntem, sığınak ve biyolojik mücadele baskıyı çeşitlendirerek direncin yayılmasını yavaşlatabilir.')},
];return <Plate src="yapay-secilim-direnc-v1" alt="Yapay seçilim, antibiyotik ve pestisit direncini gösteren AYT levhası." items={items} activeRegion={activeRegion}/>}
