import InteractiveIllustration from './InteractiveIllustration'

const zones = [
  { x: 0, y: 0, width: 768, height: 512 }, { x: 768, y: 0, width: 768, height: 512 },
  { x: 0, y: 512, width: 768, height: 512 }, { x: 768, y: 512, width: 768, height: 512 },
]
const markerPositions = [
  { x: 70, y: 78, targetX: 360, targetY: 265 }, { x: 845, y: 78, targetX: 1165, targetY: 265 },
  { x: 70, y: 946, targetX: 360, targetY: 760 }, { x: 845, y: 946, targetX: 1165, targetY: 760 },
]
function Plate({ src, alt, items, activeRegion }) {
  const regions = items.map((item, index) => ({ ...item, shape: zones[index], zoom: { x: index % 2 ? 75 : 25, y: index < 2 ? 25 : 75, scale: 1.45 } }))
  const markers = items.map((item, index) => ({ key: item.key, title: item.marker, width: item.width ?? 365, ...markerPositions[index] }))
  return <InteractiveIllustration src={`/lesson-assets/bitki-biyolojisi/${src}.jpg`} srcSet={`/lesson-assets/bitki-biyolojisi/${src}-900.jpg 900w, /lesson-assets/bitki-biyolojisi/${src}.jpg 1536w`} alt={alt} activeRegion={activeRegion} regions={regions} markers={markers} />
}

export function PlantTissuePlate({ activeRegion = null }) {
  const items = [
    { key: 'meristem-buyume', marker: 'Meristem · birincil · ikincil büyüme', width: 420, detail: { src: '/lesson-assets/bitki-biyolojisi/details/meristem-buyume.jpg', title: 'Bölünme konumunu büyümenin yönüyle eşleştir', alt: 'Kök ve sürgün uç meristemleri ile vasküler ve mantar kambiyumun oluşturduğu birincil ve ikincil büyüme.', note: 'Uç meristemler kök ve gövdenin boyuna uzamasını sağlar. Vasküler kambiyum içe sekonder ksilem, dışa sekonder floem; mantar kambiyumu ise koruyucu periderm üreterek enine kalınlaşmaya katılır.' } },
    { key: 'parankima-cesitleri', marker: 'Parankima · fotosentez · depo · hava', width: 420, detail: { src: '/lesson-assets/bitki-biyolojisi/details/parankima-cesitleri.jpg', title: 'Aynı temel dokuyu hücre içeriği ve boşlukla uzmanlaştır', alt: 'Klorenkima, depo parankiması, havalandırma parankiması ve iletim parankimasının mikroskobik yapıları.', note: 'Parankima hücreleri canlı, ince çeperli ve farklılaşma yeteneği yüksek olabilir. Klorenkima fotosentez; depo parankiması nişasta, yağ, protein veya su; aerenkima geniş hava boşlukları; iletim parankiması kısa mesafeli aktarım sağlar.' } },
    { key: 'destek-doku', marker: 'Kollenkima · sklerenkima', width: 345, detail: { src: '/lesson-assets/bitki-biyolojisi/details/destek-doku.jpg', title: 'Esnek canlı desteği ligninli ölü destekten ayır', alt: 'Köşeleri selüloz ve pektinle kalın kollenkima ile ligninli sklerenkima lifleri ve taş hücreleri.', note: 'Kollenkima büyüyen genç organlarda canlı ve esnektir; çeper kalınlığı düzensizdir. Sklerenkima hücreleri olgunlukta çoğunlukla ölü, ligninli ve serttir; lifler çekmeye, taş hücreleri basınca direnç sağlar.' } },
    { key: 'ortu-iletim', marker: 'Örtü doku · ksilem · floem', width: 360, detail: { src: '/lesson-assets/bitki-biyolojisi/details/ortu-iletim.jpg', title: 'Koruma yüzeyini taşıma sütunlarından ayır', alt: 'Epidermis, kütikula, stoma, kök tüyü, periderm ve kambiyum arasında ksilem-floem dokuları.', note: 'Epidermis genç organları, periderm yaşlı gövde ve kökü örter. Ksilemin trake-trakeitleri olgunlukta ölü ve ligninli; floemin kalburlu boruları canlı fakat çekirdeksizdir ve arkadaş hücrelerinden metabolik destek alır.' } },
  ]
  return <Plate src="bitki-doku-v1" alt="Bitkisel meristem, temel, destek, örtü ve iletim dokularını gösteren AYT levhası." items={items} activeRegion={activeRegion} />
}

export function PlantOrganPlate({ activeRegion = null }) {
  const items = [
    { key: 'kok-bolgeleri', marker: 'Kaliptra · bölünme · uzama · farklılaşma', width: 440, detail: { src: '/lesson-assets/bitki-biyolojisi/details/kok-bolgeleri.jpg', title: 'Kök ucunda hücre kaderini art arda oku', alt: 'Kaliptradan başlayıp bölünme, uzama ve kök tüylü farklılaşma bölgelerine ilerleyen boyuna kök kesiti.', note: 'Kaliptra uç meristemi korur ve yer çekimi algısına katılır. Arkasında hücre bölünmesi, sonra boyca uzama, daha yukarıda kök tüyleri ve kalıcı dokulara farklılaşma görülür.' } },
    { key: 'kok-kesiti', marker: 'Kök kesiti · endodermis · periskl', width: 395, detail: { src: '/lesson-assets/bitki-biyolojisi/details/kok-kesiti.jpg', title: 'Topraktan merkeze her doku halkasının işini kur', alt: 'Çift çenekli kökte epidermis, korteks, endodermis, periskl, yıldız biçimli ksilem, floem ve yan kök başlangıcı.', note: 'Su epidermis ve korteksi geçip endodermiste seçilir. Periskl yan kökleri oluşturabilir. Çift çenekli genç kökte ksilem merkezde yıldız, floem yıldız kolları arasında yer alır.' } },
    { key: 'govde-buyume', marker: 'Tek–çift çenek gövde · kambiyum', width: 420, detail: { src: '/lesson-assets/bitki-biyolojisi/details/govde-buyume.jpg', title: 'Demet dizilişinden ikincil büyüme olasılığını çıkar', alt: 'Çift çenekli gövdede halka hâlinde açık demetler, tek çeneklide dağınık kapalı demetler ve yıllık halkalı odunsu büyüme.', note: 'Çift çenekli gövdede iletim demetleri halka hâlinde ve ksilem-floem arasında kambiyumludur. Tek çeneklilerde demetler dağınık ve çoğunlukla kapalıdır; tipik sekonder kalınlaşma görülmez.' } },
    { key: 'yaprak-kesiti', marker: 'Yaprak · mezofil · iletim demeti', width: 390, detail: { src: '/lesson-assets/bitki-biyolojisi/details/yaprak-kesiti.jpg', title: 'Işığı üstten, gazı boşluklardan, suyu damardan yürüt', alt: 'Kütikula, epidermis, palizat ve sünger parankiması, ksilem-floem demeti ve alt epidermis stomaları olan yaprak kesiti.', note: 'Palizat parankiması yoğun kloroplastla ışığı kullanır; sünger parankimasının boşlukları gazların yayılmasını kolaylaştırır. Yaprak damarında ksilem genellikle üstte, floem altta; stomalar kara bitkilerinde çoğunlukla alt epidermistedir.' } },
  ]
  return <Plate src="organ-anatomi-v1" alt="Kök bölgeleri, kök ve gövde kesitleri ile yaprak anatomisini gösteren AYT bitki levhası." items={items} activeRegion={activeRegion} />
}

export function PlantTransportPlate({ activeRegion = null }) {
  const items = [
    { key: 'kok-alim', marker: 'Kök tüyü · apoplast · simplast · Kaspari', width: 445, detail: { src: '/lesson-assets/bitki-biyolojisi/details/kok-alim.jpg', title: 'Duvar yolunu endodermiste zar seçimine zorla', alt: 'Kök tüyünden su ve mineral alımı, apoplast-simplast yolları ve Kaspari şeridinde seçici geçiş.', note: 'Mineral iyonları gerektiğinde aktif taşımayla biriktirilir, su su potansiyeli farkıyla izler. Apoplast duvarlardan, simplast sitoplazma-plazmodezmalardan ilerler; Kaspari şeridi apoplastı kesip maddeleri endodermis zarından seçilmeye zorlar.' } },
    { key: 'ksilem-cekimi', marker: 'Terleme çekimi · kohezyon · adhezyon', width: 430, detail: { src: '/lesson-assets/bitki-biyolojisi/details/ksilem-cekimi.jpg', title: 'Yapraktaki buharlaşmayı kökteki su sütununa ilet', alt: 'Ksilemde terleme çekimi, su molekülleri arasında kohezyon, çepere adhezyon, kök basıncı ve gutasyon.', note: 'Mezofilden su buharlaşınca yaprak ksileminde gerilim oluşur. Kohezyon kesintisiz su sütununu, adhezyon çepere tutunmayı sağlar. Kök basıncı ve kılcallık katkı yapar fakat uzun ağaçta ana güç terleme çekimidir.' } },
    { key: 'stoma-kontrol', marker: 'Bekçi hücresi · iyon · ABA', width: 345, detail: { src: '/lesson-assets/bitki-biyolojisi/details/stoma-kontrol.jpg', title: 'İyon hareketini su ve gözenek açıklığına bağla', alt: 'Işıkta iyon ve su alan bekçi hücrelerinin stoma açması, kuraklıkta ABA ile iyon-su kaybedip kapanması.', note: 'Bekçi hücrelerine K⁺ ve eşlik eden anyonlar girince su potansiyeli düşer, su girer ve özel çeper yapısı gözenek açar. Su kıtlığında ABA iyon çıkışını, su kaybını ve kapanmayı destekler; CO₂ alımı azalırken terleme sınırlanır.' } },
    { key: 'floem-basinc-akis', marker: 'Kaynak–havuz · basınç akışı', width: 365, detail: { src: '/lesson-assets/bitki-biyolojisi/details/floem-basinc-akis.jpg', title: 'Sakkaroz yüklemesini hidrostatik kütle akışına çevir', alt: 'Kaynak yapraktan floeme sakkaroz yüklenmesi, ksilemden su girişi, havuz kök ve meyveye akış ve suyun dönüşü.', note: 'Kaynakta sakkaroz yüklenmesi floeme su çeker ve basıncı yükseltir. Özsu düşük basınçlı havuza kütle akışıyla ilerler; boşaltmada su potansiyeli yükselir ve su ksileme dönebilir. Farklı borular zıt yönlerde çalışabilir.' } },
  ]
  return <Plate src="bitki-tasima-v1" alt="Kökten su-mineral alımı, ksilem, stoma ve floem taşımasını gösteren AYT levhası." items={items} activeRegion={activeRegion} />
}

export function PlantHormonePlate({ activeRegion = null }) {
  const items = [
    { key: 'oksin-tropizma', marker: 'Oksin · fototropizma · gravitropizma', width: 430, detail: { src: '/lesson-assets/bitki-biyolojisi/details/oksin-tropizma.jpg', title: 'Aynı oksin dağılımının gövde ve kökte farklı sonuç verdiğini gör', alt: 'Sürgünde gölgeli tarafta oksinle uzama ve ışığa bükülme, kökte yüksek oksinle alt taraf uzamasının baskılanması.', note: 'Tek yönlü ışıkta oksin sürgünün gölgeli tarafında birikip hücre uzamasını artırır ve gövde ışığa döner. Yatay kökte alt tarafta biriken yüksek oksin uzamayı baskıladığı için üst taraf daha çok uzar ve kök aşağı kıvrılır.' } },
    { key: 'giberellin-sitokinin', marker: 'Giberellin · sitokinin', width: 330, detail: { src: '/lesson-assets/bitki-biyolojisi/details/giberellin-sitokinin.jpg', title: 'Çimlenme ve uzamayı hücre bölünmesiyle dengede tut', alt: 'Giberellinin tohum çimlenmesi ve gövde uzamasını, sitokininin hücre bölünmesi, tomurcuk gelişimi ve yaşlanmayı geciktirmesi.', note: 'Giberellin dormansiyi kırıp çimlenme enzimlerini ve boğum arası uzamasını artırır. Köklerde de sentezlenen sitokinin hücre bölünmesini, yan tomurcuk ve sürgün oluşumunu destekler; yaprak yaşlanmasını geciktirebilir.' } },
    { key: 'aba-etilen', marker: 'ABA · kuraklık · etilen · olgunlaşma', width: 420, detail: { src: '/lesson-assets/bitki-biyolojisi/details/aba-etilen.jpg', title: 'Stres frenini gaz hâlindeki olgunlaşma sinyalinden ayır', alt: 'ABA ile stoma kapanması ve tohum dormansisi; etilenle meyve olgunlaşması ve yaprak dökülmesi.', note: 'ABA su stresinde stomayı kapatır ve bazı tohumlarda dormansiyi korur. Gaz hâlindeki etilen meyve olgunlaşmasını hızlandırır, çevredeki meyveleri de etkiler ve yaşlanma-yaprak kopma süreçlerine katılır.' } },
    { key: 'nasti-fotoperiyot', marker: 'Tropizma · nasti · fotoperiyot', width: 380, detail: { src: '/lesson-assets/bitki-biyolojisi/details/nasti-fotoperiyot.jpg', title: 'Uyaran yönünü hareketten, gece uzunluğunu çiçeklenmeden oku', alt: 'Yöne bağlı tropizma, küstüm otu nasti hareketi ve kesintisiz gece süresiyle kısa-uzun gün bitkilerinin çiçeklenmesi.', note: 'Tropizma büyümenin uyaran yönüne bağlıdır; nastide hareket yönü uyaran yönünden bağımsızdır ve çoğu kez turgor değişimi etkilidir. Fotoperiyodizmde kritik sinyal çoğunlukla kesintisiz gece uzunluğudur.' } },
  ]
  return <Plate src="hormon-hareket-v1" alt="Bitki hormonlarını, tropizma-nasti hareketlerini ve fotoperiyodizmi gösteren AYT levhası." items={items} activeRegion={activeRegion} />
}

export function FlowerReproductionPlate({ activeRegion = null }) {
  const items = [
    { key: 'cicek-anatomi', marker: 'Çiçek · erkek organ · dişi organ', width: 400, detail: { src: '/lesson-assets/bitki-biyolojisi/details/cicek-anatomi.jpg', title: 'Dört organ halkasını üreme görevleriyle yerleştir', alt: 'Çanak ve taç yapraklar, anter-sapçıklı erkek organ ve tepecik-boyuncuk-yumurtalıklı dişi organ kesiti.', note: 'Çanak yaprak tomurcuğu korur, taç yaprak tozlaştırıcı çekebilir. Erkek organın anterinde polen; dişi organın tepeciğinde polen kabulü, boyuncuğunda tüp yolu, yumurtalığında tohum taslakları bulunur.' } },
    { key: 'sporogenez-gametofit', marker: 'Mayoz · polen · embriyo kesesi', width: 380, detail: { src: '/lesson-assets/bitki-biyolojisi/details/sporogenez-gametofit.jpg', title: 'Diploit ana hücreden haploit gametofitleri üret', alt: 'Anterde mikrospor mayozu ve polen gelişimi ile ovülde megaspor mayozu ve yedi hücreli sekiz çekirdekli embriyo kesesi.', note: 'Mikrospor ana hücresi mayozla dört haploit mikrospor, bunlar polen gametofitini oluşturur. Megaspor ana hücresinin dört ürününden genellikle biri yaşar; mitozlarla yumurta, iki sinerjit, üç antipod ve iki polar çekirdekli embriyo kesesi gelişir.' } },
    { key: 'tozlasma-cift-dollenme', marker: 'Tozlaşma · tüp · çift döllenme', width: 395, detail: { src: '/lesson-assets/bitki-biyolojisi/details/tozlasma-cift-dollenme.jpg', title: 'Polenin taşınmasını iki ayrı çekirdek birleşmesinden ayır', alt: 'Tepecikte çimlenen polen tüpü, mikropilden iki sperm girişi, zigot ve triploit endosperm oluşumu.', note: 'Tozlaşma polenin tepeciğe taşınmasıdır, döllenme değildir. Polen tüpü iki spermi mikropilden taşır; biri yumurtayla 2n zigotu, diğeri iki polar çekirdekle 3n endosperm başlangıcını oluşturur.' } },
    { key: 'tohum-meyve-cimlenme', marker: 'Tohum · meyve · çimlenme', width: 350, detail: { src: '/lesson-assets/bitki-biyolojisi/details/tohum-meyve-cimlenme.jpg', title: 'Döllenme ürünlerini organ dönüşümleriyle tamamla', alt: 'Tohum taslağından tohum, yumurtalıktan meyve; su, oksijen ve sıcaklıkla kökçüğün önce çıktığı çimlenme.', note: 'Zigot embriyo, triploit çekirdek endosperm, integümentler tohum kabuğu olur; tohum taslağı tohuma, yumurtalık çoğunlukla meyveye dönüşür. Uygun su, oksijen ve sıcaklıkta metabolizma yeniden başlar ve kökçük önce çıkar.' } },
  ]
  return <Plate src="bitki-ureme-v1" alt="Çiçek anatomisi, gametofit gelişimi, çift döllenme ve tohum-meyve oluşumunu gösteren AYT levhası." items={items} activeRegion={activeRegion} />
}
