/**
 * A1 — AİLE VE EŞYALAR
 * ==================================================================
 *
 * Bu havuzun asıl işi kelime öğretmek değil, CİNSİYET öğretmektir.
 * İyi haber: İspanyolcada tahmin oranı yüksektir (-o eril, -a dişil).
 * Kötü haber: istisnalar tam da en sık kullanılan kelimelerdedir
 * (el problema, el día, la mano). Bunlar yalnız `cins` alanından öğrenilir.
 */

export const KELIMELER = [
  {
    id: 'es-familia', dil: 'es', kelime: 'familia', artikel: 'la', cins: 'disil', cogul: 'las familias',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'Las personas que viven juntas: los padres y los hijos.',
    turkceDestek: 'aile', ipa: '/fa.ˈmi.lja/', heceler: 'fa-mi-lia (vurgu: Mİ)',
    ornekler: [
      { es: 'Mi familia vive en Ankara.', tr: 'Ailem Ankara\'da yaşıyor.' },
      { es: 'Somos una familia de cinco personas.', tr: 'Beş kişilik bir aileyiz.' },
    ],
    esdizim: ['una familia grande', 'en familia'], aile: ['los padres', 'familiar'],
    hata: 'Türkçedeki "ailem var" mantığıyla "tengo familia" demek. Aile için "mi familia" ile başlanır: "Mi familia es pequeña."',
    hatirlatma: 'Aile üyelerinden söz ederken iyelik sıfatı artikeli alır: MI familia (la familia değil).',
    uretim: { yonerge: '"Ailem küçük." cümlesini yaz.', kabul: ['Mi familia es pequeña'] },
  },
  {
    id: 'es-padre', dil: 'es', kelime: 'padre', artikel: 'el', cins: 'eril', cogul: 'los padres',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'El hombre que tiene un hijo o una hija.',
    turkceDestek: 'baba', ipa: '/ˈpa.ðɾe/', heceler: 'pa-dre (vurgu: PA)',
    ornekler: [
      { es: 'Mi padre es ingeniero.', tr: 'Babam mühendis.' },
      { es: 'El padre de Ana trabaja en Madrid.', tr: 'Ana\'nın babası Madrid\'de çalışıyor.' },
    ],
    esdizim: ['mi padre', 'el padre de', 'papá'], aile: ['la madre', 'los padres'],
    hata: 'Çoğulu "los padres"in hem "babalar" hem "anne baba" demek olduğunu bilmemek. Bağlam ayırır; genelde "anne baba" anlamındadır.',
    hatirlatma: 'Günlük dilde "papá" denir ve aksanlıdır; aksansız "papa" patates ya da papa demektir.',
    uretim: { yonerge: '"Babam öğretmen." cümlesini yaz.', kabul: ['Mi padre es profesor'] },
  },
  {
    id: 'es-madre', dil: 'es', kelime: 'madre', artikel: 'la', cins: 'disil', cogul: 'las madres',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'La mujer que tiene un hijo o una hija.',
    turkceDestek: 'anne', ipa: '/ˈma.ðɾe/', heceler: 'ma-dre',
    ornekler: [
      { es: 'Mi madre es médica.', tr: 'Annem doktor.' },
      { es: 'Mi madre es muy simpática.', tr: 'Annem çok cana yakın.' },
    ],
    esdizim: ['mi madre', 'mamá'], aile: ['el padre', 'los padres'],
    hata: 'Sıfatı dişile uydurmamak: "Mi madre es simpático" değil, "simpática".',
    hatirlatma: '-e ile bitmesine rağmen dişildir; -o/-a kuralı her kelimede geçerli değildir.',
    uretim: { yonerge: '"Annem çok cana yakın." cümlesini yaz.', kabul: ['Mi madre es muy simpática'] },
  },
  {
    id: 'es-hermano', dil: 'es', kelime: 'hermano / hermana', artikel: 'el', cins: 'eril', cogul: 'los hermanos',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'El hijo o la hija de los mismos padres.',
    turkceDestek: 'erkek kardeş / kız kardeş', ipa: '/eɾ.ˈma.no/', heceler: 'her-ma-no (h okunmaz: "ermano")',
    ornekler: [
      { es: 'Tengo un hermano y una hermana.', tr: 'Bir erkek kardeşim ve bir kız kardeşim var.' },
      { es: 'Mi hermano mayor tiene veinte años.', tr: 'Ağabeyim yirmi yaşında.' },
    ],
    esdizim: ['hermano mayor', 'hermano menor'], aile: ['la familia', 'el primo'],
    hata: 'Türkçedeki "kardeş" cinsiyet belirtmez; öğrenci ikisini ayırmadan kullanır. İspanyolcada bu ayrım zorunludur.',
    hatirlatma: 'Ağabey = hermano mayor, küçük kardeş = hermano menor.',
    uretim: { yonerge: '"Bir erkek kardeşim var." cümlesini yaz.', kabul: ['Tengo un hermano'] },
  },
  {
    id: 'es-hijo', dil: 'es', kelime: 'hijo / hija', artikel: 'el', cins: 'eril', cogul: 'los hijos',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'El niño o la niña de una familia, respecto a sus padres.',
    turkceDestek: 'oğul / kız evlat', ipa: '/ˈi.xo/', heceler: 'hi-jo (h okunmaz, j gırtlaktan: "iho")',
    ornekler: [
      { es: 'Mis tíos tienen dos hijos.', tr: 'Amcamların iki çocuğu var.' },
      { es: 'Es el hijo de mi vecino.', tr: 'Bu komşumun oğlu.' },
    ],
    esdizim: ['hijo único', 'tener hijos'], aile: ['el padre', 'la madre'],
    hata: 'İki kuralı aynı kelimede uygulamayı unutmak: baştaki "h" okunmaz, ortadaki "j" gırtlaktan gelir.',
    hatirlatma: '"los hijos" hem "oğullar" hem "çocuklar" anlamına gelir.',
    uretim: { yonerge: '"Bu komşumun oğlu." cümlesini yaz.', kabul: ['Es el hijo de mi vecino'] },
  },
  {
    id: 'es-abuelo', dil: 'es', kelime: 'abuelo / abuela', artikel: 'el', cins: 'eril', cogul: 'los abuelos',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'El padre o la madre de tus padres.',
    turkceDestek: 'dede / nine', ipa: '/a.ˈβwe.lo/', heceler: 'a-bue-lo (vurgu: BUE)',
    ornekler: [
      { es: 'Mis abuelos viven en un pueblo.', tr: 'Dedem ve ninem bir köyde yaşıyor.' },
      { es: 'Mi abuela cocina muy bien.', tr: 'Ninem çok iyi yemek yapar.' },
    ],
    esdizim: ['los abuelos', 'la casa de los abuelos'], aile: ['el nieto', 'la familia'],
    hata: 'Çoğulunda karışık grup olduğunda dişil kullanmak: dede ve nine birlikte "los abuelos"tur.',
    hatirlatma: 'Torun "el nieto / la nieta"dır.',
    uretim: { yonerge: '"Dedem ve ninem bir köyde yaşıyor." cümlesini yaz.', kabul: ['Mis abuelos viven en un pueblo'] },
  },
  {
    id: 'es-casa', dil: 'es', kelime: 'casa', artikel: 'la', cins: 'disil', cogul: 'las casas',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'El edificio donde vive una familia.',
    turkceDestek: 'ev', ipa: '/ˈka.sa/', heceler: 'ca-sa (vurgu: CA)',
    ornekler: [
      { es: 'Nuestra casa está cerca del instituto.', tr: 'Evimiz liseye yakın.' },
      { es: 'Vuelvo a casa a las seis.', tr: 'Eve saat altıda dönüyorum.' },
    ],
    esdizim: ['en casa', 'volver a casa', 'la casa de'],
    aile: ['el piso', 'la habitación'],
    hata: '"en casa" ifadesinde artikel kullanmak. "Estoy en casa" doğrudur; "estoy en la casa" başka bir evi işaret eder.',
    hatirlatma: 'Yer bildirdiği için hep "estar" ile kullanılır: la casa ESTÁ cerca.',
    uretim: { yonerge: '"Evdeyim." cümlesini yaz.', kabul: ['Estoy en casa'] },
  },
  {
    id: 'es-habitacion', dil: 'es', kelime: 'habitación', artikel: 'la', cins: 'disil', cogul: 'las habitaciones',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'La parte de la casa donde dormimos.',
    turkceDestek: 'oda', ipa: '/a.βi.ta.ˈθjon/', heceler: 'ha-bi-ta-ción (h okunmaz, vurgu sonda)',
    ornekler: [
      { es: 'Mi habitación es pequeña pero bonita.', tr: 'Odam küçük ama şirin.' },
      { es: '¡Ordena tu habitación!', tr: 'Odanı topla!' },
    ],
    esdizim: ['ordenar la habitación', 'una habitación doble'],
    aile: ['la casa', 'el cuarto'],
    hata: 'Çoğulda aksanı bırakmak: tekilde "habitación" aksanlı, çoğulda "habitaciones" AKSANSIZDIR. Çoğul eki vurguyu kuralın içine sokar.',
    hatirlatma: '-ción ile biten bütün isimler dişildir ve bu ek çok yaygındır.',
    uretim: { yonerge: '"Odam küçük." cümlesini yaz.', kabul: ['Mi habitación es pequeña'] },
  },
  {
    id: 'es-libro', dil: 'es', kelime: 'libro', artikel: 'el', cins: 'eril', cogul: 'los libros',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'Un objeto con páginas que leemos.',
    turkceDestek: 'kitap', ipa: '/ˈli.βɾo/', heceler: 'li-bro',
    ornekler: [
      { es: 'Leo un libro en español.', tr: 'İspanyolca bir kitap okuyorum.' },
      { es: 'El libro está encima de la mesa.', tr: 'Kitap masanın üstünde.' },
    ],
    esdizim: ['leer un libro', 'el libro de texto'], aile: ['leer', 'la librería'],
    hata: '"la librería" kelimesini "kütüphane" sanmak. Librería = kitapçı, biblioteca = kütüphane. Klasik yanlış dost.',
    hatirlatma: 'Yer bildirdiği için "estar" ile: el libro ESTÁ en la mesa.',
    uretim: { yonerge: '"Bir kitap okuyorum." cümlesini yaz.', kabul: ['Leo un libro'] },
  },
  {
    id: 'es-mesa', dil: 'es', kelime: 'mesa', artikel: 'la', cins: 'disil', cogul: 'las mesas',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'Un mueble donde comemos o trabajamos.',
    turkceDestek: 'masa', ipa: '/ˈme.sa/', heceler: 'me-sa',
    ornekler: [
      { es: 'Hay un libro en la mesa.', tr: 'Masada bir kitap var.' },
      { es: 'Comemos en la mesa grande.', tr: 'Büyük masada yemek yiyoruz.' },
    ],
    esdizim: ['poner la mesa', 'en la mesa'], aile: ['la silla', 'el escritorio'],
    hata: '"var" demek için "está" kullanmak: "Está un libro en la mesa" yanlıştır; doğrusu "HAY un libro en la mesa".',
    hatirlatma: 'Türkçedeki "masa" ile neredeyse aynı; öğrenmesi kolay kelimelerden.',
    uretim: { yonerge: '"Masada bir kitap var." cümlesini yaz.', kabul: ['Hay un libro en la mesa'] },
  },
  {
    id: 'es-perro', dil: 'es', kelime: 'perro / perra', artikel: 'el', cins: 'eril', cogul: 'los perros',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'Un animal doméstico que ladra.',
    turkceDestek: 'köpek', ipa: '/ˈpe.ro/', heceler: 'pe-rro (çift r TİTREŞİMLİ)',
    ornekler: [
      { es: 'Tenemos un perro negro.', tr: 'Siyah bir köpeğimiz var.' },
      { es: 'El perro de mi vecino es muy tranquilo.', tr: 'Komşumun köpeği çok sakin.' },
    ],
    esdizim: ['pasear al perro', 'un perro guardián'], aile: ['el gato', 'el animal'],
    hata: '"perro" ile "pero" (ama) karıştırmak. Tek "r" ile yazılırsa bambaşka bir kelimedir; titreşim anlam ayırır.',
    hatirlatma: 'Renk sıfatı isimden sonra gelir: un perro NEGRO.',
    uretim: { yonerge: '"Siyah bir köpeğimiz var." cümlesini yaz.', kabul: ['Tenemos un perro negro'] },
  },
  {
    id: 'es-gato', dil: 'es', kelime: 'gato / gata', artikel: 'el', cins: 'eril', cogul: 'los gatos',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'Un pequeño animal doméstico que maúlla.',
    turkceDestek: 'kedi', ipa: '/ˈɡa.to/', heceler: 'ga-to',
    ornekler: [
      { es: 'Mi gato duerme en el sofá.', tr: 'Kedim kanepede uyuyor.' },
      { es: 'Me gustan mucho los gatos.', tr: 'Kedileri çok severim.' },
    ],
    esdizim: ['un gato blanco', 'tener un gato'], aile: ['el perro', 'el animal'],
    hata: '"Me gusta los gatos" demek. Sevilen şey çoğulsa fiil de çoğul olur: "me gustAN los gatos".',
    hatirlatma: 'Genel beğenide belirli artikel kullanılır: me gustan LOS gatos.',
    uretim: { yonerge: '"Kedileri severim." cümlesini yaz.', kabul: ['Me gustan los gatos'] },
  },
  {
    id: 'es-coche', dil: 'es', kelime: 'coche', artikel: 'el', cins: 'eril', cogul: 'los coches',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'Un vehículo de cuatro ruedas para viajar.',
    turkceDestek: 'araba', ipa: '/ˈko.tʃe/', heceler: 'co-che ("ch" → Türkçedeki "ç")',
    ornekler: [
      { es: 'Mi padre tiene un coche rojo.', tr: 'Babamın kırmızı bir arabası var.' },
      { es: 'Voy al instituto en coche.', tr: 'Liseye arabayla gidiyorum.' },
    ],
    esdizim: ['en coche', 'conducir un coche'], aile: ['el autobús', 'el tren'],
    hata: 'Ulaşımda "con" kullanmak: "con el coche" değil, "EN coche".',
    hatirlatma: 'Latin Amerika\'da "el carro" ya da "el auto" denir; üçü de doğrudur.',
    uretim: { yonerge: '"Kırmızı bir araba" ifadesini yaz.', kabul: ['un coche rojo'] },
  },
  {
    id: 'es-problema', dil: 'es', kelime: 'problema', artikel: 'el', cins: 'eril', cogul: 'los problemas',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'Una situación difícil que hay que resolver.',
    turkceDestek: 'sorun, problem', ipa: '/pɾo.ˈβle.ma/', heceler: 'pro-ble-ma (vurgu: BLE)',
    ornekler: [
      { es: 'No hay problema.', tr: 'Sorun yok.' },
      { es: 'Tenemos un problema con el ordenador.', tr: 'Bilgisayarla ilgili bir sorunumuz var.' },
    ],
    esdizim: ['no hay problema', 'resolver un problema'], aile: ['el tema', 'el sistema'],
    hata: '-a ile bittiği için dişil sanmak: "la problema" YANLIŞTIR. Yunanca kökenli -ma isimleri erildir: el problema, el tema, el idioma, el sistema.',
    hatirlatma: 'Bu grup küçüktür ama çok kullanılır; hepsini birlikte ezberlemek en kolayıdır.',
    uretim: { yonerge: '"Sorun yok." cümlesini yaz.', kabul: ['No hay problema'] },
  },
  {
    id: 'es-grande', dil: 'es', kelime: 'grande', tur: 'sifat', seviye: 'A1',
    ispanyolcaTanim: 'De tamaño importante; lo contrario de pequeño.',
    turkceDestek: 'büyük', ipa: '/ˈɡɾan.de/', heceler: 'gran-de',
    ornekler: [
      { es: 'Madrid es una ciudad muy grande.', tr: 'Madrid çok büyük bir şehir.' },
      { es: 'Tengo una familia grande.', tr: 'Büyük bir ailem var.' },
    ],
    esdizim: ['muy grande', 'una gran ciudad'], aile: ['pequeño', 'el tamaño'],
    hata: 'İsimden önce geldiğinde biçim değiştiğini bilmemek: "una gran ciudad" (büyük/önemli şehir) — sondaki -de düşer.',
    hatirlatma: '-e ile bittiği için cinse göre değişmez: un coche grande / una casa grande. Yalnız çoğulda -s alır.',
    uretim: { yonerge: '"Büyük bir şehir" ifadesini yaz.', kabul: ['una ciudad grande'] },
  },
  {
    id: 'es-pequeno', dil: 'es', kelime: 'pequeño / pequeña', tur: 'sifat', seviye: 'A1',
    ispanyolcaTanim: 'De tamaño reducido; lo contrario de grande.',
    turkceDestek: 'küçük', ipa: '/pe.ˈke.ɲo/', heceler: 'pe-que-ño ("qu" → k, "ñ" → ny)',
    ornekler: [
      { es: 'Mi habitación es pequeña.', tr: 'Odam küçük.' },
      { es: 'Vivimos en un pueblo pequeño.', tr: 'Küçük bir kasabada yaşıyoruz.' },
    ],
    esdizim: ['muy pequeño', 'de pequeño'], aile: ['grande', 'el tamaño'],
    hata: 'Dişile uydurmayı unutmak: "Mi habitación es pequeño" değil, "pequeña".',
    hatirlatma: '"de pequeño" = "küçükken" demektir; çocukluk anlatırken çok kullanılır.',
    uretim: { yonerge: '"Odam küçük." cümlesini yaz.', kabul: ['Mi habitación es pequeña'] },
  },
  {
    id: 'es-simpatico', dil: 'es', kelime: 'simpático / simpática', tur: 'sifat', seviye: 'A1',
    ispanyolcaTanim: 'Persona agradable, con la que da gusto estar.',
    turkceDestek: 'cana yakın, sempatik', ipa: '/sim.ˈpa.ti.ko/', heceler: 'sim-pá-ti-co (vurgu aksanla gösterilir)',
    ornekler: [
      { es: 'Mi profesora es muy simpática.', tr: 'Öğretmenim çok cana yakın.' },
      { es: 'Sus amigos son simpáticos.', tr: 'Arkadaşları cana yakın.' },
    ],
    esdizim: ['muy simpático', 'una persona simpática'], aile: ['amable', 'antipático'],
    hata: 'İngilizcedeki "sympathetic" ile karıştırıp "anlayışlı" sanmak. İspanyolcada "simpático" cana yakın, hoş demektir.',
    hatirlatma: 'Aksan vurgunun sondan üçüncü hecede olduğunu gösterir; bu tür kelimeler her zaman aksanlıdır.',
    uretim: { yonerge: '"Annem çok cana yakın." cümlesini yaz.', kabul: ['Mi madre es muy simpática'] },
  },
  {
    id: 'es-alto', dil: 'es', kelime: 'alto / alta', tur: 'sifat', seviye: 'A1',
    ispanyolcaTanim: 'De gran estatura o altura.',
    turkceDestek: 'uzun boylu, yüksek', ipa: '/ˈal.to/', heceler: 'al-to',
    ornekler: [
      { es: 'Mi hermano es alto.', tr: 'Ağabeyim uzun boylu.' },
      { es: 'Las montañas son muy altas.', tr: 'Dağlar çok yüksek.' },
    ],
    esdizim: ['muy alto', 'en voz alta'], aile: ['bajo', 'la altura'],
    hata: 'Boy söylerken "ser" yerine "estar" kullanmak. Boy KALICI bir özelliktir: "Es alto", "Está alto" değil.',
    hatirlatma: 'Karşıtı "bajo"dur (kısa boylu, alçak).',
    uretim: { yonerge: '"Ağabeyim uzun boylu." cümlesini yaz.', kabul: ['Mi hermano es alto', 'Mi hermano mayor es alto'] },
  },
  {
    id: 'es-hay', dil: 'es', kelime: 'hay', tur: 'kalip', seviye: 'A1',
    ispanyolcaTanim: 'Forma que indica que algo existe en un lugar.',
    turkceDestek: 'var', ipa: '/ai/', heceler: 'hay (h okunmaz: "ay")',
    ornekler: [
      { es: 'Hay tres habitaciones en mi casa.', tr: 'Evimde üç oda var.' },
      { es: 'No hay pan.', tr: 'Ekmek yok.' },
    ],
    esdizim: ['hay que', '¿qué hay?', 'no hay de qué'],
    aile: ['haber', 'estar', 'tener'],
    hata: 'Tekil-çoğul için ayrı biçim aramak. "Hay" hiç değişmez: hay un libro / hay tres libros.',
    hatirlatma: 'Üç kavramı ayır: hay (var, belirsiz) · está (bilinen şeyin yeri) · tiene (sahiplik).',
    uretim: { yonerge: '"Evimde üç oda var." cümlesini yaz.', kabul: ['Hay tres habitaciones en mi casa'] },
  },
  {
    id: 'es-mi', dil: 'es', kelime: 'mi / mis', tur: 'sifat', seviye: 'A1',
    ispanyolcaTanim: 'Palabra que indica que algo pertenece a la persona que habla.',
    turkceDestek: 'benim', ipa: '/mi/', heceler: 'mi (aksansız — "mí" ise "bana" demektir)',
    ornekler: [
      { es: 'Mi hermano y mis padres viven aquí.', tr: 'Kardeşim ve annem babam burada yaşıyor.' },
      { es: 'Mis amigos son muy simpáticos.', tr: 'Arkadaşlarım çok cana yakın.' },
    ],
    esdizim: ['mi casa', 'mis padres'], aile: ['tu', 'su', 'nuestro'],
    hata: 'Fransızcadaki gibi cinse uydurmaya çalışmak. İspanyolcada iyelik sıfatı yalnız SAYIYA uyar: mi hermano / mi hermana ama mis hermanos.',
    hatirlatma: 'Aksanlı "mí" bambaşka bir kelimedir: "a mí me gusta" (bana hoş geliyor).',
    uretim: { yonerge: '"Kardeşlerim burada yaşıyor." cümlesini yaz.', kabul: ['Mis hermanos viven aquí'] },
  },
  {
    id: 'es-no', dil: 'es', kelime: 'no', tur: 'zarf', seviye: 'A1',
    ispanyolcaTanim: 'Palabra que sirve para negar.',
    turkceDestek: 'hayır; değil, -me/-ma', ipa: '/no/', heceler: 'no (tek hece)',
    ornekler: [
      { es: 'No entiendo la pregunta.', tr: 'Soruyu anlamıyorum.' },
      { es: 'No, gracias.', tr: 'Hayır, teşekkürler.' },
    ],
    esdizim: ['no… nada', 'no… nunca', 'no, gracias'],
    aile: ['nada', 'nunca', 'nadie'],
    hata: 'Fransızcadaki gibi iki parçalı olumsuzluk aramak. İspanyolcada olumsuzluk TEK kelimedir ve fiilin ÖNÜNE gelir: "No entiendo".',
    hatirlatma: 'İyi haber: çift olumsuzluk DOĞRUDUR ve Türkçedeki gibi çalışır: "No sé nada" = hiçbir şey bilmiyorum.',
    uretim: { yonerge: '"Anlamıyorum." cümlesini yaz.', kabul: ['No entiendo'] },
  },
  {
    id: 'es-tambien', dil: 'es', kelime: 'también', tur: 'zarf', seviye: 'A1',
    ispanyolcaTanim: 'Palabra que indica que algo se añade a lo dicho antes.',
    turkceDestek: 'de, da; ayrıca', ipa: '/tam.ˈbjen/', heceler: 'tam-bién (vurgu sonda, aksanlı)',
    ornekler: [
      { es: 'Yo también hablo inglés.', tr: 'Ben de İngilizce konuşuyorum.' },
      { es: 'Mi hermana también estudia español.', tr: 'Kız kardeşim de İspanyolca çalışıyor.' },
    ],
    esdizim: ['yo también', 'y también'], aile: ['tampoco', 'además'],
    hata: 'Olumsuz cümlede kullanmak: "Yo también no" yanlıştır. Olumsuzda "tampoco" kullanılır: "Yo tampoco".',
    hatirlatma: 'Bu, "yo" zamirinin doğal olarak kullanıldığı yerlerden biridir: "Yo también" (ben de).',
    uretim: { yonerge: '"Ben de İngilizce konuşuyorum." cümlesini yaz.', kabul: ['Yo también hablo inglés', 'También hablo inglés'] },
  },
]
