/**
 * A1 — GÜNLÜK RUTİN
 * ==================================================================
 *
 * Bu havuz FİİL havuzudur ve İspanyolcanın kalbi buradadır: fiil kişiye
 * göre çekilir, bu yüzden özne zamiri gereksizdir. Türkçede de öyle
 * olduğu için bu bölüm Türk öğrenciye kolay gelir — ama İngilizceden
 * gelen "yo" alışkanlığı bozar. `hata` alanı bunu her kelimede hatırlatır.
 *
 * DÖNÜŞLÜ FİİLLER (levantarse, acostarse) ayrı işaretlendi: Türkçede
 * "-in-" eki neyse İspanyolcada "se" odur, ama İspanyolcada AYRI yazılır
 * ve kişiye göre değişir (me levanto, te levantas…).
 */

export const KELIMELER = [
  {
    id: 'es-levantarse', dil: 'es', kelime: 'levantarse', tur: 'fiil', seviye: 'A1',
    duzensiz: false, cekim: 'me levanto · te levantas · se levanta · nos levantamos · os levantáis · se levantan',
    ispanyolcaTanim: 'Salir de la cama por la mañana.',
    turkceDestek: 'kalkmak (yataktan)', ipa: '/le.βan.ˈtaɾ.se/', heceler: 'le-van-tar-se (vurgu: TAR)',
    ornekler: [
      { es: 'Me levanto a las siete.', tr: 'Yedide kalkıyorum.' },
      { es: '¿A qué hora te levantas los domingos?', tr: 'Pazarları saat kaçta kalkıyorsun?' },
    ],
    esdizim: ['levantarse temprano', 'levantarse tarde'], aile: ['acostarse', 'despertarse'],
    hata: '"se" ekini unutmak: "Levanto a las siete" demek "Yediyi kaldırıyorum" gibi eksik kalır. Doğrusu "ME levanto".',
    hatirlatma: 'Dönüşlü ek kişiye göre değişir ve fiilin ÖNÜNE gelir: me / te / se / nos / os / se.',
    uretim: { yonerge: '"Yedide kalkıyorum." cümlesini yaz.', kabul: ['Me levanto a las siete'] },
  },
  {
    id: 'es-desayunar', dil: 'es', kelime: 'desayunar', tur: 'fiil', seviye: 'A1',
    duzensiz: false, cekim: 'desayuno · desayunas · desayuna · desayunamos · desayunáis · desayunan',
    ispanyolcaTanim: 'Tomar la primera comida del día.',
    turkceDestek: 'kahvaltı yapmak', ipa: '/de.sa.ʝu.ˈnaɾ/', heceler: 'de-sa-yu-nar (vurgu: NAR)',
    ornekler: [
      { es: 'Desayuno pan con queso.', tr: 'Peynirli ekmekle kahvaltı yapıyorum.' },
      { es: 'No desayunamos en casa los lunes.', tr: 'Pazartesileri evde kahvaltı yapmıyoruz.' },
    ],
    esdizim: ['desayunar fuerte', 'el desayuno'], aile: ['comer', 'cenar', 'almorzar'],
    hata: '"hacer desayuno" demek. İspanyolcada kahvaltı yapmak tek fiildir: desayunar.',
    hatirlatma: 'Üç öğünün üçü de fiildir: desayunar (sabah), comer/almorzar (öğle), cenar (akşam).',
    uretim: { yonerge: '"Sekizde kahvaltı yapıyorum." cümlesini yaz.', kabul: ['Desayuno a las ocho'] },
  },
  {
    id: 'es-ir', dil: 'es', kelime: 'ir', tur: 'fiil', seviye: 'A1',
    duzensiz: true, cekim: 'voy · vas · va · vamos · vais · van',
    ispanyolcaTanim: 'Moverse de un lugar a otro.',
    turkceDestek: 'gitmek', ipa: '/iɾ/', heceler: 'ir (tek hece)',
    ornekler: [
      { es: 'Voy al colegio en autobús.', tr: 'Okula otobüsle gidiyorum.' },
      { es: 'Vamos a estudiar esta tarde.', tr: 'Bu öğleden sonra çalışacağız.' },
    ],
    esdizim: ['ir a', 'ir en autobús', 'ir de compras'], aile: ['venir', 'volver'],
    hata: 'Mastarın çekimle hiç benzememesi: "iro" diye bir biçim YOKTUR, doğrusu "voy". Bu fiil baştan sona ezberlenir.',
    hatirlatma: '"ir a + mastar" gelecek zaman kurar: Voy a comer = Yemek yiyeceğim.',
    uretim: { yonerge: '"Okula gidiyorum." cümlesini yaz.', kabul: ['Voy al colegio', 'Voy a la escuela'] },
  },
  {
    id: 'es-hacer', dil: 'es', kelime: 'hacer', tur: 'fiil', seviye: 'A1',
    duzensiz: true, cekim: 'hago · haces · hace · hacemos · hacéis · hacen',
    ispanyolcaTanim: 'Realizar una acción o crear algo.',
    turkceDestek: 'yapmak, etmek', ipa: '/a.ˈθeɾ/ · Latin Amerika /a.ˈseɾ/', heceler: 'ha-cer (baştaki h okunmaz)',
    ornekler: [
      { es: '¿Qué haces los fines de semana?', tr: 'Hafta sonları ne yapıyorsun?' },
      { es: 'Hago los deberes por la tarde.', tr: 'Ödevleri öğleden sonra yapıyorum.' },
    ],
    esdizim: ['hacer los deberes', 'hacer deporte', 'hace calor'], aile: ['el hecho', 'deshacer'],
    hata: 'Birinci tekil kişiyi düzenli sanmak: "haco" YANLIŞTIR, doğrusu "hago".',
    hatirlatma: 'Hava durumunda da bu fiil kullanılır: hace frío, hace sol, hace calor.',
    uretim: { yonerge: '"Spor yapıyorum." cümlesini yaz.', kabul: ['Hago deporte'] },
  },
  {
    id: 'es-estudiar', dil: 'es', kelime: 'estudiar', tur: 'fiil', seviye: 'A1',
    duzensiz: false, cekim: 'estudio · estudias · estudia · estudiamos · estudiáis · estudian',
    ispanyolcaTanim: 'Aprender algo leyendo, escuchando o practicando.',
    turkceDestek: 'ders çalışmak, okumak (öğrenim görmek)', ipa: '/es.tu.ˈðjaɾ/', heceler: 'es-tu-diar (vurgu: DIAR)',
    ornekler: [
      { es: 'Estudio español todos los días.', tr: 'Her gün İspanyolca çalışıyorum.' },
      { es: 'Mi hermana estudia medicina.', tr: 'Ablam tıp okuyor.' },
    ],
    esdizim: ['estudiar para el examen', 'estudiar en la universidad'], aile: ['el estudiante', 'el estudio'],
    hata: '"leer" ile karıştırmak. "Okumak" Türkçede iki anlamlıdır: metni okumak → leer, öğrenim görmek → estudiar.',
    hatirlatma: 'Dil adları küçük harfle yazılır: estudio español, no Español.',
    uretim: { yonerge: '"Her gün İspanyolca çalışıyorum." cümlesini yaz.', kabul: ['Estudio español todos los días'] },
  },
  {
    id: 'es-comer', dil: 'es', kelime: 'comer', tur: 'fiil', seviye: 'A1',
    duzensiz: false, cekim: 'como · comes · come · comemos · coméis · comen',
    ispanyolcaTanim: 'Tomar alimentos; en España, la comida del mediodía.',
    turkceDestek: 'yemek yemek; öğle yemeği yemek', ipa: '/ko.ˈmeɾ/', heceler: 'co-mer (vurgu: MER)',
    ornekler: [
      { es: 'Comemos a las dos.', tr: 'İkide öğle yemeği yiyoruz.' },
      { es: 'No como carne.', tr: 'Et yemiyorum.' },
    ],
    esdizim: ['comer fuera', 'la comida'], aile: ['la comida', 'cenar'],
    hata: 'İspanya\'da "comer"in saat 14:00 civarındaki ÖĞLE yemeği demek olduğunu bilmemek. Akşam yemeği "cenar"dır.',
    hatirlatma: 'Bu fiil -er grubunun örnek fiilidir; çekimi ezberlersen bütün -er fiillerini çekersin.',
    uretim: { yonerge: '"İkide yemek yiyoruz." cümlesini yaz.', kabul: ['Comemos a las dos'] },
  },
  {
    id: 'es-trabajar', dil: 'es', kelime: 'trabajar', tur: 'fiil', seviye: 'A1',
    duzensiz: false, cekim: 'trabajo · trabajas · trabaja · trabajamos · trabajáis · trabajan',
    ispanyolcaTanim: 'Hacer una actividad por la que se gana dinero.',
    turkceDestek: 'çalışmak (iş)', ipa: '/tɾa.βa.ˈxaɾ/', heceler: 'tra-ba-jar ("j" gırtlaktan)',
    ornekler: [
      { es: 'Mi madre trabaja en un hospital.', tr: 'Annem bir hastanede çalışıyor.' },
      { es: 'No trabajo los domingos.', tr: 'Pazarları çalışmıyorum.' },
    ],
    esdizim: ['trabajar en', 'trabajar de'], aile: ['el trabajo', 'el trabajador'],
    hata: '"Ders çalışmak" için bu fiili kullanmak. Ders çalışmak → estudiar; işe gitmek → trabajar.',
    hatirlatma: 'Meslek söylerken artikel kullanılmaz: Trabaja de profesor (un profesor değil).',
    uretim: { yonerge: '"Annem bir hastanede çalışıyor." cümlesini yaz.', kabul: ['Mi madre trabaja en un hospital'] },
  },
  {
    id: 'es-volver', dil: 'es', kelime: 'volver', tur: 'fiil', seviye: 'A1',
    duzensiz: true, cekim: 'vuelvo · vuelves · vuelve · volvemos · volvéis · vuelven',
    ispanyolcaTanim: 'Regresar al lugar de donde se salió.',
    turkceDestek: 'dönmek, geri gelmek', ipa: '/bol.ˈβeɾ/', heceler: 'vol-ver ("v" Türkçedeki "b"ye yakın)',
    ornekler: [
      { es: 'Vuelvo a casa a las cinco.', tr: 'Eve beşte dönüyorum.' },
      { es: '¿Cuándo vuelves de Madrid?', tr: 'Madrid\'den ne zaman dönüyorsun?' },
    ],
    esdizim: ['volver a casa', 'volver a + mastar'], aile: ['ir', 'venir'],
    hata: 'Kök değişimini kaçırmak: "volvo" değil "VUELVO". Vurgulu hecede o → ue olur, biz/siz biçimlerinde olmaz.',
    hatirlatma: '"volver a + mastar" = yeniden yapmak: Vuelvo a leer = Yeniden okuyorum.',
    uretim: { yonerge: '"Eve beşte dönüyorum." cümlesini yaz.', kabul: ['Vuelvo a casa a las cinco'] },
  },
  {
    id: 'es-acostarse', dil: 'es', kelime: 'acostarse', tur: 'fiil', seviye: 'A1',
    duzensiz: true, cekim: 'me acuesto · te acuestas · se acuesta · nos acostamos · os acostáis · se acuestan',
    ispanyolcaTanim: 'Meterse en la cama para dormir.',
    turkceDestek: 'yatmak (uyumak için)', ipa: '/a.kos.ˈtaɾ.se/', heceler: 'a-cos-tar-se',
    ornekler: [
      { es: 'Me acuesto a las once.', tr: 'On birde yatıyorum.' },
      { es: 'Los niños se acuestan temprano.', tr: 'Çocuklar erken yatıyor.' },
    ],
    esdizim: ['acostarse temprano', 'acostarse tarde'], aile: ['levantarse', 'dormir'],
    hata: 'Hem "se"yi hem kök değişimini birden kaçırmak: doğrusu "me ACUESTO".',
    hatirlatma: 'Yatmak (acostarse) ile uyumak (dormir) ayrı fiillerdir; Türkçede ikisi de "yatmak" sanılır.',
    uretim: { yonerge: '"On birde yatıyorum." cümlesini yaz.', kabul: ['Me acuesto a las once'] },
  },
  {
    id: 'es-dormir', dil: 'es', kelime: 'dormir', tur: 'fiil', seviye: 'A1',
    duzensiz: true, cekim: 'duermo · duermes · duerme · dormimos · dormís · duermen',
    ispanyolcaTanim: 'Descansar con los ojos cerrados durante la noche.',
    turkceDestek: 'uyumak', ipa: '/doɾ.ˈmiɾ/', heceler: 'dor-mir',
    ornekler: [
      { es: 'Duermo ocho horas.', tr: 'Sekiz saat uyuyorum.' },
      { es: 'Mi hermano duerme mucho los sábados.', tr: 'Kardeşim cumartesileri çok uyuyor.' },
    ],
    esdizim: ['dormir bien', 'dormir la siesta'], aile: ['acostarse', 'el sueño'],
    hata: 'Kök değişimini unutmak: "dormo" değil "DUERMO".',
    hatirlatma: '"dormir la siesta" İspanyol kültürünün öğle uykusudur; sınav metinlerinde sık geçer.',
    uretim: { yonerge: '"Sekiz saat uyuyorum." cümlesini yaz.', kabul: ['Duermo ocho horas'] },
  },
  {
    id: 'es-empezar', dil: 'es', kelime: 'empezar', tur: 'fiil', seviye: 'A1',
    duzensiz: true, cekim: 'empiezo · empiezas · empieza · empezamos · empezáis · empiezan',
    ispanyolcaTanim: 'Dar comienzo a algo.',
    turkceDestek: 'başlamak', ipa: '/em.pe.ˈθaɾ/', heceler: 'em-pe-zar',
    ornekler: [
      { es: 'Las clases empiezan a las ocho.', tr: 'Dersler sekizde başlıyor.' },
      { es: 'Empiezo a estudiar ahora.', tr: 'Şimdi çalışmaya başlıyorum.' },
    ],
    esdizim: ['empezar a + mastar', 'empezar la clase'], aile: ['terminar', 'el comienzo'],
    hata: '"empezar" ile mastarı doğrudan bağlamak: "Empiezo estudiar" YANLIŞ. Araya "a" girer: "Empiezo A estudiar".',
    hatirlatma: 'Kök değişimi e → ie\'dir ve yalnız vurgulu hecelerde olur.',
    uretim: { yonerge: '"Dersler sekizde başlıyor." cümlesini yaz.', kabul: ['Las clases empiezan a las ocho'] },
  },
  {
    id: 'es-salir', dil: 'es', kelime: 'salir', tur: 'fiil', seviye: 'A1',
    duzensiz: true, cekim: 'salgo · sales · sale · salimos · salís · salen',
    ispanyolcaTanim: 'Ir fuera de un lugar.',
    turkceDestek: 'çıkmak, dışarı çıkmak', ipa: '/sa.ˈliɾ/', heceler: 'sa-lir',
    ornekler: [
      { es: 'Salgo de casa a las siete y media.', tr: 'Evden yedi buçukta çıkıyorum.' },
      { es: 'Los viernes salimos con los amigos.', tr: 'Cumaları arkadaşlarla dışarı çıkıyoruz.' },
    ],
    esdizim: ['salir de casa', 'salir con amigos'], aile: ['entrar', 'la salida'],
    hata: 'Birinci tekil kişide "g" harfini atlamak: "salo" değil "SALGO".',
    hatirlatma: 'Nereden çıkıldığı "de" ile söylenir: salgo DE casa.',
    uretim: { yonerge: '"Evden yedide çıkıyorum." cümlesini yaz.', kabul: ['Salgo de casa a las siete'] },
  },
  {
    id: 'es-dia', dil: 'es', kelime: 'día', artikel: 'el', cins: 'eril', cogul: 'los días',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'Periodo de veinticuatro horas.',
    turkceDestek: 'gün', ipa: '/ˈdi.a/', heceler: 'dí-a (aksan vurguyu DI hecesine sabitler)',
    ornekler: [
      { es: 'Estudio todos los días.', tr: 'Her gün çalışıyorum.' },
      { es: '¿Qué día es hoy?', tr: 'Bugün günlerden ne?' },
    ],
    esdizim: ['todos los días', 'buenos días', 'el día siguiente'], aile: ['la semana', 'el mes'],
    hata: '-a ile bittiği için dişil sanmak: "la día" YANLIŞTIR. Doğrusu EL día.',
    hatirlatma: 'Gün adları küçük harfle yazılır ve artikel alır: el lunes = pazartesi günü.',
    uretim: { yonerge: '"Her gün çalışıyorum." cümlesini yaz.', kabul: ['Estudio todos los días'] },
  },
  {
    id: 'es-manana', dil: 'es', kelime: 'mañana', artikel: 'la', cins: 'disil', cogul: 'las mañanas',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'La primera parte del día, antes del mediodía.',
    turkceDestek: 'sabah; (zarf olarak) yarın', ipa: '/ma.ˈɲa.na/', heceler: 'ma-ña-na ("ñ" → ny)',
    ornekler: [
      { es: 'Por la mañana tomo café.', tr: 'Sabahları kahve içiyorum.' },
      { es: 'Mañana tenemos examen.', tr: 'Yarın sınavımız var.' },
    ],
    esdizim: ['por la mañana', 'mañana por la mañana'], aile: ['la tarde', 'la noche'],
    hata: 'İki anlamı karıştırmak. Artikelle "la mañana" = sabah; artikelsiz "mañana" = yarın.',
    hatirlatma: 'Günün bölümleri "por" ile söylenir: por la mañana / por la tarde / por la noche.',
    uretim: { yonerge: '"Sabahları kahve içiyorum." cümlesini yaz.', kabul: ['Por la mañana tomo café'] },
  },
  {
    id: 'es-tarde', dil: 'es', kelime: 'tarde', artikel: 'la', cins: 'disil', cogul: 'las tardes',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'Parte del día entre el mediodía y la noche.',
    turkceDestek: 'öğleden sonra; (zarf olarak) geç', ipa: '/ˈtaɾ.ðe/', heceler: 'tar-de',
    ornekler: [
      { es: 'Por la tarde hago los deberes.', tr: 'Öğleden sonra ödevlerimi yapıyorum.' },
      { es: 'Llego tarde a clase.', tr: 'Derse geç kalıyorum.' },
    ],
    esdizim: ['por la tarde', 'buenas tardes', 'llegar tarde'], aile: ['la mañana', 'la noche'],
    hata: 'Zarf anlamıyla artikelli kullanmak: "Llego la tarde" değil, "Llego tarde".',
    hatirlatma: 'İspanya\'da "tarde" öğle yemeğinden akşam 20:00\'ye kadar sürer; bu yüzden 17:00\'de bile "buenas tardes" denir.',
    uretim: { yonerge: '"Öğleden sonra ders çalışıyorum." cümlesini yaz.', kabul: ['Por la tarde estudio'] },
  },
  {
    id: 'es-noche', dil: 'es', kelime: 'noche', artikel: 'la', cins: 'disil', cogul: 'las noches',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'Parte del día en la que no hay luz del sol.',
    turkceDestek: 'gece, akşam', ipa: '/ˈno.tʃe/', heceler: 'no-che ("ch" → ç)',
    ornekler: [
      { es: 'Por la noche leo un libro.', tr: 'Geceleri kitap okuyorum.' },
      { es: 'Buenas noches, hasta mañana.', tr: 'İyi geceler, yarın görüşürüz.' },
    ],
    esdizim: ['por la noche', 'buenas noches', 'esta noche'], aile: ['la tarde', 'dormir'],
    hata: '"ch" harfini Türkçedeki "h" gibi okumak. İspanyolcada "ch" her zaman Türkçedeki "Ç"dir: "noçe".',
    hatirlatma: '"Buenas noches" hem karşılaşmada hem ayrılırken kullanılır — Fransızcanın aksine.',
    uretim: { yonerge: '"Geceleri kitap okuyorum." cümlesini yaz.', kabul: ['Por la noche leo un libro'] },
  },
  {
    id: 'es-hora', dil: 'es', kelime: 'hora', artikel: 'la', cins: 'disil', cogul: 'las horas',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'Unidad de tiempo de sesenta minutos; también el momento del reloj.',
    turkceDestek: 'saat (süre ve zaman)', ipa: '/ˈo.ɾa/', heceler: 'ho-ra (baştaki h okunmaz)',
    ornekler: [
      { es: '¿Qué hora es?', tr: 'Saat kaç?' },
      { es: 'La clase dura una hora.', tr: 'Ders bir saat sürüyor.' },
    ],
    esdizim: ['¿qué hora es?', '¿a qué hora?', 'a la hora'], aile: ['el minuto', 'el reloj'],
    hata: 'Saati söylerken artikeli unutmak: "Son tres" değil, "Son LAS tres".',
    hatirlatma: 'Saat sorusu tekildir (¿Qué hora es?), cevabı biri hariç çoğuldur (Son las dos / Es la una).',
    uretim: { yonerge: '"Saat kaç?" sorusunu yaz.', kabul: ['¿Qué hora es?', 'Qué hora es'] },
  },
  {
    id: 'es-clase', dil: 'es', kelime: 'clase', artikel: 'la', cins: 'disil', cogul: 'las clases',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'Lección que da un profesor; también el aula y el grupo de alumnos.',
    turkceDestek: 'ders; sınıf', ipa: '/ˈkla.se/', heceler: 'cla-se',
    ornekler: [
      { es: 'Tengo clase de español los martes.', tr: 'Salı günleri İspanyolca dersim var.' },
      { es: 'En mi clase somos veinte.', tr: 'Sınıfımızda yirmi kişiyiz.' },
    ],
    esdizim: ['ir a clase', 'clase de español'], aile: ['el colegio', 'el profesor'],
    hata: '"Derse gidiyorum" derken artikel koymak. Kalıp artikelsizdir: "Voy A CLASE".',
    hatirlatma: 'Ders adı "de" ile bağlanır: la clase de matemáticas.',
    uretim: { yonerge: '"Derse gidiyorum." cümlesini yaz.', kabul: ['Voy a clase'] },
  },
  {
    id: 'es-fin-de-semana', dil: 'es', kelime: 'fin de semana', artikel: 'el', cins: 'eril', cogul: 'los fines de semana',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'El sábado y el domingo.',
    turkceDestek: 'hafta sonu', ipa: '/fin de se.ˈma.na/', heceler: 'fin de se-ma-na',
    ornekler: [
      { es: 'Los fines de semana juego al fútbol.', tr: 'Hafta sonları futbol oynuyorum.' },
      { es: '¡Buen fin de semana!', tr: 'İyi hafta sonları!' },
    ],
    esdizim: ['este fin de semana', 'los fines de semana'], aile: ['la semana', 'el sábado'],
    hata: 'Çoğulunu yanlış kurmak: "los fin de semanas" değil, "los FINES de semana" — çoğul eki BAŞ kelimeye gelir.',
    hatirlatma: '"Her hafta sonu" için artikel çoğul kullanılır: LOS fines de semana.',
    uretim: { yonerge: '"Hafta sonları futbol oynuyorum." cümlesini yaz.', kabul: ['Los fines de semana juego al fútbol'] },
  },
  {
    id: 'es-siempre', dil: 'es', kelime: 'siempre', tur: 'zarf', seviye: 'A1',
    ispanyolcaTanim: 'En todo momento, todas las veces.',
    turkceDestek: 'her zaman, hep', ipa: '/ˈsjem.pɾe/', heceler: 'siem-pre',
    ornekler: [
      { es: 'Siempre desayuno en casa.', tr: 'Her zaman evde kahvaltı yaparım.' },
      { es: 'Mi padre siempre llega temprano.', tr: 'Babam hep erken gelir.' },
    ],
    esdizim: ['casi siempre', 'para siempre'], aile: ['nunca', 'a veces'],
    hata: 'Cümlenin sonuna atmak. Sıklık zarfı genelde fiilden ÖNCE ya da öznenin hemen ardından gelir.',
    hatirlatma: 'Karşıtı "nunca"dır ve fiilden önce geldiğinde "no" gerekmez: Nunca desayuno.',
    uretim: { yonerge: '"Her zaman evde kahvaltı yaparım." cümlesini yaz.', kabul: ['Siempre desayuno en casa'] },
  },
  {
    id: 'es-nunca', dil: 'es', kelime: 'nunca', tur: 'zarf', seviye: 'A1',
    ispanyolcaTanim: 'En ningún momento.',
    turkceDestek: 'asla, hiç', ipa: '/ˈnuŋ.ka/', heceler: 'nun-ca',
    ornekler: [
      { es: 'Nunca llego tarde.', tr: 'Asla geç kalmam.' },
      { es: 'No como nunca carne.', tr: 'Hiçbir zaman et yemem.' },
    ],
    esdizim: ['casi nunca', 'nunca más'], aile: ['siempre', 'nada'],
    hata: '"No nunca" diye başlamak. Fiilden ÖNCE gelirse "no" kullanılmaz: "Nunca como carne". Fiilden SONRA gelirse "no" gerekir: "No como nunca carne".',
    hatirlatma: 'Çift olumsuzluk İspanyolcada doğrudur; Türkçedeki "hiç ... değil" mantığıyla aynıdır.',
    uretim: { yonerge: '"Asla geç kalmam." cümlesini yaz.', kabul: ['Nunca llego tarde'] },
  },
  {
    id: 'es-a-veces', dil: 'es', kelime: 'a veces', tur: 'zarf', seviye: 'A1',
    ispanyolcaTanim: 'En algunas ocasiones, no siempre.',
    turkceDestek: 'bazen', ipa: '/a ˈbe.θes/ · Latin Amerika /a ˈbe.ses/', heceler: 'a ve-ces',
    ornekler: [
      { es: 'A veces voy al cine.', tr: 'Bazen sinemaya giderim.' },
      { es: 'A veces estudiamos en la biblioteca.', tr: 'Bazen kütüphanede çalışırız.' },
    ],
    esdizim: ['a veces sí, a veces no', 'muchas veces'], aile: ['siempre', 'nunca', 'la vez'],
    hata: 'Tekil yazmak: "a vez" YANLIŞTIR, kalıp her zaman çoğuldur: a VECES.',
    hatirlatma: 'Sıklık merdiveni: siempre → normalmente → a veces → casi nunca → nunca.',
    uretim: { yonerge: '"Bazen sinemaya giderim." cümlesini yaz.', kabul: ['A veces voy al cine'] },
  },
]
