/**
 * A1 — ŞEHİR, YER VE YOL TARİFİ
 * ==================================================================
 *
 * Bu havuzun gizli konusu KAYNAŞMADIR: a + el = al, de + el = del.
 * Türkçede böyle bir kaynaşma yoktur ve öğrenci "a el banco" yazar.
 * Yer bildiren her kelimede bu hatırlatıldı.
 *
 * İkinci gizli konu ESTAR'dır: bir şeyin NEREDE olduğu her zaman "estar"
 * ile söylenir, "ser" ile değil. Bu havuzdaki örnek cümlelerin tamamı
 * bilinçli olarak "estar" ile kuruldu.
 */

export const KELIMELER = [
  {
    id: 'es-calle', dil: 'es', kelime: 'calle', artikel: 'la', cins: 'disil', cogul: 'las calles',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'Vía de una ciudad por donde pasan personas y coches.',
    turkceDestek: 'sokak, cadde', ipa: '/ˈka.ʝe/', heceler: 'ca-lle ("ll" → y)',
    ornekler: [
      { es: 'Vivo en la calle Mayor.', tr: 'Mayor Sokağı\'nda oturuyorum.' },
      { es: 'La farmacia está en esta calle.', tr: 'Eczane bu sokakta.' },
    ],
    esdizim: ['en la calle', 'la calle principal'], aile: ['la avenida', 'la plaza'],
    hata: '"ll" harfini Türkçedeki çift "l" gibi okumak. İspanyolcada "ll" tek sestir ve Türkçedeki "Y"ye çok yakındır: "kaye".',
    hatirlatma: 'Adres verirken artikel kullanılır: en LA calle Goya.',
    uretim: { yonerge: '"Mayor Sokağı\'nda oturuyorum." cümlesini yaz.', kabul: ['Vivo en la calle Mayor'] },
  },
  {
    id: 'es-plaza', dil: 'es', kelime: 'plaza', artikel: 'la', cins: 'disil', cogul: 'las plazas',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'Espacio abierto y grande en el centro de una ciudad.',
    turkceDestek: 'meydan', ipa: '/ˈpla.θa/ · Latin Amerika /ˈpla.sa/', heceler: 'pla-za',
    ornekler: [
      { es: 'La plaza está cerca del museo.', tr: 'Meydan müzenin yakınında.' },
      { es: 'Quedamos en la plaza a las seis.', tr: 'Altıda meydanda buluşuyoruz.' },
    ],
    esdizim: ['la plaza mayor', 'en la plaza'], aile: ['el parque', 'la calle'],
    hata: 'Buluşma yeri söylerken "en" yerine "a" kullanmak: "Quedamos a la plaza" değil, "EN la plaza".',
    hatirlatma: 'Her İspanyol şehrinin bir "Plaza Mayor"u vardır; okuma metinlerinde en sık geçen yerdir.',
    uretim: { yonerge: '"Meydan müzenin yakınında." cümlesini yaz.', kabul: ['La plaza está cerca del museo'] },
  },
  {
    id: 'es-parque', dil: 'es', kelime: 'parque', artikel: 'el', cins: 'eril', cogul: 'los parques',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'Lugar con árboles y bancos donde la gente pasea.',
    turkceDestek: 'park', ipa: '/ˈpaɾ.ke/', heceler: 'par-que ("qu" → k)',
    ornekler: [
      { es: 'Los sábados voy al parque.', tr: 'Cumartesileri parka giderim.' },
      { es: 'El parque está detrás del colegio.', tr: 'Park okulun arkasında.' },
    ],
    esdizim: ['ir al parque', 'en el parque'], aile: ['la plaza', 'el jardín'],
    hata: '"a el parque" yazmak. a + el kaynaşır ve tek kelime olur: AL parque.',
    hatirlatma: '"qu" harf grubu her zaman "k" okunur ve "u" sesi hiç duyulmaz.',
    uretim: { yonerge: '"Parka gidiyorum." cümlesini yaz.', kabul: ['Voy al parque'] },
  },
  {
    id: 'es-estacion', dil: 'es', kelime: 'estación', artikel: 'la', cins: 'disil', cogul: 'las estaciones',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'Lugar donde paran los trenes o los autobuses.',
    turkceDestek: 'istasyon, gar; (ayrıca) mevsim', ipa: '/es.ta.ˈθjon/', heceler: 'es-ta-ción (vurgu: CIÓN)',
    ornekler: [
      { es: '¿Dónde está la estación de tren?', tr: 'Tren garı nerede?' },
      { es: 'La estación está lejos de aquí.', tr: 'İstasyon buradan uzakta.' },
    ],
    esdizim: ['la estación de tren', 'la estación de autobuses'], aile: ['el tren', 'el metro'],
    hata: 'Çoğulda aksanı korumak: "estaciónes" YANLIŞ. Çoğulda vurgu kendiliğinden doğru heceye düştüğü için aksan DÜŞER: estaciones.',
    hatirlatma: '-ción ile biten bütün kelimeler dişildir; bu kural istisnasızdır ve çok işe yarar.',
    uretim: { yonerge: '"Tren garı nerede?" sorusunu yaz.', kabul: ['¿Dónde está la estación de tren?', 'Dónde está la estación de tren'] },
  },
  {
    id: 'es-mercado', dil: 'es', kelime: 'mercado', artikel: 'el', cins: 'eril', cogul: 'los mercados',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'Lugar donde se compran frutas, verduras y otros alimentos.',
    turkceDestek: 'pazar, çarşı', ipa: '/meɾ.ˈka.ðo/', heceler: 'mer-ca-do',
    ornekler: [
      { es: 'Mi madre va al mercado los sábados.', tr: 'Annem cumartesileri pazara gider.' },
      { es: 'En el mercado la fruta es más barata.', tr: 'Pazarda meyve daha ucuz.' },
    ],
    esdizim: ['ir al mercado', 'el mercado central'], aile: ['la tienda', 'comprar'],
    hata: '"Pazar günü" ile karıştırmak. Pazar günü → el domingo; alışveriş yeri → el mercado.',
    hatirlatma: 'Süpermarket "el supermercado"dur; aynı kökten gelir.',
    uretim: { yonerge: '"Pazara gidiyorum." cümlesini yaz.', kabul: ['Voy al mercado'] },
  },
  {
    id: 'es-tienda', dil: 'es', kelime: 'tienda', artikel: 'la', cins: 'disil', cogul: 'las tiendas',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'Establecimiento donde se venden cosas.',
    turkceDestek: 'dükkân, mağaza', ipa: '/ˈtjen.da/', heceler: 'tien-da',
    ornekler: [
      { es: 'La tienda abre a las nueve.', tr: 'Dükkân dokuzda açılıyor.' },
      { es: 'Hay una tienda al lado de mi casa.', tr: 'Evimin yanında bir dükkân var.' },
    ],
    esdizim: ['una tienda de ropa', 'ir de tiendas'], aile: ['el mercado', 'comprar'],
    hata: 'Belirsiz bir dükkândan söz ederken "la" kullanmak. İlk kez söyleniyorsa "UNA tienda" denir.',
    hatirlatma: '"hay" belirsiz nesne için, "está" belirli nesne için kullanılır: Hay una tienda / La tienda está aquí.',
    uretim: { yonerge: '"Evimin yanında bir dükkân var." cümlesini yaz.', kabul: ['Hay una tienda al lado de mi casa'] },
  },
  {
    id: 'es-banco', dil: 'es', kelime: 'banco', artikel: 'el', cins: 'eril', cogul: 'los bancos',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'Lugar donde se guarda el dinero; también un asiento del parque.',
    turkceDestek: 'banka; (ayrıca) bank, sıra', ipa: '/ˈbaŋ.ko/', heceler: 'ban-co',
    ornekler: [
      { es: 'El banco está enfrente de la plaza.', tr: 'Banka meydanın karşısında.' },
      { es: 'Estamos sentados en un banco del parque.', tr: 'Parktaki bir bankta oturuyoruz.' },
    ],
    esdizim: ['ir al banco', 'un banco del parque'], aile: ['el dinero', 'la tienda'],
    hata: 'İki anlamı ayırmamak. Bağlam ayırır: para → banka, parque → bank.',
    hatirlatma: 'Türkçedeki "banka" ve "bank" kelimeleri de aynı kökten gelir; ezberlemesi kolaydır.',
    uretim: { yonerge: '"Banka meydanın karşısında." cümlesini yaz.', kabul: ['El banco está enfrente de la plaza'] },
  },
  {
    id: 'es-hospital', dil: 'es', kelime: 'hospital', artikel: 'el', cins: 'eril', cogul: 'los hospitales',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'Lugar donde los médicos curan a los enfermos.',
    turkceDestek: 'hastane', ipa: '/os.pi.ˈtal/', heceler: 'hos-pi-tal (baştaki h okunmaz)',
    ornekler: [
      { es: 'Mi tía trabaja en el hospital.', tr: 'Teyzem hastanede çalışıyor.' },
      { es: 'El hospital está lejos del centro.', tr: 'Hastane merkezden uzakta.' },
    ],
    esdizim: ['ir al hospital', 'en el hospital'], aile: ['el médico', 'la farmacia'],
    hata: 'Baştaki "h"yi okumak. İspanyolcada "h" hiçbir zaman okunmaz: "ospital".',
    hatirlatma: 'Sessizle biten isimlerin çoğulu -es alır: hospital → hospitales.',
    uretim: { yonerge: '"Hastane merkezden uzakta." cümlesini yaz.', kabul: ['El hospital está lejos del centro'] },
  },
  {
    id: 'es-farmacia', dil: 'es', kelime: 'farmacia', artikel: 'la', cins: 'disil', cogul: 'las farmacias',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'Tienda donde se compran medicinas.',
    turkceDestek: 'eczane', ipa: '/faɾ.ˈma.θja/', heceler: 'far-ma-cia',
    ornekler: [
      { es: '¿Hay una farmacia por aquí?', tr: 'Buralarda bir eczane var mı?' },
      { es: 'La farmacia está al lado del banco.', tr: 'Eczane bankanın yanında.' },
    ],
    esdizim: ['la farmacia de guardia', 'ir a la farmacia'], aile: ['el hospital', 'la medicina'],
    hata: '"de el banco" yazmak. de + el kaynaşır: DEL banco.',
    hatirlatma: '"por aquí" = "buralarda" demektir ve yer sorarken en doğal kalıptır.',
    uretim: { yonerge: '"Buralarda bir eczane var mı?" sorusunu yaz.', kabul: ['¿Hay una farmacia por aquí?', 'Hay una farmacia por aquí'] },
  },
  {
    id: 'es-museo', dil: 'es', kelime: 'museo', artikel: 'el', cins: 'eril', cogul: 'los museos',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'Edificio donde se exponen obras de arte u objetos históricos.',
    turkceDestek: 'müze', ipa: '/mu.ˈse.o/', heceler: 'mu-se-o (vurgu: SE)',
    ornekler: [
      { es: 'El Museo del Prado está en Madrid.', tr: 'Prado Müzesi Madrid\'de.' },
      { es: 'Vamos al museo el domingo.', tr: 'Pazar günü müzeye gidiyoruz.' },
    ],
    esdizim: ['ir al museo', 'el museo de arte'], aile: ['el arte', 'la exposición'],
    hata: 'Vurguyu sona atmak: "museó" değil, "muSEo".',
    hatirlatma: 'Ünlüyle biten kelimelerde vurgu SONDAN BİR ÖNCEKİ hecededir; aksan yoksa kural budur.',
    uretim: { yonerge: '"Müzeye gidiyoruz." cümlesini yaz.', kabul: ['Vamos al museo'] },
  },
  {
    id: 'es-barrio', dil: 'es', kelime: 'barrio', artikel: 'el', cins: 'eril', cogul: 'los barrios',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'Parte de una ciudad donde vive la gente.',
    turkceDestek: 'mahalle, semt', ipa: '/ˈba.rjo/', heceler: 'ba-rrio (çift "rr" titrek)',
    ornekler: [
      { es: 'Mi barrio es muy tranquilo.', tr: 'Mahallem çok sakin.' },
      { es: 'En mi barrio hay dos parques.', tr: 'Mahallemde iki park var.' },
    ],
    esdizim: ['mi barrio', 'un barrio tranquilo'], aile: ['la ciudad', 'la calle'],
    hata: 'Çift "rr"yi tek "r" gibi söylemek. "caro" (pahalı) ile "carro" (araba) farkı buradadır; titremek zorunludur.',
    hatirlatma: 'Kelime başındaki tek "r" de titrektir: Roma, rojo.',
    uretim: { yonerge: '"Mahallem çok sakin." cümlesini yaz.', kabul: ['Mi barrio es muy tranquilo'] },
  },
  {
    id: 'es-autobus', dil: 'es', kelime: 'autobús', artikel: 'el', cins: 'eril', cogul: 'los autobuses',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'Vehículo grande que lleva a muchas personas por la ciudad.',
    turkceDestek: 'otobüs', ipa: '/au̯.to.ˈβus/', heceler: 'au-to-bús (vurgu: BÚS)',
    ornekler: [
      { es: 'Voy al colegio en autobús.', tr: 'Okula otobüsle gidiyorum.' },
      { es: 'El autobús llega a las ocho.', tr: 'Otobüs sekizde geliyor.' },
    ],
    esdizim: ['en autobús', 'coger el autobús'], aile: ['el metro', 'el tren'],
    hata: 'Ulaşım aracını "con" ile söylemek. Doğru edat "EN"dir: en autobús, en coche, en metro.',
    hatirlatma: 'Tek istisna yürümektir: "a pie" (yaya).',
    uretim: { yonerge: '"Okula otobüsle gidiyorum." cümlesini yaz.', kabul: ['Voy al colegio en autobús'] },
  },
  {
    id: 'es-metro', dil: 'es', kelime: 'metro', artikel: 'el', cins: 'eril', cogul: 'los metros',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'Tren que va por debajo de la ciudad.',
    turkceDestek: 'metro', ipa: '/ˈme.tɾo/', heceler: 'me-tro',
    ornekler: [
      { es: 'El metro es más rápido que el autobús.', tr: 'Metro otobüsten daha hızlı.' },
      { es: 'Cojo el metro todos los días.', tr: 'Her gün metroya biniyorum.' },
    ],
    esdizim: ['en metro', 'la estación de metro'], aile: ['el autobús', 'la estación'],
    hata: '"Metroya binmek" için "subir" aramak. En doğal fiil "coger"dir (Latin Amerika\'da "tomar").',
    hatirlatma: 'İspanya\'da "coger", Latin Amerika\'nın bazı ülkelerinde uygunsuz anlamdadır; orada "tomar" kullanılır.',
    uretim: { yonerge: '"Metroyla gidiyorum." cümlesini yaz.', kabul: ['Voy en metro'] },
  },
  {
    id: 'es-tren', dil: 'es', kelime: 'tren', artikel: 'el', cins: 'eril', cogul: 'los trenes',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'Vehículo largo que va sobre raíles entre ciudades.',
    turkceDestek: 'tren', ipa: '/tɾen/', heceler: 'tren (tek hece)',
    ornekler: [
      { es: 'El tren para Sevilla sale a las diez.', tr: 'Sevilla treni onda kalkıyor.' },
      { es: 'Vamos a Madrid en tren.', tr: 'Madrid\'e trenle gidiyoruz.' },
    ],
    esdizim: ['en tren', 'el billete de tren'], aile: ['la estación', 'el billete'],
    hata: 'Çoğulunu "trens" yapmak. Sessizle biten isimler -es alır: trenes.',
    hatirlatma: 'Yüksek hızlı tren "el AVE"dir; İspanya metinlerinde çok geçer.',
    uretim: { yonerge: '"Trenle gidiyoruz." cümlesini yaz.', kabul: ['Vamos en tren'] },
  },
  {
    id: 'es-billete', dil: 'es', kelime: 'billete', artikel: 'el', cins: 'eril', cogul: 'los billetes',
    tur: 'isim', seviye: 'A1',
    ispanyolcaTanim: 'Papel que se compra para viajar en tren, autobús o avión.',
    turkceDestek: 'bilet', ipa: '/bi.ˈʝe.te/', heceler: 'bi-lle-te ("ll" → y)',
    ornekler: [
      { es: 'Un billete para Valencia, por favor.', tr: 'Valencia\'ya bir bilet, lütfen.' },
      { es: '¿Cuánto cuesta el billete?', tr: 'Bilet ne kadar?' },
    ],
    esdizim: ['un billete de ida', 'un billete de ida y vuelta'], aile: ['la estación', 'el precio'],
    hata: 'Latin Amerika\'da da "billete" sanmak. Orada "el boleto" ya da "el pasaje" kullanılır.',
    hatirlatma: '"ida" gidiş, "ida y vuelta" gidiş-dönüş demektir; gişede en çok bu ikisi sorulur.',
    uretim: { yonerge: '"Valencia\'ya bir bilet, lütfen." cümlesini yaz.', kabul: ['Un billete para Valencia, por favor', 'Un billete para Valencia por favor'] },
  },
  {
    id: 'es-cerca', dil: 'es', kelime: 'cerca (de)', tur: 'zarf', seviye: 'A1',
    ispanyolcaTanim: 'A poca distancia.',
    turkceDestek: 'yakın, yakınında', ipa: '/ˈθeɾ.ka/ · Latin Amerika /ˈseɾ.ka/', heceler: 'cer-ca',
    ornekler: [
      { es: 'Vivo cerca del colegio.', tr: 'Okulun yakınında oturuyorum.' },
      { es: 'La parada está muy cerca.', tr: 'Durak çok yakında.' },
    ],
    esdizim: ['cerca de aquí', 'muy cerca'], aile: ['lejos', 'al lado de'],
    hata: '"de" edatını unutmak. Bir yere göre yakınlık söyleniyorsa "de" zorunludur: cerca DE la plaza.',
    hatirlatma: 'Tek başına kullanılırsa "de" gerekmez: Está cerca.',
    uretim: { yonerge: '"Okulun yakınında oturuyorum." cümlesini yaz.', kabul: ['Vivo cerca del colegio'] },
  },
  {
    id: 'es-lejos', dil: 'es', kelime: 'lejos (de)', tur: 'zarf', seviye: 'A1',
    ispanyolcaTanim: 'A mucha distancia.',
    turkceDestek: 'uzak, uzağında', ipa: '/ˈle.xos/', heceler: 'le-jos ("j" gırtlaktan)',
    ornekler: [
      { es: 'Mi casa está lejos del centro.', tr: 'Evim merkezden uzakta.' },
      { es: '¿Está lejos la estación?', tr: 'İstasyon uzak mı?' },
    ],
    esdizim: ['lejos de aquí', 'muy lejos'], aile: ['cerca', 'la distancia'],
    hata: 'Sondaki -s\'yi çoğul sanıp atmak. "lejo" diye bir kelime yoktur; zarf her zaman "lejos"tur.',
    hatirlatma: '"j" harfi Türkçedeki "j" değil, gırtlaktan çıkan sert bir "h"dir: "lehos".',
    uretim: { yonerge: '"Evim merkezden uzakta." cümlesini yaz.', kabul: ['Mi casa está lejos del centro'] },
  },
  {
    id: 'es-al-lado-de', dil: 'es', kelime: 'al lado de', tur: 'kalip', seviye: 'A1',
    ispanyolcaTanim: 'Justo a la derecha o a la izquierda de algo, muy cerca.',
    turkceDestek: '-in yanında', ipa: '/al ˈla.ðo ðe/', heceler: 'al la-do de',
    ornekler: [
      { es: 'El banco está al lado del museo.', tr: 'Banka müzenin yanında.' },
      { es: 'Vivo al lado de la escuela.', tr: 'Okulun yanında oturuyorum.' },
    ],
    esdizim: ['justo al lado', 'al lado de casa'], aile: ['enfrente de', 'detrás de'],
    hata: 'Kalıbın içindeki iki kaynaşmayı da kaçırmak: "a el lado de el museo" → doğrusu "AL lado DEL museo".',
    hatirlatma: 'Yer kalıplarının hepsi "de" ile biter: al lado de, cerca de, lejos de, detrás de, delante de.',
    uretim: { yonerge: '"Banka müzenin yanında." cümlesini yaz.', kabul: ['El banco está al lado del museo'] },
  },
  {
    id: 'es-a-la-derecha', dil: 'es', kelime: 'a la derecha', tur: 'kalip', seviye: 'A1',
    ispanyolcaTanim: 'En el lado derecho.',
    turkceDestek: 'sağda, sağa', ipa: '/a la ðe.ˈɾe.tʃa/', heceler: 'a la de-re-cha ("ch" → ç)',
    ornekler: [
      { es: 'La farmacia está a la derecha.', tr: 'Eczane sağda.' },
      { es: 'Gire a la derecha en la plaza.', tr: 'Meydanda sağa dönün.' },
    ],
    esdizim: ['a la derecha de', 'la primera a la derecha'], aile: ['a la izquierda', 'todo recto'],
    hata: '"en la derecha" demek. Yön tarifinde edat "A"dır: A la derecha.',
    hatirlatma: 'Bir şeye göre sağ söyleniyorsa "de" eklenir: a la derecha DEL banco.',
    uretim: { yonerge: '"Eczane sağda." cümlesini yaz.', kabul: ['La farmacia está a la derecha'] },
  },
  {
    id: 'es-a-la-izquierda', dil: 'es', kelime: 'a la izquierda', tur: 'kalip', seviye: 'A1',
    ispanyolcaTanim: 'En el lado izquierdo.',
    turkceDestek: 'solda, sola', ipa: '/a la iθ.ˈkjeɾ.ða/', heceler: 'a la iz-quier-da',
    ornekler: [
      { es: 'El hospital está a la izquierda.', tr: 'Hastane solda.' },
      { es: 'Toma la segunda calle a la izquierda.', tr: 'Soldaki ikinci sokağa gir.' },
    ],
    esdizim: ['a la izquierda de', 'la segunda a la izquierda'], aile: ['a la derecha', 'seguir'],
    hata: 'Kelimenin içindeki "qu" yüzünden "izkuierda" demek. "qu" → k, "u" okunmaz: "izkierda".',
    hatirlatma: 'Yol tarifinde üçlü kalıp yeter: todo recto (dümdüz), a la derecha, a la izquierda.',
    uretim: { yonerge: '"Hastane solda." cümlesini yaz.', kabul: ['El hospital está a la izquierda'] },
  },
  {
    id: 'es-seguir', dil: 'es', kelime: 'seguir', tur: 'fiil', seviye: 'A1',
    duzensiz: true, cekim: 'sigo · sigues · sigue · seguimos · seguís · siguen',
    ispanyolcaTanim: 'Continuar por el mismo camino.',
    turkceDestek: 'devam etmek, izlemek', ipa: '/se.ˈɣiɾ/', heceler: 'se-guir ("gui" → gi, u okunmaz)',
    ornekler: [
      { es: 'Siga todo recto hasta la plaza.', tr: 'Meydana kadar dümdüz devam edin.' },
      { es: 'Sigo estudiando español.', tr: 'İspanyolca çalışmaya devam ediyorum.' },
    ],
    esdizim: ['seguir todo recto', 'seguir + gerundio'], aile: ['girar', 'continuar'],
    hata: '"gui" grubundaki "u"yu okumak: "seguir" → "segir" okunur, "seguir" değil.',
    hatirlatma: 'Yol tarifi genelde usted emir kipiyle verilir: siga, gire, tome.',
    uretim: { yonerge: '"Dümdüz devam edin." cümlesini yaz.', kabul: ['Siga todo recto', 'Sigue todo recto'] },
  },
  {
    id: 'es-girar', dil: 'es', kelime: 'girar', tur: 'fiil', seviye: 'A1',
    duzensiz: false, cekim: 'giro · giras · gira · giramos · giráis · giran',
    ispanyolcaTanim: 'Cambiar de dirección hacia un lado.',
    turkceDestek: 'dönmek (yön değiştirmek)', ipa: '/xi.ˈɾaɾ/', heceler: 'gi-rar ("gi" gırtlaktan, "hi" gibi)',
    ornekler: [
      { es: 'Gire a la derecha en el semáforo.', tr: 'Işıkta sağa dönün.' },
      { es: 'Giramos a la izquierda aquí.', tr: 'Burada sola dönüyoruz.' },
    ],
    esdizim: ['girar a la derecha', 'girar a la izquierda'], aile: ['seguir', 'la calle'],
    hata: '"volver" ile karıştırmak. Eve dönmek → volver; yön değiştirmek → girar.',
    hatirlatma: '"ge" ve "gi" gırtlaktan okunur; "ga, go, gu" ise Türkçedeki "g" gibidir.',
    uretim: { yonerge: '"Sağa dönün." cümlesini yaz.', kabul: ['Gire a la derecha', 'Gira a la derecha'] },
  },
]
