/**
 * A1 — TANIŞMA KELİMELERİ
 * ==================================================================
 *
 * Bir kelimeyi "bilmek" burada dört şey demektir: anlamını bilmek,
 * bağlamda tanımak, doğru biçimde yazmak, kendi cümlende kullanmak.
 *
 * İSPANYOLCAYA ÖZGÜ ZORUNLULUK: her isimde `artikel`, `cins` ve `cogul`
 * doludur. İyi haber şu ki İspanyolcada cinsiyet tahmini kolaydır: -o
 * genelde eril, -a genelde dişildir. Ama istisnalar (el problema, la mano)
 * yalnız `cins` alanından öğrenilebilir.
 *
 * `hata` alanı Türk öğrencilerin o kelimede yaptığı EN SIK hatadır.
 */

export const KELIMELER = [
  {
    id: 'es-hola',
    dil: 'es',
    kelime: 'hola',
    tur: 'kalip',
    seviye: 'A1',
    ispanyolcaTanim: 'Palabra que se dice para saludar a alguien.',
    turkceDestek: 'merhaba, selam',
    ipa: '/ˈo.la/',
    heceler: 'ho-la (baştaki h OKUNMAZ: "ola")',
    ornekler: [
      { es: '¡Hola! ¿Cómo estás?', tr: 'Merhaba! Nasılsın?' },
      { es: 'Hola, me llamo Deniz.', tr: 'Merhaba, adım Deniz.' },
    ],
    esdizim: ['¡Hola!', 'hola a todos'],
    aile: ['buenos días', 'adiós'],
    hata: 'Baştaki "h" harfini okumak. İspanyolcada "h" hiçbir zaman okunmaz; kelime "ola" gibi söylenir.',
    hatirlatma: 'Her saatte ve her ortamda kullanılabilir; İspanyolcada "salut" gibi bir samimiyet sınırı yoktur.',
    uretim: { yonerge: 'Birini selamla ve nasıl olduğunu sor.', kabul: ['Hola ¿cómo estás?', '¡Hola! ¿Cómo estás?', 'Hola cómo estás'] },
  },
  {
    id: 'es-buenos-dias',
    dil: 'es',
    kelime: 'buenos días',
    tur: 'kalip',
    seviye: 'A1',
    ispanyolcaTanim: 'Saludo que se usa desde la mañana hasta el mediodía.',
    turkceDestek: 'günaydın, iyi günler',
    ipa: '/ˈbwe.nos ˈdi.as/',
    heceler: 'bue-nos dí-as (vurgu: DÍ)',
    ornekler: [
      { es: 'Buenos días, señora García.', tr: 'Günaydın, García Hanım.' },
      { es: 'Buenos días a todos.', tr: 'Herkese günaydın.' },
    ],
    esdizim: ['buenas tardes', 'buenas noches'],
    aile: ['la tarde', 'la noche'],
    hata: 'Tekil kullanmak: "buen día" bazı ülkelerde duyulur ama İspanya\'da standart biçim ÇOĞULDUR: buenos días.',
    hatirlatma: 'Üç selam da çoğuldur: buenos días, buenas tardes, buenas noches.',
    uretim: { yonerge: 'Sabah öğretmenini selamla.', kabul: ['Buenos días', 'Buenos días profesor', 'Buenos días profesora'] },
  },
  {
    id: 'es-gracias',
    dil: 'es',
    kelime: 'gracias',
    tur: 'kalip',
    seviye: 'A1',
    ispanyolcaTanim: 'Palabra que se dice cuando alguien nos ayuda o nos da algo.',
    turkceDestek: 'teşekkürler',
    ipa: '/ˈɡɾa.θjas/ · Latin Amerika /ˈɡɾa.sjas/',
    heceler: 'gra-cias (ci → İspanya\'da peltek, Latin Amerika\'da "s")',
    ornekler: [
      { es: 'Muchas gracias por tu ayuda.', tr: 'Yardımın için çok teşekkürler.' },
      { es: '— Aquí tienes. — ¡Gracias!', tr: '— Buyur. — Teşekkürler!' },
    ],
    esdizim: ['muchas gracias', 'gracias por', 'mil gracias'],
    aile: ['de nada', 'agradecer'],
    hata: '"muy gracias" demek. "Çok teşekkürler" ifadesi İspanyolcada "MUCHAS gracias"tır; "muy" sıfat önünde kullanılır.',
    hatirlatma: 'Karşılığı "de nada" ya da "no hay de qué"dir.',
    uretim: { yonerge: 'Birine çok teşekkür et.', kabul: ['Muchas gracias', '¡Muchas gracias!'] },
  },
  {
    id: 'es-por-favor',
    dil: 'es',
    kelime: 'por favor',
    tur: 'kalip',
    seviye: 'A1',
    ispanyolcaTanim: 'Fórmula de cortesía para pedir algo.',
    turkceDestek: 'lütfen',
    ipa: '/poɾ fa.ˈβoɾ/',
    heceler: 'por fa-vor (vurgu: VOR)',
    ornekler: [
      { es: 'Un café, por favor.', tr: 'Bir kahve, lütfen.' },
      { es: '¿Puede repetir, por favor?', tr: 'Tekrar eder misiniz, lütfen?' },
    ],
    esdizim: ['por favor', 'sí, por favor'],
    aile: ['gracias', 'el favor'],
    hata: 'Fransızcadaki gibi hitaba göre değiştirmeye çalışmak. İspanyolcada tek biçim vardır: "por favor" hem tú hem usted ile kullanılır.',
    hatirlatma: 'Cümlenin başına da sonuna da gelebilir; sonda daha yaygındır.',
    uretim: { yonerge: 'Kibar biçimde bir kahve iste.', kabul: ['Un café por favor', 'Un café, por favor'] },
  },
  {
    id: 'es-perdon',
    dil: 'es',
    kelime: 'perdón',
    tur: 'kalip',
    seviye: 'A1',
    ispanyolcaTanim: 'Palabra para disculparse o para llamar la atención de alguien.',
    turkceDestek: 'pardon, affedersiniz',
    ipa: '/peɾ.ˈdon/',
    heceler: 'per-dón (vurgu SON hecede, aksan onu gösterir)',
    ornekler: [
      { es: 'Perdón, ¿dónde está la estación?', tr: 'Affedersiniz, istasyon nerede?' },
      { es: 'Perdón, no te oí.', tr: 'Pardon, seni duymadım.' },
    ],
    esdizim: ['perdón', 'perdone', 'con permiso'],
    aile: ['lo siento', 'disculpe'],
    hata: 'Ciddi bir özür için yeterli sanmak. Küçük kazalarda "perdón", gerçek özürde "lo siento" kullanılır.',
    hatirlatma: 'Resmî biçimi "perdone" ya da "disculpe"dir; yol sorarken bu biçimler daha uygundur.',
    uretim: { yonerge: 'Sokakta birine yol soracaksın. Cümleye nasıl başlarsın?', kabul: ['Perdón', 'Perdone', 'Disculpe', 'Perdón, ¿dónde está'] },
  },
  {
    id: 'es-adios',
    dil: 'es',
    kelime: 'adiós',
    tur: 'kalip',
    seviye: 'A1',
    ispanyolcaTanim: 'Palabra que se dice al despedirse de alguien.',
    turkceDestek: 'hoşça kal, güle güle',
    ipa: '/a.ˈðjos/',
    heceler: 'a-diós (vurgu son hecede)',
    ornekler: [
      { es: 'Adiós, hasta mañana.', tr: 'Hoşça kal, yarın görüşürüz.' },
      { es: 'Adiós y buen viaje.', tr: 'Hoşça kal, iyi yolculuklar.' },
    ],
    esdizim: ['hasta luego', 'hasta mañana', 'hasta pronto'],
    aile: ['hola', 'nos vemos'],
    hata: '"Adiós" kelimesini her vedada kullanmak. Günlük dilde "hasta luego" çok daha yaygındır; "adiós" biraz daha kesin bir ayrılık hissi verir.',
    hatirlatma: 'Günlük konuşmada en sık duyacağın veda "hasta luego"dur.',
    uretim: { yonerge: 'Arkadaşına veda et (yarın görüşeceksiniz).', kabul: ['Hasta mañana', 'Adiós, hasta mañana'] },
  },
  {
    id: 'es-mucho-gusto',
    dil: 'es',
    kelime: 'mucho gusto',
    tur: 'kalip',
    seviye: 'A1',
    ispanyolcaTanim: 'Lo que se dice cuando conocemos a alguien por primera vez.',
    turkceDestek: 'memnun oldum',
    ipa: '/ˈmu.tʃo ˈɡus.to/',
    heceler: 'mu-cho gus-to ("ch" → Türkçedeki "ç")',
    ornekler: [
      { es: '— Soy Elif. — Mucho gusto.', tr: '— Ben Elif. — Memnun oldum.' },
      { es: 'Encantado de conocerte.', tr: 'Tanıştığımıza memnun oldum.' },
    ],
    esdizim: ['mucho gusto', 'encantado', 'encantada'],
    aile: ['conocer', 'presentar'],
    hata: '"encantado" kelimesini cinsiyete uydurmamak: erkek "encantado", kadın "encantada" der. "Mucho gusto" ise değişmez ve bu yüzden daha güvenlidir.',
    hatirlatma: 'Yalnız İLK tanışmada söylenir; her karşılaşmada değil.',
    uretim: { yonerge: 'Yeni biriyle tanıştın. Ona ne dersin?', kabul: ['Mucho gusto', 'Encantado', 'Encantada'] },
  },
  {
    id: 'es-llamarse',
    dil: 'es',
    kelime: 'llamarse',
    cekim: 'me llamo · te llamas · se llama · nos llamamos · os llamáis · se llaman',
    tur: 'fiil',
    seviye: 'A1',
    ispanyolcaTanim: 'Tener un nombre determinado.',
    turkceDestek: 'adı … olmak',
    ipa: '/ʎa.ˈmaɾ.se/',
    heceler: 'lla-mar-se ("ll" → y: "yamarse")',
    ornekler: [
      { es: 'Me llamo Mert. ¿Y tú?', tr: 'Benim adım Mert. Ya senin?' },
      { es: '¿Cómo se llama tu hermana?', tr: 'Kız kardeşinin adı ne?' },
    ],
    esdizim: ['¿Cómo te llamas?', '¿Cómo se llama usted?', 'me llamo…'],
    aile: ['el nombre', 'llamar'],
    hata: 'Türkçede "adım Mert" derken fiil yoktur; öğrenci "Yo Mert" ya da "Mi nombre Mert" yazar. İspanyolcada mutlaka bir fiil olmalı: me llamo ya da es.',
    hatirlatma: 'Dönüşlü fiildir: zamir (me/te/se) fiilin ÖNÜNDE durur ve düşürülemez.',
    uretim: { yonerge: 'Adını "Me llamo …" kalıbıyla yaz.', kabul: ['Me llamo'] },
  },
  {
    id: 'es-ser',
    dil: 'es',
    kelime: 'ser',
    cekim: 'soy · eres · es · somos · sois · son',
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    ispanyolcaTanim: 'Verbo que expresa identidad, origen, profesión y características permanentes.',
    turkceDestek: 'olmak (kalıcı özellik, kimlik)',
    ipa: '/seɾ/',
    heceler: 'ser (tek hece)',
    ornekler: [
      { es: 'Soy estudiante y soy turco.', tr: 'Öğrenciyim ve Türk\'üm.' },
      { es: 'Mi hermana es muy simpática.', tr: 'Kız kardeşim çok cana yakın.' },
    ],
    esdizim: ['ser de', 'ser estudiante', 'es la una'],
    aile: ['estar', 'la identidad'],
    hata: 'Yer bildirirken kullanmak: "Soy en casa" yanlıştır. Yer her zaman "estar" ile bildirilir. Ayrıca yaş "tener" ile söylenir.',
    hatirlatma: 'Özne zamiri gerekmez: "Soy estudiante" yeterlidir, "Yo soy" demek vurgu katar.',
    uretim: { yonerge: '"Öğrenciyim." cümlesini özne zamiri kullanmadan yaz.', kabul: ['Soy estudiante'] },
  },
  {
    id: 'es-estar',
    dil: 'es',
    kelime: 'estar',
    cekim: 'estoy · estás · está · estamos · estáis · están',
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    ispanyolcaTanim: 'Verbo que expresa lugar, estado temporal y acción en curso.',
    turkceDestek: 'olmak (yer, geçici durum)',
    ipa: '/es.ˈtaɾ/',
    heceler: 'es-tar (vurgu son hecede)',
    ornekler: [
      { es: 'Estoy en casa ahora.', tr: 'Şu anda evdeyim.' },
      { es: 'Estoy muy cansado hoy.', tr: 'Bugün çok yorgunum.' },
    ],
    esdizim: ['estar en', 'estar cansado', 'estar bien'],
    aile: ['ser', 'el estado'],
    hata: 'Kimlik ve meslek için kullanmak: "Estoy estudiante" yanlıştır; doğrusu "Soy estudiante".',
    hatirlatma: 'Üç iş yapar: YER, GEÇİCİ DURUM ve SÜREN EYLEM (estoy comiendo).',
    uretim: { yonerge: '"Evdeyim." cümlesini yaz.', kabul: ['Estoy en casa'] },
  },
  {
    id: 'es-tener',
    dil: 'es',
    kelime: 'tener',
    cekim: 'tengo · tienes · tiene · tenemos · tenéis · tienen',
    duzensiz: true,
    tur: 'fiil',
    seviye: 'A1',
    ispanyolcaTanim: 'Verbo que expresa posesión, edad y ciertos estados del cuerpo.',
    turkceDestek: 'sahip olmak; (yaş, açlık) …-mak',
    ipa: '/te.ˈneɾ/',
    heceler: 'te-ner (tengo: "TEN-go")',
    ornekler: [
      { es: 'Tengo dos hermanos y una hermana.', tr: 'İki erkek kardeşim ve bir kız kardeşim var.' },
      { es: 'Ella tiene dieciséis años.', tr: 'O on altı yaşında.' },
    ],
    esdizim: ['tener … años', 'tener hambre', 'tener que + mastar'],
    aile: ['hay', 'la posesión'],
    hata: 'Türkçede "iki kardeşim var" cümlesindeki "var" öğrenciyi "hay"a götürüyor. Sahiplikte "tener" kullanılır: Tengo dos hermanos.',
    hatirlatma: 'Yaş, açlık, susuzluk, soğuk, korku — hepsi bu fiille söylenir.',
    uretim: { yonerge: '"On yedi yaşındayım." cümlesini yaz.', kabul: ['Tengo diecisiete años', 'Tengo 17 años'] },
  },
  {
    id: 'es-nombre',
    dil: 'es',
    kelime: 'nombre',
    artikel: 'el',
    cins: 'eril',
    cogul: 'los nombres',
    tur: 'isim',
    seviye: 'A1',
    ispanyolcaTanim: 'La palabra con la que llamamos a una persona.',
    turkceDestek: 'ad, isim',
    ipa: '/ˈnom.bɾe/',
    heceler: 'nom-bre (vurgu: NOM)',
    ornekler: [
      { es: 'Mi nombre es Ada.', tr: 'Adım Ada.' },
      { es: '¿Cuál es tu nombre completo?', tr: 'Tam adın nedir?' },
    ],
    esdizim: ['el nombre completo', 'a nombre de'],
    aile: ['el apellido', 'llamarse'],
    hata: '"nombre" ile "apellido" karıştırılır: nombre = ad, apellido = soyadı. Formlarda ikisi ayrı satırdır.',
    hatirlatma: 'Günlük konuşmada "¿Cómo te llamas?" daha doğaldır; "¿Cuál es tu nombre?" biraz resmîdir.',
    uretim: { yonerge: 'Adını "Mi nombre es …" kalıbıyla yaz.', kabul: ['Mi nombre es'] },
  },
  {
    id: 'es-apellido',
    dil: 'es',
    kelime: 'apellido',
    artikel: 'el',
    cins: 'eril',
    cogul: 'los apellidos',
    tur: 'isim',
    seviye: 'A1',
    ispanyolcaTanim: 'El nombre de familia que se hereda de los padres.',
    turkceDestek: 'soyadı',
    ipa: '/a.pe.ˈʎi.ðo/',
    heceler: 'a-pe-lli-do ("ll" → y)',
    ornekler: [
      { es: 'Mi apellido es Yazçiçek.', tr: 'Soyadım Yazçiçek.' },
      { es: '¿Puede deletrear su apellido?', tr: 'Soyadınızı heceleyebilir misiniz?' },
    ],
    esdizim: ['el primer apellido', 'deletrear el apellido'],
    aile: ['el nombre', 'la familia'],
    hata: 'İspanyollarda İKİ soyadı olduğunu bilmemek: biri babadan, biri anneden gelir. Formlarda "primer apellido" ve "segundo apellido" ayrı sorulabilir.',
    hatirlatma: 'Türkçe soyadlarında "ç, ş, ğ" olduğu için heceleme neredeyse her zaman gerekir.',
    uretim: { yonerge: 'Soyadını söyle.', kabul: ['Mi apellido es'] },
  },
  {
    id: 'es-vivir',
    dil: 'es',
    kelime: 'vivir',
    cekim: 'vivo · vives · vive · vivimos · vivís · viven',
    tur: 'fiil',
    seviye: 'A1',
    ispanyolcaTanim: 'Tener su casa en un lugar; estar vivo.',
    turkceDestek: 'yaşamak, oturmak',
    ipa: '/bi.ˈβiɾ/',
    heceler: 'vi-vir ("v" harfi "b" gibi okunur: "bibir")',
    ornekler: [
      { es: 'Vivo en Esmirna con mi familia.', tr: 'Ailemle İzmir\'de yaşıyorum.' },
      { es: '¿Dónde vives?', tr: 'Nerede yaşıyorsun?' },
    ],
    esdizim: ['vivir en', 'vivir con'],
    aile: ['la vida', 'el vecino'],
    hata: '"Estoy viviendo en Izmir" demek. Bu biçim "geçici olarak" anlamı verir; alışkanlık için düz şimdiki zaman kullanılır: "Vivo en Izmir".',
    hatirlatma: 'İspanyolcada "v" ve "b" harfleri AYNI okunur; ikisi de yumuşak "b" sesidir.',
    uretim: { yonerge: 'Nerede yaşadığını yaz.', kabul: ['Vivo en'] },
  },
  {
    id: 'es-hablar',
    dil: 'es',
    kelime: 'hablar',
    cekim: 'hablo · hablas · habla · hablamos · habláis · hablan',
    tur: 'fiil',
    seviye: 'A1',
    ispanyolcaTanim: 'Decir palabras; usar un idioma.',
    turkceDestek: 'konuşmak',
    ipa: '/a.ˈβlaɾ/',
    heceler: 'ha-blar (baştaki h okunmaz: "ablar")',
    ornekler: [
      { es: 'Hablo turco, inglés y un poco de español.', tr: 'Türkçe, İngilizce ve biraz İspanyolca konuşuyorum.' },
      { es: '¿Habla usted inglés?', tr: 'İngilizce konuşuyor musunuz?' },
    ],
    esdizim: ['hablar español', 'hablar con', 'hablar de'],
    aile: ['la palabra', 'decir'],
    hata: 'Dil adını büyük harfle yazmak: "Hablo Español" değil, "hablo español". Dil adları küçük yazılır.',
    hatirlatma: '-ar grubunun çekim örneğidir; bu tabloyu bilen binlerce fiili bilir.',
    uretim: { yonerge: 'Hangi dilleri konuştuğunu yaz.', kabul: ['Hablo turco', 'Hablo turco e inglés', 'Hablo español'] },
  },
  {
    id: 'es-pais',
    dil: 'es',
    kelime: 'país',
    artikel: 'el',
    cins: 'eril',
    cogul: 'los países',
    tur: 'isim',
    seviye: 'A1',
    ispanyolcaTanim: 'Un territorio con sus fronteras y su gobierno.',
    turkceDestek: 'ülke',
    ipa: '/pa.ˈis/',
    heceler: 'pa-ís (aksan iki sesliyi ayırır: pa-İS)',
    ornekler: [
      { es: 'Turquía es un país grande.', tr: 'Türkiye büyük bir ülke.' },
      { es: '¿En qué país vives?', tr: 'Hangi ülkede yaşıyorsun?' },
    ],
    esdizim: ['un país extranjero', 'en mi país'],
    aile: ['la ciudad', 'la nacionalidad'],
    hata: 'Aksanı yazmamak. Buradaki aksan vurguyu değil, "a" ve "i" seslerinin AYRI hece olduğunu gösterir: pa-ís. Aksansız yazılırsa "pais" tek hece gibi okunur.',
    hatirlatma: 'Çoğulunda da aksan korunur: los países.',
    uretim: { yonerge: '"Türkiye güzel bir ülke." cümlesini yaz.', kabul: ['Turquía es un país bonito', 'Turquía es un país hermoso'] },
  },
  {
    id: 'es-ciudad',
    dil: 'es',
    kelime: 'ciudad',
    artikel: 'la',
    cins: 'disil',
    cogul: 'las ciudades',
    tur: 'isim',
    seviye: 'A1',
    ispanyolcaTanim: 'Un lugar con muchas casas, calles y habitantes.',
    turkceDestek: 'şehir',
    ipa: '/θju.ˈðað/ · Latin Amerika /sju.ˈðað/',
    heceler: 'ciu-dad (vurgu son hecede)',
    ornekler: [
      { es: 'Mi ciudad se llama Esmirna.', tr: 'Şehrimin adı İzmir.' },
      { es: 'Madrid es una ciudad muy grande.', tr: 'Madrid çok büyük bir şehir.' },
    ],
    esdizim: ['el centro de la ciudad', 'una ciudad grande'],
    aile: ['el país', 'el pueblo'],
    hata: '-dad ile bittiği için eril sanmak. -dad ve -tad ile biten isimler DİŞİLDİR: la ciudad, la libertad, la universidad.',
    hatirlatma: 'Türkçedeki İzmir\'in İspanyolcası "Esmirna"dır; birçok şehir adının İspanyolca biçimi vardır.',
    uretim: { yonerge: 'Yaşadığın şehri tanıt.', kabul: ['Mi ciudad se llama', 'Vivo en'] },
  },
  {
    id: 'es-amigo',
    dil: 'es',
    kelime: 'amigo / amiga',
    artikel: 'el',
    cins: 'eril',
    cogul: 'los amigos / las amigas',
    tur: 'isim',
    seviye: 'A1',
    ispanyolcaTanim: 'Una persona con la que tenemos una relación de cariño y confianza.',
    turkceDestek: 'arkadaş',
    ipa: '/a.ˈmi.ɣo/',
    heceler: 'a-mi-go (vurgu: Mİ)',
    ornekler: [
      { es: 'Este es mi amigo Kaan.', tr: 'Bu arkadaşım Kaan.' },
      { es: 'Tengo una amiga española.', tr: 'İspanyol bir kız arkadaşım var.' },
    ],
    esdizim: ['mi mejor amigo', 'un amigo íntimo', 'ser amigo de'],
    aile: ['la amistad', 'el compañero'],
    hata: 'Karışık gruplarda dişil kullanmak: bir grupta bir erkek bile varsa "los amigos" denir.',
    hatirlatma: 'Cinsiyete göre biçim değişir: amigo (erkek) / amiga (kadın).',
    uretim: { yonerge: 'Bir arkadaşını tanıt.', kabul: ['Este es mi amigo', 'Esta es mi amiga', 'Es mi amigo'] },
  },
  {
    id: 'es-profesor',
    dil: 'es',
    kelime: 'profesor / profesora',
    artikel: 'el',
    cins: 'eril',
    cogul: 'los profesores',
    tur: 'isim',
    seviye: 'A1',
    ispanyolcaTanim: 'Persona que enseña en una escuela o instituto.',
    turkceDestek: 'öğretmen',
    ipa: '/pɾo.fe.ˈsoɾ/',
    heceler: 'pro-fe-sor (vurgu son hecede)',
    ornekler: [
      { es: 'Mi profesor de español es muy simpático.', tr: 'İspanyolca öğretmenim çok cana yakın.' },
      { es: 'La profesora explica la lección.', tr: 'Öğretmen dersi anlatıyor.' },
    ],
    esdizim: ['el profesor de español', 'un buen profesor'],
    aile: ['la clase', 'el alumno', 'enseñar'],
    hata: 'Meslek söylerken artikel kullanmak: "Soy un profesor" değil, "Soy profesor". "ser" fiilinden sonra meslekte artikel kullanılmaz.',
    hatirlatma: 'Dişil biçimi düzenlidir: profesor → profesora.',
    uretim: { yonerge: '"İspanyolca öğretmenim cana yakın." cümlesini yaz.', kabul: ['Mi profesor de español es simpático', 'Mi profesora de español es simpática'] },
  },
  {
    id: 'es-estudiante',
    dil: 'es',
    kelime: 'estudiante',
    artikel: 'el',
    cins: 'eril',
    cogul: 'los estudiantes',
    tur: 'isim',
    seviye: 'A1',
    ispanyolcaTanim: 'Persona que estudia en un instituto o en la universidad.',
    turkceDestek: 'öğrenci',
    ipa: '/es.tu.ˈðjan.te/',
    heceler: 'es-tu-dian-te (vurgu: DİAN)',
    ornekler: [
      { es: 'Soy estudiante de instituto.', tr: 'Lise öğrencisiyim.' },
      { es: 'Los estudiantes escuchan al profesor.', tr: 'Öğrenciler öğretmeni dinliyor.' },
    ],
    esdizim: ['ser estudiante', 'un buen estudiante'],
    aile: ['estudiar', 'el alumno', 'la escuela'],
    hata: 'Kadın öğrenci için "estudianta" uydurmak. Bu kelime iki cinste de aynıdır; fark yalnız artikeldedir: el/la estudiante.',
    hatirlatma: 'Okul öğrencisi için "alumno" da kullanılır; "estudiante" daha geniştir.',
    uretim: { yonerge: '"Öğrenciyim." cümlesini yaz.', kabul: ['Soy estudiante'] },
  },
  {
    id: 'es-como',
    dil: 'es',
    kelime: 'cómo',
    tur: 'soru',
    seviye: 'A1',
    ispanyolcaTanim: 'Palabra que se usa para preguntar la manera.',
    turkceDestek: 'nasıl',
    ipa: '/ˈko.mo/',
    heceler: 'có-mo (soru olduğu için AKSANLI)',
    ornekler: [
      { es: '¿Cómo te llamas?', tr: 'Adın ne?' },
      { es: '¿Cómo está usted?', tr: 'Nasılsınız?' },
    ],
    esdizim: ['¿Cómo estás?', '¿Cómo se dice…?', '¿Cómo se escribe?'],
    aile: ['dónde', 'qué', 'cuándo'],
    hata: 'Aksanı yazmamak. Soru kelimeleri SORUDA aksan alır: "¿cómo?" Aksansız "como" ise "gibi" ya da "yiyorum" demektir.',
    hatirlatma: 'Bütün soru kelimeleri soruda aksan alır: qué, dónde, cuándo, quién, cuánto.',
    uretim: { yonerge: 'Bir arkadaşına adını sor.', kabul: ['¿Cómo te llamas?', 'Cómo te llamas', '¿Cómo te llamas'] },
  },
  {
    id: 'es-donde',
    dil: 'es',
    kelime: 'dónde',
    tur: 'soru',
    seviye: 'A1',
    ispanyolcaTanim: 'Palabra que se usa para preguntar el lugar.',
    turkceDestek: 'nerede, nereye',
    ipa: '/ˈdon.de/',
    heceler: 'dón-de (soruda aksanlı)',
    ornekler: [
      { es: '¿Dónde vives?', tr: 'Nerede yaşıyorsun?' },
      { es: '¿De dónde eres?', tr: 'Nerelisin?' },
    ],
    esdizim: ['¿Dónde está…?', '¿De dónde eres?', '¿Adónde vas?'],
    aile: ['aquí', 'allí', 'cómo'],
    hata: 'Yer sorarken "ser" kullanmak: "¿Dónde eres?" yanlıştır (bu köken sorar). Yer için "¿Dónde ESTÁ…?" kullanılır.',
    hatirlatma: 'İki ayrı soru: "¿De dónde eres?" (nerelisin — köken, ser) · "¿Dónde estás?" (neredesin — yer, estar).',
    uretim: { yonerge: '"Nerede yaşıyorsun?" sorusunu yaz.', kabul: ['¿Dónde vives?', 'Dónde vives', '¿Dónde vives'] },
  },
]
