/**
 * DRKOÇ — KELİME KAYITLARI: A2 / Modül 1 — Anılar ve alışkanlıklar
 *
 * Bu modülün zorluğu kelime değil, GEÇMİŞİN İKİYE BÖLÜNMESİDİR:
 * indefinido olan biteni, imperfecto süren durumu ve alışkanlığı
 * anlatır. Türkçede ikisi de "-di / -yordu" ile karşılanır ama seçim
 * bağlamdan doğar. Bu yüzden her kayıtta kelimenin hangi geçmiş zamanı
 * çağırdığı yazar.
 */

export const KELIMELER = [
  {
    id: 'es-la-semana-pasada',
    dil: 'es',
    kelime: 'la semana pasada',
    artikel: 'la',
    cins: 'disil',
    cogul: 'las semanas pasadas',
    tur: 'isim',
    seviye: 'A2',
    ispanyolcaTanim: 'La semana anterior a esta semana.',
    turkceDestek: 'geçen hafta',
    ipa: '/la seˈmana paˈsaða/',
    heceler: 'la se-ma-na pa-sa-da',
    ornekler: [
      { es: 'La semana pasada fuimos a Izmir.', tr: 'Geçen hafta İzmir\'e gittik.' },
      { es: 'Estudié mucho la semana pasada.', tr: 'Geçen hafta çok çalıştım.' },
    ],
    esdizim: ['el año pasado', 'el mes pasado', 'el verano pasado'],
    aile: ['pasar', 'el pasado'],
    hata: 'Sıfat isimden SONRA gelir: "la semana pasada". Ayrıca edat almaz: "en la semana pasada" YANLIŞTIR.',
    hatirlatma: 'Bu ifade bitmiş bir dönemi gösterir; indefinido ister.',
    uretim: { yonerge: '"Geçen hafta çok çalıştım." cümlesini yaz.', kabul: ['La semana pasada estudié mucho', 'Estudié mucho la semana pasada'] },
  },
  {
    id: 'es-hace-dos-anos',
    dil: 'es',
    kelime: 'hace dos años',
    tur: 'zaman ifadesi',
    seviye: 'A2',
    ispanyolcaTanim: 'Dos años antes de ahora.',
    turkceDestek: 'iki yıl önce',
    ipa: '/ˈa.θe dos ˈa.ɲos/',
    heceler: 'ha-ce dos a-ños',
    ornekler: [
      { es: 'Hace dos años nos mudamos a esta ciudad.', tr: 'İki yıl önce bu şehre taşındık.' },
      { es: 'Me llamó hace diez minutos.', tr: 'Beni on dakika önce aradı.' },
    ],
    esdizim: ['hace mucho tiempo', 'hace tres días', 'hace un mes'],
    aile: ['hacer'],
    hata: 'Türkçede "önce" sona gelir; İspanyolcada "hace" BAŞA gelir. "Dos años hace" YANLIŞTIR.',
    hatirlatma: 'Aynı kelime "yapmak" fiilidir; burada zaman ifadesi kurar.',
    uretim: { yonerge: '"Üç gün önce hastaydım." cümlesini yaz.', kabul: ['Hace tres días estaba enfermo', 'Hace tres días estuve enfermo'] },
  },
  {
    id: 'es-luego',
    dil: 'es',
    kelime: 'luego',
    tur: 'zarf',
    seviye: 'A2',
    ispanyolcaTanim: 'Después de eso, como paso siguiente.',
    turkceDestek: 'sonra',
    ipa: '/ˈlwe.ɣo/',
    heceler: 'lue-go',
    ornekler: [
      { es: 'Primero desayunamos y luego salimos.', tr: 'Önce kahvaltı ettik, sonra çıktık.' },
      { es: 'Luego empezó a llover.', tr: 'Sonra yağmur başladı.' },
    ],
    esdizim: ['primero … luego', 'y luego', 'hasta luego'],
    aile: [],
    hata: '"Hasta luego" vedalaşmadır ("sonra görüşürüz"); tek başına "luego" sıralama yapar.',
    hatirlatma: 'Anlatı iskeleti: primero → luego → después → por fin.',
    uretim: { yonerge: '"Önce ders çalıştım, sonra çıktım." cümlesini yaz.', kabul: ['Primero estudié y luego salí', 'Primero estudié, luego salí'] },
  },
  {
    id: 'es-despues',
    dil: 'es',
    kelime: 'después',
    tur: 'zarf',
    seviye: 'A2',
    ispanyolcaTanim: 'Más tarde, a continuación.',
    turkceDestek: 'daha sonra, ardından',
    ipa: '/desˈpwes/',
    heceler: 'des-pués (vurgu son hecede)',
    ornekler: [
      { es: 'Después fuimos al parque.', tr: 'Ardından parka gittik.' },
      { es: 'Después de comer, dormimos un poco.', tr: 'Yemekten sonra biraz uyuduk.' },
    ],
    esdizim: ['después de', 'poco después', 'justo después'],
    aile: [],
    hata: 'Bir eylemden sonra derken "después de + mastar" kalıbı kullanılır: "después de comer".',
    hatirlatma: 'Karşıtı "antes" = önce; o da "antes de + mastar" alır.',
    uretim: { yonerge: '"Yemekten sonra biraz uyuduk." cümlesini yaz.', kabul: ['Después de comer dormimos un poco'] },
  },
  {
    id: 'es-por-fin',
    dil: 'es',
    kelime: 'por fin',
    tur: 'kalıp',
    seviye: 'A2',
    ispanyolcaTanim: 'Al final, después de esperar mucho.',
    turkceDestek: 'sonunda, nihayet',
    ipa: '/poɾ fin/',
    heceler: 'por fin',
    ornekler: [
      { es: 'Por fin encontramos la dirección.', tr: 'Sonunda adresi bulduk.' },
      { es: 'El autobús llegó por fin a las nueve.', tr: 'Otobüs sonunda dokuzda geldi.' },
    ],
    esdizim: ['por fin llegar', 'y por fin', 'finalmente'],
    aile: ['el fin', 'finalmente'],
    hata: '"Por fin" beklemenin bitmesindeki rahatlamayı, "finalmente" ise sıralamanın son adımını anlatır.',
    hatirlatma: 'Kompozisyonda kapanış cümlesini açar.',
    uretim: { yonerge: '"Sonunda otobüsü bulduk." cümlesini yaz.', kabul: ['Por fin encontramos el autobús'] },
  },
  {
    id: 'es-de-repente',
    dil: 'es',
    kelime: 'de repente',
    tur: 'kalıp',
    seviye: 'A2',
    ispanyolcaTanim: 'Muy rápido y sin aviso.',
    turkceDestek: 'aniden, birdenbire',
    ipa: '/de reˈpen.te/',
    heceler: 'de re-pen-te',
    ornekler: [
      { es: 'De repente empezó a llover.', tr: 'Birdenbire yağmur başladı.' },
      { es: 'El coche se paró de repente.', tr: 'Araba aniden durdu.' },
    ],
    esdizim: ['de pronto', 'y de repente'],
    aile: ['repentino'],
    hata: 'Anlatının dönüm noktasını işaretler ve daima indefinido ile kullanılır; imperfecto ile gelmez.',
    hatirlatma: '"De pronto" ile eşanlamlıdır.',
    uretim: { yonerge: '"Birdenbire yağmur başladı." cümlesini yaz.', kabul: ['De repente empezó a llover', 'De pronto empezó a llover'] },
  },
  {
    id: 'es-suceder',
    dil: 'es',
    kelime: 'suceder',
    tur: 'fiil',
    seviye: 'A2',
    ispanyolcaTanim: 'Ocurrir, tener lugar.',
    turkceDestek: 'olmak, meydana gelmek',
    ipa: '/su.θeˈðeɾ/',
    heceler: 'su-ce-der',
    ornekler: [
      { es: '¿Qué sucedió ayer?', tr: 'Dün ne oldu?' },
      { es: 'El accidente sucedió cerca de la escuela.', tr: 'Kaza okulun yakınında oldu.' },
    ],
    esdizim: ['qué sucedió', 'no sucedió nada'],
    aile: ['el suceso'],
    hata: 'Günlük konuşmada daha çok "pasar" kullanılır: "¿Qué pasó?" Aynı anlamdadır ama daha yaygındır.',
    hatirlatma: 'Üçüncü tekil ve çoğulla kullanılır; birinci kişiyle kurulmaz.',
    uretim: { yonerge: '"Dün ne oldu?" sorusunu yaz.', kabul: ['Qué sucedió ayer', 'Qué pasó ayer'] },
  },
  {
    id: 'es-acordarse',
    dil: 'es',
    kelime: 'acordarse de',
    tur: 'fiil',
    seviye: 'A2',
    ispanyolcaTanim: 'Tener algo en la memoria.',
    turkceDestek: 'hatırlamak',
    ipa: '/a.koɾˈðaɾ.se/',
    heceler: 'a-cor-dar-se',
    ornekler: [
      { es: 'Me acuerdo muy bien de ese día.', tr: 'O günü çok iyi hatırlıyorum.' },
      { es: '¿Te acuerdas de nuestro viaje?', tr: 'Yolculuğumuzu hatırlıyor musun?' },
    ],
    esdizim: ['acordarse de algo', 'si mal no me acuerdo'],
    aile: ['el acuerdo', 'recordar'],
    hata: 'Dönüşlü zamir ve "de" edatı birlikte gerekir: "me acuerdo DE ese día". "Recordar" ise edat almaz: "recuerdo ese día".',
    hatirlatma: 'Çekimi düzensizdir: me acuerdo, te acuerdas, se acuerda.',
    uretim: { yonerge: '"O günü çok iyi hatırlıyorum." cümlesini yaz.', kabul: ['Me acuerdo muy bien de ese día', 'Recuerdo muy bien ese día'] },
  },
  {
    id: 'es-viaje',
    dil: 'es',
    kelime: 'viaje',
    artikel: 'el',
    cins: 'eril',
    cogul: 'los viajes',
    tur: 'isim',
    seviye: 'A2',
    ispanyolcaTanim: 'La acción de ir de un lugar a otro.',
    turkceDestek: 'yolculuk, seyahat',
    ipa: '/ˈbja.xe/',
    heceler: 'via-je',
    ornekler: [
      { es: 'El viaje duró cuatro horas.', tr: 'Yolculuk dört saat sürdü.' },
      { es: 'Hicimos un viaje muy largo en autobús.', tr: 'Otobüsle çok uzun bir yolculuk yaptık.' },
    ],
    esdizim: ['hacer un viaje', 'buen viaje', 'un viaje escolar'],
    aile: ['viajar', 'el viajero'],
    hata: 'Yolculuk "yapılır": "hacer un viaje". "Tener un viaje" YANLIŞTIR.',
    hatirlatma: 'Kısa gezi "la excursión", günlük gidiş geliş "el trayecto"tur.',
    uretim: { yonerge: '"Yolculuk üç saat sürdü." cümlesini yaz.', kabul: ['El viaje duró tres horas'] },
  },
  {
    id: 'es-recuerdo',
    dil: 'es',
    kelime: 'recuerdo',
    artikel: 'el',
    cins: 'eril',
    cogul: 'los recuerdos',
    tur: 'isim',
    seviye: 'A2',
    ispanyolcaTanim: 'Lo que queda en la memoria de un momento pasado.',
    turkceDestek: 'anı, hatıra',
    ipa: '/reˈkweɾ.ðo/',
    heceler: 're-cuer-do',
    ornekler: [
      { es: 'Tengo un buen recuerdo de aquel verano.', tr: 'O yaza dair güzel bir anım var.' },
      { es: 'Son mis recuerdos de la infancia.', tr: 'Bunlar çocukluk anılarım.' },
    ],
    esdizim: ['un buen recuerdo', 'recuerdos de la infancia', 'guardar un recuerdo'],
    aile: ['recordar', 'acordarse'],
    hata: 'Aynı kelime "hediyelik eşya" anlamına da gelir; bağlam ayırır.',
    hatirlatma: 'Anı yazısının başlığı için en uygun kelimedir: "Un recuerdo de infancia".',
    uretim: { yonerge: '"Bunlar çocukluk anılarım." cümlesini yaz.', kabul: ['Son mis recuerdos de la infancia'] },
  },
  {
    id: 'es-emocionante',
    dil: 'es',
    kelime: 'emocionante',
    tur: 'sıfat',
    seviye: 'A2',
    ispanyolcaTanim: 'Que produce emoción y ganas de seguir.',
    turkceDestek: 'heyecan verici',
    ipa: '/e.mo.θjoˈnan.te/',
    heceler: 'e-mo-cio-nan-te',
    ornekler: [
      { es: 'Fue un partido emocionante.', tr: 'Heyecan verici bir maçtı.' },
      { es: 'El viaje fue realmente emocionante.', tr: 'Yolculuk gerçekten heyecan vericiydi.' },
    ],
    esdizim: ['una historia emocionante', 'resultar emocionante'],
    aile: ['la emoción', 'emocionarse'],
    hata: 'Kişi için "emocionado" kullanılır: "estoy emocionado" = heyecanlıyım. Sıfat ile ortacı karıştırma.',
    hatirlatma: 'Karşıtı "aburrido" = sıkıcı.',
    uretim: { yonerge: '"Heyecan verici bir maçtı." cümlesini yaz.', kabul: ['Fue un partido emocionante'] },
  },
  {
    id: 'es-horrible',
    dil: 'es',
    kelime: 'horrible',
    tur: 'sıfat',
    seviye: 'A2',
    ispanyolcaTanim: 'Muy malo o desagradable.',
    turkceDestek: 'berbat, korkunç',
    ipa: '/oˈri.βle/',
    heceler: 'ho-rri-ble (baştaki h okunmaz)',
    ornekler: [
      { es: 'El tiempo fue horrible toda la semana.', tr: 'Hava bütün hafta berbattı.' },
      { es: 'Pasé una noche horrible.', tr: 'Berbat bir gece geçirdim.' },
    ],
    esdizim: ['un tiempo horrible', 'una idea horrible'],
    aile: ['el horror'],
    hata: 'Eril ve dişilde aynıdır: "-e" ile biten sıfatlar cinse göre değişmez.',
    hatirlatma: 'Anlatıda olumsuz dönüm noktasını işaretler.',
    uretim: { yonerge: '"Hava berbattı." cümlesini yaz.', kabul: ['El tiempo fue horrible', 'El tiempo era horrible'] },
  },
]

export default KELIMELER
